### ISSUE TITLE
Uusia automaattitunnuksia Kyytiin

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha#1001]
### Tukipyyntö

Lähetin tukipostiin turvasähköpostilla tarkemmat tiedot.

**Comment by johannaraisa** [comment]
Lisätty, pitäisi olla toiminnassa huomenna.

**Comment by VaisanRo** [comment]
Kiitos! Mistä saankaan automaatin toimittajalle toimitettavan SIP2-palvelimen osoitteen ja portin numeron? 😃

**Comment by AnneliO** [comment]
> Kiitos! Mistä saankaan automaatin toimittajalle toimitettavan SIP2-palvelimen osoitteen ja portin numeron? 😃

Vastasin sulle sähköpostissa, mutta viesti näköjään jäi miettimään, että haluaisiko lähteä vai ei. Ehkä se sieltä kohta lähtee. :)

**Comment by VaisanRo** [comment]
Tämä unohtunut vahingossa auki. Kiitos avusta! Suljen nyt tiketin.
