### ISSUE TITLE
Viestitaulun lukitus kaataa Kohan

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha#1002]
### Mikä vikana?

Viestitaulu lukitaan kun aineistoa lainataan, se ja viestijonon käsittely yhdessä kaatavat Kohan.

**Comment by johannaraisa** [comment]
En kyllä tiedä pystyykä tätä testaamaan muualla kuin tuotannossa, testeillä ei liiku niin paljoa dataa kerralla.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 15.1.2024: Muutetaan samalla viestien lähetyksen ajastus takaisin 15 minuutin välein.

**Comment by johannaraisa** [comment]
Taululukkoja ei ainakaan ole enää näkynyt, suljen tiketin.
