### ISSUE TITLE
Välimerkkiongelma Z39.50/SRU-haussa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1006]
### Mikä vikana?

Kuvailija tekee Vaarassa tekijänimimuutosten takia Z39.50/SRU-hakuja Melindasta. Kun tietuetta lähtee hakemaan Melindasta Vaarassa olevan nimeketietueen Muokkaa -> Korvaa tietue Z39.50/SRU-kyselyn kautta, nimeke- ja tekijärivien loppuun tulee välimerkit, jotka täytyy poistaa ennen haun tekemistä. TäTissä välimerkkien poistoa ei tarvitse tehdä, joten kuvailija pyytää samanlaista toimintoa myös Vaaraan. 
"Testasin jättämällä tekijäkenttään pilkun, mutta poistin nimekeriviltä /-merkin ja haku toimi, mutta merkin kanssa ei tule hakutulosta."
![2023kuvat 260](https://github.com/KohaSuomi/Koha/assets/73887264/f77565de-a580-4ac0-917f-bd494dc49e9b)

**Comment by AnttHeik** [comment]
Sama ongelma on myös OUTIssa.

**Comment by annavii** [comment]
Sama ongelma myös Vaskissa.

**Comment by mauriaittaniemi** [comment]
Lapissa myös... eli mieluusti sama muutos myös meille.

**Comment by paxed** [comment]
Tämä on tehty liitännäisenä, nimi on "IntranetUserJS: Trim Z39.50 search terms", ja oletuksena on kaikilla päällä.

**Comment by pknuuti** [comment]
Voiko tämän jo sulkea? Vaarassa toimii, mutta onko kaikilla muillakin käytössä?

**Comment by Hanna-Lumme** [comment]
Lumpeissa puuttuu myös.

**Comment by mauriaittaniemi** [comment]
Lapissakin puuttuu. Välimerkit tulevat edelleen.

**Comment by Kati-Helle** [comment]
Puuttuu Hellestä, välimerkit tulevat edelleen hakuehtoon mukaan.

**Comment by pirliis** [comment]
OUTIsta liitännäinen puuttuu myös.

**Comment by ElinaUotila** [comment]
Kirkesistä ei löydy myöskään liitännäistä.

**Comment by LeenaKinnunen** [comment]
Lapistakin liitännäinen puuttuu.

**Comment by MikkoLiimatainen** [comment]
Vaskistakin liitännäinen puuttuu

**Comment by paxed** [comment]
Tämän liitännäisen pitäisi nyt olla kaikilla.

**Comment by mauriaittaniemi** [comment]
Huomenta. Näyttäisi toimivan Lapin Kohassa myös.
-Mauri

ti 21. toukok. 2024 klo 8.37 Kati-Helle ***@***.***)
kirjoitti:

**Comment by pirliis** [comment]
Näyttäisi toimivan OUTIssa myös.

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
