### ISSUE TITLE
OUTI: Lähetystä odottavan Finvoice-laskun poisto asiakkaalta

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1008]
### Tukipyyntö

Oulun laskuttaja oli laskutustyökalussa vahingossa painanut yhden asiakkaan kohdalla "luo finvoice" -painiketta, vaikka laskun ei pitäisi vielä lähteä. Joten laskun lähetys pitäisi perua/poistaa asiakkaalta borrowernumber=113265.

**Comment by lmstrand** [comment]
Asiakkaalta poistettu tänään muodostunut finvoice-viesti message_queue -taulusta:
```
MariaDB [outiprod]> delete from message_queue where message_id = 12049148;
Query OK, 1 row affected (0.002 sec)
```

**Comment by pirliis** [comment]
Kiitos! Suljen tiketin.
