### ISSUE TITLE
Hyllyvarausraportista katosi julkaisuvuosi

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1009]
### Mikä vikana?

Ilmeisesti publicationyear/copyrightdate-mäppäysmuutos aiheutti sen, että nyt ei näy hyllyvarauslistalla Nimeke-sarakkeessa nimekkeen julkaisuvuotta. Sitä kaipaillaan takaisin.

**Comment by lmstrand** [comment]
Korjattu testeille. Ainakin Vaarassa pyörii hyllyvarauslistan generointi.

**Comment by AnneliO** [comment]
> Korjattu testeille. Ainakin Vaarassa pyörii hyllyvarauslistan generointi.

Laitatko Lari pyörimään generoinnin ainakin muutamassa muussakin testissä, niin saadaan useamman kimpan testaukset. :)

**Comment by pknuuti** [comment]
Vuosiluku näkyy taas! Kiitos.

**Comment by lmstrand** [comment]
Vaski- Helle- ja OUTI-testillä pyörii myös.

**Comment by ajrajala** [comment]
Vaski-testillä testattu, tietueen tallennuksen jälkeen julkaisuvuosi tuli hyllyvarausraportille näkyville kuten pitikin.
