### ISSUE TITLE
Käännöstoive: asiakastakaajan lisäys ja select-nappi

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1014]
### Tukipyyntö

Asiakkaalle takaajaa/huoltajaa lisätessä klikataan Lisää takaaja. Tästä avautuu ponnahdusikkuna, jossa voi etsiä takaajaksi lisättävän asiakkaan. Tuloksena saatavien asiakastietojen perässä oleva valintanappi on englanniksi (Select). Saako muutettua suomeksi?

Jos on mitenkään mahdollista, voisiko valintanapin siirtää asiakastietojen eteen ennen Kortti-saraketta, koska nyt se jää ponnahdusikkunassa oikealle ja näytön resoluutiosta riippuen joskus piiloon (vaatii oikealle skrollausta). Voin tehdä tästä uuden tiketin, jos on toteutettavissa tai nähdään lainkaan tarpeelliseksi? 

Molemmista asioista tullut palaute asiakaspalvelusta.

**Comment by AnneliO** [comment]
Mie luulen, että nyt jokin Koha-Suomi-muutos kadottaa käännöksen tuosta Select-napista, koska outi-nextillä (jossa ei ole vielä juurikaan muutoksia) nappi on kääntynyt ihan oikein. IntranetUserJS-asetuksen tyhjentäminen ei vaikuttanut asiaan, joten ongelma ei johdu ainakaan niistä.

Hakuikkunalle voisi tehdä periaatteessa saman tempun kuin mitä [Z39.50-hakuikkunalle tehdään JS-rimpsulla](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#z3950-hakuikkuna-suuremmaksi) eli ikkunaa muutetaan isommaksi, jolloin tiedot mahtuvat paremmin.

Sain periaatteessa toimivan version tehtyä tuon pohjalta, mutta joku paremmin JavaScriptiä tunteva voisi varmistaa rimpsun vielä:

```
/// ALKU ///
/* Muuta asiakashakuikkunan koko suuremmaksi. Ikkunan koko on turhan pieni hakutuloksille. */
//Members - search patrons pop-up
 //BEGIN Resize Patron search pop-up
  if (document.location.href.indexOf('search.pl')>-1) window.resizeTo((screen.width * 0.55), (screen.height * 0.9)), window.moveTo(0, 0);
  $(window).on('load resize', function(){
   $('#common_patron_search.common').height($(this).height() * 0.75);
   $('#common_patron_search.common').css('overflow-y', 'scroll');
  });
//END

/// LOPPU ///
```

**Comment by AnneliO** [comment]
Nyt kun tutkin tarkemmin, niin version 22.xx käännöksissä ei itse asiassa ole käännöstä tuolle Select-sanalle. Tai on, mutta sitä ei ole kytketty tuohon asiakashakuun. Versiossa 23.xx käännös on kytketty asiakashakuun, joten sen kääntyy oikein. Eli tuo ongelma korjaantuu versionvaihdossa. En käyttäisi siihen nyt tällä hetkellä enempää aikaa. :)

**Comment by atarnus** [comment]
Katselin tuon taulukon muodostumista, niin hoksasin, että siellähän on vähän hassusti kirjastotieto kahteen kertaan:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/c513f646-ea82-4689-88ac-a8c586fae23e)

Tuon pop-up-ikkunan kun avaa, niin sinne tulevat sarakkeet näkyivät muodostuneen URL:issa:
cgi-bin/koha/members/search.pl?columns=cardnumber,name,category,branch,dateofbirth,address-library,action

members.js:stä tämä löytyy, ja vaihtaisin näin: actionin alkuun ja address-libraryn tilalle pelkkä address:
```
$('body').on('click', '#guarantor_search', function(e) {
    e.preventDefault();
    var newin = window.open('/cgi-bin/koha/members/search.pl?columns=action,cardnumber,name,category,branch,dateofbirth,address','popup','width=1024,height=768,resizable=no,toolbar=false,scrollbars=yes,top'>
});
```

Ja lopputulos näyttäisi tältä:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/7979ef21-a173-4282-94f7-09fde4ea8d6a)

Tuohon ikkunan kokoon ei varmaan tarvi puuttua jos se select nappula tulee alkuun?

**Comment by atarnus** [comment]
Sarakkeiden leveyteen vaikuttaa tosiaan mahdollisen sisällön leveys: nimi-, asiakstyyppi- ja kirjasto-kentät eivät katkaise sisältöä, joten leveys tulee vaihtelemaan paljon.

Tarkistin myös, niin nextillä näyttää kääntyvän myös nuo hakukentät.
![image](https://github.com/KohaSuomi/Koha/assets/63994411/a0f5d43f-77bc-415f-a86f-e2fff7194ebf)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 22.1.2024: Tehdään yhteisön Bugzillaan kaksi tikettiä:

* Valinta-napin siirrosta rivin alkuun ja tarjotaan sinne korjaus. Ei tuoda itselle väliaikaisesti ennen kuin nähdään, päätyykö muutos yhteisöön.
* Muutos, että osoite-sarakkeeseessa ei turhaan näytetä toiseen kertaan kirjasto-tietoa.

**Comment by AnneliO** [comment]
@IrinaHalminen teetkö Bugzillaan tiketin Valinta-napin siirrosta rivin alkuun? :)

**Comment by IrinaHalminen** [comment]
Kiitos täggäyksestä, jäinkin pohtimaan, kenen työksi tiketti tuli. Nyt laitettu pienoisella viiveellä: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36558

**Comment by atarnus** [comment]
Tämän saisi muuten kyllä ihan näppärästi JS-rimpsuunkin, jos halutaan.

```
$(document).on('click', '#guarantor_search', function(e) {
    e.preventDefault();
    var newin = window.open('/cgi-bin/koha/members/search.pl?columns=action,cardnumber,name,category,branch,dateofbirth,address','popup','width=1024,height=768,resizable=no,toolbar=false,scrollbars=yes,top');
});
```

Tuo ajaa yli sen alkuperäisen funktion.

**Comment by atarnus** [comment]
Yhteisössä on nyt kirjoitettu tuo popup-ikkunan avautuminen bootstrap-moduuliin, niin ei fiksaannu enää tuolla koodinpätkällä. Ja koska minulla ei ole toimivaa yhteisöversiota, niin on aika tyhjää koittaa rukata siihen mitään pätsiä. Kävin sandboxilla katsomassa, niin taulu on edelleen samanlainen moduulin sisällä, mutta pääkäyttäjien lienee tarpeen testata meneekö se valinta-nappi piiloon eri tilanteissa, ja halutaanko se ensimmäiseen sarakkeeseen.

**Comment by sksandel** [comment]
Testeillä näyttäisi toimivan nyt kuten speksattu. Valitse-nappi kätevästi ensimmäisessä sarakkeessa ja ylimääräinen kirjastotieto poissa. En keksinyt missä tilanteessa valinta-napin pitäisi "mennä piiloon". Lisää takaaja-toiminto oli näkyvissä vain niillä asiakastyypeillä, joille takaaja kuuluu lisätä.
![image](https://github.com/KohaSuomi/Koha/assets/99008412/5f130c00-0203-45d6-b76f-25f9426e0d02)

**Comment by CodoDerDritte** [comment]
Yhteisöversion muutoksista johtuen korjaus ei tule olemaan kestävä. Homma on samalla tapaa rikki taas seuraavan versiopäivityksen jälkeen nyt tehdystä korjauksesta huolimatta. Mikäli korjaus halutaan, voitte lisätä Kassun laittaman JavaScript-rimpsun Kohaan pitäen mielessä korjauksen tilapäisyyden. Merkitsen tämän tiketin 'Odottaa' tilaan ja tutkitaan tilanne uudestaan seuraavan versiopäivityksen jälkeen.

**Comment by johannaraisa** [comment]
Koha-Suomen kehittäjien viikkopalaveri 3.6.2024: Tehdään tästä js-liitännäinen.

**Comment by lmstrand** [comment]
Viety testattavaksi plugin IntranetUserJS: Add guarantor select view fixes.

**Comment by sksandel** [comment]
Vaskin testeillä testattu. Toimii. Samat havainnot kuin aiemmassa toteutuksessa. 

Piiloon tuo nappi ei mene, vaikka hakutuloksessa olisi asiakas, joka ei voi olla takaaja (esim automaatti). Mutta ei se aikaisemminkaan ole mennyt.

**Comment by Kati-Helle** [comment]
Helle-testissä Lisää takaaja -asiakashaun hakutuloksessa
- Valinta-painike ensimmäisenä
- Osoite-sarakkeessa ei enää toisteta tarpeettomasti kirjaston nimeä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d75ebab2-a3b0-4b4c-b8a7-dde0051526ac)

**Comment by IrinaHalminen** [comment]
Vaarassa testattu ja samat havainnot kuin edellä. Jos hakee tyhjällä kentällä, virheilmoitus on englanniksi. Onko tarvetta muuttaa (aika vähän varmaan näin hakuja tapahtuu)?

![image](https://github.com/KohaSuomi/Koha/assets/99409279/642bb828-a475-48ca-9436-0d459581646a)

**Comment by AnneliO** [comment]
Hmm.. tuolle Please fill out this field -tekstille on kyllä käännös olemassa fi-FI-staff-prog.po-tiedostossa:

#. SCRIPT
#: koha-tmpl/intranet-tmpl/prog/en/includes/patron-search.inc:254
msgid "Please fill out this field."
msgstr "Kirjoita kenttään."

**Comment by AnneliO** [comment]
> Vaarassa testattu ja samat havainnot kuin edellä. Jos hakee tyhjällä kentällä, virheilmoitus on englanniksi. Onko tarvetta muuttaa (aika vähän varmaan näin hakuja tapahtuu)?
> 
> ![image](https://private-user-images.githubusercontent.com/99409279/339767994-642bb828-a475-48ca-9436-0d459581646a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTA1NzAsIm5iZiI6MTcxODYxMDI3MCwicGF0aCI6Ii85OTQwOTI3OS8zMzk3Njc5OTQtNjQyYmI4MjgtYTQ3NS00OGNhLTk0MzYtMGQ0NTk1ODE2NDZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA3NDQzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNmExNDdlZmYyY2FkNTkwZjRkNjM5ODU5ZTc5YWRjZGQ4ZTdmZmQ1YjMzZmZmOGIwOTQwZWVkNDIxODY1OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lR1GU2uaB6D9SjlDsFhh6WINFcV5xgJqkI7FrFGiSvI)

Teetkö Irina tästä erillisen tiketin, niin jatketaan sen selvittelyä siinä. :)

**Comment by IrinaHalminen** [comment]
Teen toisen tiketin em. asiasta. Tämä toimii tuotannossa, kiitos! :)

**Comment by AnneliO** [comment]
Pitäiskö tästä tehdä uusi tiketti 24.xx-tietovarantoon?

**Comment by AnneliO** [comment]
Onko tuolle itse asiassa enää tarvetta, koska asiakkaiden haku on siirtynyt modaaliin, joka on koko näytön levyinen?

![kuva](https://github.com/user-attachments/assets/0f108b2a-10cd-4bf5-a487-62a9e76445d6)

Itse en kokisi sitä enää tarpeelliseksi.

**Comment by lmstrand** [comment]
Totta. Yksi plugin vähemmän säädettävää. Kyllähän sen napin nyt hoksaa vaikka vikana onkin.

**Comment by AnneliO** [comment]
Testasin vielä pienentämällä selaimen ikkunaa ja katsoin, milloin Valitse-nappi menee piiloon. Ikkunan piti olla n. 922 pikseliä kapeampi, jolloin se rupesi menemään osittain piiloon. Pienehköllä läppärin näytöllä nappi näkyi kokonaisuudessaan.

**Comment by lmstrand** [comment]
Sovittiin kehittäjäpalaverissa, että tästä luovutaan versionvaihdossa.
