### ISSUE TITLE
KIRKES: MARC-kuvailuvirheraportit käyttöön

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha#1015]
### Tukipyyntö

Kirkesin tuotantokannan IntranetReportsHomeHTML -järjestelmäasetukseen on lisätty html-koodia MARC-kuvailuvirheraportteja varten:

<div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
<h2>MARC-virheraportit</h2>
<ul>
<li><a href="https://kirkes.koha-suomi.fi/marc_virheet.kirkesprod.html" target="_blank" rel="noopener">Virheelliset tietueet </a></li>
<li><a href="https://kirkes.koha-suomi.fi/marc_virhemaara.kirkesprod.txt" target="_blank" rel="noopener">Virhem&auml;&auml;r&auml;t</a></li>
</ul>
</div>

Tarvitsemme raportinrakennusajon käyttöön.

**Comment by paxed** [comment]
kirkes-prod:sta uupui yksi hakemisto, seurataan että virherapsat näkyvät huomenna kun ne ensi yönä tehdään.

**Comment by helasann** [comment]
Virheraportit eivät näy vieläkään, näyttää virheen 404.
