### ISSUE TITLE
Tunnusten (4 kpl) poistaminen SIP-palvelimelta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1016]
### Tukipyyntö

Seuraavat käytöstä poistuneet automaattitunnukset saisi poistaa SIP-palvelimelta:

TUVSLPA1040
TUVSLPA1045
LIPKLPA1001
LIPKLPA1002

**Comment by lmstrand** [comment]
Tunnukset poistettu.
