### ISSUE TITLE
Siilinjärvi: Myöhästymismaksujen kertymisessä (tai asetuksissa) outoutta

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#1018]
### Mikä vikana?

Siilissä myöhästymismaksuja kertyy pääsääntöisesti 0,20 €/vrk heti eräpäivästä ja maksukatto kaikista lainoista kerralla maksettavaksi on 20 €. Ei siis lainakohtainen maksu. Asiakkaan id=31652 kohdalla esiin tuli nyt outous, onkohan tämä bugi maksujen kertymisessä vai epäloogisuus meidän asetuksissa, johon en vain ole aiemmin törmännyt?

Maksusäännöissä on Kohan alusta lähtien ollut määriteltynä lainakohtainen maksimimyöhästymismaksu 20,00 €, maksukaton MaxFine 20,00 € olen lisännyt myöhemmin käyttöön, mutta nämä ovat tuntuneet toimivan yhdessäkin. Paitsi nyt kun verkkomaksut ovat tulleet käyttöön, tässäkö epäloogisuus realisoituu?

Asiakkaan myöhässä olevien lainojen maksukatto on täyttynyt 29.12.2023, hän on maksanut 20,00 € verkkomaksuna 10.1.2024 mutta ei ole uusinut myöhässä olevia lainojaan vaan on palauttanut ne 11.1.2024. Nollautuneet maksut ovat tuon vuorokauden aikana lähteneet kertymään uudelleen mutta ei 10.1.2024 alkaen vaan 29.12.2023 alkaen, eli 13 x 0,20 € = 2,60 € per laina.

Auttaako tässä lainakohtaisen maksimimyöhästymismaksun poistaminen maksusäännöistä vai kuinka lähtisin ongelmaa ratkomaan?

![kuva](https://github.com/KohaSuomi/Koha/assets/98806001/d413678c-a6dc-4773-b74c-82e43edf79a4)

**Comment by AnneliO** [comment]
Jos asiakas maksaa maksut, mutta ei uusi myöhässä olevia lainoja, niin niistä lähtee kertymään uudelleen myöhästymismaksut. Silloin myös maksimisumma ikäänkuin lähtee kertymään uudelleen. Tästä saattais olla jokin aiempi tikettikin, voisin koittaa etsiä sitä.

**Comment by ReettaSiili** [comment]
Ongelmasta keskusteltu matrixissa 17.1., ei toistaiseksi selkeää ratkaisua.

**Comment by janPasi** [comment]
Ei tule nyt ainakaan mieleen miten tuon voisi muuttaa. Koha maksujen laskenta toimii näin. Ajatuksena siinä on, että maksut voidaan laskea milloin tahansa, esimerkiksi vaikka kerran viikossa tai vasta palautustilanteessa, jolloin ne lätkäistään sitten asiakkaalle kerralla koko myöhässäoloajalta.
