### ISSUE TITLE
Joulukuun 2023 tilastoraportin uudelleenajo

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1019]
### Tukipyyntö

Olisiko mahdollista saada raportointityökalun joulukuun 2023 tilasto ajettua uusiksi?

Turussa otettiin joulukuussa käyttöön Puppe-saapumisvalvonta ja alkuvaiheessa sillä tehty saapumiskäsittely ei aluksi päivittänyt niteiden dateaccessioned-kenttään saapumispäivämäärää eli dateaccessioned-kenttään jäi vanhat tilauspäivämäärät. Dateaccessioned-päivät on niteille nyt korjattu, mutta koska niteitä oli ehditty käsitellä yllättävän paljon ja Turussa katsottiin joulukuun hankintaluvun heittävän selvästi normaalista, voisi tilaston sen takia ajella uusiksi.

**Comment by emta001** [comment]
Kävin laittamassa ajon päälle ensi yöksi, huomenna pitäs olla uudet tilastot käytettävissä.

**Comment by emta001** [comment]
> @emta001 Olin näköjään sokea enkä huomannut, että koko vuoden (2023) tilastot (id:t 38 ja 39) oli myös ajettu jo heti vuodenvaihteessa. Meneekö niiden uusiksi ajo samalla vaivalla?

Laitetaan menemään :+1:

**Comment by emta001** [comment]
Ajot näyttäisi menneen onnistuneesti läpi. Näyttääkö tilastot nyt paremmille @ajrajala ?

**Comment by ajrajala** [comment]
Kiitokset! Turun joulukuun hankintaluvut näyttävät kasvaneen kutakuinkin siinä mittakaavassa mitä pitikin. Noissa koko vuoden tilastoissa luvuissa ei hirveästi tapahtunut muutosta, osa hiukan laski ja osa nousi, mutta eiköhän nämä ole ok.
