### ISSUE TITLE
Kirkes: API-tunnukset Raportteri-rajapinnan käyttöön Järvenpään kaupungille

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1021]
### Tukipyyntö

Tarvitsemme API-tunnukset Raportteri-rajapinnan käyttöön Järvenpään kaupungin tiedolla johtamisen palvelulle. 

Tunnukset voi toimittaa Frendsin kehittäjälle: janne.hietanen@frends.com.

**Comment by lmstrand** [comment]
API-käyttäjätunnus luotu Kirkes-testille borrowernumber 101745 ja API-avain lähetetty sähköpostitse onetimesecretissä.

Huomasin, ettei raporttirajapinta-pluginia ollut asennettu Kirkes-testille, joten asensin sen. Nyt sitä voi konfiguroida plugin-asetuksista.

**Comment by ElinaUotila** [comment]
Testillä yhteydet pelaa ja kutsuttu testiraportti meni perille.

**Comment by ElinaUotila** [comment]
Nyt voisi toimittaa Janne Hietaselle API-käyttäjätunnuksen myös tuotannon puolelle.

**Comment by lmstrand** [comment]
Uusi API-tunnus luotu tuotantoon (borrowernumber 102780) ja sille määritetty api-avain lähetetty ontimesecretillä Jannelle.

**Comment by ElinaUotila** [comment]
Kiitos!
