### ISSUE TITLE
API-avain (Kellutin)

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1022]
### Tukipyyntö

Vaskin tuotantoon on lisätty API-tunnus kellutuksen hallintajärjestelmää varten: https://vaski.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=398140

Tunnukselle tarvitaan avain, joka pitäisi toimittaa Weaselille (voisi toimittaa aleksi.kokko@weaselsoftware.fi).

Tunnuksella ei vielä käyttöoikeuksia, lisättävä kun onetimesecretistä on tullut vahvistus.

**Comment by ajrajala** [comment]
Liittyy projektiin #925

**Comment by janPasi** [comment]
Avaimet toimitettu weaselille onetimesecretinä.

**Comment by ajrajala** [comment]
Kiitokset! Weasel kuittasi saaneensa avaimet, joten lisäsin tunnukselle samat käyttöoikeudet mitä testilläkin oli.
