### ISSUE TITLE
Asiakasmääreen HOLDID tallentaminen antaa virhe 500 -ilmoituksen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1027]
### Mikä vikana?

Yrittäessä tallentaa asiakasmääreen HOLDID asetuksia, tulee ainakin vaski-nextillä virhe 500 -ilmoitus. Virheilmoitus tulee vaikka olemassa oleviin valintoihin ei tekisi mitään muutoksia vaan yrittää ainoastaan tallentaa. Muiden asiakasmääreiden asetusten tallentaminen näyttäisi onnistuvan.

**Comment by emta001** [comment]
Yhteisön masterissa tää näyttäs toimivan.

**Comment by emta001** [comment]
Nonnih, eli jos kannassa on kaksi samaa HOLDID-arvoa, niin Koha ei anna tallentaa asiakasmäärettä olemaan uniikki. 

`The property 'unique_id' cannot be changed, some patron attributes are using it that way.`

Eli se tekee juurikin niin kuin virheilmoituksessa sanotaan, ei voi olla uniikkiarvo koska joidenkin asiakkaiden kohdalla määrettä ei ole käytetty uniikkina :smile: Tämän sais korjattua ajamalla kaikille asiakkaille uniikin varaustunnisteen NULLin tilalle. Sen vois tehä testeille ja nexteille, mutta tuotannoissa on varmaan käytävä asiakkaat läpi raportin kanssa ja säädettävä käsin.

**Comment by AnneliO** [comment]
Sitä mien ymmärrä, miten siellä voi olla tuplia, kun tuo HOLDID pitäis olla ollut alusta saakka määritetty uniikiksi.

**Comment by emta001** [comment]
> Sitä mien ymmärrä, miten siellä voi olla tuplia, kun tuo HOLDID pitäis olla ollut alusta saakka määritetty uniikiksi.

Ei mitään käsitystä. Teen rapsan jolla nuo saa kiinni, niin sieltä voi vakoilla millon noita on tehty. Vaskista osaan sen verran sanoa, että siellä on 176 asiakasta joilla HOLDID on NULL.

**Comment by emta001** [comment]
Ainakin tällä saa kiinni määreet, jotka on kannassa tuplana:

`SELECT code, attribute, COUNT(*) occurences FROM borrower_attributes WHERE code = "HOLDID" GROUP BY code, attribute HAVING COUNT(*) > 1;`

Yritän vielä saada aikaan semmosen rapsan, jolla saa nuo käyttäjät kiinni.

**Comment by emta001** [comment]
Näyttäisi tosiaan sille, että ainakin Vaskissa nää tupla-varaustunnukset koskee vain VIRKAILIJA käyttäjiä ja arvona on NULL. NULL pitäisi kyllä käsitellä Kohan päässäkin niin, että sitä voi esiintyä kannassa useamman kerran, joten kyseessä on bugi. Etsitään yhteisöstä tiketti tai tehdään semmoinen jos ei löydy.

**Comment by ajrajala** [comment]
Käy järkeen, ovat siis kaikki virkailijatunnuksia jotka on luotu massana käyttöönoton yhteydessä ja joita ei ole kertaakaan sen jälkeen Kohan kautta muokattu.

**Comment by emta001** [comment]
Tutkin tätä lisää ja tuskin tästä kannattaa tehdä yhteisöön tikettiä/korjausta. Asiakasmääretauluun (borrower_attributes) ei pitäisi muodostua rivejä, joissa attribute-sarakkeen arvo on NULL. Jos määre ei ole pakollinen eikä siihen tallenneta mitään, ei myöskään tauluun tallenneta mitään. Tässä virhe on siis enemmin siinä, että meidän datassa on virhe, ei Kohassa.

Järkevintä olisi varmaan käydä ajamassa nämä NULL arvoiset HOLDID:t pois kannasta. Ne voi generoida sitten käyttäjille uudestaan, jos/kun käyttäjän tietoja käydään muokkaamassa.

**Comment by emta001** [comment]
NULL arvoiset HOLDID:t on ajettu kaikista kannoista pois ja määreen tallennuksen tulisi onnistua nyt kuten pitääkin.

**Comment by MikkoLiimatainen** [comment]
HOLDID-määreen muuttaminen onnistui nyt kaikissa ympäristöissä. Tämä ongelma ei tainnut vaivata muita kuin Vaskia, joten suljen tiketin.
