### ISSUE TITLE
OUTI: Vanhojen myöhästymismaksujen date-kentän korjaus

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1030]
### Tukipyyntö

OUTIssa myöhästymismaksujen päiväkohtaiset maksut nousivat 5.1.2021, jolloin kaikkien lainassa olleiden niteiden maksurivit myös päivittyivät. Koska date-kenttä päivittyi maksujen päivityksessä, maksut eivät tulleet 1.1.2024 maksujen vanhentamisajoon mukaan. 

Näiden maksujen päivämäärät pitää korjata lähemmäs alkuperäistä maksujen luontipäivämäärää. Tämän jälkeen maksut mitätöidään writeoffauksella ja maksujen note-kenttään tieto mitätöinnistä.

OUTIn tuotannossa on raportit:
- 705: Vanhat maksut, joille päivittynyt uusi luontipäivämäärä, raportti 1. Raportille tulee asiakkaiden borrowernumberit.
- 706: Vanhat maksut, joille päivittynyt uusi luontipäivämäärä, raportti 2. Raportille tulee asiakkaiden maksukohtaiset tiedot.

@lmstrand, tuleeko raporteille samat asiakkaat ja maksurivit, jotka sinä löydät tietokannasta?

Raportin 2 alkuun tulee myös muita kuin 5.1.2021 päivittyneitä vanhoja maksuja. Onneksi ei kovin paljon. Erikoista vain, että mikä on päivittänyt maksurivejä noina päivinä.

**Comment by lmstrand** [comment]
OUTIn tuotantoon ajettu:

MariaDB [outiprod]> update accountlines set date = ( SELECT STR_TO_DATE(CONCAT(LEFT(RIGHT(description, 16),10), ' 00:00:00'), '%d.%m.%Y %H:%i:%s') + INTERVAL 30 DAY ) WHERE debit_type_code IN ('OVERDUE') AND DATE(date) = '2021-01-05' AND amountoutstanding > 0;
Query OK, 2217 rows affected (8.928 sec)
Rows matched: 2217  Changed: 2217  Warnings: 0

**Comment by lmstrand** [comment]
Ajan vielä maksujen mitätöintiajon, nyt ainakin nuo 5.1.2021 päivittyneet rivit pääsevät mukaan mitätöintiin, joille tuo date-päivämäärä meni yli sen 5v.

**Comment by lmstrand** [comment]
Nyt ajettu ja pari maksuriviä/borrowernumberia vilkastuani näyttää ajo mennen kuten piti. 1321 noista 2217 maksurivistä, joille päivämäärä siirrettiin, mitätöityivät.

2024-01-24 15:28:24 1321 OVERDUE debit rows written off.
2024-01-24 15:28:24 6898.5 eur worth of OVERDUE type debits written off and marked expired in total.

**Comment by atarnus** [comment]
Koska sieltä löytyi muutamia maksurivejä, joissa oli vanha eräpäivä ja uudempi maksurivin päiväys, mutta kuitenkin jokin muu kuin tuo 5.1.2021, niin näillä raporteilla saa ne nyt kiinni:

```
 SELECT date(al.date) AS pvm, i.borrowernumber, i.itemnumber, i.issue_id, al.description, al.amount, al.amountoutstanding, al.debit_type_code, timestamp, interface
  FROM issues i
       INNER JOIN accountlines al USING(issue_id)
 WHERE al.debit_type_code = 'OVERDUE'
   AND al.amountoutstanding > 0
   AND date(al.date) > ADDDATE(date(i.date_due), INTERVAL 35 DAY)
 ORDER BY 2
```

```
 SELECT date(al.date) AS pvm, i.borrowernumber, i.itemnumber, i.issue_id, al.description, al.amount, al.amountoutstanding, al.debit_type_code, timestamp, interface
  FROM old_issues i
       INNER JOIN accountlines al USING(issue_id)
 WHERE al.debit_type_code = 'OVERDUE'
   AND al.amountoutstanding > 0
   AND date(al.date) > ADDDATE(date(i.date_due), INTERVAL 35 DAY)
 ORDER BY 2
```

Nämä etsii kaikki maksurivit, jotka on muodostuneet enemmän kuin 35 päivää eräpäivän jälkeen, järjestettynä asiakkaan mukaan.

**Comment by pirliis** [comment]
Tsekkailin eilen vanhennettuja maksuja OUTIn rapsalla 713 ja näyttäisi, että niille on päivittynyt taas uudet maksut. :(

**Comment by atarnus** [comment]
Tällä saa kiinni taas ne vanhat eräpäivät uudelleen muodostuneille maksuille:

```
SELECT i.date_due + INTERVAL 29 DAY + INTERVAL 1 SECOND AS pvm, al.*
  FROM accountlines al
       INNER JOIN issues i USING(issue_id)
 WHERE al.debit_type_code IN ('OVERDUE')
   AND DATE(al.date) = '2024-01-25'
   AND al.amountoutstanding > 0
   AND i.date_due < '2019-01-01'
```

Hakee siis näille uusimille turhaan syntyneille maksuriveille eräpäivän timestampin issues taulusta, ja laittaa maksun dateksi 30 päivää lisää.

**Comment by lmstrand** [comment]
Outiin ajettu uusiksi muodostuneille overdue-maksuille:

```
MariaDB [outiprod]> update accountlines set date = STR_TO_DATE(CONCAT(REGEXP_SUBSTR(description, '[0-9]{2}.[0-9]{2}.[0-9]{4}'), ' 00:00:00'), '%d.%m.%Y %H:%i:%s') + INTERVAL 30 DAY
    -> where accountlines_id in
    -> (
    -> select accountlines_id from accountlines where date(date) = '2024-01-25' and amountoutstanding >0 and debit_type_code = 'OVERDUE'
    -> and date(STR_TO_DATE(CONCAT(REGEXP_SUBSTR(description, '[0-9]{2}.[0-9]{2}.[0-9]{4}'), ' 00:00:00'), '%d.%m.%Y %H:%i:%s') + INTERVAL 30 DAY) < '2019-01-01'
    -> );
Query OK, 1220 rows affected (50.230 sec)
Rows matched: 1226  Changed: 1226  Warnings: 0
```

**Comment by lmstrand** [comment]
Ajettu myös uusiksi korjattu mitätöintiskripti. 1226 riviä mitätöityi klo. 15.30-15.32.

**Comment by atarnus** [comment]
Lisätty vanhentuneiden maksujen rapsaan (714) aikarajaus, että tämä toinen mitätöinti samoille maksuille jää huomioimatta.
`AND (al.date NOT BETWEEN '2024-01-29 15:30:00' AND '2024-01-29 15:31:30')`

**Comment by pirliis** [comment]
Vanhentuneiden maksujen uudelleen mitätöinti 29.1.2024 on onnistunut. Maksut eivät ole enää päivittyneet asiakkaille uudestaan.
