### ISSUE TITLE
Lumme: Virhe 500 asiakkaan Maksut-välilehdellä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1032]
### Mikä vikana?

Aloin käymään läpi asiakkaita, joiden vanhentuneet maksut olivat generoituneet ajon jälkeen uudelleen. Esiin nousi heti muutamia asiakkaita, joiden kohdalla ilmenee virhe 500, kun heidän Maksut-välilehden yrittää klikata auki. Muut välilehdet avautuvat normaalisti.

Maksut-välilehdessä virhe 500:
1499
1550
9733

Maksut-välilehden saa auki, mutta Tapahtumat-välilehti heittää virheen 500:
6385
8969

**Comment by emta001** [comment]
Johtuu siis siitä, että kyseiset lainat on tehty kirjastoissa joiden branchcodea ei enää ole Lumpeen kannassa. Esim. MLI_RA on korvautunut MLI_RAN:illa. Tein tästä rapsan jolla nämä saa kiinni ja tietopyynnön muille kimpoille tarkistaa omansa.

**Comment by emta001** [comment]
Tämä siis näkyy lokeissa tämmösenä virheilmotuksena:

`Template process failed: undef error - DBIC result _type  isn't of the _type Branch at /home/koha/Koha/koha-tmpl/intranet-tmpl/prog/fi-FI/modules/members/pay.tt line 150.`

**Comment by emta001** [comment]
Linkki [tietopyyntöön](https://github.com/KohaSuomi/Koha/discussions/1033#discussioncomment-8232269).

**Comment by Hanna-Lumme** [comment]
Kiitoksia korjauksesta!
