### ISSUE TITLE
Helle-Finna: tietueen niteiden saatavuustiedot eivät näy aina oikein

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1035]
### Tukipyyntö

Helle-Finnassa tietueen niteiden saatavuustiedot eivät näy aina oikein, kun tietueeseen kohdistuu varaus/varauksia.
Esimerkki
- tietueeseen kohdistuu yksi voimassa oleva varaus
- ja tietueella on useampi kuin yksi nide, joka voi täyttää varauksen
-> saatavuustiedoissa kaikki ko. niteet näkyvät virheeellisesti Varattu-tilaisina

Esimerkissä tietueeseen kohdistuu yksi varaus ja kaksi nidettä on vapaana (tämä tapaus on lähetetty aikoinaan Finna-toimistolle esimerkkinä)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/834a6ccd-f0a6-4446-b238-ac85e27d6a36)

Finna-toimistolta saatu tieto: "Näyttäisi siltä, että Koha raportoi molemmat niteet varatuiksi, eli Finnan puolella ei tässä tehdä mitään sen ihmeempää päättelyä."

Löytyisikö tähän ratkaisu Kohan puolelta?

Finna-toimistolle on kerrottu, että saatavuusnäkymä toimii oikein Koha-Suomen kirjastoista mm. OUTI-Finnassa.
Finna-toimistolta tieto: "Asetukset ovat Outi-kimpan kanssa yhteneväiset."

**Comment by ajrajala** [comment]
Matrixissa mietittiin, että Finnan saatavuustietojen priorisointijärjestys voisi vaikuttaa tähän. Vaskissa Finnan saatavuustietojen priorisointijärjestystä on viime vuoden puolella muutettu ja nykyinen järjestys on kuvattu [tänne](https://github.com/KohaSuomi/Finna-kehitysehdotukset/issues/2#issuecomment-1735484414). Tuon mukaan meilläkin "On Hold" yliajaisi kaikki erikoistilat ja saatavana-tilan, mutta testieni perusteella näin ei kuitenkaan ole:

Tietueeseen kohdistuu voimassa oleva varaus ja niteistä toinen saatavilla ja toinen tilattu -> molemmat näkyvät oikein:
![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/f7e509ac-4d0c-477e-a53a-1d148343f865)

Tietueella kaksi nidettä, toinen noudettavissa varausta varten ja toinen tilattu -> molemmat näkyvät oikein:
![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/71984e5c-09ce-4ffb-85ff-7bac40f6ec8e)

En hiffaa mitä tuo "On Hold" tuolla Finnan priorisointijärjestyksessä ylipäätään tekee. Mutta voisikohan tässä Hellen tapauksen tutkimisessa päästä silti mahdollisesti eteenpäin, jos Finna-toimistolta pyytäisi laittamaan priorisointiasetukset näkyville vaikka testinäkymään?

**Comment by ajrajala** [comment]
Susanna, joka priorisointien kanssa askarteli, kommentoi vielä että tuo "On Hold" -tila ei tosiaan meidän käsityksen mukaan vaikuta mihinkään eikä ole tietoa miksi. "On Hold" oli Kansalliskirjaston alkuperäisissä priorisoinneissa tuon niminen, mutta olisiko sitten niin ettei järjestelmä tunnista sitä tuolla nimellä tms eikä meillä siksi vaikuta mihinkään. Hellen priorisointiasetuksethan voi poiketa meistä hyvinkin, tulee mieleen että jos siellä varattu-status kulkee vaikka oikealla nimellä ja siksi vaikuttaa saatavuustilojen näyttämiseen. 🤔

**Comment by Kati-Helle** [comment]
Ere Maijala on maininnut tämän sähköpostikeskustelussa: Helle-kirjastoilla ei ole StatusRankings-asetuksia. Niillä on kuitenkin vaikutusta vain siinä tilanteessa, että niteellä on useita tiloja, esim. lainassa ja varattu.

**Comment by lmstrand** [comment]
Jos testillä tuon yhden ainoan varauksen tietueeseen keskeyttää, tilat näkyvät oikein jokaisella niteellä. Se varaus "varaa" koko tietueen niteiden tilan itselleen, vaikka se varaus ei saisi näkyä niteiden tiloissa ollenkaan. Voiko tähän olla jotakin järjestelmäasetusta Kohassa, joka raportoi Finnaan kaikkien niteiden tilaksi "Varattu" niiden todellisen tilan sijaan, jos tietueeseen on varaus? Kuulostaa kyllä aika kummalliselta. Onko Finnassa mahdollista priorisoida tuo varaus-tieto niin, että menee kaikkien tietueen nidetilojen yli, tai toisin sanoen voiko tietyn nidetilan jättää huomioimatta niteen tilatietoa haettaessa? Onko kyse juuri noista priorisoinneista? Laitetaan On Hold tai mikä tahansa joka liittyy varattuun aineistoon vikaksi, ja katsotaan miten käy?

**Comment by lmstrand** [comment]
Niin tällä testasin: https://helle.finna-pre.fi/kohatest/Record/helle_kohatest.1627962?sid=226483636
Biblionumber 1627962. Keskeytin varauksen / jatkoin ja varauksen keskeydyttyä näkyi niteiden tila ok.

![image](https://github.com/KohaSuomi/Koha/assets/18394834/2895568b-1fe1-4a44-9f68-6f4deb8470eb)

**Comment by lmstrand** [comment]
Kävin läpi järjestelmäasetuksia, joita Finna-plugin ymmärtää ja asetus AllowItemsOnHoldCheckoutSIP vaikutti noihin tiloihin. Kun asetus on "salli", niteet näkyvät oikein myös, kun tuo ainoa varaus ei ole keskeytettynä.

**Comment by lmstrand** [comment]
Myös laittamalla salli järjestelmäasetukseen AllowItemsOnHoldCheckoutSCO taitaa korjautua tuo nidetilojen näyttö.

**Comment by AnneliO** [comment]
Täähän oli mielenkiintoista, että Finna noudattaa SIPiin liittyviä asetuksia. :D 

AllowItemsOnHoldCheckoutSIP -asetus tuli muistaakseni jossain edellisistä versioista ja sen on varmaan suurin osa silloin vaihtanut Salli-vaihtoehdoksi, jotta asiakkaat pystyvät lainaamaan hyllyvarattuja niteitä automaateilla (erityisesti omatoimiaikaan). Muistaakseni silloin testattiin, että asetus ei kuitenkaan salli noudettavissa olevien varausten lainaamista muille kuin sen varaajalle.

**Comment by lmstrand** [comment]
Ok, no sittenhän sekin on ihan varteenotettava vaihtoehto pistää sallituksi ongelman korjaamiseksi.

**Comment by Kati-Helle** [comment]
Vaihdoin Helle-testillä asetuksen  AllowItemsOnHoldCheckoutSIP=Salli

Vaikuttaisi toimivalta ratkaisulta :) Hienoa!

Testaan tietueella, jolla on 2 varausta. Saatavana olevia niteitä on 8
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/eb9fa5b9-57b2-4090-b9f0-231b9f0ab0db)

**Comment by AnneliO** [comment]
@Kati-Helle Tämän tiketin saanee sulkea? :)

**Comment by Kati-Helle** [comment]
Joo, suljen.
