### ISSUE TITLE
Kyyti: Kouvolan kirjastoauton yhteysongelmat

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1037]
### Tukipyyntö

Kohan yhteysongelmat Kouvolan kirjastoautossa ovat jatkuneet jo pitkään. "Suojatun yhteyden muodostaminen epäonnistui"-virheilmoitus ei tule joka kerta, mutta välillä niin toistuvasti, että se häiritsee työn tekemistä. Ohessa kuvakaappaus virheilmoituksesta. Virhe esiintyy ainoastaan auton pöytätietokoneella, joka ottaa reitittimen ja modeemin kautta yhteyttä Kohaan. Millään muulla sivustolla vikaa ei esiinny eikä myöskään muilla verkoilla Kohaan yhteyttä ottaessa. Kaikki verkkolaitteet autossa on käynnistelty uudelleen eikä siitä ollut apua. 

Ongelma ei myöskään ole tietokoneissa, koska auton läppärin sim-kortin verkkoa käyttäessä ongelma poistuu. Kuitenkin jos läppärin liittää reitittimen/modeemin verkkoon ongelma taas ilmenee. Vaikuttaisi siltä, että Kohan päivitykset saattavat vaikuttaa ongelmaan, koska joidenkin päivitysten myötä ongelma on vähentynyt tai ollut hetken kokonaan ongelmaton ja palaa taas myöhemmin.

Kouvolan ict-asioita hallinnoiva KS-Tieto on käynyt autossa ja raportoinut: "KSTieto kävi paikanpäällä selvittämässä tilannetta kirjastoautonkuljettajien kanssa. Verkko kirjastoautossa toimii moitteetta. Ongelma on KOHA-kirjastojärjestelmässä, joten KSTiedolla ei ole asiassa tehtävää. Asiaa pitää selvittää KOHA-ohjelmiston toimittajan kanssa. Suljetaan työpyytö."

Onko Koha-Suomella ajatusta mistä tämä voisi johtua ja miten asian kanssa tulisi edetä?

### Jotain muuta?

![ERRORI](https://github.com/KohaSuomi/Koha/assets/99244794/f909c41f-5290-4e5e-8352-65dea8e8d2c7)

**Comment by janPasi** [comment]
Ongelma tässä on kyllä minusta tuon kuvauksen perusteella aivan selvästi ja 100% varmuudella auton verkkoyhteydessä, joten Kohan päässä tälle ei ole mitään tehtävissä. Koha toimii normaalisti muista yksiköistä ja toimii tuolta autostakin jos käytetään toista verkkoa.
