### ISSUE TITLE
OUTI: Tietue jäänyt roikkumaan OUTIn indeksiin?

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1038]
### Mikä vikana?

Lehden "Kodin Pellervo 2013" tietue löytyy tiedonhaulla, mutta kun tietueen klikkaa auki, tulee ilmoitus:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/e8857353-aae6-4715-981c-06c253f311cc)
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1937455&searchid=scs_1706187568370

Saatavuustiedoissa näyttää, että tietueessa olisi yksi nidekin:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/1d7c5d04-f7fb-494b-b703-b937f271f64b)

OUTIn nextillä tietuetta ei enää löytynyt.

**Comment by emta001** [comment]
Millaisessa tilanteessa tämä on siis syntynyt? Tehtiinkö tietueiden yhdistelyä, jos tehtiin, millä tavalla? Oliko kyseessä eräpoisto? Onko näiden yhteydessä ollut auki välilehtiä tjsp? Lumpeissa on ollut samaa ongelmaa (tiketti #992) ja ollaan yritetty saada kiinni siitä, missä tilanteissa tätä on tapahtunut.

**Comment by AnneliO** [comment]
Näyttäisi olleen niteen poisto eräajona kyseessä:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/3a5ff891-6e1c-4f14-b371-5401c58a4226)

Minusta on outoa, että tietueen indeksointi on mennyt jonoon ennen kuin niteen poisto on mennyt jonoon. Jos tietueen tilan indeksissä muuttava työ menee jonoon ennen kuin tietueesta on poistettu nide ja itse tietue, niin eihän se tieto koskaan päädy indeksiin.

**Comment by pirliis** [comment]
Kiitos! Suljen tiketin.
