### ISSUE TITLE
Viestiasetukset tyhjentyvät, jos asiakastietuetta ei voi tallentaa olemassa olevan varaustunnuksen takia

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1039]
### Mikä vikana?

Samankaltainen ongelma mitä aikaisemmin on tapahtunut huoltajan suhde-tiedolle (ks. versionvaihdon tiketti https://github.com/KohaSuomi/Koha-23x/issues/56)

### Kuinka toistaa ongelma/asia

1. Aloita lisäämään uutta asiakasta
2. Laita asiakkaalle jokin jo olemassa oleva varaustunnus
3. Täytä loputkin pakolliset tiedot ja sähköpostikenttä
4. Lisää viestiasetuksiin jokin sähköpostivalinta
5. Valitse Tallenna, huomaa että tallennus ei onnistu päällekkäisen varaustunnuksen takia ja viestiasetukset ovat tyhjentyneet

**Comment by AnneliO** [comment]
Tästä olikin jo tiketti olemassa eli #839.

**Comment by ajrajala** [comment]
Hyvä kun huomasitte, suljen tämän tuplatiketin.
