### ISSUE TITLE
Broomworksin sertifikaatin uusiminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1042]
### Tukipyyntö

Broomworksilla on vielä tarve päästä Kohaan Puppe-sovellukseen liittyen muutaman kuukauden ajan. Nykyinen sertifikaatti lienee vanhentunut, joten onnistuisiko sertin uusiminen vielä vaikka 31.8.2024 asti?

**Comment by janPasi** [comment]
Serti tehty ja toimitettu Vaski pääkäyttäjälle Matrixissa.
