### ISSUE TITLE
Helle: kuljetustilaisesta varatusta niteestä on lähtenyt asiakkaalle noutoilmoitus

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1043]
### Mikä vikana?

Hellessä asiakkaalle on muodostunut ja lähtenyt tekstiviestinoutoilmoitus kuljetustilassa olevasta varatusta niteestä.

Asiakas, borrowernumber=25955
Kuljetustilainen varattu nide, itemnumber=1772456
Varattu teos, biblionumer=1612324

Varauksen tietoja reserves-taulussa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ae519657-5f68-4766-b5e2-979e511fcc60)

Niteen viimeisimpien liikkeiden tiedot statistics-taulussa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c321f2c9-b0dd-4546-a18b-3e1e311a4c0e)

Asiakkaalle muodostunut ja lähetetty noutoilmoitus
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/79024e60-4a3c-4c4e-863b-0e1e796f91ea)

Viestin sisältö
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/8b66528a-d76e-4d5c-825d-405c321bfb9f)

Viestin tietoja taulussa message_queue
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/173b799c-dec4-4665-9209-0ce701e074ee)

**Comment by AnneliO** [comment]
Tuossa on nyt kyllä sinänsä outoa, että noutoilmoitus on muodostunut ennen kuin nidettä on edes palautettu. Ilmoitus on muodostunut 25.1.2024 klo 16:46, kun nide on palautettu vasta 26.1.2024 klo 7:51.

**Comment by Kati-Helle** [comment]
varaus on tehty ko. päivänä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/249bb932-47ad-4d90-b43d-4c4372710312)

**Comment by AnneliO** [comment]
> varaus on tehty ko. päivänä ![kuva](https://private-user-images.githubusercontent.com/99952449/300376573-249bb932-47ad-4d90-b43d-4c4372710312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTU4NDgsIm5iZiI6MTcwNjUxNTU0OCwicGF0aCI6Ii85OTk1MjQ0OS8zMDAzNzY1NzMtMjQ5YmI5MzItNDdhZC00ZDkwLWI0M2QtNGM0MzcyNzEwMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDA4MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMTlkZGEyODhkN2EyOWE3MWI4ZjhkYmEzMDMwZjQ0ZThhNjZhMmY4ZjQyZjVjZGQ1M2UxZmY4N2I2NzkxNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gnLK-XAzaPAJt5UMklHFS8q4fSM5ISGzIh90mQORobY)

Niin, on mutta Hellessä on ReservesNeedReturns -järjestelmäasetuksessa _Älä täytä varausta automaattisesti_, joten ei sen olisi pitänyt jäädä kiinni.

**Comment by Kati-Helle** [comment]
Ei niin.

**Comment by AnneliO** [comment]
Varaus on luotu lokien mukaan 2024-01-25 15:13:30 ja sitä on muokattu 2024-01-25 16:46:59 eli samaan aikaan kuin noutoilmoitus on muodostunut. Muokkauksen on tehnyt PRVPK:ssa oleva virkailija ja varauksen found-tilaksi on tuolloin muutettu W eli waiting.

select * from action_logs where object in (select reserve_id from reserves where borrowernumber='25955' and biblionumber='1612324') and module='HOLDS'

En kyllä nyt hoksaa, mitä tuossa on tehty, koska niteen palautusta ei ole kirjautunut lokeille eikä statistics-tauluun.

**Comment by AnneliO** [comment]
Virkailijalta voisi kysyä, muistaako hän tapauksen ja mitä siinä mahdollisesti on tapahtunut. Asiaa tuskin kannattaa tutkia tätä enempää yksittäisen tapauksen vuoksi. Avataan tiketti uudelleen, jos ongelma toistuu. :)

**Comment by Kati-Helle** [comment]
Katsoin vielä varauksen lokitiedot Kohasta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fc953648-c31e-496b-ba10-4335e6a6380f)

Asiakkaan varaukseen on tärpännyt nide, joka on lainattu toiselle asiakkaalle
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/62d73853-501d-44c9-88bf-4676102683d2)

**Comment by Kati-Helle** [comment]
Suljen tiketin.
