### ISSUE TITLE
Raportti kirjaston aineiston arvosta

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1050]
### Tukipyyntö

Kirjasto haluaa tietää kokoelmansa rahallisen arvon, kun Kohaan on tallennettu hankinta- ja korvaushinnat. Raportista voisi ilmetä aineistotyypeittäin kokoelman rahallinen arvo, valinnaksi kirjasto.

**Comment by atarnus** [comment]
OUTIssa tällä hetkellä raportti nro 723: Kokoelman arvo (niteiden hankinta- ja korvaushinnat) aineistotyypeittäin

Seuraava lauseke listaa hinnat aineistotyypeittäin ja yhteensä. Raportille voi syöttää yksittäisen kirjaston koodin tai vaikka OU%

```
SELECT COALESCE(d.Aineistotyyppi, 'Yht.') AS Aineistotyyppi, count(*) AS kpl, sum(d.price) AS Hankintahinta,
       ROUND(sum(d.price)/count(*), 2) AS 'Hank.Keskihinta', sum(d.replacementprice) AS Korvaushinta,
       ROUND(sum(d.replacementprice)/count(*), 2) AS 'Korv.Keskihinta'
       FROM (SELECT COALESCE(bi.itemtype, 'Tieto puuttuu') AS Aineistotyyppi, i.price, i.replacementprice
       FROM items i INNER JOIN biblioitems bi USING(biblionumber)
 WHERE i.homebranch LIKE <<Kunta tai kirjasto ja %>>) AS d 
 GROUP BY d.Aineistotyyppi WITH ROLLUP
 LIMIT 50
```

Mahd. lisäehtoja ja poisrajauksia voi lisätä vaikkanäin:
```
SELECT COALESCE(d.Aineistotyyppi, 'Yht.') AS Aineistotyyppi, count(*) AS kpl, sum(d.price) AS Hankintahinta,
       ROUND(sum(d.price)/count(*), 2) AS 'Hank.Keskihinta', sum(d.replacementprice) AS Korvaushinta,
       ROUND(sum(d.replacementprice)/count(*), 2) AS 'Korv.Keskihinta'
       FROM (SELECT COALESCE(bi.itemtype, 'Tieto puuttuu') AS Aineistotyyppi, i.price, i.replacementprice
       FROM items i INNER JOIN biblioitems bi USING(biblionumber)
 WHERE i.homebranch LIKE <<Kunta tai kirjasto ja %>>
    OR i.homebranch LIKE <<2. Kunta tai kirjasto ja %>>
   AND i.homebranch NOT IN ('kirj1', 'kirj2')) AS d 
 GROUP BY d.Aineistotyyppi WITH ROLLUP
 LIMIT 50
```

Tai jos haluaa käyttää yksittäisten kirjastojen pudotusvalikkoa niin WHERE tämmöiseksi:
`WHERE i.homebranch = <<Kirjasto|branches>> `


Esimerkki raportin tuloksista:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/b5d8e089-027d-4345-81e7-2ea99cd84f9a)

**Comment by pknuuti** [comment]
Kiitos, tämä on hyvä. Suljen tiketin.
