### ISSUE TITLE
Oulun PowerBI-raportin optimointi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1051]
### Tukipyyntö

Oulussa käytössä oleva PowerBI-raportti ei hae aina nimekettä ja aineistotyyppiä, jos lainattu/uusittu nide tai kuvailutietue on poistettu. Raportin voisi koittaa optimoida toimimaan paremmin.

Raportti tällä hetkellä:
```
SELECT s.type AS Tapahtumatyyppi, s.itemnumber AS Nidenumero, IFNULL(bi.title, dbi.title) as Nimeke, s.branch AS Lainauskirjasto,
b.categorycode AS Asiakastyyppi, b.zipcode AS Postinumero, 
s.datetime AS 'Tapahtuma-aika', IFNULL(biblioitems.itemtype, deletedbiblioitems.itemtype) AS Aineistotyyppi,
IFNULL(i.permanent_location, d.permanent_location) AS Hyllypaikka,
IFNULL(i.cn_sort, d.cn_sort) AS 'Luokka ja pääsana'
FROM statistics s
LEFT JOIN borrowers b ON s.borrowernumber = b.borrowernumber
LEFT JOIN items i ON s.itemnumber = i.itemnumber
LEFT JOIN deleteditems d ON s.itemnumber = d.itemnumber
LEFT JOIN biblioitems ON i.biblionumber = biblioitems.biblionumber
LEFT JOIN deletedbiblioitems ON i.biblionumber = deletedbiblioitems.biblionumber
LEFT JOIN biblio bi ON i.biblionumber=bi.biblionumber
LEFT JOIN deletedbiblio dbi ON i.biblionumber=dbi.biblionumber
WHERE date(datetime) BETWEEN <<Aikaväli alkaen|date>> AND <<Päättyen|date>>
AND b.categorycode in ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA")
AND s.type in ('issue', 'renew')
AND s.branch like 'OU%'
AND s.branch !='OUBY'
```

**Comment by atarnus** [comment]
OUTIssa raportti nro 724:

Ongelmanahan oli tosiaan se, että poistetun niteen biblionumberilla ei yhdistetty biblio- tai biblioitems-tauluihin, ja kaikkien näiden liittäminen useammasta kohtaa luo aika massiivisen taulun. Onnistuu ratkaista niin, että ensin tekee Statistics, borrowers ja nidetietojen (ml. poistetut) haun, johon poimitaan mukaan biblionumber jokaiselle niteelle, ja sitten yhdistetään biblio- ja biblioitems-tauluihin hakemaan nimeke ja ainestotyyppi.

```
SELECT d.type AS Tapahtumatyyppi, d.itemnumber AS Nidenumero, IFNULL(b.title, db.title) AS Nimeke, d.branch AS Lainauskirjasto,
       d.categorycode AS Asiakastyyppi, d.zipcode AS Postinumero, d.datetime AS 'Tapahtuma-aika',
       IFNULL(bi.itemtype, dbi.itemtype) AS Aineistotyyppi, d.loc AS Hyllypaikka, d.cn AS 'Luokka ja pääsana'
  FROM (SELECT s.datetime, s.type, s.itemnumber, s.branch, bo.zipcode, bo.categorycode,
               IFNULL(i.biblionumber, di.biblionumber) AS biblionumber,
               IFNULL(i.permanent_location, di.permanent_location) AS loc,
               IFNULL(i.cn_sort, di.cn_sort) AS cn
          FROM statistics_2022 s
               LEFT JOIN borrowers bo ON s.borrowernumber = bo.borrowernumber
               LEFT JOIN items i ON s.itemnumber = i.itemnumber
               LEFT JOIN deleteditems di ON s.itemnumber = di.itemnumber 
         WHERE date(s.datetime) BETWEEN <<Aikaväli alkaen|date>> AND <<Päättyen|date>>
           AND bo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA")
           AND s.type IN ('issue', 'renew')
           AND s.branch like 'OU%'
	   AND s.branch !='OUBY') as d
        LEFT JOIN biblioitems bi ON bi.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblioitems dbi ON dbi.biblionumber = d.biblionumber
        LEFT JOIN biblio b ON b.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblio db ON db.biblionumber = d.biblionumber
```

(Statistics-taulun käsittelyssä on aiheuttanut vähän hämmennystä se, että miksi biblionumberit eivät ole siellä valmiiksi mukana. Nyt pitää hankalasti aina mennä items ja deleteditems -taulujen kautta hakemaan ne.)

**Comment by AnneliO** [comment]
Kiitos!

Lisäsin tämän version raportista myös [Raporttikirjastoon](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#optimoitu-powerbi-kysely).

**Comment by Tuomas-Kyyti** [comment]
Vertasin tätä omaan PowerBI-raporttiini, niin tästä puuttuvat poistetut asiakkaat, kun ei hae deletedborrowers-taulusta. Sitä ei siis ollut tuossa Oulun vanhassakaan versiossa, mutta onkohan tarkoituksella vai vahingossa jäänyt silloin jo pois. Aiheuttaa asiakastyypin ja postinumeron puuttumisen silloin, kun haetaan lainatietoja vanhemmilta vuosilta.

**Comment by AnneliO** [comment]
En muista, onko täysin tarkoituksella, mutta raporttia ajetaan normaalisti kuukausittain, jolloin poistettuja asiakkaita ei ehkä tule vastaan kovin usein. Kyllähän nuo poistetut asiakkaat voisi tähänkin raporttiin lisätä. Aukaisen tiketin ja pistän taas Kassulle.

**Comment by atarnus** [comment]
Jos tähän rapsaan halutaan yhdistää uusia tauluja, niin ei ole hirveän monimutkaista kuitenkaan :)
Tuonne loppuun vain uusi joini ja ensimmäiseen selectiin mukaan se haluttu sarake. (Sisempi select tässä ottaa mukaan tiedot statistics ja items-tauluista, jonka jälkeen jokaiselle riville löytyy tuo d.biblionumber, jolla voi yhdistellä eteenpäin.)

```
SELECT d.type AS Tapahtumatyyppi, d.itemnumber AS Nidenumero, IFNULL(b.title, db.title) AS Nimeke, d.branch AS Lainauskirjasto,
       d.categorycode AS Asiakastyyppi, d.zipcode AS Postinumero, d.datetime AS 'Tapahtuma-aika',
       IFNULL(bi.itemtype, dbi.itemtype) AS Aineistotyyppi, d.loc AS Hyllypaikka, d.cn AS 'Luokka ja pääsana', bde.primary_language AS Pääkieli
  FROM (SELECT s.datetime, s.type, s.itemnumber, s.branch, bo.zipcode, bo.categorycode,
               IFNULL(i.biblionumber, di.biblionumber) AS biblionumber,
               IFNULL(i.permanent_location, di.permanent_location) AS loc,
               IFNULL(i.cn_sort, di.cn_sort) AS cn
          FROM statistics s
               LEFT JOIN borrowers bo ON s.borrowernumber = bo.borrowernumber
               LEFT JOIN items i ON s.itemnumber = i.itemnumber
               LEFT JOIN deleteditems di ON s.itemnumber = di.itemnumber 
         WHERE date(s.datetime) BETWEEN <<Aikaväli alkaen|date>> AND <<Päättyen|date>>
           AND bo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA")
           AND s.type IN ('issue', 'renew')
           AND s.branch like 'OU%'
           AND s.branch !='OUBY') as d
        LEFT JOIN biblioitems bi ON bi.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblioitems dbi ON dbi.biblionumber = d.biblionumber
        LEFT JOIN biblio b ON b.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblio db ON db.biblionumber = d.biblionumber
        LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON bde.biblionumber = d.biblionumber
```

Tämän pitäisi toimia, joskin testillä kun katsoo niin näyttää kielen kohdalla tyhjää, kun siellä ei ole mukana koko biblio_data_elementsiä.

**Comment by atarnus** [comment]
Tässä mukana deletedborrowers ja bibliodataelements:

```
SELECT d.type AS Tapahtumatyyppi, d.itemnumber AS Nidenumero, IFNULL(b.title, db.title) AS Nimeke, d.branch AS Lainauskirjasto,
       d.categorycode AS Asiakastyyppi, d.zipcode AS Postinumero, d.datetime AS 'Tapahtuma-aika',
       IFNULL(bi.itemtype, dbi.itemtype) AS Aineistotyyppi, d.loc AS Hyllypaikka, d.cn AS 'Luokka ja pääsana', bde.primary_language AS Pääkieli
  FROM (SELECT s.datetime, s.type, s.itemnumber, s.branch,
               IFNULL(bo.zipcode, dbo.zipcode) AS zipcode,
               IFNULL(bo.categorycode, dbo.categorycode) AS categorycode,
               IFNULL(i.biblionumber, di.biblionumber) AS biblionumber,
               IFNULL(i.permanent_location, di.permanent_location) AS loc,
               IFNULL(i.cn_sort, di.cn_sort) AS cn
          FROM statistics s
               LEFT JOIN borrowers bo ON s.borrowernumber = bo.borrowernumber
               LEFT JOIN deletedborrowers dbo ON s.borrowernumber = dbo.borrowernumber
               LEFT JOIN items i ON s.itemnumber = i.itemnumber
               LEFT JOIN deleteditems di ON s.itemnumber = di.itemnumber 
         WHERE date(s.datetime) BETWEEN <<Aikaväli alkaen|date>> AND <<Päättyen|date>>
           AND (bo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA")
               OR dbo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA"))
           AND s.type IN ('issue', 'renew')
           AND s.branch like 'OU%'
	   AND s.branch !='OUBY') as d
        LEFT JOIN biblioitems bi ON bi.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblioitems dbi ON dbi.biblionumber = d.biblionumber
        LEFT JOIN biblio b ON b.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblio db ON db.biblionumber = d.biblionumber
        LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON bde.biblionumber = d.biblionumber
```

**Comment by pknuuti** [comment]
Olisiko mitenkään mahdollista saada nimekkeestä näkyviin myös alaotsikko ja osan tiedot. Varsinkin sarjoissa saattaa olla sama nimeke, vaikka kyseessä on ihan eri osat, jotka erotetaan vain noilla muilla nimekkeen kentillä. Näköjään tekijäkin puuttuu, sekin on hyvin olennainen, koska saman nimisiä teoksia on eri tekijöiltä.
Tuomaksen aikaisemmin tekemässä raportissa on näin:
IFNULL(bi.author, IFNULL(bi2.author, dbi.author)) as 'Tekijä', 
IFNULL(bi.title, IFNULL (bi2.title, dbi.title)) AS 'Nimeke', 
IFNULL(bi.subtitle, IFNULL(bi2.subtitle, dbi.subtitle)) AS 'Alanimeke', 
IFNULL(bi.part_name, IFNULL(bi2.part_name, dbi.part_name)) AS 'Osan nimi', 
IFNULL(bi.part_number, IFNULL(bi2.part_number,dbi.part_number)) AS 'Osan numero',

**Comment by AnneliO** [comment]
Voi olla osalle itsestään selvää, mutta hoksautan varalta, että jos lisäätte sarakkeiden määrää raporttiin, niin se ei sen jälkeen välttämättä vastaa teidän vanhan raportin rakennetta, eikä tiedot ole suoraan yhdistettävissä PowerBI:ssä vanhoihin tietoihin. Eli voi vaatia säätöjä siellä taustalla, missä määritetään tietojen yhteydet. Tai kaikkien vanhojen tietojen vientiä uudella sarakerakenteella. @Tuomas-Kyyti varmaan osaisi kertoa tarkemmin, vaatiiko jotain säätöä.

Suosittelisin joka tapauksessa, että ainakin kaikki nimeketiedot yhdistetään yhteen sarakkeeseen. :)

**Comment by pknuuti** [comment]
Teen uuden raportin uusilla sarakkeilla, ei se muuten toimi. Minustakin on kätevämpää, että kaikki nimeketiedot ovat yhdessä sarakkeessa, koska nimeke on kuitenkin silloin yksilöllisempi.

**Comment by atarnus** [comment]
Tässä yhdistetty nimeke:

```
SELECT d.type AS Tapahtumatyyppi, d.itemnumber AS 'Nidenumero', IFNULL(b.author, db.author) AS 'Tekijä',
       CONCAT_WS(' ', IFNULL(b.title, db.title), IFNULL(b.subtitle, db.subtitle), IFNULL(b.part_name, db.part_name), IFNULL(b.part_number, db.part_number)) AS 'Nimeke',
       d.branch AS 'Lainauskirjasto', d.categorycode AS 'Asiakastyyppi', d.zipcode AS 'Postinumero', d.datetime AS 'Tapahtuma-aika',
       IFNULL(bi.itemtype, dbi.itemtype) AS 'Aineistotyyppi', d.loc AS 'Hyllypaikka', d.cn AS 'Luokka ja pääsana', bde.primary_language AS 'Pääkieli'
  FROM (SELECT s.datetime, s.type, s.itemnumber, s.branch,
               IFNULL(bo.zipcode, dbo.zipcode) AS zipcode,
               IFNULL(bo.categorycode, dbo.categorycode) AS categorycode,
               IFNULL(i.biblionumber, di.biblionumber) AS biblionumber,
               IFNULL(i.permanent_location, di.permanent_location) AS loc,
               IFNULL(i.cn_sort, di.cn_sort) AS cn
          FROM statistics s
               LEFT JOIN borrowers bo ON s.borrowernumber = bo.borrowernumber
               LEFT JOIN deletedborrowers dbo ON s.borrowernumber = dbo.borrowernumber
               LEFT JOIN items i ON s.itemnumber = i.itemnumber
               LEFT JOIN deleteditems di ON s.itemnumber = di.itemnumber 
         WHERE date(s.datetime) BETWEEN <<Aikaväli alkaen|date>> AND <<Päättyen|date>>
           AND (bo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA")
               OR dbo.categorycode IN ("HENKILO", "KOTIPALVEL","LAPSI", "LAOMATOIMI", "MUUHUOL", "YHTEISO","KAUKOLAINA"))
           AND s.type IN ('issue', 'renew')
           AND s.branch like 'OU%'
	   AND s.branch !='OUBY') as d
        LEFT JOIN biblioitems bi ON bi.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblioitems dbi ON dbi.biblionumber = d.biblionumber
        LEFT JOIN biblio b ON b.biblionumber = d.biblionumber
        LEFT JOIN deletedbiblio db ON db.biblionumber = d.biblionumber
        LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON bde.biblionumber = d.biblionumber
```

**Comment by pknuuti** [comment]
Kiitos noista lisäyksistä raporttiin. Kun vertaan tuota Tuomaksen aikaisemmin tekemään lainausdata-raporttiin, niin Outin raportista puuttuu muutama mielestäni tärkeä tieto: tietuenumero, kokoelma ja asiakkaaseen liittyvät tiedot eli asiakas-id, svuosi (asiakkaan syntymävuosi). Asiakkaaseen liittyvät tiedot ovat toki vähän arveluttavia tietoturvan takia, mutta toki käyttäjälle näkyy vain numerotietoja, ei mitään asiakkaan tietoja. 
Tuomaksen raporteissa tapahtuma-aika on jaettu pienempiin osiin päivämäärän ja tunnin osalta, jotta saadaan tarkempia lainaustietoja vuorokaudenajan mukaan. Myös luokka ja pääsana ovat omina sarakkeinaan, jotta luokalla voidaan rajata hakua. Tokihan näitä voi tehdä myös PowerBI:ssä, mutta kun raporttia päivitetään, siitä tulee ongelmia. 
Olisiko nämä lisäykset mahdollista/järkevää tehdä myös tähän Outin raporttiin? Vai olisiko jotain muuta, mitä tähän pitäisi lisätä, jotta lainausdataa saisi hyödynnettyä paremmin?

**Comment by Ritu-Oulu** [comment]
Oulussa yksilöivät asiakastiedot on tarkoituksella tiputettu rapsasta pois, koska mukana ei haluta pitää tietosuojan alaisia yksilöiviä tietoja. Helpottaa rapsasta tehtyjen visualisointien jakamista. Hyvä muutos on tuoda tarkempi nimeke, mutta komppaan Annelia, että samaan sarakkeeseen.

Päivämäärä Oulun/OUTIn rapsaan tulee sekuntitasolla ja sitä onkin hyödynnetty visualisoinnissa, kun on tsekattu mihin aikaan vuorokaudesta lainoja tehdään.

**Comment by pknuuti** [comment]
Olen yrittänyt muokata tuota viimeisintä raporttiversiota sellaiseksi, että se ei vaatisi mitään kirjastovalintaa, vaan antaisi lainat koko Vaarasta. Kun poistan rivit "AND s.branch like 'SII%'    AND s.branch !='OUBY') as d" raportti antaa virheilmoituksen. Miten tuo pitää muokata niin, että saan koko Vaaran lainaukset kerralla? Jos laitan tuohon meidän kirjastotunnuksia, saan kyllä sen sillä tavalla toimimaan, mutta siis rivien poistaminen ei ole se oikea ratkaisu.

**Comment by atarnus** [comment]
Hei,

`) AS d `
osaa rivistä ei saa poistaa, se määrittelee tuon sisemmän SELECTin lopun.

Muokkasin ylläolevaa lauseketta nyt niin että myös kirjasto on syötettävä parametri, jos haluaa käyttää samaa raporttia eri rajauksilla muuttamatta koko lauseketta.

Nyt voi poistaa tuolta
```
AND s.branch LIKE <<Kunta- tai kirjastokoodi ja %>>
	   AND s.branch !='OUBY'
```
ja lausekkeen pitäisi toimia ilman kirjastorajausta.

!='OUBY' rajaa tuon haun ulkopuolelle, niin vaikka se ei ole tarpeen muille kuin Oululle, sen ei pitäisi myöskään olla haitaksi muille.

**Comment by pknuuti** [comment]
Kiitos, enpä hoksannut tuota sulkumerkkiä!

**Comment by AnneliO** [comment]
Tässä on jo tehty paljon optimointia. Jos tulee vielä tarpeita, niin tehdään uusi tiketti. :)
