### ISSUE TITLE
Ylläpito/Lisäkentät: auktorisoidun arvon luokan tallennus ei onnistu kenttään

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1053]
### Mikä vikana?

Hankinnan uudesta tyhjästä tietueesta -toimintoon saa nyt lisättyä kentän/kenttiä 
Ylläpito/Lisäkentät (Administration/Additional fields)

Helle-testausta.

Kenttään on mahdollista valita auktorisoitu arvo. Arvon saa valittua, mutta uutta kenttäarvoa ei saa tallennettua arvon kera.

Ennen tallennusta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/33ef4ebb-7b77-4378-909d-9ecf12635035)

Tallenna-painikkeesta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/aa9b9c48-e8f7-469b-9f39-6e689fad2795)

Ilman auktorisoitua arvoa kenttä tallentuu
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/6fb501f5-5330-4c14-ae28-b48f54be687a)

**Comment by AnneliO** [comment]
[Koha-manuaali](https://koha-community.org/manual/23.11/en/html/administration.html#additional-fields) sanoo näin:

Note

You can only choose one of the two options (authorized value OR MARC field)

**Comment by Kati-Helle** [comment]
Erikoista. Kiitos tiedosta.
