### ISSUE TITLE
Kyyti: tekstiviestien lähettäjän nimi ei enää kuntakohtainen

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1055]
### Mikä vikana?

1.2.2024 alkaen Kyytin tekstiviesteissä alkoi näkyä lähettäjänä Hamina, vaikka aiemmin siinä ollut sen kunnan nimi, jonka kirjastosta viesti on lähtenyt.

Kyyti-kirjastoilla on yhteinen tekstiviestisopimus Arena Interactiven kanssa, mutta jokainen kunta on saanut omat laskunsa.

Matrixin keskustelussa päädyttiin siihen, että tekstiviestien erottelu on perustunut kirjaston sähköpostiosoitteisiin (branchemail), jotka 31.1. iltapäivällä muutettiin kaikissa samoiksi noreply@koha-suomi.fi.

Oletettavasti myös lasku kaikista tekstiviesteistä menee nyt Haminaan. Hamina on varmaan valikoitunut, koska se on aakkosissa Kyytin kunnista ensimmäinen.

Mitä ratkaisuja tähän voisi olla?

**Comment by johannaraisa** [comment]
Tämän korjaamiseen ei taida olla muuta vaihtoehtoa kuin ottaa viestistä asiakkaan kotikirjasto, reply_to kenttiä ei noihin tule.

**Comment by Tuomas-Kyyti** [comment]
> Tämän korjaamiseen ei taida olla muuta vaihtoehtoa kuin ottaa viestistä asiakkaan kotikirjasto, reply_to kenttiä ei noihin tule.

Parempi toki kuin tämän hetken tilanne, mutta ei toki ideaali. Asiakas odottaa saavansa viestin siitä kirjastosta, jossa varaus on odottamassa eikä omasta kotikirjastostaan, joka voi olla eri. Omaa kotikirjastoaan asiakas ei edes näe eikä voi muuttaa itse. (Finnassa oleva oletusnoutokirjasto on eri asia.). Tottumisasia on toki.

**Comment by johannaraisa** [comment]
Sitten on tietenkin sekin vaihtoehto, että kaikkien tunnusten lyhytnumeroksi laitetaan Kyyti tai Kirjasto.

**Comment by Tuomas-Kyyti** [comment]
> Sitten on tietenkin sekin vaihtoehto, että kaikkien tunnusten lyhytnumeroksi laitetaan Kyyti tai Kirjasto.

Tuokin voisi olla vaihtoehto, mutta entä se laskutus. Nyt jokainen kunta on saanut oman laskunsa. Eikä ainakaan Kouvola halua alkaa tekemään jyvitystä ja laskuttamaan muita kuntia.

**Comment by johannaraisa** [comment]
> > Sitten on tietenkin sekin vaihtoehto, että kaikkien tunnusten lyhytnumeroksi laitetaan Kyyti tai Kirjasto.
> 
> Tuokin voisi olla vaihtoehto, mutta entä se laskutus. Nyt jokainen kunta on saanut oman laskunsa. Eikä ainakaan Kouvola halua alkaa tekemään jyvitystä ja laskuttamaan muita kuntia.

Tuota jyvitystä varten joutuu tekemään sen muutoksen, että katsotaan se asiakkaan kotikirjasto.

**Comment by Tuomas-Kyyti** [comment]
> > > Sitten on tietenkin sekin vaihtoehto, että kaikkien tunnusten lyhytnumeroksi laitetaan Kyyti tai Kirjasto.
> > 
> > 
> > Tuokin voisi olla vaihtoehto, mutta entä se laskutus. Nyt jokainen kunta on saanut oman laskunsa. Eikä ainakaan Kouvola halua alkaa tekemään jyvitystä ja laskuttamaan muita kuntia.
> 
> Tuota jyvitystä varten joutuu tekemään sen muutoksen, että katsotaan se asiakkaan kotikirjasto.

Eli voi siis olla sama lyhytnumero ja silti laskutus menee kotikirjaston mukaan?

**Comment by johannaraisa** [comment]
En kyllä tiedä miten se siellä Arenalla menee, olikohan teillä jokin hallintapaneeli siellä Arenalla missä voi lyhytnumeron määritellä erikseen?
