### ISSUE TITLE
Helle: asiakastyypin salasanan generointiin muutos

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1058]
### Tukipyyntö

Hellessä kaukolaina-asiakastyypin salasanan pituus muutetaan. Muutoksen toteutustapa IntranetUserJS-rimpsu:
Generoi henkilöasiakkaalle PIN-koodi salasanaksi

Asiakastyypin tunnus: 
KAUKOLAINA

Sopisiko toteutukselle joku aamu ensi viikolla (viikko 7 eli 12.-16.2.2024)?

**Comment by paxed** [comment]
KAUKOLAINA lisätty sinne

**Comment by Kati-Helle** [comment]
Kiitos Pasi!
