### ISSUE TITLE
Lumme: Sotu-avainkentän siirto

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1059]
### Tukipyyntö

Lumpeissa tarvittaisiin apua sotu-avainkentän siirtoon hetun lisäyksen alle kuvan mukaisesti. Tarkoituksena helpottaa virkailijaa huomaamaan, jos hetun lisäys ei ole onnistunut ja sotu-avain jää puuttumaan.

![image](https://github.com/KohaSuomi/Koha/assets/129748294/f66670ef-312f-41d3-8acc-390ae8189294)

**Comment by lmstrand** [comment]
Voin tehdä muutoksen tänään illalla jos sopii.

**Comment by Hanna-Lumme** [comment]
Muutos näkyy oikein, suljen tiketin. Kiitos!
