### ISSUE TITLE
Lumme/automaatin siirto ja uudet tunnarit

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#1064]
### Tukipyyntö

Automaatti jonka borrowernumber on 255228 siirretään pääkirjastolta Kalevankankaan koululle. Kotikirjastoksi tulee uusi kirjastopiste Kalevankankaan koulu/Liikkuvat palvelut (MLI_KAL). On sen verran vanha automaatti, ettei salasanaa ole meillä tiedossa-> poistatteko vanhat tunnarit palvelimelta ja teette uudet?

**Comment by AnneliO** [comment]
[Sip-tunnusten käsittelyohje](https://koha-suomi.fi/dokumentaatio/automaatit/#sip2-tunnusten-k%C3%A4sittelyohje) eli pääkäyttäjät tekevät sip-tunnukset ja toimittavat ne Koha-Suomelle ja automaatin toimittajalle salattuna. :)

**Comment by lmstrand** [comment]
Pahoittelut, tuo vanhakin viestilinkki aukesi vielä, kun satuin tarkistamaan. Työllistin nyt turhaan, mutta vanha automaattitunnus on korvattu uudella. Huomisesta käytettävissä.

**Comment by Katja-Lumme** [comment]
[like]  Valjakka Katja reacted to your message:
________________________________
