### ISSUE TITLE
Hetun tallennukseen painikkeen siirto tai muistutus tallentamattomasta hetusta

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1066]
### Kehitysehdotukseni

Hetun tallennus voi jäädä tekemättä, jos käyttäjä kirjoitettuaan hetun "Lisää hetu"-kenttään ei paina "Tallenna"-painiketta. Kirjastolla on oikeus tallentaa hetu, ja hetuttomien asiakastietojen läpikäynti ja hetujen saaminen asiakkailta voi olla hankalaa. Hetu-kentästä ei voi tehdä pakollista, koska kaikilla asiakkailla hetua ei ole. 

Ehdotukset toteutusvaihtoehdoiksi: 
1. Tallenna-painike siirretään "Lisää hetu" kentän alle, ennen "Hetuavain"-kenttää. 

2. Jos käyttäjä ei ole painanut hetun lisättyään "Tallenna" -painiketta, mutta on muuten täyttänyt asiakastietojen kentät ja painaa sen jälkeen Lisää asiakas -sivun keltaista Tallenna-painiketta, näytetään poppari esim. tekstillä "Hetua ei ole tallennettu. Haluatko tallentaa asiakastiedon tallentamatta hetua?" Tämän jälkeen olisi valittavissa joko Kyllä tai Ei. 

Lappi kannattaa vaihtoehtoa 2.

**Comment by AnneliO** [comment]
Asiantuntijaryhmän päätös 29.4.2024:

Tutkitaan, saisiko asiakkaan muokkaus/lisäyssivun yläreunan Tallenna-napin "epäaktiiviseksi" kunnes on painettu Lisää hetu -osiossa joko Tallenna tai Ohita. Jonkinlainen ohjeistus myös, jos yritetään tallentaa ilman hetun tallennusta tai ohitusta.

**Comment by lmstrand** [comment]
Käytetään Tallenna-napin epäaktiivista/aktiivista tilaa asiakastietojen tallennuksessa. Toteutus viety testattavaksi testeille.

**Comment by piiaseme** [comment]
OUTIn testillä sekä Ohitus-nappi että Vie Sotu-siiloon-nappi toimivat kuten pitääkin eli jompi kumpi tulee klikata, jotta Tallenna-nappi aktivoituu.

**Comment by sksandel** [comment]
Nykyinen toteutus ei huomioi mitä käyttäjä on tekemässä. Tallenna-painike on epäaktiivisena aina, myös silloin kun käy muokkaamassa asiakastietoja. Eli joka kerta pitäisi ohittaa tai tallentaa hetu. Näin myös silloin kun asiakastiedoissa on jo entuudestaan tallennettuna sotu-avain. Käyttäjälle ei myöskään kerrota, miksi tallenna-painike ei ole aktiivisena, joten se voi jäädä epäselväksi. 

Toiminnon (Tallenna-painikkeen epäaktiivisuuden) pitäisi olla aktiivisena vain silloin, kun käyttäjä on muokannut hetu-kenttää.

**Comment by AnneliO** [comment]
Ohjeistus tosiaan vielä puuttuu alkuperäisen toimeksiannon mukaisesti. Ehdotin Matrixissa kehittäjille tällaista ohjetta johonkin kohtaan laitettavaksi, kun nappi on epäaktiivinen:

"Lisää tai ohita henkilötunnus ensin"

**Comment by pirliis** [comment]
Punaisella lisätty ohjeistus kyllä kertoo käyttäjälle selkeästi, mitä pitää ensin tehdä, ennen kuin tiedot voidaan tallentaa. Tuntuu vähän turhauttavalta, jos vaikka asiakkaan tietoja on vain päivitetty, pitää erikseen aina painaa Ohita-painiketta ennen kuin pystyy tallentamaan tiedot.

Pystyykö tätä toteuttamaan kuin Susannakin ehdotti, jos Lisää hetu -kentässä on tallentamaton henkilötunnus, Tallenna-painike ei olisi aktiivinen ennen kuin hetu on viety sotu-siiloon?

**Comment by IrinaHalminen** [comment]
Olen samaa mieltä tuosta ohittamisesta. Tekee asiakastietojen muokkauksen varmasti sekavamman oloiseksi. Tarvitseeko ohitusta tyrkyttää myöhemmissä tilanteissa, joissa hetu on jo asiakastiedoissa?

**Comment by paxed** [comment]
Tein sotuteekki-plugariin muutoksen, jossa sotun kysely ohitetaan automaattisesti, jos käyttäjällä on jo SSN-arvo. Päivitin plugarin testeille, mut en tiedä miten sitä siellä oikein testaisi, kun eihän noita sotuja voi oikein siellä syötellä... Voi tietysti manuaalisesti antaa SSN-arvon, vaikka se ei olekaan sotuteekissa mitenkään kiinni.

**Comment by pirliis** [comment]
OUTIn tesiltä on yhteys sotusiiloon. Lisäsin testitunnukseeni oman hetun ja sain näin tallennettua sotu-avaimen Sotu-avain -kenttään. 

Muutos näytti toimivan eli jos asiakkaalla on sotu-avain, ei tarvinnut painaa Ohita-painiketta, vaan Tallenna-painike oli oletuksena aktiivinen. Jos asiakkaalla ei ole sotu-avainta, tallennus vaati, että painaa ensin Ohita-painiketta, jonka jälkeen Tallenna-painike aktivoitui.

**Comment by paxed** [comment]
Ja vielä yksi päivitys: Jos Uusi/muokattava asiakas on tyyppiä institution ("I"), eli esim. YHTEISO, niin silloin sotun kyseleminen on ohitettu automaattisesti. Testaa kun kerkiät @pirliis

**Comment by pirliis** [comment]
> Ja vielä yksi päivitys: Jos Uusi/muokattava asiakas on tyyppiä institution ("I"), eli esim. YHTEISO, niin silloin sotun kyseleminen on ohitettu automaattisesti. Testaa kun kerkiät @pirliis

OUTIn testillä asiakastyypillä YHTEISO ohitus toimii automaattisesti.

**Comment by pknuuti** [comment]
Toimii Vaaran testillä. Jos asiakkaalla on sotuavain, tallennus onnistuu ilman ylimääräisiä ohituksia, kuten Pirliis on todennut 14.6. Jos sotuavainta ei ole, tallentaminen vaatii ohittamisen.

**Comment by AnneliO** [comment]
> Toimii Vaaran testillä. Jos asiakkaalla on sotuavain, tallennus onnistuu ilman ylimääräisiä ohituksia, kuten Pirliis on todennut 14.6. Jos sotuavainta ei ole, tallentaminen vaatii ohittamisen.

Vaatiiko se ohittamisen myös instituition-tyyppisillä asiakkailla eli näillä, joilla tyyppinä on "Org.":

![kuva](https://github.com/user-attachments/assets/14a1b5e8-0f70-470b-93c5-b1c3ba19f484)

**Comment by pknuuti** [comment]
Testasin yhteisöasiakkaalla, ei vaadi ohittamista, tallentaminen onnistuu kunhan pakolliset kentät on täytetty.

**Comment by piiaseme** [comment]
Testasin OUTIn org.-tyyppisillä tunnuksilla ja tallentaminen onnistui molemmilla ilman ohittamista.
Pirliin aiemmat testaukset OUTIssa pätevät edelleen eli jos asiakkaalla on sotuavain, tallennus onnistuu ilman ylimääräisiä ohituksia ja ,jos sotuavainta ei ole, tallentaminen vaatii ohittamisen.

**Comment by IrinaHalminen** [comment]
Näin yhden päivän tuotantokäytön jälkeen toivoisin, että myös virkailijatunnuksilla voisi olla tuo ohituksen vaatiminen poissa käytöstä. Vaihdamme virkailijatunnuksen kotikirjastoa sijainnin mukaan useammankin kerran päivässä/viikossa, jos työskentelemme useamman kirjaston alueella (esim. oma alueeni käsittää viisi kirjastoa, joitten alueella henkilökunta kiertää).

**Comment by lmstrand** [comment]
> Näin yhden päivän tuotantokäytön jälkeen toivoisin, että myös virkailijatunnuksilla voisi olla tuo ohituksen vaatiminen poissa käytöstä. Vaihdamme virkailijatunnuksen kotikirjastoa sijainnin mukaan useammankin kerran päivässä/viikossa, jos työskentelemme useamman kirjaston alueella (esim. oma alueeni käsittää viisi kirjastoa, joitten alueella henkilökunta kiertää).

Tähän voidaan tehdä muutos ensi keskiviikon palvelinhuollon jälkeen. Tilapäisesti virkailijat voivat kirjoittaa itselleen jotain sotuavain-kenttään, niin ohitusta ei enää tarvita.

**Comment by IrinaHalminen** [comment]
Sotuavainkenttään ei voi kirjoittaa, joten odotellaan vain muutosta. :)

**Comment by IrinaHalminen** [comment]
Tämä muutostoive koskien virkailijatiliä ei ole vielä päivittynyt (henkilökunnalle tiedotettu aiemmin tuosta viime viikon aikataulusta). Saisiko ensi tiistain päivitykseen?

**Comment by lmstrand** [comment]
Staff-tyypin asiakkaille (sis. virkailijat, automaatit ja eitilasto-asiakastyypit) lisätty ohituksen vaatimisen poisto eli kentän/nappien poisto käytöstä. Testattavissa testeillä.

**Comment by IrinaHalminen** [comment]
Kiitos. Virkailija ja automaatti (Org.) ok. Ei-tilastoiva asiakas (siis vain se 1 kpl) vielä haluaa ohita-painiketta painettavan, mutta sillä tuskin on väliä. Ei-tilastoiva on tyypiltään tilastoyksikkö, ei henkilökunta.

![kuva](https://github.com/user-attachments/assets/66c6f1c3-6e16-44b2-bae5-0395a23930f4)

**Comment by lmstrand** [comment]
Aivan näissä siis on kimppakohtaisuuksia. No virkailijatunnukset varmasti ovat kaikilla tuota henkilökunta-tyyppiä joten korjauksen pitäisi olla ok ja puree siis kaikkiin niihinkin nyt Org.-tyypin lisäksi.

**Comment by lmstrand** [comment]
> Staff-tyypin asiakkaille (sis. virkailijat, automaatit ja eitilasto-asiakastyypit Vaarassa, Kirjaston työntekijä-tyyppi) lisätty ohituksen vaatimisen poisto eli kentän/nappien poisto käytöstä uutta asiakastiliä tehdessä ja niiden muokkauksessa. Testattavissa testeillä.

Tämä muutos on viety tuotantoihin.
