### ISSUE TITLE
OUTI: Oulussa otetaan koekäyttöön Puppe-tilaustenvastaanottotyökalu 23.2.2024

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1069]
### Tukipyyntö

Oulussa otetaan koekäyttöön ensin pariksi viikoksi Puppe-tilaustenvastaanottotyökalu perjantaina 23.2.2024. Jos työkalu osoittautuu toimivaksi, jää ilmeisesti käyttöön.

Broomworksilta ovat pyytäneet API-avaimen ja tunnukset samoilla oikeuksilla kuin Broomworksin Turun API-avaimessa on. 

Koha-Suomi hoitanee muut tarvittavat asiat kuntoon ennen koekäytön alkamista?

**Comment by ajrajala** [comment]
Turun API-avaimen käyttöoikeudet:
- catalogue
- editcatalogue
- budget_manage_all
- order_manage
- order_manage_all

**Comment by lmstrand** [comment]
Puppe vaatii portaali-id:n EditX-sanomiin. Plugin osaa sen kyllä laittaa paikalleen, jos se vaan välittyy sanomissa. Tämä siis on hoidettava Woiman kanssa kuntoon.

**Comment by pirliis** [comment]
> Tarkistatteko siis Woiman kanssa, että portaali-id lisätään sanomiin/kulkee sanomissa ennen koekäyttöä.

Laitan tästä Broomworksille.

**Comment by pirliis** [comment]
Broomworksille toimitettu salattuna API- tunnus ja -avain.

Broomworksilta ilmoittivat, että portaali-id tulee jo Oulun Editx-sanomissa.

**Comment by ajrajala** [comment]
Tiedoksi vielä tähän tikettiin, että Broomworks yrittää parantaa tilausten kohdentumista Pupessa tapauksissa joissa ei löydy portalID -arvoa ja sitä varten he tarvitsevat listauksen vendoreista GET /api/v1/acquisitions/vendors/ kautta. Endpoint vaatii oikeuden vendors_manage, jota ei aiemmin ollut käyttöoikeuksiin listattu mutta joka nyt on lisätty [Integraatiot-listaukseen](https://github.com/KohaSuomi/Koha/wiki/Integraatiot). Eli tuo käyttöoikeus on varmaan hyvä lisätä myös OUTIn API-tunnukselle.

**Comment by AnneliO** [comment]
Onko tässä tiketissä vielä tehtävää, vai voisiko sen sulkea? :)

**Comment by pirliis** [comment]
Broomworks ei ole OUTIn API-tunnukselle pyytänyt vendors_manage-oikeutta, mutta lisäsin sen nyt.

Uutiskirjeen myötä kuulimme, että Puppe on tullut ilmeisesti Ouluun jäädäkseen. Eli suljetaan tiketti. :)
