### ISSUE TITLE
Lainojen määrän esitystapa muuttuu asiakashaun tuloksissa, jos lainoja on myöhässä

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1074]
### Mikä vikana?

Hae asiakastietoja, esim. kirjaston työkortit. Saaduissa hakutuloksissa on yksi sarake lainojen määrälle (Lainoja). Sarakkeessa esitetään lainamäärä muodossa 0/65 (esim.), joka antaa ymmärtää, että asiakkaalla on 65 lainaa, joista 0 on myöhässä. Jos asiakkaalla on myöhässä olevia lainoja, sarakkeessa näkyy punaisella myöhässä olevien lainojen määrä, mutta kaikkien lainojen määrä häviää. Eli jos ko. esimerkkiasiakkaalla on vaikka 2 lainaa 65 lainasta myöhässä, näkyy sarakkeessa punaisella vain luku 2. 

### Mitä pitäisi tapahtua

Lainat esitettäisiin muodossa myöhässä olevat/kaikki lainat eli esim. 2/65, jossa numero 2 olisi punaisella. 

![thumbnail_3FACF54BE6AA4032B4A07339F0DCA3BB](https://github.com/KohaSuomi/Koha/assets/99409279/7dee123e-3033-4044-bd47-68058a1f1364)

**Comment by pknuuti** [comment]
Eikös tämä muutos ole tulossa jo versionvaihdossa? https://github.com/KohaSuomi/Koha-23x/wiki/Uutta-23.x%E2%80%90versiossa#my%C3%B6h%C3%A4ss%C3%A4-olevien-lainojen-m%C3%A4%C3%A4r%C3%A4-asiakashaussa
