### ISSUE TITLE
Fasettien järjestys suomenkielisen aakkostuksen/halutun valinnan mukaiseksi?

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1075]
### Kehitysehdotukseni

Fasetit ovat nyt englanninkielisen aakkosjärjestyksen/järjestyksen mukaisesti myös suomen- ja ruotsinkielisessä valikossa. Olisiko mahdollista järjestää ne aakkosjärjestykseen tai yhteisesti sovittuun käytönmukaiseen järjestykseen? Esim. Nykyinen paikka on valikossa toiseksi alimpana, vaikka sitä tarvitaan usein asiakaspalvelussa. 

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/41ac98c1-113f-4ec0-a0cc-7d220dfc7002)
![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/1aa7d20d-ee01-4026-b100-13c835026e78)

**Comment by AnneliO** [comment]
Fasettien keskinäistä järjestystä voi muuttaa Ylläpidossa Hakukoneen asetukset (Elasticsearch) Nimeketietueet -välilehdellä ihan pohjalla Fasettien järjestys -osiossa. Fasetteja voi järjestellä ottamalla halutusta rivistä kiinni hiirellä ja hiissaamaalla se haluttuun kohtaan ja sen jälkeen tallentamaan tiedot.

Suosittelen testaamaan testillä huolellisesti ennen kuin tekee tuotantoon muutoksen. :)

**Comment by IrinaHalminen** [comment]
Jee, hienoa, kiitos! Tämä oli Vaaran porukoilta unohtunut täysin. Testaillaan!
