### ISSUE TITLE
Lappi: Virheellinen varaussija 0

### ISSUE THREAD

**Issue by noorsuva** [KohaSuomi/Koha#1076]
### Mikä vikana?

Asiakkaalta tullut palaute verkkokirjaston kautta "kirjan varaussijani on 0. Kerran aiemmin käynyt myös näin toisen kirjan kanssa. Ihmettelin silloin miksi kirja ei tule minulle varatuksi, vaikka oli vapaana kirjoja. Silloinkin varauksen numero oli 0. Silloin poistin varauksen ja tein varauksen uudelleen ja sain kirjan varaushyllylle." Asiakas siis näkee verkkokirjastossa olevansa varaussijalla 0.

Tietuenäytöllä niteen kohdalla lukee "Niteestä on varaus (prioriteetti = 0)", ei esim. kuljetustilaa.
Varausnäytöllä lukee lukee "Nidettä käsitellään pisteessä Rovaniemen pääkirjasto".
Asiakkaan varauksissa näkyy nidenumero, mutta varauksen tilaa ei ole.
Hyllyvarauslistalla ei ole varausta.

Liitteenä vielä kuvankaappauksia. Mikä voisi olla syy?
![0 varaus 1](https://github.com/KohaSuomi/Koha/assets/98962815/9ac32641-c328-400b-bb27-8e1d34ec7a60)
![0 varaus 2](https://github.com/KohaSuomi/Koha/assets/98962815/c4a598fc-df17-49a7-a98b-54d6f6a8d582)
![0 varaus 3](https://github.com/KohaSuomi/Koha/assets/98962815/9fa1c660-078a-457c-a353-04394d2b1234)

### Kuinka toistaa ongelma/asia

En saa toistettua virhettä.

**Comment by AnneliO** [comment]
Katselin tuon kyseisen asiakkaan ja teoksen tietoja lokilta raportilla 227 ja varaus on jäänyt kiinni 2024-02-05 15:21:24 automaatilla, jolloin se on mennyt käsiteltävänä eli prosessing-tilaan. Silloin varauksen prioriteetti on 0.

Tuossa on nyt siis jäänyt palauttamatta nide vielä Kohassa, jolloin varaus muuttuu noudettavana-tilaiseksi ja asiakkaalle lähteeä noutoilmoitus.

**Comment by AnneliO** [comment]
Teillä on tallennetuissa raporteissa [raportti 394](https://lappi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=394&phase=Run+this+report&param_name=Valitse+kirjasto%7Cbranches&sql_params=ROPK) (linkissä Rovaniemen pääkirjasto valittuna kirjastoksi raporttia ajaessa), jolla saa haettua niteet, jotka odottavat uudelleenpalautusta varauksen vuoksi. Korjasin sen toimivaksi. Tällä hetkellä Lapissa on 12 varausta, jotka ovat processing/käsiteltävänä-tilassa, vanhin vuoden takaa.

**Comment by noorsuva** [comment]
Kiitos! Me tiedotamme näistä ja pyydämme kirjastoja palauttamaan.

**Comment by AnneliO** [comment]
@noorsuva suljetko tiketin, jos asia korjaantui tällä. :)
