### ISSUE TITLE
Maksa maksuja -näytön ongelmat

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1077]
### Mikä vikana?

Kun menee asiakkaan tiedoissa Maksa maksuja -näkymään, siellä on ylimpänä Maksa-painike keltaisella pohjalla ja vihreä Poista-teksti valkoisella pohjalla. Kun kursorin vie Poista-tekstin päälle, teksti katoaa näkyvistä kokonaan ja käyttäjä luulee, että se ei toimi. Valkoista linkkiä klikkaamalla saa Poista valitut myöhästymismaksut-näkymän esille ja siellä toistuu näiden painikkeiden katoaminen näkyvistä. Näille painikkeille pitäisi varmaankin olla joku pohjaväri, niin eivät häviäisi näkyvistä. 
Onko tämä korjattavissa IntranetUserCSS-määrityksellä vai millä?
Liitteenä kuvat tapauksista.
![2023kuvat 310](https://github.com/KohaSuomi/Koha/assets/73887264/831c3bae-ad39-4489-a4ec-aa690e889ae7)
![2023kuvat 311_ver001](https://github.com/KohaSuomi/Koha/assets/73887264/8bbec0eb-5fb1-4206-87f5-482f64cb4ac2)
![2023kuvat 312](https://github.com/KohaSuomi/Koha/assets/73887264/c999a2c2-6434-446e-8c88-864cc9a38172)
![2023kuvat 313](https://github.com/KohaSuomi/Koha/assets/73887264/d9b7c71c-ff75-43b4-bdde-95adcdbd0cb0)

**Comment by AnneliO** [comment]
Testasin next-kannassa ja minusta tätä ongelmaa ei esiinny enää siellä. Versionvaihtoon on muutama kuukausi, joten riittäisikö, että korjaus tulee siinä yhteydessä? :)

**Comment by pknuuti** [comment]
Onko nextillä päällä samat CSS:t jotka ehkä vaikuttaa tuohon näkymään tuotannossa? Jos se on vain siitä kiinni, jaksamme odottaa versionvaihtoon saakka.

**Comment by AnneliO** [comment]
Poistin nyt vielä outi-testillä kaikki intranetusercss:t ja intranetuserjs:t eikä niillä ollut vaikutusta noiden nappien väreihin ja näkyvyyteen, joten ongelma ei johdu niistä. Ongelma varmaan siis huomattu myös yhteisössä ja tehty korjaus sinne.

**Comment by pknuuti** [comment]
Hyvä juttu, suljen siis tämän tiketin. Kiitos Anneli.
