### ISSUE TITLE
Vaara: Osittain maksaminen ongelmana

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1078]
### Mikä vikana?

Vaarassa on käytössä maksujen maksaminen myös osittain eli asiakkaan ei ole pakko maksaa koko velkasaldoa kerralla. Nyt on havaittu ongelma maksujen maksamisessa Joensuun pääkirjaston Ceepos-kassalla. Kun asiakkaalla on maksuja 3,90 euroa ja asiakas haluaa maksaa vain 2 euroa, merkitään 2.00 euroa sekä Maksettava summa että Tarjottu rahamäärä -laatikoihin. Kuitenkin kassalle menevä summa on 2,60 euroa. Tämä pitäisi saada korjattua näyttämään oikeaa summaa.

**Comment by AnneliO** [comment]
Tätä testattiin myös Oulussa niin, että valittiin yksi 1.00 € maksu maksettavaksi. Maksettava summa ja Tarjottu rahamäärä -kohtiin laitettiin 0.50 € ja vietiin summa Ceepos-kassaan. Sitten käytiin katsomassa Ceepos-kassassa, mitä sinne on välittynyt. Summa oli 0.50 €, kuten pitää.

**Comment by AnneliO** [comment]
Testasimme Pirliin kanssa vielä niin, että veimme kaikki asiakkaan maksut eli 10.70 € maksettavaksi ja merkitsimme Maksettava summa ja Tarjottu rahamäärä -kohtiin 0.50 € ja veimme maksun Ceepos-kassaan. Sinne oli mennyt oikea summa 0.50 €.

**Comment by emta001** [comment]
Ja tapahtuuko tätä muilla summilla kuin 2 eurolla? Entä jos summa maksettu summa on yli 2,6?

**Comment by emta001** [comment]
Niin ja koskeeko ongelma vain yhtä asiakasta vai kaikkia asiakkaita?

**Comment by lmstrand** [comment]
Lokien mukaan tänään 12:20 tehty maksutapahtuma 2 eurolle on epäonnistunut eikä ceepokselta ole tullut kuittausta kohaan. Silloin maksun olisi pitänyt jäädä kuittautumatta asiakkaan maksuista, jos noin tapahuu.

**Comment by pknuuti** [comment]
Testattiin asiakas id1093189 maksuilla, jotka nyt on poistettu kokonaan. Emme kuitanneet sitä Ceepoksessa, koska summa näkyi kassaohjelmassa väärin.
Testasin nyt omalla testikortillani id10979913, jolla on maksuja 18,70 euroa. Yritin maksaa 5 euroa, mutta maksu ei suostunut menemään kassaan muuten kuin 18,70 summana. 
Tämä on nyt oikea ongelma, joten ottaisitteko Vaarasta pois päältä tuon painikemuutoksen (eli käytännössä se rivi jossa on JOE_JOE pitää poistaa IntranetUser JS:stä?)

**Comment by emta001** [comment]
> Testattiin asiakas id1093189 maksuilla, jotka nyt on poistettu kokonaan. Emme kuitanneet sitä Ceepoksessa, koska summa näkyi kassaohjelmassa väärin. Testasin nyt omalla testikortillani id10979913, jolla on maksuja 18,70 euroa. Yritin maksaa 5 euroa, mutta maksu ei suostunut menemään kassaan muuten kuin 18,70 summana. Tämä on nyt oikea ongelma, joten ottaisitteko Vaarasta pois päältä tuon painikemuutoksen (eli käytännössä se rivi jossa on JOE_JOE pitää poistaa IntranetUser JS:stä?)

Kävin kommentoimassa js-rimpsun pois.

**Comment by pknuuti** [comment]
Ei noin! Nyt hävisi koko Ceepos-kassayhteys. Jos ei muu auta niin entinen js takaisin.

**Comment by emta001** [comment]
> Ei noin! Nyt hävisi koko Ceepos-kassayhteys. Jos ei muu auta niin entinen js takaisin.

Joo miun moka, pahoittelut. Nappi on palautettu paikalleen.

**Comment by emta001** [comment]
Tarkastelin lokeja lisää, asiakkaan 1093189 maksusta siellä näkyy seuraavaa:

```
[2024/02/14 12:12:47] [INFO] Payments received: $VAR1 = [
  {
    'office' => '15',
    'borrowernumber' => '1093189',
    'amountoutstanding' => '2.00',
    'accountlines' => '2054076,2044110,2041076'
  }
];
```

Ja asiakkaan 10979913:

```
[2024/02/14 13:54:55] [INFO] Payments received: $VAR1 = [
  {
    'amountoutstanding' => '5.00',
    'accountlines' => '1883658,1883659,1961692,1883660,1915418,1883657,1894879,1894882,1894884',
    'office' => '15',
    'borrowernumber' => '10979913'
  }
];
```

Eli vaikuttas sille, että Kohasta kyllä lähtee maksettava summa ihan semmoisena kuin se on sieltä laitettu menemään. Sitä miksi kassan päässä sitten tulee väärä summa ei kyllä meidän lokeista taida selvitä. Joten tässä on ehkä oltava yhteydessä myös Ceepokseen.

**Comment by pknuuti** [comment]
Testataan asiakasid:llä 10979913

**Comment by emta001** [comment]
Lokin sisältö testimaksun osalta:

```
[2024/02/21 10:12:07] [INFO] Payments received: $VAR1 = [
  {
    'amountoutstanding' => '15.00',
    'office' => '15',
    'borrowernumber' => '10979913',
    'accountlines' => '1883658,1883659,1961692,1883660,1915418,1883657,1894879,1894882,1894884'
  }
];
[2024/02/21 10:12:08] [INFO] Sent payment: $VAR1 = {
  'ApiVersion' => '2.0',
  'Id' => 'B8CA6DE143FD04453BF96198',
  'NotificationAddress' => 'https://vaara.koha-suomi.fi/api/v1/contrib/kohasuomi/payments/ceepos/report',
  'Office' => '15',
  'Source' => 'KOHA',
  'Hash' => '036b1fbac4bc1ed975110b4297bb264360af57138b19c6f6abf3fdedb460a886',
  'Products' => [
    {
      'Code' => '5100',
      'Price' => 280,
      'Description' => 'Inkerin romaani / 17.11.2022 23:59'
    },
    {
      'Description' => 'Jouten : 17.11.2022 23:59',
      'Code' => '5100',
      'Price' => 330
    },
    {
      'Price' => 400,
      'Code' => '5140',
      'Description' => 'Kaukolaina'
    },
    {
      'Description' => 'Kreuzberg : 17.11.2022 23:59',
      'Price' => 330,
      'Code' => '5100'
    },
    {
      'Description' => 'Kuvittelen sinut vierelleni / 31.01.2023 23:59',
      'Code' => '5100',
      'Price' => 60
    },
    {
      'Code' => '5100',
      'Price' => 330,
      'Description' => 'MurhenÃ¤ytelmÃ¤ / 17.11.2022 23:59'
    },
    {
      'Description' => 'Mustat nuotit : 13.12.2022 23:59',
      'Price' => 30,
      'Code' => '5100'
    },
    {
      'Description' => 'PimeÃ¤n piiri : 13.12.2022 23:59',
      'Price' => 30,
      'Code' => '5100'
    },
    {
      'Price' => 30,
      'Code' => '5100',
      'Description' => 'Viimeiset runonlaulajat / 13.12.2022 23:59'
    }
  ],
  'Description' => '#B8CA6DE143FD04453BF96198',
  'Mode' => 2
};
[2024/02/21 10:12:52] [INFO] Report received: $VAR1 = {
  'Id' => '2C4DCFC983F9F7A44D895F72',
  'Hash' => '88c4dbb3083a9085614f1248ef35488d51d9c31b699c8f0a63be9aa03cdc9514',
  'Status' => 0
};
[2024/02/21 10:13:22] [INFO] Payments received: $VAR1 = [
  {
    'borrowernumber' => '10979913',
    'accountlines' => '1883658,1883659,1961692,1883660,1915418,1883657,1894879,1894882,1894884',
    'office' => '15',
    'amountoutstanding' => '15.00'
  }
];
[2024/02/21 10:13:23] [INFO] Sent payment: $VAR1 = {
  'Description' => '#4BA66328FD09D866BA14887E',
  'Mode' => 2,
  'Products' => [
    {
      'Description' => 'Inkerin romaani / 17.11.2022 23:59',
      'Code' => '5100',
      'Price' => 280
    },
    {
      'Description' => 'Jouten : 17.11.2022 23:59',
      'Price' => 330,
      'Code' => '5100'
    },
    {
      'Description' => 'Kaukolaina',
      'Code' => '5140',
      'Price' => 400
    },
    {
      'Code' => '5100',
      'Price' => 330,
      'Description' => 'Kreuzberg : 17.11.2022 23:59'
    },
    {
      'Code' => '5100',
      'Price' => 60,
      'Description' => 'Kuvittelen sinut vierelleni / 31.01.2023 23:59'
    },
    {
      'Description' => 'MurhenÃ¤ytelmÃ¤ / 17.11.2022 23:59',
      'Code' => '5100',
      'Price' => 330
    },
    {
      'Price' => 30,
      'Code' => '5100',
      'Description' => 'Mustat nuotit : 13.12.2022 23:59'
    },
    {
      'Description' => 'PimeÃ¤n piiri : 13.12.2022 23:59',
      'Code' => '5100',
      'Price' => 30
    },
    {
      'Description' => 'Viimeiset runonlaulajat / 13.12.2022 23:59',
      'Code' => '5100',
      'Price' => 30
    }
  ],
  'NotificationAddress' => 'https://vaara.koha-suomi.fi/api/v1/contrib/kohasuomi/payments/ceepos/report',
  'Id' => '4BA66328FD09D866BA14887E',
  'Office' => '15',
  'Source' => 'KOHA',
  'Hash' => '0a47c0463393cfb9ad38d3258257e179c87f3eabc95fc2ee9204f79a58c2c1db',
  'ApiVersion' => '2.0'
};
[2024/02/21 10:13:35] [INFO] Report received: $VAR1 = {
  'Status' => 0,
  'Hash' => '2b98bf69ef41096cebf1f581e1e8fbb0b692166d443cd4c6c37f33fece3d92a1',
  'Id' => 'B8CA6DE143FD04453BF96198'
};
[2024/02/21 10:15:10] [INFO] Report received: $VAR1 = {
  'Reference' => '91434',
  'Hash' => '0ec3b9a8178a7cb372951e42b3a9fc56a52da8e4acaf5321835fbd441eeb8a36',
  'Id' => '4BA66328FD09D866BA14887E',
  'Status' => 1
};

```

Eli sieltä on tullut 15 euron maksu ja lokeille on kirjautunut kaksi maksutapahtumaa, eka klo 10:12:07 ja toinen klo 10:13:22.

**Comment by pknuuti** [comment]
Muuten hyvä, mutta asiakkaan maksuissa näkyy maksettuna 18,20! Kummassa siis vika, Kohassa vai Ceepoksessa?
![2023kuvat 321](https://github.com/KohaSuomi/Koha/assets/73887264/d62c28d5-cdca-4b5f-897a-bfdaaa22242c)

**Comment by emta001** [comment]
Kannassa näkyy tuo maksu näin:

```
MariaDB [vaaraprod]> select * from accountlines where accountlines_id = 2083127\G
*************************** 1. row ***************************
  accountlines_id: 2083127
         issue_id: NULL
   borrowernumber: 10979913
       itemnumber: NULL
             date: 2024-02-21 10:15:10
           amount: -18.200000
      description: 
 credit_type_code: PAYMENT
  debit_type_code: NULL
    credit_number: NULL
           status: NULL
     payment_type: 15
amountoutstanding: 0.000000
        timestamp: 2024-02-21 10:15:10
             note: 4BA66328FD09D866BA14887E
       manager_id: 11005415
      register_id: NULL
        interface: api
       branchcode: JOE_JOE
```
Tää on siis napannut tuohon maksuun 4BA66328FD09D866BA14887E. Näyttäs nyt sille, että maksu on lähtenyt kyllä sinne kassan suuntaan oikein, mutta palannut sitten vääränä takaisin.

**Comment by pknuuti** [comment]
CPU vastasi aikaisemmin näin: "Ensimmäinen kuva on ilmeisesti Kohasta ja toinen kuva on Ceeposista. Kuten Ceeposista otetussa kuvakaappauksessa näkyy, niin summa siirtyy Kohasta Ceepokseen kokonaisuudessaan eli liittymä ei tuo Kohasta tuota osamaksusummaa kassalle. Vika on silloin Kohan päässä, joten oletteko sinne yhteydessä."
Mutta nythän summa (15 e) näyttää menneen Ceeposiin (?) oikein, mutta Kohan päässä näyttää veloittaneen koko maksun eli 18,20 e. En ymmärrä varsinkaan sitä, että kaikki osamaksut eivät käyttäydy samalla tavalla.

**Comment by emta001** [comment]
> CPU vastasi aikaisemmin näin: "Ensimmäinen kuva on ilmeisesti Kohasta ja toinen kuva on Ceeposista. Kuten Ceeposista otetussa kuvakaappauksessa näkyy, niin summa siirtyy Kohasta Ceepokseen kokonaisuudessaan eli liittymä ei tuo Kohasta tuota osamaksusummaa kassalle. Vika on silloin Kohan päässä, joten oletteko sinne yhteydessä." Mutta nythän summa (15 e) näyttää menneen Ceeposiin (?) oikein, mutta Kohan päässä näyttää veloittaneen koko maksun eli 18,20 e. En ymmärrä varsinkaan sitä, että kaikki osamaksut eivät käyttäydy samalla tavalla.

Mitkä kuvat sinne CPU:lle on laitettu?

**Comment by emta001** [comment]
Sovittiin niin, että Lari käy illalla vaihtamassa Vaaraan sen vanhan js-rimpsun. Sen jälkeen pitää testata, että toimiiko osamaksut kun:
1) maksetaan osittain vain yksittäinen maksurivi
2) maksetaan osittain kaikki maksurivit

Varmistetaan tällä se, että onko vika uudessa rimpsussa sekä se, toimiiko kaikkien maksurivien osittainen maksaminen nyt oikein.

**Comment by emta001** [comment]
> > ```
> > 2. maksetaan osittain kaikki maksurivit
> > ```
> 
> Tässä vois tehdä vielä silleen, että se maksettava summa ei vastaa mitään yksittäistä maksuriviä summaltaan tai kahden rivin yhteissummaa. Eli jos esim. maksettavana on summat 1.00, 3.00 ja 5.00, niin maksaa summan 2.00, mutta ei 4.00, koska se on 1.00 ja 3.00 summa.

Kokeilkaa myös sitä, että maksatte sekä tasasummia (1.00) että sentillisiä summia (1.20).

**Comment by pknuuti** [comment]
Nyt ei onnistu osittain maksaminen kassaan asti, Kohasta osamaksu kuittaantuu.

**Comment by AnneliO** [comment]
> Nyt ei onnistu osittain maksaminen kassaan asti, Kohasta osamaksu kuittaantuu.

Siis maksu ei mene kassaan, mutta se silti kuittaantuu Kohassa? Vai ymmärränkö nyt väärin? :)

**Comment by pknuuti** [comment]
Juu, ei mene kassaan automaattisesti eli se pitää sinne itse näpytellä. Sain lisätiedon lehtisalista, siellä ongelma ollut jo pari päivää. Ei mulle asti ole tieto kulkenut. Ja koskee siis myös koko summan maksaneita, ei pelkästään osamaksuja.

**Comment by pknuuti** [comment]
Päivitys: osamaksuongelma on siis vain pääkirjaston 2. kerroksessa, kokonaan maksaminen toimii kassaan asti. 1. kerroksessa ei toimi koko summan maksaminenkaan kassaan asti. Saman talon kassoissa on siis erilainen ongelma, outoa. Tieto ongelmista vaan ei kulje.

**Comment by lmstrand** [comment]
Tuotantoon vaihdettu Wikin versio js-rimpsusta.
```
/// ALKU ///

/// Ceepos-maksu -napin lisäys ///
/// Napin taustavärinä ja reunavärinä keltainen? #ffc32b ///

$(document).ready(function() {
  let ceeposBranches = ['JOE_JOE'];
  if (ceeposBranches.includes($("#logged-in-info-full .logged-in-branch-code").text())) {
    $("#payfine .action, #payindivfine .action").find("input").after('<input type="button" id="CeeposMaksu" class="btn btn-primary" style="margin-left:3px;"  value="Ceepos-maksu"  onclick="setCeeposPayment($(this))"/>');
   if(localStorage.getItem('ceeposOffice')){
     $('#payment_type').val(localStorage.getItem('ceeposOffice'));
   }
  }
  $('#paycollect').hide();
  $("#circmessages a[href*='/cgi-bin/koha/members/paycollect.pl'").hide();
  $("#patron_messages a[href*='/cgi-bin/koha/members/paycollect.pl'").hide();
});
function setCeeposPayment(element) {
  var ceeposOffice = $('#payment_type').find(":selected").val();
  localStorage.setItem('ceeposOffice', ceeposOffice);
  	let payments;
  	let borrowernumber;
    if($("#payindivfine").find("#pay_individual").val() == 1) {
      borrowernumber = $("#payindivfine").find("#borrowernumber").val();
       payments = [{'borrowernumber': $("#payindivfine").find("#borrowernumber").val(), 'accountlines_id': $("#payindivfine").find("#accountlines_id").val(), 'description': $("#payindivfine").find("#description").val(), 'amountoutstanding': $("#payindivfine").find("#amountoutstanding").val(), 'payment_type': $("#payindivfine").find("#debit_type_code").val(), 'office': ceeposOffice}];
} else {
  	borrowernumber = $("#payfine").find("#borrowernumber").val();
  	payments = [{'borrowernumber': $("#payfine").find("#borrowernumber").val(), 'accountlines': $("#payfine").find("#selected_accts").val(), 'amountoutstanding': $("#payfine").find("#collected").val(), 'office': ceeposOffice}];
}
    $.ajax({
     url: "/api/v1/contrib/kohasuomi/payments/ceepos", 
     type: "POST",
     dataType: "json",
     contentType: "application/json; charset=utf-8",
     data: JSON.stringify(payments),
     beforeSend: function() {
        $("#CeeposMaksu").attr("disabled", true);
        alert("Maksu lähetetty, käsittele kassassa!");
     },
     success: function (result) {
         location.href = '/cgi-bin/koha/members/boraccount.pl?borrowernumber='+borrowernumber;
      },
      error: function (xhr, status, error) {
          $("#CeeposMaksu").attr("disabled", false);
          alert(JSON.parse(xhr.responseText).error);
      }
   });
}

///LOPPU ///
``

**Comment by pknuuti** [comment]
Ainakin lainausosaston kassa toimii nyt oikein myös osamaksujen kohdalla. Alakerran kassassa oli joku muu vika, jonka CPU sai korjattua eilen.

**Comment by lmstrand** [comment]
Ceepos-rimpsua ylläpidetään nykyisin pluginissa itsessään, eikä erillistä intranetUserJS-rimpsua enää tarvitse. Rikkoutunut rimpsu korjattu sinne. Tuotannot siirtyneet käyttämään pluginia.
