### ISSUE TITLE
Uusi SIP-tunnus

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1082]
### Tukipyyntö

Tiedot lähetetty support-postiin. Asennus on tiistaina 20.2., joten jos tunnuksen saisi lisättyä vaikka jo tänään niin se olisi hyvä.

**Comment by paxed** [comment]
Tämä lisätty, tulee voimaan kun sip-palvelimet käynnistyvät seuraavan kerran yöllä.

**Comment by ajrajala** [comment]
Kiitos!
