### ISSUE TITLE
Lappi: Virheellisiä tietueita

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha#1083]
### Mikä vikana?

Lapissa on joukko virheellisiä tietueita (pääosin osakohteita), joissa auktoriteettilinkitykset ja/tai emo-osakohdelinkitykset ovat rikki. Indeksointi kompastuu näihin:

Cannot determine authority type for record: 4154 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4155 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4156 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4157 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4158 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4159 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4160 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4161 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4162 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4163 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4164 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4165 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4166 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 4167 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 145630 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270621 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270622 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270623 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270626 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270627 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270674 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270675 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.
Cannot determine authority type for record: 270676 at /home/koha/Koha/Koha/SearchEngine/Elasticsearch.pm line 567.

Esimerkiksi listan ensimmäinen (biblionumber 4154) sisältää 773-kentän, jossa t-osakentässä on 'LAULAJAN KIRJA'. 773w kentässä on kuitenkin biblionumber, joka osoittaa tietokannassa tietueeseen "Minä kerron, piirrä sinä /". Kun klikkaa emon linkkiä liittymässä niin tuloksena on "Lintuharrastuskirja /" (biblionumber 1551). Otappa tästä nyt selvää... "LAULAJAN KIRJA" nimekkeistä tietuetta ei Lapin kannassa isolla kirjoitettuna ole olemassakaan. Pienellä kirjoitettuja löytyisi muutama kappale sekä aktiivisesta taulusta että poistetuista, mutta niiden biblionumberit ovat kyllä ihan muuta.

Osassa tietueita 773w -kenttä sisältää jotain ihan vallan muuta kuin biblionumberin (esimerkiksi <subfield code="w">M042088043</subfield>). M042088043 ei voi Kohassa olla biblionumber, koska biblionumber-kenttä on numeerinen (ei voi olla M:ää alussa).

Tietue 145630 (nimeke "Oskar Merikanto ja hänen aikansa /") ei ole osakohde, mutta ilmeisesti jokin sen auktoriteettilinkityksistä on rikki.

### Mitä pitäisi tapahtua

Osakohteiden pitäisi olla kiinni oikessa emoissansa biblionumberin perusteella ja auktoriteettiviittauksille pitäisi löytyä vastine auktoriteettirekisteristä. Virheelliset emolinkit ja auktoriteettiviittaukset pitäisi siis korjata, mutta ainakin osakohteiden tapauksessa suosittelisin ehkä poistamaan koko osakohteet ja tekemään ne tarvittaessa uudelleen.

### Kuinka toistaa ongelma/asia

Tietueisiin pääsee käsiksi varmaankin helpoiten suorilla linkeillä: https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=[biblionumber]. Ongelman toistamiseksi voi mennä oikein muotoillulla osoitteella tutkailemaan tietueen MARC:ia, kliksuttelemaan emolinkkiä ja ihmettelemään että mihinkäs sitä nyt päädyttiinkään.

### Selain

```markdown
Tietokantajuttu, ei ole selainasia.
```

**Comment by LeenaKinnunen** [comment]
Selvä, korjataan nämä tietueet mahdollisimman pian.

**Comment by LeenaKinnunen** [comment]
Tietueet on korjattu.

**Comment by johannaraisa** [comment]
@CodoDerDritte Suljetko tämän?
