### ISSUE TITLE
Automaattien lainausviestiparin 11-12 vastauksessa ei tule AH-kentässä eräpäivää, mikäli ”no block” -asetuksessa lähetetään ”Y”

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1084]
### Mikä vikana?

Lainaukseen käytettävässä SIP2-viestiparissa 11-12 on OUTI-kirjastoissa havaittu muutos versiopäivityksen 16.-17.5.2023 jälkeen.

Lyngsoe Systemsin Kirjakaapeissa ("LibCabinet") käytetään yleisesti asetusta `"no block" = ”Y” (11<SC renewal policy><no block>)`. Näin jokainen teos annettaisiin lainaan, vaikka siitä olisi varaus eri henkilöllä.

"no block":
1-char, fixed-length field: Y or N. This field notifies the ACS that the article was already checked in or out while the ACS was not on-line.  When this field is Y, the ACS should not block this transaction because it has already been executed. The SC can perform transactions while the ACS is off-line. These transactions are stored and will be sent to the ACS when it comes back on-line.

Ennen versiopäivitystä 12-paluuviestissä on tullut eräpäivä AH-kentässä normaalisti. Versiopäivityksen jälkeen tilanne muuttui. Jos lähetetään 11-viestissä "no block" = ”Y”, niin AH-kenttä tulee tyhjänä, vaikka Koha ilmoittaa lainauksesta tai uusinnasta:

`Y <response>121YNY20240201 153159AOOUPK|AA564A****|AB564N03123178|AJVillitalo /|AH|AFItem already checked out to you: renewing item.|CK001|</response>`

Lainalla on myös Kohasta katsottuna eräpäivä, mutta AH-kentässä se ei tule.

Jos 11-viestissä lähetetään "no block" = ”N”, eräpäivä tulee AH-kentässä normaalisti:

`N <response>121YNY20240201 153338AOOUPK|AA564A****|AB564N03123178|AJVillitalo /|AH20240229 235900|AFItem already checked out to you: renewing item.|CK001|</response>
`
Tämä ei riipu esim. SC renewal policyn asetuksesta (Y tai N), vaan nimenomaan tuo "no block" -asetus on syyllinen. Automaattikaan ei voi tälle mitään, kun kenttä tulee tyhjänä. Testitapauksessa oli sattumalta nide joka oli jo lainassa testiasiakkaalla, mutta sama toistuu, vaikka nide ei olisikaan lainassa ennestään.

AH-kenttää käytetään automaateissa lainan eräpäivän näyttämiseen automaatilla ja eräpäivän tulostamiseen kuitille, joten tähän pitäisi saada korjaus.

**Comment by Thoriell** [comment]
Näköjään GitHub siivoaa kulmasulkeita ja niiden välissä olevia juttuja pois. Testaanpa saako ne säilymään koodi-merkattuna:

"Lyngsoe Systemsin Kirjakaapeissa ("LibCabinet") käytetään yleisesti asetusta "no block" = ”Y” `(11<SC renewal policy><no block>)`. Näin jokainen teos annettaisiin lainaan, vaikka siitä olisi varaus eri henkilöllä."

```
Y <response>121YNY20240201 153159AOOUPK|AA564A****|AB564N03123178|AJVillitalo /|AH|AFItem already checked out to you: renewing item.|CK001|</response>

N <response>121YNY20240201 153338AOOUPK|AA564A****|AB564N03123178|AJVillitalo /|AH20240229 235900|AFItem already checked out to you: renewing item.|CK001|</response>

```

**Comment by lmstrand** [comment]
Yhteisössä on jo korjaus tähän.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32934
Onnistuisiko teidän testata tuota korjausta testillä/nextillä? Ilmoitelkaa, niin käyn laittamassa korjauksen paikalleen.

**Comment by Thoriell** [comment]
Emme kovin helposti voi testata, kun tuo ”no block” -asetus on vain Kirjakaapin ohjelmistossa (LibCabinet). Tästä ei meillä ole asennuspakettiakaan, kun on omanlaisensa laite. Sitä ainoaa laitettamme tuotannossa emme mielellään menisi härveltämään testille, vaatisi sinne paikan päälle jonkun, ja tunnusten virittelyn testille ym.

Voisiko tätä testata suoraan testille/nextille SIP2-rajapintaan, kuten ongelmaa selvitellessä?

**Comment by lmstrand** [comment]
Onnistuuhan se, jos testisip-palvelin suostuu vastaanottamaan vielä noita vanhoja viestejä, joilla kokeiltiin. Ilmoittelen miten kävi/ jos tarvitsen apua uuden testitapauksen luomiseksi.

**Comment by lmstrand** [comment]
Lappi-testillä sanomaan ilmestyi AH-kenttään korjauksen tuonnin jälkeen eräpäivä, joka oli tyhjänä ennen korjausta:

<response>121YNY20240219 124533AOROPK|AA66666666|AB698N23042801531|AJLeonardo da Vinci ja kissa ja koira
		/|AH20240229 000000|AFItem already checked out to you: renewing item.|</response>

Näyttää siis toimivan. Viedään muutos tuotantoon.

**Comment by lmstrand** [comment]
Voisitteko vielä testata, ettei mikään mennyt rikki testillä muiden toimintojen osalta? Käynnistin sip-palvelimen outi-testillä uusiksi yhteisön korjauksen koodin kera. Ominaisuus saadaan mukaan seuraavaan tiistain päivitykseen aikaisintaan, niin tässä on nyt aikaa varmistaa että korjaus pelaa muiltakin osin.

**Comment by Thoriell** [comment]
Testataan keskiviikkona tai torstaina kun ollaan paikan päällä testiautomaatin kanssa.

**Comment by lmstrand** [comment]
Ok kiitos.

**Comment by Thoriell** [comment]
Testasimme nyt testiautomaatilla perusjutut eli lainaus, palautus, lainojen uusinta, omien tietojen katselu ym. eikä huomattu mitään ongelmia. Mielestämme tämän voi viedä tuotantoon.

**Comment by lmstrand** [comment]
Korjaus viety ksdev/ks-0043-K22-15-SIP2-branchiin.

**Comment by piiaseme** [comment]
Suljen tiketin.

**Comment by lmstrand** [comment]
Korjaus viety myös 23-versioon.  Branchissa ksdev/ks-0043-K23-15-SIP2.

**Comment by lmstrand** [comment]
Ilmeisesti tätä yhteisön korjausta ei ole tuotu tähän 23-versioon, vaikka tiketissä niin mainitaan. Yhteisössä tiketti on jäänyt roikkumaan ja tulee puuttumaan myös versionvaihdossa. Kokeilen tuoda korjauksen 24-versioon.

**Comment by lmstrand** [comment]
Korjaus on viety nexetille, mutta testaaminen taitaa olla devaajien vastuulla.

**Comment by lmstrand** [comment]
Tuodaan tämä korjaus myös tuotantoon.

**Comment by Thoriell** [comment]
Emme huomanneet tuotannossa mitään ongelmia normaalitoiminnoissa, eli siltä osin puolestamme kunnossa. "no block" -asetustahan emme pysty testaamaan, mutta muut perustoiminnot ok!

**Comment by piiaseme** [comment]
Tämä lienee nyt valmis, joten suljen tiketin. Avataan uudelleen, jos olin liian hoppuinen.
