### ISSUE TITLE
Vaaran Ceepos-kassan ongelmat

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1091]
### Mikä vikana?

Joensuun pääkirjaston Ceepos-kassan osittaiset maksut epäonnistuvat satunnaisesti, välillä menee ihan oikein. Tämä pitäisi saada toimimaan joka kerta oikein.

**Comment by pknuuti** [comment]
Testattu mm. asiakasid10979913

**Comment by AnneliO** [comment]
Onko tämä samaa ongelmaa kuin tiketissä #1078?

**Comment by pknuuti** [comment]
No on! En muistanut, että tästä oli jo tiketti enkä heti löytänyt haulla. Suljen tämän.
