### ISSUE TITLE
Kirkes: tietojen tuonti TäTistä paikalliskantaan ei toimi osakohteellisilla CD-levyillä

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1093]
### Tukipyyntö

Välitän kuvailijan havaitseman ongelman, koska en itse keksinyt mistä se voisi johtua: "Järvenpäässä huomattiin eilen, että tietojen tuonti TäTistä paikalliskantaan ei toimi osakohteellisilla CD-levyillä. Kuvailua odottavilla hankintatietueilla kuvailu- ja nidetiedot aukeavat normaalisti muokattaviksi Kirkesin paikalliskannassa, mutta kun valmiit Kirjastopalvelun kuvailutiedot TäTistä ovat valuneet meidän tietueeseen, sen jälkeen sekä niteen että tietueen muokkaus näyttää tyhjää. Näkymä on siis aivan blanco ja jos tässä vaiheessa tallentaa, hankintatiedot korvautuvat tyhjällä eli katoavat kokonaan. Marc-esikatselussa (esim. perustiedot) tiedot näkyvät.
 
Tässä joitakin tietuenumeroita: 1613701, 1609586, 1614248, 1613749, 1613701, joilla tämä havaittiin. Kirja-tietueen valutuksessa ei ollut ongelmaa.
 
Huomasin, että Kirkesin raporttiliitännäisiin on ilmestynyt siirtoraportin lisäksi Tietuesiirtäjä-raportti, mutta se näyttää tyhjää.
 
Käytin Firefox-selainta."

**Comment by AnneliO** [comment]
Näillä tietueilla on käytössä kuvailupohjana CDA-pohja, jollaista Kirkeksessä ei ole olemassa. Tutkin lisää.

**Comment by AnneliO** [comment]
select * from biblio where biblionumber in ('1609586', '1614248', '1613749', '1613701')

**Comment by AnneliO** [comment]
Tuo CDA taitaa tulla Auto Framework Code -liitännäisen määrityksistä

```
--
- 000/06 + 000/07:
   a+s: SER
- 000/06:
   a: KIR
   c: NUO
   e: MAP
   g: VR
   j: CDA
   r: LAU
   t: KIR
- 008/26 + 000/06:
   g+m: KP
```

**Comment by ElinaUotila** [comment]
Vähän arvelinkin, että se liittyy tuohon liitännäiseen.
