### ISSUE TITLE
Voiko saada palauttamaan tietueen ennalleen, kun sen päälle on valunut konvertoimaton ISBD-tietue?

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1096]
### Tukipyyntö

Vaskissa RDA-tietueiden päälle on valunut konvertoimattomia ISBD-tietueita. Valuminen johtui luultavasti siitä, että TäTin vanhemmilta tietueilta poistettiin 21.2.2024 942c-kentästä vanhentuneita aineistotyyppiarvoja, jotka estivät aineistotyypin muodostumisen oikein paikalliskannoissa.

Onko tarvittaessa mahdollista palauttaa tietueita entiseen muotoonsa?

**Comment by AnttHeik** [comment]
Olinkin kertonut päivämäärän väärin eli kyseessä keskiviikko 21.2.

**Comment by AnneliO** [comment]
Kuvailutiedot ovat kyllä tallessa action_logs-taulussa tällaisena möykkynä:

<html><body>

  | biblio BEFORE=>LDR 02970nam a22006134i 4500 001     7439554 003     FI-BTJ 005     20240219070600.0 008     240216t20242024fi \|\|\|\|       \|0\| 0dfin\|c 020    _a978-952-5783-88-9        _qpehmeäkantinen 035    _a(FI-BTJ)7439554 040    _aFI-BTJ        _bfin        _erda        _dFI-NL 041 0  _afin 084    _a86.13        _2ykl 084    _a74.92        _2ykl 130 0  _aSarjakuvan paikka,        _lsuomi 245 10 _aSarjakuvan paikka :        _bnykysarjakuva suomalaisen taiteen kentällä /        _c[vastaava toimittaja:] Ville Hänninen ; julkaisija: Kutikuti ry. 250    _a1. painos. 264  1 _a[Helsinki] :        _bKutikuti ry,        _c[2024] 264  3 _bTallinna Raamatüttrükikoda 264  4 _c©2024 300    _a112 sivua :        _bkuvitettu ;        _c19 cm 336    _ateksti        _btxt        _2rdacontent 337    _akäytettävissä ilman laitetta        _bn        _2rdamedia 338    _anide        _bnc        _2rdacarrier 500    _aEsseet: Ilan Manouach, Tommi Musturi ja Aarnoud Rommens ; esseiden käännökset (Manouach/Rommens): Eeva Talvikallio. 546    _aKaksi artikkelia käännetty englannin kielestä. 648  7 _a2020-luku        _2yso/fin        _0http://www.yso.fi/onto/yso/p6202062029 650  7 _asarjakuvataide        _2yso/fin        _0http://www.yso.fi/onto/yso/p38773 650  7 _asarjakuvat        _2yso/fin        _0http://www.yso.fi/onto/yso/p1148 650  7 _ataideala        _2yso/fin        _0http://www.yso.fi/onto/yso/p21183 650  7 _arahoitus        _2yso/fin        _0http://www.yso.fi/onto/yso/p1406 650  7 _aapurahat        _2yso/fin        _0http://www.yso.fi/onto/yso/p5436 650  7 _akustannustoiminta        _2yso/fin        _0http://www.yso.fi/onto/yso/p2045 650  7 _asarjakuvataiteilijat        _2yso/fin        _0http://www.yso.fi/onto/yso/p21601 650  7 _akoulutus        _2yso/fin        _0http://www.yso.fi/onto/yso/p84 650  7 _ataiteellinen työ        _2yso/fin        _0http://www.yso.fi/onto/yso/p9454 650  7 _atyöprosessit        _2yso/fin        _0http://www.yso.fi/onto/yso/p13504 650  7 _ahyödyntäminen        _2yso/fin        _0http://www.yso.fi/onto/yso/p11327 650  7 _atekoäly        _2yso/fin        _0http://www.yso.fi/onto/yso/p2616 650  7 _atutkimus        _2yso/fin        _0http://www.yso.fi/onto/yso/p183 650  7 _ataiteentutkimus        _2yso/fin        _0http://www.yso.fi/onto/yso/p3746 650  7 _akirjallisuudentutkimus        _2yso/fin        _0http://www.yso.fi/onto/yso/p1066 651  7 _aSuomi        _2yso/fin        _0http://www.yso.fi/onto/yso/p94426 700 1  _aHänninen, Ville,        _etoimittaja,        _ekirjoittaja.        _0(FI-ASTERI-N)000124442 700 1  _aManouach, Ilan,        _ekirjoittaja.        _0(FI-ASTERI-N)000220707 700 1  _aMusturi, Tommi,        _ekirjoittaja.        _0(FI-ASTERI-N)000124935 700 1  _aRommens, Aarnoud,        _ekirjoittaja. 700 1  _aTalvikallio, Eeva,        _ekääntäjä. 710 2  _aKutikuti (yhdistys),        _ekustantaja.        _0(FI-ASTERI-N)000158432 856 42 _qimage        _uhttps://sopimusasiakkaat.booky.fi/image.php?size=medium&id=9789525783889        _zKansikuva 856 42 _qtext        _uhttps://sopimusasiakkaat.booky.fi/description.php?ean=9789525783889        _zKuvaus 942    _cKIRJA        _6\| 74.92 999    _c2335988        _d2335988
-- | --



</body>
</html>

Mutta en osaa sanoa suoraan, pystyykö tuosta parsimaan jotenkin tiedot niin, että ne saa vietyä takaisin biblio-tauluihin.

**Comment by AnttHeik** [comment]
Tuosta ei varmaan saa muokattua / tallennettua sellaista Marcxml-tiedostoa, jollaisessa voi tuoda tietueita jostain toisesta kannasta?

**Comment by AnneliO** [comment]
> Tuosta ei varmaan saa muokattua / tallennettua sellaista Marcxml-tiedostoa, jollaisessa voi tuoda tietueita jostain toisesta kannasta?

Sitä juuri en tiedä, ainakaan vielä. :)

**Comment by johannaraisa** [comment]
Katsotaan saako tuosta lokista kaivettua sen ja muutettua takaisin marcxml-muotoon.

**Comment by johannaraisa** [comment]
Nyt on skripti mikä muuttaa lokin merkinnän marciksi ja tallentaa kantaan. Pitää vaan tietää mikä niistä action_logs-merkinnöistä halutaan palauttaa.

**Comment by AnttHeik** [comment]
Mainiota! Eli riittääkö jos ilmoittaa tietuenumerot vai pitääkö olla muitakin tietoja?

**Comment by johannaraisa** [comment]
> Mainiota! Eli riittääkö jos ilmoittaa tietuenumerot vai pitääkö olla muitakin tietoja?

Tietue numero ja sitten se lokin aika mihin halutaan palauttaa, ku siellä saattaa olla useampia muokkauslokimerkintöjä.

**Comment by AnneliO** [comment]
Valmis
