### ISSUE TITLE
Raporttipyyntö: Virheellisesti valuneet tietueet

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1097]
### Tukipyyntö

Tarvitaan tietueet, jotka valuivat tiistaina 21.2. aamupäivän aikana, riittää pelkät monografiat
Tietueista pitäisi erottaa ne, joissa tapahtui muutoksia joistakin näistä kentistä: 000/17, 084a, 100a, 110a, 245abnp, 336, 337, 338

Raportilla pitäisi näkyä näiden tietueiden
a.	tietuenumero
b.	aineistotyyppi 942c
c.	001-kentän arvo
d.	003-kentän arvo
e.	020a-kenttä (kaikki toistumat)
f.	024a-kenttä (kaikki toistumat)
g.	040a-kenttä (tarvitaan vanha ja uusi tieto, jos saa järkevästi näkyville)
h.	040d-kenttä
i.	084a-kenttä (tarvitaan vanha ja uusi tieto, jos saa järkevästi näkyville)
j.	tekijä (100a,110a,111a) (tarvitaan vanha ja uusi tieto, jos saa järkevästi näkyville)
k.	nimeke (245abnp) (tarvitaan vanha ja uusi tieto, jos saa järkevästi näkyville)

Jos muuttuneiden tietueiden erottelu ei onnistu, niin sitten käy kaikki tietueet.

### Jotain muuta?

Anneli on muokannut OUTIssa olevan raportin 616 pohjalta raportin: 743 Virheellisesti valuneet tietueet. Raportissa jo osa noista pyydetyistä tiedoista tulee tulokseen.
https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?phase=Run+this+report&reports=743&sql_params=%25&param_name=Kirjasto%7Cbranches%3Aall&limit=500

**Comment by piiaseme** [comment]
Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/1096

**Comment by AnneliO** [comment]
> Tietueista pitäisi erottaa ne, joissa tapahtui muutoksia joistakin näistä kentistä: 000/17, 084a, 100a, 110a, 245abnp, 336, 337, 338

Tämä voi olla hankala toteuttaa sql-raportilla, koska vertailtavat tiedot haetaan action_logs-taulusta sellaisesta kivasta tietomöykystä paikallistamalla ja poimimalla. Mutta voin yrittää miettiä vielä asiaa. :D

Juttelin perjantaina pikaisesti tästä Johannan kanssa ja hän arveli, että Tietuesiirtäjän raportille pystyisi ehkä tekemään jonkin rajauksen, jolla suodattaa näkyville tietueet, joissa on muutoksia tietyissä kentissä. Hän on kuitenkin tämän viikon lomalla, joten tämän toteutus mennee myöhemmäksi.

**Comment by AnttHeik** [comment]
> > Tietueista pitäisi erottaa ne, joissa tapahtui muutoksia joistakin näistä kentistä: 000/17, 084a, 100a, 110a, 245abnp, 336, 337, 338
> 
> Tämä voi olla hankala toteuttaa sql-raportilla, koska vertailtavat tiedot haetaan action_logs-taulusta sellaisesta kivasta tietomöykystä paikallistamalla ja poimimalla. Mutta voin yrittää miettiä vielä asiaa. :D

Ok, mietin sellaista, että ensiapuna voisi toimia pelkästään sekin, että saisi ainakin kaikki nuo mahdolliset 020- tai 024-toistumat näkymään raportille. Sillä saisi kiinni todennäköisesti suurimman osan väärin valuneista tietueista, koska niissä on ollut väärä ISBN- tai EAN-koodi aktivoitumisarvona, koska tietueella on useampi 020- tai 024-kenttä.

> 
> Juttelin perjantaina pikaisesti tästä Johannan kanssa ja hän arveli, että Tietuesiirtäjän raportille pystyisi ehkä tekemään jonkin rajauksen, jolla suodattaa näkyville tietueet, joissa on muutoksia tietyissä kentissä. Hän on kuitenkin tämän viikon lomalla, joten tämän toteutus mennee myöhemmäksi.

Tämä olisi kyllä hyvä idea.

**Comment by AnneliO** [comment]
> Ok, mietin sellaista, että ensiapuna voisi toimia pelkästään sekin, että saisi ainakin kaikki nuo mahdolliset 020- tai 024-toistumat näkymään raportille. Sillä saisi kiinni todennäköisesti suurimman osan väärin valuneista tietueista, koska niissä on ollut väärä ISBN- tai EAN-koodi aktivoitumisarvona, koska tietueella on useampi 020- tai 024-kenttä.

Toistumatkin ovat hankala löytää muuten kuin ottamalla mukaan tarpeeksi pitkästi merkkijonoa, jolloin ne tulee näkyviin. Silloin voi kyllä tulla ns. turhaakin tietoa eli ihan muun kentän tietoja, jos toistumaa ei olekaan.

**Comment by AnneliO** [comment]
Mutta katellaan, josko joku keksisi jotain. :D

**Comment by AnttHeik** [comment]
Joo, no löysin minä onneksi tuon vanhankin raportin perusteella jo joitakin tapauksia, kun tutki läpi ne luokat, joissa todennäköisimmin on moniviestimiä tai muita moniosaisia teoksia. Lisäksi vanhaa ja uutta luokkaa vertailemalla löytää jotain, mutta tietueita on niin paljon, että varmasti osa jää löytymättä.

**Comment by johannaraisa** [comment]
Mietin tuossa, että tallennetaan kaikki 020- ja 024-kentien esiintymät aktivoinnissa, sillä ainakin saisi estettyä valuminen väärään. Tuossa kun ei ole oikein tapaa selvittää mikä niistä on ns. oikea arvo, jos on kyseessä kokoelma jne.

**Comment by AnttHeik** [comment]
> Mietin tuossa, että tallennetaan kaikki 020- ja 024-kentien esiintymät aktivoinnissa, sillä ainakin saisi estettyä valuminen väärään. Tuossa kun ei ole oikein tapaa selvittää mikä niistä on ns. oikea arvo, jos on kyseessä kokoelma jne.

Ok, mitenkäs se toimisi sitten käytännössä? Hankintatietueissa ei taida yleensä olla kuin kuin yksi tunnus jossakin kentässä. Tulisiko aktivoituminen sitten muihin 020- ja 024-kenttiin sen jälkeen kun täydellinen tietue on valunut hankintatietueen päälle?

**Comment by johannaraisa** [comment]
> > Mietin tuossa, että tallennetaan kaikki 020- ja 024-kentien esiintymät aktivoinnissa, sillä ainakin saisi estettyä valuminen väärään. Tuossa kun ei ole oikein tapaa selvittää mikä niistä on ns. oikea arvo, jos on kyseessä kokoelma jne.
> 
> Ok, mitenkäs se toimisi sitten käytännössä? Hankintatietueissa ei taida yleensä olla kuin kuin yksi tunnus jossakin kentässä. Tulisiko aktivoituminen sitten muihin 020- ja 024-kenttiin sen jälkeen kun täydellinen tietue on valunut hankintatietueen päälle?

Miten editx osaa hoitaa tuon jos löytyy jo sama isbn, eikös se silloin mene päälle? Se kyllä vaihtaa aktivointiarvoa ja löytää parempia, nuo useammat esiintymät voisi laittaa vaikka pötköön siihen aktivointitauluun ja erottaa pilkulla.

**Comment by AnttHeik** [comment]
> Miten editx osaa hoitaa tuon jos löytyy jo sama isbn, eikös se silloin mene päälle? Se kyllä vaihtaa aktivointiarvoa ja löytää parempia, nuo useammat esiintymät voisi laittaa vaikka pötköön siihen aktivointitauluun ja erottaa pilkulla.

Joo, eikös se silloin osaa yhdistää tietueet, mutta olikohan niin, että se yhdisti ensimmäisen kenttätoistuman perusteella... @AnneliO varmaan muistaa paremmin, miten editx yhdistää tietueet :)

Mietin vielä, että jos on useampia kenttäesiintymiä, niin mitenkäs sitten käy, jos täydellistä tietuetta muokataan myöhemmin noiden 020- tai 024-kenttien osalta, jos on ollutkin vaikka niin, että jossakin kentässä on ollut virheellinen arvo tai kenttien toistumia lisätään jälkeen päin?

**Comment by johannaraisa** [comment]
Onko se ensimmäinen yleensä se oikea vaihtoehto? Etsimisenhän voisi sitten katkaista siihen, luulen että nyt se käy ne kaikki läpi ja viimeinen esiintymä aktivoituu.

**Comment by AnneliO** [comment]
EDItX tekee täsmäytyksen biblioitems-taulun isbn-, ean-sarakkeiden mukaan. Lisäksi yhdessä publishercode ja editionresponsibility -sarakkeiden tietoja verraten (kumpikin siis pitää täsmätä, jotta tulee osuma).  Muistelisin myös, että meillä on tehty muutos, että isbn/ean-sarakkeisiin viedään vain yksi arvo, vaikka niitä olisi tietueessa useampi. Näin saadaan täsmällisempi osuma.

**Comment by johannaraisa** [comment]
Tuollaista muistelin sen tekevän, sillä sinne biblioitemsiin voi tallentaan useamman esiintymän. Jos laitetaan se katkaisu, että otetaan vain ensimmäinen huomioon niin menisiköhän sillä?

**Comment by AnttHeik** [comment]
Kyllä se ensimmäinen on yleensä osuvin vaihtoehto, mutta valitettavasti ei ihan aina. 

Esim. tässä yhdessä OUTIn valumistapauksessa (OUTI-ID: 2135286) on kirja vaihtunut moniviestimeksi, koska kirjan päälle valuneessa moniviestimessä oli ensimmäisessä 020-kentän toistumassa kirjan ISBN ja toisessa CD-äänilevyn (TäTissä pelkkä kirjatietue: 1947242 ja moniviestin: 2012996), ja tämä on ihan normaalikäytäntö. Mutta toisaalta onneksi tällaisia moniviestinpaketteja on nykyään yhä vähemmän ja nekin kootaan suurimmaksi osaksi itse. Mitä katselin OUTIn uusimpia tilattuja moniviestimiä, niin niillä näyttäisi olevan ihan oma ISBN-tunnus nykyään. 

Tämän valossa varmaan voitaisiin mennä tuolla ensimmäisellä toistumalla, mutta kuvailijoiden pitää tiedostaa tämä, jos jotkut kimpat tekevät vielä itse koottuja aineisto- tai moniviestinpaketteja TäTiin tai omaan kantaan. Valumista voi nimittäin tapahtua toisinkin päin, kuten OUTIssa, jossa on omia Selkis-kasseja, joissa on mukana kirjoja yms. muuta sälää. Sitten kun kassissa olevien kirjojen tiedot tallennetaan tuon selkis-kassin tietueeseen, niiden ISBN-tunnukset tallennetaan 020-kenttiin, ja sitten jos TäTissä sattuukin olemaan nuo kirjat omina tietueinaan, niin sieltä valuu sitten jokin kirjatietue tuon kassin päälle, kuten tässä vähän aikaa sitten oikeasti tapahtuikin :D Tämän takia tällaiset tapaukset pitäisi minun mielestä kuvailijoiden ja hankintaa tekevien tiedostaa, ennen kuin tallentavat tällaisissa tapauksissa hankintatietueita tai kuvailutietueita.

Sellaiset tietueet, jotka viedään Melindaan asti, on sitten helpompi yksilöidä, koska aktivointiarvoksi saadaan yksilöity 035a-kentässä oleva Melinda-ID. Näissä tapauksissa, jos tietueella on useampi ISBN, kannattaa melkein ensin tehdä tietue TäTiin ilman ISBN-tunnuksia, viedä se Melindaan, jotta saadaan Melinda-ID:t, katsoa aktivointiarvot oikeiksi, ja lopuksi täydentää sitten 020-kentät ja päivittää tietue Melindaan.

**Comment by AnttHeik** [comment]
> Onko se ensimmäinen yleensä se oikea vaihtoehto? Etsimisenhän voisi sitten katkaista siihen, luulen että nyt se käy ne kaikki läpi ja viimeinen esiintymä aktivoituu.

Onko tuo viimeisen esiintymän aktivoituminen ollut muuten se juju, jolla aktivointiarvoksi on saatu 035a-kentän Melinda-ID aiemmin, vai tarkoititko sitä, että se käy yhden kentän, esim. 020-kentän, sisällä kaikki toistumat läpi ja ottaa viimeisen 020-kentän arvon aktivointiarvoksi?

**Comment by johannaraisa** [comment]
Olen siis koo

> > Onko se ensimmäinen yleensä se oikea vaihtoehto? Etsimisenhän voisi sitten katkaista siihen, luulen että nyt se käy ne kaikki läpi ja viimeinen esiintymä aktivoituu.
> 
> Onko tuo viimeisen esiintymän aktivoituminen ollut muuten se juju, jolla aktivointiarvoksi on saatu 035a-kentän Melinda-ID aiemmin, vai tarkoititko sitä, että se käy yhden kentän, esim. 020-kentän, sisällä kaikki toistumat läpi ja ottaa viimeisen 020-kentän arvon aktivointiarvoksi?

Olen siis tehnyt sellaisen systeemin, että se Melindan 035a on painoarvoltaan suurin ja jos se löytyy niin se tulee aktivointiarvoksi. Seuraavana on tulee 020a, 024a ja viimeisenä 003|001. Tuossa 020a:ssa se näytti käyvän ne kaikki 020a:n esiintymät läpi ja ei katkaise sitä tarkistusta ensimmäiseen. 

Ehkä tämä on minulla jokin ajatusvirhe, että ajattelin siellä olevan vain yksi 020a-arvo. Muokkasin tuota aamulla ja nyt se ottaa huomioon vain sen ensimmäisen 020a-arvon. Lisäksi muokkasin tuota 035a:ta sen verran, että jos löytyy FI-BTJ, niin sitä tulee aktivointiarvo. Nuo on ainakin varmoja arvoja kun pitäisi olla yksilöllisiä ja alkaa olemaan kaikilla Kipalta tulevilla tietueilla. Sen pitäisi muuttua Melinda-ID:lle, jos sellainen siihen tietueeseen tulee.

**Comment by AnttHeik** [comment]
> > > Onko se ensimmäinen yleensä se oikea vaihtoehto? Etsimisenhän voisi sitten katkaista siihen, luulen että nyt se käy ne kaikki läpi ja viimeinen esiintymä aktivoituu.
> > 
> > 
> > Onko tuo viimeisen esiintymän aktivoituminen ollut muuten se juju, jolla aktivointiarvoksi on saatu 035a-kentän Melinda-ID aiemmin, vai tarkoititko sitä, että se käy yhden kentän, esim. 020-kentän, sisällä kaikki toistumat läpi ja ottaa viimeisen 020-kentän arvon aktivointiarvoksi?
> 
> Olen siis tehnyt sellaisen systeemin, että se Melindan 035a on painoarvoltaan suurin ja jos se löytyy niin se tulee aktivointiarvoksi. Seuraavana on tulee 020a, 024a ja viimeisenä 003|001. Tuossa 020a:ssa se näytti käyvän ne kaikki 020a:n esiintymät läpi ja ei katkaise sitä tarkistusta ensimmäiseen.
> 
> Ehkä tämä on minulla jokin ajatusvirhe, että ajattelin siellä olevan vain yksi 020a-arvo. Muokkasin tuota aamulla ja nyt se ottaa huomioon vain sen ensimmäisen 020a-arvon. Lisäksi muokkasin tuota 035a:ta sen verran, että jos löytyy FI-BTJ, niin sitä tulee aktivointiarvo. Nuo on ainakin varmoja arvoja kun pitäisi olla yksilöllisiä ja alkaa olemaan kaikilla Kipalta tulevilla tietueilla. Sen pitäisi muuttua Melinda-ID:lle, jos sellainen siihen tietueeseen tulee.

Ok, kiitokset. Tuo vaikuttaisi oikein hyvältä ratkaisulta. Seuraillaan tilannetta tässäkin.

**Comment by AnttHeik** [comment]
> 
> Juttelin perjantaina pikaisesti tästä Johannan kanssa ja hän arveli, että Tietuesiirtäjän raportille pystyisi ehkä tekemään jonkin rajauksen, jolla suodattaa näkyville tietueet, joissa on muutoksia tietyissä kentissä. Hän on kuitenkin tämän viikon lomalla, joten tämän toteutus mennee myöhemmäksi.

Palatakseni vielä tämän tiketin alkuperäiseen aiheeseen, niin onkohan tuo Tietuesiirtäjän raportin suodatus mahdollista toteuttaa jollakin tapaa?

**Comment by johannaraisa** [comment]
> > > > Onko se ensimmäinen yleensä se oikea vaihtoehto? Etsimisenhän voisi sitten katkaista siihen, luulen että nyt se käy ne kaikki läpi ja viimeinen esiintymä aktivoituu.
> > > 
> > > 
> > > Onko tuo viimeisen esiintymän aktivoituminen ollut muuten se juju, jolla aktivointiarvoksi on saatu 035a-kentän Melinda-ID aiemmin, vai tarkoititko sitä, että se käy yhden kentän, esim. 020-kentän, sisällä kaikki toistumat läpi ja ottaa viimeisen 020-kentän arvon aktivointiarvoksi?
> > 
> > 
> > Olen siis tehnyt sellaisen systeemin, että se Melindan 035a on painoarvoltaan suurin ja jos se löytyy niin se tulee aktivointiarvoksi. Seuraavana on tulee 020a, 024a ja viimeisenä 003|001. Tuossa 020a:ssa se näytti käyvän ne kaikki 020a:n esiintymät läpi ja ei katkaise sitä tarkistusta ensimmäiseen.
> > Ehkä tämä on minulla jokin ajatusvirhe, että ajattelin siellä olevan vain yksi 020a-arvo. Muokkasin tuota aamulla ja nyt se ottaa huomioon vain sen ensimmäisen 020a-arvon. Lisäksi muokkasin tuota 035a:ta sen verran, että jos löytyy FI-BTJ, niin sitä tulee aktivointiarvo. Nuo on ainakin varmoja arvoja kun pitäisi olla yksilöllisiä ja alkaa olemaan kaikilla Kipalta tulevilla tietueilla. Sen pitäisi muuttua Melinda-ID:lle, jos sellainen siihen tietueeseen tulee.
> 
> Hei, palaan vielä tähän, koska hoksasin, että OUTIssa näyttää olevan vanhempia tietueita aktivoituna siten, että viimeisin 020-kentän toistuma on aktivointiarvona. Kyseessä on ainakin moniosaisen kirjasarjan teoksia, joten näissä saattaa nyt olla väärin valumisen vaaroja, jos tällaisia tapauksia on paljonkin.
> 
> Esim. mangasarja Yotsuba&!., jossa oli valunut ykkösosan (ID: 894862) päälle kasiosan tietue. Korjasin tämän, mutta haeskelin sitten muita koko kirjasarjan tietueita ISBN-tunnuksella 9789525630275 ja joissakin muissakin osissa on aktivointiarvona nyt tuo koko kirjasarjan tunnus eikä ensimmäisessä 020-kentässä olevan osan tunnus, esim OUTI-tietueet: 924242 ja 894865.
> 
> Mietityttää tosin, että miksi nuo muut tietueet eivät ole muuttuneet samalla eikä myöskään varsinainen kasiosan tietue 932370 muuttunut mitenkään, kun TäTissä on käsitelty tuota kasiosan tietuetta, vaan vain ykkösosa oli se, johon muutos kohdistui.
> 
> Mitäköhän noiden kanssa olisi järkevintä tehdä? Pystyykö vanhempien tietojen aktivointiarvoja ajamaan uusiksi tai niiden tietueiden, joilla on useampi 020-kenttä, vai pitäisikö tässä vain laittaa viestiä muille kuvailijoille, että aina kun TäTissä päivitetään tai sinne tuodaan tietueita, niin kannattaa tarkistella, ettei tietueet valu väärin?

Pitää varmaan ajella uudestaan noita, jotta tuo arvo päivittyy noille vanhoille.

**Comment by johannaraisa** [comment]
Nyt pitäisi olla nämä ajettu uudestaan. Jos löytyy joku esimerkki, niin vilkaise miltä näyttää.

**Comment by AnttHeik** [comment]
Pitäiskö nämä näkyä heti? Ainakaan näissä tietueissa ei tapahtunut muutoksia, vaan edelleen on vanhat arvot ovat edelleen: 924242 ja 894865. Sitten myös esim. tällainen tietue: 2146584, jossa onkin muuten mielenkiintoisesti joku laittanut 020a-kenttään koko rimpsun väärin: 9789519751283 (koko teos) :D

**Comment by johannaraisa** [comment]
> Pitäiskö nämä näkyä heti? Ainakaan näissä tietueissa ei tapahtunut muutoksia, vaan edelleen on vanhat arvot ovat edelleen: 924242 ja 894865. Sitten myös esim. tällainen tietue: 2146584, jossa onkin muuten mielenkiintoisesti joku laittanut 020a-kenttään koko rimpsun väärin: 9789519751283 (koko teos) :D

Hmm, laitoin sen ajelemaan eilen. No pitää katsoa uudestaan.

**Comment by johannaraisa** [comment]
Olin näköjään laittanut liian tiukan säännön sillle, no ajellaan ensi yönä uudestaan.

**Comment by AnttHeik** [comment]
Ok! Tarkastellaanpa sitten huomenna taas, miten kävi.

**Comment by AnttHeik** [comment]
OUTIn alkoi tipahdella nyt jo tietueita. Pitäisikö tuon uudelleenaktivoinnin vaikuttaa vai tapahtuukohan TäTissä tai Melindassa jotain muuta tällä hetkellä?

**Comment by johannaraisa** [comment]
> OUTIn alkoi tipahdella nyt jo tietueita. Pitäisikö tuon uudelleenaktivoinnin vaikuttaa vai tapahtuukohan TäTissä tai Melindassa jotain muuta tällä hetkellä?

Ei se tehnyt muuta kuin korjasi niitä aktivointiarvoja, muuten kaikki pyörii kuten ennenkin.

**Comment by johannaraisa** [comment]
Tai lähinnä yritti korjata, mutta ei purenut noihin joissa oli jo 020a aktivointuna.

**Comment by AnttHeik** [comment]
Ok, olisikohan tuossa sitten käsitelty joitain sellaisia, jotka eivät olisi aiemmin aktivoituneet jostain syystä. Aika monta useamman 020-kentän sisältävää tietuetta tuolta TäTistä asti kuitenkin tipahti. Yksi ainoa tietue tuli vastaan, jossa oli ollut 020-kentät väärin päin, mutta korjasin sen :)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 20.5.2024: Suljetaan tiketti. Jos tulee uusia tarpeita, avataan uusi tiketti.
