### ISSUE TITLE
Kirkes: nidetyypin 28VRKYL noutoajan muokkaus ei toimi

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1099]
### Mikä vikana?

Tuusulan kirjastoautossa on ollut se ongelma, että laina-aika 28 vrk yleinen antaa seitsemän päivän noutoajan, vaikka asetuksissa on 14 päivää. Kun testailin laina- ja maksusääntöjä Kirkes-nextillä, havaitsin, että noutoajat tulivat oikein asiakastyypin, nidetyypin ja kirjaston mukaan, paitsi siinä tapauksessa kun yritin muuttaa 28 vrk yleiselle lyhyemmän noutoajan muissakin kirjastoissa kuin kirjastoautoissa. Edelleen tuli seitsemän päivää. Havaitsin myös, että 28VRKYL saa seitsemän päivän noutoajan 14 päivään sijaan itse asiassa molemmissa kirjastoautoissa, sekä nextillä, testillä että tuotannossa. Mäntsälän kirjastoautosta ei ole annettu asiasta palautetta, mutta luultavasti ongelma on koskenut tätä yhtä nidetyyppiä sielläkin. 

Lisäksi olen Kirkes-testin puolella olen testannut, että noutoaika ei muutu, vaikka koko nidetyypin laina- ja maksusäännöt poistaisi kokonaan ja tekisi ne alusta uudestaan. Itse nidetyyppiä en ole kyllä kokeillut poistaa.

**Comment by emta001** [comment]
Hmm, jostain syystä tuo sääntö tosiaan nappaa nyt "ReservesMaxPickUpDelay" asetukseen, muttei laina- ja maksusääntöön. Pitää tutkia onko tuossa jokin ehto koodissa, joka tuon aiheuttaa vai mikä.

**Comment by emta001** [comment]
Voisiko tässä käydä nyt niin, että varaukset nappaavat lähes aina sääntöön joka koskee "Henkilö"-asiakkaita ja jolle ei ole määritetty mitään noutoaikaa? Kun kantaa tarkastelee, sieltä löytyy Tuusulan kirjastoauton 28VRKYL nidetyypille seuraavat säännöt:

```
MariaDB [kirkesprod]> select * from circulation_rules where rule_name = "holds_pickup_period" and branchcode = "TUAU" and itemtype like "28VRKYL";
+-------+------------+--------------+----------+---------------------+------------+
| id    | branchcode | categorycode | itemtype | rule_name           | rule_value |
+-------+------------+--------------+----------+---------------------+------------+
| 49145 | TUAU       | EITILASTO    | 28VRKYL  | holds_pickup_period | 14         |
| 49297 | TUAU       | HENKILO      | 28VRKYL  | holds_pickup_period |            |
| 49298 | TUAU       | KAUKOLAINA   | 28VRKYL  | holds_pickup_period |            |
| 49709 | TUAU       | KOTIPALVEL   | 28VRKYL  | holds_pickup_period | 14         |
| 49803 | TUAU       | VIRKAILIJA   | 28VRKYL  | holds_pickup_period |            |
| 50423 | TUAU       | YHTEISO      | 28VRKYL  | holds_pickup_period | 14         |
| 50634 | TUAU       | NULL         | 28VRKYL  | holds_pickup_period | 14         |
+-------+------------+--------------+----------+---------------------+------------+
```

Mitä tapahtuu jos aineistoa lainaa vaikkapa lapsi-asiakkaalle?

**Comment by ElinaUotila** [comment]
Kävin kurkkaamassa. Testillä on tällä hetkellä siellä sellainen määritys kuin "kaikki asiakastyypit, kaikki nidetyypit," jossa on se kolmen päivän noutoaika. Ja mulla on viimeisimmän poistoyrityksen ja testauksen jälkeen ilmeisesti jäänyt tekemättä 28VRKYL säännöt uudestaan, koska ne puuttuu sieltä.

**Comment by emta001** [comment]
> Testasin lapsi-asiakkaalla, tuli 3 päivän noutoaika 😄

Tää noudataakin tämmöstä sääntöä:

```
+-------+------------+--------------+------------+---------------------+------------+
| id    | branchcode | categorycode | itemtype   | rule_name           | rule_value |
+-------+------------+--------------+------------+---------------------+------------+
| 44770 | TUAU       | NULL         | NULL       | holds_pickup_period | 3          |
```

Missä ei taas ole mitään järkeä, koska kyllähän tolla niteellä oli nidetyyppinä 28VRKYL. Ettei nuo nyt vaan kuitenkin yrittäs nappailla tuolta kannasta sääntöjä, jotka tulee vaan ensimmäisenä vastaan.

**Comment by emta001** [comment]
> Nuo asiakastyyppikohtaiset noutoajat tuolla ylempänä on mulle vähän mysteeri. Meillä on siellä laina- ja maksusääntöjä yhteisö- ja kotipalvelu- asiakkaalle, ja sitten kaikki. Kuitenkin tuon taulun mukaan yhteisö ja ei tilasto -asiakkaille on myös määritetty se 14 päivää, eli mistä se sitten tulee.

No niinpä onkin. Ei kyllä mitään havaintoa mistä nuo oikein on tulevinaan. Ja tuo kaikkia koskeva sääntökin on näemmä nidetyypille "28 vrk yleinen lapset".

**Comment by emta001** [comment]
> > Nuo asiakastyyppikohtaiset noutoajat tuolla ylempänä on mulle vähän mysteeri. Meillä on siellä laina- ja maksusääntöjä yhteisö- ja kotipalvelu- asiakkaalle, ja sitten kaikki. Kuitenkin tuon taulun mukaan yhteisö ja ei tilasto -asiakkaille on myös määritetty se 14 päivää, eli mistä se sitten tulee.
> 
> No niinpä onkin. Ei kyllä mitään havaintoa mistä nuo oikein on tulevinaan. Ja tuo kaikkia koskeva sääntökin on näemmä nidetyypille "28 vrk yleinen lapset".

Jaa, no miun ois ehkä kannattanut katsoa nuo testiltä ei tuotannosta :D Siellä on tuommoset, testillä taas:

```
+-------+------------+--------------+----------+---------------------+------------+
| id    | branchcode | categorycode | itemtype | rule_name           | rule_value |
+-------+------------+--------------+----------+---------------------+------------+
| 46225 | TUAU       | EITILASTO    | 28VRKYL  | holds_pickup_period | 14         |
| 46377 | TUAU       | HENKILO      | 28VRKYL  | holds_pickup_period |            |
| 46378 | TUAU       | KAUKOLAINA   | 28VRKYL  | holds_pickup_period |            |
| 46789 | TUAU       | KOTIPALVEL   | 28VRKYL  | holds_pickup_period | 14         |
| 46883 | TUAU       | VIRKAILIJA   | 28VRKYL  | holds_pickup_period |            |
| 47503 | TUAU       | YHTEISO      | 28VRKYL  | holds_pickup_period | 14         |
+-------+------------+--------------+----------+---------------------+------------+
```

**Comment by emta001** [comment]
Nonnih, lisäsin sinne säännön, joka koskee "28 vrk yleinen" niteitä ja kaikkia asiakastyyppejä, varauksen noutoaika 14 päivää. Nyt kun nappasin varauksen lapsi-asiakkaalle, niin tälle tuli 14 päivää noutoaikaa.

**Comment by ElinaUotila** [comment]
Mutta henkilöasiakkaille tulee ilmeisesti edelleen lyhyempi noutoaika kuin muille?

**Comment by emta001** [comment]
> Mutta henkilöasiakkaille tulee ilmeisesti edelleen lyhyempi noutoaika kuin muille?

Juu, juuri testasin ja edelleen tulee 7 päivää. Tuo henkilöasiakkaiden sääntö ei jostain syystä näy edelleenkään laina- ja maksusäännöissä. Mutta se on kannassa, joten noutoaika menee sitten sen mukaan. Eli ongelmana on nyt se, että kaikki laina- ja maksusäännöt eivät näy liittymässä vaikka ne on kannassa. Pitää tutkia miten ne saa näkymään.

**Comment by emta001** [comment]
Muistelin tuossa palaverissa, että näissä sääntöjen poistamisissa on saattanut joskus olla bugi. Eli kun sääntö on poistettu, niin tietokantaan on silti jäänyt "orpoja" sääntöjä ja se on koskenut nimenomaan näitä noutoaikoja. Kirkeksen testikannassa ei ainakaan ole henkilöasiakkaille muuta sääntöä kuin tuo varauksen noutoaikasääntö. 

Tutkasin yhteisön tiketin [8367](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=8367). Siellä on tosiaan ollut virhe, joka on estänyt säännön poistamisen, jos noutoaika on täytetty. Luulen, että tuosta tämä on nyt kiikastanut. Paras ratkaisu lienee vaan poistaa nuo orvot rivit. Yritän askarrella siihen jonkin fiksun tavan, että nää kaikki tapaukset saataisiin pois kannasta kerralla.

**Comment by ElinaUotila** [comment]
Kiitos vaivannäöstä ja tutkimisesta!

**Comment by emta001** [comment]
Ylimääräiset laina- ja maksusäännöt on nyt poistettu. Poisto koski 312 sääntöä, jotka on tallessa aputaulussa mahdollisten ongelmian varalta. Näillä loitsuilla onnistui:

```
CREATE TABLE ks_240228_circrules_ks221099 SELECT id FROM circulation_rules GROUP BY branchcode, categorycode, itemtype HAVING COUNT(*) = 1;

UPDATE circulation_rules SET rule_value = "VIRHE" WHERE id IN(SELECT id FROM circulation_rules GROUP BY branchcode, categorycode, itemtype HAVING COUNT(*) = 1);

DELETE FROM circulation_rules WHERE rule_value = "VIRHE";
```

**Comment by emta001** [comment]
Samat temput tehty testille ja nextille.

**Comment by ElinaUotila** [comment]
Tuusulan kirjastoauton noutoajat muodostuvat nyt oikein ja muualla ei ole havaittu sääntöjen poiston aiheuttaneen ei-toivottuja muutoksia, joten suljen tämän tiketin.
