### ISSUE TITLE
Kirkes: koulukirjastojen myöhästymistoiminnot eivät toimi niin kuin on määritetty

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1104]
### Mikä vikana?

Koulukirjastoille on määritetty myöhästymistoiminnot eri tavalla kuin muille kirjastoille https://kirkes.koha-suomi.fi/cgi-bin/koha/tools/overduerules.pl . Palautuskehotukset lähtevät säädetyn aikataulun mukaan ja toisesta palautuskehotuksesta ei tule lainauskieltoa, eli näiltä osin asetukset toimivat. Mutta muistutuskirjeistä tulee asiakkaalle 1. euron maksu, vaikka sitä ei pitäisi tulla. 

Koulujen myöhästymistoiminnot määriteltiin vasta tuotantokonversioviikolla, kun oletustoiminnot, ml. maksulliset muistutukset oli tehty ennen konversiota. Onko mahdollista että maksut tulevat nyt tuolta oletuksesta eivätkä koulujen omista säännöistä?

**Comment by AnneliO** [comment]
Kaikilla muilla kouluilla paitsi Järvenpään yhteiskoululla on omat määritykset. Onko tuo yksi tarkoituksella määrittelemättä?

Onko maksuja syntynyt siis kaikkien koulujen lainojen palautuskehotuksista?

**Comment by ElinaUotila** [comment]
Toi yhteiskoulu on täysin mun moka, eli jostain syystä jäänyt välistä. Kiitos huomiosta!

Maksuja on kyllä muodostunut muillakin kouluilla, tässä pari esimerkkiasiakasta Kartanon koululta: borrowenumberit 82406 ja 69821. Aikaisemmin mun tietoon on tullut myös yksi Kinnarin koulun asiakas, jolta maksut on kyllä ehditty jo poistaa.

**Comment by AnneliO** [comment]
OUTIssa on myös Oulun koulukirjastossa määritetty palautuskehotukset maksuttomiksi ja kaivelin nyt sieltä vastaavia tapauksia (vähän haastoi se, että viive on 5000 päivää :D). Löytyi kolme tapausta ja kaikille oli muodostunut myöhästymismaksu, vaikka Myöhästymisilmoitukset-sivulle ei ole määritetty maksua. Eli viive on kyllä huomioitu, mutta maksu ei.

**Comment by ElinaUotila** [comment]
Tuo pidempi viive on käynyt mullakin mielessä vaihtoehtona, mutta alun perin on ajateltu, että noilla koulukirjaston muikkareilla saa kätevästi opetettua lapsille kirjaston käyttöä ilman rahallisia seuraamuksia.

**Comment by emta001** [comment]
Vika löytyi. Cronissa overdue_notices.pl on seuraava ehto:
```
    if (my $f = $sth->fetchrow_array) {
        $price = $f;
    }else {
        my $sth2 = C4::Context->dbh->prepare("SELECT ".$fine." FROM overduerules WHERE categorycode = ?");
        $sth2->execute($categorycode);
        $price = $sth2->fetchrow_array
    }
```
Eli tuossa `if (my $f = $sth->fetchrow_array)` kohdassa tarkastellaan onko kannasta löytynyt maksun määrää tietyillä hakuehdoilla. Koska näissä koulukirjaston aineistoissa tuo määrä on 0 ja perl käsittelee arvon 0 falsena, siirrytäänkin tässä tuohon else-ehtoon, joka hakee kannasta default-arvon. 

Tein tähän korjauksen ja vein sen testeille.

**Comment by emta001** [comment]
Ajo tehty kirkes-testille.

**Comment by AnneliO** [comment]
Tein nyt OUTIssa Oulun koulukirjastolle lainan [henkilöasiakkaalle](https://outi-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=128100) niin, että eräpäivä on tänään. Muutin viiveen yhdeksi päiväksi eli huomenna pitäisi lähteä palautuskehotus.

**Comment by ElinaUotila** [comment]
Ihmettelin miksi testiasiakkaalle ei ollut muodostunut palautuskehotusta ja tajusin mokanneeni tässä, eli unohdin vaihtaa kirjaston, kun tein noita testilainoja. Asiakas ja niteet olivat kyllä oikeasta yksiköstä, mutta lainat oli tehty väärässä kirjastossa :D. Viitsitkö Emmi pyöräyttää ajon uudestaan kirkes-testillä huomenna? Nyt siellä olisi lainauspiste oikein ja eräpäivä tänään.

**Comment by emta001** [comment]
Ajot on nyt tehty molemmille testeille.

**Comment by ElinaUotila** [comment]
Kinnarin testiasiakkaalle on muodostunut aivan oikein palautuskehotus, mutta ei maksua.

**Comment by AnneliO** [comment]
Oulun koulukirjastosta lainanneelle henkilöasiakkaalle oli muodostunut palautuskehotus, mutta ei maksua. :)

**Comment by emta001** [comment]
Hieno homma! Uskaltaako tämän laittaa näillä testauksilla tuotantoon ensi viikolla?

**Comment by AnneliO** [comment]
Pitäiskö se varmuuden välttämiseksi testata vielä, että se oletussääntö toimii vielä oikein?

**Comment by AnneliO** [comment]
Tein OUTI-testille nyt vielä sellaiset testit, että ne pitäisi osua oletussääntöön. Eräpäiväksi su 10.3.2024 eli kehotus pitäisi muodostua ma 11.3.2024.

[Kaukolainakirjasto-asiakas](https://outi-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=105165), jolle pitäisi lähteä kehotus, mutta ei tulla maksua.

[Henkilöasiakas](https://outi-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=128100), jolle pitäisi lähteä ilmoitus ja muodostua maksu.

**Comment by ElinaUotila** [comment]
Samanlaiset testit tehty Kirkesiin samalla eräpäivällä: 

[Kaukolainakirjasto-asiakas](https://kirkes-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=98841)

[Henkilöasiakas](https://kirkes-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=33778)

**Comment by emta001** [comment]
Molemmille ajettu overdue_notices-ajo.

**Comment by ElinaUotila** [comment]
Kirkesissä kaukolaina-asiakkaalle muodostui kehotus, ei maksua. 

Henkilöasiakkaalle muodostui kehotus ja maksu. 

Eli meillä ainakin toimii oikein.

**Comment by ElinaUotila** [comment]
Näyttää siltä, että tänään lähteneissä koulujen palautuskehotuksissa ei ole sitä maksua enää muodostunut, eli suljen tämän.
