### ISSUE TITLE
Raportilta eräkäsittelyyn viennin tekstissä virhe

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1106]
### Mikä vikana?

Kun raporttiin on määritelty LIMIT yli 20, eräkäsittelyyn viennissä lukee aina "Eräkäsittele 20 näkyvillä olevaa riviä" vaikka käsittely tehdään aina kaikille näkyville riveille, eli sille määrälle, joka määritellään limitillä.

### Mitä pitäisi tapahtua

Tekstinä pitäisi olla "Eräkäsittele kaikki näkyvillä olevat rivit" tai "Eräkäsittele <<limit-arvo>> näkyvillä olevaa riviä", kun käytössä on raporttiin määritelty limit-arvo.

**Comment by AnneliO** [comment]
Nämä yhteisön bugit ei ole ihan samasta asiasta, mutta pistän varalta ylös.

Tämä liittyy limitointiin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=17120

Tämä taas liittyy raportilta eräkäsittelyyn vientiin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=21893

**Comment by atarnus** [comment]
Itse olen miettinyt ihan samaa tuon ensimmäisen yhteisötiketin kanssa, että tuo oletus 20 riviä on ihan hassu ja sivun vaihtaminen tuntuu tosiaan tekevän koko kyselyn uusiksi tulosasetusten mukaisella offsetillä ja limitillä. Eli tulosten lukumäärän määrittely jo hakua tehdessä olisi hyvä, mutta itse lausekkeessa LIMIT ei ole mikään sivunvaihdon merkki, vaan sen ylittävät tulokset jäävät sitten kokonaan pois.

Jälkimmäinen tiketti koskee vain eräajoon vietäviä yli tuhannen niteen hakuja, jonka senkin voi kiertää sitten käyttämällä LIMITiä, mutta edelleen on toki vähän epäoptimaalista joutua muokkaamaan raporttien lausekkeita käsin (etenkin kun tuo LIMIT ei toimi edes parametrinä). Ja kaikkiin raportteihin tuskin halutaan laittaa jotain LIMIT 5000?

Tässä tapauksessa tuo 'Eräkäsittele näkyvillä olevat rivit' nappi toimii joka tapauksessa todella hassusti, riippumatta noista muista bugeista.

Nappi nappaa luvun 'tuloksia per sivu' luvun mukaan silloin kun se jää alle kokonaistulosten. Esim. 24 tuloksen kanssa jos vaihtaa 10 per sivu, niin sanoo 'Eräkäsittele 10 näkyvillä olevaa riviä' tai 50 per sivu, niin sanoo 'Eräkäsittele 24 näkyvillä olevaa riviä'. Joka tapauksessa se vie eräkäsittelyyn kaikki 24 riviä, ellei vaihda sivua. (Jos laittaa tulokset 10/sivu ja vaihtaa kakkossivulle, niin sieltä lähtee käsittelyyn oikeastikin vain ne 10 näkyvillä olevaa riviä, vain 1. sivulla näkyy limitin mukainen rajaus. Ja sitten kun menee kolmannelle sivulle, jossa on vain 4 tulosta, se edelleen sanoo 'Eräkäsittele 10 näkyvillä olevaa riviä'. )

Viesti tulee guided_reports_start.tt templatesta:
```
<button class="btn btn-default btn-sm dropdown-toggle" type="button" id="batch_mod_menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
  Batch operations with [% IF unlimited_total >= limit %][% limit | html %][% ELSE %][% unlimited_total | html %][% END %] visible records
```

Sivulla on kuitenkin jo tieto oikeasti näkyvillä olevista riveistä:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/727eb75a-78f3-4bb2-8e4d-12f204e3398f)
```
<span class="label">Total number of results:</span>
  [% unlimited_total | html %]
    [% IF unlimited_total >= limit %]
  ([% results.size | html %] shown)
  [% END %]
```

Napin muuttaminen käyttämään results.sizea limitin sijaan näyttäisi toimivan ihan hyvin. Tarpeen vaatiessa tuon luvun saa napattua sivulta myös JS-rimpsuun.

**Comment by atarnus** [comment]
Tämä ei ole tosiaan vielä nexteillä fiksattu.

Nappimuutokset jälkeen tulokset:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/9d746a9f-9054-449f-b4dc-5fa4fbc898e0)
![image](https://github.com/KohaSuomi/Koha/assets/63994411/31d1acdc-92df-4df9-907c-183add00c5c4)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 2.4.2024: @MikkoLiimatainen teetkö tästä tiketin yhteisöön, niin Kassu tekee sinne sitten patchin, joka korjaa tämän virheen.

**Comment by MikkoLiimatainen** [comment]
Tiketti yhteisössä: [36534](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36534)

**Comment by atarnus** [comment]
Tämä muutos on nyt githubissa, vietävä vielä nexteille.

**Comment by MikkoLiimatainen** [comment]
Testattu. Erämuokkauksen nappi näyttää nyt näkyvien rivien määrän ja vie näkyvät rivit muokkaukseen. Toimii siis oikein.

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja napissa oikea määrä.

**Comment by MikkoLiimatainen** [comment]
Toimii, suljen tiketin.

**Comment by atarnus** [comment]
Tämä tulee yhteisössä versioon 24.05
