### ISSUE TITLE
Raportti, joka laskee tietueen niteiden lainamäärät sekä JavaScriptillä nappi raportin ajoon.

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1109]
### Tukipyyntö

Tarvitaan raportti, joka laskee tietueen niteiden lainamäärät sekä aktiivisista niteistä että poistetuista niteistä. 
* Tiedot ryhmitellään niteen mukaan
* Lainat ja uusinnat erikseen ja yhteensä
* Lisäksi vielä kaikkien niteiden lainojen ja uusintojen yhteissummat
* Parametriksi biblionumber

Lainat ja uusinnat voisi hakea biblionumberin perusteella items- ja deleted_items-tauluista issues- ja renewals-sarakkeista.

Lisäksi voisi tehdä JavaScriptillä perustiedot-sivulle napin, jota klikkaamalla ajetaan tämä raportti uudella välilehdellä tai pop-upissa. JS poimii sivulta parametriksi biblionumberin.

Raportilla valmistellaan yhteiseen kuvailutietokantaan siirtymistä, koska siellä ei pystytä käyttämään biblioitems-taulun totalissues-sarakkeen tietoja.

**Comment by atarnus** [comment]
Tällainen kaunis lauseke toiminee:

```
SELECT *
 FROM (SELECT COALESCE(itemnumber, 'Niteet yht.') AS 'Nidenumero',
              CASE WHEN itemnumber IS NULL THEN ''
              ELSE homebranch END AS 'Kotikirjasto',
              CASE WHEN itemnumber IS NULL THEN ''
              ELSE DATE(deleted_on) END AS 'Poistettu',
              SUM(IFNULL(issues,0)+0) AS 'Ensilainat', SUM(IFNULL(renewals,0)+0) AS 'Uusinnat', SUM(IFNULL(issues,0)+IFNULL(renewals,0)) AS 'Lainat yht.'
         FROM (SELECT itemnumber, homebranch, deleted_on, issues, renewals
                 FROM items i
                WHERE biblionumber = <<biblionumber>>
                GROUP BY itemnumber WITH ROLLUP
                UNION
               SELECT itemnumber, homebranch, deleted_on, issues, renewals
                 FROM deleteditems di
                WHERE biblionumber = <<biblionumber>>
                GROUP BY itemnumber) AS d
        GROUP BY itemnumber WITH ROLLUP) AS e
ORDER BY 6 DESC
```

![image](https://github.com/KohaSuomi/Koha/assets/63994411/49c01ed9-7b84-430e-8e62-3cf0259f4f22)

Katselen miten se laitettaisiin avautumaan nappulaan vielä.

**Comment by atarnus** [comment]
Outi-testille laitettu linkki uudessa ikkunassa avautuvaan raporttiin.

![image](https://github.com/KohaSuomi/Koha/assets/63994411/51909ca6-8c64-49c1-95d8-61ecb3684907)

intranetuser.js:
```
/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 
    $('#catalogue_detail_biblio div').append('<span class="results_summary"><span class="lainatiedot label">Lainaustilastot: </span><a id="lainatiedot" href="#">Raportti</a></span>');
  }  
});

$('body').on('click', '#lainatiedot', function(e) {
  e.preventDefault();
    var reportnumber = 708;   
    var params = new URLSearchParams(window.location.search);
    var biblionumber = params.get('biblionumber');
    var reporturl = '/cgi-bin/koha/reports/guided_reports.pl?reports=' + reportnumber + '&phase=Run+this+report&param_name=biblionumber&sql_params=' + biblionumber;
    var newin = window.open(reporturl,'popup','width=1024,height=768,resizable=no,toolbar=false,scrollbars=yes,top');
});
/// LOPPU ///
```

SQL-raportti: (raportin numero tulee laittaa intranetuser.js:ssä tuonne var reportnumberiin)

```
SELECT *
 FROM (SELECT COALESCE(itemnumber, 'Niteet yht.') AS 'Nidenumero',
              CASE WHEN itemnumber IS NULL THEN ''
              ELSE homebranch END AS 'Kotikirjasto',
              CASE WHEN itemnumber IS NULL THEN ''
              ELSE DATE(deleted_on) END AS 'Poistopvm',
              SUM(IFNULL(issues,0)+0) AS 'Ensilainat', SUM(IFNULL(renewals,0)+0) AS 'Uusinnat',
              SUM(IFNULL(issues,0)+IFNULL(renewals,0)) AS 'Lainat yht.'
         FROM (SELECT IFNULL(itemnumber, 'Tieto puuttuu') AS itemnumber,
         	      homebranch, deleted_on, issues, renewals
                 FROM items i
                WHERE biblionumber = <<biblionumber>>
                GROUP BY itemnumber WITH ROLLUP
                UNION
               SELECT IFNULL(itemnumber, 'Tieto puuttuu') AS itemnumber,
               	      homebranch, deleted_on, issues, renewals
                 FROM deleteditems di
                WHERE biblionumber = <<biblionumber>>
                GROUP BY itemnumber) AS d
        GROUP BY itemnumber WITH ROLLUP) AS e
ORDER BY 6 DESC
```

**Comment by AnneliO** [comment]
Joitain huomioita:

[Ylismaan Gregorissa](https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1327566) Raahen niteeltä puuttuu nidenumero, mutta on lainalukuja. Tietueella on 66 nidettä, mutta raportti listaa 67. RAPK-kirjastossa väitetään olevan kolme nidettä, mutta niitä oikeasti vain yksi.

[Pimeyden hovissa](https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2331322) on listattuna enemmän niteitä, kuin tietueella on items/deleteditems-tauluissa ja nidenumeroilla on vääriä kotikirjastoja. Esim. nidenumero 3692734 väittää olevansa LUPK, mutta oikeasti se on RAPK. :) Lisäksi siellä on nidenumero 3694321, jota tietueella ei ole olemassa.

**Comment by atarnus** [comment]
Olipa tämä jännä. Liikarivit tulivat yksinkertaisesti siitä, että tuonne sisempiin selecteihin jäi kummittelemaan tuo turha ROLLUP, (ja GROUP myös), noita ei enää tarvinnut, kun siirsin varsinaisen laskutoimituksen ulompaan SELECTiin. Kuitenkin edelleen nuo CASE WHEN NULLit sitten muuttivat niitä olemassaolevia rivejä jostain mystisestä syystä, vaikka ei siellä ollut kuin se yksi yhteenlaskurivi, jossa itemnumber on NULL. Näyttäisi kuitenkin toimivan nyt kun pyöräytti tuon käsittelyn ihan ulommaisimpaan SELECTiin eikä käytä enää NULL arvoa. Lisätty myös nimeke tähän, ettei sekota niin pahasti tuloksia, jos on useampi ikkuna auki.

```

SELECT CONCAT_WS(' ', b.title, b.subtitle, b.part_name, b.part_number) AS Nimeke, itemnumber AS Nidenumero,
       CASE WHEN itemnumber = 'Niteet yht.' THEN '' ELSE barcode END AS 'Viivakoodi',
       CASE WHEN itemnumber = 'Niteet yht.' THEN '' ELSE homebranch END AS 'Kotikirjasto',
       CASE WHEN itemnumber = 'Niteet yht.' THEN '' ELSE DATE(deleted_on)END AS 'Poistopvm',
       issues AS Ensilainat, renewals AS Uusinnat, loans AS 'Lainat yht.'
  FROM (SELECT COALESCE(itemnumber, 'Niteet yht.') AS itemnumber, barcode, homebranch, deleted_on,
               SUM(IFNULL(issues,0)+0) AS issues, SUM(IFNULL(renewals,0)+0) AS renewals,
               SUM(IFNULL(issues,0)+IFNULL(renewals,0)) AS loans
          FROM (SELECT IFNULL(itemnumber, 'Tieto puuttuu') AS itemnumber,
                       IFNULL(barcode, 'Tieto puuttuu') AS barcode,
         			         homebranch, deleted_on, issues, renewals
                  FROM items i
                 WHERE biblionumber = <<biblionumber>>
                 UNION ALL
                SELECT IFNULL(itemnumber, 'Tieto puuttuu') AS itemnumber, IFNULL(barcode, 'Tieto puuttuu') AS barcode,
               		     homebranch, deleted_on, issues, renewals
                  FROM deleteditems di
                 WHERE biblionumber = <<biblionumber>>) AS d
         GROUP BY itemnumber WITH ROLLUP) AS e
       LEFT JOIN biblio b ON b.biblionumber = <<biblionumber>>
 ORDER BY 8 DESC
```

Tässä on nyt poimittu se biblionumber URLista, että jos jostain syystä raportti antaa tyhjää tulosta, kannattaa tsekata puuttuuko tietueen sivun osoitekentästä määre ?biblionumber=XXX

**Comment by atarnus** [comment]
Kyllä minä löydän Pimeyden Hoville 24 nidettä, ml. itemnumber 3694321 items-taulusta ihan erillisellä haullakin. Tuossa raportissa on nyt mukana myös viivakoodi, niin erottaa vielä hankinnassa olevassa tulokset, olisiko näistä ollut kyse? Pitäisikö nämä rajata haun ulkopuolelle, hankinnassa olevilla kappaleilla ei vielä mahda olla lainoja, vai onko se hyvä että näkee että näitä on tulossa lisää?

**Comment by atarnus** [comment]
Näyttää siltä että sivulla on jo valmiina muuttuja biblionumber, jota voi käyttää suoraan (poimimatta URLista) eli intranetuser-rimpsuun riittää:

```
/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 
    $('#catalogue_detail_biblio div').append('<span class="results_summary"><span class="lainatiedot label">Lainaustilastot: </span><a id="lainatiedot" href="#">Raportti</a></span>');
  }  
});

$('body').on('click', '#lainatiedot', function(e) {
  e.preventDefault();
    var reportnumber = 708;   
    var reporturl = '/cgi-bin/koha/reports/guided_reports.pl?reports=' + reportnumber + '&phase=Run+this+report&param_name=biblionumber&sql_params=' + biblionumber;
    var newin = window.open(reporturl,'popup','width=1024,height=768,resizable=no,toolbar=false,scrollbars=yes,top');
});
/// LOPPU ///
```

**Comment by AnneliO** [comment]
En tiedä, miten olen saanut erimäärän, mutta ihan raportilla laskin niteiden määrät. :D 

Minusta tuo viivakoodi on hyvä ja hyvä myös, että mukana on tilatut. Kaikissa kimpoissa ei tosin käytetä tuollaista "HANK"-alkuista viivakoodia hankinnassa oleville. Nyt rupesin miettimään, pitäisikö siihen lisätä tuon takia dateaccessioned ja datelastborrowed.. ja ehkä datelastseen? Olispahan melko kattava kokoelmatyön apu sitten. :D 

Lisäksi ois mukava kuulla muiden mielipiteitä, että minkä sarakkeen mukaan olisi parasta tiedot järjestää? Määrän mukaan on ihan jees, mutta tuleeko kokoelmatyössä katsottua enemmänkin oman kirjaston niteitä, jolloin kotikirjaston mukaan järjestäminen olisi järkevämpää?

**Comment by AnneliO** [comment]
Testasin raporttia ja js-rimpsua myös outi-nextillä ja ne toimivat minusta myös siellä oikein. :)

**Comment by AnneliO** [comment]
No nyt tuli nextillä vastaan tietue, jossa Lainaustilasto: Raportti -linkki tulee kahteen kertaan perustiedot-näytölle: https://outi-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1643913

**Comment by atarnus** [comment]
Tuohon katsoin jo fiksin tänä aamuna, huomattiin sama Pirlin kanssa. Vähän tarkesin tuota javascriptiä (tämä tehty Outi-testillä):

```
/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 
    $('#catalogue_detail_biblio div.page-section').append('<span class="results_summary"><span class="lainatiedot label">Lainaustilastot: </span><a id="lainatiedot" href="#">Raportti</a></span>');
  }  
});

$('body').on('click', '#lainatiedot', function(e) {
  e.preventDefault();
    var reportnumber = 708;   
    var reporturl = '/cgi-bin/koha/reports/guided_reports.pl?reports=' + reportnumber + '&phase=Run+this+report&param_name=biblionumber&sql_params=' + biblionumber;
    var newin = window.open(reporturl,'popup','width=1024,height=768,resizable=no,toolbar=false,scrollbars=yes,top');
});
/// LOPPU ///
```

Katselen nyt myös muutoksia itse raporttiin meidän keskustelun pohjalta. Laitan sitten testattavaksi ja laajemmin kommentoitavaksi kun saan työstettyä sen SQL-lausekkeenkin uusiksi.

**Comment by atarnus** [comment]
Mukana linkki biblion sivulle, kirjaston koko nimi (jonka mukaan aakkostettu).
Voisi vähän kasvattaa avautuvan ikkunan kokoa, koska alkaa olemaan tuloksilla leveyttä.

```
SELECT CONCAT('<a href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',<<biblionumber>>,'\">',CONCAT_WS(' ', b.title, b.subtitle, b.part_name, b.part_number),'</a>') AS Nimeke, e.itemnumber,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE e.barcode END AS 'Nidenumero',
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE e.homebranch END AS Kirjastokoodi,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE br.branchname END AS Kotikirjasto,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE DATE(e.deleted_on) END AS 'Poistopvm',
       e.issues AS Ensilainat, e.renewals AS Uusinnat, e.loans AS 'Lainat yht.'
  FROM (SELECT COALESCE(itemnumber, 'Niteet yht.') AS itemnumber,
	             d.barcode, d.homebranch, deleted_on,
               SUM(IFNULL(issues,0)+0) AS issues, SUM(IFNULL(renewals,0)+0) AS renewals,
               SUM(IFNULL(issues,0)+IFNULL(renewals,0)) AS loans
          FROM (SELECT itemnumber, barcode, homebranch, deleted_on, issues, renewals
                  FROM items i
                 WHERE biblionumber = <<biblionumber>>
                 UNION ALL
                SELECT itemnumber, barcode, homebranch, deleted_on, issues, renewals
                  FROM deleteditems di
                 WHERE biblionumber = <<biblionumber>>) AS d
         GROUP BY itemnumber WITH ROLLUP) AS e
       LEFT JOIN biblio b ON b.biblionumber = <<biblionumber>>
       LEFT JOIN branches br ON br.branchcode = e.homebranch
 ORDER BY Kotikirjasto
```

![image](https://github.com/KohaSuomi/Koha/assets/63994411/8390f56c-2b5a-4d6e-8117-88d456710854)

**Comment by atarnus** [comment]
Tätä voisi nyt testata muuallakin, ja antaa kommentteja. Laitan copypastettavat rimpsut vielä tähän, niin on oikeat versiot.
Linkki avaa tosiaan raportin popup-ikkunaan, jos linkin valitsee avattavaksi uuteen ikkunaan, avautuu vain sama perustietosivu sinne uudestaan. Tämänkin toiminnallisuutta voidaan toki vielä miettiä, alkuperäinen ajatus oli kuitenkin popupista.

**Raportiksi:**
```
SELECT CONCAT('<a href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',<<biblionumber>>,'\">',CONCAT_WS(' ', b.title, b.subtitle, b.part_name, b.part_number),'</a>') AS Nimeke, e.itemnumber,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE e.barcode END AS 'Nidenumero',
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE e.homebranch END AS Kirjastokoodi,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE br.branchname END AS Kotikirjasto,
       CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE DATE(e.deleted_on) END AS 'Poistopvm',
       e.issues AS Ensilainat, e.renewals AS Uusinnat, e.loans AS 'Lainat yht.'
  FROM (SELECT COALESCE(itemnumber, 'Niteet yht.') AS itemnumber,
	             d.barcode, d.homebranch, deleted_on,
               SUM(IFNULL(issues,0)+0) AS issues, SUM(IFNULL(renewals,0)+0) AS renewals,
               SUM(IFNULL(issues,0)+IFNULL(renewals,0)) AS loans
          FROM (SELECT itemnumber, barcode, homebranch, deleted_on, issues, renewals
                  FROM items i
                 WHERE biblionumber = <<biblionumber>>
                 UNION ALL
                SELECT itemnumber, barcode, homebranch, deleted_on, issues, renewals
                  FROM deleteditems di
                 WHERE biblionumber = <<biblionumber>>) AS d
         GROUP BY itemnumber WITH ROLLUP) AS e
       LEFT JOIN biblio b ON b.biblionumber = <<biblionumber>>
       LEFT JOIN branches br ON br.branchcode = e.homebranch
 ORDER BY Kotikirjasto
```

**intranetuser.js:ään**  -- muista vaihtaa raporttinumero!
(Testeillä ei tarvittu checksummausta, joten pääkäyttäjät voivat lisätä tämänkin.)
```
/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 
    $('#catalogue_detail_biblio div.page-section').append('<span class="results_summary"><span class="lainatiedot label">Lainaustilastot: </span><a id="lainatiedot" href="#">Raportti</a></span>');
  }  
});

$('body').on('click', '#lainatiedot', function(e) {
  e.preventDefault();
    var reportnumber = 708;   
    var reporturl = '/cgi-bin/koha/reports/guided_reports.pl?reports=' + reportnumber + '&phase=Run+this+report&param_name=biblionumber&sql_params=' + biblionumber;
    var newin = window.open(reporturl,'popup','width=1280,height=720,resizable=no,toolbar=false,scrollbars=yes,top');
});
/// LOPPU ///
```

**Comment by atarnus** [comment]
Lisätty nyt tällaisena Lappi testille ja nextille.
Voisin vielä muokata ja lisätä en/sv käännökset linkkitekstiin, raportti tietysti sitten avautuu vain yhdellä kielellä.

**Comment by atarnus** [comment]
JS-rimpsu kielivalinnan kanssa:

/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 

    // Kielivalinta
    var labelname = 'Lainatilasto';
    var linkname = 'Raportti';
    if ( document.documentElement.lang.toLowerCase() === "en" ) {
	  labelname = 'Circulation statistics';
      linkname = 'Report';
	} else if ( document.documentElement.lang.toLowerCase() === "sv-se" ) {
      labelname = 'Utlåning statistik';
      linkname = 'Rapport';
  	}

    // Linkin luonti
    $('#catalogue_detail_biblio div.page-section').append('<span class="results_summary"><span class="lainatiedot label">' + labelname + ': </span><a id="lainatiedot" href="#">' + linkname + '</a></span>');
  }  
});

$('body').on('click', '#lainatiedot', function(e) {
  e.preventDefault();
    var reportnumber = 708;   

    var reporturl = '/cgi-bin/koha/reports/guided_reports.pl?reports=' + reportnumber + '&phase=Run+this+report&param_name=biblionumber&sql_params=' + biblionumber;
    var newin = window.open(reporturl,'popup','width=1280,height=720,resizable=no,toolbar=false,scrollbars=yes,top');
});
/// LOPPU ///

**Comment by atarnus** [comment]
Lisätty Vaara ja Helle Nexteille käännösten kanssa.

**Comment by Kati-Helle** [comment]
Helle-nextissä olen tarkistanut vain yhden tietueen niteiden osalta. Raportti näyttää oikeat lukemat.

Vertasin raportin nidekohtaisia lukemia tietueen (bilbionumber=1611059) niteen muokkausnäytöllä näkyvän nideluettelon nidetunnuskohtaisiin lukemiin (keltaisena näkyvä nide valittuna nidemuokkaukseen).

Vasemmalla raporttituloksen näkymä, oikealla kuvakaappaus tietueen niteen muokkausnäytöltä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ee8229f4-3ffd-46b0-9425-a7745be5c730)

**Comment by Kati-Helle** [comment]
Testasin vielä Helle-nextissä niin, että poistin tietueelta biblionumber=1601549 yhden niteen (nextissä ei ollut poistettuja niteitä).

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ae697e7d-ef9b-4bef-8109-9640e6db03d9)

Poistettu nide näkyy Lainatilasto-raportilla, tiedoissa mm. Poistopvm-arvo
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/af8c5469-5594-4e29-841d-5da1991c8962)

**Comment by ElinaUotila** [comment]
Samaa olin juuri testaamassa kuin Katikin, eli poistettu nide näkyy raportilla ja raportin yhteissumma täsmää:  
![image](https://github.com/KohaSuomi/Koha/assets/112157980/0a31416d-ddd4-4f51-b4d9-d93a3a952016)

**Comment by ElinaUotila** [comment]
Testasin yhdellä tietueella myös Kirkes-testillä. Vertasin raportin lukemia kunkin niteen lainamääriin, ja kaikki oli oikein. Myös poistettu nide tuli raportille oikein.

**Comment by ajrajala** [comment]
> 
> Lisäksi ois mukava kuulla muiden mielipiteitä, että minkä sarakkeen mukaan olisi parasta tiedot järjestää? Määrän mukaan on ihan jees, mutta tuleeko kokoelmatyössä katsottua enemmänkin oman kirjaston niteitä, jolloin kotikirjaston mukaan järjestäminen olisi järkevämpää?

Komppaan tuota kotikirjaston mukaan järjestämistä, kokoelmatyön näkökulmasta se tuntuisi järkevimmältä.

Vaski-testille lisätty raportti ja linkki Tietue-sivulle. Kuten edellä jo kommentointiinkin niin määrät näyttävät täsmäävän.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii oikein. Kotikirjaston mukaan järjestäminen olisi minustakin hyvä ominaisuus.

**Comment by atarnus** [comment]
Tulokset on tosiaan tuossa viimeisimmässä versiossa aakkostettu jo sen kotikirjaston mukaan. Tuloksista voinee pudottaa pois tuon kirjastokoodi-rivin, eli raportin kolmannen rivin:
`CASE WHEN e.itemnumber = 'Niteet yht.' THEN '' ELSE e.homebranch END AS Kirjastokoodi,`

homebranch tieto kuitenkin tarvitaan itse haussa, niin se saa olla mukana noissa sisemmissä SELECTeissä.

Kunhan JS-rimpsu on sitten paikoillaan, niin itse raportin sisältöähän voi helposti vielä muuttaa tarpeen mukaan ohjatuista raporteista.

**Comment by lmstrand** [comment]
Nexteille on aennettu raporttilinkin lisäävä intranetUserJS-plugin, johon voi konfiguroida käytettävän raportin ID:n.

**Comment by AnneliO** [comment]
OUTI-nextillä tulee Virhe 500, kun klikkaa liitännäisen kohdalla Määrittele.

**Comment by atarnus** [comment]
Lapissa, Outissa ja Hellessä toimii nyt. Siilistä en löytänyt konffausvalintaa pudotusvalikosta.
![image](https://github.com/KohaSuomi/Koha/assets/63994411/2b50d475-6a0c-415b-ba80-eba3e68f2b6a)

Joku ääkkösongelma mahtanee vielä myös olla. Tässä kuva, jossa on käytössä sekä intranet.js että plugin:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/006a6aeb-1b5d-45fd-9d6d-9a3650d6024f)

**Comment by lmstrand** [comment]
Korjasin tuon ääkkösongelman.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii.

**Comment by PiaKusmin** [comment]
Lapin testillä näyttää toimivan halutulla tavalla.

**Comment by ElinaUotila** [comment]
Kirkesin Nextillä näyttää toimivan.

**Comment by MikkoLiimatainen** [comment]
Vaski Nextilläkin toimii

**Comment by AnttHeik** [comment]
Onkohan se hyvä juttu, että tuo linkki raporttiin näkyy osakohteissakin?

![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/78cc3ead-e98a-4d6d-b615-350eade5ebd4)

**Comment by pknuuti** [comment]
Ei ole mitään järkeä näyttää tuota raporttia osakohteissa. Saisikohan sen linkin niistä pois?

**Comment by atarnus** [comment]
```
/// ALKU ///
// Linkki lainatilastoraporttiin tietueen pääsivulla
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') { 
    var osakohde = document.getElementsByClassName('in');
    if (osakohde.length < 1) {

      // Kielivalinta
      var labelname = 'Lainatilasto';
      var linkname = 'Raportti';
      if (document.documentElement.lang.toLowerCase() === "en" ) {
        labelname = 'Circulation statistics';
        linkname = 'Report';
      } else if (document.documentElement.lang.toLowerCase() === "sv-se" ) {
        labelname = 'Utlåning statistik';
        linkname = 'Rapport';
      }

      // Linkin luonti
      $('#catalogue_detail_biblio div.page-section').append('<span class="results_summary"><span class="lainatiedot label">' + labelname + ': </span><a id="lainatiedot" href="#">' + linkname + '</a></span>');
    }  
  }
});
```

Tuonne lisätty siis toinen if, joka tsekkaa löytyykö sivulta classia 'in'
```
    var osakohde = document.getElementsByClassName('in');
    if (osakohde.length < 1) {
    }
```

Voisiko @lmstrand päivittää jossain välissä plugariin?

**Comment by lmstrand** [comment]
> Ei ole mitään järkeä näyttää tuota raporttia osakohteissa. Saisikohan sen linkin niistä pois?

Muutos pluginin rimpsuun on päivitetty nexteille. Testaatteko, että toimii toivotusti?

**Comment by pknuuti** [comment]
Pitääkö minun tehdä jotain nextille? Ainakin tässä tietueessa on edelleen Raportti-linkki, vaikka tämä on osakohteen tietue:
https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=10724573&searchid=scs_1712225993208

**Comment by lmstrand** [comment]
> Pitääkö minun tehdä jotain nextille? Ainakin tässä tietueessa on edelleen Raportti-linkki, vaikka tämä on osakohteen tietue: https://vaara-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=10724573&searchid=scs_1712225993208

Teillä on tuolla intranetUserJS-asetuksessa tuo skripti lisättynä. Se lisätään sivustoille pluginilla tässä tapauksessa. Pluginin nimi on IntranetUserJS: Checkout report link. Siitä on hävinnyt määrittelystä raportin id myös.

Eli siis: poistakaa tuo rimpsu intranetUserJS-järjestelmäasetuksesta. Se nyt varmaan ylikirjoittaa pluginin mukana tulevan korjatun rimpsun. Myös tuo raportti-id pitää lisätä pluginin määrittelyyn uudelleen, on jostain syystä tyhjä.

**Comment by lmstrand** [comment]
ps. piilotin tiketistä js-rimpsut näkyvistä väärinkäsitysten välttämiseksi. Me siis ylläpidämme/päivitämme rimpsuja plugin-tietovarannoissa ja virkailijaliittymään lisättävää rimpsua voi tarkastella pluginin "Käynnistä työkalu"-toiminnolla.
Linkin pitäisi olla kadonnut osakohteilta nexteillä, jos rimpsua ei ole lisätty käsin intranetUserJS-järjestelmäasetukseen.

**Comment by pknuuti** [comment]
Ei toimi oikein. Ei kai mennyt emostakin linkki pois, vaikka piti mennä vain osakohteista? Kirjassa linkki näkyy, cd-tietueessa ei.

**Comment by lmstrand** [comment]
Ok kiitos testeuksesta. Tutkitaan asiaa.

**Comment by AnneliO** [comment]
Mie luulen, että se piilotus ottaa nyt kiinni Osakohteet-välilehden Teoksessa-riveihin:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/9ae190ec-1f99-45c2-9bb0-0aa44f55561e)

**Comment by atarnus** [comment]
Joo. Näemmä on uudessa versiossa tuo osakohteet välilehtien span class muuttunut sourcesta siihen inniin. Eli ongelma on tosiaan nyt nexteillä tämän kanssa. Katselenpa miten nuo kannattaisi nyt erottaa toisistaan.

**Comment by lmstrand** [comment]
Korjaus on viety nexteille.

**Comment by Kati-Helle** [comment]
Helle-nextissä vaikuttaa toimivan oikein. Esimerkiksi
- musiikkiäänitteen osakohteessa raporttia ei ole, kun taas ko. osakohteen emossa oikein toimiva raportti on.
- kirjan osakohteessa raporttia ei ole, kun taas ko. osakohteen emossa oikein toimiva raportti on.

**Comment by MikkoLiimatainen** [comment]
Emokohteissa raportti on ja osakohteissa ei. Toimii oikein.

**Comment by AnneliO** [comment]
Tämä toimii, suljen tiketin.
