### ISSUE TITLE
Kyyti: tietue, joka ei ole tietokannassa, näkyy hakutuloslistalla

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1112]
### Mikä vikana?

Kyytissä tulee tiedonhaussa kaksi tietuetta, kun hakee nidenumerolla 28622120800167.

Tietue 1500602 näkyy vain hakutuloslistassa, kun sitä klikkaa Koha ilmoittaa, että "Tietuetta 1500602 ei ole tietokannassa". 

Toinen tietue 1516093 ja siihen liitetty nide toimivat normaalisti.

Saisiko tuon tietueen 1500602 pois näkyvistä.

Ei ole tietoa, miten tilanne on syntynyt. Deletedbiblio-taulusta en löytänyt biblionumberilla 1500602. Alun perin tilanne oli se, että nide 28622120800167 oli kiinni vain tietueessa 1500602, mutta pääkäyttäjäkokouksen vinkkien perusteella liitin niteen toimivaan tietueeseen 1516093.

**Comment by lmstrand** [comment]
Tietue poistettu indeksistä.

**Comment by Tuomas-Kyyti** [comment]
Kiitos, asia kunnossa.
