### ISSUE TITLE
Vaski: Ilpoisten varausten keskeytys remontin ajaksi

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1113]
### Tukipyyntö

Keskeytetään määräajaksi Ilpoisten kirjaston tärppäämättömät ja keskeyttämättömät tai remontin aikana aktivoituvat varaukset varaukset.

Kirjasto TUIL
Vain tärppäämättömät varaukset
Vain keskeyttämättömät ja remontin aikana aktivoituvat varaukset
Keskeytys tehdään 25.3.2024
Keskeytys päättyy 17.6.2024

`SELECT reserve_id
FROM reserves
WHERE branchcode = 'TUIL'
AND found IS NULL
AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-03-25' AND '2024-06-17'))`

**Comment by paxed** [comment]
Keskeytys tehty yo rajauksella, muutos koski 1661 varausta.

**Comment by MikkoLiimatainen** [comment]
Kiitos!
