### ISSUE TITLE
Hankintoja tehdessä, kun tietueen poimii ulkoisista tietokannoista, muodostuu kaksi 000-kenttää

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1114]
### Mikä vikana?

Oulun luetteloinnissa ja hankinnassa on huomattu, kun tekee Kohassa itse hankintoja ja poimii valmiin tietueen ulkoisesta lähteestä, niin jostain syystä tietueelle muodostuu kaksi 000-kenttää:

Esimerkit:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/97e70c5d-10d1-47ac-8482-1007998ca287)
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2306843

![image](https://github.com/KohaSuomi/Koha/assets/98814860/2c8aad7d-30c9-4b5c-a2a7-87da1a60d9b9)
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2304404

Tätä ei kuitenkaan näe, jos avaa tietueen muokattavaksi luettelointieditorilla. Tallennuksen jälkeen toinen 000-kenttä katoaa. Näitä tietueita on tullut vastaan aineistotyypittömien tietueiden listoilla. Eli jos ei muista käydä laittamassa 942c-kenttään aineistotyyppiä heti kun tekee tilauksen, niin tietueille jää kaksi 000-kenttää, joista alimmainen ”nam a22 8i 4500” -kenttä on turha.

Sama tilanne muodostuu myös, jos Hankinnan lomakkeella tekee tyhjästä uuden tietueen. Ennen kuin tietueen aukaisee muokattavaksi kuvailueditorilla Marcin esikatselu näyttää, että tietueella olisi kaksi 000-kenttää, joista toisena on tuo ”nam”-versio.

Heikkisen Antin päätelmä: 
”Jos ymmärrän oikein, niin vika tulee siinä vaiheessa, kun tietue luodaan tai tuodaan ulkoisesta lähteestä, ja se tallentuu ensimmäisen kerran Kohassa MARC-tiedostoksi (onkohan se just MARCXML-tiedosto nimeltään?). Tuo toiseen 000-kenttään tuleva rimpsu on sellainen, joka yleensä laitetaan oletusarvoksi tekstiaineiston kuvailupohjaan. Voiko olla, että Koha ottaisi jostakin Hankintaan linkitetystä kuvailupohjasta tuon tiedon ja lisäisi sen sitten tietueeseen tuplakenttänä, eli se ei tavallaan noudata sääntöä, ettei tietueella voi olla kuin yksi 000-kenttä? Onkohan tätä huomattu jo yhteisön puolella?”

### Mitä pitäisi tapahtua

Toista kenttää ei pitäisi syntyä poiminnassa tietueelle ollenkaan.

**Comment by AnneliO** [comment]
Hankinta-osiossa kun lisää tietueen, käytetään tietueille ilmeisesti ACQ-kuvailupohjaa. Tuon pohjan 000-kentällä on oletusarvona "     nam a22     8i 4500", joten se lisättiin tietueelle. Kun ACQ-kuvailupohjasta poistaa oletusarvon, syntyy tietueelle vain yksi 000-kenttä. 

Sama 000-kentän tuplaantuminen tapahtuu myös silloin, kun tietue lisätään uudesta tyhjästä tietueesta. Voisiko oletusarvon vain poistaa ACQ-kuvailupohjan 000-kentästä?

**Comment by AnttHeik** [comment]
Ok, eli se ei ymmärrä yhdistää noita oletusarvoja uuden tietueen 000-kenttään eikä jättää oletusarvoja pois, jos tuodaankin täysitietue. Minä poistan nuo oletusarvot, se on varmaankin helpoin ratkaisu, koska nuo hankintatietueet pitäisi muutenkin muistaa käydä muokkaamassa aina.

**Comment by pirliis** [comment]
Tämä taisi ratketa Anneli ehdottamalla tavalla. Suljen tiketin.

**Comment by pirliis** [comment]
Jep, mainitsen huomenna.
