### ISSUE TITLE
EDItX-dokumentaation päivitys

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1119]
### Tukipyyntö

[EDItX-hankinnan dokumentaatio](https://github.com/KohaSuomi/kohasuomi.github.io/blob/master/_docs/editx.md) ei ole ajantasalla erityisesti Koha-palvelimen osalta. Dokumentaatio kaipaa päivitystä.

**Comment by CodoDerDritte** [comment]
Tämä on #805 duplikaatti, joten suljen.
