### ISSUE TITLE
Uusi työkalu Varausten erämuokkaus: Mahdollisuus olla muokkaamatta noutokirjastoa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1126]
### Kehitysehdotukseni

Saisiko kehitteillä olevaan Varausten erämuokkaus -toimintoon valittavaksi vaihtoehdon, jossa noutokirjastoa ei muokata.
Modify holds / New pickup library -kohdasta puuttuu kirjastoton/arvoton vaihtoehto.

Helle-testistä kuva
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/44085bc7-260e-4041-b361-74bdc7bc5136)

**Comment by Kati-Helle** [comment]
Kiitos, nyt toimintoa on mahdollista käyttää noutokirjastoa muokkaamatta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f63a7c08-93fb-407c-9e52-9e42043133b2)

**Comment by johannaraisa** [comment]
Voiko tämän sulkea?

**Comment by Kati-Helle** [comment]
Joo. Toimii nyt toivotusti. Suljen tiketin.
