### ISSUE TITLE
Vaski: Kutsumanimen piilotus tietyiltä asiakaslajeilta

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1127]
### Tukipyyntö

Saisiko Vaskin tuotannon IntranetUserJS-asetuksiin seuraavan rimpsun, jolla piilotetaan Other names-kenttä asiakaslajeilta: "YHTEISO", "KAUKOLAINA", "AUTOM", "EITILASTO", "VIRKAILIJA", "API". 
Liittyy tikettiin https://github.com/KohaSuomi/Koha/issues/956 

///ALKU///

// Piilottaa 'Other names' kentän valituille asiakastyypeille (categorycode) muokkauslomakkeilla (add, modify, duplicate)
$(document).ready(function () {
if ( window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' ) {
var categories = ["YHTEISO", "KAUKOLAINA", "AUTOM", "EITILASTO", "VIRKAILIJA", "API"];
if ( ( window.location.search.includes('?op=add') && categories.some(cat => window.location.search.includes(cat)) ) || ( ( window.location.search.includes('?op=modify') || window.location.search.includes('?op=duplicate') ) && categories.some(cat => $('.patroncategory')[0].innerHTML.includes(cat)) ) ) {
$('#othernames').attr('disabled', 'disabled');
// Piilottaa li-elementin, jonka sisällä on label ja input
$('#othernames').parent().hide();
}
}
});
///LOPPU///

**Comment by ajrajala** [comment]
> Tällä rimpsulla on tosiaan vain tuo yksi muuttuja. Sen voisi tehdä JS-plugariksi ja antaa kimppojen itse määritellä omat categorycodensa asetuksista.
> 
> Tämä muuten sekä disabloi kentän että piilottaa sen. Disabloinnin voi varmaankin poistaa. `$('#othernames').attr('disabled', 'disabled');`

Kuulostaisi järkevältä. Pitäisikö meidän tehdä tästä kehitysehdotus jos tämän sitten jossain vaiheessa saisi js-plugariksi?

**Comment by AnneliO** [comment]
> Kuulostaisi järkevältä. Pitäisikö meidän tehdä tästä kehitysehdotus jos tämän sitten jossain vaiheessa saisi js-plugariksi?

Lari sai projektiksi käydä läpi kaikki meidän JS-rimpsut ja tarkistaa, missä ne on käytössä. Sen jälkeen pohdimme Koha-Suomen palaverissa, mitkä rimpsut kannattaisi plugarisoida. Ei siis tarvitse tehdä erillistä tikettiä. :)
