### ISSUE TITLE
OUTI: Muhoksen kirjaston uudet SIP2-tunnukset

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#1130]
### Tukipyyntö

Support-postiin on laitettu pyyntö Muhoksen kirjaston omatoimiovikoneen SIP2-tunnusten lisäämisestä OUTIn automaattipalvelinten konfiguraatioon, palvelinryhmään outi-outi.

Asennus tehdään 16.-18.4.2024, joten tunnusten tulisi olla käytössä 15.4.2024 mennessä.

**Comment by lmstrand** [comment]
Lisätty sip-palvelinkonfiguraatioon. Käytettävissä huomisesta alkaen.

**Comment by velimarj** [comment]
Kiitokset, suljenpa tämän siis.
