### ISSUE TITLE
Vaski: eräpäivien siirtopyyntö

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1131]
### Tukipyyntö

Turun pääkirjastossa oli unohdettu sulkea eräpäiväkalenteri pääsiäiseltä, jonka seurauksena ehti tulla yli 800 varausta, jonka noutopäivä on kiinniolopäivä 29.3. Nämä noutopäivät pitäisi siirtää ennen kuin noutomuistutus lähtee 27.3.

Yksiköstä TUPK noudettavat varaukset, joiden viimeinen noutopäivä on 29.3.2024 siirretään noudettavaksi viimeistään 2.4.2024.

**Comment by lasse-koha** [comment]
Muutos tehty. Varauksia oli 529, ilmeisesti siis osa jo noudettu.
