### ISSUE TITLE
Lappi: Rovaniemen pääkirjaston remontti : niteet

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1132]
### Tukipyyntö

Toimenpiteet koskevat toimipisteitä: ROPK (Rovaniemen pääkirjasto) ja ROLO (Rovaniemi Lappi-osasto). 

Rovaniemen pääkirjasto menee remonttiin vuodeksi ja muuttaa väistötiloihin. Väistötilaan otetaan mukaan vain osa kirjaston aineistosta, osa menee varastoitavaksi. Tarvitsemma seuraavia toimenpiteitä aineistolle:

Kaikille saatavilla oleville niteille, joiden kotikirjasto on ROPK tai ROLO muutetaan not_loan arvo 9. Jos niteellä on jo jokin muu not_loan arvo, siihen ei kosketa (esim. 6 laskutettu, -1 tilattu). Muutoksesta jätetään myös pois lainassa olevat, kuljetettavana olevat ja noutoa odottavat niteet.

Muutos tulisi tehdä 30.4.2024. HUOM. Mikäli lähtevä aineisto saadaan pakattua aiemmin, muutosajolle voi olla tarve jo aiemmin huhtikuussa. 

Arvon poistamisesta ilmoitetaan myöhemmin (kun on päästy takaisin omiin tiloihin väistötiloista).

**Comment by lmstrand** [comment]
Sopiiko, jos toimitamme raportin niteistä, joiden not_loan- tila tulisi vaihtaa (kuvauksen mukaisilla ehdoilla), ja tekisitte muutoksen itse niteiden erämuokkaustyökalulla oman aikataulunne mukaan?

**Comment by lmstrand** [comment]
Noita muutettavia niteitä onkin niin paljon (yli 300 tuhatta), että ehkä on järkevä tehdä suoraan tietokanta-ajona :D.

**Comment by LeenaKinnunen** [comment]
Aivan, suurin osa kokoelmasta jää tänne lukkojen taakse, eli ei mielellään tehdä sitä itse :)

**Comment by lmstrand** [comment]
Laitan ajon ylös odottamaan ajoa tähän tikettiin:
```
update items set notforloan=9 where homebranch in ('ROPK', 'ROLO')
and notforloan=0 
and onloan is null
and itemnumber not in (select itemnumber from reserves where found in ('W', 'T'))
```

**Comment by LeenaKinnunen** [comment]
@lmstrand : Aineistot on nyt pakattu ja siirretty Asemakirjastolle, joten tämän ajon saisi tehdä heti kun vain pystyt?

**Comment by lasse-koha** [comment]
Ajo tehty.

**Comment by LeenaKinnunen** [comment]
Huomattiin, että osalle aineistoja, jotka ajon pitäisi kattaa, ei ole tullut tilaa 9. Esim. 
[biblionumber=952550](https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=952550)
[biblionumber=399494](https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=399494).
Vastaavia on tullut esille myös ROPK-havainto-osaston niteissä. 

Ajo jouduttiin tekemään kaksi kertaa, koska alkuperäisessä pyynnössä olin väärin kirjoittanut "kotikirjasto", vaikka tarkoitus oli olla havaintokirjasto. Uusi ajo tehtiin havaintokirjaston mukaan.

**Comment by lmstrand** [comment]
Ajettu:
```
create table ks_20240418_items_1132_3 like items;

insert into ks_20240418_items_1132_3
    -> (
    -> select * from items where holdingbranch in ('ROPK', 'ROLO')
    -> and notforloan=0 
    -> and onloan is null
    -> and itemnumber not in (select itemnumber from reserves where found in ('W', 'T'))
    -> and itemnumber not in (select itemnumber from branchtransfers where datearrived is null AND datecancelled is null)
    -> );
Query OK, 21683 rows affected (11.176 sec)
Records: 21683  Duplicates: 0  Warnings: 0

MariaDB [lappiprod]> update items set notforloan=9 where itemnumber in 
    -> (select itemnumber from ks_20240418_items_1132_3);
Query OK, 21683 rows affected (11.084 sec)
Rows matched: 21683  Changed: 21683  Warnings: 0
```

**Comment by lmstrand** [comment]
ks_20240418_items_1132_2 -taulussa on tallessa OR-ehdolla ajettujen niteiden ennen ajoa ollut tila.

**Comment by LeenaKinnunen** [comment]
Asia hoidettu, seuljen tiketin.
