### ISSUE TITLE
Lappi: Noudettavissa ja kuljetuksessa olevien varausten noutopaikan vaihto

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1133]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: ROPK (Rovaniemen pääkirjasto).

Kirjastosta ROPK noudettavissa oleviin varauksiin ja toimipisteeseen ROPK kuljetuksissa oleviin varauksiin tehdään seuraavat muutokset:
Varausten noutopaikka muutetaan ROPK -> ROPO: 

Muutos tulisi tehdä 12.4.2024, jolloin varaukset fyysisesti siirretään ROPO:on. 

Henkilökunta hoitaa itse uusien (ajon jälkeen tehtyjen) varausten noutopaikan muutoksen. ROPK jätetään tarkoituksella noutopaikaksi.

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [lappiprod]> update reserves set branchcode = 'ROPO' where branchcode = 'ROPK' and found in ('T', 'W');
Query OK, 959 rows affected (0.077 sec)
Rows matched: 959  Changed: 959  Warnings: 0
```

**Comment by LeenaKinnunen** [comment]
Muutokset ok, suljen tiketin.
