### ISSUE TITLE
Lappi: Tärppäämättömien varausten noutopisteen muutos

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1134]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: ROPK (Rovaniemen pääkirjasto).
Varausten, joiden noutopiste on ROPK noutopiste muutetaan Asemakirjastoksi ROLO. 

Tärppäämätön varaus, noutopiste ROPK, muutetaan ROPK-> ROPO. 

Muutos tulisi tehdä 12.4.2024, jolloin Rovaniemen pääkirjaston varausten nouto siirretään Asemakirjastoon.

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [lappiprod]> UPDATE reserves set branchcode = 'ROPO' WHERE branchcode = 'ROPK' AND found IS NULL;
Query OK, 3375 rows affected (0.089 sec)
Rows matched: 3375  Changed: 3375  Warnings: 0
```

**Comment by LeenaKinnunen** [comment]
Muutokset kunnossa, suljen tiketin.
