### ISSUE TITLE
Lainaus-välilehdellä ongelma istunnon aikakatkaisuun liittyen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1135]
### Mikä vikana?

Vaskissa on raportoitu tilanteista, joissa istunnon aikakatkaisun jälkeen tapahtuneen uudelleenkirjautumisen jälkeen Koha heittää käyttäjän uudestaan ulos. Alla kuvaus siitä, miten ongelman ainakin saa toistumaan. Kuvauksen mukainen tilanne toistuu siis nimenomaan silloin, kun käytetään Lainaus-välilehteä. Vastaavaa ei tapahdu jos käyttää asiakkaan Tiedot-välilehteä.

### Kuinka toistaa ongelma/asia

1. Muuta timeout-järjestelmäasetukseen jokin sopivan lyhyt aika testaamista varten
2. Hae joku asiakas ja siirry Lainaus-välilehdelle
3. Odota, että aikakatkaisu tulee täyteen ja klikkaa Lainat-napista asiakkaan lainat näkyville
4. Huomaa, että lainat eivät aikakatkaisun takia lataudu
5. Klikkaa vasemman laidan valikosta uudelleen Lainaus-välilehteä
6. Siirryt nyt aikakatkaisun takia kirjautumissivulle, kirjaudu uudelleen sisälle
7. Klikkaa taas vasemman laidan valikosta Lainaus-välilehteä ja huomaa, että Koha heittää käyttäjän uudestaan kirjautumissivulle
8. Kirjaudu vielä sisään ja yritä tällä kertaa tehdä joku tiedonhaku käyttämällä "Hae tietokannasta" -kenttää
9. Huomaa, että Koha heittää käyttäjän uudestaan kirjautumissivulle
10. Kirjaudu vielä sisään, nyt käyttäjälle aukeaa äsken tehdyn tiedonhaun tulokset. Jos nyt siirryt jollekin toiselle sivulle, ei Koha heitä enää ulos.

**Comment by ajrajala** [comment]
Ehdin nyt testata tätä nextillä enkä saa siellä ongelmaa toistumaan tuolla nimenomaisella tavalla, joten versiopäivitys voisi hyvinkin korjata tämän mystisesti vain meillä ilmenevän ongelman.

**Comment by lmstrand** [comment]
Voisiko tämä yhteisön tiketti liittyä ongelmaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34478. Tilana pushed to main. Voisi testata, onnistuuko ongelman toistaminen enää yhteisön sandboxissa. Tuo on kyllä aika mahdoton tuoda tähän versioon.

**Comment by lmstrand** [comment]
Pääkäyttäjäkanavan kommentista päätellen ongelma on edelleen olemassa Vaskissa nyt versionvaihdon jälkeen.

**Comment by MikkoLiimatainen** [comment]
Juu, meillä on tosiaan edelleen havaittu uudelleenkirjautumisluuppi. Tällä kertaa ongelman näyttäisi aiheuttavan se, että uudelleenkirjautumisessa epäonnistutaan ensimmäisellä kerralla. Ilman virheellistä kirjautumista luuppia ei synny. Sain toistettua ongelman näin:

1. Kohan etusivu oli auki aikakatkaisun tapahtuessa.
2. Yritin mennä yläpalkin kautta lainaukseen syöttämällä siihen asiakkaan kirjastokortin.
3. Aukesi uudelleenkirjautumissivu.
5. Tein virheellisen kirjautumisyrityksen ja sitten kirjauduin sisään oikein.
6. Yritin lainata asiakkaalle niteen, jolloin päädyin uudelleenkirjautumissivulle.
7. Kirjauduin oikein.
8. Lainaus meni läpi ja yritin lainata toisen niteen, jolloin päädyin taas uudelleenkirjautumiseen.
9. Kirjauduin oikein.
10. Lainaus meni läpi ja jatkoin lainaamista, jolloin tapahtui taas uloskirjautuminen.

Tätä olisi varmaan voinut jatkaa loputtomiin. Tämän ongelman yhteydessä meille on myös kerrottu virkailijan kirjautumiskirjaston vaihtuneen mystisesti, mutta sitä ei kyllä testeissäni tapahtunut.

**Comment by MikkoLiimatainen** [comment]
Sain nyt tuon alkuperäisenkin ongelman toistettua vain tekemällä uudelleenkirjautumisessa ensin virheellisen kirjautumisen, kun aiemmin ongelma ilmeni oikein kirjautuessakin. Eli ongelma on tosiaan edelleen olemassa, vaikka se on hieman muuttunut.

**Comment by ajrajala** [comment]
En saa nextillä enää toistumaan ongelmaa alkuperäisellä tavalla enkä Mikon kuvaamalla tavalla. Mutta ehkä hyvä, jos joku muukin vielä kokeilee.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä enkä saanut virhettä toistumaan. Testasin Mikon testisuunnitelman mukaan. Kohtaan 6 asti tein samalla tavalla, mutta senkään jälkeen ei tullut enää mitään uudelleenkirjautumisia, vaan sain lainattua useita niteitä ilman erillisiä kirjautumisia. Kävin välill Tiedot-välilehdellä eikä ongelmia ollut senkään jälkeen Lainaus-välilehdellä.

**Comment by emta001** [comment]
Vaikuttaisi korjaantuvan versiossa 24. Odotetaan siis vielä seuraavaan versionvaihtoon ja katsotaan onko ongelma oikeasti korjaantunut.

**Comment by emta001** [comment]
Tätä voisi taas testata kun uusi versio on nyt alla.

**Comment by ajrajala** [comment]
Vaskin tuotannossa testasin tätä Mikon testisuunnitelman mukaan enkä saanut ongelmaa toistumaan.

**Comment by ajrajala** [comment]
Suljen tiketin kerta tätä ei ole enää 24-versiossa onnistuttu toistamaan.
