### ISSUE TITLE
Kyyti: Pyhtään uuden automaatin lainojen uusinta -ongelma

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1137]
### Mikä vikana?

Pyhtään uuden automaatin lainojen uusinta -toiminnassa on jokin ongelma. Lainaus ja palautus toimivat.

"Meille asennettiin juuri uusi lainaus-/palautusautomaatti. Näiden toimintojen lisäksi sillä pitäisi voida uusia lainat. Testissä huomattiin, että se ei palauta asiakkaan tietoja Kohasta. Hakee kyllä, mutta paluuviestissä on vain N-kirjaimia ja näin ollen ruutu pysyy otsikkoja lukuunottamatta tyhjänä. Asentaja pyysi ottamaan yhteyttä järjestelmän pääkäyttäjään."

Supan automaatti: https://kyyti.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=303460

Mitä ja kenen pitäisi tehdä?

**Comment by lmstrand** [comment]
Lokeilla ei näy ollenkaan tapahtumia tuolla uudella automaattitunnuksella, oletan että automaatille on ohjelmoitu jokin väärä tunnus.

**Comment by lmstrand** [comment]
Tarkastatteko/korjaatteko automaatille käyttöön uuden tunnuksen/salasanan ([borrowernumber=303460](https://kyyti.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=303460). Ongelma voi johtua siitä, että automaatti käyttää jonkin toisen automaatin tunnuksia nyt yhtäaikaisesti. Jos ei auta uusintaongelmaan, niin selvitellään lisää.

**Comment by lmstrand** [comment]
Vaikuttaa myös tilastoihin, kun automaatti/sip-palvelin ei käytä oikeaa yksikkötunnusta.

**Comment by Tuomas-Kyyti** [comment]
Tämä on kuulemma korjaantunut jotain muuta kautta.
