### ISSUE TITLE
Hyllyvarausraportissa värikoodaus seudun mukaan

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1138]
### Kehitysehdotukseni

Hyllyvarausraportissa värikoodaus on todettu erittäin toimivaksi ratkaisuksi siinä, kun varauksen sijaintikirjasto ja paikalla oleva teos täsmäävät. 
![MLI_PK](https://github.com/KohaSuomi/Koha/assets/129748294/af39c82a-6b76-4da5-b00a-cbf78983ef0b)

Toiveena olisi, että samanlaisen värikoodauksen saisi myös seudulla olevaan varaukseen, jotta kuljetuksia voisi vähentää ja näin hyödyntää mahdollista seudullista kellutusta. Esimerkiksi Mikkelin pääkirjaston (MLI_PK) kohdalla olisi värikoodaus, kun varaus on tehty Anttolaan (MLI_ANT). Tällöin varausta ei poimittaisi vahingossa esimerkiksi Savonlinnasta. Värikoodina voisi käyttää toista väriä, jotta sekaannuksia ylemmän värikoodin kanssa ei tulisi.

![MLI_ANT](https://github.com/KohaSuomi/Koha/assets/129748294/e7713f37-4601-4b9c-aa4a-e1c3a72a84d5)

**Comment by ajrajala** [comment]
Tätä samaa on toivottu myös Vaskissa. Toimisiko, jos värin lisäksi korostuksessa käytettäisiin esim. alleviivausta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/93ca74ff-a3cf-4b50-83eb-4ae8efbad678)

**Comment by pknuuti** [comment]
Kannatan myös Vaaran puolesta tätä värikoodausta. Erottuisi helpommin kelluvat kirjastot.

**Comment by lmstrand** [comment]
Tästä on prototyyppi testattavana testillä. Luo kirjastoryhmä/ryhmiä, minkä nimi alkaa sanalla "VARAUSRYHMA". Jos hyllyvarauslistan varaus-sarakkeen tieto (hold at) täsmää tämän/näiden ryhmien kanssa hyllyssä (on shelf)-sarakkeen kanssa, pitäisi kirjastoykiskkötunnuksen olla lihavoitu ja sininen.

**Comment by pknuuti** [comment]
Päivittyykö hyllyvarausryhmä automaattisesti testillä? Kun olen lisännyt varausryhmän, pitääkö tehdä vielä jotain muuta? Ei ainakaan heti näy muutos.

**Comment by piiaseme** [comment]
OUTIn testillä tein VARAUSRYHMA Oulu -nimisen ryhmän. Valitsin nämä vaihtoehdot ryhmälle: 
    - Käytä virkailijaliittymän hakuryhmille
    - Paikallinen varausryhmä
Oliko jotain muuta ryhmän teossa huomioon otettavaa, kun ei näy boldilla/sinisenä Oulun kirjastoja.

**Comment by lmstrand** [comment]
Pitäisi suorilta alkaa näkyä. Onkohan testien päivityksessä ollut jokin ongelma. Käyn tutkimassa.

**Comment by lmstrand** [comment]
Koodi ei ollut päässyt testiympäristöjen päivitykseen mukaan, nyt se on paikallaan ja testauksen pitäisi onnistua.

**Comment by lmstrand** [comment]
Hyllyvarauslista päivittyy automaattisesti Vaara-testillä (1min välein). Outi-testillä 5 minuutin välein, vaihdoin ajettavaksi joka minuutti.

**Comment by piiaseme** [comment]
Oulun hyllyvarausryhmään kuuluvat kirjastot eivät ole sinisiä/boldilla joka varauksen kohdalla. Esim. 
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/4d656f6b-7c13-482c-abb1-14179c8495f9)

**Comment by LeenaKinnunen** [comment]
Sama virhe kuin Outilla em. kommentissa. Ko. kirjastot Lapissa kuuluvat samaan varausryhmään. 
![image](https://github.com/KohaSuomi/Koha/assets/99165331/06e7cc04-c33f-41b0-a142-cb23d552765c)

**Comment by lmstrand** [comment]
Ainakin tarkastus tehtiin vain joka toiseen taulun elementtiin, nyt jokainen rivi käsitellään.

**Comment by LeenaKinnunen** [comment]
Lapissa näkyy nyt oikein.

**Comment by pknuuti** [comment]
Nyt näyttää hyvältä Vaarankin testillä.

**Comment by pknuuti** [comment]
Siirretäänkö testiltä valmiit varausryhmät tuotantoon vai tehdäänkö ne tuotannossa sitten uudelleen, kun tulee käyttöön?

**Comment by lmstrand** [comment]
Ehkä on järkevämpi tehdä uusiksi tuotantoon. Tietokantataulu, joka nuo sisältää on aikamoinen himmeli, pitäisi ylikirjoittaa tuotannon kaikki tavara.

**Comment by lmstrand** [comment]
Oltiinko tuosta väristä sovittu jotain? Jätetäänkö mustaksi, mutta boldattuna? Lisäsin tuon sinisen värin nyt vain havainnoinnin helpottamiseksi.

**Comment by MikkoLiimatainen** [comment]
Vaskissakin testattu toimivaksi.

**Comment by ajrajala** [comment]
> Oltiinko tuosta väristä sovittu jotain? Jätetäänkö mustaksi, mutta boldattuna? Lisäsin tuon sinisen värin nyt vain havainnoinnin helpottamiseksi.

Anneli oli tuonne ylemmäs kirjannut asiantuntijaryhmän päätökseen, että "Kokeillaan riittäisikö yksiköiden tunnusten lihavointi."

**Comment by AnneliO** [comment]
Dokumentoitava

**Comment by lmstrand** [comment]
Väritys otettu pois varausryhmiin osuvilta yksikkötunnuksilta. Kehittäjäpalaverissa esitettiin lisättäväksi hyllyvarauslistaan tiedot, mitä punainen väritys/yksikköjen boldaus tarkoittaa.
