### ISSUE TITLE
Koha-Ceepos sertifikaatti vanhentunut

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1140]
### Tukipyyntö

Joensuun pääkirjaston Ceepos-kassa ei toimi (Oulussa ilmeisesti samanlainen ongelma). Kohan ja Ceepoksen välillä oleva sertifikaatti lienee vanhentunut, jotta saadaan palvelu taas toimimaan.

**Comment by emta001** [comment]
Vaaran Ceepos-asetuksiin on käyty vaihtamassa uusi serti ja palvelut käynnistettiin uudestaan.

**Comment by pknuuti** [comment]
Vika edelleen Joensuussa.
