### ISSUE TITLE
Tietuesiirtäjä: paikalliskantaan valuu emosta irrallaan olevia osakohteita

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1142]
### Mikä vikana?

Vaskissa on huomattu, että tietokantaan tulee emostaan irrallaan olevia ylimääräisiä osakohteita. Viimeksi tänään tuli vastaan tapaus, jossa kuvailija ei mielestään tässä käyttänyt vie/tuo -nappia ja tietueet tosiaan näkyvät Tietuesiirtäjässä eivätkä Siirtoraportissa. Kuvailija teki Tätiin siis tämän tietueen + osakohteet: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2445125&searchid=scs_1712054853710

Parin osakohteen kohdalla kuvailija kirjoitti 245-kenttään ensin nimekkeen japaniksi, mutta muutti sen tallennuksen jälkeen ja tallensi uudelleen. Tätissä ja Melindassa osakohteita on oikea määrä + nimekkeet ilman japanilaisia merkkejä kuten pitääkin. Vaskiin on kuitenkin valunut muokatut osakohteet kahteen kertaan ja niitä on nyt 3 ylimääräistä. Ylimääräiset osakohteet ovat emosta irrallaan, tietuenumerot [4366290](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4366290), [4366291](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4366291) ja [4366288](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4366288).

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/b76ab632-6a47-4e55-9b18-f7f663bb3f25)

**Comment by ajrajala** [comment]
Toinen samankaltainen tapaus sattui 28.3. 9:25:04, kun Vaskin paikalliskantaan valui Dragonforce: Speed warriors (id [4362335](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4362335)), ja viiden minuutin kuluttua samaiseen tietueeseen valui uudestaan Melindan ja TäTin 035-kentät. Kaikista tietueen osakohteista kuitenkin puuttui tässä vaiheessa aineistolaji.

9:30 on tietuesiirtäjän mukaan valunut myös emotietueen seitsemän osakohdetta (kaikkiaan niitä on kymmenen). Näissä osakohteissa on myös aineistolaji, mutta näillä osakohteilla ei ole emotietuetta.

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/d381cca7-943e-4cb0-86fa-238dd8bad784)

**Comment by AnttHeik** [comment]
Onko noiden osakohteiden, joilla ei ole emoa, 003- ja 001-kentissä vielä FI-TATIn tunnukset? Se selittäisi sen, ettei ne yhdisty enää emoon.

Tämä viittaisi minusta sellaiseen tapaukseen, että TäTiin on ehditty tallentaa emo ja osa osakohteista, ennen kuin tietuesiirtäjä on reagoinut siihen, eli koska tietuesiirtäjä tarkistelee tietuemuutoksia TäTistä viiden minuutin välein, niin tuossa viiden minuutin aikana on ehditty tehdä emo ja osa osakohteista, jotka ovat siirtyneet sitten paikalliskantaan TäTi-tietueina. Kun tietue on sitten tehty TäTissä loppuun ja se on viety Melindaan, niin tämän jälkeen tietue on valunut paikalliskantaan uudestaan, mutta se ei ole osannut päivittää noita aiemmin tulleita osakohteita vaan on tehnyt kaikki uudestaan. Tämä ei välttämättä selitä ehkä ihan kaikkea, mutta kuulostaa tilanteelta, johon itsekin olen törmännyt :)

Dragonforcen seitsemän osakohdetta viittaisi ehkä siihen, että vain nuo olivat ehtineet tulla Melindasta takaisin siinä vaiheessa kun tietue valutettiin taas paikalliskantaan.

**Comment by AnttHeik** [comment]
OUTIin tuo Dragonforec oli valunut näin:

![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/fdd1ad83-7103-4d49-b4c2-d4c8d0b82cdc)

09.30.06 ovat TäTi-tietueita, jotka näyttävät meilläkin roikkuvan ilman emoa, ja 9.35.04 ovat sitten Melinda-tietueita

**Comment by AnttHeik** [comment]
Kyllä tuossa jokin ihmeellinen päivityshäikkä ehkä vielä on. Mielestäni tuo osakohteiden määrien epätäsmäys (7 vs. 10) olisi pitänyt huomata, koska samaa emoa on kuitenkin päivitetty.

**Comment by AnttHeik** [comment]
Samanlainen nyt myös OUTIssa: 

1. 2.4.2024 16:15:05 Emon hankintatietue päivittyy TäTi-tietueeksi
2. 2.4.2024 16:20:04 Viiden minuutin päästä tähän tietueeseen valuu jostakin syystä osakohteita, niin kuin emoa olisi päivitetty jommassa kuussa päässä, jotta siihen alkaa valumaan osakohteita, joita tulee 7 kpl. En kuitenkaan tallentanut emoa kertaakaan sen jälkeen kun aloin tehdä osakohteita.
3.  2.4.2024 16:35:04 TäTi-tietue päivittyy Melinda-tietueeksi.
4.  2.4.2024 16:40:04 Melinda-tietueelle valuu osakohteet uusina tietueina, jolloin nuo aiemmin valuneet 7 kpl jäävät tietokantaan roikkumaan ilman emoa, koska ne ovat noita aiempia TäTi-tietueen osakohteita.

![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/033cf46a-08a3-4e72-8dd7-cb713b0facbb)

**Comment by johannaraisa** [comment]
Tein nyt tähän korjauksen, katsotaan tuleeko uudet osakohteet oikein. Mutta tuota 942b:n käyttämistä Täti-kuvailussa voisi miettiä.

**Comment by AnttHeik** [comment]
Ok, kiitokset. Tuo 942b-kentän käyttö on kyllä ihan hyvä idea. Pitää testata sitäkin.

**Comment by ajrajala** [comment]
Onkohan näitä emosta irrallaan valuneita osakohteita vielä tullut vastaan Johannan huhtikuisen korjauksen jälkeen?

**Comment by AnttHeik** [comment]
Kyllä noita osakohteita voi edelleen karata paikalliskantaan, mutta koska tietuesiirtäjä ei hyväksy päivityksiä, jos osakohteiden määrä ei täsmää paikalliskannan ja TäTin välillä, niin nämä on nyt helpompi huomata ja karanneet osakohteet pitää poistaa ennen kuin tietueen voi tuoda kaikkien osakohteiden kanssa. Siinä mielessä tämän tiketin voinee nyt sulkea.
