### ISSUE TITLE
Lappi : Palautuskehotukset sähköpostilla, cron-ajoon lisättävä prefer email

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1143]
### Tukipyyntö

Lapissa on otettu käyttöön 2. palautuskehotuksen lähettäminen sähköpostilla. Myöhästymisilmoituisten määrittelyyn lisätty tarvittavat täpit.

Kehittäjää pyydetään lisäämään cron-ajoon pitää päälle “vipu” prefer email.

**Comment by emta001** [comment]
Tarkistin Lapin overdue_notices-cronin ja siellä onkin jo käytössä tuo -preferemail vipu.

**Comment by LeenaKinnunen** [comment]
Jostain syystä asiakkaalle on tullut sekä sähköpostiin että paperisena 2. palautuskehotus, tosin eri päivinä. Mistähän se voisi johtua? borrowernumber=407188

**Comment by AnneliO** [comment]
Tuolle kyseiselle asiakkaalle on viime aikoina lähtenyt tällaisia viestejä
Viestin otsikko | Kirjepohja | Viestityyppi | Viesti jonoon
--- | --- | --- | ---
| Palautuskehotus kirjastosta         | ODUE1       | email                  | 2024-03-17 09:19:11 |
| Varaus saapunut kirjastoon          | HOLD        | sms                    | 2024-03-21 11:39:30 |
| Muistutus kirjaston eräpäivästä     | PREDUEDGST  | email                  | 2024-03-25 09:21:30 |
| Varaus saapunut kirjastoon          | HOLD        | sms                    | 2024-03-27 10:47:13 |
| Palautuskehotus kirjastosta         | ODUE2       | print                  | 2024-03-28 09:19:19 |
| Muistutus kirjaston eräpäivästä     | DUEDGST     | email                  | 2024-03-28 09:21:24 |
| Palautuskehotus kirjastosta         | ODUE1       | email                  | 2024-03-31 09:19:25 |
| Muistutus kirjaston eräpäivästä     | PREDUEDGST  | email                  | 2024-04-02 09:21:29 |

Eli asiakkaalle on lähtenyt vain yksi ODUE2  printtinä 28.3.2024. Milloin teitte asetusmuutokset?

**Comment by emta001** [comment]
> Jostain syystä asiakkaalle on tullut sekä sähköpostiin että paperisena 2. palautuskehotus, tosin eri päivinä. Mistähän se voisi johtua? borrowernumber=407188

Johtunee siis siitä, että asiakas on Pellon kirjaston asiakas ja Pellon kirjaston palautuskehotus-asetuksissa ei ole email-täpää päällä. Kannattaa varmaan tarkistaa nuo kaikilta muiltakin kirjastoilta, että ovat kuosissa.

**Comment by LeenaKinnunen** [comment]
Ok, ei huomattu katsoa tuota. Käydään läpi kirjastot ja hoidetaan ruksit kuntoon. Kiitos Emmi!
