### ISSUE TITLE
Vaski: Runosmäen varausten keskeytys muuton ajaksi

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1147]
### Tukipyyntö

Keskeytetään määräajaksi Runosmäen kirjaston tärppäämättömät ja keskeyttämättömät tai muuton aikana aktivoituvat varaukset varaukset.

Kirjasto TURU
Vain tärppäämättömät varaukset
Vain keskeyttämättömät ja muuton aikana aktivoituvat varaukset
Keskeytys tehdään 11.4.2024
Keskeytys päättyy 6.5.2024

SELECT reserve_id FROM reserves WHERE branchcode = 'TURU' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-04-11' AND '2024-05-06'))

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [vaskiprod]> UPDATE reserves set suspend = 1, suspend_until = '2024-05-06' WHERE branchcode = 'TURU' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-04-11' AND '2024-05-06'));
Query OK, 1631 rows affected (0.067 sec)
Rows matched: 1631  Changed: 1631  Warnings: 0
```

**Comment by iinaniemi** [comment]
Vaikuttaa olevan ok, kuittaan valmiiksi.
