### ISSUE TITLE
OUTI: Muhoksen alle 16-vuotiaiden lasten takaajille viesti ajona

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1151]
### Tukipyyntö

Saisimmeko Muhoksen (MU%) alle 16-vuotiaiden lasten takaajille ajona Kohaan viestin (Lisää viesti kohteelle: Asiakasliittymä) , joka näkyy myös verkkokirjastossa.

OUTIn tuotannossa on Kassun tekemä raportti 762: "Alle 16-vuotiaat lapset, joilla asiakastyyppi Omatoimi sallittu ja heidän huoltajat". Raportilla voi hakea lapset, joiden takaajille viesti lisätään.

Lisättävä viesti:
“Hei! Oletko huomannut, että lapsellasi on oikeus käyttää omatoimikirjastoja itsenäisesti eli silloin kuin henkilökunta ei ole paikalla. Huoltaja vastaa alle 16-vuotiaan mahdollisesti aiheuttamista vahingoista. Muhoksen kirjaston omatoimikäyttö alkaa 17.6.2024. Voit halutessasi kieltää lapsesi omatoimikirjaston käytön käymällä kirjastossa tai olemalla yhteydessä kirjastoon sähköpostitse ([kirjasto@muhos.fi](mailto:kirjasto@muhos.fi)) tai puhelimitse (0444970409). Omatoimikäyttöön tarvitsee kirjastokortin lisäksi myös PIN-koodin.”

Olisiko mahdollista saada myös uusi raportti, jolla voi hakea takaajat, joilla ei ole enää huollettavana alle 16 vuotiasta lasta ja joilla on viesteihin lisätty yllä mainittu teksti?

**Comment by atarnus** [comment]
Lista huoltajien borrowernumbereista:

```
SELECT DISTINCT r.guarantor_id
  FROM borrower_relationships r
       INNER JOIN (SELECT b.borrowernumber
                     FROM borrowers b
                    WHERE b.categorycode = 'LAOMATOIMI'
                      AND b.dateofbirth > '2008-04-10'
                      AND b.branchcode LIKE 'MU%') AS lapsi
       ON r.guarantee_id = lapsi.borrowernumber
```

Insert message:
```
INSERT INTO messages (borrowernumber, branchcode, message_type, message)
VALUES (?, 'MUPK', 'B', 'Hei! Oletko huomannut, että lapsellasi on oikeus käyttää omatoimikirjastoja itsenäisesti eli silloin kuin henkilökunta ei ole paikalla. Huoltaja vastaa alle 16-vuotiaan mahdollisesti aiheuttamista vahingoista. Muhoksen kirjaston omatoimikäyttö alkaa 17.6.2024. Voit halutessasi kieltää lapsesi omatoimikirjaston käytön käymällä kirjastossa tai olemalla yhteydessä kirjastoon sähköpostitse (kirjasto@muhos.fi) tai puhelimitse (0444970409). Omatoimikäyttöön tarvitsee kirjastokortin lisäksi myös PIN-koodin.')
```


Ajon jälkeen käytettävä raportti viestien siivoamiseen 16 vuotta täyttäneiden huoltajilta:

```
SELECT DISTINCT m.borrowernumber
  FROM messages m 
       INNER JOIN borrower_relationships r
       ON r.guarantor_id = m.borrowernumber
       INNER JOIN (SELECT b.borrowernumber
                     FROM borrowers b
                    WHERE b.categorycode = 'LAPSI'
                      AND b.dateofbirth < DATE(CURRENT_TIMESTAMP) - INTERVAL 16 YEAR
                      AND b.branchcode LIKE 'MU%' AS lapsi
       ON r.guarantee_id = lapsi.borrowernumber
  WHERE m.message LIKE 'Hei! Oletko huomannut, että lapsellasi on oikeus käyttää omatoimikirjastoja%'
```

**Comment by atarnus** [comment]
Itse asiassa tällainen raportti jälkikäteen varmaan toimisi ok:

```
SELECT m.borrowernumber, r.guarantee_id
  FROM messages m
       INNER JOIN borrower_relationships r
       ON r.guarantor_id = m.borrowernumber
       INNER JOIN borrowers b
       ON r.guarantee_id = b.borrowernumber
 WHERE m.message LIKE 'Hei! Oletko huomannut, että lapsellasi on oikeus käyttää omatoimikirjastoja%'
   AND m.borrowernumber NOT IN (SELECT r.guarantor_id 
                                 FROM borrower_relationships r
                                      INNER JOIN borrowers b ON r.guarantee_id = b.borrowernumber
                                WHERE b.categorycode = 'LAOMATOIMI'
                                  AND b.dateofbirth > DATE(CURRENT_TIMESTAMP) - INTERVAL 16 YEAR)
```

Tuo nappaa kiinni sellaiset huoltajat, joiden huollettavista yksikään ei ole tyyppiä LAOMATOIMI ja iältään alle 16v. Tähän tarttuisi sitten sellaisetkin, joilta on jäänyt viesti poistamatta vaikka tuo omatoimi olisi vaihdettu pois. Eikä turhaan näy sitten listassa jos joku huollettavista on täyttänyt sen 16v.

**Comment by atarnus** [comment]
Ajettiin skripti Kodon kanssa, 422 ilmoitusta tuli.

Listan saa vaikkapa näin:

`SELECT * from messages where message LIKE 'Hei! Oletko huomannut%'`

Ylemmässä viestissä oleva rapsa alkaa sitten antamaan tuloksia kun huollettavat vanhenee, ja turhia viestejä voi poistaa sen ohjaamana.

**Comment by pirliis** [comment]
Kiitos! Kassun tekemä raportti, jolla voi hakea takaajat, joilla huomautusviesti on ajanmittaan aiheeton, toimii. Raportista ilmoitettu Muhoksen kirjastolle, että ajavat sitä säännöllisesti ja poistavat takaajilta tarpeettomaksi käyneen viestin. 

Suljen tiketin. Jos pitää säätää jotain lisää, avataan tiketti uudestaan.
