### ISSUE TITLE
Vaara: Käytöstä poistuneiden aineistotyyppien piilottaminen Tarkka haku -sivulta

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1152]
### Tukipyyntö

Haluaisimme tietyt aineistotyypit piiloon [Tarkka haku -sivulta](https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl) hakunäkymän selkiyttämiseksi. Tätä ei kuulemma kannata tehdä poistamalla aineistotyyppejä kokonaan, joten olisiko mahdollista piilottaa ne ko. sivulta? Jos tämä on mahdollista, voisimme kerätä tiedot piilotettavista aineistotyypeistä.

**Comment by AnneliO** [comment]
Olen tätä joskus kokeillut, eikä tulos ollut hyvä. Aineistotyypit ovat sivulla taulukkona ja yksittäisen solun saa kyllä tyhjäksi, mutta siitä jää sitten jäljelle tosiaan tyhjä solu.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/c3aaea9a-5fd7-447f-8212-87327eb97e87)

Mielummin jättäisin ne piilottamatta. :)

**Comment by IrinaHalminen** [comment]
Nostan vielä tätä keskusteluun eli mikä oli tarkka syy sille, ettei noita aineistotyyppejä voisi poistaa järjestelmästä? Rikkooko se jotain Finnan suuntaan? Oletettavasti näitä aineistotyyppejä ei tulla ikinä tarvitsemaan.

**Comment by johannaraisa** [comment]
Koha-Suomen kehittäjien viikkopalaveri 3.6.2024: Asiasta on aikanaan tehty päätös, että seurataan Finnan aineistotyyppejä. Poistaminen voi saada aikaan jänniä tilanteita.
