### ISSUE TITLE
Palautuskuitille tieto, jos asiakkaan lainahistoria anonymisoidaan

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1153]
### Tukipyyntö

Asiantuntijaryhmän kokouksessa 8.4.2024 päätettiin tutkia, onnistuuko palautuskuitille tulostamaan vaihtoehtoisen tiedon, että asiakkaan lainahistoria on anonymisoitu, eikä kuittia voida tulostaa.

Muuten tulostuisi normaali palautuskuitti.

Liittyy tikettiin #441.

**Comment by AnneliO** [comment]
Testasin tätä asiaa ja vaihtoehtoisella tekstillä olevan CHECKINSLIP-kuitin tulostaminen onnistuu ainakin näin:

```
<style type="text/css">
  h1 { font-family: arial; font-size: 20pt; }
  h2 { font-family: arial; font-size: 18pt; }
  h3 { font-family: arial; font-size: 16pt; }
  h4 { font-family: arial; font-size: 14pt; }
  p { font-family: arial; font-size: 10pt; }
</style>

[% IF "<<borrowers.privacy>>" == 2 %]
<h2>Asiakkaan lainahistoria on anonymisoitu</h2>

<p>Asiakkaan lainahistoria anonymisoidaan palautuksessa, joten palautuskuittia ei voida tulostaa.</p>

[% ELSE %]

<h3>[% branch.branchname %]<br />
[% today | $KohaDates %]<br /></h3><br /><br />



<h3>Palautetut lainat</h3>

[% FOREACH checkin IN old_checkouts %] [% SET item = checkin.item %] <p> [% item.biblio.title %] [% item.enumchron %] [% item.biblio.author %] <br />
Nide: [% item.barcode %] <br />
[% END %]
</p>
<p>
</p>
<p>
Palautusten määrä: [% old_checkouts.count %]
</p>

<p>
<br /><<branches.branchfax>>
<br /><<branches.branchphone>>
<br />www.outikirjastot.fi</p>
<br />

[% END %]
```

**Comment by pirliis** [comment]
OUTIssa tekstin tulostus toimi palautuskuitille, mutta jos lisätyn tekstin lisäsi sähköpostina menevään palautuskuittiin ja asiakkaalla on valittuna palautuskuitti s-postiin, palautustilanteessa tulee virhe 500.

**Comment by AnneliO** [comment]
> OUTIssa tekstin tulostus toimi palautuskuitille, mutta jos lisätyn tekstin lisäsi sähköpostina menevään palautuskuittiin ja asiakkaalla on valittuna palautuskuitti s-postiin, palautustilanteessa tulee virhe 500.

Aa, tätä ei ole tarkoitettu sähköpostiviestiin laitettavaksi, eikä sitä oikeastaan sinne tarvikaan. Sähköpostikuitti toimii eri tavalla ja se muodostuu, vaikka asiakkaan lainahistoria anonymisoidaankin. :)

**Comment by Tuomas-Kyyti** [comment]
Testasin sekä Kyytin testillä että nextillä ja tuntui toimivan.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.

**Comment by AnneliO** [comment]
Testausten perusteella vein muutokset nyt myös [Kuitit ja viestipohjat -dokumentaatioon Koha-Suomen verkkosivuille](https://koha-suomi.fi/dokumentaatio/kuititjaviestit/#checkinslip-eli-palautuskuitti). Kuittipohjan voi muuttaa kimpoissa tämän mukaisesti halutessa ja omalla aikataululla.

**Comment by AnneliO** [comment]
Suljen tiketin.
