### ISSUE TITLE
EDItX-virheilmoituksessa sähköpostiin on vanha linkki EDItX-dokumentaatioon

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1155]
### Tukipyyntö

Sähköpostiin lähtevä virheilmoitus EDItX-sanomista sisältää vanhan linkin EDItX-dokumentaatioon. Linkki vie Redmineen, eikä toimi enää. Toimiva linkki on https://koha-suomi.fi/dokumentaatio/editx/#43-erilaisia-virhetilanteita.

**Comment by CodoDerDritte** [comment]
Linkki korjattu skriptiin ja viety myös tuotantoon.

**Comment by AnneliO** [comment]
Vielä ei ole tullut yhtään EDItX-virheraporttia sähköpostiin, joten muutosta ei ole voinut todeta toimivaksi. Odottelen edelleen. :)

**Comment by AnneliO** [comment]
Nyt oli tullut virheraportti sähköpostiin. Osoite on ok. Suljen tiketin. Kiitos!
