### ISSUE TITLE
Lumme: turhien asiakaslistojen poisto

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1156]
### Tukipyyntö

Meillä Lumpeissa keikkuu todella vanhoja turhia asiakaslistoja, eivätkä pääkäyttäjät pysty niitä poistamaan. 
Voisiko seuraavat listat poistaa kehittäjien toimesta:
- Kalevankankaan asiakkaat
- Lähemäen asiakkaat
- Rantakylän asiakkaat
- Siirrettävät virkailijatunnukset Mikkeli
- Virkailijaksi
- Virkailijatunnusten muutos SAV

**Comment by AnneliO** [comment]
Listan omistajan pitäisi pystyä poistamaan lista. Tässä listaus, kuka on minkäkin asiakaslistan omistaja:

MariaDB [lummeprod]> select * from patron_lists;

| patron_list_id | name                                       | owner  | shared |
---|---|---|---
|              1 | Kotipalvelu                                | 258071 |      0 |
|              2 | Kalevankankaan asiakkaat                   |  56292 |      0 |
|              3 | Lähemäen asiakkaat                         |  56292 |      0 |
|              4 | Rantakylän asiakkaat                       |  56292 |      0 |
|              7 | Siirrettävät virkailijatunnukset Mikkeli   | 259684 |      0 |
|              8 | Virkailijaksi                              | 165274 |      0 |
|             12 | Virkailijatunnusten muutos SAV             | 258528 |      0 |
|             14 | Yhdistettävät samalla sotulla              | 259684 |      1 |
|             18 | Ei-aktiiviset asiakkaat - poistettava      | 269082 |      0 |

Pystyisikö he yrittämään ensin? :)

**Comment by Hanna-Lumme** [comment]
Kiitos, tämä auttoi kovasti! 😃 Voisitteko te poistaa tuon Virkailijatunnusten muutos SAV -listan? Kyseinen työntekijä on tällä hetkellä poissa, eikä ole tietoa hänen takaisin tulostaan.

**Comment by emta001** [comment]
> Kiitos, tämä auttoi kovasti! 😃 Voisitteko te poistaa tuon Virkailijatunnusten muutos SAV -listan? Kyseinen työntekijä on tällä hetkellä poissa, eikä ole tietoa hänen takaisin tulostaan.

Kävin poistamassa.
