### ISSUE TITLE
Lappi : epäonnistuneiden e-kirjeiden poisto

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1160]
### Tukipyyntö

Lapissa on 5.4.2024 epäonnistunut e-kirjeiden lähetys. Raportti 12 antaa tuolle päivälle 86 epäonnistunutta e-kirjettä. 
Poistatteko nämä e-kirjeet.

**Comment by CodoDerDritte** [comment]
Miksi?
