### ISSUE TITLE
Sotun lisäys-kentän ja painikkeen luonti ja sotuavain-asiakasmääreen siirto Sotuteekki-pluginiin

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#1162]
### Kehitysehdotukseni

IntranetUserJS-rimpsut liittyen sotuteekin toimintaan pitää siirtää pluginiin ylläpidettäväksi.

**Comment by lmstrand** [comment]
Siirretty tarvittava koodi branchiin 23.xx. Viety nexteille testattavaksi. Pääkäyttäjät testaavat.

Testaus tapahtuu siis siillä tapaa, että poistaa intranetuserjs-asetuksista rimpsut "Lisätään asiakkaan lisäys/muokkausnäytölle hetun lisäysmahdollisuus" ja "Sotuavain-asiakasmääreen siirto" ja kokeillaan, toimiiko sotun lisäys ja muodostuuko sotuavain oikein omaan kenttäänsä.

**Comment by IrinaHalminen** [comment]
Vaarassa toimii.

**Comment by AnneliO** [comment]
Siili-nextillä ei toimi. Lisää hetu -kenttää ei muodostu ollenkaan, eikä sen myötä myöskään sotu-avain-kenttä siirry. Lisäksi hetun lisäämistä ei pysty testaamaan, koska nexteiltä (paitsi ilmeisesti vaarassa) ei ole yhteyttä sotu-siiloon.

Vaarassakin näyttäisi olevan sellainen ongelma, että Sotu-avain -kenttä on nyt kahdessa paikkaa.
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/aa645c6a-d7db-489f-bdcb-b0deab1bd608)

Sotu-avain meni kyllä kumpaankin kenttään, mutta onhan tuo hieman outo. :)

Vielä sellainen pieni huomio, että IntranetUserJS:n rimpsua käytettäessa Lisää hetu -kentän ja Tallenna-napin välissä on pieni rako, mikä selkeyttää ja rauhoittaa näkymää. Vaarassa Tallenna-nappi on ihan kentässä kiinni.

Siilistä:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/30b0af1d-8edf-4bab-a37b-728a5dafb89b)

**Comment by Kati-Helle** [comment]
Helle-nextistä puuttuu rimpsujen poiston jälkeen hetuun liittyvät kentät
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2bb7b2d3-fd17-4eb7-baef-6ccb47a8a9c5)

**Comment by lmstrand** [comment]
Tuplakenttäongelmakin siis oletettavasti ratkottu.

**Comment by ElinaUotila** [comment]
Kirkesin nextillä näkyy hetukentät oikein rimpsujen poiston ja sotuteekin aktivoinnin jälkeen.

**Comment by pirliis** [comment]
Myös OUTIssa Lisää hetu- ja Sotu-avain -kentät näkyvät nyt oikein. Hetun tallennusta sotuteekkiin ei voi testata, kun ei ole yhteyttä nextiltä sotutekekkiin.

**Comment by IrinaHalminen** [comment]
En torstaina lomallelähtöpäissäni huomannutkaan tuota tuplakenttää. Tuolloin sotun lisäys toimi ja se loi sotuavaimen ihan oikein. Tuli sellainen juttu mieleen, että testasin tuota myös omalla hetulla, eikä se herjannut mitään siitä, että se olisi jo käytössä. Pitäisikö nextillä näin käydäkin vai miten siellä nuo siilot menevät?

Kokeilin nyt uudelleen henkilöasiakkaan luomista ja hetun lisäys ei enää onnistukaan, vaan lomake herjaa, että pakollisia kohtia ei ole tallennuttu. Yrittääkö Lisää hetu -kentän Tallenna-nappi tallentaa nyt koko sivua eikä pelkkää hetua?

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/3c6f3d43-34d2-4137-bec2-894356dfa540)

**Comment by IrinaHalminen** [comment]
Pitäisikö tämän rimpsun olla mukana tässä samassa kokonaisuudessa? 

/* Kirjoitussuojaa sotu-avain kenttä asiakkaan muokkauksessa. Vaihda patron_attr-kohtaan sopiva numero kimpan mukaan. */
body#pat_memberentrygen.pat textarea#patron_attr_3 { pointer-events: none; }

**Comment by AnneliO** [comment]
> En torstaina lomallelähtöpäissäni huomannutkaan tuota tuplakenttää. Tuolloin sotun lisäys toimi ja se loi sotuavaimen ihan oikein. Tuli sellainen juttu mieleen, että testasin tuota myös omalla hetulla, eikä se herjannut mitään siitä, että se olisi jo käytössä. Pitäisikö nextillä näin käydäkin vai miten siellä nuo siilot menevät?

Eli se ei antanut linkkiä olemassa olevaan asiakkaaseen? Onko sotuavaimesi tallennettuna nextillä tällä hetkellä millekään asiakkaalle? Sotuavaimethan poistettiin asiakastiedoista anonymisoinnin yhteydessä.  Siitähän se ei herjaa, jos hetu löytyy siilosta, mutta ei ole tallennettuna mihinkään asiakastietoon. Se vain iloisesti lisää sen uudelle asiakkaalle. Tämä johtuu siitä, että sotusiilo on kaikkien kimppojen yhteinen, joten hetu voi olla tallennettu siiloon jossakin toisessa kimpassa aiemmin.

**Comment by AnneliO** [comment]
> Pitäisikö tämän rimpsun olla mukana tässä samassa kokonaisuudessa?
> 
> /* Kirjoitussuojaa sotu-avain kenttä asiakkaan muokkauksessa. Vaihda patron_attr-kohtaan sopiva numero kimpan mukaan. */ body#pat_memberentrygen.pat textarea#patron_attr_3 { pointer-events: none; }

En tiedä, pystyykö liitännäiseen lisäämään CSS:iä, mutta tuo kannattaa kyllä pitää mukana IntranetUserCSS:ssä vähintäänkin. Lari osannee kommentoida, voiko tuota lisätä suoraan liitännäiseen.

**Comment by lmstrand** [comment]
Voi lisätä liitännäiseen javascriptinä.

**Comment by lmstrand** [comment]
Lisätty kentän kirjoitussuojaus nyt nexteille ja korjattu tuo Irinan mainitsema ongelma. Nappi meni rikki väärin koodatusta marginaalista.

**Comment by Kati-Helle** [comment]
Helle-nextissä puuttuu edelleen rimpsujen poiston jälkeen hetuun liittyvät kentät.

**Comment by lmstrand** [comment]
Plugin pitää aktivoida tuossa pluginlistausnäkymässä oikealta valitsemalla toiminnot-alasvetovalikosta aktivoi, jolloin kenttien pitäisi ilmestyä asiakkaan lisäys/muokkausnäkymään. Puuttuukohan sinulta manage_plugins-oikeus kun sitä ei tuossa näy?

**Comment by lmstrand** [comment]
Sotuavain ei tällä hetkellä suostu tallentumaan asiakastietoihin. Liittyy varmaan tuon kentän kirjoitussuojaukseen jotenkin.

**Comment by Kati-Helle** [comment]
Kiitos Lari tiedosta. Aktivoin liitännäisen ja Lisää hetu -toiminto on nyt Helle-nextissä käytettävissä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c6686ea5-bdd9-4ca0-9976-0c3587469ff5)

**Comment by Kati-Helle** [comment]
Tallenna-painikkeelle myös taustaväri, kuten muuallakin Kohassa?
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b92b5f2c-4836-4c3c-be12-9e2b7424982f)

**Comment by pknuuti** [comment]
Vaaran nextillä on tällainen näkymä tuosta tallennuskohdasta. Missä tuo erilainen muotoilu määritellään?
![2023kuvat 382](https://github.com/KohaSuomi/Koha/assets/73887264/3376a5f6-baac-458f-9a9c-674343132701)

**Comment by pirliis** [comment]
> Vaaran nextillä on tällainen näkymä tuosta tallennuskohdasta. Missä tuo erilainen muotoilu määritellään? ![2023kuvat 382](https://private-user-images.githubusercontent.com/73887264/324763656-3376a5f6-baac-458f-9a9c-674343132701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjM3ODcsIm5iZiI6MTcxMzg2MzQ4NywicGF0aCI6Ii83Mzg4NzI2NC8zMjQ3NjM2NTYtMzM3NmE1ZjYtYmFhYy00NThmLTlhOWMtNjc0MzQzMTMyNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZGFiMTdmZGJmZDNlMjJiYmM2YzZhYjg0NjhjY2YxN2NkYTM5M2Y2OGI2ZWI2ZGE1NTgwOTNiZTI4M2EzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZHLC_kt7-Zf4x-qEpxw7Si3OWJt3crGUZrUfa26siAI)

Tarkoitatko Päivi tuota Sotuavain-kentän korkeutta? Jos tarkoitat, niin tällä intranetusercss-rimpsulla OUTIssa on muutettu se yhden rivin korkuiseksi: 
/* Varaustunnisteen ja sotuavaimen kenttien korkeus yhdeksi riviksi. Tarkista, että attribuuttien arvot vastaavat oman kimpan arvoja. */
#patron_attr_2 { height: 2em; }
#patron_attr_3 { height: 2em; }

**Comment by pknuuti** [comment]
Eikö tuo plugin osaa suoraan tehdä järkevän kokoista kenttää? Ja tuo teksti Hellessä on myös ihan hyvä.

**Comment by AnneliO** [comment]
> Tallenna-painikkeelle myös taustaväri, kuten muuallakin Kohassa? ![kuva](https://private-user-images.githubusercontent.com/99952449/324758583-b76c70f5-d836-43c3-b6bc-3d31412b47db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjQzNDQsIm5iZiI6MTcxMzg2NDA0NCwicGF0aCI6Ii85OTk1MjQ0OS8zMjQ3NTg1ODMtYjc2YzcwZjUtZDgzNi00M2MzLWI2YmMtM2QzMTQxMmI0N2RiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MjA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0NjE1YzRiOGJhMWZlYjFjYzZlNmRlOTA5MGRjNmVkM2IxODFjYmU1MzEwZTg4MmEwODhmZTk5ZmNhOTA3MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p-QfbmajYuNyMcOGFKfBSbXUlr3qykgSteXA6WXQqhU)

Tuo keltainen taustaväri laitetaan ymmärtääkseni sivun "päänapille", mikä olisi tässä tapauksessa koko asiakastietueen tallennus-nappi. :)

**Comment by AnneliO** [comment]
> Ja tuo teksti Hellessä on myös ihan hyvä.

Sitä pystyy säätämään asiakasmääreen ylläpidossa muuttamalla asiakasmääreen kuvausta. :)

**Comment by pknuuti** [comment]
> 
> Tuo keltainen taustaväri laitetaan ymmärtääkseni sivun "päänapille", mikä olisi tässä tapauksessa koko asiakastietueen tallennus-nappi. :)

Voisko siinä kuitenkin olla jotain väriä pohjalla, vaikka vähän hailakampaa?

**Comment by Kati-Helle** [comment]
> > Vaaran nextillä on tällainen näkymä tuosta tallennuskohdasta. Missä tuo erilainen muotoilu määritellään? ![2023kuvat 382](https://private-user-images.githubusercontent.com/73887264/324763656-3376a5f6-baac-458f-9a9c-674343132701.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NjM3ODcsIm5iZiI6MTcxMzg2MzQ4NywicGF0aCI6Ii83Mzg4NzI2NC8zMjQ3NjM2NTYtMzM3NmE1ZjYtYmFhYy00NThmLTlhOWMtNjc0MzQzMTMyNzAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDA5MTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZGFiMTdmZGJmZDNlMjJiYmM2YzZhYjg0NjhjY2YxN2NkYTM5M2Y2OGI2ZWI2ZGE1NTgwOTNiZTI4M2EzODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZHLC_kt7-Zf4x-qEpxw7Si3OWJt3crGUZrUfa26siAI)
> 
> Tarkoitatko Päivi tuota Sotuavain-kentän korkeutta? Jos tarkoitat, niin tällä intranetusercss-rimpsulla OUTIssa on muutettu se yhden rivin korkuiseksi: /* Varaustunnisteen ja sotuavaimen kenttien korkeus yhdeksi riviksi. Tarkista, että attribuuttien arvot vastaavat oman kimpan arvoja. */ #patron_attr_2 { height: 2em; } #patron_attr_3 { height: 2em; }

Entäpä kentille sama leveys?

**Comment by lmstrand** [comment]
Nappi korvattu bootstrap-mallisella vihreällä napilla ja nyt sotuavainkin tallentuu asiakasmääreeseen, kun käytin tuota pointer-events:none -css:ää kentän kirjoitussuojaukseen.

**Comment by Kati-Helle** [comment]
Kiitos Lari väristä nappiin. Erottuu nyt paremmin
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d95a89d1-2020-48c4-95da-c97945e297af)

**Comment by PiaKusmin** [comment]
Lapissa ei toimi. Eli kun poistin JS-rimpsun niin katos ne hetu- ja sotuavain-kentät kokonaan. Enkä löytänyt meiltä aktivoitavaa pluginia. @lmstrand

**Comment by PiaKusmin** [comment]
Ai se on se. Mie luulin, että se on yhteys sotuteekkiin. :) Miepä aktivoin sen ja katson uudelleen. Kiitos!

**Comment by PiaKusmin** [comment]
Nyt näyttää Lapissakin oikealta.

**Comment by lmstrand** [comment]
Tiketin vaadittujen muutosten seuranta:
Peukuttakaa tähän, kun olette saaneet tiketin muutokset tehtyä (intranetuserjs-asetuksesta rimpsut "Lisätään asiakkaan lisäys/muokkausnäytölle hetun lisäysmahdollisuus" ja "Sotuavain-asiakasmääreen siirto" pois ja Sotuteekki-pluginin aktivointi).

- [ ] Vaski
- [ ] Vaara
- [ ] Lappi
- [ ] Lumme
- [ ] Kyyti
- [ ] Kirkes
- [ ] Lastu
- [ ] Helle
- [ ] Siili
- [ ] Outi

**Comment by AnneliO** [comment]
@LastuJanneS Teettekö vielä Lastussakin tuon muutoksen, niin voidaan sitten sulkea tämä tiketti. :)

**Comment by LastuJanneS** [comment]
Tämä tehty nyt Lastussakin.
