### ISSUE TITLE
Tuhoutuneille lainoille eräajo kirjastossa tehtävää poistamista varten

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1166]
### Tukipyyntö

Päiväkodin kolmen kortin kaikki lainat tuhoutuivat tulipalossa ja kirjastossa pitäisi saada niteet poistettua. Poistaminen ei kuitenkaan onnistu ennen kuin niteet on palautettu ja niteitä on kolmella kortilla yhteensä yli sata. Olisiko mahdollista saada ajona merkittyä lisätiedoissa olevat itemnumberit ei-lainassa oleviksi ja siihen samaan syssyyn laittaa niteille lost-tila '1' & itemnotes_nonpublic-kenttään teksti _Tuhoutunut tulipalossa_?

Kirjasto voisi sitten tämän jälkeen hoitaa rauhassa niteiden poiston.

### Jotain muuta?

1806080
1798372
1766941
1631022
2388741
3001245
1759517
2251760
2502309
2675057
2927446
2700753
2592342
2592369
2633007
2733052
2251616
2502210
1784059
2154007
1745313
1725358
1982585
1729398
2953335
2603233
2497249
2728912
2430268
2501227
2615572
2341260
1535267
1791295
2188585
1697642
2026851
2161991
2729009
2495388
2728914
1667010
1882075
1876552
1765745
1813237
1606860
1800533
1773429
1811449
1861932
1570827
1818974
1664984
1756855
1724137
1735686
2304224
1692745
1777772
2592304
2844120
1784473
1586717
1726754
2899189
1622722
2701225
3107700
1693508
1470083
1574155
1478713
1508799
2189927
1521027
2670740
2826336
1508798
2931304
3001241
2423878
1652397
1902020
1793827
1661783
2181459
1470214
2691670
2592410
2497190
2675041
2615483
2502195
2728879
2502598
2102459
1985831
1875729
2728910
1983044
2615559
2927355
2781207
2592392
1760274
1809683
1682645
1656223
1641992

**Comment by ajrajala** [comment]
Heitin määräajaksi keskiviikon 24.4. mutta saa tehdä vaikka huomennakin jos kerkiää.

**Comment by AnneliO** [comment]
Jos näillä ei ole kiire, niin yksi vaihtoehto olisi odottaa versionvaihtoa ja käyttää sitten niteiden erämuokkauksessa sitä uutta lainojen palautustoimintoa. :)

**Comment by ajrajala** [comment]
Toiveena oli, että nämä saisi hoidetuksi ennen kuin nämä päiväkotiryhmät asioivat ensi viikolla kirjastossa. En vielä vahvistanut onnistuuko, mutta kuulostaako mahdolliselta?

**Comment by AnneliO** [comment]
Tulipa sellainenkin vaihtoehto mieleen, että jos laitatte asiakkaan lainoihin näkyviin Palauta-sarakkeen ja valitsette tarvittavat niteet ja klikkaatte sitten Uusi tai palauta valitut niteet -nappia, niin ne pitäisi palautua. Tuo toiminto ei muistaakseni ota huomioon varauksia yms.

**Comment by paxed** [comment]
Nidenumeroilla olevat niteet ja lainat ovat tallessa väliaikaisesti tauluissa ks_20240424_items_gh1166 ja ks_20240424_issues_gh1166
Jokainen nidenumero on käsitelty tälä rimpsulla:
```
insert into old_issues select * from issues where itemnumber=XXXX;
delete from issues where itemnumber=XXXX;
update items set itemnotes_nonpublic="Tuhoutunut tulipalossa", onloan=NULL, itemlost=1, itemlost_on='2024-04-24 00:00:05' where itemnumber=XXXX;
```

jossa XXXX on siis tiketissä oleva nidenumero.

**Comment by ajrajala** [comment]
Mainiota, kiitokset! Muutokset näyttävät olevan ok.
