### ISSUE TITLE
Virkailijaoikeuksien muodostuminen automaattisesti asiakasmääreen perusteella

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha#1169]
### Kehitysehdotukseni

Virkailijaoikeuksia miettiessä heräsi ajatus, että voisikohan Kohaan lisätä asiakasmääreen, jonka arvon perusteella voisi automaattisesti antaa virkailijalle arvolle kuuluvat virkailijaoikeudet. Asiakasmääreen arvot olisivat siis käytännössä erilaisia virkailijaoikeuksia tarvitsevia käyttäjäryhmiä.

Tämä helpottaisi kirjanpitoa siitä mitä oikeuksia kullakin virkailijalla on, sekä auttaisi esimerkiksi versiovaihtojen yhteydessä tulevien uusien virkailijaoikeuksien päivittämistä virkailijoille. Asiakasmääre tulisi rajata pelkästään Henkilökunta-asiakastyypin käyttöön, ja sen vaihtaminen pitäisi olla tavalla tai toisella rajattua (esim. pääkäyttäjille tai esihenkilöille).

Keskustelujen perusteella tämä vaatisi oman pluginin tekemisen, sekä yhtenä vaihtoehtona halutut virkailijaoikeudet sisältävän malliasiakastietueen tekemisen jokaiselle virkailijaoikeusryhmälle, josta oikeudet kopioitaisiin eteenpäin kyseisen ryhmään kuuluvalle virkailijalle.

**Comment by AnneliO** [comment]
Suljetaan tämä tiketti nyt, ja jos yhteisö tuo oikeuksien kopiointiominaisuuden vanhempiin versioihin, avataan siitä sitten itsellemme uusi, erillinen tiketti.
