### ISSUE TITLE
Jäädytetyjen ja aktiivisten varausten erottaminen lukumäärässä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1170]
### Kehitysehdotukseni

Kohan virkailijatyökalussa ja myös Finnassa näkyy nimekkeen varausten määrä yhtenä lukuna, vaikka varauksilla on erilainen status. Aktiiviset varaukset tarttuvat kiinni palautuksiin, mutta jäädytetyt varaukset eivät tartu. Asiakas voi jäädyttää (keskeyttää) varauksen toistaiseksi tai valitsemaansa päivämäärään saakka. Nimekkeellä voi olla pelkästään keskeytettyjä varauksia, joten vaikka näkymä näyttää nimekkeestä olevan varauksia, palautukset eivät tartu varauksiin. Tämä aiheuttaa toisinaan ihmettelyä henkilökunnassa virkailijatyökalun puolella. Finnassa asiakkaalle voi tulla virheellinen käsitys nimekkeen saatavuudesta, jos siellä on varauksia, jotka kuitenkaan eivät ota kiinni palautukseen. 

Olisi toivottavaa, että aktiiviset ja jäädytetyt varaukset näkyisivät jotenkin eri tavalla, josta voi tietää aktiivisten varausten määrän. Tai sitten jäädytetyt varaukset jätetään pois näytettävästä varausten määrästä. Tämä antaisi oikeamman kuvan nimekkeen saatavuudesta.

**Comment by atarnus** [comment]
Vilkaisin tätä. Sivupalkissa oleva numero Holds (n) tulee Biblio.pm:stä

```
sub HoldsCount {
    my ( $self, $biblionumber ) = @_;
    my $holds = Koha::Holds->search( { biblionumber => $biblionumber } );
    return $holds->count();
}
```

ja Perustiedot-näytöllä oleva "laatikko" muodostuu detail.pl:ssä.

```
#we only need to pass the number of holds to the template
my $holds = $biblio->holds;
$template->param( holdcount => $holds->count );
```

Ainakin tuossa detail.pl:ssä olevassa oliossa on mukana taas melkein koko tietokanta, että sieltä voisi tarvittaessa kaivella myös tarkempia varaustietoja, mutta kuten tuossa yllä on koodiinkin kommentoitu, templatelle annetaan tällä hetkellä vain tuo kokonaisarvo.

Todennäköisesti näitä molempia pitäisi siis muuttaa.

**Comment by atarnus** [comment]
Varaukset-sivulla olisi todennäköisesti suht helppo tehdä jonkinlainen lisäteksti taulukon yläosaan tms. paikkaan, koska taulukon rakennukseen on kaikki varaustieto jo saatavilla. Mutta olisiko tällaisesta hyötyä?

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Tutkitaan, olisiko Kassun ehdotus taulukon lisätekstistä mahdollinen ratkaisu. Sinne voisi siis koota tietoja tyyliin

Aktiivisia 5
Keskeytettyjä 3
Ei vielä voimassa 2

Knuutisen Päivi on kysynyt Finna-toimistosta asiasta ja he ovat tehneet varausten näkyvyydestä muutosehdotuksen.

**Comment by sksandel** [comment]
Vaski-testi näyttää jaottelun varauksista.


![Image](https://github.com/KohaSuomi/Koha/assets/99008412/4716c7c8-53f5-4f26-bed9-c19b63f84273)

**Comment by atarnus** [comment]
Outi-testillä näkyy oikein:

![Image](https://github.com/KohaSuomi/Koha/assets/63994411/cd310ba4-c48b-4625-aeee-c75b31dc87de)


Siirrän yhden aktiivisen varauksen tulevaisuuteen ja keskeytän toisen. Tiedot eivät päivity automaattisesti jaotteluun, mutta kun painan Päivitä varaukset -nappia, niin tulee oikea näkymä taas:

![Image](https://github.com/KohaSuomi/Koha/assets/63994411/9ee559c9-8504-406e-aed2-9821b0df42bd)

**Comment by lasse-koha** [comment]
> Vaskissa ei ole mahdollista tehdä varausta tulevaisuuteen. Olisiko mahdollista, että jos AllowHoldDateInFuture-asetus on älä salli, niin tuota riviä ei näytettäisi?

Koha-Suomen palaveri 1.7.2024: Ei tehdä koodimuutosta, rivin voi piilottaa CSS:llä.

**Comment by MikkoLiimatainen** [comment]
Tein tällaisen piilotuksen:
```
/* Tulevien varausten määrän piilotus varaussivulla */
body#circ_request form#existing_holds :nth-child(3) { display:none; }
``` 

Vaikuttaisi toimivalta, mutta en ole ehtinyt testaamaan kunnolla.

**Comment by atarnus** [comment]
Tsekkasin tätä nyt tuotannossa (ehkä 6-7 bibliota Kohassa ja näistä kolme myös Finnassa), ja Kohassa kuljetettavat ja odottavat sisältyvät aktiivisiin lainoihin, kun taas Finnassa eivät.

Minusta tuntuisi järkevältä jos tuohon Kohan lajitteluun lisättäisiin uudet kohdat tai ainakin yksi yhteinen kohta, johon lasketaan nämä kuljetettavat ja odottavat varaukset (ja jätetään ne tietty sitten pois aktiivisista), niin varausten määrä olisi yhdenmukainen Finnan kanssa, ja meillä olisi samalla silmäyksellä myös tieto tärpänneistä varauksista.

**Comment by MikkoLiimatainen** [comment]
Tässä on minusta myös hyvä huomioida se, että mitä ja mille käyttäjäryhmälle yritetään kommunikoida. Kohassa pitäisin hyödyllisenä jakaa varausten määrät tarkemmin aktiivisiin, kuljetettaviin, noudettaviin ja keskeytettyihin, koska näistä tiedoista voi olla virkailijalle hyötyä.

Finnassa sen sijaan en välttämättä pitäisi hyödyllisenä poistaa tietueen varausmääristä keskeytettyjä, sillä se voi aiheuttaa suurtakin hämmennystä asiakkaassa, joka ei ole perillä järjestelmän toiminnasta. Katsoimme juuri tietueen varausmäärää Finnassa tietueesta, johon kohdistui 1325 varausta. Kun tähän tietueeseen teki varauksen, niin asiakas sai jononumeron 1416. Tämä johtui 90 keskeytetystä varauksesta. Eli nyt tietueen varausten määrä ei välttämättä kerro asiakkaalle mitään hyödyllistä tietoa ja hän varmasti hämmästelee miksi hänen jononumeronsa on noin paljon suurempi kuin mitä tietueessa on varauksia. Ehkä voisi laittaa varausten kokonaismäärän ja lisäksi keskeytettyjen varausten määrän näkyviin erikseen, mutta siinäkin asiakkaan täytyy ymmärtää mikä merkitys keskeytetyillä varauksilla voi olla hänen todelliseen jonosijaintiinsa.

**Comment by atarnus** [comment]
Olen samaa mieltä siitä, että asiakkaalle on ikävää saada se isompi varausjononumero kuin mitä varauksia teokselle näkyy. Varauksen oletettua nopeampi saapuminen taas tuskin useinkaan haittaa, ja jos se herättää ihmettelyä, niin voidaan aina opastaa keskeyttämään. Asiakasnäkymässä hyvät vaihtoehdot olisivat siis joko 1. näyttää kokonaisvaraukset, 2. eritellä aktiiviset ja pysäytetyt.

2. vaihtoehto saattaa hieman hämmentää, mutta toisaalta se antaa täsmällisempää tietoa niille, jotka asian ymmärtävät, ja saattaisi myös herätellä ihmisiä käyttämään keskeytystoimintoa enemmän, mikä lienee aineiston kierrolle hyvä asia. Tärkein ominaisuus olisi kuitenkin tuo aloitusviestissäkin ilmoitettu tilanne, jossa jollain tietueella on suurin osa tai kaikki keskeytettyjä varauksia, mutta asiakas näkee siellä pitkän varausjonon, ja jättääkin teoksen varaamatta, tai ehkä jopa ymmärtää lainattavissa olevan teoksen olevankin ei-saatavilla.

Minä siis kannattaisin tuota 2. vaihtoehtoa, että eritellään aktiiviset ja ei-aktiiviset lainat myös Finnaan.

Ja sitten Kohan puolelta ne odottavat ja kuljetettavat pois aktiivisista, niin meillä on samanlaiset jonojen pituuden käytössä.
(Odottavat ja kuljetettavat ovat ilman jononumeroa - tämä tarkistettiin varmuuden vuoksi vielä Pirkko-Liisan kanssa - sama jononumero näkyy Kohassa ja Finnassa, ja tärpänneiltä puuttuu jononumero.)

**Comment by pknuuti** [comment]
Koska tämä muutos on tuotu jo Kohaan, suljetaanko tiketti, vaikka Finna-puoli on kesken?

**Comment by MikkoLiimatainen** [comment]
Vaski kannattaa Finnaan aktiivisten ja keskeytettyjen erottelua, sekä Kohan puolelta jonojen pituuden yhtenäistämistä tämän tavan kanssa kuten @atarnus ehdottaa.

**Comment by lmstrand** [comment]
Finnaan (ja Finna-pluginiin) on lisätty muutos https://github.com/NatLibFi/koha-plugin-rest-di/commit/ac12aa3d5222552843894f13ad0a9727a0d0858f
jolla voi määrittää, otetaanko varausjonossa huomioon myös keskeytetyt varaukset:

"Suspended holds can be included by including query parameter include_suspended_in_hold_queue=1."

Eli oletuksena ne eivät nyt lukeudu varausjonoon.

**Comment by IrinaHalminen** [comment]
Heitän oman mielipiteeni soppaan, eli mielestäni kuljetettavat ja noudettavat varaukset pitäisi tosiaan saada pois aktiivisten laskujoukosta Kohassa. 

Finnassa varausten määrässä ei siis näy noita kuljetettavia/noudettavia eikä keskeytettyjä, joka saattaa hämätä, kun varauksen on tehnyt ja sija onkin keskeytettyjen määrän verran suurempi. Eikö olisi parempi, että ne lukeutuisivat tuohon varausten kokonaismäärään, koska se ei vaikuta asiakkaan sijaan varausjonossa, eikä vaadi mitään selittelyjä? Tai sitten sanoisi jotenkin sen kokonaismäärän esiin tuoden, esim. "Varauksia 306, joista väliaikaisesti/tilapäisesti/tällä hetkellä (tms.) keskeytettyjä 6".

Ymmärrän kyllä toiveen/tarpeen, että olisivat yhtenäiset Finnassa ja Kohassa. :)

**Comment by emta001** [comment]
Otamme tämän asian pohdintaan meidän päässä kesälomien jälkeen. Katsotaan sitten, mikä olisi järkevin ratkaisu tässä ja kuinka asian kanssa edetään.

**Comment by AnneliO** [comment]
Kohassa

Active/Aktiiviset: ei vielä kiinni jääneet, mutta ei keskeytetty eikä tulevaisuudessa
Triggered/Kiinni jääneet: varauksen tilat T, W, P
Inactive/Ei aktiiviset: alkamispäivä tulevaisuudessa tai keskeytetty

Päivi tekee Finna-kehitysehdotukset-tietovarantoon tiketin Finnaan tehtävistä muutoksista. Jatketaan vkolla 33 Finna-puolen termien miettimistä.

**Comment by pknuuti** [comment]
Vaaran nextillä näkyy nyt näin:
![2023kuvat 583](https://github.com/user-attachments/assets/9303f026-00f8-47c7-b861-f83a0ceb97a3)

**Comment by ElinaUotila** [comment]
Kirkes-nextillä näyttää samalta kuin Vaarassa: 

![image](https://github.com/user-attachments/assets/320cac0e-b4f2-4bff-9b97-fcd9470bf3b9)

**Comment by ajrajala** [comment]
Tekstit ja määrät myös vaski-nextillä kunnossa.

**Comment by Kati-Helle** [comment]
Helle-nextissä ok.

**Comment by AnneliO** [comment]
Tämä tuntuisi toimivan oikein, joten suljen tiketin. Muutos tulee mukaan versionvaihdossa.

**Comment by AnneliO** [comment]
Tää pitääkin vielä dokumentoida, joten avaan sittenkin tiketin ja pistin Hannan/Lumpukoiden piikkiin. :D

**Comment by Hanna-Lumme** [comment]
Lisätty Kohan ohjeisiin. :)
