### ISSUE TITLE
Takaajan tietoihin tekstimuutosehdotus taattavan maksuista, ehdotus 2

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1173]
### Kehitysehdotukseni

Tiketissä KohaSuomi/Koha-translations#46 on pyydetty taattavan maksunäkymään tekstimuutosta, jonka voisi ilmeisesti toteuttaa kevyemmin käännösmuutoksena. 

Tämä tekstin lisäysehdotus vaatisi ilmeisesti koodimuutoksia.

Voisiko taattavien maksunäkymätekstiin saada lisäksi tiedon, kuinka paljon maksuja taattavilla on yhteensä?
Eli teksti olisi kokonaisuudessaan näin: 

"**Maksut**: Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä 9,50 €." Yhteensä (sis. maksut, jotka eivät vaikuta lainauskieltoon): 13 € . Näytä kaikki maksut."

![image](https://github.com/KohaSuomi/Koha/assets/98814860/45585958-b5b7-49ea-94e7-43166fccc5ea)

**Comment by AnneliO** [comment]
Asiantuntijaryhmään valmistelua: @pirliis Taattavat maksut -välilehden ongelmasta voisi tehdä erillisen tiketin.

**Comment by pirliis** [comment]
#1239

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Toteutetaan itse ja tarjotaan yhteisölle muutos. Edellinen vastaava on mennyt siellä läpi.

**Comment by AnneliO** [comment]
@pirliis Teetkö tästä tiketin yhteisön Bugzillaan?

**Comment by pirliis** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37102

**Comment by lmstrand** [comment]
Tästä viety korjaus testeille.

**Comment by lmstrand** [comment]
Käyttöön tarvitsee sysprefejä:

 NoIssuesChargeGuarantees 	
Estä asiakasta lainaamasta, jos hänen taattavillaan on maksuja enemmän kuin EUR maksuja.
NoIssuesChargeGuarantorsWithGuarantees 	
Estä asiakasta lainaamasta, jos asiakkaalla on takaajia ja noiden takaajien taattavilla on yhteensä enemmän kuin EUR maksuja.

**Comment by AnneliO** [comment]
Suomenkieliset käännökset viety GitHubiin.

**Comment by pirliis** [comment]
> Käyttöön tarvitsee sysprefejä:
> 
> NoIssuesChargeGuarantees Estä asiakasta lainaamasta, jos hänen taattavillaan on maksuja enemmän kuin EUR maksuja. NoIssuesChargeGuarantorsWithGuarantees Estä asiakasta lainaamasta, jos asiakkaalla on takaajia ja noiden takaajien taattavilla on yhteensä enemmän kuin EUR maksuja.

Nämä on kimppakohtaisesti päätettävissä, onko käytössä vai ei. OUTIssa nämä ei ole olleet koskaan käytössä.

**Comment by lmstrand** [comment]
Lisäsin outi-testille seuraavat cronit:

```
 13 09 * * *    $TRIGGER cronjobs/advance_notices.pl -c --itemscontent date_due,title,part_number,enumchron,author,barcode
 13 09 * * *    $TRIGGER cronjobs/overdue_notices.pl -letternumbers 12 -t -p -s -v
 10 00 * * *        $TRIGGER misc/expire_holds.sh EITILASTO KAUKOLAINA KOTIPALVEL
```

**Comment by pirliis** [comment]
OUTIn testillä taattavien maksut näkyvät nyt oikein ja halutulla tavalla. Tosin käännöstekstit ovat vielä puutteelliset.
![image](https://github.com/KohaSuomi/Koha/assets/98814860/db959c21-c256-4d0f-8f6a-8447c5035b35)

![image](https://github.com/KohaSuomi/Koha/assets/98814860/bdbefaaf-ca44-4e2d-95a6-ece054f3de12)

**Comment by MikkoLiimatainen** [comment]
Vaskin testillä maksut esitetään myös halutulla tavalla. Käännökset tosiaan vielä puutteelliset.

Näytä kaikki maksut linkki ei näytä siirtävän sivua Taattavien maksut kohtaan, kuten olisi tarkoitus. Linkki osoittaa nyt sivun kohtaan #guarantees_finesandcharges, kun pitäisi osoittaa kaiketi kohtaan #guarantees_finesandcharges-tab.

**Comment by pirliis** [comment]
> Vaskin testillä maksut esitetään myös halutulla tavalla. Käännökset tosiaan vielä puutteelliset.
> 
> Näytä kaikki maksut linkki ei näytä siirtävän sivua Taattavien maksut kohtaan, kuten olisi tarkoitus. Linkki osoittaa nyt sivun kohtaan #guarantees_finesandcharges, kun pitäisi osoittaa kaiketi kohtaan #guarantees_finesandcharges-tab.

OUTIn testillä kun klikkaa linkkiä "Näytä kaikki maksut", avautuu Taattavien maksut -välilehti, mutta sivua pitää vierittää alas, jotta välilehdet tulevat näkyville. Auttaisiko tuo "tab", että sivu myös pomppaisi välilehtien kohdalle?

**Comment by MikkoLiimatainen** [comment]
> > Vaskin testillä maksut esitetään myös halutulla tavalla. Käännökset tosiaan vielä puutteelliset.
> > Näytä kaikki maksut linkki ei näytä siirtävän sivua Taattavien maksut kohtaan, kuten olisi tarkoitus. Linkki osoittaa nyt sivun kohtaan #guarantees_finesandcharges, kun pitäisi osoittaa kaiketi kohtaan #guarantees_finesandcharges-tab.
> 
> OUTIn testillä kun klikkaa linkkiä "Näytä kaikki maksut", avautuu Taattavien maksut -välilehti, mutta sivua pitää vierittää alas, jotta välilehdet tulevat näkyville. Auttaisiko tuo "tab", että sivu myös pomppaisi välilehtien kohdalle?

Juu, testasin selaimen tarkista-toiminnolla muokata tuon linkin tuolla tavalla, niin silloin se siirtää käyttäjän suoraan oikeaan kohtaan. Tässä on varmaan tuon välilehden id muutettu ja linkki osoittaa vielä vanhaan id:hen.

**Comment by AnneliO** [comment]
Hetken meni ennen kuin tajusin, että tekemäni aiemmin tekemäni käännösmuutos oli puutteellinen. :D Nyt kuitenkin viety koha-translations-tietovarantoon uusi versio, jossa:

Patron's guarantees collectively owe %s.

Asiakkaan taattavilla on yhteensä maksuja %s. -> Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä %s.

Tulee testeille näkyviin seuraavassa buildissä.

**Comment by lmstrand** [comment]
Sivun vieritykseen korjaus yhteisössä: https://github.com/Koha-Community/Koha/commit/e2d54b1279b65507596ca3a08d6b44d1b15fe2b8

**Comment by lmstrand** [comment]
Käännös ja sivun vieritys kaikkiin maksuihin pitäisi olla  korjattuna testeillä.

**Comment by AnneliO** [comment]
Hmm.. käännösmuutos ei nyt näy jostain syystä vaikka sen mielestäni tein kyllä.

https://github.com/KohaSuomi/Koha-translations/commit/2b67331b22dd6313574014b17b557061e2554f4a

Selvittelen vielä.

**Comment by AnneliO** [comment]
Aaaah, lainauskieltoon liittyviä tekstejä olikin useampia. Tehty myös nämä muutokset.

Patron's guarantees collectively owe %s. %s -> Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä %s.
Patron's guarantees collectively owe %s. Total (incl. non-blocking): %s. -> Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä %s. %s 
Patron's guarantees collectively owe %s. Total (incl. non-blocking ): %s. Guarantees total (incl. non-blocking ): %s. %s -> Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä %s. Taattavilla yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): %s. 
The patron's guarantors and their other guarantees collectively have a debt of %s. -> Asiakkaan taattavilla on lainauskieltoon vaikuttavia maksuja yhteensä %s. Yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): %s. Taattavilla yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): %s. %s 
Patron's guarantors and their other guarantees collectively owe %s. %s -> Asiakkaan takaajilla ja heidän muilla taattavillaan on lainauskieltoon vaikuttavia maksuja yhteensä %s.
Patron's guarantors and their other guarantees collectively owe %s. Total (incl. non-blocking): %s. %s -> Asiakkaan takaajilla ja heidän muilla taattavillaan on lainauskieltoon vaikuttavia maksuja yhteensä %s. %s 
Patron's guarantors and their other guarantees collectively owe %s. Total (incl. non-blocking): %s. %s  -> Asiakkaan takaajilla ja heidän muilla taattavillaan on lainauskieltoon vaikuttavia maksuja yhteensä %s. Yhteensä (sis. maksut, jotka eivät vaikuta lainakieltoon): %s. %s

**Comment by AnneliO** [comment]
Testasin tällä asiakkaalla: https://outi-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=91426

Lari ajoi buildin uudelleen ja nyt minusta käännös on nyt oikein kohdillaan. Sivun vierityskin toimii linkistä oikein.

**Comment by pirliis** [comment]
Jep, OUTIn testillä käännökset näkyvät nyt oikein takaajan Tiedot-sivulla. :)
![image](https://github.com/user-attachments/assets/4c94a636-cade-4bf6-a908-44b7b0d77ee4)
