### ISSUE TITLE
Elasticsearch ei käsittele skandeja oikein hauissa eikä aakkostuksissa

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha#1177]
### Mikä vikana?

Koha ei tällä hetkellä erottele toisistaan A, Ä, Å (a, ä,å) ja O ja Ö (o, ö) kirjaimia haettaessa eikä hakutuloksia aakkostettaessa. Esimerkiksi "vaarassa" hakutermi täsmää myös "väärässä" tekstiin tietueessa.

Elasticsearchista löytyy scandinavian_folding, normalisointi, jolla tuon erottelun _periaatteessa_ saisi tapahtumaan oikein, mutta sen käyttöönotto vaatii luultavasti oman (Koha-Suomi spesifin?) normalisointisäännöstön luomisen. 

### Mitä pitäisi tapahtua

Skandit pitäis erottaa haussa ja aakkostuksessa "pistettömistä" kirjaimista eikä esimerkiksi "vaarassa" hakutermin tulisi täsmätä "väärässä" tekstiin. Aakkostuksessa ÅÄÖ pitäisi sijoittua oikeille paikoilleen eikä sekaisin A ja O kirjainten kanssa.

### Kuinka toistaa ongelma/asia

Tee haku vaikkapa termilla 'aiti' (ei varmaan pitäisi palauttaa paljon mitään). Hakutuloksissa mukana on myös 'äiti' termin sisältävät tietueet. Huomaa myös tietueiden järjestys esimerkiksi nimekkeen mukaan järjestettäessä (A, Ä ja Å kirjaimet ovat sekaisin keskenään).

### Selain

```markdown
Ei ole selainasia vaan liittyy hakukoneen konfiguraatioon.
```

### Jotain muuta?

Normalisointi määritellään Kohassa admin/searchengine/elasticsearch/index_config.yaml ja field_config.yaml tiedostoissa. Tietoja elasticsearchin normalisoinnista löytyy täältä: https://www.elastic.co/guide/en/elasticsearch/reference/current/normalizer.html

**Comment by AnneliO** [comment]
Lari löysi tällaiset tiedot:


Tuolla sivulla alhaalla on miten elasticsearchiin saa sen suomenkielen tuen (Ä=A probleema): https://wiki.koha-community.org/wiki/Elasticsearch

Here is an example index_config.yaml for Swedish/Finnish.

```
---
index:
analysis:
analyzer:
analyser_phrase:
tokenizer: keyword
filter:
- finnish_folding
- lowercase
char_filter:
punctuation
analyser_standard:
tokenizer: icu_tokenizer
filter:
- finnish_folding
- lowercase jne.
```

**Comment by lmstrand** [comment]
Muokkasin yhteisön 23.11-branchissa olevaa index_config.yaml-tiedostoa tuon yhteisön linkin suomi/ruotsikonfiguraation materiaalin sisältäväksi ja sain aikaiseksi toimivan konfiguraation. Lisäsin muokatun tiedoston elasticsearch_index_config.yaml koha-suomi-utilityyn yhteisön field_config.yaml-tiedoston kanssa.

Lisäsin nuo konffaustiedostot Vaski-nextin koha-konffiin ja ajoin uudelleenindeksoinnin sinne.

**Comment by lmstrand** [comment]
Pitää tutkia miten tuo järjesteleminen toimii. Se ei enää elasticsearchiin ymmärtääkseni liity.
Lisäsin index_config.yaml:iin asetuksen index.number_of_replicas: 0 ja kommentoin muut, joidden vaikutuksesta ei ole hajua. Tuo replica piti ennen poistaa skriptillä uuden indeksin rakentamisen jälkeen. Toivottavasti ei enää.

Vaara-next myös indeksoitu uusiksi uudella konffilla.

**Comment by lmstrand** [comment]
Nexteille lisätty myös aakkostukseen ruotsinkieltä vastaava kirjainten käsittely, ja nyt näyttää sorttauskin toimivan huomioiden skandit oikein. Nextit on myös indeksoitu uusiksi uuden konfiguraation kera. Outi-next indeksoituu tänä yönä uusiksi.

**Comment by AnneliO** [comment]
Testailin hakutulosten järjestämistä sekä nimekkeen mukaan a-z että tekijän mukaan a-z ja ääkköset tuntuisi nyt menevän suomalaisittain oikein.

**Comment by lmstrand** [comment]
Muutokset tuotannossa. Suljen tiketin.
