### ISSUE TITLE
Lappi : neljän lainaus-palautusautomaatin tunnukset palvelimelle

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1178]
### Tukipyyntö

Rovaniemen Asemakirjaston neljälle automaatille tarvittaisiin tiedot palvelimelle. Tiedot lähetetty Koha-Suomen support-sähköpostiin turvapostilla.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle.

**Comment by LeenaKinnunen** [comment]
Kiitos Emmi!
