### ISSUE TITLE
Asiakkaat ovat saaneet noutamattoman varauksen maksuja varauksista, jotka ovat heillä lainassa

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1181]
### Mikä vikana?

Kirkesissä on lyhyen ajan sisällä tullut kaksi tapausta, jossa asiakas on lainannut varauksensa, mutta varaus on silti jäänyt jotenkin voimaan ja tullut mukaan varausten vanhenemisajoon. Ajon myötä asiakas on saanut noutamattoman varauksen maksun, vaikka varaus on noudettu noutoajan puitteissa. 

Tapaus 1. 
![varaus ei täyttynyt 3](https://github.com/KohaSuomi/Koha/assets/112157980/2ec32323-3b12-499d-918d-5a7fec11b798)
![varaus ei täyttynyt 4](https://github.com/KohaSuomi/Koha/assets/112157980/1635b4de-ebe2-4f6b-9b6e-9e6654cccbb5)

Tapaus 2. 
![varaus ei täyttynyt 1](https://github.com/KohaSuomi/Koha/assets/112157980/9bd777f0-aabb-4ae8-aaf2-5c1028ff551c)
![varaus ei täyttynyt 2](https://github.com/KohaSuomi/Koha/assets/112157980/a7f051c7-3381-4970-a94f-e374894e661a)

### Mitä pitäisi tapahtua

Varauksen lokitietoihin olisi pitänyt tulla tieto varauksen täyttymisestä siinä vaiheessa, kun nide lähti asiakkaalle lainaan. Näin ei kuitenkaan tapahtunut.

**Comment by johannaraisa** [comment]
Koha-Suomen kehittäjien viikkopalaveri 3.6.2024: Seurataan tilannetta, tuleeko vielä nykyisessä versiossa.

**Comment by ElinaUotila** [comment]
Tuli vastaan uusi tällainen tapaus, jossa varaus on sekä lainattu että noudettavana:

![varauslainassajanoudettavana1](https://github.com/user-attachments/assets/a617f701-d902-4505-a2f0-4a664f64a1d9)
![varauslainassajanoudettavana2](https://github.com/user-attachments/assets/af652315-29af-4682-af0b-dc54f2a9270b)

Toisin kuin yllä olevat, tämä saatiin kiinni ennen kuin varaus ehti vanhentua ja tulla vanhentuneiden noutamattomien varausten raportille.

**Comment by AnneliO** [comment]
Sellaisia huomioita, että tuolla niteelle 617633 on lisätty muutoslokin mukaan 31.10.2024 10:44 notforloan-tila 9. Se ainakin estää varauksen poistumisen lainatessa. Varaus on tullut noudettavaksi 25.10.2024 13:17 ja lainattu 4.11.2024 klo 17:36, joten notforloan-tila on käsittääkseni lisätty silloin, kun varaus on noudettavissa.

**Comment by ElinaUotila** [comment]
No, se taitaakin sitten selittää sen. Täytyy varmaankin täsmentää toimintaohjeita noiden notforloan-tilojen kanssa.

**Comment by AnneliO** [comment]
Testasin vielä testillä ja jos lainaa tuollaisen niteen (ohittaa lainakiellon), jossa on notforloan-tilana UpdateNotForLoanStatusOnCheckout -järjestelmäasetuksessa määritetty ONLYMESSAGE-ilmoitus, niin niteen notforloan-tilaksi tulee 0 ja muutos ei tallennu action_logs-tauluun.

**Comment by ElinaUotila** [comment]
Eli tila siis poistuu tässä tapauksessa ilman, että siitä jää mitään jälkeä? Tämä selittäisi yhden toisenkin mystisen tapauksen, jota olen pohtinut. 

Täytyy testailla tätä lisää.

**Comment by AnneliO** [comment]
Juu, siltä se nyt näyttäisi. Minusta tuon ONLYMESSAGEN ei pitäisi edes poistaa notforloan-tilaa, joten jotain outoa tuossa nyt on. 

Mutta sinänsä tuo notforloan-tilan lisääminen kesken noutoajan on ainakin tuon viimeisimmän tapauksen selitys. Pitää tosiaan tutkia tuota tilan poistumista ja lokittumattomuutta lisää versionvaihdon jälkeen. (Tai voishan sitä testata nextillä ainakin näin alkuunsa).

**Comment by ElinaUotila** [comment]
Hyvin pikaisissa alustavissa testeissä nextillä näyttää siltä, että ONLYMESSAGE poistaa tilan, mutta sen poistuminen ei lokitu. Eli sama homma kuin testillä. 

Kun otin kaikki ONLYMESSAGE -arvot pois UpdateNotForLoanStatusOnCheckout -asetuksesta, tilat eivät enää poistuneet. Notforloan-tilasta tuli kuitenkin lainatessa huomautus. 

UpdateNotForLoanStatusOnCheckin-järjestelmäasetuksessa ONLYMESSAGE toimii oikein, eikä tila poistu palautuksessa.

**Comment by ElinaUotila** [comment]
Sellainen huomio vielä, että UpdateNotForLoanStatusOnCheckout-järjestelmäasetuksen kuvauksessa ei mainita mitään ONLYMESSAGE-vaihtoehdosta. Eli voi olla että tässä on käynyt niin, että olen vain olettanut asetuksen toimivan samalla logiikalla UpdateNotForLoanStatusOnCheckin, mutta nuo ONLYMESSAGE-arvot pitäisi jättää pois.

**Comment by AnneliO** [comment]
Tuo sama kävi minullakin mielessä, mutta yhteisön manuaalissa asetuksen kuvauksessa tuo ONLYMESSAGE-vaihtoehto mainitaan: https://koha-community.org/manual/24.05/en/html/circulationpreferences.html#updatenotforloanstatusoncheckout Mutta onko se siellä virheellisesti, onkin sitten eri asia.

En löydä Bugzillasta oikein mitään tähän liittyvää. Ainoa, mitä löytyy asetuksen nimellä on tiketti, jossa pyydetään nidekohtaista määritystapaa kuten checkin-asetuksessa.

Voisin testailla tätä vielä sandboxissa.

**Comment by AnneliO** [comment]
Jeps, sandboxissakin käy niin, että jos  UpdateNotForLoanStatusOnCheckout-asetuksessa määrittää ONLYMESSAGE:lla notforloan-arvon ja käytössä on AllowNotForLoanOverride -järjestelmäasetuksessa "Salli" ja lainaa määritetyn notforloan-tilaisen niteen asiakkaalle -> poistuu notforloan-tila. Eikä notforloan-tilan muutos lokitu action_logs-tauluun.

**Comment by AnneliO** [comment]
Selvittelimme tätä vielä Johannan ja Emmin kanssa lisää ja yhteisön dokumentaatio on virheellinen.  UpdateNotForLoanStatusOnCheckout-järjestelmäasetus ei tue tuota ONLYMESSAGE-toimintoa. Se varmaankin nyt asettaa oletusarvon, kun ei tunnista annettua merkkijonoa miksikään notforloan-tilaksi.

Eli toisin sanoen, nuo ONLYMESSAGEt kannattaa ottaa pois. :)

**Comment by AnneliO** [comment]
Tein dokumentaatiosta bugin Bugzillaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38355
