### ISSUE TITLE
Hetuttomien asiakkaiden vanhentumispäivän muutos

### ISSUE THREAD

**Issue by iinaniemi** [KohaSuomi/Koha#1182]
### Tukipyyntö

Vaskissa on sääntö, että ilman hetua lisätty asiakas saa olla voimassa vain vuoden kerrallaan. Meiltä löytyy kuitenkin paljon asiakkaita joilta puuttuu henkilötunnus, mutta joiden voimassaolo on pidemmällä kuin vuoden päässä. Meidän pitäisi siis saada näille päivitettyä vanhenemispäivä vuoden päähän.

Vanhentumispäiviä olisi hyvä porrastaa, jotta kaikki eivät sattuisi samalle hetkelle. Meillä oli tällainen ajatus:
Voisi etsiä raportilla kaikki hetuttomat henkilöasiakkaat, lapsiasiakkaat ja huollettava, muu kuin lapsi -asiakkaat, joiden vanhenemispäivä on kauempana kuin esim. 30.4.2025.
 
Jotta vanhentumispäivät jakautuisivat suhteellisen tasaisesti, voisi määrittää, että jos vanhentumispäivä on esim kesäkuussa 2028, laitettaisiin vanhentumispäivä kesäkuulle 2025, jos joulukuussa 2026, laitettaisiin joulukuu 2025 jne. Eli sama kuukausi kuin aikaisemminkin, mutta vuosi päivitettäisiin vuoteen 2025. Ainoastaan tammi-huhtikuussa vanhentuvien vuodeksi pitäisi laittaa 2026. Käytännössä siis jos MONTH(dateexpiry) < 5, niin muutetaan dateexpiry vuodeksi 2026, muutoin vuodeksi 2025.

Saiko tästä selityksestä jotain selvää? Onko toteutettavissa? Onko parempia ajatuksia tuohon eri ajankohdille jakamiseen?

Lisäksi viestikenttään lisättäisiin viesti: Ei Hetua, vanhentumispäivä päivitetty.

**Comment by lmstrand** [comment]
Kuulostaa järkevältä ja on toteutettavissa.

**Comment by lmstrand** [comment]
Kuulemma onnistuu myös asiakkaiden erämuokkauksella. Pystyttekö sillä tekemään tämän? Voin tehdä raportin borrowernumbereista jos tarvitsee.

**Comment by iinaniemi** [comment]
Asiakkaiden erämuokkaus taipuu vähän huonosti tähän, kun pitäisi saada nuo viestit myös lisättyä. Täytyisi saada messages tauluun message_type L tyyppinen viesti, jolloin se olisi sellainen kuin nuo viestit mitä meillä käytetään. Borrowernotesia meillä ei ole käytössä. Erämuokkauksella sitä viestiä ei taida pystyä lisäämään?

**Comment by lmstrand** [comment]
Aivan. Tehdään sitten tietokanta-ajolla.

**Comment by lmstrand** [comment]
Tässä ajossa siis ei koskettaisi sotuttomiin asiakkaisiin, joiden vanhenemisvuosi on aiemmin kuin tänään + 1 vuosi. Kaikille muille vanhenemisvuodeksi 2025, mutta kuukausi ja vanhentumispäivä säilyisivät päivämäärässä. Onko ok?

Ajoon mukaan tulevat asiakkaat ja niiden nykyiset vanhenemispäivät:

select borrowernumber, dateexpiry from borrowers where dateexpiry > DATE_ADD(NOW(), INTERVAL 1 YEAR)
and categorycode = 'HENKILO'
and borrowernumber not in (select borrowernumber from borrower_attributes where code = 'SSN')

**Comment by lmstrand** [comment]
Miksi asiakkaille, jotka erääntyvät tammi-huhtikuussa 2025, pitää siirtää vuodella eteenpäin vanhenemisaika? Eikö kyseisillä asiakkailla se tili ole nyt vanhenemassa, kuten kuuluu?

**Comment by atarnus** [comment]
Tässä olisi raportti, jota voitte vilkaista että näyttääkö oikealta:

```
SELECT borrowernumber, dateexpiry,
       CASE WHEN MONTH(dateexpiry) > 4
            THEN DATE_SUB(dateexpiry, INTERVAL (YEAR(dateexpiry) - 2025) YEAR)
            ELSE DATE_SUB(dateexpiry, INTERVAL (YEAR(dateexpiry) - 2026) YEAR)
       END AS new_expiry
  FROM borrowers
 WHERE categorycode = 'HENKILO'
   AND dateexpiry > CURRENT_DATE + INTERVAL 1 YEAR
   AND borrowernumber NOT IN (SELECT borrowernumber
                                FROM borrower_attributes
                               WHERE code = 'SSN')
```

Voitte tarkistaa että new_expiry näyttää oikealta ja oikeat asiakkaat tarttuvat tuloksiin.
Voidaan ajaa sitten jos on ok.

**Comment by MikkoLiimatainen** [comment]
Nähdäkseni tuo raportti antaa muuten juuri oikean tuloksen ja uudet päivämäärät, mutta siitä puuttuu lapsi ja muuhuollettava asiakastyypit. Eli  `WHERE categorycode IN ('HENKILO', 'MUUHUOL', 'LAPSI')` olisi oikea rivi tuohon.

**Comment by atarnus** [comment]
Hyvä huomio, kopsasin tuon vain toisen lausekkeen pohjalta enkä yhtään miettinyt noita oikeita categorycodeja.

**Comment by lmstrand** [comment]
ajettu:

```
MariaDB [vaskiprod]> CREATE TABLE ks_20240503_borrowers_gh1182 AS
    -> 
    -> SELECT borrowernumber, dateexpiry,
    ->        CASE WHEN MONTH(dateexpiry) > 4
    ->             THEN DATE_SUB(dateexpiry, INTERVAL (YEAR(dateexpiry) - 2025) YEAR)
    ->             ELSE DATE_SUB(dateexpiry, INTERVAL (YEAR(dateexpiry) - 2026) YEAR)
    ->        END AS new_expiry
    ->   FROM borrowers
    ->  WHERE categorycode IN ('HENKILO', 'MUUHUOL', 'LAPSI')
    ->    AND dateexpiry > CURRENT_DATE + INTERVAL 1 YEAR
    ->    AND borrowernumber NOT IN (SELECT borrowernumber
    ->                                 FROM borrower_attributes
    ->                                WHERE code = 'SSN');
Query OK, 30549 rows affected (2.917 sec)
```

**Comment by MikkoLiimatainen** [comment]
Juu, tuon taulun sisältö näyttää hyvältä. Päivityksen voi ajaa tuotantoon

**Comment by lmstrand** [comment]
Ajettu:
``
MariaDB [vaskiprod]>      UPDATE borrowers  
    ->     INNER JOIN  
    ->     ks_20240503_borrowers_gh1182
    ->     ON borrowers.borrowernumber = ks_20240503_borrowers_gh1182.borrowernumber
    ->     SET borrowers.dateexpiry = ks_20240503_borrowers_gh1182.new_expiry;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    16505631
Current database: vaskiprod

Query OK, 25189 rows affected (2.163 sec)
Rows matched: 30549  Changed: 25189  Warnings: 0

```

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [vaskiprod]> INSERT INTO messages (borrowernumber, message_type, message)
    ->        SELECT borrowernumber, 'L', 'Ei Hetua, vanhentumispäivä päivitetty.' FROM ks_20240503_borrowers_gh1182;
Query OK, 30549 rows affected (0.519 sec)
Records: 30549  Duplicates: 0  Warnings: 0

```

**Comment by lmstrand** [comment]
Viestiajoon tuli touko-joulukuussa 2026 vanhentuvia asiakkaita mukaan, joiden pvm ei muuttunut, mutta voidaan poistaa näiltä viestit jos tarvitsee.
