### ISSUE TITLE
OUTI: Laskun peruminen asiakkaalta ettei ehdi lähteä eteenpäin

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1185]
### Tukipyyntö

Laskuttaja vahingossa painoin Luo finvoice -painiketta tämän asiakkaan kohdalla: borrowernumber=161838
Asiakkaalta ja niteeltä on otettu laskumerkinnät pois. 

Voitteko perua laskun tältä asiakkaalta, jotta se ei mene eteenpäin?

**Comment by emta001** [comment]
Outoa, en löydä kys. asiakkaalle finvoice-laskua message_queque-taulusta. Pelkkiä print laskuja :D

**Comment by piiaseme** [comment]
Kiitos salapoliisityöstä, suljen tiketin :-)
