### ISSUE TITLE
Kiireetön varaus: Asiakkaan tiedoissa olevasta varausjonosta ei erotu, jos jokin varauksista on kiireetön varaus

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1187]
### Kehitysehdotukseni

Kun tekee varauksen ja merkitsee sen kiireettömäksi, niin tuo tieto ei näy tallentamisen jälkeen asiakkaan Varaukset-välilehdellä.

Varaus Oulu-teokseen on kiireettömänä tehty nidevaraus. Varaus Koira-nimiseen teokseen on ns. normivaraus, joka on tehty kiireettömänä.
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/1957b77c-f0bd-4184-ad89-a57cf2abd370)

Voisiko kiireettömän varauksen ja nidevarauksen saada jotenkin erottumaan asiakkaan Varaukset-välilehdellä?

### Jotain muuta?

Liittyy ehkä tikettiin https://github.com/KohaSuomi/Koha/issues/1186
Yhteisön sandboxissa oli samanlainen näkymä asiakkaan Varaukset-välilehdellä kuin meillä tuotannossa (22.11) ja nextillä (23.11).

**Comment by atarnus** [comment]
Tämän pitäisi onnistua koodimuutoksella suhteellisen helposti. (Holds-taulun taustalla oli se mystinen massiivinen koha-olio, mutta tällä kertaa tarvittavat tiedot on siinä valmiina mukana, niin ne saa näppärästi poimittua matkaan.)

svc/holds voi lisätä non_priority ja item_level_hold määreet mukaan menemään holds.js:lle
```
        priority              => $h->priority(),
        reservenotes          => $h->reservenotes(),
        non_priority          => $h->non_priority(),
        item_level_hold       => $h->item_level_hold(),
```

jolloin taulukon rakentamiseen saa nuo arvot mukaan:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/73ff5761-7d7c-4ee4-ac8e-6ddaf97acc12)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Ei toteuteta.

@piiaseme tekee tästä yhteisöön kehitysehdotuksen, mutta ei seurata sen etenemistä meidän Githubissa, eli suljetaan tiketti näiltä osin.
