### ISSUE TITLE
Lappi: ID kiinni kahdessa taulussa.

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1192]
### Tukipyyntö

Seuraava ID on kiinni kummassakin taulussa biblio ja deletedbiblioitems:
1805769
Saa poistaa deleted-taulusta. On osakohde ja emo löytyy.

**Comment by lasse-koha** [comment]
Poistettu.

**Comment by PiaKusmin** [comment]
Kiitos. Suljen tiketin.
