### ISSUE TITLE
Kori: Osakohteen Nimeke-sarakkeen Finna-linkit

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1193]
### Kehitysehdotukseni

Jos koriin on lisännyt osakohteen, niin korissa Nimeke-sarakkeessa on linkki sekä emolle että osakohteelle. Molemmat linkit ovat tarpeen, mutta saisiko näkymää selvennettyä siten, että niistä näkisi samantien, kumpi on kumman linkki?

Ylemmällä rivillä on  esimerkki emon näkymästä korissa ja alemalla osakohteen:
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/454bc2c0-4edc-42f9-a305-321bc2f1a9d8)

### Jotain muuta?

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/883

**Comment by piiaseme** [comment]
OUTIssa toimii ja nyt linkki-nappulat erottuvat toisistaan.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 13.5.2024: Tehdään liitännäiseksi. Vanha korilinkki pitää poistaa IntranetUserJS:stä, kun liitännäinen asennetaan.

**Comment by pknuuti** [comment]
Vaaran testillä toimii uusi rimpsu, linkit erottuvat toisistaan.

**Comment by atarnus** [comment]
Edelleen muuten muistutuksena, että kun testaatte Kohan testiltä ja jos linkki vie tuontanto-Finnaan, niin biblionumbereissa saattaa olla eroa, ja linkki viedä näennäisesti "väärään" paikkaan. Kannattaa tuolloin tarkistaa, että linkissä näkyvä biblionumber on nimenomaan yhtenevä Kohan kanssa.

**Comment by Kati-Helle** [comment]
myös Hellen testillä erottaa nyt emon ja osakohteen toisistaan.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5f2ce31d-3dc2-4710-9398-47d9bbf4d4a0)

**Comment by atarnus** [comment]
> Myös Kyytin testillä toimii ja linkit erottuvat selkeästi. Jos osakohteen lisää koriin perustiedot näytön kautta ja sen jälkeen lisää niteitä/osakohteita koriin suoraan hakutulosten kautta saa hieman hassun ilmoituksen. Esimerkiksi omassa korissa oli lisättynä 11 kohdetta. Koitin lisätä seuraavan osakohteen koriin perustiedot näytön kautta niin sain ilmoituksen "Tämä nide on lisätty koriisi". Kun lisäsin seuraavan osakohteen koriin taas hakutuloslistan kautta tuli ilmoitus "1 teosta lisätty koriin". Tämän jälkeen kun lisäsi vielä toisen osakohteen hakutulosnäytön kautta tuli ilmoitus "1 teosta lisätty koriin 1 on jo korissasi" vaikka tässä kohtaa osakohteita/niteitä oli lisättynä koriin jo 14. Sinällään tuo ei vaikuta korin toimintaan kai mitenkään ja nuo uudet nappulat toimivat hyvin, tuo huomio tuli vain tuossa sivussa tehtyä.

Sain toistettua tämän itse. Teetkö asiasta oman tiketin? Voisi vilkaista mikä tuossa mättää, vaikkei "iso" asia olekaan.

**Comment by VaisanRo** [comment]
Tein tästä nyt oman tiketin #1219

**Comment by MikkoLiimatainen** [comment]
Uusi rimpsu toimii, linkit erottaa nyt hienosti toisistaan.

**Comment by ReettaSiili** [comment]
Samoin Siilissä toimii hienosti.

**Comment by AnneliO** [comment]
Plugarisoitava.

**Comment by AnneliO** [comment]
Liittyy tikettiin #883

**Comment by lmstrand** [comment]
Plugarisointi vaatii muutoksen basket.tt-tiedostoon, siitä puuttuu [% INCLUDE '[intranet-bottom.inc](http://intranet-bottom.inc/)' popup_window=1 %] joka hakee liitännäisten intranet-javascriptit.

**Comment by lmstrand** [comment]
Kehittäjäpalaveri 5.6.: Päivitetään rimpsu intranetUserJS-järjestelmäasetukseen kimpoille, joilla Kori-ominaisuus käytössä. Plugin tallennetaan Githubiin versionvaihdon, jossa edellä mainittu muutos, jälkeistä käyttöönottoa varten. Muutokseen liittyvä tiketti bugzillassa: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37033.

**Comment by piiaseme** [comment]
Tätä ei pystynyt muuttamaan liitännäiseksi ilman koodimuutosta itse Kohaan, joten tämä säilyy toistaiseksi rimpsuna. Rimpsu lisätty tuotantoon ja toimii kuten pitää. Suljen tiketin.
