### ISSUE TITLE
Mikkeli: asiakkaiden tilejä lukittuu

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#1194]
### Mikä vikana?

Tänä aamuna tuli lyhyen ajan sisällä kuusi asiakasta, joiden tilit olivat lukittuneet. Support-lootasta löytyy borrower-numberit. 

En nyt osannut sen paremmin lokeja tulkita, paitsi sen huomion tein, että näistä aamuisista tapauksista kaikki olivat joko palauttaneet kirjoja aamullla TAI heidän sulkuaikana palautuslaatikkoon palauttamiaan kirjoja oli palautettu eilen meillä automaateilla. Nämä tapaukset tulivat esiin Mikkelin pääkirjastossa (MLI_PK) noin tunnin sisään (9.15-10). 

Aamupäivän aikana on tullut koko ajan lisää, jo kymmeniä. Osalla on ollut pinkoodi, osalla ei. Testasin oman palautuksen automaatilla, tili ei lukittunut (sekä kirja jonka lainasin tänään, että aiemmin lainattu kirja). Näitä en ollut lainannut automaatilla.

**Comment by Katja-Lumme** [comment]
Ja vielä se tieto, että Lyngsoen viime kesänä hommatut lainaavat ja palauttavat automaatit meillä käytössä.

**Comment by lmstrand** [comment]
Miksi asiakkailla ei ole pin-koodia? Sip-palvelimelle pitää erikseen määrittää asetus, jos salasanaa ei vaadita laitteelle kirjautumiseen, enkä ymmärrä miten asiakkaat ovat voineet käyttää automaatteja/Finnaa ilman salasanaa.

Lokeilla näkyy palautustapahtumia, mutta ei mitään, joka selittäisi että kun asiakas kirjautuu (patron information request), vastauksessa lukee ACCOUNT LOCKED. Toimintalokeissa tilin lukkiutumisen syy ei paljastu. Onkohan tämä jokin ongelma jonkin meidän tietokantatriggerin kanssa?

**Comment by Katja-Lumme** [comment]
Mikkelissä (eikä taida olla missään lumpeilla) ei ole pinkoodikyselyä lainaus- ja palautusautomaateilla. Ja vanhemmat asiakkaat eivät käytä Finnaa...

**Comment by lmstrand** [comment]
Ja silti tätäkö ei tapahdu muualla, kuin Mikkelissä? Tietokantatriggeritkään eivät tätä selitä. Olisiko esimerkkiasiakasta, jonka tili on tällä hetkellä lukittuna?

**Comment by Katja-Lumme** [comment]
Ei tapahdu muualla, eikä Mikkelin läheistäkään ole kuulunut mitään. Läheissä Mikroväylän automaatit, siksi mietin onko Lysyn automaateilla tässä nyt jotain tekemistä. Kaikki asiakkaat ovat tuossa aspassa halunneet heti tietenkin tilinsä auki- mistähän mie löytäisin tähän esimerkin🤔 Käyn kattomassa palautettua aineistoa, josko sitä kautta löytäisin lukkiutuneita tilejä...

**Comment by lmstrand** [comment]
Lokeilla on password change-tapahtumia. Oletteko nyt lisännyt pin-koodeja asiakkaille, vai miten tuo lukkotilanne on ratkaistu, kun ei näy lokeilla lukituksen poistamistapahtumia, vain noita password changeja?

**Comment by Katja-Lumme** [comment]
Johannan kanssa tästä puhuttiin täällä, eli asia nyt näyttäisi olevan ratkaistu, kiitokset!!! Ja siis ollaan lisätty pinkoodit asiakkaille tiskillä että saadaan tilit vapautettua.

**Comment by lmstrand** [comment]
Ok. Hyvä homma.

**Comment by lmstrand** [comment]
Lisäsin kaikille Mikkelin pääkirjaston automaateille pinittömät kirjautumiset sallituksi, eli ei pitäisi enää kerryttää vääriä kirjautumisyrityksiä kyseiset automaatit.

**Comment by lmstrand** [comment]
Voimassa huomisesta lähtien.

**Comment by johannaraisa** [comment]
Katselin noita asiakkaita joilla on paljon näytä yrityksiä, niin ne on parempi vaan hoitaa asiakaspalvelussa. Saa ainakin tuolta nuo huomautukset pois.

**Comment by lmstrand** [comment]
Samaa ongelmaa Pieksämäellä. Palvelinkonfiguraatioon lisätty kimpan kaikille automattitunnuksille tyhjät pin-koodit sallituiksi (ei kerrytä kirjautumisyrityksiä).
Samalla ajettu asiakkaille, joiden tiedoissa on Pieksämäen pääkirjasto:
```
MariaDB [lummeprod]> update borrowers set login_attempts = 0 where branchcode = 'PIE_PK' and login_attempts >8 and categorycode = 'LAPSI';
Query OK, 471 rows affected (0.206 sec)
Rows matched: 471  Changed: 471  Warnings: 0
```

**Comment by Hanna-Lumme** [comment]
Kiitokset korjauksesta!
