### ISSUE TITLE
Lappi: Tärppäämättömien varausten noutopaikan muutos

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1195]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: ROPK (Rovaniemen pääkirjasto).

Kaikki tärppäämättömät varaukset, joiden noutopisteeksi on valittu ROPK muutetaan noutopisteeksi ROPO.

Muutoksen saa tehdä heti kun ennätätte.

**Comment by lasse-koha** [comment]
Ajettu `update reserves set branchcode = 'ROPO' where branchcode = 'ROPK' and found is null;`. Muutos koski 469 varausta.

**Comment by LeenaKinnunen** [comment]
Kiitos, suljen tiketin.
