### ISSUE TITLE
Lumme: kadonnut kausijulkaisunumero

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1198]
### Mikä vikana?

Haukivuorelta ilmoitettiin, että heidän Meidän talo 5/2024 kausijulkaisunumeronsa on kadonnut Kohan tietokannasta. Numero on otettu vastaan 1.5.24 viivakoodilla 491K00471069 ja Kohassa numero näkyykin vastaanotettujen lehtinumeroiden listalla. Kohasta itsestään lehteä ei kuitenkaan löydy. Kävin katsomassa myös deleteditems-taulun raportilla, josko lehti olisi vahingossa poistettu, mutta sitä ei löytynyt sieltäkään.

<img width="424" alt="Lehti 01" src="https://github.com/KohaSuomi/Koha/assets/129748294/9d6f93f7-fae9-4ad3-aca3-37c1c9aa51a3">

<img width="586" alt="Lehti 02" src="https://github.com/KohaSuomi/Koha/assets/129748294/b2922c25-337e-459b-b683-76f0cb1a5465">

**Comment by AnneliO** [comment]
Biblionumberilla 3144904 löytyy deleteditems-taulusta kaksi nidettä, joista toisella ei ole juuri muuta identioifaa tietoa kuin, että koti- ja sijaintikirjasto on MLI_HV, hyllypaikka Y, signum 66.051. Kyseinen nide on poistettu 2024-05-08 13:16:08. Lokilla ei näy niteen poistosta kirjausta.

Eli sanoisin, että joku on todennäköisesti poistanut niteen vahingossa ennen kuin sille on tallennettu tuo mainittu viivakoodi.

**Comment by Hanna-Lumme** [comment]
Tuon niteen olen minä poistanut, sillä kokeilin tallentaa sitä uudelleen tuolta vastaanotettujen kautta. 😅 Ei mennyt ihan nappiin, niin katsoin parhaaksi poistaa sen.

**Comment by AnneliO** [comment]
Jaha, no tutkitaanpas lisää. :D

**Comment by AnneliO** [comment]
Numero tosiaan näkyy serial-taulussa

MariaDB [lummeprod]> select * from serial where subscriptionid=12015;

| serialid | biblionumber | subscriptionid | serialseq | serialseq_x | serialseq_y | serialseq_z | status | planneddate | notes | publisheddate | publisheddatetext | claimdate | claims_count | routingnotes |
---|---|---|---|---|---|---|---|---|---|---|---|---|---|---
|   160596 |      3144904 |          12015 | 2024 : 1  | 2024        | 1           | NULL        |      2 | 2024-01-16  |       | 2024-01-02    |                   | NULL      |            0 | NULL         |
|   161996 |      3144904 |          12015 | 2024 : 2  | 2024        | 2           | 0           |      2 | 2024-02-15  |       | 2024-02-01    |                   | NULL      |            0 | NULL         |
|   163439 |      3144904 |          12015 | 2024 : 3  | 2024        | 3           | 0           |      2 | 2024-03-12  |       | 2024-03-02    |                   | NULL      |            0 | NULL         |
|   164633 |      3144904 |          12015 | 2024 : 4  | 2024        | 4           | 0           |      2 | 2024-04-09  |       | 2024-04-01    |                   | NULL      |            0 | NULL         |
|   165823 |      3144904 |          12015 | 2024 : 5  | 2024        | 5           | 0           |      2 | 2024-05-08  |       | 2024-05-01    |                   | NULL      |            0 | NULL         |
|   167077 |      3144904 |          12015 | 2024 : 6  | 2024        | 6           | 0           |      1 | 2024-05-31  |       | 2024-05-31    | NULL              | NULL      |            0 | NULL         |

Mutta jos numeron serialid:llä hakee serialitems-taulusta, joka linkittää kausijulkaisutilaukset ja nide-taulun, niin nidettä ei löydy sieltäkään.

Testailin vähän lumme-testillä ja en saanut aikaiseksi samanlaista tilannetta. Testasin niin, että otin vastaan numeron ja sitten poistin sen kausijulkaisujen vastaanotossa numerolistauksessa "poista valitut numerot" -napilla. Nide poistui serial- ja serialitems-taulusta jälkiä jättämättä, mutta deleteditems-tauluun se päätyi. Lokille ei tullut mitään merkintää.

**Comment by Hanna-Lumme** [comment]
Joo, toivotaan. 😄 Jäipähän nyt kuitenkin tällaisesta haamusta nyt jälki. Seuraillaan tilannetta.
