### ISSUE TITLE
Täti: Mitä JavaScript-rimpsuja Tätiin tarvitaan?

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1201]
### Kehitysehdotukseni

Sovitaan mitä JS-rimpsuja Tätiin tarvitaan.

Tätin tuotannossa on tällä hetkellä nämä IntranetUserJS-rimpsut:
- Cataloging > Z39.50/SRU pop-up
- Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu 
- Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */ /* Toimii 22.03.2022 MLI */
- Varaustunnuksen generointi/anonymisointi - Adapted from Koha-suomi patch for KD-1452 (commit 1c71b272885d9c510630 from https://github.com/KohaSuomi/Koha/ branch master) 
- Kielten aakkostus/priorisointi tarkassa haussa

**Comment by AnneliO** [comment]
> Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu

Tämä päivittyi  versiossa 23.11, enkä ainakaan minä muistanut käydä muuttamassa sitä täti-nextille. Eli ainakin tuo kaipaa päivitystä.

Päivitetyt [IntranetUserJS-rimpsut löytävät vielä täältä](https://github.com/KohaSuomi/Koha-23x/wiki/IntranetUserJS). Tuolta voisi pääkäyttäjät (ja miksei kuvailijatkin) käydä vilkuilemassa, mitä tarvitaan Tätiin. Kaikkia ei tarvita, koska Tätissä ei ole lainausta/palautusta/varauksia/yms.

**Comment by MikkoLiimatainen** [comment]
Kun en erityisesti tiedä, miten tuota Tätiä käytetään, niin on vaikea kommentoida sitä, mitä rimpsuja sinne kannattaisi laittaa. Huomasin kuitenkin, että jotain vanhentuneita rimpsuja siellä vielä on käytössä.

Ainakin nämä ovat vanhentuneita, eivätkä toimi oikein:

/* Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
 - Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa -kohta on tarpeeton, koska tuo location-haku on muuttunut ja sitä ei vissiin muutenkaan Tätissä tarvita.

/* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */
- Haun muokkauksessa kenttien järjestys ja käytetyt hakutermit eivät välttämättä täsmää. Rimpsu kannattaisi päivittää muokkauksen kanssa paremmin toimivaan.

//Kielten aakkostus/priorisointi tarkassa haussa
- Tässäkin on ongelma haun muokkauksen kanssa. Rimpsu ei toimi kun hakua muokataan.

**Comment by piiaseme** [comment]
Versiossa 24.05

JS-rimpsu;
 /// Estä sivun vieritystä jumimasta pitkillä näytöillä ja tietyn kokoisilla näytöillä
$(document).ready(function() {
  if (typeof dataTablesDefaults !== 'undefined') {
  	dataTablesDefaults.fixedHeader = false;
  }
});

Aktiiviset plugarit:
Add MARC field 001
Authorised values endpoints
Auto Framework Code
borrowers/status endpoint
Delete Biblio Components
EDItX-plugin
Import remote biblios
IntranetUserJS: Alphabetize/prioritize advanced search languages
IntranetUserJS: Changes to search page
IntranetUserJS: Remove excess spaces
IntranetUserJS: Trim Z39.50 search terms
Nalkutin
Tietuesiirtäjä

**Comment by AnttHeik** [comment]
Tuon Auto Framework Code -plugarin voisi ensin kytkeä vain TäTin testille, että sen toimimista voi vähän seurata siellä.

**Comment by piiaseme** [comment]
> Tuon Auto Framework Code -plugarin voisi ensin kytkeä vain TäTin testille, että sen toimimista voi vähän seurata siellä.

Ok, kuittaa tänne, kun se halutaan aktivoida tuotantoon.

**Comment by AnneliO** [comment]
Auto Framework Code ei toimi vielä versionvaihdon jäljiltä.

**Comment by AnttHeik** [comment]
> Auto Framework Code ei toimi vielä versionvaihdon jäljiltä.

Joo, tiedossa on. Piti vain varmistaa, ettei se mene vahingossa päälle TäTiinkin sitten kun se toimii :) Melinda-tietueissa tulee edelleen vastaan kenttiä, joita ei meidän kuvailupohjista löydy.

**Comment by piiaseme** [comment]
Version 24.05 IntranetUserCSS-rimpsut:

Tätin logo-rimpsut
Tätin taustaväri-rimpsu

Levennä otsikkokenttiä
Piilota asiakkaan tiedot -näytöltä muokkaa-linkit. Jatkossa muokkaus onnistuu vain yläreunan Muokkaa-napista 
Käyttäjänimi-kentän piilotus salasananvaihto-sivulla
Piilota Ensisijainen yhteydenottotapa -valinta asiakkaan muokkauksesta
Säädä Selaa sukunimen mukaan -kohdan kirjaimet isommaksi ja harvemmaksi
Säädä Selaa sukunimen mukaan -kohdan kirjaimien taustaväri toiseksi, kun hiiri viedään kirjaimen kohdalle
Piilota asiakashaun "Kaikki"-vaihtoehto
Piilota Asiakkaan pikalisäys -nappi
Rivien otsikot boldilla perustiedot-näytöllä
Boldaa hakutuloslistan ja Osakohteet-välilehden nimekkeet
Säädä perustiedot-näytön kansikuva tietyn kokoiseksi. Muuta pikselikoko tarvittaessa toiseksi.
Muuta kaikissa taulukoissa rivin taustaväri, kun hiiri viedään rivin kohdalle.
Piilota Esikatsele SQL -vaihtoehto valikosta Tallennetuissa raporteissa.

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 26.11.2024: Liitännäisistä voi ottaa pois vielä päältä borrowers/status ja Editx.

Poistin Tätistä jo aiemmin käytöstä myös Auto Framework Code -liitännäisen Antin kommentin perusteella.

**Comment by piiaseme** [comment]
> Pääkäyttäjien palaveri 26.11.2024: Liitännäisistä voi ottaa pois vielä päältä borrowers/status ja Editx.

Poistin nämä Tätistä käytöstä.

**Comment by AnneliO** [comment]
Kiitos Piia! Luulisin, että tämän tiketin voinee jo sulkea. :)

**Comment by piiaseme** [comment]
Suljen tiketin. Avataan varmaan tarvittaessa uudelleen.
