### ISSUE TITLE
Tietueen varausnäkymässä noutokirjasto-alasvetovalikossa kirjastot tunnuksen, ei nimen mukaan aakkosissa

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1202]
### Mikä vikana?

Tietueen varausnäkymässä noutokirjasto-alasvetovalikossa kirjastot tunnuksen, ei nimen mukaan aakkosissa. Esim. Korkalovaaran kirjasto (tunnus ROKO) on aakkosissa R:n kohdalla, ei K:n kohdalla. 
![varauksen_muutos_kirjastot](https://github.com/KohaSuomi/Koha-23x/assets/99165331/0ccc126f-ef80-45e7-93df-2af2ff7bc1d5)

### Mitä pitäisi tapahtua

Tietueen varausnäkymän noutokirjasto-alasvetovalikon tulisi aakkostua kirjaston nimen mukaan.

**Comment by lasse-koha** [comment]
Aakkostus lisätty 0015-branchiin.

**Comment by sksandel** [comment]
Vaskin tuotannossa noutopaikat aakkostuvat oikein, nimen mukaisesti.

**Comment by emta001** [comment]
Onko tämä vielä ajankohtainen nykyisessä tuotannossa?

**Comment by lasse-koha** [comment]
On ja voisi varmaan laittaa tuotantoon?

**Comment by lasse-koha** [comment]
On ajankohtainen niin kauan kuin käytetään meidän versiota varaussivusta. Menossa tuotantoon.

**Comment by Kati-Helle** [comment]
Helle-nextissä kirjastot aakkostuvat nimen mukaan tietueen perustietojen varaukset-välilehden olemassa olevien varausten muokkauksessakin.
Poikkeuksena ääkkösellinen kirjastonimi (kuvassa Särkijärven koulun kirjasto)

![kuva](https://github.com/user-attachments/assets/8fbdf70f-636d-407b-be31-2b4a5b6e23d2)

Kirjastojen tunnukset
PUKPK
RASBU
ASKSK
SIPPK
SIPBU

**Comment by pknuuti** [comment]
Vaaran nextillä testattu: noutopaikkavalikko tulee kirjaston nimen mukaan aakkosiin varausta tehtäessä, varauksen noutopaikkavalikossa sekä asiakkaan tiedoissa varauksen kohdalla. Eli toimii oikein.
