### ISSUE TITLE
Käännösvirhe toimittajatiedoissa olevassa valikossa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1204]
### Mikä vikana?

Toimittajan tiedoissa on uusi välilehti ongelmien tallentamista varten. Itse sivulla Vendor issues kääntyy "Toimittajan ongelmat" mutta vasemman laidan valikossa harhaanjohtavasti Issues => Numeroita.

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha-23x/assets/44638512/ad5f1dea-0fb6-466f-965b-dc8a0c336480)

**Comment by emta001** [comment]
Koha-Suomen palaveri 9.9.2024: Tarkistatko @ajrajala, että onko tämä korjaantunut nextillä?

**Comment by ajrajala** [comment]
Tämä nyt ok, toimittajan tiedoissa vasemman laidan valikossa nyt Vendor issues / Toimittajan ongelmat.
