### ISSUE TITLE
Tietuesiirtäjä: Valuneisiin osakohteisiin ei muodostu aineistotyyppiä

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1205]
### Mikä vikana?

Valuneisiin osakohteisiin ei muodostu aineistotyyppiä tällä hetkellä. esim. 2352523 ja 2348620

**Comment by piiaseme** [comment]
Korjaus siirtyi tuotantoon vkon 20 päivityksessä. Suljen tiketin.

**Comment by PiaKusmin** [comment]
Kuvailijoilta tuli tietoa, että Lapissa ei ilmeisesti vielä toimi. 
Tässä esimerkki biblionumber=1936923

**Comment by johannaraisa** [comment]
> Kuvailijoilta tuli tietoa, että Lapissa ei ilmeisesti vielä toimi. Tässä esimerkki biblionumber=1936923

Okei, tutkitaan.

**Comment by johannaraisa** [comment]
Nyt toimii, teillä oli määritelty "Tietueiden yhdistämissäännöissä", että ei saa lisätä noita 942-kenttiä. Muutin sen, että "Suojaa poistamiselta".

**Comment by PiaKusmin** [comment]
Kiitos! Suljen tiketin.
