### ISSUE TITLE
Uusi/palauta valitut niteet -valintanapit eivät toimi

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1207]
### Mikä vikana?

Päivityksen myötä Palauta / Uusi valitut niteet -nappi muuttuivat omiksi valintanapeikseen. Lumpeissa kumpikaan ei tällä hetkellä toimi oikein, vaan pysyvät harmaana, kun tiettyjä niteitä haluaisi esim. uusia. Uusi kaikki lainat -nappi toimii kuten pitääkin.

<img width="776" alt="Uusinta" src="https://github.com/KohaSuomi/Koha-23x/assets/129748294/e0271de2-30c7-40d5-89cb-57232f041892">

**Comment by pirliis** [comment]
OUTIn testillä näyttäisi toimivan, kun Lainat-sivun avaa:
- Myöhässä olevien lainojen eräpäivät punaisella, lainojen uusintatäpät valittuna.
- Tänään erääntyvien lainojen eräpäivät boldattuna, lainojen uusintatäpät valittuna.
- "Uusi valitut niteet" -painike on aktiivinen.
- Kun kaikki uusittavat lainat uusittu, lainojen uusintatäpät poistuivat ja "Uusi valitut niteet" -painike muuttui epäaktiiviseksi.

**Comment by Kati-Helle** [comment]
Helle-testissä toimii. 
Uusi valitut niteet -painike on automaattisesti aktiivinen, kun asiakkaalla on tänään erääntyviä tai aiemmin erääntyneitä lainoja. Uusintaa kaipaavilla uusittavilla niteillä on automaattisesti valinta Uusi-sarakkeessa. Uusi valitut niteet -painikkeesta ko. niteet uusiutuvat. Tämän jälkeen Uusi valitut niteet -painike on ei-aktiivinen.

**Comment by ElinaUotila** [comment]
Kirkes-testillä toimii samalla tavalla kuin yllä on kuvattu.

**Comment by atarnus** [comment]
Oletteko kokeilleet asiakkaalla, jolla on hirveä litania lainoja? Tuossa nyt haetaan tuota yhtä tauluelementtiä, mutta jos sitä ei löydy, niin laitoin pysäytyksen kuitenkin 15 sekunnin kohdalle, ettei jäisi turhaan junnailemaan jos jotain sattuu. Kestääkö asiakkaiden lainojen haku yleensä koskaan yli 15 sekuntia?

**Comment by ElinaUotila** [comment]
Kokeilin asiakkaalla, jolla oli 51 lainaa. Uusin niistä kahdeksan. Lainoja avatessa vilahti "Ladataan, voit jatkaa skannausta" -ilmoitus, samoin sen jälkeen, kun olin uusinta-nappia painanut, mutta se näkyi todella pienen hetken. Eli ehkä vähän yli 15 sekuntia meni mutta ei kuitenkaan puolta minuuttia.

**Comment by MikkoLiimatainen** [comment]
Kokeilin asiakkaalla, jolla oli yli 700 lainaa ja siinä jouduin muuttamaan i = 60, koska lataaminen kesti yli 30 sekuntia.

**Comment by atarnus** [comment]
> Kokeilin asiakkaalla, jolla oli yli 700 lainaa ja siinä jouduin muuttamaan i = 60, koska lataaminen kesti yli 30 sekuntia.

Hyvä tietää. Tuo tsekkaa nyt tosiaan puolen sekunnin välein että onko taulu valmis. Tsekkauksen ei pitäisi olla mitenkään raskas, mutta johonkin raja lienee hyvä kuitenkin laittaa. Nostetaanko 60 asti vai onko "ihan sama" jos tällaisilla muutamilla massa-asiakkailla tuo nappi ei sieltä aktivoidu itsestään vaan pitää painaa jotain ruksia tai 'valitse kaikki'? Mikä on pääkäyttäjien toive?

**Comment by MikkoLiimatainen** [comment]
Mä mietin myös tuon intervallin muuttamista 1000:sta 2000:een ja i:n pitämistä 30:ssa, jolloin saadaan periaatteessa sama vaikutus. Tosin tuo pidempi intervalli voi näkyä hieman pienillä lainamäärillä.

En muista millaisia latausaikoja sain aiemmin kun selvittelimme suurimpien lainamäärien latausongelmia. Tuo reilu 700 on kuitenkin suhteellisen lähellä huippulukemia ja taulun lataus kesti n. 33 sekuntia, joten tuossa pitäisi olla aika hyvin varaa tuolla i = 60 arvolla. Mitään suorituskykyongelmaa en tuossa havainnut.

**Comment by atarnus** [comment]
Ah, tuossa oli vielä näköjään 1000 eli sekunnin välein, itse olin jo ottanut käyttöön 500. Jos on vain pari lainaa, niin minusta se sekuntikin oli vähän liikaa, en pidentäisi ainakaan. Kyllähän sitä sivua varmasti vilkaistaan ensin ennen kuin klikataan, että pieni viive ei ole pahaksi, mutta omaan silmään erottui kyllä ikävästi.  Suurin osa lainaajista kuitenkin on varmasti tällaisia muutamien lainojen tyyppejä.

**Comment by AnneliO** [comment]
Lisättävä päivityksessä IntranetUserJS-järjestelmäasetukseen.

**Comment by lmstrand** [comment]
Yhteisön tiketti tilassa "Passed QA".

**Comment by lmstrand** [comment]
Koitetaan tuoda yhteisön korjaus.

**Comment by lmstrand** [comment]
Tämä viety testeille. Kannattaa myös testata yllä mainitun tiketin ominaisuus myös, että edelleen toimii (https://github.com/KohaSuomi/Koha-23x/issues/131).

**Comment by lmstrand** [comment]
Branchissa siis nämä commitit mukana yhteisöstä:

Applying: Bug 35600: Prevent checkouts table to flicker
Applying: Bug 35506: Move the checkouts table load delay logic out of document ready
Applying: Bug 35944: Add link to 'booked' biblio in checkouts table
Applying: Bug 36347: Avoid return claims table being loaded twice
Applying: Bug 36581: Define ymd in scope for checkouts table
Applying: Bug 36060: Simplify logic to enable/disable CheckinChecked/RenewChecked buttons
Applying: Bug 36060: (follow-up) Remember selections when refreshing the table

ja Koha-Suomi-muutos Asiakkaan lainatietoihin uusinta-sarakkeeseen oletuksena rasti myös tänään erääntyville.

**Comment by IrinaHalminen** [comment]
Kokeiltu uusia yksittäisiä ja kaikkia lainoja. Ruksit olivat oikein paikoillaan ja uusinta onnistui. Jos käy toisella välilehdellä (esim. Varaukset), tehdyt valinnat pysyvät, eli jos esim. ruksin on ottanutkin pois ja käy Varausten puolella, ruksi ei ole ilmestynyt takaisin. Mutta jos käy vas. sivuvalikon kautta vaikkapa asiaakkaan tiedoissa, ruksi on sivun päivittyessä paikoillaan. Meillä ei ole tuota Palauta valitut niteet -nappia käytössä, joten sitä en voi testata.

**Comment by piiaseme** [comment]
OUTIssa toimii sekä yksittäisen lainan (eräpäivä tänään) ja kaikkien lainojen uusinta. Ei tarvinnut klikata lainaa/lainoja vaan "Uusi valitut"-nappi oli valmiiksi aktiivinen, kun eräpäivä oli kuluva päivä tai menneisyydessä.

Sivulta poistuminen nollaa lainojen rukseihin tehdyt muutokset kuten Vaarassakin. 

Asettaa uusintaruksin, kun tietueeseen on varauksia ja tietueessa on saatavana-tilaisia niteitä. Ei aseta uusintaruksia, kun tietueeseen on varaus eikä vapaita niteitä ole. Eli toimii oikein tuossa.

OUTIn testillä ei ole asiakasta, jolla olisi valmiiksi huisin paljon lainoja, joten sitä en vielä ehtinyt testaamaan. Meillä ole Palauta valitut lainat-toimintoa käytössä, niin se jää minulla nyt testaamatta.

**Comment by lmstrand** [comment]
Muutokset branchissa ksdev/ks-0155-K23-G1207-issues-renew-return-fixes. Alkuperäinen branch ksdev/ks-0138-K23-131-autocheck-renew-for-loans-due-today poistettu.

**Comment by lmstrand** [comment]
Suljen tiketin.
