### ISSUE TITLE
Salasanan vaihtoviesti lähtee myös takaajalle

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1208]
### Mikä vikana?

PASSWORD_CHANGE -viesti lähtee myös takaajalle/takaajille (takaaja kopiokentässä) vaikka RedirectGuaranteeEmail -asetuksessa olisi valittuna, että viestejä ei lähetetä sekä huollettaville, että takaajille. 

### Mitä pitäisi tapahtua

Myös salasanan vaihtoviestien pitäisi noudattaa RedirectGuaranteeEmail -asetuksia.

**Comment by piiaseme** [comment]
> Viety testeille tämä, sinne kyllä pitäs laittaa Postfix päälle jos haluaa testailla lähetystä.

Vaihdoin OUTI-testillä taattavan PINin. Annelin antaman raportti-rimpsun perusteella viesti PINin vaihdosta lähti sekä taattavalle että takaajalle.

**Comment by emta001** [comment]
> > Viety testeille tämä, sinne kyllä pitäs laittaa Postfix päälle jos haluaa testailla lähetystä.
> 
> Vaihdoin OUTI-testillä taattavan PINin. Annelin antaman raportti-rimpsun perusteella viesti PINin vaihdosta lähti sekä taattavalle että takaajalle.

No räkä, siellä oli asetuksessa edelleen arvona "no". Patcheissa tullut filu tosiaan teki ton korjauksen vain vaski-testille. Pitää käydä muille ajamassa muutos käsin.

**Comment by emta001** [comment]
Nyt tuo on korjattu myös testeille.

**Comment by piiaseme** [comment]
Testasin uudestaan OUTI-testillä taattavan PINin vaihtoa. Raportin perusteella viesti PINin vaihdosta lähti edelleen sähköposti sekä taattavalle että takaajalle.

Testasimme vielä OUTIn tuotannossakin ja siellä vain taattavalle tuli PINin vaihtoviesti.

**Comment by emta001** [comment]
> Testasin uudestaan OUTI-testillä taattavan PINin vaihtoa. Raportin perusteella viesti PINin vaihdosta lähti edelleen sähköposti sekä taattavalle että takaajalle.
> 
> Testasimme vielä OUTIn tuotannossakin ja siellä vain taattavalle tuli PINin vaihtoviesti.

Ajoin outi-testille korefreshin, toimisko nyt? Kannassa oli ihan oikea arvo.

**Comment by piiaseme** [comment]
Nyt OUTI-testillä lähti vain taattavalle viesti eikä lähtenyt kopiona kenelleen :)

**Comment by piiaseme** [comment]
OUTIssa korjaus toimii myös tuotannossa. Kiitos :)

**Comment by sksandel** [comment]
Toimii tuotannossa. Suljen tiketin.
