### ISSUE TITLE
Käsittelyerätoiminto: Niteiden lisääminen käsittelylistalle Odotuslista-sivulta ei toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1210]
### Mikä vikana?

Jos ollaan ymmärretty oikein, odotuslistalle viedyt niteet pitäisi pystyä siirtämään käsittelyerään (käsittelylistalle) Odotuslista-sivulla toiminnolla _+Lisää viimeiset xx nidettä käsittelylistalle_, heti sen jälkeen, kun niteet oli lisätty odotuslistalle. Ohjelma antaa kuitenkin alla näkyvän tiedon, eikä niteet siirry käsittelyerään.
![image](https://github.com/KohaSuomi/Koha-23x/assets/98814860/9e10447c-7868-4e7d-bd35-19c8e04fcacd)

Niteet saa siirrettyä käsittelyerään kyllä yksitellen, kun avaa luodun käsittelyerän ja lisää siellä niteet toiminnolla _+Lisää niteitä._

Tai voi olla, että olen ymmärtänyt tai tehnyt joitain väärin. :D

### Kuinka toistaa ongelma/asia

1. Luo käsittelyerä, johon haluat niteet lähettää.
2. Lisää lähetettävät niteet ensin odotuslistalle Odotuslista-sivun toiminnolla +Lisää odotuslistalle.
3. Kun niteet on lisätty odotuslistalle, ohjelma ehdottaa: +Lisää viimeiset xx nidettä käsittelylistalle.
4. Valitse käsittelyerä, johon haluat niteet lisätä.
5. Nimeke- ja Tekijä-kenttiin tulee tieto:
_Nimeke: Ei voida muokata, koska arvo haetaan ominaisuudesta biblio.title
Tekijä: Ei voida muokata, koska arvo haetaan ominaisuudesta biblio.author_
6. Niteet eivät siirry haluttuun käsittelyerään.

**Comment by AnneliO** [comment]
Suljen tiketin.
