### ISSUE TITLE
Asiakashaun "Muu nimi (Varaustunnus)" -valinta kohdistuu kaikkiin haettaviin asiakasmääreisiin

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1211]
### Mikä vikana?

Vaskissa huomattiin, että kun hakee varaustunnuksella ja kohdistaa haun vaihtoehtoon "Other name" / "Muu nimi (Varaustunnus)", kohdistuu haku kyllä uuteen asiakasmääre HOLDID -tietoon mutta lisäksi haku kohdistuu kaikkiin muihinkin haettaviksi merkittyihin asiakasmääreisiin (eli esim. sotu-avaimeen).

Ongelma haussa on ollut siitä lähtien kun varaustunnus-kenttä uudistettiin, mutta ongelmasta raportoitiin vasta nyt kun Vaskin vanhojen 4-6 numeroisten varaustunnisteiden väliin lisättiin välilyönti numerosarjan hahmottamisen helpottamiseksi. Aiemmin 12345 tyylisellä varaustunnuksella tehty haku ei niin helposti löytänyt samaa numerosarjaa sotuavaimesta, mutta nyt 12 345 -tyyppinen haku saa huomattavasti helpommin kymmeniäkin osumia koska haku ilmeisesti etsii erikseen numerosarjoja 12 ja 345.

### Mitä pitäisi tapahtua

Asiakashaussa pitäisi olla mahdollista kohdistaa haku pelkästään varaustunnukseen eli asiakasmääreeseen HOLDID.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 20.5.2024: Testaatteko tämän uudelleen nyt versionvaihdon jälkeen?

**Comment by ajrajala** [comment]
Haun kohdistaminen tiettyyn asiakasmääreeseen toimii, suljen tiketin.
