### ISSUE TITLE
Hakutulosnäytön kautta voi varata ei varattavissa olevan tietueen niteitä

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1213]
### Mikä vikana?

Vaarassa on pelkkiä pikalainoja sisältäviä tietueita, jotka eivät ole varattavissa Finnassa/Kohassa. Jos ko. tietueen valitsee hakutulosnäytöltä ja jatkaa sivun ylälaidan Varaa-painikkeen kautta, varaus kuitenkin onnistuu. (Riippuen tehtävien varausten määrästä järjestelmä herjaa, että osa/mikään niteistä ei ole lainattavissa, mutta varauksen voi silti tallentaa.) Ei siis ole väliä, varaako yhtä tai useampaa nidettä, kunhan valinta on tehty hakutulosnäytöltä. 

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/7220a1b5-1f12-431b-8371-c1bcbccb163d)

Jos on valittuna vain ei varattavissa oleva tietue, varatessa tulee ilmoitus, ettei asiakas voi varata mitään niteistä. Varauksen voi silti tehdä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/d1719369-fbef-45c4-8393-91f683a62e33)

Nyt oli käynyt niin, että pikalainatietueessa oli roikkunut jo kuukauden verran asiakkaalle tehty varaus. Virkailija oli ilmeisesti tehnyt useampia varauksia yhtä aikaa, ja niitä tehdessä huomautus oli mennyt ohi, tai koska varauksen oli kuitenkin pystynyt tekemään, hän oli ehkä olettanut, ettei ilmoitus varmaankaan ollut ollut aiheellinen. 

Mielestäni järjestelmä ei toimi oikein, jos ei varattavissa -tilan voi kiertää.

**Comment by AnneliO** [comment]
Testailin tätä Vaarassa ja varauksen pystyy tekemään myös niin, että menee perustiedot-näytön kautta Varaukset-välilehdelle ja sitten tekee normaalisti varauksen. Käyttäjä saa kyllä ilmoituksen silloinkin, että varausta ei voi tehdä, mutta sen saa tehtyä silti. 

Vaarassa on sallittu varaussääntöjen ohitus AllowHoldPolicyOverride-järjestelmäasetuksella. Jos tuohon asetukseen laittaa "Älä salli", niin varausta ei voi tehdä. En nyt tiedä, onko teillä tuo tarkoituksella sallittu, mutta kannattanee harkita, pitäisikö asetus muuttaa.

**Comment by IrinaHalminen** [comment]
Niinpäs pääseekin, huomioin vain varausnapin puuttumisen. :) Mepäs jutellaan asiasta palaverissamme tarkemmin, eilen vaan todettiin, että pitää tiketöidä.

**Comment by IrinaHalminen** [comment]
Kyseinen ehdotettu asetus otetaan käyttöön. Aiemmin ei ollut käytössä, koska oli aiheuttanut jotakin ongelmatilanteita (muistin mukaan esim. vinkkaukseen tehtävien varausten suhteen). Nyt testailtu testillä, ettei sitä ongelmaa ainakaan pitäisi olla.
