### ISSUE TITLE
Myöhemmin voimaan tulevan varauksen erottuminen varausjonossa

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1214]
### Kehitysehdotukseni

Henkilökunnalta tullut palaute: Keskeytetty varaus näkyy hyvin punaisella tekstillä, mutta jos virkailija laittaa varauksen tulemaan voimaan myöhemmin kuin tänään, varausta on vaikea erottaa varausjonosta. Varaus ei kuitenkaan ole vielä voimassa ja sen näkyminen jonossa aiheuttaa välillä sekaannuksia, etenkin jos jonossa on yhtä myös aikaa keskeytettyjä ja voimassa olevia varauksia.

Voisiko varauksen erottumista muista parantaa jotenkin, esim. laittaa varauksen alkamispäivän punaisella, jos se on tulevaisuudessa?

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/575e3729-a19f-4abe-b137-22db8df8c50f)

**Comment by AnneliO** [comment]
Minkälaisia sekaannuksia tulevaisuudessa olevista päivistä on syntynyt? Pystytkö laittamaan muutamia esimerkkejä, niin asiaa on helpompi pohtia asiantuntijaryhmässä. :)

**Comment by IrinaHalminen** [comment]
Kyselin tästä juuri ja ilmeni, että etenkin niissä tilanteissa, kun varauksia on kuljetettavana/noudettavana, keskeytettynä ja voimassa olevina, tämä myöhemmin voimaan tuleva sekoittaa pakkaa entisestään. On hankala erottaa, monta varausta on oikeasti voimassa, ja asiakkaalle tulee helposti sanottua väärä määrä, kun silmäilemällä ei välttämättä huomaa katsoa varauksen päiväystä. Toki tähän auttaisi toisessa tiketissä esitetty ehdotus siitä, että varausten määrässä olisivat vain voimassa olevat varaukset. 

![image](https://github.com/KohaSuomi/Koha/assets/99409279/d4912af3-c288-416a-bf65-776d0654a910)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Tiketissä #1170 päätettiin tutkia, saisiko varaustaulukkoon lisättyä jonkinlaisen tiedon, kuinka monta aktiivista, keskeytettyä ja ei-aktiivista varausta tietueella on. Se riittänee tämänkin tiketin osalta. Suljetaan tiketti.
