### ISSUE TITLE
Sotu-siilon tallenna-napin tekstimuutos

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1216]
### Kehitysehdotukseni

Sotu-siilon tallenna-napin käytössä vaikuttaisi olevan epäselvyyttä, joka aiheuttaa sen, ettei asiakastietueita tallenneta hetun lisäyksen yhteydessä. Pääkäyttäjäpalaverissa 14.5. ehdotettiin muutettavaksi napin teksti muotoon "Vie sotu-siiloon".

**Comment by lmstrand** [comment]
Napin teksti muutettu testeille.

**Comment by MikkoLiimatainen** [comment]
Minusta tämä on nyt informatiivisempi, eikä ainakaan sekoitu tuon varsinaisen tallenna-napin kanssa.

**Comment by pknuuti** [comment]
Tämä on hyvä muutos, mielestäni riittävän selkeä.

**Comment by PiaKusmin** [comment]
Tämä on hyvä muutos. Tosin minusta tuo ohita-nappi on turha. Kenttä ei ole pakollinen.

**Comment by AnneliO** [comment]
> Tämä on hyvä muutos. Tosin minusta tuo ohita-nappi on turha. Kenttä ei ole pakollinen.

Ohita-nappi on päätety lisätä tiketin https://github.com/KohaSuomi/Koha/issues/1066 perusteella. :)

**Comment by PiaKusmin** [comment]
Aaa. No niinpä onkin. Mulla oli mennyt tuo ohi. :)

**Comment by Kati-Helle** [comment]
Mainio ja toimintatapaa selventävä muutos. Oikea reuna nätisti linjassa :)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/07560a84-bcec-4887-9cb5-dc26a57579c2)

**Comment by lmstrand** [comment]
Suljen tiketin.
