### ISSUE TITLE
Raporttitoive: nimekkeiden luokkien korjaus

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1218]
### Tukipyyntö

Vaarassa on vanhan (poistetun) käytännön mukaan vääriä luokkia kaunokirjoissa. Nidehaulla saisi korjattavat niteet haettua helposti kielen (041a) ja luokan mukaan, mutta hakutulokseen ei tule nimekkeen biblionumeroa, jolla pääsisi korjaamaan erämuokkauksella nimekkeen luokan oikeaksi. Luokkavirheen takia Vaaran Finnassa näkyy tiettyjen nimekkeiden kieliversiot väärin (suomenkieliset näkyvät kveeninkielisenä). Tarvittaisiin siis raportti, jossa määritellään nimekkeen kieli (041a) ja luokka (084a), hakutulokseen näkyville nimekkeen biblionumber, tekijä ja nimeke.

**Comment by AnneliO** [comment]
biblio_metadatasta haettuna luokka ja kieli. Hiiiidas.
```
SELECT b.biblionumber,b.title,b.author
FROM biblio b
LEFT JOIN biblio_metadata bm ON b.biblionumber = bm.biblionumber
WHERE ExtractValue(bm.metadata, '//datafield[@tag="084"]/subfield[@code="a"]') = <<Luokka>>
AND ExtractValue(bm.metadata, '//datafield[@tag="041"]/subfield[@code="a"]') = <<Kielikoodi>>
```

Tämä versio hakee biblio_data_elements-taulusta, mutta luokista vain sellaiset, joissa haettu luokka on ensisijaisena arvona.
```
SELECT b.biblionumber,b.title,b.author
FROM biblio b
LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON b.biblionumber = bde.biblionumber
WHERE bde.cn_class LIKE <<Luokka ja/tai % (älä jätä tyhjäksi)>>
AND bde.primary_language LIKE <<Kielikoodi tai % kaikki (älä jätä tyhjäksi)>>
```

Kokeiletko, toimisiko jompi kumpi, kuten pitää? :)

**Comment by pknuuti** [comment]
Kiitos, tuo jälkimmäinen ainakin näyttäisi toimivan riittävän hyvin. Suljen tiketin.
