### ISSUE TITLE
Melinda-tunnusten aktivointi Tätin Tietuesiirtäjässä

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha#1221]
### Tukipyyntö

Melindan käyttöönotto vaatii Melinda-tunnusten aktivoinnin Tietuesiirtäjän asetuksissa. Jokaisen kimpan pääkäyttäjä hoitaa omat tunnuksensa kuntoon.

Ohjeet löytyy Tietuesiirtäjän [wikistä.](https://github.com/KohaSuomi/koha-plugin-broadcast-biblios/wiki/Melinda%E2%80%90tunnukset-yhdist%C3%A4minen-T%C3%A4ti%E2%80%90tunnukseen.)

Jos tunnuksen kanssa tulee jotain ongelmia, niin ilmoittakaa tähän tikettiin.

**Comment by pknuuti** [comment]
Mä kyllä kaipaisin nyt vähän lisäohjeita. Tarkoittaako tämä sitä, että käyttäjän kanssa pitää lisätä tunnukset, koska salasana pitää tallentaa?

**Comment by johannaraisa** [comment]
> Mä kyllä kaipaisin nyt vähän lisäohjeita. Tarkoittaako tämä sitä, että käyttäjän kanssa pitää lisätä tunnukset, koska salasana pitää tallentaa?

Tunnukset ja salasanat ovat jo liitännäisessä, lisää vain sen borrowernumberin oikealle Melinda-tunnukselle.

**Comment by pknuuti** [comment]
Kiitos, niinpä ovat Tätissä eikä tietenkään Vaarassa, jossa yritin katsoa. Nyt on tallennettu Tätiin tunnukset.

**Comment by johannaraisa** [comment]
Kun olette saaneet linkitykset tehtyä, niin kuitatkaa. Kopioin samat tunnukset Vaari-tietueiden siirtoon.

- [ ] Kirkes
- [ ] Vaara
- [ ] Vaski
- [ ] OUTI
- [ ] Lumme
- [ ] Kyyti
- [ ] Siili
- [ ] Lappi
- [ ] Helle

**Comment by pknuuti** [comment]
Tuohon ei pääse muokkaamaan, joten pistin peukun.

**Comment by piiaseme** [comment]
OUTIssa yhdelle tunnukselle on väärä borrowernumber tallennettuna (ehkä testailuvaiheessa tallennettu?). Voinko huoleti pyyhkiä väärän pois ja tallentaa tunnukselle oikean borrowernumberin?

Voiko poistaa käyttämättömät OUTIn Melinda-tunnukset pois tietuesiirtäjästä (Poista-napilla)? Tarvitseeko tunnukset poistaa tuolloin myös Koha-Suomi Servicesin configuraatioista vai riittääkö pelkkä tietuesiirtäjäpoisto?

**Comment by johannaraisa** [comment]
> OUTIssa yhdelle tunnukselle on väärä borrowernumber tallennettuna (ehkä testailuvaiheessa tallennettu?). Voinko huoleti pyyhkiä väärän pois ja tallentaa tunnukselle oikean borrowernumberin?

Voi vaihtaa, jos on väärä.

> 
> Voiko poistaa käyttämättömät OUTIn Melinda-tunnukset pois tietuesiirtäjästä (Poista-napilla)? Tarvitseeko tunnukset poistaa tuolloin myös Koha-Suomi Servicesin configuraatioista vai riittääkö pelkkä tietuesiirtäjäpoisto?

Poisto-napilla käyttämättömät pois Tietuesiirtäjästä. Koha-Suomi Services ei ole enää käytössä, tuhoan sen kannan jossain välissä kokonaan.

**Comment by johannaraisa** [comment]
Jos tuo laatikon kuittaus ei toimi niin laittakaa vaikka tähän kommenttina tai peukku.

**Comment by piiaseme** [comment]
OUTI valmis.

**Comment by ReettaSiili** [comment]
Toiminko Siilissä oikein, jos teen näin?
Meillä ei ole tällä hetkellä Melinda-kuvailijaa, eli poistan Tietuesiirtäjästä SIILI1001-tunnuksen kokonaan.
Vai jätänkö sen odottamaan mahdollista tulevaisuutta?
Samalla poistan tämän id=86 Tätistä, hänen tunnuksensa on tänään poistettu myös Melindasta.
Valuttaja (Siili)-tunnukselle ei tarvitse tehdä mitään?

**Comment by johannaraisa** [comment]
> Toiminko Siilissä oikein, jos teen näin? Meillä ei ole tällä hetkellä Melinda-kuvailijaa, eli poistan Tietuesiirtäjästä SIILI1001-tunnuksen kokonaan. Vai jätänkö sen odottamaan mahdollista tulevaisuutta? Samalla poistan tämän id=86 Tätistä, hänen tunnuksensa on tänään poistettu myös Melindasta. Valuttaja (Siili)-tunnukselle ei tarvitse tehdä mitään?

Joo, poista vaan jos ei ole enää tarpeen.

**Comment by johannaraisa** [comment]
Ja Valuttaja-tunnus pitää olla, että valutus toimii.

**Comment by johannaraisa** [comment]
Tällaisilla tunnuksilla on jotain ongelmia, saavat Unauthorized-virhettä. Salasanan joutuu mahdollisesti laittamaan uudestaan.

VASKI4012
VASKI4025
LUMME1002
LAPPI4011
LAPPI1001

**Comment by johannaraisa** [comment]
Tämä vielä, LAPPI4006

**Comment by ReettaSiili** [comment]
Päivitystieto Siilistä: EmmiV:n Melinda-tunnukset aktivoitu käyttöön.

**Comment by johannaraisa** [comment]
Tämän voi jo sulkea.
