### ISSUE TITLE
Tätin favicon paikoilleen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1222]
### Tukipyyntö

Tätin välilehdistä on kadonnut favicon eli välilehti on ilman kuvaketta ja on hankala tunnistaa muiden avoimien välilehtien joukosta. Saisiko siihen kuvakkeen?

**Comment by AnneliO** [comment]
Tyhjensin  IntranetFavicon-järjestelmäasetuksen, jossa oli linkki sellaiseen kuvaan, jota ei enää ole olemassa. Nyt faviconina näkyy Kohan oletus eli k-kirjain.

**Comment by pknuuti** [comment]
Kiitos, sehän sujui näppärästi. Suljen tiketin.
