### ISSUE TITLE
Käyttäjän kirjastoasetus muuttuu aikakatkaisun jälkeisessä sisäänkirjautumisessa

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1224]
### Mikä vikana?

Vaskissa raportoitu tapauksista, joissa istunnon aikakatkaisun jälkeen tapahtuneen uudelleenkirjautumisen yhteydessä käyttäjän istuntokohtainen kirjastoasetus on muuttunut ilman, että käyttäjä on sitä itse muuttanut. Yleensä käyttäjä on huomannut asetuksen muuttuneen kun palautus- tai lainaustapahtumassa on väärän kirjaston tiedot. 

Testeissä emme ole pystyneet toistamaan ongelmaa.

Liittyy tikettiin https://github.com/KohaSuomi/Koha/issues/1135

**Comment by ajrajala** [comment]
Kirjataanpa vielä tikettiinkin ylös, että koska ongelma tuntuu virkailijoiden raportointien perusteella liittyvän [tiketin 1135](https://github.com/KohaSuomi/Koha/issues/1135) bugiin, pidensimme Vaskissa väliaikaisesti timeout-asetusta, koska tuo kirjaston vaihtuminen käyttäjän huomaamatta on aika ongelmallista. Tarkoitus on palata suositeltuun 30 minuuttiin kunhan tämä ongelma selviää.

**Comment by emta001** [comment]
#1135 vaikuttaisi korjaantuneen versiossa 24, joten tätäkin voisi testata nexteillä.

**Comment by sksandel** [comment]
Tätä ei ikinä saatu testatessa toistumaan, niinpä testaus on aika mahdotonta. Pitääkö vaan sulkea tiketti ja avata uudelleen jos toistuu?
