### ISSUE TITLE
LAPPI: Uudelleenpalautus-raportin päivitys

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1226]
### Tukipyyntö

Tarvitsisimme tähän raporttiin mukaan myös automaatilla palautuneet kuljetus-tilaan siirtyneet niteet, koska ne tarvitsevat uudelleen palautuksen virkailijalta, että saamme kuitin väliin. Nyt tuloksissa on vain käsittelyssä olevat eli oman kirjaston varaukset. Onko mahdollista?

SQL-raportti:
select title as 'Nimeke', author as 'Tekijä', CONCAT('<a href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',i.biblionumber,'" target="_blank">',i.barcode,'</a>') AS Nide,datelastseen as 'Nähty viimeksi', reserves.timestamp AS 'Varausta viimeksi käsitelty'
from items i
join reserves using (itemnumber)
join biblio b ON i.biblionumber=b.biblionumber
where found='P' 
and itemnumber not in (select itemnumber from branchtransfers) /* saved_sql.id: 538 */

**Comment by AnneliO** [comment]
Tämä hakee niteet, joihin kohdistuu varaus, joka on joko kuljetettavana tai käsiteltävänä. Se ei kyllä ole ihan sitä mitä haitte, mutta toiminee paremmin kuin teidän nykyinen raportti. Mietin vielä tuota varsinaista tarvetta lisää, mutta pistän tämän tänne varalta talteen.
```
select title as 'Nimeke', author as 'Tekijä', CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=',i.biblionumber,'" target="_blank">',i.barcode,'') AS Nide,datelastseen as 'Nähty viimeksi', reserves.timestamp AS 'Varausta viimeksi käsitelty', reserves.found as 'Varauksen tila'
from items i
join reserves using (itemnumber)
join biblio b ON i.biblionumber=b.biblionumber
where found in ('P', 'T')
and itemnumber not in (select itemnumber from branchtransfers where datearrived is null and datecancelled is null)
```

**Comment by AnneliO** [comment]
Tämä raportti hakee kuljetustilassa olevat niteet, joihin kohdistuu varaus, joka on joko P- tai T-tilassa (eka ei ehkä tarpeen). Toimisiko tämä?

```
SELECT CONCAT('<a href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',b.biblionumber,'">',b.title,'</a>') AS Nimeke, b.author AS 'Tekijä', i.barcode AS Viivakoodi, i.cn_sort AS 'Luokka ja pääsana', tobranch as 'Kohdekirjasto'
FROM branchtransfers bt
JOIN items i USING (itemnumber)
JOIN biblio b USING (biblionumber)
LEFT JOIN reserves r on i.itemnumber=r.itemnumber
WHERE bt.frombranch=<<Valitse kirjasto|branches>>
AND date(bt.datesent)=<<Mennyt kuljetettavaksi - valitse päivämäärä|date>>
AND datearrived is null and datecancelled is null
AND bt.itemnumber IN (SELECT itemnumber FROM reserves WHERE found in ('P', 'T'))
ORDER BY 4
```

Jäin kyllä miettimään, että eikö teillä automaatti lajittele kuljetukseen meneviä niteitä uudelleenkäsiteltävien laariin?

**Comment by PiaKusmin** [comment]
Kiitos Anneli. Jostain syystä en edelleenkään saa noilla raporteilla tarvittavia niteitä samaan raporttiin...

Ensimmäisessä (joka tuntui paremmalta/helpommalta) raportissa näkyy automaatilla palautettu aineisto, johon kohdistuu oman kirjaston varaus. Testinide https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1152952

Toisessa näkyy automaatilla palautettu aineisto, johon varaus ja joka tulee kuljettaa toiseen kirjastoon. Testinide https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=498077

Ja mie tarttisin nämä niteet samalle raportille. :)

Ja meillä ei ole lajittelevia palautusautomaatteja vaan lajittelun hoitavat asiakkaat ja sehän taas ei aina toimi oikein. :D

**Comment by AnneliO** [comment]
Hmm.. mie taisin miettiä tätä vähän turhan monimutkaisesti. Toimisiko tämä:

```
select title as 'Nimeke', author as 'Tekijä', CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=',i.biblionumber,'" target="_blank">',i.barcode,'') AS Nide,datelastseen as 'Nähty viimeksi', reserves.timestamp AS 'Varausta viimeksi käsitelty', reserves.branchcode as 'Varauksen noutokirjasto', reserves.found as 'Varauksen tila'
from items i
join reserves using (itemnumber)
join biblio b ON i.biblionumber=b.biblionumber
where found in ('P', 'T')
AND i.holdingbranch like <<Nykyinen kirjastoni|branches:all>>
```

Se hakee varaukset, jotka ovat joko käsiteltävänä tai kuljetettavana. Lisäksi pitää valita sijaintikirjasto, jotta listalle ei tule kaikkien mahdollisien kirjastojen uudelleenpalautettavia niteitä.

**Comment by AnneliO** [comment]
Missään ei oikein ole tietoa, että virkailija on sen jo "käsitellyt".  Nähty viimeksi -sarakkeesta voi vähän tulkita kellonajan mukaan, voisiko niteelle olla tarvetta palauttaa uudelleen. Periaatteessa siihen voi jonkinlaisen aikarajauksen tehdä sen mukaan, mutta se on sitten sellainen kiinteä raja eli esim. tyyliin 24 h tai vain tänään nähdyt.

**Comment by PiaKusmin** [comment]
Ok. Se aikaraja on vähän huono, koska esim. Tornion kokoisessa kirjastossa ensimmäisen tunnin aikana tulee eniten palautuksia/varauksia kuljetettavaksi ja niitä on hiljaisempanakin päivänä heti toista sataa. 

Vastaanotettavat kuljetukset listasta näkee "ohi menneitä" palautuksia ja varauksia, mutta nekin huomataan vasta 7 vuorokauden jälkeen... Mutta mepä selvitellään tätä vielä täällä omalla porukalla ja koitetaan yhdistellä tietoja. :) Kiitos Anneli avusta. Suljen tiketin.

**Comment by AnneliO** [comment]
Kerkesin tuossa jo vähän miettiä aikarajausta, niin pistän tämän säätöni vielä tänne talteen, jos vaikka joskus tarvii:

```
select title as 'Nimeke', author as 'Tekijä', CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=',i.biblionumber,'" target="_blank">',i.barcode,'') AS Nide,datelastseen as 'Nähty viimeksi', reserves.timestamp AS 'Varausta viimeksi käsitelty', reserves.branchcode as 'Varauksen noutokirjasto', reserves.found as 'Varauksen tila'
from items i
join reserves using (itemnumber)
join biblio b ON i.biblionumber=b.biblionumber
where found in ('P', 'T')
AND i.holdingbranch like <<Palautuskirjasto|branches:all>>
AND i.datelastseen > NOW() - INTERVAL '7' HOUR
```

Tuohon tulee mukaan vain niteet, jotka on nähty viimeksi (items.datelastseen) aiemmin kuin 7 tuntia sitten.
