### ISSUE TITLE
Helle: yhden asiakkaan lainatiedot eivät lataudu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1228]
### Mikä vikana?

Hellessä on tullut vastaan asiakastieto, jonka lainat eivät lataudu. Asiakkaalla on juuri nyt 9 lainaa. (Varaukset latautuvat.)
Lainat eivät myöskään näy asiakkaalle Helle-Finnassa. 

Asiakasnumero
76372

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/6bd9a333-e156-4a4c-8b49-da9d3d78b4c6)

**Comment by emta001** [comment]
Lokiin tulee siis seuraava virhe:
>Can't call method "notforloan" on an undefined value at /home/koha/Koha/C4/[Reserves.pm](http://reserves.pm/) line 1382.

joka viittaa siihen, että asiakkaan lainoissa on nide, jonka nidetyypissä on jotain vikaa. Mutta ainakaan pikaisella tutkimisella tällaistä nidetyyppiä ei ole vielä löytynyt.

Hellestä löytyy kuitenkin kyllä yksi nide, jolla on olematon nidetyyppi. Biblionumber 1634031, viivakoodia ei ole, itype on CD. Tämän voisi käydä korjaamassa ja katsoa mitä sen jälkeen tapahtuu.

**Comment by emta001** [comment]
Samaa virhettä on esiintynyt myös Vaskissa, #879.

**Comment by emta001** [comment]
Ongelmana oli siis se, että asiakkaalla on lainassa nide, jonka tietueeseen liittyi tuo virheellisen nidetyypin sisältävä nide. Sen korjaaminen sai asiakkaan lainat taas näkymään.

**Comment by Kati-Helle** [comment]
Kiitos Emmi ongelman ratkaisemisesta :)
