### ISSUE TITLE
Kuljetus-tilaisille niteille määritelty on_shelf-arvo Kellutin-nideraportilla

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1230]
### Tukipyyntö

Tiketissä #928 määriteltiin mm. raportti, jolla Kellutin hakee nidetiedot Kohasta (raportti [Vaskin tuotannossa](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2279&phase=Run%20this%20report), raportti [vaski-testillä](https://vaski-test.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2193&phase=Run%20this%20report)). Raportille määriteltiin on_shelf-sarake joka huomioi mm. sen ettei kuljetustilaisia esitetä raportilla hyllyssä olevina. Nyt kun tietoja on Kelluttimessa päästy tarkastelemaan, huomattiin että joissain tapauksissa kuljetettavana oleva nide saa raportilla ei-toivotusti on_shelf-arvoksi "yes" vaikka sen tulisi olla "no". Esimerkki tällaisesta tapauksesta alla eli nide 1368190 tulee tämän näköisenä nideraportille:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

itemnumber | biblionumber | homebranch | holdingbranch | permanent_location | ccode | cn_sort | itemnotes | dateaccessioned | issues | datelastborrowed | datelastseen | timestamp | on_shelf | onloan
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1368190 | 2992048 | MYPK | TUHI | AIK |   | 59.4 RAN |   | 24.6.2015 | 36 | 5.2.2024 | 18.5.2024 | 18.5.2024 20:57 | Yes |  

</body>

</html>

...ja branchtransfers-taulussa nide näyttää tältä:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

branchtransfer_id | itemnumber | daterequested | datesent | frombranch | datearrived | datecancelled | tobranch | comments | reason | cancellation_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
4638074 | 1368190 | 5.2.2024 14:51 | 5.2.2024 14:51 | NAME | 5.2.2024  14:51:43 |   | NAME | Forced branchtransfer | ReturnToHome |  
5201549 | 1368190 | 18.5.2024 20:57 | 18.5.2024 20:57 | TUHI |   |   | MYPK |   | ReturnToHome |  

</body>

</html>

Verrokkina vielä alla toinen kuljetettavana oleva nide 60142, jolla raportilla näkyy on_shelf-arvona halutulla tavalla "no":

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

itemnumber | biblionumber | homebranch | holdingbranch | permanent_location | ccode | cn_sort | itemnotes | dateaccessioned | issues | datelastborrowed | datelastseen | timestamp | on_shelf | onloan
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
60142 | 112579 | MAPK | TUPK | AIK |   | 15 VIR |   | 1.6.1990 | 9 | 4.3.2024 | 19.5.2024 | 19.5.2024 11:14 | No |  

</body>

</html>

Nide 60142 branchtransfers-taulussa:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ajrajala/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

branchtransfer_id | itemnumber | daterequested | datesent | frombranch | datearrived | datecancelled | tobranch | comments | reason | cancellation_reason
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
5201751 | 60142 | 19.5.2024 11:14 | 19.5.2024 11:14 | TUPK |   |   | MAPK |   | ReturnToHome |  

</body>

</html>

Mitenköhän raportille pitäisi muuttaa branchtransfers-tauluun liittyvää rajausta, jotta kuljetettavana oleva nide saisi raportilla aina on_shelf-arvoksi "no"?

**Comment by atarnus** [comment]
Keksin nopsaan korjauksen siihen, mutta sitten saikin vielä äheltää että sain toistettua ongelman ja testattua että korjaus toimii :)

Nappasin teidän testiltä tuon rapsan ja muokkasin sitä:

```
SELECT i.itemnumber, i.biblionumber, i.homebranch, i.holdingbranch, i.permanent_location, i.ccode,
       i.cn_sort, i.itemnotes, i.dateaccessioned, i.issues,
       i.datelastborrowed, DATE(i.datelastseen) AS 'datelastseen', i.timestamp,
       CASE WHEN i.onloan IS NOT NULL OR i.itemlost != 0 OR i.notforloan != 0 OR r.found IS NOT NULL
       OR i.itemnumber IN (select itemnumber from branchtransfers bt where bt.itemnumber IS NOT NULL AND bt.datearrived IS NULL AND bt.datecancelled IS NULL)
       THEN 'No'
       ELSE 'Yes'
       END AS on_shelf,
       i.onloan
  FROM items AS i
       LEFT JOIN biblioitems AS bi
       ON i.biblionumber = bi.biblionumber
       LEFT JOIN reserves AS r
       ON i.itemnumber = r.itemnumber
 WHERE date(i.timestamp) BETWEEN <<Start Date|date>> AND <<End Date|date>>
   AND i.holdingbranch LIKE <<Branchcode>>
   AND i.permanent_location NOT IN ('TYO', 'VAR', 'VRL', 'VAS')
   AND IFNULL(i.ccode, '') NOT IN ('AVO', 'KKO')
   AND bi.itemtype IN ('ATLAS', 'BLURAY', 'CD', 'DVD', 'KARTTA', 'KIRJA', 'KORTTI', 'LAUTAPELI', 'MONIVIES', 'NUOTTI', 'PUHECD', 'VIDEOPELI')
 GROUP BY i.itemnumber
```

Tällä pitäisi toimia. Ongelma oli sellaisten niteiden kohdalla, jolla oli branstransfersissa useampi rivi, eikä niistä ollut varausta. Omassa testikannassa kaikilla branchtrasfersissa useampaan kertaan esiintyvillä niteillä oli myös olemassaoleva varaus, niin siksi tämä ei jäänyt kiinni. Nyt tekaisin pari feikkiä siirtoa ja näyttää siltä, että vanha rapsa sano että on hyllyssä ja uusi ei. Testatkaa.

**Comment by ajrajala** [comment]
Jeps, testasin korjattua raporttia ja nyt on_shelf-arvo tulee oikein myös niissä tapauksissa, joissa branchtransfers-taulussa on useampi rivi. Kiitos supernopeasta avusta!
