### ISSUE TITLE
Hankinnan tilien hakuruutu ei enää toimi

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1231]
### Mikä vikana?

Hankinnan vastaanotossa oleva tilien hakuruutu ei enää toimi. Edellisessä versiossa toiminut.

![Hakuruutu](https://github.com/KohaSuomi/Koha/assets/99241432/cf173906-dcc6-4c2b-ba81-1f97820c54d5)

Samanlainen hakuruutu toimii kuitenkin uuden aineiston kohdalla tilausta tehdessä.

![Tilin hakuruutu](https://github.com/KohaSuomi/Koha/assets/99241432/bec37504-576f-4529-b2ab-1d8e58ad86e5)

**Comment by AnneliO** [comment]
Tämä sama virhe on myös yhteisön sandboxissa versiossa 24.05. Teetkö tästä @PiaKusmin tiketin myös yhteisön Bugzillaan? :)

**Comment by lmstrand** [comment]
Korjaus branchissa ksdev/ks-0151-K23-G1231-fix-select2-search-in-orderreceive. Viety testeille testattavaksi.

**Comment by PiaKusmin** [comment]
Lapissa haku ruutu toimii oikein.

**Comment by pknuuti** [comment]
Vaaran testillä toimii hakuruutu.

**Comment by piiaseme** [comment]
OUTIssa testillä toimii myös.

**Comment by PiaKusmin** [comment]
Tehty Bugzillaan tiketti, jos @lmstrand kommentoi korjauksen sinnekin.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36973

**Comment by emta001** [comment]
> Tehty Bugzillaan tiketti, jos @lmstrand kommentoi korjauksen sinnekin. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36973

Katrin Fischer olikin kommentoinut, että kyseessä on tuplatiketti. Korjaus pitää laittaa vanhempaan tikettiin [34718](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34718).

**Comment by PiaKusmin** [comment]
Korjaus tuotu tuotantoon ja toimii. Suljen tiketin.
