### ISSUE TITLE
Asiakastietojen suojattu-valinta näkyviin vain pääkäyttäjille

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1232]
### Kehitysehdotukseni

Pääkäyttäjäpalaverissa 21.5.2024 keskusteltiin, että suojattu-valinta haluttaisiin piiloon. Vaskissa valinta on piilotettu muilta kuin pääkäyttäjiltä tällaisella rimpsulla.

```
///ALKU///
// Asiakastietojen suojattu-valinnan piilotus
$(document).ready(function() {
	if (window.location.href.indexOf('/cgi-bin/koha/members/memberentry.pl') > -1){
		var superlib = $('span#logged-in-info-full').children().hasClass('is_superlibrarian');
		if(!superlib){
			$('fieldset#memberentry_library_management ol li.radio').hide();
		}
	}
});
///LOPPU///
``` 

Potentiaalisena ongelmana tässä toteutuksessa on se, jos Kirjastonhallinta-osiossa on useampia "radiopainikkeita". Tämä ei myöskään piilota suojattu-valinnan tilaa asiakkaan tiedot sivun kirjastotiedot osiosta.

**Comment by pknuuti** [comment]
Onko tämä IntranetUserJS-piilotus? Eli tuotannossa vaatii kehittäjän toimenpiteen?

**Comment by Kati-Helle** [comment]
Kiitos Mikko! Helle-testissä asiakastiedon muokkauksen Tiedonhallinta-osion Suojattu-kohta piiloutuu rimpsullasi. 

Tuleekohan tämän IntranetUserJS-rimpsun toteutus tuotantoon kaikille ominaisuuden käyttöön ottaville samaan aikaan?

**Comment by piiaseme** [comment]
OUTIssa testille myös laitettu, hyvin toimii. Kiitos! OUTIllekin saa rimpsun laittaa tuotantoon.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Muutetaan liitännäiseksi ja asennetaan kaikille. Pääkäyttäjät voivat sitten aktivoida sen tarvittaessa omassa kimpassa.

**Comment by lmstrand** [comment]
Jotta js-rimpsu koskee vain suojattu-valintaa, muutin sen muotoon:
```
///ALKU///
// Asiakastietojen suojattu-valinnan piilotus
$(document).ready(function() {
	if (window.location.href.indexOf('/cgi-bin/koha/members/memberentry.pl') > -1){
		var superlib = $('span#logged-in-info-full').children().hasClass('is_superlibrarian');
		if(!superlib){
             var label = $('label[for="protected"]');
          label.parent().children().hide();
		}
	}
});
///LOPPU///
```

Viedään tämä pluginina testeille.

**Comment by lmstrand** [comment]
Plugin IntranetUserJS: Hide patron protected radio button asennettu testeille.

**Comment by pknuuti** [comment]
Testattu Vaaran testillä, toimii. Suojaus näkyy vain pääkäyttäjälle.

**Comment by Kati-Helle** [comment]
Helle-testissä asiakastiedon muokkauksen Suojattu-kohta on piilossa, kun Kohaan on kirjauduttu ei-pääkäyttäjä tunnuksella
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/78150cb1-1bf3-4e49-854e-f15db7841e0b)

Pääkäyttäjä-tunnuksella Suojattu-kohta edelleen näkyy ja toimii.

**Comment by lmstrand** [comment]
Kiitos testeistä.

**Comment by PiaKusmin** [comment]
Toimii myös tuotannossa.

**Comment by piiaseme** [comment]
Samoin toimii myös OUTIn tuotannossa.

**Comment by lmstrand** [comment]
Suljen tiketin.
