### ISSUE TITLE
Vaara: Varausjonon piilotus

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1235]
### Tukipyyntö

Tarvitsisimme piilotuksen Varausjono-toiminnolle sekä sivulla: https://vaara.koha-suomi.fi/cgi-bin/koha/circ/circulation-home.pl että Lainaus ja palautus -sivuvalikossa, joka Vaarassa muutoin halutaan pitää esillä. 
![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/dd6e074a-de19-4c2e-b422-51c540f57168)

**Comment by atarnus** [comment]
Intranet.css voi lisätä:

```
/* Piilota Varausjono-linkki Lainaus ja palautus -sivulla */
a.circ-button[href="/cgi-bin/koha/circ/view_holdsqueue.pl"] { display: none;}

/* Piilota Varausjono-linkki Lainaus ja palautus -sivupalkista */
div#navmenulist a[href="/cgi-bin/koha/circ/view_holdsqueue.pl"] {display: none;}
```

**Comment by IrinaHalminen** [comment]
Kiitos, siirsin testille.

**Comment by pknuuti** [comment]
Tuotannossa. Suljen tiketin.

**Comment by AnneliO** [comment]
Rimpsu lisätty myös IntranetUserCSS-kirjastoon Lainaus ja palautus -sivun osioon.
