### ISSUE TITLE
Hyllyvarausraportille ohjeistus lihavointien ja punerruksien merkityksistä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1236]
### Tukipyyntö

Hyllyvarausraportille pitää lisätä ohjeistus, mitä kirjastolyhenteiden lihavointi ja punerrus merkitsee.

Lihavoinnin yhteyteen käyttöön termi _poimintaryhmä_ /  _pickup group_ tai _pickup location group_.

**Comment by AnneliO** [comment]
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/4a89de61-f84d-44f2-99fc-c8a3fdc818f1)

Nyt kun tekstejä katsoo paikoillansa, niin ehkä ne kaipaa vielä vähän tarkennusta. Kävisikö näin:

Orange color means that the item can be found in the hold pickup library.
Bold text means that the item can be found in a library that belongs to the same hold pickup location group as the hold's pickup library.

**Comment by lmstrand** [comment]
Testeillä.

**Comment by lmstrand** [comment]
Vaatii vielä käännöstiedostojen päivityksen ja käännökset.

**Comment by Kati-Helle** [comment]
Tuleeko tämä käyttöön kaikille vai vain silloin, kun Varausryhmät ovat käytössä? Jos tulee, onko piilotettavissa?

Hellessä ei ainakaan vielä ole päätetty ottaa Varausryhmiä käyttöön.

**Comment by lmstrand** [comment]
> Tuleeko tämä käyttöön kaikille vai vain silloin, kun Varausryhmät ovat käytössä? Jos tulee, onko piilotettavissa?
> 
> Hellessä ei ainakaan vielä ole päätetty ottaa Varausryhmiä käyttöön.

Hyvä idea, tämän saa varmaankin piilotettua, jos varausryhmiä ei ole määritetty. Lisätään tämä hyllyvarausraporttiin.

**Comment by lmstrand** [comment]
Piilotusominaisuus, jos varausryhmiä ei ole määritetty, viety testeille.

**Comment by Kati-Helle** [comment]
Helle-testissä ei ole käytössä varausryhmiä. Hellelle tarpeetonta varausryhmään liittyvää ohjeistusta ei näy
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5f6a4f41-e671-4bff-b741-26c15f4d4b8b)

**Comment by pknuuti** [comment]
Vaarassakin testillä näyttää oikein hyvältä. Kiitos!

**Comment by Kati-Helle** [comment]
Ruotsinnokset Porvoosta Helenalta:

Orange färg betyder att exemplaret finns i det bibliotek där reservationen hämtas.
Fet stil betyder att exemplaret finns i ett bibliotek som hör till samma plockgrupp som hämtbiblioteket.

**Comment by Kati-Helle** [comment]
@AnneliO Helenalta huomasi vielä jälkeenpäin, että fetstil yhteen kirjoitettuna on enemmän käytetty kuin erikseen.
Välilyönti siis pois sanojen fet JA stil välistä tyyliin:

Fetstil betyder att exemplaret finns i ett bibliotek som hör till samma plockgrupp som hämtbiblioteket.

**Comment by AnneliO** [comment]
> @AnneliO Helena huomasi vielä jälkeenpäin, että fetstil yhteen kirjoitettuna on enemmän käytetty kuin erikseen. Välilyönti siis pois sanojen fet JA stil välistä tyyliin:
> 
> Fetstil betyder att exemplaret finns i ett bibliotek som hör till samma plockgrupp som hämtbiblioteket.

Jeps, se tulee silleen, koska Fetstil oli erillisenä sanana jo valmiiksi siis käännetty tuohon muotoon. :)

**Comment by piiaseme** [comment]
Vilkaisin OUTIn tuotannossa miltä ruotsinnokset näyttävät ja huomasin, että otsake on enkuksi. Tämä on ehkä jo huomattu ja tiedossa, mutta laitan varuiksi kuitenkin hoksautuksen tänne :) 
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/c8644f78-3d69-47e9-a46f-68b95e07cd60)

**Comment by AnneliO** [comment]
> Vilkaisin OUTIn tuotannossa miltä ruotsinnokset näyttävät ja huomasin, että otsake on enkuksi. Tämä on ehkä jo huomattu ja tiedossa, mutta laitan varuiksi kuitenkin hoksautuksen tänne :) ![kuva](https://private-user-images.githubusercontent.com/98805552/338479279-c8644f78-3d69-47e9-a46f-68b95e07cd60.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwOTE2MTYsIm5iZiI6MTcxODA5MTMxNiwicGF0aCI6Ii85ODgwNTU1Mi8zMzg0NzkyNzktYzg2NDRmNzgtM2Q2OS00N2U5LWE0NmYtNjhiOTVlMDdjZDYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDA3MzUxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxZGQzYjc0YjM5NGE1NTRiNzZmNWJmY2UxZDg5MjRlN2JiNWVkYzFiYzdmNjljMmY2ZjZmODQ3ZTczN2JlYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MApCTy9e0SE4SJtwbGTxKPi0ZHiM7WHzdv8R_Zfl0dU)

Ruotsinkieliset käännökset ovat puutteelliset monelta osin, koska minä en osaa tehdä niitä. Jos tulee vastaan puuttuvia käännöksiä, niin niistä voisi tehdä jokaisesta erikseen tiketin ja ehdotuksen käännökseksi. :)

**Comment by AnneliO** [comment]
Tekstit ja niiden käännökset näkyvät oikein tuotannossa, joten suljen tiketin.
