### ISSUE TITLE
Fasetit: Nimi aakkostuu väärin, jos alussa erikoinen merkki

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1238]
### Mikä vikana?

Šostakovitš, Dmitri aakkostuu väärin fasetissa viimeiseksi. Ilmeisesti ongelmana on tuo ensimmäinen kirjain, jossa on hattu päällä. Saisiko sen aakkostumaan oikein.
![2023kuvat 422](https://github.com/KohaSuomi/Koha/assets/73887264/61750a8f-fb4c-479c-ac3f-edd919275760)

**Comment by lmstrand** [comment]
Korjaus branchissa ksdev/ks-0152-K23-G1238-normalize-and-uc-facet-sorting. Muutin samalla fasettien aakostuksen niin, etteivät isot ja pienet alkukirjaimet aakostu erikseen, vaan että ovat samanarvoisia (ongelma näkyi asiasanoissa, jossa isolla kirjaimella alkavat sanat aakkostuivat ensiksi).

Viety testeille testattavaksi.

Yheisössä on ollut mielenkiintoa normalisoituun aakkostukseen Zebra-ajoilta ja jolloin tarjottu patch käytti Text::Unaccent-moduulia erikoismerkkien riisumiseen lajittelussa. Teen tiketin yhteisöön Elasticsearchin fasetoinnista samoilla huomautuksilla, mutta lisäksi tuota isojen ja pikkukirjainten samanarvoistamista voisi tarjota.

**Comment by lmstrand** [comment]
Muutos vaikuttaa siis kaikkien fasettien aakkostumiseen.

**Comment by lmstrand** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36947

**Comment by lmstrand** [comment]
Ps. FacetOrder-järjestelmäasetus oltava asetettuna "aakkosjärjestyksessä".

**Comment by pknuuti** [comment]
Vaaran testillä testattua: Paikat-fasetissa Örebro sijoittuu Oslon ja Palermon väliin eli ö ei aakkostu oikein. Sarjoissa Väinö Mujunen sijoittuu Varjo-sarjan ja Vera Stanhope -sarjan väliin. Aineistotyypeissä Äänilevy on ensimmäisenä. 
Vaaran testillä olevan aineiston vähäisyys estää isomman testailun, mutta eiköhän tuo ääkkösongelma ainakin näy noista. Eteeni ei tullut yhtään Sostakovitsia musiikkihaulla, joten erikoismerkkejä en saanut testikannassa esille.

**Comment by Kati-Helle** [comment]
Helle-testissä aineistotyyppi Äänilevy aakkostuu oikein
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b79bcf87-0341-40c0-bf58-99e648cd05bf)

**Comment by pknuuti** [comment]
Ai, minusta äänilevy ei ole ennen Blu-rayta aakkosissa :)

**Comment by Kati-Helle** [comment]
Joo, totta :) Ajatusharhani.

**Comment by AnneliO** [comment]
Aakkostus on nyt tosiaan aika erikoinen. Ä menee a:n jälkeen.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/886c83ae-0935-41ef-9b13-5d4cfc00a40a)

Jos tuo aakkostuisi ilman diakriittejä, niin järjestys pitäisi olla äidit, aikatasot, animaatiot. Jos taas menisi suomalaisen aakkostuksen mukaan, niin äidit olisi paljon alempana fasettilistaa.

Lisäsin outi-testille pari Sostakovitsin teosta ja kun hain nuotti-aineistotyypillä, niin se aakkostui näin:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/0c644769-b807-4b0f-abb3-4d29129c6f21)

Minun aakkostusjärjen mukaan Sostakovits pitäisi olla Sinkkosen ja Spindlerin välissä. Samalla tavalla se tosin aakkostuu myös silloin, jos hakutulokset järjestää nousevasti tekijän mukaan.

**Comment by AnneliO** [comment]
On tehty, Lari toi bugista https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36947 korjauksen äsken. Ei näköjään muistettu heti päivittää tänne tietoa. :)

Se korjaus tosiaan tekee nyt niin, että diakriittiset (myös åäö) aakkostuvat perusmuotonsa mukaisesti aakkosiin, mikä ainakin minusta on yleisesti ottaen loogista. Noiden åäö:n osalta pitää vielä miettiä, miten ne saisi toimimaan suomalaisittain. Suurin osa maailmasta tuskin haluaa niiden aakkostuvan kuten me.

**Comment by AnneliO** [comment]
> Tarkka haku -toiminnon Aineistotyyppi-välilehdellä vastaavaa ![kuva](https://private-user-images.githubusercontent.com/99952449/333492258-32ac2b58-fc91-4851-83f4-ef29fbd0a095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1MzU2ODgsIm5iZiI6MTcxNjUzNTM4OCwicGF0aCI6Ii85OTk1MjQ0OS8zMzM0OTIyNTgtMzJhYzJiNTgtZmM5MS00ODUxLTgzZjQtZWYyOWZiZDBhMDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDA3MjMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGU4ZGFmNTljYWE3MDNjZTVjNjYyYzY0NDYzMTUwMTUzYjAwNzQ2MDA2YjRlYmQ3MjEzMjBiMmEwMGM4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cBgIO3m4DzEHNaH0HM561NRaeYXhsElYxDRXVsfhtP8)

Tämä muutos koskee vain fasetteja. :)

**Comment by AnneliO** [comment]
Sain samanlaiset tulokset kuin Piia eli minusta fasettien järjestäytyminen toimii nyt korjauksen mukaisesti.

**Comment by Kati-Helle** [comment]
Helle-testissä myös
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/76615cba-45e7-474a-ad09-956cb5a8e20d)

**Comment by lmstrand** [comment]
Testeille viety muutos, jossa käytetään Unicode::Collate::Locale -moduulia aakkostamiseen suomenkielen mukaisesti. Nyt ääkkösten pitäisi myös aakkostua, kuten kuuluu.

**Comment by Kati-Helle** [comment]
Helle-testissä esim. Äänilevy on nyt suomen kielen mukaisesti aakkostettuna 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2cab53d4-969c-45c0-8629-2bea3b83a5c8)

**Comment by AnneliO** [comment]
> Tutkailin outi-testillä. Muut fasetit tuntuis aakkostuvan oikein, mutta Kokoelmat ja kielet eivät.
> 
> Kokoelmat: ![kuva](https://private-user-images.githubusercontent.com/33121325/334359333-10696d98-747e-4892-b619-b747c6dbdcd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4OTA4MTAsIm5iZiI6MTcxNjg5MDUxMCwicGF0aCI6Ii8zMzEyMTMyNS8zMzQzNTkzMzMtMTA2OTZkOTgtNzQ3ZS00ODkyLWI2MTktYjc0N2M2ZGJkY2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDEwMDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0MWRkMGRkODU2Mjg2YjQ1NjU2OWYzYWU1OTVlMGViMDY5NTE5ZjNkYzRiMDc2MTRkMGRhNTA5YjY0OWM3MDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4uqWM7a8TfTGXxdyPpm1VWnYBw23ews-Tb2LwGX-aYo)
> 
> Kokoelmat ovat auktorisoituja arvoja, joten vaikuttaisiko se?

Toisaalta, myös hyllypaikat ovat auktorisoituja arvoja ja ne menee nätisti oikeisiin aakkosiin.
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/a211170a-4d6d-4240-9fe2-8e07bc284f62)

**Comment by pknuuti** [comment]
Sama havainto Vaaran testillä, muuten aakkostus näyttäisi toimivan, mutta ei Kokoelmat ja kielet -faseteissa.

**Comment by Kati-Helle** [comment]
Aivan kuin kielikoodit järjestäytyisivät kielikoodin mukaan.

**Comment by lmstrand** [comment]
Kielet taitavat mennä englanninkielisen nimen mukaan.

**Comment by lmstrand** [comment]
Kokoelmien aakkostukseen kuvauksen mukaan viety korjaus testeille.

**Comment by piiaseme** [comment]
OUTIn testillä faseteissa näyttäisi nyt aakkostus toimivan.

**Comment by Kati-Helle** [comment]
Helle-testissä vaikuttaa toimivalta.

Hakutuloksen Tekijät-fasetin ääkkösiä sisältävä Kärkkäinen on oikealla paikalla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/e16b4efa-5724-4de9-baef-a5cb96c34fe5)

Samoin Kokoelmat-fasetin ääkkösellinen Käsikirjasto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/479b4cc9-0583-42ec-8a3c-600c5754dd2c)

**Comment by lmstrand** [comment]
Suljen tiketin.
