### ISSUE TITLE
Takaajan tiedoissa Taattavan maksut -välilehden maksunäkymään muutosehdotus

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1239]
### Kehitysehdotukseni

Takaajan tiedoissa Taattavan maksut -välilehdellä näkyvät jokaisen taattavan maksut erikseen. Maksusummat sisältävät sekä julkis- että yksityisoikeudelliset maksut. Välilehden Yhteensä-rivin summassa näkyy kuitenkin vain taattavien julkisoikeudelliset maksut yhteensä eli vain ne maksut, jotka vaikuttavat lainauskieltoon. 

Yhteensä-rivillä tulisi olla maksujen yhteissumma, joka sisältää taattavien sekä julkis- että yksityisoikeudelliset maksut.

![image](https://github.com/KohaSuomi/Koha/assets/98814860/1c9fe564-c2d6-4701-8bd9-450ff03c4a67)

**Comment by pirliis** [comment]
#1173

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.5.2024: Tehdään korjaus niin, että Yhteensä-sarake näyttää kokonaissumman kaikista maksuista, ei vain lainauskieltoon vaikuttavista maksuista ja tarjotaan sitä yhteisöön.

**Comment by lmstrand** [comment]
Tästä viety korjaus testeille tiketin #1173 korjauksen yhteydessä.

**Comment by sksandel** [comment]
Vaski-testillä testattu. Taattavien maksut-välilehti on halutun mukainen. 

Huoltajan tiedoissa oleva selostus on hiukan epälooginen. Ensimmäinen lause voisi olla esim "Asiakkaan taattavilla on lainakieltoon vaikuttavia maksuja yhteensä..." Tai sitten tässäkin voisi näyttää vain koko summan?

![Image](https://github.com/KohaSuomi/Koha/assets/99008412/949cdea3-d72e-4d2f-8ef6-e5d31b99b8ef)


Tämä on selkeä:

![Image](https://github.com/KohaSuomi/Koha/assets/99008412/3e9170ef-52f8-40a7-8226-7ea8b5eaca8a)

**Comment by pirliis** [comment]
> Vaski-testillä testattu. Taattavien maksut-välilehti on halutun mukainen.
> 
> Huoltajan tiedoissa oleva selostus on hiukan epälooginen. Ensimmäinen lause voisi olla esim "Asiakkaan taattavilla on lainakieltoon vaikuttavia maksuja yhteensä..." Tai sitten tässäkin voisi näyttää vain koko summan?
> 
> ![Image](https://private-user-images.githubusercontent.com/99008412/343066128-949cdea3-d72e-4d2f-8ef6-e5d31b99b8ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTA3OTksIm5iZiI6MTcxOTQ5MDQ5OSwicGF0aCI6Ii85OTAwODQxMi8zNDMwNjYxMjgtOTQ5Y2RlYTMtZDcyZS00ZDJmLThlZjYtZTVkMzFiOTliOGVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEyMTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMzE2Y2IzZjY2ZDkzYjlhN2VhYzIwMmMyMWUzNTk4MzM5YzFlNjNmMTgzNGY1ZTc4NzE5MWM3ZmM1ZmFlNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dlzfIfRCWHznMNuJsiMsGPDt7Wy7m6H-eGcLeITC4js)
> 
> Tämä on selkeä:
> 
> ![Image](https://private-user-images.githubusercontent.com/99008412/343066215-3e9170ef-52f8-40a7-8226-7ea8b5eaca8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0OTA3OTksIm5iZiI6MTcxOTQ5MDQ5OSwicGF0aCI6Ii85OTAwODQxMi8zNDMwNjYyMTUtM2U5MTcwZWYtNTJmOC00MGE3LTgyMjYtN2VhOGI1ZWFjYThhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDEyMTQ1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMWNkZWFjMjY4NzhiYTc4ZmVhZjJmZDRhOWE3YWNjNjM3MWIyMzg1MzlkNjBhOTY1ODI3MTUxZDFkZDA4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kPckQGcqnx1tpXkX6Y19APcbB0ddt-57HMsY425SCcQ)

Tiketissä #1173 on ehdotus sanamuodoista, jotka olisivat samaa muotoa kuin esim. takaajalla on.

**Comment by pirliis** [comment]
OUTIn testillä takaajan tiedoissa taattavien maksut näkyvät oikein välilehdellä Taattavien maksut:


![Image](https://github.com/user-attachments/assets/8847d600-4d59-4dfe-9cdf-63f7c2102033)
