### ISSUE TITLE
OUTI: Paavolan kirjaston omatoimiovikoneen SIP2-tunnuksen lisääminen

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1240]
### Tukipyyntö

Support-postiin lähetetään kohtapuolin pyyntö Paavolan kirjaston omatoimiovikoneen SIP2-tunnuksen lisäämisestä OUTIn automaattipalvelinten konfiguraatioon, palvelinryhmään outi-outi.

Tunnuksen tiedot on lähetetty salattuna myös automaatin asentajalle.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle, ovat käytössä huomenna.

**Comment by piiaseme** [comment]
Kiitos, suljen tiketin.
