### ISSUE TITLE
API- ja automaattitunnusten suojaaminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1243]
### Tukipyyntö

Asiakastunnukset pystyy Kohan nykyisessä versiossa suojaamaan poistamiselta. Suojattu-asetusta ei saa laitettua päälle asiakkaiden erämuokkaus -työkalulla ja automaattitunnuksia on Vaskissa aika paljon, joten saisiko Vaskille ajon joka asettaisi borrowers-tauluun protected arvoksi '1' asiakkaille, joiden asiakastyyppi on 'AUTOM' tai 'API'?

**Comment by ajrajala** [comment]
Määräajaksi heitetty 31.5., saa tehdä aiemminkin.

**Comment by emta001** [comment]
Tunnukset suojattu seuraavalla loitsulla:

`UPDATE borrowers SET protected = 1 WHERE categorycode IN("AUTOM", "API");`

**Comment by ajrajala** [comment]
Kiitokset, nämä ok!
