### ISSUE TITLE
OUTI: Muhoksen kirjaston niteet pois Muuttolaatikossa-tilasta

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1254]
### Tukipyyntö

Muhoksen kirjasto on ollut remontissa ja on avautumassa kesäkuun aikana. Toivomuksena olisi, että kirjaston niteiltä, jotka ovat Muuttolaatikko-tilassa, niteiden tilat ajettaisiin Saatavana-tilaan kahdessa erässä:

Ajo maanantaina 3.6.2024:
- Nykyinen kirjasto: Muhoksen kirjasto (MUPK)
- Hyllypaikka: Aikuiset, Käsikirjasto, Lehdet, Musiikki, Varasto, Varasto, ei lainata
- Nidetilamuutos: Muuttolaatikossa -> Saatavana

Ajo maanantaina 17.6.2024:
- Nykyinen kirjasto: Muhoksen kirjasto (MUPK)
- Hyllypaikka: Lapset ja nuoret, Lasten ja nuorten varasto
- Nidetilamuutos: Muuttolaatikossa -> Saatavana

Liittyy tikettiin #997

**Comment by paxed** [comment]
Eka ajo tehty tällä rimpsulla: update items i set i.notforloan=0 where i.notforloan=15 and i.holdingbranch='MUPK' and i.location in ('AIK', 'K', 'LEH', 'MUS', 'VAR', 'VAREILAI');

Muuto koski 34731 nidettä.

**Comment by emta001** [comment]
Toinen ajo tehty:

`update items i set i.notforloan=0 where i.notforloan=15 and i.holdingbranch='MUPK' and i.location in ('LN', 'VARLN');`

8229 nidettä vaihtui.

**Comment by pirliis** [comment]
Kiitos! Muhoksen kirjastolta ei löytynyt enää yhtään muuttolaatikossa olevaa nidettä, joten suljen tiketin.
