### ISSUE TITLE
"Uusi kaikki"-toiminto ei toimi testikannassa

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha#1259]
### Mikä vikana?

Asiakkaan lainoissa oleva "Uusi kaikki"-toiminto ei toimi Lastun testikannassa, ja Annelin testausten perusteella ei myöskään Vaaran testikannassa. Vaaran tuotannossa kuitenkin toimii, eli näyttäisi vaikuttavan vain testikantoihin.

Kun "Uusi kaikki"-nappia painaa, Koha avaa uusimisen sijaan "Tietojen vienti"-työkalun (...tools/export.pl). Järjestelmäasetukset käyty läpi, enkä keksi sieltä mitään mikä tähän vaikuttaisi. DevToolsin perusteella näyttäisi lähettävän POST-pyynnön suoraan tuonne export.pl - URLille heti nappia painettaessa.

### Mitä pitäisi tapahtua

Napin pitäisi uusia asiakkaan kaikki lainat.

### Kuinka toistaa ongelma/asia

1. Avaa testikannasta asiakastietue jolla on lainoja
2. Koita uusia kaikki lainat "Uusi kaikki"-nappia painamalla

### Selain

```markdown
Firefox 115.11.0es
Chrome 125.0.6422.61
```

**Comment by emta001** [comment]
Tämä johtui siitä, että tiketin #736 kehityshaarassa oli tullut mukana sinne kuulumatonta koodia. Tämä on nyt korjattu testeillä ja "Uusi kaikki"-toiminnon tulisi nyt toimia kuten pitääkin.

**Comment by LastuJanneS** [comment]
Kiitos nopeasta korjauksesta! Tämä todettu toimivaksi, suljen tiketin.
