### ISSUE TITLE
TäTistä käyttäjätunnuksilta Varaustunnuksen tyhjennys/poisto

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1260]
### Tukipyyntö

Haluaisin poistaa Tätistä kokonaan HOLDID-asiakasmääreen, koska se on siellä turha. Se on kuitenkin käytössä tällä hetkellä reilulla 100 tunnuksella, eikä uniikiksi merkittyä asiakasmäärettä saa poistettua asiakkaiden erämuokkauksella. Voisiko joku tyhjentää/poistaa kaikilta tunnuksilla HOLDID-määreet, niin poistan sen jälkeen koko asiakasmääreen?

**Comment by lmstrand** [comment]
Kaikki borrower_attributes-taulun merkinnät olivat noita HOLDID:tä.

Ajettu:

MariaDB [tatiprod]> delete from borrower_attributes;
Query OK, 116 rows affected (0.007 sec)

**Comment by AnneliO** [comment]
Kiitos, nyt sain poistettua HOLDID-asiakasmääreen! :)
