### ISSUE TITLE
Tätissä tuplatietoja biblio- ja deletedbiblioitems-taulussa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1263]
### Tukipyyntö

Tätin [about-sivu](https://tati.koha-suomi.fi/cgi-bin/koha/about.pl) kertoo seuraavaa:

Bibliographic records

The following IDs exist in both tables biblio and deletedbiblioitems:

1590758 , 1590759 , 1590760 , 1590761 , 1590762 , 1590763 , 1590764 , 1590765 , 1590766 , 1590767 , 1590768 , 1590769 , 1590770 , 1590771 , 1590772 , 1590773 , 1590774 , 1590775 , 1590776 , 1590777 , 1590778 , 1590779 , 1590780 , 1590781 , 1590782 , 1590783 , 1590784 , 1590785 , 1590786 , 1590787 , 1590788 , 1590789 , 1590790 , 1590791 , 1590792 , 1590793 , 1590794 , 1590795 , 1590796 , 1590797 , 1590798 , 1590799 , 1590800 , 1590801 , 1590802 , 1590803 , 1590804 , 1590805 , 1590806 , 1590807 , 1590808 , 1590809 , 1590810 , 1590811 , 1594049 , 1594050 , 1594051 , 1594052 , 1594053 , 1594054 , 1594055 , 1594056 , 1594057 , 1594058 , 1594059 , 1594060 , 1594061 , 1594062 , 1594063 , 1594064 , 1594065 , 1594066 , 1594067 , 1594068 , 1594069 , 1594070 , 1594071 , 1594072 , 1594073 , 1594074 , 1594075 , 1594076 , 1594077 , 1594078 , 1594079 , 1594080 , 1594081 , 1594082 , 1594083 , 1594084 , 1594085 , 1594086 , 1594087 , 1594088 , 1594089 , 1594090 , 1594091 , 1594092 , 1594093 , 1594094 , 1594095 , 1594096 , 1594097 , 1594098 , 1594099 , 1594100 , 1594101 , 2120292

**Comment by lmstrand** [comment]
Ajettu:

MariaDB [tatiprod]> delete from deletedbiblioitems where biblionumber in (1590758 , 1590759 , 1590760 , 1590761 , 1590762 , 1590763 , 1590764 , 1590765 , 1590766 , 1590767 , 1590768 , 1590769 , 1590770 , 1590771 , 1590772 , 1590773 , 1590774 , 1590775 , 1590776 , 1590777 , 1590778 , 1590779 , 1590780 , 1590781 , 1590782 , 1590783 , 1590784 , 1590785 , 1590786 , 1590787 , 1590788 , 1590789 , 1590790 , 1590791 , 1590792 , 1590793 , 1590794 , 1590795 , 1590796 , 1590797 , 1590798 , 1590799 , 1590800 , 1590801 , 1590802 , 1590803 , 1590804 , 1590805 , 1590806 , 1590807 , 1590808 , 1590809 , 1590810 , 1590811 , 1594049 , 1594050 , 1594051 , 1594052 , 1594053 , 1594054 , 1594055 , 1594056 , 1594057 , 1594058 , 1594059 , 1594060 , 1594061 , 1594062 , 1594063 , 1594064 , 1594065 , 1594066 , 1594067 , 1594068 , 1594069 , 1594070 , 1594071 , 1594072 , 1594073 , 1594074 , 1594075 , 1594076 , 1594077 , 1594078 , 1594079 , 1594080 , 1594081 , 1594082 , 1594083 , 1594084 , 1594085 , 1594086 , 1594087 , 1594088 , 1594089 , 1594090 , 1594091 , 1594092 , 1594093 , 1594094 , 1594095 , 1594096 , 1594097 , 1594098 , 1594099 , 1594100 , 1594101 , 2120292);
Query OK, 108 rows affected (0.027 sec)

**Comment by AnneliO** [comment]
Yritin poistaa tietueet, mutta taustatyö jää Started-tilaiseksi. Progress 1/108. Työ ei valmistu.

**Comment by lmstrand** [comment]
Kaikki muu data on kadonnut tietokannasta, paitsi tietueen 2120292 metadata.

**Comment by AnneliO** [comment]
Poistin tietueen 2120292 nyt tietueesta käsin ja se poistui.

About-sivu ei enää herjaa tuplatunnuksista, joten suljen tiketin. Kiitos!
