### ISSUE TITLE
Varaustunnusten anonymisointi ja pseudonymisointi

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha#1264]
### Kehitysehdotukseni

Nykyinen anonymisointi ja pseudonymisointi ei koske varaustunnukseen. Jotkut asiakkaat käyttävät varaustunnuksissa omia nimiään tai muita tunnistettavissa olevia tietoja. Raija-skriptiin kannattaisi lisätä HOLDID:t tyhjenemään/muodostumaan uudestaan.

**Comment by paxed** [comment]
Raija anonymisoi nyt HOLDID:t
