### ISSUE TITLE
Ruotsinkielinen Koha: Asiakkaan etu- ja sukunimellä haku ei tuo aina hakutulosta 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1268]
### Mikä vikana?

Ruotsinkielisessä asiakashaussa asiakkaan etu- ja sukunimellä hakiessa ei saa aina hakutulosta. Haku jää bearbetar-tilaan eikä valmistu.

Tämä haku Hellessä ei valmistune koskaan (ollut päällä nyt n. 20 min.). Haetun asiakastiedon borrowernumber=127655
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/031393fe-84f6-40f2-beb2-2245d49398e6)

Vastaava haku toimii suomenkielisessä Helle-Kohassa ja englanninkielisessä Helle-Kohassa.

**Comment by AnneliO** [comment]
Ruotsinkielistä Kohaa käyttäessä tulee konsoliin tällainen virheilmoitus:

Uncaught ReferenceError: $format_address is not defined
    render Ember
    S https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:56
    fnGetData https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:50
    B https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:55
    Ha https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:63
    P https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:67
    vb https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:78
    lb https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:75
    i https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:73
    success https://helle.koha-suomi.fi/intranet-tmpl/lib/datatables/datatables.min_23.1100000.js:74
    jQuery 4

**Comment by johannaraisa** [comment]
Arvaus on, että Hellessä on joku paikallinen säätö joka rikkoo tuon. Kokeilin muissa ympäristöissä ja ruotsinkielellä haku toimi.
Onko mahdollisesti muutettu jotain lähiaikona?

**Comment by johannaraisa** [comment]
Näyttäisi ettei Koha osaa ladata tällaista tiedostoa ruotsinkielisessä versiossa: js-patron-format-address.inc. Muissa kielissä se tulee ja katsoin, että kyllä se on tiedostoissakin paikallaan. Muissa kimpoissakin tiedosto latautuu ruotsinkielisessä versiossa. En tiedä onko plackin uudelleen käynnistyksestäkään apua, se tehdään joka yö joten olisi kai pitänyt jo korjaantua.

**Comment by johannaraisa** [comment]
Selvisi, template cache oli jostain syystä jumissa. Nyt pitäisi toimia!

**Comment by Kati-Helle** [comment]
Toimii. Kiitos!
