### ISSUE TITLE
Varauksen lainaaminen ei aina päivitä timestampia reserves-taulussa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1269]
### Mikä vikana?

Vaskissa huomattiin, että old_reserves-taulussa osassa varauksista timestamp ei muutu silloin kun nide lainataan ja varauksen found-arvoksi tulee 'F'. Esim. alla olevissa esimerkeissä toisessa timestamp on päivittynyt ja toisessa ei:

<body link="#0563C1" vlink="#954F72">

reserve_id | borrowernumber | reservedate | biblionumber | branchcode | cancellationdate | cancellation_reason | found | timestamp | itemnumber | waitingdate | expirationdate
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
34660 | 37131 | 21.3.2021 | 674665 | TUPK |   |   | F | 19.1.2024  19:16:44 | 1743353 | 19.1.2024 | 26.1.2024
498221 | 28 | 16.11.2021 | 4217687 | TUPK |   |   | F | 16.1.2024  15:21:29 | 2745827 | 14.1.2024 | 21.1.2024

</body>

</html>

Action_logs näyttää tältä:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/f8d064c1-b019-4c71-8a8c-0f471bc11285)

Tämä huomattiin, kun oli tarkoitus tarkastella miten nopeasti noudettavaksi saapumisen jälkeen varaukset keskimäärin lainataan. Old_reserves-taulussa selkeällä enemmistöllä näytti timestampissa olevan sama päivä kuin mikä waitingdate oli. Sen perusteella vaikuttaisi, että timestamp jäisi päivittymättä ihan toistuvasti.

**Comment by johannaraisa** [comment]
Timestamp arvo päivittyy aina kun tietokanta riviin tapahtuu muutos. Old_reserves-tauluun siirretään reserves-taulun rivi ja minusta minusta sql toimii niin, että jos kaikki kentät kopioidaan, niin ne pysyvät alkuperäisinä. Timestampin varmaan pitäisi päivittyä jo kun se on reserves-taulussa ennen siirtoa old_reserves-tauluun.

**Comment by ajrajala** [comment]
Aivan, kuulostaa loogiselta. Korjasin tuon tiketin otsikkoon.

**Comment by johannaraisa** [comment]
Tämä näyttää olevan ihan yhteisön versiossa tämä ongelma, kun tuo siirretään sinne old_reserves-tauluun niin siitä päivitettän se found-arvo ja priority laitetaan nollaksi. Samassa kohdassa pitäisi muokata tuo aikaleima.

**Comment by johannaraisa** [comment]
Tein tästä tiketin yhteisöön, [37023](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37023)

**Comment by johannaraisa** [comment]
Tätä voi nyt testata testeillä.

**Comment by ajrajala** [comment]
Testasin vaski-testillä, nyt timestamp päivittyi lainaushetken mukaisesti kun tärpänneen varauksen lainasi asiakkaalle. Testejä edeltävissä tapauksissa aikaleima ei vastannut lainausajankohtaa:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/a6d57845-2723-43ec-b143-781ae56008c0)

**Comment by Kati-Helle** [comment]
Helle-testissä timestamp päivittyy noudettavan varauksen lainauksessa

voimassa oleva varaus
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0628e9d3-2af4-4185-ad8c-ac46a93bde78)

ko. varaus lainattu
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/e5d24c76-748f-4482-94d5-b161674e35ce)

lainatun varauksen timestamp-arvo vastaa statistics-taulun lainausajankohtaa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1644c788-0fd6-4702-984f-e89c6636683c)

**Comment by ajrajala** [comment]
Tarkastelin old_reserves-taulusta tänään lainattuja varauksia ja nyt timestampiksi näyttää päivittyneen aina lainaushetken aikaleima. Tämä siis kunnossa, suljen tiketin.
