### ISSUE TITLE
OUTI: Finvoice-laskun peruutus

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1270]
### Tukipyyntö

Oulussa luotiin vahingossa laskutustyökalussa asiakkaalle finvoice-lasku. Lasku ei saisi lähteä liikkeelle, joten voisiko laskun perua?
Asiakas: borrowernumber=271627

Otan asiakkaalta ja niteiltä laskutusmerkinnät pois.

**Comment by johannaraisa** [comment]
Nyt se on failed-tilassa, en ole ihan varma onko nuo poistettu kokonaan message_queue-taulusta.

**Comment by piiaseme** [comment]
Edellisellä kerralla @emta001 kommentoi, että viesti piti perua ja, että se oli failed-tilassa. Tämä tapahtui tiketissä: https://github.com/KohaSuomi/Koha/issues/1185, jos siitä on apua.

**Comment by emta001** [comment]
En oo poistellut noita taulusta, pelkästään laittanut failed-tilaan. Tosin rupesin miettimään, että tekeekö näillä sitten jatkossa mitään vai voisiko ne ihan yhtä hyvin poistaakin.

**Comment by piiaseme** [comment]
Jos ne poistaa taulusta, niin estääkö se laskun lähettämisen uudelleen? Jos estää, niin onko niistä haittaa, jos jäävät tauluun roikkumaan?

Eilistä laskua ei lähetetä asiakkaalle lainkaan, mutta tiketin #1185 asiakkaan lasku muistaakseni lähetettiin uudelleen oikeilla tiedoilla ja oikeaan aikaan.

**Comment by johannaraisa** [comment]
Ei estä mitään, aina voi luoda uuden laskun.

**Comment by piiaseme** [comment]
Kiitos :) Suljen tiketin.
