### ISSUE TITLE
Ohita rajoitus tilapäisesti -painike ei päästä lainaamaan

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1273]
### Mikä vikana?

Tuotantoympäristöissä (ainakin vaski, outi ja helle) Lainaus-välilehdellä oleva "Ohita rajoitus tilapäisesti" -painike lataa sivun https://vaski.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?forceallow=1&borrowernumber=307898 mutta lainauslaatikkoa ei tule kuitenkaan näkyviin. Testiasiakkaalla on yksi aktiivinen ja yksi vanhentunut rajoite, mutta ongelma toistuu vaikka rajoitteita olisi asiakkaalla yksikin.

Testiympäristöissä samaa ongelmaa ei saatu toistumaan.

**Comment by johannaraisa** [comment]
Heittääkä muillakin Koha kokoajan ulos, jos yrittää linkin kautta sisään?

**Comment by AnneliO** [comment]
Mulla teki nyt niin, että jos klikkasin Ohita rajoitus tilapäisesti -nappulaa, niin Koha kysy uudelleen kaksivaiheisen kirjautumisen tokenia, jonka jälkeen se palasi samalle sivulle. Kokeilin parikin kertaa. Vasta sitten kun klikkasin Tiedot-välilehdelle, niin se kertaalleen vielä kysyi tokenin uudelleen, muttan sen jälkeen ei enää. Sain vastaavan uudelleenkirjautumisluupin aikaiseksi myös tikettiä [1135](https://github.com/KohaSuomi/Koha/issues/1135) testatessa.

**Comment by ajrajala** [comment]
Minullakin tuli ihan toisessa yhteydessä (yritin siirtyä lainauksesta maksut-sivulle) uudelleen tuo kaksivaiheisen tunnistautumisen kysely.

**Comment by AnneliO** [comment]
Bugzillasta löytyi tällainen tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36146

**Comment by johannaraisa** [comment]
Hmm, tossa sanotaan että olisi korjaantunut versiossa 23.11, pitää varmaan katsella onko versioon tullu jotain päivityksiä.

**Comment by sksandel** [comment]
En saa tätä ongelmaa toistumaan Vaskin tuotannossa. 

13.8.2024 Koha-päivityksessä korjattiin virhe, joka esti lainarajoituksen ohituksen jos asiakkaalla oli maksuja yli lainakiellon. Olisiko tämäkin siis korjaantunut?

**Comment by AnneliO** [comment]
OUTIn tuotannossakin Ohita rajoitus tilapäisesti -nappulan painallus tuo nyt näkyville lainaus-boksin. Eli vaikuttaisi tosiaan siltä, että ongelma on korjaantunut.
