### ISSUE TITLE
Vaski: Ilpoisten varausten keskeytysten siirto

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1274]
### Tukipyyntö

Ilpoisten remontti jatkuu arvioitua pidempään, joten varausten keskeytyksiä täytyisi jatkaa. Aikavälillä 6.6. - 7.7. jatkuvat varaukset tulisi siirtää jatkumaan 8.7.
Nähdäkseni riittää, että näille varauksille laittaa suspend_until päiväksi 8.7.2024:
```
SELECT reserve_id FROM reserves WHERE branchcode = 'TUIL' AND suspend_until BETWEEN '2024-06-06' AND '2024-07-07'
```

**Comment by johannaraisa** [comment]
Nyt on siirretty päivää.

**Comment by MikkoLiimatainen** [comment]
Kiitos!
