### ISSUE TITLE
Kahden uuden automaattitunnuksen lisääminen SIP-palvelimelle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1275]
### Tukipyyntö

Tiedot lähetetty support-postiin. Pyyntö tuli meille lyhyellä varoitusajalla, mutta saisiko nämä lisättyä jo tänään jotta olisivat huomenna toiminnassa?

**Comment by johannaraisa** [comment]
Nyt on lisätty, pitäisi huomenna toimia.

**Comment by ajrajala** [comment]
Jes, kiitokset!
