### ISSUE TITLE
Kotkan kirjastoauton varausten viimeisen noutopäivän siirto

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha#1276]
### Tukipyyntö

Kotkan kirjastoauton varausten viimeiset noutopäivät pitäisi siirtää aikaväliltä 17.6.-4.8. päivälle 5.8.

**Comment by johannaraisa** [comment]
Nyt on siirretty.

**Comment by VaisanRo** [comment]
Kiitos! Suljen tiketin.
