### ISSUE TITLE
Siilinjärvi: Vahvista lainaus -pop-upin Kyllä, lainaa -valinta antaa väärän eräpäivän

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#1277]
### Mikä vikana?

Kirja on lainattu kirjastosta A asiakkaalle a eräpäivällä 19.8.2024.
Kun se on jostain syystä palauttamattomana hyllyssä kirjastossa B ja asiakas b yrittää sitä lainata, virkailijalle tulee Vahvista lainaus -poppari.

![Vahvista lainaus](https://github.com/KohaSuomi/Koha/assets/98806001/e827c389-d734-416e-a345-91a061a170c9)

Kyllä, lainaa -valinta lainaa kirjan asiakkaalle b, mutta antaa eräpäiväksi kirjasto A:n kalenterin mukaisen eräpäivän 19.8.2024 eikä kirjasto B:n kalenterin mukaista eräpäivää 4.7.2024.

En löytänyt tästä aiempaa tikettiä.

### Mitä pitäisi tapahtua

Eräpäivän pitäisi tulla lainaavan kirjaston kalenterin mukaan.

**Comment by AnneliO** [comment]
Tämä johtuu minusta periaatteessa asetuksesta  HomeOrHoldingBranch, jossa määritetään, käytetäänkö koti- vai sijaintikirjaston lainasääntöjä. Tässä tapauksessa sijaintikirjasto on lainatessa ollut kirjasto A, jolloin on käytetty sen laina- ja maksusääntöjä. Tämä olis tapahtunut, vaikka nide olisi ollut saatavana-tilaisena kirjaston B hyllyssä ja lainattu sitten kirjastossa B. Vastaavaa on tapahtunut esim. kirjastoautoissa, jotka ovat poimineet "parkkeerauskirjaston" kokoelmista niteitä mukaansa palauttamatta tai muokkaamatta niiden sijaintikirjastoa ensin.

**Comment by AnneliO** [comment]
Lisäyksenä vielä, että käytännössä tuohon asetukseen ei siis vaikuttaisi vaihtaa toista vaihtoehtoa, koska silloin säännöt menisi aina niteen kotikirjaston mukaan, joka voi olla yleisesti ottaen / normaalitilanteessa vielä enemmän väärin.

**Comment by AnneliO** [comment]
Laina- ja maksusäännöt noudattavat eräpäiväkalenteria määrittäessään eräpäivän, joten tuossa tapauksessa mennään kirjaston A kalenterin mukaan. :)

**Comment by ReettaSiili** [comment]
Suljen tämän ja ohjeistan virkailijaa, että jos mahdollista, Kohan popparien "oikoteitä" ei kannata käyttää. Varmempi tehdä tässäkin tapauksessa pitkän kaavan mukaan: ensin palauttaa, sitten vasta lainata asiakkaalle b.
