### ISSUE TITLE
Sotuteekissä vääränmallisia henkilötunnuksia?

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1279]
### Tukipyyntö

OUTIssa tämän viikon Finvoice-laskutuksessa on kahden asiakkaan laskut jumittaneet Oulun kaupungin intimeen eli laskut ovat lähtenee Kohasta, mutta juuttuneet matkan varrelle. Laskutuksessa olivat päätyneet siihen tulokseen, että jumi voisi johtua väärin tallennetuista hetuista. 

Sotuteekissä en näe onko hetussa esim. ylimääräisiä välilyöntejä, joka voisi olla mahdollista toisen asiakkaan kohdalla.
Asiakas: borrowernumber=281862
Toisella asiakkaalla on välimerkkinä +. Hän ei ole 1800-luvulla syntynyt.
Asiakas: borrowernumber=216738

Pääseekö kehittäjät tarkistamaan sotuteekistä onko hetussa ylimääräisiä merkkejä, jotka voivat sotkea asioita? Sillä tavalla saisi ehkä ainakin sen toisen selvitettyä ja tohtisimme laittaa hänen laskun eteenpäin.

### Jotain muuta?

Laskin asiakkaiden hetujen tarkistusmerkit ja ne oli ok eli niiden mukaan hetut ovat oikein, lukuunottamatta toisen asiakkaan välimerkkiä, joka on +.

**Comment by CodoDerDritte** [comment]
Molempien asiakkaiden henkilötunnukset siilossa ovat muodollisesti oikein, joskin toki toinen asiakkaista on hetun mukaan yli 100 vuotias.

**Comment by CodoDerDritte** [comment]
Tarkistin myös avaimen Kohassa, sekin on tallentunut virheettömästi.

**Comment by piiaseme** [comment]
Tallennamme näille asiakkaille henkilötunnukset uudelleen. Ainakin tämän yli 100 vuotiaan asiakkaan kohdalla hänen tietonsa päivittyvät oikeiksi uudelleen tallennuksella. Kiitos Kodo selvittelystä :) Suljen tiketin.
