### ISSUE TITLE
Vaski: Lainauskirjaston muutos poistettavan kirjaston lainoille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1280]
### Tukipyyntö

Kirjastoyksikkö TUSK on suljettu pysyvästi viime joulukuussa ja tarkoituksena on saada poistettua jossain vaiheessa kirjasto Kohasta. Kirjaston varaukset, kuljetukset ja asiakkaat on jo kaikki käsitelty/siirretty toiselle kirjastolle, mutta issues-taulussa on vielä lainoja joiden lainauskirjasto TUSK on.

Onnistuisiko siis muuttaa issues-tauluun branchcode TUSK tilalle TUPK? Muutettavia lainoja on yhteensä 61 kpl.

(Olemme todenneet, että lainauskirjaston muutos on esim. laskutuksen kannalta meille ok ja tarpeen tullen statistics-taulusta on mahdollista selvittää mistä yksiköstä nide alun perin on oikeasta lainattu.)

**Comment by ajrajala** [comment]
Ei mitään kriittistä määräaikaa, ok tehdä aiemmin tai myöhemmin.

**Comment by johannaraisa** [comment]
Muutos on nyt tehty näille lainoille (issue_id):
3002
4188
19046
19047
19216
19217
19218
940203
1814511
1814515
1814517
1814520
1901065
1950283
1950287
1950288
3615513
4508418
4842449
4947099
4985308
5018626
5044165
5044167
5044170
5044171
5044278
5066164
5088524
5115680
5168797
5177000
5181698
5181703
5195759
5195781
5195934
5195940
5406927
5467204
5616026
5647588
5666696
5669720
5669721
5827814
5827817
5827819
5827839
5827846
5827859
5827876
6291113
6296094
6305446
6491693
6522939
6811863
6856422
7446261
8264764

**Comment by ajrajala** [comment]
Kiitokset, nämä ok!
