### ISSUE TITLE
Virheilmoituksia käsin lisätyissä hankinnoissa

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha#1282]
### Mikä vikana?

Kun on lisätty käsin uusi hankinta tyhjästä tietueesta, 942 c -kenttään tulee virheilmoitus "Nykyistä arvoa 14VRKLAULA ei ole määritetty tätä osakenttää kontrolloivan auktorisoidun arvon tyyppiin". Koha tarjoaa aluksi laina-aikaa, mutta ei hyväksy sitä vaan se pitää vaihtaa pudotusvalikosta. Aiemmin, ts. ennen järjestelmäpäivitystä kenttä oli tyhjä.
![kuva](https://github.com/KohaSuomi/Koha/assets/111975210/302fbe9e-0d6b-4e39-ba97-3376aab447c7)

Toinen virheilmoitus tuli, kun lisättiin kausijulkaisusta yksi numero myöskin käsin.
![kuva](https://github.com/KohaSuomi/Koha/assets/111975210/1fe1f7c3-0633-412e-889f-a5ad806f9283)

### Selain

```markdown
Firefox ESR 115.11
```

**Comment by johannaraisa** [comment]
Mitä kuvailupohjaa on käytetty, onkohan teillä jotain häikkää niissä? Tuo 14VRKLAULA on nidetyyppi ja 942c-kenttiin laitetaan aineistotyyppi eli auktorisoituarvo MTYPE.

**Comment by AnneliO** [comment]
SER-kuvailupohjan 952y-kentän oletusarvoksi on merkitty _ALEHTI_, jollaista nidetyyppiä teillä ei ole:
https://kirkes.koha-suomi.fi/cgi-bin/koha/admin/marc_subfields_structure.pl?op=add_form&tagfield=952&tagsubfield=y&frameworkcode=SER#subyfield

**Comment by AnneliO** [comment]
> SER-kuvailupohjan 952y-kentän oletusarvoksi on merkitty _ALEHTI_, jollaista nidetyyppiä teillä ei ole: https://kirkes.koha-suomi.fi/cgi-bin/koha/admin/marc_subfields_structure.pl?op=add_form&tagfield=952&tagsubfield=y&frameworkcode=SER#subyfield

Eli ALEHTI-tieto pitäisi poistaa 952y-kentän oletusarvosta. :)

**Comment by helasann** [comment]
ALEHTI-tieto poistettu.
