### ISSUE TITLE
LAPPI: Vanhojen lehtitilausten sulkeminen

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1283]
### Tukipyyntö

Lapin lehtitilaukset vuosilta 2022-2023 saa sulkea ja tilauksiin liittyvät odottavat numerot pitäisi "pysäyttää".

[Lehtitilausten sulkeminen ja odottaa-tilaisten tiputtaminen reklamaatiot -listalta](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#lehtitilausten-sulkeminen-ja-odottaa--tilaisten-tiputtaminen-reklamaatiot--listalta)

**Comment by IrinaHalminen** [comment]
Saako tähän samaan tulla kuokkimaan ja pyytämään tuota myös Vaaran vuoden 2023 lehtitilauksille?

**Comment by AnneliO** [comment]
> Saako tähän samaan tulla kuokkimaan ja pyytämään tuota myös Vaaran vuoden 2023 lehtitilauksille?

Tee Irina mielummin oma tiketti. :)

**Comment by johannaraisa** [comment]
Nyt tämä on tehty Lapille.

**Comment by PiaKusmin** [comment]
Kiitos! Suljen tiketin.
