### ISSUE TITLE
Vanhentuneiden maksujen mitätöintiajo ei ole ollut päällä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1284]
### Tukipyyntö

OUTIn asiakkailla on yksityisoikeudellisia maksuja, jotka ovat vanhentuneet viimeisen versiopäivityksen jälkeen eli joka yö ajettava vanhentuneiden maksujen mitätöintiajo ei ole toiminut enää päivityksen jälkeen.

**Comment by CodoDerDritte** [comment]
Ongelma oli siinä, että jouduin taannoin korjailemaan cronien ajamisesta huolehtivaa skriptiä, koska se ei osannut käsitellä tuon vanhentumisajon parametrejä oikein. En ole vielä vaihtanut sitä uutta kaikille croneille, koska parametriongelma on akuutti vain nimenomaan tuon maksujen vanhentumisajon kanssa. Versiopäivityksessä sitten tietysti unohdin koko homman ja uusi versio skriptistä jäi tuomatta uuteen tuotantoon. Nyt se on kuitenkin tuotu ja maksujen vanhentumisajon pitäisi taas toimia normaalisti.

**Comment by pirliis** [comment]
Nyt ainakin OUTIssa versiopäivityksen jälkeen vanhentuneet maksut ovat myös mitätöityneet. Kiitos!

Varmaan sama ajo toimii nyt muissakin kimpoissa, joten suljen tiketin.
