### ISSUE TITLE
Raportteja MARC-tietueiden korjauksia varten

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1285]
### Tukipyyntö

Saisimmeko OUTIin kaksi raporttia MARC-tietueiden korjauksia varten.

1.	Raportti, jolla voi hakea tietueet, joiden 007-kentässä on vain arvo r ensimmäisessä merkkipaikassa tai sitten vaihtoehtoisesti tietueet, joilla on kaksi 007-kenttää, joista ensimmäisessä arvot qu ja toisessa r. 

Esim. tietue: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=359684
![image](https://github.com/KohaSuomi/Koha/assets/98814860/c67ac2e5-f44b-49e2-a331-242f4fc12784)

Tässä herja tulee tuosta toisesta r-kentästä ja nämä pitäisi saada poistettua. Herjaus tulee, koska loput r-kentän arvoista ovat tyhjiä, joten tämän ehkä voisi hakea niinkin, että tietueet, joissa 007-kentän 00-merkkipaikka on r ja loput 01-10 tyhjiä. 

2.	Raportti, jolla pystyy hakemaan tietueet, joiden 007-kentässä on merkkipaikoilla 00-04 arvot vd cv (tuossa välissä 02 on tyhjä merkkipaikka) ja merkkipaikat 05-08 on tyhjänä.

Esim. tietue: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=461534
![image](https://github.com/KohaSuomi/Koha/assets/98814860/9cfebb43-bb93-4199-a275-5aeb85ce44c6)

Raporttipyynnöt liittyvät tikettiin #981

**Comment by AnneliO** [comment]
Raportti 2.

Tein OUTIn tuotantoon [raportin 775](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=775&phase=Run%20this%20report), joka hakee tietueet, joissa 007 alkaa 'vd cv' ja loppuosa on tyhjä (tai ainakin toisen v:n jälkeen on kolme tyhjää). Tulokset on rajoitettu 7000 riviin, mikä tuo kaikki tulokset näkyville. Tarkistatteko, että tulokset ovat oikeanlaisia?

Raporttia 1 pitää vielä tutkia, en näköjään osaa hakea kenttien toistumia.

**Comment by AnneliO** [comment]
> > Raporttia 1 pitää vielä tutkia, en näköjään osaa hakea kenttien toistumia.
> 
> Tarkoitatko, ettei se osaa löytää noita tietueita, jos r-arvolla alkava 007-kenttä on toisena toistumana?

Jeps, mutta sain nyt apua muilta, niin saan nekin ehkä nyt haettua. Pistän kohta lisää tarkistettavaa. :)

**Comment by AnneliO** [comment]
Raportti 1.

Raportti 776 hakee nyt ne tietueet, joissa on ekassa 007:ssa qu ja tokassa r. Pelkkiä r:iä en löytänyt. Tutkailetteko taas, miltä tulokset näyttää?

Tuo ExtractValue-toiminto, jota tuossa raportissa käytetään toimii siten, että jos kentästä on toistuma, niin se "liimaa" kenttien tiedot yhteen, jolloin esimerkin kaltaisessa tapauksessa haettava merkkijono on 'qu r'. Laitan tämän tiedon tänne itselleni muistiin. :D

**Comment by AnttHeik** [comment]
> Raportti 1.
> 
> [Raportti 776](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=776&phase=Run%20this%20report) hakee nyt ne tietueet, joissa on ekassa 007:ssa qu ja tokassa r. Pelkkiä r:iä en löytänyt. Tutkailetteko taas, miltä tulokset näyttää?
> 
> Tuo ExtractValue-toiminto, jota tuossa raportissa käytetään toimii siten, että jos kentästä on toistuma, niin se "liimaa" kenttien tiedot yhteen, jolloin esimerkin kaltaisessa tapauksessa haettava merkkijono on 'qu r'. Laitan tämän tiedon tänne itselleni muistiin. :D

Kiitokset, oikeita tuloksia tuli, mutta vain 28 kappaletta. r-virheellisiä tietueita on OUTIssa 169 kpl, joten kaikkia tuo ei vielä löytänyt. Osa näyttää olevan myös moniviestimiä eli saisiko vielä toisen raportin, jossa hakuehto olisi: 'ou r' ? :)

**Comment by AnneliO** [comment]
Joo, noita 'ou r'-versioita oli myös. Koitan saada kummatkin samaan.. hetki pieni.

**Comment by AnttHeik** [comment]
> Raportti 2.
> 
> Tein OUTIn tuotantoon [raportin 775](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=775&phase=Run%20this%20report), joka hakee tietueet, joissa 007 alkaa 'vd cv' ja loppuosa on tyhjä (tai ainakin toisen v:n jälkeen on kolme tyhjää). Tulokset on rajoitettu 7000 riviin, mikä tuo kaikki tulokset näkyville. Tarkistatteko, että tulokset ovat oikeanlaisia?
> 
> Raporttia 1 pitää vielä tutkia, en näköjään osaa hakea kenttien toistumia.

Raportti 2 olikin oikein hyödyllinen. Kerralla korjaantui lähemmäs 7000 marc-virheellistä tietuetta :) Nyt tarvittaisiin tuon raportin perusteella vielä kolme eri raporttia, jossa hakuehto:

1. vd cs
2. vd bv
3. vd bs

Jos Annelilla on kiireitä, niin varmaan @pirliis tai @piiaseme saisi tehtyä nämä tuon alkuperäisen raportin osalta :)

**Comment by AnneliO** [comment]
> Joo, noita 'ou r'-versioita oli myös. Koitan saada kummatkin samaan.. hetki pieni.

Taisitkin jo käsitellä 'qu r' -versiot, koska niitä ei enää löydy. :) Mutta se sama raportti hakee nyt sitten tietueet, joissa on 'ou r'.

**Comment by CodoDerDritte** [comment]
Eiks toi "kriteeri" ois fiksuu heittää vaan parametriksi sille raportille, sit sillä vois hakee vaikke mitä?

**Comment by AnneliO** [comment]
> Eiks toi "kriteeri" ois fiksuu heittää vaan parametriksi sille raportille, sit sillä vois hakee vaikka mitä?

Testailen, että se varmasti onnistuu. Nuo Kohan tallennetut raportit ei aina toimi niin kuin olettaisi. :D

**Comment by AnneliO** [comment]
Testattu ja muutin raportin 775:n sellaiseksi, että siihen voi syöttää halutun merkkijonon. Ainakin minun testailujen mukaan se toimisi, mutta kannattaa testailla itsekin. :D

**Comment by AnttHeik** [comment]
> Testattu ja muutin raportin 775:n sellaiseksi, että siihen voi syöttää halutun merkkijonon. Ainakin minun testailujen mukaan se toimisi, mutta kannattaa testailla itsekin. :D

Pitääkö tässä syöttää kaikki tyhjätkin välilyönnit, jos niitä tulee jonkin rimpsun jälkeen lopuille merkkipaikoille?

**Comment by AnneliO** [comment]
> > Testattu ja muutin raportin 775:n sellaiseksi, että siihen voi syöttää halutun merkkijonon. Ainakin minun testailujen mukaan se toimisi, mutta kannattaa testailla itsekin. :D
> 
> Pitääkö tässä syöttää kaikki tyhjätkin välilyönnit, jos niitä tulee jonkin rimpsun jälkeen lopuille merkkipaikoille?

Vain nuo merkkijonot, minkä olet kirjannut tuossa aiemmin. Ei välilyöntejä tai muita merkkejä.

**Comment by AnneliO** [comment]
Lisäsin tuon parametrisen raportin myös [Raporttikirjastoon](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#tietueet-joissa-on-marc-kent%C3%A4ss%C3%A4-007-tietty-merkkijono).

**Comment by pirliis** [comment]
Kiitos Annelille! Suljen tiketin.
