### ISSUE TITLE
Vaara: Vanhojen lehtitilausten sulkeminen

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1289]
### Tukipyyntö

Vuoden 2023 lehtitilaukset voisi sulkea myös Vaarasta (vrt. tiketti #1283).
Kiitos!

**Comment by emta001** [comment]
Suljettu seuraavalla rimpsulla:

`UPDATE subscription SET closed='1' WHERE startdate > '2022-12-31' AND enddate < '2024-01-01';`

Muutos koski 1136 tilausta.
