### ISSUE TITLE
Helle: Pukkilan kirjaston voimassa olevien varausten keskeytys ma 24.6.2024

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1290]
### Tukipyyntö

Keskeytättekö maanantaina 24.6.2024 Hellen Pukkilan kirjaston voimassa olevat (ei tärpänneet) varaukset.
(Tällä hetkellä aktiivisia varauksia on 176.)

Kirjastotunnus
PUKPK

Varaukset aktivoitumaan 30.7.2024

**Comment by paxed** [comment]
Muutettu tällä rimpsulla:
`update reserves SET suspend = 1, suspend_until = '2024-07-30' WHERE branchcode = 'PUKPK' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-06-23' AND '2024-07-30'));`

Koski 158 varausta; siellä on 16 varausta, jotka on keskeytetty määräämättömäksi ajaksi, eli en muuttanut niitä.

**Comment by Kati-Helle** [comment]
Kiitos!
