### ISSUE TITLE
SIP2: Uusitun lainan eräpäivä ei päivity 

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#1291]
### Mikä vikana?

SIP2 raportoi väärin uusitun lainan eräpäivän ja tieto puuttuu kuitilta. Jos asiakas uusinnan jälkeen kirjautuu uudelleen automaatille, niin sitten pvm päivittyy tietoihin.

**Comment by lmstrand** [comment]
Yhteisössä korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37016

Tuodaan testeille ja kokeillaan korjaako ongelman.

**Comment by lmstrand** [comment]
Hienoa, kiitos testailusta. Viedään tämä SIP2-featurebranchiin, pääsee tuotantoon sitten ensi tiistaina.

**Comment by pirliis** [comment]
OUTIssa testattu uusintaa lainausautomaatilla ja nyt uusi eräpäivä näkyy heti uusintanäytöllä ja kun tulosti uusintakuitin, uusittu eräpäivä näkyi myös siinä oikein.

**Comment by ReettaSiili** [comment]
Samoin Siilissä Mikroväylän automaatilla eräpäivä päivittyy nyt oikein.

**Comment by lmstrand** [comment]
Suljen tiketin.

**Comment by IrinaHalminen** [comment]
Vaarassa palvelupäällikön testin mukaan toimii myös ok.
