### ISSUE TITLE
Lisää raportteja MARC-tietueiden korjauksia varten

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1293]
### Tukipyyntö

OUTIin haluttaisiin vielä pari uutta raporttia koskien 007-kentä arvoja.

1. Raportti, joka hakee tietueet, joissa merkkipaikan 007/00 arvo on k ja merkkipaikassa 007/04 on tyhjä merkki
Marc-virheilmoitus: (007-k/04 illegal value " ", should be [abcdefghilnmopqrstuvwz|])

Esim. tietue 1309165:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/2ee55d8d-388c-47bd-af91-8ec97cf3308f)

tai tietue 1969171:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/853911ae-f544-40a0-8c9e-5058b2ea1589)

2. Raportti, joka hakee tietueet, joissa on 007/00 = a ja merkkipaikalla 007-a/03 on tyhjä merkki
Marc-virheilmoitus (007-a/03 illegal value " ", should be [ac|])

Esim. tietue 1971935:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/fccc0c7f-c736-4030-ad74-529088798ecd)

tai tietue 1471651:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/cdf3e28e-dc7e-4561-8b7a-53971ba6ba81)

Pyynnöt liittyvät tiketteihin:
#1285 
#981

**Comment by AnneliO** [comment]
Raportti 1.

OUTIn tuotannossa [raportti 777](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=777&phase=Run%20this%20report) hakee nyt tietueet, joissa on 007/00 on 'k' ja 007/04 on tyhjä joko ensimmäisessä tai toisessa 007:n toistumassa. Testaatteko, toimiiko oikein?

**Comment by AnttHeik** [comment]
> Raportti 1.
> 
> OUTIn tuotannossa [raportti 777](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=777&phase=Run%20this%20report) hakee nyt tietueet, joissa on 007/00 on 'k' ja 007/04 on tyhjä joko ensimmäisessä tai toisessa 007:n toistumassa. Testaatteko, toimiiko oikein?

Kiitokset, oikealta näyttää :)

**Comment by AnneliO** [comment]
Raportti 2.

OUTIn tuotannossa [raportti 778](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=778&phase=Run%20this%20report) hakee tietueet, joissa 007/00 on 'a' ja 007/03 on tyhjä joko ensimmäisessä tai toisessa 007:n toistumassa. Testaatteko taas? :)

**Comment by AnttHeik** [comment]
> Raportti 2.
> 
> OUTIn tuotannossa [raportti 778](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=778&phase=Run%20this%20report) hakee tietueet, joissa 007/00 on 'a' ja 007/03 on tyhjä joko ensimmäisessä tai toisessa 007:n toistumassa. Testaatteko taas? :)

Joo, näyttäisi suurin piirtein vastaavan virheellisten tietueiden määrää :)

**Comment by AnneliO** [comment]
Raportti 2:

```
SELECT biblionumber, ExtractValue(bm.metadata,'//controlfield[@tag="007"]') AS '007'
FROM biblio_metadata bm
WHERE SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="007"]'),1,1) = 'a'
AND SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="007"]'),4,1) = ' '

UNION

SELECT biblionumber, ExtractValue(bm.metadata,'//controlfield[@tag="007"]') AS '007'
FROM biblio_metadata bm
WHERE SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="007"][2]'),1,1) = 'a'
AND SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="007"][2]'),4,1) = ' '
AND ExtractValue(metadata, 'count(//controlfield[@tag="007"])') > 1

LIMIT 5000
```

**Comment by AnneliO** [comment]
Raportit lisätty myös [Raporttikirjastoon](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#tietueet-joissa-00700-on-k-ja-00704-on-tyhj%C3%A4).

**Comment by pknuuti** [comment]
Miten (007-a/03 illegal value " ", should be [ac|])  virheet saisi korjattua?

**Comment by AnneliO** [comment]
> Miten (007-a/03 illegal value " ", should be [ac|]) virheet saisi korjattua?

Onko tämä vielä ajankohtainen kysymys?

**Comment by pknuuti** [comment]
Eiköhän tuo ole jo korjattu. Tiketin voinee sulkea?
