### ISSUE TITLE
Vaara: Varaustunnus näkyviin lainausautomaateille

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1294]
### Tukipyyntö

Asiakaspalaute: Asiakas toivoo, että lainausautomaatilla voisi saada tietoon varaustunnuksensa. Palvelupäällikkömme on selvitellyt tätä Mikro-Väylän kanssa, eikä toive tällä hetkellä Kohasta johtuvista syistä onnistu. 

Larin kanssa asiasta keskusteltu:
"Kohan SIP-palvelin ei välitä tietoa asiakkaan varaustunnuksesta automaateille oletuksena, mutta palvelinasetuksiin voi tiedon varmastikin lisätä (Koha sallii itsemääritettyjen kenttien käyttämisen asiakastietoviestissä ja muutenkin viestejä voi kustomoida). Tällä hetkellä siis 64-viestin AE-kentässä välittyy ainakin asiakkaan nimi (AA-kenttä patron identifier varattu korttinumerolle). Nimen voisi kokeilla korvata varaustunnuksella, jos asiakkaalta sellainen löytyy? Olisiko tuo sopiva paikka varaustunnustiedolle ja voisiko tietoa siitä käyttää tuossa omien varausten näkymässä automaatilla?"

**Comment by lmstrand** [comment]
Tähän on ehdotettu paria ratkaisua:

1. Korvataan asiakkaan etu- ja/tai sukunimi varaustunnuksella, jos asiakkaalla sellainen on
2. Luodaan mikroväylän automaatteja varten uusi kenttä asiakastietosanomaan, jossa välitetään varaustunnus (M-V:n mukaan automaattiohjelmistossa voi määrittää varaustunnustiedoksi minkä tahansa kentän). Ehkä myös käytettävissä Lyngsoen automaateilla

Molemmat vaativat muutoksen jokaiseen SIP-palvelinkonfiguraation tunnukseen.

**Comment by Thoriell** [comment]
Lyhyt kommentti: etu- ja sukunimi tulevat kentässä AE eli personal name (variable-length field; the patron’s name).. Tähän ei voi alkaa tunkea mitä vain, se rikkoo SIP2-protokollan sääntöjä ja hajottaa tuon kentän sisältöön nojaavien automaattien toiminnan.

Ehdottaisin kenttää PS (secondary patron identifier, toissijainen asiakastunnus), joka tuntuisi olevan kuin tälle luotu. (Kohassakin tuo näyttää olevan patron_attr_2, jos oikein katsoin.) Tämä ei ehtinyt SIP2:een, mutta on SIP3:ssa ja minusta tämä olisi tilanteeseen kuin nenä päähän. Osa P-kentistä on jo käytössä Kohassa ja SIP2:ssa, osa ei ehtinyt:

```
PA PAC access type (käytössä, omatoimiblokkauksessa)
PB patron birth date (käytössä, syntymäaika)
(PC patron class) (käytössä, asiakaslaji)
PE patron expiration date 
PI patron PIN 
PN new patron password 
**PS secondary patron identifier** 
PT payment type 
```

Tuo kuuluu varsinaisesti Kohan lähettämään 64-viestiin (patron information response). PS-kentästä voisi tuoda varaustunnuksen suoraan Lyngsoen kuiteille, kuittipohjia kun voi itsekin muokata ja niihin tuoda SIP2-kenttien sisältöjä.

**Comment by lmstrand** [comment]
Tämä vaatisi sittenkin koodimuutoksen. Nykyinen SIP-palvelimen tukema custom_patron_field
(esimerkki:<custom_patron_field field="EW" template="Phone: [% patron.phone %] Email: [% patron.email %]" />)
ei näköjään tue asiakasmääreiden hakua. Ehkä tästä voisi tehdä tiketin yhteisöön ja ehdottaa tukea asiakasmääreille/tarjota toteutusta heille.

**Comment by IrinaHalminen** [comment]
Yritämme saada automaatin näytölle tekstin varaustunnuksen tarkastamisesta noutoilmoituksesta. Jospa se ohjaisi asiakasta, ja tätä muutosta ei tarvittaisi.

**Comment by Thoriell** [comment]
Sinänsä kyllä kannattaisin varaustunnuksen tuontia automaatille tuolla mainitsemallani tavalla (esim. PS-kenttä). Tätä kysellään aika-ajoin ja voisi olla hyödyllinen ominaisuus. Ei toki mikään prioriteetti, mutta tuollainen sopiva kenttäkin olisi jo olemassa. :)

**Comment by IrinaHalminen** [comment]
Voin kyllä tarvittaessa tehdä tästä yhteisötiketin, jos vaikka Lari auttelee selostuksen kanssa. ;)
