### ISSUE TITLE
Käännöstoive: Asiakastakaajan haku tyhjällä kentällä, virheilmoitus englanniksi

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1295]
### Tukipyyntö

Jos takaajaa lisätessä hakee tyhjällä kentällä, virheilmoitus on englanniksi. Saisiko suomeksi?
![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/9dfda656-3d19-4525-8ba5-de26963c5ebe)
Tuli ilmi tiketissä #1014.

**Comment by AnneliO** [comment]
Tälle tosiaan on käännös olemassa fi-FI-staff-prog.po-tiedostossa:

#. SCRIPT
#: koha-tmpl/intranet-tmpl/prog/en/includes/patron-search.inc:254
msgid "Please fill out this field."
msgstr "Kirjoita kenttään."

Mutta jostain syystä se ei nyt "tartu".

**Comment by atarnus** [comment]
Hei, tähän on mahdollisesti jo ratkaisu. Ehdin laittaa githubiin päivitystä tuolle branchille, jossa virheteksti on muutettu sellaiseen muotoon, että sen pitäisi tarttua kääntäjään. Branchia ei ole kuitenkaan vielä päivitetty testille tai tuotantoon.

(KOHA-467: Prevent patron search with empty search field)

**Comment by atarnus** [comment]
OUTI-testillä toimii käännös nyt:

Asiakashaku:
![image](https://github.com/user-attachments/assets/81dc7349-6583-4156-a830-d6e69ff8dfb2)
Asiakkaan haku varauksen yhteydessä:
![image](https://github.com/user-attachments/assets/91614a2f-007b-4f8e-b15a-d875412d4886)

**Comment by emta001** [comment]
Toimii tuotannossa.

**Comment by AnneliO** [comment]
Tarkistettu, että toimii myös version 24.05 tuotannossa.
