### ISSUE TITLE
Vanhoja kuvalutietoja valuu uusien päälle

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1298]
### Mikä vikana?

OUTIssa on 19.6. ja 20.6. valunut tietueita normaaliin verrattuna paljon. 
Esim. tietueen 1906550 Taivassalo: Scandorama (https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1906550) kohdalla heräsi epäilys, että korjatun tietueen päälle olisi valunut TäTistä aikaisempi, korjaamaton tietue. Kirjastopalvelu oli korjannut kyseisen tietueen ykl-luokkaa 84.31 -> 85.331. Meillä OUTIssa signum oli oikein, mutta valuneen tietueen luokka oli 84.31. 

Samainen ongelma ilmeisesti Vaskissa ja Lumpeessa. Vaskista tuli tieto, että vanhoja FI-Om-tietueita olisi valunut heidän RDA-tietueidensa päälle.

**Comment by pirliis** [comment]
Ongelmat liittynee tikettiin: #1288

**Comment by pirliis** [comment]
Kimppojen paikalliskantojen metadatojen timestampit päivitetty 27.6., jonka jälkeen valutus laitettiin päälle, mutta ilmeisesti 20.6. keskeytetyn valutuksen loputkin tietueet lähtivät valumaan vielä paikalliskantoihin. Valutukset keskeytettiin taas 27.6. Paikalliskantojen metadatojen timestampit oikaistu uudelleen 1.7. Valutus laitettu Tätissä ja OUTIssa päälle 2.7. Tarkistetaan ensin mitä alkaa valumaan OUTIin. Jos mitään vanhaa ja väärää ei valu, Tietuesiirtäjät voidaan aktivoida myös muihin kimppoihin päälle.

**Comment by AnttHeik** [comment]
Hyvältä näyttää, ei tullut enää ylimääräisiä tietueita.

**Comment by emta001** [comment]
Käynnistin myös Vaskin ja Hellen. Vaskissa olikin enemmän päiviteltävää, mutta jono valmistui näemmä ihan kohtuullisessa ajassa. Myös Helle näyttäisi olevan ok. Käynnistän loputkin valutukset.

**Comment by emta001** [comment]
Tietuesiirtäjä on aktivoitu ja valutus laitettu päälle kaikissa kimpoissa.

**Comment by VaisanRo** [comment]
Kyytissä on viime viikolla valunut vanhan aineiston päälle tietueita TäTistä. Ainakin näiden tietueiden päälle on valunut luettelointi TäTistä:

211788 Derbyshire: Alkulukujen lumoissa (9525202755) 
•	kirja on lainattu viimeksi vuonna 2019
 
871076 Puonti: Suhteesta siunaukseen (978-951-619-523-3)
•	kirja on lainattu viimeksi vuonna 2018
 
220632 Roope Ankka ja automobiilit (951-875-022-X)
 
849493 Pohjonen: Allmogens skatter (952-90-9040-4)
 
624431 Lepäsmaa: Suomen kielen alkeisoppikirja (9789517920346)

**Comment by AnneliO** [comment]
Kaivelin vähän valumistietoja Tietuesiirtäjästä näille:


> 211788 Derbyshire: Alkulukujen lumoissa (9525202755) • kirja on lainattu viimeksi vuonna 2019

Valunut 4.7.2024 16:06:04, Aktivointiaika 17.4.2024 22:18:52, Aktivointiarvo (FI-MELINDA)2466817

> 871076 Puonti: Suhteesta siunaukseen (978-951-619-523-3) • kirja on lainattu viimeksi vuonna 2018

Valunut 17.7.2024 9:46:04, Aktivointiaika 17.4.2024 23:35:53, Aktivointiarvo (FI-MELINDA)005692102


> 220632 Roope Ankka ja automobiilit (951-875-022-X)

Valunut 15.7.2024 15:56:04, Aktivointiaika 17.4.2024 22:19:37, Aktivointiarvo (FI-MELINDA)007092988

> 849493 Pohjonen: Allmogens skatter (952-90-9040-4)

Valunut 16.7.2024 13:36:04, Aktivointiaika 17.4.2024 23:33:20, Aktivointiarvo (FI-MELINDA)002600840

> 624431 Lepäsmaa: Suomen kielen alkeisoppikirja (9789517920346)

Valunut 16.7.2024 13:45:06, Aktivointiaika 17.4.2024 23:05:34, Aktivointiarvo (FI-MELINDA)004716228

Mistään näistä ei ole valutusta estetty.

**Comment by VaisanRo** [comment]
Itsellä ei ole valitettavasti vielä kovin syvällistä ymmärrystä kuvailusta, mutta nämä johtuivat siis ilmeisesti meidän omasta virheestämme. Onko jossain ohjeistettu miten valutuksen saa estettyä?

**Comment by AnneliO** [comment]
Lumme siirtyi käyttämään uutta Tietuesiirtäjää noihin aikoihin. Johanna kertoi kyllä ottaneensa vanhoja valutusestoja mukaan vanhasta valutustavasta, mutta voi olla, että kaikki ei sitten ole siirtynyt.

**Comment by VaisanRo** [comment]
Okei, Mitenhän tämän saisi selvitettyä, että miksi vanhojen tietueiden päälle valuu luettelointitietueita Tätistä. Ensimmäisen kerran sain näistä kuvailijoilta tietoa toukokuun lopulla, josta silloin keskustelimme ja poistin silloin kyytiltä kytköksen Kohan MARC-määrityksissä biblioitems.totalissues -> 942$0-kenttään korjausehdotuksena ongelmalle. Tämä ei kuitenkaan ole korjannut ongelmaa ainakaan kokonaan, kun viime viikolla tosiaan oli tullut nuo uudet tapaukset. Tähän olisi kyllä hyvä löytää joku ratkaisu, meillä tulee kuvailijoille ylimääräistä työtä kun osaan niteistä pitää näiden vuoksi tulostaa uudet tarrat.

**Comment by AnttHeik** [comment]
Hei, kommentoin tästä välistä, että puhutko Anneli nyt valutuksenestosta, joka näkyy tietueen 942b-kentässä vai jostain muusta?

Tässä pitää huomioida nimittäin se, että kun valutus otettiin käyttöön, niin jokaisessa kimpassa päätettiin aikaraja, josta vanhempien tietueiden päälle ei saisi valua mitään ja jonka jälkeen tulleiden tietueiden päälle saisi valua. Tätä estoa ei pysty näkemään tietueista, vaan se on jokin Johannan tekemä erityissäätö. Tässä tapauksessa tietueen muokkaus paikalliskannassa saattaa tosin vaikuttaa siihen, että vanhempikin tietue aktivoituu uudestaan valutukseen. 942b-kenttään laitettava valutuksen esto tehdään käsin tietueisiin, jos sen haluaa laittaa johonkin tiettyyn tietueeseen päälle.

Kun katsoo noita Kyytin tietueiden aktivointiaikoja (17.4.2024), niin näyttää siltä, että tietueet ovat aktivoituneet ehkä vasta silloin (tod. näk, kun uusi tietuesiirtäjä otettiin siellä käyttöön), ja nyt kun sen jälkeen joku on tuonut kyseiset nimekkeet Melindasta TäTiin, niin tietueet ovat valuneet myös Kyytiin ja tällöin niiden aktivointiarvot ovat vaihtuneet 035a-kentän Melinda-ID:eihin. Tämän voi tarkistaa siten, että hakee tietuesiirtäjässä jonkin tietueen paikalliskannan biblionumberilla ja vertaa tietueita toisiinsa. Tästä on helppo nähdä oliko aiempi paikalliskannan tietue jo Melindan vai ei. Esim. OUTIssa valui meillekin tämä nyt 3.7. : "Puonti: Suhteesta siunaukseen (978-951-619-523-3)"

![kuva](https://github.com/user-attachments/assets/d7d346fe-51af-4e62-aeaf-621a302787d1)

Aktivointiarvo on 6.2., mutta tietueella nyt Melindan ID:

![kuva](https://github.com/user-attachments/assets/d01737ed-f808-450b-8ecd-9aa0373335d2)

Meilläkin kyseessä on todella vanha tietue, jota tosin on viimeksi lainattu vuonna 2023. Eli tässäkin olisi tavallaan eston pitänyt pysyä, mutta voi olla että 6.2., jolloin suunnilleen tietuesiirtäjä otettiin OUTIssa käyttöön, niin tietue on vasta aktivoitunut. Tätä voi olla todella hankala estää mitenkään kokonaan, mutta itse olen vähän miettinyt sitä, että olisiko mahdollista tehdä tuo valutuksen eston aikarajan asettaminen uudestaan tietueille?

**Comment by AnneliO** [comment]
Hmm.. en ole itekään ihan varma, mistä estoista puhun, mutta ymmärsin, että Johanna yritti saada rajaukset ja estot uuteen liitännäiseen samalla tavalla kuin ne oli ennenkin.

Ja tosiaan, kun tietue on aktivoitunut kertaalleen, niin sen jälkeen siihen valuu kuvailutiedot, jos niihin on tullut Tätissä/Melindassa muutoksia. Siinä vaiheessa, kun tietue on aktivoitu, niin siihen ei enää siinä vaiheessa vaikuta lainaamiset paikalliskannassa yms. Jos tietue on syystä tai toisesta aktivoitu, voi valutuksen estää vain tuolla 942b-kentän arvolla. Tai näin olen ymmärtänyt. Joku voi tarkentaa tai korjata, jos olen ihan hakoteillä. :D

@johannaraisa osaatko kommentoida tuohon Antin kysymykseen valutuksen eston aikarajan asettamisesta uudestaan?

**Comment by johannaraisa** [comment]
Tein niitä estoja työkalun vaihdon yhteydessä. Katsoin sen vanhan estopäivän ja lisäsin eston uuteen aktivointitauluun sen perusteella. Sitä estoa voi hallita 942b-kentän tai sitten suoraan siellä Tietuesiirtäjässä, "Tarkista aktivointiarvo"-osiossa. Se aktivointitaulussa oleva arvo on hallitsevampi, esim. jos aktivointitauluun on lisätty esto ja tietueesta se jostain syystä puuttuu, niin valutus käyttää sitä taulussa olevaa arvoa.

Tietenkin tässä on voinut käydä niin, että ne tietueet ovat eläneet Mikropalvelun ja Tietuesiirtäjän välisenä aikana. Pitäisi varmaan verrata Mikropalvelun aktivointitaulua ja Tietuesiirtäjän taulua keskenään.

**Comment by AnttHeik** [comment]
Jeps, ja lisäksi muistaakseni kun OUTiin vaihdettiin tietuesiirtäjä ja tietueita aktivoitiin uudestaan, niin joukkoon tuli tietueita, jotka eivät olleet aikoinaan tarttuneet ns. haaviin, kun tietueet ensimmäisen kerran aktivoitiin. Tätä ainakin pohdittiin syyksi silloin kun ihmeteltiin muutamia OUTIn vanhojen tietueiden päälle valumisia tän vuoden alussa.

(Sivuhuomautuksena muuten, että tämä Kyytin asia ei liity tiketin alkuperäiseen otsikkoon/aiheeseen, koska tässä tapauksessa uudempi tietue TäTissä on valunut vanhan tietueen päälle Kyytissä eikä niin kuin tässä tiketissä alun perin puhutaan eli uudemman paikallliskannan tietueen päälle valui TäTistä vanhempi tietue. Periaatteessa kyseessä on ihan normaali tilanne, paitsi että Kyytin tietueet olivat ajalta ennen valutusta ja niihin ei olisi saanut valua mitään päälle, mutta jostain syystä valui, eli ehkä tietueet olivat aktivoituneet valutukseen tuolloin huhtikuussa.)

**Comment by VaisanRo** [comment]
![tietuesiirtäjä](https://github.com/user-attachments/assets/c73a9db2-3fc2-4218-9494-835ee26ab6fa)

Kävin läpi nuo Kyytin kaikki tietueet ja niissä oli kaikissa aiemmin 003 kentässä FI-Kyyti ja aktivointiarvo oli nyt vaihtunut jokaisessa Melinda-ID:ksi. Eli ehkä näissä meidän omissa voisi nimenomaan olla kyse sitten tuosta, että tietueet ovat aktivoituneet, kun Kyytissä otettiin tietuesiirtäjä käyttöön ja nyt ovat sitten valuneet sen seurauksena, että joku on tuonut nimekkeet Melindasta TäTiin. 
Ei näille sitten ehkä mitään mahda ja sinällään kyllä ihan hyvä saada täydellisemmät kuvailut käyttöön. Pitää tiedottaa kuvailijoille, että jos ehdottomasti haluaa jollain tietueella estää valutuksen niin lisää sitten 942b-kenttään eston, tai tietuesiirtäjän "Tarkista aktivointi"-osiossa laittaa sen päälle. Kiitos kaikille pohdinta avusta. Ja pahoittelut, näköjään tosiaan loman jälkeen tuli alkuperäinen tiketin sisältö sisäistettyä vähän väärin.

**Comment by johannaraisa** [comment]
RDA-konversio voidaan aloittaa lähiaikoina, joten nämä pitäisi hoitaa korkealla prioriteetilla kuntoon. @paxed palaa ensi viikolla lomalta, hän oli työstänyt skriptiä tätä varten, joten odotetaan siihen asti.
