### ISSUE TITLE
Lisätään puuttuvat hankintahinnat kuluvan vuoden osalta

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1302]
### Tukipyyntö

Kantoihin on syntynyt iso määrä hankintahinnattomia niteitä. Kuluvana vuonna (2024) hankituille niteille tulisi lisätä hankintahinta. Aikakausilehdille tai tilattu-tilaisille hintaa ei lisätä. Hankintahinnan puuttuminen vääristää OKM-tilastoja.

Lisättävä hinta voisi olla:
- Niteen korvaushinta
- Niteellä aikaisemmin ollut hinta
- Saman tietueen muiden niteiden hankintahinta

**Comment by emta001** [comment]
Tutkin tätä hieman. Vaskissa on 1621 kappaletta vuonna 2024 hankittuja niteitä  yllä olevilla kriteereillä, joilla ei ole hankintahintaa:

`SELECT COUNT(*) FROM items i LEFT JOIN biblioitems bi ON(i.biblionumber = bi.biblionumber) WHERE i.dateaccessioned BETWEEN "2024-01-01 00:00:00" AND "2024-12-31 23:59:59" AND i.price IS NULL AND i.notforloan != "-1" AND bi.itemtype != "ALEHTI";`

Näistä 346 niteellä ei ole myöskään korvaushintaa. En oo ihan varma onnistuuko esim. niteen aiemman hinnan etsiminen ihan pelkällä SQL:llä, voi olla että tarvitaan skripti.

Koskeeko tämä myös niteitä, joiden hankintahinta on 0.00 tms.?

**Comment by MikkoLiimatainen** [comment]
Suuri osa näistä niteistä, joille hankintahinnaksi on laitettu 0.00€, ovat lahjoituksia tai muita erikoistapauksia, joten niiden hankintahintoja ei tarvitse muuttaa.

Tein viime viikolla SQL-kyselyn, jolla kaivoin korvaus- ja hankintahintoja lokeista niteille, joilla ei ole hankinta- eikä korvaushintaa, enkä löytänyt kuin kaksi nidettä, joille lokista löytyi tieto puuttuvasta hinnasta. Haun tein tällaisella koodilla:
```
SELECT i.itemnumber,
  i.price,
  i.replacementprice,
  al.info,
  IF(LOCATE("'price'", al.info) = 0, '', REGEXP_SUBSTR(SUBSTRING_INDEX(SUBSTRING(al.info, LOCATE("'price'", al.info)+10, 8), ',', 1), '[0-9.]+')) AS 'hinta',
  IF(LOCATE("'replacementprice'", al.info) = 0, '', REGEXP_SUBSTR(SUBSTRING_INDEX(SUBSTRING(al.info, LOCATE("'replacementprice'", al.info)+21, 8), ',', 1), '[0-9.]+')) AS 'korvaushinta'
FROM items i 
LEFT JOIN biblioitems bi ON bi.biblioitemnumber = i.biblioitemnumber
LEFT JOIN action_logs al ON al.module = 'CATALOGUING' AND al.action = 'MODIFY' AND al.object = i.itemnumber 
WHERE IFNULL(i.price, '') = ''
  AND IFNULL(i.replacementprice, '') = ''
  AND i.dateaccessioned LIKE '2024%' 
  AND i.notforloan NOT IN ('-1')
  AND bi.itemtype NOT IN ('ALEHTI')
``` 

Kävin raportilla läpi vanhemmatkin lokit, mutta tuon enempää hintoja en niteille löytänyt. Ellei ole jotain parempaa ajatusta vanhojen hintatietojen selvittämiseksi, niin nämä pari tapausta voidaan hoitaa käsin.

**Comment by emta001** [comment]
Näitä vanhoja hankintahintoja vois tietty yrittää löytää myös aqorders-taulusta.

**Comment by emta001** [comment]
> Näitä vanhoja hankintahintoja vois tietty yrittää löytää myös aqorders-taulusta.

Eipä taida auttaa, näiltä niteiltä näyttäs systemaattisesti puuttuvan merkinnät aqorders_items-taulusta.

**Comment by PiaKusmin** [comment]
Katsoin tuolla Mikon tekemällä raportilla Lapin kannasta ja meillä tuli huimat 3847 nidettä ilman hintatietoa. Mutta kun tarkastelin niteitä niin ne ovat Celia-aineistoa, koulujen tai museoiden kokoelmiin lisättyä aineistoa tai lahjoituksia, jotka on lisätty kantaan vain "lisää nide" toimintoa käyttämällä (ei hankinnan kautta). Eli millekään näistä aineistosta ei tarvitse laittaa hintaa.

Mutta jäin miettimään, että mihin hintatiedon puuttuminen vaikutta OKM tilastoissa? Ainoastaan Hankinta(kulut) yhteensä ja Kirjojen hankinta(kulut) -kohtiin?

**Comment by ReettaSiili** [comment]
Pikainen kommentti Siilistä ilman hyvin tarkkaa perehtymistä asiaan: meillä ei ole tarvetta korjauksille. Hinnat on riittävän tarkalla tasolla ja meillä okm-tilastoihin eurot taidetaan katsoa kunnan kirjanpitojärjestelmästä. Kohan luvut ovat meillä suuntaa-antavassa tarkkailussa vain.

**Comment by ajrajala** [comment]
Päivityksenä tähän tikettiin: Vaskille riittäisi siis ajo, jossa vuonna 2024 hankituille, kokonaan ilman hankintahintaa oleville niteille kopioitaisiin hinta korvaushinta-kentästä. Jos niteen tiedoissa ei ole korvaushintaa, hankintahintaa ei tarvitse yrittää korjata.

Niteet, joilla hankintahinta on 0,00€, jätetään koskematta, niissä hinta on tarkoituksella nolla euroa.

**Comment by pknuuti** [comment]
> Sopisiko muillekin kimpoille, että hinta kopioitaisiin korvaushinta-kentästä ja korvaushinnattomat niteet jätetään korjaamatta?

Kuulostaa järkevälle, Vaaralle käy niin.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä ei ole tarvetta ajolle. Meiltä löytyi vain parikymmentä nidettä, joissa oli korvaushinta muttei hankintahintaa ja suurin osa niistäkin oli lahjoituksia. Jossain on ilmeisesti tapana merkitä lahjoituksille korvaushinta eivätkä nämä saa siirtyä hankintahinnoiksi.

**Comment by PiaKusmin** [comment]
Lapissa ei ole tarvetta ajolle.

**Comment by piiaseme** [comment]
OUTIssa ei ole tarvetta ajolle.

**Comment by Hanna-Lumme** [comment]
Lumpeissa ei ole tarvetta ajolle.

**Comment by emta001** [comment]
Testailin tätä vaski-nextillä. Keräsin kaikki muuttuvat niteet aputauluun `ks_20240910_items_1302` ja ajoin seuraavan rimpsun kantaan:

`UPDATE items i LEFT JOIN biblioitems bi ON(i.biblionumber = bi.biblionumber) SET i.price = i.replacementprice WHERE i.dateaccessioned BETWEEN "2024-01-01 00:00:00" AND "2024-12-31 23:59:59" AND i.price IS NULL AND i.replacementprice IS NOT NULL AND i.notforloan != "-1" AND bi.itemtype != "ALEHTI";`

Vaikuttaisi toimivan kuten pitääkin, vaskilaiset voi halutessaan tarkistaa vielä näyttääkö oikeelle. Tehdään ajot jossain vaiheessa myös tuotantoihin.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextiltä löytyy tuota ajoa vastaavilla määrityksillä 1173 hankintahinnatonta nidettä, eli joiden olisi pitänyt kaiketi korjaantua ajolla. En myöskään löytänyt tuota aputaulua. Onkohan tämä ajettu kuitenkin testille? En pystynyt vielä tarkistamaan sen tilannetta.

**Comment by emta001** [comment]
No testillähän ne ja testit on vielä alhaalla.

**Comment by emta001** [comment]
> Vaski-nextiltä löytyy tuota ajoa vastaavilla määrityksillä 1173 hankintahinnatonta nidettä, eli joiden olisi pitänyt kaiketi korjaantua ajolla. En myöskään löytänyt tuota aputaulua. Onkohan tämä ajettu kuitenkin testille? En pystynyt vielä tarkistamaan sen tilannetta.

Nyt voi testailla, testit pelittää taas.

**Comment by MikkoLiimatainen** [comment]
No niin, nyt näyttää siltä, että korjaus on purrut ja minusta tuo on ok.

**Comment by Kati-Helle** [comment]
Hellessä ei tarvetta korjausajolle.

**Comment by helasann** [comment]
Kirkesissä ei ole tarvetta ajolle.

**Comment by emta001** [comment]
Ajo tehty sekä Vaaralle että Vaskille. Muuttuneet niteet löytyvät aputaulusta `ks_20241002_items_1302`.

**Comment by iinaniemi** [comment]
Vaskilla ajo näyttää toimineen oikein.
