### ISSUE TITLE
Ongelmia viestien kanssa

### ISSUE THREAD

**Issue by LottaJuvonenHelle** [KohaSuomi/Koha#1303]
### Tukipyyntö

Hei! 

Tänään tuli ilmi että Hellessä pari asiakasta ovat saanet eräpäivän muistutusviestin vaikka eräpäivää ei olisi lähellä. Esimerkiksi asiakas 638A0148610 oli ongelmia viestin kanssa.

Eräpäivämuistutuksia on hänelle tullut vaikkea ei ollut mitään erääntymässä eikä noudettavasta varauksesta ollut tullut mitään viesti tekstiviestinä. 

Toinen vastaava tapaus oli meillä eilen. Sekin asiakas oli saanut eräpäivämuistuksia vaikka ei ole lainannut mitään kirjastolta moneen vuoteen. En vielä tiedä onko meillä hänen kirjastokortin tietoja.

Onko mitään tietoa mistä tämä voisi johtua?

yt,  Lotta, Helle

**Comment by lmstrand** [comment]
Huomasin myös, että asiakkailla on sama sähköpostiosoite.

**Comment by LottaJuvonenHelle** [comment]
Kiitos selvästä vastauksesta! Tarkistetaan ja päivittetään oikeat tiedot molemille asiakkaille.
