### ISSUE TITLE
Lumme: kaikkien lehtien varaus ei onnistu

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#1306]
### Mikä vikana?

Lumpeissa esimerkiksi uusimpien Kodin kuvalehtien varaus ei onnistu. Varaustilanteessa tulee virhe 500. Joidenkin vanhempien vuosikertojen KK-lehtien varaus oli myös hidasta mutta mene läpi. Sitten taas toiset lehdet onnistuvat moitteetta. Voiko tietueessa olla jotain ongelmaa, vai mistähän tätä alkaisi selvittää. Emon niteisiin on kuitenkin saatu jossain vaiheessa tehtyä varauksia, tämä ongelma huomattiin Varkaudessa perjantaina.

**Comment by emta001** [comment]
Tarkistakaa niteiden nidetyyppi, onhan ne olemassa olevia ja muuten virheettömiä. Lokille tulee tämmöstä virhettä:

`Can't call method "notforloan" on an undefined value at /home/koha/Koha/C4/Reserves.pm line 1382.`

Joka viittaa Kohan koodissa kohtaan:

`my $notforloan_per_itemtype = Koha::ItemTypes->find($itemtype)->notforloan;`

**Comment by emta001** [comment]
Tarkistin Lumpeista nuo olemattomat nidetyypit, löysin kolme nidettä:

74020240300269
4620240600029
915N03405203

Tuo toisena oleva on Kodin kuvalehti 2024 : 1-13. Eka on joku vanha Protocall teknikbiten ja kolmas Kotiliesi / 2024 : 1-13.

**Comment by Katja-Lumme** [comment]
Hienoa, kiitos kun selvittelit! Suljen tiketin.
