### ISSUE TITLE
Vaski: Ilpoisten kirjastoautopysäkin varausten siirto

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1307]
### Tukipyyntö

Ilpoisten tilapäisen kirjastoautopysäkin tärppäämättömät varaukset täytyisi siirtää Ilpoisten kirjastoon.
Eli näille varauksille muutetaan noutopaikaksi TUIL:
```
SELECT r.reserve_id
FROM reserves r 
WHERE r.branchcode = 'TUA4'
  AND found IS NULL
```

**Comment by lasse-koha** [comment]
Noutopaikka muutettu.

**Comment by MikkoLiimatainen** [comment]
Asia näyttäisi olevan kunnossa. Kiitos!
