### ISSUE TITLE
Asiakkaan lainarajoituksen ohittaminen ei onnistu (jos liikaa maksuja)

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#1308]
### Mikä vikana?

![image](https://github.com/KohaSuomi/Koha/assets/98803917/4ec5ba01-c6fc-45f7-92c1-c7bf0e6f8289)

Lainaus ei aktivoidu, vaikka painaa Ohita rajoitus tilapäisesti- namiskaa. Ei tapahdu mitään, itseasiassa.

**Comment by lmstrand** [comment]
Päivitin testille circulation.pl-tiedostoon muutokset, jotka ovat mukana 24.05-versiossa ja lainarajoituksen ohitus toimi. En tiedä, mikä yksittäinen commit korjasi ongelman, enkä löydä tikettiä bugzillasta koskien tätä ongelmaa.

**Comment by lmstrand** [comment]
(Tiedosto palautettu takaisin alkuperäiseksi, ja ongelma on palannut.)

**Comment by lmstrand** [comment]
Ongelmaan löytyi korjaus bugzillatiketistä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35518. Vien korjauksen testeille.

**Comment by lmstrand** [comment]
Korjaus viety testeille.

**Comment by MikkoLiimatainen** [comment]
Testasin Vaski-testillä ja korjaus näyttäisi toimivan.

Tuossa bugzillan-tiketissä mainittiin toinen ongelma, jonka tämä korjaus aiheuttaa ja joka korjataan tiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36139.

Tämä ongelma vaatii, että AutoSwitchPatron-asetus on Salli, jolloin lainauksen viivakoodikenttään lukemalla asiakkaan kirjastokortin siirrytään toisen asiakkaan tietoihin. Testillä siirtyminen tapahtuu, mutta Koha herjaa myös, että viivakoodia ei löytynyt, mikä käsittääkseni on tuon toisen tiketin kuvaama ongelma. Vaskissa tämä asetus ei ole käytössä, joten sinällään korjaus vaikuttaa meidän näkökulmastamme tarpeettomalta ja nähdäkseni tulee joka tapauksessa mukaan seuraavassa versiossa. Tämä lähinnä tiedoksi, jos korjaus on tarpeen ottaa mukaan jo nyt.

**Comment by lmstrand** [comment]
Tuodaan Mikon mainitsema korjaus mukaan bz-tiketistä 36139 samaan feature branchiin ksdev/ks-0163-G1308-fix-bypass-checkout-restriction (AutoSwitchPatron käytössä kimpoissa helle, kyyti ja lumme).

**Comment by lmstrand** [comment]
AutoSwitchPatron-korjaus viety testeille.

**Comment by pknuuti** [comment]
Vaarassa on havaittu sama ongelma lainauskieltoon vaikuttavien maksujen ohittamisen kohdalla. Tuotannossa ei toimi (Ohita rajoitus tilapäisesti) ohittaminen, mutta Vaaran testillä toimii, joten korjaus on ilmeisesti toimiva.

**Comment by lmstrand** [comment]
Tämä ilmeisesti ok, suljen tiketin.
