### ISSUE TITLE
Asiakkaille lähtenyt englanninkielisiä noutoilmoitusten koosteviestejä (asiakas lisännyt itselleen täpän Finnassa)

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1309]
### Tukipyyntö

Vaarassa ilmeni, että joillain asiakkailla on päällä noutoilmoitusten koostetoiminto, vaikka meillä ei ole sitä käytössä - ei sähköpostissa eikä tekstiviestissä. 

Tämä johtuu siitä, että Finnassa viestiasetuksissa on valittavana myös kooste, vaikka sen pitäisi olla piilotettuna. Meiltä ei Päivin loman vuoksi kukaan pysty piilottamaan valintakohtaa ennen ensi viikon maanantaita.

![image](https://github.com/KohaSuomi/Koha/assets/99409279/2e75ef5a-de11-43c6-8248-b64d307a14bb)

Valinnan tehneille on asiakkaille on lähtenyt noutoilmoituksia englanniksi (myös tekstiviestitse), sillä HOLDDGST-pohjassa suomi, englanti ja ruotsi ovat tyhjänä, joten toiminto on käyttänyt englanninkielistä oletuspohjaa. 

Pystymmekö saamaan jotenkin kiinni ne asiakkaat, joilla on tuo noutoilmoitusten kooste käytössä ja poistamaan sen heiltä käytöstä?

**Comment by lmstrand** [comment]
Näitä saa kiinni raportilla:

select b.borrowernumber, bmp.*, ma.message_name from borrowers b
left join borrower_message_preferences bmp on bmp.borrowernumber = b.borrowernumber
left join borrower_message_transport_preferences bmtp on bmtp.borrower_message_preference_id = bmp.borrower_message_preference_id
left join message_attributes ma on bmp.message_attribute_id = ma.message_attribute_id
where
bmp.message_attribute_id = 4
and wants_digest = 1

**Comment by MikkoLiimatainen** [comment]
Vaskissa on tiedoston /themes/custom/templates/myresearch/change-messaging-settings-driver.phtml loppuun laitettu piilotuksia näille viestiasetuksille.

```
<script nonce="<?=$this->cspNonce()?>">
    $("input#Hold_Reminder_transport_types_sms").parent().parent().css("display", "none");
    $("input[name='Advance_Notice_digest']").prop("checked", true).parent().parent().parent().css("display", "none");
    $("input[name='Item_Due_digest']").prop("checked", true).parent().parent().parent().css("display", "none");
    $("input[name='Hold_Filled_digest']").prop("checked", false).prop("disabled", "disabled").parent().parent().parent().css("display", "none");
  </script>
``` 
Hold_Filled_digest rivi piilottaa noutoilmoituksen koosteviestin otsikoineen.

**Comment by pirliis** [comment]
> Näitä saa kiinni raportilla:
> 
> select distinct b.borrowernumber, bmp.*, ma.message_name from borrowers b left join borrower_message_preferences bmp on bmp.borrowernumber = b.borrowernumber left join borrower_message_transport_preferences bmtp on bmtp.borrower_message_preference_id = bmp.borrower_message_preference_id left join message_attributes ma on bmp.message_attribute_id = ma.message_attribute_id where bmp.message_attribute_id = 4 and wants_digest = 1

OUTIsta löytyi yksi asiakas.

**Comment by IrinaHalminen** [comment]
Kiitos! Minä muokkailen tänään täpät pois niiltä asiakkailta, jotka olivat ne ehtineet laitella (ei onneksi ollut montaa). Meillä ei tosiaan muut kuin Päivi pääse Finnaan tekemään noita muutoksia, joten täytyy odotella ensi viikkoon.

**Comment by PiaKusmin** [comment]
Kiitos! Lappi tarkistettu (9 kpl) ja korjattu. Ja Finnaan tehty piilotukset.

**Comment by Kati-Helle** [comment]
Hellessä koosteviesti-täpällisiä asiakastietoja löytyi kaksi. Kooste-täpät on nyt poistettu.

**Comment by Katja-Lumme** [comment]
Lumpeilla tän oli ehtinyt täppäillä jo 48 asiakasta, JA @MikkoLiimatainen : mitä teillä on muuta tässä tiedostossa /themes/custom/templates/myresearch/change-messaging-settings-driver.phtml ? Koska meillä sellaista tiedostoa myresearch-kansiossa ei ole ollenkaan🙈, joten en osannut korjata Finnan puolella asiaa...

**Comment by MikkoLiimatainen** [comment]
> Lumpeilla tän oli ehtinyt täppäillä jo 48 asiakasta, JA @MikkoLiimatainen : mitä teillä on muuta tässä tiedostossa /themes/custom/templates/myresearch/change-messaging-settings-driver.phtml ? Koska meillä sellaista tiedostoa myresearch-kansiossa ei ole ollenkaan🙈, joten en osannut korjata Finnan puolella asiaa...

Tuo tiedosto on kopio tiedostosta /themes/finna2/templates/myresearch/change-messaging-settings-driver.phtml. Kun tämän kopioi tuohon /themes/custom/templates/myresearch/-kansioon, niin tiedostoa pystyy muokkaamaan ja silloin se ohittaa Finnan oman tiedoston.

**Comment by Katja-Lumme** [comment]
Kiitos @MikkoLiimatainen 🤩. Lumme-Finna nyt korjattu myös.

**Comment by IrinaHalminen** [comment]
Hyvä, että kyselystä oli muillekin hyötyä. Suljen tiketin tältä erää. :)
