### ISSUE TITLE
Viinijärven kirjaston varausten jäädytys

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1314]
### Tukipyyntö

Viinijärven kirjasto menee väistötiloihin remontin takia. Muutto tapahtuu elokuussa. Varaukset, joiden noutokirjasto on Viinijärven kirjasto JOE_VII, jäädytetään ajalle 1.8.-1.9.

Jäädytys tehtävä 1.8.2024 voimassa oleville varauksille, joiden noutokirjasto on JOE_VII. Näiden varausten jäädytys poistetaan 1.9.2024. Muissa tiloissa oleville Viinijärven varauksille ei tehdä mitään.

**Comment by paxed** [comment]
Tehty tällä rimpsulla:
`update reserves set suspend=1, suspend_until='2024-09-01' where branchcode = 'JOE_VII' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-08-01' AND '2024-09-01'));`

Koski 292 varausta.

**Comment by pknuuti** [comment]
Kiitos! Teenkö uuden tiketin varausten voimaantuloon vai meneekö näillä tiedoilla?

**Comment by paxed** [comment]
> Kiitos! Teenkö uuden tiketin varausten voimaantuloon vai meneekö näillä tiedoilla?

Laitoin tän tiksun odottaa tilaan, ja vaihdoin eräpäivän tuohon millon tarvitsee tehdä muutos, niin mennään tällä samalla tiketillä.

**Comment by paxed** [comment]
... Paitsi että kun tuo suspend_until on asetettu, niin ne jatkuu automaattisesti tuollon ilman että tarvitsee tehdä mitään.

**Comment by pknuuti** [comment]
Hienoa, kiitos.

**Comment by johannaraisa** [comment]
Tähän on muutettu vain tila, suljen.
