### ISSUE TITLE
Hyllyvarausraportille rivien oletusmäärät valittavaksi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1317]
### Kehitysehdotukseni

Olisiko iso työ saada Koha-Suomen hyllyvarausraportille samanlaista rivien oletusmääräävalintaa, kuin on kv-version raportille taulujen asetuksissa. Nyt oletuksena on aina 20, jonka työntekijä joutuu joka kerta vaihtamaan, kun sivu ladataan uudestaan.
![image](https://github.com/user-attachments/assets/45a4d816-38b1-42a2-9f17-c177203e2b60)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.8.2024: Toteutetaan.

**Comment by lmstrand** [comment]
Tämä on viety testeille ja nexteille testattavaksi.

**Comment by lmstrand** [comment]
Ei ole vielä nexteillä.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä. Valitsin kaikki näytettäväksi oletuksena. Testilistalla oli 97 varausta, kaikki näkyivät kerralla. Kätevää, kiitos!

**Comment by lmstrand** [comment]
Nyt pitäisi olla nexteilläkin. Mukana on myös tuo oletuslajittelu uutena muutoksena (vaikkakin tuo oletusvalinta on varmaan se ainut järkevä ja käytännöllinen).

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä. Siellä hyllyvarauksia oli 117, kaikki-valinnalla kaikki näkyivät kerralla. Jäin miettimään tuota lajittelua, mikä siinä olisi järkevää. Taidan kysellä käyttäjiltä, miten lajittevat ja kokeilla sen mukaan.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii. Kaikki tämän hetken 71 hyllyvarausta näkyvillä toiminnon avatessa.

**Comment by pirliis** [comment]
OUTIn testillä ja nextillä rivien oletusmäärävalinnat toimivat.

**Comment by lmstrand** [comment]
Kiitos testauksista.

**Comment by pirliis** [comment]
Tuotantoon 17.9.2024. Suljen tiketin.
