### ISSUE TITLE
Vaski: KALI-yksikön varausten keskeytys

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1318]
### Tukipyyntö

Keskeytetään määräajaksi Littoisten kirjaston tärppäämättömät ja keskeyttämättömät tai kirjaston sulkuaikana aktivoituvat varaukset.

Kirjasto KALI
Vain tärppäämättömät varaukset
Vain keskeyttämättömät ja keskeytyksen aikana aktivoituvat varaukset
Keskeytys tehdään 18.7.2024
Keskeytys päättyy 16.9.2024

```
SELECT reserve_id
FROM reserves
WHERE branchcode = 'KALI'
  AND found IS NULL
  AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-07-18' AND '2024-09-15'))
```

**Comment by emta001** [comment]
Varaukset otettu ylös aputauluun ja keskeytetty sitten ne jotka eivät olleet jo kesken.

`CREATE TABLE ks_20240718_reserves_1318 SELECT * FROM reserves WHERE branchcode = 'KALI' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-07-18' AND '2024-09-15'));`

`UPDATE reserves SET suspend = 1 WHERE branchcode = 'KALI' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-07-18' AND '2024-09-15'));`

Yhteensä varauksia löytyi 752 ja tuo muutos koski niistä 745 kappaletta. Ihan nyt varmistan, että siirretäänkö noiden 7 jäljelle jääneen varaukset suspend_until-arvoa 16.9.2024 asti vai vielä myöhäisemmäksi?

**Comment by MikkoLiimatainen** [comment]
Minusta asia näyttää nyt olevan kunnossa. Jos en nyt ihan väärin asiaa katso, niin noiden seitsemän varauksen keskeytyspäivämäärät ovat jo pidemmällä kuin varauksille nyt asetetut, joten niihin ei haluta koskea. Suljen tiketin. Kiitos!

**Comment by MikkoLiimatainen** [comment]
Voisiko tämän tehdä samoilla spekseillä uudelleen? Varauksia on menty aktivoimaan ja vaikka niitä ei paljoa ole, niin turhaan ovat aktiivisina.

**Comment by emta001** [comment]
Tehty uudestaan, löytyvät aputaulusta `ks_20240726_reserves_1318`. Muutos koski 36 varausta.

**Comment by MikkoLiimatainen** [comment]
Kiitos!
