### ISSUE TITLE
Lumme: vanhojen lehtitilausten sulku

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1323]
### Tukipyyntö

Lumpeissa voisi sulkea kaikki vanhat lehtitilaukset, jotka päättyivät vuonna 2023. 

Kiitos!

**Comment by emta001** [comment]
Tilaukset suljettu. Sulku koski 138 tilausta.

`UPDATE subscription SET closed='1' WHERE enddate LIKE '2023%';`
