### ISSUE TITLE
Helle: IntranetUserJS-rimpsun poisto

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1325]
### Tukipyyntö

Poistatteko Helle-Kohasta IntranetUserJS-rimpsun:
Laita Muutospyynnöt-sivulla oletuksena valinta Hyväksy-kohtaan

**Comment by emta001** [comment]
Teen tän huomenaamulla ennen kuin kirjastot aukeaa.

**Comment by pirliis** [comment]
Testasimme OUTIssa myös Tietojensa muokkaamista haluavat asiakkaat -toimintoa. OK-painike tosiaan hyväksyy kaikkien asiakkaiden muutokset kerralla, kun Hyväksy-painike on oletuksena. 

OUTIsta saa poistaa myös JS-rimpsun.

**Comment by emta001** [comment]
Rimpsu poistettu Hellestä ja OUTIsta.

**Comment by Kati-Helle** [comment]
Kiitti Emmi!

**Comment by Kati-Helle** [comment]
Suljen tiketin.
