### ISSUE TITLE
Mobiilikirjautuminen automaateille hyväksymään myös pienet aakkoset

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha#1326]
### Kehitysehdotukseni

Asiakkaiden ja virkailijoidenkin parissa välillä aiheuttaa hämmennystä, kun mobiilikirjautuminen automaatille (QR-koodin kautta) ei hyväksy kirjautumistunnusta vaan antaa ohessa olevien kuvien kaltaisen virheen, vaikka tunnus on syötetty "oikein" eikä ole vanhentunut, eikä mitään estoja ole päällä. Kyseessä on todennäköisesti ollut tunnuksessa olevien kirjainten kirjoittaminen pienillä kirjaimilla. (Ongelman esiintyminen varmistettiin testaamalla parin virkailijan henkkoht. lainaajatunnuksilla.)

Asiakkaat voivat kirjautua Finnaan pienillä tai isoilla kirjaimilla, joten kirjautumisen logiikka ei ole nyt johdonmukainen. Kirjautumistapahtuman aikana ei myöskään saa minkäänlaista vihjettä siitä, että missä on vika. Ehdottaisin, että kirjainkoolla ei tulisi olla merkitystä mobiilikirjautumisen yhteydessä. OUTIn IT-gurut kertoivat ettei ongelma liity automaatteihin, vaan johtuisi nimenomaan siitä, että Koha on tässä asiassa case sensitive.

### Jotain muuta?

![kirj](https://github.com/user-attachments/assets/f0930032-74bf-41a6-85e4-45da853d5dcf)
![eionnaa](https://github.com/user-attachments/assets/247c89f1-66b1-45a4-bfe0-860a19594d9e)
![autom](https://github.com/user-attachments/assets/5d471169-e7c0-4b6a-9e40-a5ae2bfb709d)

**Comment by johannaraisa** [comment]
Olisiko testausaikoja, luultavasti näkee SIPin lokista mille kirjautumisyritys näyttää?

**Comment by Thoriell** [comment]
Komento takaisin! Testasin tätä juuri Oulussa, ja SIP2-logista bongasin että pientä a-kirjainta käyttäessä AA-kenttä (patron identifier) lähteekin nyt tyhjänä. Hetken pähkittyäni tajusin, että tässä onkin kyse ns. sotuestosta eli meillä on automaatin tasolla rajattu, minkä muotoisia asiakastunnuksia se hyväksyy. Mikäli luettu viivakoodi ei täsmää filtteriin, sitä ei edes kysytä kirjastojärjestelmältä. Ja sieltä on pieni a jossain vaiheessa jäänyt pois:

^\d{3}[A]\d+$|^OUTI\d+$

Tuo tosiaan vaikuttaa myös mobilelogin-palveluun, mikä ei ollut ihan itsestään selvää. Tämä on paitsi Pallas-peruja (hetu oli sellaisenaan asiakastiedoissa), mutta myös siksi ettei asiakkaiden hetuja päätyisi SIP2-logeille sellaisenaan, jos joku yrittää kirjautua automaatille tai omatoimeen esim. ajokortilla tai Kela-kortilla. AA-kenttäähän meillä ei logeilta anonymisoida, koska se on se tärkein millä yleensä saadaan tilanteita tutkittua. Emme siis voi oikeastaan poistaa tuota filtteriä, tai muuten niitä hetuja päätyy logille ihan varmasti.

Lisäksi, kuten huomaatte, meillä on nykyään myös OUTI-alkuisia kortteja. Siinä onkin sitten variaatiota runsaasti napuloida eri muotoja (OUTI, Outi, outi, oUti...). Joten filtteröimme jatkossa näin:

^\d{3}[Aa]\d+$|^[Oo][Uu][Tt][Ii]\d+$

Testasimme tätä testikannassa ja tämä toimii, eli mm. oUTi-versiolla pääsi kirjautumaan. Muutamme tuon tänään Oulun automaateille ja omatoimille.

**Comment by atarnus** [comment]
Tämä toimii, asia kunnossa.
