### ISSUE TITLE
Lajittelu-laatikot piiloon Takaajaa lisättäessä

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha#1330]
### Tukipyyntö

Asiakkaalle takaajaa lisättäessä on haku-popupiin ilmestynyt pari lajittelukenttää, joille ei ole tarvetta.

Ne saa piiloon esim. seuraavalla CSS:llä:

```
/* Lajittelu-kenttien piilotus takaajaa lisättäessä */
body#common_patron_search label[for=sort1_filter],
body#common_patron_search input#sort1_filter,
body#common_patron_search label[for=sort2_filter],
body#common_patron_search input#sort2_filter { display: none; }
```

Nextillä popup on muuttunut modaaliksi, ja on hyvin erilainen. Siellä toimii kuitenkin alustavasti ainakin tämä (joskin tämä taas piilottaa vain lomakkeen 4. ja 5. kentän, joten lomakkeen muuttuessa voi mennä väärä kenttä piiloon): 

```
body#pat_memberentrygen.modal-open form fieldset.brief ol li:nth-child(4),
body#pat_memberentrygen.modal-open form fieldset.brief ol li:nth-child(5) { display: none; }
```

### Jotain muuta?

![image](https://github.com/user-attachments/assets/6902386b-0fd6-430b-96c7-641bbdacf52e)

**Comment by CodoDerDritte** [comment]
Tähän ei tarvita Koha-Suomea, joten muuten labeliksi documentation.

**Comment by AnneliO** [comment]
Dokumentoitu version 24.05 [IntranetUserCSS-wikiin asiakastietojen vapaaehtoisiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#vapaaehtoiset)
