### ISSUE TITLE
Asiakas saa varausilmoitukset englanniksi, vaikka ilmoituskieli on suomi.

### ISSUE THREAD

**Issue by markokosonen** [KohaSuomi/Koha#1331]
### Tukipyyntö

Asiakas saa varausilmoitukset englanniksi, mutta haluaisi saada viestit suomeksi. Tuolla kirjastonhallinnassa ilmoituskielenä on suomi, eikä sitä ole muutettu muuten kun nyt testaillessa. Vaikuttaako ilmoituskieleen joku muukin asia kuin tuo asiakastiedoissa oleva täpy? https://siili.koha-suomi.fi/cgi-bin/koha/members/notices.pl?borrowernumber=39341

### Jotain muuta?

![ilmoitukset](https://github.com/user-attachments/assets/a386efc5-a3e0-4978-b87a-ff4471bca0e7)
![ilmoitukset2](https://github.com/user-attachments/assets/a14ec462-fe1f-4a22-8207-5f0c53eb4b3c)

**Comment by AnneliO** [comment]
Nyt on jännää, koska Siilinjärvellä ei ole englanninkielisiä viestipohjia edes olemassa. Pitääpä ihmetellä vielä lisää.

**Comment by AnneliO** [comment]
No nyt selvis. Asiakkaalla on valittuna kooste-viesti saapumisilmoituksesta ja siihen on oletusviestipohjassa tuo kyseinen viesti, jonka asiakas on saanut.

![kuva](https://github.com/user-attachments/assets/d2d45032-2385-4d3f-afe0-522d7f337015)

Kooste-sarake on piilotettuna IntranetUserCSS:llä, niin se ei äkkiseltään osunut silmään. Otin piilotuksen hetkeksi pois päältä ja poistin asiakkaalta rastin Kooste-kohdasta. Nyt hänelle pitäisi lähteä normaali suomenkielinen saapumisilmoitus-viesti.

Kannattaa ehkä varalta lisätä HOLDDGST-viestipohjaan jatkossa vaikka sama teksti kuin HOLD-viestipohjassa on. Jos vaikka jollekin muullekin onnistutaan lisäämään estoista huolimatta kooste-täppä. :)

**Comment by markokosonen** [comment]
Hieno homma, kiitoksia =D. Myöpä katellaan noita viestipohjia, jospa noita ei enempää olisi.

**Comment by lmstrand** [comment]
Onkohan teilläkin asiakkailla mahdollista muuttaa noita täppiä Finnassa: https://github.com/KohaSuomi/Koha/issues/1309#issuecomment-2208222434

**Comment by AnneliO** [comment]
Jos Marko tämä ongelma on nyt ok, niin tiketin voi sulkea. :)

**Comment by markokosonen** [comment]
Jees, suljetaan pois :)
