### ISSUE TITLE
Tietueiden eräpoiston taustatyö näkyy keskeneräisenä vaikka tietueet on poistettu

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1332]
### Mikä vikana?

Vaskin tuotannossa 22.07.2024 09:37 aloitetun taustatyön [20075576](https://vaski.koha-suomi.fi/cgi-bin/koha/admin/background_jobs.pl?op=view&id=20075576) tilana ei ole valmis eikä työllä ole päättymisajankohtaa. Työn tiedoissa kuitenkin on tieto "Kaikki tietueet on poistettu!" ja ko. työn tietueid:t todella löytyvät deletedbiblio-taulusta. Näyttäisi siis siltä, että taustatyö on valmistunut mutta sille on jäänyt virheellinen tila tietokannassa?

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/6bc39565-1386-4717-9a65-384b299c5842)

**Comment by CodoDerDritte** [comment]
Tässä työn tiedot tietokannassa:

```
MariaDB [vaskiprod]> select id,status,progress,enqueued_on,started_on,ended_on from background_jobs where id=20075576;
+----------+---------+----------+---------------------+---------------------+----------+
| id       | status  | progress | enqueued_on         | started_on          | ended_on |
+----------+---------+----------+---------------------+---------------------+----------+
| 20075576 | started |        0 | 2024-07-22 09:37:07 | 2024-07-22 09:37:58 | NULL     |
+----------+---------+----------+---------------------+---------------------+----------+
```

Työ näyttäisi edelleen olevan started-tilassa eikä sillä ole päättymisaikaa. Merkkaanko päättyneeksi?

**Comment by ajrajala** [comment]
Joo, eiköhän sen voisi merkata. Tarkistin vielä, että noiden tietueiden biblioitemitkin oli siirtyneet deleted-tauluun, joten en keksi että tuossa poistossa olisi jäänyt mitään oikeasti kesken. 🤔

**Comment by CodoDerDritte** [comment]
Mikä lie härö. Nyt se on merkattu päättyneeksi. Laitoin päättymisajaksi tämän hetken.

**Comment by ajrajala** [comment]
Kiitos! Löysin ehkä selityksenkin valmistuneista töistä, siellä oli minuuttia aiemmin aloitettu työ 20075541 jossa samat tietueet. Ehkä käyttäjä on kerennyt aloittaa eräpoiston mutta vahingossa sulkenut välilehden ja vienyt sitten sen takia saman setin eräpoistoon uudelleen. Tai jotain sen suuntaista.
