### ISSUE TITLE
Kirkes: Tuusulan pääkirjaston viimeisten noutopäivien siirto

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1335]
### Tukipyyntö

Tuusulan pääkirjasto joudutaan sulkemaan yllättäen muutamaksi päiväksi, joten pyytäisin siirtämään tiistaille 30.7.2024 ne varausten viimeiset noutopäivät, jotka nyt ovat pe 26.7.2024 ja ma 29.7.2024.

**Comment by paxed** [comment]
Siirretty tällä rimpsulla `update reserves set expirationdate = '2024-07-30' where branchcode = 'TUPK' and found = 'W' and (expirationdate = '2024-07-27' or expirationdate = '2024-07-29');`

Yhteensä 13 kpl.

**Comment by paxed** [comment]
Hups, typo tuossa rimpsussa, tein uuden niin että muutettiin myös tämän päivän varaukset, joita oli 9 kpl.

**Comment by ElinaUotila** [comment]
Kiitos paljon, siirrot näyttävät oikealta.
