### ISSUE TITLE
Tietueen Melinda-tuonnissa syntynyt ongelma

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1336]
### Mikä vikana?

Kuvailija raportoi meille ongelmasta TäTiin priimärikuvaillun tietueen kanssa. Käyttäjä oli luonut tietueen [2469414](https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=2469414) ja huomannut seuraavana päivänä, että tietueelle oli syntynyt tuplatietue [2469424](https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=2469424) TäTiin.

Alkuperäisellä tietueella näkyy 035-kentässä ikään kuin kaksi Melinda-id:tä. Ensimmäisen kenttätoistuman id on kuitenkin TäTi-tietueen id ja jälkimmäinen kenttätoistuma oikea Melinda-id.

![kuva](https://github.com/user-attachments/assets/a82939f1-3ca8-4f17-b69b-3a8505213efc)

Alkuperäisen tietueen muutoslokissa näkyy, että käyttäjä 0 (Koha?) on muokannut tietuetta 25.07.2024 14:35. Samalla minuutilla on muodostunut tuplatietue 2469424. Oletettavasti nämä lokitapahtumat liittyvät tietueen tuontiin Melindasta?

Onko tuossa 035a-kenttien tallentumisessa tapahtunut jotain outoa, kun tuo TäTi-tietueen id näkyy ikään kuin Melinda-id:nä eikä TäTi-id:nä? Ja onko tuo sitten aiheuttanut sen, että TäTiin onkin tallentunut tuonnin yhteydessä tuplatietue?

Voiko tilanteen korjata yksinkertaisesti niin, että tietueen 2469414 ensimmäisessä 035a-toistumassa näkyvän id:n muuttaa muotoon (FI-TATI)2469414 ja tuplatietueen 2469424 poistaa kokonaan?

**Comment by johannaraisa** [comment]
Mietin, että oliko kuvailija laittanut siihen jo primäärissä 003-kenttään FI-MELINDA? Se nimittäin kopsaa sen sinne 035a-kenttään, jos ei ole jo siellä. Tuon kyllä saa korjattua niin, että vaihtaa vaan sen 035a-kentän alun FI-TATI-arvoksi.

**Comment by ajrajala** [comment]
Kuulostaisi kyllä todennäköiseltä selitykseltä. Jos tietueen pohjaksi on ottanut kopion olemassaolevasta tietueesta niin silloin 003-kentässä voisi olla valmiiksi FI-MELINDA. Tarjoan tätä selitykseksi.

**Comment by ajrajala** [comment]
Virkailijalta ei tullut tähän vastausta, mutta uskoisin tästä olleen kuitenkin kyse ja suljen tiketin.
