### ISSUE TITLE
Lappi: Automaattitunnus Posion koulukirjastolle

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1341]
### Tukipyyntö

Lapin kirjastolle tarvitaan uusi salasana Posion koulukirjaston automaatille. Tiedot laitettu tukipostiin [support@koha-suomi.fi](mailto:support@koha-suomi.fi)

**Comment by emta001** [comment]
Salasana vaihdettu.

**Comment by LeenaKinnunen** [comment]
Asia kunnossa, suljen tiketin.
