### ISSUE TITLE
Vaara: niteiden vastaanotto ei onnistu

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1342]
### Mikä vikana?

Hankinnasta raportoitiin, että tänään on tullut useassa niteessä vastaanotettaessa virheilmoitus "Jotain meni pieleen taulua ladatessa. 400: Bad request."
Tällaisia nimekkeitä ovat mm. 
https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11726891&found1=1 
https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=11743164&found1=1
Mikähän näissä on vialla?

**Comment by pirliis** [comment]
OUTIssa Iistä ja Kuivaniemeltä tuli nyt myös ilmoitus, ettei vastaanotto toimi. Sama herja kuin Vaarassa "Jotain meni pieleen taulua ladattaessa. 400: Bad Request".

**Comment by emta001** [comment]
Vika on nyt korjattu väliaikaisesti tekemällä pieni muutos suoraan tuotantoihin. Tämä vaatii vielä kunnollisen paikkauksen, tehdään se tänään ja ajetaan tuotantoon illalla tai huomenaamulla.

Ongelmana oli siis tämän viikon päivityksessä mukana tullut tietoturvapaikka, joka estää haitallisen koodin lähettämisen API:n q-parametrin kautta. Korjaus sisälsi validoinnin joka estää esimerkiksi "in" operaattorin käytön ilman väliviivaa operaattorin edessä. Niteiden vastaanotossa olikin sitten käytetty tuota operaattoria juuri väärin ja tämä kutsu:

`q={"order_id":{"in":[...]}}`

aiheutti sitten taulun latauksen epäonnistumisen. Tarkistin koodin vielä näiden varalta ja näyttäisi sille, että niteiden vastaanotto sivu oli ainut mistä löytyi tällainen virhe.

 Pahoittelut kaikille tästä aiheutuneesta vaivasta.

**Comment by pknuuti** [comment]
Kiitos, toimii. Suljen tiketin.

**Comment by emta001** [comment]
Availen tän vielä siks aikaa, että saadaan korjaus tuotua paikalleen ja todettua, että kaikki toimii.

**Comment by emta001** [comment]
Korjaus viety tuotantoon ja vastaanotto toimii taas.
