### ISSUE TITLE
Kyyti: Saapumisilmoitukset sähköpostiin jos se on tallennettu asiakastietoihin

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1343]
### Tukipyyntö

Kyyti-kirjastojen johtoryhmä on päättänyt Kohan asiakasviestejä koskevista muutoksista, joiden tarkoituksena ovat kustannussäästöt. Muutosten olisi tarkoitus tulla voimaan 1.9.2024.

Mikäli asiakkaan tiedoissa on sähköpostiosoite tallennettuna ja saapumisilmoitus menee tekstiviestillä, muutetaan saapumisilmoitus lähtemään sähköpostilla. Poistetaan näissä tapauksissa tekstiviestiruksi asiakkaan saapumisilmoituksista.

Koskee kaikkia asiakastyyppejä.

Saapumisilmoituksen voi jatkossakin siis edelleen saada tekstiviestillä ja tekstiviestivaihtoehto säilyy, mutta tällaisella kertamuutoksella niiden määrä vähenee merkittävästi.

Onnistuuko tämä toivotussa ajassa? Olisi hyvä tietää, jotta saadaan asiakastiedotus hoidettua ajoissa.

**Comment by lmstrand** [comment]
Ajettava maanantaina:

./change_sms_to_email_messaging_preference.pl -m sms -l HOLD -c HENKILO -c VIRKAILIJA -c KOTIPAL -c LAPSI -c SISAINEN -c KIRJASTO -c YHTEISO -r --confirm

**Comment by Tuomas-Kyyti** [comment]
Nähdäkseni tämäkin on ok. Kiitos.
