### ISSUE TITLE
Kyyti: Ennakkoilmoitus vain sähköpostina

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1344]
### Tukipyyntö

Kyyti-kirjastojen johtoryhmä on päättänyt Kohan asiakasviestejä koskevista muutoksista, joiden tarkoituksena ovat kustannussäästöt. Muutosten olisi tarkoitus tulla voimaan 1.9.2024.

Ennakkoilmoituksen (PREDUEDGST) on Kyytissä voinut saada tekstiviestinä ja/tai sähköpostina. Poistetaan tekstiviestimahdollisuus, niin että ennakkoilmoituksen voi saada 1.9. alkaen vain sähköpostilla.

Toimenpiteet:
1. Kaikille asiakkaille, joilla on ennakkoilmoitus tekstiviestinä-ruksi ja joilla on sähköpostiosoite tallennettuna asiakastietoihin, ruksitaan ennakkoilmoitus sähköpostiin.

2. Poistetaan ennakkoilmoituksista kaikki tekstiviesti-ruksit.

3. Estetään mahdollisuus ruksia ennakkoilmoituksesta tekstiviesti. Vaihtoehtoisia toimintatapoja:
3.1 Poistetaan SMS-message_transport ennakkoilmoitukselta (vrt. tiketti https://github.com/KohaSuomi/Koha/issues/861)
3.2 Piilotetaan tekstiviestivalinta ennakkoilmoituksista CSS-piilotuksella Kohasta ja Finnasta Vaskin "tekstiviestivalinnan estäminen noutomuistutukselta"-rimpsuja muokkaamalla (mainittu tiketissä #861)
3.3 Jokin muu tapa

Koskee kaikkia asiakastyyppejä.

Tekstiviesteinä voisi jatkossa lähteä vain saapumisilmoitukset.

Meidän tulee itse hoitaa Finnan tekstiviestiruksin piilotus.

Onnistuuko tämä toivotussa ajassa? Olisi hyvä tietää, jotta saadaan asiakastiedotus hoidettua ajoissa.

**Comment by lmstrand** [comment]
Kohtaan 3. Viestiasetuksen poistaminen tietokannasta poistaa sen myös Finnasta ja Kohasta, eikä se enää ole saatavilla. Erillisiä piilotuksia ei tarvitse silloin.

Kohtaan 1 Voi laatia kyllä SQL-kyselyn. Eiköhän tuo onnistu aikataulun puitteissa. Otan saman tien työn alle.

**Comment by lmstrand** [comment]
Ajettava maanantaina:

delete from message_transports where letter_code = 'PREDUEDGST' and message_transport_type= 'sms';

**Comment by Tuomas-Kyyti** [comment]
Ainakin vielä pystyy asiakkaan viestiasetuksissa ruksittamaan ennakkoilmoituksen tekstiviestillä. Se piti siis estää.

**Comment by johannaraisa** [comment]
Tuolle ennakkoilmoitukselle on kaksi pohjaa, PREDUE ja PREDUEDGST. 
Luultavasti tuo näkyy vielä, koska PREDUEsta ei ole poistetu sms-valintaa. Pitäisi ajaa myös:

delete from message_transports where letter_code = 'PREDUE' and message_transport_type= 'sms';

**Comment by paxed** [comment]
Nyt on se PREDUE myös poistettu message_transport-taulusta.

**Comment by Tuomas-Kyyti** [comment]
Nyt ei enää pysty valitsemaan ennakkoilmoitusta tekstiviestinä ja muiltakin osin tämä vaikuttaa olevan kunnossa. Kiitos.

**Comment by Tuomas-Kyyti** [comment]
Näyttää siltä, että tässä samassa yhteydessä kaikille niille asiakkaille, joita tämä muutos koski, on ennakkoilmoituksen Päivää etukäteen -arvoksi vaihtunut 1, vaikka se on aiemmin voinut ollut jotain muuta. Onkohan mitään mahdollisuutta palauttaa Päivää etukäteen -arvoa siihen mikä se oli aiemmin.

**Comment by Tuomas-Kyyti** [comment]
Tai vaihtoehtoisesti muuttaa kaikille niille asiakkaille, joille muutos toteutui, päiviä ennen arvoksi 1 - > 3, joka on yleisimmin käytetty arvo ennakkoilmoituksissa.

**Comment by lmstrand** [comment]
Ajo tehty. Liitän tiedostona ajoskriptin tähän.

Query OK, 54567 rows affected (1.346 sec)
Rows matched: 54567  Changed: 54567  Warnings: 0
[kyyti_days_in_advance_sql.txt](https://github.com/user-attachments/files/16961095/kyyti_days_in_advance_sql.txt)

**Comment by Tuomas-Kyyti** [comment]
Hyvä, tuo päiviä ennen -arvo on nyt ok.

2.9.2024 tehdyn eston jälkeen kahdelle asiakkaalle on tekstiviesti kuitenkin lähtenyt.

Asiakas: 180504
Lähetetyissä ilmoituksissa näkyy, että viesti on luotu 06.08.2024 09:19 ja päivitetty 13.09.2024 15:15. Miksi viesti on päivittynyt 13.9. ja lähtenyt asiakkaalle?

Asiakas: 287740
Asiakkaalle on luotu viesti 11.09.2024 09:19 ja se on päivitetty eli lähtenyt 11.09.2024 09:30. Asiakkaan lokissa näkyy 02.09.2024 11:43 Finnassa tehty muokkaus:
`[{'mtt' => ['sms'],'_name' => 'Hold_Filled'},{'_name' => 'Item_Check_in','mtt' => ['email']},{'mtt' => ['email'],'_name' => 'Item_Checkout'},{'mtt' => ['sms'],'_name' => 'Hold_Reminder'},{'mtt' => ['sms'],'dig' => 1,'_name' => 'Advance_Notice','da' => 1}] `
Onko tuosta tulkittavissa, että hän on pystynyt vaihtamaan vielä silloin tekstiviesti-ilmoituksen päälle? Ja jos on, niin miten sen saa pois, kun virkailija-Kohassa viestiasetuksissa on ennakkoilmoituksissa vain viiva? 

Tapaukset vaikuttavat erilaisilta, mutta onko yleispätevä toimi tyhjentää ilmoituspohjissa PREDUEDGST tekstiviesti-kohta?

**Comment by lmstrand** [comment]
287740 tapauksessa tuota viestipohjan poistoajoa ei vielä ole tehty, joten asiakas on pystynyt vaihtamaan sen ilmeisesti Finnassa (jos teillä ei ole ollut piilotusta Finnan päässä).

"Tapaukset vaikuttavat erilaisilta, mutta onko yleispätevä toimi tyhjentää ilmoituspohjissa PREDUEDGST tekstiviesti-kohta?"
 Viestipohjan poisto sms:stä varmistaa, etteivät viestit synny.

180504:  13.9.  lähteneen viestin viestipohjana lukee message_queue:ssa ODUE1e. Vanha 6.8. lähetetty viesti on eri pohjalla PREDUEDGST ja se on mennyt perille ok statuksena sent. Kun ne on lähetetty, niihin ei enää kajota.

**Comment by lmstrand** [comment]
Niinpä näkyykin, että viesti on päivittynyt tuolloin 13.9. tuolle asiakkaalle borrowernumberilla 180504. En kyllä keksi, miksi näin olisi käynyt. Viestin lähetys on alunperin epäonnistunut ja virkailija on käsin yrittänyt uudelleenlähetystä, jolloin se onkin onnistunut? Tuossa on kyllä liian pitkä aika viestin alkuperäisen syntymisen ja update-aikaleman välillä ja virkailijakin olisi hoksannut, ettei kannata niin vanhaa viestiä lähettää uusiksi. Ajokin on tehty 11.9. ja jos se millään tapaa olisi voinut vaikuttaa, olisi viesti lähtenyt jo silloin. Osaisiko @AnneliO heittää tähän jotain?

No mutta näitä ei enää lähde kun on pohja poistettu sms:stä.

**Comment by AnneliO** [comment]
Tuon asiakkaan 180504 Ilmoitukset-välilehdellä on ainakin käynyt virkailija 13.9.2024 juuri ennen kuin viesti on lähtenyt uudelleen asiakkaalle, joten on hyvin mahdollista, että hän on joko tarkoituksella tai vahingossa lähettänyt viestin uudelleen.
