### ISSUE TITLE
Kyyti: Asiakkaan tietopyyntö

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha#1345]
### Tukipyyntö

Hei, Haminaan oli tullut tietosuoja-asetuksen mukainen tietopyyntö yhdestä asiakkaastamme tallennetuista rekisteritiedoista. Laitan asiakkaan tiedot turvasähköpostilla koha-suomen support-osoitteeseen. Pystyykö joku kehittäjistä kokoamaan tarvittavat tiedot asiakkaasta?

**Comment by emta001** [comment]
Tämän toteuttamiseen tarvittaisiin vielä asiakkaan borrowernumber, sen voi lisätä ihan suoraan tähän tikettiin [Tietopyyntö-ohjeen](https://github.com/KohaSuomi/Koha/wiki/Tietopyynt%C3%B6) mukaisesti.

**Comment by VaisanRo** [comment]
Kyseisellä henkilöllä on sekä virkailijatunnus, että henkilöasiakastunnus. Pitäisiköhän tiedot toimittaa molempien tunnusten osalta. Työkortilla asiakkaan ID: 303083 ja henkilöasiakkaan ID: 300506

**Comment by emta001** [comment]
> Kyseisellä henkilöllä on sekä virkailijatunnus, että henkilöasiakastunnus. Pitäisiköhän tiedot toimittaa molempien tunnusten osalta. Työkortilla asiakkaan ID: 303083 ja henkilöasiakkaan ID: 300506

Hmm, luultavasti kerta ei ole tarkennettu kumpaa tiliä asia koskee. Kerään molemmista tiedot.

**Comment by VaisanRo** [comment]
Jep varmempi laittaa molemmat, kiitos.

**Comment by VaisanRo** [comment]
Toimititko tiedot suoraan asiakkaalle? Minulle ei ainakaan vielä tullut turvasähköpostia.

**Comment by emta001** [comment]
Vastasin siihen siun laittamaan turvapostiin, mutta se ei kai nyt jostain syystä toimi. Laitan ne Elementsissä.

**Comment by VaisanRo** [comment]
Okei, löytyi Elementsistä, kiitos! 😊 Suljen tiketin.
