### ISSUE TITLE
Esikatsele SQL-toiminnon piilotus

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1346]
### Mikä vikana?

_Tallennetut raportit_ -sivun _Toiminnot_-sarakkeessa oleva _Esikatsele SQL_-toiminto on ongelmallinen. Sen kautta pystyy ohittamaan virkailijaoikeuksia. Toisaalta koko toiminto on varsin tarpeeton. Matrixin keskustelussa ratkaisuksi esitettiin koko Esikatsele SQL-toiminnon piilottamista ainakin siihen asti, kunnes ongelmat on korjattu.

**Comment by AnneliO** [comment]
Tämä IntranetUserCSS-järjestelmäasetukseen lisättävä piilotus toimii testieni mukaan sekä versiossa 23.11 että 24.05, mutta kannattaa vielä muidenkin testata:

```
/* Piilota Esikatsele SQL -vaihtoehto valikosta Tallennetuissa raporteissa */
body#rep_guided_reports_start.rep a.preview_sql { display: none; }
```

**Comment by pknuuti** [comment]
Piiloutuu sekä nextillä että testillä.

**Comment by Tuomas-Kyyti** [comment]
Vaikuttaa tosiaan toimivan nextillä ja testillä.

**Comment by MikkoLiimatainen** [comment]
Piilotus toimii ja meni Vaskissa jo tuotantoonkin asti.

**Comment by pknuuti** [comment]
Piilotettu Vaarankin tuotannosta.

**Comment by pirliis** [comment]
OUTIssa toimi myös. Piilotus tehty testille, nextille ja tuotantoon.

**Comment by AnneliO** [comment]
Rimpsu on nyt lisätty nyt myös 24-version IntranetUserCSS-wikiin [Muita-osion suositeltuihin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#suositellut).

**Comment by Tuomas-Kyyti** [comment]
Piilotus toimii ok. Tehdään sitten varsinaisista ongelmista erillinen tiketti, jos tarpeellista.
