### ISSUE TITLE
Käyttäjätietojen muokkausten estäminen muilta kuin pääkäyttäjiltä

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#1347]
### Kehitysehdotukseni

Pääkäyttäjäpalaverissa 6.8.2024 oli puhetta Vaskissa tehdystä JS-skriptistä, jolla estetään virkailijoita muuttamasta käyttäjän etunimeä, sukunimeä ja kirjastokortin numeroa virkailija-, api- ja automaattikäyttäjiltä. Virkailijoita estetään myös luomasta uusia näitä tyyppiä olevia käyttäjiä ja muuttamasta olemassa olevia käyttäjiä näiksi tyypeiksi. Ainoastaan pääkäyttäjillä on oikeus tehdä näitä käyttäjiä ja muokata olemassa olevien kaikkia tietoja.

Koska kiinnostusta löytyi muualtakin, niin tässä on skripti testattavaksi:
```javascript
/// ALKU ///
// Virkailijatunnusten muokkausten esto
$(document).ready(function() {
	if (window.location.pathname.includes('/cgi-bin/koha/members/memberentry.pl')){
		var e = document.getElementById("categorycode_entry");
		var value = e.value;
        var superlib = $('span#logged-in-info-full').children().hasClass('is_superlibrarian');
		if (!superlib && (value=='VIRKAILIJA' || value=='AUTOM' || value=='API')){ // Muokkaa tähän asiakastyyppien tunnukset. Muokkausten esto tehdään tässä määritellyille asiakastyypeille, jotka erotellaan toisistaan ||-operaattoreilla.
			e.disabled = true;
            $('input#cardnumber').prop('disabled',true);
            $('input#surname').prop('disabled',true);
            $('input#firstname').prop('disabled',true);
		}
        if (!superlib){
            $('select#categorycode_entry optgroup[label="Tilastoyksikkö"]').hide(); // Muokkaa näihin piilotettavien asiakastyyppien tyypit. Piilotus poistaa nämä tyypit näkyvistä asiakasmuokkauksen tyyppi-pudotusvalikosta.
            $('select#categorycode_entry optgroup[label="Henkilökunta"]').hide();
        }
	}
    if (window.location.pathname.includes('/cgi-bin/koha/members/members-home.pl')){
        var superlib = $('span#logged-in-info-full').children().hasClass('is_superlibrarian');
        if (!superlib){
            $('div#new-patron-button ul li a:contains("Automaatti")').parent().hide();  // Muokkaa näihin asiakastyyppien nimet. Nämä asiakastyypit piilotetaan uuden asiakkaan lisäyksen pudotusvalikosta.
            $('div#new-patron-button ul li a:contains("Kirjaston työntekijä")').parent().hide();
            $('div#new-patron-button ul li a:contains("Z API Z")').parent().hide();
        }
    }
});
/// LOPPU ///
``` 
Koodia on testattu Vaskin testissä ja nextissä. Koodia saattaa joutua muuttamaan oman kimpan ympäristöön sopivaksi. Koodiin on kommentoitu, mitä asiakastyyppien tietoja koodi tarvitsee missäkin kohtaa. Koitin myös kevyesti selittää kommenteissa, mitä koodin eri osat tekevät.

Tätä voisivat kiinnostuneet kimpat testailla, jos tästä olisi vaikka ihan yhteiseksi plugariksi. Vaskilla on ajatuksena ottaa tämä käyttöön jossain muodossa lähiaikoina ja olisi mukava saada muilta vielä kommentteja ja parannusehdotuksia.

**Comment by pirliis** [comment]
Testasin OUTIn testillä ja nextillä. Näyttäisi toimivan kuin pitääkin. Tarpeellinen muutos. :)

**Comment by MikkoLiimatainen** [comment]
Tein koodista vähän selkeämmän version, jossa ei tarvitse määritellä erikseen eri piilotuksia, vaan ainoastaan määritellä categories muuttujaan käyttäjätyyppien tunnukset. Testeissäni tämä toimii samalla tavalla kuin aiemminkin, mutta ylläpito helpottuu.
```javascript
/// ALKU ///
// Virkailijatunnusten muokkausten esto
$(document).ready(function() {
    if (window.location.pathname.includes('/cgi-bin/koha/members/memberentry.pl') || window.location.pathname.includes('/cgi-bin/koha/members/members-home.pl')){
        var superlib = $('span#logged-in-info-full').children().hasClass('is_superlibrarian');
        var categories = ["VIRKAILIJA", "AUTOM", "API"];
        if (window.location.pathname.includes('/cgi-bin/koha/members/memberentry.pl')){
            var e = document.getElementById("categorycode_entry");
            var value = e.value;
            if (!superlib && categories.includes(value)){
                e.disabled = true;
                $('input#cardnumber').prop('disabled',true);
                $('input#surname').prop('disabled',true);
                $('input#firstname').prop('disabled',true);
            }
            if (!superlib){
                categories.forEach(piilotus);
                function piilotus(item) {
                    $('select#categorycode_entry option[value="'+ item +'"]').parent().hide();
                }
            }
        }
        if (window.location.pathname.includes('/cgi-bin/koha/members/members-home.pl')){
            if (!superlib){
                categories.forEach(piilotus);
                function piilotus(item) {
                    $('div#new-patron-button ul li a[href*="categorycode=' + item + '"]').parent().hide();
                }
            }
        }
    }
});
/// LOPPU ///
```

**Comment by AnneliO** [comment]
Asiantuntijaryhmä 26.8.2024: Tehdään JS-liitännäiseksi siten, että asiakastyypit voi määrittää konfiguroinnissa.

**Comment by lmstrand** [comment]
Lisätty määriteltäväksi pluginiksi nexteille.

**Comment by LastuJanneS** [comment]
Meillä tuo Mikon laittama viimeisin skripti aiheutti sellaisen sivuvaikutuksen testillä, että jos henkilökunta teki omaan virkailijatietueeseensa minkäänlaisia muutoksia, niin cardnumber-kenttä menee jostain syystä nulliksi tallentamisen yhteydessä ja Koha heittää virkailijan pihalle. Sen verran ehdin testata että liittyi tuohon $('input#cardnumber').prop('disabled',true); koodinpätkään, sen poistamalla virhettä ei enää tullut.

**Comment by MikkoLiimatainen** [comment]
Juu, pahoittelut, etten tänne ole päivittänyt tätä tietoa. Laitoin huomion tuohon plugarin-tikettiin ja Lari tarjosi vaihtoehtona readonlyä: $('input#cardnumber').prop("readonly", true);

Tuo ajaa saman asian, mutta ilman korttinumeron pois tipahtamista.

**Comment by emta001** [comment]
Plugari on nyt käytössä ja testattu nexteillä, että toimii. Tiketin voinee sulkea.
