### ISSUE TITLE
Kirkes: Tuusulan pääkirjastossa tarvitaan viimeisten noutopäivien siirtoa

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1349]
### Tukipyyntö

Tuusulan pääkirjasto (TUPK) joudutaan sulkemaan ajalle 12.-27.8. Pyytäisin siirtämään tuolle välille osuvat varausten viimeiset noutopäivät keskiviikolle 28.8.

**Comment by emta001** [comment]
Varaukset siirretty seuraavalla rimpsulla:

`update reserves set expirationdate = '2024-08-28' where branchcode = 'TUPK' and found = 'W' and expirationdate between '2024-08-12' and '2024-08-27';`

**Comment by ElinaUotila** [comment]
Kiitos!
