### ISSUE TITLE
Lappi : Kustannuspaikka e-kirjeeseen

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1351]
### Tukipyyntö

Lapin e-kirjepohjaan tarvittaisiin lisättäväksi kustannuspaikka, jotta kaupunki pystyisi erittelemään kirjastolle kuuluvat e-kirjelaskut muista kaupungin kustannuksista. Postista tuli ohje muokkaukseen: 
Sivu 7: 2.4. EPLK record = Letters specific parameterized control data. Pääsääntönä että department code tuodaan EPLK rivin positiossa 41-45.

**Comment by CodoDerDritte** [comment]
Rajapinnassa on tähän valmis toiminnallisuus ja kustannuspaikkakoodi on lisätty Lapin testille. Testiviesti on toimitettu Posti Messagingin järjestelmään, odotetaan sieltä kuittaus että homma ok ja sen jälkeen tuotantoon.

**Comment by CodoDerDritte** [comment]
Testi saatiin, näyttää oikelta ja osastotietokin on välittynyt Posti Messagingille oikein. Milloin haluatte tuotantoon?

**Comment by LeenaKinnunen** [comment]
Tämän saa nyt laittaa tuotantoon.

**Comment by CodoDerDritte** [comment]
Muutos on tehty, astuu voimaan huomenna.

**Comment by LeenaKinnunen** [comment]
Asia kunnossa, suljen tiketin.
