### ISSUE TITLE
Kyyti: DUEDGST lähtenyt tekstiviestinä vaikka ei pitäisi

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1355]
### Mikä vikana?

Muutamalle asiakkaille on lähtenyt DUEDGST eli ilmoitus eräpäivänä -viesti tekstiviestinä, vaikka tekstiviestiä ei siihen voi valita ja näilläkin asiakkailla näkyy vain viiva viestiasetusten tekstiviestisarakkeessa.

Kuitenkin message_queue-taulussa näkyy nämä viestit sent-tilassa ja asiakkaiden ilmoitukset-välilehdellä viestit näkyvät lähteneinä.

Viestit ovat lähteneet englanninkielisinä oletusviesteinä, koska tuota viestiä tekstiviestinä ei ole meillä käännetty, kun sen ei ole koskaan pitänyt olla edes käytössä tekstiviestinä, vaan vain sähköpostina.

Tänä vuonna tekstiviesti on kuitenkin lähtenyt 11 asiakkkaalle. Kaikki viestit ovat lähteneet versionvaihdon jälkeen touko-elokuussa, joten se lienee jotenkin vaikuttanut asiaan.

Yhteistä näille asiakkaille vaikuttaa olevan, että heille lähtee tekstiviestinä jokin ilmoitus (ennakkoilmoitus PREDUEDGST tai saapumisilmoitus HOLD), mutta versionvaihdon jälkeen myös DUEDGST on alkanut lähteä tekstiviestillä.

Viestiasetusmuutoksia ei näy kenelläkään asiakkaalla.

Mitenhän tämä on mahdollista?

Asiakkaat, joille DUEDGST-viestejä on lähtenyt tekstiviesteinä:
275486
273016
271086
272162
208220
212941
180369
141057
273302
204340
145062

### Mitä pitäisi tapahtua

DUEDGST pitäisi lähteä vain sähköpostina, jos asiakas on sen halunut. Kohassa ja Kyyti-finnassa ei pysty valitsemaan DUEDGST-viestiä tekstiviestinä.

**Comment by PiaKusmin** [comment]
Voisko liittyä tähän tikettiin [https://github.com/KohaSuomi/Koha/issues/1309](https://github.com/KohaSuomi/Koha/issues/1309)?

**Comment by AnneliO** [comment]
> Voisko liittyä tähän tikettiin #1309?

SMS-vaihtoehtoa ei ole näkyvissä Kyyti-Finnassa. Estin JavaScriptit, jotta näkisin, onko jotain piilotettu ja näkyville tuli vain koosteviesti-mahdollisuus, mutta ei tekstiviestimahdollisuutta:

![kuva](https://github.com/user-attachments/assets/39b1f2b1-aed5-4201-a3c6-69e023bacafd)

**Comment by lmstrand** [comment]
Varmuuden vuoksi DUEDGST-letter codelta voisi poistaa tuon viestimistavan(transport) SMS kuten tiketissä https://github.com/KohaSuomi/Koha/issues/861 kokeiltiin. Poistuu siten Finnasta ja Kohan virkailijaliittymästä. Se löytyy Kyytin tuotannon tietokannasta, joten piilotukset on tehty skripteillä Finnaan ja Kohaan. Sitä en osaa sanoa, että missä vaiheessa noita on pystynyt syntymään asiakkaille. Kohaan on lisätty muutos, jolloin viestiasetusten muutokset ovat alkaneet lokittua asiakkaan tapahtumalokiin 8.3.2024.

**Comment by lmstrand** [comment]
Hetkinen katsoin väärin. Kyytin tuotannossa löytyy vain vain email, phone ja suomifi -transportit DUEDGST-lettercodelle.

**Comment by lmstrand** [comment]
Voisiko tässä olla kyseessä jonkin uusi ominaisuus, joka käyttää sitten automaattisesti toissijaista lähetysmuotoa jos vain tuo kooste-täppä on valittuna eikä sitä toimitustapaa ollenkaan...

**Comment by AnneliO** [comment]
Ainakaan järjestelmäasetuksista en löytänyt mitään tuommoseen liittyvää sanoilla fallback, sms tai message. Mutta voihan se "fallback" olla jossain muuallakin kuin järjestelmäasetuksissa.

**Comment by lmstrand** [comment]
En minäkään huomaa noissa cronskripteissä mitään sellaista muutosta. Viestiasetusten muutoslokitus on lisätty tuotantoihin sittenkin 13.5. https://github.com/KohaSuomi/Koha/issues/241#issuecomment-2107321030

**Comment by AnneliO** [comment]
Vastaavia oletusviestejä näyttäisi lähteneen sms:nä myös Lumpeissa, Lapissa ja Vaarassa. Hellessäkin on lähtenyt viestejä, mutta ne näyttää sisällöltään "aiheellisilta".

**Comment by AnneliO** [comment]
Laskeskelin, kuinka monta sms-tyyppistä DUEDGST-viestiä on lähtenyt eri kimpoissa ja tällaisia lukuja löytyi:

Kimppa|Määrä
---|---
Lumme|17
Kyyti|17
Lappi|27
Vaara|4

Tein tällaisen kyselyn kantoihin:

```
select count(*) from message_queue where letter_code='DUEDGST' and message_transport_type='sms';
```

**Comment by lmstrand** [comment]
Lapin tuotantoon on lisätty verbose-vipu ajastettuun ajoon advance_noticesille, jos lokille saisi enemmän tietoa, mistä tämä voisi johtua. Lokeilla oli merkintöjä esim. Kyytissä:

No circulation DUEDGST letter transported by sms at /home/koha/Koha/C4/Letters.pm line 585.
Use of uninitialized value in concatenation (.) or string at /home/koha/Koha/misc/cronjobs/advance_notices.pl line 624.
no letter of type '' found for borrowernumber 275486. Please see sample_notices.sql at /home/koha/Koha/misc/cronjobs/advance_notices.pl line 624.

Tuon perusteella ei olisi kuulunut lähteä viestiä, eli onkohan kysessä jonkinlainen bugi Letters.pm-moduulissa. En näe uusilta lokeilta samanlaisia ilmoituksia enää näistä skettäin parin päivän sisään syntyneistä viesteistä.

Oletusviestipohjan tyhjentämisen kuuluisi estää viestin syntymisen, mutta jos Lappi jättäisi vielä hetkeksi omansa, niin saatetaan saada kiinni, mistä tämä johtuu.

**Comment by AnneliO** [comment]
Lappiin oli muodostunut yksi sms-duedgst tänä aamuna, mutta lokille ei ollut kirjaantunut mitään hyödyllisiä lisätietoja.

Päätimme kokeilla duedgst-pohjasta sms-viestityypiltä oletuspohjan tyhjentämistä. Se pitäisi estää viestien lähteminen. Tyhjensin Lapista, Vaarasta, Lumpeista ja Kyytistä kyseiset oletuspohjat. Seuraillaan taas tilannetta.

**Comment by AnneliO** [comment]
Tarkistin viestimäärät tänään ja uusia ei ollut vielä ainakaan syntynyt, mutta suht harvoihan noita muutenkin syntyy.

**Comment by AnneliO** [comment]
Tarkistin viestimäärät, ei uusia.

**Comment by emta001** [comment]
Voisiko tämän sulkea? Avataan uudelleen, jos näitä tulee lisää.

**Comment by Tuomas-Kyyti** [comment]
Kyytiin ei ole tullut 12.8.24 jälkeen. Tarkistaako @AnneliO muut kimpat vai suljetaanko pois?

**Comment by AnneliO** [comment]
Muissa kimpoissakaan ei ole tullut uusia, joten sulje vaan pois. :)

**Comment by Tuomas-Kyyti** [comment]
Ilmeisesti siis duedgst-pohjasta sms-viestityypiltä oletuspohjan tyhjentäminen auttoi tähän ongelmaan. Suljen tiketin.

**Comment by PiaKusmin** [comment]
Lappiin on muodostunut muitakin viestejä englannin kielisinä SMS-viesteinä, vaikka näin ei pitäisi tapahtua. 
Kyseessä on PREDUEDGST ja PREDUE viestit. Molemmissa löytyy eng. kieliset SMS-pohjat. Pitäisikö nekin tyhjentää?

Asiakas: borrowernumber=517596

**Comment by PiaKusmin** [comment]
Ja vielä DUE-pohjakin.
Lapissa SMS viestit pitäisi lähteä vain noutoilmoituksista

**Comment by lmstrand** [comment]
Ainakaan Finnasta noita ei voi laittaa päälle:

![image](https://github.com/user-attachments/assets/2eca8228-5658-4461-bfee-41a9e16bbb45)

**Comment by lmstrand** [comment]
DUE-pohjaa ei pitäisi pystyä käyttämään (tai sellaista viestiasetusta ei pitäis pystyä tallentamaan, jossa ei käytetä koostetta), meillä on triggeri joka pakottaa koosteen päälle tietokannassa.

**Comment by lmstrand** [comment]
Nää on varmaan vanhoja asiakkaita, jotaka ovat saaneet laitettua joskus itselleen tuollaiia viestiasetuksia ennen kuin niitä piiloteltiin ja estettiin. Jos viestipohjan tyhjentää, niin viestejä ei synny. Ehkä ratkaisisin asian niin.

**Comment by PiaKusmin** [comment]
Kävin tyhjentämässä meidän viesteistä nuo SMS-pohjat. Jospa niitä ei enää muodostu. 
Kiitos selvittelystä. Suljen tiketin uudelleen.
