### ISSUE TITLE
OUTI: Karjasillan noudettavissa olevien varausten noutopäivien siirto

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1358]
### Tukipyyntö

Karjasillan kirjastossa ei ole tehty kalenteriin ylityksiä sen omatoimi-aukioloaikojen vuoksi. Nyt kirjaston omatoimilaitteet ovat rikki eivätkä asiakkaat välttämättä pääse hakemaan varauksiaan, joten jatkaisitteko kaikkien Karjasillan kirjaston noudettavissa olevien varausten noutoaikaa syyskuulle.

Noutokirjasto: OUKS Karjasillan kirjasto
Varaukset, joiden viimenen noutopäivä on välillä 15.8.2024-1.9.2024
Muutetaan noudettavissa olevien varausten viimeiseksi noutopäiväksi ma 2.9.2024

**Comment by lmstrand** [comment]
Ajettu:

MariaDB [outiprod]> UPDATE reserves SET expirationdate = '2024-09-02' WHERE reserve_id IN(SELECT reserve_id FROM reserves WHERE expirationdate between '2024-08-15' AND '2024-09-02' AND found = 'W' AND branchcode = 'OUKS');
Query OK, 8 rows affected (0.041 sec)
Rows matched: 19  Changed: 8  Warnings: 0

**Comment by piiaseme** [comment]
Kiitos, tarkistin eilen noutopäivät Karjasillan Odottavat varaukset -raportilla enkä hoksannut miten joillain varauksilla oli viimeiseksi noutopäiväksi muuttunut myös 3.9., 6.9. ja 7.9.? 

Esim. 
niteen 564N27684580 (itemnumber=3561538) noutopäivä oli 20.8. ja nyt se on 7.9.
niteen 564N28129460 (itemnumber=3644560) noutopäivä oli 16.8. ja nyt se on 3.9.
niteen 678N00297095 (itemnumber=2904083) noutopäivä oli 19.8. ja nyt se on 6.9.

Tein eilen ensin Karjasillan kalenteriylitykset väärin, jolloin uusille varauksille tuli noutopäiväksi 8.9. Korjasin kalenteriylityksen siten, että noutopäiviksi alkoi muodostua 2.9. Kirjastolle oli ok jättää varausten noutopäivät tuolle myöhäisemmälle päivälle, joten niitä ei tarvinnut alkaa muuttamaan. Nuo 3.9., 6.9. ja 7.9. noutopäivät ovat myös ok kirjastolle, joten niitä ei tarvitse muokata uudelleen. Ihmettelen vain mistä nuo erilaiset noutopäivät johtuvat?

**Comment by AnneliO** [comment]
> 564N27684580

Tämän on [henkilökunnan jäsen muuttanut](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=218&phase=Run+this+report&param_name=biblionumber&sql_params=2298044&param_name=borrowernumber&sql_params=128378) 2024-08-15 10:50:54

>564N28129460 

[Sama tässä](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=218&phase=Run+this+report&param_name=biblionumber&sql_params=2323845&param_name=borrowernumber&sql_params=255306)

>678N00297095 

[Tässä myös](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=218&phase=Run+this+report&param_name=biblionumber&sql_params=2122669&param_name=borrowernumber&sql_params=254746)

**Comment by piiaseme** [comment]
Kiitos selvityksestä, sepäs selittääkin eroavaisuudet noutopäivissä. Suljen tiketin.
