### ISSUE TITLE
Lumme: OKM-tilastojen puolivuotiskatsaus

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1360]
### Tukipyyntö

Lumpeissa olisi tarvetta OKM-tilastojen puolivuotiskatsaukselle. Tilastoihin tulisi olla koottuna OKM:n tilastoluvut ajanjaksolta 1.1.-30.6.2024, samalla tavalla kuin vuoden 2023 puolivuotiskatsauksessa.

**Comment by lmstrand** [comment]
Ajettu:

./generate_okm_annual_statistics.pl --timeperiod '2024-01-01 - 2024-06-30' --individual 'ALL' -r -v

Tähän siis ei tarvitse ajaa niitä OKM-ryhmiä?

**Comment by Hanna-Lumme** [comment]
Ei tarvitse, nämä tiedot riittää. :) Kiitos!
