### ISSUE TITLE
Vaski: KALI-yksikön varausten keskeytysten aktivointipäivän muutos

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1361]
### Tukipyyntö

Littoisten kirjaston sulkuaikaa on jatkettu ja siksi jo keskeytettyjen varausten aktivointipäivää tulisi vaihtaa 15.10.2024. Kyseessä varaukset, jotka keskeytettiin tässä työpyynnössä: https://github.com/KohaSuomi/Koha/issues/1318

Kirjasto KALI
Vain keskeyttämättömät ja keskeytyksen aikana aktivoituvat varaukset (18.7.2024-15.10.2024)
Keskeytys tehdään ennen 16.9.2024
Keskeytys päättyy 15.10.2024

**Comment by emta001** [comment]
Varaukset keskeytetty, löytyvät aputaulusta `ks_20240909_reserves_1361`. 

`CREATE TABLE ks_20240909_reserves_1361 SELECT * FROM reserves WHERE branchcode = 'KALI' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-07-18' AND '2024-10-15'));`

`UPDATE reserves SET suspend = 1 WHERE branchcode = 'KALI' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-07-18' AND '2024-10-15'));`

Keskeytys koski 27 varausta.

**Comment by sksandel** [comment]
Hei,

hain yksikön KALI varaukset (SELECT * FROM reserves WHERE branchcode = "KALI"), jotka kaikki olivat kyllä keskeytettyjä, mutta yhdelläkään ei ollut tuota 15.10.2024 aktivointipäivänä. Ei löytynyt myöskään tuon aikaisemman tiketin https://github.com/KohaSuomi/Koha/issues/1318 16.9.2024 aktivointipäivää. Aikaisemmassa ajossa on käsitelty 745 varausta ja myöshemmin 36 lisää. Tämänkin ajon olisi pitänyt siis koskea suurinpiirtein samaa määrää varauksia. 

Nyt lähes kaikki yksikön KALI varaukset näyttäisivät olevan keskeytettynä toistaiseksi. Pystymmekö tunnistamaan varaukset, jotka on keskeytetty edellisellä ajolla (ja joita asiakas ei ole siirtänyt toiseen yksikköön)?

**Comment by emta001** [comment]
> Hei,
> 
> hain yksikön KALI varaukset (SELECT * FROM reserves WHERE branchcode = "KALI"), jotka kaikki olivat kyllä keskeytettyjä, mutta yhdelläkään ei ollut tuota 15.10.2024 aktivointipäivänä. Ei löytynyt myöskään tuon aikaisemman tiketin #1318 16.9.2024 aktivointipäivää. Aikaisemmassa ajossa on käsitelty 745 varausta ja myöshemmin 36 lisää. Tämänkin ajon olisi pitänyt siis koskea suurinpiirtein samaa määrää varauksia.
> 
> Nyt lähes kaikki yksikön KALI varaukset näyttäisivät olevan keskeytettynä toistaiseksi. Pystymmekö tunnistamaan varaukset, jotka on keskeytetty edellisellä ajolla (ja joita asiakas ei ole siirtänyt toiseen yksikköön)?

Niiden pitäis olla tallessa siis tauluissa ks_20240718_reserves_1318, ks_20240726_reserves_1318 ja ks_20240909_reserves_1361. Kattelin tuota ajoa uudestaan ja en tosiaan kummallakaan kerralla hoksannut asettaa suspend_until-sarakkeeseen arvoa.

**Comment by emta001** [comment]
Muutama ei keskeytetty löytyy KALIsta ja muutama semmonenkin, jossa on jo suspend_until-arvo. Mutta muille pitänee käydä tekemässä vielä uusi ajo.

**Comment by emta001** [comment]
Nonnih, jospa ne nyt olisi paremmin. Uusi aputaulu luotu:

`create table ks_20240917_reserves_1361 select * from reserves where branchcode = "KALI" and found is null and suspend_until is null;`

Ja varaukset keskeytetty näin:

`update reserves set suspend = 1, suspend_until = "2024-10-15" where branchcode = "KALI" and found is null and suspend_until is null;`

**Comment by emta001** [comment]
> Katsoimme, että monelle toistaiseksi keskeytettynä olleille varauksille on nyt tullut suspend_until-päivämääräksi 15.10.2024. En tiedä saako tuota mitenkään tarkasti selvitettyä, mitä varauksia tämä nyt koskee, mutta otin tuon alkuperäisen ajon perusteella sellaiset varaukset, joille ei silloin olisi pitänyt asettaa päättymispäivää näin:
> 
> ```
> SELECT * 
> FROM reserves r 
> WHERE r.reserve_id NOT IN (SELECT reserve_id
> FROM ks_20240718_reserves_1318)
>   AND r.branchcode = 'KALI'
>   AND r.suspend_until = '2024-10-15'
> ```
> 
> Tämän lisäksi pitäisi käydä nuo muidenkin ajojen muutokset läpi ja selvittää niiden vaikutus varauksiin, mutta tämän perusteella näyttää siltä, että aika monella varauksella (238) on nyt väärin tuo päivämäärä. Se on asiakkaan kannalta harmillista, jos varaus aktivoituu nyt heidän tahtomattaan.

Tuo on varmastikin parhain ja tarkin tapa saada nämä selville. Sen tiketin #1318 toisen ajon saanee toisen ajon aputaulusta. Mietin kyllä tässä, että pitäisikö ensiksi kuitenkin palauttaa varausten suspend ja suspend_until sarakkeiden arvot tämän tiketin aputaulun (ks_20240917_reserves_1361) avulla ja sitten katsoa tarkemmin mitä muutetaan ja miten?

**Comment by MikkoLiimatainen** [comment]
Kun ainoastaan viimeisimmässä ajossa varauksille asetettiin suspend_until, niin eikö silloin kävisi järkeen, että kaikki ne keskeytetyt varaukset, joita muutettiin vain neljännessä ajossa olisivat sellaisia, joilla ei pitäisi olla suspend_until-arvoa? Tällä tavoin saisin määräksi 162 varausta, jotka olisivat alun perin olleet tilapäisesti keskeytettyjä tai ne olisi tässä välissä keskeytetty tilapäisesti ja ovat yhä varattuna yksikössä KALI suspend_until arvon kanssa.

Olisinpa huomannut alun perinkin tuon päivämäärän puuttumisen, niin tätäkään ei tarvitsisi miettiä. Tosin nyt kun kaikki muutokset kertyvät päällekkäin, niin nähdäkseni noiden 162 varauksen suspend_until-arvon poisto riittäisi korjaamaan tilanteen.

Tämä nähdäkseni antaisi ne varaukset, joilta voisi poistaa suspend_until-arvon.
```
SELECT reserve_id 
FROM reserves r 
WHERE r.reserve_id NOT IN (SELECT reserve_id
FROM ks_20240718_reserves_1318
UNION ALL 
SELECT reserve_id
FROM ks_20240726_reserves_1318
UNION ALL 
SELECT reserve_id
FROM ks_20240909_reserves_1361)
  AND r.branchcode = 'KALI'
  AND r.suspend_until = '2024-10-15'
```

**Comment by MikkoLiimatainen** [comment]
Toivottavasti tuo käy järkeen, kun en itsekään tiedä onko kirjoittamani sitä, mitä tarkoitan.

**Comment by MikkoLiimatainen** [comment]
Lokienkin perusteella nuo varaukset näyttäisivät olevan sellaisia, jotka on keskeytetty toistaiseksi ja joita ei ole jatkettu, joten minusta noilta voi ottaa suspend_until-arvon pois.

**Comment by emta001** [comment]
> Kun ainoastaan viimeisimmässä ajossa varauksille asetettiin suspend_until, niin eikö silloin kävisi järkeen, että kaikki ne keskeytetyt varaukset, joita muutettiin vain neljännessä ajossa olisivat sellaisia, joilla ei pitäisi olla suspend_until-arvoa? Tällä tavoin saisin määräksi 162 varausta, jotka olisivat alun perin olleet tilapäisesti keskeytettyjä tai ne olisi tässä välissä keskeytetty tilapäisesti ja ovat yhä varattuna yksikössä KALI suspend_until arvon kanssa.
> 
> Olisinpa huomannut alun perinkin tuon päivämäärän puuttumisen, niin tätäkään ei tarvitsisi miettiä. Tosin nyt kun kaikki muutokset kertyvät päällekkäin, niin nähdäkseni noiden 162 varauksen suspend_until-arvon poisto riittäisi korjaamaan tilanteen.
> 
> Tämä nähdäkseni antaisi ne varaukset, joilta voisi poistaa suspend_until-arvon.
> 
> ```
> SELECT reserve_id 
> FROM reserves r 
> WHERE r.reserve_id NOT IN (SELECT reserve_id
> FROM ks_20240718_reserves_1318
> UNION ALL 
> SELECT reserve_id
> FROM ks_20240726_reserves_1318
> UNION ALL 
> SELECT reserve_id
> FROM ks_20240909_reserves_1361)
>   AND r.branchcode = 'KALI'
>   AND r.suspend_until = '2024-10-15'
> ```

Juups, vaikuttas ihan järkevälle. Teen tästä ajon kohtapuoliin.

**Comment by emta001** [comment]
Nuin, näyttäskö nyt oikeemmalle? Seuraavilla rimpsuilla meni:

`CREATE TABLE ks_20241009_reserves_1361 SELECT * FROM reserves r WHERE r.reserve_id NOT IN (SELECT reserve_id FROM ks_20240718_reserves_1318 UNION ALL SELECT reserve_id FROM ks_20240726_reserves_1318 UNION ALL SELECT reserve_id FROM ks_20240909_reserves_1361) AND r.branchcode = 'KALI' AND r.suspend_until = '2024-10-15';`

`UPDATE reserves r SET r.suspend_until = NULL WHERE r.reserve_id NOT IN (SELECT reserve_id FROM ks_20240718_reserves_1318 UNION ALL SELECT reserve_id FROM ks_20240726_reserves_1318 UNION ALL SELECT reserve_id FROM ks_20240909_reserves_1361) AND r.branchcode = 'KALI' AND r.suspend_until = '2024-10-15';`
