### ISSUE TITLE
Lappi: Asiakas ei pysty kirjautumaan omatoimeen / Hublettiin, mutta automaatilla lainaus toimii

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1365]
### Tukipyyntö

Asiakkaan kortti + pin-koodi toimii lainausautomaatilla. 
Ei pääse omatoimiaikana kirjastoon eikä voi lainata hublettia. 

Asiakastiedoissai ei näy mitään syytä, miksi kortti ei toimisi.  
Kokeiltu myös vaihtaa pin-koodia ja kirjastokorttia.
Borrowernumber 463772

**Comment by CodoDerDritte** [comment]
Asiakastietojen puolella kaikki näyttäisi olevan kunnossa ja virheellisten kirjautumisyritysten määrä tällä asiakkaalla on 0. SIP-lokeista en löydä yhtään kirjautumis tai lainausmerkintää tälle asiakkaalle automaattipalvelimen lokeista, ei aiis omatoimikirjautumisia eikä automaattikäyttöä tällä kortilla. Automaattikirjautumiset on varmaan tehty sillä vanhalla kortilla, joten niitä en nyt saanyt tässä selvityksessä kiinni. Jos asiakkaan aiempi korttinumero on tiedossa, niin sen voi laittaa minulle vaikka Matrixissa. Voin tutkailla noita SIP-lokeja vielä uudemman kerran.

Hubbletit ovat Lapissa kiinni borrowers/status endpointissa. Testasin borrowers/status endpointin tämän asiakkaan kortilla ja PIN-koodilla, jonka vaihdoin asiakkaalle hetkeksi testausta varten. Rajapinta palauttaa asiakkaan tiedot aivan oikein, joten tuo vaikuttaisi kyllä olevan kunnossa. Rajapinnan vastaus "sensuroituna" alla.

```
{"age":**,"borrowernumber":463772,"card_reported_lost":false,"cardnumber":"698A******","charge_privileges_denied":false,"email":"***","excessive_outstanding_fines":false,"fines":0,"firstname":"***","hold_privileges_denied":false,"homebranch":"ROOU","language":"fin","recall_overdue":false,"recall_privileges_denied":false,"renewal_privileges_denied":false,"surname":"***","too_many_claims_of_items_returned":false,"too_many_items_billed":false,"too_many_items_charged":false,"too_many_items_lost":false,"too_many_items_overdue":false,"too_many_renewals":false}
```

Syöttäähän asiakas PIN-koodinsa varmasti oikein?

**Comment by LeenaKinnunen** [comment]
Mahdollisesti kyse on ollut tästä. On nyt testattu Hubletilla, ja siinä toimii. Asiakas aikoo vielä kokeilla omatoimeen kirjautumista.

**Comment by LeenaKinnunen** [comment]
Asiakkaasta ei ole enää kuulunut mitään, joten todennäköisesti kirjautuminen toimii nyt. Suljen tiketin, avataan tarvittaessa uudelleen.
