### ISSUE TITLE
Siili: Muutospyyntö-sivuun liittyvän IntranetUserJS-rimpsun poisto

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#1366]
### Tukipyyntö

Myös Siilistä pyydetään poistamaan tämä JS-rimpsu Laita Muutospyynnöt-sivulla oletuksena valinta Hyväksy-kohtaan, joka on tiketin [#1325](https://github.com/KohaSuomi/Koha/issues/1325) mukaisesti poistettu jo Hellestä ja Outista. Ominaisuus saattaa aiheuttaa enemmän ongelmia kuin ratkoa niitä.

Voi tehdä ilman eri ilmoitusta joku aamu ennen klo 9. Kiitos :)

**Comment by CodoDerDritte** [comment]
Lasse lupasi tekaista tämän perjantaina 23.8. aamulla.

**Comment by ReettaSiili** [comment]
On poissa päältä, kiitos, suljen tämän!
