### ISSUE TITLE
Kyyti: tietueiden eräpoisto jumittunut

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1369]
### Tukipyyntö

Olin poistamassa e-kirjatietueita tietueiden poiston eräajona. Se ajo tyssäsi kohtaan 9/455. Syy on varmaan se, että mukana taisi olla e-kirjojen osakohdetietueita, joihin ajo pysähtyi. Mitä pitäisi tehdä? Voiko käyttää Taustatöiden Peruuta-toimintoa vai pitääkö kehittäjän tehdä jotain? Taustatyön id 9835600.

**Comment by CodoDerDritte** [comment]
Tällä tosiaan näkyy kannassa aloitusaika muttei lopetusaikaa ja "progress" kenttä osoittaa yhdeksää:

```
MariaDB [kyytiprod]> select enqueued_on,started_on,ended_on,status,progress,size from background_jobs where id='9835600';
+---------------------+---------------------+----------+---------+----------+------+
| enqueued_on         | started_on          | ended_on | status  | progress | size |
+---------------------+---------------------+----------+---------+----------+------+
| 2024-08-21 09:15:36 | 2024-08-21 09:15:44 | NULL     | started |        9 |  455 |
+---------------------+---------------------+----------+---------+----------+------+
```

Mitäs haluaisit että tälle tehdään? :D Voisin merkitä sille lopetusajan ja statukseksi 'failed'. Tai sitten voisin poistaa aloitusajan ja merkitä statukseksi 'NULL' ja katsotaan meniskö se toisella yrittämällä läpi (tuskinpa).

**Comment by Tuomas-Kyyti** [comment]
Parempi feilata se. Teen sitten loppujen osalta uuden ajon, josta siivoan pois ne osakohteet.

**Comment by CodoDerDritte** [comment]
Nyt se on 'failed'. En merkannut tuota ended_on aikaa, koska muillakaan failed-tilaisilla (muutamaa poikkeusta lukuunottamatta) sitä ei näy olevan.

**Comment by Tuomas-Kyyti** [comment]
Kiitos, tämä ok.
