### ISSUE TITLE
OUTI: Aseman kirjaston automaatin SIP-tunnuksen salasanan vaihto

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1371]
### Tukipyyntö

Aseman kirjaston automaatti herää taasen henkiin ja automaatin toimittaja vaihtuu, joten vaihdoimme SIP-tunnukselle uuden salasanan ja se tulisi päivittää myös järjestelmään. Automaatin asennus on sovittu 5.9., joten tällä ei ole kiire.

Voin lähettää tunnuksen tiedot matrixissa yksityisviestinä kehittäjälle, joka tunnuksen tietojen päivityksen tekee.

SIP-tunnuksen tiedot on lähetetty laitteen toimittajalle.

**Comment by CodoDerDritte** [comment]
Salasana on muutettu.

**Comment by piiaseme** [comment]
Sopiiko, että suljen tiketin vasta sitten, kun olen saanut varmistuksen Mikroväylältä, että sielläkin on tiedot turvallisesti saatu talteen? Vielä ei ole vastausta kuulunut ja jos menee kovin pitkään tai eivät saa tietoja turvallisesti talteen, niin joudutaan vaihtamaan salasana uudelleen.

**Comment by CodoDerDritte** [comment]
> Sopiiko, että suljen tiketin vasta sitten, kun olen saanut varmistuksen Mikroväylältä, että sielläkin on tiedot turvallisesti saatu talteen? Vielä ei ole vastausta kuulunut ja jos menee kovin pitkään tai eivät saa tietoja turvallisesti talteen, niin joudutaan vaihtamaan salasana uudelleen.

Juu, lienee viisainta sulkea vasta sitten kun homma on oikeasti todettu toimivaksi.
