### ISSUE TITLE
Next-kantojen tiedonhaun korjaus

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1373]
### Tukipyyntö

Useammassa next-kannassa ei toiminut tiedonhaku.

**Comment by CodoDerDritte** [comment]
Myös kirkeksessä indeksi oireilee, joten pistetään uusiksi sekin.

**Comment by AnneliO** [comment]
Ilmeisesti helle-nextin tiedonhaku ei toimi. Tieto Matrixista klo 7.56 Pääkäyttäjät -Versionvaihdot -kanavalta.

**Comment by CodoDerDritte** [comment]
Vaskin indeksointi on valmistunut eilen illalla, joten sen pitäisi nyt myös olla kunnossa.

**Comment by CodoDerDritte** [comment]
https://github.com/KohaSuomi/Koha-24.05/issues/117

**Comment by MikkoLiimatainen** [comment]
Vaskin indeksi on kunnossa, mutta jostain syystä tietoja kohasta -sivulla lukee, että elasticsearch ei ole toiminnassa, mutta zebra on toiminnassa. SearchEngine-järjestelmäasetuksessa kuitenkin on määritelty käytettäväksi elasticsearchia, joten en nyt keksi mikä tässä mättää. Tiedonhaku vaikuttaisi toimivan tästä huolimatta.

**Comment by CodoDerDritte** [comment]
> Vaskin indeksi on kunnossa, mutta jostain syystä tietoja kohasta -sivulla lukee, että elasticsearch ei ole toiminnassa, mutta zebra on toiminnassa. SearchEngine-järjestelmäasetuksessa kuitenkin on määritelty käytettäväksi elasticsearchia, joten en nyt keksi mikä tässä mättää. Tiedonhaku vaikuttaisi toimivan tästä huolimatta.

Kyllä siellä ihan elasticsearch on toiminnassa. Zebraa ei varmasti ole XD Mitä lie hourailee. Tuo elastic vaikuttaa nyt uudessa Koha-versiossa kyllä tekevän vähän mitä sattuu.

**Comment by CodoDerDritte** [comment]
Samalla tapaa väärin näyttää raportoivan muissakin Nexteissä. Kohan about-sivu on sinnikkäästi sitä mieltä että Zebraa käytetään, mutta ei kyllä käytetä :D

**Comment by CodoDerDritte** [comment]
Näköjään puhuu muutenkin mitä sattuu tuo about-sivu, ei siellä mitään RabbitMQ:takaan ole käytössä oikeasti.

**Comment by AnneliO** [comment]
Versionvaihto tehty, joten suljen tiketin.
