### ISSUE TITLE
Helle-nextin plack omituisessa limbossa

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha#1374]
### Mikä vikana?

Helle-nextillä plack oli käynnissä (master + workerit), mutta socket-tiedostoa (/var/run/koha/plack.sock) ei ollut. Tästä syystä Helle-nextiin ei päässyt, vaikka kaikki vaikutti ensisilmäyksellä olevan kunnossa. Ongelma liittynee viime viikon käyttöhäiriöiden jälkimaininkeihin ja korjaantui pysäyttämällä plackin master-prosessi ja käynnistämällä sen jälkeen plack uudelleen.

### Mitä pitäisi tapahtua

No ei pitäis limbota. Ei ole varmaan hyvä selällekkään.

### Kuinka toistaa ongelma/asia

Service unavailable ilmoitus poksahti selaimeen heti helle-nextin osoitteeseen yritettäessä.

### Selain

```markdown
Mikä tahansa selain
```

### Jotain muuta?

Korjattu, toivotaan ettei toistu ja jos toistuu niin korjataan lisää.

**Comment by Kati-Helle** [comment]
Nyt toimii, kiitti!
