### ISSUE TITLE
Vaaran vastuuhenkilöille (takaajille) muutettava "kirjastokortin" numero

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1376]
### Tukipyyntö

Vaarassa on kaikilla asiakkailla pakollisena tietona kirjastokortti-kenttä eli sitä ei voi jättää tyhjäksi edes vastuuhenkilöiltä (=TAKAAJA). Olemme aikoinaan ohjeistaneet tallentamaan tähän kenttään vaikka asiakkaan puhelinnumeron, mikä ei ole järkevää. Toki siihen on aikojen saatossa tallennettu syntymäaikoja ja kaikkea muutakin henkilökohtaista, joten nämä tunnukset pitäisi korvata jollakin anonyymillä merkkijonolla (vaikka tyyliin varaustunnisteen merkkijono).
Jotta uusille vastuuhenkilöille ei tallennettaisi enää sopimattomia tunnuksia, saisiko siihen jonkun automaattisen tunnuksen, jos asiakkaalla ei ole käytössä oikeaa kirjastokorttia?

**Comment by emta001** [comment]
Koha-Suomen palaveri 9.9.2024: Asiasta keskusteltiin kehittäjien palaverissa, mutta emme päässeet oikein mihinkään selkeään päätökseen mitä tälle kannattaisi tehdä. Tässä on vahvasti kyseessä nimenomaan kimpan oma toimintatapa, joten tämän korjaaminen koodillisesti ei ehkä ole järkevää. Ainakin seuraavia ratkaisuehdotuksia pohdittiin:
- otetaan kirjastokortti-kentän pakollisuus pois päältä Vaarasta
- syötetään kenttään oikean kirjastokortin tunnus, vaikkei asiakas ottaisikaan korttia vastaan
- poistetaan koko takaajavaatimus (tästä on ilmeisesti käyty hieman keskustelua asiantuntijaryhmässä)
- autoMemberNum-asetuksen käyttöönotto (tämä ei ole kuitenkaan hyvä ratkaisu, koska asetus voi aiheuttaa korttinumeroiden tuplaantumista)

Mutta viedään tämä vielä asiantuntijaryhmään käsitetäväksi ja katsotaan millaiseen ratkaisuun siellä päädytään.

**Comment by IrinaHalminen** [comment]
Meillä oli pääkäyttäjien kanssa puhetta, voisiko takaajille kopioida varaustunnuksen siihen kirjastokorttinumeron kohtaan? Uusia takaajia luodessa sen voisi tehdä käsin, voisiko vanhoille tehdä ajolla?

**Comment by emta001** [comment]
> Meillä oli pääkäyttäjien kanssa puhetta, voisiko takaajille kopioida varaustunnuksen siihen kirjastokorttinumeron kohtaan? Uusia takaajia luodessa sen voisi tehdä käsin, voisiko vanhoille tehdä ajolla?

Varaustunnus on julkinen tieto, joten sen käyttäminen tuossa kentässä ei ole suositeltavaa. Meidän [tietoturvaohjeissa](https://koha-suomi.fi/dokumentaatio/tietoturvaohje/) todetaan varaustunnuksista seuraavaa:
>Asiakkaiden varaustunnukseksi ei tulisi hyväksyä kirjautumiskelpoisia tunnuksia, esimerkiksi kirjastokortin numeroita. Varaustunnuksen ei ole tarkoitus avata pääsyä järjestelmään tai kirjaston palveluihin, vaan ainoastaan anonyymisti identifioida tietylle asiakkaalle menossa olevat varaukset noutohyllyssä.

Tuo pätee myös toisinpäin. Varaustunnukset ovat kaikkien nähtävillä esim. varaushyllyllä. Silloin sitä ei tulisi käyttää sellaisena arvona, joka voi mahdollistaa pääsyn Kohaan.

**Comment by IrinaHalminen** [comment]
Ymmärrän, mutta näissä tapauksissa se ei ole kenenkään muun kuin virkailijan tiedossa, ei asiakkaalla eikä hyllyssä, koska asiakas on vain takaajan roolissa. Eikö tietyn kentän pakollisuutta ole mahdollista muokata pois asiakaslajikohtaisesti? Jos sen mahdollistamiseen ei ryhdytä, täytyy vain meidän keskenämme pohtia, miten toimia. Joka tapauksessa meidän pitäisi saada puhelinnumerot vanhoilta asiakkailta pois kirjastokorttikohdasta, mitä tilalle?

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 25.9.2024: Suurimmassa osassa kimppoja kirjastokorttikenttä ei ole pakollinen. Lumpeissa ja Vaarassa on. Suositellaan pakollisuuden ottamista pois, koska toimintatapa on toiminut muissa kimpoissa.

Kun Vaara ja Lumme on poistanut pakollisuuden, voidaan TAKAAJA-asiakastyypin asiakkailta tyhjentää kirjastokorttikenttä tietokanta-ajolla. Tehkää Vaara ja Lumme niistä erilliset tukipyynnöt.

**Comment by pknuuti** [comment]
Vaara on poistanut nyt kirjastokorttikentän pakollisuuden ja TAKAAJA-asiakastyypin kirjastokorttikenttä voidaan tyhjentää.

**Comment by lmstrand** [comment]
Ajettu:

MariaDB [vaaraprod]> update borrowers set cardnumber = NULL where borrowernumber in (select borrowernumber from borrowers where categorycode = 'TAKAAJA');
Query OK, 766 rows affected (0.178 sec)
Rows matched: 766  Changed: 766  Warnings: 0

**Comment by pknuuti** [comment]
Kiitos! Suljen tiketin.
