### ISSUE TITLE
Raporttipyyntö: Maksetut myöhästymismaksut tietyltä ajalta

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1378]
### Tukipyyntö

OUTIssa tarvitaan raportti, jolla voi hakea kirjastoittain tai koko kimpan tasolla maksetut myöhästymismaksut. 

Meillä ei ole semmoista raporttia olemassa OUTIssa, jolla saisin tämän tiedon enkä saa muokattua tätä raporttia: https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#asiakkaiden-maksut-maksutyypin-mukaan-aikav%C3%A4lilt%C3%A4, jotta saisin tarvitun tuloksen. Ehtisikö joku muokata raporttia tarvitsemallamme tavalla tai tehdä uuden raportin?

Raportille tulisi voida valita
- joko kirjasto tai koko kimppa esim. koko OUTI-kimppa ("Kaikki") tai Oulu ("OU%")
- aikaväli esim. 1.1.2023-31.12.2023

Tulokseen tulisi maksetut maksut eroteltuna
- maksutyypeittäin eroteltuna verkkomaksut ja kassamaksut
esim. kaikki maksutyypit omilla riveillään siten, että eri sarakkeissa näkyy tieto miten maksu on suoritettu ja paljonko on maksettu verkkomaksuna ja paljonko suoraan kassaan sekä omassa sarakkeessaan näiden maksujen yhteenlaskettu summa.

Onnistuuko tämmöinen raportti? 

### Jotain muuta?

Kassu pääsee pähkäilemään tätä vasta loppuviikosta, joten jos jollakulla olisi jo sitä aiemmin aikaa perehtyä tähän, niin olisi hyvä.

**Comment by AnneliO** [comment]
Ei ehditty juurikaan katsomaan, mutta muutaman asian kerkesin katsomaan accountlines-taulusta avuksi (toivottavasti):

* credit_type_code = PAYMENT
* payment_type-sarakkeessa näkyy Ceepos-kassan tunnus, tällöin myös branchcode-sarakkeessa näkyy maksaneen kirjaston tunnus
*  notessa lukee Online transaction... kun maksu on tehty verkossa
* verkkomaksuista ei näe kirjaston tunnusta

**Comment by AnneliO** [comment]
Mutta miten saa yhdistettyä maksutapahtumat yksittäisiin maksuriveihin onkin sitten oma pulmansa.

**Comment by AnneliO** [comment]
Jotenkin ne kytkeytyy toisiinsa account_offsets-taulun kautta account_id:llä.

**Comment by AnneliO** [comment]
En tiedä, onko tämä pyytäjän toiveen mukaista, mutta yksi vaihtoehto olisi laskea vaan yhteen ne rivit, joissa amountoutstanding on nolla. Se ei tosin sitten erottele maksettuja/poistettuja.

**Comment by piiaseme** [comment]
Raportti on toimitettu eteenpäin, joten suljen tiketin. Avataan tarvittaessa, jos rapsan työstämistä jatketaan.
