### ISSUE TITLE
Lappi: SMS viestit menee perille vaikka Koha sanoo toisin

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1380]
### Mikä vikana?

Asiakkaalle menee varausten noutoilmoitukset sms-viestinä perille, vaikka Kohaan tulee aina huomautus viestin epäonnistumisesta. Viestit todettu henkilökunnan toimesta oikeiksi ja oikea-aikaisiksi asiakkaan puhelimesta.   
Operaattori Telia.
borrowernumber=518367 

Muutama muukin tapaus ilmeisesti on, mutta niistä ei ole saatu borrowernumberia kiinni.

Missä vika ja miten voidaan korjata?

**Comment by johannaraisa** [comment]
On mahdollista, että Telialla on rajapinnan vastaukset muuttuneet. Oletamme, että onnistuneessa lähetyksessä vastataan tietyllä tavalla ja muut menevät sitte ns. hylkyyn. Pitäisi saada käsiin uusin rajapintakuvaus, että tuota voisi tarkastella. Katsotaan saisiko sellaisen jostain.

**Comment by johannaraisa** [comment]
Siis asiakkaalla on Telia, ajattelin että kirjastolla. Siis Link Mobilitystä tulee vastaukseksi ettei onnistunut?

**Comment by PiaKusmin** [comment]
Jep, asiakkaan liittymä on Telia. Varausilmoitus lähtee hälle ja hän saa sen puhelimeen, mutta kohassa näkyy tällainen ilmoitus

![Varausviesti](https://github.com/user-attachments/assets/8b045b01-bae5-49f9-ba4b-9a6766a35dfc)

Kuitenkin näitä virhetapauksia ei ole paljoa, varauksia ja Telian liittymiä on. Eli miksi tässä tapahtuu näin? Ja aina.

**Comment by johannaraisa** [comment]
Tätä tapahtuu siis vain muutamalle asiakkaalle?

**Comment by johannaraisa** [comment]
Tätä asiaa joutuu kyllä kysymään sieltä Link Mobilityltä, virheviesti kannassa on "Unknown error". Käyttöliittymä ei osaa näyttää oikein muualta kuin Kohasta tulleita virheilmoituksia.

**Comment by johannaraisa** [comment]
Seuraavassa versiossa tähän on tulossa parannusta, muutkin alkavat näkyä.

**Comment by ReettaSiili** [comment]
Siilissä sama ongelma yksittäisen asiakkaan kohdalla, borrowernumber=21367, liittymä muistaakseni myös Telia.

**Comment by sksandel** [comment]
Vaskissa, jossa palveluntarjoajana on DNA, on ilmennyt samaa ilmiötä. Virheviesti näissä on ollut delivery expired. Isoin ongelma on ollut se, että ainakin osa näistä asiakkaista on saanut jo kertaalleen perille tulleen noutoilmoituksen uudelleen aika pitkänkin ajan päästä. Viime viikon lopulla meille raportoitiin kuudesta tapauksesta, jossa asiakas on saanut uudelleen vanhan noutoilmoituksen. Alla näistä kolme.

Asiakkaiden liittymistä ei valitettavasti ole tietoa.

Borrowernumber: 26365
Virheviesti: delivery expired 
Viestin ID: 7147511 (Kohan lähetysaika 11.08.2024 15:09-16.08.2024 16:15)
Viesti saapui uudelleen 7.9.2024

Borrowernumber: 235273
Virheviesti: delivery expired
Viestin ID: 7032540  (Kohan lähetysaika 23.07.2024 17:28 -28.07.2024 18:30)
Viesti saapui uudelleen 7.9.2024

Borrowernumber: 278293
Virheviesti: delivery expired
Viestin ID: 6972196 (Kohan lähetysaika 12.07.2024 09:26 - 17.07.2024 10:37)
Viestin ID: 6972173 (Kohan lähetysaika 12.07.2024 09:23 - 17.07.2024 10:37)
Viestit saapuivat uudelleen 6.9.2024

**Comment by PiaKusmin** [comment]
Hieman väliaikatietoa. LinkMobility on vastannut meille seuraavaa meidän esimerkkitapauksista:
---
Näille on palautunut myös operaattorilta meille toimitusvirhe. 

Normaalisti kun viesti toimitetaan onnistuneesti, palauttaa vastaanottava matkapuhelin operaattorille tiedon siitä, että viesti on vastaanotettu ja operaattori palauttaa tuon tiedon meille ja meidän rajapintamme sitten teille.
 
Tässä tapauksessa tuo kuittaus on kuitenkin jäänyt uupumaan. Laitan tästä viestejä välittäneelle operaattorille tiedustelun, että näkevätkö mitään tarkempaa syytä tuolle.
---
Odotellaan siis edelleen vastausta. Nyt sitten ihan operaattorilta asti.

**Comment by PiaKusmin** [comment]
Nyt tuli vastaus operaattorilta: 
"Vastaanottajalla on rinnakkaisliittymä. Vaikka pääliittymälle tullut viesti on mennyt hylkyyn on se kerinnyt monistua rinnakkaisliittymälle ja siksi tavoittanut vastaanottajan. Pääliittymään ei näyttäisi onnistuvan viestit lainkaan. Käyttäjän on suositeltavaa tarkistaa asetukset laitteestaan."
-
 
Eli tässä meidän tapauksessa numeroon XXX-XXX viestin toimitus on epäonnistunut ja tästä syystä viestille on palautunut toimitusvirhe, mutta sen sijaan viesti on toimitettu kyseisen liittymän rinnakkaisliittymälle. Eli me emme voi tehdä muuta kuin laittaa asiakkaalle viesti, jossa kehotetaan tarkistamaan asetukset. Tai antaa asian vain olla.
