### ISSUE TITLE
Helle, uudet automaattitunnukset SIP2-palvelimelle

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1382]
### Tukipyyntö

Lisäättekö Hellen kolmen uuden automaatin tunnukset SIP2-palvelimelle. Lähetin automaattien tunnustiedot salattuna sähköpostina tukipostiin.

Automaatit asennetaan käyttöön 4.9.2024.

**Comment by lmstrand** [comment]
Tunnukset lisätty SIP-palvelimelle.
