### ISSUE TITLE
Kyyti: toisen kirjan tiedot valuneet tietueen päälle

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1385]
### Mikä vikana?

22.8.2024 on valunut Kyytin tietueen 1543191 päälle aivan eri teoksen tiedot. Tekijän ja teoksen nimet ja isbn-numerot ovat aivan eri. Mistä johtuu, että näin voi käydä? Onko tässä jotain, jota voi korjata, jotta näin ei kävisi jatkossa?

![vaarinvalunut](https://github.com/user-attachments/assets/0c993a0e-61fb-4b6f-a9fe-a4f6a31adcdd)

**Comment by AnneliO** [comment]
Tuossa tietueessa on aktivointiarvona 035a | (FI-BTJ)7450560. Tätiin on lisätty 22.08.2024 14:49 tietue 2475398, jossa on ollut tuo kyseinen 035a-kenttä:

biblio  BEFORE=>LDR 01217nam a22003494i 4500 001     2475398 003     FI-TATI 005     20240822144702.0 008     240822s2024    fi \|\|\|\|       \|0\| 0\|fin\|c 020    _a978-952-65298-0-6        _qpehmeäkantinen 035    _a(FI-BTJ)7450560 040    _aFI-Lumme        _bfin        _erda 041 0  _afin        _aeng        _ajpn 084    _a87.038        _2ykl 084    _a89.923038        _2ykl 084    _a89.5038        _2ykl 084    _a88.2038        _2ykl 100 1  _aOkabe-Silvasti, Chieko,        _ekirjoittaja,        _ekääntäjä. 245 10 _aKuka oli Erik Laxman? =        _bWho was Erik Laxman? /        _cChieko Okabe-Silvasti, Katriina Koponen, Riitta Moisander. 246 31 _aWho was Erik Laxman? 264  3 _aSavonlinna :        _bTott Print,        _c2024. 300    _a50 sivua :        _bkuvitettu ;        _c21 x 23 cm 336    _astillkuva        _bsti        _2rdacontent 336    _ateksti        _btxt        _2rdacontent 337    _akäytettävissä ilman laitetta        _bn        _2rdamedia 338    _anide        _bnc        _2rdacarrier 600 14 _aLaxman, Erik,         _d1737-1796.        _0(FI-ASTERI-N)000105635 700 1  _aKoponen, Katriina,        _ekirjoittaja. 700 1  _aMoisander, Riitta,        _ekirjoittaja. 700 1  _aAihara, Hideki,        _evalokuvaaja. 999    _c2475398        _d2475398 942    _687038__89923038__895038__882038

Ymmärtääkseni tässä on sitten syntynyt täsmäävyys 035a-kentän perusteella ja tietue on valunut. Tuo kyseinen tietue on poistettu TäTistä 22.08.2024 15:49.

Sanoisin, että tässä on kyseessä jonkinlainen inhimillinen erhe, mikäli tuo 035a-kentän arvo ei kuulu tuolle poistetulle tietueelle. Tai vaihtoehtoisesti 035a-kentän arvo on virheellinen Kyytin tietueessa. En nyt tiedä, mistä tuon voisi tarkistaa. :)

**Comment by AnttHeik** [comment]
Sama oli tapahtunut myös OUTIssa (tietuenumero 2346935). Minun veikkaus on, että Laxmanin tietue on tehty TäTiin tuon Arabia-kirjan pohjalta ja unohdettu ennen ensimmäistä tallennusta tyhjentää tietueen 035-kenttä, jossa oli tuo BTJ:n tunnus. Tämän takia tietue on valunut sitten väärin.

**Comment by Tuomas-Kyyti** [comment]
Kiitos selvityksestä. Ei siis aiheuta toimenpiteitä, muuta kuin tarkkuutta kuvailuun.
