### ISSUE TITLE
Helle, EditX-virheilmoitukset myös Lotalle ja Vilgotille

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1388]
### Tukipyyntö

Lisäättekö Hellen EditX-virhesanomien postituslistalle:
lotta.juvonen@sipoo.fi
vilgot.stromsholm@inkoo.fi

**Comment by lmstrand** [comment]
s-postiosoitteet lisätty procurement-config.xml-konfiguraatiotiedostoon.

**Comment by Kati-Helle** [comment]
Kiitos!
