### ISSUE TITLE
Asiakkaan vanhenemispäivämäärän valinnassa kummallisuus

### ISSUE THREAD

**Issue by atarnus** [KohaSuomi/Koha#1390]
### Mikä vikana?

Uutta asiakasta tallentaessa tälle on mahdollista tallentaa vanhenemispäiväksi mennyt päivämäärä. Tätä käytetään esim. virkailijatunnuksia luodessa, jotta tunnus ei ole voimassa ennen kuin salasana luovutetaan tunnuksen haltijalle. Tänään klikkasin vahingossa ensin 'Tullut asiakkaaksi' kenttää, ja tämän jälkeen vanhenemispäiväksi ei ollutkaan mahdollista enää valita aikaisempaa päivämäärä. Rajoite kytkeytyy nimenomaan 'Tullut asiakkaaksi'-kenttään.
1. Sitä täytyi hipelöidä, että mitään rajoitusta syntyi (varsinaisesti mitään päivämäärää ei tarvinnut valita, vaan klikkaaminen datepickerin ulkopuolelle, mikä jättää edellisen/oletuspäivämäärän kenttään, aiheutti saman asian.
2. Päivämäärän voi tallentaa nykyhetkestä menneisyyteen, kunhan vain ensin siirtää myös 'Tullut asiakkaaksi' päivää menneisyyteen.
3. Toistuu myös asiakasta muokatessa, ei vain luodessa.

Tämä mahdollisesti on "working as intended", ja vanhemman vanhentumispäivämäärän tallentamisen onnistuminen taas on se "bugi" (valmiiksi täytetty pvm ei kytke rajoitetta päälle)? Tarvinneeko tälle mitään tehdäkään?

### Kuinka toistaa ongelma/asia

1. Luo uusi asiakas tai muokkaa olemassa olevaa.
2. Huomioi 'Tullut asiakkaaksi' päivämäärä, mutta älä koske kenttään.
3. Katso 'Vanhenee' kenttää, ja huomaa, että voit valita datepickeristä liittymispäivää vanhempia päivämääriä.
4. Klikkaa 'Tullut asiakkaaksi' kenttää (tallenna uusi pvm tai anna vanhan olla).
5. Katso 'Vanhenee'-kenttää uudestaan, ja huomaa ettei enää ole mahdollista valita liittymispäivää vanhempia päivämääriä. Tällaisen päivämäärän kirjoittaminenkaan ei onnistu, vaan kenttä tyhjenee.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 25.9.2024: Käyttäjätunnus vanhenee sinä päivänä, mitä kenttään on valittu, joten saman päivän valitseminen tekee tunnuksen vanhentuneeksi. Saman päivän valitseminen onnistuu myös silloin, jos on käynyt avaamassa Tullut asiakkaaksi -päivämäärävalinnan. Kyseessä on siis lähinnä kosmeettinen haitta, joten ei koettu tarvetta korjata toimintoa.
