### ISSUE TITLE
OUTI: Varausten noutopäivien siirto 

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1391]
### Tukipyyntö

Karjasillan omatoimilaitteet ovat edelleen rikki eivätkä asiakkaat pääse noutamaan varauksiaan viikonloppuna 7.-8.9.2024. Varausten viimeiset noutopäivät tulisi siirtää maanantaille 9.9.2024.

Noutokirjasto: OUKS Karjasillan kirjasto
Varausten viimeinen noutopäivä muutetaan seuraavasti: 
la 7.9.2024 -> ma 9.9.2024
su 8.9.2024 -> ma 9.9.2024

### Jotain muuta?

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/1358

**Comment by piiaseme** [comment]
Milloin Pasi ehdit tehdä muutokset?

**Comment by paxed** [comment]
Tehty tällä rimpsulla: update reserves set expirationdate = "2024-09-09" WHERE branchcode = "OUKS" AND found='W' AND expirationdate in ("2024-09-07", "2024-09-08");

Muutos koski 38 varausta.

**Comment by piiaseme** [comment]
Kiitos, varausten noutopäivät näyttävät päivittyneen kuten pitää. Suljen tiketin.
