### ISSUE TITLE
Hakutuloslistan tietueiden nimien boldaukset kadonneet suomenkielisestä Kohasta, englannikielisellä puolella boldaukset ovat oikein

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1395]
### Mikä vikana?

Kohan testillä, nextillä ja tuotannossa on suomenkieliseltä puolelta kadonneet hakutuloslistan tietueiden nimien boldaukset. 
![kuva](https://github.com/user-attachments/assets/a1726396-0ee5-4087-8c32-f75520bada08)

Englannin kielen puolella boldaukset ovat ok tietueiden nimissä ja kaikissa Kohissa. 
![kuva](https://github.com/user-attachments/assets/b27c7624-5747-42ea-8888-3322d574fd78)

**Comment by paxed** [comment]
Ongelma on käännöstiedostossa.

MARC21slim2intranetResults.xsl tämä kohta:
`<xsl:attribute name="class">title</xsl:attribute>`
on käännettävää tekstiä jostain syystä:
`<xsl:attribute name="class">nimeke</xsl:attribute>`

En kyllä löydä mistä käännöstekstistä tuo oikein tulee...

**Comment by paxed** [comment]
Tämän voisi ehkä kiertää laittamalla IntranetuserCSS:ään jotain tähän tyyliin:

`#catalog_results #search_results a.nimeke { font-weight: bold }`

**Comment by AnneliO** [comment]
fi-FI-marc21.po-tiestostossa on käännettävänä "/cgi-bin/koha/catalogue/detail.pl?biblionumber=" -merkkijono, joka löytyy tästä xsl-tiedostosta:

koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slimUtils.xsl:98
koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slimUtils.xsl:110
koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slimUtils.xsl:208
koha-tmpl/intranet-tmpl/prog/en/xslt/MARC21slimUtils.xsl:654

Tuo on ehkä lähin, minkä löysin tähän liittyen. Mutta tuossa ei ole käännöstiedostossa mitään boldauksia alkuperäisessä eikä käännöksessä (joka on sama kuin alkuperäinen).

**Comment by paxed** [comment]
Se boldaus tulee staff-global.scss -tiedostosta, eli on kohan omaa CSS:ää.

**Comment by piiaseme** [comment]
Lisäsin rimpsun sellaisenaan OUTIn testille, mutta en saanut boldausta.

**Comment by paxed** [comment]
No siksi koska joku käännöstiedostojen teksti tarttuu siihen.

**Comment by paxed** [comment]
> Lisäsin rimpsun sellaisenaan OUTIn testille, mutta teksti ei boldautunut.

Korjasin outi-test:lle, mulla oli yksi ylimääränen alaviiva tuolla välissä.

**Comment by piiaseme** [comment]
Näyttäisi olevan nyt boldaukset kohillaan OUTIn testillä. Voin siis kopioida rimpsun ja lykätä OUTIn tuotantoonkin sellaisenaan, eikö niin?

**Comment by pknuuti** [comment]
Eli mitä pitää tehdä, että nuo boldaukset näkyy tuotannossa vai tehdäänkö jotain keskitetysti?

**Comment by piiaseme** [comment]
Lisäsin Pasin tekemän rimpsun OUTIn tuotantoon ja nyt näkyy boldilla hakutuloslistalla myös tietueen nimi ja mahdolliset tekijätiedot.
/* Boldaa hakutuloslistan nimet */
#catalog_results #searchresults a.nimeke { font-weight: bold }

**Comment by AnttHeik** [comment]
Perustiedot-näytöllä osakohteet eivät näy vielä boldattuina, vaikka englanninkielisessä näkyvät:

![kuva](https://github.com/user-attachments/assets/872066c2-44da-42fc-8796-32283691aaf7)

**Comment by piiaseme** [comment]
Hakutuloslistalla osakohteiden boldaus toimii. Teenkö uuden tiketin tästä?

> Perustiedot-näytöllä osakohteet eivät näy vielä boldattuina, vaikka englanninkielisessä näkyvät:
> 
> ![kuva](https://private-user-images.githubusercontent.com/116169663/365983506-872066c2-44da-42fc-8796-32283691aaf7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NjMxODksIm5iZiI6MTcyNTk2Mjg4OSwicGF0aCI6Ii8xMTYxNjk2NjMvMzY1OTgzNTA2LTg3MjA2NmMyLTQ0ZGEtNDJmYy04Nzk2LTMyMjgzNjkxYWFmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMFQxMDA4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MDA2MTQ0NDQ4NDIwM2YxMWU0OWQ5Mzc1ZjUwMWZiMGQxMGRjN2FjNDRhYzQ5NmZmNjhlOWUwMGI4YzBhYjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qk188E7oH19Q_g99B_W2f-BG2bKyiy-yC_V3t1715UA)

**Comment by AnneliO** [comment]
> No siksi koska joku käännöstiedostojen teksti tarttuu siihen.

Onkohan tämä ongelma ilmennyt samaan aikaan kuin tein tämän pieleen menneen muutoksen: #1404

**Comment by paxed** [comment]
> Perustiedot-näytöllä osakohteet eivät näy vielä boldattuina, vaikka englanninkielisessä näkyvät:
> 

On sama ongelma, eli linkin class pitäisi olla "title", mutta on kääntynyt suomeksi.

Tämä lienee korjannee asian, en ole testannut:

`#bibliodetails #components a.nimeke { font-weight:bold; }`

**Comment by AnneliO** [comment]
Lisäsin nämä rimpsut myös 24xx-tietovarannon [IntranetUserCSS-wikiin](https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserCSS#suositeltavat-4).

**Comment by piiaseme** [comment]
Rimpsut toimivat, sillä tietueiden nimet ovat nyt OUTIssa boldattuina (eng ja fin) Nextillä, testillä ja tuotannossa. Suljen tiketin.
