### ISSUE TITLE
LAPPI: Uusi omatoimilaitteisto tarvitsee SIP-tunnukset

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1399]
### Tukipyyntö

Utsjoen kirjastoon tulee omatoimi-laitteisto, jolle tarvitaan SIP-tunnukset. Tiedot lähetetty turvapostilla kehittäjien support-lootaan.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimele, ovat käytössä huomenna.

**Comment by PiaKusmin** [comment]
Kiitos! Suljen tiketin.
