### ISSUE TITLE
Vaski: IntranetUserJS-muutos

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1403]
### Tukipyyntö

Vaskin tuotantoon haluttaisiin seuraava uusi koodinpätkä IntranetUserJS-asetukseen (piilottaa asiakkaalta Reklamaatiot-välilehden silloin kun välilehdellä ei ole mitään näytettävää):

```
/* Reklamaatiot välilehden piilotus */
/* Teoriassa tehtävissä myös ccs:llä, kunhan Firefoxista saadaan käyttöön versio, joka tukee has() pseudoluokkaa */
$(document).ready(function() {
    if (window.location.pathname.includes('/cgi-bin/koha/circ/circulation.pl') || window.location.pathname.includes('/cgi-bin/koha/members/moremember.pl')){
      var reklamaatiot = $('span#return-claims-count-resolved').text() + $('span#return-claims-count-unresolved').text();
      if(reklamaatiot === '00') {
        $('a#return-claims-tab').hide();
      }
    }
});
```

Onnistuuko lisääminen jo tällä viikolla vai meneekö seuraavan viikkopäivityksen yhteyteen?

**Comment by emta001** [comment]
Onnistuu tälläkin viikolla, toki huoltokatkon aikaan ei kannata tehdä :smile: Mutta voidaan sopia jokin hetki, jolloin käyn laittamassa checksummauksen pois päältä ja takas päälle, kunhan rimpsu on paikallaan. Esimerkiksi torstaiaamu.

**Comment by ajrajala** [comment]
Torstaiaamu on hyvä. 👍 Huikkaatko tikettiin kun on pois päältä ja voin käydä lisäämässä?

**Comment by emta001** [comment]
> Torstaiaamu on hyvä. 👍 Huikkaatko tikettiin kun on pois päältä ja voin käydä lisäämässä?

Voisin huikata vaikka Elementsiin mieluummin, sieltä sen huomaa ehkä helpommin.

**Comment by ajrajala** [comment]
IntranetUserJS-asetukset päivitetty, suljen tiketin.
