### ISSUE TITLE
Uuden automaattitunnuksen lisääminen SIP-palvelimelle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1405]
### Tukipyyntö

Tiedot lähetetty support-postiin.

**Comment by ajrajala** [comment]
Jes, kiitos!

**Comment by ajrajala** [comment]
Laitoin tunnukset aamulla hultokatkon päättymisen jälkeen toimittajalle, sieltä tuli viestiä (hiukan 9:00 jälkeen) etteivät toimisi. Katsoin, että olin muistanut lisätä käyttöoikeudet tunnukselle Kohassa, ja olin lähettänyt samat tiedot kuin mitä support-postiin. Onko mahdollista, että tunnus ei olisi sittenkään vielä toiminnassa?

**Comment by emta001** [comment]
> Laitoin tunnukset aamulla hultokatkon päättymisen jälkeen toimittajalle, sieltä tuli viestiä (hiukan 9:00 jälkeen) etteivät toimisi. Katsoin, että olin muistanut lisätä käyttöoikeudet tunnukselle Kohassa, ja olin lähettänyt samat tiedot kuin mitä support-postiin. Onko mahdollista, että tunnus ei olisi sittenkään vielä toiminnassa?

Taitaa olla miun moka ihan puhtaasti. Mielestäni tallensin tunnukset eilen palvelimelle, mutta ei niitä siellä näy. Pahoittelut, voitko laittaa ne uudestaan? Salasana varmaan on vaihdettava.

**Comment by ajrajala** [comment]
Eipä mitään, ei ollut kiireellinen tunnusasia. :) Vaihdoin salasanan ja laitoin äsken uudestaan support-postiin. Menee varmaan niin, että olisi sitten huomenna toiminnassa?

**Comment by emta001** [comment]
> Eipä mitään, ei ollut kiireellinen tunnusasia. :) Vaihdoin salasanan ja laitoin äsken uudestaan support-postiin. Menee varmaan niin, että olisi sitten huomenna toiminnassa?

Jeppis, nyt on tunnarit tallennettu (ja varmistettu kolmeen kertaan että ovat paikallaan :smile:). Ovat käytössä tosiaan huomenna.

**Comment by ajrajala** [comment]
Hienoa, kiitos triplatsekkauksesta. 😄
