### ISSUE TITLE
Vaari-tunnukset

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha#1406]
### Tukipyyntö

Lisää Vaari-tunnukset Tietuesiirtäjään

**Comment by johannaraisa** [comment]
Taidan tehdä tämän niin, että ei tarvitse kopioida tunnuksia. Liitän jotenkin Vaarin Melindaan.

**Comment by johannaraisa** [comment]
Tätä on testattu ja toimii, testitunnuksella ei ollut vain oikeutta laittaa aineistoa Vaariin.

**Comment by AnneliO** [comment]
Tarviiko tämä vielä testausta vai voiko tiketin sulkea?
