### ISSUE TITLE
Kaikki tietuepaketit eivät ole valuneet TäTiin tänään

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1409]
### Mikä vikana?

TäTin välivarastoon oli tullut vain yksi tietuepaketti tänään, mutta toinen puuttuu kokonaan. Saisiko nuo liikkeelle jossain välissä?

### Mitä pitäisi tapahtua

Tietuepakettien valuminen Tätiin tapahtuu joka yö ja sen jälkeen tietueet valuvat paikalliskantoihin. Nyt ei ollut OUTIin valunut, josta syystä hoksattiin katsoa TäTin tilanne.

**Comment by johannaraisa** [comment]
Nyt tämän päivän paketit on tuota uudestaan, tuossa tarvitaan indeksiä joten siirrot oli sen takia keskeytyneet.

**Comment by AnttHeik** [comment]
Tämä on kunnossa. Voi sulkea tiketin :)
