### ISSUE TITLE
Indeksihäiriö 12.9.

### ISSUE THREAD

**Issue by CodoDerDritte** [KohaSuomi/Koha#1410]
### Mikä vikana?

Tuotannon indeksit olivat 12.9. aamulla hävinneet. Indeksit palautettiin varmuuskopioista, mutta myös osa varmuuskopioista oli korruptoitunut. Indeksointi joudutaan tästä syystä tekemään uudestaan Lapissa, Outissa ja Vaskissa.

**Comment by CodoDerDritte** [comment]
Indeksien dumppaus on otettu pois käytöstä nyt kaikissa muissa kimpoissa paitsi siilissä. Toimenpiteen tarkoituksena on varmistaa ettei itse dumppaus aiheuta nyt näitä ongelmia.

**Comment by CodoDerDritte** [comment]
Lapin indeksointi on käynnissä. Lapissa kannattaa tänään käyttää tiedonhakuihin Finnaa, koska Kohan haku on melko puutteelllinen. Vaskin ja Outin indeksoinnit käynnistyvät tänään illalla kirjastojen sulkemisen jälkeen ja huomenna aamulla meillä on (toivottavasti) sitten toimivat indeksit kaikissa kimpoissa.

**Comment by johannaraisa** [comment]
Poistin 12.9. dumpit ja kopioin 11.9. ksstaffiin varmuudenvuoksi.
