### ISSUE TITLE
Asiakkaan palauttaminen deletedborrowers-taulusta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1411]
### Tukipyyntö

Kirjastossa oli vahingossa poistettu asiakastietue, borrowernumber 176450. Onko mahdollista saada asiakastietue palautettua?

**Comment by johannaraisa** [comment]
Saa tämän tuotua takaisin borrowers-tauluun, mutta historia on tainnut hävitä poistossa.

**Comment by ajrajala** [comment]
Voisi palauttaa siitä huolimatta, saadaan sitten kuitenkin edes muuten tiedot takaisin.

**Comment by johannaraisa** [comment]
Nyt on palautettu:
```sql
insert into borrowers select * from deletedborrowers where borrowernumber = 176450;
```
Ja poistettu rivi deletedborrowers-taulusta.

**Comment by ajrajala** [comment]
Kiitos!
