### ISSUE TITLE
Siilin indeksissä vielä jotain vialla?

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#1415]
### Mikä vikana?

Siilin tiedonhaussa löytyy vielä aineistoa, jota on poistettu loppuviikosta 37. Kun tietuetta yrittää avata, tulee aivan oikein ilmoitus esim. "Tietuetta 22987 ei ole tietokannassa." Tämä liittynee indeksihäiriöön #1410 ?

Voi todentaa esim. tekijähaulla Pitkänen, Jope, hänen vanhemmilla teoksillaan.

**Comment by lmstrand** [comment]
Tehdään indeksi uusiksi tänään illalla.

**Comment by johannaraisa** [comment]
Tämä taitaa olla kunnossa?

**Comment by ReettaSiili** [comment]
Tuntuu olevan. Suljen tämän, kiitos!
