### ISSUE TITLE
Vanhentuneet maksut -raportin korjaus

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha#1417]
### Tukipyyntö

Kohan Raporttikirjastossa olevan SQL-raportin "Vanhentuneet maksut" ajo aiheuttaa virheilmoituksen. Raportin korjausta toivotaan.

**Comment by emta001** [comment]
Tiistaina asennettiin tietoturvapaikka, joka estää asiakkaan salasanan hakemisen tietokannasta raporteilla. Tuossa raportissa pitää korvata `borrowers.*` niillä sarakkeilla, jotka asiakkaasta halutaan tulostaa. Nythän tuo tulostaa ne kaikki. Esim. `borrowers.firstname`, `borrowers.surname` jne. Ainakin nuo varmaan on semmosia mitä halutaan tulostaa, muista sarakkeista en oikein osaa arvata mitkä olisi tässä tarpeellisia. Lisäsin nuo rapsaan, muut sarakkeet löytyvät Kohan [skeemasta](https://schema.koha-community.org/23_11/tables/borrowers.html).

Lisäksi tuossa vaikuttaisi olevan toinenkin virhe. Tässä ehdossa ei ole oikein järkeä.
>AND accountlines.accounttype LIKE <<asiakastyyppi TAI syötä %-merkki jos haluat kaikki>>

Sarake `accountlines.accounttype` kertoi maksuntyypin, ei asiakastyyppiä. Eikä `accounttype`-saraketta ole enää edes olemassa, se on korvattu sarakkeilla `credit_type_code` ja `debit_type_code`. Kattelin raporttikirjastosta tuota ja siellä ohjeistuksessa lukee 
><<accounttype TAI syötä %-merkki jos haluat kaikki>> 

Eli jos tuossa halutaan tutkia maksuntyyppiä, olisi käytettävä `accountlines.debit_type_code`. Jos taas halutaan asiakastyyppi, niin `borrowers.categorycode`.
