### ISSUE TITLE
Kyytin raportit 833 ja 1132

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha#1418]
### Tukipyyntö

Jos hakee raportilla 833 esimerkiksi niteet luokasta 84.2 luokkaan 84.3 saa tuloksia 12700.

Jos taas hakee raportilla 1132 niteet luokasta 84.2 luokkaan 84.3 ja Excelissä suodattaa tuloksia niin, että aineistolaji on kirja, sijaintikirjasto on KOT_PK ja onloan on NULL saa tulokseksi 12741 riviä.

Ajattelin että myös tuo superpoistaja raportti 833 ottaisi tuloksiin kaikki Kotkan pääkirjastossa parhaillaan sijaitsevat aikuisten hyllypaikalla olevat kirjat, jotka eivät ole tällä hetkellä lainassa, mutta jostain näihin tulee pieni ero. Olen koittanut tutkia mistä tuo ero voisi tulla, mutta en osaa tuota raporttia 833 varmaan tulkita oikein, kun on sen verran monimutkainen.

**Comment by johannaraisa** [comment]
Tuossa 833 raportissa tarkastetaan myös nämä

```sql
AND i.itemlost = '0'
AND NOT notforloan IN (3,4,5,6,7)
```
Voisiko noita olla mukana siinä 1132 raportissa?

**Comment by johannaraisa** [comment]
Tai ehkä lähinnä tuo itemlost, sen notforloan NULL pitäisi kai poissulkea nuo notforloanit.

**Comment by johannaraisa** [comment]
Tuossa 1132 raportissa otetaan huomioon vain niteet jotka ovat lainassa, siellä on tällainen.

```sql
LEFT JOIN issues ON (items.itemnumber=issues.itemnumber)
```

**Comment by johannaraisa** [comment]
> Tuossa 1132 raportissa otetaan huomioon vain niteet jotka ovat lainassa, siellä on tällainen.
> 
> ```sql
> LEFT JOIN issues ON (items.itemnumber=issues.itemnumber)
> ```

Jos halutaan ei lainassa olevat, niin tuo joini pitäisi poistaa. Minusta 833 raportissa yritettiin etsiä juuri niitä jotka eivät ole lainassa, siellä oli _i.onloan is null_.

**Comment by VaisanRo** [comment]
Lisäsin tuohon 833 raporttiin nyt myös nuo AND i.itemlost = '0'
AND NOT notforloan IN (3,4,5,6,7) koska ne olisi hyvä saada mukaan myös tuohon 833 raporttiin. Siinä olisi tarkoituksena saada tieto kaikista tietyssä luokassa aikuisten hyllypaikalla olevista niteistä joiden sijaintikirjasto on Kotkan pääkirjasto ja jotka ovat nyt hyllyssä saatavina. Jotta saataisiin tieto kuinka monta nidettä meillä on tietyssä luokassa aikuisten hyllypaikalla. Kuitenkaan ei voi käyttää kotikirjastoa rajaamiseen, koska meillä on kelluva kokoelma muiden Kotkan toimipisteiden kanssa niin siksi pitäisi käyttää tuota sijaintikirjastoa. Lisäksi tarvittaisiin tieto kuinka moni Kotkan pääkirjaston niteistä on lainassa. Tässäkin on kuitenkin haasteena tuo yhteinen kokoelma, että minkä mukaan tehdään rajaus. Tuolla LEFT JOIN issues ON (items.itemnumber=issues.itemnumber) koitettiin saada issues taulu liitettyä kyselyyn, jotta olisin saanut kaikki Kotkan pääkirjastosta lainatut niteet tuloksiin. Tarkoituksena olisi kuitenkin saada tuloksiin kaikki niin lainassa olevat kuin hyllyssä olevat niteet. Eli tuota taulujen liitosta pitäisi sitten varmaan muuttaa jotenkin?

**Comment by AnneliO** [comment]
Oletteko kokeilleet hakea noita tietoja nidehaulla? Siinä voi rajata myös hyllyssä oleviin ja lainassa oleviin?

**Comment by johannaraisa** [comment]
> Tuossa 833 raportissa tarkastetaan myös nämä
> 
> ```sql
> AND i.itemlost = '0'
> AND NOT notforloan IN (3,4,5,6,7)
> ```
> 
> Voisiko noita olla mukana siinä 1132 raportissa?

Minun piti kokeilla suoraan tietokannassa lauseella missä on nuo excelissä tehdyt suodatukset siinä sql:ssä. Saan saman tulokset kuin tuolla 833 raportilla, eli niitä niteitä oli 12660 sillä hetkellä kun kokeilin. Tuo oli varmaankin juuri noista kahdesta rivistä kiinni.

**Comment by VaisanRo** [comment]
> Oletteko kokeilleet hakea noita tietoja nidehaulla? Siinä voi rajata myös hyllyssä oleviin ja lainassa oleviin.

Nidehaussa ei pysty rajaamaan tuloksia sen mukaan mistä pisteestä nide on lainattu, eikä siinä pysty suodattamaan tuloksia aineistotyypin mukaan.

**Comment by VaisanRo** [comment]
> > Tuossa 833 raportissa tarkastetaan myös nämä
> > ```sql
> > AND i.itemlost = '0'
> > AND NOT notforloan IN (3,4,5,6,7)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Voisiko noita olla mukana siinä 1132 raportissa?
> 
> Minun piti kokeilla suoraan tietokannassa lauseella missä on nuo excelissä tehdyt suodatukset siinä sql:ssä. Saan saman tulokset kuin tuolla 833 raportilla, eli niitä niteitä oli 12660 sillä hetkellä kun kokeilin. Tuo oli varmaankin juuri noista kahdesta rivistä kiinni.

Okei, eli tuo LEFT JOIN issues ON (items.itemnumber=issues.itemnumber) ei kuitenkaan sotke tuota vaan pitäisi toimia niin, että näyttää kaikki Kotkan pääkirjastolla tällä hetkellä hyllyssä olevat, mutta sitten lisäksi pystyy rajaamaan myös kaikki tällä hetkellä lainassa olevat, jotka on lainattu Kotkan pääkirjastosta luotettavasti?

**Comment by johannaraisa** [comment]
> > > Tuossa 833 raportissa tarkastetaan myös nämä
> > > ```sql
> > > AND i.itemlost = '0'
> > > AND NOT notforloan IN (3,4,5,6,7)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Voisiko noita olla mukana siinä 1132 raportissa?
> > 
> > 
> > Minun piti kokeilla suoraan tietokannassa lauseella missä on nuo excelissä tehdyt suodatukset siinä sql:ssä. Saan saman tulokset kuin tuolla 833 raportilla, eli niitä niteitä oli 12660 sillä hetkellä kun kokeilin. Tuo oli varmaankin juuri noista kahdesta rivistä kiinni.
> 
> Okei, eli tuo LEFT JOIN issues ON (items.itemnumber=issues.itemnumber) ei kuitenkaan sotke tuota vaan pitäisi toimia niin, että näyttää kaikki Kotkan pääkirjastolla tällä hetkellä hyllyssä olevat, mutta sitten lisäksi pystyy rajaamaan myös kaikki tällä hetkellä lainassa olevat, jotka on lainattu Kotkan pääkirjastosta luotettavasti?

Ei, se ei sotke. Excelin suodatuksilla sen rajaamisen pitäisi onnistua. Tosin tietokanta elää kokoajan ja excel ei saata koko ajan olla ajantasalla.

**Comment by AnneliO** [comment]
> > Oletteko kokeilleet hakea noita tietoja nidehaulla? Siinä voi rajata myös hyllyssä oleviin ja lainassa oleviin.
> 
> Nidehaussa ei pysty rajaamaan tuloksia sen mukaan mistä pisteestä nide on lainattu, eikä siinä pysty suodattamaan tuloksia aineistotyypin mukaan.

Sijaintikirjasto on aina lainauskirjasto silloin kun nide on lainassa. Tuloksia ei pysty suodattamaan aineistotyypin mukaan, mutta aineistotyyppi valinnan pystyy tekemään kyllä ennakkoon.

**Comment by AnneliO** [comment]
> Niin joo totta ajattelin tuon jotenkin liian vaikeasti. Miten tuon aineistotyypin saa ennakkoon valittua? Tai kun tuolla on vain tuo nidetyyppi valinta?

Aineistotyypin voi lisätä Räätälöityihin hakukenttiin (Viivakoodi-valikko) eli ylläpidossa [Nidehakukentät](https://kyyti.koha-suomi.fi/cgi-bin/koha/admin/items_search_fields.pl). Vaikka se kyllä teillä siellä näyttääkin olevan. :)

**Comment by VaisanRo** [comment]
> > Niin joo totta ajattelin tuon jotenkin liian vaikeasti. Miten tuon aineistotyypin saa ennakkoon valittua? Tai kun tuolla on vain tuo nidetyyppi valinta?
> 
> Aineistotyypin voi lisätä Räätälöityihin hakukenttiin (Viivakoodi-valikko) eli ylläpidossa [Nidehakukentät](https://kyyti.koha-suomi.fi/cgi-bin/koha/admin/items_search_fields.pl). Vaikka se kyllä teillä siellä näyttääkin olevan. :)

No niimpä olikin, en vain hoksannut katsoa oikeasta kohdasta. Eli jep nidehaulla olisi saanut ihan saman tuloksen kuin tuolla raportilla. Pitää ensi kerralla tutkia ensin nidehaun mahdollisuuksia ennen kuin käy tekemään raporttia. Sulejn tiketin, kiitos kummallekin avusta! 😊
