### ISSUE TITLE
Osakohteiden näkymisessä emokohteessa ongelmia, jos osakohteen taso on d

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha#1419]
### Mikä vikana?

Lastussa on hieman reilu 300 000 osakohdetta, joilla on bib-level:d. Nämä ilmeisesti linkittyvät emokohteisiin, mutta eivät tule näkyviin emokohteen tietueessa "Osakohteet"-välilehdellä. Tämä johtuu ilmeisesti siitä, että d-taso on rajattu pois haussa jossa Koha hakee osakohteet mukaan.

Koha-Suomen kehittäjät ovat tästä keskustelleet, ja tavoite korjata tämä tekemällä pieni koodimuutos Kohaan.

**Comment by johannaraisa** [comment]
Laitan tämän tänä iltana tuotantoon.

**Comment by johannaraisa** [comment]
Tämä on viety tuotantoon.

**Comment by AnneliO** [comment]
@LastuJanneS jos tämä on mielestäsi ok, niin suljetko tiketin? :)
