### ISSUE TITLE
Helle: Lapinjärven kirjaston voimassa olevien varausten keskeytys

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1424]
### Tukipyyntö

Keskeytättekö nyt Lapinjärven kirjaston voimassa olevat varaukset (ei tärpänneet, ei keskeytetyt).

Lapinjärven kirjaston tunnus
LAPPK

Keskeytys 1.11.2024 asti.

**Comment by paxed** [comment]
Tehty tällä rimpsulla:

update reserves set suspend=1, suspend_until='2024-11-01' where branchcode = 'LAPPK' AND found IS NULL AND (suspend = 0 OR (suspend = 1 AND suspend_until BETWEEN '2024-09-23' AND '2024-11-01'));

Kosketti 174 varausta.

**Comment by Kati-Helle** [comment]
Kiitos :)
