### ISSUE TITLE
Vaara: Viesti huoltajalle, jonka huollettavalla ei ole hetua tiedoissa

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#1425]
### Tukipyyntö

Vaara-kirjastojen asiakaspalvelutyöryhmä toivoo, että 30.9. lähetettäisiin sähköpostiviestit kaikille niille huoltajille, joitten huollettavilla ei ole hetua tallennettuna. Viestissä pitäisi olla mainittuna huollettavan etunimi/-nimet. Meillä on viestin teksti valmiina. Ajankohta ei ole päivän tarkka. Miten edetään? 

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/865

**Comment by arimak100** [comment]
Ottakaa nuo s-postit raportilla ulos ja laittakaa sitä kautta noille asiakkaille. Koha-Suomella ei ole omaa s-postipalvelinta. Meidän kautta lähtee vain järjestelmän luomat viestit.
