### ISSUE TITLE
UpdateItemLocationOnCheckout-asetus ei toimi, kun niteessä varaus

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1427]
### Mikä vikana?

Testasin Lumpeille UpdateItemLocationOnCheckout-järjestelmäasetusta, jonka pitäisi vaihtaa hyllypaikka paikasta X paikkaan Y lainauksen yhteydessä. Tätä ei kuitenkaan tapahdu, jos lainattavassa niteessä on aktiivinen varaus - olipa kyseessä varauksen ohitus toiselle asiakkaalle tai niteen lainaus niteen varanneelle asiakkaalle. 

![Tilanahtaus](https://github.com/user-attachments/assets/09ec7427-a834-4866-9445-8532f6c25a9d)

### Mitä pitäisi tapahtua

Kun UpdateItemLocationOnCheckout-asetukseen on laitettu sääntö, jossa hyllypaikka vaihtuu paikasta X paikkaan Y lainauksen yhteydessä, tämän pitäisi tapahtua myös silloin, kun niteeseen on varaus.

### Kuinka toistaa ongelma/asia

1. Valitse nide tietueesta, jossa on varaus tai tee sellainen.
2. Vaihda jonkin niteen hyllypaikaksi Tilanahtaus aikuiset.
3. Lainaa kirja asiakkaalle.
4. Hyllypaikka pysyy edelleen Tilanahtaudessa, vaikka sen pitäisi vaihtua hyllypaikkaan Aikuiset.

**Comment by AnneliO** [comment]
Testasin tätä outi-nextillä siellä hyllypaikka vaihtuu lainatessa, oli tietueeseen varausta tai ei.

Voiskohan tässä nyt jotenkin sekottaa se, että Lumpeissa käytössä on myös CART-tila?

**Comment by AnneliO** [comment]
> Voiskohan tässä nyt jotenkin sekottaa se, että Lumpeissa käytössä on myös CART-tila?

Jeps, otin lumme-nextillä pois  UpdateItemLocationOnCheckin -järjestelmäasetuksesta säännön _ALL_: CART ja hyllypaikka rupesi vaihtumaan lainatessa.

**Comment by Hanna-Lumme** [comment]
Onkohan tässä sitten tosiaan jonkinlainen bugi? Testailin lisää testillä ja tosiaan tuo hyllypaikka kyllä vaihtuu ihan oikeasti silloin, kun lainattavassa niteessä ei ole varausta. 🤔

**Comment by AnneliO** [comment]
Testasin tätä nyt uudelleen lumme-nextillä ja Tilanahtaus-hyllypaikka muuttui Aikuiset-hyllypaikaksi lainatessa.

https://lumme-next.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=3154643 nide JJR20240500404

UpdateItemLocationOnCheckin -asetuksessa on \_ALL_: CART
UpdateItemLocationOnCheckout -asetuksessa on TILVA: A

Eli nyt tämä toimiikin ihan oikein?

**Comment by Hanna-Lumme** [comment]
Tsekkasin vielä testillä, ja ainakaan testillä ei toimi. 🤔 Eli onkohan joku muutos tullut versionvaihdossa? Sen bongasin, että testillä näkyy kotikirjaston kohdalla "Mikkelin pääkirjasto _Aikuiset (Tänään palautettu)_". Nyt tuosta nextillä olevasta tietueesta on tipahtanut se hyllypaikka pois - näkyy vain "Mikkelin pääkirjasto _Tänään palautettu_".

**Comment by AnneliO** [comment]
Miekin testasin testillä ja sielläkin se minusta toimi. Testasin samalla tietueella kuin nextillä.

**Comment by Hanna-Lumme** [comment]
Näyttää tämä asetus toimivan muutaman päivän miettimistauon jälkeen kaikissa kolmessa Kohassa. 😄
