### ISSUE TITLE
Vanhojen voimassa olevien varausten voimassaolon muuttaminen ajona kolmesta vuodesta viiteen vuoteen

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1430]
### Tukipyyntö

Koha-Suomen asiantuntijaryhmässä päätettiin 25.9.2024, että muutetaan varausten oletusvoimassaoloaika Kohassa ja Finnassa viiteen vuoteen. Muutetaan ajolla jo olemassa olevien varausten voimassaoloajaksi viisi vuotta tekopäivästä.

Samassa kokouksessa sovittiin myös, että Piia Semenoff on yhteydessä Finna-toimistoon ja pyytää kaikille kimpoille voimassaoloajan muutoksen viiteen vuoteen.

Kimppojen pääkäyttäjät kommentoivat tähän tikettiin, kun järjestelmäasetus DefaultHoldExpirationdate on muutettu ja ajo voidaan tehdä.

**Huom. Tämä on pääkäyttäjäpalaverin 1.10.2024 asialistalla, joten laitetaan työ etenemään vasta palaverin jälkeen, jos siellä sovitaan esim, aikataulusta tarkemmin.**

### Jotain muuta?

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/1350
Aiemmin varausten voimassaoloajan pidennyksestä tehty tiketti: https://github.com/KohaSuomi/Koha/issues/451

**Comment by piiaseme** [comment]
Otetaan huomioon, jos asiakas on valinnut jonkin tietyn varauksen voimassaolopäättymispäivän, kun tehdään Kohassa ajo.

**Comment by piiaseme** [comment]
> Samassa kokouksessa sovittiin myös, että Piia Semenoff on yhteydessä Finna-toimistoon ja pyytää kaikille kimpoille voimassaoloajan muutoksen viiteen vuoteen.
> 
Sähköpostia Finna-toimistoon lähetetty 1.10.2024

**Comment by AnneliO** [comment]
Kommentoi tikettiä, kun omaan kimppaan on muutettu DefaultHoldExpirationdate-järjestelmäasetukseen 5 vuotta.

Asetus muutettu:

- [ ] Lappi
- [ ] OUTI
- [ ] Siili
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Lastu
- [ ] Vaski

Ajo tehty:

- [ ] Lappi
- [ ] OUTI
- [ ] Siili
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Lastu
- [ ] Vaski

**Comment by johannaraisa** [comment]
Skripti ajoon löytyy utilitystä, set_expirationdate_for_holds.pl

**Comment by LastuJanneS** [comment]
Lastuun muutettu DefaultHoldExpirationdate 5 vuotta.

**Comment by piiaseme** [comment]
Ehdolla olisi Finnassa tehtävälle muutokselle ma 7.10. 
Tuo pvm on ok Vaaralle, Hellelle, Lastulle, Lummelle, Kirkesille, OUTIlle ja Vaskille. 

Sopiiko tuo pvm myös Lapille, Siilille ja Kyytille?

**Comment by Tuomas-Kyyti** [comment]
> Sopiiko tuo pvm myös Lapille, Siilille ja Kyytille?

Pannaan sopimaan Kyytille. Muutan asetuksen huomenna Kohaan ja tänään lähtee pikaisesti kyhätty tiedotus.

**Comment by LeenaKinnunen** [comment]
Lapille sopii.

**Comment by ReettaSiili** [comment]
Siilissä asetus muutettu.
Meillä on myös laskutuksessa oleviin aineistoihin varauksia, joilta puuttuu tarkoituksella vanhenemispäivä. Mikäli mahdollista, voisivatko nämä jäädäkin ilman päivämäärää?

**Comment by piiaseme** [comment]
Kaikille kimpoille sopii ma 7.10., joten viestin Finna-toimistoon, että muutoksen voi tehdä silloin kaikille kimpoille. Ja Finna-toimisto vastasi samalla tarkempaan aikataulukysymykseeni, että tekevät Finnassa muutoksen kaikille klo 9-12.

**Comment by pknuuti** [comment]
Vaaraan tehty muutos.

**Comment by ElinaUotila** [comment]
Kirkesiiin on muutettu DefaultHoldExpirationdate 5 vuotta.

**Comment by ajrajala** [comment]
Vaskiin tehty asetusmuutos.

**Comment by johannaraisa** [comment]
Ajastan cronin tekemään tämän tänä iltana.

**Comment by piiaseme** [comment]
Muutostyö on valmis kaikilla kimpoilla Finnassa ja Kohassa, joten suljen tiketin.

**Comment by ElinaUotila** [comment]
Kirkesissä on Auroran aikana ja Kohan alkuaikoina tullut vielä Finnasta varauksille kahden vuoden voimassaoloaikoja. Voisiko ne vielä muuttaa viideksi vuodeksi?

**Comment by johannaraisa** [comment]
> Kirkesissä on Auroran aikana ja Kohan alkuaikoina tullut vielä Finnasta varauksille kahden vuoden voimassaoloaikoja. Voisiko ne vielä muuttaa viideksi vuodeksi?

Joo, onnistuu. Ajastan tuon tälle illalle.

**Comment by ElinaUotila** [comment]
Ajo on tehty, suljen tiketin uudestaan :)
