### ISSUE TITLE
000-kentän muokkaaminen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1433]
### Tukipyyntö

Ainakin Vaarassa on tietueita, joiden koodaus 000-kentässä ei ole synkronissa aineistotyypin kanssa (kenttä 942c). Erämuokkauksella voi muokata muita kiinteämittaisia kenttiä, kun antaa niille koko rivin rimpsun korjaukseksi, mutta 000 (leader) ei toimi samalla tavalla. Jos poistaa 000-kentän sisällön ja lisää uuden sisällön, tulee jostain syystä ylimääräinen LDR-nimetty kenttä tietueelle. Jos taas yrittää muokata LDR-kenttää tyhjentämällä sen ja lisäämällä LDR-kenttään oikeanlaiset koodit, saa vain virheilmoituksen "Nimeketietuetta xxxxx ei muokattu. Muokkauksen aikana tapahtui virhe. (Field LDR must have indicators (use ' ' for empty indicators) at /home/koha/Koha/Koha/[SimpleMARC.pm](http://simplemarc.pm/) line 215. )"

Saisiko 000-kenttää muokattua oikeanlaiseen aineistotyypin muotoon esim. regex-korvauksella? Tai jotenkin muuten?

**Comment by AnneliO** [comment]
Tähän asti kokeiltua:

- tein muokkauspohjan, jossa ensin poistetaan LDR$@ ja 000$@ ja sitten lisätään 000$@ jollain sisällöllä. Tällä sain lisättyä kyllä uuden 000-kentän, mutta erämuokkauksessa esikatselussa näkyy aina LDR-rivi, joka on tietueen nykyinen nimiö. Erämuokkauksen  jälkeen tietueella on kaksi 000-kenttää.
- kysyin yhteisön Mattermostissa Cataloguing-palstalla, onko nimiön muokkaus ylipäätään mahdollista.

**Comment by AnneliO** [comment]
Eipä tuolta yhteisön palstalta tullut tähän oikein mitään apua. Ilmeisesti muualla ovat käyttäneet MarcEdit-ohjelmaa tietueiden 000-kenttien muokkaamiseen ja tuoneet tietueet sitten takaisin Kohaan.

Eli käytännössä 000-kentät pitää muokata kehittäjien tekemillä ajoilla tai opetella käyttämään tuota MarcEdit-ohjelmaa. 

Ehkä tuosta 000-kentän muokkaustarpeesta voisi tehdä tiketin yhteisöön?

**Comment by AnttHeik** [comment]
Ilmeisesti Alma-kirjastoissakin on tuo MarcEdit-käytössä, kun ovat tällaiset ohjeetkin tai koulutuksen väsänneet: https://wiki.helsinki.fi/xwiki/bin/view/lumikko/Suomen%20Alma-kirjastot/Lumikko-Alma%20kuvailu%20%28Copy%29/Kotimaiset%20e-aineistot/MarcEdit-koulutus/

Noista kiinteitä pitäisi kyllä pystyä muokkaamaan muitakin suoraan tietystä merkkipaikasta. Vaikka 006 ja 007 nyt meneekin joten kuten, niin 008 on paljon hankalampi. Pitäisikö jokaiselle kiinteälle kentälle olla oma tikettinsä vai voiko tehdä vain yhden?

**Comment by AnneliO** [comment]
Mie tekisin jokaisesta kentästä erillisen tiketin, koska silloin niitä on helpompi seurata ja suunnitella. Yksi tiketti, joka sisältää useita hyvin erilaisia tehtäviä menevät helposti tosi sekaviksi ja kukaan ei pysy perässä, mitä on tehty ja minne ja onko vielä jotain tekemättä. :)

**Comment by AnttHeik** [comment]
Aivan, eli sitä ei pysty ohjelmoimaan siten, että haluan muuttaa tässä kyseisessä kiinteässä kentässä just tätä merkkipaikkaa :)

**Comment by AnneliO** [comment]
En kyllä osaa sanoa teknisesti, mutta muutostenhallinan kannalta (ja suorittajan pään suojelemiseksi :D) pitäisin hommat pienempinä pompseina. Meillä on näitä kilometritikettejä historian varrella ollut ja ne tahtoo venyä ja vanua, koska kukaan ei enää tiedä, mitä pitäisi tehdä ja minne. :)

**Comment by AnneliO** [comment]
Näyttäis vähän siltä, että Kohan tietueiden erämuokkauksella nimiön muokkaus ei nyt tule onnistumaan, joten olisiko sama sulkea tämä tiketti?

**Comment by pknuuti** [comment]
Joo, suljen tiketin.
