### ISSUE TITLE
Kentän 490 haettavuus

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#1435]
### Kehitysehdotukseni

490-kentässä ollaan ottamassa käyttöön osakenttiä y (virheellinen ISSN) ja z (peruttu ISSN). Nämä pitäisi saada haettaviksi. Lisäksi näyttää olevan niin, että 490-kentässä x (ISSN) ei ole tälläkään hetkellä haettavissa.

**Comment by AnneliO** [comment]
Indeksointi- ja tiedonhakuryhmä 23.10.2024:

Lisätään Koha-Suomen omaan mappings.yaml-tiedostoon seuraavat mäppäykset samoilla säädöillä kuin aiemmilla issn-indeksien mäppäyksillä on:

canceled-issn: 490z
incorrect-issn: 490y
issn: 490x

Lisäksi yhteisöstä on tulossa versioon 24.11 issn-all-indeksi, josta todettiin, että sen kanssa ei ole kiire.

**Comment by AnneliO** [comment]
Pitäisikö tämä muutos saada mukaan jo marraskuun versionvaihtoon?

**Comment by lmstrand** [comment]
Tämä muutos on lisätty issn-all:n kera, johon lissin nämä uudet kentät mukaan.
Testattavana nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextissä
- kentän 490x arvolla haku toimii (esim. hakuehto 1238-5042 tai hakuehto 2954-2960)

(En löytänyt raportilla tietueita, joissa olisi kenttä 490z tai kenttä 490y)

**Comment by AnneliO** [comment]
> (En löytänyt raportilla tietueita, joissa olisi kenttä 490z tai kenttä 490y)

Jos lisäät noihin kenttiin tietoja jollekin olemassaolevalle tietueelle, niin löytyykö tietueet sen jälkeen issn-hauissa?

**Comment by Kati-Helle** [comment]
Unohdin, että voihan testauksen tehdän myös noin :)

Tietue löytyy myös tietueen 490z-arvolla hakiessa sekä tietueen 490y-arvolla hakiessa.

**Comment by Kati-Helle** [comment]
> Unohdin, että voihan testauksen tehdän myös noin :)
> 
> Tietue löytyy myös tietueen 490z-arvolla hakiessa sekä tietueen 490y-arvolla hakiessa.

Korjaan: tietueet eivät löydy ISSN-haulla tietueelle lisäämilläni arvoilla 490z-kenttään ja 490y-kenttään.
Mutta löytyvät Hae tietokannasta -haulla.

**Comment by AnneliO** [comment]
> > Unohdin, että voihan testauksen tehdän myös noin :)
> > Tietue löytyy myös tietueen 490z-arvolla hakiessa sekä tietueen 490y-arvolla hakiessa.
> 
> Korjaan: tietueet eivät löydy ISSN-haulla tietueelle lisäämilläni arvoilla 490z-kenttään ja 490y-kenttään. Mutta löytyvät Hae tietokannasta -haulla.
> 
> Vaativatko nyt lisätyt arvot kuitenkin indeksoinnin?

Haitko siis kaikki indeksistä "issn" vai haitko 490z-kenttään lisättyä indeksistä "canceled-issn" ja 490y-kenttää lisättyä "incorrect-issn" -indeksistä?

Ne pitäisi löytyä myös jos hakee indeksistä "issn-all".

**Comment by AnneliO** [comment]
Testasin siili-nextillä kaikkia neljää (issn, canceled-issn, incorrect-issn ja issn-all) indeksiä ja minusta ne toimivat oikein lisäyksien osalta.

issn-indeksissä oli ennestään määritettynä jo mainittujen lisäksi kenttä 830x, jota ei nyt ole kuitenkaan issn-all -indeksissä. Pitäisiköhän sekin mäppäys vielä lisätä? Eli issn-all: 830x

**Comment by annavii** [comment]
Testasin Vaski-nextillä, oikein tosiaan toimii. 830x pitäisi lisätä issn-all -indeksiin.

**Comment by lmstrand** [comment]
> Testasin Vaski-nextillä, oikein tosiaan toimii. 830x pitäisi lisätä issn-all -indeksiin.

Lisätty nextin mäppäystiedostoon. Pitää vielä uudelleenindeksoida.

**Comment by lmstrand** [comment]
Nyt muut, paitsi lastu- ja vaski-next on uudelleenindeksoitu.

**Comment by Kati-Helle** [comment]
Helle-nextissä 830x-kenttäarvon haku vaikuttaa toimivalta. Lisäsin testatakseni tietueelle biblionumber=1627595 kentän 830x=2343-0832

Tietue löytyy hakiessa arvolla 2343-0832
- Hae tietokannasta -haulla hakuehdolla: 2343-0832
- Hae tietokannasta -haulla hakuehtolla: issn:2343-0832
- Hae tietokannasta hakuehdolla: issn-all:2343-0832
- Tarkka haku -haulla alasvetovalikosta valitulla hakusalalla issn hakuarvonaan 2343-0832

**Comment by piiaseme** [comment]
OUTIn nextillä mäppäykset toimivat.

**Comment by AnneliO** [comment]
Tämä toimii, joten suljen tiketin. Mäppäykset tulevat käyttöön versionvaihdossa.

**Comment by AnneliO** [comment]
Elasticsearchin indeksilistaus päivitetty issn:n osalta Kohan ohje suomeksi -sivulle.
