### ISSUE TITLE
Raportterin kautta ladatun Kellutin-raportin kanssa ongelma

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1440]
### Tukipyyntö

Kelluttimeen haetaan Vaskissa Raportteri-rajapinnan kautta raportit 2279, 2280 ja 2281. _2279 Kellutin: nidetiedot_ -raportilla on sarake status, johon tulee arvo active tai deleted riippuen siitä onko nide poistettu vai ei. Raportti toimii Kohassa ajaessa kuten pitää, listan loppuun tulee deleted-arvon saavia niteitä.

Nyt Kelluttimen porukalta tuli kuitenkin viestiä, etteivät saa raporttia ladatessaan mukaan yhtäkään deleted-arvon saanutta nidettä. Edes postmanilla hakemalla deleted-arvoja ei kuulemma tule vaan kaikilla riveillä status=active: 
https://vaski.koha-suomi.fi/api/v1/contrib/kohasuomi/reportservices/reports?report_id=2279&param1=2024-10-01&param2=2024-10-02&param3=TU%

Itse olen siis samoilla päivärajauksilla eilen ajanut raportin Kohassa ja listalle on kyllä ollut deleted-arvon saaneita niteitä.

Tuleeko mieleen mitään mistä tällainen voisi johtua?

**Comment by ajrajala** [comment]
Se nyt vielä lisätietona, että status-sarake lisättiin raportille jälkikäteen - mutta tälläkään tuskin merkitystä, kun raporttia ladatessa heille status-sarakkeessa kuitenkin active-arvot tulee.

**Comment by AnneliO** [comment]
Kuinka monta riviä tuloksia he saavat noilla parametreillä apin kautta haettaessa? Voiko siellä olla jokin rajoitus heidän päässään, kuinka monta riviä haetaan?

deleted-arvolliset on tosiaan siellä lopussa, niin jotenkin tuntuisi loogiselta, että ne rajautuvat pois jonkin määrärajoitteen vuoksi.

**Comment by ajrajala** [comment]
Voisin kysyä tuota vielä uudelleen, ehdotin jo aiemmin että keskeytyisikö tulosten lataus johonkin kun deleted-arvolliset on aina siellä listan lopussa.

**Comment by AnneliO** [comment]
Larin mukaan itse rajapinta ei rajoita tulosten määrää. :)

**Comment by ajrajala** [comment]
Saatiin tuossa ajettua raportti suht samanaikaisesti ja tuloksissa eroa aika lailla sen verran, mitä minun ajamassani raportissa oli deleted-arvon saaneita niteitä. Laitoin myös muutamien poistettujen niteiden itemnumberit heille ja yhtään niistä ei löytynyt rajapinnan kautta haetulla raportilla.

Ja tässä vielä vastaus latautumisen keskeytymis-epäilystä:
_Postmanissa ei pitäisi olla päällä mitään tiedostokoon rajoituksia ja response on json-lista joka ei jää myöskään mitenkään kesken vaan lopussa on }]_

**Comment by ajrajala** [comment]
Nuo kaikki niteet, joilla status on 'deleted' haetaan raportille UNION ALL -komennolla deleteditems-taulusta. Tämä nyt on ihan hatusta heitettyä, mutta voiko sillä olla mitään tekemistä asian kanssa?

**Comment by AnneliO** [comment]
> Nuo kaikki niteet, joilla status on 'deleted' haetaan raportille UNION ALL -komennolla deleteditems-taulusta. Tämä nyt on ihan hatusta heitettyä, mutta voiko sillä olla mitään tekemistä asian kanssa?

Onhan se hyvinkin mahdollista. Larilla on yksi muutos, joka pitäisi laittaa tuotantoon, että pystymme tarkastelemaan tietoja tarkemmin, mutta emme halua näin perjantaina klo 15 tehdä muutoksia tai katkoksia, niin jatketaan ensi viikolla asian tutkimista. :)

**Comment by ajrajala** [comment]
> > Nuo kaikki niteet, joilla status on 'deleted' haetaan raportille UNION ALL -komennolla deleteditems-taulusta. Tämä nyt on ihan hatusta heitettyä, mutta voiko sillä olla mitään tekemistä asian kanssa?
> 
> Onhan se hyvinkin mahdollista. Larilla on yksi muutos, joka pitäisi laittaa tuotantoon, että pystymme tarkastelemaan tietoja tarkemmin, mutta emme halua näin perjantaina klo 15 tehdä muutoksia tai katkoksia, niin jatketaan ensi viikolla asian tutkimista. :)

Jes, kiitokset tästä väliaikatiedosta. 👍 Harmillisesti tuli tämä ilmi vasta tuotannossa ollessa, noita deleted-tietoja alun perin hoksattu ottaa raportille edes mukaan, joten siksi viime keväänä testausvaiheessa ei tullut tämä ongelma ilmi. :/

**Comment by lmstrand** [comment]
Tuodaan tuotantoon muutos, jolla raportteja voi hakea selaimesta Kohaan kirjautuneena. Poistaa ylimääräisen OAuth-tarkistuksen ja helpottaa diagnosointia.

**Comment by ajrajala** [comment]
Mikäli tästä lisätiedosta on hyötyä, niin Raportterin kautta haetaan Turun Tietovarastoon tietoja mm. raportilla 2262. Tuossakin raportissa yhdistetään deleteditems UNION ALL -komennolla ja tiettävästi Tietovarastoon nuo poistettujen niteiden tiedot ovat kyllä menneet.

Erona tuohon Tietovaraston raporttiin 2262 on Kelluttimen raportilla 2279 se, että kellutinraportilla ei haeta kaikkia niteitä vaan hakua rajataan kirjasto- ja timestamp-parametreillä (samat parametrit sekä items että deleteditems-tauluista hakemiselle).

**Comment by MikkoLiimatainen** [comment]
No, tuossa on varmaankin ongelma. Parametrit pitää lähettää uudelleen, jos samat parametrit käytetään toista taulua varten. Parametrit pitää tässä tilanteessa siis tuplata samassa järjestyksessä kuin ne on raportilla. Voi muistaakseni käyttää parametrin tallentamista muuttujaan ja käyttää muuttujaa deleted-taulussa, jolloin parametrejä ei tarvitse lähettää tuplattuna.

**Comment by lmstrand** [comment]
Helpointa olisi vain toistaa parametrit raportin tarvitsemalla tavalla. Voin kasvattaa lähetettävien parametrien määrää, niin ne riittävät. Asiasta on myös yhteisössä tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32413.

**Comment by lmstrand** [comment]
https://github.com/KohaSuomi/Koha/issues/1446

**Comment by ajrajala** [comment]
Okei, no mutta hyvä mikäli ratkeaa noin eikä muutoksia raporteille tarvita. Eli ymmärränkö oikein tuon avaamasi tiketin perusteella, että esim. tuossa [nideraportissa 2279](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2279&phase=Show%20SQL) parametrejä on 6 eikä ole siksi toiminut? Ja sen sijaan [teostiedot-raportilla 2280](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2280&phase=Show%20SQL) parametrejä on 4 ja sen rapsan ajo rajapinnan kautta pitäisi olla toiminut oikein tähänkin saakka?

**Comment by johannaraisa** [comment]
Kokeilisin tuota mitä Mikko sanoi, että asettaa ne muutujaan. Ei tarvitse samoja aikoja laittaa kyselyyn montaa kertaa. Tässä esimerkki Kohan SQL-kirjastosta.

```sql
SELECT * 
FROM items i
WHERE i.homebranch=@TargetBranch:=<<Pick your branch|branches>>
UNION
SELECT *
FROM deleteditems di
WHERE di.homebranch=@TargetBranch
```

**Comment by lmstrand** [comment]
Aivan, tuo muutujaan laitto tuolla Kohan päässä siis toimii noin. Kasvatetaan niitä parametrien lukumäärää sitten tarvittaessa. Suljen sen tiketin.

**Comment by johannaraisa** [comment]
Kuka muokkaa raporttia?

**Comment by ajrajala** [comment]
> Kuka muokkaa raporttia?

Jättäisin mieluummin sinulle tai Larille, vaikka suunnilleen ymmärsin miten pitäisi muokata. Muutokset varmaan sekä [nideraportille 2279](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2279&phase=Show%20SQL) että [teostiedot-raportille 2280](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2280&phase=Show%20SQL)?

Sen kysyisin vielä, että onkohan poistettujen tietueiden haku teostiedot-raportilla kuitenkin toiminut tähän saakka kun siinä on parametrejä vähemmän? Vai olenko tipahtanut kärryiltä? :D Kelluttimen porukalta ei siis poistettujen tietueiden osalta ole tullut tietoa, etteikö poistettuja tietueita olisi saatu haettua, mutta on tietty mahdollista ettei sitä ole ehditty huomata.

**Comment by lmstrand** [comment]
Kävin vielä testaamassa Vaski-nextillä että tuo parametrointi toimii oikein myös rajapinnasta. Teostiedot-raportilla on samanlainen UNION ALL -liitos ja parametrien määrittäminen tuplana, joten ei ole varmaankaan toiminut, ellei päivämäärärajaus-parametrejä ole lähetetty kyselyyn kahdesti (4 parametriä).

**Comment by lmstrand** [comment]
Ajetut raportit eivät ole lokittuneet tuotantoon, joten en voi tarkastaa miten niitä on ajettu.

**Comment by ajrajala** [comment]
Ok, kerron ettei ole varmaankaan toiminut, en usko että päivämäärärajauksia on lähetetty kahdesti koska alun perin rajaukset oli vain yhteen kertaan.

**Pystyykö teistä jompi kumpi muokkaamaan raportit, jotta menee varmasti oikein?** Mietin lisäksi, että kannattaako muokkaus tehdä vasta huomisaamuna jolloin Kelluttimen väellä olisi aikaa testata ajoa päivän aikana? Nyt jos muutoksen tekee niin tieto ei välttämättä ennätä enää heille ja jos jotakin on pielessä niin sitten raporttien automaattinen ajo ensi yönä epäonnistuu?

**Comment by johannaraisa** [comment]
Tuon alustaminen ei ihan mene samalla tavalla ku on noita between ja like komentoja, kokeillaan saada se eka testillä kuntoon.

**Comment by johannaraisa** [comment]
Sain nyt tehtyä testille sellaisen version, missä valittavat kentät laitetaan muuttujiin. Sen voisi kokeilla tuoda tuotannon puolelle.

**Comment by ajrajala** [comment]
Kiitos! Voin viedä tuon nideraportin tuotantoon ja pyytää Weaseliä testaamaan ajamista rajapinnan kautta. Heidän näkökulmastaan ajamiseen liittyen ei ilmeisesti tarvitse muuttaa mitään vaan menee samoilla parametreillä jotka on olleet käytössä tähänkin saakka?

**Comment by johannaraisa** [comment]
> Kiitos! Voin viedä tuon nideraportin tuotantoon ja pyytää Weaseliä testaamaan ajamista rajapinnan kautta. Heidän näkökulmastaan ajamiseen liittyen ei ilmeisesti tarvitse muuttaa mitään vaan menee samoilla parametreillä jotka on olleet käytössä tähänkin saakka?

Joo, samat parametrit vaan.

**Comment by johannaraisa** [comment]
> Ajoin raportin vielä itse tuotannossa, vanhalla raportilla tulee 11188 tulosriviä kun rajaa eilispäivään ja TUPK. Uudella raportilla saan tuloksiin ainoastaan 20 riviä. 🤔

Jaahas, katsotaanpas uudestaan.

**Comment by johannaraisa** [comment]
Laitoin sen vanhan takaisin, katson tuota testin puolella

**Comment by johannaraisa** [comment]
> Helpointa olisi vain toistaa parametrit raportin tarvitsemalla tavalla. Voin kasvattaa lähetettävien parametrien määrää, niin ne riittävät. Asiasta on myös yhteisössä tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32413.

Alkoi menemään jo sen verran hankalaksi, että tein tämän yhteisöbugin. Laitan sen testille, ni voi kokeilla eka ja tuodaan sitten tuotantoon.

**Comment by ajrajala** [comment]
Ok, kiitos! Mites tuon testaus onnistuu, testaatteko itse rajapinnan kautta raportin ajamista kun muutos on tuotu testille?

**Comment by johannaraisa** [comment]
> Ok, kiitos! Mites tuon testaus onnistuu, testaatteko itse rajapinnan kautta raportin ajamista kun muutos on tuotu testille?

Joo, voin kokeilla. Teetkö muutaman poiston, niin näkee tuleeko ne listalle.

**Comment by ajrajala** [comment]
Poistin kolme Turun pääkirjaston nidettä äsken: 656695, 1943062, 2652348

**Comment by johannaraisa** [comment]
Nyt näyttäisi tulevan listalle myös nuo poistetut.

![image](https://github.com/user-attachments/assets/27028801-19bb-4ef2-a329-9a02169f1397)

**Comment by ajrajala** [comment]
Jees, hieno homma. Ja tietue-raportilla parametreja onkin vähemmän kuin tuolla nideraportila eli pitäisi sitten toimia senkin. Vaatiiko tämä vielä jotain muuta testailua vai menisikö seuraavaksi tuotantoon (ja milloin se onnistuisi)? Voisin tuonne Weaselin suuntaan laittaa tilannepäivitystä.

**Comment by johannaraisa** [comment]
> Jees, hieno homma. Ja tietue-raportilla parametreja onkin vähemmän kuin tuolla nideraportila eli pitäisi sitten toimia senkin. Vaatiiko tämä vielä jotain muuta testailua vai menisikö seuraavaksi tuotantoon (ja milloin se onnistuisi)? Voisin tuonne Weaselin suuntaan laittaa tilannepäivitystä.

Tuodaan tämä ensi tiistaina kriittisenä päivityksenä.

**Comment by ajrajala** [comment]
Heitin vielä varuilta tikettiin tuon "Seuraavaan päivitykseen" tägin kun tällä ei vielä ollut mitään statusta.

**Comment by johannaraisa** [comment]
Tämä on nyt tuotannossa.

**Comment by ajrajala** [comment]
Hienoa, kiitos! Testaatteko ajamista vielä rajapinnan kautta vai laitanko Weaselille viestiä ja pyydän kokeilemaan ajoa?

**Comment by johannaraisa** [comment]
> Hienoa, kiitos! Testaatteko ajamista vielä rajapinnan kautta vai laitanko Weaselille viestiä ja pyydän kokeilemaan ajoa?

Joo, voin kokeilla eka itse.

**Comment by johannaraisa** [comment]
Toimii, loppuun tulee ne poistetut.

**Comment by ajrajala** [comment]
Hyvä homma. Weaselille laitettu viestiä, jätän tiketin vielä auki kunnes saan sieltäkin kuittauksen.

**Comment by ajrajala** [comment]
Sieltäkin tuli kuittaus asian olevan kunnossa, joten suljen tiketin.
