### ISSUE TITLE
Vaski: Lainauskirjaston muutos poistettavan kirjaston lainoille

### ISSUE THREAD

**Issue by iinaniemi** [KohaSuomi/Koha#1441]
### Tukipyyntö

Kirjastoyksikkö SLA2 on suljettu pysyvästi ja tarkoituksena on poistaa kirjasto Kohasta lähiaikoina. Kirjaston varaukset, kuljetukset ja asiakkaat on jo kaikki käsitelty/siirretty toiselle kirjastolle, mutta issues-taulussa on vielä lainoja joiden lainauskirjasto SLA2 on.

Onnistuisiko siis muuttaa issues-tauluun branchcode SLA2 tilalle SLPK? Muutettavia lainoja on yhteensä 21 kpl.

(Olemme todenneet, että lainauskirjaston muutos on esim. laskutuksen kannalta meille ok ja tarpeen tullen statistics-taulusta on mahdollista selvittää mistä yksiköstä nide alun perin on oikeasta lainattu.)

**Comment by emta001** [comment]
Muutos tehty. Ihan varoiksi otin vielä nuo 21 lainaa talteen aputauluun.

**Comment by iinaniemi** [comment]
Hyvältä näyttää, kiitos!
