### ISSUE TITLE
Vaara: SIP-tunnukset uusille oviautomaateille

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1444]
### Tukipyyntö

Joensuun seutukirjastossa siirrytään Tovereista Mikroväylän oviautomaatteihin. Olen toimittanut salattuna sähköpostina support-laatikkoon kirjastojen tunnukset, joille SIP-tunnukset pitää tehdä. Osa tulee käyttöön vasta ensi vuoden puolella, ensimmäiset jo tämän kuun aikana.

**Comment by IrinaHalminen** [comment]
Laitan tälle deadlineksi alustavasti 31.10. Tiedotamme tarkemmin, kun asennusajat ovat tiedossa, mutta marraskuulla pitäisi tapahtua.

**Comment by lmstrand** [comment]
Tunnukset lisätty SIP-palvelimelle ja ovat huomisesta lähtien käytettävissä.

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
