### ISSUE TITLE
Lastu: SIP-tunnukset automaatille ja ovikoneille

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha#1447]
### Tukipyyntö

Kärkölässä ollaan ottamassa käyttöön automaattia ja omatoimen ovikoneita. Tiedot toimitettu Elementissä Larille.

**Comment by lmstrand** [comment]
Tunnukset lisätty SIP-palvelimelle. Korjasin samalla palvelinkonfiguraation timeout-asetuksen 600 sekunnista 10 sekuntiin. Aiheutti pienen katkoksen automaateille.

**Comment by LastuJanneS** [comment]
Tämä kunnossa, suljen tiketin.
