### ISSUE TITLE
Hyllyvarauslista huomioimaan nidetyyppiin määritetyn ei-lainattavuuden

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1450]
### Kehitysehdotukseni

Hyllyvarauslistalle tulee mukaan sellaiset niteet, joiden nidetyyppi on määritetty _ei lainattavaksi_. Tällaiset niteet eivät kuitenkaan jää palautettaessa kiinni varauksiin, joten ne tulevat hyllyvarauslistalle turhaan mukaan.

![kuva](https://github.com/user-attachments/assets/991cf87e-364d-4abf-bd3e-90c46a062fa6)

Tietokannassa tällaisilla nidetyypeillä on määritetty itemtypes-taulussa notforloan-sarakkeeseen '1'.

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä, toimii kuten Anneli mainitsee.

**Comment by LastuJanneS** [comment]
Testattu Lastun nextillä ja toimii. Testasin nimekkeellä jossa on kolme nidettä, kaksi kappaletta pääkirjastolla (toinen lainattava, joka lainassa, toinen käsikirjastokappale EILAINATA-nidetyypillä) ja yksi lainattava muualla hyllyssä. Varauksen tehdessä hyllyvarauslistalle tulee tieto pelkästään tuosta muualla hyllyssä olevasta niteestä, eli EILAINATA-nidetyypin nide ei tule listalle ollenkaan. Eli toimii juuri kuten pitää.

**Comment by MikkoLiimatainen** [comment]
Testasin Vaski-nextillä ja toimii minunkin nähdäkseni oikein.

**Comment by piiaseme** [comment]
OUTIn nextillä toimii oikein.
