### ISSUE TITLE
LAPPI: Takaaja ei pysty liittämään lapsen korttia omaansa Finnassa

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1453]
### Mikä vikana?

Kaksi eri asiakasta ilmoittaa, ettei pysty liittämään lapsen korttia omaansa Finnassa. Finna ei hyväksy pin-koodia eikä kirjastokortin numeroa ja tili lukittuu. 
Pin-koodi vaihdettu molemmissa tapauksissa, ei auttanut.
Asiakastiedoissa ei näyt mitään, mikä voisi aiheuttaa ongelman.
Lainat ja varauksetkin näyttävät olevan ok. 

Missä siis vika ja miten korjataan?

Pari yksi: Lapsi borrowernumber=533516, huoltaja borrowernumber=457865
Pari kaksi: Lapsi borrowernumber=533288, huoltaja borrowernumber=440865 (Lapselle jätetty Tili lukittu tila päälle)

### Mitä pitäisi tapahtua

Finnassa on mahdollisuus liittää kirjastokortti/rinnakkaiskortti, joka näissä tapauksissa olisi lapsen kortti, huoltajan tietoihin.

**Comment by AnneliO** [comment]
Asiakkaan 533288 lokeilla näkyy, että Finna on tehnyt seitsemän epäonnistuneen kirjautumisyrityksen merkintää yhdestä kirjautumisyrityksestä:
 2024-10-05 16:59:23
 2024-10-05 16:59:23
 2024-10-05 16:59:24
 2024-10-05 16:59:24
 2024-10-05 16:59:24
 2024-10-05 16:59:24
 2024-10-05 16:59:25

Tuon jälkeen tili on lukossa. Tuotahan se on tehnyt viime vuodet ja siitä on [tiketti auki](https://github.com/KohaSuomi/koha-plugin-rest-di/issues/2).

Asiakkaalla 533516 näkyy samalla tavalla lokeilla useita kirjauksia kerralla, jonka vuoksi tili aina lukkiutuu.

En ainakaan Kohan lokeilta muuta näe kuin että on yritetty väärällä pin-koodilla, mutta oletteko kysyneet Finna-toimistosta, näkevätkö he tarkemmin, miksi kirjautumisyritys päätyy epäonnistuneeksi?

Onko asiakas koittanut kirjautua suoraan Finnaan lapsen kirjastokortilla ja pin-koodilla ja toimiiko kirjautuminen silloin? Vai onko ongelma vain tuolloin, kun kortti yritetään lisätä toiseen tiliin?

**Comment by PiaKusmin** [comment]
Kiitos Anneli selvityksestä. Minun tietojen mukaan sama tapahtuu ainakin toisen tapauksen kohdalla ihan, jos koittaa kirjautua suoraan lapsen kirjastokortilla ja pin-koodilla. Mutta varmistan asian vielä uudestaan. Ja olen sitten yhteydessä Finna-toimistoon, kun Kohasta ei sen enempää vikaa löydy.
