### ISSUE TITLE
Kirkes: Asiakkaan tiedot jumissa virheellisen vanhenemispäivän vuoksi

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1454]
### Tukipyyntö

Virkailija muutti asiakkaan kortin vanhenemispäivää tavalla, joka sai asiakkaan sivun sekä nimellä hakemisen antamaan virhe 500-ilmoituksen. Asiakkaan borrowernumber on 33171.

**Comment by johannaraisa** [comment]
Nyt siellä on arvo, muuttakaa oikeaksi.

**Comment by ElinaUotila** [comment]
Kiitos, asia kunnossa.
