### ISSUE TITLE
Lumme: asiakastyypin evääminen omatoimikirjaston käytöstä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1460]
### Tukipyyntö

Lumpeissa siirryttiin OUTI-kirjastojen malliin, jossa Lapsi-asiakastyypille tehtiin kaksi eri tyyppiä: Lapsi (omatoimi) ja Lapsi (ei-omatoimi). Kohasta pitäisi estää Lapsi (ei-omatoimi) -asiakastyypin pääsy omatoimikirjastoihin omatoimiaikana ja tämän asiakastyypin pitäisi siirtyä 15-vuotiaana tyyppiin Lapsi (omatoimi).

Muutoksen voi ottaa käyttöön heti.

**Comment by AnneliO** [comment]
Asiakastyypeistä on [yhteinen päätös vuodelta 2017](https://koha-suomi.fi/dokumentaatio/asetukset/#5-asiakastyypit) ja käyttöön otettiin tunnus LAOMATOIMI. Käytättehän Lumpeissa tuota samaa yhtenäisyyden vuoksi? :)

**Comment by AnneliO** [comment]
Omatoimen esto asiakastyypin mukaan tehdään omatoimiovikoneelle. Täältä löytyy ohje: https://koha-suomi.fi/dokumentaatio/automaatit/#yleisohje

**Comment by AnneliO** [comment]
> Kohasta pitäisi estää Lapsi (ei-omatoimi) -asiakastyypin pääsy omatoimikirjastoihin omatoimiaikana ja tämän asiakastyypin pitäisi siirtyä 15-vuotiaana tyyppiin Lapsi (omatoimi).

Lumpeissa on kummankin lapsi-asiakastyypin yläikäraja 15 vuotta, jolloin ne muuttuvat henkilöasiakkaaksi. Eli tuota muutosta ei voi noilla ikämäärityksillä toteuttaa.

Onko siis tarkoitus muuttaa lapsi-asiakkaasta toiseen lapsiasiakas-tyyppiin vai voiko kumpikin lapsiasiakastyyppi muuttua henkilöasiakas-tyypiksi 15 vuotiaana?

**Comment by AnneliO** [comment]
(Ja siis tuota estoa ei siis tehdä Kohassa vaan tosiaan omatoimiovikoneen ohjelmistossa, Kohan ajastetuissa ajoissa vain määritetään nuo asiakastyyppien muuttumiset toiseksi ikärajan mukaan)

**Comment by Hanna-Lumme** [comment]
Suljen tiketin.

**Comment by AnneliO** [comment]
Tarvitsetteko kuitenkin tuon ajon, että lapsiasiakkaat muuttuvat aikuiseksi? Nykyiseen ajastetun ajon määrityksiin pitää tehdä muutoksia, jotta se osaa muuttaa myös uuden lapsiasiakastyypin henkilöasiakkaaksi. :) Siitä voisi ehkä tehdä kyllä ihan oman tikettinsä.
