### ISSUE TITLE
Lumme: automaattien PIN-koodikysely käyttöön ti 19.11.

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1461]
### Tukipyyntö

Lumpeille koko kimpan alueelle otetaan automaateilla PIN-koodikysely käyttöön versionvaihdon yhteydessä ti 19.11. Tämä vaatii muutoksen SIP-konfiguraatioon.

**Comment by lmstrand** [comment]
Tässä huomioitavaa on ovikoneet, jotka eivät saa kerryttää kirjautmisyrityksiä:
https://github.com/KohaSuomi/Koha/issues/512#issuecomment-1522843099

**Comment by lmstrand** [comment]
Pin-koodin kysely pakolliseksi on muutettu nyt kaikkiin tunnuksiin SIP-palvelinkonfiguraatiossa ja SIP-palvelin on käynnistetty uudelleen.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon!
