### ISSUE TITLE
RecordStaffUserOnCheckout-järjestelmäasetus päälle kaikissa kimpoissa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#1462]
### Tukipyyntö

Pääkäyttäjien palaverissa ti 15.10.2024 keskusteltiin RecordStaffUserOnCheckout-järjestelmäasetuksen käyttöönotosta kaikissa kimpoissa. Kun asetus on päällä, tallentuu issues-tauluun lainan tehneen virkailijan borrowernumber issuer_id-kenttään. Tästä on apua silloin, jos pitää esim. siirtää tietyn virkailijan tekemät lainat toiselle kirjastolle, jos virkailija on unohtanut vaihtaa kirjautumiskirjaston.

Sovittiin, että kaikissa kimpoissa laitetaan asetus päälle ja samalla piilotetaan tietueen lainahistoria-sivulta lainaaja-sarake Taulujen asetukset -sivulla ylläpidossa. Taulun id: checkoutshistory-table (Luettelo-osiossa) ja checked_out_by -kohtaan rasti kumpaankin sarakkeeseen.

Kommentoikaa tätä tikettiä, kun olette tehnyt tarvittavat muutokset **tuotantoon ja nextille**, niin merkitsen alla olevaan seurantaan rastin kimpan kohdalle.

### Jotain muuta?

Seuranta kimpoista:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by Kati-Helle** [comment]
Muutos tehty Helle-tuotantoon ja Helle-nextiin.

**Comment by ElinaUotila** [comment]
Muutos tehty Kirkesin tuotantoon ja nextille.

**Comment by Hanna-Lumme** [comment]
Muutos tehty Lumpeissa tuotantoon ja nextille.

**Comment by pknuuti** [comment]
Vaarassa muutos tehty tuotantoon ja nextille.

**Comment by ajrajala** [comment]
Vaskissa asetus olikin jo päällä.

**Comment by Tuomas-Kyyti** [comment]
Kyyti tehty molempiin.

**Comment by ReettaSiili** [comment]
Siilin tuotanto ja next tehty.

**Comment by AnneliO** [comment]
Muutokset on nyt tehty kaikissa kimpoissa, joten suljen tiketin. Kiitos kaikille!
