### ISSUE TITLE
Teokseen kohdistuvat varaukset näkyviin asiakkaan lainoihin

### ISSUE THREAD

**Issue by helasann** [KohaSuomi/Koha#1469]
### Kehitysehdotukseni

Asiakkaan lainanäkymässä ei näy ollenkaan teokseen mahdollisesti kohdistuvia varauksia. 

Varausten kokonaismäärän näkymisestä olisi hyötyä asiakaspalvelutilanteessa. Toivotaan, että teoksen varaukset näkyvät lainataulukossa esimerkiksi uusintasarakkeessa.

### Jotain muuta?

Aiheesta on olemassa bugitiketti:
https://github.com/KohaSuomi/Koha/issues/425

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.11.2024: Kehitys yhteisön kautta.  

Annika, teetkö tästä tiketin yhteisön bugzillaan?

**Comment by helasann** [comment]
> Koha-Suomen asiantuntijaryhmä 27.11.2024: Kehitys yhteisön kautta.
> 
> Annika, teetkö tästä tiketin yhteisön bugzillaan?

Tiketti tehty [#38551](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38551).
