### ISSUE TITLE
Vanhentunut varaus yhä noudettavana

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1471]
### Mikä vikana?

Kuusamon kirjastossa olivat tänä aamuna ottaneet hyllystä pois vanhentuneet varaukset. Jostain syystä asiakkaan borrowernumber=98669 varaus "Klaavu, Juha: Lapsuuden kehityksellinen trauma" (nide 564N27626146) näkyy yhä hänen varauksissa noudettavana varauksena, vaikka varauksen viimeinen noutopäivä on ollut eilen 21.10.2024. 
![image](https://github.com/user-attachments/assets/c64dab10-469c-4c3c-9b3b-05e590c391b3)

Kassu katsoi raportilla, ettei muita vastaavia vanhentamattomia varauksia OUTIsta löydy. Onkohan varausten vanhentamisajossa ollut joku hikka, joka on jättänyt tämän varauksen vanhentamatta vai mistähän voisi johtua?

**Comment by emta001** [comment]
Vaikea kyllä sanoa mitä tuossa on käynyt, koska meillä tuon ajon tekemiset ei lokitu. Ajo on kyllä pyörähtänyt ja näyttäisi myös sille, että tuo asiakkaan varaus on nyt vanhentunut (onko se peruttu käsin?). Tarkistin myös vielä ettei eilen vanhentuneita varauksia vielä pyöri aktiivisina ja ei niitäkään näyttäs olevan.

**Comment by pirliis** [comment]
Ilmoitin Kuusamoon, etteivät käsittelisi varausta pois, ennen kuin tätä on tutkittu. Noutamattoman varauksen maksuajo on kirjannut maksun asiakkaalle 23.10.2024 klo 00:10 eli viime yön vanhentamisajoon varaus on nyt tärpännyt myös tähän varaukseen.

Tämä lienee yksittäinen tapaus ja toivotaan, että se jää myös sellaisesi. :)

Suljen tiketin.
