### ISSUE TITLE
Lappi : Asiakkaan varaukseen on tarttunut kaksi nidettä

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1473]
### Mikä vikana?

Asiakas on tehnyt varauksia lokin mukaan 22.9., ja kahteen hänen tekemään varaukseen on tarttunut eri päivinä kaksi nidettä. Asiakkaan borrowernumber 437767. Molemmissa esimerkkitapauksissa Varaus lokilla raportin (#211) mukaan varauksia olisi tehty vain yksi. Asiakkaan muutoslokilla ei kuitenkaan näy tapahtumia 22.9.?

Tapaus 1. 
Varausid 1338253: biblionumber 1220270. Nide 1191426 tarttunut 23.9. ja nide 2507278 tarttunut 30.9.  ja tämä lainattu 8.10.

Tapaus 2.
Varausid 1338255:  biblionumber 1816090. Nide 2234501 tarttunut 23.9. ja lainattu 8.10.,  ja nide 2213320  tarttunut 30.9.  

Asiakkaan viesteissä näkyy lähteneet noutoilmoitukset molemmista kerroista kummastakin niteestä

### Mitä pitäisi tapahtua

Varaukseen pitäisi tarttua vai yksi nide.

**Comment by AnneliO** [comment]
Olen joskus selvitellyt vähän vastaavaa ja silloin(kin) arvelin, että varaus on jostain syystä tiputettu takaisin varausjonoon tietueen varaukset-sivulla, jolloin se jää uudelleen kiinni seuraavaan palautuvaan niteeseen. Se ei tallennu lokille, jos joku klikkaa "Peruuta Odottava-tila" tai "Peruuta kuljetus-tila" varauksen kohdalla.

Olisiko tässä mahdollista, että joku on vahingossa tai tarkoituksella käynyt tiputtamassa odottava-tilan pois?

**Comment by LeenaKinnunen** [comment]
Tätä on mahdotonta selvittää, koska kyse on kohta kuukauden takaisesta tapahtumasta. Tarkistin niteen kulun kirjastoissa, ja siltä osin näyttää loogiselta, mutta mitä noutokirjastossa tapahtui, jää nyt avoimeksi. Suljen tiketin.
