### ISSUE TITLE
Jokin nidetieto estää nidehaun tulosten lataamisen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#1475]
### Mikä vikana?

Vaski-nextillä huomattiin, että kun tekee nidehaun rajauksella "Nykyinen kirjasto: Kaarina, Piikkiön kirjasto" saa virheilmoituksen.

Ongelma ei siis liity varsinaisesti nykyiseen kirjastoon rajaamiseen, mutta jokin ko. haun tulosjoukossa aiheuttaa nyt virheilmoituksen. Tehdyssä haussa ei siis käytetty mitään muita hakuehtoja.

### Jotain muuta?

![kuva](https://github.com/user-attachments/assets/416b88b6-76fc-467c-95dd-7a51870b2485)

**Comment by AnneliO** [comment]
Siirsin tiketin Koha-tietovarantoon, koska tämä ei olekaan versionvaihtoon/uuteen versioon liittyvä ongelma, kun se toistuu myös nykyisessä tuotannossa.

**Comment by ajrajala** [comment]
Oliko niin, että tähän tuli ratkaisuksi ongelmia aiheuttaneen nimekkeen muutos? Suljenko tämän tiketin?

**Comment by emta001** [comment]
> Oliko niin, että tähän tuli ratkaisuksi ongelmia aiheuttaneen nimekkeen muutos? Suljenko tämän tiketin?

Juu, se oli tuo Annelin linkkaama nimeke ja sen korjaamiseksi tuli ohjekin 15.11.2024. Kaivelin Elementsistä tämän Annelin laittaman viestin:

> Hei,
> 
> muuttunut nimeke Melindan tietueella 006023609, johon yhdistetty nyt myös tuplatietueet 011621245 ja 014504766.
> 
> Jean David Morvanin ja Philippe Bouchet’n Sillage-sarjakuvasarjan viidennen osan nimi on ilmaistu sarjassa keksityllä merkkijärjestelmällä, jonka on tulkittu aiemmin olevan UCS-merkeillä ilmaistuna hieman vaihdellen muodossa ’J.V.J,..’. Nimekkeessä ollut takakenoviiva tai merkkien yhdistelmä on kuitenkin osoittautunut yhteensopimattomaksi Koha-järjestelmän kanssa kaataen aina näille riveille kohdistuvan haun.
> 
> Kumea tutustui kansainvälisiin kirjastotietokantojen ratkaisuihin ja mahdollisuuksiin, ja päätyi korjaamaan nimekettä seuraavasti:
> 
> 240 10 $a Ma vie pour les miens. $l Suomi
> 245 10 $a [Elämäni omieni puolesta] /
> 500 ## $a Tunnettu myös keksityllä merkkijärjestelmällä ilmaistulla nimekkeellä 'J.V.J,..’, joka voidaan kääntää nimekkeeksi Elämäni omieni puolesta.
> 
> Kirjastot, joita muutos koskee listattu otsikossa.
> 
> Otsikko: Melinda-id 006023609, 011621245 ja 014504766: Nimeke korjattu (ALMA, ANDER, EEPOS, FENNI, FIKKA, HEILI, JYKDO, KUOPI, OULA, PIKI, SATA, VAARI, VOLTE)
