### ISSUE TITLE
Helle: poistettujen niteiden palautus (503 nidettä)

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1481]
### Tukipyyntö

Saatteko palautettua Hellen 503 poistettua nidettä. 

Niteiden poistoajankohta:
22.10.2024

Niteiden kotikirjasto:
LAPPK

**Comment by AnneliO** [comment]
deleteditems-taulusta löytyy 625 nidettä noilla ehdoilla. Palautetaanko ne kaikki vai pystytkö kertomaan lisää rajauksia? Liittyykö ne johonkin tiettyyn niteiden eräpoistoon esim.?

**Comment by Kati-Helle** [comment]
Poisto ei liity eräpoistoon, vaan tilausten poistamiseen hankinta-toiminnossa.

Palautuksen voi tehdä mainituilla ehdoilla.

**Comment by johannaraisa** [comment]
Varmistan nyt vielä, eli voin palauttaa nuo 625 nidettä?

**Comment by Kati-Helle** [comment]
Joo, voit palauttaa 625 nidettä.

**Comment by johannaraisa** [comment]
Nyt niiden pitäisi olla taas paikallaan.

**Comment by Kati-Helle** [comment]
Kiitos!
