### ISSUE TITLE
Lumme: raportti lainausmääristä postinumeroalueittain

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1482]
### Tukipyyntö

Kirjaston johtoportaalta esitettiin toive, että saisi raportin lainoista postinumeroalueittain. Raportissa olisi hyvä mahdollista valita aikaväli ja kirjasto (esim. MLI_PK). Mukaan voisi laskea vain ensilainat.

**Comment by AnneliO** [comment]
Tästä raportista voisi ehkä lähteä muokkaamaan: https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#kaukolainojen-vuositilasto-postinumero-ja-aineistotyyppi

**Comment by AnneliO** [comment]
Lähdin nyt kuitenkin käyttämään pseudonymized_transactions-taulua ja sain aikaiseksi tällaisen kyselyn

```
SELECT p.zipcode AS 'Postinumero', count(*) AS 'Ensilainojen määrä'
FROM pseudonymized_transactions p
WHERE p.categorycode not in ('TILASTO', 'OMA')
   AND transaction_type = 'issue'
   AND transaction_branchcode LIKE <<Lainaava kirjasto|branches:all>>
   AND date(datetime) BETWEEN <<Alkupvm|date>> AND <<Loppupvm|date>>
GROUP BY p.zipcode
```

Tuo löytyy Lumpukoiden raporteista nimellä Lainat postinumeroittain, raportin numero 763.

Raportti hakee ensilainojen määrän postinumeroittain. Mukaan ei lasketa asiakastyyppejä TILASTO ja OMA. Parametrinä annetaan haettavien lainojen päivämääräväli ja lainaava kirjasto. Ylimmäiseksi tuloksissa tulevat niiden asiakkaiden lainat, joille ei ole tallennettuna postinumeroa.

Olisiko tuo toiveiden mukainen?

**Comment by Hanna-Lumme** [comment]
On täysin toiveiden mukainen, kiitos paljon avusta! :)

**Comment by AnneliO** [comment]
Uusi raportti [Ensilainat postinumeron mukaan aikavälillä](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#ensilainat-postinumeron-mukaan-aikav%C3%A4lill%C3%A4) lisätty myös Raporttikirjastoon.
