### ISSUE TITLE
OUTI: Vaalan kirjaston aikuisten ja musiikin hyllypaikan aineisto "Saatavana, ei varattavissa" -tilaan 21.11.2024

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1486]
### Tukipyyntö

Vaalan kirjaston aikuistenosaston hyllyt uusitaan 21.11.-15.12.2024.
Kirjaston **aikuisten hyllypaikan (AIK) ja musiikin hyllypaikan (MUS) Saatavana-tilassa olevat niteet**  halutaan ajaa "Saatavana, ei varattavissa" -tilaan torstaina 21.11.2024 mahdollisuuksien mukaan jo aamusta.

**Ajossa rajataan pois aikuisten hyllypaikalla (AIK) ja  musiikin hyllypaikalla (MUS) olevat niteet:**
o	jotka ovat kuljetustilassa
o	jotka ovat kuljetustilassa kiinni jääneeseen varaukseen
o	jotka ovat lainassa
o	jotka ovat varattuna odottamassa noutoa
 
**Tai jos niteen not_loan-arvo on:**
1 (Ei lainattavissa)
-1 (Tilattu)
-2 (Saapunut)
2 (Henkilökunnan käsikirjasto)
6 (Laskutettu, toimi kirjastosi laskutusohjeiden mukaisesti)
8 (Ei laskuteta, toimi kirjastosi laskutusohjeiden mukaisesti)
9 (Tarkistettavat)
10 (Poistoehdotukset)
-11 (Korjattavana)
-12 (Tarroitettavat)
13 (Puutteelliset)
-14 (Uusin numero, ei lainata)
16 (Turmeltuneet)

**Tai jos niteen lost-arvo on:**
1 (Kadonnut)

**Ajosta jätetään pois myös Lyhytlaina-kokoelmassa olevat nidetyypin 14 vrk – 40 snt/pv niteet** (näillä niteillä on jo nidetila ”Saatavana, ei varattavissa”)

### Jotain muuta?

Muistutamme sitten hyvissä ajoin joulukuussa, kun tila pitää ajaa pois niteiltä 16.12.2024

**Comment by pirliis** [comment]
Vaalasta tuli lisäyksenä, että musiikin hyllypaikalla olevat saatavana-tilassa olevat niteet pitää ajaa samalla myös "Saatavana, ei varattavissa" -tilaan. Päivitin pyyntöä tältä osin.

**Comment by emta001** [comment]
Pohdittiin tätä ja aateltiin, että tän muutoksenhan voisi kokeilla tehdä erämuokkauksella. Näitä niteitä on (tällä hetkellä) semmoset 23567 kappaletta ja niiden muokkauksen pitäis kyllä onnistua (kahessa erässä kylläkin todennäköisesti). Ne voi hakea tällä rimpsulla:

`SELECT itemnumber FROM items i LEFT JOIN reserves r ON(i.itemnumber = r.itemnumber) WHERE i.homebranch = "VAPK" AND i.location IN("AIK", "MUS") AND i.itype != "14VRK40SNT" AND i.notforloan = 0 AND i.itemlost != 1 AND i.onloan IS NULL AND r.found IS NULL;`

Nuo niteiden itemnumberit pitää vaan muistaa sitten ottaa ylös. Ja jos tää ei onnistu erämuokkauksella, niin Lari tai Pasi voi tuon rimpsun avulla tehdä muutoksen suoraan kantaan.

**Comment by pirliis** [comment]
Joo, katellaan vielä tuota rapsaa Kassun kans ja kokeillaan tehdä nidetilamuutokset erämuokkauksella. :)

**Comment by atarnus** [comment]
Hei, muokkasin tuosta lausekkeesta vielä tällaisen, joka huomioi toisenkin pikalainatyypin ja jättää pois myös kuljetuksessa (muusta syystä kuin varauksesta) olevat.

```
SELECT i.itemnumber
  FROM items i
       LEFT JOIN reserves r ON (i.itemnumber = r.itemnumber)
 WHERE i.homebranch = "VAPK"
   AND i.location IN ("AIK", "MUS")
   AND i.itype NOT IN ("14VRK40SNT", "7VRK40SNT")
   AND i.notforloan = 0
   AND i.itemlost != 1
   AND i.onloan IS NULL
   AND r.found IS NULL
   AND i.itemnumber NOT IN (SELECT itemnumber
                              FROM branchtransfers bt
                             WHERE bt.datearrived IS NULL
                               AND bt.datecancelled IS NULL)
```

Tässä on nyt versionvaihdon jälkeen ollut hitautta eräajoissa, ja eräajoja tehdään koko ajan runsaasti. Tämänhetkinen niteiden määrä on 23460 kpl, ja nyt meitä kyllä arveluttaa laittaa tuollainen eräajo tulille, kun ei ole vielä takuuta että hidastelu olisi täysin korjaantunut.

_**Eli voitaisiinko ajo kuitenkin tehdä teidän kehittäjien puolesta?**_ Ja tietysti ottaa talteen sen itemnumber-listan, niin saadaan ajeltua damaged-arvo sitten poiskin 16.12. Pääkäyttäjiä on tuolloinkin paikalla vain 1, joten onnistuisi varmaan aika helposti ajaa teidän sama homma sitten uudestaan eri arvolle taas?

**Comment by atarnus** [comment]
Koska nyt jonot kuitenkin näyttävät purkautuneet, niin kokeillaan tehdä itse. 😄 
Nyitään päivystäjiä sitten hihasta jos ei onnistu.

**Comment by atarnus** [comment]
Nämä ajeltiin ja kaikki vaikuttaisi menneen ok.
Eräajojen ID:t:
22018173
22019131
22019992

**Comment by pirliis** [comment]
Otimme nidetunnukset talteen ja poistamme itse eräajolla nidetilat määräpäivänä, joten suljen tämän tiketin.
