### ISSUE TITLE
Tätiin Tietuesiirtäjän käyttäjätunnuksiin järjestystä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1494]
### Kehitysehdotukseni

Tätissä on kaikkien kimppojen käyttäjien tunnuksia Tietuesiirtäjän Käyttäjät-asetuksessa. Tunnukset ovat ilmeisesti tallennusjärjestyksessä. Niiden haku on mahdotonta, koska haku ei toimi. Olisi hyvä saada tunnukset vaikka kimpoittain numerojärjestykseen, niin on tarvittaessa helpompi muokata/lisätä käyttäjätunnus(ta).

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 27.11.2024: Muutetaan käyttäjä-valikko järjestymään aakkosjärjestykseen, jolloin ne menevät samalla kimpoittain, koska tunnuksissa on kimpan nimi ja numero.

**Comment by johannaraisa** [comment]
Tämä on TäTi-testillä siellä ei tosin ole kuin yksi tunnus, joten pitää tehdä enemmän ja katsoa miten järjestyy.

**Comment by pknuuti** [comment]
Mä lisäsin testi-Tätiin muutaman käyttäjän tunnuksen ja nyt ne menee aakkosiin. Ihanaa, kiitos!

**Comment by pknuuti** [comment]
Tämä siis toimii, joten suljen tiketin.

**Comment by johannaraisa** [comment]
Ei vielä, laitetaan ensi viikolla tuotantoon.

**Comment by pknuuti** [comment]
Tuotannossa, toimii. Suljen tiketin.
