### ISSUE TITLE
Vaara: LAOMATOIMI siirto HEOMATOIMI-asiakastyyppiin

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1504]
### Tukipyyntö

Vaarassa otettu käyttöön kolme uutta asiakastyyppiä, kun siirrytään vähitellen Tovereista MikroVäylän oviautomaatteihin. LAOMATOIMI on lapsiasiakkaille, jotka ovat alle 15-vuotiaita ja joiden vastuuhenkilö on allekirjoittanut lapsen omatoimisopimuksen. HEOMATOIMI on henkilöasiakkaille, jotka ovat vähintään 15 vuotta täyttäneitä ja jotka ovat allekirjoittaneet omatoimisopimuksen. LAOMATOIMI asiakkaan siirtyminen HEOMATOIMI-asiakkaaksi täytyy ajastaa siihen, kun asiakas täyttää 15 vuotta.

**Comment by IrinaHalminen** [comment]
Valitsin itselleni tämän uuden asiakastyypin alasvetovalikosta ja huomasin, että viestiasetukset nollautuvat, jos alla olevasta ilmoituksesta painaa ok. Voiko tälle tehdä jotain? Ja eihän nollautumisia tule ajon yhteydessä?

![image](https://github.com/user-attachments/assets/4c59db99-e360-4cf5-aaf4-09900e38af08)

**Comment by CodoDerDritte** [comment]
Minusta tuolla ei kyllä pitäisi olla vaikutusta viestiasetuksiin, mutta täytyy tutkia.

**Comment by CodoDerDritte** [comment]
> Valitsin itselleni tämän uuden asiakastyypin alasvetovalikosta ja huomasin, että viestiasetukset nollautuvat, jos alla olevasta ilmoituksesta painaa ok. Voiko tälle tehdä jotain? Ja eihän nollautumisia tule ajon yhteydessä?
> 
> ![image](https://private-user-images.githubusercontent.com/99409279/387647057-4c59db99-e360-4cf5-aaf4-09900e38af08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMTg2NTEsIm5iZiI6MTczMjAxODM1MSwicGF0aCI6Ii85OTQwOTI3OS8zODc2NDcwNTctNGM1OWRiOTktZTM2MC00Y2Y1LWFhZjQtMDk5MDBlMzhhZjA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDEyMTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViODYwYTY3YjAyZTM0OWE4MzViYzU4ZWFkMzlmMTE1ZDAxMThlNmEyYWMyNmVjYzBiZmFkN2IwMjk1ZDMyN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0zbPHMyjZ9UKD2tewYzHyfuZiqL5_Qtdp2896GD092U)

Voi painaa "peruuta" ;D

**Comment by CodoDerDritte** [comment]
> Minusta tuolla ei kyllä pitäisi olla vaikutusta viestiasetuksiin, mutta täytyy tutkia.

Ajossa viestiasetukset eivät nollaudu. Tsekkasin testillä parilta asiakkaalta.

**Comment by CodoDerDritte** [comment]
Henkilökunnan ohjeistuksessa täytyy sitten vain huomioida tuo viestiasetusboksi ja ohjeistaa, että pitää painaa Peruuta, ettei asiakkaan viestiasetukset ylikirjoitu tyhjillä oletuksilla.

**Comment by CodoDerDritte** [comment]
Jaaniijaa, taidettiin puhua vähän eri ajoista nyt, mutta siis ei ne viestiasetukset varmasti tuossa iän mukaan tapahtuvassa asiakastyypin vaihdossakaan vaihdu, kerta eihän ne vaihdu silloinkaan kun lapsiasiakkaita päivitetään henkilöiksi :D

**Comment by IrinaHalminen** [comment]
Tarkoitin tuota uutta ajoa, jossa muutetaan omatoimisopimuksen hyväksynyt (käyttöoikeus annettu Toveriin) asiakas esim. henkilöstä "omatoimihenkilöksi". Mutta hyvä, jos näin ei tapahdu. Eilen laitoinkin jo henkilökunnalle huomion, että eivät painaisi tuohon ilmoituksen ok, vaan peruuta, mutta onko tuo ilmoitus/toimi viestiasetusten muutoksesta pakollinen, kun vaihtaa asiakastyyppiä vanhaa asiakasta muokattaessa?

**Comment by AnneliO** [comment]
Tuo poppari, joka kysyy, vaihdetaanko tilalle asiakastyypin oletusviestiasetukset on ihan yhteisön toiminto. Testasin sandboxissa.

Esim. OUTIssa tuossa on ohjeistettu, että painakaa Peruuta, eikä OK (kuten varmaan ensireaktio olisi). Yleisesti ajatellenkin halutaan todennäköisesti säilyttää asiakkaan itse valitsemat viestiasetukset, eikä tuoda tilalle oletusasetuksia, jotka eivät vastaa asiakkaan valintaa.

Yritin muistella, miksi meillä ei ole asiakastyypeillä oletusasetuksia ja se ehkä liittyi jotenkin meidän viestiasetusten tarkistusskripteihin, jotka eivät toimineet oikein, jos uudelle asiakkaalle asetettiin oletuksena asiakastyypille määritetyt asetukset. Se ei jotenkin tunnistanut niitä olemassaoleviksi, eikä osannut poistaa niitä tallennettaessa, jos sähköpostiosoitetta/puhelinnumeroa ei ollut. Siinä vaiheessa ohjeistettiin, että asiakastyypeiltä pitäisi ottaa pois oletusrastit.

**Comment by pknuuti** [comment]
Kiitos, tämän voinee sulkea.

**Comment by IrinaHalminen** [comment]
@AnneliO Olisiko popparin tekstin muuttaminen kuitenkin mahdollista? Nyt käännös on aika ontuva eikä kovinkaan informatiivinen ("ryhmälle"?), eivätkä käyttäjät tiedä/muista, että viestiasetusten oletusasetus on tyhjä. Vaikka on tiedotettu, on ongelmana, ettei uskalleta painaa Peruuta-nappia, koska vaikuttaa siltä, että sen painaminen johtaisi asiakaslajin vaihdon epäonnistumiseen. Voisiko tekstiin lisätä esim. Paina peruuta, jos haluat säilyttää asiakkaan nykyiset viestiasetukset?

**Comment by AnneliO** [comment]
Tuota on jo kerran aiemmin säädetty ja silloinen säätö on näköjään taas tippunut pois, koska se on taidettu tehdä vain Koha-Suomen käännöksiin, enkä ole muistanut sitä dokumentoida mihinkään.

https://github.com/KohaSuomi/Koha-translations/issues/3

Tuossa tiketissä tekstiksi muutettiin muotoon _Vaihda asiakkaan viestiasetukset asiakastyypin oletusarvoiksi_. Taidan tehdä tuon muutoksen tällä kertaa yhteisöön, niin se ei katoa taas. :)
