### ISSUE TITLE
Vaara: Asiakastyyppien muutosajo omatoimisopimuksen perusteella

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1505]
### Tukipyyntö

Vaarassa siirrytään vähitellen Tovereista MikroVäylän ovikoneisiin. Vaarassa kaikkien omatoimikirjastoa käyttävien täytyy allekirjoittaa omatoimisopimus (alle 15-vuotiaiden sopimuksen allekirjoittaa vastuuhenkilö). Asiakkaalle on tallennettu asiakastietoihin omatoimen käyttöoikeus. Tämä oikeus pitää nyt kopioida LAOMATOIMI ja HEOMATOIMI -asiakkaille tietokanta-ajona asiakkaiden iän mukaisesti. Yhteisöasiakkaalla on myös omatoimiasiakastyyppi YHOMATOIMI.

**Comment by CodoDerDritte** [comment]
Lisätty myös YHOMATOIMI omatoimea käyttäviä yhteisöasiakkaita varten ja muutokset ajettu testille.

**Comment by pknuuti** [comment]
Testattu laina- ja maksusääntöjen toimivuutta Vaaran testillä näillä uusilla asiakastyypeillä. Toimii yhtä pientä kummallisuutta lukuunottamatta. Miten voi saman nimekkeen niteille tulla eri eräpäivä (3. ja 4.12.) samana päivänä lainattaessa, nidetyyppi sama.
![Image](https://github.com/user-attachments/assets/f8d5742c-e9df-44a4-a168-499fe3b9ccb7)

**Comment by pknuuti** [comment]
Anneli keksi selityksen tuolle päiväyksen omituisuudelle. Tuo Joensuun nide oli olevinaan Kesälahden kirjastossa, jossa kalenteri oli kiinni 3.12. Kiitos Anneli!

**Comment by pknuuti** [comment]
Kiitän ja suljen tiketin.
