### ISSUE TITLE
Kun tekee tilauksen, heti ACQ-pohjan tuonnin jälkeen, niin siihen määritettyjen MARC-kenttien lisäksi tulee näkyviin myös muita kenttiä.

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1511]
### Mikä vikana?

Versionvaihdon jälkeen OUTIssa tehdessä tilausta "Uudesta tyhjästä tietueesta" tuli hankinnan oletuspohjassa suuri määrä kenttiä täytettäväksi (luultavasti kaikki kentät). 

Kokeilimme auttaisiko Tätistä Hankinnan oletuspohjan tuominen ja saimme sen tuotua, mutta edelleen tehdessä uutta tyhjä tietuetta sai sen suuren määrän kenttiä täytettäväksi. 

Pohja päivittyi, kun kävin tallentamassa pohjasta jonkun kentän uudelleen (en tehnyt kenttään muutoksia) ja tallennuksen jälkeen tehdessä tilausta "Uudesta tyhjästä tietueesta" tuli näkyville ainoastaan Tätistä tuodun pohjan kentät.

**Comment by piiaseme** [comment]
Lisäsin ja poistin eilen OUTIn testikannassa Hankinnan oletuspohjan kenttiä. Tänä aamuna toin pohjan tuotantoon käyttäen Vie OpenDocument-taulukkolaskentamuotoa (CSV-taulukkomuoto päätyi epäonnistumis-poppariin). Vienti onnistui ja hankinnan puolella muokattu pohja näkyi heti ilman, että tarvitsi tehdä ylimääräistä tallennusta.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 9.12.2024: Tätä voi olla hankala toistaa ja todentaa ongelmaa, joten suljetaanko tiketti toistaiseksi?

**Comment by piiaseme** [comment]
Suljen tiketin.
