### ISSUE TITLE
Kohan itsepalvelutoiminnon Palautus-toiminnossa aloitussivu ei tyhjene

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#1518]
### Mikä vikana?

Kun Kohan itsepalvelutoiminnolla palauttaa niteen, aloitussivu ei enää tyhjene, vaan viimeinen palautus jää näkyviin:
![image](https://github.com/user-attachments/assets/3792d3fb-30ee-4747-bf25-74d6b1811b3e)

Tämä on kertaalleen korjattu lokakuussa, mutta näköjään on mennyt rikki taas.
https://github.com/KohaSuomi/Koha-24.05/issues/6

Olisiko voinut mennä rikki tämän korjauksen yhteydessä:
https://github.com/KohaSuomi/Koha-24.05/issues/176

### Mitä pitäisi tapahtua

Viimeksi palautetun niteen tiedot pitäisi tyhjentyä näytöltä OUTIssa n. 20 sekunnin kuluttua.

**Comment by emta001** [comment]
No sinnehän livahtikin sitten taas väärä muuttuja matkaan, kun katsoin että se muuttuja joka siellä oli, onkin väärä. Nyt tää on korjattu taas testeille ja sivun tulisi tyhjentyä.

**Comment by pirliis** [comment]
> No sinnehän livahtikin sitten taas väärä muuttuja matkaan, kun katsoin että se muuttuja joka siellä oli, onkin väärä. Nyt tää on korjattu taas testeille ja sivun tulisi tyhjentyä.

Yritin testata palautusta nyt OUTIn itsepalvelulainauksen testillä. Palautus antaa Internal server erroria.

**Comment by emta001** [comment]
> > No sinnehän livahtikin sitten taas väärä muuttuja matkaan, kun katsoin että se muuttuja joka siellä oli, onkin väärä. Nyt tää on korjattu taas testeille ja sivun tulisi tyhjentyä.
> 
> Yritin testata palautusta nyt OUTIn itsepalvelulainauksen testillä. Palautus antaa Internal server erroria.

Toimiiko nyt?

**Comment by pirliis** [comment]
Nyt palautus toimii. 
Palautetun niteen tiedot tyhjenevät nyt n. 10 sekunnin kuluttua eli sen puoleen toimii, mutta OUTIssa on määritelty järjestelmäasetuksessa SelfCheckInTimeout, että palautusnäyttö tyhjenee 20 sekunnin kuluttua.

**Comment by AnneliO** [comment]
> SelfCheckInTimeout

Tämä liittyy muistaakseni siihen, missä ajassa kirjaudutaan ulos lainausnäkymästä. Ei liity palautukseen. :)

**Comment by pirliis** [comment]
> > SelfCheckInTimeout
> 
> Tämä liittyy muistaakseni siihen, missä ajassa kirjaudutaan ulos lainausnäkymästä. Ei liity palautukseen. :)

Itsepalvelupalautuksessa on kyllä järjestelmäasetus:
![image](https://github.com/user-attachments/assets/47c36c22-067c-454d-836b-67e6c4545244)

Itsepalvelulainauksessa on oma asetus:
![image](https://github.com/user-attachments/assets/de832044-5f2f-4466-a158-589915b7a130)

**Comment by pirliis** [comment]
Korjaus tuotu tuotantoon viikon 49 Koha-päivityksessä.
