### ISSUE TITLE
Lumme: huollettavan varaustunnuksen generointi ei toimi

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1520]
### Mikä vikana?

Lumpeissa tuli esiin tapaus, että kun lähtee lisäämään Lapsi (omatoimi) -asiakastyyppiä suoraan takaajatietojen kautta, varaustunnisteen generoinnin kolme pistettä puuttuu.

![Omatoimi01](https://github.com/user-attachments/assets/a23ccad2-188a-4fc5-98d4-a944db07b629)

Samaa asiakastyyppiä lisättäessä Lisää uusi asiakas -linkin kautta, kolme pistettä generoituvat normaalisti.
![Omatoimi 02](https://github.com/user-attachments/assets/239509f7-1a05-4656-8149-c4c3353fb189)

**Comment by Hanna-Lumme** [comment]
Sama ongelma näyttää olevan myös Lapsi (omatoimi ei sallittu) -asiakastyypillä, kun sitä lähdetään lisäämään takaajatietojen kautta.

**Comment by lmstrand** [comment]
Muutin rimpsua pluginissa niin, että generointi lisätään aina, jos ollaan sivulla /cgi-bin/koha/members/memberentry.pl. Nyt pitäisi näkyä generointi kaikkialla. Testattavana testeillä.

**Comment by MikkoLiimatainen** [comment]
Ongelmana testin rimpsussa on nyt se, että se ei säilytä muokkauksessa asiakkaan entistä varaustunnusta. Se muistaakseni oli syynä, että tuo op=edit_form on eriytetty nykyisessä rimpsussa omaksi funktiokseen.

**Comment by MikkoLiimatainen** [comment]
Jos kimpoissa on käytössä myös Lisää huollettava monivalintanappi, niin olettehan huomanneet, että siihen ripsuun tulee tehdä korjauksia?
[https://github.com/KohaSuomi/Koha-24.05/issues/91](https://github.com/KohaSuomi/Koha-24.05/issues/91)
Muuten esim. varaustunnuksen luonti ei onnistu ja takaajan tiedot eivät siirry.

**Comment by lmstrand** [comment]
Lisäsin rimpsuun ehdon, ettei uutta varaustunnusta generoida automaattisesti, jos kentässä on jo tekstiä. Testattavana testeillä.

**Comment by MikkoLiimatainen** [comment]
Nyt asiakkaan vanha varaustunnus säilyy muokattaessa, mutta uutta taattavaa tai asiakasta ylipäätään lisätessä kenttään ei muodostu automaattisesti varaustunnusta. Varaustunnuksen saa luotua kolmesta pisteestä.

**Comment by lmstrand** [comment]
No johan on kumma kun tuo elementti ei jäänyt kiinni. Muutin tuota tapaa, miten tuo tekstikenttä etsitään. Nyt se tuntuisi tärppäävän ja näyttäisi toimivan eri tapauksissa, missä lisätään/muokataan uutta/jo olemassa olevaa asiakasdataa.

**Comment by MikkoLiimatainen** [comment]
Kokeilin muokata ja kopioida asiakastietoja, sekä luoda eri asiakkaita eri tavoilla ja minusta kaikki näytti toimivan oikein.

**Comment by Hanna-Lumme** [comment]
Näyttää toimivan myös Lumpeiden testillä eri asiakastyypeillä ja niiden lisäyksillä.

**Comment by piiaseme** [comment]
OUTIn testillä toimii eri asiakastyypeillä.
