### ISSUE TITLE
Lähtökirjastossa kuljetuksessa olevat - raportti ei toimi oikein

### ISSUE THREAD

**Issue by LastuJanneS** [KohaSuomi/Koha#1521]
### Mikä vikana?

Lastussa otettiin käyttöön Raporttikirjastossa oleva raportti [Lähtökirjastossa kuljetuksessa olevat](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#l%C3%A4ht%C3%B6kirjastossa-kuljetuksessa-olevat), mutta se ei vaikuta toimivan oikein. Tarkemmin tutkailtuani vaikuttaa siltä, että branchtransfers-taulussa oleva datearrived-sarake on kaikissa kuljetuksissa tyhjä tai NULL, vaikka ovat saapuessa palautettu ja menneet asiakkaille lainaankin.

### Mitä pitäisi tapahtua

Raportin pitäisi rajata tulokset vain kuljetuksessa oleviin niteisiin.

### Kuinka toistaa ongelma/asia

1. Ota käyttöön raportti [Lähtökirjastossa kuljetuksessa olevat](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#l%C3%A4ht%C3%B6kirjastossa-kuljetuksessa-olevat)
2. Valitse mikä tahansa kirjasto
3. Raportille tulee tulokseksi myös kuljetuksesta aiemmin saapuneet niteet

**Comment by lmstrand** [comment]
Lisäsin testiraporttiin (Lastu-tuotantoon) 115 https://lastu.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?id=115&op=show
ehdot:
  AND datecancelled IS NULL
  AND datesent IS NOT NULL
eli kuljetus ei päädy raportille jos on peruutettu tai sille ei ole lähetysaikaleimaa.

Sillä putosi tulosten lukumäärä roimasti.

Kertookohan tuo nyt sen, mitä pitää?

**Comment by AnneliO** [comment]
> Sivuhuomiona: Näyttäisi siltä, että kun nide palautetaan automaatilla, nide menee tässä vaiheessa kuljetettavaksi (saa datesent-arvon), ja kun nide palautetaan uudelleen Kohassa esim. varausten varalta, tämä tapahtuma kirjautuu tuohon datecancelled-kenttään. Nide pysyy Kohan saatavuustietojen mukaan kuljetettavana-tilassa, mutta siitä huolimatta kun nide lopulta palautetaan kohdekirjastossa, ei tuo datearrived-kenttä saa koskaan mitään arvoa tällaisessa tapahtumaketjussa.

Tuosta voisi tehdä erillisen tiketin, niin asiaa voisi tutkia sitten tarkemmin.

**Comment by LastuJanneS** [comment]
> Tuosta voisi tehdä erillisen tiketin, niin asiaa voisi tutkia sitten tarkemmin.

Teen erillisen tiketin. Tämän voi varmaan sulkea?

**Comment by AnneliO** [comment]
Muutos olisi vielä hyvä dokumentoida Raporttikirjastoonkin. Haluatko tehdä sen, vai teenkö minä? :)

**Comment by LastuJanneS** [comment]
Tee vain, testailen vielä vähän kattavammin tuota mahdollista bugia, että mitä siinä tapahtuu.

**Comment by AnneliO** [comment]
SQL-kysely on nyt päivitetty  myös [Raporttikirjastoon](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#l%C3%A4ht%C3%B6kirjastossa-kuljetuksessa-olevat).
