### ISSUE TITLE
"Tyhjennä suodatin" -painike ei toimi tietueen perusnäytöllä

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#1522]
### Mikä vikana?

Jos tietueen perusnäytöllä valitsee "Näytä rajaukset" ja rajaa hakua suodattamalla tai hakukenttään kirjoittamalla, "Tyhjennä suodatin" -toiminto ei muutu missään vaiheessa aktiiviseksi. "Näytä rajaukset"/"Piilota rajaukset" -kohta näyttää kyllä toimivan tyhjentävästi, mutta sitä ei kovin moni hoksaa kokeilla, koska ko. napin nimessä ei mainita mitään tyhjentämisestä. 

![image](https://github.com/user-attachments/assets/317cdfec-1a14-4de1-8431-107d5f4b5e19)

**Comment by AnneliO** [comment]
Yhteisöstä löytyy korjaus tähän tiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=38071

**Comment by johannaraisa** [comment]
Tämä on nyt testeillä.

**Comment by ElinaUotila** [comment]
Kirkesin testillä Tyhjennä suodatin -nappi aktivoituu nyt aivan oikein, kun Hae-kenttään kirjoittaa jotain.

**Comment by MikkoLiimatainen** [comment]
Myös vaskin testillä tyhjennä suodatin aktivoituu, kun kenttään on kirjoitettu jotain.

**Comment by johannaraisa** [comment]
Tämänkin voi laittaa seuraavaan päivitykseen.

**Comment by ElinaUotila** [comment]
Tämä toimii, suljen tiketin.
