### ISSUE TITLE
Lappi: Viivakoodit generoituvat liian pitkiksi

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#1523]
### Mikä vikana?

Versionvaihdon yhteydessä tuli muutoksia viivakoodin generointiin. Ongelmana on nyt, että muodostunut viivakoodi on liian pitkä mahtuakseen tarralle. Maksimimerkkimäärä on 15 ja nyt muodostuu 17 merkkiä.

**Comment by johannaraisa** [comment]
Mistä tuo maksimimerkkimäärä tulee, tarrapohjassako vai jostain muusta? Minusta esim. Vaskilla tuo prefiksi on enemmän kuin teillä.

**Comment by PiaKusmin** [comment]
Rovaniemellä laskivat, montako merkkiä mahtuu viivakoodiin, että mahtuu tulostumaan tarralle (tarrapohja, iso rullatarra viivakoodilla).

**Comment by johannaraisa** [comment]
Säädin testillä tarraan viivakoodin leveyttä, pakotin sille maksimileveyden 77mm. Kokeiltaa pysyykö tarralla ja saako sen luettua.

**Comment by PiaKusmin** [comment]
Testattu 698N2411270801071 ja se mahtui tulostumaan tarralle, mutta tassut eivät suostuneet sitä lukemaan eikä myöskään automaatti. Kokeiltu myös yhtä numeroa lyhyempää nidenumeroa ja sen tassut ja automaatti vielä luki.

**Comment by johannaraisa** [comment]
Muut ovat vain muokanneet prefiksin merkkimäärää. https://github.com/KohaSuomi/Koha/issues/772
Tämä voisi olla se ratkaisu myös teille. Tuon koodin säätäminen alkaa olemaan jo melko hankalaa.

**Comment by AnneliO** [comment]
> Testattu 698N2411270801071 ja se mahtui tulostumaan tarralle, mutta tassut eivät suostuneet sitä lukemaan eikä myöskään automaatti. Kokeiltu myös yhtä numeroa lyhyempää nidenumeroa ja sen tassut ja automaatti vielä luki.

Toimisiko se, että jättäisitte prefixistä pois N-kirjaimen?

**Comment by PiaKusmin** [comment]
Prefixiä muutettu kahden kirjaston kohdalla (Roi ja Utsjoki). Muiden käyttämiin tarra-arkkeihin uudet viivakoodit mahtuivat luettavassa muodossa.
