### ISSUE TITLE
Lapsiasiakkaan tallentaminen takaajatietojen kautta tekee virheen

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1532]
### Mikä vikana?

Ainakin Lumpeissa lapsiasiakasta kun tallentaa takaajatietojen kautta, Koha heittää virheen "Asiakasta ei löytynyt. Palaa hakuun." Tätä on tullut esiin ihan kentällä ja kokeilin lisätä testiasiakasta niin tuotannossa kuin testillä tätä kautta. Molemmissa tuli sama virhe. 

![Virhe](https://github.com/user-attachments/assets/c0b6f268-5057-438a-a845-f4bd23d82a80)

Taattavaa lisätessä takaajatietojen kautta ei myöskään täyty automaattisesti taattavan osoitetiedot takaajan mukaan.

**Comment by AnneliO** [comment]
Lumpeissa on käytössä virheellinen IntranetUserJS-rimpsu tuossa Lisää huollettava -napin muodostamisessa.

Oikea versio löytyy esim. täältä: https://github.com/KohaSuomi/Koha-24.05/wiki/IntranetUserJS

**Comment by Hanna-Lumme** [comment]
Niinpäs oli vanha JS-livahtanut mukaan. Tuo on nyt vaihdettu ja nyt pystyy taattavia taas lisäämään. Kiitoksia!
