### ISSUE TITLE
Varausten vanhenemisajo ei toimi Kyytissä

### ISSUE THREAD

**Issue by VaisanRo** [KohaSuomi/Koha#1536]
### Mikä vikana?

Haemme normaalisti Kyytissä vanhentuneet varaukset päivittäin raportilla 873. Raportti ei ollut tänään näyttänyt yhtään vanhentunutta varausta. Kuitenkin kun meni tutkimaan varausten noutohyllyä löytyi sieltä useampia varauksia joissa oli ollut viimeinen noutopäivä eilen 2.12.24. Jos tällaisen varauksen jonka olisi pitänyt jo vanhentua koittaa palauttaa, ei nide lähde eteenpäin vaan jää samalle asiakkaalle. Varauksen saapumispäivä tai vanhenemispäivä eivät muutu vaan pysyvät samana. Asiakkaille ei ole myöskään muodostunut maksuja noutamattomista varauksista. Tässä esimerkiksi yksi nide jonka olisi pitänyt vanhentua 2.12.24 biblionumber=831777 item120582.

**Comment by emta001** [comment]
Elikäs cancel_expired_holds.sh-ajoon oli livahtanut testausvaiheessa olevaa koodia, joka ilmeisesti rikkoi Kyytissä käytössä olevan nidetyyppillä tehtävän ajon. Kävin tiputtamassa koodin pois ja tein ajon käsin uusiksi. Näyttääkö nyt oikeemmalle?

**Comment by VaisanRo** [comment]
Nyt alkoi raportti toimia, mutta siiä ei näy kaikkia missä on eilen 2.12.24 ollut viimeinen noutopäivä. Esimerkiksi tuo yllä mainitsemani esimerkki nide ei tullut raportille ollenkaan. Onkohan meidän raportissamme jotain vikaa, vai onko ajossa joku viive tms. että saa kaikki vanhentuneet käsiteltyä.

**Comment by VaisanRo** [comment]
On tuo nide 2860N1303609 näköjään nyt kuitenkin vanhentunut kun näyttää tilana saatavana ja asiakkaalle on muodostunut noutamattoman varauksen maksu. Jostain syystä se ei tuohon raportille 873 tule näkyviin.

**Comment by emta001** [comment]
> Eikun se ei varmaan näy tuossa raportilla kun koitin testimielessä sen aamulla palauttaa ja silloin siinä tietysti päivittyi datelastseen-arvo tälle päivälle, niin tuo meidän raportti taitaakin jättää sen pois listalta sen takia. Eli varausten vanhentumisajo vaikuttaisi taas toimivan normaalisti, kiitos Emmi! 😊

Hyvä että toimii! Itse oisin veikannut, että replicalle ei oo vielä päivittynyt tiedot noista vanhenemisista, onneksi vika olikin simppelimpi :sweat_smile:

**Comment by VaisanRo** [comment]
Suljen tiketin, kiitos! 😊
