### ISSUE TITLE
Kausijulkaisut-toiminnossa lisänumeron lisääminen: numerointiarvoon lisätty välilyönti ei pysy

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#1537]
### Mikä vikana?

Kausijulkaisut-toiminnossa lisänumeroa lisätessä numerointiarvon välilyönti ei pysy. Esimerkiksi numerointiarvon 2024 24 lisäämisen tuloksena on arvo ilman välilyöntiä tyyliin 
202424

**Comment by Kati-Helle** [comment]
Anneli mainitsi, että lisänumeron käsittely on lisätty versionvaihdon aikaan. Ja että tiketissä mainittu sääntö kaipaa korjausta:
https://github.com/KohaSuomi/koha-plugin-intranetjs-remove-excess-spaces/issues/1

**Comment by lmstrand** [comment]
Tähän on tehty korjaus, jossa kentän tekstiin numeroiden väliin sallitaan jätettäväksi yksittäisiä välilyöntejä (esim "2024 4"). Testattavana testeillä.

**Comment by Kati-Helle** [comment]
Helle-testissä toimii. 
Yksittäisen lisätty välilyönti pysyy, esim. 2024 14.
Ylimääräiset välilyönnit poistuvat automaattisesti.

**Comment by AnneliO** [comment]
Tässä kannattaa nyt testailla myös muidenkin, että muunkinlaisissa tapauksissa välilyöntien poisto toimii edelleen oikein lisänumero-kentässä. :)

**Comment by piiaseme** [comment]
OUTIn testillä testasin lisänumeron lisäämistä ja olemassa olevan numeron muokkaamista Kausijulkaisujen vastaanotossa. Yksittäinen lisätty välilyönti pysyy ja ylimääräiset poistuivat automaattisesti.

**Comment by ajrajala** [comment]
Vaskin testillä testattu lisänumeroiden lisäämistä muodossa 2024 : 5b, välilyönnit säilyivät. Jos lisäilin tuohon extra-välilyöntejä niin ne poistuivat kuten haluttukin.

**Comment by Kati-Helle** [comment]
Toimii nyt myös Helle-tuotannossa.

Suljen tiketin.
