### ISSUE TITLE
Vaara: Uusia CPU-kassoja

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#1538]
### Tukipyyntö

Joensuun seutukirjaston alueella otetaan käyttöön muutama uusi CPU-kassa, joiden pitäisi keskustella Kohan kanssa. Miten tässä pitää menetellä eli mihin tahoihin pitää olla yhteydessä ja mitä tietoja tarvitaan Kohaa varten? En löytänyt ohjeita.

**Comment by lmstrand** [comment]
OUTIssa ainakin on tehty ilmeisesti alueittain (laskutusalueet/itsenäiset kunnat?) eri kassoille omat tunnukset omilla salasanoilla/avaimilla ja maksuosoitteilla. Teillä varmaan voisi käyttää samaa maksuosoitetta ja tuota avainta, kun maksut voivat olla samaa laskutusaluetta?
OUTI:n ja muiden CPU-kimppojen kanssa tehtiin alkuvuodesta muutos, jossa jokainen kassa alkoi käyttää jaettua sertifikaattia, joten teillä jo käytössä olevaa pääkirjastolle luotua sertifikaattia (ja maksuosoitetta ja avainta) voisi käyttää uusien kassatunnusten kanssa varmaan.

Voin lisätä jollekin yksikölle uuden kassatunnuksen Kohan konfiguraatiotiedostoon testiksi Vaara-testille ja voidaan testata, että maksu välittyy ja kuittautuu Kohaan.
Ennen testausta pitää myös Ceepos-kassaintegraatiopluginiin konfiguroida uusi kassatunnus(yksikkö) ja käytettävät maksutyypit ja niiden koodit.

**Comment by pknuuti** [comment]
Joo, maksut ovat Joensuun maksuja, joten sama tunnus käy. Reijolassa, Lehmossa ja Kontiolahdella CPU-kassat ovat jo olleet käytössä, mutta niillä ei ole yhteyttä suoraan Kohaan kuten pääkirjaston kassoilla. Uusia kassoja tulee Enoon, Kiihtelysvaaraan, Pyhäselkään ja Tuupovaaraan.
Kokeillaan ensin noilla mitkä jo on olemassa eli vaikka Kontiolahden kassalla? JOE_KON on kirjaston tunnus ja teen sille pluginiin tarvittavat tunnukset ja maksutyypit.

**Comment by pknuuti** [comment]
Joko Vaaran testikantaan voi tuon tehdä vai onko uudelleenluonti ja redusointi vielä tekemättä (tiketti https://github.com/KohaSuomi/Koha/issues/1519)?

**Comment by AnneliO** [comment]
Lisäsin Ceepos-kassaliitännäisen wikiin vielä kuvien kanssa [käyttöönotto-ohjeet](https://github.com/KohaSuomi/koha-plugin-ceepos-integration/wiki/Ceepos%E2%80%90kassaliittym%C3%A4n-k%C3%A4ytt%C3%B6%C3%B6notto). Tiedot löytyivät periaatteessa kyllä liitännäisen Readme:stäkin, mutta ehkä tuo on selkeämpi noin. :)

**Comment by AnneliO** [comment]
> Joko Vaaran testikantaan voi tuon tehdä vai onko uudelleenluonti ja redusointi vielä tekemättä (tiketti #1519)?

Se on vielä tekemättä, helle-test on tällä hetkellä työn alla. Pasi lupasi tehdä vaara-testin seuraavaksi.

**Comment by lmstrand** [comment]
Vaara-testille lisätty koha-conf.xml:ään testausta varten JOE_REI, JOE_LEH ja JOE_KON tunnuksille ceeposmääritys tuotannosta löytyvän konfiguraation parametreilla (paitsi notificationAddress osoittaa testeille).

**Comment by lmstrand** [comment]
Näitä uusia lisättyjä kassoja (tai niiden kautta maksun suorittamista Kohaan) voi kokeilla tuotannossa, kunhan Ceepos-pluginiin on lisätty nuo yksiköt ja maksutyypit/koodit. Ne käyttävät samaa oletusta koha-conf.xml:n Ceepos-konfiguraatiota, joten maksamisen pitäisi toimia sen jälkeen suorilta.

**Comment by pknuuti** [comment]
Kiitos, selvittelen missä testaus olisi parasta tehdä.

**Comment by pknuuti** [comment]
Tuotannossa tulee jälleen tuo virhe 403, kun yritän tallentaa asetuksia pluginiin.

**Comment by lmstrand** [comment]
Ainiin totta, käyn noutamassa korjauksen sinnekin.

**Comment by pknuuti** [comment]
Lehmon kirjastossa kassa saatu toimimaan käytännössä, joten nyt myös Kontiolahdelle ja Reijolaan laitettu asetukset päälle.

**Comment by pknuuti** [comment]
Kiitos, tältä osin asia kunnossa. Vuoden vaihteessa saadaan loput CPU-kassat kirjastoihin. Toimiiko ne suoraan, kun vaan laitetaan asetukset päälle Vaaran tuotantoon?

**Comment by pknuuti** [comment]
Kiitos, voin siis sulkea tämän tiketin.
