### ISSUE TITLE
Pertunmaan varausten siirto ja jäädytys 13.12.24-19.1.2025

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1540]
### Tukipyyntö

Pertunmaa siirtyy Mikkelin seutukirjastosta Mäntyharjun lähikirjastoksi 1.1.2025 alkaen. Tästä johtuen Pertunmaan varaukset tulisi:

1) Siirtää MLI_PE-tunnuksen alta MAN_PE-tunnuksen alle.
2) Jäädyttää aikavälille 13.12.24-19.1.2025

Jäädytys ja vapautus eivät koske varauksia jotka ovat jo jäädytettyinä ennen 13.12. ja joiden jäädytys kestää pidemmälle kuin 19.1.25.

**Comment by AnneliO** [comment]
Varausten noutokirjaston vaihto: https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#varausten-noutopaikan-vaihtaminen-toiseen-kirjastoon

Jäädytys: https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#varausten-keskeytys-ja-ei-noutopaikaksi-laitto
* kannattanee tehdä jäädytys 13.12.2024 ja laittaa suspend_until-arvoon 2025-01-20

**Comment by lmstrand** [comment]
Ajettu:

MariaDB [lummeprod]> create table ks_G1540_reserves like reserves;
Query OK, 0 rows affected (0.037 sec)

MariaDB [lummeprod]> insert into ks_G1540_reserves select * from reserves where branchcode='MLI_PE';
Query OK, 253 rows affected (0.016 sec)
Records: 253  Duplicates: 0  Warnings: 0

MariaDB [lummeprod]> update reserves set branchcode='MAN_PE' where reserve_id in (select reserve_id from ks_G1540_reserves);
Query OK, 253 rows affected (0.611 sec)
Rows matched: 253  Changed: 253  Warnings: 0

MariaDB [lummeprod]> update reserves set suspend=1 where branchcode = 'MAN_PE' and suspend=0;
Query OK, 218 rows affected (0.047 sec)
Rows matched: 218  Changed: 218  Warnings: 0

MariaDB [lummeprod]> update reserves set suspend_until='2025-01-20' where branchcode = 'MAN_PE' and suspend_until is null;
Query OK, 218 rows affected (0.014 sec)
Rows matched: 218  Changed: 218  Warnings: 0

**Comment by Hanna-Lumme** [comment]
Kiitos paljon!
