### ISSUE TITLE
Varauksen noutokirjasto näkymään automaateilla oikein

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#1548]
### Tukipyyntö

Lumpeissa asiakkaat pystyvät nyt päivityksen jälkeen katsomaan lainausautomaateilla omia varauksiaan. Varausten tiedoissa näkyy kuitenkin noutokirjaston sijaan niteen kotikirjasto, mikä hämmentää asiakkaita. Tähän pitäisi saada korjaus.

**Comment by lmstrand** [comment]
liittyy tikettiin https://github.com/KohaSuomi/Koha/issues/651

**Comment by lmstrand** [comment]
Tein SIP-palvelimeen muutoksen äsken n. 8.40 aikoihin. Aiheutti lyhyen n. 10 sekunnin katkoksen. Nyt varauksen noutokirjastotieto näkyy SIP-sanomissa samoin kuin Vaarassa, kentässä AP, tietona niteen sijaintikirjasto.

**Comment by Hanna-Lumme** [comment]
Kiitoksia!
