### ISSUE TITLE
Nalkutin: Onko mahdollista säätää ohitettavaksi merkkipaikaksi 007/02?

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1565]
### Mikä vikana?

Koha-Suomen kuvailuryhmässä on toivottu, että olisiko mahdollista säätää Nalkuttimeen ohitettavaksi merkkipaikaksi 007/02?

Merkkipaikan 007/02 osalta virheellisiä tietueita on Melindassa massoittain ja merkkipaikkaa 007/02 korjataan Melindassa vain silloin, kun tietueeseen tehdään muitakin korjauksia. Koska virheellisiä tietueita tulee Melindasta jatkuvasti, niin näitä ei kannata lähteä manuaalisesti korjailemaan ennen kuin Melindassa on tehty vastaavat korjaukset. Yleensä kyseessä on osakohteellisia tietueita, joiden korjaaminen käsin on työlästä.

### Jotain muuta?

Alun perin toivomus on esitetty tiketissä: https://github.com/KohaSuomi/Koha/issues/1434. Koska tiketti koskee korjausajoa, niin siirrän Nalkuttimen säätöä koskeavan toivomuksen omaan tikettiin.

**Comment by paxed** [comment]
Testeillä on Nalkutin päivitetty, se hyväksyy asetuksissa Ignore MARC fields -kohtaan esim. 007/02

**Comment by pknuuti** [comment]
Lisäsin Vaaran testille tuon päivityksen. Testasin vaihtamalla tyhjän merkin tilalle 0 eikä siitä tullut herjaa.

**Comment by paxed** [comment]
Tämä on nyt myös tuotannossa. Muutos näkyy myös virhelistoissa.

Eli, Nalkuttimeen voi määrittää ohitettavaks kentäks esim. "007/02", tai vaikkapa "006-MU/07-12"

**Comment by AnttHeik** [comment]
Ehditkö @pknuuti laittaa tuon päälle TäTiin jossain välissä?

**Comment by pknuuti** [comment]
Mä olin vielä nopeampi eli tein sen jo tänä aamuna 😊

Päivi Knuutinen
kirjastovirkailija
Vaara-kirjastot
050 441 2247
***@***.******@***.***>

Lähettäjä: AnttHeik ***@***.***>
Lähetetty: 18. joulukuuta 2024 11:01
Vastaanottaja: KohaSuomi/Koha ***@***.***>
Kopio: Knuutinen Päivi ***@***.***>; Mention ***@***.***>
Aihe: Re: [KohaSuomi/Koha] Nalkutin: Onko mahdollista säätää ohitettavaksi merkkipaikaksi 007/02? (Issue #1565)


Ehditkö @pknuuti<https://github.com/pknuuti> laittaa tuon päälle TäTiin jossain välissä?

**Comment by AnttHeik** [comment]
Mainiota, kiitokset :)

**Comment by piiaseme** [comment]
Testattu ja todettu toimivaksi. Suljen tiketin.
