### ISSUE TITLE
Lappi: Vanttauskosken lainojen siirto kirjastoautoon 31.12.2024

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1575]
### Tukipyyntö

Vanttauskosken kirjasto ROVA suljetaan 31.12.2024. 
Kaikki lainat kirjastosta ROVA pyydetään siirtämään kirjastoautoon ROAU.

Siirron voi tehdä 31.12.2024

**Comment by paxed** [comment]
Tämä tehty, koski 250 kpl.

**Comment by LeenaKinnunen** [comment]
Asiakkaan tiedoissa lainauskirjasto näkyy oikein, mutta muutos ei näy teoksen saatavuudessa? Eikä nidehaussa?

![Näyttökuva 2024-12-31 124623](https://github.com/user-attachments/assets/3d211632-fc1e-4bc2-9086-694ea78165e7)

**Comment by AnneliO** [comment]
Yksinkertaisinta olisi varmastikin, että muutatte niteiden erämuokkauksella sijaintikirjaston oikeaksi. :)

**Comment by LeenaKinnunen** [comment]
Joo, sen voi tehdä. Sitä vain ihmettelin, että vaikka lainat siirtyivät autoon, ei näkyneet näissä näkymissä. Asia kuitenkin kunnossa, suljen tiketin .

**Comment by AnneliO** [comment]
Lainat ovat eri taulussa kuin niteet ja tässä ajossa muutettiin ymmärtääkseni vain lainojen kirjastotieto. Muutos pitää tehdä erikseen nidetauluun, josta sijaintikirjasto-tieto haetaan hakutuloksissa ja nidehaussa. Olisi ne toki päivittyneet myös sitten, kun lainat palautuvat. :)
