### ISSUE TITLE
Lappi: Vanttauskoski -noutopaikan varausten siirto Kirjastoautoon

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1576]
### Tukipyyntö

Vanttauskosken (ROVA) kirjasto suljetaan 31.12.2024.

Kaikille varauksille, joiden noutopiste on ROVA, pyydetään vaihtamaan noutokirjastoksi kirjastoauto ROAU. 

Siirron saa tehdä heti.

**Comment by emta001** [comment]
Muutettu, koski 16 varausta.

**Comment by LeenaKinnunen** [comment]
Asia kunnossa, suljen tiketin.
