### ISSUE TITLE
Kyyti: mobile-kentän kopiointi smsalertnumber-kenttän jos se on tyhjä

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#1577]
### Tukipyyntö

Kyytissä näyttää olevan vajaa 5 000 asiakasta, joilla on puhelinnumero mobile-kentässä, mutta smsalertnumber-kenttä on tyhjä. 
Pyydän, että puhelinnumerot mobile-kentästä kopioidaan ajolla smsalertnumber-kenttään, mikäli smsalertnumber-kenttä on tyhjä. 
Itse viestiasetukset eivät saa ajossa muuttua.

Asia kävi ilmi, kun eräs asiakas vaihtoi saapumisilmoitukset sähköpostista tekstiviestiksi. Numero oli valmiina mobile-kentässä eikä siihen siten koskettu. Saapumisilmoitus tuli aikanaan sitten paperikirjeenä. Syyksi paljastui tyhjä smsalertnumber-kenttä. Kyseinen kenttähän ei näy virkailijalle, jos se on tyhjä.

Meille ei nyt tarvitse huomioida mobile-kentän ja smsalertnumber-kentän eroavaisuuksia.

### Jotain muuta?

Ajo on toteutettu aiemmin ainakin Outissa [835](https://github.com/KohaSuomi/Koha/issues/835).

**Comment by emta001** [comment]
Haeskelin noita asiakkaita tuosta OUTIn ajosta sovelletulla rimpsulla:

SELECT COUNT(*) FROM borrowers WHERE mobile != "" AND (smsalertnumber IS NULL OR smsalertnumber = "");

 ja sain tulokseksi 26199. Pitääkö tässä vielä ottaa huomioon esim. asiakkaan viestiasetukset vai voiko muutos koskea kaikkia näitä asiakkaita?

**Comment by Tuomas-Kyyti** [comment]
Katos vaan, siinä olikin noin iso ero. Mun rapsasta puuttui tuo `smsalertnumber IS NULL`.
Mutta siis ajetaan vaan noin, ei tarvitse ottaa huomioon viestiasetuksia, kunhan ne eivät muutu ajossa.

**Comment by emta001** [comment]
Nyt on ajo tehty, koski tosiaan 26199 asiakasta. Laitoin nuo asiakkaat vielä aputauluun.

`CREATE TABLE ks_20241219_borrowers_1577 SELECT * FROM borrowers WHERE mobile != "" AND (smsalertnumber IS NULL OR smsalertnumber = "");`

`UPDATE borrowers SET smsalertnumber = mobile WHERE (mobile != '') AND (smsalertnumber IS NULL OR smsalertnumber = '');`

**Comment by Tuomas-Kyyti** [comment]
Pikaisella tarkastelulla (loma painaa päälle) näyttäisi olevan kunnossa. Kiitos.
