### ISSUE TITLE
Lappi: asiakkaiden kotikirjaston vaihto ROVA -> ROAU ei onnistu

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#1578]
### Tukipyyntö

Asiakkaiden borrowernumberilla 543680, 543856, 543857, 543679 kotikirjaston vaihto ei onnistu ROVA -> ROAU asiakkaiden muokkauksella eräajona asiakastietojen puutteellisuuden vuoksi . 

Pyydän vaihtamaan ko. asiakkaiden kotikirjastoksi kirjastoauton ROAU.

**Comment by emta001** [comment]
Vaihdettu.

**Comment by LeenaKinnunen** [comment]
Asia kunnossa, suljen tiketin.
