### ISSUE TITLE
OUTI: Varausten noutopäivien siirto 

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#1580]
### Tukipyyntö

Rajakylän kirjaston ovi on rikki eivätkä asiakkaat pääse noutamaan varauksiaan viikonloppuna 28.-29.12.2024. Varausten viimeiset noutopäivät tulisi siirtää maanantaille 30.12.2024.

Noutokirjasto: OUR Rajakylän kirjasto
Varausten viimeinen noutopäivä muutetaan seuraavasti:
la 28.12.2024 -> ma 30.12.2024
su 29.12.2024 -> ma 30.12.2024

**Comment by emta001** [comment]
Muutos tehty, koski 68 varausta. Varaukset löytyvät aputaulusta ks_20241220_reserves_1580.

`CREATE TABLE ks_20241220_reserves_1580 SELECT * FROM reserves WHERE branchcode = "OUR" AND found='W' AND expirationdate BETWEEN '2024-12-28' AND '2024-12-29';`

`UPDATE reserves SET expirationdate = "2024-12-30" WHERE branchcode = "OUR" AND found='W' AND expirationdate BETWEEN '2024-12-28' AND '2024-12-29';`

**Comment by piiaseme** [comment]
Kiitos, tarkistin Rajakylän noudettavissa olevat varaukset-listan ja kaikki varaukset ovat siellä nyt kuten halusimmekin. Suljen tiketin.
