### ISSUE TITLE
Lastun Urheilulehden niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1581]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet 2023-2024 vuoden niteet aikakauslehdestä Urheilulehti. Ilmeisesti tapahtunut jokin massapoisto ~viikon sisään? 

Riittääkö tämä tieto?

**Comment by johannaraisa** [comment]
Nyt niteet on palautettu.

Varmuuskopiotaulu niteistä.
```
create table ks_1581 as select * from deleteditems where biblionumber = 1507614 and (enumchron like '2023%' or enumchron like '2024%');
``` 
Niteiden lisäys.
```
insert into items select * from deleteditems where biblionumber = 1507614 and (enumchron like '2023%' or enumchron like '2024%');
```
Poisto poistettuista.
```
delete from deleteditems where biblionumber = 1507614 and (enumchron like '2023%' or enumchron like '2024%');
```

Yritin etsiä jos lainatauluissa olisi ollut jotain merkintöjä lainassa olevista, mutta sellaista tietoa ei näkynyt.

**Comment by LastuLauriH** [comment]
Kiitos, niteet nyt ok.
