### ISSUE TITLE
Lastun Tee itse -lehden niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1584]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet 2023-2024 vuoden niteet aikakauslehdestä Tee itse. Ilmeisesti tapahtunut isompi eräpoisto lähiaikoina?

https://lastu.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1507586

Aiempi vastaava: https://github.com/KohaSuomi/Koha/issues/1581

### Jotain muuta?

Esimerkki poistetusta niteestä: LASL01129293

**Comment by emta001** [comment]
Niteet on nyt palautettu seuraavilla loitsuilla:

`create table ks_20241223_deleteditems_1581 as select * from deleteditems where biblionumber = 1507586 and (enumchron like '2023%' or enumchron like '2024%');`

`insert into items select * from deleteditems where biblionumber = 1507586 and (enumchron like '2023%' or enumchron like '2024%');`
`
delete from deleteditems where biblionumber = 1507586 and (enumchron like '2023%' or enumchron like '2024%');`

**Comment by LastuLauriH** [comment]
Anteeksi mun moka, tämä olikin pysyvästi säilytettävä lehti joten pitäisi palauttaa kaikki mitkä löytyy.

**Comment by emta001** [comment]
Loputkin niteet on nyt palautettu:

`create table ks_20241223_deleteditems_1581_2 as select * from deleteditems where biblionumber = 1507586;`

`insert into items select * from deleteditems where biblionumber = 1507586;`

`delete from deleteditems where biblionumber = 1507586;`

**Comment by LastuLauriH** [comment]
Kiitos, nämä palautuneet.
