### ISSUE TITLE
Lastun Apu 2023 -tietueen niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1586]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet niteet. Ilmeisesti väärin tehty niteiden eräpoisto.

https://lastu.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1985321

**Comment by emta001** [comment]
Niteet palautettu:

`create table ks_20241223_deleteditems_1586 as select * from deleteditems where biblionumber = 1985321;`

`insert into items select * from deleteditems where biblionumber = 1985321;`

`delete from deleteditems where biblionumber = 1985321;`

**Comment by CodoDerDritte** [comment]
Niteet palautettu indeksiin.
