### ISSUE TITLE
Lastun Aku Ankka -tietueen niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1587]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet niteet 2023-2024. Ilmeisesti väärin tehty niteiden eräpoisto.

https://lastu.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1507256

**Comment by emta001** [comment]
Niteet palautettu:

`create table ks_20241223_deleteditems_1587 as select * from deleteditems where biblionumber = 1507256 and (enumchron like '2023%' or enumchron like '2024%');`

`insert into items select * from deleteditems where biblionumber = 1507256 and (enumchron like '2023%' or enumchron like '2024%');`

`delete from deleteditems where biblionumber = 1507256 and (enumchron like '2023%' or enumchron like '2024%');`

**Comment by CodoDerDritte** [comment]
Niteet palautettu indeksiin.

**Comment by LastuLauriH** [comment]
Kiitokset, tämä kunnossa.
