### ISSUE TITLE
Lastun Suomen Kuvalehti 2023 -tietueen niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1588]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet niteet. Ilmeisesti väärin tehty niteiden eräpoisto.

https://lastu.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1985334

**Comment by emta001** [comment]
Niteet palautettu:

`create table ks_20241223_deleteditems_1588 as select * from deleteditems where biblionumber = 1985334;`

`insert into items select * from deleteditems where biblionumber = 1985334;`

`delete from deleteditems where biblionumber = 1985334;`

**Comment by CodoDerDritte** [comment]
Niteet palautettu indeksiin.

**Comment by LastuLauriH** [comment]
Kiitokset, tämä kunnossa.
