### ISSUE TITLE
Lastun Kotilääkäri-tietueen niteet kadonneet

### ISSUE THREAD

**Issue by LastuLauriH** [KohaSuomi/Koha#1589]
### Tukipyyntö

Pyydetään palauttamaan Lastun deleteditems-tauluun eksyneet vuoden 2023-2024 niteet. Ilmeisesti väärin tehty niteiden eräpoisto.

https://lastu.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1507397

**Comment by emta001** [comment]
Niteet palautettu:

`create table ks_20241223_deleteditems_1589 as select * from deleteditems where biblionumber = 1507397 and (enumchron like '2023%' or enumchron like '2024%');`

`insert into items select * from deleteditems where biblionumber = 1507397 and (enumchron like '2023%' or enumchron like '2024%');`

`delete from deleteditems where biblionumber = 1507397 and (enumchron like '2023%' or enumchron like '2024%');`

**Comment by CodoDerDritte** [comment]
Niteet palautettu indeksiin.

**Comment by LastuLauriH** [comment]
Kiitokset, tämä kunnossa.
