### ISSUE TITLE
getitem-ajax.pl error management

### ISSUE THREAD

**Issue by taskula** [KohaSuomi/Koha#178]
Hi,

We had the following error in `catalogue/getitem-ajax.pl`:

> [2021/02/23 13:05:50] [ERROR] Can't call method "description" on an undefined value at /home/koha/Koha/catalogue/getitem-ajax.pl line 76.

I'm not sure where this script is used but would it be possible to add checks so that the script doesn't crash but instead notifies the client of the error? Or is this a feature that is going to be dropped in the next version upgrade?

**Comment by taskula** [comment]
The underlying problem was of course due to an item missing an itemtype, which the client will fix, but it would be better to notify the client of the error instead of reporting it to the sysadmins for those who are automatically monitoring Koha logs for errors.

**Comment by taskula** [comment]
Related: https://tiketti.koha-suomi.fi/issues/4641, pinging @emta001

**Comment by taskula** [comment]
See https://tiketti.koha-suomi.fi/issues/4775 for omnibus ticket for such issues.

**Comment by johannaraisa** [comment]
I looked and this script is in latest community version also. I think nobody in Koha-Suomi has touched this, atleast I don't know where this is used.

**Comment by taskula** [comment]
Apparently our git history was squashed thus providing misleading author info for the script. It is indeed a KC script making this issue invalid in KohaSuomi/Koha. Sorry for the wrong ping @emta001.

But the Redmine omnibus ticket mentioned in https://github.com/KohaSuomi/Koha/issues/178#issuecomment-784470595 still stands.

Closing this issue.
