### ISSUE TITLE
[BUG] Testitiketti

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#183]
**Kuvaus**
Selkeä kuvaus siitä mitä teit, missä teit ja mitä tapahtui.

**Kuinka saadaan toistettua**
Kirjoita vaiheet:
1. Mene '...'
2. Paina '....'
3. Selaa '....'
4. Virhe

**Kuvakaappaus**
Jos mahdollista, niin kuvakaappaus tapahtumasta.

**Järjestelmä (täytä seuraavat kohdat):**
 - Kimppa [mm. OUTI]
 - Selain [mm. chrome, safari]

**Muuta lisättävää**
Lisää jotain muuta bugiin liittyen.

**Comment by AnneliO** [comment]
Testikommentti

**Comment by pknuuti** [comment]
_Täytyypi testata_

**Comment by pirliis** [comment]
Testataanpa nyt.
