### ISSUE TITLE
[Bugi] Issue-pohjan testausta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#186]
### Mikä vikana?

Päätä ja jalkoja särkee.

### Mitä pitäisi tapahtua

Päätä ja jalkoja ei saisi särkeä.

### Kuinka toistaa ongelma/asia

Istu koneella koko päivä.

### Selain

```markdown
Firefox
```

### Jotain muuta?

Näistä vaivoista ois tosi kiva päästä eroon.

**Comment by janPasi** [comment]
Auttaisiko pieni happihyppely tai taukojumppa + kuppi kahvia?
