### ISSUE TITLE
[Bugi] Githubin testijakson huomiot

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#188]
### Mikä vikana?

Tähän tikettiin kerätään huomiot loka-marraskuun Githubin testijakson aikana huomatut ongelmat ja kehitysehdotukset.

**Comment by piiaseme** [comment]
Tikettiin ei voi määritellä määräaikaa, jos sellainen on tarpeen, muuta kuin tekstin sekaan. Miten määräajan saa näkymään siten, että kehittäjät sen huomaavat helpoimmin?

**Comment by pknuuti** [comment]
En löydä mistään painiketta, mistä peukuttaa ehdotusta. Onko se edes mahdollista?

**Comment by AnneliO** [comment]
> En löydä mistään painiketta, mistä peukuttaa ehdotusta. Onko se edes mahdollista?

![kuva](https://user-images.githubusercontent.com/33121325/195551865-66eea937-f114-48c8-879f-472bc74b1517.png)

**Comment by ajrajala** [comment]
Saako tuonne projects-tageihin lisätä tagin omalle kimpalle? Mietin, että meillä Vaskissa voitaisiin hyödyntää sitä kun käymme säännöllisesti läpi oman kimppamme avoimien tikettien tilannetta. Issues-näkymässä ainakin näyttäisi nimittäin siltä, ettei pysty kerralla suodattamaan kuin yhden tiketin tekijän mukaan.

**Comment by AnneliO** [comment]
> Saako tuonne projects-tageihin lisätä tagin omalle kimpalle? Mietin, että meillä Vaskissa voitaisiin hyödyntää sitä kun käymme säännöllisesti läpi oman kimppamme avoimien tikettien tilannetta. Issues-näkymässä ainakin näyttäisi nimittäin siltä, ettei pysty kerralla suodattamaan kuin yhden tiketin tekijän mukaan.

Katotaas!

**Comment by AnneliO** [comment]
Nyt siellä on custom field "Kimppa". Lisäsin sen myös Tikettien seurantaan "Taulukko"-näkymään oikeaan reunimmaiseksi.

**Comment by ajrajala** [comment]
Mainiota, kiitos Anneli!

**Comment by AnneliO** [comment]
Testijakso on ohi, joten suljen tiketin.
