### ISSUE TITLE
[Bugi] Lappi: Varaus ei mene lainaan

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#189]
### Mikä vikana?

Nidettä 698N11369243 ei saa lainattua asiakkaalle borrowernumber=451986, vaikka hänellä on siitä varaus. Tulee Virhe 500. Missä vika?

### Selain

```markdown
Eri selaimet, istunnot ja käyttäjätunnukset kokeiltu.
```

### Kohan osio

Varaukset

**Comment by AnneliO** [comment]
Varaus on jostain syystä sekä reserves- että old_reserves-taulussa samalla reserve_id:llä 901746, minkä vuoksi Koha ei saa sitä siirrettyä pois reserves-taulusta lainatessa. Siitä tulee sitten virhe 500. Pyydän päivystäjää poistamaan varauksen old_reserves-taulusta, jolloin lainaaminen pitäisi onnistua.

**Comment by PiaKusmin** [comment]
Nyt sain lainattua. Suljen tiketin.
