### ISSUE TITLE
[Bugi] Siilinjärvi: Tilastotyökalun syyskuun lainojen jaottelu ei toimi

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#191]
### Mikä vikana?

Elokuun tilastossa jaottelu kielen ja aineistolajin mukaan näyttäisi toimivan, mutta syyskuun tilastossa jotain on pielessä, kts. kuva. En muista että tähän olisi tullut mitään muutosta? Lainojen kokonaismäärä näyttää oikealta.

### Jotain muuta?

![Lainat_syyskuu](https://user-images.githubusercontent.com/98806001/193764575-86543e30-3787-48a1-ba02-cd3fc4ef13ac.png)

### Kohan osio

Raportit ja tilastot

**Comment by emta001** [comment]
Näyttäisi sille, että lähes kaikki lainat on kategorisoitu other-sarakkeen alle. Liittynee korjaukseen, jonka oli tarkoitus korjata lehtiaineistojen laskeminen ither-lainoihin. Korjataan.

**Comment by emta001** [comment]
Ongelma onkin lainojen datan haussa tietokannasta. Se tehdään UNION-lausekkeella, koska on tarvetta tehdä hakua sekä items- että deleteditems-tauluun. Tässä oli virhe jossa dataa haettiinkin kahteen kertaan items-taulusta ja se korjattiin viime kuussa. Mutta nyt näyttäisi sille, että korjauksen jälkeen lähes kaikista lainoista jää ainakin aineistolaji hakematta. Äkkiseltään en hoksaa minkä vuoksi näin tapahtuu, mutta korjauksena toimii ainakin SELECT-lauseiden vaihtaminen päikseen (ensi tehdään hakua deleteditemsiin ja sitten itemsiin). Korjaan tämän ensin testeille ja sitten tuotantoon.

**Comment by emta001** [comment]
Korjaus viety tuotantoon. Ajoin Siilin viime kuun tilastot uusiksi, näyttävätkö nyt oikeammilta?

**Comment by ReettaSiili** [comment]
Syyskuun tilasto tuotannossa näyttää nyt oikealta. Kiitos! Yritän sulkea tämän.
