### ISSUE TITLE
[Bugi] Lappi: Asiakkaan varaukset eivät näy

### ISSUE THREAD

**Issue by noorsuva** [KohaSuomi/Koha#192]
### Mikä vikana?

Asiakkaan borrowernumber=431064 varaukset eivät näy. Varaukset-välilehdellä on tieto, että asiakkaalla on 39 varausta, muta mitään tietoja varauksista ei näy.

Finna sanoo asiakkaalle, että järjestelmästä ei saa tietoja, ja että hänellä ei ole varauksia.

### Selain

```markdown
Kokeiltu Firefoxilla ja Chromella.
```

### Jotain muuta?

![Asiakkaan varaukaukset eivät näy](https://user-images.githubusercontent.com/98962815/193811803-80303eba-08cd-476f-99d5-ac290eae8c84.png)

### Kohan osio

Varaukset

**Comment by johannaraisa** [comment]
Liittyy jotenkin biblionumber=1856340 varauksiin, jotain on voinut jäädä kun tuota teosta palautettiin. Ehkä kokeilisin tehdä varauksen uudestaan.

**Comment by noorsuva** [comment]
Ongelma johtui tästä lehdestä biblionumber=1856011. Siellä oli tapahtunut jotain todella kummallista. Myös toisella asiakkaalla, jolla oli varaus lehteen, oli sama tilanne että varaukset eivät näy. Hänen kotikirjastonsa on TOPK, varattu nide TOPK mutta noutokirjasto ENPK. Tämän lisäksi hänen varauksensa näkyi TLPE:n hyllyvarauslistalla, mutta siinä ei näkynyt noutokirjastoa laisinkaan. Ensimmäisen asiakkaan tapauksessa varauksen noutokirjasto oli myös ENPK, vaikka olisi pitänyt olla TLPE. Molemmat asiakkaat ovat kirjastojen työntekijöitä, joiden varausten noutopisteet pitäisivät olla TLPE ja TOPK. Mitähän kummaa tässä on voinut tapahtua :D

**Comment by johannaraisa** [comment]
Tämä on kyllä mysteeri minullekin, varausten hakeminen kaatui tuohon että ei saanut haettua noutokirjastoa. Ajattelin ensin, että tämä liittyisin Me Naiset liittyvään hankinnan palautukseen, ei näköjään liity. No ainakin selvisi missä vika, pahoin pelkään ettei tuosta pääse näillä tiedoilla paremmin perille.

**Comment by AnneliO** [comment]
Oisko tässä nyt sama kuin tiketissä https://tiketti.koha-suomi.fi/issues/5616? Eli varaus on tehty siirtymällä Finnasta Kohaan kirjanmerkillä ja Finnasta on tullut mukana osoitteessa ylimääräistä tauhkaa, joka aiheuttaa varauksen tallentumisen ilman noutokirjastoa. Kirjanmerkistä on uudet versiot tuossa tiketissä.

Jos varaus tallentuu ilman noutokirjastoa, silloin tietueen varausjonossa näyttää siltä kuin noutokirjasto olisi kirjastovalikon ensimmäinen vaihtoehto. Tuo ENPK kuulostaisi siltä, että se voisi olla ensimmäinen.

**Comment by noorsuva** [comment]
Tuo siinä on täytynyt käydä. ENPK on tosiaan meillä ensimmäisenä. Kiitos!
