### ISSUE TITLE
Helle: vuoden 2021 lehtitilausten sulkeminen  

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#195]
### Tukipyyntö

Suljetteko Hellen vuoden 2021 lehtitilaukset ja päivitättekö vuoden 2021 lehtitilausten odottaa-tilaisten tilan.

### Kohan osio

Kausijulkaisut

### Jotain muuta?

Tiketti vuoden 2020 lehtitilausten sulkemisesta:
https://tiketti.koha-suomi.fi/issues/4971

**Comment by paxed** [comment]
Tämä tehty näillä rimpsuilla:

```
UPDATE subscription SET closed='1' where startdate > '2020-12-31' and enddate < '2022-01-01';
UPDATE serial SET status=8 WHERE subscriptionid IN (SELECT subscriptionid FROM subscription WHERE closed=1) AND status=1;
```

**Comment by Kati-Helle** [comment]
Kiitos Lari :)
Suljenpa tämän.
