### ISSUE TITLE
[Tukipyyntö] Kaikille kimpoille totalissues-arvon päivitys 942$0-kenttään

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#196]
### Tukipyyntö

Tietueen 942$0-kenttään eli tietokannassa biblioitems.totalissues-kenttään päivittyy tietueen kaikkien niteiden lainojen määrä, mutta se ei ole ajan tasalla esim. konversioiden jälkeen. Kentän avulla olisi helppo hakea lainatuimmat teokset.

Kaikkiin kimppoihin pitäisi päivittää tuo arvo ajantasalle.

Tällä hetkellä tiedon päivittää update_totalissues.pl -cron job, mutta sekään ei tunnu toimivan oikein (teen tästä erillisen tiketin). Lisäksi nidekohtaisesti päivittyy lainamäärä items.issues-kenttään. Tähän kyseiseen kenttään on tuotu konversioissa niteen lainamäärä edellisestä järjestelmästä (ainakin osassa konversiota).

### Kohan osio

Raportit ja tilastot

**Comment by ajrajala** [comment]
[Tämä vanha tekemäni tiketti](https://tiketti.koha-suomi.fi/issues/4525) taitaa koskea samaa asiaa, voineeko tuon Redmine-tiketin sulkea pois kuleksimasta?

**Comment by AnneliO** [comment]
Jes, sulje vaan. :)

Nostan sieltä myös tänne varalta Johannan ja Pasin kommentit.

Johanna Räisä

Kimpoilta täytyy kommentoida run_broadcast_biblios.pl croni, ennen kuin muutetaan kaikkia tietueita.

Pasi Kallinen

myös Finnan kanssa sovittava ettei haravoi kaikkia tiedostoja?

**Comment by AnneliO** [comment]
Tiketissä #1175 on päätetty, että totalissues-ajot laitetaan kaikilta pois päältä ja poistetaan marc-kytkös totalissues-sarakkeeseen. Tätä ei tarvitse siis toteuttaa, joten suljen tiketin.

Lisäksi on toteutettu SQL-kysely, joka laskee tietueen kaikkien (myös poistettujen) niteiden laina- ja uusintamäärät.
