### ISSUE TITLE
[Kehitysehdotus] Signum-plugarit käyttämään ensisijaisesti 942$m-kenttää

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#197]
### Kehitysehdotukseni

Vaihdetaan signum-plugarit käyttämään ensisijaisesti aakkospaikkana 942$m-kenttää. Jos kenttää ei ole, käytetään pääsanaa pääsanakirjauskentistä tai näiden puuttuessa nimekekenttää.

### Kohan osio

Niteet

**Comment by emta001** [comment]
Viety testeille.

**Comment by emta001** [comment]
> Onko tämä muutos tehty kaikkiin plugreihin, koska ainakin loc_084a_mainheading_signum_builder.pl pääsana tulee edelleen 245-kentästä, vaikka 942m-kentässä on arvo. Esim. https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1799395

Hmm, pitäisi tän muutoksen koskea myös kyseistä plugaria.

**Comment by emta001** [comment]
Niin siis täähän saattas toimia hieman paremmin jos päivittäisinkin nuo testit :smile:

**Comment by emta001** [comment]
Toimiiko nyt?

**Comment by AnneliO** [comment]
Ainakin mulla näytti toimivan, mutta odotellaan vielä muidenkin kommentteja. :)

**Comment by Kati-Helle** [comment]
Toimivalta vaikutti Helle-testissä: signum-plugin haki signumin pääsana-arvoksi 942$m-kenttäarvon kolme ensimmäistä merkkiä.
Kuvailupohjassa käytössä tämä: loc_ccode_084a_mainheading_signum_builder.pl

**Comment by AnneliO** [comment]
Heikkisen Antti testasi myös ja totesi toimivaksi.

Kun tämä uusi versio plugarista otetaan käyttöön, pitää kuvailupohjiin käydä laittamassa muokkaukseen/editoriin näkyviin kentät 942him.

**Comment by emta001** [comment]
Tila vaihdettu "Ratkaisu ehdotettu". Ominaisuus tulee käyttöön ensi viikon päivityksessä.

**Comment by AnneliO** [comment]
> Tämä signum-plugari-kehitys tehnee Pääsana hyllyttäessä -tyylisen kuvailupohjan käytöstä tarpeettoman?

Kyllä, näin se tekee.

**Comment by Kati-Helle** [comment]
Tiedoksi vielä, että testini perusteella oikean signumin muodostumiseen riitti vain 942m-kenttätiedon lisääminen tietueelle.

**Comment by AnneliO** [comment]
Muutos viety tuotantoon.
