### ISSUE TITLE
[Kehitysehdotus] Hyllytarkenne näkymään niteen palautukseen.

### ISSUE THREAD

**Issue by johannaraisa** [KohaSuomi/Koha#198]
### Kehitysehdotukseni

Hyllytarkenne näkyy nyt vain teosnäytöllä, joten palautustilanteessa ei tiedetä pitäisikö nide sijoittaa jonnekin muualle.

### Kohan osio

Palautus

**Comment by johannaraisa** [comment]
Lisäsin testeille tämän, pitäisi näkyä palautuksessa taulukon tiedoissa.

![Image](https://user-images.githubusercontent.com/1818117/194285117-a2ca7d03-4e7e-462d-8554-07642f840f46.png)

**Comment by Kati-Helle** [comment]
Helle-testissä näkyy palautuksen Shelving location -sarakkeessa. 
Hienoa!

![kuva](https://user-images.githubusercontent.com/99952449/194469143-3e8c4de6-8526-4216-93f9-d525a56da4aa.png)

**Comment by johannaraisa** [comment]
Hyvä juttu, eiköhän se toimi, ei ollut kovin ihmeellinen lisäys. Laitan seuraavaan päivitykseen mukaan.

**Comment by Kati-Helle** [comment]
Hyllytarkenne näkyy nyt myös tuotannon palautuksessa.
Suljen tiketin.
