### ISSUE TITLE
[Tukipyyntö] Lumme: lapsiasiakkaan ns. takaajavalikkoon neljäs vaihtoehto

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#199]
### Tukipyyntö

Toiveena olisi saada tähän valikkoon myös vaihtoehto "Muu takaaja". Saadaanko lisättyä jostain kohtaa itse?
![huoltaja](https://user-images.githubusercontent.com/98803917/194291428-7200cdf5-4f88-47f4-9385-bdaf43b81718.png)

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Tuon valikon sisältöä hallinnoidaan  borrowerRelationship-järjestelmäasetuksella. Eli lisää haluamanne vaihtoehto sinne. :)

**Comment by Katja-Lumme** [comment]
Hyvä, kiitos tiedosta:)!
