### ISSUE TITLE
Helle: asiakasviestit eivät ilmesty tulostettaviksi eli asiakasviestien tulostaminen ei onnistu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#200]
### Mikä vikana?

Asiakasviestien tulostus -toiminnossa asiakasviestit eivät ilmesty tulostettavaksi.
Toiminto: Työkalut/Työkaluliitännäiset/Tulosta ilmoituksia 

Toiminnon avatessa toiminto hakee ja hakee mutta ilman tulosta ja haku jää pyörimään. Eri viestityyppien valinta onnistuu, mutta tästä ei ole apua hakutuloksettomuuteen.

Toiminnon Helle-näkymä:

![kuva](https://user-images.githubusercontent.com/99952449/194510673-84952b04-d5a8-4218-9f0a-1ab6ddfc3cee.png)

### Mitä pitäisi tapahtua

Tulostettavien asiakasviestien pitäisi tulla näkyville ja valittaviksi tulostusta varten.
Kirjaston suodatuksen pitäisi toimia Suodata-kohdassa.

**Comment by johannaraisa** [comment]
Nyt pitäisi toimia, jos ei vielä niin lataa sivun ctrl+f5. Samoja ongelmia kirjastojen kanssa kuin tarratulostuksessa.

**Comment by Kati-Helle** [comment]
Jep, nyt toimii. Kiitos Johanna :)
