### ISSUE TITLE
[Tukipyyntö] Lappi: Rovaniemen remontti - sijaintikirjaston muutos

### ISSUE THREAD

**Issue by noorsuva** [KohaSuomi/Koha#201]
### Tukipyyntö

Rovaniemen pääkirjaston kirjaston remontti on valmis ja toiminta siirtyy takaisin väliaikaiselta Revontulikirjastolta. Tarvitsemme sijaintikirjaston siirron seuraavasti:

1. kotikirjasto ROLO ja sijaintikirjasto ROPO ja tila saatavana, sijaintikirjasto muutetaan ROPO->ROLO
2. kotikirjasto on jokin muu, mutta sijaintikirjasto ROPO ja tila saatavana, sijaintikirjasto muutetaan ROPO->ROPK.

Muutoksen saa tehdä heti.

### Kohan osio

Niteet

**Comment by emta001** [comment]
Muutokset tehty seuraavilla rimpsuilla:

`CREATE TABLE items_kd201_20221007 SELECT * FROM items WHERE homebranch = "ROLO" AND holdingbranch = "ROPO" AND notforloan = 0;`
`UPDATE items SET holdingbranch = "ROLO" WHERE homebranch = "ROLO" AND holdingbranch = "ROPO" AND notforloan = 0;`

`CREATE TABLE items_kd201_20221007_2 SELECT * FROM items WHERE holdingbranch = "ROPO" AND notforloan = 0;`
`UPDATE items SET holdingbranch = "ROPK" WHERE holdingbranch = "ROPO" AND notforloan = 0;`

**Comment by noorsuva** [comment]
Kiitos!
