### ISSUE TITLE
OUTI: Poistetaan Failed-tilaiset EDIFACT-sanomat käsittelystä

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#203]
### Mikä vikana?

Poistaisitteko käsittelystä Iin kirjaston virheelliset EDIFACT-sanomat.

Poistettavat sanomat:
portaali_order_20221005150002.xml
portaali_order_20221005150004.xml
portaali_order_20221005161003.xml
portaali_order_20221005161006.xml

Poistan ko. sanomat EDIFACT-sivulta.

### Kohan osio

Hankinta

**Comment by lmstrand** [comment]
EditX-validaattori valittaa, ettei tilikoodia löydy Kohasta: 'IIPKKIKI2023'

**Comment by lmstrand** [comment]
Siirretty failed-archived -hakemistoon.

**Comment by piiaseme** [comment]
Kiitos, suljen tiketin.
