### ISSUE TITLE
[Bugi] Lumme: asiakastili lukkiutuu toistuvasti

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#205]
### Mikä vikana?

Kirjaston henkilökuntaan kuuluvan oma asiakastili lukkiutuu toistuvasti. Borrowernumber 130505. 

"Käytän tiliä enimmäkseen Lumme-Finnan kautta, jonne  kirjaudun joko puhelimen tai pädin Safari-selaimella (iOS 16, iPadOS 15.jotain), Näissä on kyllä kaikissa iCloudin kautta salasana tallennettuna, mutta ei siis ole automaattista sisäänkirjautumista, vaan käyttäjätunnus on itse näpyteltävä ensin, jotta ohjelma tietää antaa oikean salasanan. 

Lainaan useimmiten töissä Kohan virkailijapäätteellä ja joskus harvoin lainausautomaatilla. Lisäksi käytän tunnuksia ainakin iPhonen Ellibs-sovelluksessa ja selaimen kautta eMagzissa suht. säännöllisesti. Nyt on useamman kuukauden aikana käynyt monta kertaa niin, että **en ole päässyt kirjautumaan kirjaston koneella eBookingiin tai ovikoneella omatoimikirjastoon** ja kun olen Kohasta katsonut, niin tili on lukittu. Ja olen tietysti aina vaihtanut pin-koodin ”Vaihda salasana” -kohdasta, jolloin tilin lukitus poistuu. Viimeksi 4.10. tili oli lukittu ja uudelleen 6.10. "

Näkyykö mistään lokeista mitään?

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Jos menet katsomaan lokeja Työkalut -> Lokien katselu ja haet ID-tunnus-kentällä asiakkaan borrowernumberilla, niin siellä näkyy, että epäonnistuneita kirjautumisyrityksiä tulee Finnan kautta.

Nuo tiedot ei näy, jos menet asiakkaan tietojen kautta muutoslokille, koska silloin sivu rajoittaa tulokset vain lainaukseen ja palautukseen.

**Comment by janPasi** [comment]
Poistan bugi-merkinnän, koska melko varmasti ei ole bugi (jos olisi niin ilmenisi muillakin kuin yhdellä henkilöllä). Kyseessä on nyt jokin muu asia.

**Comment by janPasi** [comment]
"Käytän tiliä enimmäkseen Lumme-Finnan kautta, jonne kirjaudun joko puhelimen tai pädin Safari-selaimella (iOS 16, iPadOS 15.jotain), Näissä on kyllä kaikissa iCloudin kautta salasana tallennettuna, mutta ei siis ole automaattista sisäänkirjautumista, vaan käyttäjätunnus on itse näpyteltävä ensin, jotta ohjelma tietää antaa oikean salasanan.

Vaikuttaisi vähän siltä, että tässä taitaa kyllä olla niin että ohjelma ei nyt anna oikeaa salasanaa.

**Comment by Katja-Lumme** [comment]
@janPasi Jeps, miä välitän viestiä tälle henkilölle. Koska tosiaan jos olisi isompi juttu, niin näkyisi muillakin asiakkailla.

**Comment by kyyti** [comment]
Meillä on yksi asiakas, joka ei pääse kirjautumaan Finnaan ja Katilla oli Hellessä ongelmia. Ehkä näitä voisi koittaa kerätä tähän, jos kyse on laajemmasta ongelmasta. Pyysin asiakasta vielä koittamaan kirjautumista. 

select login_attempts as 'Kirjautumisyrityksiä' from borrowers where cardnumber=<<Kirjastokortin numero>> antaa nyt aamusta: kirjautumisyrityksiä: 0.

**Comment by Katja-Lumme** [comment]
Jep, nyt tuli meille juuri chattiin samasta asiasta kysymys. Kirjautumisyrityksiä rapsan mukaan nolla. Borrowernumber=18077

**Comment by kyyti** [comment]
Onko Finnapostista kommentoitu mitään? Voisiko liittyä Kansalliskirjaston uusimpaan päivitykseen?

**Comment by kyyti** [comment]
Tällä "meidän" asiakkaalla kokeilin täällä päässä vaihtaa PIN-tunnuksen, eikä se siltikään toimi.

**Comment by kyyti** [comment]
Kansalliskirjasto/Arto käski kokeilla esituotannossa ja kokeilin nyt kello 11:42. https://kyyti.finna-pre.fi/

Rajapinta näyttää palauttavan Finnan lokin mukaan "error":"Login failed.".

**Comment by Katja-Lumme** [comment]
Meillä nyt jo useampi tapaus asiakaspalautteiden perusteella...

**Comment by kyyti** [comment]
KK/Arto:

Kiitos lisätiedoista. Hieman hankalaa sanoa mistä johtuu ongelma. Voitteko olla yhteydessä Kohaan ja tarkistaa tätä vielä kun meillä ei oikein ole tämän enempää tietoa ongelmasta kuin tuo Finnan lokista löytyvä error Login failed.

**Comment by kyyti** [comment]
Hei,

Tuli yhtäkkiä mieleen, että Koha-Suomen puolella on tehty kirjautumiseen muutoksia, joiden myötä Kohan puolella huomioidaan epäonnistuneiden kirjautumisten määrä. Koska sitä ei aiemmin ole huomioitu rajapintaa käytettäessä, saattaa olla, ettei myöskään laskuria ole nollattu onnistuneen kirjautumisen yhteydessä.

t. Ere

Vielä tarkennuksena, etten ole varma siitä, onko tämä toiminnallisuus Koha-Suomessa tuotannossa. Jos on, niin Kohan asetus FailedLoginAttempts vaikuttaa siihen, ja voisi ainakin tarkistaa asetuksen ja kokeilla, onnistuuko kirjautuminen, jos sen tyhjentää.

t. Ere


Porvoossa oli huomattu, että kun korttinumerokenttä ja käyttäjätunnuskenttä eivät vastaa toisiaan, Finnaan kirjautuminen ei onnistu.
Minun tiedoissani käyttäjätunnus-kentässä ei ollut kirjastokortin numeroa. Nyt on ja Finnaan kirjautuminen onnistuu.

**Comment by lmstrand** [comment]
Tuotannoissa on nyt ollut Finna-pluginissa koodi, jossa ei ole tarkasteltu korttinumeroa jos kirjautujan userid-tieto puuttuu tai sen perusteella ei löydetä asiakasta. Olisiko tuon ominaisuuden puuttuminen aiheuttanut ongelmia. Tuotannossa on nyt uusi versio kirjautumisesta, jossa logiikka on selkeämpi ja myös userid:ttömien asiakkaiden kirjautumiset jatkuvat, jos asiakkaalla on korttinumero tiedoissaan. Toivotaan, että ratkaisisi ongelman.

**Comment by kyyti** [comment]
Kuulostaa ainakin juurisyyltä. Asiakas kertoo, että vielä lokakuussa kirjautuminen onnistui, eli tässä aika hiljakkoin jotain on mennyt rikki.

**Comment by kyyti** [comment]
Saamani tiedon mukaan korjaus tähän on nyt tehty Koha-Suomen puolesta, eli näiden ei enää pitäisi tarvita olla samat.

Finnalla ei siis ollut osaa eikä arpaa tässä, vaan ongelma oli Kohan koha-plugin-rest-di:n puolella.

t. Ere

**Comment by janPasi** [comment]
Onko tämä ratkennut? Voidaanko tiketti sulkea?

**Comment by kyyti** [comment]
Kyytin asiakkaalla userid kentän korjaaminen samaan arvoon, kun kirjastokortti-kentässä korjasi ongelman. Meillä oli vain tuo yksi asiakas ongelmallinen.

**Comment by Katja-Lumme** [comment]
Meilläkään ei valituksia enää ole tullut, suljen tiketin:)
