### ISSUE TITLE
[Bugi] Tätissä välivarastoitu erä 4818 on staging-tilassa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#206]
### Mikä vikana?

Tätissä Kirjastopalvelun päiväpaketti https://tati.koha-suomi.fi/cgi-bin/koha/tools/manage-marc-import.pl?import_batch_id=4818 on jäänyt staging-tilaan, eikä tietueet ole siirtyneet tietokantaan. Erän tiedoista puuttuu mm. täsmäytyssääntö RCN. Tietueita ei saa vietyä liittymän kautta tietokantaan.

### Mitä pitäisi tapahtua

Erän tietueet pitäisi saada vietyä tietokantaan.

**Comment by emta001** [comment]
Batchin käsittely oli epäonnistunut koska huoltokatkossa Elasticsearch oli mennyt pois päältä. Katsotaan auttaako cronin uudelleenajo huomen aamuna tähän. Säädettiin cronin ajastusta kuitenkin tunnilla taaksepäin (klo 06:05) ettei se jatkossa satu samaan aikaan huollon kanssa.

**Comment by AnneliO** [comment]
/var/spool/koha/importedMARC/BTJbiblios/B20221012xmav-601 (erä 4818) ei tullut käsitellyksi uudelleen, mutta toinen 12.10.2022 tullut tiedosto /var/spool/koha/importedMARC/BTJbiblios/B20221012xmk-601 (erä 4819) oli käsitelty. En muista, että sitä olisi eilen ollut tuolla eräluettelossa.

Mitähän tuon kanssa nyt tekisi? Viedään manuaalisesti käyttöliittymän kautta tiedosto?

**Comment by AnneliO** [comment]
Tiedosto saatiin uudelleen sekä palvelimelle (hakutoiminto ehkä haki sen uudelleen, koska vanha poistettiin) että sähköpostitse Kirjastopalvelusta. Tietueet viety nyt Tätiin.
