### ISSUE TITLE
[Bugi] Suomi.fi-palvelua ei voi lisätä asiakkaan viestiasetuksiin 

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#207]
### Mikä vikana?

Edellisessä Kohaversiossa Vaarassa oli asiakkaan viestiasetuksissa käytössä valinta, jonka kautta viestit sai suomi.fi-palveluun. Nyt tämä sarake puuttuu kokonaan asiakastiedoista ja sitä on kysytty. Ennen versionvaihtoa merkityt valinnat suomi.fi-palvelun käyttöön toimivat (mm. minulle tulee palautusviestit sitä kautta).

### Mitä pitäisi tapahtua

Pitäisi saada asiakastietoihin näkyviin sarake, jossa voisi valita suomi.fi-palvelun viestien vastaanottotavaksi.

### Kohan osio

Viestit

**Comment by paxed** [comment]
suomifi pitänee lisätä kohan template-tiedostoon koha-tmpl/intranet-tmpl/prog/en/includes/messaging-preference-form.inc

**Comment by lmstrand** [comment]
Testeille lisätty Suomi.fi -viestiasetustäpät. Täpät noudattavat Paikalliskäyttö(Local use)-asetusta SuomiFiMessaging, jonka totuusarvon mukaan täpät joko näytetään tai ei näytetä. Lisää paikalliskäyttöasetus 'SuomiFiMessaging' testataksesi. Viestiasetus lisätty jo Vaaran testille.

**Comment by IrinaHalminen** [comment]
Mielestäni toimii Vaaralla, kuten pitääkin.

**Comment by AnneliO** [comment]
Lisätty tuotantoon ja näkyy.
