### ISSUE TITLE
[Bugi] Tarratulostustyökalun tarrapohjien esikatselu menee yhdelle riville

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#208]
### Mikä vikana?

Työkalun esikatseluruudussa tarran ja signumin kaikki kentät näkyvät yhdellä rivillä. Tulostettaessa tarrat tulostuvat oikein. Vika vaikuttaisi olevan esikatselun div-elementin käyttämässä position-relative classissa ja span-elementtien käyttämässä position-absolute classissa, koska vastaavien tyylimuotoiluiden lisääminen elementtien style-määrittelyihin korjaa ongelman.

### Kohan osio

Työkalut

**Comment by PiaKusmin** [comment]
Voisiko tähän saada pikaista korjausta? Meille tulisi uusi tarrapohja, jota on todella vaikea muokata, kun ei hahmota kenttien paikkoja. (Ja kun pohjan tekijä ja itse tarratulostin ovat eri kaupungeissa...)

**Comment by AnneliO** [comment]
Mulla toimii Chromessa oikein asettelut (ainakin välimuistin tyhjennyksen jälkeen). Kokeiletteko miten teillä? Firefoxissa ei tuntunut auttavan välimuistin tyhjennys tai ctrl+f5.

**Comment by MikkoLiimatainen** [comment]
Chrome kyllä rivittää nuo span-elementit, mutta eivät ne mene lähellekään oikeita paikkoja. Vasta kun lisää nuo position:relative ja position:absolute stylet elementteihin selaimen tarkista-toiminnolla, menevät ne oikeille paikoilleen.

**Comment by AnneliO** [comment]
No niin vain, katsoin vain nopeasti, että ovat oikeilla paikoilla Chromessa, mutta eipä ne olekaan.

**Comment by emta001** [comment]
Vaikuttaisi sille, että esikatselussa ei nyt jostain syystä toimi Bootstrap. Se, että noissa elementeissä on käytetty position-absolute ja position-relative classeja, viittaisi siihen. Edellisen kerran kun plugaria päivitettiin, noihin tyylikirjastojen hakuun näyttäisi tulleen jotain päivitystä. Ehkäpä sieltä tippui jotain mitä ei olisi pitänyt tippua.

**Comment by lmstrand** [comment]
Ongelmana oli väärä versio bootstrapin tyylitiedostosta. Ongelma korjattu suoraan tuotantoihin. Selaimen välimuisti/cache pitää tyhjentää, jotta tuo oikea kirjasto tulee uudelleen ladatuksi palvelimelta työkalua käyttäessä.
