### ISSUE TITLE
[Tukipyyntö] Vaski: Virheellisten sähköpostien poisto

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#209]
### Tukipyyntö

Voisiko Vaskista poistaa asiakkailta virheelliset sähköpostiosoitteet ja lisätä asiakkaille viesti ”Virheellinen sähköpostiosoite poistettu”?

Sain virheellisen sähköpostin omaavien asiakkaiden määräksi 238 tällä kyselyllä:
`select borrowernumber
from borrowers
where (email not like '%@%' and email is not null and email!='') OR email like '% %'`

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Asiakkaita on sen verran vähän, että ne pystyy  minusta käymään läpi käsin, varsinkin jos työn jakaa useammalle henkilölle. En käyttäisi tällaiseen siivoustyöhön kehittäjien työaikaa. :)
