### ISSUE TITLE
[Bugi] Kyyti: Nide lainassa ja saatavana samaan aikaan

### ISSUE THREAD

**Issue by tuokun** [KohaSuomi/Koha#210]
### Mikä vikana?

Nide on lainassa ja saatavana samaan aikaan.
https://kyyti.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1448884

Mistä on kyse ja miten korjataan?

### Jotain muuta?

![lainassa_ja_saatavana](https://user-images.githubusercontent.com/99244794/195594292-d202383f-3fc7-4097-8550-04bf8005cdc4.png)

### Kohan osio

Niteet

**Comment by AnneliO** [comment]
Muutoslokilla ei ole kirjausta, että nidettä olisi lainattu kyseiselle asiakkaalle. Siellä on kyllä lainaushetkelle kirjaus, jossa virkailija muuttaa niteen tietoja.

Niteen onloan-arvo items-taulussa on NULL, joten se selittänee, miksi perustiedot-näytöllä tilaksi sanotaan "Saatavana".

Eli en osaa sanoa, mitä tässä on käynyt. Lainaushetkellä todennäköisesti sattunut jotain poikkeavaa.

**Comment by janPasi** [comment]
Niteen issuedate issues taulussa on 2022-09-19 18:28:54. Jännä myös, että liittymä näyttää 2 uusintakertaa, vaikka issues taulussa renewals on 0.

**Comment by tuokun** [comment]
Tilanne on oiennut ajan kanssa. Syy jäänee arvoitukseksi.
