### ISSUE TITLE
[Bugi] Lappi: Asiakkaan varaukset eivät näy Finnassa, Kohassa näkyy

### ISSUE THREAD

**Issue by noorsuva** [KohaSuomi/Koha#212]
### Mikä vikana?

Rovaniemeltä on raportoitu kaksi tapausta, jossa asiakas ei näe varauksia Finnassa, vaikka ne näkyvät Kohassa normaalisti. Asiakkaat ovat borrowernumber=407112 ja borrowernumber=414075. Finnassa näkyy teksti "Kirjastojärjestelmään ei saatu yhteyttä. Tietoja, jotka liittyvät tiliisi kirjastossa, ei voida näyttää. Jos ongelma jatkuu, ota yhteyttä kirjastoon." Lainat heillä näkyy normaalisti. Ei taida liittyä Finna->Koha kirjanmerkkeihin, kun Kohan puolella kaikki näyttää olevan ok?

### Kohan osio

Verkkokirjasto

**Comment by lmstrand** [comment]
Lapin testi-Finnassa molempien asiakkaiden varaukset näkyivät ja tulivat haetuksi ihan ok. Borrowernumberilla borrowernumber=407112 oli yli sata varausta. Olisiko siinä syy, että tietojen hakeminen kestää liian kauan ja testi-Finnassa/Kohassa ei ole mitään aika/määrärajoitteita tietojen hakuun? Toisaalta toisen asiakkaan kanssa ei pitäis olla mitään ongelmia, kuin tuotannossa varauksia on vain neljä- Tällä toisella asiakkaalla oli vain kaksi varausta testillä ja nekin näkyivät testi-Finnassa ihan ok. Koodi, jonka avulla jutellaan Kohan kanssa Testi-Finnassa on sama, kuin mitä tuotanto-Finna käyttää. Onko mahdollista selvittää, onko ongelma edelleen olemassa?

**Comment by noorsuva** [comment]
Tänään ei ole tullut ilmoituksia, mutta vielä eilen illalla tuli toisesta kirjastosta että useamman asiakkaan tiedot eivät näy Finnassa. Mutta me testaillaan ja seurataan tilannetta.

**Comment by noorsuva** [comment]
Käyttäjällä borrowernumber=436789 on sama ongelma, kolmas kirjasto josta raportoidaan vikaa.

**Comment by MariaJoon** [comment]
Sama ongelma käyttäjälläborrowernumber=482245.  Kohan puolella kuitenkin näkyy 30 varausta.

**Comment by janPasi** [comment]
Onko näillä asiakkailla tai heidän varauksillaan jotain yheisiä tekijöitä? Kohdistuvatko "kummittelevat" varaukset esimerkiksi samaan nimekkeeseen?

**Comment by MariaJoon** [comment]
Ainakaan tällä hetkellä varauksia ei ko asiakkailla ole samoihin nimekkeisiin, asiakkaat ovat eri kirjastoista, ja ongelmat ilmenneet eri ajankohtina. Viimeisimmän raportoidun asiakkaan kohdalla (482245) tänään kokeillessa Kohakaan ei ensimmäisellä kerralla näyttänyt minulle asiakkaan varauksia (ts. varaukset eivät näkyneet Kohan välilehdellä), mutta heti uudelleen yritettäessä näytti. Toisaalta tämä asiakas oli ilmeisesti kokeillut Finnassa varausten katsomista useana päivänä peräkkäin, eikä se ollut onnistunut.

**Comment by janPasi** [comment]
Kuulostaisi ehkä hieman jonkin sortin timeout-ongelmalta, mutta onpas omituista jos ilmenisi vain Lapissa.

**Comment by janPasi** [comment]
Kurkkasin tässä omalla työasemallani tuota asiakasta Kohassa ja minulla varaukset latautuivat ihan sutjakasti.

**Comment by MariaJoon** [comment]
Joo, mullakin toisella klikkauksella latautui ongelmitta, eikä virkailijoilla ole ollut ongelmia näiden asikkaiden varausten näkymisessä Kohassa.

**Comment by janPasi** [comment]
Kokeilin testi-Finnassa vielä kirjautumista tuona 482245 käyttäjänä ja hitaasti kyllä tapahtui kirjautuminen, mutta varaukset (95 kpl) suostuivat silti näkymään.

**Comment by AnneliO** [comment]
Voisko liittyä tähän #280?

**Comment by lasse-koha** [comment]
> Voisko liittyä tähän #280?

Lapista näitä virheellisiä niteitä ei enää löydy, joten jos ongelma jatkuu niin se johtunee jostain muusta.

**Comment by AnneliO** [comment]
@noorsuva @MariaJoon Juteltiin tästä kehittäjien palsussa tänään ja Lapin ongelmat voivat johtua tuosta AllowRenewalIfOtherItemsAvailable. Olisiko mahdollista, että otatte Lapissa pois käytöstä tuon asetuksen ja seuraatte, onko sillä vaikutusta ongelman esiintymiseen?

**Comment by MariaJoon** [comment]
Ok, me kokeillaan ottaa se pois päältä.

**Comment by AnneliO** [comment]
Miltä näyttää, oliko asetuksen muutoksella merkitystä? :)

**Comment by lasse-koha** [comment]
Kohan koodista on jo pari vuotta sitten siivottu pois noita 0000-00-00 -arvoja mutta kyllä niitä näköjään edelleenkin joissain erikoistapauksissa syntyy (esim. jos päivämääräkenttään kirjoittaa 0*). Jos kirjoittaa pelkän nollan tai jättää kentän tyhjäksi, tietokantaan tallentuu oikein NULL mikä kelpaa Finnallekin.

https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=7806

Sen verran harvinaisia virheitä ilmeisesti kuitenkin että voi hyvin korjata käyttöliittymästä käsin. Niteitä muokatessa olisi hyvä tarkistaa että päivämääräkentissä on järkevät päivämäärät oikeassa muodossa (tai että ne ovat kokonaan tyhjiä). Virheelliset niteet löytyvät raportilla:

https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Valmiita_SQL-raportteja#Niteet-joissa-Hakintap%C3%A4iv%C3%A4m%C3%A4%C3%A4r%C3%A4-tai-Hinta-voimassa-alkaen-kent%C3%A4ss%C3%A4-on-arvo-0000-00-00

**Comment by Kati-Helle** [comment]
Ovatkohan kaikki 0000-00-00 arvon mahdolliset lisäystavat tiedossa? Jos, niin saisiko kenttään eston ko. arvojen syöttämiseen ja/tai tallentumiseen?

**Comment by AnneliO** [comment]
> Ovatkohan kaikki 0000-00-00 arvon mahdolliset lisäystavat tiedossa? Jos, niin saisiko kenttään eston ko. arvojen syöttämiseen ja/tai tallentumiseen?

Onko Kati Hellessä tehty nämä [viikon 10 palaverissa](https://koha-suomi.fi/paakayttajat2023#viikko-10-muistio) sovitut muutokset kuvailupohjiin?

**Comment by Kati-Helle** [comment]
Juu, nuo on tehty Helleen.

**Comment by lasse-koha** [comment]
Suljen tämän tiketin, jos nollapäivistä on vielä ongelmia avataan niistä uusi.

**Comment by lmstrand** [comment]
Nollapäivät eivät vaikuta lainojen näkymiseen Finnassa.
