### ISSUE TITLE
[Kehitysehdotus] 505$r author- ja author-in-order indeksiin

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#213]
### Kehitysehdotukseni

MARC-osakenttä 505$r pitäisi määrittää indeksoitumaan Elasticsearchin author- ja author-in-order -indekseihin.

**Comment by janPasi** [comment]
505$r ei kyllä taida kuulua titleen (nimeke), siellähän on tekijän vastuullisuusmerkintöjä, eli ennemminkin authoreita.

**Comment by lmstrand** [comment]
Kaikkiin kimppoihin päivitetty uusi Elasticsearch-konfiguraatio. Muutos vaatii uudelleenindeksoinnin.

Siilinjärvi on uudelleenindeksoitu eilisiltana 7.11.

**Comment by lmstrand** [comment]
Vaara ja Helle uudelleenindeksoitiin eilen illalla 10.11. - 11.11.

**Comment by lmstrand** [comment]
Lappi ja Outi uudelleenindeksoitu eilen illalla 17.11.

**Comment by AnneliO** [comment]
Hakua voi testata esim. teoksella https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2289313 eli Marple, 978-0-00-846731-9

**Comment by ajrajala** [comment]
Vaskissa testattu, että haku toimii.

**Comment by pknuuti** [comment]
Vaarassakin haku toimii.

**Comment by AnneliO** [comment]
OUTIssakin toimii.

**Comment by AnneliO** [comment]
Seuranta

| Kimppa | Tehty | Tarkistettu toimivaksi |
| --- | --- | --- |
| Helle | x ||
| Kyyti | x ||
| Lappi | x ||
| Lumme | x ||
| OUTI | x | x |
| Siilinjärvi | x ||
| Vaara | x | x |
| Vaski | x | x |

**Comment by Tuomas-Kyyti** [comment]
Kyytissä toimii.

**Comment by AnneliO** [comment]
[ ] Helle
[ ] Kyyti

**Comment by AnneliO** [comment]
- [ ] Helle

**Comment by LeenaKinnunen** [comment]
Lappi toimii.

**Comment by AnneliO** [comment]
Kaikkialla toimii, joten suljen tiketin. Kiitos!
