### ISSUE TITLE
[Tukipyyntö] Kuvailupohjiin käyttöön 942$b-kenttä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#215]
### Tukipyyntö

Saisiko kaikkiin kimppoihin ajettua kaikkiin kuvailupohjiin osakentän 942$b ja siihen auktorisoidun arvon YES_NO?

### Kohan osio

Ylläpito

**Comment by AnttHeik** [comment]
Olisikohan tätäkin mahdollista asentaa seuraavan tiistaipäivityksen yhteydessä?

**Comment by AnneliO** [comment]
Ajo on tehty ja kentät pohjissa. Suljen tiketin.
