### ISSUE TITLE
[Tukipyyntö] Käyttöoikeuden suggestions_manage poistaminen käyttäjiltä.

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#217]
### Tukipyyntö

Hankintaehdotuksia ei enää tehdä Kohan kautta, joten käyttöoikeus suggestions_manage on turha ja voidaan ottaa pois käyttäjiltä.

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Poistetaanko kumpikin suggestion-oikeus?

**Comment by emta001** [comment]
> Poistetaanko kumpikin suggestion-oikeus?

Jos tarkoitat poistetaanko myös yläoikeus suggestions, niin kyllä. Muitahan suggestions-oikkia ei taida olla?

**Comment by emta001** [comment]
Niin aivan, hankinnat oikissa on myös sama oikka. Ainakin mitä Hellessä ja Lumpeessa noita poistin niin se meni siinä samassa. Sekin lienee turha, joten kai se voi mennä.

**Comment by emta001** [comment]
Käyttöoikeus poistettu muilta kimpoilta paitsi Helleltä ja Lumepeelta (tehtiin jo aiemmin) sekä OUTIlta (tehdään käsin) seuraavasti:

```
DELETE FROM user_permissions WHERE code = "suggestions_manage";
UPDATE borrowers SET flags = flags - (1<<12) WHERE flags = flags | (1<<12);
```
