### ISSUE TITLE
[Kehitysehdotus]Asiakkaan eräpäiväkuittiin lainat eräpäiväjärjestykseen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#218]
### Kehitysehdotukseni

Kun asiakkaalle tulostetaan hänen kaikista lainoistaan kuitti (ISSUESLIP), olisi lainat hyvä saada kuitille eräpäiväjärjestykseen, jotta niitä on helpompi seurata. Ennen versionvaihtoa kuitti tulostui eräpäiväjärjestyksessä.

**Comment by lmstrand** [comment]
Tästä taidettiin keskustella joskus aiemminkin, eikä muutosta hyväksytty. Vaatisi koodimuutoksen eikä voi tehdä kimppakohtaisesti kuittipohjassa. Voin ottaa vielä puheeksi, josko tuohon olisi joku kikka.

**Comment by janPasi** [comment]
Kyseessä taisi olla Koha-Suomi muutos ja niistähän juuri haluttiin eroon versiopäivityksessä. Mielestäni tätä voisi kyllä edistää yhteisössä, koska toive on minusta sinänsä kyllä hyvinkin perusteltu.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 15.1.2024: Tästä löytyy yhteisöstä tiketti, joka ei ole edennyt pitkään aikaan. Yritetään edistää asiaa yhteisössä.

[Yhteisön tiketti](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=12388)

**Comment by IrinaHalminen** [comment]
Tähän myöhästynyt lisähuomio, että asiakkaan lainathan voi järjestää lainausnäytöllä hyvin monipuolisesti (vaikkapa lainauspäivämäärän mukaan, aakkosjärjestykseen tms.) ja jos käyttää selaimen tulostusta, näkymän saa tulostettua valitussa järjestyksessä. Olisi hienoa, jos sama joustavuus toimisi myös, jos kuitin tulostaa Kohan toiminnolla. Eli en peräänkuuluta vain eräpäivän mukaista vaan järjestetyn näkymän mukaista tulostusasettelua.

**Comment by lmstrand** [comment]
Ratkaistu yhteisössä tiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37636.

**Comment by lmstrand** [comment]
Sain rakennettua tähän syntaksin, jolla lainoja voi järjestellä periaatteessa minkä tahansa kentän perusteella nousevassa tai laskevassa järjestyksessä (sort, nsort, reverse).

ISSUESLIP:lle pohja näyttäisi tältä Template Toolkitillä toteutettuna:

```
[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[%~ SET item = checkout.item ~%]
[% sortedcheckouts.push(checkout)  %]
[% END %]

[% sortedcheckouts = sortedcheckouts.nsort('checkout.date_due') %]


Lainatut:
<br>
[% FOREACH checkout IN sortedcheckouts %]
[% checkout.item.biblio.title %] - [% checkout.item.biblio.author %]
-- Eräpäivä: [% checkout.date_due | $KohaDates with_hours => 1 %]
Uusittu
[% checkout.renewals_count %]
kertaa
<br>
[% END %]


[% sortedoverdues = [] %]
[% FOREACH overdue IN overdues %]
[%~ SET item = overdue.item ~%]
[% sortedoverdues.push(overdue)  %]
[% END %]

[% sortedoverdues = sortedoverdues.nsort('overdue.date_due') %]

<br>
Myöhssä olevat:
<br>
[% FOREACH overdue IN sortedoverdues.reverse %]
[% overdue.item.biblio.title %]
-- Eräpäivä: [% overdue.date_due | $KohaDates with_hours => 1 %]
Uusittu
[% overdue.renewals_count %]
kertaa
<br>
[% END %]

```

Tällä pohjalla lainat ja myöhässä olevat järjestyvät eräpäivän mukaan vanhin päivämäärä ensin.

![image](https://github.com/user-attachments/assets/16117736-7546-4c3f-b051-dc4e183452a0)

**Comment by lmstrand** [comment]
Yhteisön tiketti ei siis tule järjestämään lainoja eräpäivän mukaan, vaan lainaamispäivän mukaan.

**Comment by lmstrand** [comment]
Tekijä jäi puuttumaan myöhässä olevista, lisäsin koodiin.

**Comment by pknuuti** [comment]
Kopioin tuon ISSUESLIPin koodin Vaaran nextille. Kokeilin asiakkaan https://vaara-next.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=10997006 lainoilla eikä ne järjestyneet kuitille (Tulosta kuitti) eräpäiväjärjestykseen. Enkö hoksaa jotain vai eikö tämä toimi oikein?

**Comment by lmstrand** [comment]
Ei taida sitten toimia oikein. On varmaan omalla koneellani sattunut olemaan järjestyksessä omalla testitapauksellani. Koitan fikstata tuota Vaara-nextillä tuon asiakkaan kanssa.

**Comment by lmstrand** [comment]
Fiksasin syntaksia vähän, lisäsin vaara-nextin testiasiakkaalle muutaman lainan ja vaihdoin niille eräpäivää.
Nyt näyttäisi menevän oikeassa järjestyksessä lainat eräpäivän mukaan.

**Comment by pknuuti** [comment]
Nyt näyttäis menevän oikein. Hyvä juttu.

**Comment by lmstrand** [comment]
Lisäsin dokumentaatioon.

**Comment by pknuuti** [comment]
Kiitos!

**Comment by LLK-Hanninen** [comment]
Kiitos! Muotoilin näistä Lastuun versiot kaikki lainat ja tänään lainatut kuiteille jos joku haluaa hyödyntää tai jatkokehittää:

ISSUEQLSLIP
Suomeksi:
`[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-kirjastot<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Lainattu tänään</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% checkout.date_due | $KohaDates with_hours => 0 %]</p> 
[% END %]


<p>Yhteensä: [% checkouts.count %][% IF checkouts.count > 1 %]
      lainaa
[% ELSE %]
      laina
    [% END %] </p>
<p>Maksut:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Tervetuloa uudelleen! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />`

Englanniksi:
`[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-libraries<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Today's checkouts</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% checkout.date_due | $KohaDates with_hours => 0 %]</p> 
[% END %]


<p>Total: [% checkouts.count %][% IF checkouts.count > 1 %]
      checkouts
[% ELSE %]
      checkout
    [% END %] </p>
<p>Fines:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Welcome back! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />`


ISSUESLIP 
Suomeksi:
`[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-kirjastot<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Lainat</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% checkout.date_due | $KohaDates with_hours => 0 %], uusittu [% checkout.renewals_count %]/5 kertaa</p> 
[% END %]

<p>Yhteensä: [% checkouts.count %]</p>

[% sortedoverdues = [] %]
[% FOREACH overdue IN overdues %]
[% sortedoverdues.push(overdue)  %]
[% END %]

<h2>Myöhässä olevat lainat</h2>

[% FOREACH overdue IN sortedoverdues.sort('date_due') %]<p>
[% overdue.item.biblio.title %] [% overdue.item.biblio.subtitle %] [% overdue.item.biblio.part_name %] [% overdue.item.biblio.part_number %] [% overdue.item.enumchron %] [% overdue.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% overdue.date_due | $KohaDates with_hours => 0 %], uusittu [% overdue.renewals_count %]/5 kertaa</p>

[% END %]
<p>Yhteensä myöhässä: [% overdues.count %]</p>
<p>Maksut:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Tervetuloa uudelleen! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />`

Englanniksi:
`[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-libraries<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Checkouts</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% checkout.date_due | $KohaDates with_hours => 0 %], renewed [% checkout.renewals_count %]/5 times</p> 
[% END %]

<p>Items: [% checkouts.count %]</p>

[% sortedoverdues = [] %]
[% FOREACH overdue IN overdues %]
[% sortedoverdues.push(overdue)  %]
[% END %]

<h2>Overdue checkouts</h2>

[% FOREACH overdue IN sortedoverdues.sort('date_due') %]<p>
[% overdue.item.biblio.title %] [% overdue.item.biblio.subtitle %] [% overdue.item.biblio.part_name %] [% overdue.item.biblio.part_number %] [% overdue.item.enumchron %] [% overdue.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% overdue.date_due | $KohaDates with_hours => 0 %], renewed [% overdue.renewals_count %]/5 times</p>

[% END %]
<p>Number of items overdue: [% overdues.count %]</p>
<p>Fines:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Welcome back! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />`

**Comment by LLK-Hanninen** [comment]
Kiitos! Muotoilin näistä Lastuun versiot kaikki lainat ja tänään lainatut kuiteille jos joku haluaa hyödyntää tai jatkokehittää:

ISSUEQLSLIP
Suomeksi:
```
[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-kirjastot<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Lainattu tänään</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% checkout.date_due | $KohaDates with_hours => 0 %]</p> 
[% END %]


<p>Yhteensä: [% checkouts.count %][% IF checkouts.count > 1 %]
      lainaa
[% ELSE %]
      laina
    [% END %] </p>
<p>Maksut:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Tervetuloa uudelleen! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />
```

Englanniksi:
```
[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-libraries<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Today's checkouts</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% checkout.date_due | $KohaDates with_hours => 0 %]</p> 
[% END %]


<p>Total: [% checkouts.count %][% IF checkouts.count > 1 %]
      checkouts
[% ELSE %]
      checkout
    [% END %] </p>
<p>Fines:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Welcome back! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />
```


ISSUESLIP 
Suomeksi:
```
[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-kirjastot<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Lainat</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% checkout.date_due | $KohaDates with_hours => 0 %], uusittu [% checkout.renewals_count %]/5 kertaa</p> 
[% END %]

<p>Yhteensä: [% checkouts.count %]</p>

[% sortedoverdues = [] %]
[% FOREACH overdue IN overdues %]
[% sortedoverdues.push(overdue)  %]
[% END %]

<h2>Myöhässä olevat lainat</h2>

[% FOREACH overdue IN sortedoverdues.sort('date_due') %]<p>
[% overdue.item.biblio.title %] [% overdue.item.biblio.subtitle %] [% overdue.item.biblio.part_name %] [% overdue.item.biblio.part_number %] [% overdue.item.enumchron %] [% overdue.item.biblio.author %]<br />
Viivakoodi: [% checkout.item.barcode %]<br />
Eräpäivä: [% overdue.date_due | $KohaDates with_hours => 0 %], uusittu [% overdue.renewals_count %]/5 kertaa</p>

[% END %]
<p>Yhteensä myöhässä: [% overdues.count %]</p>
<p>Maksut:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Tervetuloa uudelleen! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />
```

Englanniksi:
```
[% USE Price %]

<style type="text/css">
  h1 { font-family: calibri; font-size: 18pt; }
  h2 { font-family: calibri; font-size: 10pt; }
  p { font-family: calibri; font-size: 10pt; }
</style>

<h2>Lastu-libraries<br />
https://lastu.finna.fi</h2>
<p><<today>></p>

[% sortedcheckouts = [] %]
[% FOREACH checkout IN checkouts %]
[% sortedcheckouts.push(checkout)  %]
[% END %]

<br />
<h2>Checkouts</h2>

[% FOREACH checkout IN sortedcheckouts.sort('date_due') %]<p>
[% checkout.item.biblio.title %] [% checkout.item.biblio.subtitle %] [% checkout.item.biblio.part_name %] [% checkout.item.biblio.part_number %] [% checkout.item.enumchron %] [% checkout.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% checkout.date_due | $KohaDates with_hours => 0 %], renewed [% checkout.renewals_count %]/5 times</p> 
[% END %]

<p>Items: [% checkouts.count %]</p>

[% sortedoverdues = [] %]
[% FOREACH overdue IN overdues %]
[% sortedoverdues.push(overdue)  %]
[% END %]

<h2>Overdue checkouts</h2>

[% FOREACH overdue IN sortedoverdues.sort('date_due') %]<p>
[% overdue.item.biblio.title %] [% overdue.item.biblio.subtitle %] [% overdue.item.biblio.part_name %] [% overdue.item.biblio.part_number %] [% overdue.item.enumchron %] [% overdue.item.biblio.author %]<br />
Barcode: [% checkout.item.barcode %]<br />
Due date: [% overdue.date_due | $KohaDates with_hours => 0 %], renewed [% overdue.renewals_count %]/5 times</p>

[% END %]
<p>Number of items overdue: [% overdues.count %]</p>
<p>Fines:
[% SET balance = borrower.account.balance %]
[% balance | $Price %] €
</p>
<br />
<p>Welcome back! </p>
<br />
<p><<branches.branchname>><br />
<<branches.branchphone>><br />
<<branches.branchreplyto>></p>

<br />
```

**Comment by pknuuti** [comment]
Voiko tämän tiketin jo sulkea?

**Comment by lmstrand** [comment]
Suljen tämän.
