### ISSUE TITLE
Helle: automaatilla lainattujen lainojen kirjaston vaihtaminen

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#219]
### Tukipyyntö

Saako vaihdettua automaatilla lainattujen lainojen kirjaston mm. tilastoja varten? Muutosta tarvitaan, sillä automaattitunnuksella on ollut väärä kirjastotieto.

Automaattiin liittyvä virheellinen kirjastotunnus koskee automaatilla lainattuja lainoja ajalla 25.8.-18.10.2022 (tai 25.8.-17.10.2022). Automaatille on vaihdettu oikea kirjastotieto tänään 18.10.2022.

Kyseessä on automaattitunnus
https://helle.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=129235

Automaatilla lainatut lainat kuuluvat Mustion lähikirjastolle, jonka kirjastotunnus on RASSV

### Kohan osio

Lainaus

**Comment by emta001** [comment]
Kyllä tämän käytännössä pitäisi onnistua. Sellaista kuitenkin varmistaisin, että lokien (tarkistin sekä action_logsit että sip-lokit) mukaan automaatilla ei ole tehty lainoja eikä uusintoja ennen 15.9. vaikka tunnus onkin luotu jo 25.8. Onko automaatti otettu käyttöön vasta 15.9.? Ihan vaan sillä, että meillä ei ole jostain syystä tässä tilannetta jossa osa lainoista on hävinnyt jonnekin bittiavaruuteen :D

**Comment by emta001** [comment]
Lainojen ja uusintojen kirjastotieto muutettu seuraavan loitsun avulla:

`SELECT CONCAT('UPDATE statistics SET branch = "RASSV" WHERE borrowernumber = ',object,' AND itemnumber = ',info,' AND datetime = "',timestamp,'";') FROM action_logs WHERE user = 129235 AND module = "CIRCULATION" AND timestamp BETWEEN "2022-08-25" AND "2022-10-19";`

Muutos koski noin 300 tapahtumaa. Ajetaan Hellen tilastot uusiksi sitten kun categorycode-muutos on saatu ajettua, tämäkin muutos näkyy siellä sitten.

**Comment by Kati-Helle** [comment]
Hienoa että muutos onnistui! 
Kiitos Emmi :)
