### ISSUE TITLE
[Kehitysehdotus] Hankintaehdotuksiin liittyvien tarpeettomien toimintojen piilotus

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#220]
### Kehitysehdotukseni

Saisiko tarpeettomia hankintaehdotuksiin liittyviä toimintoja piilotettua?

Etusivulla 
-Hyväksymistä odottavat hankintaehdotukset
![kuva](https://user-images.githubusercontent.com/99952449/196602824-7c26c472-5353-4815-88d7-249e0fdaad5f.png)

Hankinta-osiossa
- Hankintaehdotukset
- Odottavat ehdotukset
![kuva](https://user-images.githubusercontent.com/99952449/196604082-ff25c209-d4c6-4d05-a4de-956d0bba8e09.png)

### Kohan osio

Hankinta

**Comment by emta001** [comment]
Hmm, voisikohan näihinkin liittyä suggestions_manage-oikan piilotus (tiketti [217](https://github.com/KohaSuomi/Koha/issues/217)). Silloin ainakin peruskäyttäjiltä nämä menisivät piiloon (superlibrarianeilla ne edelleen näkyisivät). Pitää tutkia, toivottavasti nuo saisi vähintään CSS:llä piiloon.

**Comment by Kati-Helle** [comment]
Tosiaan Emmi! Testasin tämän nyt: hankintaehdotuksiin liittyvät toiminnot näkyvät Hellessä ainoastaansuperlibrarian-tunnuksilla. 

Olet Emmi poistanut helleläisiltä oikeuden suggestions-manage.
https://tiketti.koha-suomi.fi/issues/5621

**Comment by janPasi** [comment]
Voidaanko tämä tiketti sulkea?

**Comment by emta001** [comment]
> Voidaanko tämä tiketti sulkea?

Onko vielä tarvetta piilottaa nuo Katin mainitsemat linkit yms. vaikka ne näkyykin vain superlibrarian käyttäjille? Jos on, niin silloin tää on vielä työn alla. Muuten voi sulkea.

**Comment by Kati-Helle** [comment]
> > Voidaanko tämä tiketti sulkea?
> 
> Onko vielä tarvetta piilottaa nuo Katin mainitsemat linkit yms. vaikka ne näkyykin vain superlibrarian käyttäjille? Jos on, niin silloin tää on vielä työn alla. Muuten voi sulkea.

Ainakaan Hellen osalta piilotukselle ei ole enää tarvetta.
