### ISSUE TITLE
[Kehitysehdotus] Luettelointioikeuksiin erillinen tietueiden poisto-oikeus

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#221]
### Kehitysehdotukseni

Käytössä olevassamme Koha-versiossa 21.11 ei ole enää luettelointioikeuksissa erillistä tietueiden poisto-oikeutta (delete_catalogue). Oikeus olisi erittäin tarpeellinen kirjaston kokoelmatyötä tekeville. Nykyisessä versiossa tietueiden poisto-oikeus on sisällytetty luettelointioikeuksiin eli käytännössä lähes koko henkilökunnalle joudumme antamaan luettelointioikeudet, jotta he pystyvät poistamaan tietueita kokoelmatyössään.

### Kohan osio

Kuvailu

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 15.1.2024: Jos käytetään niteiden eräpoistoa, niin tietue poistetaan, kun viimeinen nide poistetaan (olettaen, että valittuna on, että tietue poistetaan). Tähän ei tarvita kuvailuoikeutta.

Olemme menossa kohti yhteistä kuvailutietovarantoa, joten tätä toiminnallisuutta ei kannata tässä vaiheessa toteuttaa. Poistokuviot pitää miettiä uusiksi, kun yhteinen kuvailutietovaranto otetaan käyttöön.
