### ISSUE TITLE
[Kehitysehdotus] Siirtotoiminto ja varattu nide

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#222]
### Kehitysehdotukseni

Kuljetukset ja siirrot: https://vaara.koha-suomi.fi/cgi-bin/koha/circ/branchtransfers.pl

Olen laittamassa siirtotoiminnon kautta kelluvaa nidettä kuljetettavaksi toiseen kirjastoon eli kotikirjastoonsa. Tietueessa sattuu olemaan varaus, jolloin siirtotoiminto antaa kolme toimintavaihtoehtoa (ks. kuva):

1. Aseta nide kuljetettavaksi ja kuljeta nide Reijolan kirjasto (= kirjasto, joka on varauksen noutopaikka)
2. Peruuta varaus ja yritä sitten kuljetusta
3. Älä huomioi, palaa kuljetuksiin

Ensimmäisen vaihtoehdon valitsemalla siirtonäytöllä lukee "Nide on kuljetettavana toimipisteeseen Joensuun pääkirjasto" (Reijolan sijasta), ei mahdollista tulostaa varauskuittia, vaikka kyseessä on varauksen kuljettaminen. Perustiedot-näytöllä nide on kuljetettavana kotikirjastoonsa (Joensuu) ja varausnäytöllä (https://vaara-test.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?) varauksen noutopaikkaan eli Reijolaan. Jos niteen palauttaa uudelleen, tulee normaali varauksesta kertova poppari.

Toisen vaihtoehdon valitsemalla asiakkaalla oleva varaus poistetaan kokonaan ja siirtoa voi yrittää uudelleen. 

Kolmas vaihtoehto ohittaa varauksen ja laittaa niteen kuljetettavaksi kotikirjastoon, ei siis pelkästään "palaa kuljetuksiin". 

(Oikeassa tilanteessa olisin tarvinnut juuri viimeistä vaihtoehtoa, koska varaus kohdistui tietueeseen, josta oli jo yksi nide paikalla varauksen noutokirjastossa. En kuitenkaan uskaltanut käyttää mitään näistä vaihtoehdoista ennen testillä testaamista, koska kuvaukset ovat jotenkin hämmentäviä. Keskimmäinen vaihtoehto on sanamuodoltaan loogisin, mutta jäin siltikin epäröimään, tarkoittaako varauksen peruminen tässä tilanteessa sen ohittamista vai todellako tätä kautta voi poistaa koko varauksen yhdellä klikkauksella.) 

Voisiko rikkinäisen tuplalinkin poistaa (ks. kuva)? Ja voisiko näitä kolmen vaihtoehdon tekstejä hiukan selkiyttää (ovat englanniksikin kyllä suht samaa tarkoittavat)? Toimiiko kohta 1 oikein, tarvitseeko fiksausta? 

### Jotain muuta?

Kuvankaappaus testiltä:
![siirto2](https://user-images.githubusercontent.com/99409279/196970992-5bd08704-95ba-482d-8675-5acfe1329577.png)

**Comment by AnneliO** [comment]
1. kohta
Mulla nide menee kuljetukseen siihen kirjastoon, mihin sitä ollaan siirtämässä, mutta varaus menee kuljetettavaksi noutokirjastoon. Englanniksi kohdassa sanotaan "Set reserve to transit and transfer book to Oulun kaupungin pääkirjasto:" (jossa oupk on varauksen noutokirjasto). Eli varaus laitetaan ilmoituksen mukaisesti kuljetettavaksi noutokirjastoon, mutta nide laitetaankin Siirto-toiminnossa valittuun kirjastoon. Tämä ei toimi minusta oikein. Nidekin pitäisi laittaa kuljetettavaksi varauksen kohdekirjastoon.

2. kohta
"Cancel reservation and then attempt transfer:" Varaus poistetaan, kuten kerrotaan tehtävän, mutta nide ei mene kuljetettavaksi. Näkymä palaa siirto-sivulle ja yläreunassa lukee "Reserve cancelled", joten todennäköisesti tarkoituksena on siirtää nide uudelleen. Voin muuttaa käännöksen muotoon "Poista varaus ja tee sitten siirto uudelleen", jos se tuntuu selkeämmältä.

3. kohta
"Ignore and return to transfers: " Mulla tapahtuu, kuten väitetään. Nide ei mene kuljetettavaksi mihinkään ja näkymä palaa Siirto-sivulle. Siinä kyllä näkyy aiemmat siirrot, jos niitä on tehnyt ennen viimeisimmän käsittelyä.

En tiedä, mistä tuo ylimääräinen a href-juttu tulee, käännöksissä sitä ei näy. Ehkä jotain on rikki sivun templatessa.

**Comment by emta001** [comment]
> En tiedä, mistä tuo ylimääräinen a href-juttu tulee, käännöksissä sitä ei näy. Ehkä jotain on rikki sivun templatessa.

Tulee siis meille (ja yhteisöön) tehdystä korjauksesta, tiketti [5343](https://tiketti.koha-suomi.fi/issues/5343) ja yhteisön tiketti [29768](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29768). Sillä siis korjattiin ongelma, jossa kirjastokortiton huoltaja ei näkynyt muokkaussivulla. Ongelmana vaan on se, että paikoitellen hyperlinkit menivät höpsis myös muiltakin sivuilta ja tämä on näköjään yksi niistä. Pitää korjailla hieman tarkemmin tämä, mutta kerennee mukaan vasta ensi viikon päivitykseen.

**Comment by emta001** [comment]
Rikkinäisen linkin korjaus viety testeille.

**Comment by AnneliO** [comment]
Irina, teetkö tuosta ensimmäisestä kohdasta erillisen tiketin? Muut kohdat minusta nyt ok. :)

**Comment by IrinaHalminen** [comment]
Laitettu uusi tiketti (#247).

**Comment by janPasi** [comment]
Suljen tämän tiketin.
