### ISSUE TITLE
[Tukipyyntö] Vaski: Finvoice-lasku ei lähde järjestelmästä

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#224]
### Tukipyyntö

Laskuviesti, jonka message_id on 2842747, ei jostain syystä lähde järjestelmästä eteenpäin. Viesti oli jäänyt failed-tilaan ja yritimme lähettää viestin uudelleen. Viesti jäi toisellakin yrittämällä failed-tilaan. Päällisin puolin viesti näyttää normaalilta. 

### Kohan osio

Laskutus

**Comment by emta001** [comment]
Tarkistin lokit, kys. viestin validointi on epäonnistunut:

`2842747 failed with unknown-555812541fb0:0: Schemas validity error : Element 'ArticleName': [facet 'maxLength'] The value has a length of '103'; this exceeds the allowed maximum length of '100'.`

Viittaa siis siihen, että tietueen tekijän - tietueen titlen yhdistelmä on liian pitkä. Vilkaisin viestin sisällön, tämä lienee se ongelma kenttä:
_Rönström, Jon - Stalinin makaronit ja 30 muuta historiallista huikopalaa, herkkua ja viimeistä ateriaa_

Pitänee kokeilla kasvattaa tuon kentän pituutta hieman.

**Comment by emta001** [comment]
Tehdäänkin niin, että pätkäistään tuosta yhdistelmästä ylimääräiset merkit pois. Pidempi rimpsu ei välttämättä mahdu viestipohjalle.

**Comment by emta001** [comment]
Tähän on nyt testillä korjaus, kerkeättekö Vaskissa testaamaan?

**Comment by MikkoLiimatainen** [comment]
Hienoa. Saako tuon epäonnistuneen viestin muokattua ja lähetettyä uudelleen?

**Comment by emta001** [comment]
> Hienoa. Saako tuon epäonnistuneen viestin muokattua ja lähetettyä uudelleen?

Voi sitä ainakin yrittää.

**Comment by emta001** [comment]
Viesti näyttäsi lähteneen onnistuneesti eteenpäin.

**Comment by MikkoLiimatainen** [comment]
Ok. Tämä lienee sitten selvä homma. Kiitos.

**Comment by MikkoLiimatainen** [comment]
Avaan tämän uudelleen, sillä nyt näyttää siltä, ettei laskujäljennökseen tulostu teoksen nimi, vaikka PDF-laskupohjaa ei ole muutettu. Eli tarvitseeko nyt pohjan <<biblio.title>> korvata jollain muulla tiedolla, vai miksi työkalu ei näytä osaavan hakea tuota enää?

**Comment by MikkoLiimatainen** [comment]
Itse asiassa tuo teoksen nimi ei enää näytä tulevan Finvoicellekaan.

**Comment by MikkoLiimatainen** [comment]
Jostain syystä näyttäisi siltä, että teoksen nimi ei tule laskulle, jos se ei ole vähintään 100 merkkiä pitkä ja joudu katkaisuun. En tuota huomannut aiemmasta testistäni, kun katsoin vain tuota katkaisun toimintaa, mutta ongelma oli jo siinä. Testissä siis laskutettavana oli kaksi teosta, joista toinen meni katkaisun läpi ja tiedot tulivat oikein laskulle, mutta toista ei tarvinnut katkaista ja siitä tuli laskulle vain tekijän nimi, ei teoksen nimeä.

**Comment by emta001** [comment]
Omituista, muutos näyttäisi purreen tosiaan vain pitkiin teoksen nimiin, lyhyet jäävät tulostumatta. Nappaan tuon muutoksen pois ja katson sitä uudestaan.

**Comment by emta001** [comment]
Nyt pitäisi toimia.

**Comment by emta001** [comment]
Nonnih, nyt on korjaus tehty sekä testille että tuotantoon. Siellä oli ylimääräinen muuttuja my $title, joka alusti teoksen nimen tyhjäksi ellei sitä käytetty katkaisun läpi.  Jouduin käynnistämään palvelut uusiksi jälleen, mutta nyt pitäisi toimia kuten pitää.

**Comment by MikkoLiimatainen** [comment]
Hienoa. Nyt näyttää toimivan. Kiitos nopeasta korjauksesta.
