### ISSUE TITLE
[Kehitysehdotus] Useamman tilatiedon välittäminen Kohasta Finnaan

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#225]
### Kehitysehdotukseni

Finnaan siirtyy Kohasta vain yksi nidetila status_array-arrayhin ja sama tieto menee availibility => statukseen, ja tämä tila näkyy verkkokirjastossa. Näyttää siltä, että esimerkiksi Damaged-tilan tieto priorisoidaan ennen Kuljetettavana-tilaa, mikä on tällä hetkellä ongelmallista koska pikalainojen ei-varattavuus on nykyisessä Kohan versiossa jouduttu toteuttamaan Damaged-tilalla (esim. Vaskissa tehty tila "Saatavissa, ei varattavissa"). Tästä johtuen pikalaina-nide saattaa olla kuljetuksessa takaisin kotikirjastoonsa, mutta näkyy silti verkkokirjastossa Damaged-tilan takia "Saatavana, ei varattavissa" -tilaisena.

Samankaltainen ongelma näkyy lainojen uusimisessa, jossa Finna kertoo vain yhden syyn uusimisen estolle. Esimerkiksi uusintakertojen ollessa täynnä asiakas näkee ainoastaan sen tiedon, ei tietoa siitä jos niteen uusinta on estynyt myös nimekkeeseen kohdistuneen varauksen takia.

Pikalainoja koskevaan ongelmaan on tehty kehitysehdotus (https://github.com/KohaSuomi/Koha/issues/226), mutta se ei välttämättä silti poista tämän ehdotuksen tarvetta. Finnan saatavuus-/tilatietojen esittäminen vaatinee muutoksia myös Kansalliskirjaston päässä, joten tämä ei ole puhtaasti pelkkä Koha-kehitysehdotus.

### Kohan osio

Verkkokirjasto

**Comment by janPasi** [comment]
Ongelma tässä on ehkä hieman se, ettei kuljetettavana olo ole Kohassa varsinaisesti "niteen tila" ollenkaan. Kuljetuksessa olo ilmaistaan Kohassa ainoastaan sillä, että niteestä on avoin merkintä Kohan branchtransfers taulussa + varauksen ollessa kyseessä _varauksen_ tilaksi varaustauluun merkitään T (In transit, tai whatnot).

**Comment by lmstrand** [comment]
Koha kyllä raportoi Finnaan useamman unavailability-statuksen unavailabilities-tiedoissa (tein niteeseen siirron toiseen kirjastoon siirto-toiminnolla ja laitoin päälle jonkin ei lainattavissa-statuksen):

            "availability": {
                "available": false,
                "unavailabilities": {
                    "Item::NotForLoan": {
                        "code": "Ei saatavilla",
                        "status": -5
                    },
                    "Item::Transfer": {
                        "datesent": "2022-11-07T15:32:42+02:00",
                        "from_library": "SII_PK",
                        "to_library": "SII_VU"
                    }
                }

**Comment by janPasi** [comment]
Tässä pitäisi siis vain saada Finna reagoimaan oikein noihin rajapinnasta tuleviin unavailabilities-tietoihin. Nähdäkseni ei vaadi muutoksia Kohaan.
