### ISSUE TITLE
[Kehitysehdotus] Hyllyvarausraportilta pois nidetyypit, joiden varattavuus on estetty laina- ja maksusäännöissä 

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#226]
### Kehitysehdotukseni

Laina- ja maksusäännöissä on mahdollista luoda Oletusvaraussääntö nidetyypeittäin. Varaussäännöllä olisi mahdollista estää tiettyjen nidetyyppien kiinnijääminen varauksiin palautuksessa (esim. pikalainat). Ongelmana sääntöön liittyen on kuitenkin hyllyvarausraportti, jolle nidetyypin niteet tulevat näkyviin vaikka varaussääntö olisikin käytössä.

Pikalainojen kiinnijääminen varauksiin on siksi tällä hetkellä estetty kimpoissa käyttämällä Damaged-tilaa. Damaged-tila aiheuttaa kuitenkin ongelmia saatavuustietojen esittämisessä Finnassa (https://github.com/KohaSuomi/Koha/issues/225) ja varaussääntö olisi ehkä muutenkin oikeampi tapa estää varausten kiinni jääminen järjestelmässä.

### Kohan osio

Varaukset

**Comment by AnneliO** [comment]
Haa, hyvä keksintö! Tätä tapaa ei olekaan voinut käyttää ennen nidetyyppikonversiota, koska harvemmin varauskielto koski esim. kaikkia kirjoja. Mutta nyt kun nidetyypit ei perustu aineistolajiin, niin tätä voi hyödyntää hienosti!

Hyllyvarausraportti on Koha-Suomen koodia, joten sen puolesta muutoksen voisi raporttiin tehdä. 

Testasin tätä tapaa estää varauksen teko Bywaterin sandboxissa ja siellä pendingreserves-raportti osaa ottaa huomioon oletusvaraussäännön. Se toiminto/sääntö/ehto on todennäköisesti vain riisuttu pois meidän versiosta.

**Comment by janPasi** [comment]
Tapa olisi parempi, mutta niteiden filtteröinti hyllyvarausraportilta saattaa olla haastavaa. Hyllyvarausraportin tässä suhteessa oikein toimivasta yhteisöversiostakaan ei ole tässä iloa, koska se on tekniseltä toteutukseltaan täysin meidän versiosta poikkeava. 

Tuota yhteisön versiota taas ei meidän varausmäärillä nähdäkseni saa toimimaan järkevästi, koska esitettävän datan filtteröinti tehdään siinä vasta selainpäässä. Tällaiseen toimintatapaan noudettavia varauksia teos- ja nidetietoineen on meidän kimpoissa yksinkertaisesti liikaa ja raportin suorituskyky romahtaa. Tämä siis vaikka kokeilin versiopäivitystä tehdessä siirtää varsinaiset kyselyt tausta-ajoon, kuten se on tehty meidän tämänhetkisessäkin raportissa. Loppujen lopuksi jouduin versiopäivityksessä nöyrtymään ja porttaamaan meidän oman hyllyvarausraportin (joskin huomattavasti siistittynä) uuteen Koha-versioon.

Täytyy tutkia jossain sopivassa kohtaa saisiko raportilta filtteröityä laina- ja maksusääntöjen mukasesti "varauskelvottomat" niteet pois siellä tausta-ajon puolella. Aikataulua tälle en uskalla ihan tähän hätään antaa.

**Comment by janPasi** [comment]
No tämä taisikin olla suht helppo korjaus. Testeillä on nyt muutos tähän versiohallinnan päällä (ei kommitoitu vielä). Tekaisen maanantaina commitin niin voidaan testailla. Hyvässä lykyssä saadaan mukaan ensi tiistain päivitykseen.

**Comment by ajrajala** [comment]
Kiitokset tutkimisesta, tämähän alkoi edetä ripeästi! Kiva jos saadaan ainakin testaukseen jo heti ensi viikolla.

**Comment by janPasi** [comment]
Voidaan tosiaan testata nyt testeillä. Listan automaattinen päivitys testeillä ei ole käytössä. Se on raskas prosessi, joka käyttää melkoisesti järjestelmän resursseja ja testeillä listan jatkuva päivittely on hieman turhaa. Pyytäkää tarvittaessa kehittäjää ajamaan hyllyvarauslistan päivitys testatessanne.

**Comment by janPasi** [comment]
Ongelma johtuu siitä että jollekkin jonossa keikkuvalle niteelle ei löytynyt laina- ja maksusääntöä, tuo on nyt korjattu ja lista päivietty.

**Comment by ajrajala** [comment]
Raportille pitäisi tulla "säännöttömät" niteet. En tiedä selkiyttääkö yhtään, mutta esim. Vaskin testissä on nyt yksi ainoa oletusvaraussääntö (default hold policy by item type) joka kohdistuu nidetyyppiin JOKERI ja säännössä hold policyyn määritelty, että "no holds allowed". Eli muuta ei pitäisi karsiutua raportilta pois kuin tuohon varaussääntöön tarttuvat niteet.

**Comment by janPasi** [comment]
Muutin raporttia ja nyt pitäisi näkyä myös "säännöttömien".

**Comment by ajrajala** [comment]
Vielä varmistaisin, pitäisikö raportilta karsiutua pois myös niteet jotka on varsinaisessa laina- ja maksusääntötaulukossa määritelty "Holds allowed (total)"-sarakkeessa nollaan? Vai pelkästään niteet, jotka mätsäävät default hold policy by item type -sääntöön?

Olen siis lisännyt hold policy by item type -kohtaan säännön JOKERI-nidetyypille ja ne näyttävät karsiutuneen raportilta pois kuten halutaankin. Sen sijaan raportilla näkyy EILAINATA-nidetyypin niteitä. Sille ei ole lisätty default hold policya mutta laina- ja maksusääntötaulukossa Holds allowed (total) on kyllä nolla. Tosin taulukossa näkyy olevan myös sarake Holds allowed (daily) ja siinä on Unlimited - sekin voi ehkä mahdollisesti aiheuttaa nyt ongelman tuon EILAINATA-nidetyypin kanssa?

Työpäivä loppuu uhkaavasti, mutta voin kyllä esimerkiksi huomenna tehdä muutoksia tuonne laina- ja maksusääntösivulle ja pyytää sitten ajamaan raportin uudestaan?

**Comment by janPasi** [comment]
Nykyisellään ainoastaan tarkistetaan, ettei nidettä vastaavaa sääntöä joko ole olemassa tai jos on, tarkistetaan ettei 'holdallowed' säännön ole arvo 'not_allowed'. Noihin sallittujen varausten määriin ei varsinaisesti ole mitään erillistä käsittelyä.

**Comment by ajrajala** [comment]
Okei, tämä taisi selventää, kiitos. :) Päivitin hold policyt vielä Vaskin testiin, joten jos raportin kertaalleen voisi ajaa meille uudestaan, voin vielä tarkistaa että hyllyvarauslistalta poistuu kaikki sellaiset varaukset joiden pitääkin.

Alla vielä kuvakaappaus säännöistä, jotka pitää määritellä, jos/kun muissakin kimpoissa tulee olemaan tarvetta näille:

![kuva](https://user-images.githubusercontent.com/44638512/199264403-ba10e08a-cf98-4323-b798-7447293f5766.png)

**Comment by janPasi** [comment]
Päivitetty nyt.

**Comment by ajrajala** [comment]
Kiitokset! Tarkistin hyllyvarausrapsan ja listalta poistui varaukset nimekkeisiin joiden saatavilla olevat kappaleet mätsäsivät jonkin default holds policy -nidetyypin kanssa. Jos nidetyypille ei oltu määritelty default holds policya, näkyi se edelleen hyllyvarausraportilla.

**Sellainen poikkeus tuli kuitenkin esille, että jos varaaja oli asiakastyyppiä "Ei-tilastoitavat lainat", tuli varaus hyllyvarausraportille vaikka saatavilla olevan niteen nidetyypille olisikin lisätty default holds policy -sääntö.**
![kuva](https://user-images.githubusercontent.com/44638512/199475604-76894159-6e90-40d5-a428-8706fc9dfa9a.png)
Arvailua, mutta johtuisiko sitten siitä, että Vaskin laina- ja maksusääntötaulukossa tuolle nidetyypille+asiakaslajille on sarakkeeseen _On shelf holds allowed_ määritelty _Yes_ kun muilla asiakaslajeilla se on taulukossa _If all unavailable_... Nide ei palautuksessa kuitenkaan tärppää varaukseen eli tuo default holds policy siinä mielessä kuitenkin yliajaa laina- ja maksusääntötaulukon sääntörivin.

Tämä ei minusta varsinaisesti ole ongelma, mutta pitää tiedostaa kun laina- ja maksusääntöjä laatii (eli ei kannata tehdä default holds policyn kanssa ristiriidassa olevia sääntöjä).

Muuta testattavaa en keksi, minusta hyllyvarausraportin muutos toimii kuten pitää.

**Comment by piiaseme** [comment]
Voisiko OUTIn testiltä ajaa hyllyvarausraportin? Tein sinne muutaman testivarauksen, niin näkisi miten säännöt meillä toimii.

**Comment by pknuuti** [comment]
Vaaran testillä ei tullut pikalainaa hyllyvarauslistalle eli näyttäis toimivan ainakin siltä osin.

**Comment by piiaseme** [comment]
Testasin monella eri tavalla ja hyllyvarauslista näytti OUTIn testillä toimivan kuten pitää.

**Comment by AnneliO** [comment]
Muutos viety tuotantoon.

**Comment by ajrajala** [comment]
Onko joku ehtinyt testata tätä tuotannossa? Tein Vaskin tuotantoon aamupäivällä oletusvaraussäännön nidetyypille JOKERI ja varauksen teokseen, jonka ainoa saatavilla olevalla kappaleella on tämä nidetyyppi. Toisin kuin testissä, tuotannossa varaus näyttää tulevan hyllyvarausraportille.

**Comment by janPasi** [comment]
Jännittävää, koska koodi on kyllä ihan identtinen kummassakin...

**Comment by ajrajala** [comment]
ANTEEKSI, mullahan on virhe tuotantoon tekemässäni oletusvaraussäännössä. Tämän täytyy olla siis aivan väärä hälytys.
