### ISSUE TITLE
[Kehitysehdotus] Palautusten määrä näkyviin sähköpostikuittiin

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#227]
### Kehitysehdotukseni

Asiakas haluaisi myös lukumäärän palautuksistaan palautuskuittiin/sähköpostiviestiin, jotta olisi helpompi tarkistaa kaikkien palautusten onnistuminen, kun palauttaa suuren lukumäärän aineistoa. En löytänyt tuohon sopivaa toimintoa, olisikohan se mahdollista saada?

### Kohan osio

Palautus

**Comment by lmstrand** [comment]
<<old_issues.count>> saattaisi toimia kuittipohjassa (yhteisön kuittipohjaohjeesta mukailtu). En saanut Vaara-testillä testattua kun en löytänyt oikeaa palautuskuittipohjaa millä testata.

**Comment by IrinaHalminen** [comment]
Testailujen jälkeen todettu, että [% old_checkouts.count %] toimii. Se on nyt lisätty palautuskuitille (CHECKINSLIP). Sähköpostipohjan tuunailu jatkuu huomenna, koska nyt on yö. :D

**Comment by AnneliO** [comment]
Testasin OUTI-testillä seuraavalla viestipohjalla (Tuloste) ja määrä tulostui kuitille.

<style type="text/css">
  h1 { font-family: arial; font-size: 20pt; }
  h2 { font-family: arial; font-size: 18pt; }
  h3 { font-family: arial; font-size: 16pt; }
  h4 { font-family: arial; font-size: 14pt; }
  p { font-family: arial; font-size: 10pt; }
</style>

<h3>[% branch.branchname %]<br />
[% today | $KohaDates %]<br /></h3><br /><br />

<h3>Palautetut lainat</h3>

[% FOREACH checkin IN old_checkouts %] [% SET item = checkin.item %] <p> [% item.biblio.title %] [% item.enumchron %] [% item.biblio.author %] <br />
Nide: [% item.barcode %] <br />
</p>
<p>
Palautusten määrä: [% old_checkouts.count %]
</p>
[% END %]

<p>
<br /><<branches.branchfax>>
<br /><<branches.branchphone>>
<br />www.outikirjastot.fi</p>
<br />

**Comment by AnneliO** [comment]
Minusta tuntuu, että CHECKIN-pohja eli sähköpostikuitti ei tue noita [% old_checkouts.count %]-tyyppisiä määrityksiä. En ainakaan saanut niillä tulostumaan sähköpostiin mitään tietoja.

**Comment by AnneliO** [comment]
CHECKIN-pohjassa ei toimi myöskään <<old_issues.count>>-tägi.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 15.1.2024: Edistetään yhteisössä.

Tekisitkö Päivi tästä tiketin Bugzillaan.

**Comment by pknuuti** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35873

**Comment by lmstrand** [comment]
Yhteisön kommentin mukaan yhteenlaskua ei voi toteuttaa.
Pohjassa voisi käyttää numeroitua listaa <ol>:
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_lists_ordered2
