### ISSUE TITLE
Hyllyvarausraporttin kirjastotunnuksen korostus "On shelf" ja "Varaus" sarakkeisiin jos sama tunnus on molemmissa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#233]
### Kehitysehdotukseni

Saamani Hyllyvaraukset-toimintoon liittyvä ehdotus/toive:
Voisiko hyllyvarausten poimimisen helpottamiseksi Kohaan saada sellaisen ominaisuuden, että se korostaisi kirjastojen lyhenteet, jos varaus löytyy omasta kirjastosta? Tämä vähentäisi sitä, että toiset kirjastot poimivat varauksia kuljetukseen, vaikka kyseinen varaus löytyy omasta kirjastosta. 

### Kohan osio

Raportit ja tilastot

**Comment by lmstrand** [comment]
Jotkut virkailijat käyttävät selaimen etsi-toimintoa ja korostavat löytyneet osumat, jolloin molemmista sarakkeista löytyvät kirjastotunnukset huomaa helposti. Tämäntyyppistäkö toteutusta meinaat?
![image](https://user-images.githubusercontent.com/18394834/199008102-2d3c3d5a-8746-4aa1-bb9e-41b9f606797f.png)

**Comment by AnneliO** [comment]
Nykyisessä Koha-versiossa on ainakin asiakkaiden haussa sellainen ominaisuus, että se "korostaa" kirjautumiskirjaston aina listauksesta:

![kuva](https://user-images.githubusercontent.com/33121325/199009243-945fd1c2-94fb-4b58-bb61-a9af40c9165c.png)

Eli tuo vihreä korostus Oulun kaupungin pääkirjasto -sanassa. En tiedä, onko tästä tiedosta mitään hyötyä, mutta tuli mieleen.

**Comment by Kati-Helle** [comment]
Kyllä vain Lari, tuon tyylistä on toivottu. Korostetut kohdat on helpompi ohittaa/olla poimimatta, jolloin varattua teosta ei vahingossa poimittaisi muualla kuin teoksen noutokirjastossa.

On shelf -kirjastolistaukset saattavat olla kovin pitkiä ja jää huomaamatta, että hyllyvaratun teoksen nide olisikin sopivasti jo noutokirjastossaan paikalla.

**Comment by AnneliO** [comment]
> Kyllä vain Lari, tuon tyylistä on toivottu. Korostetut kohdat on helpompi ohittaa/olla poimimatta, jolloin varattua teosta ei vahingossa poimittaisi muualla kuin teoksen noutokirjastossa.
> 
> On shelf -kirjastolistaukset saattavat olla kovin pitkiä ja jää huomaamatta, että hyllyvaratun teoksen nide olisikin sopivasti jo noutokirjastossaan paikalla.

Hmm.. siis.. korostus näkyisi silloin, kun sitä on paikalla omassa kirjastossa. Eihän niitä silloin ole helpompi ohittaa? Eikä ole tarkoituskaan?

**Comment by Kati-Helle** [comment]
> > Kyllä vain Lari, tuon tyylistä on toivottu. Korostetut kohdat on helpompi ohittaa/olla poimimatta, jolloin varattua teosta ei vahingossa poimittaisi muualla kuin teoksen noutokirjastossa.
> > On shelf -kirjastolistaukset saattavat olla kovin pitkiä ja jää huomaamatta, että hyllyvaratun teoksen nide olisikin sopivasti jo noutokirjastossaan paikalla.
> 
> Hmm.. siis.. korostus näkyisi silloin, kun sitä on paikalla omassa kirjastossa. Eihän niitä silloin ole helpompi ohittaa? Eikä ole tarkoituskaan?

Ei pelkästään tuolloin... korostus näkyisi aina, kun On-shelf-sarakkeessa JA Varattu-sarakkeessa on sama kirjastotunnus. Näin erottuisivat myös poimimatta jätettävät hyllyvaraukset silloin, kun ei poimi hyllyvarauksia korostetun kirjastotunnuksen kirjastossa.

Korostuksen sijaan käytössä voisi olla myös kirjastotunnuksen lihavointi, värillinen fontti tms. toteutettavissa oleva tapa.

**Comment by AnneliO** [comment]
Minun täytyy myöntää, että en nyt oikein ymmärrä tarvetta (saa vääntää rautalankaa :D). Eikö riitä, että suodattaa raporttia sekä On shelf -sarakkeessa ja Varaus-sarakkeessa samalla kirjastolla?

![kuva](https://user-images.githubusercontent.com/33121325/200578483-3a82d381-dffc-4377-bf1b-3de1376de81a.png)

**Comment by IrinaHalminen** [comment]
Kati tarkoittaa varmaankin sitä, että jos jokin varattu kirja on jo noutokirjastossaan, sen näkisi helposti, eikä lähtisi hakemaan sitä turhaan omasta hyllystä (ei-noutokirjaston hyllystä). Nopeuttaisi hyllyrapsan silmäilyä.

**Comment by Kati-Helle** [comment]
> > Kati tarkoittaa varmaankin sitä, että jos jokin varattu kirja on jo noutokirjastossaan, sen näkisi helposti, eikä lähtisi hakemaan sitä turhaan omasta hyllystä (ei-noutokirjaston hyllystä). Nopeuttaisi hyllyrapsan silmäilyä.
> 
> Jos tosiaan tätä tarkoitetaan, niin sitten ehkä ymmärrän tarpeen. Tosin, esim. OUTIssa on sovittu, että jos nide on paikalla noutokirjaston kunnan kirjastoissa, niin silloinkaan muut ei sitä poimi. Eli toiminto jäisi tuon kannalta vähän vaillinaiseksi, mutta onhan se parempi kuin ei mitään. :)

**Comment by Kati-Helle** [comment]
> > > Kati tarkoittaa varmaankin sitä, että jos jokin varattu kirja on jo noutokirjastossaan, sen näkisi helposti, eikä lähtisi hakemaan sitä turhaan omasta hyllystä (ei-noutokirjaston hyllystä). Nopeuttaisi hyllyrapsan silmäilyä.
> > 
> > 
> > Jos tosiaan tätä tarkoitetaan, niin sitten ehkä ymmärrän tarpeen. Tosin, esim. OUTIssa on sovittu, että jos nide on paikalla noutokirjaston kunnan kirjastoissa, niin silloinkaan muut ei sitä poimi. Eli toiminto jäisi tuon kannalta vähän vaillinaiseksi, mutta onhan se parempi kuin ei mitään. :)

Voisiko tuon osalta tarvittaessa hyödyntää OKM-kirjastoryhmiä?

**Comment by lmstrand** [comment]
Kehitysehdotuksesta on testiympäristöissä toteutus. Toimii tällä hetkellä englanninkielisenä. Pistin hyllyvarauslistat päivittymään testiympäristöihin klo 7-17 välisenä aikana jos haluatte testailla. Päätettiin jättää tuo varaus-sarakkeen kirjastotunnus-arvon korostus pois, kun se ei sinänsä ole tarpeellinen. Irina Halminen vastasi korostusväristä :) minua ei saa pilkata huonosta värisilmästä.

**Comment by lmstrand** [comment]
![image](https://user-images.githubusercontent.com/18394834/207846003-53aeb123-510d-4274-9c4a-bff40bf3d200.png)

**Comment by Kati-Helle** [comment]
Mainiota! Nyt erottaa selkeästi ne varatut teokset, jotka ovat noutokirjastossaan paikalla.

**Comment by pirliis** [comment]
Näyttääpä OUTIssakin korostuvan halutulla tavalla.

**Comment by ajrajala** [comment]
Vaskin testilläkin käyty kurkkaamassa, että korostus toimii.

**Comment by janPasi** [comment]
Käytämmä tämän muutoksen vielä 16.1. asiantuntijaryhmässä. Ei liene mitään syytä miksei se menisi läpi sielläkin, mutta mennään nyt "protokollan" mukaisesti.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmän päätös 16.1.2023: hyväksytään ja viedään tuotantoon seuraavassa päivityksessä.

**Comment by Kati-Helle** [comment]
Toteutettu tiistain 17.1.2023 Koha-päivityksessä. Kiitos! 
Suljen tiketin.

**Comment by lmstrand** [comment]
Toteutukseen oli jäänyt bugi suodatukseen. Vanha versio palautettu tuotantoihin. Laitan tiketin vielä työn alle.

**Comment by lmstrand** [comment]
Korjattu hyllyvarauslista korostuksin on viety testeille. Voisiko joku vilaista vielä varmuuden vuoksi.

**Comment by Kati-Helle** [comment]
Korostuksia näkyvillä
![kuva](https://user-images.githubusercontent.com/99952449/213125809-c96179e0-0891-4da9-9ad5-5ecb7c53d3d5.png)

**Comment by Kati-Helle** [comment]
Mutta: esim. hyllypaikka-arvovalinnat eivät toimi
![kuva](https://user-images.githubusercontent.com/99952449/213126130-98c8960f-c1d2-412c-af63-5e6e0177c5da.png)

**Comment by Kati-Helle** [comment]
KIrjastovalinnat toimivat
![kuva](https://user-images.githubusercontent.com/99952449/213127415-974a9cfc-48c2-451e-adf5-c555df5f2033.png)

**Comment by Kati-Helle** [comment]
Hyllypaikatkin nyt valittavissa (samoin Nidetyypit, Materiaalit ...)
![kuva](https://user-images.githubusercontent.com/99952449/213131540-1bdbd3b7-1432-40cf-8676-ae6e6721d6eb.png)

**Comment by ajrajala** [comment]
Kävin myös testailemassa raporttia uudelleen, suodatukset näyttävät tosiaan nyt toimivan ja korostukset pelittää edelleen.

Julkaisuvuosi ei kuitenkaan näy Nimeke-sarakkeessa kaikkien varausten osalta. Jos tulkitsen oikein, niin tuotannon raportissa tieto poimitaan sekä 260c että 264c -kentistä ja testillä olevassa raportissa ainoastaan 260c-kentästä.

**Comment by AnneliO** [comment]
@ajrajala Tuo julkaisuvuoden puuttuminen voisi johtua siitä, että testeillä ei ehkä ole tehty rebuild_bibliotables-ajoa sen jälkeen, kun on tehty määritykset https://vaski-test.koha-suomi.fi/cgi-bin/koha/admin/koha2marclinks.pl -asetukseen. Tuossa ajossa viedään kuvailutietueista tietoja biblio-tauluihin. Aiemmin tuonne pystyi määrittämään vain yhden kentän ja se oli 260c-kenttä silloin.

**Comment by ajrajala** [comment]
Meille siis ehti tulla henkilökunnalta palautetta julkaisuvuoden puuttumisesta silloin viime viikolla, kun hyllyvarausraportin muutokset oli hetken aikaa tuotannossa. En ehtinyt itse todentaa asiaa, mutta luulisin että oli ihan paikkansapitävä huomio.

**Comment by Kati-Helle** [comment]
Hellessä teoksen tietueen julkaisuvuosi näkyy sekä 260c-kentästä että 264c-kentästä.
![kuva](https://user-images.githubusercontent.com/99952449/214220836-560a9e44-85ff-4f7f-8864-94916256a76d.png)
