### ISSUE TITLE
[Bugi] Ilmoituspohjan muutokset kopioituvat toiseen kirjastoon vaikka painaa "Peruuta"

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#237]
### Mikä vikana?

Redmine tiketissä [5459](https://tiketti.koha-suomi.fi/issues/5459) tehtiin muutos, jolla yhteen ilmoituspohjaan tehdyt muutokset voidaan kopioida myös sellaisiin kirjastoihin joissa pohja on jo olemassa. Kopioitavan ilmoituspohjan tallennuksessa laukaisee varmennus pop-upin, jossa ilmoitetaan että kyseisellä kirjastolla on jo sama ilmoituspohja ja muutoksen voi joko hyväksyä tai peruuttaa. Tällä hetkellä muutokset kuitenkin kopioituvat joka tapauksessa vaikka painaisi peruuta.   

### Kohan osio

Työkalut

**Comment by Kati-Helle** [comment]
Helle-testissäni ilmoituspohjaan ei kopioitunut kopioitavaa ilmoituspohjaa, kun peruutin kopioimisen Peruuta-painikkeilla.

Ilmoituspohjan kopioinnin jälkeen
Valitsin Tallenna, jonka jälkeen tämä popup:

![kuva](https://user-images.githubusercontent.com/99952449/199688943-18764b86-3068-4ab2-b340-60e2da571869.png)

Ennen tallennuksen peruutusta ilmoituspohjassa näkyi kopioitu muutos.
Popupista valitsin Peruuta
Ilmoituspohjassa näkyi kopioitu muutos edelleen.


Poistuin ilmoituspohjan kopioinnista valitsemalla Peruuta:

![kuva](https://user-images.githubusercontent.com/99952449/199690041-aff8e38a-d46e-44ea-97eb-f5e01f68944d.png)

Kopioinnin kohdekirjaston ilmoituspohja oli muuttumaton (eli kopioidun ilmoituspohjan tiedot eivät olleet kopioituneet).

**Comment by pknuuti** [comment]
Vaaran testillä toimii kuten Katri kuvannut Hellen toiminnon.
