### ISSUE TITLE
[Kehitysehdotus] Tietueen aineistotyyppi näkymään asiakkaan Lainassa-välilehden teostietoihin sekä Palautus-toimintoon

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#238]
### Kehitysehdotukseni

Saisiko tietueen aineistotyyppi-arvon (auktorisoitu arvo MTYPE) näkymään asiakkaan Lainassa-välilehden teostietoihin. Samoin Palautus-toimintoon

Teoksen tietueessa aineistotyyppi on kentässä 942c

Lainassa-välilehdellä Aineistotyyppi-sarake on, mutta tyhjä. 
Palautus-toiminnossa Aineistotyyppi-sarake on, mutta tyhjä.

![kuva](https://user-images.githubusercontent.com/99952449/199199093-2c207c7e-0c5e-4c9b-bba8-c3cee4ffcca1.png)

![kuva](https://user-images.githubusercontent.com/99952449/199200127-6d137959-570c-4ff9-a0b4-50e6612b427e.png)

### Kohan osio

Palautus

**Comment by lmstrand** [comment]
Muutokset viety testille testattavaksi. Omainaisuudet branchissa ksdev/ks-0074-KD-G238.

**Comment by Kati-Helle** [comment]
Kiva, kiitos! Helle-testissä asiakkaan Lainassa-välilehdellä tietueen aineistotyyppi näkyy nyt
![kuva](https://user-images.githubusercontent.com/99952449/199475940-e0e4b660-f08f-4842-b468-ea1b937429b4.png)

Palautus-toiminnossa ei näy ainakaan vielä
![kuva](https://user-images.githubusercontent.com/99952449/199476142-0f1285c5-2c46-44b8-b697-1835650f9fde.png)

**Comment by pknuuti** [comment]
Samanlainen havainto Vaaran testillä eli asiakkaan lainoissa näkyy aineistotyyppi, mutta ei palautuksessa.

**Comment by ReettaSiili** [comment]
Englanniksi näkyy Siilissä palautuksissakin record-level itemtype.

**Comment by Kati-Helle** [comment]
Hellen palautuksessa aineistotyyppi-arvo näkyy nyt suomen- ja englanninkielisessä Kohassa.
Ruotsinkielisessä ei näy.

![kuva](https://user-images.githubusercontent.com/99952449/199657622-e01381b1-c8a3-43b6-a631-ba3d507a17ff.png)

**Comment by pknuuti** [comment]
Vaarassakin toimii nyt myös palautuksessa aineistotyypin näkyminen.

**Comment by lmstrand** [comment]
Nyt pitäisi näkyä oikein kaikilla kielillä testeillä.

**Comment by Kati-Helle** [comment]
Kiitos Lari, nyt aineistotyyppi-arvo näkyy myös ruotsinkielisen Kohan Palautus-toiminnossa.

![Image](https://user-images.githubusercontent.com/99952449/199666746-15d37c2a-6649-455a-85a4-c968755204dc.png)


(Asiakkaan Lainassa-tiedoissa aineistotyyppi-arvo näkyy myös kaikilla kolmella kielellä.)

**Comment by AnneliO** [comment]
Saisiko tunnisteen sijaan näkymään arvon kuvauksen?

**Comment by lmstrand** [comment]
Aineiston MTYPE-autorisoidun arvon kuvaus (virkailijaliittymälle) näkyy nyt Aineistotyyppi-sarakkeessa testiympäristöissä. Harmi kun noille arvoille ei voi lisätä käännöksiä kun MTYPEa ei ole tarkoitettu sellaiseen käyttöön kuten nidetyypit, joille käännökset voisi halutessaan tehdä nidetyyppien muokkauksessa. Eiköhän tällä nyt pärjätä.

**Comment by AnneliO** [comment]
Muutos viety tuotantoon ja aineistotyyppi näkyvillä.
