### ISSUE TITLE
[Bugi] Vaski: Virhe 500 -ilmoitus palautuksessa, uudelleenindeksointi tarvitaan?

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#243]
### Mikä vikana?

Parista kirjastosta on tänään raportoitu, että tietueen https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=692706 niteitä palauttaessa tulee virhe 500 -ilmoitus vaikka niteiden pitäisi tärpätä varaukseen. Tätä ongelmaa on ilmeisesti ollut aiemminkin ja johtunut siitä, ettei indeksointi ole ajan tasalla?

### Kohan osio

Niteet

**Comment by emta001** [comment]
Tietueen varaukselta puuttuu noutokirjasto, sen valitseminen pitäisi korjata ongelma.

**Comment by emta001** [comment]
Lisähuomautuksena, näin pääsee käymään kun käytetään vanhetunutta versiota Finna_koha-bookmarkletista. Täällä korjattu versio https://tiketti.koha-suomi.fi/issues/5616

**Comment by AnneliO** [comment]
Noutokirjasto puuttuu asiakkaalta, jonka borrowernumber on 166047, varauksen tekopäivä 1.11.2022.

**Comment by ajrajala** [comment]
Kiitos, eipä tullut tuo mieleen ollenkaan, Varaukset-sivulla näennäisesti on noutopaikkana yksikkölistauksen eka kirjasto.
