### ISSUE TITLE
[Bugi] Helle: Palautus-toiminnossa ei saa vaihdettua Kohaan kirjautumiskirjastoa, sillä Aseta kirjasto -valintavaihtoehtoa ei ole

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#244]
### Mikä vikana?

Palautus-toiminnossa Kohaan-kirjautunut ei saa vaihdettua sijaintikirjastoaan, sillä Aseta kirjasto -valintaa ei ole.

![kuva](https://user-images.githubusercontent.com/99952449/199662861-1f268bd7-792a-42a6-87d8-15ecfaa77655.png)

### Kohan osio

Palautus

**Comment by AnneliO** [comment]
Mie oon ajatellut, että tuo on jonkinlainen turvaominaisuus, ettei vaihda vahingossa kesken palautuksen kirjastoa. :D 

Mutta ilmeisesti nyt on niin, että IntranetUserCSS:ssä oleva rivi piilottaa tuon.

body#circ_returns.circ ul li:nth-child(4) { display: none; }

Tuolla piilotetaan varausruudusta asiakkaan yhteystieto. Pitää miettiä, miten asian korjais.

**Comment by AnneliO** [comment]
Jos tuon yllä olevan rivin tilalle laittaa

body#circ_returns.circ a#boremail { display: none; }

niin sähköpostiosoite menee piiloon, mutta näkyville jää luettelopallero. Se kuitenkin ehkä on parempi vaihtoehto kuin että Aseta kirjasto -vaihtoehto häviää valikosta kokonaan?

![kuva](https://user-images.githubusercontent.com/33121325/199668068-3b0cf0dd-019f-4c25-83c7-9f40797a14af.png)

**Comment by Kati-Helle** [comment]
Kiitos Anneli! Luettelopallero näkyköön.

![kuva](https://user-images.githubusercontent.com/99952449/199673831-86a978fd-0337-44f3-a35e-2abe100757d7.png)
