### ISSUE TITLE
[Bugi] Hankinta: Myöhässä olevat -haku antaa virheilmoituksen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#246]
### Mikä vikana?

Kun lähtee hakemaan Hankinnat-välilehdeltä Myöhässä olevat-tilassa olevia tilauksia, Vaarassa tulee virheilmoitus:
Virhe!
Virhe 500
Tämä viesti johtuu jostain seuraavasta syystä:

    Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
    Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
    Yritit päästä sivulle, jonne pitää kirjautua.
    Linkki oli virheellinen ja sivua ei ole olemassa

### Mitä pitäisi tapahtua

Pitäisi saada listaus tilauksista, joista on kulunut paljon aikaa.

### Kohan osio

Hankinta

**Comment by emta001** [comment]
Sieltä tulee template-erhe:

_Template process failed: undef error - DBIC result _type  isn't of the _type Aqbudgetperiod at /home/koha/Koha/koha-tmpl/intranet-tmpl/prog/fi-FI/modules/acqui/lateorders.tt line 153._

Eli jonkin rivin jossakin sarakkeessa vaikuttaisi olevan virheellistä dataa.

**Comment by emta001** [comment]
Hmm, myös testillä tulee 500 virhe.

**Comment by Kati-Helle** [comment]
Saman virheilmoitus Hellessä Kohan suht pitkähköhän hakemisen jälkeen.

**Comment by emta001** [comment]
Tämä johtuu siis siitä, että taulussa aqbudgets on NULL arvoja sarakkeessa budget_period_id. Eli eli kannassa on ristiriita sen suhteen, että tuo sarake voi olla NULL, mutta homma kuitenkin kaatuu siihen. 

Tähän liittyy versionvaihdossa tullut muutos, joka näkyi tietokannan päivityksessä ilmoituksena:
`Upgrade to 20.06.00.055 [15:40:59]: Bug 18050 - Add FK constraint on aqbudgets.budget_period_id. There are <joku_määrä> funds in your database that are not linked to a valid budget. Setting invalid budget id (budget_period_id) to null. The table _bug_18050_aqbudgets was created with original data. Please check that table and place valid ids in aqbudget table as soon as possible.`
Silloin ei tiedetty, että kuinka tämä tulee vaikuttamaan. Näköjään tämä oli sitten se missä tuo palasi kummittelemaan. Pitää tehdä tästä jokin päätös kuinka korjataan, muistelisin että budjettien poistaminen ei ainakaan ole vaihtoehto.

**Comment by emta001** [comment]
Hieman tätä testailtiin, tilien liittäminen ns. valebudjettiin auttanee 500 virheeseen. Mutta ongelmana on sen jälkeen se, että vanhentuneita tilauksia voi olla kimpassa niin paljon että niiden lataaminen johtaa lopulta Proxy erroriin. Eli virheellisten budjettien korjaamisen lisäksi olisi optimoitava Kohan koodia.

**Comment by velimarj** [comment]
OUTIssa budjetti nimellä "OUTIn valebudjetti".

**Comment by emta001** [comment]
> OUTIssa budjetti nimellä "OUTIn valebudjetti".

Budjetti lisätty tileille.

**Comment by pknuuti** [comment]
Vaarassa budjetti nimeltä "Vaaran valebudjetti".

**Comment by emta001** [comment]
> Vaarassa budjetti nimeltä "Vaaran valebudjetti".

Muutos tehty.

**Comment by Kati-Helle** [comment]
Hellessä ei-aktiivinen budjetti: Hellen valebudjetti
Oliko merkitystä budejetin arvoilla Alkupvm JA Loppumispvm? Vai voiko olla mitä vain?

**Comment by emta001** [comment]
> Hellessä ei-aktiivinen budjetti: Hellen valebudjetti Oliko merkitystä budejetin arvoilla Alkupvm JA Loppumispvm? Vai voiko olla mitä vain?

Voivat olla mitä vaan.

**Comment by emta001** [comment]
Muutos tehty Helleen ja Lumpeeseen.

**Comment by PiaKusmin** [comment]
Lapin valebudjetti (Ei-aktiivinen) lisätty.

**Comment by emta001** [comment]
> Lapin valebudjetti (Ei-aktiivinen) lisätty.

Kappas, Lapissa ei ollutkaan näitä ongelmatilejä. Sori, en tajunnut tarkistaa oliko tälle kaikille tarvetta. Tuon budjetin voinee poistaa, ellei sitä halua pitää varmuuden varalla.

**Comment by tuokun** [comment]
Kyytin valebudjetti lisätty.

**Comment by emta001** [comment]
> Kyytin valebudjetti lisätty.

Kyytillekin tehty muutos.

**Comment by emta001** [comment]
Olikohan tässä muuten kaikki, koska muistelisin että Siilissä ja Vaskissa tätä ongelmaa ei ole.

**Comment by emta001** [comment]
Muistin osittain väärin, Siilille ei tarvitse tehdä mutta Vaskille tarvii.

**Comment by ajrajala** [comment]
Vaskillekin nyt lisätty valebudjetti (Vaski valebudjetti, budget_period_id=69).

**Comment by emta001** [comment]
> Vaskillekin nyt lisätty valebudjetti (Vaski valebudjetti, budget_period_id=69).

Muutos tehty. Nyt tämän pitäisi olla kaikilla ok. Suljen tiketin.
