### ISSUE TITLE
[Kehitysehdotus] Siirtotoiminto ja varattu nide (kuljetustila)

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#247]
### Kehitysehdotukseni

Kuljetukset ja siirrot: https://vaara.koha-suomi.fi/cgi-bin/koha/circ/branchtransfers.pl

Olen laittamassa siirtotoiminnon kautta kelluvaa nidettä kuljetettavaksi toiseen kirjastoon eli kotikirjastoonsa. Tietueessa sattuu olemaan varaus, jolloin siirtotoiminto antaa kolme toimintavaihtoehtoa:

Aseta varaus kuljetettavaksi ja kuljeta teos kirjastoon Reijolan kirjasto (= kirjasto, joka on varauksen noutopaikka)
Peruuta varaus ja tee siirto uudelleen
Älä huomioi, palaa kuljetuksiin

Ensimmäisen vaihtoehdon valitsemalla siirtonäytöllä lukee "Nide on kuljetettavana toimipisteeseen Joensuun pääkirjasto" (Reijolan sijasta), ei mahdollista tulostaa varauskuittia, vaikka kyseessä on varauksen kuljettaminen. Perustiedot-näytöllä nide on kuljetettavana kotikirjastoonsa (Joensuu) ja varausnäytöllä (https://vaara-test.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?) varauksen noutopaikkaan eli Reijolaan. Jos niteen palauttaa uudelleen, tulee normaali varauksesta kertova poppari.

-> Voisiko olla mahdollista tulostaa niteeseen varauskuitti/vahvistaa varaus heti kohdan 1 vaihtoehdon valitsemisen jälkeen? Tällöin ehkä kuljetustilatkin näkyisivät oikein?

**Comment by AnneliO** [comment]
@IrinaHalminen Testaatko tätä next-kannassa, onko toive vielä ajankohtainen. Jos ei ole, suljetko tiketin? :)
