### ISSUE TITLE
[Kehitysehdotus] Matkapuhelinnumeron kopioituminen taattavan Tekstiviesti numeroon -kenttään 

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#248]
### Kehitysehdotukseni

Lisään henkilöasiakkaalle taattavan hänen oman tilinsä kautta Lisää taattava -painikkeella. Olen täyttämässä tässä tapauksessa lapsen tietoja ja hänelle on tarkoitus tulla sama puhelinnumero kuin takaajalle. Takaajan puhelinnumero ei automaattisesti kopioidu taattavan Tekstiviesti numeroon -kenttään ennen kuin on käynyt klikkaamassa Matkapuhelin-kenttää ja klikkaa sen jälkeen uudeelleen Tekstiviesti numeroon -kenttää.

Puhelinnumero (ja viestiasetukset?) voisi kopioitua siinä vaiheessa, kun ohjelma luo taattavalle oman asiakastietopohjan. Jos tätä ei haluta tapahtuvan, voisi edes olla niin, että numero kopioituisi Tekstiviesti numeroon -kenttään, kun kenttää klikkaa, jotta ei aina tarvitsisi erikseen muistaa klikata Matkapuhelin-kenttää tai kirjoittaa/kopsata numeroa. 

Uutta asiakasta lisätessä (esim. uusi henkilöasiakas) numero kopioituu suoraan Matkapuhelin-kentästä Tekstiviesti numeroon -kenttään, eli siinä ei ole ongelmia.

### Kohan osio

Asiakastiedot

**Comment by AnneliO** [comment]
Kohassa on olemassa järjestelmäasetus PrefillGuaranteeField, jossa määritetään, mitkä huoltajan tiedoista kopioidaan huollettavalle. Siellä ei kuitenkaan ole minusta valittavissa smsalertnumberia. Olisikohan järkevää, että kenttä pyrittäisiin lisäämään tuohon asetukseen?

**Comment by AnneliO** [comment]
PrefillGuaranteeField-asetuksessa voi valita other phone -kentän, johon meillä on triggeri, joka kopioi numeron smsalertnumberiin. Tämä ratkaissee asian.

**Comment by AnneliO** [comment]
@IrinaHalminen Onko ehdotettu ratkaisu ok?

**Comment by IrinaHalminen** [comment]
Kiitos tiedosta. Tämä ei itse asiassa ole enää muutenkaan aiheellinen tiketti, koska tekstiviesti numeroon -kenttään tuli tämä muutos: https://github.com/KohaSuomi/Koha/issues/204.
