### ISSUE TITLE
[Tukipyyntö] Vaski: asiakkaiden 358-alkuisiin puhelinnumeroihin + merkki

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#250]
### Tukipyyntö

Saisiko ajon, jolla Vaskin asiakasrekisterissä oleviin 358-alkuisiin puhelinnumeroihin laitettaisiin + merkki eteen? Nyt tietokannassa on jonkin verran toimimattomia puhelinnumeroita, joissa on maakoodi, mutta + -merkki puuttuu. 

### Kohan osio

Asiakastiedot

**Comment by paxed** [comment]
Kyseessä siis borrowers.phone -kenttä, eikä esim. smsalertnumber tai mobile -kentät?

phone-kentässä näyttää olevan jonkun verran todella lyhyitä numeroita, tyyliin 358XXX (eli alkavat 358 ja sen perässä on kolme numeroa) - mahtaako nämä olla jotain vanhoja tai kaupungin sisäisiä numeroita, ja tehdäänkö niille sama juttu?

**Comment by paxed** [comment]
phone, mobile, ja smsalertnumber-kenttiin laitettu tuo plussa eteen; phone-kenttiä muutettiin 76 kpl, mobile ja smsalertnumber-kenttiä molempia 323 kpl.

**Comment by sksandel** [comment]
Kiitokset!
