### ISSUE TITLE
[Tukipyyntö] Kuvailupohjien automaattinen päivitys

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#256]
### Tukipyyntö

Kenttien 
034 Kartta-aineiston matemaattiset tiedot koodeina → Mittakaava ja sijaintitiedot
046 Erikoiskoodattu julkaisuaika → Erikoiskoodatut aikamääreet
340 Fyysinen väline → Fyysinen tallenne
388 Luomisaika → Luontiaika
nimet on päivitetty MARC 21 -formaatin suomennokseen ja sovellusohjeisiin. Muutokset eivät näy OUTIn eikä TäTin kuvailupohjissa vielä. 

Miksiköhän pohjat eivät ole vielä päivittyneet? 

### Kohan osio

Kuvailu

### Jotain muuta?

Aiemmin näitä muutoksia haettiin aina joka kuukauden alussa ja siitä tuli ilmoitus sähköpostiin. Onko sama aikataulu edelleen käytössä? Tai onko käynyt niin, että tämä MARC-päivitys on tehty ennen 18.10. (jolloin päivitystoiminto laitettiin päälle) eikä tuota päivitystä ole vain tarkistettu?

**Comment by paxed** [comment]
Pohjat päivittyvät kerran kuukaudessa, alkaen 1.1.2023 - piti päivittyä jo aikasemmin, mutta koodissa oli bugi.

**Comment by AnneliO** [comment]
MARCiin on kuulemma tullut uutta ja pohjat pitäisi päivittyä. Ilmeisesti automaatiinen päivitys ei toimi?
