### ISSUE TITLE
[Tukipyyntö] Hea-käyttötilastojen jako -cron päälle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#257]
### Tukipyyntö

Vaskissa on käyttöönoton yhteydessä jäänyt laittamatta Hea-tilastojen jako päälle (unohtunut meiltä vaikka siitä puhetta olikin ollut). Muutin nyt UsageStats-järjestelmäasetukseksi "Kyllä", muuten hea-tilastoihin liittyvät asetukset olivat jo kunnossa (kirjastojen koordinaatit, verkkosivujen osoite yms).

Järjestelmäasetuksessa mainitaan, että asetus "vaatii misc/cronjobs/share_usage_with_koha_community.pl -ajastetun ajon (cronjob)". Onkohan tuollainen cron ollut Vaskissa jo käytössä vai vaatiiko toimenpiteitä?

### Kohan osio

Ylläpito

**Comment by janPasi** [comment]
Hea-tilastot on tällä hetkellä pois käytöstä joka paikassa ja ne pitäisi laittaa takaisin käyttöön.

**Comment by lmstrand** [comment]
Kaikille kimpoille laitettu Hea-tilastoja varten croni käyttöön. Ne ajautuvat joka kuun loppupuolella  20.-28. päivä, yksi kimppa per päivä. Vaskin ajautuu 24. päivänä.

**Comment by ajrajala** [comment]
Katselin tänään, että Vaski on sivulla https://hea.koha-community.org/libraries nyt mukana, joten tämän tiketin voinee sulkea.
