### ISSUE TITLE
[Tukipyyntö] Helle: lisäättekö torstaiaamuna 17.11.2022 Hae tietokannasta -hakuehdon tyhjennysrimpsun 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#258]
### Tukipyyntö

Lisäättekö torstaiaamuna 17.11.2022 Helleen IntranetUserJs-asetukseen rimpsun, joka tyhjentää Hae tietokannasta -kentän hakuehdon (tietyissä tapauksissa). 

Lisättävä rimpsu tiketistä https://tiketti.koha-suomi.fi/issues/5354#note-7

$(document).ready(function() {
      localStorage.removeItem("searchbox_value");
});

 
Hellessä rimpsu toimii näin:
- kun siirtyy hakutuloksesta jonkun teoksen perustiedot-näytölle, hakuehto poistuu
- kun siirtyy hakutulosnäytöltä Lainaus- TAI Palautus- TAI Uusinta-toimintoon, hakukenttä ei tyhjene vaan hakuehto pysyy

### Kohan osio

Tiedonhaku

**Comment by janPasi** [comment]
Voisiko tämän tehdä jo tiistaina muiden IntranerUserJS muutosten yhteydessä?

**Comment by Kati-Helle** [comment]
> Voisiko tämän tehdä jo tiistaina muiden IntranetUserJS muutosten yhteydessä?

Helleläisille on tiedotettu, että ko. muutos tulee Helle-Kohaan torstai-aamuna 17.11.2022.
Hellessä on sovittu, että mahdollisuuksien mukaan Koha-muutoksista tiedotetaan viikko ennen muutoksen toteutusta.

(Vastaukseni myöhässä, kun huomasin Pasi kysymyksesi vasta nyt.)

**Comment by janPasi** [comment]
Ok, mennäänpä sitten torstailla, mutta mielellään jatkossa nämä aina siihen tiistain päivityspompsiin :)

**Comment by Kati-Helle** [comment]
Kiitos toteutuksesta!
