### ISSUE TITLE
[Bugi] Lainasääntöä ei voi poistaa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#259]
### Mikä vikana?

Laina- ja maksusääntö sivulla ei pysty poistamaan olemassa olevaa lainasääntöä. Poisto ei toimi millään kieliversiolla. Lokilla ei kuulemma näy mitään virhettä.

### Mitä pitäisi tapahtua

Lainasääntö pitäisi poistua.

### Kohan osio

Ylläpito

**Comment by emta001** [comment]
Kummallista, testasin Siilin testillä niin että loin uuden säännön ja poistin sen. Poistui ihan ok. Missä kimpoissa tätä on testattu ja millaisia sääntöjä? Testattiinko testeillä vai tuotannossa?

**Comment by janPasi** [comment]
Kirkes ja Outi eivät ainakaan toimi.

**Comment by emta001** [comment]
Kokeilin uudestaan molemmissa, uuden säännön poistaminen toimi aluksi. Mutta kun tein Kirkekseen uuden säännön, joka on suht samankaltainen muiden sääntöjen kanssa, poisto ei enää onnistu. Tulee vain mieleen, että siellä on jokin kenttä joka jostain syystä estää poistamisen.

**Comment by emta001** [comment]
Yhteisössä on samaa oireilua, mutta kentässä _Decreased loan period for high holds (day)_. Siellä ei edes ole tuota _Holds pickup period (day)_ kenttää. Oliskohan datatable härö?

**Comment by emta001** [comment]
Yhteissössä on tähän tiketti [30694](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30694)

**Comment by janPasi** [comment]
Poistaminen onnistuu muuten lisäksi suoraan tietokannasta kyllä, siellä suunnassa ei tule mitään herjoja. Liittymä vain oikuttelee.

**Comment by emta001** [comment]
> Poistaminen onnistuu muuten lisäksi suoraan tietokannasta kyllä, siellä suunnassa ei tule mitään herjoja. Liittymä vain oikuttelee, eli voisi varmaankin liittyä kyllä datatablesiin.

Ei ollutkaan datatables :D Liittyy siis siihen, että perlin puolella holds_pickup_period _ja_ decreaseloanholds arvoja ei aseteta undefiks kun sääntö poistetaan. Hieman meni mutkikkaaksi kun näyttäisi sille, että meille on tuotu oman ominaisuutena tuo holds_pickup_period, ei ihan korjaannu tuolla yhteisöön viedyllä korjauksella :P

**Comment by emta001** [comment]
Korjaukset tuotu testeille.

**Comment by AnneliO** [comment]
Testasin OUTIn testissä ja pystyi poistamaan olemassa olevan säännön, luotua uuden ja poistettua sen sitten. Olemassa olevaa sääntöä pystyi muokkaamaan.

**Comment by erikamiettinen** [comment]
Kirkes-testikannassa pystyi nyt poistamaan luodun lainasäännön!

**Comment by emta001** [comment]
Viedään ominaisuus ensi viikon päivityksessä tuotantoihin.
