### ISSUE TITLE
[Bugi] Lumme: tuplavarauksia

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#260]
### Mikä vikana?

Mikkelissä on syntynyt tuplavarauksia, havaintoja useammastakin mutta konkreettiset todisteet kahdelta asiakkaalta, 31.10. ja asiakaspalautespostista 9.11.

Case 1: borrowernumber=58817

kirja: Seppä, Anita: Kuvien tulkinta : menetelmäopas kuvataiteen ja visuaalisen kulttuurin tulkitsijalle
varaukseen tarttuneet niteet: [N0000N722330] ja 915N02012074

Case 2: borrowernumber=54041, Hyvä journalismi-kirja, kävi hakemassa kirjan ajoissa, hyllyssä oli toinenkin sama kirja samalla varausnumerolla mutta eri noutopäivällä, vaikka asias ei  ollut sitä toiseen kertaan paria päivää myöhemmin varannut. 

### Kohan osio

Varaukset

**Comment by AnneliO** [comment]
Case 1: 

Asiakas on lainannut niteen N0000N722330 - 2022-10-20 15:02:34. Se ei ollut silloin kiinni varauksessa. Tämä nide on palautettu ennen tätä lainatapahtumaa edellisen kerran  2022-09-26 08:34:27. Siinä välissä ei tapahtumia statistics-taulussa.

Asiakas on tehnyt varauksen Kuvien tulkinta teokseen 19.10.2022 klo 14.19 ja se on jäänyt kiinni varaukseen 20.10.2022 klo 11.43 niteeseen 915N02012074. Asiakas on lainannut niteen  2022-10-31 13:28:12. Asiakas palautti tämän niteen samantien 2022-10-31 13:28:18.

Eli sanoisin, että asiakkaalla on ollut nide 915N02012074 noudettavana, mutta hän onkin lainannut syystä tai toisesta niteen N0000N722330. Asiakkaalla on ollut vain yksi varaus tietueeseen. Noutoilmoitus on lähtenyt vain niteestä 915N02012074.

Case 2:

Asiakas on tehnyt teokseen 258559 kolme kertaa varauksen:
2022-04-06 22:39:13 (tämä on poistettu 2022-04-14 15:27:15 ennen kuin se on jäänyt kiinni)
2022-10-06 15:24:25 (tehty Finnassa)
2022-10-10 16:44:54 (tehty Finnassa)

Asiakas on saanut noutoilmoituksen kahteen eri niteeseen: 593N0T208814 (24.10.2022) ja 915N02021630 (21.10.2022)

Nide 593N0T208814 (itemnumber 1381269) on palautettu 2022-10-24 13:26:33 ja jäänyt kiinni 10.10.2022 tehtyyn varaukseen. Se on lainattu 2022-10-28 13:04:41.

Nide 915N02021630 (itemnumber 817607) on palautettu edelliseltä asiakkaalta 2022-10-17 15:07:03 SAV_PK:ssa ja jäänyt kiinni 6.10.2022 tehtyyn varaukseen. Sen jälkeen se on palautettu  neljä kertaa:

2022-10-17 15:09:05 | SAV_PK
2022-10-21 10:48:12 | MLI_PK
2022-11-02 09:15:09 | MLI_PK 
2022-11-04 10:08:14 | VAR_PK

Yhteenveto: Asiakas on tehnyt teokseen kaksi varausta ja ne on jäänyt kiinni kahteen eri niteeseen. Asiakas on myös saanut kaksi noutoilmoitusta.

**Comment by Katja-Lumme** [comment]
Kiitos tiedoista, ja miten olit noita selvitellyt, laitan tuon itselleni ylös mikäli tulee joskus vastaavaa häpsinkiä:) Suljen tämän.
