### ISSUE TITLE
[Kehitysehdotus] Asiakkaan lainatietoihin uusinta-sarakkeeseen oletuksena rasti myös tänään erääntyville

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#261]
### Kehitysehdotukseni

Tällä hetkellä ainakin Siilinjärvellä rasti on oletuksena valmiina vain jo aiemmin erääntyneille. Toive on tullut suoraan asiakaspalvelusta.

### Jotain muuta?

![Uusinta-sarake](https://user-images.githubusercontent.com/98806001/202205207-380c1d5c-36d2-42eb-b7ed-6dfbae325ac0.png)

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 15.1.2024: Toteutetaan itse ja tarjotaan yhteisölle.

@ReettaSiili Tekisitkö tästä tiketin yhteisön Bugzillaan.

**Comment by ReettaSiili** [comment]
Mun eka :)
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35931

**Comment by atarnus** [comment]
Oletusrasti tulee checkouts.js:ssä näin:

```
if ( oObj.date_due_overdue && can_renew ) {
    content += "checked='checked' ";
```

Ja olio rakennetaan svc/checkouts näin:

```
my @parameters;
my $sql = '
    SELECT
        issues.issuedate,
        issues.date_due,
        issues.date_due < now() as date_due_overdue,
        issues.timestamp,
```

```
my $checkout = {
    .
    .
     date_due_overdue    => $c->{date_due_overdue} ? JSON::true : JSON::false,
```

Tuonne voidaan hakea myös arvo sille, onko eräpäivä nykyinen päivä, ja lisätä se eteenpäin menevään olioon:

`    date(issues.date_due) = date(now()) as date_due_today,`

`    date_due_overdue    => $c->{date_due_today} ? JSON::true : JSON::false,`

Ja muutetaan checkouts.js:ssä laittamaan ruksi myös tälle arvolle:

```
if ( can_renew && oObj.date_due_overdue || oObj.date_due_today ) {
    content += "checked='checked' ";
```

**Comment by atarnus** [comment]
Näyttää siltä, että Ceepos-maksu-nappi on tulostunut myös 'Poista Valitut' välilehdelle, ja nyt sitten Hyväksy-nappikin katoaa sieltä, eli viilataan vähän enemmän.

**Comment by atarnus** [comment]
Nyt on Outi-testillä seuraava rimpsu. Mukana on sinne aiemmin lisätyt loggausrivit, ilmeisesti ovat tarpeen. Lisäsin alkuun tarkistuksen, että ollaan oikealla sivulla eikä kyseessä ole poisto. (Jostain syystä 'Poista valitut' ja 'Maksa valitut' -lomakkeet ovat samannimisiä.)

```
/// ALKU ///

/// Ceepos-maksu -napin lisäys ///
/// Napin taustavärinä ja reunavärinä keltainen? #ffc32b ///
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/members/paycollect.pl' && !window.location.search.includes("WRITEOFF")) {
    var ceeposBranches = ['OUPK','OUR','OUHA','OUMA','OUUL','OUOS','OUH','OUKI','OUKS','OUKA','OUPE','UTPK','IIPK','PUPK','VAPK','LUPK'];
    if (ceeposBranches.includes($("#logged-in-info-full .logged-in-branch-code").text())) {
      console.log("ceeposbranch löytyi");
      console.log($("#logged-in-info-full .logged-in-branch-code").text()); 
      $("#payfine .action, #payindivfine .action").find("input").hide().after('<input type="button" id="CeeposMaksu" class="btn btn-primary" style="margin:0px 10px;" value="Ceepos-maksu"  onclick="setCeeposPayment($(this))"/>');
      if(localStorage.getItem('ceeposOffice')) {
        $('#payment_type').val(localStorage.getItem('ceeposOffice'));
      }
    }
  }
  $('#paycollect').hide();
  $("#circmessages a[href*='/cgi-bin/koha/members/paycollect.pl'").hide();
  $("#patron_messages a[href*='/cgi-bin/koha/members/paycollect.pl'").hide();
});

function setCeeposPayment(element) {
  var ceeposOffice = $('#payment_type').find(":selected").val();
  console.log("CeeposOffice:");
  localStorage.setItem('ceeposOffice', ceeposOffice);
  console.log(localStorage.getItem("ceeposOffice"));
  var payments;
  var borrowernumber;
  if($("#payindivfine").find("#pay_individual").val() == 1) {
    console.log("payindividual = 1");
    borrowernumber = $("#payindivfine").find("#borrowernumber").val();
    console.log("borrowernumber:");
    console.log(borrowernumber);
    payments = [{'borrowernumber': $("#payindivfine").find("#borrowernumber").val(), 'accountlines_id': $("#payindivfine").find("#accountlines_id").val(), 'description': $("#payindivfine").find("#description").val(), 'amountoutstanding': $("#payindivfine").find("#amountoutstanding").val(), 'payment_type': $("#payindivfine").find("#debit_type_code").val(), 'office': ceeposOffice}];
    console.log("Payments:");
    console.log(payments);
  } else {
    borrowernumber = $("#payfine").find("#borrowernumber").val();
    payments = [{'borrowernumber': $("#payfine").find("#borrowernumber").val(), 'accountlines': $("#payfine").find("#selected_accts").val(), 'amountoutstanding': $("#payfine").find("#collected").val(), 'office': ceeposOffice}];
    console.log("not paying invidual");
    console.log("payments:");
    console.log(payments);
  }
  console.log ("sending data:");
  console.log (JSON.stringify(payments));
  $.ajax({
    url: "/api/v1/contrib/kohasuomi/payments/ceepos", 
    type: "POST",
    dataType: "json",
    contentType: "application/json; charset=utf-8",
    data: JSON.stringify(payments),
    beforeSend: function() {
      $("#CeeposMaksu").attr("disabled", true);
      alert("Maksu lähetetty, käsittele kassassa!");
    },
    success: function (result) {
      console.log("api Success:");
      console.log(result);
      location.href = '/cgi-bin/koha/members/boraccount.pl?borrowernumber='+borrowernumber;
    },
    error: function (xhr, status, error) {
      console.log("api Error:");
      console.log(xhr, status, error);
      console.log(error);
      $("#CeeposMaksu").attr("disabled", false);
      alert(JSON.parse(xhr.responseText).error);
    }
  });
}
///LOPPU ///
```

**Comment by atarnus** [comment]
Vielä jos laitamme lihavonnin kuluvan päivän eräpäiville, niin tämä checkouts.js:

```
if ( oObj.date_due_today ) {
    due = "<span class='strong'>" + due + "</span">;
}
```

**Comment by atarnus** [comment]
Tämän pitäisi olla nyt nexteillä. Uusinnan kohdalla oletusrasti tänä päivänä erääntyville ja kuluvan pvm:n lihavointi eräpäivä-sarakkeessa.

**Comment by pknuuti** [comment]
Toimii Vaaran nextillä. 
![2023kuvat 381](https://github.com/KohaSuomi/Koha/assets/73887264/b7599b85-17f2-495a-a130-791c0aa595a5)

**Comment by ReettaSiili** [comment]
Toimii Siilin nextillä toivotulla tavalla ja uusinta onnistuu uusi valitut niteet -painikkeesta.

Lihavointi kuluvan päivän eräpäiville erotuksena myöhässä oleville punaisille on mielestäni hyvä ratkaisu.

**Comment by PiaKusmin** [comment]
Testattu Lapin nextillä. Meillä uusinta-nappi on oletuksena ei-aktiivinen. Miksi? Onko muilla? Tulee aktiiviseksi, kun klikkaa esim. jonkun ruksin pois tai lisää uuden ruksin. Mutta suoraan ei pääse uusimaan kuin Uusi kaikki-napilla.

![Uusintanappi](https://github.com/KohaSuomi/Koha/assets/99241432/03970f8a-bada-4324-8792-e56e3e539a26)

**Comment by Kati-Helle** [comment]
Helle-nextissäkin asiakkaan lainoissa tänään erääntyvä laina on automaattisesti valittuna uusintaa varten (tänään on 24.4.2024)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2d3d83e3-41f0-434c-b9fb-134132d01ea1)

**Comment by Kati-Helle** [comment]
> Testattu Lapin nextillä. Meillä uusinta-nappi on oletuksena ei-aktiivinen. Miksi? Onko muilla? Tulee aktiiviseksi, kun klikkaa esim. jonkun ruksin pois tai lisää uuden ruksin. Mutta suoraan ei pääse uusimaan kuin Uusi kaikki-napilla.
> 
> ![Uusintanappi](https://private-user-images.githubusercontent.com/99241432/325196185-03970f8a-bada-4324-8792-e56e3e539a26.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NTgzNjEsIm5iZiI6MTcxMzk1ODA2MSwicGF0aCI6Ii85OTI0MTQzMi8zMjUxOTYxODUtMDM5NzBmOGEtYmFkYS00MzI0LTg3OTItZTU2ZTNlNTM5YTI2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDExMjc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhOTE0OGY5NjYzZDE5ODQ0YmI2MTY1MjdmMWMwYmVlOGVkMDA5YjNhNmY3MmI5MmM3MjBkYjVmOTJlNzE2YjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8WTrGA0g9qyESFnzfcKR1oVLE02rJQpxUj5P-x-eiao)

Helle-nextissäkään Uusi valitut niteet -painike ei ole automaattisesti aktiivinen.

**Comment by atarnus** [comment]
Testasin pikaisesti poistamalla tuon branchin ja siltikin tuo uusimisnappi on alkuun disabled, eli ei pitäisi johtua tästä muutoksesta. Pitää tutkia mikä on, mahd. tehdä asiasta oma tiketti.

**Comment by ReettaSiili** [comment]
2 päivää sitten Siili-nextillä nappi on ollut vielä aktiivinen ja toiminut ok :), nyt ei ole enää.

**Comment by AnneliO** [comment]
Olen testannut tuota ennen Kassun muutosta ja nappula ei ollut aktiivinen sitä ennenkään. Tästä ongelmasta löytyy [Bugzillasta tiketti 36060](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36060). :)

**Comment by ReettaSiili** [comment]
Muistaakseni :) en koskenut Siilissä rukseihin, mutta olen varmaankin koskenut, kun sain uusinnan napista onnistumaan.

**Comment by AnneliO** [comment]
Tämä on viety tuotantoon. Tuosta napin epäaktiivisuudesta pitää tehdä erillinen tiketti. :)

**Comment by ReettaSiili** [comment]
Suljen tämän, valintanapin korjaus jatkuu tiketissä #1207.
