### ISSUE TITLE
[Tukipyyntö] Vaski: Hyllypaikan muutos niteille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#262]
### Tukipyyntö

Vaskissa aloitetaan kellutuskokeilu koko kimpan tasolla. Kellutusta varten pitäisi saada muutettu locationiksi 'MUS' seuraavat ehdot täyttäville niteille:
- niteen homebranch EI ala alkukirjaimilla KK ('KKLI', 'KKNA' jne)
- niteen mtype on 'CD'
- niteen nykyinen location on 'AIK'

Jos katsoin oikein niin näillä spekseillä muutettavia niteitä olisi hitusen alle 9800 eli varmaan nopeampi hoitaa ajona kuin erämuokkaus-työkalulla.

**Comment by ajrajala** [comment]
Määräpäivä viitteellinen, tärkeintä että saataisiin muutos marraskuun loppuun mennessä.

**Comment by janPasi** [comment]
Muuten aika suoraviivainen homma, mutta mtype ei ole nidetieto vaan kuvailutietueessa, joten se tarvinee kaivella biblioitems-taulun itemtype-kentästä.

**Comment by janPasi** [comment]
https://vaski-test.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2185&phase=Run%20this%20report

 10395 nidettä palautuisi tuolla raportilla. Miltä tämä näyttää?

**Comment by ajrajala** [comment]
Näyttää oikealta, määrä testillä täsmää sen kanssa miten nuo itsekin hain. Eli tämän ajon saanee tehdä, kun on sopiva hetki.

**Comment by janPasi** [comment]
Tehdään vaikka ensi tiistaina Koha-päivityksen yhteydessä.

**Comment by janPasi** [comment]
update items set location='MUS' where homebranch not like 'KK%' and location='AIK' and biblionumber in (select biblionumber from biblioitems where itemtype='CD');

Tuolla menee.

**Comment by emta001** [comment]
Ajo tehty, muutos koski 9673 nidettä.

**Comment by ajrajala** [comment]
Kiitokset! Saatavuustiedoissa näkyy muutettujen niteiden kohdalla kotikirjasto-sarakkeessa hyllypaikka näin: Masku, Lemun kirjasto _Aikuiset (Musiikki)_ (esim. tietue https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=672943). Liittyykö tuo permanent_locationiin, olisiko siihenkin kenttään pitänyt muuttaa AIK -> MUS? Tikettiä tehdessä ei tullut tuo mulle mieleen.

Samaten unohdin, että Kohan koko signumit (itemcallnumber) pitäisi näille niteille päivittää, koska nyt niissä mukana vielä hyllypaikkalyhenne AIK.

Onnistuuko tehdä jossain kohtaa vielä uusi muutosajo? :S

**Comment by emta001** [comment]
Pitää hieman testailla, mutta eiköhän tuo onnistu.

**Comment by emta001** [comment]
Tein muutoksen Vaski testille, vilkaisetko Anni että näyttää oikealta.

**Comment by ajrajala** [comment]
Näyttää oikealta! Saatavuustiedoissa näkyy hyllypaikkana nyt pelkkä Musiikki ja Kohan koko signumeissa on hyllypaikkalyhenne MUS (eikä signumeista pudonnut mitään muuta tietoa pois). Saa tehdä samat temput siis tuotantoon sitten kun ehdit.

**Comment by emta001** [comment]
Tällaisen muutoksen ajoin (niteet tallessa aputaulussa items_kd_g262_20221123):

`UPDATE items SET permanent_location = "MUS", itemcallnumber = CONCAT('MUS',(substring(itemcallnumber,4))) WHERE homebranch NOT LIKE "KK%" AND permanent_location = "AIK" AND location = "MUS";`

Muutos koski 9630 nidettä eli sellaiset 43 jäi tämän ajon ulkopuolelle. Katselen vielä löytyisikö niitä ja onko niissäkin korjattavaa.

**Comment by emta001** [comment]
Vielä löytyi 13, nekin on nyt muutettu. Lopuissa 30 on oletettavasti sekä locationit että signum kohdillaan.

**Comment by ajrajala** [comment]
Hienoa, kiitos näistä muutosajoista, näyttää tuotannossakin niteet nyt siltä kuin pitää.
