### ISSUE TITLE
[Tukipyyntö] OUTI: Omatoimen käyttökiellon asettaminen asiakkaalle

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#265]
### Tukipyyntö

"Sovitulle" asiakkaalle asetataan omatoimen käyttökielto kirjastoon OUKV (Kaukovainion kirjasto) ajalle 18.11.2022-2.1.2023. 
Päätöksen tekijä: Oulun alueellinen kirjastopalvelupäällikkö 

Kodo hoitaa.

Koha-tuki laittaa tiedon käyttökiellosta asiakkaan Viesti-osioon.

**Comment by janPasi** [comment]
Käyttökielto asetettu seuraavasti:

<code>insert into borrower_ss_blocks (borrowernumber, branchcode, expirationdate, notes, created_by, created_on) values ('xxx', 'OUKV', '2022-01-02 00:00:00', 'Kirjastopalvelupäällikkö xxx päätös', 'xxx', now());</code>
