### ISSUE TITLE
[Bugi] Signum-pluginit ei lisää alaviivaa välilyönnin tilalle

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#267]
### Mikä vikana?

Jos signumin ottaa 942m-kentästä, niin se rakentuu vanhan mallin mukaan. Jos signumissa on väli keskellä, esim. 5 M signumista näkyy tarrassa pelkkä 5, eikä kuten niteiden signum-plugarissa, jossa tulee alaviiva tuohon väliin 5_M.

### Mitä pitäisi tapahtua

Signumiin pitäisi tulla välilyönnin tilalle alaviiva. Esim. 5 M -> 5_M

**Comment by emta001** [comment]
Niin siis... koskeeko ongelma tarroja vai signumeita yleensä?

**Comment by AnneliO** [comment]
> Niin siis... koskeeko ongelma tarroja vai signumeita yleensä?

Hyvä kysymys. Selvittelen vielä vähän lisää.

**Comment by AnneliO** [comment]
Tämä toimikin oikein, kun testattiin lisää. Suljen tiketin! :)
