### ISSUE TITLE
[Tukipyyntö] Helle: niteiden virheellisten cn_sort-kentän arvojen korjaus. Korjattavia Loviisan niteissä.

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#270]
### Tukipyyntö

Hellen niteiden virheellisille signumeille on aikoinaan tehty korjausajoja. Signumin korjauksen lisäksi myös niteen cn_sort-kentän arvot tarvitsevat korjauksen. Osa cn_sort-kentän korjausajoista on vielä toteuttamatta.

Alkuperäisen Redmine-tiketin kommentti https://tiketti.koha-suomi.fi/issues/3161#note-44 tämä:

Saisiko vielä korjauksen Loviisan kirjastojen niteiden virheellisille cn_sort-arvoille? 
Loviisan kirjastotunnusten alkuna on LOV

Korjausta kaipaavat cn_sort-arvot alkavat arvoilla
Lov
Var

Poistettavan arvon jälkeinen tyhjämerkki tulee myös poistaa.
Kyseisiä arvoja on erilaisin kirjainkokovariaatioin.

Muutama esimerkki tarvittavasta korjauksesta:
itemnubmer:627768
cn_sort:Lov 82.31 NYN
cn_sort korjauksen jälkeen:82.31 NYN

itemnumber:630749
cn_sort:Var 99.1 TAU
cn_sort korjauksen jälkeen:99.1 TAU

**Comment by janPasi** [comment]
Tähän voisi olla hyvä harjoitus meidän uusille tulijoille. Pidetäänpä mielessä.

**Comment by paxed** [comment]
Esimerkkiniteissä cn_sort ja itemcallnumber (kohan koko signum) sisältävät tuon poistettavan "Lov " tai "Var " -osan, mutta itemcallnumberia ei muuteta?

**Comment by Kati-Helle** [comment]
> Esimerkkiniteissä cn_sort ja itemcallnumber (kohan koko signum) sisältävät tuon poistettavan "Lov " tai "Var " -osan, mutta itemcallnumberia ei muuteta?

itemcallnumber-arvot ovat nyt kunnossa/sääntöjen mukaisia, eli niitä ei muuteta. Virheellisten itemcallnumber-arvojen massamuutos on jo tehty aiemmin, mutta muutoksen yhteydessä cn_sort-arvot jääneet muuttamatta.

**Comment by Kati-Helle** [comment]
Kiitos!
