### ISSUE TITLE
Tieteellisten pääkäyttäjille pääsy tikettien seuranta -projektiin

### ISSUE THREAD

**Issue by janPasi** [KohaSuomi/Koha#271]
Tieteellisten kirjastojen pääkäyttäjät ovat seuranneet Redminessä Koha-Suomen tikettejä. Tällä hetkellä he pystyvät seuraamaan GitHubissa olevia tikettejä kunkin repositorion kautta, mutta tikettien seuranta -näkymä olisi selkeämpi. Voitaisiinko tieteellisten pääkäyttäjät liittää esimerkiksi vain luku -oikeuksin Tikettien seuranta -projektiin?

**Comment by AnneliO** [comment]
Yksi vaihtoehto on, että tikettejä seuraa Githubiin kirjautuneena.

Kaikki Koha-Suomen tiketit näkyvät, kun klikkaa kirjautuneena Githubin yläreunasta [Issues-linkkiä](https://github.com/issues) ja muuttaa hakukenttään seuraavan tiedon "is:open is:issue user:kohasuomi archived:false" (ilman hipsuja).

Tuossa näkymässä ei toki näe tiketin "tilaa" yhtä kätevästi, mutta se ei vaatisi lukuoikeuksien antamista.

**Comment by AnneliO** [comment]
Tikettien seuranta -projekti muutettiin julkiseksi, joten sitä pystyy nyt seuraamaan kaikki kirjautumatta.
