### ISSUE TITLE
OUTI: SIP-tunnuksen lisääminen palvelimelle

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#272]
### Tukipyyntö

Support-postiin lähetetään salattuna tarkemmat tiedot.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle, tulevat käyttöön huomenna.

**Comment by velimarj** [comment]
Kiitokset, laitamme toisenkin SIPin Support-postiin.

**Comment by emta001** [comment]
Toinenkin tunnus lisätty.

**Comment by velimarj** [comment]
Kiitos, suljen tiketin.

**Comment by piiaseme** [comment]
Hei, automaatin toimittaja lähetti epähuomiossa salasanan meille salaamattomassa vastausviestissä, joten vaihdan salasanan uuteen. Lähetän sen kohta teille Support-lootaan. Pahoittelut :/

**Comment by emta001** [comment]
Tunnuksen salasana vaihdettu.

**Comment by piiaseme** [comment]
Kiitos !!
