### ISSUE TITLE
Helle: lainatessa kirjaston Koha-kalenterin kiinniolopäiviä ei ole huomioitu, vaan lainan eräpäiväksi on tullut kiinniolopäivä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#273]
### Mikä vikana?

Kerkkoon kirjastossa lainattujen lainojen eräpäiväksi on tullut kirjaston Koha-kalenterin kiinniolopäiviä.

Kerkkoon kirjaston kirjastotunnus: PRVKR
Koha-kalenterin yksittäiset kiinniolopäivät 5.12.2022 ja 7.12.2022 ovat lainojen eräpäivinä. Kiinniolopäivät ovat olleet tallennettuina kirjaston Koha-kalenteriin lainaustapahtumien aikaan.

Kerkkoon kirjaston marraskuun 2022 Koha-kalenteri, jossa näkyvät esimerkkitapausten lainauspäivät sekä joulukuun ensimmäisen viikon yksittäiset kiinniolopäivät
![kuva](https://user-images.githubusercontent.com/99952449/203306183-63fb3d50-6adf-4492-aa95-e50c1bac83c8.png)

Lainatietoja issues-taulusta (hakuun otettu mukaan items-taulun homebranch JA itype)
![kuva](https://user-images.githubusercontent.com/99952449/203305341-ba30368d-f08a-4913-bb13-73b488e69b01.png)

AsiakasID: 7627 
- lainauspäivä 7.11.2022
- kolmen lainan eräpäivänä Koha-kalenterin kiinniolopäivä 5.12.2022, esim. issue_id = 4813051
- yhden lainan eräpäivänä Koha-kalenterin kiinniolopäivä 7.12.2022, issue_id = 4813055

AsiakasID=19185
- lainauspäivä 21.11.2022
- kahden lainan eräpäivänä Koha-kalenterin kiinniolopåivä 5.12.2022, esim. issue_id = 4859021

AsiakasID=4507
- lainauspäivä 21.11.2022
- yhden lainan eräpäivänä Koha-kalenterin kiinniolopäivä 5.12.2022, issue_id = 4859048

**Comment by Kati-Helle** [comment]
Tarkistin muiden Porvoon kirjastojen eräpäivät: ei eräpäiviä kirjastokalenteriin merkittyinä kiinniolopäivinä.

Esimerkiksi Porvoon kirjastoauton kalenterissa arki-kiinniolopäivät on merkitty vuosittain toistuvina (eikä yksittäisinä kuten Kerkkoon kirjaston kalenterissa).
![kuva](https://user-images.githubusercontent.com/99952449/204456078-794da517-6da8-44cd-a405-0cf0cc0fe30a.png)

Kalenterin kiinniolopäivien värien merkitykset
![kuva](https://user-images.githubusercontent.com/99952449/204456643-d78e9956-8951-4645-a2a0-df0ef8953f53.png)

**Comment by AnneliO** [comment]
Onko lainat tehty automaateilla vai virkailijaliittymän kautta?

**Comment by Kati-Helle** [comment]
> Onko lainat tehty automaateilla vai virkailijaliittymän kautta?

Virkailijaliittymällä. Kerkkoon kirjastossa ei ole lainausautomaattia. 
(Porvoon kirjastoautossakaan ei ole lainausautomaattia.)

**Comment by Kati-Helle** [comment]
Porvoon kaikki kirjastot olivat kiinni 28.10.2022 ja kirjastojen kalentereissa kiinniolopäivä on merkitty yksittäisenä kiinniolopäivänä.
old_issues-taulusta löytyy tänään yksi laina, jonka eräpäivä on 28.10.2022 (issue_id 4707090). issues-taulussa ei yhtäkään Porvoon kirjastojen lainaa eräpäivällä 28.10.2022.

**Comment by Kati-Helle** [comment]
Uusi 'tapaus': Kerkkoon kirjastossa (PRVKR) ma 23.1.2023 lainatulle niteelle on tullut eräpäiväksi kirjaston Koha-kalenteriin merkitty yksittäinen kiinniolopäivä 20.2.2023.

![kuva](https://user-images.githubusercontent.com/99952449/214519228-a6f8172d-181a-4b5f-965f-bac58f4c7dba.png)

Kerkkoon kirjaston helmikuun 2023 Koha-kalenteri
![kuva](https://user-images.githubusercontent.com/99952449/214519351-a27ea032-32c8-401c-904b-ec5070087dab.png)

Muilla samana päivänä lainatuilla niteillä sekä yhdellä uusitulla niteellä on Koha-kalenteria noudattava eräpäivä 27.2.2023.

**Comment by emta001** [comment]
Ainakin kannassa tuo päivä on ihan oikein tallennettuna. Siellä saattaa olla tämän niteen (ja muidenkin) kohdalla nyt jotakin, minkä vuoksi se pääsee ohi järjestelmäasetuksista tai muista ehdoista.

**Comment by emta001** [comment]
Voisiko olla, että kyseinen nide (viivakoodi 638N053452214) onkin noudattanut kotikirjastonsa (PRVPK) eikä sijaintikirjastonsa (PRVKR) kalenteria?

**Comment by Kati-Helle** [comment]
Niteen kotikirjaston (PRVPK) Koha-kalenterissa niteelle lainatessa tullut eräpäivä ei ole kiinniolopäivä. 
Siltä osin ainakin voisi siis olla noin.

Mutta: kirjastossa PRVKR on mm. 23.1.2023 kirjaston Koha-kalenterin mukaisia eräpäiviä niteille, joiden kotikirjasto on myös PRVPK.

**Comment by emta001** [comment]
> Niteen kotikirjaston (PRVPK) Koha-kalenterissa niteelle lainatessa tullut eräpäivä ei ole kiinniolopäivä. Siltä osin ainakin voisi siis olla noin.
> 
> Mutta: kirjastossa PRVKR on mm. 23.1.2023 kirjaston Koha-kalenterin mukaisia eräpäiviä niteille, joiden kotikirjasto on myös PRVPK.

Hmm, sitten se ei ole välttämättä se pääasiallinen syy vaan siellä on vielä jotain muutakin. Pitää testailla.

**Comment by Kati-Helle** [comment]
> > Niteen kotikirjaston (PRVPK) Koha-kalenterissa niteelle lainatessa tullut eräpäivä ei ole kiinniolopäivä. Siltä osin ainakin voisi siis olla noin.
> > Mutta: kirjastossa PRVKR on mm. 23.1.2023 kirjaston Koha-kalenterin mukaisia eräpäiviä niteille, joiden kotikirjasto on myös PRVPK.
> 
> Hmm, sitten se ei ole välttämättä se pääasiallinen syy vaan siellä on vielä jotain muutakin. Pitää testailla.

Porvoossa eli keskenään kelluvissa PRV-kirjastoissa lähes kaiken aineiston kotikirjasto on PRVPK.

**Comment by Kati-Helle** [comment]
Hain vertailtavaksi items taulusta PRVKR-kirjastossa 23.1.2023 lainattujen niteiden tiedot. 
Kuvassa on sinifonttisena kahden oikeaeräpäiväisen niteen tiedot sekä yhden mustafonttisena vääräeräpäiväisen. (itype on niteiden viimeinen arvollinen kenttä.)
![kuva](https://user-images.githubusercontent.com/99952449/214538900-9e3174c2-05ba-429b-ac63-585a54727494.png)

**Comment by AnneliO** [comment]
Tuo väärän eräpäivän saanut nide on palautettu viimeisimmän kerran 20.10.2022 Porvoon pääkirjastolla eli siinä on todennäköisesti ollut sijaintikirjastona PRVPK, kun se on lainattu Kerkkoossa.

| 2022-10-20 15:20:09 | PRVPK  | 0.0000 | return |       | NULL     |    1522809
| 2023-01-23 18:15:15 | PRVKR  | 0.0000 | issue  |       | NULL     |    1522809

Hellessä on circcontrol-asetuksessa "mistä nide on kotoisin/where the item is from"
HomeOrHoldingBranch-asetuksessa taas "niteen sijaintikirjasto"

Eli käytännössä käytetään niteen sijaintikirjaston kalenteria ja laina- ja maksusääntöjä. Ja kun niteellä on ollut sijaintikirjastona Porvoon pääkirjasto, jossa ei ole sulkupäivää 20.2.2023, on laina saanut sen eräpäiväksi.

**Comment by Kati-Helle** [comment]
Hienoa, että tämä selvisi. Kiitos!
Syystä tai toisesta Kerkkoon kirjastossa sijaitsevia niteitä on siis jäänyt palauttamatta Kerkkoon kirjastona.
