### ISSUE TITLE
Varaukset eivät näy asiakkaalle Finnassa ja korjaus siihen

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#280]
### Mikä vikana?

Asiakas ei pääse katsomaan varauksiaan Finnassa. Antaa virheilmoituksen 

![Varaukset](https://user-images.githubusercontent.com/99241432/203978661-18f2d1f2-9ec8-4db8-8f17-73053c5a03fb.jpg)

Finna-tuesta tuli vastaus: 
"Epäonnistuvan varausten hakuun Koha vastaa näin:

{"errors":[{"message":"Month out of range.","path":"\/acquisition_date"},{"message":"Month out of range.","path":"\/replacement_price_date"}],"status":200}

Tämän perusteella arvelisin, että asiakkaan varaus kohdistuu niteeseen, jolla on virheellisiä päivämääriä. Kohassa sisäisesti nuo kentät ovat siis dateaccessioned ja replacementpricedate. Lienee syytä käydä niteet läpi ihan yleisestikin, koska tyypillisesti juuri virheelliset päivämäärät aiheuttavat näitä ongelmia."

Eli jompi kumpi nuista arvoista on muotoa "0000-00-00" ja se aiheuttaa tuon ongelman. Virheelliset päivämäärät tulee korjata.

**Comment by PiaKusmin** [comment]
Jos replacementpricedate arvon kirjoittaa muotoon 12.12.2012, koha muuttaa sen 0000-00-00 arvoksi, jolloin aiheuttaa ongelmia varausten näkymisen kanssa. 

Dateaccessioned ongelmaa en saanut toistettua, mutta virheenä näkyy viallinen päivämäärä ko. kohdassa. Tullut sanoman mukana? Käsin vaikea laittaa virheellisesti, koska siinä on se kalenteri.

Bugi järjestelmässä? Miten korjataan, ettei virheellisiä arvoja tulisi lisää?

**Comment by emta001** [comment]
Tehdään tähän raportti, jolla pääkäyttäjät voivat hakea virheelliset päivämäärät sisältävät niteet.

**Comment by emta001** [comment]
Raportti lisätty [raporttikirjastoon](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Valmiita_SQL-raportteja#Niteet-joissa-Hakintap%C3%A4iv%C3%A4m%C3%A4%C3%A4r%C3%A4-tai-Hinta-voimassa-alkaen-kent%C3%A4ss%C3%A4-on-arvo-0000-00-00).

**Comment by emta001** [comment]
Hmm, minusta tässä voisi tehdä niin, että otetaan kentässä 952$w käyttöön dateaccessioned.pl plugin. Se siis lisää kenttään automaattisesti lisäyspäivän arvon ja normaalisti kirjoitetun päivämäärän tallennuskin onnistuu. Omaa plugaria tuolle tuskin kannattaa tehdä, se olisi lopulta vain tuon dateaccessioned.pl:n kopio.

**Comment by Kati-Helle** [comment]
Hellessä 952w-kenttä (replacementpricedate) on piilotettu kuvailupohjista, eli kenttä ei ole käytettävissä.

**Comment by Kati-Helle** [comment]
> Hellessä 952w-kenttä (replacementpricedate) on piilotettu kuvailupohjista, eli kenttä ei ole käytettävissä.

Laitoin hetkeksi 952w-kentän kuvailupohjaan näkyviin ja katsoin marraskuussa 2022 tilatun teoksen nidetiedot: 952w-kenttä niteellä on. Onko muodostunut automaattisesti tilatessa (EditX-tilaus)? 
![kuva](https://user-images.githubusercontent.com/99952449/204723150-fdd50e66-ee04-4a1e-925f-ff30832c1d93.png)

**Comment by emta001** [comment]
Anneli tutki tuota dateaccessioned.pl käyttöä. Seuraavassa versiossa plugin on oletuksena käytössä default kuvailupohjilla, mutta meillä se pitää lisätä pohjiin joko kävin tai ajolla. Vielä on testailematta kuitenkin, oliko pluginissa jotain korjattavaa kun sitä  käyttää nide muokkauksessa.

**Comment by lasse-koha** [comment]
Näitä virheellisiä niteitä on tällä hetkellä Lumpeessa 43, Kyytissä 4, Vaarassa 129, Outissa 2, Vaskissa 1 kpl, muissa ei yhtään. Muutamissa niteissä on nollilla sekä dateaccessioned että replacementpricedate, useimmissa kuitenkin on jommassakummassa järkevä päivämäärä. Nuo olisi varmaan hyvä käydä yksitellen läpi ja korjata niihin mahdollisimman oikeat tiedot. Jospa seuraavassa versiossa plugin varmistaisi ettei virheitä synny lisää.

**Comment by ajrajala** [comment]
Kävin Vaski-tuotannon kuvailupohjat läpi ([pääkäyttäjäpalaverissa sovitun mukaisesti](https://koha-suomi.fi/paakayttajat2023#viikko-10-muistio)) ja replacementpricedate ei ollut missään pohjassa pakollinen (oli joko määritelty ei-pakolliseksi tai sitten osakenttä oli ohitettu kokonaan). Meillä on silti kuukausittaisissa tarkistuksissa tullut vastaan aina yksi tai kaksi nidettä, joissa 0000-00-00 -arvoa esiintyy, esim. nyt itemnumber 2923095 jolle virheelliset päivämäärät näyttäisi tallentuneen joko tilaussanomasta tallentuessa tai sitten hankinnan vastaanotossa (lokista ei näy mitkä pvm:t niteellä on ollut ennen hankinnan vastaanottoa).

Eli ilmeisesti tuon replacementpricedaten määrittely ei-pakolliseksi ei täysin takaa sitä, etteikö 0000-00-00 arvoa voisi siihen tallentua, vaan jokin virhe tapahtuu hyvin satunnaisesti tilauksen ( saapumiskäsittelyn tallennusvaiheessa tässä nykyisessä versiossa..?

**Comment by emta001** [comment]
Hmm, ainakin dateaccessioned ja datelastseen arvojen tulisi syntyä kutsumalla _getDateCreated_ funktiota, joka taasen kutsuu _getLocalTime_ funktiota. Jota muuten kutsuu _getTimeStamp_, jolla asetetaan timestampin arvo ja sehän näkyisi menneen oikein. Joten tässä saattaa tapahtua jotain jännää joko silloin kun päivämäärä luodaan tai silloin kun se muutetaan oikeaan muotoon (%Y-%m-%d).

**Comment by AnneliO** [comment]
Jos näitä tilanteita ei ole enää tullut vastaan, niin voisiko tiketin sulkea? :)

**Comment by emta001** [comment]
Minun puolesta voi.
