### ISSUE TITLE
Siirtoraportti-toimintoon näkymään lisää tietoja tietueesta: teoksen nimi JA aineistotyyppi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#285]
### Kehitysehdotukseni

Saisiko Siirtoraportilla näkymään nämä tietueen tiedot:
- teoksen nimi: arvo tietueen 245a-kentässä
- aineistotyyppi: arvo tietueen 942c-kentässä

Siirtoraportilla näkyy nyt tietueesta tietuenumero: 
![kuva](https://user-images.githubusercontent.com/99952449/205030360-c4227bdd-637b-4743-8c98-5e13910b551c.png)

**Comment by AnneliO** [comment]
Uudessa Tietuesiirtäjä-liitännäisessä on näkyvillä tietueen nimeke ja aineistotyyppi.

![Image](https://github.com/KohaSuomi/Koha/assets/33121325/635537e8-d226-43a4-95ed-311b51425b32)

**Comment by Kati-Helle** [comment]
Hienoa! 
Milloin onkaan käytössä?

**Comment by AnneliO** [comment]
> Hienoa! Milloin onkaan käytössä?

Tietuesiirtäjän kehitystä voi seurata tässä tiketissä: https://github.com/KohaSuomi/Koha/issues/915

**Comment by AnneliO** [comment]
Suljetko Kati tiketin? :)
