### ISSUE TITLE
Signumbuilderista pois 130a-kenttä

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#288]
### Tukipyyntö

Vaskissa on ollut toive siitä, että signumbuilderista saisi pois käytöstä 130a-kentän perusteella muodostuvat signumit. Kentän 130a käyttö aiheuttaa useimmiten sen, että signum joudutaan korjaamaan käsin. Redminessa tiketissä [4589](https://tiketti.koha-suomi.fi/issues/4589) asia näyttäisi jääneen kesken siihen, että on pitänyt tarkistaa onko käyttämämme signumbuilder loc_084a_mainheading_signum_builder.pl käytössä muilla. Jos tuo on käytössä muilla, niin voisiko Vaskille tehdä oman version ilman tuota 130a-kenttää tai jos tuo ei ole muilla käytössä, niin muutoksen varmaan voisi tehdä suoraan tuohon builderiin?

**Comment by AnneliO** [comment]
Pääsääntöisesti liitännäiset tehdään kaikille yhteisiksi, ei kimppakohtaisiksi. Nykyäänhään kaikki signum-liitännäiset tarkistavat ensin 942m-kentän, joten voisiko näissä tapauksissa pääsanan kirjata kyseiseen kenttään? Liitännäismuutoksen jälkeen sitä on suositeltukin tehtäväksi.

**Comment by MikkoLiimatainen** [comment]
Eikö kuitenkin olisi järkevämpää käyttää tuota 942m-kenttää niissä harvoissa tapauksissa, kun signum halutaan muodostaa 130a-kentän perusteella? Eikö se nimenomaan ole poikkeavaa pääsanaa varten? Nyt 942m-kenttää jouduttaisiin käyttämään useimpien ulkomaisten elokuvien kohdalla sen sijaan, että sitä käytettäisiin vain Raamattujen ja muunkielisten Kalevaloiden kohdalla. Vaskin luetteloijien mukaan 245a-kenttä on paljon useammin käytetty kenttä signumissa kuin 130a-kenttä, joten olisi loogisempaa pitää tuota 130a-kentän perusteella tehtävää signumia poikkeuksena, joka laitettaisiin 942m-kenttään. Nyt luetteloijat joutuvat tekemään paljon ylimääräistä työtä, jota voitaisiin vähentää poistamalla 130a-kentän käyttö signumbuilderista, jolloin ei tarvitsisi käsin lisätä 942m-kenttää läheskään yhtä monelle tietueelle.

**Comment by AnneliO** [comment]
Pyydän Heikkisen Anttia lisäämään tämän kuvailuryhmän esityslistalle keskusteltavaksi. Olen edelleen sitä mieltä, että jos tehdään muutos, niin se tehdään sitten kaikille. :)

**Comment by AnttHeik** [comment]
Jos signum tulisi 942m-kentästä 130-kentän tiedon perusteella, niin mistä nimeke poimittaisiin 130a-kentästä vai 245a-kentästä?

**Comment by AnneliO** [comment]
Kuvailuryhmä kokoontui 14.12.2022 ja oli sitä mieltä, että 130-kentän voi tiputtaa signumbuildereista kokonaan pois. Siitä kentästä tarvitaan paljon harvemmin tietoja kuin kentästä 245.

**Comment by lasse-koha** [comment]
Jätin uuden Koha-version signum buildereistä kentän 130a pois, nykyisessä on vielä mukana.
