### ISSUE TITLE
Virhe 500 -ilmoitus palautuksessa tai niteen tallennuksessa, uusi yritys menee läpi normaalisti

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#290]
### Mikä vikana?

Vaskissa on satunnaisesti tullut käyttäjiltä raporttia virhe 500 -ilmoituksesta palautuksessa. Osa on selittynyt esim. sillä, että niteen tietueeseen kohdistuu varaus jolta puuttuu noutopaikka, mutta osaan ei ole keksitty selitystä ja tapauksissa virheilmoitus ei ole myöskään toistunut enää nidettä uudelleen palauttaessa.

Palautuksen ohella virheilmoitukseen on törmätty niteen tallennuksessa, silloinkin uusi tallennusyritys on mennyt normaalisti läpi.

Nyt hiljattain raportoitiin jälleen virhe 500 -ilmoituksesta palautuksessa. Kyseessä oli tietueen 4250815 nide 2864099, josta tuli palautuksessa 28.11.22 klo 13:53:05 virheilmoitus. Uusi palautus klo 13:56:38 meni läpi normaalisti. Kun tutkin lokeja, näytti käyneen niin, että ensimmäinen palautusyritys palautti niteen asiakkaan lainoista mutta vasta toinen palautuskerta kiinnitti niteen jonossa olevaan varaukseen.

Tutkin vielä tietueen tapahtumia ja ainoa, mikä pisti silmään, oli tietueeseen TäTistä valuneet päivitykset 22.11. ja 26.11. Tuon 26.11. tapahtuneen valutuksen jälkeen ensimmäinen palautuksessa käsitelty nide oli nimenomaan nide 2864099. Tämän havainnon myötä katselin vielä, miten tietueen niteet ovat 22.11. tapahtuneen valutuksen jälkeen liikkuneet ja käyttäytyneet. Lokien perusteella tällöinkin on ensimmäisenä palautunut nide (2863957) jouduttu palauttamaan kahdesti (25.11.22 klo 12:52:40 & 12:58:33). Tuossakin tapauksessa vasta jälkimmäinen palautus on kiinnittänyt niteen jonossa olevaan varaukseen.

Tallennuksessa tulleista virheilmoituksista löysin yhden tapauksen, josta meille oli ilmoitettu nidetunnus. Kyseessä oli itemnumber 2345014 ja epäonnistunut tallennus tapahtunut 3.8.2022. Lokeissa näkyi yksi niteen muokkaus klo 13:03, joten epäonnistunut tallennusyritys ei ilmeisesti ollut lokittunut. Tietueeseen oli valunut päivitys 23.7., mutta sen jälkeen oli kyllä ehditty jo uusia, palauttaa ja lainata tietueen niteitä. Eli tuossa tapauksessa ei kyllä vaikuttaisi, että tietueeseen tulleella päivityksellä olisi mitään tekemistä virheilmoituksen kanssa.

Pystyyköhän tätä yhtään enempää tutkimaan? Vaikea sanoa minkä verran virheilmoitusta ylipäätään esiintyy, sillä veikkaan etteivät käyttäjät yleensä niistä raportoi jos uudelleenyritys on korjannut tilanteen.

**Comment by ajrajala** [comment]
Nyt tuli omalla kohdalla ensimmäistä kertaa vastaan virhe 500 palautuksessa. Niteen 1231447 palautus antoi 2022-12-19 12:37:59 virheilmoituksen, 10 sekuntia myöhemmin uudelleen palautettaessa virheilmoitusta ei tullut. Ko. tietueelle ei ainakaan näytä tulleen mitään muutoksia, joten ilmeisesti teoria virheilmoituksen liittymisestä tietueen päivittymiseen ei ainakaan päde.

Voiko noissa olla joku hetkellinen häiriö, ettei palautus/niteen tallennus onnistu hakemaan nimekkeen tietoja tms ja siksi tulisi virheilmoitus?

**Comment by emta001** [comment]
Tällainen virheilmoitus löytyi lokeilta:

`[2022-12-19 12:38:01.10113] [2361548] [warn] OpenAPI >>> POST api/v1/checkouts/5242396/renewal [{"message":"Missing property.","path":"\/errors"}]`

Sitä on seurannut muutama ElastiSearch virhe, jotka voi toki liittyä myös toiseen ongelmaan.

`[Bad response received when submitting request to Elasticsearch][Bad response received when submitting request to Elasticsearch][Bad response received when submitting request to Elasticsearch]`

**Comment by ajrajala** [comment]
Tiedoksi pari tuoretta tapausta siltä varalta jos ne jotain hyödyttävät selvittelyssä:

itemnumber 1965588 -> virhe 500 ensimmäisellä palautusyrityksellä 2023-01-17 13:41:06. Nimekkeeseen kohdistui varaus, lokien mukaan näyttäisi että kiinnittyi siihen vasta jälkimmäisellä palautuskerralla (palautettu uudelleen 2023-01-17 13:42:27, old_reserves-taulussa varauksen timestamp 2023-01-17 13:42:30).

itemnumber 2760403 -> virhe 500 ensimmäisellä palautusyrityksellä 2023-01-17 13:54:52.

**Comment by AnneliO** [comment]
Liittyisköhän tämä yhteisön tiketti ongelmaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29856

**Comment by AnneliO** [comment]
Elasticsearchin asetuksissa on mahdollista säätää cxn_pool-asetuksia. https://github.com/elastic/elasticsearch-perl/blob/master/lib/Search/Elasticsearch.pm#L305

**Comment by AnneliO** [comment]
Vieläkö näitä ilmoituksia on tullut?

**Comment by ajrajala** [comment]
Erikseen ei ole ilmoiteltu, kyselin henkilökunnalta vielä Teamsissä näiden virheilmoitusten perään. Yhdestä kirjastosta muisteltiin, että pari kertaa kesän aikana olisi tullut virheilmoitus kirjojen palauttamisen yhteydessä, mutta eivät muistaneet varmaksi oliko kyse juuri virhe 500 -viestistä vai jostain muusta.

Ehkä tämä kannattaa tällä erää sulkea ja avata uudelleen, jos näitä taas ilmaantuu?

**Comment by AnneliO** [comment]
Jeps, suljetaan vaan.
