### ISSUE TITLE
Eräpäiväkalenterien ylimääräisten sulkupäivien poisto tietokannasta

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#291]
### Tukipyyntö

OUTIssa huomattiin, että tietokannan päässä saattoi olla kirjastojen kalentereiden sulkupäivät useampaan kertaan. Kohassa sulkupäivät näkyivät vain kerran, mutta sulkupäivien poistotilanteessa poistot piti tehdä niin monta kertaa, kuin ne olivat tietokannan päässä. 

Ylimääräiset sulkupäivätiedot pitäisi poistaa ainakin OUTIlta, mutta muiltakin kimpoilta pitäää tarkistaa, onko ylimääräisiä sulkupäiviä tietokannan päässä ja poistaa ne tarvittaessa.

Syytä ylimääräisien sulkupäivien syntyyn ei ainakaan vielä hoksattu.

**Comment by emta001** [comment]
Muistelisin, että näitä pääsee syntymään esimerkiksi silloin, kun tehdään sulkupäiviä tietylle aikavälille ja sillä välillä sattuu olemaan jo sulkupäiviä. Kohan kalenteri on tässä hieman tönkkö, ettei se osaa tarkistaa onko päivälle jo sulku vai ei. Kannassa ei edes voida periaatteessa vaatia, että arvot ovat uniikkeja koska päivämäärän eri osta (päivä, kuukausi ja vuosi) tallennetaan kukin omaan sarakkeeseen. Oliskohan tämä mahdollista myös silloin kun kopioidaan toisen kirjaston kalenteri toiseen kirjastoon?

**Comment by emta001** [comment]
Näillä saa tutkailtua sulkupäivien tuplat:
`SELECT a.* FROM repeatable_holidays a JOIN (SELECT branchcode, weekday, day, month, COUNT(*) FROM repeatable_holidays GROUP BY branchcode, weekday, day, month HAVING count(*) > 1) b ON a.branchcode = b.branchcode AND ( a.weekday = b.weekday OR (a.day = b.day AND a.month = b.month)) ORDER BY a.branchcode, a.weekday, a.day, a.month;`

`SELECT a.* FROM special_holidays a JOIN (SELECT branchcode, day, month, year, isexception, COUNT(*) FROM special_holidays GROUP BY branchcode, day, month, year, isexception HAVING count(*) > 1) b ON a.branchcode = b.branchcode AND a.day = b.day AND a.month = b.month AND a.year = b.year AND a.isexception = b.isexception ORDER BY a.branchcode, a.day, a.month, a.year;`

**Comment by emta001** [comment]
Ja tämmösillä saa tuplat pois:

`DELETE a FROM repeatable_holidays a INNER JOIN repeatable_holidays b WHERE a.id < b.id AND a.branchcode = b.branchcode AND ( a.weekday = b.weekday OR (a.day = b.day AND a.month = b.month));`
`
DELETE a FROM special_holidays a INNER JOIN special_holidays b WHERE a.id < b.id AND a.branchcode = b.branchcode AND a.day = b.day AND a.month = b.month AND a.year = b.year AND a.isexception = b.isexception;`

Ajelen nuo kaikille kimpoille tässä tämän päivän aikana. Nappaan varuiksi vielä vanhat arvot aputauluihin.

**Comment by emta001** [comment]
Ajot tehty kaikille kimpoille.

**Comment by pirliis** [comment]
Kiitos!
Tein nyt testillä tuplaylityksiä kalentereihin. Ainakaan raportit eivät enää antaneet mitään tulosta eli voisimmeko tästä päätellä, että virhe on ollut aiemmissa versioissa. :)
