### ISSUE TITLE
Not for loan -tila TUVR-yksikön niteille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#292]
### Tukipyyntö

Varissuon kirjasto (TUVR) menee kolmeksi kuukaudeksi kiinni ja siellä hyllyssä oleville niteille pitäisi asettaa notforloan tila '4'. Muutoksen tulisi siis koskea niteitä, jotka täyttävät nämä ehdot:
- holdingbranch = TUVR
- nide ei ole lainassa, noudettavissa tai kuljetettavana
- niteellä ei ole entuudestaan mitään notforloan-tilaa

Muutos haluttaisiin tehtävän heti joulun jälkeen 27.12.

**Comment by paxed** [comment]
21221 kpl niteitä muutettu notforlaon = 4, tällä rimpsulla:
`update items i left join reserves r on (i.itemnumber=r.itemnumber) set i.notforloan = 4 where i.holdingbranch = 'TUVR' and i.notforloan = 0 and i.onloan is null and r.found is null;`

**Comment by ajrajala** [comment]
Kiitos! Nähdäkseni muutos on ok, joten suljen tiketin.
