### ISSUE TITLE
Vaski: okm-tilastovääristymän korjaaminen

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#295]
### Tukipyyntö

Koska okm-tilastointi käsittääkseni käyttää 084a-kentän ensimmäisen ilmentymän tietoja aineiston ryhmittelyyn tieto-, kauno- ja musiikkiaineistoksi, on tilastoissa havaittavaa heittoa. Vaskissa on esim. yli 9000 tietuetta, jotka ryhmitellään muuhun kuin fiktioon, vaikka tietueiden niteistä suurin osa on luokitukseltaan fiktiota. Olisikohan mahdollista tarkastella tarkemmin näitä 084a-kenttien arvoja ja mikäli niissä on ristiriitaisuutta voitaisiin tarkastella tietueen niteiden luokkia ja tehdä ryhmittely sen mukaan mitä ryhmää niteistä suurin osa edustaa? Vai onko tietueiden 084a-kenttien muokkaaminen ainoa keino korjata tilastovääristymä?

**Comment by emta001** [comment]
Tässä tapauksessa tietueiden korjaaminen on ainut keino korjata vääristymä, sillä kyseessä on selkeästi virhe kuvailutiedoissa. Oletettavasti niteetkin olisi korjattava. Se kuinka nämä korjataan, onkin sitten asia erikseen, käsin tuollaisen määrän korjaaminen on aikamoinen urakka. Onko Vaskilla siis olemassa tästä jonkinlainen raportti?

**Comment by MikkoLiimatainen** [comment]
Ok. No sitten sitä täytynee vain tehdä käsityönä tätä. Tuolla on joitakin tilanteita, jotka voisi ehkä tehdä ajolla työn helpottamiseksi, mutta niitä täytynee tarkastella hieman tarkemmin. Olen tehnyt tilanteesta analyysiä tällaisen raportin avulla:
`SELECT *
FROM (SELECT bde.*,
    bi.cn_class AS bi_cn_class,
    IF(SUM(IF(LEFT(i.cn_sort, LOCATE(' ',i.cn_sort)-1) REGEXP '^8[0-5].*', 1,0))>SUM(IF(LEFT(i.cn_sort, LOCATE(' ',i.cn_sort)-1) NOT REGEXP '^8[0-5].*', 1,0)), 1, 0) AS Fiktio
FROM koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde
LEFT JOIN biblioitems bi ON bi.biblioitemnumber=bde.biblioitemnumber
JOIN items i ON i.biblioitemnumber=bde.biblioitemnumber
WHERE bi.cn_class NOT REGEXP '^8[0-5].*'
    AND bi.cn_class REGEXP '\\s8[0-5]\\S*'
GROUP BY bde.biblioitemnumber ASC) apu
WHERE fiction=0 AND Fiktio=1`

**Comment by lmstrand** [comment]
Raportilla muissa kimpoissa tuloksia:
Vaara 110 kpl
Siili 12 kpl
Outi 94 kpl
Lappi 120 kpl
Kyyti 469 kpl
Helle 496 kpl
Lumme 304 kpl

**Comment by MikkoLiimatainen** [comment]
Selvästi suurin osa noista meidän virheellisistä näyttää olevan sellaisia, että niissä on ensimmäisenä 084a-ilmentymänä jokin vanha sijainti, kuten Jännitys tai Novellit. Täytyy varmaan luetteloijilta tarkistaa ovatko samaa mieltä, mutta onko teknisesti mahdollista poistaa ajolla kaikki 084a-ilmentymät, joissa on vain kirjaimia? Sanoisin, että ainakin kaksi kolmasosaa virheellisistä tietueista korjaantuisi tällä.

**Comment by paxed** [comment]
> Täytyy varmaan luetteloijilta tarkistaa ovatko samaa mieltä, mutta onko teknisesti mahdollista poistaa ajolla kaikki 084a-ilmentymät, joissa on vain kirjaimia?

On teknisesti ihan mahdollista - valmista ohjelmanpätkää siihen ei ole, mutta sellaisen tekeminen ei ole mikään iso homma. Kunhan vain on hyvin määritelty miten kenttien sisältöä muokataan.

**Comment by MikkoLiimatainen** [comment]
Luetteloijamme eivät pitäneet ajatuksesta, että luettelointitietoa poistettaisiin. Olin itse siinä käsityksessä, että nuo ovat jotain vanhaa tarpeetonta tietoa, mutta näin ei olekaan. Lisäksi näitä luettelointitietoja valuu tietokantaan niin, että niissä ovat nuo aiheluokat ensimmäisinä, joten näitä tulee olemaan jatkossakin. Siksi ajattelimme, että voisi olla kätevintä, että OKM-raportointityökalu ohittaisi kaikki 084a-ilmentymät, jotka alkavat kirjaimella ja jakaisi tietueet kaunoon, tietoon ja musiikkiin tietueen ensimmäisen numerolla alkavan 084a-ilmentymän perusteella.

Mikäli raportointityökalua ei voida noin muuttaa, niin sitten korjaustoive olisi, että kirjaimella alkavat 084a-ilmentymät siirrettäisiin numerolla alkavien ilmentymien perään. Kunhan numeeristen järjestys keskenään säilyy, niin silloin tämä näyttäisi antavan suurimmaksi osaksi oikeat luokat raportointityökalun käyttöön. Tässä ratkaisussa pitää varmaankin varmistaa myös, että tietueiden biblioitems-taulun cn_class- ja cn_sort-sarakkeet päivitetään. Tästä olisi varmaan hyötyä Kohan muihinkin toimintoihin, joten korjaus voisi olla hyvä tehdä raportointityökalun muutoksesta riippumatta.

**Comment by AnttHeik** [comment]
Sanoit Mikko, että noita tietueita valuu edelleen. Olisiko sinulla heittää jotain esimerkkitietuetta tällaisesta tapauksesta? Kiinnostais nähdä, onko näissä jotain systeemiä taustalla.

**Comment by MikkoLiimatainen** [comment]
[https://vaski.finna.fi/Record/vaski.4264019](https://vaski.finna.fi/Record/vaski.4264019) Tähän tietueeseen on tuo Kauhu-luokitus valunut 30.8.2022. Käytännössä tämä on ainoa hiljattain valunut tapaus, jonka raporttini sai kiinni. Jos näitä on valumisen jälkeen korjailtu, niin silloin niitä ei raportilleni tule. Ei siis vaikuta mitenkään isolta asialta, mutta luetteloijamme olivat panneet merkille, että näin ajoittain tapahtuu.

**Comment by AnttHeik** [comment]
Kiitokset, eli kyseessä Kirjastopalvelun tietue vuodelta 2014. Heidän olisi tuo pitänyt aikoinaan korjata. Pistää miettimään, että onko ollut enempi ongelma joskus aiemmin kuin että vielä nykyäänkin tapahtuisi tuota kenttien laittamista väärään järjestykseen. @AnneliO saisiko meille OUTIsta tällaisen samanlaisen raportin noista 94:stä tietueesta, jotka Lari oli löytänyt?

**Comment by AnneliO** [comment]
@AnttHeik Mikon raportti on nyt OUTIn tuotannossa https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=594&phase=Run%20this%20report

**Comment by AnneliO** [comment]
Lisäsin myös Tätiin tällaisen kyselyn:

> select CONCAT('<a href=\"/cgi-bin/koha/catalogue/detail.pl?biblionumber=',biblionumber,'" target="_blank">',biblionumber,'</a>') as 'Tietue',cn_class as 'Luokka' from biblioitems where cn_class regexp '^[A-Ö]'

https://tati.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=243&phase=Run%20this%20report#

**Comment by MikkoLiimatainen** [comment]
> Luetteloijamme eivät pitäneet ajatuksesta, että luettelointitietoa poistettaisiin. Olin itse siinä käsityksessä, että nuo ovat jotain vanhaa tarpeetonta tietoa, mutta näin ei olekaan. Lisäksi näitä luettelointitietoja valuu tietokantaan niin, että niissä ovat nuo aiheluokat ensimmäisinä, joten näitä tulee olemaan jatkossakin. Siksi ajattelimme, että voisi olla kätevintä, että OKM-raportointityökalu ohittaisi kaikki 084a-ilmentymät, jotka alkavat kirjaimella ja jakaisi tietueet kaunoon, tietoon ja musiikkiin tietueen ensimmäisen numerolla alkavan 084a-ilmentymän perusteella.
> 
> Mikäli raportointityökalua ei voida noin muuttaa, niin sitten korjaustoive olisi, että kirjaimella alkavat 084a-ilmentymät siirrettäisiin numerolla alkavien ilmentymien perään. Kunhan numeeristen järjestys keskenään säilyy, niin silloin tämä näyttäisi antavan suurimmaksi osaksi oikeat luokat raportointityökalun käyttöön. Tässä ratkaisussa pitää varmaankin varmistaa myös, että tietueiden biblioitems-taulun cn_class- ja cn_sort-sarakkeet päivitetään. Tästä olisi varmaan hyötyä Kohan muihinkin toimintoihin, joten korjaus voisi olla hyvä tehdä raportointityökalun muutoksesta riippumatta.

Olisiko näistä ajatuksista jokin toteutettavissa? Olisi hyvä, jos tämän vuoden tilastot saataisiin oikein, joten nämä olisi hyvä saada jollain tavalla kuntoon ennen OKM-tilastojen ottamista.

**Comment by MikkoLiimatainen** [comment]
Tähän on siis korjaus työn alla @paxed:lla. Korjauksessa pyritään siirtämään tietueessa ensimmäisenä esiintymänä olevat kirjaimella alkavat 084a kentät järjestyksessä viimeiseksi, jolloin ensimmäiseksi ilmentymäksi tulee numeerinen luokka, jonka avulla tieto/kauno jaottelu pystytään tekemään.

**Comment by MikkoLiimatainen** [comment]
OKM-tilastot muodostetaan jatkossa niteen luokan perusteella, joten tälle korjaukselle ei ole enää tarvetta.
