### ISSUE TITLE
Vaara: Itsepalvelulainus unohtaa virkailijan(automaattitunnuksen) kirjautumisen 

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#297]
### Mikä vikana?

SCO itsepalvelulainaus on kirjautunut ulos virkailijatunnuksista vuorokauden vaihtuessa.
Ongelma ratkaistu Outissa ohjelmalla, joka tarkkailee kirjautumisikkunaa ja uudelleenkirjautuu tarvittaessa virkailijatunnuksin asiakasnäkymään.

### Mitä pitäisi tapahtua

Kirjautuminen/sessio ei sais vanhentua.

### Selain

```markdown
Kaikki
```

**Comment by lmstrand** [comment]
Koodin tehty muutoksia testeille. Testattava, pysyykö virkailijan kirjautuminen voimassa vuorokauden yli.

**Comment by lmstrand** [comment]
Testissä pitäisi kirjautua myös asiakastunnuksella virkailijatunnuskirjautumisen jälkeen, jolloin kirjatumiskeksi saa 400 vuorokauden pituisen voimassaoloajan selaimeen. Keksin voimassaolon voi tarkastaa selaimen inspect-toiminnolla.

**Comment by lmstrand** [comment]
Testeille lisätty (paikallisesti) koodimuutos, jonka pitäisi estää uloskirjautuminen itsepalvelulainuksen asiakasnäkymästä perustuen asiakasnäkymään kirjautuvan tunnuksen asiakastyyppiin (pitää alkaa kirjaimilla 'AUTO').

**Comment by IrinaHalminen** [comment]
Jätän tähän työkoneelle yöksi testiin.

**Comment by lmstrand** [comment]
Tämä uloskirjautumisongelma on niin laajasti läsnä itsepalvelulainauskeen käytettävässä koodissa,, että muutos pitää tehdä ajan kanssa yhteisössä. Suosittelin Vaaraa kiertämään ongelman kirjautumisavustajasovelluksella/toteutuksella kuten Outissa on tehty.

**Comment by IrinaHalminen** [comment]
Minäpä suljen tämän. Yritetään muuten kierrellä asia.
