### ISSUE TITLE
Omatoimen käyttökielto asiakkaalle

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#298]
### Tukipyyntö

Tukipyyntö

"Sovitulle" asiakkaalle asetetaan omatoimen käyttökielto kirjastoon HVE_HVE (Heinäveden kirjasto) ajalle 2.12.2022-31.12.2022.
Päätöksen tekijä: Heinäveden kirjaston va. kirjastotoimenjohtaja

Lari hoitaa.

Koha-tuki laittaa tiedon käyttökiellosta asiakkaan Viesti-osioon.

**Comment by lmstrand** [comment]
Lisätty:
```
insert into borrower_ss_blocks (borrowernumber, branchcode, expirationdate, notes, created_by, created_on) values ('xxxx', 'HVE_HVE', '2022-12-31 00:00:00', 'Heinäveden kirjaston va. kirjastotoimenjohtaja', 'xxxx', now());

**Comment by lmstrand** [comment]
Asiakkaan käyttökielto poistettu automaattisella ajolla. Asiakkaan tietoihin mahdollisesti lisätty viesti pitää poistaa käsin. Näin toimittava kunnes käyttökieltojen purkuskriptiin lisätään toiminnallisuus, joka osaa poistaa myös kyseiset huomautukset.
