### ISSUE TITLE
Eräpäivämuistutusten viestipohjiin PREDUEDGST ja DUEDGST tiedoksi myös kirjasto, josta nide on lainattu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#299]
### Kehitysehdotukseni

Saisiko eräpäivämuistutusviestien viestipohjiin määriteltyä tiedon kirjastosta, josta nide/niteet on lainattu. Lainaajakirjaston lisäystarve koskee viestipohjia PREDUEDGST ja DUEDGST

Ko. viestipohjissa käytetään määritystä <<items.content>> joka tuo viestiin nämä tiedot (tähän tyyliin):
lainausajankohta nimeke / tekijä, nidetunnus

esim.
28.11.2022 23:59 Saatan olla väärässä ja muita oivalluksia elämästä / Lindeblad, Björn Natthiko, 71000138874

Tieto lainaajakirjastosta auttaisi mm. siihen, että huoltajalle menevästä huollettavan/lapsen lainoja koskevasta viestistä näkee/erottaa  koulukirjastosta lainatut erääntyvät lainat.

Viestipohjien määritys -toiminto: Tools/Notices & slips

**Comment by AnneliO** [comment]
items.content-tägiin pystyy cronissa määrittämään mukaan tietoja biblio-, items- ja issues-taulusta kertoo yhteisön [Customising Notices ja Slips](https://wiki.koha-community.org/wiki/Customising_Notices_and_Slips) -wiki.

"Any column from biblios, items and issues tables may be used in --itemscontent."

issues-taulusta voisi periaatteessa poimia branchcoden, mutta se olisi silloin ymmärtääkseni ihan koodimuodossa, ei auki kirjoitettuna tietona.

**Comment by AnneliO** [comment]
#773 -tiketissä pohdittu myös items.content-tägin sisältöä.

**Comment by Kati-Helle** [comment]
> items.content-tägiin pystyy cronissa määrittämään mukaan tietoja biblio-, items- ja issues-taulusta kertoo yhteisön [Customising Notices ja Slips](https://wiki.koha-community.org/wiki/Customising_Notices_and_Slips) -wiki.
> 
> "Any column from biblios, items and issues tables may be used in --itemscontent."
> 
> issues-taulusta voisi periaatteessa poimia branchcoden, mutta se olisi silloin ymmärtääkseni ihan koodimuodossa, ei auki kirjoitettuna tietona.

Kiitos Anneli tiedosta. Asiakkaalle kirjaston tunnus ei kertone mitään...

**Comment by AnneliO** [comment]
Auttaiskohan, jos itse viestitekstiin laittaa jotain tyyliin 

```Lainanne <<issues.branchcode>>sta on erääntymässä/erääntyy```

**Comment by Kati-Helle** [comment]
Tuosta olisi apua.
Entäpä jos eräpäivämuistus-viesti sisältää useamman kuin yhden lainaajakirjaston lainoja?

**Comment by AnneliO** [comment]
Sitten se varmaan antaa vain yhden kirjaston tiedot. Pystyisitkö jotenkin testaamaan tuota?

**Comment by Kati-Helle** [comment]
Lisäsin testausta varten Helle-testin suomenkielisiin sähköpostiviesteihin:

PREDUEDGST
Lainanne <<issues.branchcode>>sta on erääntymässä

DUEDGST
Lainanne <<issues.branchcode>>sta on erääntyy

Asiakkaat

Lapsiasiakas ID 127878
- yksi koulukirjastosta Z Huhtisen koulukirjasto lainattu laina, jonka eräpäivänä huominen 15.9.2023

Takaajansa asiakas ID 127867
- yksi Porvoon pääkirjastosta ja yksi Gammelbackan kirjastosta lainattu laina. Molempien eräpäivä huominen 15.9.2023.

Molempien asiakastietojen viestiasetukset
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/aa814954-e669-40d2-a96f-eb595098b1ee)

Molempien asiakastietojen sähköposti-kentässä minun sähköpostiosoite.

**Comment by Kati-Helle** [comment]
Kiitos @lmstrand kun laitoit viestit muodostumaan.

Viesteihin ei muodostunut lainaajakirjasto-tietoa.

Viesi lapsiasiakkaan ID 127878 Ilmoitukset-välilehdellä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9e8b2da7-10b3-4559-9b9d-cfd8d180d039)

Viesti takaajan ID 127867 Ilmoitukset-välilehdellä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0a7d2243-885c-48f6-af64-f9eef0e0db9c)

**Comment by lmstrand** [comment]
Yhteisössä on tehty muutos koskien myös näitä viestipohjia. Muutos sallii monipuolisemmat viestipohjan muokkausmahdollisuudet, mutta ei taida tuonkaan muutoksen avulla saada lainanneen kirjaston koko nimeä viestiin.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29100

**Comment by lmstrand** [comment]
Tai ehkä saa sittenkin kun tätä dokumenttia katsoo:
https://wiki.koha-community.org/wiki/Notices_with_Template_Toolkit

**Comment by Kati-Helle** [comment]
Testiasiakas ID 127867 - kaksi samaeräpäiväistä lainaa kahdesta eri kirjastosta.
Viestejä muodostunut kaksi. viestit sisältävät molemmista kirjastoista lainatut teokset. Viesteissä on vain yksi, toisistaan poikkeava lainaajakirjastotieto eli viesteissä ei mainita molempien lainojen lainaajakirjastoa.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2e446de4-ceb5-4711-b418-3b01954d2142)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f66d3465-c170-4af8-a3c8-a71151eef89c)

**Comment by lmstrand** [comment]
Yhteisöstä löytyi ongelmaan bugikorjaus:
Bug 34059: Add only issues from the branch that is creating the notice. Otetaan tuo mukaan testille ja kokeillan sitten uusiksi.

**Comment by Kati-Helle** [comment]
Helle-testissä asiakkaalla ID 127878 on tänään 15.9.2023 kaksi eri kirjastosta lainattua lainaa. Lainojen eräpäivänä huominen 16.9.2023

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/8547d81c-3bfd-40ea-8208-60498577a8d1)

**Comment by lmstrand** [comment]
Vein testille yhteisön korjauksen. Riippuvuuksista jäi puuttumaan tämä patch: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33900 mutta ei näyttänyt aiheuttavan ongelmia. Ehkäpä tuo pitäisi vielä varmuuden vuoksi ottaa kyytiin ennenkuin harkitsee tuotantoon siirtoa.

Helle-testiin ajettu myös advance_notices.pl noilla uusilla vivuilla.

Miltä viestit nyt näyttävät?

**Comment by Kati-Helle** [comment]
Lainaajakirjasto näkyy nyt :)

Asiakas ID 127878

15.9.2023 on muodostunut molempien kirjastojen lainoista oma PREDUEDGST-viesti (eräpäivä lähestyy). Kummassakin viestissä on mainittu oikea lainauskirjasto.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/aa45c05e-4329-4f43-94e5-8f82c11dd135)


![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/833652ca-48e4-413d-a101-19c80e00f891)

**Comment by Kati-Helle** [comment]
Tiedoksi vielä, että 16.9.2023 muodostuneissa DUEDGST-viesteissä (eräpäivä on tänään) ei näy lainaajakirjastoa. Teksti on tyyliin: Lainanne sta erääntyy

**Comment by AnneliO** [comment]
Puuttuko nyt DUEDGST-pohjasta nuo PREDUEDGST-pohjaan tehdyt muutokset?

**Comment by AnneliO** [comment]
> Puuttuko nyt DUEDGST-pohjasta nuo PREDUEDGST-pohjaan tehdyt muutokset?

@Kati-Helle tää kysymys taisi olla sinulle suunnattu. :)

**Comment by Kati-Helle** [comment]
> > Puuttuko nyt DUEDGST-pohjasta nuo PREDUEDGST-pohjaan tehdyt muutokset?
> 
> @Kati-Helle tää kysymys taisi olla sinulle suunnattu. :)

Joo, DUEDGST-pohjasta puuttuu niteen lainaajakirjasto Helle-testissä tehtyjen testien perusteella. 

Asiakkaan borrowernumber=127878 ja DUEDGST-viestit 16.9.2023

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/3255a75c-64e2-4ab1-9db3-5e260f1e068b)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9fa19001-e4bb-45f5-8357-73fdebf5ac34)

**Comment by AnneliO** [comment]
Koitan tässä selaille kuvia, niin onko tuo kirjastotieto näkynyt vielä kertaakaan oikein DUEDGST-viesteissä? Vai vain PREDUEDGST-viesteissä?

**Comment by Kati-Helle** [comment]
> Koitan tässä selaille kuvia, niin onko tuo kirjastotieto näkynyt vielä kertaakaan oikein DUEDGST-viesteissä? Vai vain PREDUEDGST-viesteissä?

DUEDGST-viesteissä kirjastotietoa ei ole näkynyt ainakaan Helle-testissä.

PREDUEDGST-viesteissä on lainaajakirjasto näkynyt oikein ja niin, että kun testin kahdella lainalla on sama eräpäivä mutta eri lainaajakirjastot, on muodostunut kaksi lainaajakirjastokohtaista viestiä. Tämän tiketin kommentti:
https://github.com/KohaSuomi/Koha/issues/299#issuecomment-1722748855

**Comment by lmstrand** [comment]
<<branches.branchname>> -määrityksellä toimi DUEDGST-pohjassa kirjastotieto Vaara-testillä.

**Comment by lmstrand** [comment]
Hellen tuotannossa ei siis ole advance_notices.pl -croniajoon määritetty sitä digest-per-branch -vipua jolla kirjastotiedot välittyvät noille pohjille ja niistä luodaan erilliset mailit per yksikkö. Jos haluatte ominaisuuden tuotantoon, pitää se muuttaa samalla kuin viestipohjat muutetaan (kirjastotiedot sisältäviksi). Pohjissa ei nyt näyttänyt tietoja menevän.

**Comment by Kati-Helle** [comment]
> Hellen tuotannossa ei siis ole advance_notices.pl -croniajoon määritetty sitä digest-per-branch -vipua jolla kirjastotiedot välittyvät noille pohjille ja niistä luodaan erilliset mailit per yksikkö. Jos haluatte ominaisuuden tuotantoon, pitää se muuttaa samalla kuin viestipohjat muutetaan (kirjastotiedot sisältäviksi). Pohjissa ei nyt näyttänyt tietoja menevän.

Kiitos Lari tiedosta.
Sopiiko että ilmoitan, kun eräpäivämuistutuksissa lainaajakirjastotiedot välittävän vivun voi laittaa Helleen käyttöön?

**Comment by lmstrand** [comment]
Joo, ilmoita vaan kun on tarve muuttaa tuotantoon. Viestit muodostetaan aamuisin klo. 9.23, joten pelivaraa voisi olla vähän, vaikka edellispäivänä kun ilmoittaa (tai miksei voisi sopia etukäteen aiemminkin :) ).

**Comment by Kati-Helle** [comment]
Hellen osalta on nyt tiedossa, miten tieto lainaajakirjastosta tulee lisätä viestiin.
Mikä olisi Lari sinulle sopiva ajankohta tämän Helle-toteutukseen?

**Comment by lmstrand** [comment]
Sopiiko jos huomisaamuna teen cron-vipumuutoksen?

**Comment by Kati-Helle** [comment]
@lmstrand Tiistai-aamu 6.2.2024 sopii kyllä.
Lisään nyt viestipohjiin tarvittavat tiedot.

**Comment by lmstrand** [comment]
Lisätty cron-vipu tuotantoon.
