### ISSUE TITLE
Nimekkeettömät tilaukset tilauskorissa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#300]
### Mikä vikana?

Kirjastossa oli törmätty tilausten vastaanotossa tilauksiin, joilta puuttui nimeke ja joiden peruutus-yrityksestä tulee virhe 500 -ilmoitus (kuvakaappaus tilausten vastaanotto -näkymästä liitteenä).

Kun katselin kyseistä [tilauskoria](https://vaski.koha-suomi.fi/cgi-bin/koha/acqui/basket.pl?basketno=4), huomasin että samat tilausrivit näkyivät jo siellä peruutettuina ja nimekkeen tilalla oli tieto "Poistettu bibliografinen tietue, nimekettä ei löydy".

Onko tilauksen peruutus tapahtunut automaattisesti kun tietue on poistettu vai miksi tilausten vastaanotossa tilausrivit kummittelevat edelleen peruutuksesta huolimatta? Pystyykö jostakin selvittämään miten poisto on tapahtunut? (Testasin, että ainakaan tietueiden yhdistäminen ei tällaista aiheuta enkä keksinyt miten ainakaan käyttäjä saisi poistettua tietueen silloin kun siinä on vielä kiinni tilattu-tilaisia niteitä.)

Kirjasto toivoi, että tuolta vastaanotto-näkymästä saisi nuo tilaukset poistettua, joten pystyykö poiston jollain konstilla tekemään? Mietin myös, että jos noihin tilauksiin aikanaan liittyneet nimeke-tiedot pystyy kaivelemaan, niin olisin voinut ne vaikka varuiksi ilmoittaa vielä kirjastolle.

### Jotain muuta?

![kuva](https://user-images.githubusercontent.com/44638512/207320825-508e2c6b-4ea5-4afd-aea3-31723a481877.png)

**Comment by AnneliO** [comment]
Onpas outo tilanne. Katselin tilausten tietoja aqorders-taulusta ja näyttäisi siltä, että tilausriveissä on biblionumber null, mutta orderstatus 'ordered'. Se pitäisi todennäköisesti olla 'cancelled', jotta tilausrivi ei näkyisi vastaanotossa.

select * from aqorders where biblionumber is null and orderstatus='ordered';

Tuolla kyselyllä löytyy Vaskista 104 tilausriviä, joissa on tuo samanlainen tilanne "päällä".

Onko tietue siis poistettu ns. tiedonhaun kautta ennen kuin tilaus on peruttu? 

Testasin Vaskin testillä, miten käy, jos tietueen poistaa perustiedot-näytön kautta ja sain aikaiseksi sellaisen tilanteen, että tilausrivi näkyy vastaanotossa ilman nimekettä. Mutta korissakin se näkyi vastaanotettavien puolella, ei peruttuna. En saanut peruttua tilausta, vaan tuli error 500.

Varoitus tietuetta poistettaessa:
![seriousissues](https://user-images.githubusercontent.com/33121325/207533356-357763dd-99ca-451b-ab19-d52ae8d6b8ad.png)

Näkymä tilauskorissa
![seriousissues2](https://user-images.githubusercontent.com/33121325/207533355-ab423d45-3dcd-4424-9942-93f5098332b0.png)

Näkymä vastaanotossa
![seriousissues3](https://user-images.githubusercontent.com/33121325/207533349-5b9c3d93-9382-4fbf-ac04-2b4ea4c90376.png)

Ihan vastaavaa tilannetta en saanut aikaiseksi ainakaan käyttöliittymän toiminnoilla.

**Comment by IrinaHalminen** [comment]
Törmäsin samaan ongelmaan Vaarassa ja piti laittaa tiketti, mutta Anni ehtikin jo - hyvä. (Meillä oli näitten lisäksi monia vanhoja tilauksia, joitten niteet olivat saapuneet, mutta jääneet tilattu-tilaan. Varmasti uuden työntekijän tultua tullut hetkellinen inhimillinen virhe, jonka bongasin vasta nyt, koska meidän kirjastossamme on tähän saakka suurimmaksi osaksi vain yksi henkilö tehnyt vastaanottoa.)

![kuva](https://user-images.githubusercontent.com/99409279/207539030-39d48bbc-2c60-41f0-87ab-b6f45690e852.png)

**Comment by ajrajala** [comment]
Sain tietueiden eräpoistolla aikaan saman testituloksen kuin Anneli eli sekään ei ilmeisesti selitä tapausta.

Koitin vielä tilauksen perumista ja nimeketietueen poistoa tilauskorista sekä tilausten vastaanotosta käsin. Kummassakaan yhteydessä nimekkeettömät tilaukset eivät jääneet näkyviin tilausten vastaanottoon, tilaukset siirtyivät nimekkeettöminä ainoastaan tilauskorin peruutettuihin tilauksiin.

**Comment by ajrajala** [comment]
Kirjasto muisti, että tilaukset olivat alkujaan 2021 tilauksia jotka siirrettiin vuoden 2022 budjettiin. Mutta eipä tuo siirtokaan näytä alkuperäistä virhetilannetta aiheuttavan kun sitä äsken testillä testasin.

**Comment by emta001** [comment]
Korjaus tehty seuraavasti loitsimalla:

`UPDATE aqorders SET orderstatus = "complete" WHERE datereceived IS NOT NULL AND orderstatus = "ordered";`

Seuraillaan tosiaan syntyykö noita uusia ja tutkitaan sitten, mistä mahtavat johtua.

**Comment by ajrajala** [comment]
Mietin, että pitäisikö ajaa vielä orderstatukseksi cancelled-tila niille tilauksille, joissa biblionumber = null ja orderstatus silti 'ordered? Sillä saisi varmaankin siivottua vastaanottonäkymästä pois alkuperäisen viestin tapaukset?

**Comment by emta001** [comment]
> Mietin, että pitäisikö ajaa vielä orderstatukseksi cancelled-tila niille tilauksille, joissa biblionumber = null ja orderstatus silti 'ordered? Sillä saisi varmaankin siivottua vastaanottonäkymästä pois alkuperäisen viestin tapaukset?

Ohops, tämä jäi huomaamatta, pahoittelut. Äkkiseltään kuulostaisi ihan järkevälle toimenpiteelle, mutta pitänee miettiä hetki ettei mikään mene sekaisin. Esim. onko näitä tapauksia rajattava, voiko siellä olla sellaisia tapauksia joissa tuo tilanne on toivottu.

**Comment by emta001** [comment]
Eipä keksitty tilannetta, jossa tästä ajosta vois olla haittaa. Teen ajon kohtapuoliin.

**Comment by emta001** [comment]
Ajo tehty, koski 106 tilausta.

`UPDATE aqorders SET orderstatus = "cancelled" WHERE biblionumber IS NULL AND orderstatus = "ordered";`

**Comment by Tuomas-Kyyti** [comment]
> `UPDATE aqorders SET orderstatus = "cancelled" WHERE biblionumber IS NULL AND orderstatus = "ordered";`

Saisiko tämän ajon Kyytillekin?

**Comment by emta001** [comment]
> > `UPDATE aqorders SET orderstatus = "cancelled" WHERE biblionumber IS NULL AND orderstatus = "ordered";`
> 
> Saisiko tämän ajon Kyytillekin?

Juu onnistuu.

**Comment by emta001** [comment]
Ajo tehty kaikille kimpoille. Tilauksia muuttui seuraavasti

- Siili 528
- Lumme 665
- Kyyti 266
- Vaara 271
- Lappi 527
- OUTI 1146

**Comment by ajrajala** [comment]
> Ajo tehty, koski 106 tilausta.
> 
> `UPDATE aqorders SET orderstatus = "cancelled" WHERE biblionumber IS NULL AND orderstatus = "ordered";`

Kiitokset, tämä näyttää tepsineen tilausten vastaanottonäkymään toivotulla tavalla. Odotetaanko, että kaikki kimpat kuittaavat ajon olevan ok vai suljenko tämän tiketin..?

**Comment by MikkoLiimatainen** [comment]
Vaskissa on havaittu tilanne, jota tämä korjaus ei ilmeisesti ole korjannut. Korissa [7482](https://vaski.koha-suomi.fi/cgi-bin/koha/acqui/basket.pl?basketno=7482) on ordernumber 77045, jolta puuttuu tietue, mutta se ei ole peruutetuissa. Tilauksen peruutuksen yritys antaa biblionumberin puuttumisen takia error 500.

Aqorders-taulun perusteella tämä näyttäisi kuitenkin olevan sellainen tilaus, jolle on tuossa 22.2. suoritetussa ajossa laitettu orderstatus cancelled.

Bugzillassa näyttäisi olevan tähän liittyvä tiketti [10869](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=10869).

**Comment by emta001** [comment]
> Vaskissa on havaittu tilanne, jota tämä korjaus ei ilmeisesti ole korjannut. Korissa [7482](https://vaski.koha-suomi.fi/cgi-bin/koha/acqui/basket.pl?basketno=7482) on ordernumber 77045, jolta puuttuu tietue, mutta se ei ole peruutetuissa. Tilauksen peruutuksen yritys antaa biblionumberin puuttumisen takia error 500.
> 
> Aqorders-taulun perusteella tämä näyttäisi kuitenkin olevan sellainen tilaus, jolle on tuossa 22.2. suoritetussa ajossa laitettu orderstatus cancelled.
> 
> Bugzillassa näyttäisi olevan tähän liittyvä tiketti [10869](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=10869).

Ilmeisesti tilaukselta puuttuu datecancellationprinted-arvo (kuka tietää miten noilla muilla muka semmonen oli). Sen kun laittaa, niin tilaus siirtyy nätisti peruttuihin tilauksiin. Vaskissa näyttäisi olevan nyt 88 kappaletta sellaisia tilauksia, joissa biblionumber on null, orderstatus on cancelled ja datecancellationprinted on null. Onkohan ne kaikki sellaisia mille voidaan laittaa tuo datecancellationprinted arvo? Kehtaisiko joku tarkistaa? Tällä pitäs löytyä:

`select ordernumber, basketno from aqorders where biblionumber is null and orderstatus = "cancelled" and datecancellationprinted is null;`

**Comment by Tuomas-Kyyti** [comment]
Kyytissä löytyi tällä raportilla 164 hankintaa, lähes kaikki Kohan alkuajoilta. Ne kyllä voisi korjata lisäämällä tuon datecancellationprinted-arvon.

> `select ordernumber, basketno from aqorders where biblionumber is null and orderstatus = "cancelled" and datecancellationprinted is null;`

**Comment by emta001** [comment]
Ajot tehty Vaskille ja Kyytille.

**Comment by AnneliO** [comment]
Kyselyllä
```
select ordernumber, basketno from aqorders where biblionumber is null and orderstatus = "cancelled" and datecancellationprinted is null;
```
löytyy kimpoista tuloksia seuraavasti:

Lumpeissa 413
Outissa 429
Lapissa 256
Siilissä 1
Vaarassa 247
Hellessä 478

**Comment by Hanna-Lumme** [comment]
Lumpeille voi myös tehdä korjausajon.

**Comment by pirliis** [comment]
Tehdään OUTIlle myös korjausajo.

**Comment by MariaJoon** [comment]
Lappi tahtoo myös korjausajon.

**Comment by AnneliO** [comment]
En tiedä, liittyykö varsinaisesti tähän, mutta löysin Redminestä [tällaisen yli neljä vuotta vanhan tiketin](https://tiketti.koha-suomi.fi/issues/3866), jossa mainitaan myös tuo datecancellationprinted. Siinä tosin tilauksella on tuo päivämäärä asetettu, mutta tilauksen status ei ole cancelled.

**Comment by emta001** [comment]
Ajo tehty Vaaralle (248 kpl), Lumpeelle (413 kpl), OUTIlle (429 kpl) ja Lapille (256 kpl). Päivämääräksi asetettu "2023-08-07".

**Comment by ReettaSiili** [comment]
Sain Siilissä korjattua itse tuon 1 nimekkeettömän tilauksen pois korista eli asian pitäisi olla kunnossa.

Muut ovat korjaantuneet varmaan jo edellisessä ajossa.

**Comment by Kati-Helle** [comment]
Saisiko korjaavan ajon myös Hellelle?

**Comment by emta001** [comment]
Ajo tehty myös Hellelle (478 kpl).

Miun laskujen mukaan kaikkien kimppojen pitäis nyt olla kuosissa, suljen tiketin.
