### ISSUE TITLE
Asiakkaan maksujen kokonaismäärän näkymisessä puutteita, kun käytössä on asetus ManInvInNoissuesCharge=Älä sisällytä 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#301]
### Kehitysehdotukseni

Tiedot kopsattu 06/05/2022 tehdystä Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/5381

Liittyen asetukseen: ManInvInNoissuesCharge=Älä sisällytä
Asiakkaalle lisätyt kimpan (Hellen) omien maksutyyppien maksut eivät sisälly asiakkaan lainaus -toiminnossa eikä asiakkaan tiedot -näytöllä näkyviin maksuihin.

Esimerkkinä Helle-testin asiakas borrowernumber=109720.
Asiakkaalla on nyt tikettiä tehdessä Maksut-näytöllä maksuja yhteensä 33,35 ja näistä:
Kohan omien maksutyyppien maksuja 8,60 (sisältää Kohasta automaattisesti muodostuvia maksuja sekä 'käsin' lisätyn Koha-maksun New card)
Hellen omien maksutyyppien maksuja 24,75

Asiakkaan tiedot -näytöllä maksut näkyvät näin:
Maksut: Asiakkaalla on maksuja 8,60.

Asiakkaan lainaus -toiminnossa maksut näkyvät näin:
Maksut: Asiakkaalla on maksuja 8,60

![kuva](https://user-images.githubusercontent.com/99952449/207542615-01799c9e-e366-4472-8c5f-00255628a714.png)

Asiakkaan maksujen kokonaissumma näkyy ainoastaan asiakkaan Maksut -näytöllä.

Tämän päivän Helle-tuotannossa maksujen näkyminen, kun käytössä on asetus ManInvInNoissuesCharge=Älä sisällytä:
- Tiedot-näytöllä näkyy asiakkaan kaikki maksut.
- Lainaus-näytöllä näkyy tieto vain niistä asiakkaan maksuista, jotka voivat vaikuttaa asiakkaan lainauskieltoon (julkisoikeudelliset maksut).

Kun asiakkaalle on lainattu nide, näkyy Lainaus-näytöllä yksityisoikeudellisten maksujen kokonaismäärä tyyliin: Asiakkaalla on maksamattomia maksuja varauksista, lainoista, tms. 44,00.
![kuva](https://user-images.githubusercontent.com/99952449/207542732-5faf6069-dde3-49d1-ba32-8ddd96375efe.png)

Anneli Ö kommentoinut tikettiin joulukuussa 2022: Versiossa 22.11 manuaaliset maksut (yksityisoikeudelliset) eivät näy ollenkaan lainaus-sivulla, jos käytössä on ManInvInNoissuesCharge=Älä sisällytä.
Tutkaillaan tarkemmin versionvaihdon testeissä ja päätetään sitten, miten edetään.

Marraskuussa 2022 Anneli Ö lisännyt linkin tikettiin https://tiketti.koha-suomi.fi/issues/5064 (tiketti tehty 19/10/2021)

Tiketin 5064 aihe:
Helle: Finna-rajapintaan tarvitaan määritys siitä, että itse lisättyjen maksutyyppien maksut eivät vaikuta asiakkaan lainakieltorajaan eikä varauskieltorajaan

Helle-Kohassa on otettu käyttöön tapa, jossa itse lisättyjen maksutyyppien maksut eivät vaikuta eivätkä saa vaikuttaa asiakkaan maksuista johtuvaan lainauskieltoon eikä varauskieltoon.

Tähän liittyvä järjestelmäasetus ManInvInNoissuesCharge on Helle-Kohassa näin:
Älä sisällytä MANUAL_INV-maksut kun lasketaan maksuja yhteen.

Helle-Finna ei osaa tätä huomioida, vaan niputtaa lainaus- ja varauskieltorajaan asiakkaan kaikki maksut maksutyypistä riippumatta.

![kuva](https://user-images.githubusercontent.com/99952449/207544726-a26b803f-cc95-4e0c-8ed4-88244d8d279b.png)
![kuva](https://user-images.githubusercontent.com/99952449/207544795-d1e3d079-27a3-476d-8a41-763765afb16e.png)
![kuva](https://user-images.githubusercontent.com/99952449/207544848-f368a6f4-d34d-42b6-868a-a26e0e64f6b9.png)

Anneli Ö kommentoinut marraskuussa 2022: Koha-Suomen asiantuntijaryhmän päätös 14.11.2022: Tässä vaiheessa tehdään tekstimuutos Finnan ohjeteksteihin.

**Comment by AnneliO** [comment]
@Kati-Helle tässä tiketissä on kaksi eri asiaa: maksujen näkyminen Kohassa ja Finna ei noudata ManInvNoIssuesCharge-asetusta. Jaatko nämä kahteen eri tikettiin, niin asioita on helpompi edistää ja seurata. Liittyvät kyllä samaan asetukseen, mutta todennäköisesti sama ratkaisu ei päde kumpaankin. :)

**Comment by lmstrand** [comment]
En löydä Kohan virkailijaliittymän maksunäyttöpuutteista erillistä tikettiä, mutta tämän tiketin otsikko kyllä kertoo asian joten tätä tikettiä voi ylläpitää tämän asian selvittelyssä. Yhteisön tiketti:
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32450

**Comment by Kati-Helle** [comment]
> @Kati-Helle lainat pystyy uusimaan ainakin testieni mukaan Finnassa, kun ManInvNoIssuesCharge = 'älä sisällytä' ja minulla oli 3d-tulostusmaksuja Hellen testillä 100e :) eli toimii kuten pitääkin (eikä lainauskiellosta ollut testi-Finnassa mainintaa) tämän viimeisimmän versionvaihdon jälkeisessä Kohassa (22.11).

@lmstrand Hienoa! Kiitos Lari testauksesta ja tiedosta :) 
Testasinpa minäkin vielä Helle-tuotannossa lisäämällä asiakastiedolleni maksuja niin, että lainauskieltoraja ylittyy (tosin hillitymmän määrän kuin sinä :) Helle-Finnaan kirjauduin enkä saanut ilmoitusta lainauskiellosta. Lainojen uusintakin onnistui.

**Comment by Kati-Helle** [comment]
Testasin Helle-testissä. Toimivalta vaikutti :)

Helle-testistä en löydä enää asetuksia: ManInvInNoissuesCharge, RentalsInNoissuesCharge, HoldsInNoissuesCharge
Hellen lainauskieltoraja on 20.00

Testiasiakas ID=8735
Asiakkaalla on Kohasta automaattisesti muodostuneita myöhästymismaksuja 18.00. Nämä maksut vaikuttavat lainauskieltoon.
Lisäsin asiakkaalle maksuja 4.80 tulosteista. Nämä maksut eivät vaikuta lainauskieltoon. (Ei täppää maksutyypin Included in noissuescharge?)
Asiakkaalla on lainauskieltorajaan vaikuttavia maksuja 18.00, joten lainauskieltoraja ei vielä täyty.

Lainausnäkymää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c45c8e96-bab0-45cb-92ad-e5540c236d42)

Niteen lainauksen jälkeen Koha ilmoittaa muiden kuin lainauskieltoon vaikuttavien maksujen määrän tyyliin: Asiakkaalla on maksamattomia maksuja varauksista, lainoista, tms: 4,80
(eli lauseessa mainitut maksutyypit eivät ok)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fb449be5-e1a6-4841-ac72-f3a5d143a69a)


Muutan asetuksista tulostusmaksut vaikuttamaan lainauskieltorajaan täppäämällä/valitsemalla maksutyypin asetuksessa tämän:  Included in noissuescharge?
Testiasiakas edelleen sama ID=8735
Asiakkaalla on Kohasta automaattisesti muodostuneita myöhästymismaksuja 18.00. Nämä maksut vaikuttavat lainauskieltoon.
Tulostemaksut 4.80 vaikuttavat nyt lainauskieltoon.
Asiakkaalla on lainauskieltorajaan vaikuttavia maksuja 22.80 eli yli lainauskieltorajan.

Lainausnäkymää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/a22d016e-f7d2-4e04-817f-0f978f789d8d)

Nidettä lainatessa Koha ilmoittaa asiakkaan lainauskieltorajan ylittävän maksumäärän. Lainaus tulee joko vahvistaa tai perua.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c87e94a3-1b3e-435f-b1a5-9734c773fb09)

**Comment by iinaniemi** [comment]
Palaan tähän asiaan vielä. Onko nyt siis niin, että mitään aktiivista tikettiä ei ole tällä hetkellä olemassa siihen, että Kohassa saataisiin näkymään asiakkaan tiedoissa selkeästi koko maksujen kokonaissumma menemättä Maksut-välilehdelle?

Kaikkia maksuja ei voi pistää vaikuttamaan lainauskieltoon, joten Kohassa näkyy edelleen kahdenlaisia summia. On virkailijan kannalta kovin ikävää, että asiakkaan Lainaus- ja Tiedot- välilehdellä näkyy maksujen summa, mikä ei kuitenkaan ole välttämättä kokonaissumma. Muutenkin monen eri summan näkyminen ilman selkeää selitystä on virkailijalle hämmentävää. On ikävää sekin että asiakkaalle sanotaan esim. että sinulla on täällä maksuja vaikka 8 euroa, ja hänen kaivettuaan kukkaroaan huomataan että eikun sinulla olikin 23 euroa.

Olisikohan mahdollista saada Lainaus/Tiedot-välilehdille esimerkiksi näkyviin kaksi eri riviä, tyyliin "Lainauskieltoon vaikuttavat maksut" ja "Muut maksut"? Tai että Lainaus/Tiedot näkymissä näkyisi kaikkien maksujen kokonaissumma, ja sitten Maksut-välilehdelle eritellysti mistä tuo kokonaissumma koostuu.

**Comment by lmstrand** [comment]
Tein virkailijaliittymässä näkyvistä maksutiedoista ( Lainaus- ja Tiedot- välilehdellä) tiketin: https://github.com/KohaSuomi/Koha/issues/762

**Comment by lmstrand** [comment]
Automaateille välittyvästä asiakkaan maksujen yhteissummasta on tiketti https://github.com/KohaSuomi/Koha/issues/378

**Comment by iinaniemi** [comment]
Kiitos Lari! :)

**Comment by pirliis** [comment]
> OUTIn testillä määrittelin nyt maksutyyppikohtaisesti vaikuttaako maksu lainauskieltorajaan vai ei. Näyttäisi toimivan Kohassa, mutta testi-finnassa, jos asiakkaalla on julkisoikeudellisia maksuja yli sallitun maksimimäärän, lainojen uusinta onnistuu. Pitääköhän tämä uusi ominaisuus ottaa erikseen käyttöön myös finnassa jotenkin?

OUTIn testille oli päivittynyt nyt lisää maksuja ja toisella testiasiakkaalla on nyt reilusti julkisoikeudellisia maksuja (19,00 e), jotka ovat ylittäneet lainauskieltorajan. Hänellä testi-Finnassa uusiminen ei ole mahdollista eli oletettavasti uusi ominaisuus toimii sittenkin finnassa. Aiemmalla testiasiakkaalla julkisoikeudellisia maksuja oli 12,00 € ja hänen lainoja pystyi uusimaan, vaikka lainauskiellon raja on 11,99 €. Eli tätä pitää tutkia vielä lisää.

**Comment by lmstrand** [comment]
Onko tämän tiketin tilanne nyt muuttunut, kun versionvaihto on tehty?

**Comment by MikkoLiimatainen** [comment]
Tuo OpacFineNoRenewals näyttää Finnan päässä toimivan samalla tavalla kuin tuo noissuescharge Kohassa. Eli jos OpacFineNoRenewals-asetukseen laittaa sentin pienemmän summan kuin lainauskielto, niin silloin se estää uusinnan Finnassakin kun lainauskieltoraja tulee täyteen.

**Comment by pirliis** [comment]
> Tuo OpacFineNoRenewals näyttää Finnan päässä toimivan samalla tavalla kuin tuo noissuescharge Kohassa. Eli jos OpacFineNoRenewals-asetukseen laittaa sentin pienemmän summan kuin lainauskielto, niin silloin se estää uusinnan Finnassakin kun lainauskieltoraja tulee täyteen.

Kiitos vinkistä! Muutin OUTIin asetukseen OpacFineNoRenewals 11,99 e. Nyt näyttäisi toimivan verkkokirjastossa myös 12,00 euron maksuraja, ettei asiakas pääse uusimaan lainoja.

**Comment by Kati-Helle** [comment]
Kiitos toteutuksesta!
