### ISSUE TITLE
Viivakoodien lisääminen tarratulostukseen perustiedot-näytön kautta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#306]
### Kehitysehdotukseni

Kopioitu Redminestä tiketistä https://tiketti.koha-suomi.fi/issues/4950

Anni Rajala 24.6.2021

Uutuusaineiston käsittelyä helpottamaan on toivottu, että niteet voisi lisätä listalle ja listan saisi suoraan tarratulostimeen.

--

Koha-Suomen asiantuntijaryhmän päätös 14.11.2022: Lisätään toiminnallisuus viedä useampi nide kerralla tarratulostustyökaluun esim. perustiedot-näytöltä.

### Jotain muuta?

Tarratulostustyökalu on kirjoitettu täysin uusiksi alkuperäisen tiketin teon jälkeen, joten jätin kuvauksesta pois kommentit, jotka liittyivät vanhaan työkaluun.

**Comment by lasse-koha** [comment]
Tällaisella lisäyksellä intranetuserjs:ään saa valittua lisättävät niteet perustiedot-näytön listalta:
```
/* Niteiden lisäys tarratulostustyökaluun perustiedot-näytöltä */
$(document).ready(function() {
    $("#holdings .itemselection_action_modify").after('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
    if( $('.itemselection_action_print').length ) {
        $.getScript("/intranet-tmpl/lib/jquery/plugins/humanmsg.js");
        $('<link/>', {
            rel: 'stylesheet',
            type: 'text/css',
            href: '/intranet-tmpl/prog/css/humanmsg.css'
        }).appendTo('head');
    }
});
function addItemsToPrintQueue(e, element) {
    e.preventDefault();
    var requests = [];
    $("input[name='itemnumber'][type='checkbox']:checked", 'table.items_table').each(function() {
        var itemnumber = $(this).val();
        requests.push($.ajax({
            url: "/api/v1/contrib/kohasuomi/labels/print/queue",
            type: "POST",
            datatype: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ itemnumber: itemnumber, printed: 0 }),
            error: function (err) {
                humanMsg.displayAlert( `<strong>Niteen nro. ${itemnumber} lisäys tulostusjonoon epäonnistui.</strong>` );
            }
        }));
    });
    window.onbeforeunload = function () {
        if ( requests.length ) {
            return "";
        }
    };
    humanMsg.displayAlert( `Lisätään ${requests.length} nide${requests.length == 1 ? "" : "ttä"} tulostusjonoon...` );
    $.when.apply($, requests).done(function () {
        humanMsg.displayAlert( `${requests.length} nide${requests.length == 1 ? "" : "ttä"} lisätty tulostusjonoon.` );
    }).fail(function () {
        alert( "Niteiden lisäys tulostusjonoon keskeytyi. Tarkista tulostusjono." );
    }).always(function () {
        requests = [];
    });
}
```

**Comment by AnneliO** [comment]
Lisäsin rimpsun OUTIn testille IntranetUserJS:ään, mutta se ei toiminut eli perustiedot-näytölle ei tullut näkyville uutta. Järjestelmäasetuksessa näkyi tällaisia huutomerkkejä:
![kuva](https://user-images.githubusercontent.com/33121325/213381522-6e8870aa-dce2-4b48-8b25-98394f3b5e13.png)

Huutomerkkeistä tuli tällainen teksti näkyviin: 'template literal syntax' is only available ES6 (use 'esversion: 6').

**Comment by AnneliO** [comment]
Aa, tulee palvelinvirhe, kun yritän tallentaa IntranetUserJS:n, siksi ei varmaankaan mitään tullut näkyviin.

**Comment by lasse-koha** [comment]
> Aa, tulee palvelinvirhe, kun yritän tallentaa IntranetUserJS:n tämän rimpsun kanssa, siksi ei varmaankaan mitään tullut näkyviin.

Liittyy ilmeisesti tuohon humanmsg-pluginiin, pitää selvittää.

**Comment by lasse-koha** [comment]
Tämän version sain lisättyä Vaskin testille ja näyttäisi siellä toimivan oikein:
```
/* Niteiden lisätys tarratulostustyökaluun perustiedot-näytöltä */
$(document).ready(function() {
    $("#holdings .itemselection_action_modify").after('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
});
function addItemsToPrintQueue(e, element) {
    e.preventDefault();
    var requests = [];
    $("input[name='itemnumber'][type='checkbox']:checked", 'table.items_table').each(function() {
        var itemnumber = $(this).val();
        requests.push($.ajax({
            url: "/api/v1/contrib/kohasuomi/labels/print/queue",
            type: "POST",
            datatype: "json",
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ itemnumber: itemnumber, printed: 0 }),
            error: function (err) {
                console.error( `Niteen nro. ${itemnumber} lisäys tulostusjonoon epäonnistui.` );
            }
        }));
    });
    window.onbeforeunload = function () {
        if ( requests.length ) {
            return "";
        }
    };
    $('.itemselection_action_print').html(`<a> <i class="fa fa-print"></i> Lisätään ${requests.length} nide${requests.length == 1 ? "" : "ttä"} tulostusjonoon...</a>`);
    $.when.apply($, requests).done(function () {
        alert( `${requests.length} nide${requests.length == 1 ? "" : "ttä"} lisätty tulostusjonoon.` );
    }).fail(function () {
        alert( "Niteiden lisäys tulostusjonoon keskeytyi. Tarkista tulostusjono." );
    }).always(function () {
        $('.itemselection_action_print').html('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
        requests = [];
    });
}
```

**Comment by ajrajala** [comment]
Testattiin myös täällä ja näyttäisi toimivan, ei havaittu mitään ongelmia esim. isojen nidemäärienkään lisäämisessä.

**Comment by AnneliO** [comment]
Minusta kannattaa muidenkin testata vielä ja yhtenäisten käytäntöjen vuoksi laittaisin kaikille tän paikalleen. :)

**Comment by Tuomas-Kyyti** [comment]
Vaikuttaa toimivan Kyytin testillä. 

Sellainen huomio, että _Lisää valitut niteet tulostusjonoon_ -linkki tulee vain oman kirjautumiskirjaston välilehdelle, ei _Muut kokoelmat_ -välilehdelle. Kuitenkin jos _Muut kokoelmat_ -välilehdellä ruksii niteitä ja sitten painaa oman kirjaston välilehdellä _Lisää valitut niteet tulostusjonoon_ -linkkiä, tulevat nekin mukaan _Omaan tulostusjonoon_. Tämä ei varmaan ole ongelma, koska yleensä kai tulostetaan tarroja niihin niteisiin, jotka näkyvät oman kirjaston välilehdellä.

**Comment by pknuuti** [comment]
Liitin koodin Vaaran testille ja testasin tarratulostusta. Toimii hyvin! Vaarassa on kaikki niteet samalla välilehdellä, joten tulostettavaksi voi valita mitä tahansa niteitä. Toki tarve on yleensä vain oman kirjaston/kellutuskirjaston niteille, mutta sehän on käyttäjän valinta.

**Comment by lasse-koha** [comment]
> Sellainen huomio, että _Lisää valitut niteet tulostusjonoon_ -linkki tulee vain oman kirjautumiskirjaston välilehdelle, ei _Muut kokoelmat_ -välilehdelle. Kuitenkin jos _Muut kokoelmat_ -välilehdellä ruksii niteitä ja sitten painaa oman kirjaston välilehdellä _Lisää valitut niteet tulostusjonoon_ -linkkiä, tulevat nekin mukaan _Omaan tulostusjonoon_. Tämä ei varmaan ole ongelma, koska yleensä kai tulostetaan tarroja niihin niteisiin, jotka näkyvät oman kirjaston välilehdellä.

Kaipa tuokin olisi hyvä korjata. Rivin
```
    $("#holdings .itemselection_action_modify").after('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
```
tilalle
```
    $("#holdings .itemselection_action_modify, #otherholdings .itemselection_action_modify").after('<a href="#" class="itemselection_action_print" onclick="addItemsToPrintQueue(event, $(this))"> <i class="fa fa-print"></i> Lisää valitut niteet tulostusjonoon</a>');
```
ja rivin
```
    $("input[name='itemnumber'][type='checkbox']:checked", 'table.items_table').each(function() {
```
tilalle
```
    $("input[name='itemnumber'][type='checkbox']:visible:checked", 'table.items_table').each(function() {
```
, sitten pitäisi toimia oikein eli linkki näkyy molemmilla välilehdillä ja tulostukseen menevät vain näkyvillä olevalta välilehdeltä valitut niteet.

**Comment by Tuomas-Kyyti** [comment]
Toimii Kyytissä, kuten Lasse edellä kirjoittaa. Meidän puolesta nyt hyvä.

**Comment by AnneliO** [comment]
Toiminto lisätty vkon 5 päivityksen aikaan kaikille tuotantoon. Suljen tiketin.
