### ISSUE TITLE
Tietueen Varaukset-sivulla asiakas-sarakkeen tietoja ei ladata jos käyttäjältä puuttuu edit_borrowers-oikeus

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#308]
### Mikä vikana?

Varaukset-sivun lataamisessa on ollut käyttäjaoikeuksiin liittyneitä ongelmia, joista on Redminessä ollut tiketti https://tiketti.koha-suomi.fi/issues/5600. Korjausten jälkeen varausjono latautuu nyt niillekin käyttäjille joilta puuttuu edit_borrowers-käyttöoikeus, mutta asiakas-sarakkeeseen ei tule näkyville kirjastokortin numerot. Käyttämälläni testitunnuksella on siis oikeus (view_borrower_infos_from_any_libraries) muttei oikeutta (edit_borrowers), ja tällaisella testitunnuksella esim. lainaus-näkymässä tai tietueen saatavuustiedoissa näkee kyllä kirjastokortin numeron.

### Mitä pitäisi tapahtua

Varausjonossa pitäisi näkyä kirjastokorttien numerot Asiakas-sarakkeessa vaikka käyttäjältä puuttuisikin edit_borrowers-oikeus.

### Kuinka toistaa ongelma/asia

1. Tee käyttäjätunnus, jolla on käyttäjäoikeus view_borrower_infos_from_any_libraries mutta ei oikeutta edit_borrowers.
2. Hae tietue, johon on varauksia, ja siirry Varaukset-välilehdelle.
3. Havaitse, että varausjono latautuu muuten oikein mutta Asiakas-sarakkeeseen ei tule odotusajan jälkeenkään tietoja.

### Jotain muuta?

Bugi siirretty Githubiin Redminen tiketistä [#5600](https://tiketti.koha-suomi.fi/issues/5600).

**Comment by AnneliO** [comment]
Bugi on yhteisössä signed off -tilassa, mikä viittaa siihen, että se toimii. Tuodaan yhteisöstä patchi testattavaksi meillekin. Jos toimii, viedään myös tuotantoon.

**Comment by emta001** [comment]
Patchi tuotu testeille.

**Comment by LeenaKinnunen** [comment]
Testasin Annin ohjeen mukaan Lapin testillä. Asiakastieto tulee näytölle, mutta kirjastokortti-linkkiä painamalla näillä oikeuksilla tulee istunto aikakatkaistiin -sivulle. On siis korjaantunut, eli ei enää jää pyörimään ja odottamaan asiakastietoja.

**Comment by pirliis** [comment]
OUTIn testillä korjaus näyttäisi toimivan myös eli käyttäjällä, jolla ei ole edit_borrowers-oikeutta, tietueen varausjonoon tulee varaajien kirjastokorttien numerot Asiakas-sarakkeeseen.

**Comment by ajrajala** [comment]
Vaskin testillä tarkistettu myös, että toimii nyt kuten toivottu.

**Comment by emta001** [comment]
> Oliko tämä korjaus mahdollisesti tulossa jo tämän viikon Koha-päivityksen mukana tuotantoon? Tuli tästä juuri kysymystä yhden virkailijan käyttöoikeuksiin liittyen niin mietin korotanko virkailijan käyttöoikeuksia väliaikaisesti vai ratkeaako käyttöoikeusongelma jo huomenna.

Juu on tulossa, ei tartte siis mitään tehdä :)

**Comment by emta001** [comment]
> > Oliko tämä korjaus mahdollisesti tulossa jo tämän viikon Koha-päivityksen mukana tuotantoon? Tuli tästä juuri kysymystä yhden virkailijan käyttöoikeuksiin liittyen niin mietin korotanko virkailijan käyttöoikeuksia väliaikaisesti vai ratkeaako käyttöoikeusongelma jo huomenna.
> 
> Juu on tulossa, ei tartte siis mitään tehdä :)

Komento takas, tässä ilmenekin ongelmia, niin muutos ei ehdikään tämän viikon päivitykseen. Tulee ensi viikolla.

**Comment by ajrajala** [comment]
Ok, kiitos tiedosta!

**Comment by ajrajala** [comment]
Toimii tuotannossa nyt kuten pitää eli varausjono-sivu latautuu oikein vaikka käyttäjältä puuttuisikin edit_borrowers-oikeus.
