### ISSUE TITLE
Helle: Helle-Finnassa tehty varaus on tärppäytynyt palauttaessa noudettavaksi väärään kirjastoon

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#310]
### Mikä vikana?

Helle-Finnassa tehty varaus on tärppäytynyt palauttaessa noudettavaksi väärään kirjastoon.

Asiakas borrowernumber=40737 on tehnyt tänä aamuna (16.12.2022) Helle-Finnassa varauksen noutokirjastonaan Porvoon pääkirjasto PRVPK.

Lokitietojen perusteella
16.12.2022 08:41 asiakas ID=40737 on tehnyt varauksen Helle-Finnassa - noutokirjastona PRVPK
16.12.2022 08:46 asiakas on muokannut varausta Helle-Finnassa - noutokirjastona edelleen PRVPK
16.12.2022 08:56 varaukseen tärpännyt nide itemnumber=380151 on palautettu kirjastossa PRVPK -> varaus tärpännyt kuljetettavaksi kirjastoon PRVKR

![kuva](https://user-images.githubusercontent.com/99952449/208056795-d2583089-a67a-4292-81dd-f36394931d9c.png)

Hyllyvaraukset-raportilla noutokirjastona on näkynyt PRVPK
![kuva](https://user-images.githubusercontent.com/99952449/208057463-f7d86bb3-c480-4fdb-b175-79119f5393f4.png)

**Comment by Kati-Helle** [comment]
Tiedoksi vielä saman asiakkaan toinen samantyylinen varaustapaus tältä aamulta

![kuva](https://user-images.githubusercontent.com/99952449/208063765-fc162b47-395f-4a1a-8336-7fe972b6ba23.png)

**Comment by Kati-Helle** [comment]
Varaukset tehneelle asiakkaalle on soitettu. Asiakas haluaa noutaa varaukset kirjastosta PRVKV. Eli kirjastosta, jonne niteet ovat palauttaessa tärpänneet noudettavaksi.

**Comment by AnneliO** [comment]
Luulen, että tässä on käynyt niin, että asiakas on muuttanut noutokirjaston siinä välissä kun varauksen tiedot on katsottu hyllyvarausraportilta ja palautettu. Testasin, miten tiedot päivittyy lokille ja sinne menee se tieto, mikä se oli ennen muutosta. Esim.

![Image](https://user-images.githubusercontent.com/33121325/214555281-8ba9a616-e4a7-4a34-b458-8afbeab9b9a7.png)

Eli tässä tapauksessa muutoksen yhteydessä näkyy, että noutokirjaston on Kaijonharju, vaikka se muutettiin Kastelliksi. Ja kun taas Kastelli vaihdettiin takaisin Kaijonharjuksi, näkyy lokilla, että noutokirjasto on Kastelli.

**Comment by Kati-Helle** [comment]
Kiitos Anneli selvityksestä.
