### ISSUE TITLE
Finnassa tehdyn puhelinnumeron muutos vaikuttamaan Kohan Matkapuhelin-kenttään. Vaikuttaa nyt vain Tekstiviesti numeroon -kenttään

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#311]
### Kehitysehdotukseni

Kannattaisiko asiakkaan Finnassa tekemä puhelinnumeroarvomuutos muuttaa vaikuttamaan Kohan Matkapuhelinnumero-kenttään? Muutos vaikuttaa nyt vain Kohan Tekstiviesti numeroon -kenttään. Asiakas ei voi muuttaa Finnassa Koha-asiakastietojensa Matkapuhelin-kenttäarvoa.

Lari mainitsee tiketissä https://github.com/KohaSuomi/Koha/issues/204
"Pitää varmaan tehdä oma tiketti tuosta Finnan tekstiviesti numeroon-ongelmasta, jos sen vaihtaisi käyttämään matkapuhelin-kenttää Finnassa tallentaessa/vaihtaessa (jolloin triggeri hoitaisi tiedon tekstiviesti numeroon-kenttään ja tekstiviesti numeroon-kenttä jäisi tarpeettomaksi edes nähdä virkailijaliittymässä)."

Finnassa asiakas voi tehdä muutokset näihin Kohan asiakastietokenttiinsä:
- Tekstiviesti numeroon
- Sähköposti
- Varaustunnus
- Yksityisyysasetus
- Osoite
- Postinumero
- Kunta
- Maa
![kuva](https://user-images.githubusercontent.com/99952449/208363249-476058ed-091a-4eff-a144-635e80557a5d.png)

![kuva](https://user-images.githubusercontent.com/99952449/208364569-170be5c1-47be-4157-8798-0a36269e9e1c.png)

**Comment by AnneliO** [comment]
Keskustelimme tästä 20.12.2022 pääkäyttäjäpalaverissa ja sovimme, että kaikki tarkistaa oman kimpan tilanteen ja jos Finnassa lisätty puhelinnumero ei välity Kohaan sekä mobile että smsalertnumber-kenttiin, niin kyseisistä kimpoista ollaan yhteydessä Finna-toimistoon ja pyydetään säätämään Finnan tallennus niin, että tieto välittyy kumpaankin kenttään.

**Comment by ReettaSiili** [comment]
Siilinjärvelle on nyt pyydetty ja saatu korjaus Finnaan eli numero siirtyy Finnasta molempiin kenttiin.

**Comment by Kati-Helle** [comment]
> Keskustelimme tästä 20.12.2022 pääkäyttäjäpalaverissa ja sovimme, että kaikki tarkistaa oman kimpan tilanteen ja jos Finnassa lisätty puhelinnumero ei välity Kohaan sekä mobile että smsalertnumber-kenttiin, niin kyseisistä kimpoista ollaan yhteydessä Finna-toimistoon ja pyydetään säätämään Finnan tallennus niin, että tieto välittyy kumpaankin kenttään.

Mitä tapahtuu OUTIssa tai Siilinjärvellä silloin, kun Kohassa on arvo sekä Matkapuhelin-kentässä että Tekstiviesti numeroon -kentässä ja Finnassa tehdään puhelinnumeromuutos? Helle-Finnassa tehty puhelinnumeromuutos:
- päivittää Helle-Kohan Tekstiviesti numeroon -kentän
- ei päivitä Helle-Kohan Matkapuhelin-kenttää

**Comment by ReettaSiili** [comment]
Siilissä numero päivittyy Kohassa nyt molempiin kenttiin, kun asiakas tekee muutoksen Finnassa.

**Comment by AnneliO** [comment]
Puhelinnumero päivittyy sekä Tekstiviesti numeroon -kenttään että Matkapuhelin-kenttään. Ja näin se pitää tapahtuakin, jotta asiakkaan tekemä numeromuutos ei mene "hukkaan", jos virkailija käy asiakkaan tekemän muutoksen jälkeen tallentamassa asiakkaan tiedot ja matkapuhelinnumero-kentässä oleva numero kopioituu triggerillä tekstiviesti-kenttään.

**Comment by Kati-Helle** [comment]
> Puhelinnumero päivittyy sekä Tekstiviesti numeroon -kenttään että Matkapuhelin-kenttään. Ja näin se pitää tapahtuakin, jotta asiakkaan tekemä numeromuutos ei mene "hukkaan", jos virkailija käy asiakkaan tekemän muutoksen jälkeen tallentamassa asiakkaan tiedot ja matkapuhelinnumero-kentässä oleva numero kopioituu triggerillä tekstiviesti-kenttään.

Helle-Finnaan oli eilen 21.12.2022 pyydetty muutos ja muutos oli saamieni tietojen mukaan myös tehty. Ei siis toimi Hellessä ainakaan vielä oikein.

**Comment by ReettaSiili** [comment]
Meille tekivät muutoksen ensin testi-Finnaan ja vasta meidän kuittauksen jälkeen tuotantoon, onko muutos jäänyt teillä vasta testiin asti?

**Comment by Kati-Helle** [comment]
> Meille tekivät muutoksen ensin testi-Finnaan ja vasta meidän kuittauksen jälkeen tuotantoon, onko muutos jäänyt teillä vasta testiin asti?

Hellessä muutos on tehty tietääkseni tuotantoon. Testasin nyt vielä testissä. Samoin toimii, eli testi-Finnassa tehty puhelinnumeromuutos päivittää/muuttaa vain Tekstiviesti numeroon -kentän, mutta ei muuta Matkapuhelin-kenttäarvoa.

**Comment by Chriss-Kyyti** [comment]
Kyytissä muutos päivittyy kenttiin:
tekstiviesti numeroon
JA:
Lankapuhelin.

Laitan tästä Finnapostia.

**Comment by Chriss-Kyyti** [comment]
Finnapostin muutosten jälkeen toimii nyt testissä oikein.

**Comment by HeliAuranen** [comment]
Lumpeissa päivittyy Finnasta molempiin kenttiin

**Comment by MikkoLiimatainen** [comment]
Vaskissa toimii tuotannossa oikein, mutta testillä muutos menee matkapuhelin-kentän sijaan lankapuhelin-kenttään.

**Comment by ReettaSiili** [comment]
Varan vuoksi tarkennuksena Siilin tilanne testin ja tuotannon suhteen uudelleen:
Testi-Finnasta Testi-Kohaan muutos siirtyy vain SMS-number -kenttään. Tänne emme ole Finna-toimistosta mitään muutosta pyytäneetkään.
Toisesta testi-Finnasta joka on yhteydessä tuotanto-Kohaan ja tuotanto-Finnasta numero siirtyy toivotulla tavalla ja oikein tuotanto-Kohaan.
Pitäisikö tämä saada siis toimimaan oikein myös testi-Kohassa?

**Comment by Chriss-Kyyti** [comment]
Jos teillä on suunnitelmissa kopioida testin näkymä ja käyttää sitä tuotannossa on varmasti hyvä varmistaa, että asetus säilyy tuotannossa oikeana. Muuten asialla ei ole merkitystä.

**Comment by lmstrand** [comment]
Juuri näin.

**Comment by LeenaKinnunen** [comment]
Lapissa tehty muutos tuotanto-Finnaan, että Finnassa päivitetty tekstiviestinumero päivittyy Kohassa sekä sms-alert- että mobiilikenttiin. 

Nyt voisi meille tehdä: tarve ajaa tekstiviesti numeroon-kentästä numerot matkapuhelin-kenttään jos ne eroavat. Sitten kimpoille voisi asettaa triggerit tietokantaan kopioimaan asiakkaan muokkauksen yhteydessä matkapuhelinnumerot tekstiviesti numeroon-kenttään.

**Comment by Kati-Helle** [comment]
Hellessä toimii nyt oikein.
Helle-Finnassa tehty puhelinnumeroarvon muutos päivittää/muuttaa Helle-Kohan puhelinnumerokentät mobile JA smsalertnumber.

**Comment by pknuuti** [comment]
Vaarassa toimii oikein.

**Comment by AnneliO** [comment]
Onko tässä vielä jotain keskeneräistä? :)

**Comment by Kati-Helle** [comment]
Ei :)
Suljen tiketin.
