### ISSUE TITLE
Helle: tietueelle massamuokkauksessa lisätty uusi kenttä ei näy kaikilla Koha-näytöillä/toiminnoilla oikealla paikalla. Koskee sekä jo tietueella olemassa olevan kentän uuden kenttätoistuman lisäystä että tietueelle lisättyä täysin uutta kenttää.

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#312]
### Mikä vikana?

Kun Hellessä lisää Tietueen massamuokkaus -toiminnolla jo tietueella olevan kentän uuden kenttätoistuman tai tietueelle täysin uuden kentän, näkyy lisätty kenttä virheellisesti tietueen viimeisenä kenttänä, vaikka kenttä ei ole tietueen (tai välilehden) kentistä suurinumeroisin:
- tietueen Perustiedot/Marc-esikatselu...
![kuva](https://user-images.githubusercontent.com/99952449/208384998-9a4364cd-5eca-4931-9018-7c8ffdc56594.png)

...jossa tietueelle lisätty 650a=hiiret näkyy kenttälistauksen viimeisenä:
![kuva](https://user-images.githubusercontent.com/99952449/208389355-8c910e5d-6582-4265-8679-592e1f70e075.png)

- tietueen Otsikoitu Marc
![kuva](https://user-images.githubusercontent.com/99952449/208385263-815c5a2b-468d-44fc-9285-2a6d46c5d64c.png)

- tietueen Marc: (kenttä on toki oikealla välilehdellä, esim. kenttä 650 välilehdellä 6)
![kuva](https://user-images.githubusercontent.com/99952449/208386386-ba6ed0b4-6d96-452b-ac25-21109ad36dd3.png)

- Työkalut/Tietueiden muokkaus eräajona -toiminto, muutoksen esikatselu painikkeella Näytä Marc
![kuva](https://user-images.githubusercontent.com/99952449/208384507-f3db4c99-d700-4428-a4c8-5d866b1f52cc.png)

Lisätty kenttä on oikealla paikallaan tietueen muokkausnäytöllä.

Kun käy tietueen muokkauksessa tallentamassa massamuokatun tietueen, näkyy lisätty kenttä oikealla paikalla kaikilla näytöillä. Eli tietueen tallennus korjaa tilanteen.

**Comment by Kati-Helle** [comment]
Helle-testissä testauksen tulos: toimii samoin uudessa versiossa 22.11.

**Comment by AnneliO** [comment]
Tämä ongelma on [kertaalleen korjattu](https://github.com/KohaSuomi/RedGrave/blob/main/Palaute%20-%20Koha-Suomi/2018/%233548%20MARC-tietueen%20er%C3%A4muokkauksessa%20uusi%20kentt%C3%A4%20menee%20MARC-esikatselussa%20alimmaiseksi.md) ja tullut takaisin.

**Comment by emta001** [comment]
Outoa, nuo Pasin linkkaamat yhteisön tiketit on menneet läpi. Onkohan meillä ollut sitten jokin muukin korjaus näihin?

**Comment by AnneliO** [comment]
Pikainen testi OUTIn testillä väittäisi, että kenttä menee nyt oikeaan kohtaan MARC-esikatselussa tietueen erämuokkauksen jälkeen. Testaatko Kati siekin?

**Comment by Kati-Helle** [comment]
Helle-testissä vaikuttaa nyt toimivan oikein. Lisäsin tietueelle uuden kentän 650a=alkeistaso

Lisätty kenttä näkyy nyt mm. tietueen MARC-välilehdellä oikein kohdassa 6
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/92301174-b708-47bc-a2b8-ba98dc08a88e)

Lisäsin tietueelle myös jo olemassa olevan kentän uuden kenttätoistuman 650a=keskitaso
Lisäyksen jälkeistä näkymää tietueen MARC-esikatselussa. Lisätty kenttätoistuma sijaitsee ennen tietueella jo ollutta 650-kenttää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1a6b01cc-b059-42e4-9247-41562601f7d4)
