### ISSUE TITLE
Siilinjärvi: Vanhoja maksettuja maksuja on muuttunut asiakkailla hyvityksiksi konversiossa 7.6.2022

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#314]
### Mikä vikana?

Näitä on tullut joitain vastaan aiemminkin, mutta arvelin niiden olevan yksittäisiä. Nyt kun katselin vanhoja maksuja tarkemmin, niitä näyttäisi olevan enemmänkin. Esim. kuvan asiakas id=8667. Tulkintani mukaan asiakas on maksanut 24.11.2017 0,40 € myöhästymismaksuja 1vrk myöhässä olleista lainoistaan, mutta maksu onkin muuttunut hyvitykseksi ja sotkee nyt asiakaspalvelussa.

### Mitä pitäisi tapahtua

Paljonkohan tällaisia hyvityksiä mahtaa asiakkailla olla? Kuinka ne voisi korjata maksetuiksi maksuiksi?

### Jotain muuta?

![Hyvitys1](https://user-images.githubusercontent.com/98806001/208646546-24882d48-b108-49a0-858f-3afe6a17f2b4.png)

**Comment by AnneliO** [comment]
Tämä näyttäis olevan samanlainen tapaus, mitä Vaarassa oli: https://tiketti.koha-suomi.fi/issues/5465

Siellä tilanne korjattiin klikkaamalla asiakkaan maksuissa tuota Käytä-nappia. Tuolla vanhassa tiketissä on SQL-kysely, jolla pystyt hakemaan muita vastaavia asiakkaita.

**Comment by ReettaSiili** [comment]
(etsin tikettejä näköjään väärin versionvaihto-projektista... huoh)
Tästä näyttäisi olevan kyse paitsi meillä nämä on maksusuorituksia eli vaihdoin sql:ään paymentin. Tuli 248 asiakasta, jotka pystyy kyllä korjaamaan käsin. Kiitos Anneli!
