### ISSUE TITLE
Helle: Hae asiakkaita -toiminnon valittavat hakukentät Lankapuhelin JA Toissijainen puh.nro

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#315]
### Kehitysehdotukseni

Etusivu/Asiakkaat/Hae asiakkaita -toiminnon hakukentissä on puhelinnumeron hakukentät Lankapuhelin JA Toissijainen puh.nro.

Hellessä Lankapuhelin-hakukenttä hakee asiakastiedon Matkapuhelin-kentän arvon.
Toissijainen puh.nro -kenttä ei hae ainakaan asiakastiedon Lankapuhelin-kentän arvoa eikä Matkapuhelin-kentän arvoa. Mitä hakeekaan? (Lankapuhelin-kenttä on Hellessä käytössä/näkyvillä asiakastiedoissa.)

Saisiko Matkapuhelin-hakukentän Hae asiakkaita -toiminnon hakukenttävalikkoon (esimerkiksi vaihtamalla Lankapuhelin-hakukentän nimen)?

![kuva](https://user-images.githubusercontent.com/99952449/208671619-aa823c72-bcf8-4600-b87d-ab9b055255d9.png)

**Comment by AnneliO** [comment]
DefaultPatronSearchFields -järjestelmäasetuksessa voi määrittää mobile-kentänkin näkymään haussa.

> Pilkulla erotettu lista oletuskentistä, joita käytetään asiakashaussa:                      Jos tyhjä, Koha asettaa oletukseksi  "sukunimi,etunimi,varaustunnus,kirjastokortti,käyttäjätunnus". Muut  tähän asetukseen lisätyt kentät lisätään vaihtoehtoina alasvetovalikkoon  asiakkaan hakusivulla.

Lankapuhelin-haussa on jotain tosi outoa. Jos tallennan kyseiseen kenttään 0401234567, niin sitä ei näköjään pysty hakemaan. Mutta jos haen ilman ekaa nollaa (ehdolla sisältää) tai viimeistä seiskaa, niin saan tuloksia. Eli jos numero on tasan kymmenen merkkiä, ensimmäinen ja kolmas merkki on nollia ja hakee tasan kymmenellä merkillä, niin ei saa hakutuloksia.

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. Tuon lisäysmahdollisuuden olinkin unohtanut.

Lisäsin Helleen puuttuneen mobile-arvon. Helle-asetuksessa nyt nämä arvot: surname,firstname,cardnumber,userid,othernames,mobile

Hakukenttä-valikko näyttää tältä. 
![kuva](https://user-images.githubusercontent.com/99952449/208834780-496b0284-e1ed-4d27-8510-e7da676e2d11.png)

Saako listauksesta pois hakukentät Lajittelu 1 ja Lajittelu 2. Hakuehdot taitavat hakea kaikki asiakastiedot?

Testasin vielä Lankapuhelin-hakukenttää. 
Lankapuhelin-hakukenttä hakee oikein asiakastietoon tallennetun Lankapuhelin-kenttäarvon 050987654321. 
Lankapuhelin-hakukenttä hakee oikein asiakastietoon tallennetun Matkapuhelin-kenttäarvon, mm. +358-alkuisen ja 040-alkuisen ja 050-alkuisen. 
Mutta: 0400-alkuisen Matkapuhelin-kentän arvon haulla ei hakutulosta.

**Comment by AnneliO** [comment]
Lajittelut saa piiloon näillä IntranetUserCSS-säädöillä:

> /* Piilota asiakashausta valikosta Lajittelu-vaihtoehdot */
body#pat_member.pat select#searchfieldstype_filter option[value='sort1'] { display:none; }
body#pat_member.pat select#searchfieldstype_filter option[value='sort2'] { display:none; }
