### ISSUE TITLE
Kahden uuden automaattitunnuksen lisääminen SIP-palvelimelle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#316]
### Tukipyyntö

Naantaliin on tulossa uuden automaatin ja ovikoneen asennus, joten kaksi automaattitunnusta pitäisi saada lisättyä SIP-palvelimelle. Kenelle voisin toimittaa lisättävät tunnukset & salasanat?

**Comment by emta001** [comment]
Lähetä ne meidän support sähköpostiin, niin poimin ne sieltä.

**Comment by emta001** [comment]
Tunnukset lisätty ja toinenkin homma on toivottavasti kunnossa.

**Comment by ajrajala** [comment]
Kiitos, suljen tämän tiketin ja avaan uuden sitten jos toisessa tunnusongelmassa ilmenisi edelleen häikkää.
