### ISSUE TITLE
LAPPI: Puhelinnumeron kopiointin mobile-kentästä smsalert-kenttään

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#317]
### Tukipyyntö

Lapista on tippunut kokonaan pois IntranetUserJSstä koodin pätkä, jolla puhelinnumero kopioituu mobile-kentästä smsalert-kenttään. Saisiko tämän takaisin.

**Comment by janPasi** [comment]
#311

**Comment by lmstrand** [comment]
Lappiin on nyt lisätty tietokantatriggeri, joka kopioi matkapuhelin-kentän arvon tekstiviesti numeroon-kenttään asiakastiedot tallentaessa tänään tiketin https://github.com/KohaSuomi/Koha/issues/204 töiden yhteydessä.

**Comment by LeenaKinnunen** [comment]
Korjaus toimii. Suljen tiketin.
