### ISSUE TITLE
Saako Kohan yläreunaan lisättyä linkkejä alasvetovalikko-tyyliin?

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#318]
### Tukipyyntö

Onko Kohan yläreunan itse lisätyt linkit mahdollista lisätä alasvetovalikko-tyyliin kuten esim. Kohan Muita toimintoja -toteutus.
Pienemmillä näytöillä Hellen linkkirivissä tungosta ja osa linkeistä sotkeentuu toisiinsa.
Linkkien määritysasetus: IntranetNav

Helle-Kohan yläreunalinkit
![kuva](https://user-images.githubusercontent.com/99952449/208873573-59718c21-40c9-4f52-99f9-a3fe0af4d2ab.png)

Kohan Muita toimintoja -alasvetovalikko
![kuva](https://user-images.githubusercontent.com/99952449/208874992-409e47a8-027d-4fe3-9431-01a09e4d04af.png)

**Comment by lmstrand** [comment]
Lisäsin Hellen testille IntranetNav -asetukseen alasvetovalikkoversion noista teillä tuotannossa olleista linkeistä. Toimii seuraavan rakenteen kanssa ihan ok (Lisäsin huumorilla Finto-AI:llekin linkin kun vaikutti olevan ihan pätevä työkalu, saa poistaa :) 
):

```
<li class="dropdown">
  <a href="/cgi-bin/koha/mainpage.pl" class="dropdown-toggle" data-toggle="dropdown">Koha-Suomi-linkit <b class="caret"></b></a>
  <ul class="dropdown-menu dropdown-menu-left">
    <li><a href="https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/news" target="_uutiset">Koha-uutiset</a></li>
    <li><a href="https://tiketti.koha-suomi.fi" target="_ksredmine">Koha-Suomi Redmine</a></li>
    <li><a href="https://helle.finna.fi" target="_finna">Helle-Finna</a></li>
    <li><a href="https://helle-extranet.fi" target="_finna">Helle-Extranet</a></li>
    <li><a href="https://finto.fi/fi/" target="_finto">Finto</a></li>
    <li><a href="https://ai.finto.fi/?locale=fi" target="_finto">Finto-AI</a></li>
  </ul>
</li>
```

**Comment by lmstrand** [comment]
Linkit, jotka haluaa säilyvän omina erillisinä näkyvissä olevina linkkeinään, voi jättää tuon ripsun ulkopuolelle.

**Comment by Kati-Helle** [comment]
Hienoa että onnistuu, kiitos Lari!

Saisiko Kohan 'oman' Muita toimintoja -linkin alasvetovalikkoineen ennen IntranetNav-asetukseen lisättyä Koha-Suomen linkit-alasvetovalikkoa linkkeineen? 
![kuva](https://user-images.githubusercontent.com/99952449/208894208-e5b7289f-22a4-45da-a451-697df6db6d86.png)

Poistin tähän hetkeen Finto-AI-linkin. Toiminto toki pätevöitynyt/kehittynyt. Katsotaan ensin, mitä mieltä Helle-kuvailijat tuosta ovat.

Testailen vielä, olisiko tarpeeksi tilaa niin, että Koha-sivut olisivat omassa/samassa alasvetovalikossa ja muut omina linkkeinään.

**Comment by lmstrand** [comment]
Lisäämällä listaelementille id:n esim. <li  id="kohasuomi-navlinkit" class="dropdown"> ja käyttämällä seuraavaa intranetuserjs:ää:

```
$( "#kohasuomi-linkit" ).insertAfter( $( "#kohasuomi-linkit" ).next() );
```
onnistui tuon alasvetovalikon siirtäminen viimeiseksi.
Lisäsin muutoksen Helle-testille.

ps. Tuotantoihin ei voi lisätä intranetUserJS-asetukseen sisältöä ilman kehittäjää (Koha lukkiutuu).

**Comment by Kati-Helle** [comment]
Kiitos, Lari.!
Helle-Kohan ylärivilinkit ovat nyt siististi näin:

![kuva](https://user-images.githubusercontent.com/99952449/209069491-db3d981c-e141-4c6d-9c4e-482e1fcce4f5.png)

En vaihda asetusta vielä Helle-tuotantoon. Sovitaan tarkempi toteutusajankohta, kun tiedän milloin toteutuksen voi tehdä.  Helle-Koha-käyttäjille tiedotettava ennen toteutusta.

Kun uusi ylärivilinkitys on tuotannossa käytössä, IntranetNav-asetuksen tietoja voinee muuttaa ilman, että Koha-käyttö katkeaa? Vai miten onkaan?

**Comment by lmstrand** [comment]
"IntranetNav-asetuksen tietoja voinee muuttaa ilman, että Koha-käyttö katkeaa? "
Juu, kyllä voi muuttaa tuotantoon ilman, että katkeaa. Ilmoittele sitten, kun haluatte intranetUserJS-rimpsun alasvetovalikon siirtoon tuotantoon lisättäväksi.

**Comment by Kati-Helle** [comment]
> "IntranetNav-asetuksen tietoja voinee muuttaa ilman, että Koha-käyttö katkeaa? " Juu, kyllä voi muuttaa tuotantoon ilman, että katkeaa. Ilmoittele sitten, kun haluatte intranetUserJS-rimpsun alasvetovalikon siirtoon tuotantoon lisättäväksi.

Kävisikö rimpsun lisäys ensi viikolla torstai-aamuna 29.12.2022 tai perjantai-aamuna 30.12.2022?

(Lisäsin testatessani rimpsuun vielä yhden Koha-linkin eli Tiketit)
![kuva](https://user-images.githubusercontent.com/99952449/209307254-30d36f71-a131-4dc5-abce-4a2c586c176b.png)

**Comment by Kati-Helle** [comment]
Sovittu tänään Larin kanssa toteutusajankohdaksi tiistai 10.1.2023.

**Comment by MikkoLiimatainen** [comment]
Eikös tuo JS ole tässä tarpeeton? Jos tuon lista-elementin luokaksi laittaa pull-right, niin sehän siirtää nämä IntranetNav linkit Muita toimintoja pudotusvalikon oikealle puolelle.
<li class="dropdown pull-right">

**Comment by lmstrand** [comment]
Tuo näyttää toimivan. Kiitos vinkistä, @MikkoLiimatainen . @Kati-Helle voitkin itse laittaa tuon sitten kuntoon kun haluat. Eli tuo "pull-right" siihen enimmäiselle riville Mikon tapaan.

**Comment by Kati-Helle** [comment]
@lmstrand Lisäsin Mikon rimpsun asetuksen alkuun. Hellessä Koha-Suomi-linkit menevät väärään kohtaan eli ennen Kohan Muita toimintoja -linkkejä. (Testissä toimii ok.) Mikä avuksi?

![kuva](https://user-images.githubusercontent.com/99952449/211472073-88cbe99d-ee2a-4bdb-8a93-af8b25a25c25.png)

**Comment by Kati-Helle** [comment]
Tämä nyt kunnossa ja käytössä. Suljen tiketin.

**Comment by AnneliO** [comment]
Tulevaisuutta varten: mikä tässä oli vikana eli miten viimeisin ongelma korjattiin? :)

**Comment by Kati-Helle** [comment]
> sieltä puuttui riviltä 4 tuo class="dropdown pull-right".
> 
> ```
> <li id="kohasuomi-navlinkit">
> ->
> <li id="kohasuomi-navlinkit" class="dropdown pull-right">
> ```

Eli minä olin lisännyt Mikon rimpsun asetuksen alkuun ensimmäiseksi eli väärään kohtaan.

**Comment by Kati-Helle** [comment]
Lisäsin Finto-AI-linkin Helle-Kohan yläreunan rimpsuvalikkoon. Finto on nyt Kohan yläreunassa alasvetovalikkona ja alasvetovalikosta valittavissa Finto JA Finto-AI. 

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0e0ee3b3-66c8-43e3-a4c6-89e3c5691713)

Hellen IntranetNav-asetuksen rimpsuna nyt tämä:

<li class="dropdown pull-right">
 <li id="finto-navlinkit" class="dropdown pull-right">
  <a href="/cgi-bin/koha/mainpage.pl" class="dropdown-toggle" data-toggle="dropdown">Finto <b class="caret"></b></a>
  <ul class="dropdown-menu dropdown-menu-left">
<li><a href="https://finto.fi/fi/" target="_finto">Finto</a></li>
<li><a href="https://ai.finto.fi/?locale=fi" target="_finto">Finto-AI</a></li>
</ul>
<li class="nav navbar-nav pull-right"><a href="https://helle-extranet.fi" target="_extranet">Extranet</a></li>
<li class="nav navbar-nav pull-right"><a href="https://helle.finna.fi" target="_finna">Finna</a></li>
<li id="kohasuomi-navlinkit" class="dropdown pull-right">
  <a href="/cgi-bin/koha/mainpage.pl" class="dropdown-toggle" data-toggle="dropdown">Koha-Suomi <b class="caret"></b></a>
  <ul class="dropdown-menu dropdown-menu-left">
    <li><a href=" https://koha-suomi.fi/dokumentaatio/ohjeet/" target="_ohjeet">Koha-ohje</a></li>
<li><a href=" https://github.com/KohaSuomi/Koha/discussions/categories/tiedotteet" target="_tiedotteet">Tiedotteet</a></li>
<li><a href=" https://koha-suomi.fi/muistiot" target="_muistiot">Muistiot</a></li>
<li><a href=" https://github.com/orgs/KohaSuomi/projects/4" target="_tiketit">Tiketit</a></li>      
      </ul>
</li>
