### ISSUE TITLE
Palautuksessa jonossa toisena ollut varaus kiilasi jonon ensimmäisen ohi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#328]
### Mikä vikana?

Tietueeseen 2690556 on tehty kolme varausta, joista jonon ensimmäisenä on ollut ekana (9.12.) tehty varaus reserve_id:llä 1416782.

Kun tietueen nide 1528285 on palautettu 20.12.2022 16:52, on se tärpännyt kuitenkin jonossa toisena olleeseen varaukseen (reserve_id 1433387).

Kummankaan varauksen muutoslokeista ei löydy merkkejä siitä, että varauksia olisi muokattu, joten niteen olisi kaiken järjen mukaan pitänyt tärpätä ensin tehtyyn varaukseen 1416782.

Ainoastaan yksi asia pistää reserves-taulusta silmään - kolmantena tehty varaus 1439818 on timestampin mukaan tallennettu samalla sekunnilla kuin milloin nide 1528285 on palautettu. Onko mahdollista, että samanaikaisesti tapahtunut varauksen tallennus olisi sotkenut varausjärjestyksen ja palautettu nide olisi sen takia tärpännyt väärään varaukseen?

### Mitä pitäisi tapahtua

Niteen 1528285 olisi pitänyt tärpätä varaukseen 1416782.

**Comment by AnneliO** [comment]
Liittyneekö build_holds_queue -skriptiin? Tai Plackin cacheen?

Seurataan, tuleeko vastaavia tapauksia Vaskissa tai muissa kimpoissa. Kirjatkaa tähän uudet tapahtumat.

**Comment by MikkoLiimatainen** [comment]
Nextilläkin vaikuttaisi olevan sama ongelma. Tietueen [4268083](https://vaski-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=4268083) niteen palautuksessa varaus tärppää jonossa toisena olevaan varaukseen. Ensimmäisenä oleva varaus vaikuttaa olevan aivan normaali, mutta se vaan ei tärppää.

**Comment by janPasi** [comment]
Voisi ehkä olla cacheongelma, kuten Anneli tuossa ehdotteli. Joko Plack tai memcached.

**Comment by janPasi** [comment]
Ei ollut cache-ongelma, Emmi kokeili tyhjentää cachet ja ongelma on edelleen olemassa.

**Comment by emta001** [comment]
Saattaa liittyä yhteisön tikettiin [33761](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33761). Tuodaan tämä korjaus testeille ja katsotaan toistuuko ongelma.

**Comment by MikkoLiimatainen** [comment]
En ole onnistunut tätä ongelmaa toistamaan Nextillä. Tosin redusoidun tietokannan takia varausjonot eivät välttämättä ole aina oikein, kun jäljelle jääneiden varausten jononumerot voivat olla esim. 481 ja 541 ja tietueen varausjonossa molemmat varaukset näyttävät olevan jononumerolla 1. Nämäkin ovat näyttäneet kuitenkin tärpänneen todellisen jononumeronsa mukaisesti, joten kyse lienee vain visuaalisesta ongelmasta varausjonossa. Kaikissa tilanteissa jonon pienimmän prioriteetin aktiivinen varaus tärppää. Yritin myös tuon tiketin 33761 perusteella tärppäillä kuljetuksessa olevia niteitä, ei kuljetettavana olevia niteitä, kuljetukseen tärppääviä niteitä ja niteitä toisista sijaintikirjastoista saadakseni aikaan ongelmia, mutta kaikki toimi kuten pitääkin.

**Comment by ajrajala** [comment]
Uusista tapauksista ei ole raportoitu. Pitäisikö tiketti sulkea ja avata sitten uudelleen jos ongelma tulee vastaan?

**Comment by AnneliO** [comment]
> Uusista tapauksista ei ole raportoitu. Pitäisikö tiketti sulkea ja avata sitten uudelleen jos ongelma tulee vastaan?

Joo, voisi tehdä niin. Ja koittaa muistaa linkittää se uusi vaikka sitten tähän suljettuun. :)
