### ISSUE TITLE
Asiakkaan Ilmoitukset-välilehden Toimitushuomautus-sarakkeeseen oikea tieto epäonnistumisen syystä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#329]
### Kehitysehdotukseni

Tällä hetkellä asiakkaan Ilmoitukset-sivulla näkyy sarake delivery_note (jota ei kait pysty piilottamaan näkyvistä Taulujen asetukset -sivulla), johon tulee epäonnistuneista lähetyksistä ainoana tietona teksti "Virhe sähköpostia lähetettäessä".

Olisi kätevää, jos tuon nykyisen tiedon sijaan käyttäjä näkisikin oikean failure_coden silloin kun lähetys on epäonnistunut. (Vaskissa virkailijoita varten on tällä hetkellä tehtynä erillinen raportti, jolla failure_coden voi tarkistaa kun selvitetään syytä tekstiviestilähetyksen epäonnistumiselle.)

**Comment by AnneliO** [comment]
Samaa asiaa [Redmine-tiketissä 5572](https://tiketti.koha-suomi.fi/issues/5572).

**Comment by pknuuti** [comment]
Emmin kommentti Redminessä: 
Kyseessä on tavallaan ohjelmavirhe. Kun kannasta katsoo, kyseisen asiakkaan viestissä lukee failure_code-sarakkeessa "Recipient phone number is invalid or unknown". Kohan koodissa kuitenkin käsitellään nämä failure_codet seuraavasti:

[% IF ( QUEUED_MESSAGE.failure_code ) %]
  [% IF ( QUEUED_MESSAGE.failure_code == "INVALID_BORNUMBER" ) %]Invalid borrowernumber [% borrowernumber | html %]
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'NO_EMAIL' ) %]Unable to find an email address for this borrower
  [% ELSIF (matches = QUEUED_MESSAGE.failure_code.match('INVALID_EMAIL:(\w+)') ) %]Invalid [% matches.0 | html %] email address found [% borrowernumber | html %]
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'NO_FROM' ) %]Missing from email address
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'MISSING_SMS' ) %]Missing SMS number
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'DUPLICATE_MESSAGE' ) %]Message is duplicate
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'NO_NOTES' ) %]No notes from SMS driver
  [% ELSIF ( QUEUED_MESSAGE.failure_code == 'SENDMAIL' ) %]Unhandled email failure, check the logs for further details
  [% ELSIF ( QUEUED_MESSAGE.failure_code == "UNKNOWN_ERROR" ) %]Unknown error
  [% ELSE %]Error occurred while sending email.
  [% END %]
[% END %]

Koska "Recipient phone number is invalid or unknown" ei vastaa yhtäkään yllä olevista if-elsif-ehdoista eikä failure_codea tulosteta suoraan Kohaan, Koha käyttää else-ehdon "Error occurred while sending email.". Viesti saataneen kyllä Kohaan, mutta se kuinka se tehdään niin, että viesti on käännettävissä voi olla hieman monimutkaisempi toteuttaa.

"Laitan tämän kommentoitu tilaan, katsellaan jossain välissä paremmin mitä tälle tehdään."

Suljen Redminen tiketin.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 5.2.2024: Ei edistetä itse, tehdään tiketti yhteisön Bugzillaan.

**Comment by ajrajala** [comment]
Varmistan vielä ennen kuin teen Bugzillaan tiketin, että onko varsinainen tarve siis se että tuolla asiakkaan ilmoituksissa failure_code -käsittelyn ehtoihin joko pystyisi lisäämään sieltä nyt puuttuvia ehtoja tai sitten delivery note -sarake näyttäisi suoraan failure_coden?

**Comment by ajrajala** [comment]
Huomasinkin, että tuo yllä oleva kysymys ei varmaan @emta001 tavoittanut, joten tägäänpä Emmin vielä tähän ketjuun.

**Comment by emta001** [comment]
> Varmistan vielä ennen kuin teen Bugzillaan tiketin, että onko varsinainen tarve siis se että tuolla asiakkaan ilmoituksissa failure_code -käsittelyn ehtoihin joko pystyisi lisäämään sieltä nyt puuttuvia ehtoja tai sitten delivery note -sarake näyttäisi suoraan failure_coden?

Sanoisin, että ensimmäinen vaihtoehto on se lähemmin oikea mitä tässä haetaan.

**Comment by ajrajala** [comment]
Yhteisöön tehty tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36487.

**Comment by ajrajala** [comment]
Tähän on tainnut tulla muutos versiossa 24.05. Nyt epäonnistuneen tekstiviestin kohdalla asiakkaan Ilmoitukset-välilehdellä näkyy Toimitushuomautus-sarakkeessa esim. "Viestin lähetys epäonnistui seuraavan virheen vuoksi: undeliverable (Illegal Subscriber)."

**Comment by AnneliO** [comment]
Olisiko tämä siten niin sanotusti korjaantunut ja tiketin voisi sulkea? :)

**Comment by ajrajala** [comment]
Joo, kävin ensin kirjoittelemaan kommenttia tuonne yhteisön tikettiin minkä tästä olin tehnyt. Suljenko myös tuon yhteisön tiketin kun siihen ei ole edes ehtinyt keneltäkään mitään vastausta tulla?
