### ISSUE TITLE
Tietueelta putoaa 942c-kenttä z39.50-haulla tietueita yhdisteltäessä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#332]
### Mikä vikana?

Tietueella entuudestaan ollut aineistolaji suojatuksi merkityssä 942c-kentässä näkyy tyhjänä z39.50-haulla tieteueita yhdisteltäessä eikä tietueen tallentaminen onnistu ilman, että aineistolajin käy valitsemassa uudelleen.

### Mitä pitäisi tapahtua

Olemassa olevan tietueen aineistolajin pitäisi säilyä myös z39.50-haulla tietueita yhdisteltäessä.

### Jotain muuta?

Siirretty tiketistä https://tiketti.koha-suomi.fi/issues/5500

**Comment by AnneliO** [comment]
Testaatko Anni, toistuuko tämä ongelma versiossa 22.11?

**Comment by ajrajala** [comment]
Näköjään ei pysty testaaamaan, koska z39.50-haku ei toimi. Herjaa yhteyden palvelimeen localhost epäonnistuneen.

**Comment by AnneliO** [comment]
Testailin Kirkeksen konversion/käyttöönoton vuoksi MARC-yhdistelysääntöjä kirkes-testillä ja samoilla säännöillä kuin Vaskin testillä oletuskuvailupohjalla 942c-kentän sisältö sekä näkyi että säilyi z39.50-haun kautta tietueen korvatessa.

Oletuspohjassa ei ole 942c-kentässä mitään oletusarvoja, eikä niiden lisääminen vaikuttanut toimivuuteen/näkyvyyteen.

Vaski-testillä kenttä on tyhjä ja tieto katoaa, jos sitä ei valitse uudelleen. Hmmh.

**Comment by ajrajala** [comment]
Testasin tätä testillä enkä meinannut saada ensin ongelmaa enää toistettua kunnes sitten tietueella https://vaski-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=305509 ongelma ilmeni:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/8197bfa6-1fe8-475a-93a5-0b45a2f49a9c)

Kokeilin saman tietueen korvaamista tuotannossa ja siellä ongelmaa ei ole:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/c6da6e2d-b462-4038-9ca5-510ded37694c)

Pyysin kuvailijoita vielä seurailemaan tuleeko näitä tapauksia tuotannossa vastaan. Hyvin pian ilmaantui ensimmäinen, https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/MARCdetail.pl?biblionumber=4303951.

Korvatessa tietuetta näyttää käytössä olevan aina oletuspohja, sekä testillä että tuotannossa. Testiympäristössä havaitussa tapauksessa (eka kuva, tietue 305509) paikalliskannan alkuperäisellä tietueella näytti olevan käytössä Kirja-pohja. Tuotannossa havaitussa tapauksessa (tietue 4303951) käytössä on sen sijaan oletuspohja. En kyllä keksi mikä tässä mättää.

**Comment by AnneliO** [comment]
Ainakin sellainen ero näyttäisi olevan, että testillä kirja-pohjassa on 942c-kenttää määritetty oletusarvoksi KIRJA, tuotannossa ei ole 942c-kentällä oletusarvoa. Mutta sillä ei näyttänyt minun aiemmissa testeissä olleen merkitystä.

**Comment by emta001** [comment]
Onko tämä vielä ongelma?

**Comment by ajrajala** [comment]
Anna testasi tätä vielä uudelleen. Virhettä ei saatu enää toistettua sillä testimateriaalilla mitä oli käytössä. Vaskissa saatiin viime viikolla käyttöön liitännäinen, joka ottaa tietuetta siirrettäessä automaattisesti oikean kuvailupohjan käyttöön, joten olisikohan tämä ongelma poistunut kokonaan sen myötä. Suljen tiketin.
