### ISSUE TITLE
Z39.50-tietueyhdistelyssä suojatut kentät eivät ole muokattavissa/poistettavissa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#333]
### Mikä vikana?

Tietueiden yhdistämissäännöt -asetuksessa voi määritellä MARC-kenttä/kentät, jotka säilyvät tietueyhdistelyissä.

Esimerkissä 653-kenttä, jonka yhdistämissäännöt Helle-Kohassa näin
![kuva](https://user-images.githubusercontent.com/99952449/209793320-260289e6-ac8c-4882-a348-14de789d347a.png)

Z39.50-tietueyhdistelyn ja tietueen tallennuksen jälkeen tietueella on edelleen yhdistelysäännöissä suojatut 653-kentät kuten tuleekin olla, mutta
       - 653-kenttiä ei saa muokattua (muokkaus tallentuu uutena kenttätoistumana ja muokattu kenttä säilyy ennallaan)
       - 653-kenttiä ei saa poistettua

Tietueelle saa lisättyä uuden 653-kentän/kenttätoistuman, mutta
       - tietueelle tallennettua uutta 653-kenttää ei saa poistettua 
       - tietueelle tallennetun uuden 653-kentän muokkaus ei tallennu, vaan muokatusta arvosta muodostuu tietuetallennuksessa uusi 653-kenttätoistuma

Kuva:
- tietueyhdistelyssä säilyneet 653-kentät suuraakkosin 
- tietueelle tietueyhdistelyn jälkeen lisätty kenttä 653a=personhistoria
        - kenttää muokattu poistamalla viimeinen a-kirjain -> tietuetallennuksessa muokatusta arvosta muodostui uusi 653-kenttätoistuma 653a=personhistori ja muokattu 653a=personhistoria-kenttä säilyi ennallaan/muuttumattomana.

![kuva](https://user-images.githubusercontent.com/99952449/209791879-39ca2786-a7d9-4163-bcc1-2d46e959fc21.png)

### Mitä pitäisi tapahtua

Tietueyhdistelyssä suojattujen MARC-kenttien tulisi olla muokattavissa ja poistettavissa kuten muidenkin tietueen MARC-kenttien.

**Comment by Kati-Helle** [comment]
Samasta aiheesta Redmine-tiketissä https://tiketti.koha-suomi.fi/issues/5550

**Comment by Kati-Helle** [comment]
Kentän suojaus vaikuttaa myös toimintoon Työkalut/Tietueiden muokkaus eräajona. Yritin poistaa toiminnolla tiketissä mainitun tietueen 653a-kentät - ei onnistunut.

Lisätestausta tietueella jonka aikaleima on ajalta ennen uutta versiota (ja uusia yhdistelysääntöjä).
Helle-tietueen biblionumber=1019987 kenttä 005 
![kuva](https://user-images.githubusercontent.com/99952449/209941752-e056739f-22cd-4295-b0be-97c1d56fd1d1.png)

Tietueella on mm. nämä kentät
![kuva](https://user-images.githubusercontent.com/99952449/209941294-5a7d9034-9036-476b-aa86-11b745915a73.png)

poistetaan tietueen 521a-kenttä
![kuva](https://user-images.githubusercontent.com/99952449/209941340-e784828c-4375-4a1f-86fa-8c41cee90230.png)

muokkaustoiminnon Näytä Marc -esikatselussa näkyy, että kenttä poistuu
![kuva](https://user-images.githubusercontent.com/99952449/209941402-f43f97e3-e5f6-421a-8e1f-03358f7eba46.png)


poistetaan tietueen 653a-kenttä
![kuva](https://user-images.githubusercontent.com/99952449/209941455-3349b169-e7d7-4622-b68b-419ea8183a62.png)

muokkaustoiminnon Näytä Marc -esikatselussa näkyy, että kenttä ei tule poistumaan
![kuva](https://user-images.githubusercontent.com/99952449/209941503-621ceb70-ffd2-40aa-8c22-a2e7d30d4c48.png)

**Comment by AnneliO** [comment]
@Kati-Helle tässä tiketissä on kaksi eri asiaa, jaatko ne kahteen eri tikettiin? :)

**Comment by Kati-Helle** [comment]
> @Kati-Helle tässä tiketissä on kaksi eri asiaa, jaatko ne kahteen eri tikettiin? :)

Toinen asia on nyt täällä https://github.com/KohaSuomi/Koha/issues/481

**Comment by AnneliO** [comment]
@Kati-Helle onko tämä ongelma edelleen olemassa?

**Comment by Kati-Helle** [comment]
Ongelmaa ei enää ole. Kiitos Anneli tämän avoimeksi jääneen tiketin vinkkaamisesta :)

Hellen Marc-tietueiden yhdistämissäännöistä on äskettäin poistettu suodatussääntötyyppi * (oli käytössä kentillä 653 ja 856)
Mainittu tiketissä https://github.com/KohaSuomi/Koha/issues/481
