### ISSUE TITLE
Error 500 tilauksen vastaanotossa

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#334]
### Mikä vikana?

Joidenkin tilausten vastaanottoa ei voi avata, vaan Koha kuolee 500 virheeseen. Lokeihin kirjautuu Template error:

"Template process failed: undef error - The method Koha::Item->count is not covered by tests!"

Virheilmoitus viittaa template orderreceive.tt:ssä olevaan [% IF (order.items.count) %].

**Comment by AnneliO** [comment]
Tätä on vaikea testata, joten viedään tuotantoon. Ilmoitelkaa heti, jos tulee ongelmia vastaanotossa päivityksen jälkeen.
