### ISSUE TITLE
 Siirtoraportti-liitännäiseen vieraillut linkit eri väriseksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#339]
### Kehitysehdotukseni

[Redmine-tiketti 5276](https://tiketti.koha-suomi.fi/issues/5276)

Anneli Österman 18.2.2022

Saisiko Siirtoraportti-liitännäiseen sellaisen muutoksen, että tietue-linkit muuttuisivat toisen väriseksi sen jälkeen, kun käyttäjä on klikannut niitä?

--

**Koha-Suomen asiantuntijaryhmän päätös 14.11.2022:** Tutkitaan, onko toteutettavissa. 

Tutkitaan samalla, voiko Avaa-nappulan värin muutettua, jos sitä on klikattu.

**Comment by lmstrand** [comment]
Tämä ominaisuus on lisätty testeille testattavaksi. Myös onnistuneiden Avaa-nappi muuttaa klikattuna väriä.

**Comment by Kati-Helle** [comment]
Helle-testissä testatessani vierailtu linkki ja vierailtu Avaa-nappi tummansinistyivät
![kuva](https://user-images.githubusercontent.com/99952449/215424845-113aa14a-af81-4c12-8800-3211691e1a82.png)

**Comment by ReettaSiili** [comment]
Siili-testissä toimi. Sivulle palatessa linkit olivat edelleen eri väriset mutta Avaa-nappi oli palautunut vaaleaksi. Pitiköhän näin ollakin, en tiedä.

**Comment by lmstrand** [comment]
Jos se data haetaan uudelleen, tuo "katseltu"-tieto nollautuu. Tuon voi kiertää käyttämällä toista välilehteä muiden raporttien tarkkailuun ja pitää tuon onnistuneet-näkymän omassaan. Tosin tällöin data on vanhaa, kun näkymää ei päivitä (jolloin katsellut muutosnapit katoaisivat). Ominaisuutta tosin voisi ehkä jatkokehittää, mutta vaatisi paljon lisää Vue.js:n tutkiskelua ja uudelleenkoodaamista. Mennään tällä toistaiseksi.

**Comment by AnttHeik** [comment]
OUTissa toimii myös hyvin.

**Comment by AnneliO** [comment]
Toiminto lisätty kaikille kimpoille vkon 5 päivityksessä.

**Comment by piiaseme** [comment]
Saisiko tämän ominaisuuden versioon 24.05?

**Comment by AnneliO** [comment]
Siirtoraportti-liitännäistä ei enää ole olemassa, sen korvasi Tietuesiirtäjä. Testasin Tietuesiirtäjä-liitännäistä ja siellä tietuelinkki muuttuu eri väriseksi, kun sitä on klikattu, mutta Avaa-nappi ei vaihda väriä.

**Comment by piiaseme** [comment]
Olisiko Avaa-napin värin vaihtuminen mahdollista? Sitten paremmalla ajalla, kun tämähän ei ole kiireellinen :)
Varmaan oma tiketti olisi hyvä, kun eri liitännäisestä kyse?

**Comment by johannaraisa** [comment]
Tarkennan vielä, että muutos on nexteillä. Tulee sitten päivityksessä.

**Comment by piiaseme** [comment]
Testattu OUTIn nextillä. Väri vaihtuu, kiitos :)

**Comment by MikkoLiimatainen** [comment]
Testattu toimivaksi Vaskin tuotannossa.

**Comment by Kati-Helle** [comment]
Hellessäkin toimii
- vierailu Avaa-painikkeesta -> painikkeen väri muuttuu vaaleansinisestä tummansiniseen
- vierailu tietuenumerosta -> tietuenumeron väri muuttuu sinisestä vihreään

![kuva](https://github.com/user-attachments/assets/a085bc0a-b04d-4419-8a75-3e5c095872ae)

**Comment by AnneliO** [comment]
Linkit muuttuvat taas tuotannossa eri väriseksi. Suljen tiketin.
