### ISSUE TITLE
Pikahakuun poistoruksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#341]
### Kehitysehdotukseni

[Redmine-tiketti 5307](https://tiketti.koha-suomi.fi/issues/5307)

Piia Semenoff 24.3.2022

Pika-haussa hakukenttään naputettu tai vedetty tieto säilyy tiedonhaun ajan ja kentän saa tyhjäksi joko deletoimalla tai siirtymällä kokonaan eri sivulle jotain (esim. Etusivu-) linkkiä klikkaamalla. Voisiko hakulaatikon yhteyteen saada poisto/tyhjäys-ruksin?

--

**Koha-Suomen asiantuntijaryhmän päätös 14.11.2022:** Kehitys yhteisössä.

Sitä ennen ohjeistetaan miten tupla- ja triplaklikkauksella saa kentän tiedot valittua.

**Comment by emta001** [comment]
Pitäiskö tätä testata uudessa versiossa ja sitten yhteisön sandboxissa?

**Comment by AnneliO** [comment]
Versiossa 22.11 on uusi järjestelmäasetus  RetainCatalogSearchTerms -jossa voi valita tyhjennetäänkö pikahaun kenttä vai ei. Riittäisikö tämä asetus vai tarvitaanko vielä lisäksi tyhjennysmahdollisuus?

**Comment by AnneliO** [comment]
Lisäsin tiketin pääkäyttäjien vkon 38 listalle pohdittavaksi.

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 20.9.2023: Yhteisön kehitys tältä osin on riittävä. Suljetaan tiketti.
