### ISSUE TITLE
 Make the SELECT query in check-url-quick.pl non-blocking

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#343]
### Kehitysehdotukseni

[Redmine-tiketti 4892](https://tiketti.koha-suomi.fi/issues/4892)

Joonas Kylmälä 19.5.2021

It appears that check-url-quick.pl does a SQL query "SELECT biblionumber FROM biblioitems ORDER BY biblionumber" and only closes it after checking all the links in all the records. If I'm not mistaken this only seems to work currently without causing any database locking because all the biblionumbers are fetched in the beginning to cache due to just biblionumbers not taking that much memory. However, if we had a bigger amount of biblios and couldn't fetch all at once wouldn't we lock the biblios table here and prevent updates from happening?

--

**Koha-Suomen asiantuntijaryhmän päätös 14.11.2022:** Edistetään yhteisössä

**Comment by emta001** [comment]
Koha-Suomen palaveri 2.12.2024: Kukaan ei ole kaipaillut tätä ominaisuutta, joten suljetaan tiketti.
