### ISSUE TITLE
Helle: tietueettomat aineistotilaukset

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#344]
### Mikä vikana?

Löysin Hellestä tänään 473 Tilattu-tilaista (ordered) aineistotilausta, joista puuttuu nimeketieto (biblionumber puuttuu).
TIlaukset ovat ajalta 18.2.2018-22.12.2022. Lähes kaikki tilaukset ovat tyyppiä EditxShipNotice TAI portaali_order

Tietoja 22.12.2022 (timestamp 22.12.2022  12:35:17) muodostuneesta Tilattu-tilaisesta tilauksesta ilman tietuetta/teostietoja. Tämä on tänään löytyneistä tietueettomista tilauksista viimeisin.

Kohan ordernumber=193812
Tilaus sisältyy tilaussanomaan: portaali_order_20221222123306.xml

Tilaus on tilaussanoman ensimmäinen. Tilaussanomassa on mm. nämä tiedot
 <ItemDetail> <LineNumber>1</LineNumber> <ProductID> <ProductIDType>EAN13</ProductIDType> <Identifier>9789164208545</Identifier> </ProductID> <ProductID> <ProductIDType>ISBN</ProductIDType> <Identifier>978-91-642-0854-5</Identifier> </ProductID> <ItemDescription> <ProductForm>BK</ProductForm> <Title>Järnviljan.</Title> <Author>Lindfors, Jacob|kirjoittaja</Author> <SeriesTitle></SeriesTitle> <VolumeOrPart/> <EditionStatement/> <CityOfPublication>Stockholm</CityOfPublication> <PublisherName>Piratförlaget</PublisherName> <YearOfPublication>2023</YearOfPublication> </ItemDescription> <QuantityShipping>1</QuantityShipping> <PricingDetail> <Price> <MonetaryAmount>21.16</MonetaryAmount> <CurrencyCode>EUR</CurrencyCode> <CountryCode>FI</CountryCode> <PriceQualifierCode>FixedRPIncludingTax</PriceQualifierCode> <Tax> <TaxTypeCode>VAT</TaxTypeCode> <Percent>10</Percent> </Tax> </Price> </PricingDetail> <PricingDetail> <Price> <MonetaryAmount>19.24</MonetaryAmount>

Hellestä ei löydy kyseistä teostietoa.
deletedbiblio-taulusta teostiedot löytyvät
![kuva](https://user-images.githubusercontent.com/99952449/209927117-06be9983-fdcb-4e3a-b016-48061a018cc5.png)

Tietueen biblionumber=1605673 lokitiedot
![kuva](https://user-images.githubusercontent.com/99952449/209927733-dab3163e-a991-4d30-85df-aa892d836d91.png)

**Comment by AnneliO** [comment]
Onko tässä siis samanlainen tilanne kuin tiketissä #300?

**Comment by Kati-Helle** [comment]
Samalta vaikuttaa. Tiketti 300 jäänyt minulta huomaamatta.
(Helle-tietueen 1605673 poistuminen Verkkokirjasto-käyttöliittymässä tosin ihmetyttää...)

Hellessä tietueettomia tilauksia on sekä tilatuissa että vastaanotetuissa (Yhteenvesto-sarake arvoton)
![kuva](https://user-images.githubusercontent.com/99952449/212054948-8630539a-39e7-43d5-b2ca-215d49e80bdd.png)

Tilauskori-näytöllä tilausrivi 123716 näyttää tältä
![kuva](https://user-images.githubusercontent.com/99952449/212055460-edaf2a05-8ec8-492f-b4b8-db9118ab53de.png)

**Comment by Kati-Helle** [comment]
Taitaa olla jotain muuta(kin?) kuin Annelin mainitsemassa tiketissä https://github.com/KohaSuomi/Koha/issues/300

Hellessä on tilattu-tilaisia tilauksia ilman tietuetta.
Tilauksen tilauskorissa ei ole samaa tilausta vastaanotettuna (kuten Vaskin tiketissä) ainakaan niiden tilausten osalta, joita tutkailin.
Suurin osa tänään löytämistäni 484 tietueettomasta tilauksesta on ennen vuoden 2022 versionvaihtoa. Tilauksista 16 on versionvaihdon jälkeiseltä ajalta (tilaukset muodostuneet 13.6.2022-5.1.2023).

Viimeisin tapaus on tilaussanomassa EditxShipNotice_id_2947164_20230105155640.xml 
entrydate=2023-01-05
ordernumber=194933
basketnumber=17195

Tietue löytyy deletedbiblio-taulusta
![kuva](https://user-images.githubusercontent.com/99952449/216609289-b333a6c1-dd6a-4a5e-8333-8271b0a366e0.png)

Tietueen lokitiedot (tietuepoiston käyttöliittymänä Verkkokirjasto)
![kuva](https://user-images.githubusercontent.com/99952449/216609421-6f054581-de81-48ef-b32e-3fb70cf8ecaa.png)


Tilauskorissa tilaus ordernumber=194933 on vain kerran ja tilauskorin viimeisenä. 
![kuva](https://user-images.githubusercontent.com/99952449/216609945-76b5f7d7-afdf-428c-8848-3a69a28afea8.png)

**Comment by AnneliO** [comment]
Testailin ongelmaa Hellen testillä ja luulen, että tuo tilanne on syntynyt niin, että vastaanottamattoman tilauksen tietue ja nide on poistettu niteiden poistossa eräajona. Eli nide on viety eräpoistoon ja valittuna on ollut täppä, että tietue poistetaan, kun viimeinen nide poistetaan.

Vastaavanlainen lokimerkintä tuli tietueelle 1592687:
![kuva](https://user-images.githubusercontent.com/33121325/216623006-3b58e8e4-ac6b-45b0-a78e-fc6187a683c1.png)

[Tilauskorissa](https://helle-test.koha-suomi.fi/cgi-bin/koha/acqui/basket.pl?basketno=13759) näyttää poiston jälkeen tältä:
![kuva](https://user-images.githubusercontent.com/33121325/216623328-53227b53-8510-4609-8de9-d7327e242461.png)

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta. Noin on tosiaan saattanut käydä.

Hain tietokannasta tietueettomiin tilauksiin liittyviä tietoja (tilausnumero, tilauspäivä, tilauskori, tili, tilin nimi). Lähetin tiedot kirjastoille, joilla tietueettomia tilauksia on. Tietueettomissa tilauksissa on tilauksia myös viime ja tältä vuodelta, joten lähetin kertauksena Koha-Suomen ohjeen tilauksen perumiseen.
