### ISSUE TITLE
OUTI: Tilapäisten virkailijatunnuksilta pois käyttöoikeuksia

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#346]
### Tukipyyntö

OUTIn tilapäisten virkailijatunnuksilta pitäisi ajaa pois käyttöoikeudet: discount, payout, refund ja suggestions_manage.

**Comment by emta001** [comment]
Näillä ei taida olla omaa käyttäjäryhmäänsä, olisko jotain muuta keinoa erotella nämä suoraan kannasta? Vai toimitatteko jonkin listan näistä?

**Comment by pirliis** [comment]
Ei ole omaa käyttäjäryhmää. Tunnuksia on yht. 163. Tunnukset on listattuna exceliin. Voisinko toimittaa excelin sinulle jotenkin? Tunnukset kyllä löytyy tietokannasta, kun rajaa asiakastyypiksi "Kirjaston työntekijä" ja "tilapäistunnus" (kaikilla sukunimikentässä).

**Comment by emta001** [comment]
> Ei ole omaa käyttäjäryhmää. Tunnuksia on yht. 163. Tunnukset on listattuna exceliin. Voisinko toimittaa excelin sinulle jotenkin? Tunnukset kyllä löytyy tietokannasta, kun rajaa asiakastyypiksi "Kirjaston työntekijä" ja "tilapäistunnus" (kaikilla sukunimikentässä).

No jos laitat vaikka elementsissä sen, voin sitten sen avulla tarkistaa että rajaus menee oikein.

**Comment by emta001** [comment]
Oikeudet poistettu seuraavalla loitsulla:

`DELETE FROM user_permissions WHERE code IN("discount", "payout", "refund", "suggestions_manage") AND borrowernumber IN(SELECT borrowernumber FROM borrowers WHERE categorycode = "VIRKAILIJA" AND surname LIKE "Tilapäistunnus%");`

**Comment by pirliis** [comment]
Tsekkasin tunnusten oikeuksia. Näyttäisi, että suggestions_manage -oikeus on poistunut, mutta maksujen hallintointiin liittyvät oikeudet ovat vielä paikallaan eli discount, payout ja refund.

**Comment by emta001** [comment]
> 



> Tsekkasin tunnusten oikeuksia. Näyttäisi, että suggestions_manage -oikeus on poistunut, mutta maksujen hallintointiin liittyvät oikeudet ovat vielä paikallaan eli discount, payout ja refund.

Hmm, niin tietysti. Kaikilla noilla tunnuksilla on ilmeisesti täydet updatecharges-oikeudet? Siksi noita ei ole tuolla user_permissions-taulussa. Pitää tuumata hetki ja kikkailla.

**Comment by emta001** [comment]
Kys. käyttäjien maksuoikeuksia muutettu poistamalla ensin kaikki updatecharges-oikeudet ja lisätty sitten writeoff- ja remaining_permissions-oikeudet.
