### ISSUE TITLE
Emottomien osakohteiden poisto ajona

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#348]
### Tukipyyntö

Todennäköisesti jokaisen kimpan tietokannassa on nyt emottomia osakohteita, koska versionvaihdon jälkeen osakohteet ei alkuunsa poistunut emon mukana. Sovittiin, että emottomat osakohteet poistetaan ajolla jossain sopivassa välissä.

[Tiketti siirretty Redminestä](https://tiketti.koha-suomi.fi/issues/5528).

**Comment by AnneliO** [comment]
Voisiko tästä tehdä säännöllisesti ajettavan siivousskriptin?

**Comment by AnttHeik** [comment]
Tämän ajon voisi tehdä TäTissäkin.

**Comment by pknuuti** [comment]
Tämä olisi todella tarpeen. Ja säännöllisesti ajettavaa siivousta kannatan.

**Comment by pknuuti** [comment]
Tämä siivousajo olisi järkevää tehdä ennen ISBD- ja RDA-konversioita. Ja sitten säännöllinen ajoskripti.

**Comment by pknuuti** [comment]
Tämä olisi kiva saada tehtyä, Vaarassa ainakin noita orpoja löytyy edelleen.

**Comment by AnttHeik** [comment]
Sama OUTIssa ja varmaan muissakin tietokannoissa.

**Comment by pknuuti** [comment]
Emottomien osakohteiden poistoajo tarvitaan seuraaviin tietokantoihin:
[x] TäTi
[ ] Helle
[ ] Kirkes
[ ] Kyyti
[ ] Lumme
[x] Outi
[ ] Siili
[x] Vaara
[ ] Vaski

**Comment by pknuuti** [comment]
Nyt on Vaaran emottomat poistettu erämuokkauksella Pasin laatiman raportin mukaisesti. Raportin mukaan pystyin vielä varmistamaan satunnaisotannalla, että kaikki nimekkeet olivat poiston tarpeessa eli emottomia osakohteita.

**Comment by Kati-Helle** [comment]
Hellessäkin.

**Comment by Kati-Helle** [comment]
Siis Hellessäkin tarvitaan. Toteutusta ei vielä (harhautin viestilläni :)

**Comment by ReettaSiili** [comment]
Samoin Siiliin pyydetään. Minulla ei ole kyllä käsitystä, mikä tilanne meillä näiden suhteen on.

**Comment by ElinaUotila** [comment]
Kirkesissäkin tarvitaan listaus.

**Comment by Kati-Helle** [comment]
Poistin Hellestä Pasin ilmoittamat emottomat osakohdetietueet. Poistettavia oli 17269.
Tarkistin ensin satunnaisotannalla poistettavaksi tarkoitettuja osakohdetietueita. Kaikki tarkistamani olivat emottomia.

**Comment by ElinaUotila** [comment]
Kirkesissäkin on nyt tarkistettu satunnaisotannalla Pasin toimittama listaus ja siivottu sen mukaan.

**Comment by pknuuti** [comment]
Nyt on TäTin emottomat osakohteet poistettu.

**Comment by AnttHeik** [comment]
Myös OUTIsta on nyt poistettu emottomat osakohteet.

**Comment by MerjaHakulinen** [comment]
Lumme pyytää myös listausta. Kai vielä ehtii näin myöhässä?

**Comment by Tuomas-Kyyti** [comment]
Kyytin emottomat osakohteet poistettu listan mukaan.

**Comment by annavii** [comment]
Vaskin emottomat on nyt poistettu

**Comment by AnneliO** [comment]
Onko vielä joku vailla listaa emottomista osakohteista vai joko tämän tiketin voisi sulkea? :)

**Comment by ReettaSiili** [comment]
Tämä asia seisoo edelleen Siilissä. Palaan asiaan uudella tiketillä kun asia on ajankohtainen :)

**Comment by AnneliO** [comment]
Ok. Suljen tämän tiketin. Jos joku muukin kuin Siili kaipailee vielä listaa, niin avatkaa siitä uusi tukipyyntö. :)
