### ISSUE TITLE
Osa taustatöistä ei valmistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#349]
### Mikä vikana?

Taustatöistä osa jää aloitettu tilaan, eivätkä koskaan valmistu. Aiemmin korjattiin virhe, jossa taustatyöt epäonnistuivat, jos yritettiin poistaa nidettä, jonka barcode oli jo deleteditems-taulussa. Tämä korjasi suurimman osan epäonnistumisista, mutta osa töistä jää edelleen valmistumatta. En ainakaan huomaa muuta yhteistä kuin että taustatyöt ovat niteiden poistoja. Itse niteissä ei minusta ole mitään erikoista.

Valmistumattomia taustatöitä on ainakin OUTIssa, Vaskissa ja Hellessä.

[Liittyvä tiketti Redminessä 5449](https://tiketti.koha-suomi.fi/issues/5449)

### Mitä pitäisi tapahtua

Taustatyöt pitäisi valmistua ja niteet poistua.

**Comment by AnneliO** [comment]
Tutkitaan, onko uudessa versiossa sama ongelma ja seurataan myös yhteisön kehitystä tämän suhteen.

Yhteisön tikettejä:
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32573

**Comment by janPasi** [comment]
Tässä näyttäisi että työt kyllä valmistuvat (tai epäonnistuvat), mutta valmistuminen (tai epäonnistuminen) ei tule merkityksi taustatyötauluun tietokannassa.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä näitä päättymättömiä on uuden version ajalta muutama kymmenen, kaikki indeksin päivityksiä. Päättyneiksi merkittyjä on tuhansia. Eli ylivoimaisesti valtaosa tulee merkityksi valmiiksi, mutta joitain jää merkitsemättä.

**Comment by ajrajala** [comment]
Samoin Vaskissa versiopäivityksen jälkeen keskeneräisinä näkyvät työt on kaikki indeksin päivityksiä.
Versiopäivitystä edeltävältä ajalta näkyy päättymättömiä niteiden poistoja 90 kpl.

**Comment by ajrajala** [comment]
Tiedoksi vielä, että maanantain 29.5. jälkeen ei Vaskissa näyttäisi jääneen enää edes noita Päivitä Elasticsearch-indeks -töitä.

**Comment by janPasi** [comment]
Korjaus on tehty tuotantoon, mutta vaatii vielä siivoilua vanhojen taustatöiden osalta.

**Comment by lmstrand** [comment]
Background_jobs-taulut siivottu vanhojen jumineiden started-tilaisten töiden osalta.
