### ISSUE TITLE
OUTI: SIP-tunnusten lisääminen palvelimelle

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#354]
### Tukipyyntö

Muutama SIP-tunnus, tarkemmat tiedot laitetaan salattuna Support-postiin. Saisitteko lisättyä tämän viikon aikana?

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle, ovat käytössä huomenna.

**Comment by velimarj** [comment]
Kiitokset, suljen tiketin.
