### ISSUE TITLE
Lumme: vanhentuneet varaukset eivät poistu - satunnainen mutta toistuva ongelma

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#356]
### Mikä vikana?

Vanhentuneet varaukset eivät aina poistu voimassa olevista varauksista. Eli noutamattomat varaukset kun palautetaan, niille tulostuu samalle asiakkaalle varauskuitti ja sama noutopäivä. Varauksen joutuu poistamaan käsin, lisäämään maksun ja palauttamaan ja sitten vasta lähtee seur. varaajalle. 

Mikkelissä käynyt viimeksi näin 5.1., esim. niteet HIR132750G (borrowernumber=168034) ja JO0U6467 ( borrowernumber=6471) ja 18.11 tätä tapahtui sitä edellisen kerran. Myös Punkaharjulta ja Kerimäeltä tullut viestiä tämmöisestä... eli se vanhentunut varaus jää jumiin sinne reserves-tauluun?

**Comment by AnneliO** [comment]
Tämän päivän pääkäyttäjäpalaverissa pohdimme, voisiko kyse olla siitä, että viimeiselle noutopäivälle on lisätty kalenteriin sulkupäivä sen jälkeen, kun varaus on jäänyt kiinni?

**Comment by Katja-Lumme** [comment]
> Onkohan näistä tarkempaa kellonaikaa tiedossa, sillä saisi rajattua lokeista onko niihin aikoihin kirjautunut jotain hassua.

14.16, ja 13.53 ja 16.58

**Comment by Katja-Lumme** [comment]
> Tämän päivän pääkäyttäjäpalaverissa pohdimme, voisiko kyse olla siitä, että viimeiselle noutopäivälle on lisätty kalenteriin sulkupäivä sen jälkeen, kun varaus on jäänyt kiinni?

Tuo 5.1. ei ollut sulkupäivä, eikä myöskään 18.11. jolloin tää on tapahtunut edellisen kerran...

**Comment by emta001** [comment]
> > Tämän päivän pääkäyttäjäpalaverissa pohdimme, voisiko kyse olla siitä, että viimeiselle noutopäivälle on lisätty kalenteriin sulkupäivä sen jälkeen, kun varaus on jäänyt kiinni?
> 
> Tuo 5.1. ei ollut sulkupäivä, eikä myöskään 18.11. jolloin tää on tapahtunut edellisen kerran...

Tulipa mieleen, kun lueskelin koodia, varauksethan vanhenevat vasta niiden vanhenemispäivää seuraavana päivänä? Koska croni ajetaan öisin 00.10 ja koodissa vanhetuneiksi varauksiksi lasketaan kaikki ne varaukset joiden expirationdate on pienempi kuin kuluva päivä. Silloin nuo 5.1. varaukset selittyisivät sillä, että 6.1. on ollut loppiainen ja varaukset eivät vanhene pyhinä, jos ymmärsin oikein.

**Comment by emta001** [comment]
Mitä tuolle 18.11. varaukselle sitten on käynyt niin en tiedä, ei ainakaan Mikkelin pääkirjaston kalenterissa ollut mitään kiinniolopäivää 19.11.

**Comment by emta001** [comment]
Tulipa mieleen, että olisihan tuon 5.1. varauksen kuitenkin pitänyt vanhentua sitten 7.1. tehdysssä ajossa.

**Comment by Katja-Lumme** [comment]
Viime lauantaina näitä tuli jälleen, esim. nide 49120211105179 ja 49122040500326.. 3.2. oli viimeinen noutopäivä, lauantaina 4.2. antoi edelleen samalle asiakkaalle ja samalla noutopäivällä varauksen palauttaessa.

**Comment by AnneliO** [comment]
Voisko tässä olla kyse siitä, että Lumpeissa on järjestelmäasetuksessa ExpireReservesOnHolidays "älä salli", eli varaukset eivät voi vanhentua niinä päivinä, kun kalenterissa on merkitty kiinniolo?

Eli tuossa viimeisimmässä esimerkissä viimeinen noutopäivä on 3.2.2023, jolloin se vanhentuu 4.2.2023. Tuo 4. päivä on kuitenkin kalenterissa merkitty suljetuksi Mikkelissä eli asetuksen mukaan se ei voi silloin vanhentua.

**Comment by Katja-Lumme** [comment]
Hei, no niin, totta. Tämä kyllä selittäisi kaikki, ovat olleet minun mielestäni kaikki tapaukset sellaisia että perjantai on ollut viimeinen noutopäivä. Suljen tiketin ja avaan uudelleen mikäli tulee sellaisia jotka eivät tähän kaavaan istu:). Kiitos!
