### ISSUE TITLE
Kyyti: nidetyyppimuutos cd-levyille

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#358]
### Tukipyyntö

Kyyti-kirjastojen johtoryhmä on päättänyt muuttaa cd-levyjen laina-aikaa. Pyydän nidetyyppimuutoksia seuraavasti:

1.
itemtype=CD ja permanent_location on joku seuraavista: A, D, M, MV, V -> nidetyypiksi 28MAV

2. 
itemtype=CD ja permanent_location=N -> nidetyypiksi 28EAV

**Comment by lasse-koha** [comment]
Muutokset tehty.
