### ISSUE TITLE
Helle: itsepalvelulainaus-toimintoon Helle-logo käyttöön

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#363]
### Tukipyyntö

Vaihdatteko Hellen itsepalvelulainaukseen Koha-logon tilalle Helle-logon?

![kuva](https://user-images.githubusercontent.com/99952449/211990333-15f9fbaf-cc72-43ae-9792-0681b7507a27.png)

**Comment by lmstrand** [comment]
Lisäsin SCOUserCSS-asetukseen logon vaihdon testille:
```
/*Replace logo*/
#logo {
    background:url('/koha-suomi-images/helle-images/Helle-logo.png') no-repeat center center;
  width: 180px;
}
```
Kokoa voi muuttaa vaikka tuolla width-parametrilla.

Olettehan tietoisia että tuossa itsepalvelulainauksessa on ongelma, jonka takia sivusto kirjautuu ulos asiakasnäkymästä n. vuorokauden kuluttua? Outissa (ja kohta Vaarassakin) ongelma on ratkaistu kirjautumisavustajalla, joka tarkkailee sivustoa ja kirjaa asiakkaan automaattisesti asiakasnäkymään. https://github.com/KohaSuomi/Koha/issues/297

**Comment by Kati-Helle** [comment]
Helle-logo paikallaan, kiitos Lari!

Onkohan mainitsemasi kirjautumisavustaja Hellessä käytössä? Jos ei, niin saisiko tuon sekä tuotantoon että testiin?
Itsepalvelulainaus-tunnusten virkailijatyypin alku on tiketissä 297 mainittu AUTO

**Comment by lmstrand** [comment]
Tuo kirjautumisominaisuus on toteutettava jokaiselle itsepalvelulainausta käyttävälle koneelle paikallisen IT-tuen toteuttamana. Emme saaneet korjattua tuota asiakasnäkymästä ulospotkimisongelmaa ja tällä hetkellä tuo tiketti 297:n ohje automaatti-tyypin tunnuksista on sinänsä aiheeton. Sama ongelma tapahtuu kaikilla asiakastyypeillä asiakasnäkymään kirjautuessa, oli sitten automaatti/virkailija-tyypin tunnus. Ongelma pitäisi korjata yhteisössä yhteisön kanssa ja siihen saataa mennä kauankin.

**Comment by Kati-Helle** [comment]
Kiitos tarkennuksesta. Ilmoitamme ko. toteutustarpeesta IT-tuelle. 

Suljenpa tämän valmiin tiketin.
