### ISSUE TITLE
OUTI: SIP-tunnuksen lisääminen OUTIn automaattipalvelinten konfiguraatioon

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#366]
### Tukipyyntö

Lisäisittekö Pyhäjoen lukion kirjaston lainauspalautusautomaatin SIP-tunnuksen OUTIn automaattipalvelinten konfiguraatioon. Tiedot lähetetty Support-postiin.

**Comment by emta001** [comment]
Kävin juuri lisäämässä tunnuksen palvelimelle :D

**Comment by pirliis** [comment]
Kiitos! Suljen tiketin.
