### ISSUE TITLE
Waitingreserves.pl-sivulle mahdollisuus näyttää asiakkaan tiedoista vain varaustunniste

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#367]
### Kehitysehdotukseni

Sivulla https://vaski.koha-suomi.fi/cgi-bin/koha/circ/waitingreserves.pl näkyy patron-sarakkeessa tällä hetkellä tarpeettoman paljon tietoa asiakkaasta (nimi, sähköposti). Koko sarakkeen voisi kyllä piilottaa, mutta varaukseen liittyvä varaustunniste olisi kuitenkin hyödyllinen tieto näkymässä.

Eli olisiko mahdollista, että piilotettaisiin osa patron-sarakkeen tiedoista? Olisi ehkä helpompi tapa kuin se, että varaustunnisteelle olisi kokonaan oma sarake?

**Comment by Kati-Helle** [comment]
Tämän osalta hyvä huomioida se, että kaikissa kirjastoissa ei ole käytössä varausten omatoiminouto. Noudettavat varaukset ovat tiskin takana asiakkaan nimen mukaan, jolloin noudettavaan varauksen liittyy asiakkaan nimi varaustunnuksen sijaan.

**Comment by ajrajala** [comment]
Hyvä huomio, en tullut ajatelleeksi ettei varaustunnisteisiin ole kaikkialla siirrytty.

**Comment by janPasi** [comment]
> Tämän osalta hyvä huomioida se, että kaikissa kirjastoissa ei ole käytössä varausten omatoiminouto. Noudettavat varaukset ovat tiskin takana asiakkaan nimen mukaan, jolloin noudettavaan varauksen liittyy asiakkaan nimi varaustunnuksen sijaan.

Niin mutta miksi? Miksi ne eivät ole tiskin takana varaustunnisteen perusteella? :D

**Comment by Kati-Helle** [comment]
> > Tämän osalta hyvä huomioida se, että kaikissa kirjastoissa ei ole käytössä varausten omatoiminouto. Noudettavat varaukset ovat tiskin takana asiakkaan nimen mukaan, jolloin noudettavaan varauksen liittyy asiakkaan nimi varaustunnuksen sijaan.
> 
> Niin mutta miksi? Miksi ne eivät ole tiskin takana varaustunnisteen perusteella? :D Varaustunniste on asiakkaan astellessa tiskille ihan yhtä helppo selvittää kuin nimikin, ja asiakkaan tietosuojan kannalta on joka tapauksessa aina parempi, ettei niitä nimiä ole näkyvillä missään kirjaston tiloissa.

Katsotaan, saadaanko Helleen muutos tuon osalta.

**Comment by Kati-Helle** [comment]
Hellen osalta ei tule muutosta ainakaan tähän hetkeen. Helle-johtoryhmä päätti kokouksessaan 8.2.2023, että kukin kirjasto voi edelleen toimia haluamallaan tavalla. Hellessä noudettavia varauksia tulee siis jatkossakin olemaan tiskin takana asiakkaan nimen mukaan.

**Comment by Kati-Helle** [comment]
Lisään tähän vielä tiedoksi, että uudessa versiossakin varaajan nimi näkyy myös Vastaanotettavat kuljetukset -toiminnossa

Varattu asiakkaalle -sarakkeessa näkyy tällä hetkellä asiakastiedosta ainakin
asiakkaan nimi tyyliin Sukunimi, Etunimi
asiakkaan puhelinnumero (Primary phone -kentän arvo)
asiakkaan sähköpostiosoite

![Image](https://user-images.githubusercontent.com/99952449/227149696-eab06eb0-5127-4a39-a550-883fbc9faff0.png)

**Comment by Kati-Helle** [comment]
Vastaanotettavat kuljetukset -toiminnon asiakastiedoista on oma tiketti (Päivi Knuutinen tehnyt 4 päivää sitten):
https://github.com/KohaSuomi/Koha/issues/687

**Comment by Kati-Helle** [comment]
Entäpä myös Waitingreserves.pl-sivulla nykyisten Asiakas-sarakkeen (Patron) tietojen korvaaminen asiakastiedon borrowernumber-arvolla?

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 11.12.2023: Tutkitaan, saako asiakastiedon korvattua tekstillä "Kyllä" selainpäässä JavaScriptillä, jos kuljetettavaan niteeseen kohdistuu varaus.

**Comment by janPasi** [comment]
Kuva on tässä väärä. Tämän tiketin kuva ei ole waitingreserves vaan transferstoreceive. Transferstoreceive on tiketissä #687.

**Comment by AnneliO** [comment]
Kati näyttäisi mainitsevan, että kuva on vastaanotettavat kuljetukset -raportilta. Alkuperäisessä kuvauksessa ei kuvaa olekaan. :)

**Comment by janPasi** [comment]
> Kati näyttäisi mainitsevan, että kuva on vastaanotettavat kuljetukset -raportilta. Alkuperäisessä kuvauksessa ei kuvaa olekaan. :)

Juu, älkää sotkeko eri tiketteihin liittyviä asioita keskenään, menee vaikeeksi seurata :D

**Comment by janPasi** [comment]
> Entäpä myös Waitingreserves.pl-sivulla nykyisten Asiakas-sarakkeen (Patron) tietojen korvaaminen asiakastiedon borrowernumber-arvolla? Tai cardnumber-arvolla?

Tämä ratkaisu ei kyllä oikein äkkiä ajatellen tunnu minusta palvelevan ketään? Keskustellaan tämä vielä asiantuntijaryhmässä.

**Comment by Kati-Helle** [comment]
Hellenkin osalta tämän voi nyt toteuttaa.

**Comment by ajrajala** [comment]
Käyttötarve on ainakin Vaskissa niin vähäinen, että voidaan kyllä korvata waitingreserves.pl tallennetulla raportilla, jossa asiakastietoja ei näytetä. Eli meidän puolesta sopii, että waitingreserves.pl piilotetaan kokonaan Lainaus ja palautus -sivulta.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.2.2024: Suositus, että Asiakas-sarake piilotetaan sarakeasetuksissa. Pääkäyttäjien tehtävissä.

**Comment by sksandel** [comment]
Vaskissa on asiakas-sarake piilotettu. Onko tarkoitus että näitä kommentoidaan kimpoissa vai voidaanko sulkea tiketti?

**Comment by AnneliO** [comment]
Eiköhän tämän voi sulkea. :)

**Comment by sksandel** [comment]
Suljen tiketin.
