### ISSUE TITLE
Asiakasmääreen kuvauksen muutos ei onnistu

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#374]
### Mikä vikana?

Yritän vaihtaa Vaarassa asiakasmääreen SSN kuvauksen tekstin Sotu-avain muotoon Sotuavain. Vaaran testikannassa se onnistuu, mutta tuotannossa saan aina virheilmoituksen Virhe! Virhe 500.... eikä muokkaus onnistu. Mikähän vikana?

**Comment by emta001** [comment]
Johtuisikohan tästä:
_The property 'unique_id' cannot be changed, some patron attributes are using it that way._

**Comment by pknuuti** [comment]
Miksi se testikannassa sitten voidaan muokata? En ymmärrä.

**Comment by emta001** [comment]
Hyvä kysymys. Kokeilin laittaa asiakkaalle tuon SSN arvon borrower_attributes-tauluun (testeillä niitä ei ole) ja silti antaa tallentaa arvon uusiksi.

**Comment by pknuuti** [comment]
Pystytkö muuttamaan tuon tekstin tietokannan kautta? Häiritsee nyt tuo väliviiva.

**Comment by emta001** [comment]
> Pystytkö muuttamaan tuon tekstin tietokannan kautta? Häiritsee nyt tuo väliviiva.

Joo, kävin muuttamassa. Kumma juttu.

**Comment by pknuuti** [comment]
Kiitos!
