### ISSUE TITLE
Varkauden niteiden itemcallnumber- ja cn_sort-kenttien korjaus

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#377]
### Tukipyyntö

Lumme-kimpassa Varkauden niteissä on muusta kimpasta poikkeavia signumeita, mistä johtuu, että esimerkiksi okm-tilastoissa ei niteet jakaudu oikein tieto- ja kaunokirjoihin. Sovimme Koha-Suomen palaverissa Varkauden kanssa, että cn_sort-kentät korjataan samaan muotoon kuin ne muilla kimpan kirjastoilla ja he muodostavat jatkossa signumit samassa muodossa kuin muut.

Lumpeissa signumit ovat muoto 084a_mainheading_branchloc eli luokka, pääsana ja kirjastontunnus+hyllypaikka, esim. 78.3 SIB VAR_PKL. Varkauden niteissä (osassa) signumit ovat muotoa kirjastotunnu ilman VAR-alkua+hyllypaikka , luokka ja pääsana esim. PKL 85.22 WEN.

Eli käsitellään ne niteet, joissa on kotikirjastona (homebranch) "VAR_"-alkuinen kirjastotunnus. Lisätään kommentteihin tarkempia ohjeita.

**Comment by janPasi** [comment]
Joukossa on joitakin joille tarvitsee tehdä manuaalisia korjauksia ennen ajoa, esimerkiksi:

* niteen KAN110267 signumista puuttuu välilyönti sijaintitiedon ja luokkatunnukse välistä
* niteiltä 915N03330999 ja 915N03331028 puuttuu hyllypaikka, jonka vuoksi signumille käy korjauksessa huonosti

Muitakin virheitä voi olla, kannattaa tosiaan katsoa tarkasti läpi tuo raportti.

**Comment by lasse-koha** [comment]
Näkyy myös olevan todella paljon niteitä joissa hyllypaikka on eri kuin nykyisessä signumissa. Ilmeisesti hyllypaikkaa muutettu ja signumiin jäänyt vanhan hyllypaikan tunnus?

**Comment by HeliAuranen** [comment]
Rapsalta poimittu hyllypaikattomat ja korjattu. Korjatusta signumista tsekattu ne joissa ei ole luokka ensimmäisenä.
Toimisikohan nyt korjaus oikein.

Väärä hyllypaikka: Jossain välissä oli jäätävä määrä hyllypaikattomia niteitä Lumpeissa, voivat olla osin jäänteitä siitä ja voihan olla, että kaikkialla ei olla niin tarkkoja signumin hyllypaikan muutamisessa.

**Comment by HeliAuranen** [comment]
Rapsa 595 näyttä tyhjää nyt. Edellisisllä raportella (cn_sortissa kirjain ekana) tulee vielä tuloksia, myös Varkaudelle. Kaikilla ei ole edes luokkaa. Olisiko millainen homma nuo luokalliset muljauttaa oikeinpäin

**Comment by lasse-koha** [comment]
cn_sortit on vielä muuttamatta. Rapsassa on mukana vain ne niteet joissa on signum väärässä muodossa eli sen kuuluukin olla nyt tyhjä.

**Comment by irmaf471** [comment]
pystymmekö kirjastolla ajamaan raportin niteistä joissa hyllypaikka on eri kuin nykyisessä signumissa? Mikä on raportin numero?

**Comment by lasse-koha** [comment]
cn_sortit korjattu.

**Comment by lasse-koha** [comment]
> pystymmekö kirjastolla ajamaan raportin niteistä joissa hyllypaikka on eri kuin nykyisessä signumissa? Mikä on raportin numero?

Ei taida olla valmista raporttia ja hiukan haastavaa olisi saada tuollainen toimimaan luotettavasti kaikkialla. Signumista pitäisi pystyä erottamaan kirjastotunnukseen kuuluva osa ja hyllypaikka.

**Comment by emta001** [comment]
Mikä on tämä tiketin tilanne? Voidaanko jo sulkea ja tiputtaa käytetyt aputaulut kannasta vai annetaanko vielä olla?

**Comment by lasse-koha** [comment]
Eiköhän tämän voisi sulkea?
