### ISSUE TITLE
Asiakkaan maksut näkymään oikein 

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#378]
### Tukipyyntö

Vaarassa on käytössä asiakkaiden maksujen jakautuminen julkisoikeudelllisiin ja yksityisoikeudellisiin maksuihin. Vain julkisoikeudelliset maksut (myöhästymismaksut, varausmaksut) saavat johtaa asiakkaan lainauskieltoon, mikäli maksuille määritelty raja ylittyy. Nämä maksut kertyy Kohassa automaattisesti laina- ja maksusääntöjen mukaisesti. 
Yksityisoikeudellisia maksuja on mm. aineiston laskuttamiseen liittyvät maksut ja nämä eivät saa aiheuttaa asiakkaalle lainauskieltoa.

Tällä hetkellä Vaarassa lainausnäytöllä näkyy asiakkaan julkisoikeudelliset maksut, mutta yksityisoikeudelliset maksut näkyy vain Maksut-välilehdellä. MikroVäylän automaatti antaa kuittiin julkisoikeudelliset maksut väärässä muodossa "Maksut 7,8", eikä muut maksut näy ollenkaan automaatin antamalla lainauskuitilla. 

Maksujen näkymisiin pitäisi saada joku logiikka ja selkeys.

**Comment by pknuuti** [comment]
Samaa asiaa tiketissä https://github.com/KohaSuomi/Koha/issues/301

**Comment by lmstrand** [comment]
yhteisössä: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32450

**Comment by pknuuti** [comment]
Nyt kun maksut näkyvät oikein Kohassa asiakkaan lainaustilanteessakin, saisiko tämän näkymään myös automaatilla. Tällä hetkellä automaatti näyttää vain julkisoikeudelliset maksut.

**Comment by AnneliO** [comment]
> Nyt kun maksut näkyvät oikein Kohassa asiakkaan lainaustilanteessakin, saisiko tämän näkymään myös automaatilla. Tällä hetkellä automaatti näyttää vain julkisoikeudelliset maksut.

Teetkö Päivi automaatin osalta erillisen tiketin? :)

**Comment by AnneliO** [comment]
Voisiko tämän tiketin sulkea?

**Comment by AnneliO** [comment]
Tuplatiketti, suljen.
