### ISSUE TITLE
Action_logs-lokien jakaminen omiin tietokantatauluihin interfacen perusteella

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#382]
### Kehitysehdotukseni

Action_logs -tauluun kirjoitetaan tällä hetkellä runsaasti dataa (Vaski 800 000 riviä yhdessä viikossa). Jotta datan käsittely/arkistointi/siivoaminen olisi kevyempää, tulisi Kohan eritellä tapahtumat omiin tietokantatauluihinsa eri lähteiden (interface) perusteella.

**Comment by AnneliO** [comment]
Pitäiskö tämä jako aloittaa ottamalla cataloguing-lokitus erilleen? Jos kaikki eri moduulien lokit laitetaan erillisiin tauluihin, hankaloittaa se Lokien katselu/Muutosloki -työkalun käyttöä. Se hakee tietoja vain action_logs-taulusta. Tai sitten työkalua pitää muuttaa niin, että se hakee kaikista erillisistä tauluista.

**Comment by paxed** [comment]
action_logsin logituksen pilkkominen eri tauluihin interfacen tai modulin perusteella on varsin pieni ja helppo koodimuutos, pari riviä C4/Logs.pm:ssä olevaan logaction -funktioon. moduli on esim. CATALOGUING tai CIRCULATION yms.

**Comment by paxed** [comment]
Suurimmat määrät rivejä tulee näköjään MEMBERS, CIRCULATION, FINES, ja CATALOGUING, kaikki muut modulit yhteensä laskettuna näyttää olevan pienempiä kuin nuo.

**Comment by AnneliO** [comment]
Puhuimme Koha-Suomen palaverissa 2.2.2023, että toteutetaan tämä vain, jos tiketin #401 toteutus ei onnistu.

**Comment by AnneliO** [comment]
#401 näyttää etenevän, joten ei toteuteta tätä.
