### ISSUE TITLE
Saapumisilmoitus lähtee kirjeenä vaikka viestiasetuksissa valittuna sähköposti

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#383]
### Mikä vikana?

Asiakkaalle (borrowernumber 146332) lähtee jostain syystä saapumisilmoitukset printtinä vaikka viestiasetuksiin on tallennettu sähköposti-rasti. Löytyisiköhän tälle jokin selitys?

Eräpäiväilmoitukset näyttäisivät samalle asiakkaalle lähteneen onnistuneesti sähköpostilla.

**Comment by AnneliO** [comment]
Tälle asiakkaalle näyttäisi lähteneen saapumisilmoitukset "aina" printtinä. Lokitiedoissa näkyy 17.1.2023 merkintä, että viestiasetuksiin on koskettu, joten olisiko mahdollista, että sähköpostirasti on lisätty vasta sitten?

**Comment by ajrajala** [comment]
Eiköhän tuo selitä asian, luulin katsoneeni lokista ettei muutoksia olisi tehty mutta näköjään mennyt ohi. :) Suljen tiketin.
