### ISSUE TITLE
TäTistä valuneet väärät tiedot kummittelevat hakutuloksessa vaikka tietueella päivitetty uudet tiedot tilalle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#384]
### Mikä vikana?

[Tietueen 4177469](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4177469&searchid=scs_1674480988309) päälle oli valunut saman sarjan toisen teoksen tiedot, koska sarjalla on yhteinen ISBN. Tietueen päälle siirrettiin Tätistä  uudestaan oikean teoksen tiedot + lisäksi aktivoitiin tietueen 942b-kenttään valumisen esto.

Ongelmana on nyt se, että [tiedonhaun hakutuloksessa](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl?count=50&sort_by=title_az&idx=&q=se%2Cphr%3A%22Eurooppa%20liekeiss%C3%A4%20%3B%22) tietueella näkyvät edelleen väärät tiedot (hakutulos nro 10, jonka mukaan teos olisi Sukellusveneet Atlantilla vaikka oikeasti teos on Normandian maihinnousu). Tiedot näkyvät oikein, kun tietueen klikkaa auki.

Ongelmasta raportoitiin meille eilen ja ainakaan yön aikana tälle ei näyttäisi mitään tapahtuneen vaan näkyy edelleen hakutuloksessa väärin. Sivun päivittäminenkään ctrl+F5:lla ei näyttäisi muuttavan tilannetta.

### Jotain muuta?

![kuva](https://user-images.githubusercontent.com/44638512/214242604-84fd3789-c095-47a5-9dcd-c4e676337a55.png)

**Comment by AnneliO** [comment]
Auttaako, jos otatte tietueen muokkaukseen ja tallennatte sen uudelleen tekemättä muokkauksia?

**Comment by ajrajala** [comment]
Joo, tuo näytti korjaavan tilanteen. Pystyykö/kannattaako tuota vielä selvittelemään mistä johtuu, luulisi että samaa ongelmaa voi esiintyä muissakin tapauksissa..?

**Comment by AnneliO** [comment]
Jostain syystä uudelleenindeksointi ei ole aktivoitunut Tätistä tuonnin yhteydessä. Yksittäisiä tapauksia on tullut silloin tällöin aiemminkin ja ne on korjaantunut uudelleentallennuksella. Jos tämä oli yksittäinen tapaus, niin en lähtisi tutkimaan sen kummemmin. Jos tulee enemmän vastaavia tapauksia, niin tutkitaan sitten. :)

**Comment by ajrajala** [comment]
Ok, hyvä tietää! Siinä tapauksessa suljen tiketin.

**Comment by MikkoLiimatainen** [comment]
Onkohan tässäkin kyse indeksoinnin ongelmasta?

Tietue, joka deletedbibliotaulun perusteella olisi poistettu jo 22.9. näkyy hakutuloksissa:
![Poistettu tietue hakutuloksissa rajattu](https://github.com/KohaSuomi/Koha/assets/98884651/1cfe5eb2-1174-4ae1-a505-52205521e60f)

![Poistettu tietue deletedbiblio-taulussa rajattu](https://github.com/KohaSuomi/Koha/assets/98884651/4fa0506c-0b99-4a14-980f-2e97be10691a)

Tuo ylimpänä näkyvä on siis tietue 4323307, joka alemmassa kuvassa näkyy deletedbibliotaulussa. Tein haut "Seitsemän koiraveljestä" ja "9789511181002" ja molemmilla tuo postettu tietue tulee tuloksiin, vaikka se on poistettu lähes kuukausi sitten.

**Comment by emta001** [comment]
Koha-Suomen palaveri 19.2.2024: Katsotaan versionvaihdon jälkeen onko tämä vielä ongelma.

**Comment by ajrajala** [comment]
Yritin vaski-testillä testata tätä niin, että muokkasin tietueen nimekettä ja poistamalla myös tietueen. Pari kertaa ihan heti tiedonhaun tehtyäni näkyi vanha nimeke hakutulossivulla, mutta jos sen perään tein heti taas uuden haun, päivittyi nimeke hakutulossivulle.

Meidän tietoihin ei ole (raportoitujen tapausten jälkeen) tullut tällaista ongelmaa, joten suljenko tiketin vai oliko ideana että tätä vielä testataan seuraavan versiopäivityksen jälkeen? Emmin kommentin jälkeenhän meillä on jo yksi versiopäivitys ollut.

**Comment by johannaraisa** [comment]
Tämän voi sulkea, avaa uudestaan jos on ajankohtainen.
