### ISSUE TITLE
Hankintaportaalista tilatulle teokselle tieto: muovitettu/muovittamaton

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#386]
### Kehitysehdotukseni

Oulun aineistovalitsijoilta on tullut pyyntö, saisiko hankintaportaalin sanomasta Kohaan tiedon, onko tilattu aineisto muovitettu vai muovittamaton. Asiaa on tiedusteltu myös Woimalta ja sieltä on ilmoitettu, että heidän puoleltaan tämä onnistuu. 

Toiveena olisi, jos tiedon saisi esim. teoksen Perustiedot-näytön Hankintatiedot-välilehdelle, sarakkeeseen Sisäinen huomautus. Sarakkeeseen tulee tällä hetkellä myös tilaussanoman tiedot, mutta jos sanomatiedon perään saisi tiedon, onko tilattu aineisto muovitettu vai muovittamaton.

### Jotain muuta?

Tietoa tarvitaan hankittaessa lisäkappaleita tai valitessa uusia pokkarina ilmestyviä sarjoja, jotta voidaan seurata, onko aiemmin tilaukset tehty muovitettuna vai ilman. Eli tietoa tarvitaan valinnan avuksi ja seurantaan.

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.2.2024: Tälle ei ole enää tarvetta, joten ei toteuteta.
