### ISSUE TITLE
Suomennos asiakkaan maksujen Tapahtumat -välilehden tilin tyypille Credit has been voided

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#387]
### Kehitysehdotukseni

Asiakkaan Maksujen Tapahtumat-välilehdellä näkyvän maksun mitätöintitapahtuman tilin tyypin nimenä on Credit has been voided.
![kuva](https://user-images.githubusercontent.com/99952449/214490985-8d17f416-5b93-4d21-83ff-fb3be373af3f.png)

Maksun mitätöimiseen on käytetty toimintoa Mitätöi maksutapahtuma
![kuva](https://user-images.githubusercontent.com/99952449/214491196-33264d22-3bd0-4bf1-8753-0732b89c6275.png)

**Comment by AnneliO** [comment]
Tuo teksti tulee Ylläpidossa Maksutyypit-sivulla olevasta kuvauksesta. Valitse Näytä kaikki maksutyypit -> Valitse näkyville kaikki rivit -> VOID

![Image](https://user-images.githubusercontent.com/33121325/214575522-b1ea7b34-e048-417f-9dac-4ddb91bc7e3f.png)

Tuo on järjestelmän sisäinen maksu, joten sitä ei voi suoriltaan muokata, mutta kokeilin testillä tehdä niin, että otin toisen maksutyypin muokkaukseen ja muutin osoiterivillä code-sanan jälkeen maksutyypin tunnukseksi VOID ja painoin enter, jolloin pääsi muokkaamaan voidin kuvausta. 

![Image](https://user-images.githubusercontent.com/33121325/214576122-1e22e6ef-bc04-4c1b-8d5b-3c74550eb371.png)

Omien testien mukaan tämän jälkeen myös Tapahtumat-välilehdellä näkyy muutettu kuvaus.

**Comment by Kati-Helle** [comment]
Kiitos Anneli! Sain vaihdettua tilin tyypin nimen mainitsemallasi tavalla.
