### ISSUE TITLE
Huomautus asiakkaille, joilla ei sotuavainta

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#388]
### Tukipyyntö

19.1.2023 poistettiin Vaarasta yksi asiakasmääre ja se aiheutti hetutallennuksen epäonnistumisen, koska numeroarvo muuttui intranetuserjs:ssä. Tänään asia on korjattu, mutta tällä välin on voinut tallentua asiakkaita, joilla ei ole sotuavainta. Näille mahdollisille asiakkaille tarvitaan huomautus, että sotuavain puuttuu.
Vastaava tilanne tiketissä https://tiketti.koha-suomi.fi/issues/5535

**Comment by lmstrand** [comment]
ajettu:

```
INSERT INTO messages (borrowernumber, message_type, message, message_date)
      SELECT borrowernumber, 
      'L', 'Sotutunnus puuttuu', now()
      from borrowers        
WHERE       dateenrolled > '2023-01-18' AND borrowernumber not in (select borrowernumber from borrower_attributes where code='ssn')       AND categorycode in ('HENKILO', 'LAPSI', 'MUUKUINLAP', 'TAKAAJA')
```

117 asiakkaalle lisätty viesti. Näkyy vain virkailijoille.

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
