### ISSUE TITLE
Kooste-täpät päälle kaikille asiakkaille viestiasetuksissa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#389]
### Tukipyyntö

Kaikissa tietokannoissa on todennäköisesti asiakastietoja, joiden viestiasetuksissa ei ole päällä Kooste-täppää. Näille asiakkaille pitäisi lisätä Kooste-täppä, jotta heille ei turhaan lähde esim. jokaisesta lainasta omaa viestiä.

Liittyy [Redmine-tikettiin #5269](https://tiketti.koha-suomi.fi/issues/5269)

**Comment by lmstrand** [comment]
Kimpoissa pitäisi estää asiakkailta koosteviestien täpän poisottaminen Finnasta käsin ennen ajoa.
Liittyy: https://tiketti.koha-suomi.fi/issues/5369

**Comment by Chriss-Kyyti** [comment]
Mitenkäs se estetään?

**Comment by AnneliO** [comment]
Voiko hoitaa modborrowerilla (tjsp)?

**Comment by lmstrand** [comment]
Kooste-sarakkeen piilotus kokonaan Kohan viestiasetustaulusta (nth-child -1 jos ei suomi.fi-täppiä käytössä):
```
$(document).ready(function () {
  if ((window.location.href.indexOf("members/moremember.pl") > -1) || (window.location.href.indexOf("members/memberentry.pl"))) {
    $('td:nth-child(6),th:nth-child(6)').hide();
  }
});
```

**Comment by lmstrand** [comment]
Kimpoissa on hieman erilaisia virityksiä koosteviestitäppien käsittelyyn niin Finnassa kuin Kohassakin. Yritetään saada nyt kaikille kimpoille samalla tapaa toteutettu koosteviestitäppien pakotus päälle ja niiden piilottaminen Finnasta.

"Voiko hoitaa modborrowerilla (tjsp)?"
Ei ainakaan virkailijaliittymän modborrowers (batch patron modification/Asiakkaiden muokkaus eräajona) taivu viestiasetusten säätämiseen (onko olemassa vielä erillinen työkaluskripti, josta en ole tietoinen?).

Siis, ajetaan tietokanta-ajona täpät asiakkaille päälle?
Tutkitaan, onko kimpoissa intranetuserJS-toteutuksia täppien pakottamiseen päälle, ja poistetaan ne triggerin tieltä.
Triggerillä hoidetaan aina viestiasetusten muutoksen yhteydessä, että koosteviestit ovat aina päällä. (https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Viestiasetusten_kooste-t%C3%A4ppien_pakotus_triggerill%C3%A4)
Message_transports-taulujen arvot yhtenäistetään kimppojen kesken (jos ei jo ole) ja Finna-näkymistä piilotetaan halutessa koosteviesti-täpät templatemuutoksella.

**Comment by pknuuti** [comment]
Kannatan, että kaikilla olisi samanlainen viritys näissä koosteviestitäpissä. En näe mitään tarvetta sille, että jokaisesta lainasta lähtisi erillinen viesti asiakkaalle.

**Comment by AnneliO** [comment]
Koha-Suomen palsu 9.2.2023: Kimppa kerrallaan, riisutaan kaikki viestiasetuksiin liittyvät säädöt ja laitetaan triggeri päälle. Piilotetaan kooste-täpät. Sen jälkeen pitää tehdä Finnassa piilotus Kooste-täpille (Vaarassa tehty, saataneen sieltä tarvittava piilotusrimpsu muille kimpoille).

**Comment by lmstrand** [comment]
Kaikkien kimppojen tuotantoihin on asetettu triggeri, joka pakottaa koosteviestitäpät päälle viestiasetuksia tallentaessa:
```
delimiter $$
create or replace trigger before_message_preferences_insert
before insert on borrower_message_preferences
for each row
begin
  if new.message_attribute_id=1 or new.message_attribute_id=2 then
    set new.wants_digest=1;
  end if;
end $$
delimiter ;
```

**Comment by pknuuti** [comment]
Koosteviestiasetustäpät tulivat paikoilleen, vaikka asiakkaalle ei valittu mitään viestiasetuksia. Tallennettu vain sähköpostiosoite asiakkaan tietoihin uutta asiakasta lisättäessä. Vain koosteilmoitus-täpät näkyvät asiakkaan Tiedot-välilehden Asiakkaan viestiasetukset-laatikossa, mutta kun menee asiakkaan tietojen muokkausnäytölle, siellä koosteviestitäppiä ei näy paikoillaan. Onko tämä tarkoitus olla näin?
Mielestäni olisi johdonmukaisempaa, että koosteviestitäpät tulisivat vain, jos asiakkaalle on laitettu sähköpostitäppä ensin paikoilleen.

**Comment by lmstrand** [comment]
Kimppoihin lisätty myös triggeri updatelle. Finnan muutokset menevät tietokantaan updateina. Nyt ei siis Finnasta käsin voi vaihtaa kooste-asetusta pois.

```
delimiter $$
create or replace trigger before_message_preferences_update
before update on borrower_message_preferences
for each row
begin
  if new.message_attribute_id=1 or new.message_attribute_id=2 then
    set new.wants_digest=1;
  end if;
end $$
delimiter ;
```

**Comment by lmstrand** [comment]
Kaikkien kimppojen tuotantoihin ajettu koostetäpät päälle kaikille asiakkaille.

```
MariaDB [vaaraprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 39066 rows affected (2.000 sec)
Rows matched: 335137  Changed: 39066  Warnings: 0


MariaDB [vaskiprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 5014 rows affected (2.906 sec)
Rows matched: 766822  Changed: 5014  Warnings: 0


MariaDB [siiliprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 20188 rows affected (0.448 sec)
Rows matched: 34097  Changed: 20188  Warnings: 0


MariaDB [lappiprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 11960 rows affected (1.714 sec)
Rows matched: 315129  Changed: 11960  Warnings: 0


MariaDB [lummeprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 51703 rows affected (2.174 sec)
Rows matched: 362562  Changed: 51703  Warnings: 0


MariaDB [helleprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 5875 rows affected (1.202 sec)
Rows matched: 254624  Changed: 5875  Warnings: 0


MariaDB [kyytiprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 45525 rows affected (1.279 sec)
Rows matched: 180546  Changed: 45525  Warnings: 0


MariaDB [outiprod]> update borrower_message_preferences set wants_digest = 1 where message_attribute_id in (1,2);
Query OK, 16607 rows affected (2.796 sec)
Rows matched: 565556  Changed: 16607  Warnings: 0
```

**Comment by lmstrand** [comment]
Nyt tarvitsisi enää piilottaa Finnasta kooste-täpät asiakkaan näkyviltä.

**Comment by pknuuti** [comment]
Mä yritin katsoa ohjeita, mutta en uskalla tehdä mitään, kun en ihan ymmärrä miten ne täpät sais piiloon. Onko jollakin tieto, miten se tehdään vai kysynkö Finna-tuesta?

**Comment by MikkoLiimatainen** [comment]
Vaskissa on Finnaan /themes/custom/templates/myresearch/change-messaging-settings-driver.phtml -tiedoston loppuun lisätty skripti koostetäppien piilotukseen, joka lisäksi varmistaa, että täpät ovat valittuna.
`<script nonce="<?=$this->cspNonce()?>">
    $("input[name='Advance_Notice_digest']").prop("checked", true).parent().parent().parent().css("display", "none");
    $("input[name='Item_Due_digest']").prop("checked", true).parent().parent().parent().css("display", "none");
  </script>`

**Comment by pknuuti** [comment]
Kiitos Mikko, nyt on Vaaraan laitettu koosteviestitäpät piiloon. Tosin tuontanto-Finnassa näkyy vasta tiistaina, kun nyt on päivitystauko.

**Comment by pirliis** [comment]
OUTIssa nyt myös koostetäpät Finnasta piilotettu.
