### ISSUE TITLE
Elasticsearch-ongelmat Kohassa (mm. EditX-käsittely)

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#393]
### Mikä vikana?

Elasticsearch aiheuttaa ongelmia useissa kimpoissa ainakin hankinnassa, kun EditX-sanomaa käsitellään. Ongelma keskeyttää sanoman käsittelyn. Virhe:  [Bad response received when submitting request to Elasticsearch]. Ongelmat saattavat myös ilmetä muualla Kohassa.

Saattaa johtua Kohan tavasta käyttää threadeja:
https://stackoverflow.com/questions/71547835/org-apache-lucene-queryparser-classic-parseexception-cannot-parse

"It turned out that queryParser is not thread-safe - inside it has states, access to which from several threads is not synchronized. "

Lisätään tikettiin virhesanomia Elasticsearchin omista lokeista kun niitä löytyy/syntyy (.

Liittyy (mahdollisesti) mm. tiketit:
https://github.com/KohaSuomi/Koha/issues/353
https://github.com/KohaSuomi/KohaSuomiServices/issues/3
https://github.com/KohaSuomi/Koha/issues/290

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 13.2.2023: Tutkitaan tarkemmin versionvaihdon jälkeen.

**Comment by pirliis** [comment]
OUTIn hankinnassa on huomattu, että 99.9% näistä tuplista syntyy vain Kirjavälityksen tilauksista, jos tästä tiedosta olisi jotain hyötyä ongelman selvittelyssä.

**Comment by lmstrand** [comment]
Nyt versionvaihdon jälkeen nämä tilanteet ovat loppuneet, mahdollisesti juuri siitä syystä, että nykyisin indeksipäivitykset tapahtuvat tuon taustajonoprosessin kautta eikä Elasticsearch mene "tukkoon" indeksointipyynnöistä. Pirliin aiempi kommentti varmaan koskee tapauksia ennen versionvaihtoa? Tarkkaillaan tuleeko näitä tapauksia enää, mutta olen aika optimistinen että ongelma on poistunut versionvaihdon yhteydessä.

**Comment by lmstrand** [comment]
Suljen tiketin. Aukaistaan uudelleen jos näitä vielä ilmenee.
