### ISSUE TITLE
LAPPI: Toistettava ajo varausten keskeyttämiseen?

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#397]
### Tukipyyntö

Onko mahdollista saada päivittäin suoritettava ajo, jolla keskeytetään tietyn varausten noutopisteen varaukset? Meillä Tornion kirjasto menee nopealla aikataululla kiinni 3-4 kuukaudeksi. 

Aiemmin kirjaston mennessä kiinni, olemme keskeyttäneet varaukset ja poistaneet toimisteen noutopaikoista, mutta siinä ongelmaksi tuli uudet varaukset, joiden (oman noutopisteen puuttuessa) noutopisteeksi tulee listan ensimmäisenä oleva pieni pohjoisen kirjasto yli 300 km päässä, jonne varaukset sitten ohjautuvat ihan turhaan. Nyt koitettaisiin kiertää tämä ongelma... 

Ajatus tässä on siis: Noutopiste jätettäisiin voimaan ja asiakkaat voisivat tehdä normaalisti varauksia, mutta ne keskeyttäisi joka päivä ajolla. Jos asiakkaat haluavat hakea varauksensa jostain toisesta toimipisteestä, voivat he itse muuttaa noutopisteen. 

### Jotain muuta?

Tähän tarvittaisiin pikainen vastaus, onko mahdollista toteuttaa.

**Comment by janPasi** [comment]
On periaatteessa mahdollista, mutta edelleen asiakas voi itse purkaa keskeytyksen Finnassa. Varaus tärppää edelleen jos joku sattuu ottamaan kiinni varauksia juuri sillä välillä kun varaus on purettuna (eli ennen kuin seuraava ajo merkitsee sen takaisin keskeytetyksi).

**Comment by AnneliO** [comment]
Juttelimme tästä Koha-Suomen palaverissa 2.2.2023. 

Finnassa pystyy määrittämään "oletusnoutokirjaston", jos noutokirjastoa ei ole. Sinne voi määrittää joko tietyn kirjaston tai niin, että asiakkaan on pakko valita jokin kirjasto. Palaverissa totesimme, että tämä ei ehkä Lapin tapauksessa riitä, koska kirjastoyksiköiden välimatka on pitkä.

Päivittäin suoritettava ajo ei riitä, koska uusia varauksia syntyy koko ajan ja asiakkaat palauttavat aineistoa koko ajan, joten kohtalaisen suurella todennäköisyydellä varauksia ehtii tarttua ennen kuin ajo ehtii keskeyttää ne.

Lasse tutkii, voidaanko keskeytys tehdä suoraan tietokantaan triggerinä tai stored procedurena. Vielä ei ole tietoa, kuinka nopeasti tämä pystytään toteuttamaan, mutta ilmoitamme heti, kun tiedämme.

**Comment by PiaKusmin** [comment]
Ok. Kiitos tiedoista! Meillä aikataulu painaa päälle, joten joudun ainakin aluksi tekemään (pyytämään) kaikkien varausten keskeytyksen. Ja saman ajon mahdollisesti hieman myöhemmin uudestaan. Muuten ympäri Lappia lähtee tulemaan meille turhaan varauksia, joita asiakkaat eivät pääse enää noutamaan. 

Miten saamme päälle asetuksen, jolla Finnassa asiakas pakotetaan valitsemaan jokin noutokirjasto? Voimmeko tehdä sen itse vai tuleeko se Finna-tuen kautta?

**Comment by AnneliO** [comment]
Noutokirjastosäädöstä kannattaa kysyä Finna-tuesta. :)

**Comment by lasse-koha** [comment]
Järkevintä olisi hoitaa tämä Finnan kautta poistamalla noutopiste käytöstä ja antamalla asiakkaan valita toinen noutopiste. Asiakkaan näkökulmasta olisi varmasti hämmentävää jos varauksia otettaisiin edelleen vastaan ja niitä alettaisiin jälkeenpäin ajastetuilla ajoilla ilman selitystä keskeyttelemään.

Uudet varaukset olisi kaiketi mahdollista keskeyttää triggerillä heti varausta tehtäessä. Tämäkin kyllä mielestäni näyttäytyisi asiakkaalle outona virhetilanteena -- tai sitten jäisi kokonaan huomaamatta ja vasta myöhemmin ihmeteltäisiin miksi varaus on keskeytetty. Lisäksi keskeytyksen purkaminen pitäisi sekin vielä erikseen estää. Huomattavasti selkeämpää sekä asiakkaan että järjestelmän kannalta olisi poistaa noutopiste käytöstä.

**Comment by PiaKusmin** [comment]
Ok. Olemme jo poistaneet TOPKn noutopisteistä. Varauksien keskeytyksille on pyydetty ajo. Selvitämme tuon pakollisen noutopaikan Finna-tuen kanssa. Koitamme selvitellä jollain raportilla väärään meneviä varauksia. Toivottavasti niitä ei tule paljoa. 
Kiitos! Suljen tiketin.
