### ISSUE TITLE
Lappi: Tornion muutto - niteet

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#399]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: TOPK (Tornion pääkirjasto)

Tornion kirjasto aloittaa takaisin muuton väistötiloista. Tarvitsisimme seuraavia toimenpiteitä aineistolle:

Kaikille saatavana oleville niteille muutetaan not_loan arvo 8. Jos niteellä on jo jokin muu not_loan arvo, siihen ei kosketa (esim. 6 laskutettu, -1 tilattu).
Muutoksesta jätetään myös pois lainassa olevat, kuljetettavana olevat ja noutoa odottavat niteet.

Muutos tulisi tehdä 8.2.2023 heti aamulla.

Arvon poistamisesta ilmoitetaan myöhemmin (kun muutto on saatu valmiiksi).

Liittyy Redmine tikettiin [#5238](https://tiketti.koha-suomi.fi/issues/5238)

**Comment by PiaKusmin** [comment]
Hox! Tässä otetaan huomioon aineisto, jonka sijaintikirjasto/holdingbranch on TOPK. 
(Koska kirjastoauto liikkuu ja lasten aineisto kelluu pääkirjaston kanssa)

**Comment by paxed** [comment]
Muutos tehty näillä rimpsuilla:

create table items_gh399_20230208 SELECT i.itemnumber, i.homebranch, i.holdingbranch, i.onloan, r.found, i.notforloan FROM items i LEFT JOIN reserves r ON(i.itemnumber = r.itemnumber) where holdingbranch = 'TOPK' and i.notforloan = 0 and i.onloan is null and r.found is null;
update items  i LEFT JOIN reserves r ON(i.itemnumber = r.itemnumber) SET i.notforloan = 8  where holdingbranch = 'TOPK' and i.notforloan = 0 and i.onloan is null and r.found is null;

Koski 22480 nidettä.
Niteiden aikasemmet tiedot ovat tallessa taulussa items_gh399_20230208.

**Comment by PiaKusmin** [comment]
Muutos näyttäis menneen oikein. Kiitos Pasi! Suljen tiketin.

**Comment by PiaKusmin** [comment]
Toimipisteen TOPK (Tornio pääkirjasto) kaikilta niteiltä tulee poistaa not_loan arvo 8. Jos niteellä on jo jokin muu not_loan arvo, siihen ei kosketa (esim. 6 laskutettu, -1 tilattu).

Eli Tornion varastoidut (not_loan arvo 8) niteet vapautetaan saatavana tilaan.

**Comment by emta001** [comment]
Muutos tehty, aiemmat arvot on tallessa aputaulussa ks_230531_items_k21399_2. Muutos koski 95235 nidettä.

`update items set notforloan = 0 where holdingbranch = "TOPK" and notforloan = 8;`

**Comment by PiaKusmin** [comment]
Kiitos! Hyvältä näyttää! Suljen tiketin.
