### ISSUE TITLE
Lappi: Tornion muutto - eräpäivät

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#400]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: TOPK (Tornion pääkirjasto)

Tornion kirjasto aloittaa takaisin muuton väistötiloista. Tarvitsisimme seuraavia toimenpiteitä:

Eräpäivät siirretään ajalla 8.2.2023 - 31.5.2023 -> 1.6.2023
Muutettavien eräpäivien määrä on niin suuri, ettei sitä voi tehdä itse eräajona.

Muutos tulisi tehdä 8.2.2023 heti aamulla.

**Comment by PiaKusmin** [comment]
Ajo näyttää menneen oikein. Kiitos Pasi! Suljen tiketin.

**Comment by PiaKusmin** [comment]
Tornion kirjaston remontti jatkuu. Tarvitsemme uuden ajon eräpäiville: 

Toimenpiteet koskevat siis toimipistettä: TOPK (Tornion pääkirjasto)
Eräpäivät siirretään ajalla 1.6.2023 - 27.6.2023 -> 28.6.2023

Muutettavien eräpäivien määrä on niin suuri, ettei sitä voi tehdä itse eräajona.

Muutoksen voi tehdä heti.

**Comment by emta001** [comment]
Ajo tehty seuraavalla rimpsulla:

`update issues set date_due = "2023-06-28 23:59:01" where branchcode='TOPK' and date_due between '2023-06-01' and '2023-06-28';`

Muutos koski 10855 lainaa.

**Comment by PiaKusmin** [comment]
Kiitos. Suljen tiketin.
