### ISSUE TITLE
Lappi: Tornion muutto - varaukset

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#402]
### Tukipyyntö

Toimenpiteet koskevat toimipistettä: TOPK (Tornion pääkirjasto)

Tornion kirjasto aloittaa takaisin muuton väistötiloista. Tarvitsisimme seuraavia toimenpiteitä:

Voimassa olevat varaukset keskeytetään heti. 
HUOM! Ei keskeytetä noutoa odottavia tai kuljetuksessa olevia, eikä muutos koske jo valmiiksi keskeytettyjä varauksia.

(TOPK merkitään ei-noutopisteeksi. Pia hoitaa kohan ylläpidon asetuksista.)

Aiemmin suoritetut vastaavanlainen toimenpide Redminen tiketissä #5212 (huom! siellä oli jotain sekaannusta!)

Ilmoitamme myöhemmin milloin keskeytetyt varaukset voidaan taas palauttaa aktiivisiksi.

**Comment by emta001** [comment]
Muutos tehty seuraavasti:

`UPDATE reserves SET suspend = 1 WHERE branchcode IN("TOPK") AND found IS NULL AND suspend = 0;`

**Comment by PiaKusmin** [comment]
Toimii hienosti. Suljetin tiketin ja avataan se sitten uudestaan, kun on tarve palauttaa keskeytetyt varaukset. Tai sitten teen siitä uuden tiketin. :)

**Comment by PiaKusmin** [comment]
Kirjasto avataan. Varausten keskeytykset tulisi purkaa perjantaina 16.6. heti aamulla. 

Muutos koskee toimipistettä: TOPK (Tornion pääkirjasto)
HUOM! Keskeytystä ei pureta asiakkaiden itsensä keskeyttämistä varauksista.

**Comment by paxed** [comment]
Muutos tehty tällä rimpsulla: `update reserves set suspend = 0 where branchcode = 'TOPK' and found is null and suspend = 1 and suspend_until is null;` ja koski 826 varausta.

Toivottavasti tuossa ei nyt ollut noita asiakkaiden keskeyttämiä mukana, koska niitä ei nähdäkseni saa mitenkään muuten rajattua pois kuin tuolla keskeytyspäivämäärällä - eli jos varaus on keskeytetty johonkin tiettyyn päivään asti, niin siitä ei otettu keskeytystä pois...

**Comment by PiaKusmin** [comment]
Kiitos. Tällä mennään. Mulla oli uudemmat varaukset, jotka olin itse keskeyttänyt, tulleet takaisin, mutta ei mitään. Olemme tiedottaneet asiakkaita asiasta.
