### ISSUE TITLE
MTYPEn seliteteksti tulostumaan kuittiin/ilmoituksiin

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#405]
### Tukipyyntö

Mm. ODUE1 ja ODUE2 -pohjiin on pyydetty lisäämään tieto niteen aineistotyypistä. Koodipätkällä <<biblioitems.itemtype>> saa kyllä tulostumaan aineistotyypille annetun auktorisoidun arvon (ALEHTI, KIRJA jne), mutta olisikohan template toolkitin avulla ollut mahdollista määritellä tulostumaan auktorisoidulle arvolle annettu selkokielinen kuvaus-teksti?

Kokeilin lisätä [ByWatersin ohjeista löytämäni mallin](https://bywatersolutions.com/education/hold-cancellation-reasons-and-notices) avulla ISSUESLIP-pohjan alkuun [% USE AuthorisedValues %] ja sen lisäksi tällaiset koodinpätkät:

- [% AuthorisedValues.GetByCode( 'MTYPE', biblioitems.itemtype, 'IS_OPAC' ) %]
- [% AuthorisedValues.GetByCode( 'MTYPE', biblioitem.itemtype, 'IS_OPAC' ) %]

...mutta ei mennyt nappiin sillä kuittiin tulostuu koodin paikalle tyhjä rivi. Onkohan tuota MTYPEn kuvaustekstiä mahdollista saada jollain konstilla tulostumaan vai pitääkö tyytyä tuohon <<biblioitems.itemtype>> antamaan auktorisoituun arvoon?

**Comment by lmstrand** [comment]
Kokeiletko, toimiiko jos laitat biblioitems.itemtypen kalanruotojen sisään:
<<biblioitems.itemtype>>

Ainakin CHECKOUT ja RENEW-pohjat tukevat tiedon hakemisen biblioitemsistä. Niillä pohjilla voi ainakin testata. ISSUE-kuittipohja ei sitä yhteisön ohjeen mukaan tue, joten pitäisi varmaan testata toisella kuittipohjalla. 
ODUE-pohjat tukevat biblioitems-tiedon hakemista.
https://wiki.koha-community.org/wiki/Customising_Notices_and_Slips
Tuolta näkee sarakkeesta accessible data muut kuittipohjat, missä tiedon voi hakea <<biblioitems.*>> -tapaan.

**Comment by ajrajala** [comment]
Kiitti Lari, tämä auttoi eteenpäin! Pelkillä kalanruotojen lisäämisellä tulostui vielä tyhjä rivi, mutta kun ympärille lisäsi hipsut '<<biblioitems.itemtype>>' niin johan tulostui CHECKOUT-kuittiin aineistotyypin kuvausteksti. Lähden tämän kanssa testamaan muutosta ODUE-pohjassa ja jos saadaan toimiva pohja aikaan niin lisäilen sen sitten vaikka [tänne](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Kuitti-_ja_viestipohjat).
