### ISSUE TITLE
Sotuteekin tunnukset jumissa

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#408]
### Tukipyyntö

Sotuteekkitunnus "satuleht" on lukittu, eikä sitä pysty hallinnan puolellakaan vapauttamaan. Käyttäjän saama virheilmoitus on tyhjä, ja tämän virheilmoituksen saa aikaan siten, että yrittää liian monta kertaa kirjautua väärällä käyttäjätunnus/salasanayhdistelmällä.

Pystyttekö vapauttamaan tunnuksen?

**Comment by janPasi** [comment]
Tällä käyttäjällä on 24 virheellistä kirjautumisyritystä. Olisiko aiheellita vaihtaa salasana?

**Comment by sksandel** [comment]
Voidaan vaihtaa salasana, mutta jos teen vain sen, niin käsittääkseni lukitus ei purkaudu. Pääkäyttäjillä ei siis ole keinoa vapauttaa tällaista tunnusta lukituksesta?

**Comment by janPasi** [comment]
Vaihtaisin tässä tapauksessa ehkä tunnuksenklin kun kirjautumisyrityksiä on noin paljon. Voin toki purkaa lukituksen suoraan tietokannasta, mutta olisiko kokonaan uusi tunnus järkevämpi tässä?

**Comment by sksandel** [comment]
Ok. Siinä tapauksessa pystymme tekemään itsekin. Suljen tiketin.

Käyttäjä itse ei kertomansa mukaan ole tehnyt montaa kirjautumisyritystä, vaan tunnukset olivat valmiiksi lukittuneet. Meillä saattaa toki tulla Koha-Suomen yhteisen Sotuteekin kanssa tilanteita, että yritetään vahingossa kirjautua toisen tunnuksilla. Esim Koha-tunnukset voivat olla samat ja sitten muistetaan Sotuteekin tunnus identtiseksi vaikkei se olisikaan, koska jollain muulla jo käytössä sen muotoinen tunnus.
