### ISSUE TITLE
Kohan Kori-toiminto

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#411]
### Kehitysehdotukseni

Olisiko Kohan Kori-toimintoa mahdollista muokata siten, että Nidetyyppi-sarakkeen sijaan korissa olisi Aineistotyyppi-sarake? Enemmän hyötyä kori-toiminnossa olisi 942c-kentän aineistotyypistä.

Kun siirsin Koriin tietueita, niin Nidetyyppi-sarake jäi tyhjäksi kokonaan. Testasin kaksi kertaa ja molemmilla kerroilla ko. sarake oli kaikkien tietueiden osalta tyhjä. Ehkä se ei osaa laittaa siihen mitään, jos saman teoksen niteillä on useita eri nidetyyppejä vai johtuuko tyhjyys nidetyyppimuutoksesta? Liitteenä kuva toisesta testistä.
![Kohan Kori-toiminto ja nidetyyppi](https://user-images.githubusercontent.com/98805552/217521408-a86e444b-3612-45d1-8ce9-f96324130839.png)

### Jotain muuta?

AnneliÖ kommentoi: Luulen, että tässä on sama ongelma kuin mitä oli lainassa-välilehdellä ja palautuksessa: 
https://github.com/KohaSuomi/Koha/issues/238
Eli yritetään näyttää aineistotyyppi, mutta koska meillä käytetään mtype-auktorisoitua arvoa aineistotyyppinä eikä Kohan omaa itemtypeä, niin Koha ei osaa näyttää sitä.

**Comment by piiaseme** [comment]
Alkuperäinen tiketti Redminessa #5237

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.2.2024: Aineistotyypin saaminen näkyviin olisi Koha-Suomen oma koodimuutos, jota ei kannata ylläpidollisesti tehdä. Piilotetaan sarake.

**Comment by atarnus** [comment]
Laitoin Outi-testille intranetuser.css:ään:

```
/* Piilota Nidetyyppi-sarake korissa */
#cart_basket th:nth-child(3),
#cart_basket td:nth-child(3) { display: none; }
```

Vaikuttaisi toimivan, eikä pitäisi piilottaa mitään muuta.

**Comment by piiaseme** [comment]
Kiitos! OUTI-testillä näyttäisi toimivan kuten pitää. Testaako joku muu kimppa tätä myös vai hujautanko rimpsun OUTIn tuotantoon ja NEXTille?

**Comment by atarnus** [comment]
Testatkaa vaan muuallakin, ja nextissäkin. Tuotantoon ei varmaan ihan vielä. Voitte lisätä itse intranetuser.css:ään.

**Comment by pknuuti** [comment]
Testasin Vaaran nextillä ja toimi kuten pitää.

**Comment by piiaseme** [comment]
> Testatkaa vaan muuallakin, ja nextissäkin. Tuotantoon ei varmaan ihan vielä. Voitte lisätä itse intranetuser.css:ään.

Jep, lisäsin rimpsun OUTIn nextille ja testasin. Hyvin toimii sielläkin.

**Comment by AnneliO** [comment]
CSS-rimsu lisätty Koha-Suomen verkkosivuille IntranetUserCSS-kirjastoon ja version 23.xx CSS-wikiin.

**Comment by piiaseme** [comment]
Rimpsu laitettu tarjolle tarvittaviin paikkoihin, joten suljen tämän tiketin.
