### ISSUE TITLE
Kirjastoyksiköiden nimen muutos

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#412]
### Tukipyyntö

Redminen tiketti: https://tiketti.koha-suomi.fi/issues/5548

Vaarassa on historiasta johtuen Juuan kirjastotunnus muotoa JOE_JUU, vaikka JOE muuten on Joensuun seutukirjaston tunnuksen alkuosa eikä Juuka kuulu seutukirjastoon. Juuan kirjaston tunnus pitäisi saada muotoon JUU_JUU.
Valtimon kirjasto on nykyisin osa Nurmeksen kirjastoa, kun Valtimon kunta liitettiin Nurmekseen. Valtimon tunnus VAL_VAL pitäisi saada muotoon NUR_VAL, niin olisi selkeää raporttien ym. kannalta.

**Comment by AnneliO** [comment]
Samantyyppinen muutos tiketissä #409.

**Comment by emta001** [comment]
Koha-Suomen palaveri 20.6.2023: Koha-Suomessa on linjattu, ettei kirjastoyksiköiden tunnisteita muuteta.
