### ISSUE TITLE
MARC-tietueen erämuokkauksessa uusi kenttä menee MARC-esikatselussa alimmaiseksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#413]
### Mikä vikana?

Siirretty Redminestä [tiketistä 3548](https://tiketti.koha-suomi.fi/issues/3548)

Kun MARC-tietueita muokkaa eräajona ja tietueisiin lisätään (tai kopioidaan toisesta kentästä tietoja) uuteen kenttään, menee uusi kenttä MARC-esikatselussa ihan alimmaiseksi eikä numeron mukaiseen järjestykseen. Jos lisää jo olemassa olevaan kenttään uuden osakentän, niin se järjestyy oikein.
![kuva](https://user-images.githubusercontent.com/33121325/217543715-456dce51-40bd-4889-b723-79c7c4857c3c.png)

Kyse siis tästä työkalusta:
https://koha.outikirjastot.fi:8080/cgi-bin/koha/tools/batch_record_modification.pl

---

Tämä ongelma korjattiin, mutta se palasi takaisin kun päivitettiin versioon 22.11.

### Mitä pitäisi tapahtua

Lisätty kenttä pitäisi mennä numerojärjestyksessä oikeaan kohtaan MARC-esikatselussa.

**Comment by Kati-Helle** [comment]
Samasta aiheesta tiketissä https://github.com/KohaSuomi/Koha/issues/312

**Comment by AnneliO** [comment]
Tuplatiketti, suljen.
