### ISSUE TITLE
OUTI: tarvitaan raporttiliitännäisessä ALL -tilaston ajo 

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#414]
### Tukipyyntö

OUTIn raporttiliitännäisessä oli määrittelyvirhe (meidän oma moka), joka korjattiin. OKM-raportti (36) ajettiin uudelleen korjaamisen jälkeen, mutta emme huomanneet pyytää raportin ALL 01.01.2022 - 31.12.2022 uudelleen ajamista. Saisimmeko sen nyt?

**Comment by emta001** [comment]
Vuositilastot on nyt ajettu uudestaan.

**Comment by piiaseme** [comment]
Tilastot on tsekattu ja hyviksi havaittu. Kiitos! Suljen tiketin.
