### ISSUE TITLE
OUTI: 007/06-kentän korjaus LP-levyille

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#416]
### Tukipyyntö

[Redmine-tiketistä #4082 ](https://tiketti.koha-suomi.fi/issues/4082)siirretty, vielä keskeneräinen.

Antti Heikkinen:

Kaikille LP-levyille voisi vielä tehdä tällaiset korjaukset 007-kenttään:

Aineistotyyppi LP-levy (LP)
        - 007/00 = s (Äänite)
        - 007/01 = d (Äänilevy)
        - 007/02 = # (tyhjämerkki)
        - 007/03 = jos jokin muu arvo kuin b tai c, niin arvoksi | (ei koodattu)
        - 007/04 = | (ei koodattu)
        - 007/05 = | (ei koodattu)
        - 007/06 = jos jokin muu arvo kuin c, d tai e, niin arvoksi e (12 tuumaa)
        - 007/07 = | (ei koodattu)
        - 007/08 = | (ei koodattu)
        - 007/09 = | (ei koodattu)
        - 007/10 = p (muovi)
        - 007/11 = | (ei koodattu)
        - 007/12 = | (ei koodattu)
        - 007/13 = | (ei koodattu)

Pasi Kallinen 23.3.2020:
Tämä tehty.

Antti Heikkinen 23.3.2020:
Kiitokset, mutta jostain kumman syystä tuo merkkipaikan 007/06 arvo on mennyt väärin niissä tapauksissa kun olisi pitänyt säilyä arvo e. Nyt niissä onkin jostain syystä arvo b, jota ei pitäisi olla ollenkaan.

Esimerkkitietue: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2042655

**Comment by AnttHeik** [comment]
@AnneliO Saisikohan jollakin raportilla haettua nuo tietueet, joissa merkkipaikalla 007/06 on arvo b? Mietin, että saattaisin sitten pystyä tietueiden erämuokkauksella korjaamaan tämän.

**Comment by AnneliO** [comment]
> @AnneliO Saisikohan jollakin raportilla haettua nuo tietueet, joissa merkkipaikalla 007/06 on arvo b? Mietin, että saattaisin sitten pystyä tietueiden erämuokkauksella korjaamaan tämän.

Antaisiko tämä [raportti](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=772&phase=Run%20this%20report) oikeanlaisia tuloksia?

**Comment by AnttHeik** [comment]
Kiitokset, kyllähän se näyttäisi antavan ja minä saisin nämä jopa korjattua, mutta osassa tietueista, joissa alun perinkin MARC-kentät ovat hassussa järjestyksessä, niin korjattu 007-kenttä menee aika hassuun paikkaan.
Esim.
![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/efbe3dfd-6e4b-483e-be4f-bb34f0d52b30)

Vrt. Tietue, jossa marc-kentät oikein:
![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/258c1dea-ffd5-402b-b060-c78338b96ec0)

Tää on kyllä muutenkin kummallinen juttu, miksi meillä ylipäänsä on tietueita, joissa 999-kentät ovat tuolla tietueen alussa.

**Comment by AnneliO** [comment]
> Kiitokset, kyllähän se näyttäisi antavan ja minä saisin nämä jopa korjattua, mutta osassa tietueista, joissa alun perinkin MARC-kentät ovat hassussa järjestyksessä, niin korjattu 007-kenttä menee aika hassuun paikkaan. Esim. ![kuva](https://private-user-images.githubusercontent.com/116169663/338536633-efbe3dfd-6e4b-483e-be4f-bb34f0d52b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA3MjQsIm5iZiI6MTcxODEwMDQyNCwicGF0aCI6Ii8xMTYxNjk2NjMvMzM4NTM2NjMzLWVmYmUzZGZkLTZlNGItNDgzZS1iZTRmLWJiMzRmMGQ1MmIzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMDA3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzBlNDFiYWM1NTBiOGIwZGYyZjlkZGVmNDFhNGZkMDFiYTBhMGZlYWEyZWM2ZDgwMDQ1ZmVjMjZlMjM1YTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8EMkDK-jcoXI6tyYtauF78CgkuoQGXlW6dp9VXsohok)
> 
> Tää on kyllä muutenkin kummallinen juttu, miksi meillä ylipäänsä on tietueita, joissa 999-kentät ovat tuolla tietueen alussa.

Joo, tuo 999 nyt sekottaa tuolla. Sinänsä 007 menee "oikeaan" kohtaan, koska se menee 000:n jälkeen, mutta ennen 999:ä. Noissa kenttien järjestäytymisessä on ollut vuosien varrella virheitä, joten ne on varmaan jossain vaiheessa vaan syntyneet, eikä olla muistettu tai hoksattu korjata niitä.

**Comment by AnneliO** [comment]
> Lisäksi olisi kova sana, jos tässä pystyisi vielä tekemään kaksi eri raporttia, joista toinen hakee tietueet, joilla merkkipaikka 007/03 on arvo b ja 007/06 on arvo b
> 
> ja toinen, jossa 007/03 on arvo c ja 007/06 on arvo b

Tutkailen näitä.

**Comment by AnttHeik** [comment]
> > Kiitokset, kyllähän se näyttäisi antavan ja minä saisin nämä jopa korjattua, mutta osassa tietueista, joissa alun perinkin MARC-kentät ovat hassussa järjestyksessä, niin korjattu 007-kenttä menee aika hassuun paikkaan. Esim. ![kuva](https://private-user-images.githubusercontent.com/116169663/338536633-efbe3dfd-6e4b-483e-be4f-bb34f0d52b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMDA3MjQsIm5iZiI6MTcxODEwMDQyNCwicGF0aCI6Ii8xMTYxNjk2NjMvMzM4NTM2NjMzLWVmYmUzZGZkLTZlNGItNDgzZS1iZTRmLWJiMzRmMGQ1MmIzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxMVQxMDA3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzBlNDFiYWM1NTBiOGIwZGYyZjlkZGVmNDFhNGZkMDFiYTBhMGZlYWEyZWM2ZDgwMDQ1ZmVjMjZlMjM1YTMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8EMkDK-jcoXI6tyYtauF78CgkuoQGXlW6dp9VXsohok)
> > Tää on kyllä muutenkin kummallinen juttu, miksi meillä ylipäänsä on tietueita, joissa 999-kentät ovat tuolla tietueen alussa.
> 
> Joo, tuo 999 nyt sekottaa tuolla. Sinänsä 007 menee "oikeaan" kohtaan, koska se menee 000:n jälkeen, mutta ennen 999:ä. Noissa kenttien järjestäytymisessä on ollut vuosien varrella virheitä, joten ne on varmaan jossain vaiheessa vaan syntyneet, eikä olla muistettu tai hoksattu korjata niitä.

Ok, taidan siitä huolimatta korjata nuokin, koska on hankala erottaa niitä erilleen tuolta joukosta, paitsi jos kaikki tuollaiset on alun perin Raahen tai Kuusamon tietuieta.

**Comment by AnneliO** [comment]
> Lisäksi olisi kova sana, jos tässä pystyisi vielä tekemään kaksi eri raporttia, joista toinen hakee tietueet, joilla merkkipaikka 007/03 on arvo b ja 007/06 on arvo b

[Raportti 1](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=773&phase=Run%20this%20report)
 
> ja toinen, jossa 007/03 on arvo c ja 007/06 on arvo b

[Raportti 2](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=774&phase=Run%20this%20report)

**Comment by AnttHeik** [comment]
> > Lisäksi olisi kova sana, jos tässä pystyisi vielä tekemään kaksi eri raporttia, joista toinen hakee tietueet, joilla merkkipaikka 007/03 on arvo b ja 007/06 on arvo b
> 
> [Raportti 1](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=773&phase=Run%20this%20report)
> 
> > ja toinen, jossa 007/03 on arvo c ja 007/06 on arvo b
> 
> [Raportti 2](https://outi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=774&phase=Run%20this%20report)

Kiitos, mutta saisitko rajattua nämä vielä äänilevyihin? Nyt tuolla raportti 2:lla tuli vain kaksi DVD-levyä. Raportti 1 kyllä antaa sitten äänilevyjä ainakin random-tarkistuksella, mutta johtuneeko siitä, että osuu jotenkin paremmin suoraan niihin.

**Comment by AnneliO** [comment]
Raportti 2 ei näyttänyt enää tuovan tuloksia. Rajasin raportin 1 vain äänilevyihin.

**Comment by AnttHeik** [comment]
> Raportti 2 ei näyttänyt enää tuovan tuloksia. Rajasin raportin 1 vain äänilevyihin.

Kiitokset, eli ei löytynyt viallisia 45rpm-levyjä vaan pelkkää 33 1/3:sta :) Tällä minä saan nämä korjattua, joten tiketin voinee sulkea.

**Comment by AnneliO** [comment]
Hyvä juttu! Miepä suljen tiketin. :)
