### ISSUE TITLE
Helle: viivakoodi-arvon (952p) lisääminen tietyille niteettömille tietueille massana

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#419]
### Tukipyyntö

Tiedot Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/4959
Start date: 30/06/2021

Kati Sillgren

Saisitteko lisättyä massana viivakoodin (arvo 952p) tietyille niteettömille tietueille? Voivatko massana lisätyt viivakoodit olla tietyn alun omaavia juoksevanumeroisia arvoja?
Kyseisiä niteettömiä tietueita on 3220. Tietueiden tietuenumeroista (biblionumber) on listaus.

Niteille kuuluvat muut tarvittavat arvot saamme lisättyä (signumia lukuun ottamatta) toiminnolla Niteiden muokkaus eräajona.

---

Pasi Kallinen
Katri Sillgren kirjoitti:

    Saisitteko lisättyä massana viivakoodin (arvo 952p) tietyille niteettömille tietueille?

Kyllä.

    Voivatko massana lisätyt viivakoodit olla tietyn alun omaavia juoksevanumeroisia arvoja?

Kyllä.

---

Kati Sillgren
Lisättävän viivakoodin alkuna on aina:
PORBOR000

Tyyliin:

PORBOR0001
PORBOR0003219

Lisättäviä viivakoodeja on 3219 (ei siis 3220 kuten ensin ilmoitin).

Listaus tietuenumeroista liitetiedostossa.
(Redminessä on tekstitiedostona listaus 3219 tietueesta, joita tukipyyntö koski tiketin kommentointihetkellä.)

---

Pasi Kallinen
Nuo näyttäis olevan artikkeleita joilla ei ole niteitä, ja tuo 952-kenttä on kohan asetuksissa mäpätty items-tauluun, eli esim. 952p on items.barcode. Joten kun niillä ei ole niteitä, niin ei voi viivakoodiakaan lisätä tuohon kenttään.

---

Kati Sillgren
Joo, kyseessä on tietueet Porvoota käsittelevistä artikkeleista, joille ei ole lisätty nidettä. Niteellisinä tietueet välttyisivät vahinkopoistoilta. Lisäksi Helle-Finnassa artikkelin sijaintitiedon saisi paremmin näkyviin. Käsin niteiden lisääminen on melkoinen urakka...

---

Pasi Kallinen
Eli näille pitää siis luoda niteet, ei pelkästään viivakoodi. Niihin niteisiin kyllä varmaan tarviaa lisätä muitakin tietoja kuin vain viivakoodin? Mitkä tiedot saa tietueen marcista, ja mitkä pitää luoda muuten? Ja millä arvoilla?

-----

Kati Sillgren
Tietueen Marcista saa signumin 952o toisen arvon tietueen kentästä 084a.
Signumin ensimmäiseksi arvoksi tulee aina KO. Esim. tietueen 084|a = 42.34 jolloin signum KO 42.34

Niteen muut arvot:

Ei lainata, ei varata -nidetila
952|7 = 1

Saapumispäivä
952|R = 2018-06-01 00:00:00

Omistajakirjasto
952|a = PRVPK

Sijaintikirjasto
952|b = PRVPK

Hyllypaikka
952|c = KO

Hankintapvm
952|d = 2018-06-01

Korvaushinta
952|v = 5.00

Nidetyyppi
952|y = ARTIKKELI

Yleinen huomautus
952|z = Porvoo: pääkirjaston artikkelikokoelmassa. Borgå: i huvudbibliotekets artikelsamling

**Comment by lasse-koha** [comment]
Niteet lisätty.

**Comment by Kati-Helle** [comment]
Kiitos Lasse! 
Hienoa, että Porvoon artikkeli-tietueilla on nyt nide ja niteillä pyydetyt arvot.

Huomasin vasta nyt, että niteiden nidetyyppi itype on pyynnössäni = ARTIKKELI eli arvo, jota käytettiin alkuperäisen Redmine-tiketin tekoaikana, mutta ei enää. Muutan luomillesi niteille Niteiden muokkaus eräajona -toiminnolla oikean itype-arvon EILAINATA.
