### ISSUE TITLE
Helle: kausijulkaisutilauksen tilaustietojen verkkokirjastolinkkinä on Kohan verkkokirjasto-osoite

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#420]
### Mikä vikana?

Tiedot siirretty Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/5630
Start date: 30/09/2022

Kati Sillgren
Hellen kausijulkaisutilauksen tilaustiedoissa Verkkokirjastonäkymä-linkkinä on Kohan Opac. Saako linkin viemään Hellen käytössä olevaan verkkokirjastoon?

Hellen verkkokirjasto osoitteessa:
https://helle.finna.fi/

![kuva](https://user-images.githubusercontent.com/99952449/217766119-575d75fa-146d-4e96-8a1a-c3a8d4d0ceac.png)

---

Anneli Österman
related to [Bugi #5440](https://tiketti.koha-suomi.fi/issues/5440): Koriin linkki teokseen verkkokirjastossa added

**Comment by emta001** [comment]
Koha-Suomen palaveri 20.6.2023: Piilotetaan linkki IntranetuserCSS asetuksella. Tilausnäkymästä ei liene tarvetta päästä verkkokirjastoon.

**Comment by Kati-Helle** [comment]
Kiitos Emmi tiedosta.

Tarkistin näkymän nykyisessä Koha-versiossa 22.11: linkkiä ei enää näy (ainakaan vastaavassa kohdassa)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/a8d459eb-4ff7-4c93-bcf0-cb89db79a781)

Suljen tiketin.
