### ISSUE TITLE
Asiakkaat joilla on eniten lainoja -toiminto: nidetyyppi-hakuehdolla rajaus ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#427]
### Mikä vikana?

Tiedot Redmine-tiketistä https://tiketti.koha-suomi.fi/issues/5213
Start date: 13/01/2022

Kati Sillgren
Nidetyyppi-hakuehdolla rajaus ei toimi.
Hellessä toivottu toimintoon Aineistotyyppi-hakuehtoa.

---

Anneli Österman
Onko tuo nidetyyppi-rajaus toiminut aiemmin? En ole varmaan koskaan testannut sitä vaihtoehtoa (enkä juuri kyllä raporttiakaan).

Tuo raportti on Kohan ns. sisäisiä raportteja, joihin muutoksen tekeminen vaatii Kohan koodiin muutoksia. Niitä ei mielellään tehdä, koska ne vie kauemmaksi yhteisöversiosta.

---

Kati Sillgren
Raportin toiminnan puutteesta ilmoittanut ei nyt muistanut, onko toiminut oikein aiemmin.

Katsoin Koha-Suomen ohjeesta. Ohjeen hakuesimerkkihaussa ei ole käytetty Aineistolaji-hakuehdon arvoa
https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/7_Raportit#Asiakkaat-joilla-on-eniten-lainoja

Lisään tikettiin muutaman esimerkin Helle-Kohan tämän hetken hakutuloksista (nidetyyppiä on käytetty hakuehtona ja nidetyyppiä ei ole käytetty hakuehtona).

![kuva](https://user-images.githubusercontent.com/99952449/217811455-efa541ab-cd10-4f5d-a8e4-ccfefbdf3cf7.png)

![kuva](https://user-images.githubusercontent.com/99952449/217811552-2f4790d0-bddc-43a1-926d-3515f376d57c.png)

---

Kati Sillgren
Kohan Eniten lainattu aineisto -toiminnossa saa tuloksen valitulla Nidetyyppi-hakuehtorajauksella.

---

Kati Sillgren
Versio 21.11 ei ole tuonut muutosta/parannusta tähän.

Raportit/Asiakkaat, joilla on eniten lainoja -toiminto: ei tulosta Nidetyyppi-hakuehtorajauksella.
Tulokseton hakutulosnäyttö ilmestyy heti haun käynnistämisen jälkeen.

Raportit/Eniten lainattu aineisto -toiminto: hakutuloksen saa valitulla Nidetyyppi-hakuehtorajauksella.
Hakutuloksen muodostuminen kestää jonkin aikaa.

**Comment by AnneliO** [comment]
En tiedä, liittyykö tämä yhteisön bugi aiheeseen, mutta ainakin tuohon toimintoon: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32116

**Comment by emta001** [comment]
Koha-Suomen palaveri 20.6.2023: Ei korjata Koha-Suomen toimesta, odotetaan että yhteisöstä korjausta. Jos tällaiselle tiedolle on tarvetta, käyttäkää SQL-raporttia.

**Comment by AnneliO** [comment]
Testasin tätä OUTIn ja Hellen tuotannossa. Sain OUTIssa tuloksia, mutta en Hellessä. Tosin, OUTIn tulokset olivat kyllä tosi pieniä, joten ehkä tämä toiminto ei toimi oikein muutenkaan.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 2.9.2024: @Kati-Helle teetkö tästä yhteisötiketin. Suljemme tämän tiketin meidän osalta. :)
