### ISSUE TITLE
OUTI: Omatoimiovikoneen tietojen tallentaminen palvelimelle

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#428]
### Tukipyyntö

Hei, lähetin support-postiin palvelimelle tallennettavan SIP2-tunnuksen tiedot.

**Comment by lmstrand** [comment]
Lisätty. On huomenna käytettävissä.

**Comment by piiaseme** [comment]
Kiitos. Suljen tiketin.
