### ISSUE TITLE
Lumme (Varkaus): asiakkaille tullut uudestaan näkyviin jo maksettuja maksuja (versionvaihdon yhteydessä)

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#430]
### Mikä vikana?

Asiakasnumeroilla 73719 ja 75351 on tullut uudelleen näkyviin vanhoja maksuja. Voiko näitä olla enemmänkin :O ? Asiakkaalta 73719 poistettiin maksut, joten tilanne ei enää ajantasainen mutta 75351 jätettiin hänen luvallaan näkyviin 7.6.22 palautuneet maksut.

![image](https://user-images.githubusercontent.com/98803917/218381144-623e7a11-f88f-4fec-948d-66b178d22229.png)

![image](https://user-images.githubusercontent.com/98803917/218381242-ba609e91-696d-4afd-bbce-6d5e28e22687.png)

**Comment by emta001** [comment]
Kyseisellä asiakkaalla näyttää olevan sama tilanne Lumpeen testillä.

**Comment by AnneliO** [comment]
7.6.2022 on versionvaihdon päivämäärä ja se näkyy kaikilla sitä ennen syntyneillä maksuilla päivityspäivänä.

Jos lasken asiakkaan 75351 tapahtumahistoriasta maksut ja maksusuoritukset, niin loppusumma täsmää. Onko asiakkaalla kuitti tuosta jäljellä olevasta 31 eurosta vai millä perusteella ne ajatellaan olevan jo kertaalleen maksettu? :)

**Comment by Katja-Lumme** [comment]
Asiakkaat olivat sanoneet että maksut jo maksettu, mutta ehkäpä näitä nyt sattui vain kaksi lähekkäin joilla maksuja maksamatta. Avataan ihmettely uudelleen jos tulee lisää, kiitokset @AnneliO ja @emta001 :)
