### ISSUE TITLE
Vaskin OKM-raportin 1.1.2022-31.12.2022 uudelleenajo

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#433]
### Tukipyyntö

Olisikohan mahdollista ajaa Vaskille pikaisesti uudelleen tuorein OKM-raportti (eli ajalta 1.1.2022-31.12.2022)? Meillä havaittiin, että kolmen kunnan tilastoryhmiin oli lipsahtanut mukaan koulukirjastot ja niiden lukuja ei haluta sisällyttää suoraan kaupungin-/kunnankirjaston OKM-lukuihin.

Ei-toivotut koulukirjastot kävin jo poistamassa OKM-ryhmistä.

**Comment by emta001** [comment]
OKM-tilastot ajettu uusiksi.

**Comment by ajrajala** [comment]
Sellainen kysymys vielä, että mistä johtuu esim. "Kokoelmat (koti) yhteensä" -sarakkeessa eroavaisuus luvuissa aiemmin ajetussa raportissa ja nyt ajetusssa raportissa? ZL_OKM-ryhmän luku oli ilmeisesti aiemmin ollut 59 068 ja nyt se on 58 776. Tuota tullaan seuraavaksi nimittäin varmaan kysymään ja huomasin etten osaa tarjota itse siihen selitystä. :D

**Comment by emta001** [comment]
> Sellainen kysymys vielä, että mistä johtuu esim. "Kokoelmat (koti) yhteensä" -sarakkeessa eroavaisuus luvuissa aiemmin ajetussa raportissa ja nyt ajetusssa raportissa? ZL_OKM-ryhmän luku oli ilmeisesti aiemmin ollut 59 068 ja nyt se on 58 776. Tuota tullaan seuraavaksi nimittäin varmaan kysymään ja huomasin etten osaa tarjota itse siihen selitystä. :D

Eli ilmeisesti ZL_OKM-ryhmästä ei tiputettu koulukirjastoja?

**Comment by ajrajala** [comment]
Joo, ZL_OKM-ryhmästä ei poistettu mitään, ryhmä säilyi entisellään (sisältää yhden yksikön, KKLI).

**Comment by emta001** [comment]
Onkohan tässä tammi-helmikuun aikana tehty mahdollisesti poistoja? Onko niteiden kotikirjastoja vaihtunut?

**Comment by emta001** [comment]
Ei miulla näemmä enää eilen iltapäivällä ollut aivotoiminta kovin vahvaa, kun väitin ettei poistot muka vaikuta. Tietysti ne vaikuttaa, koska niitähän ei enää ole items-taulussa kun tilasto otetaan. 

Tarkistin nyt kannasta paljonko KKLI:ssä on tehty poistoja aikavälillä 1.1.-14.2.2023 ja tulos oli 296. Vastaisi aika tarkalleen tuota lukua joka tilastoista nyt puuttuu.

**Comment by ajrajala** [comment]
Nojuu, loogistahan tuo on että poistot vaikuttaa, kiitos vastauksesta!
