### ISSUE TITLE
TUVR-yksikön varausten keskeytyksen jatko

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#434]
### Tukipyyntö

Varissuon kirjaston kiinniolo jatkuu yli suunnitellun ajan. Tämän takia pitäisi jatkaa aiemmin keskeytettyjen varausten keskeytysaikaa:

branchcode = TUVR
Keskeytyksen päättymisaika nyt 12.3.2023 

Näille varauksille asetetaan uusi keskeytyksen päättymisaika: 19.3.2023

### Jotain muuta?

Tähän liittyvä toteutettu työpyyntö: https://github.com/KohaSuomi/Koha/issues/294

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [vaskiprod]> update reserves set suspend_until='2023-03-19' where branchcode = 'TUVR' and suspend = 1 and suspend_until='2023-03-12' and found is null;
Query OK, 375 rows affected (0.007 sec)
Rows matched: 375  Changed: 375  Warnings: 0
```

**Comment by lmstrand** [comment]
Huom! ajoon lähti mukaan myös mahdollisia asiakkaan itse määrittelemiä keskeytyksiä, jotka osuivat tuolle päivälle ja nekin on siirretty nyt.

**Comment by ajrajala** [comment]
Pahoittelut, tämä tiketti on jäänyt kuittaamatta. Mutta ajo siis ok, ja ei haittaa jos joukossa mahdollisia samalle päivälle osuneita, asiakkaan itse tekemiä keskeytyksiä.
