### ISSUE TITLE
Palautustilanteessa perutusta varauksesta tulee noutamattoman varauksen maksu

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#436]
### Mikä vikana?

Redminen tiketti: https://tiketti.koha-suomi.fi/issues/2828 

Jos kiinni jäänyt varaus perutaan palautustilanteessa, kun palautus tehdään ohjelman yläreunassa olevassa Palauta-kentässä, syntyy varauksen poistosta asiakkaalle noutamattoman varauksen maksu. 
![image](https://user-images.githubusercontent.com/98814860/219003747-41ea84fb-4977-4f54-8064-a57dd75efd61.png)

Jos kiinni jäänyt varaus perutaan Palautus-sivulla (https://outi.koha-suomi.fi/cgi-bin/koha/circ/returns.pl) ja asetuksissa on määritelty "Poista käsin poistettujen varausten maksut", ei asiakkaalle synny noutamattoman varauksen maksua.
![image](https://user-images.githubusercontent.com/98814860/219005230-d3f94505-7b26-41e2-be7b-59bdbd0b15e8.png)

### Mitä pitäisi tapahtua

Noutamattoman varauksen maksua ei pitäisi syntyä koskaan asiakkaalle, kun virkailija poistaa varauksen manuaalisesti. Nyt maksu tulee asiakkaalle, riippuen siitä, missä palautuskentässä tekee palautuksen ja poistaa varauksen.

**Comment by janPasi** [comment]
Luulen, että ongelmana tässä on se, että toisella templatella ruksi ruudussa "Poista käsin palautettujen varausten maksut" ei ole missään missä se olisi sen palauta-kentän peruutustoiminnallisuuden käytettävissä. Teknisesti voi olla hyvin hankala saada toteutettua toiminnallisuutta siten että se toimisi jokaisessa mahdollisessa tilanteessa johdonmukaisesti. Ehdotan että varausten perumistoiminnallisuus piilotetaan kaikkialta muualta paitsi asiakkaan varausnäytöltä. Varausten peruminen tehtäisiin siis aina siellä, jolloin se toimisi johdonmukaisesti.

**Comment by IrinaHalminen** [comment]
Tästä tuli juuri eilen ihmettelyä Vaarassa sen takia, että maksu oli tullut lapsiasiakkaalle, jolle ei pitäisi ko. maksuja tulla ollenkaan. Mutta ne siis (normaalitilanteessa muodostuessaan) ilmeisesti ajetaan erikseen pois?

**Comment by AnneliO** [comment]
> Tästä tuli juuri eilen ihmettelyä Vaarassa sen takia, että maksu oli tullut lapsiasiakkaalle, jolle ei pitäisi ko. maksuja tulla ollenkaan. Mutta ne siis (normaalitilanteessa muodostuessaan) ilmeisesti ajetaan erikseen pois?

Juu, normaalitilanteessa maksu kyllä muodostuu kaikille, mutta ne poistetaan/nollataan samantien tietyiltä asiakastyypeiltä. Tähän liittyy esim. tiketti #404.

**Comment by pirliis** [comment]
OUTIssa on palautuspopparista piilotettu varauksen poistovaihtoehto, joten ongelma tältä osin korjaantunut. Suljen tiketin.
