### ISSUE TITLE
Vaski: Korjauksia osakohteiden aineistolajeihin (musiikkitallenne)

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#438]
### Tukipyyntö

Siirretty Redminestä (https://tiketti.koha-suomi.fi/issues/4901)

Vaskissa on paljon puutteellisesti koodattuja osakohteita musiikin äänitteissä. Finnassa/Aurorassa tästä ei ole aiheutunut ongelmia tiedonhaussa, koska niiden haku kohtelee osakohdetta ja emoa eri tavalla kuin Koha. Nyt osakohteita pitäisi korjata, että saamme aineistolajihakuja Kohassa siistittyä.

Käytännössä kyse on siitä, että musiikkitallenne-aineistolajin tilalle pitäisi saada äänilevy tai CD.

942c:n lisäksi olisi tietysti hyvä saada osakohteille myös oikeat koodit kiinteämittaisiin kenttiin. Jos tuo on liian työlästä, myös pelkkä 942c:n korjaaminen auttaisi tiedonhaun selkeyttämisessä.

Musiikkitallenne-aineistolaji on voinut muodostua tietueelle monen erilaisen virheen takia (puuttuvia koodeja 007-kentässä tai kokonaan puuttuva 007). Olemassa oleviin koodeihin perustuvaa korjausta on siksi hankala ehdottaa.

Emotietueissa meillä on jo kutakuinkin kattavasti riittävät koodit. Emon koodien ja 942c:n kopiointi niille osakohteille, joiden aineistolajina on musiikkitallenne, olisi siis yksi vaihtoehto.

Jos emojen käyttäminen on mahdotonta, onnistuisiko korjaus osakohteiden 773m-kentässä olevan tiedon perusteella. Jos ko. osakentässä esiintyy ”CD-äänilevy”, tietueen aineistolajin kuuluu olla CD. Jos 773m-kentässä on ”äänilevy”, aineistolajin pitäisi olla äänilevy.

Mahdollisesti teillä on joku korjausviritys näille jo valmiinakin muiden Koha-kirjastojen peruja…?

### Jotain muuta?

Historia
[#1](https://tiketti.koha-suomi.fi/issues/4901#note-1) Updated by [Kodo Korkalo](https://tiketti.koha-suomi.fi/users/20) [yli vuosi](https://tiketti.koha-suomi.fi/projects/fbox/activity?from=2021-05-26) ago
[Vastaa](https://tiketti.koha-suomi.fi/issues/4901/quoted?journal_id=21412) [Muokkaa](https://tiketti.koha-suomi.fi/journals/21412/edit) [Poista](https://tiketti.koha-suomi.fi/journals/21412?journal%5Bnotes%5D=)
Korjaus täytyy kohdistaa osakohteiden kiinteämittaisiin kenttiin. Jatkossa aineistotyyppi määräytyy pluginilla suoraan kiinteämittaisten kenttien perustella, joten pelkkä 942-kentän korjaaminen ei ole pysyvä ratkaisu (aineistolaji muuttuu pluginilla takaisin "vääräksi" tietuetta käsiteltäessä).

[#2](https://tiketti.koha-suomi.fi/issues/4901#note-2) Updated by [Pasi Kallinen](https://tiketti.koha-suomi.fi/users/451) [yli vuosi](https://tiketti.koha-suomi.fi/projects/fbox/activity?from=2021-05-26) ago
[Vastaa](https://tiketti.koha-suomi.fi/issues/4901/quoted?journal_id=21414) [Muokkaa](https://tiketti.koha-suomi.fi/journals/21414/edit) [Poista](https://tiketti.koha-suomi.fi/journals/21414?journal%5Bnotes%5D=)
Jotain valmiita korjausskriptejä on, ja uusien kirjottaminen ei ole mikään iso homma. Mutta tarviisin tarkat tiedot mitä tehdään.

Eli muutama esimerkkitiketti tehdyistä korjauksista: [#4708](https://tiketti.koha-suomi.fi/issues/4708) [#4376](https://tiketti.koha-suomi.fi/issues/4376) [#4199](https://tiketti.koha-suomi.fi/issues/4199) [#4073](https://tiketti.koha-suomi.fi/issues/4073) [#4075](https://tiketti.koha-suomi.fi/issues/4075)

Kaikenlainen tietueiden muokkaus onnistuu kyllä, kunhan on määritelty tarpeeksi tarkasti mitä tehdään ja millä ehdoilla, esim. mitä jos tietueessa on jos valmiiksi olemassa lisättävä kenttä, tai jos toistettavaa kenttää onkin useampi kappale, tai kenttää josta haetaan tieto ei olekaan olemassa, tai kiinteämittasissa kentissä onkin virheelistä dataa, jne. Eli ensin mielellään rajataan muutos johonkin tiettyyn joukkoon tietueita, ja sitten mitä/miten muutetaan ja millä ehdoilla. Vaikka logitan kyllä tehdyt muutokset noissa skripteissä, niin jälkikäteen korjausajojen ajaminen on työläämpää...

[#3](https://tiketti.koha-suomi.fi/issues/4901#note-3) Updated by [Anna Viitanen](https://tiketti.koha-suomi.fi/users/929) [yli vuosi](https://tiketti.koha-suomi.fi/projects/fbox/activity?from=2021-05-26) ago
[Vastaa](https://tiketti.koha-suomi.fi/issues/4901/quoted?journal_id=21415) [Muokkaa](https://tiketti.koha-suomi.fi/journals/21415/edit) [Poista](https://tiketti.koha-suomi.fi/journals/21415?journal%5Bnotes%5D=)
Pasi Kallinen kirjoitti:

Jotain valmiita korjausskriptejä on, ja uusien kirjottaminen ei ole mikään iso homma. Mutta tarviisin tarkat tiedot mitä tehdään.

Eli muutama esimerkkitiketti tehdyistä korjauksista: [#4708](https://tiketti.koha-suomi.fi/issues/4708) [#4376](https://tiketti.koha-suomi.fi/issues/4376) [#4199](https://tiketti.koha-suomi.fi/issues/4199) [#4073](https://tiketti.koha-suomi.fi/issues/4073) [#4075](https://tiketti.koha-suomi.fi/issues/4075)

Kaikenlainen tietueiden muokkaus onnistuu kyllä, kunhan on määritelty tarpeeksi tarkasti mitä tehdään ja millä ehdoilla, esim. mitä jos tietueessa on jos valmiiksi olemassa lisättävä kenttä, tai jos toistettavaa kenttää onkin useampi kappale, tai kenttää josta haetaan tieto ei olekaan olemassa, tai kiinteämittasissa kentissä onkin virheelistä dataa, jne. Eli ensin mielellään rajataan muutos johonkin tiettyyn joukkoon tietueita, ja sitten mitä/miten muutetaan ja millä ehdoilla. Vaikka logitan kyllä tehdyt muutokset noissa skripteissä, niin jälkikäteen korjausajojen ajaminen on työläämpää...

OK, kaivelen siis vielä eri virhevaihtoehdot esiin ja katson mitä niille pitäisi tehdä.

[#4](https://tiketti.koha-suomi.fi/issues/4901#note-4) Updated by [Anna Viitanen](https://tiketti.koha-suomi.fi/users/929) [yli vuosi](https://tiketti.koha-suomi.fi/projects/fbox/activity?from=2021-05-31) ago
[Vastaa](https://tiketti.koha-suomi.fi/issues/4901/quoted?journal_id=21463) [Muokkaa](https://tiketti.koha-suomi.fi/journals/21463/edit) [Poista](https://tiketti.koha-suomi.fi/journals/21463?journal%5Bnotes%5D=)
Tässä korjattavia tapauksia. Emon 007-kentän koodit ovat korjattavien tietueiden määrittelemisessä kai turhia, jos/kun emon 942c:tä voidaan hyödyntää.

Tapaus A

Emoissa 942c AANILEVY + nämä koodit

000/06 = j
007/00 = s
007/01 = d
007/10 = p

Osakohteissa 942c MUSATAL

→ jos osakohteella on 007-kenttä, se korvataan emon 007-kentällä + osakohteen 942c → AANILEVY
→ jos osakohteella ei ole 007-kenttää, sille kopioidaan emon 007 + osakohteen 942c → AANILEVY

Tapaus B

Emossa 942c = CD + nämä koodit

000/06 = j
007/00 = s
007/01 = d
007/06 = g
007/10 = m

Osakohteissa 942c MUSATAL

→ jos osakohteella on 007-kenttä, se korvataan emon 007-kentällä + osakohteen 942c → CD
→ jos osakohteella ei ole 007-kenttää, sille kopioidaan emon 007 + osakohteen 942c → CD

[#5](https://tiketti.koha-suomi.fi/issues/4901#note-5) Updated by [Anna Viitanen](https://tiketti.koha-suomi.fi/users/929) [yli vuosi](https://tiketti.koha-suomi.fi/projects/fbox/activity?from=2021-05-31) ago
[Vastaa](https://tiketti.koha-suomi.fi/issues/4901/quoted?journal_id=21464) [Muokkaa](https://tiketti.koha-suomi.fi/journals/21464/edit) [Poista](https://tiketti.koha-suomi.fi/journals/21464?journal%5Bnotes%5D=)
Ja vielä kolmas tapaus

Emossa 942c = CD + nämä koodit

000/06 = j
007/00 = s
007/01 = d
007/06 = g
007/10 = m

Osakohteissa 942c AANILEVY

→ osakohteen 007-kenttä korvataan emon 007-kentällä + osakohteen 942c → CD

**Comment by sksandel** [comment]
Tämä oli odottaa tilassa, mutta voisiko tämän siirtää työn alle? 

Joku deadline pitäisi ehkä sopia?

**Comment by AnttHeik** [comment]
Hei, onko teillä Vaskissa sellaisia tapauksia, joissa emolla on erilaisia osakohteita, esim. CD, DVD ja Blu-ray ja nämä näkyvät sitten nyt Musiikkitallenteina? OUTIsta näitä ainakin näyttää löytyvän. Mietin, että onko tässä vielä yksi tapaus, joka olisi syytä huomioida.

**Comment by sksandel** [comment]
Tuollaisia Antin mainitsemia tapauksia saattaa olla joukossa. Niiden määrä on kuitenkin niin vähäinen, ettemme ole halunneet yrittää ottaa niitä korjauksessa huomioon. Korjattavia musiikkitallenne -osakohteita on paljon ja tärkeintä olisi saada suurimmat virheet korjattua.

**Comment by AnttHeik** [comment]
> Tuollaisia Antin mainitsemia tapauksia saattaa olla joukossa. Niiden määrä on kuitenkin niin vähäinen, ettemme ole halunneet yrittää ottaa niitä korjauksessa huomioon. Korjattavia musiikkitallenne -osakohteita on paljon ja tärkeintä olisi saada suurimmat virheet korjattua.

Joo, katselin läpi noita OUTIn korjattavia musiikkitallenne-osakohteita, ja mietin, että suurin osa aineistosta on sen verran vanhaa, että niissä voi olla niinkin, että niihin on kuvailtu osakohteet vain kerran eikä välttämättä esim. liite-DVD:n osakohteita ole mukana.

**Comment by MikkoLiimatainen** [comment]
Mikähän näiden korjausten tilanne on? Olisikohan nämä mahdollista saada tehtyä, vai selvitämmekö muokkausten tekoa erätyökalujen avulla? Alustavasti olen katsonut, että tarvittavat muokkaukset pystytään tekemään, mutta se vaatii jonkin verran aikaa, että saan muotoiltua sopivat raportit ja testattua tarvittavat muokkaukset testiympäristössä.

**Comment by CodoDerDritte** [comment]
Suunnitelmissa on siirtyminen jaettuun kuvailutietovarantoon (KaTi, Kaikki Tietueet). Yksittäisten kimppojen tietueisiin ei ehkä enää tässä vaiheessa ryhtyä tekemään laajoja korjausajoja, koska tietueet vedetään kuitenkin KaTin myötä yhteen tietokantaan ja deduplikoidaan. Sen jälkeen korjausajot voisi tehdä suoraan siellä keskitetyssä tietokannassa, jolloin ne koskisivat kaikkia säilytettäväksi valikoituja tietueita kerralla eikä ylimääräistä työtä tulisi sen vuoksi tehtyä.

**Comment by ajrajala** [comment]
Oliko tuolle jaettuun kuvailutietovarantoon siirtymiselle millainen aikataulu tällä hetkellä?

**Comment by CodoDerDritte** [comment]
> Oliko tuolle jaettuun kuvailutietovarantoon siirtymiselle millainen aikataulu tällä hetkellä?

Aikataulua ei ole lyöty lukkoon vielä. Työkalujen kehitys on kesken eikä meillä ole vielä tietueiden valintasäännötkään selvillä. Tätä varten päätettiin perustaa muistaakseni joku työryhmä tai muuta jossain kohtaa.

**Comment by MikkoLiimatainen** [comment]
Nämä muutokset on nyt tehty erämuokkauksella.

Ajattelimme, että tämä prosessi saattaisi kiinnostaa muitakin, joten tässä lyhyt kuvaus, miten muokkaukset tehtiin.

Tein kaksi MARC-muokkauspohjaa osakohteen muuttamiseksi äänilevyksi tai CD:ksi. Muokkauspohjissa ensin päivitetään osakenttä 942c haluttuun arvoon, sitten poistetaan 007-kenttä ja lisätään uusi 007-kenttä. Uudelle 007-kentälle haetaan raportilla arvo emotietueesta ja se pitää vaihtaa jokaista erämuokkausta varten.

![Musiikin osakohdekorjaus muokkauspohja 2024-07-26 121001](https://github.com/user-attachments/assets/0a6f5263-4636-4839-815a-e2f52dff3921)

Erämuokkaukseen vietiin kerralla kaikki osakohteet, joiden emotietueissa oli sama 007-kentän arvo. Tätä varten tein jokaista kuvattua tapausta varten raportin, jossa ryhmittelin tulokset emotietueen 007-kentän mukaan. Tästä oli helppo poimia sekä emokohteen 007-kentän arvo muokkauspohjaan, että osakohteet erämuokkaukseen. Ainoastaan yhden tapauksen kohdalla osakohteiden määrä oli niin suuri, että jouduin määrittelemään raportille vain sen tapauksen 007-kentän arvon ja poistamaan ryhmittelyn, jolloin pystyin rajaamaan tulosten määrän 10000:een ja viemään ne joukkona erämuokkaukseen.

![Musiikin osakohdekorjaus tulos 2024-07-26 121702](https://github.com/user-attachments/assets/2145ef4a-4cb5-4806-b0af-9f7ceffa4e41)

Kaikki sarakkeet raportilla eivät olleet tarpeellisia erämuokkausta ajatellen, mutta käytin niitä tilanteen kartoittamiseen ja esimerkiksi löytämään emotietueita, joita täytyy mahdollisesti muokata ennen osakohteiden erämuokkauksia. 

Esimerkkiraportti:
```
SELECT GROUP_CONCAT(t1.773m SEPARATOR '</br>') AS 'osakohteet 773m',
  GROUP_CONCAT(t1.942c_osakohde SEPARATOR '</br>') AS 'osakohteet 942c',
  GROUP_CONCAT(t1.942c_emokohde SEPARATOR '</br>') AS 'emokohteet 942c',
  CONCAT('<pre>',GROUP_CONCAT(t1.007_osakohde SEPARATOR '</br>'),'</pre>') AS 'osakohteet 007',
  CONCAT('<pre>',t1.007_emokohde,'</pre>') AS 'emokohteet 007',
  LENGTH(t1.007_emokohde) AS 'emokohde 007 merkkimäärä',
  GROUP_CONCAT(t1.osakohde SEPARATOR '</br>') AS 'osakohteet',
  GROUP_CONCAT(t1.emokohde SEPARATOR '</br>') AS 'emokohteet'
FROM (SELECT ExtractValue(osa.metadata,'//datafield[@tag="773"]/subfield[@code="m"]') AS '773m',
  ExtractValue(osa.metadata,'//datafield[@tag="942"]/subfield[@code="c"]') AS '942c_osakohde',
  ExtractValue(emo.metadata,'//datafield[@tag="942"]/subfield[@code="c"]') AS '942c_emokohde',
  ExtractValue(osa.metadata,'//controlfield[@tag="007"]') AS '007_osakohde',
  ExtractValue(emo.metadata,'//controlfield[@tag="007"]') AS '007_emokohde',
  osa.biblionumber AS 'osakohde',
  emo.biblionumber AS 'emokohde',
  osa.*
FROM biblio_metadata osa
LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements bde ON bde.biblionumber = osa.biblionumber
LEFT JOIN biblio_metadata emo ON bde.host_record = emo.biblionumber
WHERE ExtractValue(emo.metadata,'//datafield[@tag="942"]/subfield[@code="c"]') = 'AANILEVY'
  AND SUBSTR(ExtractValue(emo.metadata,'//controlfield[@tag="007"]'),1,2) = 'sd'
  AND SUBSTR(ExtractValue(emo.metadata,'//controlfield[@tag="007"]'),11,1) = 'p'
  AND SUBSTR(ExtractValue(emo.metadata,'//leader'),7,1) = 'j'
  AND ExtractValue(osa.metadata,'//datafield[@tag="942"]/subfield[@code="c"]') IN ('MUSATAL')) t1
GROUP BY t1.007_emokohde
``` 

Tiketti ei ole enää ajankohtainen, joten suljen sen.
