### ISSUE TITLE
Paperiselle palautuskuitille niteiden tiedot myös silloin kun asiakas on valinnut ettei lainahistoriaa tallenneta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#441]
### Kehitysehdotukseni

Siirrän tämän bugina Redmineen raportoidun tiketin kehitysehdotukseksi. Ongelma nykyisellään on siis se, että jos asiakas on Finnassa valinnut ettei lainahistoriaa tallenneta, tulostuu Kohasta asiakkaalle tyhjä palautuskuitti koska linkki asiakkaan ja niteen välillä katkeaa palautuksen yhteydessä. Sähköpostilla lähtevään palautuskuittiin kuitenkin näyttäisi tulostuvan palautettu laina lainahistoria-asetuksesta huolimatta.

Mikä mahdollistaa sen, että sähköpostikuittiin tulostuu niteiden tiedot? Ehtiikö sähköpostikuitti muodostua jo ennen kuin linkki asiakkaan ja niteen välillä katkeaa tms eli voisiko pidempi viive lainahistorian anonymisoinnissa ratkaista paperikuitin ongelman..?

### Jotain muuta?

Siirretty Redminen tiketistä [5203](https://tiketti.koha-suomi.fi/issues/5203).

**Comment by AnneliO** [comment]
Yhteisöstä löytyi tällainen tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=28896

**Comment by AnneliO** [comment]
Koha-Suomen asiantuntijaryhmä 26.2.2024: Koha-Suomalaiset ehdottava yhteisön tikettiin ratkaisua, jossa palautuskuitin sisältö kerättäisiin uuteen viestityyppiin ja kun palautuskuitti tulostetaan, haetaan tieto message_queue-taulusta old_issues-taulun sijaan. Eli samantyyppisesti kerättäisiin tiedot lennossa kuitille kuin mitä sähköpostikuitissa.

**Comment by atarnus** [comment]
Keskusteltiin tästä tosiaan vielä, että tuo message_queue-tauluun tallentaminen on sinänsä vähän arvelluttavaa, jos asiakas on valinnut, että lainahistoriaa ei tallenneta.

Seurailin vähän, että missä nuo sähköpostiviestit muodostuu taulukkoon, ja ne tulee ihan jossain tuolla C4/message.pm, joka tosiaan tsekkaa että onko viesti pending tilassa, ja jos on, niin se päivittää sitten sitä viestiä. Kai se mahdollista olisi tosiaan samaan tapaan kuitenkin muodostaa sinne viestiä ja poistaa pending-tila sitten kun kuitti tulostuu, jos siitä nyt ei synny ristiriitaa että voiko tuota pending-tilaa käyttää jos ei ole puhelinnumeroa tai sähköpostia johon se olisi lähdössä.

Old_issues tauluun tosiaan tulee anonyymin EITILASTO-asiakkaan borrowernumber, mutta statistics-taulusta löytyy vielä oikealla borrowernumberilla palautustiedot. Palautuskuitin voisi siis todennäköisesti tulostaa vaihtamalla nykyisestä prosessista old_issues taulun statistics tauluun (saattaa siinä tietty jotain mutkia tulla matkaan koska statistics ja issue-taulut eivät ole tiedoiltaan yhdenmukaiset). Mutta onko nyt siis ok, että tämä oikea borrowernumber päätyy statistics-tauluun? Jos on, niin uskoisin palautuskuitin tulostamisen statisticsista käsin olevan todennäköisesti huomattavasti helpompi toteuttaa kuin message_queuen kanssa säätäminen.

**Comment by AnneliO** [comment]
Asiantuntijaryhmä 8.4.2024
 * Ei ole teknisesti toteutettavissa. Lainatiedot jäävät statisticsiin, mutta niiden pitäisi oikeastaan anonymisoidessa poistua sieltäkin.
  * Tapaukset luultavasti todella harvinaisia ja lienee hoidettavissa selittämällä asiakkaalle, että tieto lainasta katoaa saman tien kun palautus tapahtuu silloin kun lainahistoriaa ei säilytetä.
  * Päätös: Ei toteuteta. Tutkitaan, saisiko kuitille tulostumaan jotain tyyliin "Ei lainahistoriaa" tai "Lainahistoria anonymisoitu, ei voida tulostaa palautuksia".
