### ISSUE TITLE
OUTI: Raportin 363 muokkaus

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#442]
### Tukipyyntö

OUTIssa tarvittaisiin jo olemassa olevaan raporttiin 363 **Varaukset yhteensä** -sarake. Uusi raportti käy myös, jos vanhan raportin muokkaus ei ole järkevää.

### Jotain muuta?

"Varaukset yhteensä" auttaisi päätöksenteossa, kun miettii kannattaako nimekkeeseen tehdä lisätilauksia tai kannattaako esim. johonkin lautapeliin tilata lisäosia tms.

**Comment by emta001** [comment]
Vilkaisin raporttia OUTIn testillä ja sieltä löytyy tuommoinen "Varaukset yhteensä" sarake.

**Comment by piiaseme** [comment]
Joo, testillä se sarake vielä on, mutta se ei toimi oikein. Muokkasin tuotannossa sitä raporttia ja otin siellä sen sarakkeen pois ja muokkasin sitä muutenkin. Testillä en ole tehnyt raportille mitään muokkauksia.

**Comment by emta001** [comment]
> Joo, testillä se sarake vielä on, mutta se ei toimi oikein. Muokkasin tuotannossa sitä raporttia ja otin siellä sen sarakkeen pois ja muokkasin sitä muutenkin. Testillä en ole tehnyt raportille mitään muokkauksia.

Millä tavalla se ei tarkalleen toimi oikein? Mitä tuolla "Varaukset yhteensä" siis halutaan ilmaista? OUTIn testiltä katsoin pari tulosta ja niissä tuo luku vastaa old_reserves-taulussa olevia tietueen varauksia (en kyllä ymmärrä miten, tuonhan pitäisi laskea reserves-taulun arvoja :D).

**Comment by piiaseme** [comment]
Tein tuotantoon raportin Testi: Lautapelien varaukset (612). Kopioin testiltä raportin 363 koodin siihen. Kun raportin ajaa, niin se antaa esim. Ark Nova-pelille Varaukset yhteensä lukemaksi 120 ja voimassa olevat varaukset sarakkeeseen lukeman 8. Peli on laitettu kiertoon elokuussa ja se on ollut lainassa vain 10 kertaa. Voiko tuo 120 varausta yhteensä pitää paikkansa? En lokilta löytänyt poistettuja/vanhentuneita varauksia, joka olisi voinut selittää varausten ja lainojen epästemman.

**Comment by emta001** [comment]
> Tein tuotantoon raportin Testi: Lautapelien varaukset (612). Kopioin testiltä raportin 363 koodin siihen. Kun raportin ajaa, niin se antaa esim. Ark Nova-pelille Varaukset yhteensä lukemaksi 120 ja voimassa olevat varaukset sarakkeeseen lukeman 8. Peli on laitettu kiertoon elokuussa ja se on ollut lainassa vain 10 kertaa. Voiko tuo 120 varausta yhteensä pitää paikkansa? En lokilta löytänyt poistettuja/vanhentuneita varauksia, joka olisi voinut selittää varausten ja lainojen epästemman.

Okei, ei tosiaan kuulosta oikealle. Miepä yritän selvitellä tätä jossain kohtaa :)

**Comment by piiaseme** [comment]
Toinen selkeä lautapeli on tuo Paleo. Jos se auttaa tutkimuksissa.

Ja tämä ei ole päivän polttava, joten no stress :)

**Comment by piiaseme** [comment]
Nuo Unlock!-pelit on eri pelejä, niillä on vain tuo päänimeke sama. Tämän hetkiset varaukset on kaikilla kolmella pelillä oikeat.

**Comment by emta001** [comment]
> Nuo Unlock!-pelit on eri pelejä, niillä on vain tuo päänimeke sama. Tämän hetkiset varaukset on kaikilla kolmella pelillä oikeat.

No hyvä :) mutta varaukset yhteensä ei kyllä tosiaan ole oikein :D

**Comment by emta001** [comment]
Lisäsin sarakkeen "Varaukset yhteensä" tuotannon raporttiin 363. Millekäs näyttää, meneekö määrät yhtään oikein?

**Comment by piiaseme** [comment]
Tarkistin kolme ensimmäistä (Ark Nova sekä Unlock, Unlock) sekä Ticket to riden. Jokaisessa oli jo järkevämpi varausmäärä.
Ark Novasta onnistuin löytämään kannasta yhteensä 29 varausta -> rapsassa se oli 30.
Unlock! : mystery adventures-pelistä onnistuin löytämään 28 varausta -> rapsassa se oli 29.
Unlock! :secret adventures-pelistä onnistuin löytämään 24 varausta -> rapsassa se oli 28.
Ticket to ridesta löysin 12 varausta -> rapsassa niitä oli 13.

Jos niteitä on poistettu, niin niiden osalta en varauksia pääse katsomaan. Voiko minimaalinen ero johtua siitä?

**Comment by emta001** [comment]
Hmm, tuon luvun pitäisi siis olla reserves- ja old_reserves-tauluista löytyvien varausten yhteenlaskettu summa. Esimerkiksi tietueelle [2030166](https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2030166) löytyy kannasta 1 aktiivinen varaus sekä 55 vanhaa varausta (katselen siis tietueita joissa on enintään 1 varaus). Tuolla Ark Novassa taas on (ainakin nyt) 2 aktiivista varausta ja 28 vanhaa varausta.

**Comment by piiaseme** [comment]
Tuota linkkaamaasi Ticket to ride-lautapeliä ei tullut ollenkaan minun aiempaan tulokseen eli puhutaan nyt eri lautapeleistä. Jätin nyt haussa tyhjäksi "Varauksia vähintään"-valikon, niin sain tuon linkkaamasi pelin myös tulokseen. 

Hassua siinä se, että laitoin määräksi 2, joten olisi sen pitänyt tulla tulokseen, mutta ottaako se sitten vain voimassa olevat varaukset tuossa määrittelyssä huomioon?

**Comment by piiaseme** [comment]
> Hmm, tuon luvun pitäisi siis olla reserves- ja old_reserves-tauluista löytyvien varausten yhteenlaskettu summa. Esimerkiksi tietueelle [2030166](https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2030166) löytyy kannasta 1 aktiivinen varaus sekä 55 vanhaa varausta (katselen siis tietueita joissa on enintään 1 varaus). Tuolla Ark Novassa taas on (ainakin nyt) 2 aktiivista varausta ja 28 vanhaa varausta.

Tutkin nyt uudelleen, kun sain oikean tuloksen näkyville :)

**Comment by piiaseme** [comment]
Tässä on ne jotka ekassa haussa sain tutkailtua:

Ark Novasta onnistuin löytämään kannasta yhteensä 29 varausta -> rapsassa se oli 30.
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2262530

Unlock! : mystery adventures-pelistä onnistuin löytämään 28 varausta -> rapsassa se oli 29.
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2206140

Unlock! :secret adventures-pelistä onnistuin löytämään 24 varausta -> rapsassa se oli 28.
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2222918

Ticket to ridesta löysin 12 varausta -> rapsassa niitä oli 13.
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2240084

**Comment by piiaseme** [comment]
> Hmm, tuon luvun pitäisi siis olla reserves- ja old_reserves-tauluista löytyvien varausten yhteenlaskettu summa. Esimerkiksi tietueelle [2030166](https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2030166) löytyy kannasta 1 aktiivinen varaus sekä 55 vanhaa varausta (katselen siis tietueita joissa on enintään 1 varaus). Tuolla Ark Novassa taas on (ainakin nyt) 2 aktiivista varausta ja 28 vanhaa varausta.

Laskin siten, että katsoin jokaisen niteen vanhat varaukset raportilla, joka hakee tuloksen old_reserves -taulusta. Voimassa olevat varaukset näin tietueen tiedoista. Ja ynnäsin ne yhteen.

**Comment by emta001** [comment]
Hmm, ainakin Ark Novasta ei löydy poistettua nidettä. Mutta old_reserves-taulusta löytyy tosiaan 28 riviä, joista 11:sta ei ole itemnumberia (arvo on NULL) ja 17:sta itemnumber on 3456185. Plus sitten ne kaksi aktiivista varausta. Mistähän ihmeestä tuo heitto sitten tulee? :D

**Comment by piiaseme** [comment]
Kerroin työkaverille, joka aktiivisesti käyttää tätä raporttia, että olet sitä korjannut ja että pikkuista heittoa on vielä havaittavissa. Työkaveri on tähän korjaukseen enemmän kuin tyytyväinen, joten jos tähän pikkuheittoon ei helposti löydy ratkaisua, niin tämä raportti on käyttökelpoinen tällaisenaan. Raporttia käytetään lähinnä siihen, että halutaan selvittää mitä lautapelejä tulisi hankkia lisää. Sitä ei käytetä tilastoinnin vuoksi. Suljen tiketin, jos sulku on Emmillekin ok :)

**Comment by emta001** [comment]
Sopii miullekin, eipä tuo vaarallinen heitto ole ja sille on varmaan ihan fiksu selitys :D Jos heittoa rupeaa esiintymään enemmän, niin tutkitaan sitten uudestaan.

**Comment by piiaseme** [comment]
Suljen tiketin. Avataan, jos tilanne uusiutuu.
