### ISSUE TITLE
Tilauksen peruminen ei onnistu, kun tilauksella ei ole tietuetta

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#446]
### Mikä vikana?

Tilauksen peruminen Hankinnat-toiminnossa ei onnistu, kun tilaukselta puuttuu tietue.
Tilausta peruessa Virhe 500.

![kuva](https://user-images.githubusercontent.com/99952449/219576314-cd9f78aa-a556-4ca1-907f-beccd3b8cecf.png)

**Comment by AnneliO** [comment]
Anni ehdotti tiketissä #300 seuraavaa:

> Mietin, että pitäisikö ajaa vielä orderstatukseksi cancelled-tila niille tilauksille, joissa biblionumber = null ja orderstatus silti 'ordered? Sillä saisi varmaankin siivottua vastaanottonäkymästä pois alkuperäisen viestin tapaukset?

Tämä ratkaisu varmaan toimisi näissä Hellen tapauksissakin?

**Comment by Kati-Helle** [comment]
Hain eilen tietokannasta tietueettomiin tilauksiin liittyviä tietoja (tilausnumero, tilauspäivä, tilauskori, tili, tilin nimi). Lähetin tiedot kirjastoille, joilla tietueettomia tilauksia on. Ehdotin samalla, että pyytäisin kehittäjää poistamaan tilaukset. Tähän mennessä kaikki vastaamaan ehtineet ovat poiston kannalla.

**Comment by Kati-Helle** [comment]
Kyllä vain. Suljen tämän tiketin.
