### ISSUE TITLE
Nidehaun julkaisuvuosi-hakuun ennen/jälkeen -toiminnot

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#447]
### Kehitysehdotukseni

Siirretty Redminen tiketistä #2860
31.12.2018

Updated by Pirkko-Liisa Lauhikari noin 4 vuotta ago
Nidehakuun tullut lisätoivomus, että vosiko Julkaisuvuosi -rajaukseen saada ennen/jälkeen -vaihtoehdon? Voisi hakea vanhentuneita niteitä kätevämmin esim. matkakirjoista.
Kuva vielä lisätoiveeseen. OUTIssa Julkaisuvuosi -rajaus on lisätty Räätälöytyihin hakukenttiin.

### Jotain muuta?

![julkaisuvuosirajaus](https://user-images.githubusercontent.com/99244794/219596232-fbfc1168-6d8e-46b1-aa62-e76322fa6a56.PNG)

**Comment by AnneliO** [comment]
Indeksointiryhmän päätös 7.3.2024: Yhteisöön tiketti. Tutkitaan, onko toteutettavissa ja mahdollisesti tarjotaan muutosta itse.

**Comment by atarnus** [comment]
Haku lähettää eteenpäin olion tähän tyyliin:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/551bb72d-5d81-414c-ad64-68da3ffd89c0)

Oletuksena tuossa on mahdollista valita operaattoriksi (op) "on" tai "ei ole", jotka vastaa SQL termejä "like" ja "not like". Jos lisää valikkoon vaihtoehdot > ja <, niin haku toimii saman tien. Nämä vaihtoehdot voi lisätä vaikka JS-rimpsullakin (sillä testasin).

Haluttaisiinko tuohon lisää noita vaihtoehtoja, vai onko suurempi ja pienempi kuin vaihtoetojen lisääminen kaikille noille saman pudotusvalikon hakuehdoille huono ajatus? On mahdollista myös tehdä tämän tyyppisiä kenttiä:
![image](https://github.com/KohaSuomi/Koha/assets/63994411/35b8390a-89be-4dbc-8697-cdb316dce798)

Tekee sitten koodimuutoksen tai JS-rimpsun, niin ei ole mitenkään iso homma.

**Comment by atarnus** [comment]
Muutos voidaan tehdä myös templateen (itemsearch.tt)

```
    [% IF params.exists('op') %]
        <select name="op" class="form-field-not">
           <option value="like">is</option>
            [% IF params.op == 'not like' %]
               <option value="not like" selected="selected">is not</option>
            [% ELSE %]
               <option value="not like">is not</option>
            [% END %]
            [% IF params.op == '>' %]
               <option value=">" selected="selected">></option>
            [% ELSE %]
               <option value=">">></option>
            [% END %]
            [% IF params.op == '<' %]
               <option value="<" selected="selected">is not</option>
            [% ELSE %]
               <option value="<"><</option>
            [% END %]
        </select>
    [% ELSE %]
        <select name="op" class="form-field-not">
           <option value="like">is</option>
           <option value="not like">is not</option>
           <option value=">">></option>
           <option value="<"><</option>
        </select>
    [% END %]
```

Joka tapauksessa tämä vaihtoehtojen lisääminen olisi minusta yksinkertaisin ratkaisu, ja se tuo lisähyötyä siinä, että noita suurempi ja pienempi kuin määreitä voi sitten käyttää muihinkin kenttiin samassa valikossa. Tietysti kaikkien arvojen kohdalla nuo eivät välttämättä toimi ollenkaan tai oikein, mutta se on tiedonhakijan pääteltävissä.
![image](https://github.com/KohaSuomi/Koha/assets/63994411/ec75f762-43b0-4b4c-bd71-ef397f0bacc2)

Jos pääkäyttäjillä on aikaa, niin tuon ylemmässä viestissä olevan JS-rimpsun voi lisätä intranetuser.js:ään ja kokeilla miten nuo > ja < operaattorit pelaa eri hakuvaihtoehtojen kanssa. Päivämäärän kohdalla tulee käyttää samaa ISO-muotoa kuten ohjeistetaan lainauspvm:nkin kohdalla, eli IYYYY-MM-DD. Ohjeistus voidaan liittää mukaan sitten jos tämä otetaan käyttöön.

**Comment by atarnus** [comment]
Tuolla templatessa määritellään se, että oikea operaattori on määritelty valituksi. Jos päivittää sivun, niin tuo js-rimpsu ei tosiaan "muista" valittua arvoa vaan nollaa sen takaisin ylimpään. Tämä kannattanee korjata vielä rimpsuun, jos mennään rimpsulla.

**Comment by AnneliO** [comment]
Testailin noita <>-merkkejä ja minusta ne toimivat ihan hyvin.

Hankinta- ja saapumispäivä 952$d
* osasi hakea tiettyä päivää aiemmat tai uudemmat päivämäärät
* onnistui myös haku aikavälillä, kun määritteli saman kentän kahdesti JA-operaattorilla yhdistäen

Viimeksi nähty 952$r
* osasi hakea pelkällä vvvv-kk-dd haulla, vaikka kentässä on myös kellonaika. Tässä pitää ottaa huomioon, että jos haluaa hakuun mukaan 19.1.2024, pitää päivämääräksi laittaa > 18.1.2024

Aineistotyyppi
* toimii kyllä. Esim. < DVD hakee aineistotyyppejä, jotka ovat aakkosissa ennen DVD:tä. Mukaan tuli siis esim. ALEHTI.

Tekijä 100$a
* toimii samoin kyllä aineistotyypin kanssa, eli jos hakee esim. < Aapeli* tulee hakuun mukaan esim. 22-pistepirkko.

**Comment by atarnus** [comment]
Olisiko tässä pääkäyttäjille loogisempaa käyttää kuitenkin operaattoreita >= ja <= ? Eli sisällytetään haettava vuosi hakuun? Tuohon ei kannattane tunkea ihan hirveästi noita lisäoperaattoreita, niin mielestäni valitaan joko setti '< ja >' tai '<= ja =>'.

Tehdään tästä se patch tarjolle yhteisöön, mutta meille tämän saisi varmaan nopeiten käyttöön JS-rimpsuna (mahd. JS-plugarina sitten). Työstän mukaan tuon valinnan säilyvyyden vielä, ja haluaisin mielipiteitä sitten noista operaattoreista.

**Comment by atarnus** [comment]
@Tuomas-Kyyti teetkö tästä tiketin yhteisöön, niin tarjotaan sinne patchia. (Tässä nyt olisi tulossa tuo ominaisuus tietysti moniin muihinkin kenttiin kuin meidän omaan räätälöityyn julkaisuvuoteen.)

Ei myöskään näytä siltä, että tuolla sivulla olisi valmiina oikein mitään, millä saisi säilytettyä valitun operaattorin sivunlatausten yli. En käytä siihen tällä hetkellä ainakaan enempää aikaa. Se toimii koodimuutoksessa, ja jos edes otetaan JS-plugarina käyttöön, niin kyseessä on minimaalinen asia, jota suurin osa käyttäjistä ei todennäköisesti edes huomaa.

**Comment by atarnus** [comment]
Näyttäisi sandboxissa että nidehaku on vähän muuttunut, mutta tuo pudotusvalikko on koodissa yhä sama, niin yllä tehty template-muutos saattaa hyvinkin toimia vielä.

Me voidaan nyt ottaa käyttöön tämä intranet.js-rimpsu, kunhan nyt vielä joku muukin kuin Anneli testaa sitä:

```
/// ALKU ///
// Lisää '<' ja '>' operaattorit monivalintavalikkoon nidehaussa
$(document).ready(function() {
  if (window.location.pathname == '/cgi-bin/koha/catalogue/itemsearch.pl') { 
    $('select[name="op"]').append('<option value=">">></option><option value="<"><</option>');
  }
});
/// LOPPU ///
```

**Comment by Tuomas-Kyyti** [comment]
Tiketti tehty Bugzillaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36920

**Comment by atarnus** [comment]
Näköjään Outilla onkin tuotannossa jo tuo rimpsu operaattoreilla >= ja <= :smile: 
Humpsahtanut sinne Nextin asetuksista.

**Comment by AnneliO** [comment]
> Näköjään Outilla onkin tuotannossa jo tuo rimpsu operaattoreilla >= ja <= 😄 Humpsahtanut sinne Nextin asetuksista.

Tästä tulikin mieleen, että pääkäyttäjäpalaverissa 21.5.2024 päätettiin mennä operaattoreilla > ja < ilman yhtäsuurikuinmerkkejä siis, jotta se olisi johdonmukainen muiden valikoiden kanssa (lähinnä Lainauksien määrä -valikon kanssa).

**Comment by atarnus** [comment]
> > Näköjään Outilla onkin tuotannossa jo tuo rimpsu operaattoreilla >= ja <= 😄 Humpsahtanut sinne Nextin asetuksista.
> 
> Tästä tulikin mieleen, että pääkäyttäjäpalaverissa 21.5.2024 päätettiin mennä operaattoreilla > ja < ilman yhtäsuurikuin-merkkejä siis, jotta se olisi johdonmukainen muiden valikoiden kanssa (lähinnä Lainauksien määrä -valikon kanssa).

Juu, tuo on ollut ihan joku lapsus, en hoksannut käydä poistelemassa testaamiani juttuja nextistä ennen kuin se kopsattiin tuotantoon.

Olinkin nyt tehnyt tästä näemmä myös ihan oikean branchinkin valmiiksi yhteisön patchia varten, niin ajateltiin että otetaan kuitenkin se testattavaksi ja käyttöön, eikä pelkkä rimpsu.

**Comment by atarnus** [comment]
Pitäisi olla nyt kaikilla testeillä, rimpsua ei tarvita. (Jos joku on rimpsun laittanut niin kannattaa poistaa.)

Tuo Outin tuotantoon vahingossa mennyt rimpsu tulee poistaa sitten kun tämä branchi laitetaan tuotantoon.

**Comment by sksandel** [comment]
Vaski-testillä oli myös tuo JS-rimpsu, joka tuplasi >< operaattorit alasvetovalikkoon. Rimpsu poistettu ja nyt vaikuttaisi toimivan kuten pitääkin.

**Comment by Kati-Helle** [comment]
Helle-testissä operaattoreilla > ja < hauilla oikeat hakutulokset.

Jokerimerkki hakuehdossa ei vaikuta Helle-testissäkään toimivan oikein.

Esim. hakuehto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/527295eb-35fc-4d2e-9986-8c072d13cc95)

Hakutulosta Julkaisuvuosi-kentän mukaan järjestettynä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4dcb9735-685b-4a64-a4a0-2abd09cadb2f)

Testissä on juuri nyt raportilla items-taulusta haettuna 3106 nidettä. Haku rajannee tuon perusteella jotain niteitä pois hakutuloksesta?

Esim hakuehto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1872fe78-647b-4af9-af2d-041d99325330)

Ei hakutulosta 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/e3aefd01-a4c5-46d4-ba8b-21361677e533)

**Comment by Kati-Helle** [comment]
> Helle-testissä operaattoreilla > ja < hauilla oikeat hakutulokset.
> 
> Jokerimerkki hakuehdossa ei vaikuta Helle-testissäkään toimivan oikein.
> 
> Esim. hakuehto ![kuva](https://private-user-images.githubusercontent.com/99952449/337567858-527295eb-35fc-4d2e-9986-8c072d13cc95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDYyMzMsIm5iZiI6MTcxNzc0NTkzMywicGF0aCI6Ii85OTk1MjQ0OS8zMzc1Njc4NTgtNTI3Mjk1ZWItMzVmYy00ZDJlLTk5ODYtOGMwNzJkMTNjYzk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OWY3NTg1MGEzOTdjMzQwMzc0MmMyMTViMzY5ZDFhZmE3MWIxMGVkYjVkYTJmNDdmZTE0YjM3MTUyZDFhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b3SRhASj6baOPmEkPrhefg0acTsPldUPIbrpiaNBfpM)
> 
> Hakutulosta Julkaisuvuosi-kentän mukaan järjestettynä ![kuva](https://private-user-images.githubusercontent.com/99952449/337568154-4dcb9735-685b-4a64-a4a0-2abd09cadb2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDYyMzMsIm5iZiI6MTcxNzc0NTkzMywicGF0aCI6Ii85OTk1MjQ0OS8zMzc1NjgxNTQtNGRjYjk3MzUtNjg1Yi00YTY0LWE0YTAtMmFiZDA5Y2FkYjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YzZlMzllZWE4YWUzN2E5ZjRkYjZmYjE2NzI3MmM2M2JjNGJiNGI0ODU0NGE0ZGFhYzlhOWMwNzUzODBhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e4VHpi6rRR5MOycTolsynQHGMXQwUZM80l8HAoqGfDA)
> 
> Testissä on juuri nyt raportilla items-taulusta haettuna 3106 nidettä. Haku rajannee tuon perusteella jotain niteitä pois hakutuloksesta? *Tarkistin: kaikilla niteiden tietueilla ei ole julkaisuvuotta (biblio.copyrightdate), joten haku ei rajanne niteitä pois.
> 
> Esim hakuehto ![kuva](https://private-user-images.githubusercontent.com/99952449/337568878-1872fe78-647b-4af9-af2d-041d99325330.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDYyMzMsIm5iZiI6MTcxNzc0NTkzMywicGF0aCI6Ii85OTk1MjQ0OS8zMzc1Njg4NzgtMTg3MmZlNzgtNjQ3Yi00YWY5LWFmMmQtMDQxZDk5MzI1MzMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjODEwNmU5YmQ0ZTNlNjI3YmJiYzEzOWE3ZGNhYzU2MDY5Nzk5NGQxNDJiZGViNDRkNjkwYTBiZjNlOGE1ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBPA5PiRonOMQfiOEDxjMbKrvChLI9XJdXvnrehSUZM)
> 
> Ei hakutulosta ![kuva](https://private-user-images.githubusercontent.com/99952449/337569040-e3aefd01-a4c5-46d4-ba8b-21361677e533.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDYyMzMsIm5iZiI6MTcxNzc0NTkzMywicGF0aCI6Ii85OTk1MjQ0OS8zMzc1NjkwNDAtZTNhZWZkMDEtYTRjNS00NmQ0LWJhOGItMjEzNjE2NzdlNTMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3Mzg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNGRjZThiNTA2MGZhZmYxMDEzNmViNWMxYjQ0Y2VmZjNlNWJkYTdmMTZiYTEwNWI1NDRlMjgwZjc0ODQxYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9Ws_3g7Ij_kX8pPmAt_IdTChhHWg3CDeLfAnkwR7G4U)

**Comment by AnneliO** [comment]
Testailin tuota vuosiluvun katkaisua <>-hauissa ja minusta vaikuttaa siltä, että jos haetaan esim. > '202%', haetaan käytännössä numeroita, jotka ovat suurempia kuin 202 eli käytännössä siis koko tietokanta. Jos taas < '202%', niin haetaan pienempiä vuosilukuja kuin 202 eli käytännössä ei löydy mitään.

Julkaisuvuosi-haku taitaa hakea publicationyear-kentästä tietokannasta ja se on tietotyypiltään tekstiä. Opiskelen vielä, onko tuolla merkitystä asiaan.

**Comment by AnneliO** [comment]
Testailin lisää ja juttelimme tästä myös Koha-Suomen palaverissa ja sanoisin, että vuosilukua ei pysty tuolla tavalla katkaisemaan. Enkä kyllä äkkiseltään hoksaa, miksi se pitäisi pystyä. Jos halutaan hakea 2020-luvun vuosia, niin haku tehdään > 2019. Jos haluaa käyttää katkaisumerkkiä, niin silloin _on 202__  ja _on 202%_ toimii mielestäni oikein tässä kontekstissa.

Minusta tämä rimpsu olisi valmis tuotantoon laitettavaksi, vai huomaako joku vielä jotain omituista? :)

**Comment by Kati-Helle** [comment]
Hakuvinkit eivät päde julkaisuvuoden hakuehtoihin > ja < 

![Image](https://github.com/KohaSuomi/Koha/assets/99952449/dfc0a26e-cc3b-40c6-92ec-8796e8f105f8)

**Comment by AnneliO** [comment]
> Hakuvinkit eivät päde julkaisuvuoden hakuehtoihin > ja <


Ei päde, mutta onko se iso ongelma? Tai pätee, mutta kun vuosiluku katkaistaan, niin haetaan ennen katkaisumerkkiä olevaa merkkijonoa isompia ja pienempiä lukuja.

Jos se on iso ongelma, niin äkkiseltään tuli mieleen, että vihjeen perään voisi laittaa lisäohjeena IntranetUserCSS:llä jotain tällaista:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/4672b2fa-389b-4f71-b45f-6c997b9f1f8a)


```
/* Lisää nidehakuun huomautus <>-operaattoreiden katkaisusta. */
body#catalog_itemsearch.catalog p.hint:nth-child(2):after {
  content: " \00a0 Vuosilukuja ei voi katkaista, jos käyttää <>-operaattoreita";
  color:red;
}
```

**Comment by Tuomas-Kyyti** [comment]
Tämä kunnossa.
