### ISSUE TITLE
Palautuskuittiin ei tule palautettujen lainojen tietoja, jos laina- ja palautuskirjasto ovat erit

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#449]
### Mikä vikana?

Redminen tiketti: https://tiketti.koha-suomi.fi/issues/5364

Palautuskuittiin ei tule palautettujen lainojen tietoja, kun lainat on lainattu eri kirjastosta kuin mihin lainat palautetaan. Eli jos palautuskuitin tulostaa siitä kirjastosta mihin lainat oli palautettu, palautuskuittin ei tule tietoja, mutta jos palautuskuitin käy tulostamassa kirjautuneena kirjastoon, jossa lainat oli alunperin lainattu, palautuskuittin tiedot tulevat.

### Mitä pitäisi tapahtua

Palautuskuittiin pitäisi tulla kaikkien palautettujen lainojen tiedot, jotka asiakas on palauttanut, riippumatta siitä, mistä kimpan kirjastosta lainat olivat lainattu.

### Jotain muuta?

Anneli kommentoinut Redminen tikettiin: 
"Ongelma jatkuu myös versiossa 22.11."
"Tarvittaessa palautuskuitti asiakkaalle sähköpostitse auttaa tähän tällä hetkellä."

**Comment by emta001** [comment]
Palautuskuittiin tulevat palautukset tosiaan rajataan kirjautuneen käyttäjän kirjaston mukaan, ei asiakkaan mukaan. En oikein keksi mitään järjellistä syytä, miksi tällaiseen ratkaisuun on päädytty. Teen tiketin yhetisöön ja ehdotan korjausta, katsotaan kuinka käy.

**Comment by emta001** [comment]
Korjausta ehdotettu yhteisöön.

**Comment by emta001** [comment]
Ilmeisesti ajatuksena on tosiaan ollut, että lainat rajattaisiin palautuskirjaston mukaan, mutta tässä on käynyt ajatusvirhe. Reserves- tai old_reserves-tauluissa branchcode sarake täytetään lainauskirjaston arvolla, mutta eihän niissä ole mitään saraketta palautuskirjastosta. Statistics-taulusta se tieto löytyisi, mutta sen käyttäminen ei ole oikeastaan mikään vaihtoehto.

**Comment by emta001** [comment]
Tämä on mennyt yhteisössä läpi ja julkaistaan seuraavassa versiossa. Tuodaanko tämä meille kuitenkin jo nyt?

**Comment by pirliis** [comment]
Ilman muuta. Jos eka laittaisi testille testattavaksi.

**Comment by emta001** [comment]
Tuotu testattavaksi.

**Comment by ReettaSiili** [comment]
Testasin Siilin testissä suomen kielellä. Palautuskuittiin tulostuivat tiedot palautetuista kirjoista, sekä palautuskirjastosta lainatusta että toisesta kirjastosta lainatusta kirjasta. Samat tiedot tulostuivat sekä palautusnäytön Tulosta palautuskuitti -painikkeesta että asiakastietojen Tulosta-valikosta Tulosta palautuskuitti -valinnasta. Eli mielestäni toimii oikein!

**Comment by pknuuti** [comment]
Toimii. Minulla oli Vaaran testillä lainassa kolme kirjaa, kaksi pääkirjastosta ja yksi Outokummusta lainattuna. Palautin kirjat Karsikon kirjastoon ja kaikki palautetut tulivat näkyviin palautuskuittiin samalla tavalla kuin Reetan testissä.

**Comment by Kati-Helle** [comment]
Helle-testissä toimii myös :)

**Comment by emta001** [comment]
Hyvä homma, kiitos pikaisesta testailusta :) Laitetaan tämä mukaan ensi viikon päivitykseen.

**Comment by piiaseme** [comment]
Hieman jälkijunassa, mutta kuitenkin.. OUTIssa toimii myös.

**Comment by lmstrand** [comment]
Korjaus tuotannossa.
