### ISSUE TITLE
Varausten voimassaoloajan jatkaminen kaikissa kimpoissa

### ISSUE THREAD

**Issue by janPasi** [KohaSuomi/Koha#451]
### Tukipyyntö

Asiantuntijaryhmässä 20.2. päätettiin jatkaa asiakkaiden varausten voimassaoloaika kolmeen vuoteen. Muutos tehdään myös nykyisin olemassaoleville varauksille ja tätä varten tarvitaan tietokanta-ajot kaikkiin kimppoihin. Voimassaoloaika muutetaan laskemalla varauksen expirationdate varauksen tekohetkestä kolme vuotta eteenpäin siinä tapauksessa, että nykyinen voimassaoloaika on kaksi vuotta. Sitä ei kuitenkaan tehdä sellasille varauksille, joille asiakas on itse asettanut kahta vuotta lyhyemmän voimassaoloajan.

**Comment by AnneliO** [comment]
Asetus muutettu: Vaara, Helle, Lappi, Kyyti, Outi, Vaski, Lumme

**Comment by AnneliO** [comment]
Voimassaoloajan muutosta ei tehdä myöskään niille varauksille, jotka odottavat noutoa tai ovat kuljetettavana.

**Comment by AnneliO** [comment]
Siilistä puuttuu vielä DefaultHoldExpirationdate-järjestelmäasetuksen muutos. Odotetaan se vielä. Laitoin Reetalle ja Markolle asiasta viestiä.

**Comment by lasse-koha** [comment]
Voimassaoloajat jatkettu.

**Comment by AnneliO** [comment]
Finna näköjään laittaa voimassaoloajaksi nyt kolme vuotta ja yhden päivän ja on aiemmin myös toiminut näin, eli kaikilla Finnan kautta tehdyillä varauksilla onkin voimassaoloaika kaksi vuotta ja yksipäivä. Esim. varaus tehty 25.2.2022 ja viimeinen voimassaolopäivä 26.2.2024.

Pystyisitkö Lasse tekemään toisen ajon, joka ottaa huomioon tuon yhden päivän heiton?

**Comment by pirliis** [comment]
Kiitos! Nyt näyttää voimassaoloajat menneen oikein. :)

**Comment by AnneliO** [comment]
Kiitos Lasse! Suljen tämän tiketin. :)

**Comment by pknuuti** [comment]
Anteeksi, en eilen huomannut, että Vaarassa ei ole tullut virkailijatyökalussa tehtyihin varauksiin pidennettyä aikaa. Johtunee siitä, että Vaarassa oli jostain syystä määritelty voimassaoloaika päivinä (730 päivää) eikä vuosissa kuten ilmeisesti muissa kimpoissa. Voisiko tämän korjata mahdollisimman pian? Finnan kautta tehdyt varaukset ovat saaneet oikeanlaisen jatkoajan.

**Comment by lasse-koha** [comment]
Nyt on Vaaran varaukset korjattu.

**Comment by pknuuti** [comment]
Kiitos, nyt suljen tiketin uudelleen.
