### ISSUE TITLE
Helle: hankinnan tietueettomien tilattu-tilaisten tilauksien poisto

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#452]
### Tukipyyntö

Poistatteko Hellen hankinnasta ne tilattu tilaiset tietueet, joilta puuttuu tietue.

Hellen tietueettomista tilauksista myös tiketissä https://github.com/KohaSuomi/Koha/issues/344

**Comment by emta001** [comment]
Eli siis ovatko kyseessä sellaiset hankinnat joiden biblionumber on null, mutta orderstatus on "ordered"?

**Comment by emta001** [comment]
Ja näitähän ei kannattane poistaa, vaan tilaksi voisi vaihtaa ennemmin "cancelled".

**Comment by Kati-Helle** [comment]
> Eli siis ovatko kyseessä sellaiset hankinnat joiden biblionumber on null, mutta orderstatus on "ordered"?

Kyllä vain.

**Comment by emta001** [comment]
Ajo tehty, koski 491 tilausta.

`UPDATE aqorders SET orderstatus = "cancelled" WHERE biblionumber IS NULL AND orderstatus = "ordered";`

**Comment by Kati-Helle** [comment]
Poissa ovat. Kiitos Emmi!
