### ISSUE TITLE
Helle: poistatteko hankinnan Failed-tilaiset EditX-sanomat vuodelta 2022

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#453]
### Tukipyyntö

Poistatteko Hellen Failed-tilaiset EditX-sanomat, jotka ovat vuodelta 2022.
Juuri nyt virheellisiä sanomia ei ole muilta vuosilta.

**Comment by emta001** [comment]
Poisto tehty seuraavasti:

`update edifact_messages set deleted = 1 where status = "failed" and deleted = 0;`

**Comment by Kati-Helle** [comment]
Kiitos Emmi :)
