### ISSUE TITLE
Hae asiakkaat -toimintoon esto hakea Haku-painikkeella kaikki asiakastiedot

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#456]
### Kehitysehdotukseni

Hae asiakkaat -haun Haku-painike hakee kaikki asiakastiedot Hae asiakkaita -kentän ollessa tyhjä. Myös ainakin tyhjämerkillä/tyhjämerkeillä -hakuehto Hae asiakkaita -kentässä hakee kaikki asiakkaat, kun klikataan Haku-painiketta.

Saisiko asiakashakuun ominaisuuden, joka estää kaikkien asiakastietojen haun Haku-painikkeella? Esimerkiksi tyyliin haku ei onnistu ilman hakuehtoa.

![kuva](https://user-images.githubusercontent.com/99952449/221532378-bfb45f89-45e1-45b6-a873-f55c4ca5d3d7.png)

**Comment by piiaseme** [comment]
Kaikki asiakkaat saa listattua näytölle myös, kun valitsee sivun yläreunassa "Hae asiakkaita" ja painaa Enter-näppäintä kursorin ollessa tyhjässä hakukentässä. 

![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/328026ff-2d3f-4271-acf9-30321f707a84)

**Comment by AnneliO** [comment]
Tämä ongelma käsiteltiin tiketin #467 yhteydessä ja ratkaisu tulee sen kautta. :) Suljen tämän tiketin.
