### ISSUE TITLE
Tietueen Perustiedot -näytön kohdehenkilö-asiasanalinkki ei toimi, kun kentällä on osakenttä 600c

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#459]
### Mikä vikana?

Tietueen perustietojen kohdehenkilö-asiasanalinkki ei toimi ainakaan silloin, kun kentällä on osakenttä 600c.
![kuva](https://user-images.githubusercontent.com/99952449/222719684-c0151c5e-3c09-48a2-961c-bb81fe82c432.png)

Hakutulos
![kuva](https://user-images.githubusercontent.com/99952449/222719938-90496658-d8e5-425f-bd7f-3bffe097e4b2.png)

Tietueen 600-kentät
![kuva](https://user-images.githubusercontent.com/99952449/222719813-7690f069-5550-4797-aae9-f1a201e253ee.png)

Samaa Helle-Kohassa. Perustiedot-näytön puutteet -tiketissä ei ole mainintaa kohdehenkilöstä https://github.com/KohaSuomi/Koha/issues/350

**Comment by AnneliO** [comment]
Tästä ongelmasta on maininta [Redmine-tiketissä 5097](https://tiketti.koha-suomi.fi/issues/5097#note-4).

**Comment by AnneliO** [comment]
Tähän vaikuttaa järjestelmäasetus _TraceSubjectSubdivisions_. Jos tuossa on valittuna _Sisällytä_, niin haku tehdään osakenttien kera. Jos taas valintana on _Älä säilytä_, haetaan ilman osakenttiä. Pikaratkaisuna on muuttaa tuo asetus, mutta sillä huomautuksella, että hakutulokset voivat periaatteessa sitten sisältää "vääriä" tuloksia, jos esim. sattuu olemaan saman niminen fiktiivinen hahmo ja todellinen henkilö.

**Comment by AnneliO** [comment]
Viedään tiketti asiantuntijaryhmään pohdittavaksi, eli lisätäänkö subject-indeksiin myös 600c-kenttä.

**Comment by AnneliO** [comment]
Seuranta, mitkä kimpat ovat tehneet muutoksen (tai päättänyt olla muuttamatta) järjestelmäasetukseen:

- [ ] Lappi
- [ ] OUTI
- [ ] Siilinjärvi
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Vaski

**Comment by ReettaSiili** [comment]
Tarkistin, Siilissä oli jo muutettu "Älä sisällytä".

**Comment by LeenaKinnunen** [comment]
Lappi vaihdettu.

**Comment by ElinaUotila** [comment]
Kirkesissä oli jo "Älä sisällytä".

**Comment by Kati-Helle** [comment]
Hellessä Älä sisällytä -vaihtoehto on ollut jo käytössä.

**Comment by Tuomas-Kyyti** [comment]
Kyyti muutettu

**Comment by MikkoLiimatainen** [comment]
Vaskissa Älä sisällytä jo käytössä

**Comment by AnneliO** [comment]
Muutos tehty kaikissa kimpoissa, sen puolesta tiketin saa nyt sulkea. :)

**Comment by Kati-Helle** [comment]
Kaikki kimpat ovat seurannan perusteella reagoineet ratkaisuehdotukseen. 
Suljen tiketin.
