### ISSUE TITLE
Vaski: Kahden uuden SIP-tunnuksen lisääminen palvelimelle

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#464]
### Tukipyyntö

Support-postiin lähetetty tarkemmat tiedot.

**Comment by lmstrand** [comment]
Tunnukset lisätty SIP-palvelinkonfiguraatioon. Käytettävissä huomisesta lähtien.

**Comment by ajrajala** [comment]
Kiitän!
