### ISSUE TITLE
Erikoistilan asettaminen osalle Turun pk:n musiikkiaineistosta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#465]
### Tukipyyntö

Osastolla alkavan remontin vuoksi pitäisi seuraavalle kahdelle nidejoukolle saada asetettua notforloan-tila 4 **tiistaiaamuna 11.4.**

**Nidejoukko 1:**

- biblioitems.itemtype NOT IN ('NUOTTI', 'LAUTAPELI', 'VIDEOPELI')
- items.holdingbranch = 'TUPK'
- items.location = 'MUS'
- items.itemlost = 0
- items.notforloan = 0
- nide on saatavana (eli käytännössä ei ole lainassa, kuljetettavana tai noudettavana?)

**Nidejoukko 2:**

- biblioitems.itemtype on joko 'NUOTTI' _tai_ biblioitems.itemtype on CD ja niteen luokka (items.cn_sort?) on joku seuraavista: 78.8912, 78.8913, 78.89141, 78.89142, 78.8915, 78.8916, 78.89161, 78.89162
- items.holdingbranch = 'TUPK'
- items.location = VAR
- items.itemlost = 0
- items.notforloan = 0
- nide on saatavana (eli käytännössä ei ole lainassa, kuljetettavana tai noudettavana?)

Onnistuko erikoistilan ajaminen tällaisin speksein?

**Comment by paxed** [comment]
Tämäpä tehty. Niteiden itemnumberit on tallessa kahdessa väliaikaisessa taulussa, _ks_20230411_itemnumbers1_gh465_ ja _ks_20230411_itemnumbers1_gh465_.

Näillä rimpsuilla:

**Nidejoukko 1**, 37879 nidettä:

```
create table ks_20230411_itemnumbers1_gh465 SELECT i.itemnumber from items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) where i.holdingbranch='TUPK' and i.location='MUS' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and bi.itemtype not in ('NUOTTI', 'LAUTAPELI', 'VIDEOPELI');
update items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) set i.notforloan=4 where i.holdingbranch='TUPK' and i.location='MUS' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and bi.itemtype not in ('NUOTTI', 'LAUTAPELI', 'VIDEOPELI');

```
**Nidejoukko 2**, 6333 nidettä:

```
create table ks_20230411_itemnumbers2_gh465 select i.itemnumber from items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) where i.holdingbranch='TUPK' and i.location='VAR' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and (bi.itemtype='NUOTTI' or (bi.itemtype='CD' and i.cn_sort regexp '\b78\.89(12|13|141|142|15|16|161|162)\b'));
update items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) set i.notforloan=4 where i.holdingbranch='TUPK' and i.location='VAR' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and (bi.itemtype='NUOTTI' or (bi.itemtype='CD' and i.cn_sort regexp '\b78\.89(12|13|141|142|15|16|161|162)\b'));
```

**Comment by ajrajala** [comment]
Olikohan tuossa ehdossa (bi.itemtype='CD' and i.cn_sort regexp '\b78\.89(12|13|141|142|15|16|161|162)\b') jotain pielessä? Pahoittelut etten tätä huomannut heti aamulla, jäi tarkistus mulla näköjään puolitiehen tuon toisen nidejoukon osalta.

**Comment by paxed** [comment]
Toinen yritys noiden CD:n osalta:

```
create table ks_20230412_itemnumbers_gh465 select i.itemnumber from items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) left join branchtransfers bt on (i.itemnumber=bt.itemnumber) where i.holdingbranch='TUPK' and i.location='VAR' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and (bt.itemnumber is null or bt.datearrived is not null or bt.datecancelled is not null) and (bi.itemtype='CD' and i.cn_sort regexp '[[:<:]]78\.89(12|13|141|142|15|16|161|162)[[:>:]]');
update items i left join biblioitems bi on (i.biblioitemnumber=bi.biblioitemnumber) left join reserves r on (i.itemnumber=r.itemnumber) left join branchtransfers bt on (i.itemnumber=bt.itemnumber) set i.notforloan=4 where i.holdingbranch='TUPK' and i.location='VAR' and i.itemlost=0 and i.notforloan=0 and i.onloan is null and r.found is null and (bt.itemnumber is null or bt.datearrived is not null or bt.datecancelled is not null) and (bi.itemtype='CD' and i.cn_sort regexp '[[:<:]]78\.89(12|13|141|142|15|16|161|162)[[:>:]]');

```

Tila laitettu 3233 niteelle.


Näköjään mariadb:n regexpeissä tuo \b ei toimi, vaikka olevinaan olin dokumentaatiosta kattonu et pitäs pelittää; korvasin sen sitten tuolla [[:<:]] ja [[:>:]] jotka näyttävät toimivan niinku pitääkin. (\b ja nuo härpäkkeet ovat ns. "word boundary", eli siinä kohdassa on jokin merkki joka katkaisee sanan, eli esim. välilyönti)

**Comment by ajrajala** [comment]
Kiitokset, tarkastelun perusteella toinen yritys teki sen mitä piti! Ajon ulkopuolelle jäi joitakin virheellisiä luokkamerkintöjä (ylimääräinen kirjain luokan perässä, esim. 78.8916B), mutta kyse ei ole monestakaan niteestä ja ne pystyy muuttamaan manuaalisestikin (+ehkä korjaamaan luokkatiedon samalla).

Uusi yritys siis nyt tiketin sulkemisen suhteen. 😄
