### ISSUE TITLE
Vaara: Kesälahden noudettavien varausten noutoaikaa pidennettävä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#466]
### Tukipyyntö

Kesälahden kirjasto on tällä viikolla avoinna vain omatoimikäyttäjille, mutta oven sähkölukko on mennyt rikki eikä korjaajaa saa kuin vasta maanantaina. Pyydetään siirtämään aikavälillä 6.-10.3. noudettavien varausten viimeiseksi noutopäiväksi 17.3. Kirjaston tunnus KIT_KES.

**Comment by lmstrand** [comment]
Aikavälillä ei löytynyt yhtään varausten viimeisiä noutopäiviä:
```
MariaDB [vaaraprod]> select * from reserves WHERE branchcode = 'KIT_KES' AND found='W' AND expirationdate BETWEEN '2023-03-06' AND '2023-03-11';
Empty set (0.002 sec)
```

**Comment by pknuuti** [comment]
Siirrä varalta sinne perjantaille 17.3. kuten alkuperäinen tarkoitus oli.

Päivi Knuutinen
kirjastovirkailija
Vaara-kirjastot
050 441 2247
***@***.***

Lähettäjä: Lari Strand ***@***.***>
Lähetetty: 9. maaliskuuta 2023 12:47
Vastaanottaja: KohaSuomi/Koha ***@***.***>
Kopio: Knuutinen Päivi ***@***.***>; Author ***@***.***>
Aihe: Re: [KohaSuomi/Koha] Vaara: Kesälahden noudettavien varausten noutoaikaa pidennettävä (Issue #466)


2 kappalettaa löytyi maanantailla. Siirretäänkö tiistaille?

-

**Comment by lmstrand** [comment]
Aivan, sori perjantaille.

Ajettu:
```
UPDATE reserves SET expirationdate='2023-03-17' WHERE branchcode = 'KIT_KES' AND found='W' AND expirationdate BETWEEN '2023-03-06' AND '2023-03-14';
```

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
