### ISSUE TITLE
Auktorisoitujen arvojen kopiointi testi-Tätistä Tätiin

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#468]
### Tukipyyntö

Olen tehnyt testi-Tätiin RDA-alkuisia auktorisoituja arvoja, joissa on vaihteleva määrä rivejä. On työlästä siirtää kaikki käsin, kun mitään tuontimahdollisuutta ei Koha tarjoa (vaikka vientimahdollisuus on, ei ole tuontia). 
Kaikki muut RDA-alkuiset auktorisoidut arvot saisi kopioida tuotanto-Tätiin paitsi RDA 020q ja RDA 261i, jotka olen kopioinut käsin.
Kun auktorisoidut arvot on kopioitu Tätiin, liitän ne kuvailupohjiin Koha-Suomen kuvailuryhmän päätöksen mukaisesti.

**Comment by emta001** [comment]
Tarkennuksena, tarkoitatko RDA 246i? En löydä tuollaista RDA 261ista kummastakaan kannasta.

**Comment by emta001** [comment]
Nyt arvot on siirretty, toivottavasti mukaan tuli oikeat :D

**Comment by pknuuti** [comment]
Kiitos, oikeat on kopioitu. Voisitko vielä poistaa TäTistä **RDA 020, 024q**-auktorisoidun arvon, joka ei toimi enkä saa sitä itse poistettua. En ymmärrä, miten tuollainen on edes syntynyt alun perin, koska eihän niissä ole samoja arvoja.

**Comment by emta001** [comment]
> Kiitos, oikeat on kopioitu. Voisitko vielä poistaa TäTistä **RDA 020, 024q**-auktorisoidun arvon, joka ei toimi enkä saa sitä itse poistettua. En ymmärrä, miten tuollainen on edes syntynyt alun perin, koska eihän niissä ole samoja arvoja.

Poisto ei onnistunut, koska arvon nimessä oli pilkku. Testailin testillä ja kun nimestä muokkasi pilkun pois, johan rupesi näkymään oikein. Poistelin kuitenkin nuo kannan kautta sekä testiltä että tuotannosta.

**Comment by emta001** [comment]
Kirjailen tännekin mitä tässä vielä tapahtui. Ilmeisesti, kun pilkullista arvoa yritettiin poistaa testillä ja tuotannossa, siinä poistettiinkin "tyhjä" auktorisoitu arvo. Tämä on olemassa tietokannassa taulussa authorised_value_categories, koska kuvailupohjissa voi olla myös kenttiä/osakenttiä joihin ei ole liitetty mitään auktorisoitua arvoa. Kannassa marc_subfield_structure-taulun ja authorised_value_categories-taulun välillä on foreign key liitos eli jos jokin arvo ei ole jälkimmäisessä taulussa, sitä ei voida tallentaa ensimmäiseenkään. Tämän vuoksi "tyhjä" arvon hävittyä kuvaialupohjia ei voitu enää tallentaa. Arvo on palautettu sekä testiin että tuotantoon ja kuvailuphjien tallennus toimii kuten pitää molemmissa.

**Comment by emta001** [comment]
Tämän voinee jo sulkea?

**Comment by janPasi** [comment]
@pknuuti pistätkö tiketin kiinni.
