### ISSUE TITLE
Rajoitteen tekstimuutosehdotus, kun asiakkaalla on yli 50 virheellistä kirjautumisyritystä

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#474]
### Kehitysehdotukseni

Kun asiakkaalla on yli 50 virheellistä kirjautumisyritystä verkkokirjastossa tai automaatilla, tulee hänelle automaattisesti rajoite, jossa tällä hetkellä selityksenä:
_Asiakkaalla on yli 50 epäonnistunutta kirjautumisyritystä. Tarkista asiakkaan henkilöllisyys ja anna uusi kirjastokortti ja pin-koodi._ 

Voisiko selityksen tekstiä muuttaa esim.:
_Asiakkaalla on yli 50 epäonnistunutta kirjautumisyritystä. Tarkista asiakkaan henkilöllisyys, anna uusi PIN-koodi ja vaihda tarvittaessa kirjastokortti._ 

Tekstimuutosehdotus syystä, että pääasiassa näissä tapauksissa asiakkailla on ollut kirjastokortti tallessa, eikä heidän mukaan korttinumero ole joutunut vääriin käsiin. Henkilökunnalta tulee ihmettelyä, että onko paikko antaa uusi kirjastokortti näissäkin tapauksissa.

**Comment by janPasi** [comment]
Ikävä kyllä kirjastokorttinumeron joutumista vääriin käsiin ei voi sulkea pois pelkästään sillä, että kirjastokortti on oikean asiakkaan hallussa ja ettei asiakas _tiedä_ sen joutuneen vääriin käsiin. Kysymyshän voi olla esimerkiksi siitä, että joku ilkimys generoi korttinumeroita omalla koneellaan ja kokeilee koputella niiden pin-koodeja auki (jolloin siis tuo kirjautumisyritysten määrä kasvaa). Tai vaihtoehtoisesti joku toinen ilkimys on kirjoitellut asiakkaan kirjastokortin numeron muistiin satuttuaan näkemään sen jossain yhteydessä.

Kortin numero voi siis aivan hyvin olla jonkun asiattoman henkilön hallussa ilman että asiakkaalla on siitä mitään tietoa. Ainoa tapa miten nämä tapaukset saadaan kiinni on juuri tuo virheellisten kirjautumisyritysten seuranta. Tästä syystä tässä täytyy siis nähdäkseni mennä asiakkaan tietosuoja edellä, eli aina ja poikkeuksetta vaihtaa kirjastokortin jos kirjautumisyrityksiä on liikaa. Haittaa siitä ei juurikaan ole, lukuunottamatta marginaalista kustannusta kirjastolle uudesta kortista.

**Comment by janPasi** [comment]
Huomautan vielä, että siis pelkän PIN-koodin vaihdostahan tässä ei ole mitään iloa, koska mahdollisesti väärissä käsissä oleva tieto tässä on nimenomaan kirjastokortin numero, ei PIN-koodi. Pelkästään PIN-koodia vaihtamalla annamme mahdolliselle murtautujalle uuden mahdollisuuden arvata koodi, eli tilanne itseasiassa huononee eikä parane.

**Comment by janPasi** [comment]
Ikävä kyllä kirjastokorttinumeron joutumista vääriin käsiin ei voi sulkea pois pelkästään sillä, että kirjastokortti on oikean asiakkaan hallussa ja ettei asiakas tiedä sen joutuneen vääriin käsiin. Kysymyshän voi olla esimerkiksi siitä, että joku ilkimys generoi korttinumeroita omalla koneellaan ja kokeilee koputella niiden pin-koodeja auki (jolloin siis tuo kirjautumisyritysten määrä kasvaa). Tai vaihtoehtoisesti joku toinen ilkimys on kirjoitellut asiakkaan kirjastokortin numeron muistiin satuttuaan näkemään sen jossain yhteydessä (tai vaikka ottanut siitä kännykällään valokuvan). Tapoja joilla kirjastokortin numero voi päätyä vääriin käsiin on lukuisia, eikä ylivoimainen valtaosa niistä edellytä kortin fyysistä hukkaamista, tai välttämättä aina edes kortin näkemistä.

Kortin numero voi siis aivan hyvin olla jonkun asiattoman henkilön hallussa ilman että asiakkaalla on siitä mitään tietoa. Ainoa tapa miten nämä tapaukset saadaan kiinni on juuri tuo virheellisten kirjautumisyritysten seuranta. Tästä syystä tässä täytyy siis nähdäkseni mennä asiakkaan tietosuoja edellä, eli aina ja poikkeuksetta vaihtaa kirjastokortti, jos kirjautumisyrityksiä on liikaa. Haittaa siitä ei juurikaan ole, lukuunottamatta marginaalista kustannusta kirjastolle uudesta kortista. Virkailijan tai asiakkaan (tai kenenkään muunkaan) paras arvaus siitä onko kortti vaarantunut ei ole tietoturvan kannalta missään määrin riittävä. On parempi pelata aina "varman päälle".

**Comment by janPasi** [comment]
Huomautan vielä, että siis pelkän PIN-koodin vaihdostahan tässä ei ole mitään iloa, koska mahdollisesti väärissä käsissä oleva tieto tässä on nimenomaan kirjastokortin numero, ei PIN-koodi. Pelkästään PIN-koodia vaihtamalla annamme mahdolliselle murtautujalle uuden mahdollisuuden arvata koodi, eli tilanne itseasiassa huononee eikä parane.

**Comment by pirliis** [comment]
Päätös kortin vaihtamisesta aina näissä tapauksissa on hyvä tehdä asiantuntijaryhmässä, jolloin voimme henkilökunnallemme vedota siihen, että näin on yhtisesti päätetty Koha-Suomesssa. :)

**Comment by janPasi** [comment]
> Päätös kortin vaihtamisesta aina näissä tapauksissa on hyvä tehdä asiantuntijaryhmässä, jolloin voimme henkilökunnallemme vedota siihen, että näin on yhtisesti päätetty Koha-Suomesssa. :)

Tottis, käydään läpi asiantuntijaryhmässä :)

**Comment by janPasi** [comment]
Alkuperäinen tiketti (#274) on käynyt asiantuntijaryhmässä 12.12.2022. Päätöksestä ei kuitenkaan löydy kirjausta mistään. Se on varmaan jäänyt kirjaamatta tuohon tikettiin.

**Comment by pirliis** [comment]
Kommentoi vielä tähän suljettuun tikettiin, koska meillä on tässä pieni porsaan reikä. :)

Kun asiakkaalla on virheellisiä kirjautumisyrityksiä yli 50 ja hänelle on tullut tästä syystä rajoite, jossa ilmoitetaan, että kortti on lainauskiellossa, henkilöllisyys on tarkistettava ja annettava uusi kirjastokortti sekä PIN-koodi.

Mutta jos asiakas kuitenkin vaihtaa PIN-koodin verkkokirjastossa toiminnolla "Unohditko PIN-koodisi?", hän pääsee kirjautumaan verkkokirjastoon uudella PIN-koodilla ja uusi PIN-koodi nollaa myös asiakkaan epäonnistuneiden kirjautumisyritysten määrän ja triggeri poistaa 15 minuutin kuluttua asiakkaalta rajoituksen.

Eli ajatus siitä, että aina ja poikkeuksetta näissä yli 50 virheellisen kirjautumisyrityksen seurauksena henkilöllisyys olisi tarkistettava, annettava uusi kirjastokortti ja PIN-koodi ei välttämättä aina toteudu.

**Comment by janPasi** [comment]
Koha-tontut olivat käyneet kirjoittamassa skriptiin hieman ylimääräistä. Sen käytössä ollut versio pudotti rajoituksen. Korjattu nyt.

**Comment by pirliis** [comment]
Nyt rajoite ei poistu automaattisesti asiakkaalta, vaikka hän vaihtaa salasanan verkkokirjastossa. Eli toimii kuin pitääkin. Suljen tiketin.
