### ISSUE TITLE
Osakohteiden näkyminen, jos niiden 245a-kentässä ei ole mitään

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#475]
### Mikä vikana?

Jos osakohteella ei ole nimeketietoa 245a-kentässä, mutta se voi olla kentässä 240a tai 130a (yhtenäistetty nimeke), niin tietueilla ei näy nimekettä (eikä linkkiä tietueeseen) hakutuloslistalla eikä Perustiedot-näytön Osakohde-välilehdellä.

Esimerkki OUTIsta: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1263090

Hakutuloslista:
![image](https://user-images.githubusercontent.com/98814860/226329372-691c8233-3604-4614-86b1-71396afee464.png)

Perustiedot-näytön Osakohde-välilehti:
![image](https://user-images.githubusercontent.com/98814860/226328472-7006c21f-805c-43f1-9b23-0791e3086b68.png)

### Mitä pitäisi tapahtua

Jos osakohteen ainoa nimeketieto on yhtenäistetty nimeke (240a/130a), pitäisi nimeketiedot ja linkit tietueeseen näkyä myös hakutuloslistalla ja Osakohde-välilehdellä.

**Comment by paxed** [comment]
Mahtaakohan tämä 245:n puuttuminen olla suomalaisen luettelointisäännöstön erikoisuus? Kaivelin hieman, ja ainakin OCLC sanoo että kenttä olis pakollinen. Jos näin, niin muutoksen saaminen yhteisöön on vähän hankalaa, ja joudutaan pitämään se meidän omana ...

**Comment by pknuuti** [comment]
Kyllä näitä löytyy Vaarastakin x-määrä. Raportti olisi kiva.

**Comment by paxed** [comment]
Esim. tälläsellä raportilla:

```
SELECT CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=', biblionumber, '">', biblionumber, '</a>') AS 'Linkki'
FROM biblio_metadata
WHERE ExtractValue(metadata, 'count(//datafield[@tag="245"]/subfield[@code="a"])') = 0
```

**Comment by Kati-Helle** [comment]
Kiitos raportista. 
Hellessä hakutulos on juuri nyt  9517.

**Comment by paxed** [comment]
Testeillä on nyt muutos että nimeketieto otetaan 240 tai 130 -kentistä, jos 245:sta ei ole.

**Comment by Kati-Helle** [comment]
Helle-testillä testasin 240-kentän näkyvyyden. Toimii.

Osakohdetietue biblionumber=966
Tietueella on 240-kenttä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f4d8bab6-32b6-4feb-b86e-b96c3e814524)

Osakohde Perustiedoissa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/7dbf3da7-06ee-44e1-b371-8d3ae37b3ec7)

Jewels of the ballet-linkki vie emotietueen Perustietoihin. Osakohteet-välilehdellä näkyvillä osakohteiden 240-kenttäarvot
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/17ca0373-951c-42c5-85d2-ba43a46eaa37)

**Comment by pknuuti** [comment]
Kiitos! Toimii Vaarankin testikannassa.

**Comment by AnttHeik** [comment]
OUTIn testillä toimii myös ainakin tuo 240-kenttä. En nyt keksi mitään esimerkkiä, jossa olisi pelkkä 130-kenttä, mutta jos toimii Hellessä, niin eiköhän sitten OUTIssakin :)

Voitko @pirliis asentaa OUTIinkin tuon Pasin tekemän raportin näistä tietueista?

> Esim. tälläsellä raportilla:
> 
> ```
> SELECT CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=', biblionumber, '">', biblionumber, '</a>') AS 'Linkki'
> FROM biblio_metadata
> WHERE ExtractValue(metadata, 'count(//datafield[@tag="245"]/subfield[@code="a"])') = 0
> ```

**Comment by pknuuti** [comment]
Vaarassa testaamassani oli nimenomaan tieto 130 kentässä.

**Comment by iinaniemi** [comment]
Vaskin testissä löysin [osakohteen](https://vaski-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=908197&searchid=scs_1697710459611) johon ei tule nimiketietoa, vaikka sellainen on kentässä 240. 

![ei nimikettä](https://github.com/KohaSuomi/Koha/assets/141715800/2ac74bb7-2ad5-46ea-a587-a40dc1cf77d2)

![marc](https://github.com/KohaSuomi/Koha/assets/141715800/06d132f3-f157-40f6-8620-a94cc2788704)

**Comment by paxed** [comment]
> Vaskin testissä löysin [osakohteen](https://vaski-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=908197&searchid=scs_1697710459611) johon ei tule nimiketietoa, vaikka sellainen on kentässä 240.
> 

Tämäpä onkin erikoinen. Jos tietuetta katsoo suoraan tietokannasta, niin siinä on kenttä 245 ... mutta sen ainoa sisältö on tyhjä osakenttä "." (joo, piste ei oo sallittu osakenttä, ja MARCia katsomalla näkee tietojen sisennyksestä että siinä on jotain mennyt rikki, ehkä konversiossa).

**Comment by Hanna-Lumme** [comment]
Toimii myös Lumpeiden testillä.

**Comment by AnneliO** [comment]
> > Vaskin testissä löysin [osakohteen](https://vaski-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=908197&searchid=scs_1697710459611) johon ei tule nimiketietoa, vaikka sellainen on kentässä 240.
> 
> Tämäpä onkin erikoinen. Jos tietuetta katsoo suoraan tietokannasta, niin siinä on kenttä 245 ... mutta sen ainoa sisältö on tyhjä osakenttä "." (joo, piste ei oo sallittu osakenttä, ja MARCia katsomalla näkee tietojen sisennyksestä että siinä on jotain mennyt rikki, ehkä konversiossa).
> 
> MUOKS: Ilmeisesti ongelma on ollut aikasemmassa järjestelmässä, konversiossa ei tuolle kentälle ole tehty mitään. Jos näitä halutaan korjata, niin teetkö @iinaniemi uuden tiketin asiasta

Testasin Vaskin testillä ja nuo 245.-osakentät saa helposti poistettua tietueiden erämuokkauksella. Vaski-testillä on valmis muokkauspohja sitä varten, jos haluatte testata. Kun 245.-kentän on poistanut, näkyy 240a otsikkona.

**Comment by AnneliO** [comment]
Tein Vaskiin siis tällaisen muokkauspohjan:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/529f7d31-9fe2-4a06-b8cc-2786ffbb7e74)

Avattuna:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/77b7aca7-8713-4c1f-8f0a-1989243692f2)

**Comment by AnneliO** [comment]
Tällä saa haettua tietueet, joissa on 245$.-kenttä:

<pre>SELECT biblionumber
FROM biblio_metadata
WHERE ExtractValue(metadata, 'count(//datafield[@tag="245"]/subfield[@code="."])') != 0</pre>

OUTIn ja Vaaran testiltä en tuollaisia löytänyt. Vaskissa on 142. Muita en testejä en testannut. :)

**Comment by Kati-Helle** [comment]
Raportin hakutuloksen perusteella Helle-testillä ei ole 245$.-kenttää. Tarkistin varulta myös tuotannon: 245$.-kenttää ei ole.

**Comment by pirliis** [comment]
> SELECT CONCAT('<a href="/cgi-bin/koha/catalogue/detail.pl?biblionumber=', biblionumber, '">', biblionumber, '</a>') AS 'Linkki'
> FROM biblio_metadata
> WHERE ExtractValue(metadata, 'count(//datafield[@tag="245"]/subfield[@code="a"])') = 0

Raportti nyt myös OUTIssa.

**Comment by janPasi** [comment]
> > SELECT CONCAT('[', biblionumber, '](/cgi-bin/koha/catalogue/detail.pl?biblionumber=', biblionumber, ')') AS 'Linkki'
> > FROM biblio_metadata
> > WHERE ExtractValue(metadata, 'count(//datafield[@tag="245"]/subfield[@code="a"])') = 0
> 
> Raportti nyt myös OUTIssa.

Vaihda @pirliis toi a-osakenttä (subfield[@code="a"]) pisteeksi subfield[@code="."], muuten raportti palauttaa kaikki missä on nimekekirjaus 245:ssa.

**Comment by janPasi** [comment]
Joo, sekoilen näköjään kuumehouruissa, sori, unohtakaa XD

**Comment by pknuuti** [comment]
Milloin tämä korjaus tulee tuotantoon?

**Comment by AnneliO** [comment]
Onko tässä tiketissä vielä jotain kesken? :)

**Comment by pirliis** [comment]
Suljen tämän tiketin. Tehdään uusi tiketti, jos halutaan korjata jossain vaiheessa tietueet, joilta puuttuu tieto 245a-kentästä.
