### ISSUE TITLE
Lisää painikkeita piiloon asiakkaan maksujen tapahtumat-välilehdeltä

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#476]
### Tukipyyntö

[Pääkäyttäjäpalaverissä 21.3.](https://github.com/KohaSuomi/kohasuomi.github.io/blob/master/_pages/paakayttajat2023.md#viikko-12-muistio) keskusteltiin Tulosta ja Maksa -painikkeiden vapaaehtoisesta piilottamisesta, jos niitä ei koeta kimpoissa tarpeellisiksi. Tähän tarvittaisiin IntranetUserCSS-rimpsu.

### Jotain muuta?

Aiemmin on jo tehty suositeltava css /* Piilota alennus, peruuta veloitus, luo hyvitys ja mitätöi maksutapahtuma -napit asiakkaan tilitapahtumat sivulta */

**Comment by AnneliO** [comment]
Tässäpä olisi piilotusrimpsuja IntranetUserCSS:ään. Kannattaa vielä testailla, että piiloon ei mene muita yllättäviä kohteita. Piilotusrimpsuja tuli yhteensä kolme, koska Tulosta-nappeja oli kahta erilaista. Toisesta sai tulostettua maksun tiedot, toisesta maksutapahtuman tiedot.

```
body#pat_borraccount a.btn.btn-default.btn-xs.invoice-print-action { display: none; } /* Maksun tietojen tulostus-napin piilotus */
```
```
body#pat_borraccount a.btn.btn-default.btn-xs.pay-action { display: none; } /* Maksu-napin piilotus */
```
```
body#pat_borraccount a.btn.btn-default.btn-xs.receipt-print-action { display: none; } /* Maksutapahtuman tai maksun poiston kuitti */
```

**Comment by pknuuti** [comment]
Ainakin Vaaran testillä näyttäisi toimivan kuten pitääkin eli piilottaa tarpeettomat napit, mutta jättää tarpeellisen eikä näytä häviävän mitään muuta olennaista.

**Comment by ReettaSiili** [comment]
Toimii Siilin testillä niin kuin toivottiin eli ylimääräiset painikkeet menivät piiloon, mitään liikaa ei näyttänyt piilottuvan. Minusta on selkeämpää, että yhden toiminnon (maksu) voi tehdä vain yhdessä paikassa.

**Comment by piiaseme** [comment]
OUTIssa rimpsut lisätty testille ja piilottavat mitä pitääkin eikä mitään ylimääräistä.

**Comment by Kati-Helle** [comment]
Rimpsut toimivat toivotulla tavalla Helle-testissä.

**Comment by AnneliO** [comment]
Rimpsut lisätty IntranetUserCSS-kirjastoon. Suljen tiketin. :)
