### ISSUE TITLE
Erikoistilan poisto kirjaston TUVR niteiltä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#477]
### Tukipyyntö

Niteiltä, joiden holdingbranch on TUVR, pitäisi poistaa notforloan tila '4' keskiviikkoaamuna 29.3.

**Comment by ajrajala** [comment]
Kirjastoa ei päästäkään avaamaan suunnitellussa aikataulussa vuotavan katon takia, joten tämän työpyynnön toteutusta täytyy siirtää. :/ Uusi avaamispäivä toivon mukaan 3.4. alkavalla viikolla, mutta laitan tälle tiketille uuden määräpäivän vasta kun avaamispäivä varmistuu.

**Comment by ajrajala** [comment]
Uudesta avaamispäivästä tuli tieto, 3.4. aamulla saisi nyt siis tehdä erikoistilojen poiston.

**Comment by lasse-koha** [comment]
Muutos tehty.
