### ISSUE TITLE
Helle: kahden uuden automaattitunnuksen lisääminen SIPoHTTPS-rajapintaan 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#478]
### Tukipyyntö

Lähetin tukipostiin salatusti sähköpostina tiedot Hellen kahdesta uudesta automaatista (Tammisaari JA Pohja).
Viestissä on tieto myös käytöstä poistetusta automaatista (Tammisaari).

Teettekö tarvittavat muutokset Hellen SIPoHTTPS-rajapintaan .

**Comment by lmstrand** [comment]
Tunnukset lisätty ja tarpeeton poistettu. RASPO-kirjastotunnusta ei ollutkaan ennestään sippikonffissa niin lisäsin sen myös. Tunnukset ovat huomenna käytettävissä.

**Comment by Kati-Helle** [comment]
Kiitos Lari :)

**Comment by janPasi** [comment]
Suljetko @Kati-Helle tämän tiketin.

**Comment by Kati-Helle** [comment]
Joo!
