### ISSUE TITLE
Siilinjärvi: asiakasmääreen USER_LANG/käyttökieli purkaminen

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#479]
### Tukipyyntö

Tarkoitus on poistaa ylimääräiset turhat asiakasmääreet LTOKEN, NATIVE ja USER_LANG. Ilmeisesti Koha-konversiossa 12/2016 vanhoille asiakkaille on ajettu käyttökieli fin, vaikka sillä ei nähdäkseni ole mitään merkitystä missään. Uusille asiakkaille tätä ei ole enää tullut. Asiakasmäärettä ei voi kuitenkaan poistaa ennen kuin se on siivottu vanhoilta asiakkailta pois. Eli siivousta pyydetään. Jos onnistuu niin sama pitäisi tehdä Siili-nextissä, jossa ehdin jo poistaa kaksi muuta asiakasmäärettä LTOKEN ja NATIVE. Pyydän sitten erikseen apua IntranetUserJS:n tarkistamiseen ja laskentaan.

**Comment by paxed** [comment]
USER_LANG poistettu asiakkailta sekä tuotannossa että nextillä. Noita LTOKEN ja NATIVE -määreitä ei näyttänyt olevan asiakkailla.

**Comment by ReettaSiili** [comment]
Kiitos! Suljen tämän tältä erää.
