### ISSUE TITLE
Lumme: printti-ilmoitukset jumahtaneet 13.2.23

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#480]
### Mikä vikana?

Asiakkaille ei ole lähtenyt printti-ilmoituksia 13.2. lähtien (pending-tilassa).

**Comment by emta001** [comment]
Sovittiin tästä, että 13.3. ja sitä tuoreemmat viestit lähetetään. Muut laitetaan failed-tilaan ja poistetaan viallinen zip-tiedosto. Katsotaan sitten lähtevätkö viestit eteenpäin.

**Comment by emta001** [comment]
Korjausliikkeet tehty. Otin nuo viestit vielä varuiksi talteen aputauluun ks_230327_message_queue_480.

**Comment by Katja-Lumme** [comment]
Kiitos, tämä selätetty!
