### ISSUE TITLE
MARC-tietueiden yhdistämissäännöissä suojatun kentän poistaminen Tietueiden muokkaus eräajona ei onnistu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#481]
### Mikä vikana?

MARC-tietueiden yhdistämissääntöihin määritelty kentän suojaus vaikuttaa myös toimintoon Työkalut/Tietueiden muokkaus eräajona. Yritin poistaa toiminnolla tiketissä https://github.com/KohaSuomi/Koha/issues/333 mainitun tietueen 653a-kentät - ei onnistunut.

Lisätestausta tietueella jonka aikaleima on ajalta ennen uutta versiota (ja uusia yhdistelysääntöjä).
Helle-tietueen biblionumber=1019987 kenttä 005
![kuva](https://user-images.githubusercontent.com/99952449/227498962-ffa92076-1d67-4903-b85a-75f263252b42.png)

Tietueella on mm. nämä kentät
![kuva](https://user-images.githubusercontent.com/99952449/227499098-b9722237-cee6-436e-b00d-ac03e28340e0.png)

poistetaan tietueen 521a-kenttä (521a-kenttää ei ole määritelty yhdistämissääntöihin)
![kuva](https://user-images.githubusercontent.com/99952449/227499204-93b70592-663d-43ab-8a35-bf1a099b24e8.png)

muokkaustoiminnon Näytä Marc -esikatselussa näkyy, että kenttä poistuu
![kuva](https://user-images.githubusercontent.com/99952449/227499286-9574bb77-eefb-4402-963f-8a128b72b998.png)

poistetaan tietueen 653a-kenttä (653a-kenttä on määritelty yhdistämissääntöihin)
![kuva](https://user-images.githubusercontent.com/99952449/227499443-2e3a9e67-4f0b-4e09-9dd4-7dc64b464220.png)

muokkaustoiminnon Näytä Marc -esikatselussa näkyy, että kenttä ei tule poistumaan
![kuva](https://user-images.githubusercontent.com/99952449/227499561-6f87c625-10b6-4b8b-86ce-cc29043df822.png)

**Comment by AnneliO** [comment]
Hellessä on 653-kenttää koskien kaikkia muokkausvaihtoehtoja koskeva (eli valittuna *)  Lisää ja liitä -sääntö. Tuo estää 653-kentän poistamisen.

Yhteisön manuaalissa kerrotaan Lisää ja liitä (Add and append) -toiminnosta seuraavaa:

[Add and append](https://koha-community.org/manual/22.11/en/html/administration.html#add-and-append)

Added: Add, Appended: Append, Removed: Skip, Deleted: Skip

In the “Add and append” preset, appending is also permitted, but **not removing or deleting.**

So if we have the following rule:

Module: source, filter: *, Tag: 650, Preset: Add and append

And the following original and incoming records:

```
100 1#$aTerrace, Vincent,$d1948-
650 #0$aTelevision serials$zUnited States$vCatalogs.

100 1#$aTerrace, Vincent,$d1948-
500 ##$aIncludes index.
650 #0$aTelevision pilot programs$zUnited States$vCatalogs.
```
The resulting record will be:
```
100 1#$aTerrace, Vincent,$d1948-
500 ##$aIncludes index.
650 #0$aTelevision serials$zUnited States$vCatalogs.
650 #0$aTelevision pilot programs$zUnited States$vCatalogs.
```
Note that the “old” 650 field from the original record was not removed since we only allow adding or appending new values.

If we instead used the “Overwrite” preset the resulting record would instead be:

```
100 1#$aTerrace, Vincent,$d1948-
500 ##$aIncludes index.
650 #0$aTelevision pilot programs$zUnited States$vCatalogs.
```
with the 650 field of the original record removed.

**Comment by Kati-Helle** [comment]
Lisää ja liitä -säännön poistamisen vaikutus: Helle-tietueen korvaaminen esim. TäTi-tietueella hävittää kansikuvalinkit Helle-tietueelta. Tästä Redmine-tiketissä (start date 28/07/2022)
https://tiketti.koha-suomi.fi/issues/5550

**Comment by AnneliO** [comment]
Jos muutat tuon *-säännön koskemaan vain Z39.50:stä, niin onnistuuko tietueiden erämuokkaukkaus?

**Comment by Kati-Helle** [comment]
Tietueiden erämuokkaus onnistuu, kun poistan *-säännön. Tarvittaessa olen näin tehden tehnyt massana tietuemuutoksia aamuisin, jotta ei vaikuttaisi tarpeettomasti muihin tietuekäsittelyihin. Ja lisännyt säännön takaisin tekemieni tietuemuutosten jälkeen.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2230685a-b133-4aaa-a28f-6ffe61ca153f)

**Comment by AnneliO** [comment]
Miksi teillä on tuo *-sääntö olemassa? Ei kai se ole tarpeen? Minun ymmärtääkseni riittää, kun sääntö on tehty koskemaan Z39.50:stä. 🤔 Vai enkö nyt vain hoksaa jotain?

**Comment by Kati-Helle** [comment]
Myös 856-kentällä on *-sääntö Hellessä.
Helle-tietueisiin tehdään tietuekorvauksia 'Korvaa tietue Z39.50/SRU-kyselyn kautta' -toiminnolla. Varastossa olevien teosten tietueita täydennetään teosten löytyvyyden parantamiseksi. 

Ilman *-sääntöä tietueen 653-kentät ja 856-kentät poistuvat tietuekorvauksessa.

**Comment by AnneliO** [comment]
Jos sama sääntö on Z39.50-versiona niin poistuuko ne silti?

**Comment by Kati-Helle** [comment]
> Jos sama sääntö on Z39.50-versiona niin poistuuko ne silti?

Emmi lisäsi tänään Helle-testin ylläpidosta puuttuneen MARC-tietueiden yhdistämissäännöt -toiminnon.

Testasin Helle-testissä 856-kentällä siten, että 856-kenttä on MARC-tietueiden yhdistämissäännöissä vain kertaalleen ja näin:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/607fb567-f6af-4f7a-aa12-c300c7caa172)

Korvaa tietue Z39.50/SRU-kyselyn kautta -toiminnolla Helle-testin tietueen biblionumber=1568302 kentät 856 säilyivät. (Tietueen korvaus Melinda-tietueella, jolla ei ole 856-kenttää.)

Testi-erikoisuus: tietueen 942-kenttä poistui (942c-arvo), kun sääntönä tämä 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ebd60656-0deb-4cca-a538-ce9e90248c83)

Testasin tuotannossa: testiä vastaava tuotannon 942-kentän ydistämissääntö toimii oikein ja säilyttää 942-kentän.

Yhdistämissäännöissä on siis tapahtunut parannustako jossain vaiheessa :) 
Hellessä 856-kentän "Lisää ja liitä" -säännön puuttumisesta on Helle-kokemuksena 856-kentän katoamisia. (Redmine-tiketissä https://tiketti.koha-suomi.fi/issues/5550 tuosta.)

**Comment by Kati-Helle** [comment]
Testasin nyt sekä Helle-testissä että Helle-tuotannossa kenttien 653 ja 856  *-suojaussäännön poistamisen.
Testatessani tietueyhdistely toimi ok, eli kenttä 653 ei poistunut, ei myöskään kenttä 856. Tietueen aineistotyyppi ei kadonnut testillä (kuten aiemmin testatessani katosi).

Poistin Hellestä kenttien 653 ja 856  *-suojaussäännön.
