### ISSUE TITLE
Lappi: niteen lainaaminen antaa virheen 500

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#482]
### Mikä vikana?

Nidettä 698N11411573 lainatessa tulee virheilmoitus 500. Niteen viivakoodissa ei ole ylimääräisiä numeroita, nide on lainattavissa eikä asiakkaalla ole mitää esteitä lainaamiseen.  Virhettä ei ilmene muilla niteillä.

**Comment by AnneliO** [comment]
Matrixin puolelta tänne myös ylös, että tulee virheilmoitus 

Can't call method "agerestriction" on an undefined value at /home/koha/Koha/C4/[Circulation.pm](http://circulation.pm/) line 1159.

ja rivi, johon homma kaatuu on

my $agerestriction  = $biblioitem->agerestriction;

Niteen biblionumber=1732798 ja tuolla tietueella ei ole jostain syystä tietoja biblioitems-taulussa, mistä tuo ikärajatietokin yritetään hakea.

**Comment by lasse-koha** [comment]
Lisäsin niteelle biblioitemin, nyt pitäisi lainaamisen onnistua.

**Comment by LeenaKinnunen** [comment]
Lainaaminen onnistuu, suljen tiketin.
