### ISSUE TITLE
Helle: kun asiakkaalla on varaus niteettömään tietueeseen, asiakkaaan tiedoissa varaukset eivät näy 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#483]
### Mikä vikana?

Asiakastiedoissa asiakkaan varauksista yksikään varaus ei näy, kun asiakkaalla on varaus niteettömään tietueeseen.

Tein Helle-tuotannon testillä varauksen asiakkaalle Asiakas ID=109720
![kuva](https://user-images.githubusercontent.com/99952449/227845797-d8140ab0-d3f4-4690-8f75-c57006603e64.png)

![kuva](https://user-images.githubusercontent.com/99952449/227846095-0663ab3b-d6bc-4205-a5b5-c717241d3125.png)

Asiakastiedon Varaukset-välilehti
![kuva](https://user-images.githubusercontent.com/99952449/227846275-1936f598-0137-4369-a443-0c8f68d0b18a.png)

Muistankohan väärin, että vastaava olisi tullut esille vuoden 2022 versionvaihtoa tehdessä? Tikettiä en nyt löytänyt.

**Comment by AnneliO** [comment]
Nyt löytyi [Niteettömän tietueen varaaminen Koha 22.xx / #34](https://github.com/KohaSuomi/Koha-22x/issues/34)

**Comment by AnneliO** [comment]
Suljen tuplatikettinä. :)
