### ISSUE TITLE
TUA3-yksikön varausten noutopaikan muutos

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#484]
### Tukipyyntö

Onnistuisiko muuttaa ajona noutopaikaksi 'TUVR' niille varauksille, joissa
- branchcode on tällä hetkellä 'TUA3'
- found IS NULL

**Comment by ajrajala** [comment]
Toiveissa saada muutos mahdollisimman pian, mutta kun tuli näin lyhyellä varoitusajalla niin en oleteta että varmasti onnistuisi tänään. :)

**Comment by lmstrand** [comment]
59 kpl muutettu:

```
MariaDB [vaskiprod]> update reserves set branchcode = 'TUVR'
    -> WHERE branchcode = 'TUA3' and found is NULL;
Query OK, 59 rows affected (0.004 sec)
```

**Comment by ajrajala** [comment]
Kiitokset!
