### ISSUE TITLE
Helle: logo käyttöön Kohan kirjautumissivulle

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#487]
### Tukipyyntö

Saisiko Helle-logon käyttöön Kohan kirjautumissivulle Koha-logon tilalle?

![kuva](https://user-images.githubusercontent.com/99952449/228436029-fd6a87c7-fe70-498e-8ceb-faba76578728.png)

**Comment by lmstrand** [comment]
StaffLoginInstructionsiin tarvitaan tällainen rimpsu:

```
<script>
	document.getElementById("login");
    login.childNodes[1].style.background = "url('koha-suomi-images/helle-images/Helle_logo_login.png') no-repeat center"; 
</script>
```
Helle-testillä asetus ei jostain syystä suostu tallentumaan wysiwyg-editoria käyttämällä tai ilman (internal server error).
Wysiwyg-editori sotkee asetuksen tallentamisen lähdekoodi-näkymässä myös Helle-Nextillä. 

Lisäsin rimpsun ilman wysiwyg-editoria ( UseWYSIWYGinSystemPreferences pois päältä) Hellen Nextille. Tallennus onnistui siellä ja logo näkyy kirjautumissivulla. Taidetaan joutua odottamaan versionvaihtoa, jotta logot saadaan paikalleen.
