### ISSUE TITLE
Työkalut/Asiakkaiden muokkaus eräajona ja mahdollisuus muokata kerralla enemmän kuin 20 asiakastietoa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#489]
### Tukipyyntö

Saisiko Asiakkaiden muokkaus eräajona -toiminnolla muokattua kerralla enemmän kuin 20 asiakastietoa?

Toiminto jakaa muokattavat asiakastiedot useammalle välilehdelle tyyliin korkeintaan 20 asiakastietoa välilehdellä 
![kuva](https://user-images.githubusercontent.com/99952449/229055275-cfc59341-aa02-409a-982f-0c4b163494ef.png)

Hellessä testatessani vain näkyvillä olevat 20 ensimmäistä 'muokkautuvat'. Muokkauksen jälkeen Koha ei ehdota jäljellä olevien asiakastietojen muokkausta. 
Muokattujen asiakastietojen lisäksi toimintosivun lopussa näkyy tämä:
![kuva](https://user-images.githubusercontent.com/99952449/229052906-1a3a25f8-cf21-492d-a73c-14db45b649fe.png)

Kokeilin vaihtamalla asetukseen PatronsPerPage suuremman arvon (20  ->  1000), mutta tämä ei testatessani vaikuttanut asiakkaiden erämuokkaus -toimintoon.

(Niteiden eräajoon liittyvissä MaxItems... asetuksissa arvona on 1000.)

**Comment by AnneliO** [comment]
Kaikkien muokkaus onnistuu näköjään sillä tavalla, että otat ennen muokkausta näkyville kaikki asiakkaat:

![kuva](https://user-images.githubusercontent.com/33121325/229429515-53b8a6f1-4780-4bea-add7-75678720ab29.png)

**Comment by Kati-Helle** [comment]
Toimii. Kiitos Anneli :)
