### ISSUE TITLE
Palautusautomaatin yhteysongelma Kohaan

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#495]
### Mikä vikana?

Mikkelin pääkirjaston palautusautomaatilla on Kohan kanssa yhteysongelma, sillä automaatti ei jostain syystä saa haettua palautetun aineiston tietoja Kohasta - hakuaika ylittyy, minkä takia palautus ei onnistu. Automaatti on käynnistetty useaan kertaan uudestaan, mutta ongelma toistuu. Mikroväylä pidensi hakuaikaa 10 sekunnista 15, mutta palautus ei edelleenkään onnistu ja ongelma näyttää nyt koskevan useampaa nidettä.

**Comment by Hanna-Lumme** [comment]
Tuli juuri viestiä, että Joroisissa on samaa ongelmaa, että automaatti kadottaa yhteyden palvelimeen. Supan puolelta eivät löytäneet tähän selitystä, muut verkkoyhteydet toimivat normaalisti.

**Comment by janPasi** [comment]
Lokien perusteella automaatin ja palvelimen välinen kommunikaatio vaikuttaisi pelaavan normaalisti ja silmämääräisesti kaikkiin palautussanomiin on vastattu palvelimelta alle sekunnissa. Käyköhän tässä nyt niin, että automaatin viestejä eksyy johonkin välille?

**Comment by Hanna-Lumme** [comment]
Selviteltiin tätä vielä Katjan kanssa ja todettiin, että automaatin antamista virheilmoituksista huolimatta vika taitaa johtua itsessään automaatista. Suljen tiketin tältä erää ja seuraillaan tilannetta, josko ongelma uusiutuu (toivottavasti ei).
