### ISSUE TITLE
Tiedonhaku ja ranskan kielen artikkeli l' - teoksen tietueen 240a-kenttäarvo alkaa artikkelilla l' jolloin teos löytyy vain artikkelin kanssa hakiessa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#496]
### Mikä vikana?

Artikkeli l' teoksen tietueen 240a-kenttäarvon alussa alussa aiheuttaa sen, että teos ei löydy tiedonhaussa ilman artikkelia.

Sama tapahtuu sekä tuotannossa että uuden version testissä.

Esimerkkiteos isbn 9789523345898, jonka tietueen 240-kentän arvossa artikkelin merkit l' on määritelty ohitettavaksi 2. indikaattorilla (arvona 2)
![kuva](https://user-images.githubusercontent.com/99952449/231358658-cece17b8-c64d-4e0f-b80e-9cc6026ea6e4.png)

Hakutulos ilman artikkelia hakiessa
![kuva](https://user-images.githubusercontent.com/99952449/231358955-9d39d454-95f0-490c-8876-e342b4879cfe.png)

Hakutulos artikkelin kera hakiessa
![kuva](https://user-images.githubusercontent.com/99952449/231359149-5fb9ff12-f8d4-47db-aa7e-7765044fb2a9.png)

Vastaava tapahtuu Finnassa
Hakutulos ilman artikkelia hakiessa
![kuva](https://user-images.githubusercontent.com/99952449/231359648-7444becc-c131-4654-a4df-47b5dff5d777.png)

Hakutulos artikkelin kera hakiessa
![kuva](https://user-images.githubusercontent.com/99952449/231359782-1ef2e7d8-8e36-48b9-9f06-3c584fc84e6a.png)

**Comment by AnneliO** [comment]
Koska ongelma koskee myös nykyistä tuotantoa, siirsin tiketin Koha-repositorioon.

**Comment by Kati-Helle** [comment]
Kiitos Anneli tiedosta.

**Comment by emta001** [comment]
Koha-Suomen palaveri 20.6.2023: Ei korjata Koha-Suomen toimesta, odotetaan korjausta yhteisöstä.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 12.8.2024: Tutkitaan, olisiko stoppisanalistasta tässä apua. Tosin, se voi sitten rikkoa haun jossain muilla kielillä.

**Comment by lmstrand** [comment]
Kohassa ei ole tukea stoppisanoille.

**Comment by lmstrand** [comment]
Elasticsearchin konfiguraatioon voi lisätä stoppisanoja: https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-stop-tokenfilter.html

**Comment by lmstrand** [comment]
Koha ei käsittele noita kentän indikaattoreita mitenkään, missä se ohitus on ja koska tämä vaikuttaa muihinkin kieliin, niin jätetään nykyiselleen.

**Comment by pknuuti** [comment]
Tätä olen ihmetellyt koko Koha-ajan eli miksei oteta indikaattoreita huomioon, vaikka ne ovat juuri sitä varten, että esim. artikkeli voidaan ohittaa nimen alussa. Luulisi yhteisöä kiinnostavan korjata tämä vuosikausia ollut ongelma.

**Comment by CodoDerDritte** [comment]
Stoppisanalistojen käyttö monikielisessä haussa voi olla aika ongelmallista, en suosittele. Se pudottelee sitten eri kielillä haettaessa mahdollisesti vääriä sanoja pois hauista.

**Comment by pknuuti** [comment]
"En etsi valtaa, loistoa" on hyvä esimerkki, joka ei löydy, jos stoppisanana on ruotsalainen "en". Mutta kun hauista poistetaan indikaattoreilla nimekkeessä oleva artikkeli pois, silloin se osuu oikeaan sanaan.

**Comment by CodoDerDritte** [comment]
Niiden indikaattorien huomiointi voi olla hieman haastavaa. Pudotettavat merkit pitäisi ehkä poistaa jo indeksointivaiheessa ja sitten haku ei palauttaisi tuloksia ollenkaan jos esimerkiksi sen l' siihen alkuun kirjoittaisi, koska sitä ei ole indeksissä. Olisi varmaankin toivottavaa että kumpikin muoto toimisivat, eli ikäänkuin että se ohitusindikaattorin osoittama etuliite tai artikkeli olisi sallittu mutta ei pakollinen.

**Comment by lmstrand** [comment]
Meillä on matkassa yhteisötiketin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36678 commit jossa nähtävästi otetaan huomioon nuo ohitusindikaattorit ja omalla testilläni haettaessa Vaski-nextillä "entree" palauttaa mm. tietueen "L'entree de l'Hierophante tuloksissa.

**Comment by lmstrand** [comment]
Hakiessa "L'entree" tai "l'entree" ei tosin palaudu teoksia, joissa pelkkä "entree".

**Comment by lmstrand** [comment]
Tähän saadaan siis tuki versionvaihdossa.
