### ISSUE TITLE
Lappi : kiinniolopäiviltä syntyneiden aiheettomien ODUE-maksujen poisto

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#499]
### Tukipyyntö

Tervolan kirjastossa TEPK on kalenterista ylitetty eräpäivät ajalta 3.-6.4. Asiakkaille on tullut Finnassa uusinnoilla kuitenkin eräpäiviä tuolle kiinnioloajalle (liittynee mahdollisesti väärin määritettyihin checkout-järjestelmäasetuksiin, joita ollaan selvittämässä). 

Tarvittaisiin joko
- lista asiakkaille syntyneistä palautuskehotusmaksuista (ODUE1), jotka ovat muodostuneet TEPK:n lainoille 6.-9.4. välisenä aikana (poistetaan itse manuaalisesti) 
- tai sitten ko. maksujen kyseisten poisto suoraan järjestelmästä.

**Comment by janPasi** [comment]
Tuolla aikarajauksella ei palaudu maksutaulusta yhtään riviä, jotka koskisivat TEPK-aineistoja. Kysely alla.

```
select date,accountlines.issue_id,concat(coalesce(issues.branchcode,old_issues.branchcode)) as 'branchcode', amount,amountoutstanding from accountlines left join issues using (issue_id) left join old_issues using(issue_id) where debit_type_code like 'OVERDUE%' and date between '2023-04-06' and '2023-04-09' order by 1;
```

Raportti täällä: https://lappi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=479&phase=Run%20this%20report

**Comment by janPasi** [comment]
Tässä vielä vastaava raportti niteen kotiosastoittain:

https://lappi.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?phase=Run+this+report&reports=480&limit=1000

Edelleenkään ei yhtään TEPK-nidettä.

**Comment by LeenaKinnunen** [comment]
Kyse oli näistä viimeisistä maksuista, jotka tuo raportti antaa. Välitän tiedon kirjastolle, poistavat maksut sitten käsin jos niitä tulee vastaan. Kiitos näistä! Suljen tiketin.
