### ISSUE TITLE
Erikoistilan lisääminen osalle Kustavin kirjaston aineistosta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#500]
### Tukipyyntö

Kustavin kirjasto (KUPK) on muuttanut väistötiloihin ja suurin osa aineistosta ei ole toistaiseksi käytettävissä.
Notforloan tila '4' pitäisi siis asettaa niteille, jotka täyttävät seuraavat ehdot:

- holdingbranch = KUPK
- biblioitems.itemtype **ei ole** 'ALEHTI'
- nide ei ole lainassa tai kuljetettavana
- nide ei ole noudettavissa tai kuljetettavana noutoyksikköön
- niteellä ei ole entuudestaan notforloan-tilaa tai lost-tilaa

Onnistuuko ajaa muutos lyhyestä varoitusajasta huolimatta jo tiistaiaamuna 18.4.?
Vaihtoehtoisesti myös keskiviikkoaamu 19.4. sopii.

**Comment by lmstrand** [comment]
Tehdään huomenaamulla.

**Comment by lmstrand** [comment]
ajettu:

create table ks_230418_itemsbck_kd500 as

select items.itemnumber, items.notforloan from items
left join biblioitems ON items.biblionumber = biblioitems.biblionumber
left join reserves ON items.itemnumber = reserves.itemnumber
where holdingbranch = 'KUPK'
and biblioitems.itemtype != 'ALEHTI'
and reserves.found is NULL
and onloan is NULL
and items.itemnumber not in (select itemnumber from branchtransfers where tobranch = "KUPK" and datearrived IS NULL)
and notforloan = 0
and itemlost = 0


ja


update items set notforloan = 4 where itemnumber in
(
select items.itemnumber from items
left join biblioitems ON items.biblionumber = biblioitems.biblionumber
left join reserves ON items.itemnumber = reserves.itemnumber
where holdingbranch = 'KUPK'
and biblioitems.itemtype != 'ALEHTI'
and reserves.found is NULL
and onloan is NULL
and items.itemnumber not in (select itemnumber from branchtransfers where tobranch = "KUPK" and datearrived IS NULL)
and notforloan = 0
and itemlost = 0
)


14698kpl notforloan-tiloja muutettu arvoon 4.

**Comment by ajrajala** [comment]
Kiitos! Silmäilin läpi ja silmään sattui ekana osumaan tällaiset itemnumberit jotka ei jostain syystä olleet saaneet notforloan-arvoa: 850196 ja 854915. En keksinyt muuta kuin että nuo itemnumberit löytyvät branchtransfers-taulusta riveinä, joissa datearrived on tyhjä mutta datecancelled-arvossa on päivämäärä. Olisiko tuohon branchtransfers-rajaukseen pitänyt lisätä vielä OR-ehto datecancelled-arvon osalta?

Muutoin ajo minusta ok.

**Comment by lmstrand** [comment]
Ajettu vielä:


insert into ks_230418_itemsbck_kd500 (itemnumber, notforloan)
select items.itemnumber, notforloan from items
left join biblioitems ON items.biblionumber = biblioitems.biblionumber
left join reserves ON items.itemnumber = reserves.itemnumber
where holdingbranch = 'KUPK'
and biblioitems.itemtype != 'ALEHTI'
and reserves.found is NULL
and onloan is NULL

and items.itemnumber not in (select itemnumber from branchtransfers where frombranch = "KUPK" and datecancelled is not null)

and notforloan = 0
and itemlost = 0





update items set notforloan = 4 where itemnumber in
(
select items.itemnumber from items
left join biblioitems ON items.biblionumber = biblioitems.biblionumber
left join reserves ON items.itemnumber = reserves.itemnumber
where holdingbranch = 'KUPK'
and biblioitems.itemtype != 'ALEHTI'
and reserves.found is NULL
and onloan is NULL

and items.itemnumber not in (select itemnumber from branchtransfers where frombranch = "KUPK" and datecancelled is not null)

and notforloan = 0
and itemlost = 0
)


318 niteen notforloan-tila vaihtui 4:ksi.

Noihin ehtoihin sisältyi ainaskin mainitsemasi niteet.

**Comment by ajrajala** [comment]
Kiitokset, asia kunnossa!
