### ISSUE TITLE
Nidevaraus näkyville vain kohdekirjaston hyllyvarauslistalle

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#501]
### Kehitysehdotukseni

Juttelin tuossa virkailijan kanssa ja tuli puheeksi nidevaraukset, jotka eivät kohdistu lehtiin. Tällä hetkellä, jos esim. kirjaan tekee nidevarauksen, niin varaus näkyy kaikkien kirjastojen hyllyvarauslistoilla, missä kirja on paikalla. Tämä tietysti sitten aiheuttaa turhaa työtä, kun muut kuin kohdekirjastot hakevat kirjan hyllystä, eikä se jää kiinni palautuksessa. 

Olisiko mahdollista tehdä niin, että nidevaraus näkyisi vain ja ainoastaan sen kirjaston hyllyvarauslistalla, johon varaus kohdistuu? Vähän niin kuin kirja olisi "ainoana" paikalla.

**Comment by janPasi** [comment]
Nidevarausten ollessa kyseessä raportilla pitäisi muistaakseni näkyä nidenumero jota varaus koskee?

**Comment by janPasi** [comment]
Eikun eipäs näykkään, muistin väärin. Outoa 🤔

**Comment by AnneliO** [comment]
Yhteisön hyllyvarausraportilla on viivakoodi-sarake. Olisiko se tippunut meidän versiosta jossain vaiheessa joko tarkoituksella tai vahingossa?

**Comment by AnneliO** [comment]
Testailin tätä outi-testillä ja lumme-testillä minun testien mukaan nidevarauksessa näkyy On shelf -sarakkeessa vain sen kirjaston lyhenne, jossa nidevarauksen nide on paikalla:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/81aa43d1-bd82-4f99-acd8-efa2a6701987)

lumme-testillä tein varauksen [tähän teokseen](https://lumme-test.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2554564), jos haluat tutkailla tilannetta.

**Comment by AnneliO** [comment]
Ja siis minun testeissä kummassakin tietuessa oli saatavana useampia niteitä, jolloin normivarauksessa On shelf -sarakkeeseen olisi tullut näkyville kaikkien saatavana olevien niteiden sijaintikirjaston tunnus.

**Comment by Hanna-Lumme** [comment]
Näyttää testailun jälkeen toimivan tuotannossakin. Hieno juttu!
