### ISSUE TITLE
Lappi : Bibliolibrary-rajapinnan sulkeminen

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#503]
### Tukipyyntö

Lapilla on ollut käytössä Axiellin Bibliolibrary. Palvelun käyttö on päättynyt, mutta palveluun pääsee vielä kirjautumaan Lapin kirjastokortilla. Onko rajapinnan sulkeminen Koha-Suomen vai Axiellin tehtävä? Jos Koha-Suomen, voitteko sulkea rajapinnan?

**Comment by janPasi** [comment]
Nyt täytyy tunnustaa, etten tiedä kyseisestä palvelusta kyllä yhtään mitään, eikä täällä meidän päässä taida kukaan tietää miten tuo palvelu itseasiassa Kohaan on integroitu :D Jos se käyttää yleisimmin integraatioihin käytettyä borrowers/status rajapintaa, niin täältä meidän päästä sulkemista ei voida tehdä vaan se on palveluntarjoajan (eli tässä tapauksessa Axiellin) homma.

**Comment by janPasi** [comment]
Lisäsin tämän ohjeistuksen myös integraatiosivulle https://github.com/KohaSuomi/Koha/wiki/Integraatiot

**Comment by LeenaKinnunen** [comment]
Ok, otamme yhteyttä toimittajaan.

**Comment by LeenaKinnunen** [comment]
Rajapinta on nyt suljettu palveluntarjoajan toimesta. Suljen tiketin.
