### ISSUE TITLE
Kyyti: asiakasmääreiden tyhjennys (ja poisto)

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#504]
### Tukipyyntö

Osittain liittyen [tikettiin 232](https://github.com/KohaSuomi/Koha/issues/232).

Kyytistä voisi poistaa seuraavat asiakasmääreet. Osa määreistä pitäisi tyhjentää ensin:

```
USER_LANG	tyhjennys ja poisto
NATIVE		tyhjennys ja poisto	
LTOKEN		poisto
SSBAN		poisto
SST&C		poisto
```

USER_LANG ja NATIVE ovat Origosta konvertoitunutta tietoa, jota ei enää tarvita.

Voin tehdä asiakasmääreiden poistot tyhjennyksen jälkeen ja korjata sotu-avain-kentän numeron IntranetUserJS:ään, mutta sitten pitää sopia yhteinen aika, jotta kehittäjä päivittää tarkastussumman.

Nämä pitää ilmeisesti myös tehdä NEXTissä, jos kerran asiakasmääreet siirretään nextiltä tuotantoon, kuten [tuolla](https://github.com/KohaSuomi/Koha-22x/wiki/Versiovaihdon-muistiinpanot) lukee . Sen voin tehdä itse, koska tyhjennysmäärät ovat pieniä eikä tarkistussummaa tarvita.

**Comment by emta001** [comment]
Kävin tekemässä tämän nexteille testi mielessä. Seuraavilla loitsuilla lähtivät:

`DELETE FROM borrower_attributes WHERE code = "NATIVE";`
`DELETE FROM borrower_attributes WHERE code = "USER_LANG";`

Otin arvot talteen aputauluihin:

`CREATE TABLE ks_240424_borrower_attributes_504_1 SELECT * FROM borrower_attributes WHERE code = "NATIVE";`
`CREATE TABLE ks_240424_borrower_attributes_504_2 SELECT * FROM borrower_attributes WHERE code = "USER_LANG";`

Tehdään nämä samat komennot ja checksummin päivitys huomenaamuna tuotantoon noin 8.15.

**Comment by Tuomas-Kyyti** [comment]
Tämä tehty, kiitos.
