### ISSUE TITLE
Työkaluliitännäiset/Tulosta ilmoituksia - viestin poistomahdollisuus tulostussivulle

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#505]
### Kehitysehdotukseni

Saisiko Tulosta ilmoituksia -toiminnon tulostussivulle tarpeettoman/ei-tulostettavan viestin poistotoiminnon?

Viestin tulostussivun toimintopainikkeina on nyt 
Takaisin (vie viestiluetteloon)
Tulosta (tulostaa viestin)
![kuva](https://user-images.githubusercontent.com/99952449/233026319-e1c30e4b-1a6b-4d16-b632-0f55557e1c00.png)

**Comment by AnneliO** [comment]
Ongelma Hellen tuotannossa, jossa Peruuta-nappi ei poista tulostettavia listalta. Toimii Hellen testillä toimii, kuten myös Kyytissä.

**Comment by Kati-Helle** [comment]
Bugi oli testaajassa eli minussa liittyen Helle-tuotantoon. Testasin nyt vielä uudestaan: viestin poistaminen Peruuta-painikkeella toimii hyvin.
