### ISSUE TITLE
Niteen poisto poistaa lainan asiakkaan lainahistoriasta

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#507]
### Kehitysehdotukseni

Redminen tiketti: https://tiketti.koha-suomi.fi/issues/4089

Kun kirjastossa poistetaan nide, jota asiakkaat ovat lainanneet, poistuu laina myös asiakkaiden lainahistoriasta. Toiminto on epälooginen asiakkaille. Ainakin OUTIssa toivotaan, että teos näkyisi asiakkaan lainahistoriassa niteen poiston jälkeenkin.

Asiantuntijaryhmän päätös 19.4.23. Seurataan yhteisön kehitystä.

**Comment by emta001** [comment]
Yhteisössä on ollut jo pidempään keskustelussa muutos, jossa tauluista deleteditems, deletedbiblioitems ja deletedbiblio luovuttaisiin ja poisto ilmaistaisiin lisäämällä sarake johon lisätään poistopäivä (tiketti [20271](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=20271)). Asia ei vain ole edennyt pitkään aikaan.

**Comment by LeenaKinnunen** [comment]
Lapin Finnassa poistettu nimeke näkyy nyt omien tietojen lainahistoriassa, mutta nimekkeen ja tekijätietojen kohdalla näytetään tiedot _Ei nimekettä ja Tuntematon_ . Lainasta näkyy lainauspaikka, lainauspäivä ja palautuspäivä.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 12.8.2024: Toteutettu yhteisön kautta poistamalla constraint. Nidenumero ei enää katoa lainahistoriasta.
