### ISSUE TITLE
Omatoimilukija ilman PIN-koodia kasvattaa epäonnistuneiden kirjautumisyritysten määrää

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#512]
### Mikä vikana?

Oulussa on Kaakkurin ja Maikkulan omatoimikirjastoissa normaalit omatoimilukijat ulko-ovilla, mutta sen lisäksi kirjastoissa on erilliset sisäoven lukijat, joka päästävät asiakkaat sisään omatoimeen pelkällä kortin luvulla, eikä kysy pin-koodia. Tämä näkyy SIP-viesteissä ”Invalid password”-kirjauksena. Sisäovi on ohjelmoitu niin, että se päästää sisään tästä huolimatta, koska siinä ei ole pin-kyselyä. Eli toimii aivan kuten halutaan.

It-tiimissä on huomattu, että tämä kysely kasvattaa asiakkaan epäonnistuneiden kirjautumisten määrää, jos sen tarkistaa Kohan raportilla. 

### Mitä pitäisi tapahtua

Kirjautuminen omatoimilukijalla ilman pin-koodia ei saisi kasvattaa asiakkaan epäonnistuneiden kirjautumisyritysten määrää.

### Jotain muuta?

It-tiimi vinkkasi, että koha-communityssä on ollut vanha sip2-bugi, joka on saanut heidät pohtimaan sen olemassaolon mahdollisuutta meidänkin järjestelmässä (https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=28822) .

**Comment by lmstrand** [comment]
Kyseiselle tunnukselle pitäisi lisätä allow_empty_passwords="1" -arvo tuonne sip-palvelinkonfiguraatioon ja katsoa, ratkaiseeko se asian.

**Comment by pirliis** [comment]
Oulun it-tiimin Mari Vesalan kommentti:
"En tiedä onko mitään vaikutusta asiaan, mutta pitää ottaa huomioon se, että vaikuttaako empty_passwordin salliminen pääoven lukijaan. Siitä ei saa päästä asiakasta sisään tyhjällä/väärällä salasanalla, koska siinä on pin-kysely. Pääoven ja sisäoven lukijat ovat osa samaa omatoimitietokonetta ja toimivat samalla tunnuksella."

**Comment by lmstrand** [comment]
Maikkulan ovikoneen tunnukselle lisätty allow_empty_passwords="1". Testattu tänään ja havaittu toimivaksi ratkaisuksi. Nyt lisätty myös Kaakkurin tunnukselle. On huomenna käytössä.

**Comment by janPasi** [comment]
Tämä ratkaisu ei välttämättä ole kovin pitkäikäinen. Jos etenemme SIPoHTTP:n kanssa suunnitellusti, ei tuommoinen yhden oven takia tehtävä poikkeus välttämättä enää ole oikein toteuttamis/ylläpitokelpoinen.
