### ISSUE TITLE
Asiakkaan Ilmoitukset-välilehteen liittyvä käännösmuutos

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#513]
### Kehitysehdotukseni

Kun asiakkaalle ei ole lähetetty Kohasta yhtäkään viestiä, ilmoittaa Koha asiakastiedon Ilmoitukset-välilehdellä näin:
![kuva](https://user-images.githubusercontent.com/99952449/233582721-eee7da3b-579b-4d50-9ada-40a44dd1a328.png)

Kenties teksti voisi olla hieman toisin? Esimerkiksi:
Asiakkaalla ei ole ilmoituksia.
Asiakkaalle ei ole lähetetty viestejä.
Asiakkaalla ei ole viestejä.

Annelilta tämä tieto:
Teksti on englanniksi There is no record of any messages that have been sent to this patron.

**Comment by janPasi** [comment]
Tässä täytyy pitää mielessä myös että se, ettei viestijonossa juuri sillä hetkellä ole viestejä asiakkaalle ei tarkoita etteikö niitä olisi koskaan lähtenyt. Viestijonon siivous on voinut siivota listalta aiemmin asiakkaalle lähetetyt viestit pois. Nykyinen alkukielistä tekstiä seuraava käännös on täsmällisempi.

**Comment by AnneliO** [comment]
Asiantuntijaryhmän päätös 18.3.2024: Ei muuteta tekstiä.
