### ISSUE TITLE
Varaustunnus-asiakasmääre näkyville mm. Noudettavissa olevat varaukset -toiminnossa

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#514]
### Mikä vikana?

Noudettavissa olevat varaukset -toiminnossa ei näy Varaustunnus-asiakasmääre, vaan varaustunnusarvona näkyy sama kuin tuotannossa eli varaustunnus-kentän arvo. 

Lisäksi Nextin Koha-asiakastiedoissa näkyy varaustunnus-kentän arvo asiakkaan muokkausnäytön 'otsikossa' ja näytön vasemmalla tietoruudussa. Varaustunnus-kentän arvo on kuvassa punalaatikoitu
![kuva](https://user-images.githubusercontent.com/99952449/232412177-3b0bcc01-9f51-4d3b-9e4c-f9512243be83.png)

Varaustunnus-asiakasmääre tarvitaan käyttöön myös ainakin Vanhentuneet varaukset -raporttiin.

Varaustunnusmuutoksesta löysin tämän tiketin https://github.com/KohaSuomi/Koha-22x/issues/36

**Comment by AnneliO** [comment]
Asiantuntijaryhmän päätös 84.4.2024: Tiketissä [Waitingreserves.pl-sivulle mahdollisuus näyttää asiakkaan tiedoista vain varaustunniste #367](https://github.com/KohaSuomi/Koha/issues/367) on päätetty, että asiakastiedot piilotetaan. Noudatetaan sitä päätöstä.
