### ISSUE TITLE
Kyyti: onix-koodi mappausmuutos

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#516]
### Tukipyyntö

Kyytissä on vaihtunut cd-levyjen laina-aika ja olisi hyvä saada onix-koodi - nidetyyppi -mappaus päivitettyä.
Liitteenä kaikki vastaavuudet. Uusi nidetyyppi on onix-koodeille AC, AH ja AI.

Kyytin vaihtoehtoiset hyllypaikkalyhenteet ovat ennallaan N, NA ja SN.

### Jotain muuta?

[map_productform_alternative_Kyyti_04_2023.xlsx](https://github.com/KohaSuomi/Koha/files/11308198/map_productform_alternative_Kyyti_04_2023.xlsx)

**Comment by lmstrand** [comment]
Sori Emmi, varastin tämän itselleni.

Kyytin tuotantoon ajettu:

```
update map_productform set productform = '28MAV', productform_alternative = '28EAV' where onix_code = 'AC';
update map_productform set productform = '28MAV', productform_alternative = '28EAV' where onix_code = 'AH';
update map_productform set productform = '28MAV', productform_alternative = '28EAV' where onix_code = 'AI';
```

**Comment by Tuomas-Kyyti** [comment]
Kiitos. Vaikuttaa toimivan oikein.
