### ISSUE TITLE
Vaara: Tarpeettoman rajoituksen poisto

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#518]
### Tukipyyntö

Asiakasmääre SSBAN on osoittautunut tarpeettomaksi ja sen voisi poistaa. Sitä ennen täytyy kuitenkin poistaa määre 655 asiakkaalta ja poistaa myös muut vanhentuneet käyttörajoitukset, joita joillakin asiakkailla näyttää olevan.

**Comment by lmstrand** [comment]
Vaaran tuotantoon ajettu:
```
MariaDB [vaaraprod]> delete from borrower_attributes where code = 'SSBAN';
Query OK, 653 rows affected (0.015 sec)
```
Poistetut arvot on tallennettu varmuuskopiotauluun ks_230425_518.

**Comment by pknuuti** [comment]
Kiitos.  Suljen tiketin.
