### ISSUE TITLE
Kyyti: kirjaimet 084-luokkakentässä ja cn_class

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#519]
### Tukipyyntö

Tutkailin uutta tietokantataulua koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements. Tuossa uudessa taulussa on sarake cn_class. Se ilmeisesti hakee tietonsa marcin 084-kentästä. Kyytissä varmaan tuhansissa vanhoissa tietueissa on 084-kentän luokkanumeron perässä kirjain, joka on kertonut kirjaston, esim. 84.2K. Luokka on siirtynyt kirjaimineen tuonne cn_class-sarakkeeseen. Onko siitä jotain haittaa siellä? Mihin cn_classia käytetään? Pitäisikö vanhat kirjaimen sisältävät 084-kentät siivota kirjaimista?

**Comment by emta001** [comment]
Tuota cn_class-sarake on bde-taulussa lähinnä kimppojen omien raporttien käyttöön. Se että onko tietue esim. musiikkiaineistoa määritetään 084$a-kentän alkuosasta (tässä tapauksessa 78). Joten ainakaan tältä osin noista kirjaimeen päättyvistä luokkanumeroista ei ole haittaa.

Kyllähän nuo voidaan koittaa korjata, mutta pitäisi saada tieto missä kaikissa muodoissa noita löytyy. Eli onko siellä lisäksi sellaisia tietueita, joissa kentässä on kirjain alussa tms. Osaatko Tuomas sanoa näistä tarkemmin?

**Comment by Tuomas-Kyyti** [comment]
Jotain pari kymmentätuhatta tietuetta löytyi, joissa oli viimeisenä kirjaimena W, V, R, Q, P, K, J, I, H, f tai A. Jos näistä ei varsinaisesti ole haittaa, niin kannattaakohan sitten korjatakaan.

Näitä tutkiessa tuli vastaan useita tietueita, jotka löytyivät bde-taulusta, mutta jotka oli Kohasta poistettu, eivätkä ihan uusilta poistoilta vaikuttaneet. Miten poistettujen tietueiden pitäisi poistua dbe-taulusta? Ovatko nämä joku ongelma? Esim. biblionumberit 725435, 585249, 617792, 893908 ja 332183.

**Comment by emta001** [comment]
> Jotain pari kymmentätuhatta tietuetta löytyi, joissa oli viimeisenä kirjaimena W, V, R, Q, P, K, J, I, H, f tai A. Jos näistä ei varsinaisesti ole haittaa, niin kannattaakohan sitten korjatakaan.
> 

Hmm, toki olisi siisteyden kannalta hyvä että ne siivotaan pois. Mutta tilastojen kannalta tällä ei tosiaan ole kiire, voidaan tehdä tuo siivous jossain vaiheessa myöhemminkin. 

> Näitä tutkiessa tuli vastaan useita tietueita, jotka löytyivät bde-taulusta, mutta jotka oli Kohasta poistettu, eivätkä ihan uusilta poistoilta vaikuttaneet. Miten poistettujen tietueiden pitäisi poistua dbe-taulusta? Ovatko nämä joku ongelma? Esim. biblionumberit 725435, 585249, 617792, 893908 ja 332183.

Tietueet eivät poistu bde-taulusta, vaan niiden deleted-sarakkeen arvoksi asetetaan 1.

**Comment by emta001** [comment]
Tämä on hieman jäänyt roikkumaan :D Mutta tosiaan, tälle asialle tuskin tarvitsee tehdä mitään, joten kehtaatko Tuomas sulkea tiketin? Avataan uudestaan, jos tarvis.

**Comment by Tuomas-Kyyti** [comment]
Suljen tämän, jos kerran kirjaimista luokan perässä ei varsinaisesti ole haittaa.
