### ISSUE TITLE
Nidetyyppien ylläpidossa omituinen luku

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#521]
### Mikä vikana?

Nidetyyppien ylläpidossa kauneusvirhe määrien näyttämisessä: Näytetään 1 - 010 / 18. Kun sitten valitsee isomman kenttämäärän kuin oletuksena oleva 10, kenttien määrä näkyy kuten kuuluukin. 

### Jotain muuta?

![2023kuvat 040](https://user-images.githubusercontent.com/73887264/234817529-43a28fb9-b611-4f80-802e-ceb684e972bf.png)

**Comment by emta001** [comment]
Toimiiko tämä näin siis sekä suomeksi että englanniksi?

**Comment by pknuuti** [comment]
Näyttää toimivan :D
![2023kuvat 041](https://user-images.githubusercontent.com/73887264/234818939-288727b3-67a7-4d2e-9880-789048d60ec2.png)

**Comment by emta001** [comment]
Vilkaisin uutta versiota, siellä ei näytä olevan tätä ongelmaa. Joten korjaantunee versionvaihdossa.

**Comment by pknuuti** [comment]
Tuo on siis nextillä!

**Comment by AnneliO** [comment]
Katsoinkin juuri, että nextillä ollaan, mutta mulla ei toistu siellä tuo ongelma. Lisäsitkö Päivi nidetyypin ja tuliko näkymä sen jälkeen tuollaiseksi?

**Comment by pknuuti** [comment]
Ei kun se oli, kun rupesin lisäämään, ei lisäämisen jälkeen. Kuvakaappaus otettu aamulla klo 8.24.

**Comment by AnneliO** [comment]
Mulla ei näy noin vaara-nextillä: 
![kuva](https://user-images.githubusercontent.com/33121325/234822918-3ee3a9a6-bf84-47e0-b0eb-d32c02bebff5.png)

Mitä jos päivität sivun ctrl+f5:lla niin pysyykö se edelleen omituisena?

**Comment by pknuuti** [comment]
Nyt näköjään näkyy oikein. Mikä lie härö ollut. Mutta näkyi siis myös englanniksi, joten omituista. Suljen tämän tiketin, koska ei aiheuta toimenpiteitä :D
