### ISSUE TITLE
Tietueen varaukset-sivulta puuttuu Ensimmäinen ja Viimeinen -linkit sivutuksesta

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#523]
### Mikä vikana?

[Varausjono-sivulla](https://vaara-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=11692301) puuttuu Ensimmäinen ja Viimeinen (First ja Last) -linkit sivutuksesta. Ne pitäisi näkyä Edellinen/Seuraava -linkkien vieressä.

![kuva](https://user-images.githubusercontent.com/33121325/235064796-b6a8baef-84f7-42c9-819b-735b7bf57a92.png)

### Jotain muuta?

Varaukset, varausjono, varasjonosivu, varaussivu, sivutus, navigaatio, navigointi

**Comment by emta001** [comment]
Tutkin tätä hieman yhdessä vaiheessa ja totesin, ettei tähän löydy oikein mitään fiksua ratkaisua. Muistaakseni tämä tuli jostain yhteisön patchista (liittyi Kohan uuteen ulkoasuun, siitä haluttiin "siisti") ja olisi vaatinut jonkin js-tiedoston käpistelyä. 

Ehdottaisin, että tämä yritetään katsoa kuntoon samalla kun tietueen varaus-sivua korjaillaan yhteisöä varten versionvaihdon yhteydessä. Ja jos siinä yhteydessä löytyy jokin helppo kikka korjata tämä nykyiseen versioon, niin tuodaan korjaus tuotantoon.

**Comment by emta001** [comment]
Siirrän tämän Lasselle, joka tutkii varaus-sivua uuteen versioon.

**Comment by lasse-koha** [comment]
Nexteillä testattavana varaussivun yhteisöversio johon lisätty sivutus ja nämä linkit.

**Comment by Kati-Helle** [comment]
Helle-nextissä linkit Ensimmäinen JA Seuraava näkyvät ja toimivat.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4375ffb2-9c76-4629-9afe-fe7a11e295e7)

**Comment by ajrajala** [comment]
Vaski-nextillä myös ok.

**Comment by AnneliO** [comment]
Liittyy [Koha-23.x #7](https://github.com/KohaSuomi/Koha-23x/issues/7), jossa päätettiin, että ylläpidetään vielä toistaiseksi meidän omaa sivutusta, koska yhteisön versio on liian hidas.

**Comment by lasse-koha** [comment]
Nämä linkit on nyt myös meidän versiossa.

**Comment by emta001** [comment]
Tähän jouduttiinkin tuomaan meidän oma versio. Tätä voisi testata uudelleen, että linkit näkyvät edelleen.

**Comment by pknuuti** [comment]
Toimii nextillä.
![2023kuvat 380](https://github.com/KohaSuomi/Koha/assets/73887264/d0045eb6-46ae-4b1f-b361-11790cefd186)

**Comment by Kati-Helle** [comment]
Helle-nextissäkin tietueen Varaukset-sivun linkit Ensimmäinen ja Viimeinen näkyvät edelleen ja toimivat.

**Comment by lasse-koha** [comment]
Testattu, suljen tiketin.
