### ISSUE TITLE
Osakohteiden päälle valunut väärät tiedot

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#527]
### Mikä vikana?

Vaskin paikalliskantaan on valunut TäTistä hiljattain kolmen eri osakohteen päälle väärät tiedot emmekä keksi selitystä miksi sillä osakohteilla ei muutoslokien perusteella näyttäisi entuudestaan olleen arvoja 020a/024a-kentissä joiden perusteella siirtoraportin mukaan valutuksen aktivointi on tapahtunut:

1. Osakohteen 4289652 (_No god before me_) päälle valui kirja _Kaikkien uskontojen jumala,_ valutuksen aktivointiarvona 020a-kenttä jossa arvona 9789518885231 (nid.)
2. Osakohteen 4289664 (_Felicidade_) päälle valui dvd _Independence day,_ valutuksen aktivointiarvona 024a-kenttä jossa arvona 7340112731526 (tietue jo poistettu)
3. Osakohteen 4289665 (_Cast your fate to the wind_) päälle valui kirja _Des chatons si mignons_, valutuksen aktivointiarvona 020a-kenttä jossa arvona 978-2-8212-1274-9

Tapaukset 2 ja 3 ovat saman emotietueen (4275865) osakohteita.

Keksisikö joku muu mitä näissä on käynyt?

**Comment by AnneliO** [comment]
1. esimerkin tietueen muutoslokien perusteella tietueessa ei ole ollut tuota 020a-kentän arvoa ennen valutusta. Tietue on tullut kantaan valutuksena 19.1.2023 klo 6.06 ja se on aktivoitu valutukseen 26.4.2023 klo 11.12. Se on valunut pian aktivoinnin jälkeen 26.4.2023 klo 11.17.  Jotain on nyt tapahtunut tuolloin 26.4.2023, mikä on aiheuttanut väärällä tiedolla aktivoinnin. Vaskin tietokannassa on  tuo _Kaikkien uskontojen jumala_ -tietue muutenkin olemassa, mutta se on aktivoitu 26.7.2021 035a-kentän arvolla, jota Tätistä ei löydy.

3. esimerkin tietue on tullut tietokantaan myöskin valutuksena samaan aikaan kuin 1. esimerkin tietue. Aktivoitu 28.4.2023 14:02:09 ja valutettu samana päivänä klo 14:07:23 väärällä aktivointiarvolla.

Täytyy kyllä sanoa, että en äkkiseltään ymmärrä, miten tällainen on voinut tapahtua.

**Comment by ajrajala** [comment]
Tiketissä raportoitujen tapausten jälkeen vastaavaan ongelmaan ei ole Vaskissa törmätty ja välissä on ollut versiopäivityskin. Suljen tiketin nyt tällä erää, mutta avataan uudelleen mikäli ongelma putkahtaa esille.
