### ISSUE TITLE
Tietueen perustietojen Julkaisutiedot-kohdan julkaisupaikan hakulinkki ei toimi oikein

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#533]
### Mikä vikana?

Tietueen perustietojen Julkaisutiedot-kohta
- julkaisupaikka-linkki ei toimi oikein
- julkaisupaikka-linkki on perustiedoissa vain silloin, kun tietueella on 260a-kenttä. Linkki puuttuu, kun tietueella on 264a-kenttä. 

Esimerkki julkaisutiedot-linkin toimimattomuudesta
Helle-tietueen (biblionumber 1598303) 260a-kenttäarvo
![kuva](https://user-images.githubusercontent.com/99952449/236998924-bb70caef-57cc-4592-b6e7-43e826d3bdc3.png)

Perustiedot-näyttöä
![kuva](https://user-images.githubusercontent.com/99952449/236999201-721bdc2f-759b-4f6f-b037-fcf5c7d1338e.png)

Perustietojen Julkaisutiedot-kohdan Helsinki-linkkiä klikatessa hakutuloksena tämä 
![kuva](https://user-images.githubusercontent.com/99952449/236999084-93adb3ac-cc5b-4e91-a33f-a289f041ab8c.png)

Tietueen perustietojen Julkaisutiedot-kohdan julkaisupaikka-linkki puuttuu, kun tietueella (esim. Helle-biblionumber 1602966) on 264a-kenttä 
![kuva](https://user-images.githubusercontent.com/99952449/236999746-01e10bcd-1fff-4fe8-ab89-2e2518cbbf14.png)

Vastaavat ominaisuudet ovat myös uudessa versiossa.

**Comment by AnneliO** [comment]
Tuonne pl-indeksiin on mäpätty vain 008_/15-17, missä ei varmastikaan ole tuon tyyppisiä tietoja. place-of-publication-indeksistä löytyy sekä 260a että 264a.

Sivupohjassa ei näköjään ole otettu huomioon uudempia luettelointisääntöjä ja linkit muodostetaan vain vanhojen sääntöjen mukaisesti 260-kentän perusteella.

**Comment by paxed** [comment]
264a:n merkitys muuttuu 2. indikaattorin mukaan - pitääkö hakuindeksin myös muuttua sen mukaan, vai haetaanko kaikki tuosta place-of-publication -indeksistä?

**Comment by AnttHeik** [comment]
Hei, minun mielestäni kaikki haetaan tuosta place-of-publication -indeksistä, koska mitään muitakaan vaihtoehtoja ei taida olla.

**Comment by paxed** [comment]
Tämä on nyt testeillä

**Comment by Kati-Helle** [comment]
Helle-testissä nyt näin:

Tietueella biblionumber=1577697 on 264-kenttä. 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5d5efa08-d4da-475c-81e3-70760bd2e056)

Julkaisupaikka-linkki on tietueen perustiedot-näytöllä 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5b6578be-0c30-4e53-9664-9f121768de09)

ja haku linkistä toimii
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4e3ca72b-426e-4b5e-8395-dd62048e88be)


Tietueella biblionumber=865802 on 260-kenttä. 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/842bf0f3-9cf7-475a-a262-2d1a6691efa0)

Tietueen perustiedoissa on julkaisupaikka-linkki 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/6361a5fe-d619-408e-9cf4-e1edf78139e4)

Hakutulos julkaisupaikka-linkistä = Ei hakutuloksia
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ab025163-72b6-4278-896f-47ecf4d5747f)

**Comment by AnttHeik** [comment]
OUTIn ja TäTin testeillä sama homma eli jos tieto on 260a-kentässä, niin haulla ei tule tuloksia. Muilla tavoilla näyttää toimivan.

@AnneliO Onko tosiaan niin, ettei Kohan indekseistä löydy vaihtoehtoja, jos 264-kentän 2. indikaattorin arvo vaihtuu eli kustantajalle, valmistajalle tai jakajalle ei löydy omia indeksejä, vaan kaikki on laitettava samaan 264:seen (place of provider tai provider)? Jotenkin hassua, kun tavallaan laittaa samoihin hakutuloksiin sekä kustantajan että valmistajan :)

**Comment by AnneliO** [comment]
Indeksin mäppäykset tehdään tähän tyyliin eikä siellä ole mahdollisuutta ilmoittaa indikaattoria:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/b7f7c66a-d750-4d27-93de-a94852206d68)

Yhteisön bögzillasta löytyy tällainen [yhdeksän vuotta vanhan tiketti indikaattoreihin liittyen](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=12813) (tosin Zebra ollut vielä tuolloin hakukoneena).

**Comment by AnttHeik** [comment]
Ok, voisikohan/olisikohan siinä kannatusta tökkiä tuota eteenpäin yhteisössä jotenkin? :)

**Comment by AnneliO** [comment]
Tuo on kyllä niin vanha tiketti ja vielä eri hakukoneelle, että en nyt ole varma.

**Comment by paxed** [comment]
Pitäisi varmaan tehdä uusi tiketti ja nimenomaan elasticille

**Comment by AnneliO** [comment]
Jos joku osaisi kirjoittaa tarkan kuvauksen siitä, mitä halutaan, niin voin kyllä lisätä sitten tiketin.

Eli oisko se jotain tyyliin (englanniksi toki):

Elasticsearchiin tarvitaan mahdollisuus tehdä indeksin mäppäyksiä MARC-kentän indikaattorin mukaan. Esim. 264c-kentän 2. indikaattorin arvo määrittelee, onko kyseessä kustantaja, valmistaja vai jakaja. Nämä toimijat pitäisi pystyä viemään eri indekseihin.

**Comment by AnttHeik** [comment]
Joo, jotenkin noin, paitsi että riittää "264-kentän 2. indikaattorin arvo..." ei tarvitse määrittää osakenttää.

Toisaalta mietin, että käytetyin haku tässä on varmaankin kustantaja tai julkaisija (2. ind. = 1), ja harvemmin se sekoittuu nimen perusteella valmistajaan (2. ind. = 3) tai jakajaan (2. ind. = 2). En tiedä, miten paljon sitten haetaan tietoa julkaisupaikan perusteella ja haluttaisiin ettei se sekoitu esim. valmistuspaikkakuntaan. Mutta toisaalta voi olla niinkin, että tulevaisuudessa indikaattoreilla määritetään muissakin kentissä tarkemmin eri asioita, jolloin olisi ihan perusteltua, että indikaattorit olisi mukana noissa indeksin mäppäysvaihtoehdoissa. En nyt heti keksi muita kenttiä joissa nämä olisi oleellisia.

**Comment by AnneliO** [comment]
Antin ja Katin mainitsemaan ongelmaan liittyen, jos julkaisijan paikka on 260a-kentässä, niin haku/linkki kohdistuu edelleen pl-indeksiin, ei place-of-publication-indeksiin.

Esim. https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1695155&searchid=scs_1695029833524

**Comment by AnneliO** [comment]
> Jos joku osaisi kirjoittaa tarkan kuvauksen siitä, mitä halutaan, niin voin kyllä lisätä sitten tiketin.
> 
> Eli oisko se jotain tyyliin (englanniksi toki):
> 
> Elasticsearchiin tarvitaan mahdollisuus tehdä indeksin mäppäyksiä MARC-kentän indikaattorin mukaan. Esim. 264c-kentän 2. indikaattorin arvo määrittelee, onko kyseessä kustantaja, valmistaja vai jakaja. Nämä toimijat pitäisi pystyä viemään eri indekseihin.

Tästä on nyt [bög 34816](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34816).

**Comment by Kati-Helle** [comment]
Tämä toimii nyt myös tuotannossa: Tietueen perustietojen Julkaisutiedot-kohdassa on toimiva julkaisupaikka-linkki, kun tietueella on 264a-kenttä. (Koha-päivitys 19.9.2023).

**Comment by AnneliO** [comment]
Jos nyt ymmärsin oikein, niin tiketin alkuperäinen ongelma on korjattu, joten voisiko tämän sulkea?

**Comment by Kati-Helle** [comment]
Suljen tiketin.
