### ISSUE TITLE
Erikoistilan poisto tiketin #465 niteille

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#534]
### Tukipyyntö

Tiketin #465 aputaulujen itemnumbereille pitäisi asettaa notforloan-arvoksi 0 maanantaina 15.5.

**Comment by ajrajala** [comment]
Varuilta huomiona vielä, että kahden ekan ajon jälkeen tehtiin vielä yksi täydentävä ajo, joten itemnumbereita kaikkiaan kolmessa aputaulussa:

- ks_20230411_itemnumbers1_gh465
- ks_20230411_itemnumbers2_gh465
- ks_20230412_itemnumbers_gh465

**Comment by emta001** [comment]
Tilat vaihdettu takaisin seuraavasti:

`update items set notforloan = 0 where notforloan = 4 and holdingbranch = "TUPK" and itemnumber in(select itemnumber from [aputaulu]);`

Käytin rajausta, koska muuten ajoissa kesti liian kauan mikä taas vaikutti jo Kohan toimintaan.

**Comment by ajrajala** [comment]
Kiitokset Emmi, erikoistila poistunut niteiltä eli tämä homma nyt paketissa.
