### ISSUE TITLE
Takaajatietojen siivous Vaarassa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#537]
### Tukipyyntö

Vaarassa on otettu käyttöön vain yksi takaajatyyppi: **vastuuhenkilö**. Kohan uuden version huomautuksissa: 
"Seuraavia arvoja käytetään takaaja/taattava-suhteena, mutta niitä ei ole olemassa 'borrowerRelationship' -järjestelmäasetuksessa:

    huoltaja
    isä
    äiti
    0

Jos suhde on haluttu, lisää se 'borrowerRelationship' -järjestelmäasetukseen, muutoin pyydä järjestelmän pääkäyttäjää korjaamaan tietokannan arvot borrowers.relationship ja/tai borrower_relationships.relationship."
Vaarasta pitäisi siis siivota pois nuo turhat arvot, kaikki huoltajat ovat nykyään vastuuhenkilöitä.

**Comment by emta001** [comment]
Arvot muutettu seuraavasti:

`update borrowers set relationship = "vastuuhenkilö" where relationship is not null and relationship != "vastuuhenkilö";`

`update borrower_relationships set relationship = "vastuuhenkilö" where relationship != "vastuuhenkilö";`

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
