### ISSUE TITLE
Puhelinnumeron tarkistus/tarpeettomien viestitäppien poisto -intranetUserJS-rimpsu: tekstiviestitäpät eivät tyhjene ensimmäisellä tallennuksella

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#538]
### Mikä vikana?

Asiakastietojen muokkauksessa tekstiviestitäpät jäävät päälle elementtien checked-muuttujien puuttumisen takia, kun intranetUserJS-rimpsu tiketistä https://github.com/KohaSuomi/Koha/issues/204 on käytössä.
Mikko Liimataista lainatakseni: "Huomasin, että noita checked-atribuutteja ei ole kuin vasta tallennuksen jälkeen muokatessa, joten noiden täppien poistaminen vaatii sen, että ne täpät on valittuna, kun menee muokkaukseen. Jos ei ole, niin täpät voi lisätä ja tallennus onnistuu. Jos tuohon saisi checked-atribuutin lisäyksen, kun viestiasetukseen laitetaan täppä, niin sitten tuo varmaan toimisi oikein."

### Mitä pitäisi tapahtua

Täppien tulisi poistua ennen asiakkaan lisäyksen/muokkauksen tallentamista, kun tiketin https://github.com/KohaSuomi/Koha/issues/204 rimpsu on käytössä.

**Comment by Kati-Helle** [comment]
Helle-testissä vaikuttaa toimivalta. Testasin lisäämällä uusia asiakastietoja.

Kun uudelta asiakastiedolta puuttuu sähköpostiosoite ja sähköpostiviesti-asetukset ovat valittuina, ilmoittaa Koha asiakastietoa tallentaessa:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/59ac175f-cfbc-4fc2-8f64-c98833078035)

Kun uudelta asiakastiedolta puuttuu tekstiviesti numeroon -arvo ja tekstiviesti-asetukset ovat valittuina, ilmoittaa Koha asiakastietoa tallentaessa:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/27da9d89-3e08-4143-8fb5-f874c54670c3)

Kun uudelta asiakastiedolta puuttuu tekstiviesti numeroon -arvo ja sähköpostiosoite JA tekstiviesti-asetukset ja sähköpotiviesti-asetukset ovat valittuina, ilmoittaa Koha asiakastietoa tallentaessa:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/3cdfdf7d-f13a-4b4c-ae97-21621c87d2e2)

Kaikissa tapauksissa asiakastiedossa ei ole tallennuksen jälkeen viestiasetuksia.

Helleen rimpsun saa laittaa käyttöön ajankohtana, jolloin pienestä käyttökatkosta on mahdollisimman vähän haittaa.

**Comment by velimarj** [comment]
Myös OUTIn testillä tuntuisi toimivan. Kokeilin sekä uudella että vanhalla ja aikuis- että lapsiasiakastyypeillä. Katin yllä mainitsemien lisäksi kokeilin vielä seuraavia:
- numero paikoilleen, sähköpostia ei ja ruksit molempiin = sähköpostitäppä poistui, tekstiviesti jäi
- sähköposti paikoilleen, numeroa ei ja ruksit molempiin = tekstiviestitäppä poistui, sähköposti jäi


Eli myös OUTIin voitaisiin ottaa, samalla tapaa sopivassa kohdassa.

**Comment by lmstrand** [comment]
Rimpsu lisätty Outin, Hellen ja Vaaran tuotantoon.

**Comment by Tuomas-Kyyti** [comment]
Testasin Kyytin testikannassa ja muuten toimi, mutta ennakkoilmoituksen tekstiviestiruksi jäi paikoilleen, vaikka puhelinnumeroa ei ollut määritetty. Onkohan niin, että Hellessä ja Outissa ei ole mahdollista ennakkoilmoitusta lähettää tekstiviestillä?

**Comment by AnneliO** [comment]
Ainakaan OUTIssa ei lähetetä ennakkoilmoituksia tekstiviestinä. Vain sähköpostilla.

**Comment by Tuomas-Kyyti** [comment]
Nyt tuntuu toimivan oikein Kyytin testillä.

**Comment by Kati-Helle** [comment]
> Ainakaan OUTIssa ei lähetetä ennakkoilmoituksia tekstiviestinä. Vain sähköpostilla.

Myös Hellessä ennakkoilmoitukset vain sähköpostitse.

**Comment by lmstrand** [comment]
Tämä rimpsu näköjään puuttui vielä tuotannosta kimpoilta Siili, Lumme, Kyyti ja Lappi. Lisään rimpsun jo yhtenäisyydenkin takia näillekin kimpoille jossain välissä iltasella, jonka jälkeen suljen tiketin.

**Comment by AnneliO** [comment]
Voisiko tämän tiketin sulkea? :)

**Comment by AnneliO** [comment]
Koska ei ole tullut kommentteja pariin kuukauteen, niin suljen tiketin.
