### ISSUE TITLE
Kausijulkaisujen vastaanotossa ei toimi viivakoodinmuodostus

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#539]
### Mikä vikana?

Kausijulkaisujen vastaanotossa ei toimi viivakoodinmuodostus. Viivakoodia ei muodostu kenttää klikkaamalla tai kolmesta pisteestä kentän perässä.

Ei toimi myöskään nextillä.

Marc-kuvailupohjissa kausijulkaisun kohdalla kaikki on niin kuin pitää ja viivakoodin muodostus toimii nidetiedoissa oikein. Eli ongelma on vain tuolla vastaanoton puolella.

**Comment by PiaKusmin** [comment]
Myöskään signumin muodostus ei toimi samaisessa paikassa.

**Comment by Hanna-Lumme** [comment]
Lumpeissa molemmat ongelmat myös.

**Comment by Tuomas-Kyyti** [comment]
Tämä on meillä suurin ongelma päivitykseen liittyvä. Lehtiä tulee päivittäin ja niitä ei nyt saa vastaanotettua eikä asiakkaitten saataville.

**Comment by LeenaKinnunen** [comment]
Lappi-testillä toimii oikein.

**Comment by Kati-Helle** [comment]
Helle-testillä toimii.

**Comment by pirliis** [comment]
OUTIn testillä kausijulkaisujen vastaanotossa viivakoodi muodostuu oikein kolmesta pisteestä ja signum muodostuu automaattisesti oikein.

**Comment by Hanna-Lumme** [comment]
Lumpeiden testillä toimii signumin ja viivakoodin muodostus oikein.

**Comment by pknuuti** [comment]
Vaaran testillä signum ei muodostu oikein, tulee vain luokka ja pääsanan kolme kirjainta, ei kirjastotunnusta. Viivakoodi muodostuu oikein.

**Comment by Kati-Helle** [comment]
Aiempi testaukseni koski vain viivakoodia. Testasin nyt vielä signumin muodostamisen.

Hellen testillä signum ei muodostu liitännäisellä oikein. Signumin alusta jää uupumaan hyllypaikka. Käytössä liitännäinen:
loc_ccode_084a_mainheading_signum_builder.pl

(Hellessä signumit muodostuvat vastaanotettavalle kausijulkaisutilaukselle automaattisesti kausijulkaisutilauksesta. Poistin testausta varten niteen signumin.)

**Comment by AnneliO** [comment]
Huomaattehan, että tämä tiketti koskee viivakoodin muodostamista, signumien osalta on omat tikettinsä. :)

**Comment by ajrajala** [comment]
Vaskissa tuli sellainen palaute viivakoodin muodostamisesta, että ennen versiopäivitystä generointi tapahtui vain kolmeä pistettä klikkaamalla ja nyt jo itse kenttää klikatessa. Lehdissä käytetään siis ilmeisesti vielä suht paljon valmiita viivakooditarroja ja sen vuoksi vanhaa toimintalogiikkaa pidettiin parempana.

Suurena ongelmana en tätä osaa nähdä, kun generoidun viivakoodin tilalle voi kuitenkin lukea uuden viivakoodin tarrasta. Mutta tuon palautteen nyt kuitenkin esille ja kysyn mitä mieltä muut tästä olette?

**Comment by Kati-Helle** [comment]
Kannatan tapaa, jossa viivakoodin gerenointia ei tapahdu viivakoodi-kenttää klikatessa. Eli vanhan version toimintalogiikan käyttöönottoa, jos se vain on mahdollista.

**Comment by Tuomas-Kyyti** [comment]
Niiden kirjastojen kannalta, jotka käyttävät Kohan viivakoodeja, on ihan hyvä, että viivakoodi muodostuu kenttää klikkaamalla. Sama toiminnallisuus on niteiden muokkauksessakin.

**Comment by Kati-Helle** [comment]
> Niiden kirjastojen kannalta, jotka käyttävät Kohan viivakoodeja, on ihan hyvä, että viivakoodi muodostuu kenttää klikkaamalla. Sama toiminnallisuus on niteiden muokkauksessakin.

Totta. Sen sijaan niissä kirjastoissa joissa ei käytetä Koha-viivakoodeja, tulee kentän klikkauksesta muodostunut arvo aina poistaa (tai ainakin maalata) ennen kuin lisää kenttään valmiin viivakooditarran arvon.
Vai olisiko tuohon joku muu tapa, jossa tarpeetonta arvoa ei tarvitse poistaa viivakooditarran arvoa lisätessä?

Viivakoodi-kenttä kentän klikkauksen jälkeen, kursori jää vilkkuman automaattisesti muodostuneen arvon jälkeen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ce8ebfe1-f409-4487-b41d-ceb6c356763f)

**Comment by AnneliO** [comment]
Voiko tämän tiketin sulkea?

**Comment by PiaKusmin** [comment]
Uskoisin näin. Miepä suljen. Jos jollain on vielä lisättävää niin avataan uudestaan.
