### ISSUE TITLE
Päivitä Elasticsearch -indeksi rivien siivoaminen taustatöistä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#541]
### Tukipyyntö

Taustatöihin muodostuu uuden version myös runsaasti "Päivitä Elasticsearch indeksi" -rivejä. Keskusteltu Matrixissa 17.5.2023, että työjonon tyhjentämisaikataulua pitäisi miettiä vähän uudelleen tämän muutoksen vuoksi. Ko. rivit voisi mahdollisesti siivota pois jopa päivittäin.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 25.5.2023: Tehdään siivousskripti, joka poistaa Päivitä Elasticsearch indeksi -rivit päivittäin.

**Comment by lmstrand** [comment]
Muutos tehty tiketin https://github.com/KohaSuomi/Koha/issues/618 mukaisesti, suljen tämän tiketin.
