### ISSUE TITLE
Lumme: Nide ei mene kuljetettavana-tilaan

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#542]
### Mikä vikana?

Lumpeissa ei niteet mene oikein kuljetettavana-tilaan. Tällainen viesti tuli virkailijalta, joka asiaa kokeili:

_"Yhteen kirjaan tein uuden siirronkin, jotta varmasti on menossa toiseen kirjastoon, mutta Koha ei näytä siirtoa/kuljetuksessa olevana.  Myös varattu kirja, joka on menossa Pertunmaalle, näkyy edelleen vain paikalla olevana Mikkelissä, ei kuljetuksessa."_

### Mitä pitäisi tapahtua

Niteen tila pitäisi näkyä kuljetettavana-tilassa, kun nide on matkalla muuhun kirjastoon joko varauksen tai siirron kautta.

**Comment by AnneliO** [comment]
Olisiko sulla esimerkkejä niteistä, jotka eivät mene kuljetettavaksi?

**Comment by AnneliO** [comment]
Ainakin [Vastaanotettavat kuljetukset](https://lumme.koha-suomi.fi/cgi-bin/koha/circ/transferstoreceive.pl) -sivulla on tänään kuljetukseen menneitä niteitä.
