### ISSUE TITLE
Turhat RabbitMQ-varoitukset

### ISSUE THREAD

**Issue by lasse-koha** [KohaSuomi/Koha#543]
### Kehitysehdotukseni

Kohan background_jobs_worker yrittää yhdistää RabbitMQ:hun jota meillä ei ole käytössä. Tästä tulee lokeihin runsaasti turhia varoituksia.

**Comment by AnneliO** [comment]
Testisuunnitelma:

1. Testaa, että taustatyöt toimivat normaalisti.

**Comment by lasse-koha** [comment]
Testattu ja tuotannossa.
