### ISSUE TITLE
Tietueen niteiden järjestäminen lehtinumeroinnin mukaan ei toimi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#544]
### Mikä vikana?

Tietueen Kokoelmat-välilehdellä on mahdollista järjestellä niteitä valitun sarakkeen perusteella. Järjestäminen näyttäisi muuten toimivan, mutta sarakkeen Kausijulkaisujen numerointi mukaan järjestäminen ei vaikuttaisi tekevän mitään.

### Kuinka toistaa ongelma/asia

1. Hae lehtitietue, jolla eri numeroiden niteitä
2. Järjestele hakutulos esim. Kotikirjaston mukaan, havaitse että järjestäminen toimii
3. Järjestele hakutulos sen jälkeen sarakkeen Kausijulkaisun numerointi mukaan, havaitse ettei mitään tapahdu

**Comment by Hanna-Lumme** [comment]
Lumpeissa samaa ongelmaa.

**Comment by AnneliO** [comment]
Testasin tätä Bywaterin sandboxissa ja siellä Kausijulkaisujen numerointi -sarakkeen mukaan järjestely toimii.

**Comment by lmstrand** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32447
Yhteisön tiketissä on korjauksia tuohon näkymään liittyen, vaikkei juuri tuota saraketta mainita. Voisi kokeilla, josko tuo patch / nuo patchit korjaavat ongelman.

**Comment by lmstrand** [comment]
Siili-testillä toimii sarakkeen Kausijulkaisujen numerointi mukaan järjestäminen.

**Comment by pknuuti** [comment]
Vaarassa ei toimi järjestäminen numerointisarakkeen mukaan.

**Comment by ajrajala** [comment]
Lari huomasi, että ongelma koskee vain tapauksia, joissa numerointi ei ole pelkästään numeerinen. Testasin tätä vielä vaski-testillä luomalla lehtiniteitä, joilla numerointina 1, 2, 3 jne. Järjestäminen numeron mukaan näyttää tällöin tosiaan toimivan:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/0f2e13d7-e5d6-44d8-a2cf-33f4d62d1f1c)

**Comment by pknuuti** [comment]
Ainakin Vaarassa numerointi menee vuosiluku : numero -tyyliin (2023 : 22) eli vuosiluvun ja numeron välissä on tyhjämerkki kaksoispiste tyhjämerkki. Ehkäpä tuonkin saisi järjestymään oikein?

**Comment by Kati-Helle** [comment]
Hellessä tietueen perustiedoissa Kausijulkaisun numerointi -kentän järjestely ei toimi. Sen sijaan tietueen varauksissa toimii.
Kausijulkaisunumerointi tyyliin:
2023 1

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2ee6e146-db20-46df-9ec9-15171d55e3a6)

**Comment by lmstrand** [comment]
Yhteisön tikettien https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33037 ja https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32555 patchit näyttäisivät korjaavan ongelman.
Korjaukset on tuotu testeille tilapäisesti (ei vielä feature branchissa).

**Comment by lmstrand** [comment]
Korjaukset vain englanninkielisellä näkymällä.

**Comment by piiaseme** [comment]
Korjaus toimii OUTIn testillä.

**Comment by ajrajala** [comment]
Lisäksi ainakin meillä on jossain vaiheessa noihin saatavuustietonäkymiin ilmestynyt ilmestymispäivämäärät numerointitiedon perään. Päivämäärä näkyy siis nimenomaan tuolla saatavuustiedoissa, mutta ei numerointikentässä jos nidettä menee muokkaamaan. Koha ei siis kuitenkaan osaa järjestää numeroita "2023 : 1" ja "2023 : 1 (01.01.2023)" perätysten. Noita tapauksia ei tainnut testiympäristössä olla ollenkaan, kun tuota päivämäärää ei ole numerointitiedon perään aina tullut. Olisikin itse asiassa parempi, että päivämäärää ei tuonne tulisi ollenkaan, mutta en tiedä pystyykö tuohon suoraan millään asetuksella vaikuttamaan?

![Image](https://github.com/KohaSuomi/Koha/assets/44638512/cdc0fb10-f4c8-451b-8a41-ce11186bf1b5)

**Comment by emta001** [comment]
Muutos on viety tuotantoon viikon 24 päivityksessä, mutta kommenteista päätellen tämä vaatiikin vielä hieman työtä. Asetan tilaksi "Tehtävä" ja Lari voinee vilkaista tätä kunhan palaa lomilta.

**Comment by lmstrand** [comment]
Yhteisössä pohditaan mm. numeerista järjestelyä follow-up -tiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=25395.

**Comment by lmstrand** [comment]
Päivämäärän saa poistettua ja ehkä jättää myös ulos järjesteltävästä datasta ilman, että tietoa tarvitsisi piilottaa (jos sen näkyminen tarpeelliseksi koetaan). Tein testeille muutoksen englanninkieliseen Kohaan, jossa poistin sarakkeesta koko päivämäärätiedon ja järjestelysäännön, jolloin nuo Vaskin päivämäärättömät ja päivämäärälliset tapaukset pitäisi järjestyä peräkkäin. Tuohon "aakkostyyliin" numerointitietojen järjestymiseen ei löydy vielä lääkettä yhteisöstäkään.

**Comment by Kati-Helle** [comment]
Hellessä on samaa kuin Vaskissa, eli lehtitietue-niteiden saatavuustietonäkymään on ilmaantunut ilmestymispäivämääriä numerointitiedon perään (ei kuitenkaan kaikille niteille). Niteen muokkausnäytöllä ilmestymispäivämäärää ei ole.

Englanninkielisessä Helle-testissä päivämäärätietoja edelleen näkyy (tietueen biblionumber=1559309 nidetietoja)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5905c58f-e632-4b42-90c3-ef98d6897c44)

**Comment by lmstrand** [comment]
muutokset detail.tt -templateen siis (poistettu/muutettu):

                        [% IF itemdata_publisheddate #If there is at least one published date, use it for sorting %]
                            <td class="enumchron" data-order="[% serial.publisheddate | html %]">
                        [% ELSE %]
                            <td class="enumchron">
                        [% END %]



                                [% IF serial.publisheddate %]
                                    <span class="pubdate">([% serial.publisheddate | $KohaDates %])</span>
                                [% END %]

**Comment by pknuuti** [comment]
Serial enumeration-sarakkeen mukaan järjestettynä Vaaran testillä numerot eivät mene oikeaan järjestykseen, vaan 2015 : 19 jälkeen tulee 2015 : 2 ja sitten 2015 : 20, 2015 : 21 jne.
En löytänyt lehtinumeroita, missä olisi päivämäärä lisänä.

**Comment by piiaseme** [comment]
OUTIssa numerot menivät suomenkielisellä sivulla (jossa näkyy pvm) oikeaan järjestykseen. 

Enkunkielisellä sivulla (jossa ei näy pvm) numerointi menee esim. seuraavasti 
2019 : 1-2 
2019 : 10
2019 : 11
2019 : 3
2019 : 4
etc

OUTIssa taitaa olla ihan järestään sillä tavalla, että pvm näkyy vain suomenkielisellä puolella, en löytänyt yhtään päivämäärällistä englanninkieliseltä puolelta.

**Comment by pknuuti** [comment]
No enpäs hoksannut, että olisi pitänyt etsiä suomenkieliseltä puolelta noita päivämääriä. Kiitos Piia hoksautuksesta! Vaarassakin menee päivämäärälliset ihan oikeaan järjestykseen, mutta en keksi mitään syytä miksi päivämäärien pitäisi olla tuossa numerosarakkeessa. Kaikissa numeroissa näytti Vaaran testillä olevan päivämäärä (suomenkielisellä puolella :))

**Comment by lmstrand** [comment]
Tuolla päivämäärän poistolla yritin siis korjata tämän Annin ongelman Vaskissa:
"Koha ei siis kuitenkaan osaa järjestää numeroita "2023 : 1" ja "2023 : 1 (01.01.2023)" perätysten." https://github.com/KohaSuomi/Koha/issues/544#issuecomment-1588763324
Jos tuo ongelma ei tuolla enkunkielisellä puolella ole korjautunut (nide, jossa päivämäärä nyt piilotettu päätyy järjestyksessä edelleen erilleen listan loppuun) eikä siitä ole muutenkaan hyötyä, niin unohdetaan tuo muutos ja annetaan päivämäärien näkyä.

**Comment by Kati-Helle** [comment]
> Poistin nuo päivämäärät uudelleen testeiltä englanninkielisestä Kohasta (muutos katosi testien päivityksen yhteydessä), mutta jotenkin hassusti tuonne silti eksyy ainakin tuon helle-testin biblionumber=1559309 nidetietojen väliin väärin järjestyneitä yksittäisiä kappaleita esim. "2021 1" löytyy tuolta listan loppupäästä jostain, vaikka pitäisi olla ylimpänä muiden "2021 1" niteiden joukossa. Onkohan tästä päivämäärien poistamisesta nyt mitään hyötyä loppujenlopuksi. No testailkaa noiden tuntemienne tapausten kanssa ja kommentoikaa onko järkeä harkita muutoksen tuomista tuotantoon.

Voisikohan Helle-testin erikoisuus liittyä siihen, kun niteiden enumchron-kentän alussa saattaa olla virheellisesti ylimääräinen tyhjämerkki. Tietueen biblionumber=1559309 niteiden raporttihaun hakutuloksen arvoja:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/768cdc90-e07f-4c15-a458-16d9b7cb4498)

**Comment by AnneliO** [comment]
Minun muistin mukaan tuo päivämäärä on ollut näkyvissä "aina", jos numero on otettu "asianmukaisesti" vastaan saapumisvalvonnassa. Se on muistaakseni kausijulkaisunumeron vastaanottopäivä.

@Kati-Helle ylimääräiset välilyönnit missä tahansa kohtaa numerointia voi vaikuttaa järjestäytymiseen. Meillä on kyllä JS-rimpsuja, jotka poistavat niitä, mutta oiskohan nyt, ettei ne toimi tuossa kentässä kausijulkaisujen vastaanotossa.. 🤔

**Comment by Kati-Helle** [comment]
> Minun muistin mukaan tuo päivämäärä on ollut näkyvissä "aina", jos numero on otettu "asianmukaisesti" vastaan saapumisvalvonnassa. Se on muistaakseni kausijulkaisunumeron vastaanottopäivä.
> 
> @Kati-Helle ylimääräiset välilyönnit missä tahansa kohtaa numerointia voi vaikuttaa järjestäytymiseen. Meillä on kyllä JS-rimpsuja, jotka poistavat niitä, mutta oiskohan nyt, ettei ne toimi tuossa kentässä kausijulkaisujen vastaanotossa.. 🤔

Hellessä käytössä tämä JS-rimpsu:

/* Poista kausijulkaisun vastaanottonäytön kentistä välilyönnit alusta, lopusta ja useammat peräkkäiset välilyönnit välistä*/
$(document).ready(function() {
  $('body#ser_serials-edit.ser input').blur(function() {
     var tmp = $(this).val();
     tmp = tmp.replace(/^ +/, '');
     tmp = tmp.replace(/ +$/, '');
     tmp = tmp.replace(/  */g, ' ');
     tmp = tmp.replace(/(^[1-2][0-9]{3}) *: */, '$1 : ');
     $(this).val(tmp);
  });
});

**Comment by lmstrand** [comment]
```
$( document ).ready(function() {
if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') {
        $(".enum").text(function (i, text) {
    return text.trim();
});
}
});
```

Tämä rimpsu poistaa ylimääräiset alussa (ja lopussa) olevat välilyönnit numeroinneista kun tuo tietuenäyttö ladataan. Se näytti ainakin purevan tuohon Hellen tapaukseen (kun niteiden enumchron-kentän alussa saattaa olla virheellisesti ylimääräinen tyhjämerkki). Toki nuohan olisi hyvä olla kunnossa jo tietokannassa. Jätin rimpsun ensimmäiseksi Helle-testille intranetUserJS:ään.

**Comment by AnneliO** [comment]
Meillä on js-rimpsu, joka [poistaa ylimääräiset välilyönnit kausijulkaisujen vastaanotossa](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#poistetaan-ylim%C3%A4%C3%A4r%C3%A4iset-v%C3%A4lily%C3%B6nnit-kausijulkaisujen-vastaantotossa), mutta onkohan nyt niin, että se ei toimi aina?

**Comment by lmstrand** [comment]
Väsäsin tällaisen js-rimpsun joka lisää lehtinumeron eteen nollan, jolloin järjestäminen toimii loogisemmin numeroinnin mukaisesti (ainakin suurimmassa osassa tapauksia). Rimpsu myös siivoaa ylimääräiset välilyönnit pois, jotka voivat haitata järjestämistä numeroinnin mukaan.

```
/* Lisää nolla lehtinumeroihin 0-9, jotta lehtinumeroinnin mukaan järjestäminen toimii "numeerisemmin" */
$(document).ready(function() {
    if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') {
        $(".enum").text(function(i, text) {
            text = text.trim();
            if (text.charAt(text.length - 2) == " ") {
                if (text.charAt(text.length - 1) >= '0' && (text.charAt(text.length - 1) <= '9')) {
                    var insert = '0';
                    var position = text.length - 1;

                    var result = [
                        text.slice(0, position),
                        insert,
                        text.slice(position),
                    ].join('');
                    return result;
                }
            }
            return text;
        });
    }
});

```
Jätin rimpsun Helle-testille intranetuserJS:ään ensimmäiseksi.

**Comment by ajrajala** [comment]
Nollan lisääminen puree kyllä noihin tapauksiin, joissa meillä numerot 1 ja 10 järjestyi perätysten eikä numeerisesti oikein. Nämä tapaukset on siis käsin (ei kausijulkaisujen saapumisvalvonnan kautta) lisättyjä tai Aurorasta siirtyneitä niteitä. Kausijulkaisujen saapumisvalvonnan kautta lisätyt niteet järjestyvät tosiaan joka tapauksessa ennen/jälkeen noita käsin lisättyjä päivämäärän mukaisesti (oli päivämäärä piilotettuna tai ei).

Meillä näkyy olevan se tilanne, että tietyt kirjastot eivät ole missään vaiheessa Kohan aikana alkaneet käyttää kausijulkaisujen saapumisvalvontaa vaan lisäävät niteet aina käsin. Eli niin kauan kun Vaskissa ei käsitellä yhtenäisellä tavalla lehtiä, ei tuota numeerista järjestämistä taida saada meillä täydellisesti toimimaan.

Voisin jättää tuon "lisää nolla" -korjauksen Vaskin osalta toistaiseksi hautumaan. Ensisijaisesti järkevintä olisi ehkä saada meille muutos toimintatapaan ja lehtien käsittely yhtenäistettyä, silloin numerot järjestyisivät kutakuinkin oikein jos ne kaikki olisivat käsitelty saapumisvalvonnassa ja saaneet sieltä päivämäärän. Iso osa lehtien vanhoista vuosikerroista menee aina poistoon, joten käsin lisättyjen lehtien aiheuttamat ongelmat numeroiden mukaisessa järjestelyssä olisi minun arvion mukaan pikku hiljaa häviävä ongelma jos Vaski saa toimintakäytäntönsä yhtenäistettyä.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä tätä muutosta. Numerot 1-9 järjestyivät pääsääntöisesti oikein, mutta listauksen edetessä ilmeni omituisia järjestelyvirheitä kuten osa 2021 : 15 numeroista oli ennen 2021 : 14 numeroita ja sitten jatkui 2021 : 16. Myös listaa eteenpäin selatessa toistui vastaava virhe muutamaan kertaan. En keksi syytä. Tein haun vuoden 2021 TM-lehdistä, joita hakutuloksen mukaan 682. 
Ihan alkuun tuli pari 2-alkuista numeroa, siitä kuva.
![2023kuvat 111](https://github.com/KohaSuomi/Koha/assets/73887264/e0d62bf0-3711-4378-8d2f-751243de0df6)

**Comment by ajrajala** [comment]
> Testasin Vaaran testillä tätä muutosta. Numerot 1-9 järjestyivät pääsääntöisesti oikein, mutta listauksen edetessä ilmeni omituisia järjestelyvirheitä kuten osa 2021 : 15 numeroista oli ennen 2021 : 14 numeroita ja sitten jatkui 2021 : 16. Myös listaa eteenpäin selatessa toistui vastaava virhe muutamaan kertaan. En keksi syytä. Tein haun vuoden 2021 TM-lehdistä, joita hakutuloksen mukaan 682. Ihan alkuun tuli pari 2-alkuista numeroa, siitä kuva.

Selittyisikö järjestelyvirheet sillä, että numeroita on vastaanotettu kausijulkaisujen saapumisvalvonnassa vähän eri aikoihin? Ainakin meidän testillä katsellessani tulin siihen lopputulokseen, että nuo kausijulkaisujen kautta saapuneeksi merkityt järjestyvät päivämäärän eikä varsinaisen numeron mukaan. 🤔

**Comment by lmstrand** [comment]
Sitten on tuo vaihtoehto, ettei vastaanottopäivämääriä tuotaisi ollenkaan noihin kenttiin. Vaatisi pienen koodimuutoksen.

**Comment by lmstrand** [comment]
Tai jos päivämäärät ovat aina sulkujen sisällä, päivämäärien tiputtaminen onnistuisi aika helpostikin tuossa js-rimpsussa ihan.

**Comment by ajrajala** [comment]
Päivämäärien pois jättäminen kuulostaisi minusta kannatettavalta, en keksi niille käyttötarvetta saatavuustietonäytöllä ja tosiaan sotkevat numeron mukaisen järjestämisen jos numeroita saapuu vaikka jälkikäteen myöhässä tms. Mutta pitäisiköhän tästä vaihtaa vaikka ensi tiistain pääkäyttäjäpalaverissa sananen, mitä @AnneliO sanot?

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 8.8.2023: Kokeillaan js:llä tehty päivämääräpiilotus ja sen jälkeen testataan, tarvitaanko lisäksi nollan lisäys numeroihin 1-9.

**Comment by lmstrand** [comment]
Pelkän julkaisupäivämäärän piilotus:
```
$(document).ready(function() {
    if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') {
        $(".pubdate").hide();
    }
});
```
Julkaisupäivämäärän piilotus ja nollan lisäys numeroihin 0-9:
```
/* Piilota julkaisupvm, siivoa välilyönnit ja lisää nolla lehtinumeroihin 0-9, jotta lehtinumeroinnin mukaan järjestäminen toimii */
$(document).ready(function() {
    if (window.location.pathname == '/cgi-bin/koha/catalogue/detail.pl') {
        $(".pubdate").hide();
        $(".enum").text(function(i, text) {
            text = text.trim();
            if (text.charAt(text.length - 2) == " ") {
                if (text.charAt(text.length - 1) >= '0' && (text.charAt(text.length - 1) <= '9')) {
                    var insert = '0';
                    var position = text.length - 1;
                    var result = [
                        text.slice(0, position),
                        insert,
                        text.slice(position),
                    ].join('');
                    return result;
                }
            }
            return text;
        });
    }
});
```

**Comment by lmstrand** [comment]
Hmmm oman testini mukaan tuo järjesteleminen ei onnistu pelkän javascript-rimpsulla piilottamisen avulla. Englanninkielisessä templatessa on tehty koodimuutoksella julkaisupäivämäärän poisto testeillä. Sillä tapaa julkaisupäivämäärän poiston jälkeen järjesteleminen lehtinumeron mukaan näyttäisi toimivan ok (nollien lisäysrimpsun kanssa).

**Comment by pknuuti** [comment]
Vaaran testillä näyttäisi toimivan englanninkielisenä nyt oikein hyvin. Virheellisesti järjestyy vain käyttäjän virheellisesti kirjaamat lehtinumerot (tallennettu ilman tarpeellisia välilyöntejä kaksoispisteen molemmin puolin).

**Comment by paxed** [comment]
Taulu on Javascriptin DataTable, jonka tiedot ladataan asynkronisesti kohan APIn kautta, eli tuon document.ready laukaistaan siinä vaiheessa kun sivu on valmis, mutta siinä vaiheessa datatable on vielä latailemassa dataa. Eli pitäisi kattoa et se taulu on valmis. Esim. https://stackoverflow.com/questions/60542015/check-when-datatables-finished-rendering

**Comment by AnneliO** [comment]
Tutkimme ja pohdimme tätä tämän päivän (10.8.2023) Koha-Suomen palaverissa järjestäytymistä vielä vähän lisää ja tässä huomioita:

* kausijulkaisun numerointi (esim. 2023 : 1) ei ole numeerinen tieto vaan merkkijono, joka sisältää numeroita ja :-merkin (suurimmalla osalla kimpoista) sekä välilyöntejä, joten sen järjestäminen numeerisesti on mahdotonta.
  * numerointi voi olla myös esim. "Vol. 12, No. 3", mitä myöskään ei pysty numeerisesti järjestämään.
* sulkeissa oleva päivämäärä on julkaisupäivä, ei niteen vastaanottopäivä. Julkaisupäivä näkyy kausijulkaisun vastaanotossa Julkaistu-sarakkeessa: 
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/cd282ede-8d75-4663-b58a-4d4a79f7e066)
  * Julkaistu-kenttään tulee arvioitu julkaisemispäivä sen mukaan, mikä numerointikaava tilaukselle on valittu (ja luultavasti myös tilauksen alku- ja loppupvm vaikuttaa)
* ainoa varmasti oikein järjestyvä tapa on järjestää niteet tuon julkaisupäivän mukaan eli olisi tärkeää, että
  * käytetään saapumisvalvontaa, jolloin julkaisupäivä syntyy
  * numeroa vastaanotettaessa julkaisupäivän oikeellisuus tarkistetaan, jotta se asettuu kokoelma-taulussa oikeaan kohtaan. Varsinkin reklamoiduilla, myöhässä tulleilla kyseinen päivä kannattaa tarkistaa, jotta numero osuu järjestyksessä oikeaan kohtaan. 
* yhteisöstä poikkeavia template-muutoksia ei mielellään tehdä, koska ne ovat sitten Koha-Suomi-spesifejä muutoksia. Ensisijaisesti järjestettävä data pitäisi saada siihen kuntoon, että Koha pystyy nykyisillä toiminnoillaan tiedot järjestämään "oikein".

**Comment by janPasi** [comment]
Keskustelimme tästä Koha-Suomen kehittäjäpalaverissa 10.8., jossa läsnä oli myös Ari.

Numeroinnin mukaan järjestäminen on hieman ongelmallista, koska kausijulkaisujen numerointitapoja on monenlaisia ja kentässä voi periaatteessa lukea ihan mitä tahansa. Esimerkiksi "Volume 151 number XI". Suomalaisissa kirjastoissa tapa on pitkälti standardoitu, mutta samaa ei ikävä kyllä voi sanoa tilanteesta maailmalla.

Testiemme perusteella näyttäisi siltä, että jos kentässä on mukana julkaisupäivä niin järjestäminen toimii oikein. Se on tässä nähdäksemme melkolailla ainoa tapa, jolla lehtinumerot voi ylipäätään saada luotettavasti kronologiseen järjestykseen numerointitavasta riippumatta. Julkaisupäivä kirjautuu tilauksen numerotietoon oikein kun kausijulkaisujen numerot otetaan vastaan Kohan kausijulkaisujen hallinnan kautta.

Päätimme, että emme toteuta muutoksia järjestämiseen tässä vaiheessa, koska:

1) Aiottu korjaus ei toimi luotettavasti kuin yhdellä numerointitavalla.
2) Muutos ei tule kelpaamaan Koha-yhteisölle, joka lisäisi tarpeettomasti ylläpitokuormaa täällä meidän päässä.
3) Nollan lisääminen liittymässä numerotiedon eteen aiheuttaa sen, ettei liittymän esittämä tieto enää vastaa tietokantaan tallennettua tietoa, joka on tilanne jonka haluamme välttää.
4) Numerolistaa voi nykyisellään suodattaa sivun filtteröintitoiminnallisuudella (joka auttaa varmasti oikean numeron löytämisessä) ja testiemme mukaan aiotut muutokset aiheuttaisivat sen etteivät sivun filtteröintiominaisuudet enää toimisi oikein.
5) Järjestysongelma vaikuttaisi olevan ratkaistavissa yksinkertaisesti käyttämällä Kohan kausijulkaisujen hallintaa siten kuin sitä on tarkoitus käyttää.

**Comment by ajrajala** [comment]
Tämä on järkevä päätös, asia ei tosiaan ollutkaan niin yksioikoinen mitä äkkiseltään ajatteli. Vaskissa yritetään saada loputkin kirjastot käyttämään kausijulkaisujen hallintaa ensi vuoden alusta lähtien.

Suljen tiketin, kun tähän ei varmaan enempää lisättävää ole.

**Comment by janPasi** [comment]
Jaa, näköjään kommentoimme @AnneliO kanssa samat asiat, mutta toistossahan on tunnetusti tehoa :D
