### ISSUE TITLE
MAPK-yksikön voimassa olevien varausten keskeytys määräajaksi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#545]
### Tukipyyntö

Maskun kirjaston kiinniolon takia pitäisi keskeyttää varaukset, jotka täyttävät nämä ehdot:

- branchcode = MAPK
- varaus ei ole vielä jäänyt kiinni (found = null)
- varaus ei ole entuudestaan keskeytetty (suspend = 0)

Keskeytykseen pitäisi asettaa määräajaksi 26.5.2022-14.8.2023 ja muutoksen saisi tehdä 26.5.

**Comment by paxed** [comment]
Muutos tehty, koski 590 varausta.

`update reserves set suspend=1, suspend_until="2023-08-14 00:00:00" where branchcode='MAPK' and found is null and suspend=0;`

**Comment by ajrajala** [comment]
Saako vielä muutettua suspend_until kellonajaksi 23:59:59, jotta varaukset pysyisi koko 14.8. ajan vielä keskeytettyinä? En hoksannut tätä riittävän tarkasti sanoa, näköjään olin kuvitellut että keskeytys on vaan päivän tarkkuudella määriteltynä.

**Comment by paxed** [comment]
Muutettu, tällä:

`update reserves set suspend_until="2023-08-14 23:59:59" where branchcode='MAPK' and found is null and suspend=1 and suspend_until="2023-08-14 00:00:00";`

**Comment by ajrajala** [comment]
Hienoa, kiitokset! Täytyy vastaisuudessa muistaa määritellä päättymisen kesto vähän selkeämmin tikettiin.
