### ISSUE TITLE
Raportti noutamattomista hyllyvarauksista ei toimi versionvaihdon jälkeen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#547]
### Tukipyyntö

Vaarassa on raportti noutamattomista varauksista:

select othernames as 'Varaustunnus', b.title as 'Teos', i.barcode as 'Viivakoodi', bi.itemtype as 'Aineistotyyppi'
from old_reserves o
JOIN biblio b using (biblionumber)
JOIN biblioitems bi using (biblionumber)
JOIN borrowers using (borrowernumber)
JOIN items i using (itemnumber)
where o.branchcode=<<Valitse kirjasto|branches>>
and o.cancellationdate between <<Vanhentumispäivä alkaen|date>> AND <<Päättyen|date>>
and o.found='W'
AND o.expirationdate = (o.cancellationdate - INTERVAL 1 DAY)
order by 1,2

Se ei toimi, koska varaustunnussarakkeeseen ei tule mitään tietoa ja se on todella olennainen tieto tässä raportissa. Kokeilin korjata raporttia vaihtamalla othernamesin tilalle HOLDID, mutta saan virheilmoituksen 

 Virheitä:
Tietokannassa tapahtui virhe:
Unknown column 'HOLDID' in 'field list'
Tarkista loki lisätietoja varten.
Palaa edelliselle sivulle

Tätä en osaa korjata. Tämä raportti pitäisi saada pikaisesti kuntoon.

**Comment by AnneliO** [comment]
Muokkasin Vaarassa raporttia 656 ja se pitäisi nyt toimia. Korjattu kysely menee näin:

```
select ba.attribute as 'Varaustunnus', b.title as 'Teos', i.barcode as 'Viivakoodi', bi.itemtype as 'Aineistotyyppi'
from old_reserves o
LEFT JOIN borrower_attributes ba ON (o.borrowernumber=ba.borrowernumber)
JOIN biblio b using (biblionumber)
JOIN biblioitems bi using (biblionumber)
JOIN items i using (itemnumber)
where o.branchcode=<<Valitse kirjasto|branches>>
and o.cancellationdate between <<Vanhentumispäivä alkaen|date>> AND <<Päättyen|date>>
and o.found='W'
AND o.expirationdate = (o.cancellationdate - INTERVAL 1 DAY)
AND ba.code='HOLDID'
order by 1,2
```

**Comment by pknuuti** [comment]
Kiitos, nyt toimii raportti. Suljen tiketin.
