### ISSUE TITLE
Indeksoinnin virheloki

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#550]
### Mikä vikana?

OUTIlla oli virhelokilla vain kaksi biblionumberia, mutta niitä ei löytynyt Kohasta millään hakutavalla. Anneli kaivoi syövereistä tiedon, että ne ovat nuottien osakohteita ja, että niiltä puuttuu biblio metadata eikä niitä sen vuoksi Kohasta löydy. Voisiko ne korjata ja saada takaisin elävien kirjoihin?

Biblionumberit: 2205626 ja 2205627
Osakohteiden tietueen biblionumber on 2196078

**Comment by lasse-koha** [comment]
Nämä metadatat olivat testikannastakin hävinneet. Nyt ovat paikallaan ja osakohteet näkyvät oikein.

**Comment by piiaseme** [comment]
Kiitos. Nyt ne näkyvät tuotannossa kuten pitää, joten suljen tiketin :)
