### ISSUE TITLE
Hae asiakkaita -kentästä valitut hakuehdot antavat väärän hakutuloksen

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#551]
### Mikä vikana?

Asiakashaussa Hae asiakkaita -kentän oikealta aukeava hakurajaus ei vaikuta toimivan ainakaan näin hakiessa oikein. 
Hakutuloksessa on kaikki Hellen asiakastiedot, kun oikea hakutulos on 1.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ddab4b00-af4b-4eb6-a4f8-4a96f2372d7b)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/51e6df27-1813-48fb-af50-342e2255589d)

**Comment by AnneliO** [comment]
Pikahaun valikkoon valittujen tietojen pitäisi siirtyä vasemman reunan valikkoon, kun haku tehdään. Näin tapahtuu ainakin PTFS Europen sandboxissa. Niin ei kuitenkaan tapahdu meillä tuotannossa.

**Comment by AnneliO** [comment]
Liittyiskö tähän bugiin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33155

**Comment by emta001** [comment]
Tuotu testattavaksi testeille.

**Comment by pirliis** [comment]
Näyttäisi toimivan ainakin OUTIn testillä.

**Comment by Kati-Helle** [comment]
Helle-testillä toimii nyt oikein.

**Comment by sksandel** [comment]
Vaski-testillä toimii oikein.

**Comment by Kati-Helle** [comment]
Tämä toimii nyt myös tuotannossa oikein (Koha-päivitys 19.9.2023).
