### ISSUE TITLE
Lumme: Eräpäivämuistutuksissa vikaa

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#553]
### Mikä vikana?

Kahdelta eri virkailijalta tuli kahdesta eri kirjastosta tällaista raporttia: 

"Ilmoitus lähestyvästä eräpäivästä, lähetti muistutuksen äsken , vaikka kirjat uusittu ja eräpäivä 14.6." 

"Lisäksi yksi sai tänään huomautusviestin eräytyvästä lainasta. Se oli palautettu jo aiemmin, ja oli tiedoissakin oikein. Ja myös lainattu eteen päin."

Koskee sähköpostitse lähetettäviä viestejä.

**Comment by AnneliO** [comment]
Oliko viestit sellaisia, jotka on luotu jo ennen perjantaita? Lumpeissahan käynnistettiin viestien lähetys vasta tänään ja silloin lähetettiin kaikki sellaiset viestit, jotka ovat kertyneet viestijonoon 16.5.2023 lähtien.

**Comment by AnneliO** [comment]
Eli siis viestit on luotu ajastuksen mukaan, mutta ei ole lähetetty ja asiakkaat ovat voineet palauttaa lainat ennen kuin viestit on tänään lähetetty eteenpäin. Viestit eivät poistu jonosta, jos laina ehditään palauttaa ennen viestin lähettämistä. :)

**Comment by Hanna-Lumme** [comment]
Vähän mietinkin johtuiko se ehkä siitä, mutta hyvä varmistaa asia. :) Jätän vielä auki, jos tähän asiaan tulee vielä maanantaihin mennessä kommentteja virkailijoilta.
