### ISSUE TITLE
Palautus- toiminto: saisiko tarpeettoman Maksuja ei peritä käsin peruutetuista varauksista. -ilmoituksen piiloon

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#555]
### Kehitysehdotukseni

Palautustoiminto: saisiko piiloon/pois käytöstä niteen palautuksen tarpeettoman ilmoituksen:
Maksuja ei peritä käsin peruutetuista varauksista.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/16ff7861-11c4-4422-903e-7572d26caae4)

**Comment by AnneliO** [comment]
Pääkäyttäjäpalaveri 23.5.2023: Ei toteuteta.

**Comment by Kati-Helle** [comment]
Olisiko mahdollista muokata ilmoituksen tekstiä, jos missään kimpassa ei veloiteta maksua peruutetuista varauksista?

Teksti nyt:
Maksuja ei peritä käsin peruutetuista varauksista.

Tekstimuutos esim. näin:
Maksuja ei peritä peruutetuista varauksista.
tai
Maksua ei peritä peruutetusta varauksesta.

**Comment by AnneliO** [comment]
Teksti on englanniksi
Fines are not charged for manually cancelled holds.

Jos käännös muutetaan ehdotetun kaltaiseksi, jää siitä puuttumaan tuo "manually" sanan tuoma merkitys. Miksi tuo tieto halutaan poistaa ohjeesta?

**Comment by Kati-Helle** [comment]
Maksu menee noutamattomasta varauksesta, mutta milloin meneekään maksu peruutetusta varauksista?

**Comment by AnneliO** [comment]
Käytännössä noutamaton varaus myös peruutetaan, kun se on vanhentunut. Teknisesti siis sama asia, mutta asiayhteys eri.

Muistaakseni joissain tieteellisissä kirjastoissa otetaan maksu myös vanhentumattomista peruutetuista. Koha-Suomen kirjastoista en ole varma.

**Comment by AnneliO** [comment]
Eli se mitä haen kysymykselläni on, että jos ohjetta muutetaan, muuttuu se epämääräisemmäksi ja voi saada kuvan, että mistään peruutetusta varauksesta (käsin tai automaattisesti joko noutamattomana tai voimassaoloajan umpeuduttua) ei mene maksua. Näin ei taida missään olla. :)

**Comment by Kati-Helle** [comment]
Entäpä teksti tähän tyyliin, jos kaikkien käytännöt sallivat?
Maksuja ei peritä peruutetuista noudettavista varauksista.

**Comment by AnneliO** [comment]
En nyt hoksaa, että miksi teksti pitäisi muuttaa? Se kertoo tällä hetkellä aika tismalleen sen, mitä se tekee. :)

**Comment by Kati-Helle** [comment]
Teksti on hämmästyttänyt :) Pitänee yrittää selventää, mistä on kyse.

Tiedoksi, että kun jo noudettavana olevan niteen palauttaa ja vastaa 'Älä huomioi'
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b9d76d6a-11fe-4771-8ef8-911a0d09462a)

ja klikkaa oikean yläreunan i-ruutua 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/aeb7b8b5-2110-4587-b098-a5be5ae8066f)

on popup tämän kaltainen (kaksi popuppia kerralla?)
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/67353809-1d8f-408e-865d-cd66d756adef)

Mistä syystä Nidepaketin... -popup tuleekaan näkyville? Nidepaketteja ei ole ainakaan vielä Helle-käytössä.
