### ISSUE TITLE
Saisiko asiakashaku-toimintoihin oletushakutyypiksi saman arvon

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#556]
### Kehitysehdotukseni

Asiakkaan hakutoiminnoissa
- Hae asiakkaita - oletushakutyyppinä on Alkaa
- Lainaus - oletushakutyyppinä on Sisältää

Saisiko  oletusarvoksi molempiin hakuihin saman eli Sisältää?

**Comment by IrinaHalminen** [comment]
On myös käynyt niin, että virkailija menee etusivun Asiakkaat-linkin kautta ja käyttääkin sen jälkeen yläpalkin hakua (jossa oletushakutyyppinä "alkaa"). Jos hakutuloksia ei ole/tule, ja hän siirtyy käyttämään Hae asiakkaita -hakua, on siihen muuttunut automaattisesti hakutyypin kohdalle valinnan"sisältää" tilalle "alkaa", jolloin hän ei taaskaan saa hakutuloksia. Eli tuo oletushakutyyppi kopioituu Hae asiakkaita -hakuun, mutta muut yläpalkissa tehdyt hakukenttien muutokset eivät tee samaa.

**Comment by sksandel** [comment]
Vaskitukeen tulleen kysymyksen perusteella havaittiin, että alkaa-hakutyypissä näyttäisi lisäksi olevan sellainenkin ongelma, että "toista nimeä" ei huomioida, oli se sitten etu- tai sukunimikentässä. Esimerkiksi haulla "Juppi Aino" tai "Juppi Aino Konversio" ei löydy testiasiakasta, jonka etunimi on Juppi Aino ja sukunimi Konversio. Sen sijaan haulla Juppi Konversio löytyy tämä tyyppi.

Ongelmaksi tämä muodostui kun erään kunnan kotipalveluasiakkaat on nimetty sukunimenään "Kunnannimi kotipalvelu" ja etunimenään asiakkaan koko nimi.

**Comment by lmstrand** [comment]
Korjaus branchissa [ksdev/ks-0108-KD-G556-set-contains-as-default-patron-search](https://github.com/KohaSuomi/Koha-22x/tree/ksdev/ks-0108-KD-G556-set-contains-as-default-patron-search), viety testattavaksi testeille.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä ja näyttäisi toimivan hyvin. Vaikka muutin ylähakuun "alkaa" hauksi, sivupalkin asiakashaku antoi edelleen "sisältää" valinnan. Ja kun uudelleen tein ylähaun, siellä oli valintana "sisältää". Haku löytää asiakkaan pelkällä sukunimelläkin tai haettaessa sukunimellä ja asiakkaan toisella etunimellä (Gili Antonio Kaadekohta löytyy myös Antonio Kaadekohta -haulla)

**Comment by Kati-Helle** [comment]
Helle-testissä Hae asiakkaita -hakutavan Hakutyypin oletuksena on nyt Sisältää. 
Asiakkaan haku vaikuttaa toimivalta.

Hae asiakkaita -asiakashakuun polkua Asiakkaat/Hae asiakkaita: Hakutyyppi-arvona on Sisältää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5619eb55-ce19-4b7f-8012-2e2e3440d0f9)

Hae asiakkaita -haun hakutyypin oletusarvona on Sisältää myös silloin, kun on ensin hakenut asiakasta käyttäen polkua Lainaus ja palautus/Lainaus
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/a8695f38-34ae-4337-8b38-af3979faa938)

Haun jälkeen hakutavaksi vaihtuu automaattisesti Hae asiakkaita -haku, jossa hakutyyppinä Sisältää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/458f2c2e-2c03-4f67-a6bb-d7cead558d45)

**Comment by pirliis** [comment]
Näyttäisi toimivan myös OUTIssa.

**Comment by lmstrand** [comment]
Pistetään tiistain päivitykseen.

**Comment by lmstrand** [comment]
Suljen tiketin.
