### ISSUE TITLE
Helle: saisiko asiakkaan muokkauksen Käyttökieli-asiakasmäärekentän (USER_LANG) paikan muutettua? 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#557]
### Tukipyyntö

Hellessä asiakastiedon muokkauksessa on Muut määreet ja tunnukset -osiossa vain yksi asiakasmäärekenttä: 
Käyttökieli (USER_LANG)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9a8a5bb6-2f61-4349-92b4-dfc5994b4402)

Saisiko 
- asiakasmäärekentän Käyttökieli (USER_LANG) siirrettyä ylemmäksi Asiakas identiteetti -osioon
- siirron jälkeen piilotettua tarpeettoman/kentättömän Muut määreet ja tunnukset -osion

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 22.5.2023: Riittäisikö tässä Ilmoitusten kieli -valinta? Onko erillinen käyttökieli tarpeen? Eli kyseisen asiakasmääreen voisi poistaa kokonaan, jos ilmoitusten kieli on riittävä.

**Comment by Kati-Helle** [comment]
Ilmoitusten kieli ei ole riittävä. 
Käyttökieli näkyy asiakastiedon vasemmassa tietoruudussa, mutta Ilmoitusten kieli ei näy.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/753184a2-65cf-4b6e-b8cc-6c260aa44d02)

**Comment by AnneliO** [comment]
Katson, jos saisin tehtyä siirtoskriptin aiempien pohjalta. Tässä kuitenkin kannattaa huomioida, että Helle poikkeaa sitten tämän osalta kaikista muista kimpoista, eikä kaikki muut muutokset välttämättä tule toimimaan Hellessä jatkossa suoriltaan.

**Comment by AnneliO** [comment]
IntranetUserJS:ään asiakasmääreen siirtorimpsu (patron_attr-arvo pitäisi olla sama kuin tuotannossa eli pitäisi toimia tuolla). Lisää asetuksessa varaustunnuksen siirto-rimpsun alapuolelle (katso testiltä paikka, jos tämä ohjeistus huono :) ):

```
///ALKU///

// Käyttökieli-asiakasmääreen siirto asiakkaan identitetti -osioon sivun alkuun
$(document).ready(function () {
  if (window.location.href.indexOf("members/memberentry.pl") > -1) {
    var holdidlabel = $('label[for="' + "patron_attr_6" + '"]');
    var clearbutton = holdidlabel.next().next().next();
    clearbutton.replaceWith( '<button type="button" class="fa fa-fw fa-trash fa-lg" style="color:green; border:none;">' );
    holdidlabel.next().next().next().on('click', function(e){
        holdidlabel.next().val('');
    });
    var li = holdidlabel.parent();
    $( "#identity_lgd" ).next().append(li);
  }
});

///LOPPU///
```

IntranetUserCSS:ään Muut määreet ja tunnukset -osion piilotus:

```
/* Piilota Muut määreet ja tunnukset -kohta asiakkaan muokkauksesta */
body#pat_memberentrygen.pat fieldset#memberentry_patron_attributes.rows { display:none; }
```

**Comment by AnneliO** [comment]
Niin joo ja JS:n muutoshan pitää tehdä yhteistyössä kehittäjien kanssa, joten sovi päivystäjän kanssa, koska tuo tehdään. :)

**Comment by AnneliO** [comment]
Tuli sellainen mieleen, että jos teillä on esim. asiakastyyppi-kohtaisia asiakasmääreitä (pitäisi olla ainakin sip-tunnuksille automaattityyppi ja -toimittaja), niin ne menee myös piiloon, jos Muut määreet ja tunnukset -osio piilotetaan.

**Comment by Kati-Helle** [comment]
Saisiko Helleen molemmat Annelin toteuttamat rimpsut käyttöön tiistaina 6.6.2023.
- Käyttökieli-asiasmääre siirretään Asiakkaan identiteetti-osioon
IntranetUserJS

- Muut määreet ja tunnukset -osio piilotetaan
IntranetUserCSS

Annelin toteuttamien rimpsujen tiedot tämän tiketin kommentissa:
https://github.com/KohaSuomi/Koha/issues/557#issuecomment-1561066413

**Comment by AnneliO** [comment]
Otitko @Kati-Helle pois sip-tunnuksilta asiakasmääreet? Nehän olisi hyvä olla käytössä kaikilla tunnuksilla.

**Comment by Kati-Helle** [comment]
> Otitko @Kati-Helle pois sip-tunnuksilta asiakasmääreet? Nehän olisi hyvä olla käytössä kaikilla tunnuksilla.

En ottanut. Paikallaan ovat :)
Asiakasmääreitä saa tarvittaessa käsiteltyä asiakastiedon muokkauksessa (esim. uusi automaattitunnus).

**Comment by Kati-Helle** [comment]
Valmis. Emmi Takkinen lisäsi IntranetUserJS-rimpsun 6.6.2023.
