### ISSUE TITLE
OUTI: Puolivälinkankaan kirjaston niteet Muuttolaatikossa-tilaan

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#559]
### Tukipyyntö

Oulussa Puolivälinkankaan kirjasto on mennyt kiinni toistaiseksi. Muuttaisitteko niteille, joiden havaintokirjasto (nykyinen kirjasto) on OUPV ja ja ovat saatavana tilassa: 
- notforloan-arvoksi 15 (Muuttolaatikossa).  

Muutosta ei tehdä, jos nide on: 
* kuljetettavana
* kuljetettavana kiinni jääneeseen varaukseen
* lainassa
* odottavat varattuna noutoa 

tai  ei myöskään tehdä, jos niteen notforloan-arvo on: 
* 1 (ei lainattavissa)
* -1 (tilattu)
* -2 (saapunut)
* 6 (laskutettu, toimi kirjastosi laskutusohjeiden mukaisesti)
* 8 (ei laskuteta, toimi kirjastosi laskutusohjeiden mukaisesti)
* 4 (laskutuksessa, alle 8 e)
* 9 (tarkistettavat)
* 10 (poistoehdotukset)
* -11 (korjattavana)
* -12 (tarroitettavat)
* 13 (puutteelliset)
* -14 (uusin numero, ei lainata)
* 16 (turmeltuneet) 

Muutoksen voi tehdä heti, kun ehditte.

**Comment by paxed** [comment]
Muutos tehty, niteet joiden notforloan-arvo muutettiin itemnumber on tallessa taulussa ks_20230524_itemnumbers1_gh_559.
Muutos koski 6467 nidettä.


Näillä rimpsuilla:

```
create table ks_20230524_itemnumbers1_gh_559 select i.itemnumber from items i left join reserves r on (i.itemnumber=r.itemnumber) left join branchtransfers bt on (i.itemnumber=bt.itemnumber) where i.holdingbranch = 'OUPV' and i.notforloan=0 and i.onloan is null and r.found is null and bt.datearrived is null;

update items i left join reserves r on (i.itemnumber=r.itemnumber) left join branchtransfers bt on (i.itemnumber=bt.itemnumber) set i.notforloan=15 where i.holdingbranch = 'OUPV' and i.notforloan=0 and i.onloan is null and r.found is null and bt.datearrived is null;

```

**Comment by pirliis** [comment]
Kiitos! Kun tsekkailin niteitä, joiden nykyinen paikka on OUPV, näyttäisi löytyvän vielä aika paljon saatavana-tilassa olevia niteitä, jotka eivät ole menneet muuttolaatikossa-tilaan, esim.:
33279
10093
3342
3394898
3471987
3177293
96645
175335
193204
240704

Muutos ei ole tainnut purra kaikkiin tarvittaviin niteisiin.

**Comment by pirliis** [comment]
Joo, nyt näyttää paremmalta. :) En löytänyt enää yhtään saatavana-tilassa olevia OUPV:n niteitä.
Suljen tiketin.
