### ISSUE TITLE
Redminessä olevat MARC-kuvailuvirheraportit eivät toimi enää

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#560]
### Tukipyyntö

Redminessä olevat MARC-kuvailuvirheraportit eivät toimi enää versiovaihdon jälkeen: https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/MARC-luettelointivirheraportit 
Tulee virhe 404.

Saisiko ne toimimaan taas? Raportit on varmaan tarkoitus jossain vaiheessa siirtää githubiin.

**Comment by janPasi** [comment]
Raportit ovat itseasiassa siellä Koha-installaatioen kyljessä, eivät varsinaisesti Redminessä. Redminessä on ainoastaan linkki raporttiin. Linkit siirretään ainakaan GitHubiin, mutta raportit säilyvät siellä missä ne ovat aina olleetkin. Tässä oli nyt käynyt niin että raporttien tämänhetkinen versio oli jäänyt Koha-asennusta vaihdettaessa sinne vanhan Koha-asennuksen yhteyteen. Kopioin sen sieltä myös uuteen Kohaan ja linkit toimivat nyt.

**Comment by AnttHeik** [comment]
Jeps, ainakin TäTin ja OUTIn raportit toimivat taas. Onko Kohan rapotti-osiostakin mahdollista päästä noihin jotakin kautta vai pitääkö käyttää vain noita linkkejä?

**Comment by AnneliO** [comment]
IntranetReportsHomeHTML -järjestelmäasetukseen voisi lisätä tällaisen html-koodin. Korjatkaa osoitteisiin oman kimpan linkit, jotka löytyvät tuolta tiketin kuvauksessa olevan linkin takaa.

```
<div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
<h2>MARC-virheraportit</h2>
<ul>
<li><a href="https://helle.koha-suomi.fi/marc_virheet.helleprod.html" target="_blank" rel="noopener">Virheelliset tietueet </a></li>
<li><a href="https://helle.koha-suomi.fi/marc_virhemaara.helleprod.txt" target="_blank" rel="noopener">Virhem&auml;&auml;r&auml;t</a></li>
</ul>
</div>
```

Otsikko ja pallerot eivät asetu samalle kohdalle kuin yläpuolella olevat tekstit, mutta katotaan ajan kanssa, saisiko ne kohdistettua paremmin.

**Comment by AnneliO** [comment]
Seuranta. Peukuta tätä kommenttia, kun olette kimpassa lisänneet linkit Raporttien etusivulle.
- [ ] Lappi
- [ ] OUTI
- [ ] Siilinjärvi
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Vaski

**Comment by piiaseme** [comment]
Linkit myös TäTissä.

**Comment by AnneliO** [comment]
Sellainen täsmennys ohjeeseen, että rimpsu pitää lisätä Lähdekoodi-näppäimen takaa löytyvällä editorilla. Eli tällä:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/2460b6d4-c3a1-45f7-9740-8c3419cb4325)

**Comment by pirliis** [comment]
Näyttäisi, että kaikki ovat lisänneet linkit. Suljen tiketin.

**Comment by AnneliO** [comment]
Lisäsin tuon IntranetReportsHomeHTML:ään lisätyn rimpsun nyt myös [Järjestelmäasetukset-ohjeeseen](https://koha-suomi.fi/dokumentaatio/jarjestelmaasetukset/#intranetreportshomehtml).
