### ISSUE TITLE
Lumme: asiakkaille ei ole kertynyt maksuja myöhässä olevasta aineistosta

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#561]
### Mikä vikana?

Ainakin Savonlinnasta on raportoitu, että perjantaina eräpäivällä olleet kirjat eivät olleet kerryttäneet maksua kahdelle eri asiakkaalle. Olivat asioineet kirjastossa lauantaina ja bonganneet kirjastossa asian silloin. Molemmissa tapauksissa aineisto oli aikuisten, joten maksua olisi pitänyt kertyä normaalisti.

**Comment by Hanna-Lumme** [comment]
ID:t olisi: 96778 ja 136045. :)

**Comment by AnneliO** [comment]
Voiskohan tähän liittyä jotenkin se, että Lumpeissa on ChargeFinesOnClosedDays-järjestelmäasetuksessa valinta, että maksuja ei laskuteta kiinniolopäivinä. Savonlinnalla on kalenterissa kiinni 20.5.2023, jolloin 19.5.2023 eräpäivä olisi laskutettavana. Eli vähän sama tilanne kuin, että varauksia ei vanhenneta kiinniolopäivinä.

**Comment by AnneliO** [comment]
Maksut muodostava ajastettu ajo fines.pl ajetaan joka yö minuutin yli puolen yön. Eli 19.5.2023 erääntyneiden lainojen maksut luodaan 20.5.2023 klo 00.01. Mutta jos tosiaan ymmärrän tuon ChargeFinesOnClosedDays-järjestelmäasetuksen toimintalogiikan oikein, niin teillä ajoa ei tehdä kalenterin kiinniolopäivinä eli juurikin tuolloin 20.5.2023. Tänään käynyt asiakas taas on saanut maksunsa 19.5.2023 erääntyneistä, koska ma 22.5.2023 klo 00.01 on kalenterissa määritetty auki olevaksi ja ajo ajetaan. Maksut luodaan ajossa eräpäivästä lähtien eli 19.5.2023 lähtien sitten kun ajo ajetaan.

Asetuksen kuvaus: If set the fines.pl cronjob will not generate fines when run on days marked as closed in the calendar. / Jos asetettu, fines.pl cronjob ei kerrytä maksuja niiltä päiviltä, jotka kalenteriin on merkitty kiinniolopäiviksi.

**Comment by Hanna-Lumme** [comment]
Minäpä välitän tämän tiedon eteenpäin, kiitos asian ratkomisesta!
