### ISSUE TITLE
Lumme: 500 Internal Server Error asiakasta lisätessä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#563]
### Mikä vikana?

Asiakastietokantaan oli oltu viemässä asiakasta, ja vastaan tuli tällainen virhe: 

"_Sotun tallennuksessa valitti, että on jo tiedot ja hyväksyttäessä antoi 500 virheen. Samoin ei hyväksynyt uudelleen samaa kirjastokorttia. Täytin alusta asti lomakkeen uudelleen (työkaveri teki aiemman, eli ei aavistustakaan mitä tehtiin eri tavalla) ja antoi lopulta tallentaa._"

Lähdin hakemaan kyseistä asiakasta koko nimellä niin löytyi Kohasta. Kun hain joko osoitteella tai etunimi+sukunimi-kombolla, niin ruutuun tuli teksti: Jotain meni pieleen taulua ladattaessa. 500: Internal Server Error. Month out of range. AsiakasID on tallessa.

**Comment by Hanna-Lumme** [comment]
Ei anna minun päästä tietoihin käsiksi edes tuota linkkiä klikkaamalla - eikä ID:llä hakemalla. Uskaltaisikohan ne tiedot kokonaan poistaa?

**Comment by AnneliO** [comment]
Emmi muuttaa tietokantaan syntymäajan hyväksyttävään muotoon, niin pääsette korjaamaan sen oikeaksi sen jälkeen.

**Comment by emta001** [comment]
Nyt on muutettu ja asiakkaan tietoihin pääsee.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon, nyt alkoi pelittää!
