### ISSUE TITLE
Niteiden vastaanotossa "nopeusongelma"

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#565]
### Mikä vikana?

Kun vastaanotetaan tilattuja niteitä, käy välillä niin, että haettu tilaustieto katoaa nopeasti näytöltä ja sen tilalle tulee ihan eri nimeke kuin mikä pitäisi olla. Jos virkailija ei ole tarkkana, nide voi tulla vastaanotetuksi ihan väärään nimekkeeseen. Tilanne ilmenee usein vasta jonkin ajan kuluttua, kun tilattuja niteitä on ryhdytty vastaanottamaan eli ei heti alkuunsa ole ongelma. 

Olin itse todistamassa vastaanottoa ja virkailija ei tehnyt yhtään mitään toimenpidettä haun jälkeen ja yhtäkkiä nimeke vaihtui näytöllä. Tämä on ollut ongelmana jo edellisestä versionvaihdosta lähtien, välillä pahempana, välillä vähän vähempänä, mutta ei tämäkään versionvaihto tuonut ongelmaan korjausta. Nextillä testatessa ongelmaa ei ilmennyt, mutta siellä testaus ei ollut niin pitkäaikaista kuin normaali aineiston vastaanotto on.

### Mitä pitäisi tapahtua

Näytöllä pitäisi pysyä haettu tilaustieto eikä se saisi muuttua yhtäkkiä ihan toiseksi nimekkeeksi.

**Comment by AnneliO** [comment]
Onko tätä tapahtunut vielä version 23.11 aikana?

**Comment by pknuuti** [comment]
Marjan mukaan ei Vaarassa ainakaan ole enää ongelma. Suljen tiketin.
