### ISSUE TITLE
Niteiden erämuokkauksesta puuttuu Kohan koko signum -kentän generointi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#568]
### Mikä vikana?

Niteiden erämuokkauksen lomakkeelta puuttuu mahdollisuus generoida kenttä _Kohan koko signum_ kolmea pistettä klikkaamalla. Aiemmassa versiossa erämuokkauksessa pystyi generoimaan kenttään luokan ja pääkirjauksen (ei hyllypaikan lyhennettä).

**Comment by AnneliO** [comment]
Tässä käy nyt samalla tavalla kuin tiketissä #540 eli kolmea pistettä painamalla kenttä menee lukkoon. Nextillä (jossa taitaa olla nyt sellainen versio, jossa ei ole tämän päivän päivityksiä mukana) kolmea pistettä painaessa sivu hyppää sivun alkuun.

**Comment by ajrajala** [comment]
Sellainen huomio, että Vaski-testillä kolmea pistettä ei ylipäätään näy eli ei pysty edes yrittämään signumin generointia:

![Image](https://github.com/KohaSuomi/Koha/assets/44638512/830b36eb-869c-46e8-bb3f-2031b2e59c04)

Tätä tikettiä tehdessä luulin katsoneeni, että tuotannossa olisi ollut sama tilanne kuin testillä, mutta tuotannossahan tuo on näköjään noin kuten Anneli kirjoitti eli menee lukkoon. 🤔 Välimuisti on kyllä tyhjätty.

**Comment by ajrajala** [comment]
Tätä ongelmaa ei enää Vaskin tuotannossa ole. Meillä ei mene kenttäkään lukkoon toisin kuin ilmeisesti muissa kimpoissa, mutta siitä on jo toinen tiketti #585 tehtynä. Suljen siksi tämän tiketin.
