### ISSUE TITLE
Lumme: Varauksia tulee lainattavissa/ei varattavissa oleviin niteisiin

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#569]
### Mikä vikana?

Lumpeissa törmättiin ongelmaan, että varaukset näyttävät tarttuvan lainattavissa/ei varattavissa -tilassa oleviin niteisiin. Tämä estää niteiden uusinnan Kohassa ja Finnassa ja vaikeuttaa esim. Mikkelissä liikkuvien palveluiden töitä. Tila toimi oikein ennen versionvaihtoa.

### Mitä pitäisi tapahtua

Lainattavissa/ei varattavissa -tilassa olevan niteen ei pitäisi päätyä varattujen listalle.

### Jotain muuta?

![Varattu-tila](https://github.com/KohaSuomi/Koha/assets/129748294/407d9530-a905-47f8-97be-4587faa7d550)

**Comment by AnneliO** [comment]
Esimerkkikuva on asiakkaan lainoista, ei hyllyvarauslistalta - onko tuossa väärä kuva?

**Comment by AnneliO** [comment]
Jos tässä tarkoitetaan, että estyy damaged-arvoisen niteen lainan uusinta, niin testasin samaa OUTIn testillä. Siellä ei esty uusiminen, vaikka tietueeseen kohdistuu varaus.

En myöskään löydä Lumpeiden laina- ja maksusäännöistä mitään, mikä estäisi uusimisen.

**Comment by AnneliO** [comment]
Lumpeissa on myös  AllowHoldsOnDamagedItems -järjestelmäasetuksessa _Älä salli_, joten varausten ei pitäisi jäädä kiinni nidettä palautettaessa. Onko niin siis käynyt?

**Comment by AnneliO** [comment]
Testasin tätä nyt taas uudelleen tällä kertaa Lumme-testillä. En saanut toistettua kuvan tilannetta [tällä asiakkaalla](https://lumme-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=143912). Sekä tietueeseen että niteeseen kohdistuu varaus, eikä kumpikaan estä uusimista.

**Comment by Hanna-Lumme** [comment]
Testailin tätä myös tuotannossa ja nyt ei tartu varaus kiinni.
