### ISSUE TITLE
Tekstiviestinoutoilmoituksissa ääkköset eivät näy oikein

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#570]
### Mikä vikana?

OUTIssa on tullut asiakaspalautetta, ettei tekstiviestinoutoilmoituksissa näy ääkköset oikein. Kohassa asiakkaan ilmoituksissa ääkköset näkyvät oikein, mutta asiakkaan puhelimeen tulleessa tekstiviestissä ääkköset eivät näy oikein.  Onkohan joku merkistöongelma?

**Comment by lmstrand** [comment]
Linkmobilityn SMS-driveri on käytössä näissä kimpoissa:

Vaara
Siili
Outi
Lumme
Lappi

Vaarassa oli Driverin konfiguraatiossa requestEncoding: UTF-8, teillä Outin tuotannossa requestEncoding: ISO-8859-1.
Vaihdan tuon arvon samaksi kuin Vaarassa. Ilmoitelkaa tuliko kuntoon.

Käyn läpi vielä nuo muut kimpat ja tarkastan tuon asetuksen.

**Comment by lmstrand** [comment]
Lapista konfiguraatio puuttuu kokonaan. Lisätään tarvittaessa.

**Comment by piiaseme** [comment]
OUTIssa ei tullut kuntoon.

**Comment by AnneliO** [comment]
Testasin Lapissa niin, että varaustunnus oli Äänisen Öölit. Se oli tekstarissa muodossa Aanisen Oolit. Eli ei toimi oikein.

Outissa tilanne oli vielä huonompi:

![oolit](https://github.com/KohaSuomi/Koha/assets/33121325/580971ee-f786-415b-a9b0-99764a33112f)

**Comment by Hanna-Lumme** [comment]
Ja Lumpeissa.

**Comment by LeenaKinnunen** [comment]
Samanlainen ääkkösongelma Lapissa kuin Päivillä Vaarasta.

**Comment by ajrajala** [comment]
Vaskissa ei ääkkösongelmaa tekstareissa.

**Comment by ReettaSiili** [comment]
SiilinjÄrvellÄ on ääkkösongelma.

**Comment by pirliis** [comment]
Nyt OUTIssa ääkköset ja öökköset näkyvät oikein. :)

**Comment by ReettaSiili** [comment]
Samoin Siilissä, _Nuorisotyötä on tehtävä_ näkyy ihan oikein.

**Comment by pknuuti** [comment]
Vaarassakin nyt oikein ääkköset.

**Comment by Hanna-Lumme** [comment]
Lumpeissa toimii skandit myös. :)

**Comment by LeenaKinnunen** [comment]
Lapissa skandit toimii myös.

**Comment by lmstrand** [comment]
Hyvä juttu. Suljen tiketin.

**Comment by janPasi** [comment]
hdiacritic on alunperin peräisin muinaisesta OpusCapita convert and sendistä, jota käytettiin e-kirjeiden toimittamiseen. Sen on sittemmin korvannut KSMessaging, jossa hdiacritic on edelleen myös mukana alkuperäisessä muodossaan.  Se on ollut mukana myös LinkMobility-ajurissa jo silloin kun LinkMobility (silloin Labyrintti) otettiin Outissa käyttöön. Ilmeisesti LinkMobilityn "plugarisoinnissa" edellisen versiopäivityksen yhteydessä hdiacriticiin on tehty (toistaiseksi tuntemattomasta syystä) muutoksia ja ne eivät nyt sitten enää toimineet.

Tällä hetkellä tilanne on siis se, että hdiacriticista on meillä kolme eri "kopiota" ympäri systeemiä ja näköjään yksi niistä samasta nimestä huolimatta myös poikkesi muista. Olisi syytä erottaa hdiacritic omaksi modulikseen esimerkiksi KohaSuomi::Tweaksin alle ja ylläpitää koodi vastaisuudessa ainoastaan siellä. Tästä täytyy avata erillinen tiketti, mutta avaan nyt toistaiseksi tämän tiketin vielä takaisin, niin pysyy mielessä.

**Comment by lmstrand** [comment]
Avasin aiheesta oman tiketin https://github.com/KohaSuomi/Koha/issues/655
