### ISSUE TITLE
Varauksenteko-sivulla ei toimi asiakastaulukon sarakkeiden piilotus

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#571]
### Mikä vikana?

[Varauksenteko-sivulla](https://outi-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=2279911) asiakashaun tulostaulukon piilotukset eivät toimi. Taulukon yläpuolelta puuttuuu _Sarakkeet_-nappula ja _Määritys_-nappula ei vie oikean taulun kohdalle Taulujen asetukset -sivulla ylläpidossa. Nappula pitäisi viedä table_borrowers-kohtaan. 
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/2685faa7-ccf4-4304-8029-88a02dc81440)

table_borrowers löytyy Taulujen asetukset -sivulta _Lainaus ja palautus_ -osiosta, mutta siihen tehdyt valinnat eivät vaikuta mihinkään.

### Mitä pitäisi tapahtua

table_borrowers-kohtaan tehdyt muutokset pitäisi vaikuttaa varauksenteko-sivun asiakashaun tulosten taulukkoon ja kyseisellä sivulla pitäisi olla Sarakkeet-nappula Vie-nappulan vasemmalla puolella.

### Kuinka toistaa ongelma/asia

1. Varmista, että varausten sivulla ei ole piilotettu haun tulostaulukkoa css:llä.
2. Hae jokin tietue ja mene varauksenteko-sivulle.
3. Hae sellaisella hakusanalla, joka tuottaa useamman hakutuloksen. Esim. test.
4. Saat hakutulostaulukon. Huomioi, että taulukon yläpuolelta puuttuu _Sarakkeet_-nappi.
5. Klikkaa Määritä-nappulaa, jolloin siirryt Taulujen asetukset -sivulle, mutta et oikean taulukon kohdalle.
6. Etsi table_borrowers-taulukko Lainaus ja palautus -osiosta ja piilota sarakkeita.
7. Huomaa varauksenteko-sivulla, että piilotetut sarakkeet eivät mene piiloon.

### Jotain muuta?

Asiasanat: varauksen teko, varauksen tekeminen, asiakashaku, taululukon sarakkeiden piilotus, piilottaminen, sarakkeet, varaukset

**Comment by AnneliO** [comment]
En ole varma, liittyykö tähän ongelmaan, mutta löysin bugzillasta tällaisen tiketin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30068

Liittyy kuitenkin tuohon samaan table_borrowers-tauluun.

**Comment by AnneliO** [comment]
Testasin tätä myös PTFS Europen sandboxissa ja ongelma toistuu myös siellä.

**Comment by AnneliO** [comment]
Vastaava virhe korjattu tiketissä [Koha-22x #71](https://github.com/KohaSuomi/Koha-22x/issues/71).

**Comment by lmstrand** [comment]
Asiantuntijaryhmän palaverissa päätetty, että:
"Otetaan pois nykyinen hakutulostaulukon piilotus ja piilotetaan taulukosta syntymäaika, osoite ja puhelinnumero."

Taulukon sarakkeiden piilotusta ei siis tarvitse korjata. Korjataan yhteisössä ajallaan. Kovakoodataan näkyville vain sovitut kentät, jolloin kaikissa kimpoissa on sama halkutulosnäkymä riippumatta tauluasetuksista, jotka nyt eivät muutenkaan toimi.

**Comment by lmstrand** [comment]
Viety testeille testattavaksi (branch ksdev/ks-0107-KD-G571-hide-table-borrowers-unwanted-fields).

**Comment by Kati-Helle** [comment]
Helle-testissä vaikuttaa toimivalta. 

Poistin IntranetUserCSS-asetuksesta rimpsun tulostaulukon piilotuksen.

Tietueen varauksenteko-sivulla asiakashakutulos
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4ad92496-8185-4044-9752-c6268c8c6010)

Varauksenteon asiakashaun hakutulostaulukosta puuttuvat nämä piiloon tarkoitetut: syntymäaika, osoite ja puhelinnumero.
Hakutuloksessa näkyvät nämä: Nimi, Kortti, Tyyppi, Kirjasto.

**Comment by pknuuti** [comment]
Vaaran testillä samanlainen tulos kuin Hellessä eli toimii. 
Testasin ensin vahingossa poistamatta css-rimpsusta piilotusta ja sitten poiston jälkeen ja kummallakin kerralla samanlainen tulos.

**Comment by pirliis** [comment]
Myös OUTIn testillä sama tulos kuin Hellessä eli toimii.

**Comment by ajrajala** [comment]
Ja sama Vaskissa, toimii.

**Comment by Hanna-Lumme** [comment]
Lumme kuittaa myös, että toimii samalla tavoin kuin Hellessä.

**Comment by lmstrand** [comment]
Kiitos, siirretään seuraavaan tuotantopäivitykseen.

**Comment by lmstrand** [comment]
suljen tiketin.
