### ISSUE TITLE
Virkailijoille tullut versionvaihdossa liikaa oikeuksia maksuissa

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#572]
### Mikä vikana?

Virkailijatunnuksille on tullut liikaa oikeuksia kohtaan Hallinnoida asiakkaan maksuja (updatecharges). Kohtaan on lisätty oikeudet manual_credit ja manual_invoice, mutta samalla on tullut kaikki oikeudet updatecharges kohtaan (eli se ylätaso). Miten oikeuksien kanssa toimitaan? Voiko uudet oikeudet ajaa keskitetysti pois käytöstä (jos niillä ei ole meidän Kohassa käyttöä) ja voiko aiempia maksuoikeusia mitenkään palauttaa vai pitääkö ne käydä käsin läpi? Ja jos pitää, saako tähän toimivan raportin, millä voi hakea vain tietyn oikeuden.

**Comment by emta001** [comment]
Muutos on perustunut siihen onko käyttäjällä aiemmin ollut "updatecharges" oikeuden alaoikeus "remaining_permissions". Tästä on tehty oletus, että nuo uudet oikeudet voidaan lisätä käyttäjälle.

Lapissa on tällä hetkellä 112 käyttäjää, joilla on joko oikeus "manual_credit" tai "manual_invoice". Käytännössä en usko, että kenellekään on tullut täysiä oikeuksia (eli niin, että borrowers.flags arvoon olisi lisätty täyden oikeuden arvo). Käytännössä noiden yksittäisten oikeuksien poistaminen onnistuu kerralla suoraan kannasta, mutta suosittelisin kyllä käymään käyttäjät läpi ja katsomaan tarvitsevatko he jomman kumman tai molemmat oikeudet. Seuraavalla raportilla saa selville sen, keillä on nuo yksittäiset oikeudet:

SELECT borrowernumber, code 
FROM user_permissions 
where code in("manual_credit","manual_invoice");

**Comment by MikkoLiimatainen** [comment]
Vaskissa ainakin on aiemmin laitettu käyttäjille tuo maksujen ylätason oikeus. Nyt käyttäjillä on turhaan nuo manual_credit ja manual_invoice. Käytännössä näyttäisi siltä, että näitä turhia oikeuksia on 462 käyttäjällä, kun luetaan pois laskuttajat, jotka tarvitsevat updatechages oikeuden. Olisikohan nämä mahdollista muokata ajolla?

**Comment by emta001** [comment]
> Vaskissa ainakin on aiemmin laitettu käyttäjille tuo maksujen ylätason oikeus. Nyt käyttäjillä on turhaan nuo manual_credit ja manual_invoice. Käytännössä näyttäisi siltä, että näitä turhia oikeuksia on 462 käyttäjällä, kun luetaan pois laskuttajat, jotka tarvitsevat updatechages oikeuden. Olisikohan nämä mahdollista muokata ajolla?

Pitää tutkia, mutta menee kyllä miun loman jälkeen tämä (ellei joku muu halua/kerkiä tutkimaan). 

Voisi muuten olla ihan hyvä, että muutkin kimpat vilkaisisivat omista kannoistaan nämä määrät ja päättäisivät mitä näille tehdään :thinking: Niin muutetaan sitten tämä kaikille kerralla. Laitan tästä vaikka muistutuksen pääkäyttäjien ensi viikon palaveriin.

**Comment by pknuuti** [comment]
Kävin Vaaran käyttäjätiedot läpi käsin ja poistin tarpeettomat maksujen oikeudet.

**Comment by LeenaKinnunen** [comment]
Lappi käyttäjäjätiedot käyty läpi ja poistettu tarpeettomat maksujen oikeudet.

**Comment by piiaseme** [comment]
OUTI poistaa tarpeettomat maksuoikeudet manuaalisesti vuosittaisen käyttäjätunnustarkistuksen yhteydessä.

**Comment by ReettaSiili** [comment]
Myös Siilinjärvellä maksuihin liittyvät käyttäjäoikeudet käyty läpi ja korjattu.

**Comment by AnneliO** [comment]
Emmi, onko kommentoineille kimpoille tehty ajot?

**Comment by emta001** [comment]
> Emmi, onko kommentoineille kimpoille tehty ajot?

Eipä ole ei. Laitan tän ens viikon tehtävälistalle.

**Comment by emta001** [comment]
> Vaskissa ainakin on aiemmin laitettu käyttäjille tuo maksujen ylätason oikeus. Nyt käyttäjillä on turhaan nuo manual_credit ja manual_invoice. Käytännössä näyttäisi siltä, että näitä turhia oikeuksia on 462 käyttäjällä, kun luetaan pois laskuttajat, jotka tarvitsevat updatechages oikeuden. Olisikohan nämä mahdollista muokata ajolla?

Vilkaisin Vaskin kantaa ja löysin vain 6 käyttäjää, joilla on manual_invoice oikka. Onko näitä jo keretty siivoamaan?

Ja nyt on pakko myöntää, olen hieman pihalla tästä tiketistä. Ilmeisesti muilla kommentoineilla kimpoilla asia on hoidettu käsin ja on nyt ok?

**Comment by piiaseme** [comment]
OUTI on ok :)

**Comment by LeenaKinnunen** [comment]
Lappikin on korjattu.

**Comment by IrinaHalminen** [comment]
Päivi on Vaarassa hoitanut asian.

**Comment by ReettaSiili** [comment]
Siilissä nämä on korjattu.

**Comment by emta001** [comment]
> > > Vaskissa ainakin on aiemmin laitettu käyttäjille tuo maksujen ylätason oikeus. Nyt käyttäjillä on turhaan nuo manual_credit ja manual_invoice. Käytännössä näyttäisi siltä, että näitä turhia oikeuksia on 462 käyttäjällä, kun luetaan pois laskuttajat, jotka tarvitsevat updatechages oikeuden. Olisikohan nämä mahdollista muokata ajolla?
> > 
> > 
> > Vilkaisin Vaskin kantaa ja löysin vain 6 käyttäjää, joilla on manual_invoice oikka. Onko näitä jo keretty siivoamaan?
> > Ja nyt on pakko myöntää, olen hieman pihalla tästä tiketistä. Ilmeisesti muilla kommentoineilla kimpoilla asia on hoidettu käsin ja on nyt ok?
> 
> Pystyykö sen vielä tarkistamaan, että onko meillä käyttäjiä joille olisi annettu ylätason oikeus updatecharges, kun ylätason oikeuden omaavia käyttäjiä ei ilmeisesti saa suoraan tuolta user_permissions-taulusta haettua..? En oo varma ymmärsinkö noista aiemmista kommenteista oikein, mutta käsitin että se ylätason oikeus olisi tullut 462 käyttäjälle silloin taannoin.

Tällä saa laskettua, monellako käyttäjällä on täydet updatecharges-oikat:

`SELECT count(*) FROM borrowers WHERE flags = flags | (1<<10);`

Sain tulokseksi 428. Kieltämättä hieman menee mutkikkaaksi tämä nyt kun miettii tarkemmin. Pitäisi ensin kyetä rajaamaan se keiltä kaikilta nuo täydet oikat otetaan pois. Sitten pitäisi määrittää se, että mitä updatecharges oikeuksia heille sitten lisätään uudestaan. Toki voisi olettaa, että kaikki muut oikat paitsi juurikin manual_credit tai manual_invoice. Ei tää ihan mahdotonta siis ole, jos kaikille muokattaville päätee samat säännöt. Mutta jos ei päde, niin tätä kyllä ajolla pysty tekemään.

**Comment by Kati-Helle** [comment]
Helle ok.

**Comment by Hanna-Lumme** [comment]
Lumme ok.

**Comment by emta001** [comment]
Onko tämä tiketti vielä ajankohtainen? Onko Vaskissa vielä tarvetta tehdä korjausajoja ja jos on, niin millä spekseillä?

**Comment by ajrajala** [comment]
Tuumattiin, että speksaaminen ei ole ihan yksiselitteistä eikä asia ole kiireinen vaan näitä voidaan siivota pikkuhiljaa pois. Meidän puolesta tiketin voi siis sulkea, jos tässä ei ollut enää muuta keskeneräistä.
