### ISSUE TITLE
Erikoistilan asettaminen osalle yksikön MAPK niteistä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#573]
### Tukipyyntö

MAPK:ssa hyllyssä oleville niteille pitäisi asettaa notforloan-tila '4' maanantaiaamuna 5.6.

Tuossa taannoin tiketin #534 yhteydessä Vaskin tuotannossa ilmeni hidastelua/katkoksia samaan aikaan kun muutosajo oli pyörimässä (ensimmäisenä muutettu isoin nidejoukko oli 37 879 nidettä). 

Onko tässä työpyynnössä edessä sama ongelma, kun muutettavia niteitä on haun perusteella peräti vajaa 64 000? Eli pitääkö joukkoa jollain tavalla palastella osiin sen sijaan että kerralla ajetaan erikoistila kaikille?

Muutettavan nidejoukon speksit (ilman mitään osiin jakamista) olisivat tällaiset:

- items.holdingbranch = 'MAPK'
- items.onloan IS NULL
- reserves.found IS NULL
- branchtansfers.itemnumber IS NULL OR branchtransfers.datearrived IS NOT NULL OR branchtransfers.datecancelled IS NOT NULL
- items.itemlost = 0
- items.norfoloan = 0

**Comment by emta001** [comment]
Muutos tehty seuraavasti:

`UPDATE items i LEFT JOIN reserves r ON (i.itemnumber = r.itemnumber) LEFT JOIN branchtransfers bt ON(r.itemnumber = bt.itemnumber) SET i.notforloan = "4" WHERE i.holdingbranch = "MAPK" AND onloan IS NULL AND itemlost = 0 AND notforloan = 0 AND r.found IS NULL AND ( bt.itemnumber IS NULL OR bt.datearrived IS NOT NULL OR bt.datecancelled IS NOT NULL);`

Niteet on talletettu aputauluun ks_20230605_items_ks573. Mutta noilla spekseillä muutos näyttäisi koskeneen 40 202 nidettä tuon vajaan 64 000 sijasta :thinking:

**Comment by ajrajala** [comment]
Kiitos! Oliskohan mulla jäänyt sitten tikettiä tehdessä jokin hakuehto pois ja määrä ollut siksi suurempi. 🤔 Tarkastelun perusteella muutos näyttää olevan ok, joten suljen tiketin.
