### ISSUE TITLE
Lista ei toimi tietueiden erämuokkauksessa

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#574]
### Mikä vikana?

Versionvaihdon jälkeen on tapahtunut jotain listojen käsittelylle. Kun käytän valmista listaa Valitse lista tietueista -välilehdellä ja valitsen MARC-muokkauksen pohjan, jonka mukaan tietueet muokataan, saan vain ilmoituksen Yhtään tietuetta ei muokattu. Mitään tietoa muokattavista tietueista ei tule näytölle eli lista ei toimi tässä yhteydessä ollenkaan.

### Mitä pitäisi tapahtua

Listan nimekkeiden pitäisi tulla näytölle, samoin kuin tieto siitä, milloin tietojen käsittely on valmis. 

### Jotain muuta?

![2023kuvat060](https://github.com/KohaSuomi/Koha/assets/73887264/9ed192ce-f112-44b4-b903-d2c687eb747c)
![2023kuvat061](https://github.com/KohaSuomi/Koha/assets/73887264/382fbb8c-6c1d-4f14-9fb6-367c21ea57ed)

**Comment by lmstrand** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32255

Törmäsin ainakin tällaiseen yhteisön korjaukseen, jossa korjaantuu tiedoston lataaminen.

**Comment by lmstrand** [comment]
Tuotu yhteisöstä sivustotemplateen liittyviä patcheja branchiin ksdev/ks-0111-KD-G574-batch-modify-bib-lists. Testeillä testattavana.

**Comment by lmstrand** [comment]
Korjauksissa pitäisi olla mukana myös ylempänä mainittu listan tuonti tiedostosta, joka on ilmeisesti ollut rikki myös.

**Comment by pknuuti** [comment]
Toimii. Tein uuden listan, lisäsin siihen nimekkeitä ja tietueiden erämuokkauksen kautta sain muokattua tietueita.

**Comment by piiaseme** [comment]
Testattu samalla tavalla kuin Vaarassa ja mielestäni toimii oikein OUTIssakin.

**Comment by lmstrand** [comment]
Kiitos testeistä, viedään tuotantoon tiistaiksi.

**Comment by lmstrand** [comment]
Korjaus tuotannossa.
