### ISSUE TITLE
Kaksi käännösvirhettä liittyen takaajiin/taattaviin

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#577]
### Mikä vikana?

1.
Järjestelmäasetus NoIssuesChargeGuarantees 	
Prevent a patron from checking out if the patron has guarantees owing in total more than EUR in fines. 

Käännös nyt
Estä asiakasta lainaamasta, jos hänen **takaajalla** on maksuja enemmän kuin EUR maksuja. 

Pitäisi olla
Estä asiakasta lainaamasta, jos hänen **taattavillaan** on maksuja enemmän kuin EUR maksuja. 

2.
Asiakkaan lainaus- ja tiedot-näytöllä Huomio-osiossa näkyvä huomautus takaajalla, jos taattavilla on maksuja: 

Charges: Patron's guarantees collectively owe xx. 
Käännös nyt
Maksut: Asiakkaan **takaajilla** on maksuja xx. 

Pitäisi olla
Maksut: Asiakkaan **taattavilla** on [yhteensä] maksuja xx. 

### Jotain muuta?

![maksut](https://github.com/KohaSuomi/Koha/assets/99244794/44ce1b2c-75b9-4051-9e5e-f46274eb3d90)

**Comment by AnneliO** [comment]
Korjattu Koha-Suomen käännöstiedostoihin sekä yhteisössä version 22.11 ja 23.05 käännöksiin. Korjaukset tulevat näkyville seuraavan buildin jälkeen.

**Comment by Tuomas-Kyyti** [comment]
Kunnossa.
