### ISSUE TITLE
Varausjonot muodostuvat väärin päivityksen jälkeen

### ISSUE THREAD

**Issue by jarmotikka2** [KohaSuomi/Koha#578]
### Mikä vikana?

Kyytin Varausjono-toiminto on mennyt päivityksessä jotenkin rikki. Suuri osa poimittavista varauksista menee joko väärän toimipisteen jonoon tai ei minkään toimipisteen jonoon. 

Kävin läpi Hyllyvaraukset-raportin antamia tuloksia ja siellä listatuista poimintaa odottaneista 132 Haminan pääkirjaston varauksesta 14 oli väärän toimipisteen listalla (= eivät noudata kuljetusten painomatriisin sääntöjä) ja 58 ei ollut missään varausjonossa (= varausjonosivun Kirjasto-suodattimen arvona "Kaikki"). Sama ongelma on myös muissa Kyytin varausjonoja käyttävissä toimipisteissä.

Tässä vielä [tarkempi lista läpikäydyistä varauksista](https://github.com/KohaSuomi/Koha/files/11554597/Varausanalyysi.xlsx) (punaisella merkatut varaukset eivät olleet missään jonossa, keltaiset olivat väärässä jonossa ja vihreät olivat oikeassa jonossa)

En ole keksinyt vielä mitään logiikkaa sille mitkä varaukset menevät väärin tai eivät ilmesty ollenkaan jonoon.

### Mitä pitäisi tapahtua

Jokainen varaus menee johonkin varausjonoon ja varausten jaottelu noudattaa kuljetusten painomatriisin arvoja.

**Comment by janPasi** [comment]
Varausjono-raportti ei ole ollut varsinaisesti meidän aktiivisesti kehittämä ja tukema raportti. Sitä on toki saanut käyttää jos se on toiminut, mutta ensisijassa on suositelty käyttämään Koha-Suomen versiota hyllyvarausraportista. 

Molemmissa raporteissa on ongelmansa. Hyllyvarausraportti ei tue kuljetusten painomatriisia, joten se ei osaa "optimoida" kuljetuksia ollenkaan, vaan "optimointi" jää henkilökunnan hoidettavaksi. Varausjono-raportti puolestaan näyttää kerrallaan ainoastaan yhdestä kirjastoyksiköstä poimittavat varaukset, jolloin varauksia poimiva henkilö ei näe onko varausta oikeasti järkevää ottaa kiinni kyseisestä kirjastoyksiköstä vai olisiko parempi jättää sen jonkun toisen (lähemmän tai parempien kuljetusyhteyksien päässä olevan) kirjastoyksikön poimittavaksi.

Tilanne tällä hetkellä tosiaan on se, ettei varausjono raporttia aktiivisesti tueta, mutta tämä käytäntö voi kyllä vaatia tarkistamista tuo painomatriisin vuoksi. Kahta periaatteessa rinnakkaista raporttia ei ole järkevää ylläpitää, joten jos päädytään ottamaan käytttöön varausjono-raportti, täytyy samalla pohtia Koha-Suomi spesifista hyllyvarausraportista luopumista.

**Comment by ajrajala** [comment]
Hyllyvarausten optimointi on Vaskissa/Turussa ollut säännöllisesti tapetilla (viimeksi nyt keväällä). Hyllyvarausraportti koetaan työlääksi lukea ja vaikka hyllyvaraukset on ohjeistettu poimimaan tietyllä logiikalla, ei ohjetta aina noudateta jolloin käyttäjän tekemä optimointi ei toteudu.

Kannattaisin siis kyllä sitä, että tämä asia otettaisiin keskusteluun/tarkasteluun. 🙂 Varausten määrä ei vaikuta olevan vähenemään päin, minkä vuoksi optimoinnin tarvekin on varmaan vain kasvanut tässä viime vuosina.

**Comment by janPasi** [comment]
Pitäisiköhän tästä tehdä erillinen tiketti ja viedä se asiantuntijaryhmään?

**Comment by jarmotikka2** [comment]
Jos pystyt tekaisemaan, se olisi hienoa. Luulen että tämä etenee sujuvammin sinun kauttasi, jos tämä tulee puheeksi kokouksissa, joihin en itse juuri osallistu.

Muutama kommentti:
> janPasi: Toisaalta jos varaukset päätyvät yksikkökohtaisille varauslistoille painomatriisin mukaisesti ja painomatriisit on määritelty oikein, onko tämän näkeminen tarpeenkaan?

Haminassa ja Kotkassa ei ainakaan ole koettu ongelmaksi, että käyttäjä näkee vain yhden toimipisteen varausjonon kerrallaan. Kun matriisin säännöt sai alkusäädön jälkeen kuntoon, tarve muiden toimipisteiden varausten tarkastamiseen on ollut hyvin satunnaista.

> ajrajala: Hyllyvarausraportti koetaan työlääksi lukea ja vaikka hyllyvaraukset on ohjeistettu poimimaan tietyllä logiikalla, ei ohjetta aina noudateta jolloin käyttäjän tekemä optimointi ei toteudu.

Täällä on sama työläyden kokemus hyllyvarausraportista. Se on korostunut nyt, kun on jo totuttu varausjonoihin ja jouduttiin palaamaan päivityksen jälkeen hyllyvarausraporttiin. Varausjonoissa on tietysti alussa virittämistä, mutta kun jonot saa kuntoon, ne ovat varausten poimijan kannalta yksinkertaisempia.

**Comment by ajrajala** [comment]
Jeps, juttelen tästä pääkäyttäjäpalaverissa ja teen sitten kehitysehdotuksen asiantuntijaryhmälle jos pääkäyttäjäryhmästäkin löytyy kannatusta. 🙂

**Comment by jarmotikka2** [comment]
Mainiota, kiitos 🙂

**Comment by ajrajala** [comment]
Pääkäyttäjäryhmässä oli niin vähän osallistujia näin kesäkuussa, että todettiin paremmaksi keskustella tästä vasta lomien jälkeen laajemmalla kokoonpanolla. Otan asian esille uudelleen silloin.

**Comment by janPasi** [comment]
Varausjono-raportti on tosiaan meillä täysin yhteisön toteutus eikä raporttiin ole missään vaiheessa koskettu Koha-Suomessa. Raportti on varsin hölmösti toteutettu. Se toimii siten, että tietokannassa oleva taulu tyhjennetään aluksi jokaisen ajon yhteydessä. Jos raportti satutaan lataamaan käyttöliittymässä juuri silloin kun taulu on tyhjennetty, voi raportin sisältö olla puutteellinen. On mahdollista, että toiminnallisuutta on Kohan nyt käytössä olevassa versiossa muutettu aiempaan nähden, jolloin tämä ongelma tulee näkyvämmäksi kuin ennen.

Raporttia päivitetään tällä hetkellä minuutin välein, joten voi olla että taulun "keskeneräisyyshetkeen" on melko helppo osua. Kokeillaan hieman purkkaratkaisuna raportin ajon harventamista vartin välein tapahtuvaksi, mutta oikeasti se koko hoito pitäisi kyllä kirjoittaa uusiksi. Vanhaa listaa pitäisi tarjoilla aina siihen asti kunnes uusi on kokonaan valmistunut, samaan tapaan kuin Koha-Suomi versio hyllyvarausraportista toimii.

Teen muutoksen ajastuksiin ja sen jälkeen voidaan kokeilla näyttävätkö tulokset järkevämmiltä. Jos raportti vielä silloinkin näyttää puutteelliselta, voi kokeilla paukutella F5:ta selaimesta. En takaa, että tästä on apua, mutta saadaanpahan ehkä ainakin rajattua ongelmaa hieman. Mahdolliset muut korjaukset raportin toimintaan pitäis varmana kuljettaa yhteisön kautta.

**Comment by janPasi** [comment]
Ajastusmuutokset on tehty.

**Comment by MikkoLiimatainen** [comment]
Varausjono vaikuttaa antavan ihan hyviäkin tuloksia, mutta suuri osa tarjotuista varauksista on sellaisia, jossa nide on kuljetuksessa, eikä muuta "vapaata" nidettä ole.

Vastaavasti osa niteistä, jotka ovat vapaana, eivät näytä tulevan jonoon ollenkaan vaikka ne voisivat täyttää varauksen.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 13.5.2024: Asiantuntijaryhmässä on päätetty, että Varausjono-raporttia ei tueta. Ylläpidetään ja kehitetään Hyllyvarausraporttia.

**Comment by jarmotikka2** [comment]
Ok. Käytellään jatkossa hyllyvarausraporttia.

**Comment by AnneliO** [comment]
Varausjono-linkin voi piilottaa seuraavalla IntranetUserCSS:llä:

```
/* Piilota Varausjono-linkki Lainaus ja palautus -sivulla */
a.circ-button[href="/cgi-bin/koha/circ/view_holdsqueue.pl"] { display: none;}

/* Piilota Varausjono-linkki Lainaus ja palautus -sivupalkista valikosta */
div#navmenulist a[href="/cgi-bin/koha/circ/view_holdsqueue.pl"] {display: none;}
```

Tämä löytyy versionvaihdon wikistä. Suljen tiketin.
