### ISSUE TITLE
Tarkan haun hakutuloksia ei esitetä järjestelmäasetuksessa valitun mukaan

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#579]
### Mikä vikana?

Ainakaan Siilinjärvellä defaultSortField ja defaultSortOrder eivät tarkassa haussa toimi, jos valitsen julkaisuajan mukaan, laskevassa järjestyksessä/uusimmat ensin.

Hassua, jos klikkaan satunnaisen tietueen satunnaista asiasanaa tai vaikka tekijää, uusi haku kuitenkin tottelee asetusta.

**Comment by lmstrand** [comment]
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32301

**Comment by AnneliO** [comment]
Bugin korjaus on backportattu myös versioon 22.11, onko tarvetta tuoda meille vai otetaanko mukaan vasta seuraavassa versiossa?

**Comment by pknuuti** [comment]
Kannattaisin korjauksen tuomista, jos ei ole kovin vaikea toimenpide.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 3.8.2023: Tuodaan meillekin.

**Comment by AnneliO** [comment]
Testasin OUTIn tuotannossa ja minusta tämä tuntuisi toimivan nyt. Testaatko? :)

**Comment by pknuuti** [comment]
Vaaran tuotannossakin näyttäisi toimivan oikein.

**Comment by ReettaSiili** [comment]
Tuntuisi nyt toimivan Siilissäkin. Taidan sulkea tämän.
