### ISSUE TITLE
Tietueen kuvailun virheilmoituksen Mene kenttään -linkki ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#580]
### Mikä vikana?

Kuvailu-toiminto ilmoittaa tietuetta tallentaessa, kun tietueelta puuttuu esim. pakollisen kentän arvo. 
Ilmoituksessa on mainittuun puuttuvaan kenttään Mene kenttään -linkki, joka ei nyt vie ilmoituksessa mainittuun kenttään eikä muuallekaan.

Esimerkki Helle-tietueesta (biblionumber=1354970). Tietueelta puuttuu pakollinen 084-kenttä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/29f4f8b2-a780-46c4-9778-bcede982bb0b)

**Comment by Kati-Helle** [comment]
Olisikohan tässä nyt jotain muutakin. Siirryin tietueen 0-välilehdelle tarkistamaan, onko tietueella 084-kenttä.
Tietueella on 084-kenttä eli ilmoituksessa maiitut arvot.

Sen sijaan Helle-tietueen korvaavalla TäTi-tietueella ei ole 084-kenttää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ca401901-400d-4033-bbbc-452517836c43)

Sain tiedon, että 942c eli aineistotyyppikentän osalta Koha oli toiminut vastaavalla tavalla. 
(Onko niin, että TäTi-tietueella ei edelleenkään pitäisi olla 942c-kenttää eli aineistotyyppiä?)

**Comment by Kati-Helle** [comment]
Testasin tietukorvauksen vielä TäTi-tietueella Helle-tietueelle biblionumber=1354970.
(Tälläkin tietueella on 084-kenttä, jonka puuttumisesta Koha virheilmoittaa.)

Helle-tietueen kentät
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/3a401ed4-63e0-43ed-be9a-44fcce7a3938)

TäTi-tietueen kentät
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9c7f1e96-b9dd-4a20-8caa-cfb306db261d)

Korvaan Helle-tietueen ja tarkistan 942c-kentän. Helle-tietueella on edelleen aineistotyyppi
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ead6422c-b860-4b86-9503-a163eb7391a3)

Tallennan Helle-tietueen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/abf9a8e9-d020-4590-b827-689e1252a49a)

Klikkaan ilmoituksen Mene-kenttään-linkkiä. Linkki ei vie 084-kenttään, vaan 9-välilehden alkuun 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/480c01cb-772b-4e70-9953-f6d651822554)

Siirryn 0-välilehdelle, jossa tietueen 084-kenttä tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/bdc1a03e-4f99-4cee-84ce-bb9efbc84473)

**Comment by AnneliO** [comment]
Testasin tätä Biblibren sandboxissa ja siellä Mene-linkit toimivat. Kokeilin myös poistaa käytöstä testiltä kaikki IntranetUserJS:t ja IntranetUserCSS:t, eikä niiden poistolla ollut merkitystä. Muistelen myös, että olisin noita linkkejä nexteillä jossain vaiheessa testannut ja ne toimi silloin. Mutta en ole muistikuvasta 100 % varma.

Kommenteissa mainitut yhdistelyt ja tietuekorvaamiset ei ymmärtääkseni liity tähän linkki-ongelmaan, joten teetkö Kati niistä tarvittaessa omat tikettinsä (yksi ongelma/tiketti). :)

**Comment by Kati-Helle** [comment]
Tarpeetontahan tuo korvaustoiminnon käyttö oli ongelman kannalta eli tarvetta uuteen tikettiin ei Anneli ole :) 
Tein tiketin esimerkin Helle-tietueen korvaamalla eli samaan tapaan, kuin ongelmaan törmännyt oli toiminut. Yhdistely ja yhdistelysäännöt toimivat oikein.

**Comment by pknuuti** [comment]
Itse asiaan eli otsikossa määriteltyyn toimintaan. Tarkoitko Anneli, että versionvaihdon jälkeen tämä ongelma pitäisi olla korjattuna? Näyttäisi liittyvän suomenkieliseen pohjaan eli kun vaihdoin kielen englanniksi, linkki toimi.

**Comment by Kati-Helle** [comment]
Kokeilin Helle-tuotannon suomenkielisessä Kohassa. Kuvailu-osion Uusi tietue -toiminto avasi uuden tietueen. Klikkasin tietueen Tallenna-painiketta lisäämättä tietueelle tietoja. Tietue-näkymää tallennuksen jälkeen:

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f57d46bf-6109-4e3c-898a-3e27fbbef62d)

Kokeilin kaikkien kuvassa näkyvien kenttien Mene kenttään -linkit tietueen Osa 0 -osiossa:
- 005 toimi
- 008 toimi
- 041 toimi
- 084 toimi
- 245 ei toiminut
- 942 ei toiminut

Siirryin tietueen Osa 2 -osioon
- 245 toimi (molemmat 245-kentät toimivat)

Siirryin tietueen Osa 9 -osioon
- 942 toimi

**Comment by AnneliO** [comment]
Testailin nyt myös ja kuten Kati tuossa on huomannut, niin linkki toimii, jos ensin menee itse oikealle välilehdelle ja sitten klikkaa Mene-linkkiä. Kielivalinnalla ei ole merkitystä eli sekä suomenkielisessä että englanninkielisessä tapahtuu tuo sama.

PTFS Europen sandboxissa linkki osaa mennä automattisesti myös oikealle välilehdelle.

Kun hiiren vie linkin päälle ja katsoo sen osoitetta, niin linkin osoite on sama sekä meidän versiossa että sandboxissa. Ja jos linkkejä katsoo selaimen Tarkastele-toiminnolla, niin minun silmään ne näyttää samanlaisilta meillä ja sandboxissa.

**Comment by atarnus** [comment]
Nykyversiossa addbiblio.tt:ssä selectTab() -funktiolle syötettävä parametri on jostain syystä vääränlainen. Nextillä siihen on tullut muutos, ja tabin vaihto toimii taas. Nextin mukainen koodinpätkä ei kuitenkaan toimi vielä nykyversiossa, se on riippuvainen jostain muista muutoksista.

Sekä minun fiksillä että nextissä esiintyy tabi-asian korjaannuttua toista ongelmaa: sivu ei skrollaannu ihan perille asti haluttuun kohtaan tabin vaihtumisen jälkeen (esim. ruutu hyppää kentän 910 kohdalle eikä mene kenttään 942 asti). Asia vaikuttaa korjaantuvan lisäämällä pienen viiveen vaihdon ja skrollauksen väliin (esim. 200 millisekuntia).

Tämä viive on tarpeen siis myös uudessa versiossa, ja kannattaa ottaa testattavaksi.

Fiksattu funktio addbiblio.tt:ssä:

```
$("body").on("click", ".linkfield", function(e){
  e.preventDefault();
  var tab = $(this).data("tab");
  var field = $(this).data("field");
  var tablink = "#tab" + tab + "XX";
  selectTab( tablink );
  setTimeout(window.scrollTo, 200, 0, getScrollto( field, "toolbar" ));
});
```

**Comment by atarnus** [comment]
Vietävä testeille.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii. 
Seuraavia pakollisia osakenttiä ei täytetty -Ilmoituksen Mene kenttään -linkki vie kyseiseen arvottomaan kenttään. Kentässä on keltainen korostusväri.

**Comment by MikkoLiimatainen** [comment]
Vaski-nextissä toimii samoin kuin Hellessäkin

**Comment by Kati-Helle** [comment]
Mene kenttään -linkki toimii. Suljen tiketin.

**Comment by atarnus** [comment]
Tein tuosta viiveen tarpeesta yhteisöön tiketin. Koska kyse oli asiasta, jonka bongasin tämän tiketin yhteydessä, eikä nimenomaan tämän tiketin alkuperäisestä ongelmasta, niin ajattelin sen kuuluvan enemmän minun tehtäväkseni.

https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36949
