### ISSUE TITLE
Taustatöissä hitautta

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#582]
### Mikä vikana?

OUTIssa taustatöissä on hitautta. Jonotuksessa kestää kauan, lähes puoli tuntia. Itse työ tapahtuu hetkessä. 

Hitautta esiintyy ainakin näissä:
- niteiden poisto eräajona
- tietueiden muokkaus eräajona
- osakohteiden tuominen

### Mitä pitäisi tapahtua

Työn pitäisi siirtyä jonosta työn alle lähes samantien. Jonotuksen, työn aloituksen ja lopetuksen tulisi normaalisti tapahtua saman minuutin aikana. 

### Kuinka toistaa ongelma/asia

1. Mene niteiden poistoon eräajona
2. vedä poistettavien niteiden viivakoodit laatikkoon (Lista viivakoodeista (koodi per rivi):) -> Jatka
3. Klikkaa Poista valitut
-> työ menee jonoon

**Comment by lmstrand** [comment]
Testeille on nyt tuotu tämä yhteisömuutos, jossa Elasticsearch-indeksityöt menevät omalle käsittelijälleen ja muut työt pääsevät samoin tein käsittelyyn niiden töiden ohi. Kimppojen pääkäyttäjät voisivat testata toimintaa luomalla erilaisia taustatyöjonoja ja tarkkailemalla jonojen tyhjentymistä. Itse lainasin Vaski-testillä itselleni 800 ET-lehteä erälainauksella :D enkä tiedä miten palauttaa ne virkailijaliittymässä kuin yksi kerrallaan. Joka tapauksessa tekemäni niteiden eräpoistotyö tuli samalla sekunnilla käsiteltyä elastic-jonon ohi noiden worker-palvelujen käynnistyttyä. Vaski-testin työjonoon synnyttämiäni elastic-töitä oli jäänyt virheiden kerra jumiin, mutta ne oli saatu aikaan lainaamalla ennen, kuin tuo uusi koodi, joka sisältää jonkinlaista virheenkorjausta oli testeillä paikallaan. Poistin nämä aloitettu-statuksella olevat työt.

Raportoikaa, jääkö uusia töitä vielä roikkumaan aloitettu-statuksella ja ilmoitelkaa jos on muita huomioita.

Testeillä siis käytössä normaaleille taustatöille vain yksi prosessi (master, ei forkkeja sallittu) + elasticsearch-indeksoija jolla yhteisön oletuksena 10 indeksointipyyntöä niputettuna (batch).

**Comment by LeenaKinnunen** [comment]
Lapin testillä iso massa eräpäivien muutoksia meni nopasti läpi.

**Comment by AnneliO** [comment]
> Lapin testillä iso massa eräpäivien muutoksia meni nopasti läpi.

Eräpäivämuokkaukset eivät näyttäisi menevän taustatöihin. Tai ainakaan niitä ei löydy taustatöiden suodatuksen alasvetovalikosta.

Yksittäisen työn koko ei ole tässä sinänsä se ongelma vaan se, että töitä tulee paljon jonoon nopealla tahdilla. Eli paljon lainauksia ja palautuksia, jotka aiheuttavat indeksointitarpeen ja siihen sitten rinnalle paljon esim. niteiden poistoja ja erämuokkauksia.

**Comment by LeenaKinnunen** [comment]
> > Lapin testillä iso massa eräpäivien muutoksia meni nopasti läpi.
> 
> Eräpäivämuokkaukset eivät näyttäisi menevän taustatöihin. Tai ainakaan niitä ei löydy taustatöiden suodatuksen alasvetovalikosta.
> 
> Yksittäisen työn koko ei ole tässä sinänsä se ongelma vaan se, että töitä tulee paljon jonoon nopealla tahdilla. Eli paljon lainauksia ja palautuksia, jotka aiheuttavat indeksointitarpeen ja siihen sitten rinnalle paljon esim. niteiden poistoja ja erämuokkauksia.

Jaa, meillä testissä ja tuotannossa ei onnistu käynnistää tietueiden muokkauksen eräajoja, koska meiltä puutuu joku kuvailupohja? " Valittua kuvailupohjaa (id=2) ei ole olemassa tai toimintoa ei ole määritetty." Siinä on valinnat Hyllypaikka, Ikäraja, Kielikoodi. Mikä sääntö näitä nyt määrää?

**Comment by AnneliO** [comment]
MARC-muokkauksen pohjia voi muokata Kuvailu -> MARC-muokkauksen pohjat ([suora linkki](https://lappi-test.koha-suomi.fi/cgi-bin/koha/tools/marc_modification_templates.pl). Tuo kakkossääntö ei sisällä näköjään mitään toimintoja.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä eräpäivien erämuokkausta. Tein ilmeisesti yhden vähän isomman määrän (jota ei näy missään) ja unohdin ottaa valinnan esikatselusta pois. Sain listauksen muutettavista niteistä (pitkä, ei mainita montako niitä on), mutta lopullinen muokkaus kaatui virheilmoitukseen "Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server"

**Comment by AnneliO** [comment]
@pknuuti Eräpäivämuokkaukset eivät tosiaan mene taustatöihin, joten kannattaa testata muilla erämuokkauksilla. :)

**Comment by pknuuti** [comment]
Tein myös yhden nimeketietueiden muokkauksen ja se sujui nopeasti. Lähinnä tuo virheilmoitus tuossa eräpäivämuokkauksessa oli se pointti.

**Comment by AnneliO** [comment]
Teetkö päivi niistä tarvittaessa oman tikettinsä, koska ne eivät liity taustatöihin. :)

**Comment by LeenaKinnunen** [comment]
Lapin testissä toimii tietueiden muokkaus eräajona, jos valitsee tietueet hakutuloksesta tai muokkaa yksittäisiä tietueita. Jos lisää tietueet listalle ja lähtee muokkaamaan listan kautta, tulee vastaus yhtään tietuetta ei muokattu. Eli nykyisen Kohan ohjeen mukaan korin muokkaus onnistuu, mutta ohjeen mukaisesti ("valitsemalla valmiin listan Kohasta, tätä varten tee lista poistettavista[!! ]tietueista".] muokkaus ei onnistu.

**Comment by pknuuti** [comment]
Listaongelmasta on jo tiketti [Lista ei toimi tietueiden erämuokkauksessa#574](https://github.com/KohaSuomi/Koha/issues/574)

**Comment by Tuomas-Kyyti** [comment]
Testasin Kyytissä. Vajaan tuhannen niteen ja 50 tietueen erämuokkaus sekä muutamien lainojen aiheuttamat indeksipäivitykset ovat menneen nopeasti ja päättymismerkintä on tullut. Mutta ei tällä testauksella pääse tietenkään lähellekään tuotannon määriä.

**Comment by sksandel** [comment]
Testasimme Vaskissa siten, että käynnistimme mahdollisimman samanaikaisesti useamman niteiden muokkauksen eräajona (n 2000 nidettä) sekä varauksen peruutuksen eräajona ja lisäksi teimme indeksin päivitykseen liittyviä toimia. Ajot holahtivat läpi siten, että emme onnistuneet oikein keräämään jonoa. Vaikea luoda sellaista kuormaa, joka tuotannossa helposti syntyy.

**Comment by janPasi** [comment]
Viety tuotantoon, suljetki @piiaseme tiketin.

**Comment by lmstrand** [comment]
Minä voin sulkea.
