### ISSUE TITLE
TäTistä valunut vanhojen tietueiden päälle tietueita ilman kenenkään käsittelyä

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#583]
### Mikä vikana?

18.5. on valunut vanhojen tietueiden päälle TäTistä tietueita, vaikka niitä ei ole kukaan käsittellyt. 

Onko mahdollista, että jokin päivitys olisi taas päällä, joka aiheuttaa tietueen aktivoitumisen? 

### Jotain muuta?

Ainoa yhdistävä tekijä on se, että niitä on lainattu jossain 17.5.

**Comment by piiaseme** [comment]
Onko havaintoa onko poisto auttanut? Voisin päätellä siitä, että mitään ei ole tästä ongelmasta kuulunut enää kevään jälkeen, että on auttanut, mutta jos Antti vielä kuittaat, niin suljetaan tiketti vasta sun kuittauksen jälkeen :)

**Comment by AnttHeik** [comment]
Näyttäisi auttaneen, koska en ole huomannut enää viime aikoina tällaista. Sulje pois vaan :)

**Comment by piiaseme** [comment]
Suljen tiketin.
