### ISSUE TITLE
Laina- ja maksusäännöt: Verkkokirjaston nidevaraukset -asetus

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#589]
### Mikä vikana?

Jos Laina- ja maksusääntöjen "Verkkokirjaston nidevaraukset" sarakkeessa on valmiina "Pakota" -asetus, ei sitä voi muuttaa arvoon "Älä salli". Sen sijaan jos arvo on valmiiksi "Älä salli" voi sen muuttaa --> Pakota ja taas takaisin --> Älä salli.

**Comment by MikkoLiimatainen** [comment]
Minusta tuo alunperin kuvattu ongelma on poistunut, mutta tietyissä tilanteissa muokattavan rivin tiedot eivät siirry muokkausriville, jos muokattavaa riviä vaihtaa tallentamatta. Näissä tilanteissa rivien muokkaukset saattavat mennä täysin sekaisin, kun Koha voi tulkita muokkaavansa aivan eri tietoja kuin on tarkoitus.

Käytännössä tämä ongelma aiheutuu siitä, että muokkaa nappia painettaessa ei muokkausrivin valintoja tyhjennetä oikein, vaan select-elementit voivat saada useille option-valinnoille selected-arvon, jolloin Koha ei tiedä mikä on oikeasti muokattava arvo.
![Verkkokirjaston nidevarauksen valinnan tupla selected arvot 2023-11-17 124425](https://github.com/KohaSuomi/Koha/assets/98884651/afe83a4f-43f6-4879-bee7-8345dc3acb15)

Tein tästä tiketin yhteisöönkin jokin aika sitten. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34826

Periaatteessa korjaus pitäisi olla melko yksinkertainen, eli noiden selected-arvojen tyhjentäminen muokkaus-napin painamisen yhteydessä ennen kuin uusia selected-arvoja asetetaan.

**Comment by MikkoLiimatainen** [comment]
Emmillä on korjaus tähän ongelmaan bugzillan tiketissä [https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34585](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34585)

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 2.9.2024: Korjattu versioon 24.11, tulee meille sitten, kun otetaan se versio käyttöön.

**Comment by emta001** [comment]
Tuota, tuo bugin [34585](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34585) korjaus on jo meillä matkassa ja sillä on korjattu meiltä [tämä ongelma](https://github.com/KohaSuomi/Koha-translations/issues/24). Kun tätä tikettiä lueskelee, niin alkuperäinen ongelma vaikuttaisi korjaantuneen jo. 

@sksandel varmistaisitko, että onko tää enää ongelma. Jos ei oo, niin tiketin voisi sulkea.

**Comment by sksandel** [comment]
Testattu versiossa 24.05. Ongelma poistunut, suljen tiketin.
