### ISSUE TITLE
Nidehaun viivakoodi-linkistä aukeaa tietueen kaikki niteet

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#591]
### Mikä vikana?

Tämä siis huomattiin tiketissä KohaSuomi/Koha-22x#107. Annin kommentti:

_Tuli kuitenkin mieleen testata vielä siirtyminen nidehaun tuloksista. Siellä niteen viivakoodia klikkaamalla päätyy edelleen tietueen kaikkiin niteisiin (sivun alkuun, ei tietyn niteen kohdalle). Tuotannossa kun testasin niin nidehaun tuloksissa niteen viivakoodi -linkki vie Niteet-sivulle suoraan oikean niteen kohdalle._

### Mitä pitäisi tapahtua

Nidehaun viivakoodi-linkistä pitäisi päätyä halutun niteen kohdalle, ei sivun ylälaitaan.

### Kuinka toistaa ongelma/asia

1. Tee nidehaku.
2. Klikkaa jotakin viivakoodi-linkkiä.
3. Siirryt tietueen Niteet-sivulle, mutta sivun alkuun, etkä tietyn niteen kohdalle kuten pitäisi.

**Comment by emta001** [comment]
Tähän ei ole löytynyt minkäänlaista ratkaisua edes yhteisöstä, jossa ominaisuus toimii oikein. Asetan tämän "Odottaa"-tilaan ja katsotaan sitten versionvaihdon jälkeen toimiiko tämä kuten pitää.

**Comment by Kati-Helle** [comment]
Helle-Nextillä NIdehaun tuloksen viivakoodi-linkki vie kyseisen viivakoodin kohdalle tietueen nidelistauksessa.

**Comment by ajrajala** [comment]
Samoin Vaski-nextillä katsottu, että viivakoodilinkki vie nyt nidehausta oikean niteen kohdalle.

**Comment by pknuuti** [comment]
Vaaran nextillä toimii myös oikein eli linkki vie oikean niteen kohdalle.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
