### ISSUE TITLE
Lumme: Asiakas ei saanut maksuja myöhästyneistä niteistä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#594]
### Mikä vikana?

Asiakas oli lainannut kaksi DVD:tä, joiden eräpäivä oli ollut 12.5. ja hän oli palauttanut ne 22.5. Näistä ei ollut mennyt myöhästymismaksua, vaikka kyseessä oli aikuisten puolen elokuvat. Asiakkaan ID on 240490 ja myöhässä palautetut elokuvat olivat (biblionumber) 787242 ja 2913580.

### Mitä pitäisi tapahtua

Myöhästyneistä aikuisten aineistosta pitäisi kertyä kimppakohtaisesti sovittu määrä maksuja per laina/per päivä. Tässä tapauksessa niin ei ollut käynyt.

**Comment by AnneliO** [comment]
Varmistan, että olihan kyseessä Varkauden niteet 915N01836456 ja 915N01965637?

**Comment by Hanna-Lumme** [comment]
Joo, kyllä!

**Comment by AnneliO** [comment]
Tässä on käynyt niin, että asiakas on maksanut maksunsa verkkomaksuna 22.5.2023 klo 18.40 ja palauttanut myöhässä olevat lainat 22.5.2023 klo 18.54 eli sen jälkeen, kun maksu on maksettu. Maksut lisätään asiakkaan "velkasaldoon" yöajoina eli ne eivät synny palautuksen yhteydessä.

Käytännössä maksut ovat kyllä syntyneet, mutta asiakas on maksanut ne ennen niteiden palauttamista. Tämän voi nähdä asiakkaan maksuista [Tapahtumat](https://lumme.koha-suomi.fi/cgi-bin/koha/members/boraccount.pl?borrowernumber=240490)-välilehdeltä kun järjestää tapahtumat Päivitetty-sarakkeen mukaan laskevasti (uusin ylinnä). Noiden niteiden kohdalla aikaleima on päivittynyt palautuksen yhteydessä.

**Comment by Hanna-Lumme** [comment]
Jaahas, on taas asianosaisella aivot perjantaikuvioissa, kun en tosiaan tuota havainnut tsekata. Parempi näin, ettei ollut isommasta ongelmasta kyse. Kiitos paljon! :)
