### ISSUE TITLE
Vaara: Enon kirjaston remontista aiheutuva kiinniolo

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#595]
### Tukipyyntö

Enon kirjasto on suljettu asiakkailta 26.6.-6.8.2023. Kirjasto avataan asiakkaille siis ma 7.8.23.

**Kirjaston tunnus JOE_ENO -> JOE_UIM**
Asiakkaiden varausten noutopaikaksi pitää muuttaa 26.6. alkaen JOE_UIM, mikäli noutopaikkana on JOE_ENO. Saako nämä muutokset kumottua elokuun alussa niille varauksille, jotka eivät ole jääneet kiinni kirjaston sulkuaikana? Koska asiakas voi itse vaihtaa valitsemansa noutopaikan varaamilleen niteille, muutoksen kumoaminen koskee vain niitä varauksia, joissa alun perin on ollut Eno noutopaikkana ja se on Uimaharju remontin ajan. Jos asiakas on vaihtanut jonku muun noutopaikaksi, sitä ei muuteta.
Uusia varauksia Enoon ei voi tehdä 9.6.-3.8.2023. (Poistan noutopaikkavalikosta tuolle aikavälille).

Enon kirjastossa oleva aineisto pitäisi laittaa **ei lainattavaksi ja ei varattavaksi 26.6.-6.8**. Auktorisoitu not_loanarvo 9 niteille, paitsi niille, joilla on auktorisoitu arvo -1 tai 6. Aineisto pakataan laatikoihin eikä niihin pääse käsiksi remontin aikana.

Lyhyesti:
niteen sijainti JOE_ENO, ei lainattavissa, ei varattavissa 26.6.-6.8. 
varauksen noutopaikka JOE_ENO -> JOE_UIM 26.6.-6.8.

**Comment by emta001** [comment]
Varoivaisesti uskallan luvata, että noutopaikan saa palautettua alkuperäiseksi noilla ehdoilla.

**Comment by emta001** [comment]
Varauksien noutopaikka muutettu, muutos koski 432 varausta.

```
create table ks_230620_reserves_595 like reserves;
insert into ks_230620_reserves_595 select * from reserves where branchcode='JOE_ENO';
update reserves set branchcode='JOE_UIM' where branchcode="JOE_ENO";
```

**Comment by emta001** [comment]
Niteiden sijainti muutettu, muutos koski 25854 nidettä.

```
create table ks_230626_items_595 select itemnumber, notforloan from items where holdingbranch = "JOE_ENO" and notforloan not in(-1, 6);
update items set notforloan = 9 where holdingbranch = "JOE_ENO" and notforloan not in(-1, 6);
```

**Comment by pknuuti** [comment]
Enon kirjaston avaaminen lähestyy. Saisiko heti maanantaiaamuna 7.8. aineiston takaisin saatavana-tilaan. Myös ne asiakkaiden varaukset, jotka on siirretty Uimaharjun kirjastolle sulkuajaksi, ne voisi palauttaa takaisin Enoon (mikäli asiakas ei ole itse muuttanut varauksen noutopaikkaa välillä). Toivottavasti tämä onnistuu.

**Comment by paxed** [comment]
Aineiston notforloan palautettu tällä rimpsulla, joka palautti aineistolle jota muutettiin sen alkuperäisen notforloan-arvon, mutta vain jos ne on edelleen JOE_ENOssa ja notforloan-arvo on edelleen 9.

update items i left join ks_230626_items_595 ki on (ki.itemnumber=i.itemnumber) set i.notforloan=ki.notforloan where i.holdingbranch='JOE_ENO' and i.notforloan=9 and ki.itemnumber is not null;

Tämä muutos koski 21758 nidettä - noiden muiden tila varmaan muuttunut tässä välillä?

**Comment by paxed** [comment]
Varaukset palautettu tällä rimpsulla, mutta tämä palautti vain ne, joita alunperin muutettin, ja joilla on edelleen noutopaikkana JOE_UIM, eikä varausta ole vielä täytetty (found is null)

update reserves r left join ks_230620_reserves_595 kr on (kr.reserve_id=r.reserve_id) set r.branchcode='JOE_ENO' where r.branchcode='JOE_UIM' and r.found is NULL and kr.reserve_id is not NULL;

Muutos koski 158 varausta.

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
