### ISSUE TITLE
Vaara: Ongelmallinen nide

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#597]
### Mikä vikana?

Nurmeksen kirjastosta tuli tieto, että asiakas ei pääse verkkokirjaston kautta käsiksi varauksiinsa eikä saa myöskään tehtyä uusia varauksia. Asiakkaan varauksista löytyi nimeke, jossa on hänelle kuljetettavana varaus, jonka nidetunnus antaa virheilmoituksen APIsta

![kuva](https://github.com/KohaSuomi/Koha/assets/73887264/fab87223-b83b-4abe-a917-103d0a7bb4ad)

Tietueen osoite on omituisessa muodossa, sekä nimeke- että nidetunnus on tuplasti:
https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=101607084&biblionumber=11710603&bi=11710603#item101607084

Voisiko tuon korjaus auttaa asiakkaan varausten näkymisongelmaan?

**Comment by emta001** [comment]
Sinne tulee seuraava virhe:

_Object { message: "Month out of range.", path: "/body/replacement_price_date" }_

Eli luultavasti tuolla on nyt 0000-00-00 arvo tuossa kentässä.

**Comment by emta001** [comment]
> Sinne tulee seuraava virhe:
> 
> _Object { message: "Month out of range.", path: "/body/replacement_price_date" }_
> 
> Eli luultavasti tuolla on nyt 0000-00-00 arvo tuossa kentässä.

Joo, tuosta se kiikastaa. Tuon kun korjaa niin pitäisi toimia.

Vilkaisin samalla Vaaran kannan muutenkin, siellä on 39 nidettä joissa tuo replacementpricedate on "0000-00-00". Ne kannattaa korvata, koska ne aiheuttavat ongelmia sekä Finnan päässä että näemmä myös Varaukset-sivulla.

**Comment by pknuuti** [comment]
Miten löydän nuo virheelliset niteet?

**Comment by AnneliO** [comment]
Ne voi hakea esim. tällä tavalla raportilla:

select barcode from items where replacementpricedate='0000-00-00'

**Comment by AnneliO** [comment]
@pknuuti suljetko tämän tiketin, jos asia on kunnossa. :)
