### ISSUE TITLE
Lumme: Varausten noutoilmoituksissa häikkää

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#599]
### Mikä vikana?

Lumpeiden tektiviesteissä on osalta häikkää, mitä tulee sulkuajalla palautettuihin varauksiin. Tekstiviestit eivät ole osalta lähteneet ja niiden viimeinen noutopäivä olisi huomenna. Onko mahdollista ns. jatkaa tätä hakuaikaa? Eli vanhentuneet varaukset palautettaisiin normaalisti, mutta ne jäisivät kiinni samalle asiakkaalle eikä niistä menisi maksua. Näin asiakkaat saisivat lisäaikaa hakea varauksensa ja voimme seurata viestien perillemenoa.

**Comment by emta001** [comment]
Ajo tehty ja varauksien noutoajat siirretty viikon päähän.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon!

**Comment by Hanna-Lumme** [comment]
Tänään tuli kentältä tieto, että jostain syystä tekstiviesti-ilmoitukset eivät menneet vieläkään perille näille, joiden varausaikaa jatkettiin 29.5. Varaukset oli palautettu ensin automaatilla ja sen jälkeen Kohassa.

**Comment by emta001** [comment]
Tää jäi ikävästi kaiken muun jalkoihin, pahoittelut :sweat_smile: Tarvitseeko tälle tehdä vielä jotain? Onko näitä vielä tullut vastaan? Tuosta alkuperäisestä ongelmasta alkaa olla sen verran aikaa, että siihen tuskin löytyy enää ratkaisua.
