### ISSUE TITLE
Lumme: 500 error asiakastietoja lisättäessä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#601]
### Tukipyyntö

Asiakastietoja lisättäessa tuli 500: internal server error - Month out of Range -viesti. Asiakkaalla oli viesti, että henkilötunnus puuttuu ja kun virkailija oli lisännyt sen, ruutuun tuli kuvan mukainen ilmoitus. Ei ole tarvittaessa antaa asiakas-ID:tä, mutta nimi on tiedossa.

### Jotain muuta?

![500 error](https://github.com/KohaSuomi/Koha/assets/129748294/e7da09ef-d12b-44c8-bb96-57be1784ed96)

**Comment by AnneliO** [comment]
Tietokannassa on kaksi asiakasta, joilla on syntymäaika 0000-00-00:

264567 ja 269524

Noilta pitäisi ensin korjata syntymäaika hyväksyttävään muotoon ja vaihtaa Lumpeisiin sitten oikea versio [hetunlisäys-rimpsusta](https://github.com/KohaSuomi/Koha-22x/wiki/IntranetUserJS). Pyydän kehittäjiä korjaamaan syntymäajan.

**Comment by janPasi** [comment]
Asiakkaiden syntymäajaksi on vaihdettu tämä päivä, käytkö @Hanna-Lumme muokkaamassa oikeaksi.

**Comment by Hanna-Lumme** [comment]
Laitettu korjauspyyntö menemään kotikirjastoille. :)

**Comment by AnneliO** [comment]
IntranetUserJS-rimpsukin korjattu uudemmaksi. Seuraillaan, syntyykö näitä viallisia syntymäaikoja vielä rimpsun vaihdonkin jälkeen.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon! Mepä jäämme seurailemaan tilannetta. :)
