### ISSUE TITLE
RUPK-yksikön varausten keskeytys määräajaksi

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#602]
### Tukipyyntö

Ruskon pääkirjasto menee remontin vuoksi kiinni, minkä vuoksi pitäisi keskeyttää varaukset, jotka täyttävät nämä ehdot:

- branchcode = RUPK
- varaus ei ole vielä jäänyt kiinni (found = null)
- varaus ei ole entuudestaan keskeytetty (suspend = 0)

Keskeytys pitäisi tehdä 31.5., jos vaan suinkin onnistuu näin lyhyellä varoitusajalla. Keskeytysten viimeinen voimassaolopäivä on 9.8.2023 eli suspend_until pitäisi olla kaiketi 2023-08-09 23:59:59.

**Comment by lmstrand** [comment]
Ajettu:

```
insert into ks_230531_suspendreserves_kd602 select * from reserves where branchcode='RUPK'
    -> AND suspend=0
    -> AND found IS NULL;
Query OK, 234 rows affected (0.020 sec)

MariaDB [vaskiprod]> update reserves set suspend=1, suspend_until = '2023-08-09 23:59:59' where branchcode='RUPK'
    -> AND suspend=0
    -> AND found IS NULL;
Query OK, 234 rows affected (0.027 sec)
```

**Comment by ajrajala** [comment]
Kiitti, tämä ok!
