### ISSUE TITLE
Tietueen poisto ei onnistu

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#604]
### Tukipyyntö

OUTIssa tietueen 1846734 poisto ei onnistunut tuotannosta eikä testiltä. Poistettaessa tuli virhe 500 ja lokeilla näkyi seuraava ilmoitus:

C4::Biblio::_koha_delete_biblioitems(): DBI Exception: DBD::mysql::st execute failed: Duplicate entry '1846734' for key 'PRIMARY'

Tietuenumero löytyi deletedbiblioitems-taulusta. Emmi poisti tiedon sieltä sekä testillä että tuotannossa,  jonka jälkeen tietueen poisto onnistui.

**Comment by pirliis** [comment]
OUTIssa on taas nide (564N14990902, item91037), joka antaa virhettä 500, kun yrittää poistaa sitä.

**Comment by AnneliO** [comment]
Tuo nide 91037 löytyy myös deleteditems-taulusta. Se näkyy myös Tietoja Kohasta -> Järjestelmätiedot-sivulla.

**Comment by janPasi** [comment]
Poistin deleteditemsistä. Niteen poiston pitäisi nyt onnistua.

**Comment by pirliis** [comment]
Vielä tulee Virhe 500, kun yrittää poistaa nidettä niteen muokkaussivulla:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/3d8a5206-e317-40a3-9c92-b222d800002c)

**Comment by emta001** [comment]
Tuo kummitteli jostain syystä edelleen tuplana kannassa. Poistin sen, onnistuuko poistaminen nyt?

**Comment by emta001** [comment]
No mitä ihmettä. Nide on varmasti poistettu deleteditemsista, mutta poisto johtaa tuplaantumiseen. Miksi? :D

**Comment by pirliis** [comment]
Niteen poisto antaa yhä virhettä 500.

**Comment by janPasi** [comment]
Tämä nyt oikaistu Outissa, voisi testata.

**Comment by pirliis** [comment]
Poisto antaa vielä virhettä 500.

**Comment by pirliis** [comment]
Nyt epäsynkat on korjattu, mutta nide 564N14990902 antaa yhä virhettä 500, kun sitä yrittää poistaa. Mistähän tämä voisi kiikastaa?

**Comment by emta001** [comment]
> Nyt epäsynkat on korjattu, mutta nide 564N14990902 antaa yhä virhettä 500, kun sitä yrittää poistaa. Mistähän tämä voisi kiikastaa?

Nide oli vielä deleteditems-taulussa, poistin sen taas uudestaan. Onnistuiskohan poisto nyt?

**Comment by pirliis** [comment]
Antaa vielä virhettä 500. :(

**Comment by emta001** [comment]
Samainen nide käyttäytyy samalla tavalla myös testillä :D Jos tehtäisiin niin, että poistetaan tuotannosta tämä nide items-taulusta. Voidaan sitten testillä selvitellä, mikä ihme tuossa niteessä on vikana.

**Comment by emta001** [comment]
> Samainen nide käyttäytyy samalla tavalla myös testillä :D Jos tehtäisiin niin, että poistetaan tuotannosta tämä nide items-taulusta. Voidaan sitten testillä selvitellä, mikä ihme tuossa niteessä on vikana.

Eipäs muuten onnistu, tulee virhe:
```

MariaDB [outiprod]> delete from items where itemnumber = 91037;
ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`outiprod`.`collections_tracking`, CONSTRAINT `coltra-fk-items` FOREIGN KEY (`itemnumber`) REFERENCES `items` (`itemnumber`))
```

**Comment by emta001** [comment]
Johan selvisi, nide 91037 oli kiinni jossain OUTIn konversion aikaisessa kokoelmassa. Koha ei näemmä osaa valittaa noista asiallisesti, vaan vetää itsensä kiikkuun. Kokoelman nimi on siis "Konversiossa OUPK:ssa olleet siirtolainat", kannattanee käydä poistamassa tuo kokonaan.

**Comment by pirliis** [comment]
Kokoelman saa poistaa.

**Comment by pirliis** [comment]
Näköjään nidekin on nyt poistettu. Kiitos! Suljen tiketin.
