### ISSUE TITLE
deleted-tauluissa biblioitemnumberin ja biblionumberin epäsynkka

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#606]
### Tukipyyntö

Myös deletedbiblioitems- ja deleteditems-tauluissa on epäsynkkaa biblioitemnumberissa ja biblionumberissa. Tämä aiheuttaa mm. sen että tietuetta ei saa poistettua, jos poistettavan tietueen biblionumber löytyy deletedbiblioitemsissa biblioitemnumberina.

Eli myös deleted-taulujen epäsynkka pitää korjata.

Liittyy mm. tiketteihin #604 ja #349.

**Comment by janPasi** [comment]
Nämä on nyt oikaistu helle, outi, siili, vaski, vaara, kyyti ja lumme. Lappi on vähän erityistapaus, täytyy ihmetellä se erikseen.

**Comment by janPasi** [comment]
Lapin korjaus täytyy tehdä tähän tapaan:

1. Päivitetään biblioitemsin virheelliset biblioitemnumberit vastaamaan biblionumberia:

MariaDB [lappi_230620]> update biblioitems set biblioitemnumber=biblionumber where biblioitemnumber>biblionumber;
Query OK, 3860 rows affected (3.144 sec)
Rows matched: 3860  Changed: 3860  Warnings: 0

2. Siirretään deleted-taulun id:t hetkeksi 10 miljoonan päähän ettei tule duplikaattiongelmia:

MariaDB [lappi_230620]> update deletedbiblioitems set biblioitemnumber=biblionumber+10000000;
Query OK, 310880 rows affected (33.658 sec)
Rows matched: 310880  Changed: 310880  Warnings: 0

3. Korjataan deletedbiblioitems-taulun biblioitemnumber vastaamaan biblionumberia:

MariaDB [lappi_230620]> update deletedbiblioitems set biblioitemnumber=biblionumber;
Query OK, 310880 rows affected (36.161 sec)
Rows matched: 310880  Changed: 310880  Warnings: 0

4. Korjataan nidetaulun biblioitemnumberit vastaamaan biblionumbereita, jostain syystä items-taulussa virheitä on myös toisinpäin (biblioitemnumber<biblionumber), joten !=:

MariaDB [lappi_230620]> update items set biblioitemnumber=biblionumber where biblioitemnumber!=biblionumber;
Query OK, 12986 rows affected (5.211 sec)
Rows matched: 12986  Changed: 12986  Warnings: 0

7. Ja sama poistetuille niteille:

MariaDB [lappi_230620]> update deleteditems set biblioitemnumber=biblionumber where biblioitemnumber!=biblionumber;
Query OK, 246 rows affected (2.170 sec)
Rows matched: 246  Changed: 246  Warnings: 0

8. Tarkistuksia:

MariaDB [lappi_230620]> select * from deletedbiblioitems where biblionumber in (select biblionumber from biblioitems);
Empty set (5.261 sec)

MariaDB [lappi_230620]> select * from deletedbiblioitems where biblioitemnumber!=biblionumber;
Empty set (0.511 sec)

MariaDB [lappi_230620]> select * from biblioitems where biblioitemnumber!=biblionumber;
Empty set (2.121 sec)

MariaDB [lappi_230620]> select * from items where biblioitemnumber!=biblionumber;
Empty set (2.618 sec)

MariaDB [lappi_230620]> select * from deleteditems where biblioitemnumber!=biblionumber;
Empty set (1.533 sec)

Tässä olisi hyvä ettei järjestelmässä korjauksen aikana tehtäisi muuta, mikä olisi sopiva ajankohta Lapin kannalta?

**Comment by janPasi** [comment]
Timestamppien kanssa tapahtui Lappia lukuunottamatta nyt muissa kimpoissa pieni hupsahdus. Täytyy palauttaa oikeat timestampit biblio- ja deletedbiblio-tauluista.

**Comment by LeenaKinnunen** [comment]
Sopivin aika olisi esim. aamulla 7-9 välillä tai illalla 19 jälkeen. Omatoimia varten olisi hyvä, jos saisimme vähän aikaa tiedottaa katkosta, eli katko aikaisintaan tämän viikon lopulla tai ensi viikolla?

**Comment by janPasi** [comment]
Miten olisi ensi viikon tiistaina aamusella vaikka noin kahdeksan aikoihin? Katko jää tosiaan kaiken mennessä suunnitellusti kaikkiaan muutamaan minuuttiin.

**Comment by LeenaKinnunen** [comment]
4.7. klo 8 sopii.

**Comment by janPasi** [comment]
Deleted-taulujen aikaleimat on nyt oiottu helle, outi, siili, vaski, vaara, kyyti ja lumme. Deleted-taulun tietueen timestamp ajettiin myös taulun deleted_on -kenttään, jossa se on toivottavasti vastaisuudessa hieman paremmassa tallessa. Tilastointi käyttää jatkossa ensisijaisesti tuota deleted-taulun deleted_on kenttää, ja vasta jos sitä ei löydy, käytetään timestamppia.

**Comment by janPasi** [comment]
Korjaukset on ajettu, mutta törmäsimme nidetaulua päivitettäessä foreign-key ongelmaan. Lapin kannassa on kaksi nidettä, joille ei ole lainkaan kuvailutietuetta:

```
MariaDB [lappiprod]> select itemnumber,barcode,biblionumber,biblioitemnumber from items where biblionumber not in (select biblionumber from biblioitems);
+------------+-----------------+--------------+------------------+
| itemnumber | barcode         | biblionumber | biblioitemnumber |
+------------+-----------------+--------------+------------------+
|    1955752 | 698N11407574    |      1732812 |          1732811 |
|    2160029 | 240N20191100205 |      1732812 |          1732811 |
+------------+-----------------+--------------+------------------+
```

Siirsin nämä niteet deleteditemsiin.

**Comment by janPasi** [comment]
```
MariaDB [lappiprod]> select barcode,itemcallnumber,homebranch,holdingbranch,datelastborrowed,datelastseen from deleteditems where barcode in ('698N11407574', '240N20191100205');
+-----------------+----------------+------------+---------------+------------------+--------------+
| barcode         | itemcallnumber | homebranch | holdingbranch | datelastborrowed | datelastseen |
+-----------------+----------------+------------+---------------+------------------+--------------+
| 240N20191100205 | MUS 78.355 AUD | KEPK       | KEPK          | NULL             | 2019-11-13   |
| 698N11407574    | MUS 78.355 AUD | ROPK       | ROPK          | 2022-02-09       | 2022-02-16   |
+-----------------+----------------+------------+---------------+------------------+--------------+
2 rows in set (0.001 sec)
```

Jotain nuotteja nää ehkä on...?

**Comment by LeenaKinnunen** [comment]
Eikö tää ole noiden kuvailutietue https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1732812&found1=1 ?

**Comment by janPasi** [comment]
Jaaha, no sille ei kyllä ole vastinettä biblioitemsissä ollenkaan :D

**Comment by janPasi** [comment]
Ja näitä tämmöisiä on sitten kaksi:

```
MariaDB [lappiprod]> select author,title,medium,subtitle,datecreated from biblio where biblionumber not in (select biblionumber from biblioitems);
+--------+---------------------+--------+-------------------+-------------+
| author | title               | medium | subtitle          | datecreated |
+--------+---------------------+--------+-------------------+-------------+
| NULL   | Audrey Hepburn :    | NULL   | a touch of music. | 2017-11-28  |
| NULL   | Things are Swingin' | NULL   | NULL              | 2019-12-05  |
+--------+---------------------+--------+-------------------+-------------+
2 rows in set (7.911 sec)
```

Eli noilta puuttuu biblioitemsistä tietue kokonaan.

**Comment by LeenaKinnunen** [comment]
Ensimmäinen on juuri tuo aiemmin kommentoimani kuvailu. 
Jälkimmäinen on osakohde: https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1819801&searchid=scs_1688452001953

**Comment by janPasi** [comment]
> Ensimmäinen on juuri tuo aiemmin kommentoimani kuvailu. Jälkimmäinen on osakohde: https://lappi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1819801&searchid=scs_1688452001953

Juu, niin on, se on toinen noista omituisuuksista. En tiedä mihin hiivattiin se biblioitemi niiltä on voinut kadota :D

**Comment by janPasi** [comment]
Noniin nämä nyt korjattu (toivottavasti). Korjasin lisäämällä tietueita varten rivin biblioitemsiin:

```
insert into biblioitems (biblionumber, biblioitemnumber) values ('1732812', '1732812');
insert into biblioitems (biblionumber, biblioitemnumber) values ('1805769', '1805769');
```

Sen jälkeen tietueen tallennus Kohassa täytti biblioitem-tietueen.

Sitten palautin niteet Audreylle:

```
insert into items select * from deleteditems where biblionumber='1732812';
delete from deleteditems where biblionumber='1732812';
```

Korjasin niteen biblioitemnumber epäsynkan:

```
update items set biblioitemnumber=biblionumber where biblionumber='1732812';
```

Ja poistin vielä nidehuomautuksen (laitoin sinne aiemmin merkinnän että miksi nide on deleteditemsissä):

```
update items set itemnotes=null where biblionumber='1732812';
```

Olipas mielenkiintointn tapaus. En kyllä hoksaa miten tilanne on voinyt ylipäätään syntyä alunperin.

**Comment by LeenaKinnunen** [comment]
Tietueet näyttää virkailijaliittymässä nyt oikeilta ja niteet näkyy missä pitää näkyä. Tämä korjaus on nyt sitten kunnossa meidänkin osalta?

**Comment by janPasi** [comment]
> Tietueet näyttää virkailijaliittymässä nyt oikeilta ja niteet näkyy missä pitää näkyä. Tämä korjaus on nyt sitten kunnossa meidänkin osalta?

Kyllä, pitäisi olla.

**Comment by AnneliO** [comment]
Jos tulkitsen oikein, niin tämä on nyt valmis. Suljen siis tiketin. :) Kiitos!
