### ISSUE TITLE
OUTI: asiakkaan tiedoissa on ruksattuna noutoilmoitus tekstiviestinä, mutta puhelinnumero SMS-kentästä puuttuu

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#607]
### Mikä vikana?

Asiakkaan (Borrowernumber=22063) tiedoissa on ruksattuna noutoilmoitus tekstiviestinä, mutta puhelinnumero SMS-kentästä puuttuu. Asiakkaan lokilla ei näy, että hänen tietojaan olisi muokattu.

5.5.2023 puhelinnumero on ollut SMS-kentässä, sillä silloin hänelle on viimeeksi lähtenyt Kohasta tekstiviestinoutoilmoitus. 
Eilen 30.5.2023 noutoilmoitus muodostui hänelle paperikirjeenä.

Hänen matkapuhelinnumeronsa on siirtynyt lankapuhelinkenttään. Matkapuhelinkenttä on tyhjä, jonka vuoksi ehkä SMS-kenttäkin on tyhjentynyt.

### Jotain muuta?

Asiakkaan tiedoissa ei ole käyty korjaamassa tietoja kentiin, joten ongelma on OUTIn Kohassa nähtävillä.

**Comment by velimarj** [comment]
OUTIssa tuli viestiä toisestakin samankaltaisesta tilanteesta: 

"Asiakkaalle oli lähtenyt varausilmoitus 30.5. tulosteena, vaikka valittuna oli ollut tekstiviesti ja ilmoitukset aiemmin tulleet ongelmitta perille. Viimeisin tekstari-ilmoitus oli lähtenyt ja tullut perille 17.5. eli versionvaihdon jälkeisenä päivänä. Tässä välissä siis on jostain syystä numero tippunut pois tekstarikentästä. Asiakastiedoissa puhelinnumero oli lankapuhelin-kentässä. Viestiasetuksissa oli raksittuna tekstari, mutta numerokenttä tyhjänä."

**Comment by AnneliO** [comment]
Pystyisittekö kysymään Finna-toimistosta, näkyykö heidän lokeillaan mitään näihin tapahtumiin/asiakkaisiin liittyen? Kohan lokeilla ei ainakaan vielä näkynyt mitään.

**Comment by AnneliO** [comment]
Tuo Kyytin tapauksen lokimerkinnät saattaisi voida tarkoittaa, että myös OUTIssa asiakas on tiketin #608 vastaavassa kirjauksessa ollut itse asialla muutosta tekemässä, mutta jokin on mennyt pieleen.

**Comment by AnneliO** [comment]
Pirkko-Liisalta sain tiedon, että Vellun mainitsema asiakas on ID 44151:

Asiakkaalle on lähtenyt tekstiviestinä noutoilmoitus 2023-05-17 12:01:42 numeroon +35850xxx1. Seuraava ilmoitus on lähtenyt paperisena 2023-05-30 18:23:45.

Lokilla näkyy, että virkailija on muokannut numeroita seuraavasti:

31.05.2023 14:56 { "mobile" : { "after" : "", "before" : null }, "phone" : { "after" : "050xxx1", "before" : "+35850xxx1" }, "primary_contact_method" : { "after" : "", "before" : null } } 

31.05.2023 15:04 { "mobile" : { "after" : "050xxx1", "before" : "" }, "phone" : { "after" : "", "before" : "050xxx1" } }

Lokilla ei näy, että tietoja olisi muokattu 17.5.-30.5. välillä. Lokimerkintöjen perusteella asiakkaan tiedoissa on ollut +358-alkuinen numero lankapuhelin-kentässä (phone) 31.5.2023 ja matkapuhelin on ollut tyhjä.

**Comment by Tuomas-Kyyti** [comment]
Kävin läpi epäonnistuneita tekstiviestejä ja löytyi lisää tapauksia

```
id	viimeksi lähtenyt sms		epäonnistunut sms	lokissa merkintä numeron muutoksesta
192456	29.4.2023			27.5.2023		ei
294213	19.03.2023			26.05.2023		22.05.2023 (rest api)	
294254	04.05.2023			29.05.2023		08.04.2022 (virkailija)
280432	17.05.2023			02.06.2023		ei
192471	18.5.2023			4.6.2023		ei
298439	1.6.2023			4.6.2023		1.6.2023 (rest api)
155456	12.05.2023			06.06.2023		5.6.2023 (rest api)
```

Osassa puhelinnumero muutos oli tehty Finnassa ja niissä Kohan lokissa oli vain merkintä
{ "smsalertnumber" : { "after" : "04XXXXXXX", "before" : "" } }
Tästä kysyin Kansalliskirjastosta, jos heillä on selitys, miksi muutos ei ole mennyt Kohassa myös mobile-kenttään, niin kuin pitäisi.

Osassa ei numeromuutoksia löytynyt lokista ollenkaan ja oli mukana yksi virkailijankin tekemä muutos.

Lisäsin numeron niille asiakkaille, joille sen löysin lokista.

Tämä on varsin harmillinen ongelma, etenkin jos asiakkaalla ei ole sähköpostiosoitetta: 1) asiakkaat harmistuvat kun eivät saa lainkaan eräpäivämuistutuksia ja lainat menevät yli eräpäivän ja 2) saapumisilmoitukset menevät e-kirjeinä, jotka ovat kirjastolle kalliita.

**Comment by lmstrand** [comment]
Kannattaisi ainakin nyt pikaisesti tarkistaa Finnalta kaikkien kimppojen osalta ensin, että muutos lähetetään mobile- ja smsalertnumber -kenttiin kumpaankin, kun asiakas tallentaa tietojaan ja muutospyyntö muodostuu. Nyt ei ilmeisesti niin ole käynyt joissain tapauksissa (Osassa puhelinnumero muutos oli tehty Finnassa ja niissä Kohan lokissa oli vain merkintä
{ "smsalertnumber" : { "after" : "04XXXXXXX", "before" : "" } }).

Triggerissäkin, joka siirtää smsalertnumberiksi mobile-kentän datan kun asiakastietoja muutetaan on ehkä ongelma nyt jos Finnasta tulee dataa erilailla kuin miten triggeri on laadittu. Pitää ehkä kirjoitella se uusiksi.

**Comment by lmstrand** [comment]
Ongelmana noissa lokittumattomissa tapauksissa on lastseen-arvon päivittyminen, joka tapahtuu nykyisin Finnaan kirjautuessa. Kimpat, jotka eivät ole saaneet ajoa tiketin https://github.com/KohaSuomi/Koha/issues/204 ominaisuuden käyttöönoton yhteydessä kärsivät nyt tästä ongelmasta. Varmistusdataa löytyy kahden viikon ajalta, mutta näitä numeroita on nyt varmasti katoillut jo pidemmän aikaa. Yritetään saada triggeri mahdollisimman pian tuotantoihin.

Tältä ongelmalta siis ovat todennäköisesti välttyneet nyt kimpat Vaara, Lappi, Siili ja Lumme. Ilmeisesti OUTIssa ongelma on siksi, että puhelinnumeroiden ajo smsalertnumberista mobile-kenttään on jäänyt tekemättä, sillä tiketin mukaan siitä ei ole mainintaa.

**Comment by lmstrand** [comment]
Kaikkiin tuotantoihin on päivitetty triggeri asiakkaiden puhelinnumeroiden tahattoman poistumisen välttämiseksi. Pääkäyttäjät voitteko testata Finnojenne/Kohienne toiminnan noiden puhelinnumerokenttien muuttamisen/tietojen tyhjentämisen osalta vielä huolellisesti, kun jouduttiin nyt näin pikaisella aikataululla tekemään muutos, että on varmasti ok.

**Comment by Kati-Helle** [comment]
Poistin Helle-Finnassa asiakastiedon Matkapuhelinnumero-kentästä arvon. Vaikutus Helle-Kohassa:
- Matkapuhelin-kentän arvo poistui
- Tekstiviesti numeroon -kentän arvo poistui
- viestiasetuksiin jäivät edelleen Tekstiviesti-valinnat

Lisäsin Helle-Kohassa asiakastietoon Matkapuhelin-kentän arvon. Numero siirtyi automaattisesti Helle-Finnaan Matkapuhelinnumero-kenttään.

Testasin myös niin, että lisäsin Matkapuhelin-kentän arvon Helle-Finnassa. Numero siirtyi automaattisesti Helle-Kohaan Matkapuhelinnumero-kenttään ja Tekstiviesti numeroon -kenttään.

**Comment by ajrajala** [comment]
Testasin itse äsken, että
- Finnassa muutettu numero siirtyy sekä mobile että smsalertnumber -kenttiin
- Finnassa poistettu numero poistuu sekä mobile että smsalertnumber -kentistä
- Kohassa muutettu/tyhjennetty mobile-kenttä kopioituu myös smsalertnumber-kenttään
- Kohassa uutta asiakasta lisättäessä mobile-kenttään lisätty numero kopioituu myös smsalertnumber-kenttään

Meiltä Mikko lupasi testata vielä toisena silmäparina, mutta näytti nyt ainakin toimivan eri tilanteissa kuten pitää.

**Comment by pknuuti** [comment]
Testattu Vaarassa, samat kokemukset kuin Vaskissa eli toimii.

**Comment by pirliis** [comment]
OUTIn testaus:
- Kohasta poistettu numero Matkapuhelin-kentästä, numero poistui automaattisesti myös Tekstiviesti numeroon -kentästä kuin myös täppä kohdasta Tekstiviesti. Finnasta numero poistui myös kentästä Numero tekstiviesteille.
- Kohaan lisättiin numero Matkapuhelin-kenttään, numero päivittyi automaattisesti myös Tekstiviesti numeroon -kenttään. Numero päivittyi myös Finnan Numero tekstiviestille -kenttään.
- Numero poistettiin Finnasta. Numero poistui molemmista Kohan puhelin numero -kentistä.
- Numero lisättiin Finnaan, numero päivittyi Kohaan molempiin puhelin numero -kenttiin.

Eli OUTIssa toimii myös.

**Comment by Tuomas-Kyyti** [comment]
Sain samat tulokset kuin edellä. Eli numeron poistaminen/muuttaminen/lisääminen toimii kuten pitää.

Lisähavaintoja, jotka eivät liity tähän asiaan.
- sähköpostiosoitetta ei voi poistaa Finnassa, tulee aina takaisin.
- Kun Finnassa poistaa puhelinnumeron, viestiasetuksiin jää tekstiviestiruksit, kuten Katikin kirjoitti. Jos sen jälkeen Kohassa menee asiakkaan muokkaustilaan ja tallentaa, Koha ilmoittaa "Matkapuhelinnumero puuttuu. Tekstiviesti-viestiasetukset poistetaan." Kuitenkin vain Saapumisilmoituksesta poistuu tekstiviestiruksi. Ennakkoilmoitukseen ruksi jää.

**Comment by Kati-Helle** [comment]
> Sain samat tulokset kuin edellä. Eli numeron poistaminen/muuttaminen/lisääminen toimii kuten pitää.
> 
> Lisähavaintoja, jotka eivät liity tähän asiaan.
> 
>     * sähköpostiosoitetta ei voi poistaa Finnassa, tulee aina takaisin.
> 
>     * Kun Finnassa poistaa puhelinnumeron, viestiasetuksiin jää tekstiviestiruksit, kuten Katikin kirjoitti. Jos sen jälkeen Kohassa menee asiakkaan muokkaustilaan ja tallentaa, Koha ilmoittaa "Matkapuhelinnumero puuttuu. Tekstiviesti-viestiasetukset poistetaan." Kuitenkin vain Saapumisilmoituksesta poistuu tekstiviestiruksi. Ennakkoilmoitukseen ruksi jää.

Hellessä tämä Kohan ilmoittama toimii oikein: "Matkapuhelinnumero puuttuu. Tekstiviesti-viestiasetukset poistetaan."

Eli tarpeeton Saapumisilmoitus-tekstiviestiruksi poistuu, samoin tarpeeton Ennakkoilmoitus-tekstiviestiruksi.

**Comment by Tuomas-Kyyti** [comment]
Kansalliskirjastosta vastattiin kyselyyni, että miksi jollain asiakkailla on numeron muutos muuttanut vain smsalertnumberin, mutta ei mobilea. Jollain asiakkailla kuitenkin molemmat.

"Vilkaisin Kyyti:n Koha-ajurin asetuksia Finnassa tähän liittyen.  Kenttiin, joihin tekstiviestinumero pitäisi päivittyä Kohassa näyttäisi olevan kunnossa. fields = "sms_number,mobile”"

Tuo _sms_number_ on kai sitten sama kuin _smsalertnumber_, vai?

**Comment by piiaseme** [comment]
OUTIssa asiakkaalla https://outi.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=66831
on kolme varauksen noutoilmoitusta lähtenyt liikkeelle tänään tulosteena, kun hänelle olisi pitänyt lähteä tänä aamuna tekstiviestit varauksista.

Tämän aamun lokilta varauksista luki tämmöistä:
[{'mtt' => ['email'],'_name' => 'Item_Due'},{'_name' => 'Hold_Filled','mtt' => ['sms']},{'da' => 3,'_name' => 'Advance_Notice','mtt' => ['email']}] 

Asiakkaan tiedoissa oli puhelinnumerot matkapuhelinkentässä sekä sms-alert-kentässä. Ruksi oli paikallaan kohdassa Varauksen noutoilmoitus tekstiviestinä.

Virkailija kävi tarkistamassa asiakkaan tiedot ja "muokkasi" asiakastietoja sen verran, että näpäytti ensin noutoilmoituksen rastin pois ruudusta ja sitten heti takaisin.

Aiempaa noutoilmoitus-historiaa ei ole tiedossa eikä sitä onko asiakas käynyt Finnassa tietojaan muuttamassa. Lokilla näkyy 26.6. tehdyn yhteystietomuutoksia, mutta ei matkapuhelinmuutoksia, jos osasin lokia lukea oikein.

**Comment by pirliis** [comment]
OUTIn asiakkailla näyttäisi viestitäpät pysyneen kuin myös matkapuhelin numero oikeissa kentissä.

**Comment by AnneliO** [comment]
Piia, jos tämä tiketti on mielestäsi ok, niin suljetko tiketin? :)
