### ISSUE TITLE
Automaateilla ei voi lainata lapsi, jonka saman takaajan sisarus on lainauskiellossa maksujen takia

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#609]
### Mikä vikana?

Kyytissä on käytössä asetus _NoIssuesChargeGuarantees_ eli takaaja on lainauskiellossa, jos joku hänen taattavistaan on lainauskiellossa maksujen takia. Sen sijaan asetus _NoIssuesChargeGuarantorsWithGuarantees_ ei ole käytössä.
Virkaija-Kohassa tämä toimii oikein eli liikaa maksuja omaava lapsi ja hänen takaajansa eivät voi lainata, mutta muut saman takaajan lapset voivat lainata.

Lainausautomaateilla tämä ei kuitenkaan toimi näin, vaan automaateilta ei pysty kukaan tästä takaaja-taattava-ryhmästä lainaamaan, vaan automaatti ilmoittaa "Asiakasta ei hyväksytty". Siis esim. lapsi, jonka sisaruksella on liikaa maksuja, ei pysty automaatilla lainaamaan.

Asiasta on [tiketti 29755 Bugzillassa ](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29755)

### Mitä pitäisi tapahtua

Taattavan, jolla ei ole liikaa maksuja pitää pystä lainaamaan myös automaateilla, vaikka hänen takaajansa muilla taattavilla onkin liikaa maksuja.

### Selain

```markdown
Mikroväylän-automaateilla testattu.
```

**Comment by lmstrand** [comment]
Viedään yhteisön korjaukset testeille testattavaksi.

**Comment by Tuomas-Kyyti** [comment]
Meillä ei ole testillä automaatteja, joten en voi tätä testata.

**Comment by lmstrand** [comment]
Vaskilla ja OUTIlla taisi olla testausvalmius. Pyydetään heitä testaamaan, kunhan saan tuotua korjauksen testeille.

**Comment by lmstrand** [comment]
Yhteisön tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33411 taitaa koskea ehkä paremmin tätä tapausta. Ei ole vielä push-tilassa mutta tuon tiketin korjausta voisi kokeilla.

**Comment by lmstrand** [comment]
Ja tiketti https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32624 liittyy tähän myös, ehkä nuo pitää kaikki ottaa kyytiin.

**Comment by lmstrand** [comment]
Jaa Vaskin testillä ei varmaan ole sip-konfiguraatio kuosissa. No outin testillä on sip-palvelin pystyssä jolla OUTESTI1 ja 2 -tunnukset konfiguraatiossa.

**Comment by lmstrand** [comment]
Tuo yhteisön bugikorjaus 29755 on ollut meillä jo matkassa tuotannossa (sen verran vanha tiketti, että koodi on lähtenyt meille matkaan vielä kun alettiin väsätä versionvaihtoa).

Testeille viety korjaus ei ilmeisesti sekään koske suoraan tämän tiketin tilannetta. Automaattikanavalla Mari OUTIsta on testannut näin:
"Testailin Pirkko-Liisan antamat kortit, takaaja ja taattava 1 (jolla maksuja) estetty lainaus, taattava 2 (jolla ei maksuja) voi lainata normaalisti. Sip viesti näyttää hyvin myös syyn."

" ...lapsi, jonka sisaruksella on liikaa maksuja, ei pysty automaatilla lainaamaan."
Vaikka yhteisötiketit ja niiden korjaukset ei kuvausten mukaan suoraan koske tämän meidän tiketin kuvailtua ongelmaa, testien mukaan lainaus nyt kuitenkin onnistuu toiselta taattavalta kun toisella taattavalla on lainauksen estäviä maksuja.

Eli viedään tiistaina tuotantoon tämä muutos.

**Comment by Tuomas-Kyyti** [comment]
Testattu nyt tuotannossa ja vaikuttaa toimivan oikein. Suljen tiketin.
