### ISSUE TITLE
Ongelma "Kopioi"-painikkeen käytössä: Takaaja-tieto ei tallennu

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#610]
### Mikä vikana?

Kun kopioi lapsiasiakkaan tiedot "Kopioi" -painikkeella, niin lomakkeelle automaattisesti täyttyvä Takaaja-tieto ei tallennu. Takaajatieto kopioituu Asiakastakaaja-kenttään oikein, mutta tallentaessa saan virheilmon (ja Asiakastakaaja-kenttä on tyhjentynyt):

![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/7ce44b12-4bac-4fe4-9229-59e61ce1cd07)

Tyhjensin testikannassa IntranetUserJS:n, mutta siitä ei ollut apua, sillä sama tilanne toistui.

### Mitä pitäisi tapahtua

Takaaja-tiedon pitäisi tallentua muiden tietojen mukana.

### Kuinka toistaa ongelma/asia

1. valitse lapsiasiakas ja klikkaa "Kopioi"-painiketta
2. Täydennä pakolliset kentät
3. Tallenna
4. Huomaa puuttuvasta takaajatiedosta kertova huomautus

**Comment by emta001** [comment]
Tuosta "Tullut asiakkaaksi"-päivämäärästä on nyt myös tiketti #771, käsitellään tämä ongelma erikseen siellä.

**Comment by emta001** [comment]
Sama ongelma on näemmä yhteisössä. Elättelin toiveita, että yhteisön tiketti [26558](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=26558) olisi korjannut tämänkin, mutta eipä näytä siitä olevan apua.

Kirjailen tälle tiketin yhteisöön.

**Comment by emta001** [comment]
Yhteisössä tästä on tiketti [32530](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32530), muttei vielä ratkaisua.

**Comment by piiaseme** [comment]
Testasin OUTI-testillä lapsiasiakkaan kopioimista, mutta tallentamisnäppäimen painallus ei aiheuta mitään tapahtumia. Eikä tule mitään virheilmoitustakaan.

1. Hain lapsiasiakkaan tiedot. Klikkasin "Kopioi". 
2. Muokkasin tietoja ja klikkasin "Tallenna". 
4. Mitään ei tapahdu. Ihan kuin näppäin ei toimisi ollenkaan. 

Kopion tallennus onnistuu muilla asiakaslajeilla paitsi "Lapsi, omatoimi kielletty", "Lapsi, omatoimi sallittu" sekä "Huollettava, muu kuin lapsi".

(Tuotannossa lapsiasiakkaan kopioiminen toimii edelleen kuten aiemmin eli takaajatieto katoaa tallentaessa.)

**Comment by emta001** [comment]
> Testasin OUTI-testillä lapsiasiakkaan kopioimista, mutta tallentamisnäppäimen painallus ei aiheuta mitään tapahtumia. Eikä tule mitään virheilmoitustakaan.
> 
>     1. Hain lapsiasiakkaan tiedot. Klikkasin "Kopioi".
> 
>     2. Muokkasin tietoja ja klikkasin "Tallenna".
> 
>     3. Mitään ei tapahdu. Ihan kuin näppäin ei toimisi ollenkaan.
> 
> 
> Kopion tallennus onnistuu muilla asiakaslajeilla paitsi "Lapsi, omatoimi kielletty", "Lapsi, omatoimi sallittu" sekä "Huollettava, muu kuin lapsi".
> 
> (Tuotannossa lapsiasiakkaan kopioiminen toimii edelleen kuten aiemmin eli takaajatieto katoaa tallentaessa.)

Luultavasti #649 nyt sitten aiheuttaa sen, että tallennus ei enää näissä tapauksissa onnistu.

**Comment by piiaseme** [comment]
> Yhteisössä tästä on tiketti [32530](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32530), muttei vielä ratkaisua.

Jos ymmärrän tuota yhteisön tikettiä oikein, niin korjaus on tulossa meille versiossa 23.11.? Voinko siis vaihtaa tämän Kommentoidusta tilaan: Odottaa versionvaihtoa?

**Comment by emta001** [comment]
> > Yhteisössä tästä on tiketti [32530](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32530), muttei vielä ratkaisua.
> 
> Jos ymmärrän tuota yhteisön tikettiä oikein, niin korjaus on tulossa meille versiossa 23.11.? Voinko siis vaihtaa tämän Kommentoidusta tilaan: Odottaa versionvaihtoa?

Ei tuossa tiketissä ole vielä patchia, joka korjaisi tämän, joten korjausta ei ole vielä yhteisön masterissa. Tämä ei siis ratkea tulevassa versiossa.

**Comment by emta001** [comment]
Vilkaisin tätä tosiaan viime kuun lopulla, mutten vielä silloin keksinyt mitään järkevää ratkaisua tähän.

**Comment by piiaseme** [comment]
Okei, ehdin jo innostua :D

**Comment by atarnus** [comment]
Sama tulee vastaan myös tilanteessa, jossa luot uutta lapsiasiakasta takaajan tiedoista käsin, ja Koha ehdottaa mahdollista duplikaattia. Tässä näkymässä tipahtaa pois takaajatieto.

![image](https://github.com/user-attachments/assets/ba0115ae-930e-4d06-af67-e30c7e415eab)

**Comment by atarnus** [comment]
Näyttäisi olevan tuon yhteisötiketin [32530](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32530) tilanne se, että korjaus tulee versioon 24.11. Joskaan ei ole varmuutta päteekö korjaus tuohon yllä mainitsemaani tilanteeseen myös. Toivotaan.

**Comment by lmstrand** [comment]
Tämä ilmeisesti backportataan pian versioon 24.05.06.

**Comment by emta001** [comment]
Yhteisötiketin [32530](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32530) myötä yhteisöön tulikin bugi, joka on korjattu tiketissä [37881](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37881). Joten pitänee tuoda meille molemmat korjaukset :sweat_smile:

**Comment by emta001** [comment]
Viety testattavaksi testeille. Testailkaa näin:

1. Kopioi lapsiasiakas.
2. Täytä vaaditut kentät ja tallenna.
=> Tallennuksen tulisi onnistua normaalisti ja takaajan tiedot ovat siirtyneet myös uudelle käyttäjälle.

Testatkaa myös, että olemassa olevan lapsiasiakkaan voi tallentaa muokkauksen jälkeen normaalisti.

**Comment by MikkoLiimatainen** [comment]
Testattu Vaski-testillä. Kopioidun lapsiasiakkaan tallennus onnistui ja olemassa olevia lapsiasiakkaita pystyy muokkaamaan. Kopioidulla asiakkaalla oli kaksi huoltajaa, joiden molempien tiedot säilyivät.

Takaajatieto säilyi ja tallentui myös kun lapsiasiakkaan kopioinnissa vaihdoin asiakastyypiksi "Huollettava, muu kuin lapsi" ennen kuin tallensin asiakkaan ensimmäisen kerran. Ja tallentui myös, kun muutin kopioinnissa asiakkaan henkilöasiakkaaksi, eli takaajatieto tulee asiakastyypeille, joille se ei kuulukaan. Ja säilyy, vaikka tietoja muokkaisikin, eikä muokkauksessa vaikuta tulevan ongelmia. Eihän tuota toki noin tule käyttää, mutta alkuperäinen ongelma vaikuttaisi korjaantuneen.

**Comment by piiaseme** [comment]
OUTIn testillä testattu onnistuneesti
- lapsiasiakkaan lisäämistä kopioimalla toisen lapsiasiakkaan tiedoista (Kopioi-toiminnolla)
- olemassa olevan lapsiasiakkaan muokkaamisen tallentamista
- lapsiasiakkaan lisäämistä huoltajalle "Lisää huollettava"-toiminnolla

**Comment by emta001** [comment]
> Testattu Vaski-testillä. Kopioidun lapsiasiakkaan tallennus onnistui ja olemassa olevia lapsiasiakkaita pystyy muokkaamaan. Kopioidulla asiakkaalla oli kaksi huoltajaa, joiden molempien tiedot säilyivät.
> 
> Takaajatieto säilyi ja tallentui myös kun lapsiasiakkaan kopioinnissa vaihdoin asiakastyypiksi "Huollettava, muu kuin lapsi" ennen kuin tallensin asiakkaan ensimmäisen kerran. Ja tallentui myös, kun muutin kopioinnissa asiakkaan henkilöasiakkaaksi, eli takaajatieto tulee asiakastyypeille, joille se ei kuulukaan. Ja säilyy, vaikka tietoja muokkaisikin, eikä muokkauksessa vaikuta tulevan ongelmia. Eihän tuota toki noin tule käyttää, mutta alkuperäinen ongelma vaikuttaisi korjaantuneen.

Hmm, tuo takaajan säilyminen ei toki ole semmonen normikäyttötilanne, mutta hyvä kuitenkin pitää mielessä :thinking:

**Comment by piiaseme** [comment]
Tämä korjaus on tuotu tuotantoihin, joten suljen tiketin.
