### ISSUE TITLE
Lumme: 500-virhe tehtäessä kirjaston perustoimintoja

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#611]
### Mikä vikana?

Kentältä kuului, että erityisesti Mikkelin pääkirjastolla oli Koha heittänyt järjestään 500-virheilmoitusta lainauksen, palautuksen, varausten käsittelyn, asiakastietojen, yms. haussa. Tätä oli kestänyt koko päivän, mutta erityisesti klo 13-15 välillä. Sitten kun oli odottanut muutaman minuutin, niin Koha haki hetkeä aikaisemman buganneen niteen normaalisti. Herjaa heitti myös sellaisten niteiden uudelleenkäsittelyssä, jotka oli hetkeä aikaisemmin palautettu automaatilla.

Tätä ongelmaa näyttäisi olevan myös Pieksämäellä kuittitulostuksen yhteydessä.

_Virhe!
Virhe 500
Tämä viesti johtuu jostain seuraavasta syystä:

    Ulkoinen lähde on ohjannut sinut nimekkeeseen, jota ei ole enää olemassa
    Seurasit vanhaa linkkiä esim. hakukoneesta tai kirjanmerkeistä
    Yritit päästä sivulle, jonne pitää kirjautua.
    Linkki oli virheellinen ja sivua ei ole olemassa

Mitä seuraavaksi?

·         Käytä ylävalikkoa siirtyäksesi toiseen Kohan osioon._

**Comment by Hanna-Lumme** [comment]
Nyt tuli ensimmäinen ylös laitettu ongelmatapaus. Laittelen lisäesimerkkejä, kunhan saan niitä tietää, mutta tällä pääsee ehkä alkuun. 

Nidettä 485887 oltiin lainaamassa asiakkaalle ID20274 n. klo 16.58, kun heitti ruutuun tuon virhe 500. Vähän myöhemmin, kun samaa nidettä oltiin lainaamassa samalle asiakkaalle, se olikin asiakkaalla jo lainassa.

**Comment by Hanna-Lumme** [comment]
Toinen virhe, nide 2997853 asiakkaalle ID170813 1.6. klo 11.12. On kuulemma ollut kahdesti 500-virhe tämän asiakkaan kohdalla eri päivinä.

**Comment by AnneliO** [comment]
ID170813 

| datetime | branch | value| type | other | itemnumber | location | borrowernumber | ccode | categorycode |
|---|---|---|---|---|---|---|---|---|---|
| 2023-06-01 11:12:35 | PIE_PK | 0.0000 | return |       |    2011528 | A28      | CART     |         170813 | NULL  | HENKILO      |
| 2023-06-01 11:12:44 | PIE_PK |   NULL | issue  |       |    2011528 | A28      | CART     |         170813 | NULL  | HENKILO     |

Nide lainattu 9 sekuntia palautuksen jälkeen.

| id | status | progress | data | enqueued_on | started_on | ended_on |
|---|---|---|---|---|---|---|
| 308553 | finished |        1 | {"record_server":"biblioserver","record_ids":[2997853]}                                                              |  2023-06-01 11:12:44 | 2023-06-01 11:12:45 | 2023-06-01 11:12:45 |
| 308554 | finished |        1 | {"record_server":"biblioserver","record_ids":[2997853]}                                                              |  2023-06-01 11:12:44 | 2023-06-01 11:12:45 | 2023-06-01 11:12:45 |

Palautuksen ja lainauksen indeksointi aloitettu ja lopetettu samaan aikaan.

**Comment by AnneliO** [comment]
ID20274

Niteen 1856248 lainaa ei näy statistics-taulussa. Viimeisin merkintä palautuksesta 2023-05-31 16:00:01.

Taustatöissä tietue 485887 näkyy jonossa vain tuolloin palautuksen aikaan.

| id     | status   | progress | data                                                                                                                | enqueued_on         | started_on          | ended_on            |
|---|---|---|---|---|---|---|
| 292811 | finished |        1 | {"record_ids":[485887],"record_server":"biblioserver"}                                                              | 2023-05-31 16:00:01 | 2023-05-31 16:00:07 | 2023-05-31 16:00:08 |

**Comment by AnneliO** [comment]
Tiketissä #290 on vähän samantyyppisiä tapauksia ollut Vaskissa joulukuussa 2022.

**Comment by AnneliO** [comment]
Kokeilin lumme-testillä palauttaa lainassa olevan niteen ja lainata sen heti asiakkaalle uudelleen. Tapahtumat aiheuttivat taustatöihin kolme indeksointia. Lumpeissa on ainakin testillä päällä Tänään palautettu (CART) -toiminto, joka ehkä aiheuttaa tuon kolmannen indeksoinnin.

**Comment by Hanna-Lumme** [comment]
Tässäpä olisi pari muuta raportoitua virhettä: Nide 171103 antoi kolme kertaa virhe 500 -ilmoituksen palautuksessa ja kyseeseen teokseen oli hyllyvaraus. Tapahtui 1.6 n. klo 14.50. 

En tiedä liittyykö tämä samaan asiaan, koska yritin toistaa virheet, mutta en onnistunut siinä. Laitetaan varmuuden vuoksi tähän.
Asiakkaalle ID170267 oltiin lisäämässä kahta taattavaa Lisää taattava -napin takaa. Ensimmäisen kohdalla oli tallennuksen kohdalla heittänyt virhe 500 (takaaja-kenttä oli mahdollisesti tyhjä). Lapsi kuitenkin löytyi Kohasta eli tiedot olivat kuitenkin tallentuneet. Toisen lapsen kohdalla huoltaja-tietoa oli yritetty muuttaa Muu huollettava-vaihtoehdosta ja takaajatieto oli kadonnut kokonaan tallennuksen yhteydessä. 

Sain lisättyä molemmat huollettavat asiakkaan tietoihin jälkikäteen ongelmitta.

**Comment by AnneliO** [comment]
UpdateNotForLoanStatusOnCheckin -järjestelmäasetuksessa jotain TIGHT: 0 ja EXHIBIT: 0 -määrityksiä. Mitähän noi on?

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/512e2a48-1ace-4d39-a4f0-ea6685b31c4e)

**Comment by AnneliO** [comment]
Lokeilla näkyy Larin tutkimusten mukaan kirjauksia

[2023/06/01 18:17:18] [ERROR] Can't call method "notforloan" on an undefined value at /home/koha/Koha/Koha/[Item.pm](http://item.pm/) line 1482.

Nuo aiemmassa kommentissa olevat tight ja exhibit saattais nyt olla vikana. Onko tietoa, miksi ne on sinne lisätty?

**Comment by AnneliO** [comment]
Poistin klo 12.01 UpdateNotForLoanStatusOnCheckin -järjestelmäasetuksesta nuo TIGHT: 0 ja EXHIBIT: 0 -määritykset. Seurataan tilannetta.

**Comment by AnneliO** [comment]
Nuo TIGHT ja EXHIBIT näyttäis olevan hyllytarkenteita ja samanlainen määritys oli myös lumme-nextillä UpdateNotForLoanStatusOnCheckin -asetuksessa. Eli se on todennäköisesti nyt sieltä kopioitunut tuotantoon versionvaihdossa.

**Comment by emta001** [comment]
Lisätään tähän nyt sekin, että Lumpeiden haravoinnissa on ilmennyt myös 500-virhe. Pyyntö oli seuraava:

https://lumme.koha-suomi.fi/cgi-bin/koha/oai.pl?resumptionToken=marc21%2F4750%2F2023-06-02T08%3A40%3A10Z%2F%2F%2F0%2F0%2F1488007&verb=ListRecords

Tuon linkin avaaminen kirjaa Lumpeiden lokiin seuraavan virheen:

_DBIC result _type  isn't of the _type BiblioMetadata at /home/koha/Koha/Koha/OAI/Server/Repository.pm line 181._

Eli jonkinlainen skeemahäröily siellä nyt hiertää.

**Comment by Hanna-Lumme** [comment]
Raportoitiin jälleen virhe 500 palautuksen yhteydessä. Tapahtui 7.6. n klo 14.49 biblio 2987105. Virkailija oli palauttanut nidettä uudelleen, kun ruutuun oli sen jälkeen hypännyt ilmoitus: "Nidettä ei palautettu järjestelmäasetuksen virheen vuoksi. Pyydä ylläpitäjää tarkistamaan tietoja ja korjaa virheet, jotka näkyvät "Järjestelmätiedot" -välilehdellä." Kolmannella kerralla oli kirja palautunut normaalisti. 

Kävin katsomassa nuo Järjestelmätiedot, enkä sieltä nyt äkkiseltään bongannut ilmoitusta, joka olisi avannut tilannetta yhtään enempää.

**Comment by Hanna-Lumme** [comment]
Mielenkiintoista kyllä! Justiisa sain tietää, että eilen oli palautuksessa tullut jatkuvasti tuota virhe 500 klo 16-19 välillä. Sen tiedän, että noilla Lysyin automaateilla bugaa välillä, koska sillä on RFID:n lukijassa jotain, mutta nämä oli tosiaan tulleet tiskin koneella palauttaessa.

**Comment by lmstrand** [comment]
Voitteko testata samalla niteellä, tapahtuuko tällaista johdonmukaisesti vaiko satunnaisesti. Onko ongelmat rajattu vain tiketissä mainittuihin yksiköihin? Oikutteleeko sama nidenumero muissa yksiköissä jos vaihtaa esim. sijaintikirjastoa?

**Comment by lmstrand** [comment]
Verkko-ongelmatkaan eivät oikein sovi tähän, sitäkin mietittiin mahdollisena ongelmana kehittäjäpalaverissa. Laitettiin lisää lokitusta tuonne tuotantoon, jos niistä selviäisi paremmin mitä tapahtuu. Yrittäkää laittaa ylös huomenna sattuvia ongelmia, niin tutkitaan sitten lokit.

**Comment by lmstrand** [comment]
Poistin Lumpeesta neljä tietuetta, joilla ei ollut metadataa. Yhdellä niistä oli deleteditemsissä nide. Ei ollut laskutettu.

**Comment by Hanna-Lumme** [comment]
Palautuksessa Pieksämäellä oli tullut paljon virhe 500 9.6. klo 16 jälkeen (yhtenä esimerkkinä nide JJR20200900769). Palautuksessa oli myös nyt huomattu uutena, että alleviivaus ylämarginaalissa vaihtuu Hae tietokannasta -osioon palautuksen yhteydessä. Tämä oli jouduttu aina vaihtamaan manuaalisesti takaisin.

**Comment by AnneliO** [comment]
Onko näitä tullut vielä sitten kesäkuun?

**Comment by Hanna-Lumme** [comment]
Kyselin kimpan työntekijöiltä ja on tullut viimeksi tiistaina 1.2. Raportoivat ongelmasta ainakin Punkaharjulla, Savonlinnassa, Rantasalmella, Pieksämäellä ja Pertunmaalla, palautuksen ja ainakin yhden kuittitulostuksen yhteydessä. Rantasalmella ongelmaa oli esiintynyt suhteellisen paljon klo 15-16.

**Comment by emta001** [comment]
Koha_Suomen palaveri 28.8.2023: Ohjeistakaa virkailijoita tyhjentämään selaimen välimuisti ja keksit 500 virheen sattuessa ja tarkkailemaan sen jälkeen syntyykö tilanne uudestaan. Jos näistä toimista huolimatta virhe toistuu samantien uudestaan, niin sitten ilmoitusta eteenpäin missä tilanteessa virhe ilmeni ja monen aikaan. Ehkä kannattaa myös tarkkailla tapahtuuko tätä aina tietyllä päättellä.

**Comment by emta001** [comment]
Yksi 500 herja saatu kiinni:

"Tänään 28.8. klo 18:24 menin niteen 588N0024912 tietoihin, asetin Kadonnut tilaksi "Kadonnut" ja painoin Aseta tilaa, jonka jälkeen tuli 500 virhe. Mutta kun menin uudestaan ko. niteen tietoihin, oli tila kuitenkin tallentunut ja asettamalla Pois kierrosta tilan, ei 500 virhettä enää tullut. En siis tyhjentänyt välimuistia tai keksejä välissä."

**Comment by AnneliO** [comment]
HOLD_SLIP-kuittipohjasta korjattu tänään yksi virhe, jossa rivillä 

```[% IF loggedinbranchname == branch.branchname%]```

prosenttimerkki oli virheellisesti kiinni sanassa branchname. Tuo ainakin on saattanut aiheuttaa osan ongelmista.

**Comment by Hanna-Lumme** [comment]
Raportoitiin, että eilen oli Poleenissa tullut pari virhe 500 lainauksen yhteydessä:
29.08.23 / 16.25 - Tulosta kuitti (palautuskuitti & tänään lainatut toimivat) - ID:178224
29.8.23 / 16.40 - Lainaus (oli kuitenkin lukenut koodin, kun tein uudest.) - Biblio: 2152901 / ID: 179475
29.8.23 / 16.45 - Varauksen lainaus - Biblio: 2298402 / ID: 170035

**Comment by AnneliO** [comment]
Jos kirjastovalintana on Pieksämäki ja tulostaa kuitin ISSUESLIP, tulee virhe 500.

**Comment by AnneliO** [comment]
Pieksämäen kuittipohja poikkeaa aika paljon [uusimmasta versiosta](https://github.com/KohaSuomi/kohasuomi.github.io/blob/master/_docs/kuititjaviestit.md#issueslip-eli-lainakuitti-kaikista-lainoista), joten se kannattaisi ehkä rakentaa uusiksi tuon esimerkin pohjalta.

**Comment by AnneliO** [comment]
Noista kahdesta lainaustilanteesta en nyt äkkiseltään hoksaa muuta kuin että niteiltä puuttuu Luokitus eli 952$2-kentästä tiedot (sen näkee niteiden muokkausessa siitä nidetaulukosta. Nidettä muokatessa se on näennäisesti paikallaan, koska se on pakollinen kenttä).

Mutta jos niissäkin ongelma on tullut kuittia tulostaessa, niin silloin voi olla sama syy kuin ensimmäisessä kohdassa.

**Comment by AnneliO** [comment]
Näyttäis muuten siltä, että ongelma on oletus-pohjassa, suomi-versio toimii.

**Comment by emta001** [comment]
Olisikohan kuittipohjan korjaus auttanut tähän ongelmaan?

**Comment by AnneliO** [comment]
Vieläkö näitä ilmoituksia on tullut vai voisiko tiketin sulkea? :)

**Comment by Hanna-Lumme** [comment]
Kyselin tuossa alkuviikosta ja mitään vastausta ei ole vielä tullut. Kyselen vielä meidän ensi viikon Koha-ryhmän palaverissa ja suljen sitten tiketin, jos asia ei kaipaa enää selvittelyä. :)

**Comment by Hanna-Lumme** [comment]
Kyselin näistä, niin kuulemma niitä vielä siellä täällä pomppaa esiin. Oli esim. asiakkaan haun yhteydessä tullut (tarkempia tietoja virkailija ei ollut ottanut ylös) ja eilen toinen virkailija oli kohdannut kyseisen errorin, kun oli vaihtanut 17.10. n. klo 9.00 jälkeen kirjastoa (oli mennyt koululle). Virkailijan ID258879.

**Comment by emta001** [comment]
> Kyselin näistä, niin kuulemma niitä vielä siellä täällä pomppaa esiin. Oli esim. asiakkaan haun yhteydessä tullut (tarkempia tietoja virkailija ei ollut ottanut ylös) ja eilen toinen virkailija oli kohdannut kyseisen errorin, kun oli vaihtanut 17.10. n. klo 9.00 jälkeen kirjastoa (oli mennyt koululle). Virkailijan ID258879.

Ainakin tuohon kirjaston vaihtamiseen liittynee tämä virhe:
`Can't use an undefined value as a HASH reference at /home/koha/Koha/circ/set-library.pl line 49.`

Rivi, jossa tuohon viitataan:
`my $userenv_branch      = C4::Context->userenv->{'branch'} || '';`

Aivan kuin Koha olisi tuolla hetkellä menettänyt yhteyden tuonne C4::Contextiin tai jotain. Tarkalleen ottaen koko tuo C4::Context->userenv on tuolla haku hetkellä ollut undef, eli käyttäjän tietoja ei ole voinut hakea. En kyllä ymmärrä kuinka tuo tarkalleen on mahdollista enkä saa tätä toistumaan omilla testeillä.

**Comment by Hanna-Lumme** [comment]
Nyt ei ole raportoitu virhe 500 vähään aikaan niin suljen tiketin. Tehdään sitten tarvittaessa uusi.
