### ISSUE TITLE
Vaara: Automaattiin Tarkista varauksesi -toiminto

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#614]
### Tukipyyntö

Mikroväylän lainausautomaatteihin on tarkoitus ottaa Tarkista varauksesi -toiminto käyttöön. Siihen tarvitaan muutos SIP-viestin kenttään, jossa näytetään noutokirjasto. Tällä hetkellä viesti näyttää vain niteen kotikirjaston, mikä ei ole välttämättä se noutokirjasto, mistä asiakas varauksensa noutaa. 
"Ohjelma kun yrittää hakee sip-viestistä noutokirjaston paikkaa kolmesta eri kentästä järjestyksessä: CT -> AP -> AQ. Ainoa minkä se löytää on tuo AQ kenttä, johon tulee tieto omistajakirjastosta. "
"Tuon CT-kentän saa laitettua näköjään käyttöön Kohan SIP-serverin konfiguraatiossa ct_always_send="1" -määrityksellä. Ehkä asia hoituisi sillä."

CT-kenttä olisi siis laitettava käyttöön ja testattava, miten varausten tarkistus toimii muutoksen jälkeen eli näyttääkö automaatti oikean noutokirjaston.

**Comment by lmstrand** [comment]
Tutkin lisää tuota CT-kenttään liittyvää sip-palvelinkonfiguraatiota. Siitä ei taida ollakaan mikroväylälle mitään iloa:

"Bug 22016: Always send CT field for SIP checkin, even if empty

Some SIP devices ( in this particular case, bin sorting machines from RFID Library Solutions ) require a CT field to be sent, even if that field is empty. Koha should be able to support this behavior."

https://github.com/Koha-Community/Koha/commit/3e63209fa828144099cfdde2a740e372c4722287
Kysyin lisätietoa siitä, missä viestiparin vastauksessa tuo tieto tulisi välittyä?
Lyngsoella varausten hakuun käytetään 63-64-viestiparin varauskyselyitä ja yksityiskohdat varauksista kysytään 17-18-viestiparilla kuulemma. Tietoa siis noutokirjastosta ei ole saatavana heillekään, mutta varaukset pystyy noilla listaamaan.

**Comment by lmstrand** [comment]
Listty Outokummun lainausautomaatille ct_always_send="1" -määritys testausta varten.

**Comment by lmstrand** [comment]
Okun automaatilta poistetu ct_always_send -asetus. Tiistaina konfiguraatiot vaihdetaan käyttämään AP-kenttää nidetiedoissa. AP-kenttä sisältää kirjastotunnuksen (items.holdingbranch). Mikroväylä sanoi, että tunnuksen voi kääntää selkokieliseksi skriptillä automaateilla. Toimivat kuulemma näin Sierra-järjestelmän kanssa (Helmet).

**Comment by pknuuti** [comment]
Tanja kertoi juuri sopineensa Mikroväylän Tuomaksen kanssa automaatin testaamisesta Outokummusa 26.6. Sitä ennen aikataulut eivät käyneet yksiin.

**Comment by lmstrand** [comment]
Sovittiin, että tämä ominaisuus otetaan käyttöön kaikissa kimpoissa. Testattu jo OUTIn testiautomaatilla (Lyngsoe).
Tein uuden tiketin ominaisuuden käyttöönotosta kaikkiin kimppoihin https://github.com/KohaSuomi/Koha/issues/651. Tämän tiketin voisi sulkea.
