### ISSUE TITLE
Näytä osakohteet -linkki piiloon tietueen perustiedot-näytöltä

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#615]
### Tukipyyntö

Pääkäyttäjäpalaverissa 30.5.2023 päätettiin, että tietueen perustiedot-näytöltä piilotetaan otsikko Osakohteet ja sen vierestä linkki Näytä osakohteet.
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/37ed1dba-4bc5-4407-8a5b-53ace6e054b7)

Toiminto on käytännössä yhteisön "analytical record" -toiminto, joka on hieman sama asia kuin osakohteet, mutta ei ihan. Linkki tekee haun _rcn:tietuenumero AND (bib-level:a OR bib-level:b)_, jolloin hakuu voi osua myös sellaiset tietuenumerot, jotka alkavat samalla merkkijonolla. Eli tietuenumeroa ei haeta täsmällisesti. Tämä sama ongelma korjattiin Osakohteet-välilehden yhteydessä, mutta pääkäyttäjäpalaverissa todettiin, että osakohteita ei tarvita näytölle kahta kertaa ja piilotetaan väärin toimiva vaihtoehto.

**Comment by AnneliO** [comment]
IntranetUserCSS:ään kun lisää tämän, niin otsikko ja linkki menee piiloon:

```
/* Piilota perustiedot-näytöltä Osakohteet ja Näytä osakohteet -kohta kuvailutietojen osiosta. */
body#catalog_detail span.results_summary.analytics.analytic_monograph { display: none; }
```
Kannattaa testata laajasti erilaisilla tietueilla, ettei mikään muu mene piiloon. :)

**Comment by pknuuti** [comment]
Testasin Vaaran testillä tuon piilotusrimpsun ja vertasin tuotannossa oleviin kirja, nuotti, cd ja dvd-aineistoja (tosin vain yhdellä haulla) mutta muu ei piilottunut kuin se mikä pitikin eli se ylimääräinen osakohteet-linkki.

**Comment by pirliis** [comment]
Vertasin OUTIn testin ja tuotannon tietueita. Testillä Osakohteet-kohta oli kuvailutiedoista pääsin pois näkyviltä, eikä muuta ylimääräistä ollut piiloutunut, paitsi tietueessa: https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1559727 Osakohteet-kohta vielä näkyy ja joissain tietueissa testillä ei ollut aineistotyyppiä.

**Comment by AnneliO** [comment]
Tuossa Pirliin linkaamassa tietueessa rivin "tägi" oli vähän erilainen. Tuonkin sai piiloon, kun laitoin toisen piilotusrivin eli näin:

```
/* Piilota perustiedot-näytöltä Osakohteet ja Näytä osakohteet -kohta kuvailutietojen osiosta. */
body#catalog_detail span.results_summary.analytics.analytic_monograph { display: none; }
body#catalog_detail span.results_summary.analytics.analytic_undefined { display: none; }
```

Oisko sulla Pirlii esimerkkejä tietueista, joissa aineistotyyppiä ei ollut?

**Comment by pknuuti** [comment]
Piilottaminen onnistuu, mutta aiheuttaa hankaluuden, jos tarvitsee kerätä osakohteita koriin tai listalle muutoksia varten. Osakohteet-välilehdellä ei voi valita tietueita koriin tai listalle. Olisiko mahdollista saada tuo "analytic"-muotoinen haku toimimaan samalla logiikalla kuin Osakohteet-välilehti, jolloin tuon voisi jättää näkyville tai sitten saada Osakohteet-välilehdelle tietueiden valintamahdollisuus?

**Comment by piiaseme** [comment]
Tässä muutama OUTIn testillä oleva aineistotyypitön tietue:
https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=559739
https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=414835
https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1004978

Olisko nämä esimerkit semmoisia mitä Anneli halusitkin?

**Comment by AnneliO** [comment]
@piiaseme ja @pirliis Noiden tietuiden käyttämissä kuvailupohjissa on määritetty väärä tieto Auktorisoitu arvo -kohtaan 942c-kentässä. Siinä pitäisi olla MTYPE, kun siinä on nyt itemtypes. Korjasin tuon ekan tietueen käyttämän kuvailupohjan oikeaksi, niin se näkyy nyt oikein.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/d33384e3-3e66-4cad-9096-2b45b8c7a119)

Käytännössä se nyt yrittää hakea nidetyypeistä aineistotyyppien tunnuksia ja niille kuvauksia ja kun niitä ei ole, niin ruudulla näytetään tyhjää.

**Comment by AnneliO** [comment]
> Piilottaminen onnistuu, mutta aiheuttaa hankaluuden, jos tarvitsee kerätä osakohteita koriin tai listalle muutoksia varten. Osakohteet-välilehdellä ei voi valita tietueita koriin tai listalle. Olisiko mahdollista saada tuo "analytic"-muotoinen haku toimimaan samalla logiikalla kuin Osakohteet-välilehti, jolloin tuon voisi jättää näkyville tai sitten saada Osakohteet-välilehdelle tietueiden valintamahdollisuus?

Tämä vaatii todennäköisesti lisäkehitystä.

Pikaratkaisuna osakohteet saa haettua indeksistä record-control-number eli kopsaa joko emon 001:stä tai osakohteen 773w:stä tietuenumeron ja tekee sillä haun tuohon indeksiin. 

Esim.

record-control-number:272972

**Comment by piiaseme** [comment]
> @piiaseme ja @pirliis Noiden tietuiden käyttämissä kuvailupohjissa on määritetty väärä tieto Auktorisoitu arvo -kohtaan 942c-kentässä. Siinä pitäisi olla MTYPE, kun siinä on nyt itemtypes. Korjasin tuon ekan tietueen käyttämän kuvailupohjan oikeaksi, niin se näkyy nyt oikein.
> 
> ![kuva](https://user-images.githubusercontent.com/33121325/252325836-d33384e3-3e66-4cad-9096-2b45b8c7a119.png)
> 
> Käytännössä se nyt yrittää hakea nidetyypeistä aineistotyyppien tunnuksia ja niille kuvauksia ja kun niitä ei ole, niin ruudulla näytetään tyhjää.

Tuotannossa olikin kaikilla 942c-kentässä MTYPE ja nyt myös testikannassa on kaikilla kuvailupohjilla 942c-kentässä MTYPE.

**Comment by ajrajala** [comment]
Vaskissa piilotus on ollut jo jonkin aikaa tuotannossa käytössä, ei olla huomattu piilottavan mitään ylimääräistä.

**Comment by AnneliO** [comment]
Suljen tämän tiketin, koska alkuperäinen tarve on täytetty. CSS:t löytyvät myös IntranetUserCSS-kirjastosta.
