### ISSUE TITLE
Sähköpostina lähetettävien noutoilmoitusten lähettäjäosoite muuttunut

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#616]
### Mikä vikana?

Ainakin OUTIssa versiopäivityksessä on tullut muutos sähköpostina lähetettävien noutoilmoitusten lähettäjäosoitteeseen. Nyt lähettäjänä on taas noutokirjaston sähköpostiosoite, kun se pitäisi olla noreply@koha-suomi.fi. 

Sähköpostina lähetettävissä eräpäivämuistutuksissa lähettäjänä on edelleen noreply@koha.suomi.fi, joten ongelma ei koske niitä.

### Mitä pitäisi tapahtua

Sähköpostina lähetettävien noutoilmoitusten lähettäjänä pitäisi olla noreply@koha-suomi.fi, joka on määritelty sähköpostien lähettäjäosoitteeksi kirjastojen tiedoissa.

**Comment by lasse-koha** [comment]
Korjaus tulossa testeille seuraavan buildin yhteydessä. Ilmeisesti reply_address on tarkoituksella tyhjä ja ollut edellisessäkin versiossa?

**Comment by AnneliO** [comment]
Hmm.. näyttää tosiaan siltä, että reply_address on ollut ainakin viimeiset pari vuotta tyhjä näissä viesteissä.

**Comment by AnneliO** [comment]
Tähän liittyy myös tiketti [KohaSuomi/koha-plugin-print-pdf-notices #2](https://github.com/KohaSuomi/koha-plugin-print-pdf-notices/issues/2).

**Comment by emta001** [comment]
Viety testeille.

**Comment by piiaseme** [comment]
Testattu testillä. Osoite muodostuu nyt oikein.

**Comment by pirliis** [comment]
Lähettäjäosoitteeksi muutettu jälleen kirjaston lähettäjäosoite (OUTIssa noreply@koha-suomi.fi). Korjaus tuotu tuotantoon 21.8.2023. Suljen tiketin.
