### ISSUE TITLE
Taustatöiden siivousskripti päivittäin ajettavaksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#618]
### Tukipyyntö

Taustatöiden siivousskripti pitää muuttaa ajettavaksi päivittäin. Muuten asetukset pysyy samana eli poistetaan kuukautta vanhemmat päättyneet ja peruutetut työt. 

Nyt skripti ajetaan kerran kuussa ja jonoa kertyy uutena tulleiden elasticsearchin indeksointien vuoksi liikaa jonoon.

**Comment by lmstrand** [comment]
Muutos tehty cleanup_background_jobs.pl -skriptiin koha-suomi-utilityyn. Repo päivitettävä tuotantoon ja cronit muutettava käyttämään --days -vipua.

**Comment by lmstrand** [comment]
skripti päivitetty, pullittu tuotantoon ja cronit muutettu.
