### ISSUE TITLE
Lappi: Asiakastieto antaa "virhe 500"

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#620]
### Mikä vikana?

Asiakastiedoissa tulee "virhe 500". Missä vika? Kaikki tiedot näyttäisi olevan oikein. 
borrowernumber=446484

**Comment by AnneliO** [comment]
Minun tutkinnoissa ei löytynyt mitään erityistä. Asiakkaalla ei ole lainoja eikä varauksia ja syntymäaika on oikean muotoinen.

**Comment by emta001** [comment]
Tänmmöstä tulee lokeihin:

_Invalid local time for date in time zone: Europe/Helsinki_

**Comment by emta001** [comment]
Luullakseni ongelma johtuu asiakkaan dateexpiry-arvosta, 2032-10-11. Ainakin aiemmin Kohassa on ollut ongelmaa vastaavan kentän kanssa kellojen siirtelystä johtuen ([bug 23079](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=23079)). Tässä tapauksessa tuo päivämäärä ei kyllä osu talviaikaan siirtymisen tienoille, mutta jotain samantyylisestä ongelmasta tässä saattaisi olla kyse. Kokeilen muuttaa tuon arvo vaikka päivällä eteepäin.

**Comment by emta001** [comment]
Ongelmana onkin asiakkaan syntymäaika, silloin on Suomessa siirrytty kesäaikaan :D Pika-apuna lienee siirtää syntymäaikaa päivällä eteen- tai taaksepäin, mutta isompi korjaus pitänee tehdä yhteisön kautta.

**Comment by PiaKusmin** [comment]
Miten tällainen asia viedään yhteisöön? Voinko sulkea tämän tiketin?

**Comment by PiaKusmin** [comment]
Ja asia tosiaan korjaantui muuttamalla asiakkaan syntymäpäivää...

**Comment by emta001** [comment]
> Miten tällainen asia viedään yhteisöön? Voinko sulkea tämän tiketin?

Pitää ensin tutkia tapahtuuko siellä tämä sama virhe. Jos ei, niin pitää etsiä bugi, jossa se on korjattu ja tuoda meille testattavaksi. Jos yhteisössä on sama virhe, pitää tehdä sinne tiketti ja mahdollisesti myös korjaus. Sitten sen korjauksen voi tuoda meillekin.

Sulje vaan tämä tiketti, teen uuden, koska tämä on nyt varmaan laajempi ongelma. Muutkin vastaavat päivämäärät saattaa herjailla vähän joka paikassa, tää vaan sattu nyt tulemaan esille.

**Comment by PiaKusmin** [comment]
Ok. Emmin luvalla siis suljen tiketin. :)
