### ISSUE TITLE
Lappi: Hakutuloksen saatavuusnäkymä ei päivity

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#623]
### Mikä vikana?

Hakutuloksissa näkyy edelleen niteitä TOPK varastoidut tilassa, vaikka tila on poistettu käytöstä ko. niteiltä 31.5.2023. 
Nidetiedoissa tieto näkyy oikein.

![image](https://github.com/KohaSuomi/Koha/assets/99241432/69774fa6-fe7c-4364-b70b-7493f6e0119e)

### Mitä pitäisi tapahtua

Saatavuustiedot pitäisi päivittyä myös hakutulossivulle. 

### Jotain muuta?

Onko Redinen tiketistä [3233](https://tiketti.koha-suomi.fi/issues/3233) apua?

**Comment by LeenaKinnunen** [comment]
Tilanne ei ole korjaantunut, nostin prioriteetin korkeaksi, koska tiedonhaku näyttää nyt virheellisiä tuloksia.

**Comment by janPasi** [comment]
Indeksoidaan Lappi uudestaan ja katsotaan korjaantuuko ongelma sillä.

**Comment by LeenaKinnunen** [comment]
Yksi nide oli vielä Tornion varastoiduissa (biblionumber=205170&itemnumber=360673), muutin sen käsin pois TOPK varastoidut-tilasta. Näkyy vastaavasti virheellisenä, seuraan tilannetta korjaantuuko hakutulosnäkymä.

**Comment by LeenaKinnunen** [comment]
Em. niteen tilanne on korjaantunut. Suljen tiketin.
