### ISSUE TITLE
Asiakastietojen avauksessa 500-virhe, jos asiakkaan syntymäaika on kesä/talviaikaan siirtymispäivä

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#624]
### Mikä vikana?

Ainakin Lapissa tuli vastaan tapaus, jossa asiakastietojen avaaminen johti 500-virheeseen, koska asiakkaan syntymäaikana oli päivämäärä 1942-04-03. Tuolloin Suomessa on siirrytty kesäaikaan ja perlin DateTime moduulista tällaiset päivämäärät ovat virheellisiä. Vastaavaa ongelmaa on ollut myös dateexpiry-kentän kanssa, siihen on tehty yhteisössä korjaus [bugissa 23079](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=23079).

Tutkitaan tapahtuuko vastaavaa yhteisössä ja etsitään sieltä korjaus. Jos korjausta ei ole, tehdään yhteisöön tiketti ja mahdollisesti myös korjaus.

### Kuinka toistaa ongelma/asia

1. Etsi asiakas, jonka syntymäaika on 3.4.1942 (tai jokin muu kesä/talviaikaan siirtymispäivä).
2. Yritä avata asiakkaan tiedot Kohan kautta
3. Koha näyttää virhe 500 sivun.

**Comment by emta001** [comment]
Tämä korjaantuu seuraavassa versiossa. Laitan tämä odottaa-tilaan.

**Comment by pirliis** [comment]
OUTIssa tuli just vastaava tapaus eli asiakkaan haku antaa virhettä 500. Asiakkaan syntymäaika on 3.4.1942. 
Asiakkaan id: 129277
Voisiko tietokannan päässä muuttaa vaikka syntymäajan virheelliseksi 2.4.1942, niin laitamme asiakkaalle huomautuksen, että korjataan syntymäaika, kun korjaus on tuotu tuotantoon?

**Comment by emta001** [comment]
> OUTIssa tuli just vastaava tapaus eli asiakkaan haku antaa virhettä 500. Asiakkaan syntymäaika on 3.4.1942. Asiakkaan id: 129277 Voisiko tietokannan päässä muuttaa vaikka syntymäajan virheelliseksi 2.4.1942, niin laitamme asiakkaalle huomautuksen, että korjataan syntymäaika, kun korjaus on tuotu tuotantoon?

Asiakkaan syntymäpäivä on nyt muutettu.

**Comment by AnneliO** [comment]
4.10.1942 on toinen vastaava ongelmapäivämäärä. Silloin siirryttiin takaisin talviaikaan.

**Comment by Kati-Helle** [comment]
Hellessä nyt vastaava tapaus. Kiitos Annelille tiedosta :)
Vaihdatteko asiakkaan syntymäpäivä-kentän arvon.

AsiakasID
9441

Asiakkaan dateofbirth nyt 
1942-04-03

Uudeksi väliaikaiseksi dateofbirth arvoksi päiväys ennen oikeaa eli 
1942-04-02

**Comment by paxed** [comment]
> Hellessä nyt vastaava tapaus. Kiitos Annelille tiedosta :) Vaihdatteko asiakkaan syntymäpäivä-kentän arvon.
> 
> AsiakasID 9441
> 

Muutettu.

**Comment by pirliis** [comment]
> OUTIssa tuli just vastaava tapaus eli asiakkaan haku antaa virhettä 500. Asiakkaan syntymäaika on 3.4.1942. Asiakkaan id: 129277 Voisiko tietokannan päässä muuttaa vaikka syntymäajan virheelliseksi 2.4.1942, niin laitamme asiakkaalle huomautuksen, että korjataan syntymäaika, kun korjaus on tuotu tuotantoon?

OUTIssa asiakkaalle vaihdoin oikean syntymäpäivän 3.4.2024. Ei anna enää virhettä 500.

**Comment by pirliis** [comment]
> > OUTIssa tuli just vastaava tapaus eli asiakkaan haku antaa virhettä 500. Asiakkaan syntymäaika on 3.4.1942. Asiakkaan id: 129277 Voisiko tietokannan päässä muuttaa vaikka syntymäajan virheelliseksi 2.4.1942, niin laitamme asiakkaalle huomautuksen, että korjataan syntymäaika, kun korjaus on tuotu tuotantoon?
> 
> OUTIssa asiakkaalle vaihdoin oikean syntymäpäivän 3.4.2042. Ei anna enää virhettä 500.

**Comment by PiaKusmin** [comment]
Myös Lapissa saatiin korjattua oikeaksi.

**Comment by emta001** [comment]
Hieno juttu! Suljen tiketin.
