### ISSUE TITLE
Oman käyttäjätunnuksen vaihtaminen aiheuttaa internal server errorin

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#625]
### Mikä vikana?

Vaihdoin itselleni työntekijätilin käyttäjätunnusta, kun olin kirjautuneena kyseiselle tilille. Tästä aiheutui tallennuksen yhteydessä internal server error. Tunnus oli kuitenkin tallentunut oikein. Valitin asiasta kehittäjälle, joka katsoi, että ongelma johtui tästä: "Can't call method "password_expired" on an undefined value at /home/koha/Koha/C4/Auth.pm line 1782."

Kyseessä oli käyttäjätili, jolla oli voimassaoloaikaa v. 2032 saakka. Kun muutin voimassaolopäivää käsin ja samassa yhteydessä muutin käyttäjätunnusta, tallennus onnistui ilman virhettä.

**Comment by lmstrand** [comment]
Korjattu yhteisössä.
https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33815

**Comment by AnneliO** [comment]
Koha-Suomen palaveri: Korjaus seuraavassa versionvaihdossa.

**Comment by IrinaHalminen** [comment]
Kokeilin nyt tätä. Tunnus tallentuu oikein ja Koha heittää samalla ulos järjestelmästä kirjautumissivulle (mikä onkin loogista, koska käytössä ollutta tunnusta ei ole enää olemassa). Onko hyväksyttävä toimintamalli vai pitäisikö tunnuksen tallentua ja tulla jokin ilmoitus ennen uloskirjausta?

**Comment by lmstrand** [comment]
Yhteisön hyväksymä ja aika loogiselta kuulostaa. Voisit tehdä yhteisön bugzillaan tiketin/kommentoida olemassaolevaan ilmoituksen lisäämisestä jos näät tarpeelliseksi. Keskustelua aiheesta yhteisötiketissä https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30700. Ei mainita kylläkään mitään ilmoitusta ennen pääsivulle siirtymistä.

**Comment by IrinaHalminen** [comment]
Kyllä, itsellänikin tuli vastaan vain siksi, että tein itselleni toista tunnusta. :) Suljen.
