### ISSUE TITLE
Lappi: Saarenkylän kirjaston remontti - niteille not_loan-tila 26.6.

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#627]
### Tukipyyntö

Toimenpiteet koskevat toimipisteitä: ROSA (Saarenkylän kirjasto). 
Saarenkylän kirjasto menee remonttiin, eikä kirjastossa oleva aineisto ole käytettävissä 26.6. - 30.7.2023

Tarvitsemme seuraavan toimenpiteen aineistolle:

Kaikille ROSA:n havaintopisteessä saatavana oleville niteille muutetaan not_loan arvo 9 (ROSA varastoidut). Jos niteellä on jo jokin muu not_loan arvo, siihen ei kosketa (esim. 6 laskutettu, -1 tilattu).
Muutoksesta jätetään myös pois lainassa olevat, kuljetettavana olevat ja noutoa odottavat niteet.

Muutos tulisi tehdä 26.6. heti aamulla, koska kirjasto on omatoimikäytössä 25.6. iltaan. 

Not_loan-tila 9 poistetaan ROSA:n niteiltä 30.7. Mikäli remontti viivästyy, ilmoitetaan uusi not_loan-tilan poistopäivä.

**Comment by emta001** [comment]
Muutos tehty, koski 36592 nidettä.

```
create table ks_230626_items_627 SELECT i.itemnumber, i.notforloan FROM items i LEFT JOIN reserves r ON (i.itemnumber = r.itemnumber) LEFT JOIN branchtransfers bt ON(r.itemnumber = bt.itemnumber) WHERE i.notforloan = 0 AND i.holdingbranch = "ROSA" AND onloan IS NULL AND r.found IS NULL AND i.itemnumber NOT IN (select itemnumber from branchtransfers where tobranch = "ROSA" and datearrived IS NULL); 

UPDATE items i LEFT JOIN reserves r ON (i.itemnumber = r.itemnumber) LEFT JOIN branchtransfers bt ON(r.itemnumber = bt.itemnumber) SET i.notforloan = "9" WHERE i.notforloan = 0 AND i.holdingbranch = "ROSA" AND onloan IS NULL AND r.found IS NULL AND i.itemnumber NOT IN (select itemnumber from branchtransfers where tobranch = "ROSA" and datearrived IS NULL);
```

**Comment by LeenaKinnunen** [comment]
Kiitos! Suljen tiketin.

**Comment by PiaKusmin** [comment]
Toimipisteen ROSA (Saarenkylän kirjasto) kaikilta niteiltä tulee poistaa not_loan arvo 9. Jos niteellä on jo jokin muu not_loan arvo, siihen ei kosketa (esim. 6 laskutettu, -1 tilattu).

Eli Saarenkylän varastoidut (not_loan arvo 9) niteet vapautetaan saatavana tilaan.

Muutos tulisi tehdä heti.

**Comment by paxed** [comment]
notforloan muutettu 0:ksi kaikilta niteiltä joilla oli notforloan=9 ja holdingbranch=ROSA. Muutos koski 38097 nidettä.

**Comment by PiaKusmin** [comment]
Kiitos! Jostain syystä sinne jäi 11 nidettä, mutta mie voin muuttaa ne käsin. :)
