### ISSUE TITLE
Nidevaraus ei estä uusimista, kun käytössä AllowRenewalIfOtherItemsAvailable-asetus

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#630]
### Mikä vikana?

Vaskissa otettiin käyttöön asetus AllowRenewalIfOtherItemsAvailable, joka mahdollistaa uusia varatun teoksen silloin kun saatavilla on riittävästi niteitä jotka voivat täyttää varauksen. Käyttöönoton jälkeen tuli esille, että asetus ei osaa kuitenkaan huomioida nidevarauksia.

Löysin Bugzillasta tuoreen tiketin asiasta: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32878. Saakohan tätä korjausta tuotua meille käyttöön?

### Mitä pitäisi tapahtua

Jos lainassa olevaan niteeseen kohdistuu nidevaraus, uusinnan pitäisi olla estetty vaikka tietueella olisikin muita saatavilla olevia niteitä.

### Kuinka toistaa ongelma/asia

1. Etsi tietue, jolla on useampi saatavilla oleva nide eikä varauksia entuudestaan
2. Lainaa jokin niteistä ja aseta eräpäiväksi esim. seuraava päivä
3. Tee kyseiseen niteeseen varaus
4. Mene asiakkaan lainoihin ja huomaa, että nide on varauksesta huolimatta uusittavissa

**Comment by Tuomas-Kyyti** [comment]
Sama ongelma huomattiin myös Kyytissä ja meillä myös _AllowRenewalIfOtherItemsAvailable_-asetuksena _Salli_. Toivottavasti saadaan korjattua.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 10.8.2023: Tuodaan korjaus meidän versioon.

**Comment by lasse-koha** [comment]
Tuotu testeille.

**Comment by ajrajala** [comment]
En onnistunut saamaan aikaiseksi tilannetta, jossa nidevaraus estäisi uusimisen. Loin ensin tilanteen, jossa tietueessa oli saatavilla-tilaisia niteitä ja nidevaraus niteeseen joka on lainassa asiakkaalla. Asiakkaan lainoissa nide näkyi uusittavissa.

Lainasin sen jälkeen tietueen muut saatavilla-tilaiset niteet. Edelleenkin nide näkyy asiakkaan tiedoissa uusittavissa olevana. 🤔 Kyseessä [tämän testiasiakkaan](https://vaski-test.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=307898) laina Ukkometso (nide 20203116031).

**Comment by Tuomas-Kyyti** [comment]
Sama havainto. Kyyti-testillä sai nidevaratun lainan edelleen uusittua.

**Comment by lasse-koha** [comment]
Omalla testikoneellani toimii oikein, "Uusinta"-sarakkeessa on "Varattu"-linkki niteen varauksiin, nidettä ei pysty valitsemaan uusittavaksi. Olisikohan tässä taas joku välimuistiongelma?

**Comment by AnneliO** [comment]
Auttaako, jos sivun päivittää ctrl+F5?

**Comment by lasse-koha** [comment]
> Auttaako, jos sivun päivittää ctrl+F5?

Näkyy nyt oikein vaski-testillä.

**Comment by ajrajala** [comment]
Näyttäisi minusta toimivan halutulla tavalla:
- Nidevaraus estää kyseisen niteen uusimisen aina (riippumatta siitä onko tietueella muita saatavilla olevia niteitä vai ei).
- Nidevaraus ei estä muiden niteiden uusimista (riippumatta siitä onko tietueella muita saatavilla olevia niteitä vai ei).

**Comment by Tuomas-Kyyti** [comment]
Myös Kyyti-testillä vaikuttaa nyt toimivan oikein.

**Comment by Kati-Helle** [comment]
Toimii myös Helle-testillä. Hienoa, että tämän asetuksen ominaisuus on nyt toimiva ja käyttökelpoinen!

**Comment by ajrajala** [comment]
Toimii tuotannossa, mutta sellainen huomio tuli nyt sattumalta vastaan että jos nidevaraus kohdistuu niteeseen joka ei ole varattavissa (niteellä vaikkapa ei lainata tai kadonnut -tila) eikä tietueella ole muita saatavilla olevia niteitä, estyy myös toisen lainassa olevan niteen uusiminen. Tilanne [tällä testitietueella](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=146018), testiasiakkaalla VASKI088534 lainassa olevaa nidettä ei pysty tällä hetkellä uusimaan vaikka nidevaraus kohdistuu tietueen toiseen niteeseen.

**Comment by lasse-koha** [comment]
Erikoinen tilanne, vaikea äkkiseltään sanoa onko tarkoituksellista vai ei, ei kuitenkaan suoraan johdu näistä muutoksista. Varattavuuden tarkistamisen logiikassa ainakin on sekavuuksia/virheitä joihin on mahdollisesti tulossa korjauksia: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32702

**Comment by ajrajala** [comment]
Suljen tiketin koska viimeisenä mainittu ongelma ei johdu tehdyistä muutoksista. Tehdään ongelmasta oma tiketti, jos koetaan tarpeelliseksi, ongelma kuitenkin aika marginaalinen.

**Comment by pirliis** [comment]
Sellainen huomio OUTIsta, kun järjestelmäasetus  AllowRenewalIfOtherItemsAvailable on päällä eli "Salli", nidevaraus estää muiden lainassa olevien niteiden uusinnan, jos yhtään nidettä ei ole saatavana-tilassa. 

Aiemmista testauksista on kommentti: _Nidevaraus ei estä muiden niteiden uusimista (riippumatta siitä onko tietueella muita saatavilla olevia niteitä vai ei)._

Näyttäisi kuitenkin niin, että jos tietueessa on saatavana olevia niteitä, nidevaraus ei estä muiden lainassa olevien niteiden uusintaa, mutta jos kaikki tietueen niteet ovat lainassa, nidevaraus estää niiden uusinnan.

**Comment by AnneliO** [comment]
> Sellainen huomio OUTIsta, kun järjestelmäasetus AllowRenewalIfOtherItemsAvailable on päällä eli "Salli", nidevaraus estää muiden lainassa olevien niteiden uusinnan, jos yhtään nidettä ei ole saatavana-tilassa.
> 
> Aiemmista testauksista on kommentti: _Nidevaraus ei estä muiden niteiden uusimista (riippumatta siitä onko tietueella muita saatavilla olevia niteitä vai ei)._
> 
> Näyttäisi kuitenkin niin, että jos tietueessa on saatavana olevia niteitä, nidevaraus ei estä muiden lainassa olevien niteiden uusintaa, mutta jos kaikki tietueen niteet ovat lainassa, nidevaraus estää niiden uusinnan.

Pirkko-Liisa, teetkö tästä ongelmasta uuden tiketin?

**Comment by pirliis** [comment]
Testasin Koha-versiossa 24.05 tilannetta, että tietueen kaikki niteet olivat lainassa, mutta yhteen niteeseen kohdistui nidevaraus. Kaikki muut niteet pystyi uusimaan, ainoastaan nidevarattua nidettä ei voinut uusia eli toimii toivotulla tavalla. Ei tarvitse tehdä tikettiä. 😊
