### ISSUE TITLE
Varauksen vanhenemis-cron päälle

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#631]
### Tukipyyntö

Saisimmeko käyttöön ajon, joka lisäisi varauksille vanhenemispäivän mikäli tieto puuttuu varaukselta? 

Ajo ollut aikaisemmin käytössä. Asiasta keskusteltiin pääkäyttäjäpalaverissa 30.5. ja cronin päälle laitto sai kannatusta kaikilta läsnä olevilta.

**Comment by lmstrand** [comment]
Croni löytyi vanahsta repositoriosta:

https://github.com/KohaSuomi/Koha/blob/production/misc/cronjobs/holds/set_expirationdate_for_holds.pl

Asettaa vanhenemispäivän 2 vuoden päähän varauspäivästä.

**Comment by lasse-koha** [comment]
Oliko cronin ajoituksesta päätöstä/toivomuksia? Laitoin nyt testeille ajoon 23:30, vanhenemispäivä tulee 3 vuoden päähän.

**Comment by lasse-koha** [comment]
Ja tuleeko nyt sitten kaikille kimpoille?

**Comment by pknuuti** [comment]
Luulisin, että kaikille. Ainakin Vaaralle saa laittaa päälle.

**Comment by sksandel** [comment]
Kukaan pääkäyttäjäryhmässä ei vastustanut cronia ja miksi vastustaisikaan? Ajon ajankohdasta ei ollut päätöstä tai toivetta. Tuo mikä testeillä on, kuulostaa ihan sopivalta.

**Comment by emta001** [comment]
Varauksien vanhenemiscronista luovuttiin jo edellisessä versionvaihdossa, koska käyttöön otettiin asetukset _DefaultHoldExpirationdate_, _DefaultHoldExpirationdatePeriod_ ja _DefaultHoldExpirationdateUnitOfTime_. Näiden ollessa päällä, varauksen vanhenemispäivän tulisi muodostua jo varausta tehdessä. Periaatteessa cronille ei siis pitäisi olla käyttöä. 

Onko nyt siis niin, että varauksilta jää puuttumaan vanhenemispäivä joissakin tilanteissa? Siinä tapauksessa pitää korjata mieluummin tuo asetus kuin tuoda cronia uudestaan.

**Comment by ajrajala** [comment]
Vanhenemispäivä jää puuttumaan, jos kiinni jääneeltä varaukselta peruuttaa Odottaa-tilan tai Kuljetus-tilan tietueen varausjonon kautta. Vanhemispäivän pystyy kyllä asettamaan manuaalisesti, mutta käytännössä sitä ei aina muisteta tehdä.

Järkevämpää kyllä, jos toimintatavan saisi muutettua niin että DefaultHoldExpirationdate asettaisi vanhenemispäivän myös silloin, kun noudettavaksi/kuljetettavaksi asetetun varauksen tilan peruuttaa. Voin tehdä tästä tiketin.

**Comment by emta001** [comment]
> Vanhenemispäivä jää puuttumaan, jos kiinni jääneeltä varaukselta peruuttaa Odottaa-tilan tai Kuljetus-tilan tietueen varausjonon kautta. Vanhemispäivän pystyy kyllä asettamaan manuaalisesti, mutta käytännössä sitä ei aina muisteta tehdä.
> 
> Järkevämpää kyllä, jos toimintatavan saisi muutettua niin että DefaultHoldExpirationdate asettaisi vanhenemispäivän myös silloin, kun noudettavaksi/kuljetettavaksi asetetun varauksen tilan peruuttaa. Voin tehdä tästä tiketin.

Näinhän se tosiaan oli. KYllä tuo kannattaa tosiaan korjata mieluummin, kuin taas tuoda meille yksi oma palikka lisää huollettavaksi :D

**Comment by ajrajala** [comment]
Nyt kun korjauksesta on tiketti tehtynä niin tämän voinee sulkea. Onkohan testeillä vielä croni päällä, se pitää varmaan muistaa ottaa pois jottei sitten sekoita testausta kun Emmi saa korjauksen tuotua testeille?
