### ISSUE TITLE
Nidepaketin palautus ei onnistu

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#632]
### Mikä vikana?

Aloitin testaamaan Kyytin testikannassa nidepaketti-toimintoa. Tein nidepaketin ja sinne niteitä. Lainaus onnistui, mutta palautuksessa ilmeni ongelma. Itse paketin palautuksen jälkeen avautuu ikkuna, johon luetaan paketin sisältöjen viivakoodit. Tässä ikkunassa ei ole painikkeita, jolla palautus vahvistetaan tai perutaan. Ikkunasta ei pääse mitenkään pois. Painikkeet puuttuivat sekä suomen- että englanninkielisessä käyttöliittymässä. Kohan ohjeessa painikkeet näkyvät, samoin sandboxissa testaessani.

Kovin kiireellinen asia tämä ei ole. Meillä ei ole akuuttia tarvetta saada nidepaketteja käyttöön, mutta olisi kiva kuitenkin jossain kohtaa testata toimintoa.

### Mitä pitäisi tapahtua

Palautusikkunassa pitäisi näkyä painikkeet, jolla vahvistetaan tai perutaan palautus.

### Selain

```markdown
Firefox 102.11.0esr, Chrome 114.0.5735.110
```

### Jotain muuta?

Kyytin testikanta:
![itembundle](https://github.com/KohaSuomi/Koha/assets/99244794/bd8f9d04-fe98-4ec3-b5b3-c1e22016103f)

Kohan ohjeet:
![itembundle_buttons](https://github.com/KohaSuomi/Koha/assets/99244794/a23cfc79-dca8-44b7-8bfb-de73fe17fb5d)

**Comment by Tuomas-Kyyti** [comment]
Jaha, kyse onkin, että jokin piilotus intranetusercss-rimpsussa piilottaa napit. Kun tyhjensin sen, alkoivat napit näkyä.

**Comment by AnneliO** [comment]
Jos lisäät noiden rimpsujen alle vielä tällaisen, niin toimisko se sitten oikein kaikkialla, missä on tarpeen.? Eli tarpeelliset napit piilottuu ja/tai on näkyvillä:

```
body#circ_returns.circ.modal-open div#bundle-needsconfirmation-modal.modal.fade.audio-alert-action.block.in button.btn.btn-default { display: initial; } /* Tuo näkyville nidepaketin palautuksessa Vahvista palautus ja merkkaa puuttuvat niteet kadonneiksi -nappi. Se piilottuu ensimmäisen rimpsun vuoksi */
```
Eli tuolla rimpsulla palautetaan alkuperäiset "asetukset" silloin, kun modaalissa (popparissa) on tuo bundle-needsconfirmation-jutska. Eli alkuperäinen asetus on, että nappi näytetään.

**Comment by Tuomas-Kyyti** [comment]
Kiitos, vaikuttaa toimivan oikein. Suljen tiketin.
