### ISSUE TITLE
Vaski: Varauksen noutomuistutus käyttöön

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#633]
### Tukipyyntö

Vaskissa haluttaisiin ottaa käyttöön varauksen noutomuistutuksen (HOLD_REMINDER) lähetys. Ilmeisesti lähetykeen määritellään kuinka monen päivän jälkeen saapumisilmoituksen lähetyksestä hold_reminder lähetetään ja huomioidaanko laskennassa eräpäiväkalenterin kiinniolopäiviä? Vaskissa saisi määritellä niin, että

- viesti lähtee 5 aukiolopäivän kuluttua saapumisilmoituksesta (kalenterin kiinniolopäiviä EI lasketa mukaan)
- viesti lähtee ainoastaan sähköpostilla (piilotamme kyllä viestiasetuksista mahdollisuuden valita tekstiviesti, mutta ilmeisesti croniinkin saa määriteltyä ettei tekstareita lähde?)

Testailen lähetyksen ja viestipohjan toimivuuden, kun lähetys on laitettu päälle. Pidämme siis varausmuistutuksen viestiasetukset piilossa Kohasta ja Finnasta, kunnes testaus on saatu tehtyä.

**Comment by ajrajala** [comment]
Heitin määräajan nyt ensi viikon alkuun, ei ole sinänsä kyllä päivän päälle kun joka tapauksessa testaillaan toimintoa ennen kuin annetaan kenenkään pistää viestiasetusta päälle itselleen.

**Comment by ajrajala** [comment]
Kiitos! Testailen vielä toimivuuden testivarauksilla, jätän tiketin siksi aikaa Odottaa-tilaan.

**Comment by ajrajala** [comment]
Testasin tätä ja sähköpostit muodostui muuten ok, mutta eräpäiväkalenterin kiinniolopäiviä ei lähetys huomioinut. Triggeriin ilmeisesti pystyisi lisäämään -holidays vivun, jos ymmärrän [tästä Bugzillan tiketistä](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=15986) oikein?

**Comment by ajrajala** [comment]
Joo pahoittelut, oli kieltämättä vähän huonosti muotoiltu. 😀 Mutta hyvä jos saa sen vielä mukaan!

**Comment by lmstrand** [comment]
Nyt on vipu lisätty tuohon ajastukseen. Olin ymmärtänyt väärin tuon vivun, sen kuvauksessa tosiaan sanotaan "-holidays                      use the calendar to NOT count holidays as waiting days" eli juuri niinkuin pyysitkin.

**Comment by ajrajala** [comment]
Kiitti! Testaan vielä uusiksi ja suljen sitten tiketin.

**Comment by MikkoLiimatainen** [comment]
Nämä noutomuistutukset näyttävät lähtevän asiakkaille, vaikka mitään valintaa ei olekaan. Lähtevätkö nämä nyt saapumisilmoitusasetuksen, eikä noutomuistutusasetuksen mukaan?

**Comment by lmstrand** [comment]
cronissa on tällainen määritys:

   -mtt          <message_transport_type> type of messages to send, default is to use patrons messaging preferences for Hold reminder
                                  populating this will force send even if patron has not chosen to receive hold notices
                                  email and sms will fallback to print if borrower does not have an address/phone

Tuolla asetuksella on tällä hetkellä rajattu lähetystavaksi email. Jos tuon määrityksen ottaisi pois, niin sitten ilmeisesti viestit generoitaisiin asiakkaan viestiasetuksen mukaan, mutta samalla muistutuksista alettaisiin lähettää kirjeitä jos esim. email-täppä olisi valittuna eikä emailosoitetta löydy?

**Comment by lmstrand** [comment]
Voin ottaa tuon määrityksen pois, mutta sitten ei voi enää rajata viestejä lähtemään pelkkinä emaileina. Määrityksen poistamisen jälkeen viestitäppävalintaa näköjään kunnioitetaan. Sitten jos asiakkaalle on laitettu täppä ja häneltä puuttuu mailiosoite, niin menee paperisena. Onko tämä ok?

**Comment by lmstrand** [comment]
Ja asetuksen poistamisen jäljeen myös sms-viestit kulkevat. Tosin Vaskin tuotannossa ei minun tilille ole mahdollista sms-täppää lisätä mikä on hyvä juttu. Oletteko piilottaneet sen jollain JS-rimpsulla?

**Comment by MikkoLiimatainen** [comment]
Voiko tuon postilähetyksen estää jotenkin muuten? Esimerkikisi, kun meillä ei ole mitään pohjia noille tehtynä, niin ne jäisivät lähettämättä? Ei meillä ole kuin neljä asiakasta, joilta puuttuu sähköposti, vaikka noutomuistutusvalinta on sähköposti, joten suuri ongelma ei ole kyseessä, mutta ihan turhaahan noita postilla on lähetellä.

Tekstiviestiasetukset meiltä on asikkailta poistettu ja teimme piilotukset verkkokirjastoon ja Kohaan noille asetuksille. Ihan yksinkertaiset CSS-piilotukset Kohassa, verkkokirjasto taisi vaatia JS:ää.

**Comment by lmstrand** [comment]
Samoin kuitenkin pitäisi käyttäytyä tuon lähetyksen kuin muidenkin viestipohjien kanssa.

**Comment by MikkoLiimatainen** [comment]
Eräpäiväilmoituksethan lähtevät vain sähköpostilla, joten kai tämä toimisi sitten samalla tavalla. Niissäkään ei ole print-pohjaa käytössä, eikä varmaankaan ole pakotettu email-lähetystäkään, kun ei niitä lähde muuten kuin valittuna. Vahva mielikuva minulla on, että tuon print-pohjan puuttuminen estää posti lähetykset, mutta kyllä on hankala löytää dokumentoitua tietoa asiasta.

Sanoisin, että muutetaan asetus ja katsotaan kuinka käy. Mikäli ymmärrän tämän nyt oikein, niin ei tosiaan koske montaakaan asiakasta tuo posti ja noista turhista viesteistä on nyt tullut jo varmaan enemmän valituksia kuin virheellisiä posteja lähtisi.

**Comment by lasse-koha** [comment]
Cronista poistettu -mtt email, katsotaan miten toimii.

**Comment by MikkoLiimatainen** [comment]
Viestit lähtevät nyt asiakkaan viestiasetusten mukaisesti. Näyttää siis toimivan oikein. Suljen tikietin.
