### ISSUE TITLE
Raahen Finvoice-laksut odottavat tuotannossa ajoa eteenpäin

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#634]
### Tukipyyntö

Raahessa tehtiin ensimmäisen kerran Finvoice-laskut (5 kpl) tuotannossa 7.6.2023. Laskut  eivät ole lähteneet Kohasta ajastetusti keskiviikkona 7.6. klo 11. Asiakkaan Ilmoitukset-sivulla näkyy muodostunut lasku, mutta sen tila on "odottavat". 

Lari tarkisti Kohasta lokin ja sen mukaan laskujen olisi pitänyt lähteä:

_Wed 07 Jun 2023 11:00:01 AM EEST: Start /home/koha/Koha/misc/cronjobs/run_[finvoice.pl](http://finvoice.pl/) /var/spool/koha/finvoice/ -p /etc/koha/finvoice-config.yaml -c LASKURA -v --noescape --xsd /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/OverdueTool/finvoice/Finvoice3.0.xsd --pretty
Wed 07 Jun 2023 11:00:03 AM EEST: End /home/koha/Koha/misc/cronjobs/run_[finvoice.pl](http://finvoice.pl/) /var/spool/koha/finvoice/ -p /etc/koha/finvoice-config.yaml -c LASKURA -v --noescape --xsd /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/OverdueTool/finvoice/Finvoice3.0.xsd --pretty
Wed 07 Jun 2023 11:00:03 AM EEST: Runtime 0 hours, 0 minutes, 2 seconds_

 Raaheen laskuaineisto ei ole siirtynyt.

Testiltä Raahen testilaskuja on lähetetty Raaheen onnistuneesti, viimeksi 6.6.2023. Olisiko mahdollista, että tuotannosta puuttuu vielä siirtomääritykset, minne laskujen pitäisi Kohasta lähteä? Voisiko tarkistaa ja voisiko laskut laittaa eteenpäin manuaalisesti?

**Comment by lmstrand** [comment]
Selvisikin, että Raahen laskutuskonfiguraatio (etc/koha/finvoice-config.yaml) on kommentoituna tuotannossa. Siksi laskut eivät ole menneet perille.

**Comment by lmstrand** [comment]
Paitsi että konfiguraatiossa ei ole olemassaolevaa lähetysosoitetta. Eli ei ole nyt tietoa mihin noita lähettää. Pitää varmaan odottaa, että Emmi tulee takaisin töihin ellette te ole tietoisia sftp-osoitteesta minne nuo kuuluu lähettää raahen osalta.

**Comment by pirliis** [comment]
Joo, laitoin Raaheen, että sopisiko heille, että Emmi hoitaa tämän maanantaina kuntoon. Jos Emmi ei ole maanantaina paikalla, pyydetään osoite ja mahdollisesti muut tarvittavat tiedot teille.

**Comment by pirliis** [comment]
Emmi on laittanut laskut liikenteeseen Kohasta. Raahesta on tullut tieto 13.6.2023, että laskut oli siirtyneet Rondoon ja ne ovat siirretty eteenpäin.

**Comment by pirliis** [comment]
Raahe on laskuttanut tänään 14.6. 10 finvoice-laskua, jotka ovat lähteneet Kohasta ajastetusti klo 11. Eli ajastus toimii nyt. Suljen tiketin.
