### ISSUE TITLE
Oulun Finvoice laskut laskutuspäivän mukaan -raportin muokkaus

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#635]
### Tukipyyntö

OUTIssa on raportti 586: "Oulun Finvoice laskut laskutuspäivän mukaan". Raportille tulostuu laskutettujen niteiden kappalemäärä ja yhteissumma.

Raporttia on käytetty vain Oulussa, koska muilla OUTI-kirjastoilla ei ole ollut käytössä Finvoice-laskutusta. Raahe on ottamassa käyttöön nyt myös Finvoicen ja raportille tulevat nyt myös Raahen laskut. Raporttia pitäisi muuttaa niin, että sen voisi ottaa kirjastokohtaisesti?

**Comment by lmstrand** [comment]
Lisäsin Outi-testille raportin 549, jolla saa rajattua laskutusyksikön mukaan laskut. Raporttia varten loin uuden auktorisoidun arvon LASKUYKS, jolle laitoin arvoiksi laskutietojen SellerPostCodeIdentifier-koodin. Testillä arvot olivat "OULU" ja "Raahe". Tuotannossa Oulun SellerPostCodeIdentifier-arvo on muodostuneissa laskuissa "Oulu".

Sopiiko, jos lisään tuon uuden auktorisoidun arvon tuotantoon ja siirrän raportin sinne, vai haluatteko tehdä itse/muokata auktorisoidun arvon nimeä/kuvausta?

**Comment by pirliis** [comment]
Toki sopii, että siirrät raportin tuotantoon ja teet tarvittavat määritykset. Kiitos! :)

Testasin testillä ja raportti näytti toimivan.

**Comment by pirliis** [comment]
Ehditkö Lari siirtämään raportin vai siirränkö? Meillä on seuraava finvoice-laskutus tulevana keskiviikkona ja siihen mennessä olisi hyvä, jos raportti saataisiin tuotantoon?

**Comment by lmstrand** [comment]
Siirä vain sinä.

**Comment by lmstrand** [comment]
Suljetko tiketin vielä sitten kun on kaikki ok.

**Comment by pirliis** [comment]
Testillä en tätä huomannut, kun Raahen ja Oulun testilaskut olivat tehty eri päivinä.

**Comment by pirliis** [comment]
Sekä Oulu että Raahe ovat laskuttaneet tänään ja ovat ottaneet kirjastokohtaiset raportit laskutetuista aineistoista. Raportit olivat näyttäneet oikeat laskutusmäärät ja -summat. Eli raportti on saatu toimimaan. Kiitos! Suljen tiketin.
