### ISSUE TITLE
Hae asiakkaita -haku ja Asiakkaan ID -hakuehto: hakee virheellisesti myös Hetu-avain-kentästä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#637]
### Mikä vikana?

Hae asiakkaita -toiminnon Hakukenttä-hakuehto Asiakkaan ID hakee asiakasnumeron lisäksi myös Hetu-avain-kentästä (eli asiakasmääreestä SSN).

Hakuehtoni
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fe66dbcc-d381-489f-9f59-da05a3b50c01)

Helle-hakutuloksena on nyt nämä asiakastiedot
borrowernumber=25434 (haettu arvo 77360 on asiakkaan Hetu-avain-kentässä)
borrowernumber=77360 (tämä hakutulos on ok)

Vastaavan hakutuloksen saan, kun Hakutyyppi-hakuehtona on Sisältää. 
Samoin silloin, kun käytän näytön vasemmalla olevaa Hae asiakkaita -toimintoa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4dd35ce3-5f21-404c-a025-d9a4d19d7f11)

**Comment by AnneliO** [comment]
Tämä liittynee samaan kuin #697 eli asiakasmääreitä voi haetaan kaikissa hauissa, halusipa tai ei.

**Comment by emta001** [comment]
> Tämä liittynee samaan kuin #697 eli asiakasmääreitä haetaan kaikissa hauissa, halusipa tai ei.

Saattanee siis korjaantua kun tuohon tuodaan korjaus.

**Comment by AnneliO** [comment]
Versiossa 23.11 on mahdollisuus määrittää asiakasmäärekohtaisesti, haetaanko sitä, kun tehdään haku käyttäen "perushakua".

[Kuvaus 23.11-version wikissä](https://github.com/KohaSuomi/Koha-23x/wiki/Uutta-23.x%E2%80%90versiossa#asiakasm%C3%A4%C3%A4reisiin-mahdollisuus-m%C3%A4%C3%A4ritt%C3%A4%C3%A4-haetaanko-niit%C3%A4-perushaussa).

**Comment by Kati-Helle** [comment]
Version 23.11 ominaisuus ratkaisi tämän.
