### ISSUE TITLE
Siilinjärvi: Asiakaslistat-työkalun asiakashaku ei toimi

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#638]
### Mikä vikana?

Kun yritän lisätä asiakkaita asiakaslistat-työkalussa sen omalla asiakashaulla, haku ei toimi vaan jää pyörittämään ratasta. Ei  toimi nimellä, ei kirjastokortilla.

Tavallisen asiakashaun kautta asiakkaan lisääminen listaan onnistuu.

**Comment by lmstrand** [comment]
yhteisössä korjaus: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=33829

**Comment by AnneliO** [comment]
Periaatteessa ongelman voisi kiertää ohjeiden tekoajaksi laittamalla PatronAutoComplete-järjestelmäasetukseen "Ehdota", mutta asetusta ei kannata tuotannossa laittaa päälle, joten ei se kuitenkaan toimisi sitten ohjeen mukaisesti. Tuo yhteisön korjaus tulee mukaan versiossa 23.05.

**Comment by ReettaSiili** [comment]
Nyt nextillä 23.11:ssä Asiakaslistat-työkalun asiakashaku toimii, voi hakea nimellä, korttinumerolla, id:llä.

**Comment by ReettaSiili** [comment]
Pitäisi nyt toimia, suljen tämän tiketin.
