### ISSUE TITLE
VASKI: Matkapuhelinnumeroiden kopiointi smsalertnumber-kenttään

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#640]
### Tukipyyntö

Vaskissa puuttuu noin 17000 asiakkaalta smsalertnumber, vaikka heillä on matkapuhelinnumero tiedoissa. Smsalertnumber on suurimmassa osassa tapauksista NULL ja osassa tyhjä merkkijono.

**Comment by lasse-koha** [comment]
Kopiointi tehty. Asiakkaat joilla smsalertnumber oli NULL ja joilla se oli tyhjä merkkijono erillisissä varmuuskopiotauluissa 1 ja 2 jos tätä tietoa joskus tarvitaan.

**Comment by MikkoLiimatainen** [comment]
Voisiko vielä poistaa smsalertnumberin sellaisilta asiakkailta, joilla on tyhjä mobile kenttä ja smsalertnumber=phone, niin saadaan turhat lankapuhelinnumerot pois tuosta?

**Comment by lasse-koha** [comment]
Poistettu.
