### ISSUE TITLE
Lumme: Asiakasta ei hyväksytä automaatilla

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#642]
### Mikä vikana?

Savonlinnassa on tullut tapaus, joka saattaa liittyä osittain tikettiin #609. Asiakkaalla itsellään on maksuja alle 10€ eli alle lainauskieltorajan. Hänen huollettavallaan on kuitenkin maksuja päälle 3€ eli yhteissumma menee yli 10€. Automaatit eivät suostu lainaamaan tälle asiakkaalle, mutta Kohassa lainaus onnistuu normaalisti. 

Asiakkaan ID100678.

### Mitä pitäisi tapahtua

Automaattien pitäisi antaa lainata, kun maksukatto on asiakkaalla itsellään alle 10€. Nyt automaatti näyttäisi yhdistävän huoltajan + huollettavan maksut, jolloin yhteissumma ylittää lainauskieltorajan ja automaatti ei suostu lainaamaan asiakkaalle.

**Comment by lmstrand** [comment]
Meille on tuotu korjaus sip2-branchiin, minkä piti korjata tämä ongelma ([Don't count related guarantees fees against NoIssuesChargeGuarantees](https://bugs.koha-community.org/bugzilla3/attachment.cgi?id=151971).
Onko teillä siis tämä NoIssuesChargeGuarantees-asetus päällä? Entä NoIssuesChargeGuarantorsWithGuarantees?

**Comment by Hanna-Lumme** [comment]
NoIssuesChargeGuarantees-kohdassa on summana 9,99€, NoIssuesChargeGuarantorsWithGuarantees on tyhjä.

**Comment by lmstrand** [comment]
Tuo korjaus on sittenkin meillä ja tuotannossa.

**Comment by janPasi** [comment]
NoIssuesChargeGuarantees estänee tässä lainauksen kuvauksensa mukaisesti. Eli lääkkeenä "Automaattien pitäisi antaa lainata, kun maksukatto on asiakkaalla itsellään alle 10€" vaatimukseen: Poistakaa 9.99 asetuksesta NoIssuesChargeGuarantees.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon ongelman ratkaisusta!
