### ISSUE TITLE
Vanhenemispäivä jää puuttumaan varaukselta, jolta perutaan odottaa tai kuljetettavana -tila

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#650]
### Mikä vikana?

Mikäli varaus on jo tärpännyt noudettavaksi tai kuljetettavaksi noutopaikkaan, mutta tila joudutaan vielä peruuttamaan, ei varaukselle muodostu automaattisesti uutta vanhenemispäivää vaan kenttä jää tyhjäksi.

Vanhemispäivän pystyy kyllä asettamaan manuaalisesti, mutta käytännössä sitä ei aina muisteta tehdä. Ongelman korjaamiseksi oli alun perin toivottu takaisin vanhenemispäivät asettavaa ajoa tiketissä #631, mutta tiketissä todettiin että järkevämpää olisi korjata DefaultHoldExpirationdate-asetuksen toiminta tältä osin.

### Mitä pitäisi tapahtua

Mikäli varauksen tila peruutetaan, varaukselle pitäisi laskea uusi vanhenemispäivä DefaultHoldExpirationdate-asetuksen mukaisesti.

### Kuinka toistaa ongelma/asia

1. Tee varaus ja tärppäytä se noudettavaksi
2. Mene tietueen varausjonoon ja peruuta odottaa-tila
3. Huomaa, että vanhenemispäivä-kenttä tyhjenee

**Comment by emta001** [comment]
Tämä johtuu siis siitä, että tuossa tilanteessa ei päivitetä reservedatea ja Koha asettaa uuden expirationdaten vain, jos reservedate muuttuu. Kalastelen yhteisöstä tiketin tai teen semmosen tarvittaessa, korjataan/tuodaan korjaus sitä kautta.

**Comment by ajrajala** [comment]
Ok, hyvä homma! Ja tuohon eiliseen huomioon liittyen; näköjään tuo ero siinä jäikö expirationdate puuttumaan vai ei liittyi siihen oliko varaus tehty Finnan vai Kohan kautta. Finnan kautta tehdylle varaukselle palautui alkuperäinen expirationdate, kun varauksen tilan perui.

**Comment by emta001** [comment]
> Ok, hyvä homma! Ja tuohon eiliseen huomioon liittyen; näköjään tuo ero siinä jäikö expirationdate puuttumaan vai ei liittyi siihen oliko varaus tehty Finnan vai Kohan kautta. Finnan kautta tehdylle varaukselle palautui alkuperäinen expirationdate, kun varauksen tilan perui.

Positiivista, toivottavasti en onnistu rikkomaan tätä omilla korjauksilla :D

**Comment by Kati-Helle** [comment]
Helle-testissä varauksen odottaa-tilan peruminen: voimassa olevalle varaukselle muodostui vanhenemispäivä Vanhenee-kenttään kolmen vuoden päähän varauksen tekopäivästä. Varaus tehty 13.6.2023 ja vanhenemispäiväksi 13.6.2026.

Tietueen varaukset, joista perutaan odottaa-tilainen varaus
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/8c6132fd-d68c-4a8c-bbb3-76f93844a06f)

Tietueen varaukset odottaa-tilaisen varauksen perumisen jälkeen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4adc1427-a9b0-4438-b840-eee265e55dbd)

**Comment by Kati-Helle** [comment]
Helle-testissä varauksen kuljetettavana-tilan peruminen: voimassa olevalle varaukselle muodostui vanhenemispäivä Vanhenee-kenttään kolmen vuoden päähän varauksen tekopäivästä. Varaus tehty 22.6.2023 ja vanhenemispäiväksi 22.6.2026.

Tietueen varaukset, joista perutaan kuljetettavana-tilainen varaus
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/8272b4c5-023c-4d5e-b9d3-2a24d22432db)

Tietueen varaukset kuljetettavana-tilaisen varauksen perumisen jälkeen
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/7989dc54-d8ce-44cf-9224-d17c0c84c9ee)

**Comment by ajrajala** [comment]
Vaski-testillä näyttäisi toimivan. Testattu sekä Kohan että verkkokirjaston kautta tehdyn varauksen peruuttamista Odottaa-tilasta ja Kuljetuksessa-tilasta.

**Comment by Kati-Helle** [comment]
Tulisiko varausten järjestyksen olla vielä Pvm-kentän mukaan vanhimmasta uusimpaan?
Nyt järjestäytyvät niin, että uusin tehty varaus on varausjonon ensimmäisenä.

**Comment by pirliis** [comment]
OUTIn testillä toimii.

**Comment by emta001** [comment]
Vaikuttaisi siis toimivan kuten pitääkin. Tuodaan tämä tuotantoon ensi viikon päivityksessä.
