### ISSUE TITLE
Helle: Raaseporin kirjastoauton (RASBU) voimassa olevien varauksien keskeytys 26.6.2023

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#652]
### Tukipyyntö

Keskeytättekö Raaseporin kirjastoauton (=noutopaikka) kaikki voimassa olevat varaukset maanantai-aamuna 26.6.2023.

Raaseporin kirjastoauton tunnus:
RASBU

**Comment by emta001** [comment]
Keskeytys tehty, koski 20 varausta (tällaiset määrät voi hyvin muokata jatkossa käsinkin).

```
create table ks_230626_reserves_652 like reserves;
insert into ks_230626_reserves_652 select * from reserves where branchcode in ('RASBU') and suspend=0;
update reserves set suspend=1 where branchcode in ('RASBU') and suspend=0;
```

**Comment by Kati-Helle** [comment]
Kiitos Emmi muutoksesta. Tosiaan, varauksia ei olisi ollut mahdotonta määrää yksitellen keskeytettäväksi.
Lisäsin keskeytetyille varauksille Keskeytetty tähän asti -päiväyksen.

**Comment by emta001** [comment]
> Kiitos Emmi muutoksesta. Tosiaan, varauksia ei olisi ollut mahdotonta määrää yksitellen keskeytettäväksi. Lisäsin keskeytetyille varauksille Keskeytetty tähän asti -päiväyksen.

Tosiaan, päiväyksen lisäys jäi uupumaan ajoista. Pitää muistaa ensi kerralla.
