### ISSUE TITLE
Kohan lokimoduuli ei lokita oikein tapahtumia

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#657]
### Tukipyyntö

Kohan lokitus ei toimi oikein Tuotannoissa/testeillä/nexteillä.
Ainakin outi-nextillä ja Lumpeen tuotannossa on debug-tason lokitus päällä eikä Kohan oman Logger-moduulin kautta tunnu tavaraa tulevan lokeille. Jo virkailijaliittymään kirjautumisen pitäisi lokittaa tavaraa, samoin kuin sivustojen hakupyynnöt jne. Sipohttp:n käyttämä log4perl-moduuli toimii log4perl-konfiguraation kanssa jostain syystä.

**Comment by janPasi** [comment]
Ainakin osittain näkyy liittyvän siihen että lokihakemistoissa nykyisellään olevien lokien käyttöoikeudet ovat vinksollaan.

**Comment by janPasi** [comment]
Nextien ja testien oikeudet ja omistajat korjattu. Hävitin samalla kaikki muinaiset lokit sieltä.

**Comment by emta001** [comment]
Eiköhän tän vois jo sulkea?
