### ISSUE TITLE
Varauksen noutomuistutus -viestiasetus pois tietyiltä asiakkailta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#660]
### Tukipyyntö

Varauksen noutomuistutuksen käyttöönoton yhteydessä huomattiin, että asiakkailla olikin jo valmiina viestiasetuksissa valittuna hold reminder -viestin lähetys sähköpostiin. Viestiasetus näyttäisi olevan päällä sähköpostittomillakin asiakkailla, mikä voi ehkä hämätä jos asiakas ei huomaa esim. verkkokirjastossa tarkistaa onko sähköpostiosoite tallennettuna. Lisäksi kaukopalvelun asiakaskirjastoille viestiä ei tarvitsisi lähettää.

Onnistuisiko siis poistaa ajona viestiasetus asiakkailta
1. joilla ei ole sähköpostiosoitetta tiedoissaan
2. joiden asiakastyyppi on KAUKOLAINA ?

**Comment by ajrajala** [comment]
Tämän saa tehdä aiemmin tai myöhemminkin, mutta heitin määräpäivän nyt alustavasti tämän viikon lopulle.

**Comment by MikkoLiimatainen** [comment]
Asetus poistettava myös asiakkailta, joilla asetus on sms. Emme ota tähän tekstiviestilähetystä käyttöön.

**Comment by lmstrand** [comment]
Ajastuksessa on käytetty email-vipua jolloin viestejä ei lähetetä kuin sähköpostitse.

**Comment by lasse-koha** [comment]
Asetus poistettu sähköpostittomilta ja kaukolaina-asiakkailta. Asiakkaita joilla tämä viestiasetus on tyyppiä sms olisi vielä reilu satatuhatta, näkyykö asetuksen olemassaolo näille asiakkaille jotenkin hämmentävästi vai annetaanko olla?

**Comment by MikkoLiimatainen** [comment]
Asetus näkyy verkkokirjastossa asiakkaan omat tiedot -sivulla:
![Varauksen noutomuistutus verkkokirjasto tekstiviesti](https://github.com/KohaSuomi/Koha/assets/98884651/0c598303-ce22-4f00-ab37-6793f502850f)
Eli kyllä tuo tekstiviestivalinta täytyisi saada kaikilta pois. Olisi hyvä, että mahdollisuus tekstiviestinoutomuistutukseen saataisiin kokonaan poistettua. Tein piilotukset Kohaan ja verkkokirjastoon, joten asetus on piilossa, mutta periaatteessahan sen saa nyt laitettua.

**Comment by lasse-koha** [comment]
Tekstiviestityyppiset noutomuistutusasetukset nyt myös poistettu. SMS-asetusmahdollisuuden poistamisesta pitäisi varmaankin keskustella asiantuntijaryhmässä.

**Comment by MikkoLiimatainen** [comment]
Kiitoksia! Tämä näyttäisi olevan kunnossa. Suljen tiketin.
