### ISSUE TITLE
Tarkka haku -toimintoon paluu hakutuloksen Muokkaa hakua -linkistä muuttaa tehdyn haun hakutyypin

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#663]
### Mikä vikana?

Tarkka haku -toimintoon paluu hakutuloksen Muokkaa hakua -linkistä muuttaa automaattisesti tehdyn haun hakutyypin.
(Poikkeuksena Hakusanat-osion ensimmäinen oletusarvo Nimeke, joka säilyy/ei muutu automaattisesti.)

Esim. Hakusanat-osion hakuun valittu hakutyyppi vaihtuu arvoksi Nimeke, vaikka hakuun on käytetty arvoa Tekijä.

Haun hakuehto Tekijä=Läckberg, Camilla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/84acb165-afba-40bb-8352-eae6235152b9)

Hakutulos-näyttöä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0d831495-4b67-4e20-b534-4be3b3344df9)

Hakutuloksen Muokkaa hakua -linkistä paluu Tarkka haku -toimintoon ja hakuehdoksi muuttunut Nimeke=Läckberg, Camilla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9f05d2a0-e747-45e4-a19f-661756dab724)

Vastaava tapahtuu, kun käyttää esim. Hakusanat-osiossa valmiiksi olevaa Asiasana-hakutyyppiä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/78497935-0f0b-4e0b-abca-47e0ac7c004e)

Hakutulosnäyttöä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/15398f7a-39ff-41fa-919b-6cd1c4812472)

Hakutuloksen Muokkaa hakua -linkistä takaisin Tarkka haku -toimintoon ja haettu arvo on siirtynyt Nimeke-hakutyypin kenttään
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f4874aa1-db7f-4cfc-87da-69c9b2307767)

Sama tapahtuu myös Hakusanat-osion alasvetovalikoista valituilla arvoilla.

**Comment by Kati-Helle** [comment]
Tiedoksi vielä, että esim. kahdella Hakusanat-osion ehdolla hakiessa ei tapahdu vastaavaa. 
Esimerkiksi näin hakiessa:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2a8be149-5220-4792-b270-0f6708c38d5a)

**Comment by Kati-Helle** [comment]
Tämä Hellessä käytössä oleva IntranetUserJS-rimpsu vaikuttanee hakutyypin arvon muuttumiseen, kun hakutuloksesta palaa hakuun Muokkaa hakua -linkistä:
/* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */
$(document).ready(function() {
  var elems = $("body#catalog_advsearch select[name='idx']");
  elems.eq(0).val('ti');
  elems.eq(1).val('au');
  elems.eq(2).val('su');
});


Poistin Helle-testissä rimpsun, jolloin Hakusanat-osio on tämä:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/a35decb3-fcd6-439d-8c0d-2910404cf1a0)

Tein haun:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0eacc98b-3652-4ecc-924b-6eebd779f5c2)

Hakutulosnäyttöä:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5102606b-93b9-43cf-abf9-4fff9002dba3)

Muokkaa hakua -linkistä paluu Haku-toimintoon, joka on  edelleen sama kuin haussa käytetty:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/bceadbae-72cc-45c0-99b7-8560398e87a5)

**Comment by AnneliO** [comment]
Niin kauan kuin tuo IntranetUserJS:ssä oleva valikoiden indeksien pakotus on päällä, minusta tämä ei voi toimia muulla tavalla. :)

**Comment by MikkoLiimatainen** [comment]
Olen tehnyt Vaskiin version tuosta JS-rimpsusta, joka tarkistaa onko osoiterivillä parametri edit_search ja sen mukaan päättää laitetaanko nuo pakotukset päälle vai ei. Tämä mahdollistaa hakuun palaamisen niin, että käytössä on oikeat kentät. Kokeilkaa onko tästä apua.

`// Tarkan haun Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana sivulla /cgi-bin/koha/catalogue/search.pl
$(document).ready(function() {
  let params = (new URL(document.location)).searchParams;
  let edit = params.get("edit_search");
  if (window.location.pathname == '/cgi-bin/koha/catalogue/search.pl' && !edit) {
    var elems = $("body#catalog_advsearch select[name='idx']");
    elems.eq(0).val('ti');
    elems.eq(1).val('au');
    elems.eq(2).val('su');
  }
});
//LOPPU`

**Comment by AnneliO** [comment]
@Kati-Helle oletko testannut Mikon laittaamaa versiota? :)

**Comment by Kati-Helle** [comment]
Kiitos Anneli vinkistä. Jäänyt minulta huomaamatta Mikon rimpsu.

Testasin rimpsua nyt Helle-testillä. 
Hakutuloksen Muokkaa hakua -linkistä palaaminen Tarkka haku -toimintoon vaikuttaa näin:
- hakuehtona on edelleen haussa käytetty Tekijä hakuarvoineen. Tämä on siirtynyt hakuehdoista ensimmäiseksi (oli hakiessa toisena)
- käyttämättömät hakuehdot Nimeke JA Asiasana ovat muuttuneet hakuehdoiksi Sanahaku

Tarkka haku -hakuehto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/687c4b97-b120-40fb-9633-638151e8d98f)

Hakutulosta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/7ebab197-7b16-4802-9032-2d611b5313f4)

Muokkaa hakua -toiminnolla hakutuloksesta takaisin Tarkka haku -toimintoon, jostä näkymää
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/17392dd2-e69d-421f-870e-101e9720871e)

**Comment by MikkoLiimatainen** [comment]
Juu, tuo meidän rimpsumme tosiaan pudottaa tuon esimäärittelyn pois hakukentiltä ja siksi muuttaa myös osan kentistä sanahauiksi ja muuttaa kenttien järjestystä, mutta säilyttää hakukentän ja hakutermin suhteen.

Teoriassa nuo tiedot olisi varmaankin järjestettävissä samalla tavalla kuin ne ovat olleet hakua tehdessä, jos siihen on tarvetta, koska nähdäkseni tarvittavan tiedon saa osoiteriviltä luettua, mutta itse en lähtisi tämän takia tekemään rimpsusta monimutkaisempaa.

Itse asiassa huomasin nyt, että kaikissa tilanteissa hakukenttä ei tule oikein.

Tein haun näin:
![Tehty haku 2024-03-01 102926](https://github.com/KohaSuomi/Koha/assets/98884651/e01f984e-bb06-4f15-92b8-1f957c2dc2f1)

Hakutuloksissa haku näkyy näin:
![Tulokset 2024-03-01 103039](https://github.com/KohaSuomi/Koha/assets/98884651/12f48a96-4389-4bb0-8813-e4999e9bd94b)

Haun muokkauksessa hyllypaikka-hakukenttä muuttuu sanahauksi:
![Tulokset 2024-03-01 103039](https://github.com/KohaSuomi/Koha/assets/98884651/260450e4-e67a-4eff-93ae-103bc03f3091)

Tämä johtuu toisesta rimpsusta, jossa muutetaan hyllypaikka hakuvalinnan arvo location muotoon loc, jotta haku toimii oikein. Tästä aiheutuu haun muokkauksessa tilanne, jossa hakuun tuodaan tehdyn haun loc-haku, mutta koska sitä valintaa ei hakuun palatessa ole, niin haku muuttuu sanahauksi. Jos osoiterivillä muuttaa loc-hakun location-hauksi, niin kenttä tulee oikein.

Tässä rimpsu, joka aiheuttaa tämän ongelman:
`$("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa */`

Tässä varmaan tarvitsisi tehdä rimpsu, joka hakee osoiteriviltä idx=loc -tietoa ja muuttaa hakukentän jälkikäteen oikeaksi.

**Comment by Kati-Helle** [comment]
Kiitos Mikko huomiostasi Hyllypaikka-koodiarvolla hakuun liittyen. 

Saisiko Hellessä käytössä olevan rimpsun tilalle Vaskin IntranetUserJS-rimpsun?
Hellessä käytössä olevan rimpsun nimenä (juuri nyt rivillä 482):
/* Tarkka-haku ja Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana */

**Comment by lmstrand** [comment]
Lisäämällä tällaisen rimpsun tuo loc-tieto muuttuu, kun hakua mennään muokkaamaan,

$(document).ready(function () {
  if (window.location.href.indexOf("catalogue/search.pl?advsearch=1&edit_search=1") > -1) {
      $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa, kun hakua mennään muokkaamaan*/     
  }
});

**Comment by lmstrand** [comment]
```
// Tarkan haun Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana sivulla /cgi-bin/koha/catalogue/search.pl
$(document).ready(function() {
  let params = (new URL(document.location)).searchParams;
  let edit = params.get("edit_search");
  if (window.location.pathname == '/cgi-bin/koha/catalogue/search.pl' && !edit) {
    var elems = $("body#catalog_advsearch select[name='idx']");
    elems.eq(0).val('ti');
    elems.eq(1).val('au');
    elems.eq(2).val('su');
  }
});

$(document).ready(function () {
  if (window.location.href.indexOf("catalogue/search.pl?advsearch=1&edit_search=1") > -1) {
      $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa, kun hakua mennään muokkaamaan*/     
  }
});
//LOPPU

```
Toimiiko tämä yhdistetty rimpsu halutusti? Oliko tuo loc-arvon muuttaminen ainut ongelma rimpsun kanssa?

**Comment by AnneliO** [comment]
Pitääkö [tästä rimpsusta](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#indeksointity%C3%B6ryhm%C3%A4n-tekem%C3%A4t-tiedonhaun-mukautukset) poistaa tuo location-arvon muutos? Vai pitäisikö se korjata siihen rimpsuun, jolloin se pysyy ikään kuin oikeassa asiayhteydessä?

**Comment by lmstrand** [comment]
Lisäsin tuon "Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa, kun hakua mennään muokkaamaan" -rimpsun [linkkaamaasi](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#indeksointity%C3%B6ryhm%C3%A4n-tekem%C3%A4t-tiedonhaun-mukautukset) rimpsuun mukaan.

**Comment by AnneliO** [comment]
> Lisäsin tuon "Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa, kun hakua mennään muokkaamaan" -rimpsun [linkkaamaasi](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#indeksointity%C3%B6ryhm%C3%A4n-tekem%C3%A4t-tiedonhaun-mukautukset) rimpsuun mukaan.

Nextillä riittää pelkästään tämä muutos, jotta hakuindeksipakotukset säilyvät. Eli lisäksi ei tarvita Mikon versiota pakotuksista.

**Comment by AnneliO** [comment]
Lisätty Larin tekemä lisäys myös Koha-23x-tietovarannon IntranetUserJS-wikiin.

**Comment by MikkoLiimatainen** [comment]
Niin, tuo location arvon muutos loc arvoksi ei Nextillä toimi ollenkaan, koska Nextillä hyllypaikkahaun arvo on location,wrdl. Nyt tarvitsee selvittää hakeeko tuo location,wrdl-haku oikeaa asiaa ja jos hakee, niin nuo location arvon muutokset voi pudottaa scriptistä pois.

**Comment by AnneliO** [comment]
Hmm.. minulla kyllä valikon arvo muuttuu loc-arvoksi ja hakukin toimii minusta oikein. 🤔

**Comment by MikkoLiimatainen** [comment]
Niin tuossa 23.11-versiossa toinen loc muutos on oikein, mutta hakua muokatessa muutos kohdistuu edelleen location-arvoon, eikä location,wrdl-arvoon, kuten tarkkaan hakuun mennessä. Tuon kun korjasi, niin muutos näyttää toimivan oikein, mutta loc-hakua muokatessa loc-valinta ei säily vaan muuttuu hakusana-valinnaksi. Ristiriitojakaan ei minusta tuossa ole, koska testasin ilman mitään muita scriptejä.

**Comment by MikkoLiimatainen** [comment]
Minäkin olin katsovinani, että haku ilman loc-muutosta olisi toiminut oikein. Ainakin sain samoja tuloksia kuin muutetulla loc-arvolla, joten sen perusteella ajattelisin muutoksen olevan tarpeeton.

**Comment by AnneliO** [comment]
Tämä
```
// Tarkan haun Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana sivulla /cgi-bin/koha/catalogue/search.pl
$(document).ready(function() {
  let params = (new URL(document.location)).searchParams;
  let edit = params.get("edit_search");
  if (window.location.pathname == '/cgi-bin/koha/catalogue/search.pl' && !edit) {
    var elems = $("body#catalog_advsearch select[name='idx']");
    elems.eq(0).val('ti');
    elems.eq(1).val('au');
    elems.eq(2).val('su');
  }
});
//LOPPU
```

yhdistettynä tähän

```
/// ALKU ///
/* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
$(document).ready(function() {

  if ( $('html').attr('lang') == 'fi-FI') {
    $("a#advsearch-tab-mtype-tab").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
    $("a#advsearch-tab-subloc-tab").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
    $("a#advsearch-tab-agelevel-tab").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
    $("a#advsearch-tab-bib-level-tab").text("Emokohde/Osakohde"); /* bib-level auktorisoituarvo tarkassa haussa */
    $("#searchterms .advsearch").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
    $("#searchterms .advsearch").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
    $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
  }
  else if ( $('html').attr('lang') == 'sv-SE') {
    $("a#advsearch-tab-mtype-tab").text("Materialtyp");
    $("a#advsearch-tab-subloc-tab").text("Underplats");
    $("a#advsearch-tab-agelevel-tab").text("Åldersgränser");
    $("a#advsearch-tab-bib-level-tab").text("Huvudobjekt/Delobjekt");
    $("#searchterms .advsearch").append(new Option('YKL-klassification', 'other-classification'));
    $("#searchterms .advsearch").append(new Option('UDC-klassification', 'udc-classification'));
    $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
    $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
  }
  else if ( $('html').attr('lang') == 'en') {
    $("a#advsearch-tab-mtype-tab").text("Material type");
    $("a#advsearch-tab-subloc-tab").text("Sub location"); 
    $("a#advsearch-tab-agelevel-tab").text("Age levels");
    $("a#advsearch-tab-bib-level-tab").text("Child/monographic record");
    $("#searchterms .advsearch").append(new Option('Other classification', 'other-classification'));
    $("#searchterms .advsearch").append(new Option('UDC classification', 'udc-classification'));
    $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
    $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
  }
/// LOPPU ///
```

tuottaa sellaisen tilanteen, että hakua muokatessa erikseen valittu indeksi säilyy valittuna, mutta lopuissa valikoissa ei ole pakotuksia paikoillaan.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/2f865501-ffdf-4cfb-8781-b2ca8160f96a)

**Comment by AnneliO** [comment]
Eli tuo taitaa olla se tilanne, johon Mikon rimpsulla päätyi aiemminkin? Se on varmaankin ok?

Tuosta pidemmästä rimpsusta on nyt siis riisuttu ne location -> loc -muutokset. Muuten sama kuin aiemmin.

**Comment by AnneliO** [comment]
Juttelimme tästä Koha-Suomen palaverissa pikaisesti ja sen keskustelun pohjalta ehdotan, että kaikki laittaisivat tämän kommentin mukaisesti rimpsut next-kantoihin, jolloin ne siirtyvät myös tuotantoihin versionvaihdon aikaan.

> Tämä
> 
> ```
> // Tarkan haun Sanahaku-oletustermit korvataan Nimeke, Tekijä, Asiasana sivulla /cgi-bin/koha/catalogue/search.pl
> $(document).ready(function() {
>   let params = (new URL(document.location)).searchParams;
>   let edit = params.get("edit_search");
>   if (window.location.pathname == '/cgi-bin/koha/catalogue/search.pl' && !edit) {
>     var elems = $("body#catalog_advsearch select[name='idx']");
>     elems.eq(0).val('ti');
>     elems.eq(1).val('au');
>     elems.eq(2).val('su');
>   }
> });
> //LOPPU
> ```
> 
> yhdistettynä tähän
> 
> ```
> /// ALKU ///
> /* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
> $(document).ready(function() {
> 
>   if ( $('html').attr('lang') == 'fi-FI') {
>     $("a#advsearch-tab-mtype-tab").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
>     $("a#advsearch-tab-subloc-tab").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
>     $("a#advsearch-tab-agelevel-tab").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
>     $("a#advsearch-tab-bib-level-tab").text("Emokohde/Osakohde"); /* bib-level auktorisoituarvo tarkassa haussa */
>     $("#searchterms .advsearch").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
>     $("#searchterms .advsearch").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
>   }
>   else if ( $('html').attr('lang') == 'sv-SE') {
>     $("a#advsearch-tab-mtype-tab").text("Materialtyp");
>     $("a#advsearch-tab-subloc-tab").text("Underplats");
>     $("a#advsearch-tab-agelevel-tab").text("Åldersgränser");
>     $("a#advsearch-tab-bib-level-tab").text("Huvudobjekt/Delobjekt");
>     $("#searchterms .advsearch").append(new Option('YKL-klassification', 'other-classification'));
>     $("#searchterms .advsearch").append(new Option('UDC-klassification', 'udc-classification'));
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
>   }
>   else if ( $('html').attr('lang') == 'en') {
>     $("a#advsearch-tab-mtype-tab").text("Material type");
>     $("a#advsearch-tab-subloc-tab").text("Sub location"); 
>     $("a#advsearch-tab-agelevel-tab").text("Age levels");
>     $("a#advsearch-tab-bib-level-tab").text("Child/monographic record");
>     $("#searchterms .advsearch").append(new Option('Other classification', 'other-classification'));
>     $("#searchterms .advsearch").append(new Option('UDC classification', 'udc-classification'));
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
>     $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
>   }
> /// LOPPU ///
> ```
> 
> tuottaa sellaisen tilanteen, että hakua muokatessa erikseen valittu indeksi säilyy valittuna, mutta lopuissa valikoissa ei ole pakotuksia paikoillaan.
> 
> ![kuva](https://private-user-images.githubusercontent.com/33121325/320809657-2f865501-ffdf-4cfb-8781-b2ca8160f96a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3NTAwMTIsIm5iZiI6MTcxMjc0OTcxMiwicGF0aCI6Ii8zMzEyMTMyNS8zMjA4MDk2NTctMmY4NjU1MDEtZmZkZi00Y2ZiLTg3ODEtYjJjYTgxNjBmOTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDExNDgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiYzkyZDUyYzlhMjY3ZWUzZDQzMTY2NTljOTQ4MDk1ZThiZTAxNWNlMjU1NzZkZjEwMGIzZWNjMTgyYjIyM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mf0i1uiB5zVgBPVK-WMYH5SR00Py15OEvtKCGkOtUuo)

**Comment by AnneliO** [comment]
Jos joku kimppa ei halua valikkopakotuksia, niin se ei toki ole pakollista. Indeksointityöryhmän rimpsu kannattaisi kuitenkin laittaa yllä mainitussa muodossa.

**Comment by AnneliO** [comment]
@Kati-Helle tämän tiketin voinee sulkea? :)

**Comment by Kati-Helle** [comment]
Tein tuotannossa haun
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/c7d78b17-ac8f-446d-bd73-562b1679e33e)

Hakutuloksen Muokkaa haku -linkistä 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/20da981f-f962-4fec-be7f-ee258b2941e8)

aukeaa tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2117c14f-6f3e-48b0-a2af-2b6db78142f4)

**Comment by AnneliO** [comment]
Jos olet laittanut nexteille suositusten mukaiset rimpsut, niin asia korjaantuu versionpäivityksessä, kun nexteiltä kopioidaan järjestelmäasetukset, mukaan lukien intranetuserjs:t, tuotantoon.

**Comment by Kati-Helle** [comment]
Ok, uudessa versiossa Muokkaa hakua -linkistä tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/693a9285-2a2d-4b35-b5fc-3fa8bc50257d)
