### ISSUE TITLE
Hae tietokannasta -haku ei unohda haun rajaukseen käytettyä fasettivalintaa Nykyinen paikka, kun hakutulosnäytöllä tehdään uusi Hae tietokannasta -haku

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#667]
### Mikä vikana?

Hae tietokannasta -haku muistaa tarpeettomasti aiemmassa haussa käytetyn fasettirajauksen Nykyinen paikka, kun Haun tulokset -näytöllä tehdään uusi haku.

Hae tietokannasta tiedonhaku:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ec338172-8824-490b-a89c-996840e79141)

Hakutulosnäyttöä:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d13813a2-bd4a-4877-b46b-8e72a9ce9630)

Rajaan hakua fasetilla Nykyinen paikka=Porvoon pääkirjasto. 
Hakutulosnäyttöä:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/6338f86b-e618-43ca-a944-d18c740a12c1)

Teen uuden Hae tietokannasta -haun:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/45cefd51-8a0f-4fa4-99b1-3aef008a4a27)

Haku huomioi edellisen haun fasettirajauksen Nykyinen paikka=Porvoon pääkirjasto:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/78a9b5a9-c77e-4c4f-b11b-057031cec1fd)

Nykyinen paikka -fasetissa ei ole rajauksen käytön osoittavaa valintarastia kohdalla Porvoon pääkirjasto:
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9506afb9-b795-4477-ad8d-797b88cac9c1)

Testasin vastaavan tyyliseen hakuun fasetteja Nidetyyppi, Kielet, Hyllypaikat: samaa ei tapahtunut, eli fasettirajaukset eivät tulleet automaattisesti uuteen hakuun. 

### Mitä pitäisi tapahtua

Hae tietokannasta -toiminnolla haussa käytetyn Nykyinen paikka -fasettirajauksen ei pitäisi tulla automaattisesti käyttöön uuteen Hae tietokannasta -hakuun.

### Kuinka toistaa ongelma/asia

1. Mene Hae tietokannasta -toimintoon
2. Tee haku
3. Rajoita hakutulos fasetilla Nykyinen paikka
4. Tee Haun tulokset -näytöllä (samalla näytöllä) uusi Hae tietokannasta -haku
5. Huomaa, että hakutuloksessa on huomioitu aiemmassa haussa käytetty Nykyinen paikka -fasetin valinta
6. Nykyinen paikka -fasetissa ei ole valinnan osoittavaa rastia kirjaston nimen perässä

**Comment by AnneliO** [comment]
Testailin tätä OUTIssa, Vaarassa ja Vaskissa ja kahdessa niistä sain toistettua ongelman. Vaskissa ongelma ei jostain syystä toistu.

Ajattelin eka, että tämä liittyisi jotenkin RetainCatalogSearchTerms -järjestelmäasetukseen, joka on Vaskissa eri tavalla, mutta ongelma toistui OUTIn testillä oli asetus kummin vain.

Eka haun jälkeen osoiterivillä on tieto

https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl?idx=&q=ti%3Aem%C3%A4nn%C3%B6itsij%C3%A4&sort_by=pubdate_dsc&count=85&limit=holdingbranch:OUPK

Uuden haun jälkeen osoiterivillä on tieto https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl?q=su%3Akissa&limit=branch%3AOUPK

**Comment by atarnus** [comment]
Vaikuttaa toimivan kun tarkentaa vähän search.pl:ssä sitä, mikä tekee tuon pudotusvalikon kirjastovalinnan.

```
my $branch_limit = '';
my $limit_param = $cgi->param('limit');
if ( $limit_param and $limit_param =~ /^branch:([\w-]+)/ ) {
    $branch_limit = $1;
}
```
Tuonne on lisätty vain tuo yksi ^ merkki, joka määrittelee että otsikkorivissä näkyvä limit-tieto täytyy alkaa stringillä 'branch' eikä vain sisältää sen, eli tämän kanssa jos rajaa homebranchilla, niin ei pudotusvalikon valinta muutu enää samalla.

**Comment by Kati-Helle** [comment]
Olikohan tämä jo testattavissa? Testasin Helle-testissä samalla tavalla kuin aiemmin. 
Testauksen uudessa Hae tietokannasta -haussa aiemman tiedonhaun Nykyinen paikka -fasettivalinta jää edelleen päälle. Fasettivalinta näkyy pudotusvalikossa, kuten atarnus kommentissaan kertoo. 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/f92c0f3d-1a99-420e-bf5a-8803b400f0f6)

**Comment by atarnus** [comment]
Ei ole vielä testattavana, tiedotetaan kun tulee.

**Comment by atarnus** [comment]
Muutos testeillä.

**Comment by Kati-Helle** [comment]
Helle-testausta:

Hae tietokannasta -haun hakutulosta kesä-sanahaulla
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/560d8072-4dc7-460d-8d06-556040b714b0)

Rajaan hakua fasetilla Nykyinen paikka=Porvoon pääkirjasto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/de594b68-2255-442b-96e7-1c62c8788fc9)

Fasettivalintaa ei ole pudotusvalikossa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b814a284-eec6-429e-ba9d-d60a9716ea4d)

Teen uuden sanahaun sanalla aika
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/4134476c-62c4-4f6d-8a30-fbde28e0f9ee)

Hakutuloksessa ei ole aiemmassa haussa käytettyä paikkavalintaa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/502d2be6-f634-468e-b430-e076cc3edcfb)

**Comment by piiaseme** [comment]
Myös OUTI-testillä kirjasto-fasetti jää uudesta "Hae tietokannasta"- hausta pois. OUTIssa korjaus siis toimii myös.

**Comment by Kati-Helle** [comment]
Toimii nyt myös tuotannossa (Koha-päivitys 16.1.2024).
