### ISSUE TITLE
Tekstiviesteissä ei näy vieraat kirjaimet oikein

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#668]
### Mikä vikana?

Vaskin tekstari-noutoilmoituksista huomattiin, että vieraat kirjaimet (esim. ž, œ) on korvattu saapuneessa tekstiviestissä ?-merkillä. Erikoismerkit kuten @ ja & toimii kyllä, samoin heittomerkilliset kirjaimet kuten é.

Ongelma on suhteellisen marginaalinen, joten ei käsitystä missä vaiheessa vieraat kirjaimet ovat alkaneet näkyä näin. Joskus syksyllä 2021 osa vieraista kirjaimista aiheutti viestin lähettämisen epäonnistumisen ja asia fiksattiin kuntoon, joten todennäköisesti silloin on tullut testattua millaisina viestit puhelimeen asti tulee. :thin

**Comment by lmstrand** [comment]
Tekstiviestidriverissa on bugi, jonka takia viestit joissa on erikoismerkkejä, jotka eivät kuulu gsm 0388-enkoodaukseen silti käyvät läpi tuon gsm0388-enkoodauksen ja merkit korjaantuvat kysymysmerkillä.  Noita 0388-enkoodaukseen sopimattomia merkkejä varten tekstiviestin pituus muutttuu 70 merkkiin ja niin on tähänkin asti ollut. Korjausta testattu Vaski-testillä ja tekstiviestit näkyvät nyt oikein puhelimessa (ainakin testaamani saamenkielisen teoksen kanssa).

**Comment by lmstrand** [comment]
Korjattu pluginin 22.xx-haaraan.

**Comment by ajrajala** [comment]
Hyvä homma. Tsekkaan ensi viikon päivityksen jälkeen tuotannossa, miltä näyttää.

**Comment by AnneliO** [comment]
Katottiin Lassen kanssa tätä päivitystä, emmekä uskalla laittaa sitä tuotantoon ilman Laria, jos jokin menee vielä pahemmin vikaan. Eli laitetaan tuotantoon, kunhan Lari palaa lomilta vkolla 31. :)

**Comment by ajrajala** [comment]
Loin saapumisilmoituksen testitietueelle, jonka nimekkeessä œ ja ž -merkit. Tekstarissa näkyivät edelleen ?-merkkeinä.

**Comment by lmstrand** [comment]
Olin unohtanut buildata tuon tekstiviestidriverin uusiksi muutoksen jälkeen. Teen sen tänään illalla. Katsotaan huomenna uusiksi.

**Comment by ajrajala** [comment]
Nyt näkyvät vieraskieliset kirjaimet oikein, suljen tiketin.
