### ISSUE TITLE
Tuotanto/testibuildeja varten tarvitaan tapa käsitellä tietokantaan tarvittavia muutoksia/atomicupdateja

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#669]
### Tukipyyntö

Tällä hetkellä build-release.sh -skripti ajaa updatedatabase.pl:n ainoastaan siihen kimppaan, missä skripti ajetaan. Tämäkin tapahtuu vasta toisella buildikierroksella, jolloin tietokantapäivityksen vaativasta branchista on päätynyt tietokantamuutoksen sisältävä atomicupdate-tiedosto oikeaan sijaintiinsa deploy-vaiheen jälkeen eli /home/koha/Koha/installer/data/mysql/atomicupdate/.
Updatedatabase.pl etsii atomicupdate-tiedostoja tästä sijainnista. Olisiko tähän ratkaisu tehdä oma versio updatedatabasesta, joka huomioi atomicupdate-tiedostojen sijainnin shm:llä?

Tarvitaan keino ajaa updatedatabase.pl jokaisessa kimpassa erikseen buildin päätteeksi. @janPasi ehdotti ratkaisuksi työjonoa.

**Comment by CodoDerDritte** [comment]
Tässä pitäisi myös saada skeemabuildi tapahtumaan vasta updatedatabasen jälkeen, ongelma on hieman mutkikas ratkaistava.

**Comment by CodoDerDritte** [comment]
Tuo "toisen buildikierroksen ongelma" on korjattu C4/Installer.pm:ssä siten että jos BUILD_DIR ympäristömuuttuja on asetettu, käytetään BUILD_DIR:in asettamassa hakemistossa olevia atomicupdateja. build_release.sh asettaa BUILD_DIR muuttujan.

**Comment by CodoDerDritte** [comment]
Keino ajaa updatedatabase.pl jokaisessa kimpassa buildin jälkeen on nyt olemassa. Sitä varten on finalize-build.sh -skripti, joka tekee nuo tarvittavata tietokantapäivitykset ja sen jälkeen käynnistelee plackit uudelleen varoen aiheuttamasta ylikuormaa OCFS2:lle. Sen voi ajaa nodelta kojumpilla.

**Comment by CodoDerDritte** [comment]
Toiminnallisuus on nyt osa korefreshiä. Korefreshissä on uusi vipu -u tietokannan päivitystä varten.
