### ISSUE TITLE
Varauksen noutopaikan muuttaminen asiakkaan tiedoista antaa virheellisen noutopaikkalistan

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#673]
### Mikä vikana?

Kun varauksen noutopaikkaa yrittää muuttaa asiakkaan tietojen kautta, Kohan noutopaikka-pudotusvalikkon antaa virheellisen listan noutopaikoista. Vaskin tuotantoympäristössä listalle tulee 20 aakkosissa viimeistä noutopaikkaa ja kun listaa selaa alaspäin, haetaan listaan samat 20 noutopaikkaa, kunnes lista on noutopaikkojen määrän 60 mittainen. Testiympäristössä noutopaikkoja on 61 ja noutopaikkalistaan tulee listan viimeinen kirjasto neljä kertaa. Tästä voi päätellä, että noutopaikkalista sivutetaan 20 noutopaikan mittaiseksi ja lista hakee sivutuksen viimeisen sivun uudelleen ja uudelleen, kunnes sivujen määrä on saavutettu.
![Virheellinen kirjastolista testiympäristö](https://github.com/KohaSuomi/Koha/assets/98884651/c12a91cb-2ed6-4c31-bdee-b18bfe6b7af2)

Viimeistä sivua lukuunottamatta näkyy listalla myös virheviesti.
![Virheellinen kirjastolista ja virheviesti](https://github.com/KohaSuomi/Koha/assets/98884651/31a85158-236e-4652-b913-9f1d7bf3cd8a)

Noutopaikan voi hakea kirjoittamalla hakukenttään osan noutopaikan nimestä.

### Mitä pitäisi tapahtua

Pudotusvalikon pitäisi hakea ensin aakkosten 20 ensimmäistä noutopaikkaa ja sitten seuraavat 20 jne.

### Jotain muuta?

Tiketti Bugzillassa: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34068

**Comment by pknuuti** [comment]
Vaarassa noutopaikkavalikko antaa kaikki noutopaikat, valikko avautuu hissiin. Valikossa on 40 noutopaikkaa.
![2023kuvat 091](https://github.com/KohaSuomi/Koha/assets/73887264/85687501-a7b5-454c-8a4e-5f2c0a2b49a6)

**Comment by pirliis** [comment]
OUTIssa noutopaikkavalikko asiakkaan varauksissa näyttää myös oikealta.

**Comment by MikkoLiimatainen** [comment]
Vaikuttaakohan tuohon sitten jokin asetus, jos se on nyt vain meillä ongelmana?

**Comment by emta001** [comment]
Vilkaisin tuota ja eihän tuon pitäisi toimia tuolla tavalla sivuttamalla kuten se Vaskissa nyt toimii. Esim. Vaarassa tehdään vain yksi API-kutsu ilman _page parametriä. Mutta enpä nyt ihan äkkiseltään huomaa, että tuohon vaikuttaisi mikään asetuskaan.

**Comment by MikkoLiimatainen** [comment]
No hyvä että syyllinen löytyi. Mitähän muita vaikutuksia tuolla mahdollisesti on, että uskaltaisiko tuon muuttaa myös tuotantoon? Ilmeisesti se muualla toimii ihan ongelmitta, joten sinällään varmasti uskaltaa muuttaa, mutta ihmetyttää kyllä tuo kytkös tämän asetuksen ja alasvetovalikon kanssa.

**Comment by emta001** [comment]
Ilmeisesti aina kun tehdään API-kutsu, niin tuo asetus määrittää sen montako tulosta esitetään kerralla. Ja nuo noutopaikathan tulee APIn kautta. Pitänee kaivella yhteisöä taas, löytyisikö sieltä tuohon tiketti tai tehdä semmoinen. Ei ihan loppuun suunniteltu juttu :D
