### ISSUE TITLE
Uusinta-toiminto antaa ohittaa varauksen ja uusintakertojen täyttymisen

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#674]
### Mikä vikana?

Lainaus ja palautus -sivulla (/cgi-bin/koha/circ/circulation-home.pl) Uusinta-toiminto antaa:
1. Uusia lainan, vaikka teokseen kohdistuu varaus. Tulee ilmoitus:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/2322c54e-696c-488d-9286-7bab16fac099)
Kun valitsee "Ohita rajoitus ja uusi laina", ohjelma uusii lainan.

2. Jos lainaa on uusittu maksimimäärä, ohjelma kyllä ilmoittaa siitä, mutta tekee uusinnan, kun valitsee "Ohita rajoitus ja uusi laina".
![image](https://github.com/KohaSuomi/Koha/assets/98814860/522c29bf-4853-4be1-a849-63a5459e80e9)
Esimerkissä virkailijalla ei ole oikeutta "override_renewals" (ohittaa uusintojen esto).

### Mitä pitäisi tapahtua

Jos toimintoa halutaan käyttää:

Kohdassa 1:
- Toiminnon ei pitäisi antaa mahdollisuutta uusia lainaa, kun teokseen kohdistuu varaus. 

Kohdassa 2:
- Toiminnon ei pitäisi antaa uusia lainaa, kun uusintojen maksimimäärä on täyttynyt, jos virkailijalla ei ole siihen oikeutta.

Yksi vaihtoehto olisi piilottaa Uusinta-toiminto Lainaus ja palautus -sivulta. Kuinkahan paljon tätä toimintoa kimpoissa lie käytetään?

**Comment by Kati-Helle** [comment]
Vastaava toiminto lienee tämä yläpalkin Uusinta-toiminto
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/7eb68a24-58ef-480d-a15a-d3f82d509747)

Ainakin Hellessä ko. toiminto on piilotettuna IntranetUserJS-rimpsulla:
/* Piilota Uusi/Renew-vaihtoehto yläpalkista. Uusinnan pystyy tekemään tällä ilman kirjastokorttia, pelkällä nidenumerolla.  */
$(document).ready(function () {
  $( "li[aria-controls='renew_search']" ).hide();
});

Testasin Helle-testissä poistamalla rimpsun: yläpalkin Uusinta-toiminnolla onnistuu varatun niteen uusinta.
(Hellessä on käytössä oikeus "override_renewals". Oikeudesta huolimatta varatun niteen uusinta asiakkaan lainatiedoissa ei onnistu. Sen sijaan lainan uusinta onnistuu, vaikka lainan kaikki uusintakerrat on käytetty.)

**Comment by pirliis** [comment]
OUTIssa on myös piilotettu yläpalkista. Taisi ollakin suosituksissa tehdä piilotus.

**Comment by Kati-Helle** [comment]
> OUTIssa on myös piilotettu yläpalkista. Taisi ollakin suosituksissa tehdä piilotus.

Ainakin OUTIssa ja Hellessä siis samoin.
Kannatan Pirkko-Liisa ehdottamaasi Uusinta-toiminnon piilotusta Lainaus ja palautus -sivulla. Saisikohan tuohon tarvittaessa kimppakohtaisesti käytettävän toteutuksen?

**Comment by pknuuti** [comment]
Kannatan myös tuon Uusinta-toiminnon piilotusta. Ei aiheuta muuta kuin ongelmia :)

**Comment by lmstrand** [comment]
Lisäämällä tämän rimpsun intranetUserCSS:ään napin saa piiloon:
```
/* Piilota uusinta-nappi lainaus- ja palautus -näkymässä */
body#circ_circulation-home a[href*="/cgi-bin/koha/circ/renew.pl"] {
  display: none;
}
```

**Comment by pknuuti** [comment]
Kiitos, hyvin piilottui.

**Comment by AnneliO** [comment]
Uusinta-välilehden piilotusta varten on ollut aiemmassa versiossa tällainen js-rimpsu, mutta ilmeisesti se on jäänyt minulla huomioimatta, kun kävin versionvaihdon aikaan rimpsut läpi.

https://koha-suomi.fi/dokumentaatio/intranetuserjs/#piilota-uusinta-v%C3%A4lilehti-yl%C3%A4osan-hakukent%C3%A4st%C3%A4

Mutta

**Comment by AnneliO** [comment]
Jaa, tuo taitaakin olla kaksi eri asiaa. JS-rimpsu piilottaa Katin kuvassa näkyvän tiedon ja Larin rimpsu taas Lainaus ja palautus -sivun Uusinta-napin.

**Comment by ReettaSiili** [comment]
Lisäsin css:n myös Siilissä, hyvin piiloutui turha uusintamahdollisuus.

**Comment by velimarj** [comment]
Myös OUTIssa lisätty tuo CSS, hyvin toimii.
