### ISSUE TITLE
Lappi: Omatoimi Kemin kirjasto

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#675]
### Tukipyyntö

Hei, lähetin support-postiin palvelimelle tallennettavan SIP2-tunnuksen tiedot Kemin omatoimikoneesta.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle.

**Comment by LeenaKinnunen** [comment]
Kiitos! Suljen tiketin.
