### ISSUE TITLE
SQL-raporttien jakaminen Koha-yhteisön Mana-tietokantaan

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#677]
### Tukipyyntö

Koha-Suomen palaveri 2.3.2023: 

SQL-raporttien jakaminen Koha-yhteisön Mana-tietokantaan
[Bywaterin esittelyvideo](https://bywatersolutions.com/education/monday-minutes-sharing-reports).

    Jaa sisältö Koha-yhteisölle Mana-tietämyskannan kautta Mana-tietämyskanta on maailmanlaajuinen tietämyskanta kirjastokeskeiselle tiedolle. Se on suunniteltu alun perin Koha-järjestelmälle (the Open Source ILS), mutta sitä voidaan hyödyntää myös muissa järjestelmissä. Mana keskittää tietoa Koha asennusten välillä ja helpottaa uusien kausijulkaisutilausten, toimittajien, raporttien jne. luontia. Voit etsiä, jakaa, tuoda ja kommentoida Manassa olevaa sisältöä. Mana-tietämyskannassa jaettu tieto on jaettu lisenssillä: CC-0 lisenssi. Lue lisää Mana-tietämyskannasta virallinen [Mana-tietämyskannan dokumentaatio](https://wiki.koha-community.org/wiki/Mana_central_database).

**Comment by emta001** [comment]
ByWatersilta löytyi myös sanalliset ohjeet siihen, kuinka Mana otetaan käyttöön:

[Setting up Mana](https://bywatersolutions.com/education/setting-up-mana)
[Using Mana in the Reports Module](https://bywatersolutions.com/education/using-mana-to-import-reports-into-koha)

Kehittäjän tehtävät:
1. Kohan koha-conf.xml-tiedostoon on lisättävä seuraava asetus:
 ```
<!-- URL of the mana KB server -->
 <!-- alternative value http://mana-test.koha-community.org to query the test server -->
 <mana_config>https://mana-kb.koha-community.org</mana_config>
```

Käyttöönotto lyhyesti:
1. Laita päälle asetus "Mana".
2. Mene sivulle "Muita toimintoja->Ylläpito->Muut parametrit->Jaa sisältö Mana-tietämyskannassa".
3. Syötä kimpan tiedot kohtaan "Konfiguroi Mana-tietämyskanta" ja paina "Lähetä Mana-tietämyskannalle".
4. Valtuutusavain luodaan ja tallennetaan kantaan automaattisesti, mutta se on tallennettava käsin myös asetukseen "ManaToken". 
5. Syöttämääsi sähköpostiin lähetetään ohjeet kuinka Manan käyttäjätilin konfigurointi viedään loppuun.

Raporttien hakeminen Manasta:
1. Mene tallennettuihin raportteihin.
2. Paina painiketta "Uusi raportti" ja valitse "Uusi SQL Manasta".
3. Syötä hakusana esim. "holds".
4. Etsi haluamasi raportti ja paina sitten "Tuo".
5. Raportista aukeaa esikatselu näkymä, josta pääsee myös muokkaamaan tai ajamaan raportin.
7. Kun palaat tallennettujen raporttien näkymään, tuomasi raportin tulisi näkyä viimeisimpänä luotuna raporttina.

Raporttien vieminen Manaan:
1. Tarkista, että jakamallasi raportilla on otsikko ja kuvaus (molempien tulee olla vähintään 20 merkkiä pitkä).
2. Paina "Käynnistä" painikkeen vieressä olevaa ylöspäin osoittavaa nuolta ja valitse "Jaa".
3. Tarkista raportin sisältö ja paina sitten "Jaa".

**Comment by emta001** [comment]
Päivittelen jossain kohti kimpoille tuon koha-conf.xml asetuksen, tämän jälkeen Mana on valmis käyttöönotettavaksi kimpoissa. 

- [ ] Siili
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Vaara
- [ ] Lappi
- [ ] OUTI
- [ ] Vaski

**Comment by emta001** [comment]
Laitoin asetuksen eilen kaikille kimpoille kuntoon. Manan voi nyt ottaa käyttöön halutessaan.

**Comment by pknuuti** [comment]
Testasin tätä Vaarassa. Käyttöönotto-ohjeiden mukaan kirjauduin ja sain sähköpostiviestin vahvistukseksi. Raporttien hakeminen Manasta onnistuu ohjeen mukaan ja vein sinne myös yhden raportin (Failed or pending messages (sms)). Tässä tuli ongelma, kun en hoksannut lisätä kuvausta, mutta Anneli hoksautti ja päätti korjata ohjetta.
Nyt huomattiin, että kun Vaarassa tehdään uusi kausijulkaisutilaus, siihen tulee huomautus Manasta puuttuvasta julkaisukaavasta ja sen voisi sinne tallentaa. Tämä varmaan hämää käyttäjiä, joilla ei ole tietoa mikä Mana on.

**Comment by AnneliO** [comment]
Minkä näköinen se kausijulkaisutilauksen huomautus on?

**Comment by pknuuti** [comment]
![2023kuvat 277](https://github.com/KohaSuomi/Koha/assets/73887264/1806e656-2f0a-46cb-bde3-c349acbd0d48)

**Comment by AnneliO** [comment]
Meniskö tuo ihan vain tiedottamisella vai pitäisikö tuo yrittää piilottaa?

**Comment by pknuuti** [comment]
Eiköhän tiedottaminen riitä.

**Comment by emta001** [comment]
Tämä vaikuttaisi sille, että tiketin voi sulkea. Avataan taas, jos tulee jotain ongelmia.
