### ISSUE TITLE
Yhdistetyt tietueet löytyvät tiedonhaulla

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#678]
### Mikä vikana?

OUTIssa on yhdistetty kaksi tietuetta 29.6.2023:
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2310917&searchid=scs_1688114670102
ja
https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=548775&searchid=scs_1688114670102

30.6.2023 molemmat tietueet löytyvät vielä tiedonhaulla, mutta tietue 2310917 ilmoittaa: "Tietuetta 2310917 ei ole tietokannassa."

### Mitä pitäisi tapahtua

Tietuetta https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2310917&searchid=scs_1688114670102 ei pitäisi löytyä enää tiedonhaulla yhdistämisen jälkeen.

**Comment by emta001** [comment]
Siellä on nyt hyvin itsepintainen indeksi, joka ei halua poistua edes suoraan deletoimalla.

**Comment by emta001** [comment]
Tehdään OUTIin maanantaiyönä uudelleenindeksointi. Katsotaan josko sillä saataisiin tämä oikaistua.

**Comment by emta001** [comment]
Uudelleenindeksointi tehty ja tietue ei näyttäisi enää löytyvän tiedonhaulla.

**Comment by pirliis** [comment]
Hyvä homma, suljen tiketin.

**Comment by emta001** [comment]
> Taas tuli OUTIssa tällainen vastaan, laitan nyt tähän samaan tikettiin kun on täysin samanlainen tilanne.
> 
> Haamu, joka pitäisi poistaa: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2246680&searchid=scs_1704366373840 Oikea: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2335004&searchid=scs_1704366373840
> 
> Onnistuuko tämä jossain kohtaa?

Haamu poistettu, haku näyttää nyt oikealta.

**Comment by velimarj** [comment]
Kiitokset, suljenpa tämän siis taas.

**Comment by piiaseme** [comment]
Hei, avaan tiketin, sillä OUTIssa on taas samanlainen tapaus kuin nuo tuolla edellä.

Tämän haamutietueen saa poistaa: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2052517&searchid=scs_1706608066408

**Comment by johannaraisa** [comment]
Olen tässä tarkkaillut noita ja tuo on ihan satunnaista, että poisto indeksistä ei vain tapahdu. Tein tätä varten skriptin millä katsotaan eka action_logsista poistetut ja sitten tarkastetaan onko se vielä indeksissä. OUTIlla ja Lumpeella on eilen jäänyt kaksi poistumatta, missään ei ole mitään tietoa että miksi ei ole muka onnistunut. 

Tuolla samalla skriptillä nämä saa poistettua indeksistä, joten ajattelin laittaa kaikille ajelemaan tuon päivittäin ja poistamaan ne roikkumaan jääneet. Toivotaan, että tämä ongelma korjaantuu uudessa versiossa sillä siinä päivitetään myös Elasticsearch uudempaan versioon.

**Comment by ajrajala** [comment]
Avaan tämän saman tiketin, koska Vaskissa yhdistettiin viime viikolla kaksi tietuetta ja molemmat tietueet löytyvät edelleen tiedonhaulla https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl?q=apukokki+late. Noista kahdesta siis [ylempää](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=3420445) ei ole oikeasti enää olemassa. Onko tuo Johannan mainitsema päivittäinen ajo kuitenkin meillä päällä?

**Comment by johannaraisa** [comment]
> Avaan tämän saman tiketin, koska Vaskissa yhdistettiin viime viikolla kaksi tietuetta ja molemmat tietueet löytyvät edelleen tiedonhaulla https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/search.pl?q=apukokki+late. Noista kahdesta siis [ylempää](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=3420445) ei ole oikeasti enää olemassa. Onko tuo Johannan mainitsema päivittäinen ajo kuitenkin meillä päällä?

Kyllä sen pitäisi kahdeksalta illalla noita käydä läpi. Käyn katsomassa lokista miltä siellä näyttää.

**Comment by johannaraisa** [comment]
Jostain syystä indeksin nimi oli vaski-test, joten näitä nyt yritettiin etsiä väärästä indeksistä. Korjasin tuon ja nyt poistelin roikkumaan jääneet vuoden alusta lähtien.
