### ISSUE TITLE
RLIN arvot tietueilla ja tekijähaku

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#682]
### Tukipyyntö

Joissakin tietueissa on 100-kentän 9-osakentässä RLIN-numero (Koha-Auth-Number) 
Esimerkiksi tietueessa biblionumber=1743001 on RLIN-tieto kentässä ja näkyy hakutuloksessa tekijätiedon linkissä muodossa an:128065, ei au: kuten normaalisti. 

![image](https://github.com/KohaSuomi/Koha/assets/99165331/a7df6e3b-b2b9-4ba0-b166-fdee710a078c)

Ilmeisesti RLIN-numero on syntynyt jossain vaiheessa, jos on ollut päällä automaattinen auktorisointi, ja se on luonut joka kerta tekijätietoa tallennettaessa uuden yksilöllisen tunnisteen. Tästä seuraa, että hakutuloksen tekijätieto ei löydä muita tietueita ko. tekijältä. 

Voiko RLIN-tiedot poistaa tietueilta ajona?

**Comment by janPasi** [comment]
Periaatteessa siis haku tehdään auktoriteettirekisterin kautta jos kyseessä on tekijänimen auktorisoitu muoto. Tämä on ihan järkevä toimintatapa. Ongelma on lähinnä siinä että meidän auktoriteettirekisterit on ihan roskaa, kun sinne on auktorisoitu suunnilleen kaikki mikä tulee vastaan. Tuo haku ei siksi toimi oikein. Näitä syntyy varmaan kuvailtaessa koko ajan lisää jos se automaattinen auktorisointi on päällä. Tämän ongelman ratkaisu vaatii nyt varmaan tuon auktorisoinnin miettimistä uusiksi.

**Comment by LeenaKinnunen** [comment]
Meillä ei ole auktorisointi nyt päällä, jos tarkoitat asetusta AutoCreateAuthorities.

**Comment by janPasi** [comment]
> Meillä ei ole auktorisointi nyt päällä, jos tarkoitat asetusta AutoCreateAuthorities.

Hyvä juttu, mitenköhän lienee asian laita muissa kimpoissa? Tämä ongelma nimittäin näyttää kyllä koskevan muitakin kuin vain Lappia.

**Comment by janPasi** [comment]
Näyttäisi olevan päällä ainoastaan Kirkeksessä tällä hetkellä ja sen voinee muuttaa.

**Comment by janPasi** [comment]
Pasilla lienee valmiihkoja työkaluja näiden fiksaamiseen, joten nimeän tiketin hänelle.

**Comment by pknuuti** [comment]
Nythän TäTin/Melindan kautta tulee Asterin auktorisoituja nimimuotoja, jotka tulevat kenttää 100/0. Kunkin kimpan omat auktorisoinnit ovat mielestäni tarpeettomia, kun on saatu käyttöön valtakunnallinen nimimuotojen auktoriteetti. Mitä tapahtuu kimpoissa oleville itse tehdyille auktorisoinneille, se liittyy varmaan isompaan revohkaan RDA-konversioineen ym. mahdollisen yhteisen rekisterin muodossa.
Vaarassakin on edelleen vanhoja auktoriointeja juuri tuolla 9-osakentässä ja ne joutaisivat kyllä pois. Uusia ei tuohon kenttään enää tule.

**Comment by janPasi** [comment]
Ottaisitko Leena sinä tämän käsittelyn hommaksesi siellä pääkäyttäjäryhmässä?

**Comment by LeenaKinnunen** [comment]
Ok, otan esille ensi viikolla.

**Comment by janPasi** [comment]
> Ok, otan esille ensi viikolla.

Hienoa, kiitos! :)

**Comment by LeenaKinnunen** [comment]
Tämä saatiin korjattua vaihtamalla järjestelmäasetukseen UseAuthoritiesForTracings valinta Älä käytä. Muutos korjaa sekä tekijä- että asiasanojen linkityksen. 

Lappi siis korjattu.

**Comment by paxed** [comment]
Poistetaanko nuo 100$9 arvot kuitenkin, vaikka tuo järjestelmäasetus korjaakin hakutuloksen?

**Comment by LeenaKinnunen** [comment]
Emme näe tarvetta poistaa noita arvoja. Suljen tiketin.
