### ISSUE TITLE
Vaara: Muutama PowerBI-raportti kaatuu proxy erroriin

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#683]
### Mikä vikana?

Olen viimeksi 1.6. ajanut Vaarassa raportit 701, 743, 747 ja ne ovat toimeet silloin ihan normaalisti. Nyt nuo samaiset raportit jauhavat aikansa ja antavat proxy errorin. Kaikkia tilastoja olen yrittänyt ajaa kesäkuun osalta eli 1.6.-30.6.2023 aikaväliltä. Pitäisi saada päivitettyä mm. poistotilastoja, jota tarvitaan seurantaa varten.

![2023kuvat 095](https://github.com/KohaSuomi/Koha/assets/73887264/855b859d-bf5e-40f7-9c8e-4c0c8e33dbdb)

### Mitä pitäisi tapahtua

Raporteilla pitäisi saada tulos, jonka voi viedä PowerBI-raportointiin.

**Comment by lmstrand** [comment]
Näitä jää junnaaman tietokantaan ikinä valmistumatta. Tänään aamulla oli tällaisesta pitkään kestävästä sql-kyselystä varoitus vaaran tuotantokontissa. Tapoin kyselyn.

**Comment by lmstrand** [comment]
Ongelmana raporteissa on biblio_data_elements-taulun liittäminen joinilla käyttäen biblioitemnumberia. Tauluun tehtiin muutos, jonka jälkeen biblionumberista tuli uniikki avain. biblioitenumber on jätetty tauluun kaikena varalta, joten raportit eivät tiedon puuttumisesta herjanneet. En tiedä tarkalleen miksei raportti valmistu vanhalla joinilla, mutta joinin luonti bde-tauluun biblionumberilla korjasi raportin 747.

**Comment by pknuuti** [comment]
Kiitos tuhannesti, nyt nämä toimii. Suljen tiketin.
