### ISSUE TITLE
Asiakashaun tuloslistauksessa on toimintopainike nimeltään Edit myös silloin, kun Kohan käyttöliittymäkielenä on suomi tai ruotsi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#684]
### Mikä vikana?

Asiakashaun tuloslistauksessa on asiakastiedon muokkaukseen vievä painike englanniksi 'Edit' kaikilla Kohan käyttöliittymäkielillä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/9c607ac9-f44b-445f-ae79-0c7a5fe7a530)

**Comment by AnneliO** [comment]
En nyt ole ihan varma, mistä tuon käännöksen pitäisi tulla. Tuo sana löytyy kyllä staff-prog-tiedostosta, mutta se osoittaa aika moneen kohtaan. Mikään niistä ei suoraan ole juuri tuolle sivulle. Mutta se saattaa kyllä tulla jonkin dataTables-määrityksenkin mukaan.

**Comment by atarnus** [comment]
Nextillä näyttäisi olevan käännettynä.

**Comment by Kati-Helle** [comment]
Joo, nyt painikkeen nimenä Muokkaa
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1dcc32f6-9396-43d3-9ae7-2d726b07266a)

**Comment by atarnus** [comment]
Tämä näyttäisi tulevan tuolta patron-search.inc:stä, myös https://github.com/KohaSuomi/Koha/issues/1014 oli samaa asiakashakua ja käännökset on puuttuneet, mutta ovat nyt nextillä mukana.
