### ISSUE TITLE
Asiakkaalla on tekstiviesti-ruksi ja matkapuhelinnumero tiedoissa, mutta asiakasviestit lähtevät tulosteena

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#686]
### Mikä vikana?

OUTIssa asiakkaalla https://outi.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=66831
on kolme varauksen noutoilmoitusta lähtenyt liikkeelle tänään tulosteena, kun hänelle olisi pitänyt lähteä tänä aamuna tekstiviestit varauksista.

Tämän aamun lokilta varauksista luki tämmöistä:
[{'mtt' => ['email'],'_name' => 'Item_Due'},{'_name' => 'Hold_Filled','mtt' => ['sms']},{'da' => 3,'_name' => 'Advance_Notice','mtt' => ['email']}] 

Asiakkaan tiedoissa oli puhelinnumerot matkapuhelinkentässä sekä sms-alert-kentässä. Ruksi oli paikallaan kohdassa Varauksen noutoilmoitus tekstiviestinä.

Virkailija kävi tarkistamassa asiakkaan tiedot ja "muokkasi" asiakastietoja sen verran, että näpäytti ensin noutoilmoituksen rastin pois ruudusta ja sitten heti takaisin.

Aiempaa noutoilmoitus-historiaa ei ole tiedossa eikä sitä onko asiakas käynyt Finnassa tietojaan muuttamassa. Lokilla näkyy 26.6. tehdyn yhteystietomuutoksia, mutta ei matkapuhelinmuutoksia, jos osasin lokia lukea oikein.

### Mitä pitäisi tapahtua

Asiakkaalle olisi pitänyt lähteä kolme varauksen noutoilmoitusta tekstiviestinä.

### Selain

```markdown

```

### Jotain muuta?
https://github.com/KohaSuomi/Koha/issues/607

**Comment by lmstrand** [comment]
Muutoslokin mukaan asiakas on itse Finnasta käynyt laittamassa viestiasetuksiinsa sms-viestit lähtemään varauksista ('Hold_Filled','mtt'  => ['sms']})

06.07.2023 09:53 | Finna API (291446) | Patrons | MOD MTT | xxxxx | [{'mtt' =>  ['email'],'_name' => 'Item_Due'},{'_name' => 'Hold_Filled','mtt'  => ['sms']},{'da' => 3,'_name' => 'Advance_Notice','mtt' =>  ['email']}]
-- | -- | -- | -- | -- | --

Viestit lähtevät 9:30 eteenpäin viidentoista minuutin välein, joten tuo täppä ei varmaan ole vielä silloin varmaan ollut asiakkaalla päällä (muutos vasta 9:53) ja Koha on muodostanut viesteistä printtiversiot.

**Comment by piiaseme** [comment]
Eipä tuo vaihtoehto edes käynyt mielessä. Kuulostaa oikealta ratkaisulta, hyvä että oli inhimillinen tekijä eikä järjestelmäbugi :-)
Kiitos selvityksestä!

**Comment by piiaseme** [comment]
Suljen tiketin.
