### ISSUE TITLE
Siilinjärvi: jäänyt tekemättä kirjastokorttinumeron ja käyttäjätunnuksen yhtenäistäminen

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#692]
### Tukipyyntö

Tämä on ilmeisesti "unohtunut", olisi varmaan hyvä tehdä ainakin henkilöasiakkaille.

Voisiko kehittäjä ottaa yhteyttä ennen ajoa, niin selvitellään onko joukossa asiakkaita, jotka pitäisi ottaa erityistarkasteluun. Luulen, että ainakin henkilökunnalla saattaa olla omia virityksiä korttinumeroissa ja käyttäjätunnuksissa.

**Comment by lmstrand** [comment]
Tein siiliin raportin 83, joka listaa käyttäjät, joilla userid ja korttinumero eivät ole samat.

**Comment by lmstrand** [comment]
Tämä ajo pitäisi tehdä kaikille, myös virkailijoille. Ajon yhteydessä laitetaan voimaan triggeri, joka siirtää korttinumeron aina asiakastietojen tallennuksen yhteydessä userid:ksi. Jos virkailijoilla säilyisi eri userid, asiakastietojen muutoksen yhteydessä userid muuttuisi korttinumeroksi ja vanhalla (tekstimuotoisella tms.) userid:lla kirjautuminen ei enää onnistuisi.

Tästä pitäisi tiedottaa asiakkaita ja virkailijoita ennen kuin ajo tehdään?

**Comment by ReettaSiili** [comment]
Raportilla 83 olevat on nyt käyty läpi ja tiedotettu tai korjattu tai arvioitu etteivät aiheuta toimia. Ajon voi Siilin puolesta tehdä. Ilmoitatteko vielä kun on tuloillaan?

**Comment by ReettaSiili** [comment]
Korttinumero kopioituu oikein käyttäjätunnus-kenttään.
Korjatuista käyttäjätunnuksista ei ole ainakaan vielä aiheutunut mitään sotkua.
Suljen tiketin. Kiitos!
