### ISSUE TITLE
Nidehaun tulosten järjestäminen julkaisuvuoden mukaan ei toimi oikein

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#693]
### Mikä vikana?

Kun nidehaun tuloksissa klikkaa saraketta Julkaisuvuosi ( Publication year), niteet hakutuloksessa järjestetään kyllä uudelleen mutta ne eivät mene julkaisuvuoden mukaiseen järjestykseen. Jos saraketta klikkaa uudelleen järjestääkseen niteet laskevaan järjestykseen, ei tapahdu enää mitään.

### Kuinka toistaa ongelma/asia

1. Mene nidehakuun ja tee jokin haku
2. Järjestä hakutulossivulla tulos Publication year -sarakkeen mukaan
3. Huomaa, että järjestys muuttuu mutta ei ole oikein
4. Järjestä tulos uudelleen saman sarakkeen mukaan
5. Huomaa, että mitään ei enää tapahdu

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/3cf4fb72-cd19-4236-95db-f6557f69956b)

**Comment by AnneliO** [comment]
Testailin vielä lisää ja tein sandboxiin samanlaisen mäppäyksen kuin meillä ja siirsin vuosiluvun 264c-kenttään. Vuosiluku tulee nidehaussa näkyville ja järjestäminenkin onnistuu.

Yritin myös kaivella bugzillaa, mutta en ainakaan löytänyt mitään tähän liityvää sieltä.

**Comment by lmstrand** [comment]
Helle-testillä järjestäminen näyttäisi toimivan molempiin suuntiin ihan oikein.

**Comment by AnneliO** [comment]
> Helle-testillä järjestäminen näyttäisi toimivan molempiin suuntiin ihan oikein.

Mielenkiintoista, minulla ei toimi siellä julkaisuvuodella järjestäminen oikein.

**Comment by lmstrand** [comment]
Tuolleen toimi siis Helle-testillä minulla, kuten Päivi kuvaili.

**Comment by AnneliO** [comment]
Minullakin kyllä tulee vuodettomat alkuun, mutta kun selaan listaa alaspäin, on vuodettomien seassa random vuosilukuja.

**Comment by pknuuti** [comment]
Mä en saa tuollaista tilannetta, mitä Anneli kuvaat. Millaisen haun teit tai onko antaa nimekkeitä, jotka järjestyvät väärin?

**Comment by AnneliO** [comment]
> Mä en saa tuollaista tilannetta, mitä Anneli kuvaat. Millaisen haun teit tai onko antaa nimekkeitä, jotka järjestyvät väärin? Vai tarkoitatko Hellen testiä, et Vaaran?

Testasin aiemmin siis Hellen testillä, mutta tein vastaavan haun nyt myös Vaaran testillä. Eli hain kaikki niteet, joissa on kotikirjastona Enon kirjasto ja järjestin ne julkaisuvuoden mukaan. Minulla ne järjestyy näin:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/de696850-ec9c-49e0-8d80-4a183bec96ce)

**Comment by pknuuti** [comment]
Kiitos Anneli. Tarkistin vastaavan haun tuloksissa muutaman nimekkeen tietoja ja kyllähän siellä oli vuosiluku monessakin ns. tyhjässä tietueessa, mutta vuosi oli hakasuluissa tai siinä oli kysymysmerkki tms. En tiedä, miksi esim. tuo Tuurin kirja on tuossa ensimmäisenä, siinä tieto on oikeassa muodossa, mutta vaikuttaako asiaan puuttuva indikaattori 260:ssa, en tiedä. Ainakin sama indikaattori puuttui myös tuosta Jouluaamun kissanpennusta ja muutakin tarkistamastani nimekkeestä. Eli ehkä nekin puutteet voivat vaikuttaa järjestykseen?

**Comment by AnneliO** [comment]
Nuo tiedot haetaan tietokannan taulusta, jonne indikaattoreita ei tallenneta, joten en usko ongelman johtuvan niistä.

**Comment by atarnus** [comment]
Ihan yksinkertaisimillaan tämä alkaa toimimaan omassa testiympäristössä sillä, että kommentoi pois seuraavat rivit itemsearch.pl -tiedostosta:

if (C4::Context->preference("marcflavour") ne "UNIMARC" && $field eq 'publicationyear') {
    $field = 'copyrightdate';
}

Minulla ne oli kahdessa kohtaa. Tämän jälkeen taulukkoon pitäisi tulla pelkästään biblioitems.publicationyear, ja sitten järjestely toimii, ja niin myös filteröinti, joka ei ainakaan minulla myöskään toiminut ennen muutosta. Käytännössä sekä sorting että filtering näki nuo kaikki kentät tyhjinä, myös ne, joissa oli dataa.

**Comment by janPasi** [comment]
Jostain syystä siis tuossa käytetään MARC21:stä käytettäessä publicationyear sorttia pyydettäessä kuitenkin copyrightdatea, joka meillä on tyhjä, koska siihen ei ole mäpätty mitään. Olisikohan tämä viisainta nyt kuitenkin ratkaista niin että tuohon copyrightdate-kenttään mäpätään järjestystä varten tarvittavat MARC-kentät ja ajetaan batch rebuild biblio-tauluille? Silloin ei tarvitsisi tehdä Kohaan meidän ylläpidolle jäävää koodimuutosta. En kyllä ihan tavoita nyt logiikkaa tämän iffityksen taustalla. Siis miksi yhteisössä on haluttu tehdä tuo sorttaus tällä tavalla.

**Comment by AnneliO** [comment]
Huomio palaverista: Jos mäppäyksen tekee copyright-kenttään, poistuu se publicationyear-kentästä. Onko meillä käytetty publicationyear-kenttää jossain eli onko haittaa, jos kenttä tyhjenee?

**Comment by ajrajala** [comment]
Ainakin tallennetuissa raporteissa voi olla publicationyear-kenttä käytössä.

**Comment by velimarj** [comment]
Eli kannattaako tätä siis tehdä?

**Comment by AnneliO** [comment]
Koha-Suomi (Lari) selvittää vielä, missä kaikkialla tuota publicationyear-saraketta on käytetty ja aiheutuuko muutoksesta ongelmia.

**Comment by AnneliO** [comment]
Lari sai tutkimukset tehtyä ja ei havainnut mitään, mikä menisi rikki, jos mäppäysmuutos tehdään.

Ainoastaan biblioitems.publicationyear-kenttää käyttävät tallennetut raportit pitää korjata käyttämään biblio.copyrightdate-kenttää. Ne löytää helpoiten, kun menee tallennettuihin raportteihin ja kirjoittaa sanahaku-kenttään "publicationyear", jolloin hakutulokseksi saa kaikki raportit, jotka sisältävät kyseisen termin. Eli siis se kenttä, joka näkyy joko raporttien etusivulla tai tallennetuissa raporteissa vasemmalla Suodata-osiossa. Raporttitaulukon yläpuolella oleva Search-laatikko ei hae raporttien sisällöistä, joten sillä näitä ei saa kiinni. Raportteja näytti olevan 2-4 kpl/kimppa.

Sovitaan viikon 2 palaverissa, millä aikataululla asian kanssa edetään.

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 9.1.2024: Tehdään rebuildbiblio-ajot kaksi kimppaa/yö ja lähdetään pohjoisesta etelään.
* 9.1.2024 Lappi ja OUTI
* 10.1.2024 Siili ja Vaara
* 11.1.2024 Lumme ja Kyyti
* 15.1.2024 Helle ja Kirkes
* 16.1.2024 Vaski

Pääkäyttäjät peukuttavat seurantakommenttia, kun omaan kimppaan on tehty tarvittava mäppäysmuutos. [Ohje mäppäysmuutoksen tekoon](https://koha-suomi.fi/dokumentaatio/asetukset/#19-kohan-marc-m%C3%A4%C3%A4ritykset).
* biblio.copyrightdate-sarakkeeseen mäpätään MARC-kentät 264c ja 260c

Lari ajelee rebuildbiblio-ajot sovittuina öinä ja kliksuttelee seurantakommenttiin, kun kimppa on valmistunut.

**Comment by lmstrand** [comment]
Outi keskeytyi eilen illalla, ajetaan uudelleen Vaskin jälkeen. Lappi ok. Ajot ajastettu alkamaan sovitusti kaikkiin loppuihin tuotantoihin.

**Comment by lmstrand** [comment]
Lumme-ajo on keskeytynyt:
C4::Biblio::_koha_modify_biblioitem_nonmarc(): DBI Exception: DBD::mysql::st execute failed: Deadlock found when trying to get lock; try restarting transaction at /home/koha/Koha/misc/batchRebuildBiblioTables.pl line 71
Thu 11 Jan 2024 10:41:59 PM EET: End /home/koha/Koha/misc/batchRebuildBiblioTables.pl -c
Thu 11 Jan 2024 10:41:59 PM EET: Runtime 0 hours, 41 minutes, 58 seconds

Ajetaan OUTIn kanssa uusiksi 17.1.

**Comment by lmstrand** [comment]
Ajettu batchRebuildBiblioTables.pl kaikille testeille, paitsi Vaski-test ja Täti-test.

**Comment by AnneliO** [comment]
Tajusin nyt käydä tekemässä mäppäysmuutoksen Tätiin ja Täti-testillekin.

**Comment by lmstrand** [comment]
Laitan tikettiin muistiin vielä outi-tuotannon ongelman:

1408700 records processed in 16702.46 seconds
C4::Biblio::_koha_modify_biblioitem_nonmarc(): DBI Exception: DBD::mysql::st execute failed: Cannot add or update a child row: a foreign key constraint fails (`outiprod`.`biblioitems`, CONSTRAINT `biblioitems_ibfk_1` FOREIGN KEY (`biblionumber`) REFERENCES `biblio` (`biblionumber`) ON DELETE CASCADE ON UPDATE CASCADE) at ./[batchRebuildBiblioTables.pl](http://batchrebuildbibliotables.pl/) line 71
[koha@outi-prod] last: 16706s ~/Koha/misc $ Connection to 10.0.2.151 closed by remote host.

**Comment by lmstrand** [comment]
Lumme ja OUTI ajettu onnistuneesti. OUTIssa valitti ajo, ettei pystynyt käsittelemään tietuetta 2308250.

**Comment by ajrajala** [comment]
Tehtyjen muutosten jälkeen julkaisuvuoden mukainen järjestäminen toimii nyt nidehaun tuloksissa oikein, suljen tiketin.
