### ISSUE TITLE
Lumme: lehden vastaanotto ei onnistu

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#695]
### Mikä vikana?

Haukivuorella on yritetty vastaanottaa uusimman Kodin kuvalehden numeroa 15 ja Me naisten numeroa 28. Kun lehteä lähtee vastaanottamaan ja sen merkkaa saapuneeksi, Koha ei anna nidetietoja täytettäväksi eli lehteä ei voi käytännössä vastaanottaa. Tallenna-nappulaa painaessa Koha oli hävittänyt numeron, jota oli yritetty vastaanottaa puutteellisilla tiedoilla. 

Kodin kuvalehteä oli yritetty vastaanottaa maanantaista lähtien ja sen vastaanotto oli onnistunut tänään 20.7. Me naisten numeroa 28 ei pysty edelleenkään vastaanottamaan, eikä esim. päivämäärän muuttaminen korjaa ongelmaa.

Tätä samaa ongelmaa on kuulemma esiintynyt aikaisemminkin.

### Mitä pitäisi tapahtua

Kun uuden lehden vastaanottaa Kohassa, nidetietolomake pitäisi avautua automaattisesti nidetietojen täyttämistä varten. Nyt näin ei tapahdu. 

### Jotain muuta?

![Me naiset](https://github.com/KohaSuomi/Koha/assets/129748294/1653a113-b4b4-44c4-a0d1-52fde38ef098)

**Comment by AnneliO** [comment]
Tilauksen tiedoissa ei ole valittuna _Luo nide lehteä vastaanotettaessa_, jolloin nidettä ei luoda. Käykää vaihtamassa määritys, niin niteiden luontikin pitäisi lähteä luistamaan. :)

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/7ba5bf94-2fa7-4c3b-8d8f-74332f49a21c)

ps. nro 28 on merkitty jo vastaanotetuksi, niin sen kanssa saattaa joutua vähän värkkäämään, että saa niteenkin luotua. :)

**Comment by Hanna-Lumme** [comment]
Kiitoksia, nyt alkoi homma taas pelittämään!
