### ISSUE TITLE
Vaskin konversiossa siirtyneiden varaustunnisteiden luettavuuden parantaminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#696]
### Tukipyyntö

Vaskin siirtyessä vanhasta kirjastojärjestelmästä Kohaan siirtyi mukana vanhat varaustunnisteet jotka ovat 1-6 numeroisia koodeja. Varauksista valtaosa on edelleen sellaisten asiakkaiden varauksia, joilla on tällainen vanha varaustunniste, ja osa kokee 5-6 numeroa pitkien koodien hahmottamisen hankalaksi, minkä vuoksi varauksia saatetaan myös hyllyttää väärään paikkaan (2XXXX laitetaankin 2XXXXX -numerosarjojen joukkoon jne). Luettavuutta helpottaisi, jos kolmen viimeisen numeron edessä olisikin välilyönti eli noutoilmoitukseen ja kuittiin tulostuisikin koodi muodossa 2XX XXX.

Olisikohan siis mahdollista ratkaista tämä niin, että niihin varaustunnisteisiin, jotka sisältävät pelkkiä numeroita ja ovat pituudeltaan 1-6 numeroa, lisättäisiin välilyönti kolmen viimeisen numeron eteen?

**Comment by lasse-koha** [comment]
Välilyönti lisätty kolmanneksi viimeisen numeron eteen varaustunnuksiin joissa vähintään 4 merkkiä pelkkiä numeroita, muutos koski 355054 varaustunnusta. Mukaan lipsahti 12 varaustunnusta joissa yli 6 merkkiä, löytyvät varmuuskopiotaulusta jos noihin ei välilyöntiä haluttu.

**Comment by ajrajala** [comment]
Kiitokset! Muutos näyttää siltä kuin pitikin. Tultiin siihen lopputulokseen, että nuo mukaan lipsahtaneet 12 varaustunnusta voi jättää sikseen, ei tarvitse muuttaa entiselleen.
