### ISSUE TITLE
OUTI: Vaalan kirjaston kokoelma ei varattavaksi (muutos toivotaan ajettavan 15.8.2023)

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#699]
### Tukipyyntö

OUTIssa Vaalan kirjasto on remontin vuoksi kiinni 17.8. - 27.9.2023. 
Muuttaisitteko niteille, joiden havaintokirjasto (nykyinen kirjasto) on VAPK ja ovat saatavana tilassa:

    damaged-arvoksi 5 (Saatavana, ei varattavissa).

Muutosta ei tehdä, jos nide on:

    kuljetettavana
    kuljetettavana kiinni jääneeseen varaukseen
    lainassa
    odottamassa varattuna noutoa

tai ei myöskään tehdä, jos niteen notforloan-arvo on:

 1 (ei lainattavissa)
-1 (tilattu)
-2 (saapunut)
  6 (laskutettu, toimi kirjastosi laskutusohjeiden mukaisesti)
  8 (ei laskuteta, toimi kirjastosi laskutusohjeiden mukaisesti)
  4 (laskutuksessa, alle 8 e)
  9 (tarkistettavat)
 10 (poistoehdotukset)
-11 (korjattavana)
-12 (tarroitettavat)
 13 (puutteelliset)
-14 (uusin numero, ei lainata)
 15 (Muuttolaatikossa)
 16 (turmeltuneet)

tai ei myöskään tehdä, jos niteen damaged-arvo on: 

6 (Saatavana oppilaille, ei varattavissa)

Muutosajon voi tehdä ti 15.8.2023.

**Comment by emta001** [comment]
Ajo tehty seuraavasti:

`CREATE TABLE ks_20230815_items_ks699 SELECT i.itemnumber, i.biblionumber, damaged, reserve_id FROM items i LEFT JOIN reserves r ON (i.itemnumber = r.itemnumber) WHERE i.damaged != 6 AND notforloan = 0 AND holdingbranch = "VAPK" AND onloan IS NULL AND r.found IS NULL AND i.itemnumber NOT IN (select itemnumber from branchtransfers where tobranch = "VAPK" and datearrived IS NULL);`

`UPDATE items i LEFT JOIN reserves r ON(i.itemnumber = r.itemnumber) SET i.damaged = 5 WHERE i.holdingbranch = "VAPK" AND  i.damaged != 6 AND notforloan = 0 AND onloan IS NULL and r.found IS NULL AND i.itemnumber NOT IN (select itemnumber from branchtransfers where tobranch = "VAPK" and datearrived IS NULL);`

Muutos koski 42079 nidettä.

**Comment by piiaseme** [comment]
Kiitos, pikaisella silmöyksellä en huomannut mitään jääneen pois ajosta tai tulleen liikaa :) Ilmoitan Vaalaan ja pyydän tarkistamaan hieman myös.

**Comment by piiaseme** [comment]
Vaalasta ei ole kuulunut, että ajossa olisi huomattu tapahtuneen virheitä, joten suljen tiketin.
