### ISSUE TITLE
Ceepos-kassaliittymän dokumentaation päivitys

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#700]
### Tukipyyntö

Ceepos-kassaliittymän dokumentaatio pitää päivittää vastamaan uusinta versiota.

Vanha versio dokumentaatiosta löytyy [Redminestä](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Kassaintegraatio_ja_verkkomaksut)

Uusi versio lisätään [liitännäisen wikiin](https://github.com/KohaSuomi/koha-plugin-ceepos-integration/wiki/Ceepos%E2%80%90kassaliittym%C3%A4n-k%C3%A4ytt%C3%B6%C3%B6notto).

**Comment by AnneliO** [comment]
Kun tiedot on siirretty ja päivitetty, merkitse Redmineen [Tekninen dokumentaatio](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/Tekninen_dokumentaatio) -sivulle ohjeen kohdalle "Siirretty" ja linkki uuteen paikkaan.

**Comment by emta001** [comment]
Tuosta Redminessä olevasta ohjeesta on vielä linkki tähän [ohjeeseen](https://tiketti.koha-suomi.fi/projects/koha-suomen-dokumentaatio/wiki/1_Asiakkaat#Maksujen-maksaminen-Ceepos-kassaliittym%C3%A4n-kautta). Tarvitseeko tämäkin siirtää vai onko se lisätty jo "Kohan ohje suomeksi" -sivulle.

**Comment by AnneliO** [comment]
Tuo ohje löytyy [Maksut](https://koha-suomi.fi/dokumentaatio/maksut/#35-maksujen-maksaminen-ceepos-kassaliittym%C3%A4n-kautta)-osiosta Kohan ohjeesta suomeksi. Tosin sekin näyttää vanhentuneelta. Pitää tarkistaa, kenen vastuulla tuon osion päivitys on. :)

**Comment by AnneliO** [comment]
Auli Vaarasta päivittää Maksut-osion Ceepoksen osalta.

**Comment by johannaraisa** [comment]
Tekninen dokumentaatio on liitännäisen READMEssä, se on ajan tasalla.

**Comment by AnneliO** [comment]
Tehty
