### ISSUE TITLE
OKM-tilastoliitännäisen dokumentaation päivitys

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#701]
### Tukipyyntö

OKM-tilastoliitännäisen dokumentaation päivitys [liitännäisen wikiin](https://github.com/KohaSuomi/koha-plugin-OKM-stats/wiki/OKM-tilastot).

**Comment by emta001** [comment]
Tästä on jo tiketti plugarin repossa ;) https://github.com/KohaSuomi/koha-plugin-OKM-stats/issues/4

**Comment by AnneliO** [comment]
> Tästä on jo tiketti plugarin repossa ;) [KohaSuomi/koha-plugin-OKM-stats#4](https://github.com/KohaSuomi/koha-plugin-OKM-stats/issues/4)

No niinpä vain. Suljenpa siis tämän. :D
