### ISSUE TITLE
KohaSuomiServices/Valutus-dokumentaation päivitys

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#703]
### Tukipyyntö

KohaSuomiServices/Valutus-palvelun dokumentaation päivitys.

[koha-plugin-broadcast-biblios -wiki](https://github.com/KohaSuomi/koha-plugin-broadcast-biblios/wiki)

[KohaSuomiServices -wiki](https://github.com/KohaSuomi/KohaSuomiServices/wiki)

Liittykö tähän muuta?

**Comment by johannaraisa** [comment]
Dokumentaatio siirretty Tietuesiirtäjän wikiin.
