### ISSUE TITLE
Emotietueesta osakohteeseen siirtyvät tiedot ja RDA

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#705]
### Kehitysehdotukseni

Alkuperäinen tiketti: "Pystyykö Kohassa määrittämään, mitkä tiedot siirtyvät emotietueesta automaattisesti osakohteen 773-kenttiin, kun tekee uuden osakohteen?"

"Koska musiikkiaineistonkin kuvailu on RDA:n mukaista, niin määrityksiä tulisi muuttaa. Anneli on joitain vuosia sitten tutkinut tätä ja todennut, ettei käyttöliittymän kautta ei pysty määrittämään, mitä tietoja emosta siirtyy osakohteeseen."

Selvisi, että määrityksille ei ole mitään järjestelmäasetusta olemassa, vaan kentät on kovakoodattu Kohan lähdekoodiin. (C4\Biblio.pm, prepare_host_field).

PasiK teki halutut muutokset ja siirsi ne tuotantoon seuraavasti:

![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/f5fec4d1-f1af-41f9-a692-9f90e7e119dd)

### Jotain muuta?

Siirretty Redminesta: https://tiketti.koha-suomi.fi/issues/3509

Liittyy tikettiin: https://github.com/KohaSuomi/Koha/issues/704

**Comment by piiaseme** [comment]
Bugzillassa tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=37061

**Comment by johannaraisa** [comment]
Nyt on testeillä PrepareHostField-järjestelmäasetus, mihin voi määritellä halutut kentät. Asetuksen esimerkissä kerrotaan miten määritykset tehdään. Jos ei määrittele mitään, niin pitäisi käyttää kovakoodattua, eli nykyistä tapaa.

**Comment by AnttHeik** [comment]
Kerrassaan mainiota. Ehtisikö @piiaseme tai @AnneliO laittamaan nämä asetukset päälle Testi-TäTissä, niin pääsee testaamaan? :)

**Comment by piiaseme** [comment]
@AnttHeik kävin tallentamassa kentät Koha-testille. Pystytkö testaamaan siellä? Jostain syystä en pääse testi-TäTiin, joten sinne tallennan, kun pääsen sisälle sinne.

**Comment by johannaraisa** [comment]
> @AnttHeik kävin tallentamassa kentät Koha-testille. Pystytkö testaamaan siellä? Jostain syystä en pääse testi-TäTiin, joten sinne tallennan, kun pääsen sisälle sinne.

Testi-Täti on redusoitu, toimiikohan tuotantotunnus siellä?

**Comment by piiaseme** [comment]
Anneli tsekkasi, ettei minun tunnusta ole testi-Tätille. Kodo tekee siirron.

**Comment by piiaseme** [comment]
Nyt kentät on tallennettu myös testi-TäTiin.

**Comment by AnttHeik** [comment]
No se toimii just niin kuin pitääkin. 

Tosin OUTIn testillä huomasin, että jos julkaisutiedot ovatkin vanhaan malliin 260-kentässä, niin silloin ei siirry mitään 773d-kenttään. Onko mahdollista määrittää useampi lähtökenttä joihinkin kohtiin eli
260abc | 773d
264abc | 773d

Lisäksi pohdin vielä kahta pientä kehitysjuttua, mutta jos nämä vaikuttavat hankalilta toteuttaviksi, niin ei tarvitse miettiä pidemmälle, koska tämänhetkiselläkin toteutuksella pärjää oikein hyvin :)
- Entä jos sattuisi olemaan vaikka useampi 028-kenttä tai 020-kenttä, niin olisiko mahdoton ajatus, että nämä kaikki muodostuisi osakohteeseen omiksi 773o- tai 773z-toistumikseen? 
- Entä olisiko mahdollista säätää kuvailupohjakohtaisesti, mitä kenttiä 773-kenttiin lähetetään eli katsottaisiin emon kuvailupohja ja sen perusteella sitten lähetettäisiin tiedot?

(Testi-Tätistä ei muuten tuntunut löytyvän nuotteja ollenkaan. Onkohan ne redusoitu pois?)

**Comment by piiaseme** [comment]
> Tosin OUTIn testillä huomasin, että jos julkaisutiedot ovatkin vanhaan malliin 260-kentässä, niin silloin ei siirry mitään 773d-kenttään. Onko mahdollista määrittää useampi lähtökenttä joihinkin kohtiin eli 260abc | 773d 264abc | 773d
> 
Voin lisätä testeille, niin nähdään miten lisäys reagoi.

**Comment by piiaseme** [comment]
Nyt on lisätty OUTIn testille sekä TäTin testille.

**Comment by AnttHeik** [comment]
Kiitos, hyvin näyttää toimivan, paitsi OUTIssa vissiin unohtui laittaa 260c-kenttä mukaan? TäTin puolella tuli sekin nätisti :)

**Comment by AnttHeik** [comment]
> > (Testi-Tätistä ei muuten tuntunut löytyvän nuotteja ollenkaan. Onkohan ne redusoitu pois?)
> 
> On siirtynyt yksi nuotti: 2460995 Löydätkö tällä tiedolla?

Joo, tein tuon just itse testitietueeksi :)

> 
> Tsekkaan tuon puuttuvan kentän ja lisään, jos puuttuu.

Ok.

**Comment by johannaraisa** [comment]
Kokeilitteko tuota useampaa lähtökenttää, se saattaa jo toimia tässä. Lisäksi se jos on esim. monta 020-kenttää. Kuvailupohjan mukaan ottaminen vaatii kyllä hieman enemmän, ku se tieto pitäisi hakea jostain, tuo saattaa käyttää oletuspohjaa aina kun tehdään osakohde.

**Comment by piiaseme** [comment]
> Kokeilitteko tuota useampaa lähtökenttää, se saattaa jo toimia tässä. 

Lisäsin kentät ja Antti taisi jo eilen kokeilla ja todeta, että hyvin toimi sekä OUTin että TäTin testillä.

**Comment by AnneliO** [comment]
Testailin lisäämällä tietueelle kahdet 020a- ja 028a-kentät ja vain ensimmäiset toistumat siirtyivät osakohteeseen. Mäppäykseen ei pystynyt lisäämään toista kertaa samaa kenttää, se valitti tuplatiedosta.

**Comment by johannaraisa** [comment]
> Testailin lisäämällä tietueelle kahdet 020a- ja 028a-kentät ja vain ensimmäiset toistumat siirtyivät osakohteeseen. Mäppäykseen ei pystynyt lisäämään toista kertaa samaa kenttää, se valitti tuplatiedosta.

Niin, se on jo avainarvona, mutta mites jos tietueessa on useampi esiintymä?

**Comment by johannaraisa** [comment]
> > Kuvailupohjan mukaan ottaminen vaatii kyllä hieman enemmän, ku se tieto pitäisi hakea jostain, tuo saattaa käyttää oletuspohjaa aina kun tehdään osakohde.
> 
> Tehdäänkö tästä oma tiketti?

Ehkä tämä on jo uusi tiketti, tuo muutos tekee nyt ainakin sen mitä siihen Bugzillan tikettiin laitoit.

**Comment by AnneliO** [comment]
> > Testailin lisäämällä tietueelle kahdet 020a- ja 028a-kentät ja vain ensimmäiset toistumat siirtyivät osakohteeseen. Mäppäykseen ei pystynyt lisäämään toista kertaa samaa kenttää, se valitti tuplatiedosta.
> 
> Niin, se on jo avainarvona, mutta mites jos tietueessa on useampi esiintymä?

Kuten tuossa ekassa lauseessa kerroin. :) Eli vain ensimmäiset toistumat siirtyivät osakohteeseen.

**Comment by AnttHeik** [comment]
Kiitokset vastauksista ja testailuista. Minusta voidaan mennä näillä säädöillä. Tässä on kuitenkin se hyvä juttu, että käyttäjät voivat nyt itse määritellä, mitä kenttiä haluavat osakohteeseen siirtyvän.

**Comment by AnneliO** [comment]
Suomenkieliset muutokset järjestelmäasetuksiin viety GitHubiin Koha-translations-tietovarantoon.

**Comment by pirliis** [comment]
> Nyt on lisätty OUTIn testille sekä TäTin testille.

Asetukset lisätty OUTIn tuotantoon 18.6. ja TäTin tuotantoon 25.6.

**Comment by piiaseme** [comment]
Tämä näyttää olevan nyt paketissa, joten suljen tiketin. Avataan uudelleen, jos olin liian hoppuinen.
