### ISSUE TITLE
Lappi: Hakutuloksen saatavuusnäkymä ei päivity

### ISSUE THREAD

**Issue by MariaJoon** [KohaSuomi/Koha#707]
### Mikä vikana?

Hakutuloksissa näkyy edelleen niteitä ROSA varastoidut tilassa, vaikka tila on poistettu käytöstä ko. niteiltä 31.7.2023.
Nidetiedoissa tieto näkyy oikein.
![image](https://github.com/KohaSuomi/Koha/assets/99168614/1b674332-5374-40ae-bd6d-e555575f4ad2)

Tarvitaan siis uudelleen indeksointi (sama ongelma kuin Tornion varastoitujen kanssa, tiketti #623 )

### Mitä pitäisi tapahtua

Saatavuustiedot pitäisi päivittyä myös hakutulossivulle.

**Comment by lmstrand** [comment]
Laitetaan uudelleenindeksointi ajautumaan tänä yönä.

**Comment by MariaJoon** [comment]
Näyttäisi olevan kunnossa, kiitos! Suljen tiketin.
