### ISSUE TITLE
Kohan floatrules ohjeeseen tieto kommentointimahdollisuudesta

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#709]
### Kehitysehdotukseni

Kohan floatrulesissa voi käyttää perlin # kommentteja. Kommentointimahdollisuudesta olisi hyvä mainita floatrulesin ohjeessa, koska kommentointi helpottaa suuren sääntömäärän ylläpitoa.

**Comment by emta001** [comment]
Tehdään versionvaihdon yhteydessä.

**Comment by Kati-Helle** [comment]
Helle-nextillä floatrules-asetuksessa kerrotaan sääntöjen kommentointimahdollisuudesta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fa34c12e-0c2f-4a03-8bbf-d86b04820b72)

**Comment by emta001** [comment]
Toiminee. Suljen tiketin.
