### ISSUE TITLE
Kirjaston nimeen tehty muutos ei näy niteen muokkaus/lisäys -näytöllä

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#710]
### Mikä vikana?

Vaskin tuotannosta poistettiin 31.7. aamulla joidenkin kirjastojen nimistä niissä ollut kiinniolotieto. Jostain syystä niteen muokkauksessa/lisäyksessä aiempi kirjaston nimi näkyy kuitenkin edelleen (ks. kuva).

Ongelma toistuu myös englannikielisellä puolella, ctrl + F5 ei auta.

Muualle (esim. saatavuustiedot, valikot) nimi näyttäisi päivittyneen ihan oikein eli toistaiseksi havaittu nimikummittelua vain tuolla niteen lisäyksessä/muokkauksessa.

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/1971cc5a-9408-4320-8585-07ab163ee7db)

**Comment by ajrajala** [comment]
Ongelma jatkuu edelleen eikä eilisaamuna muokattu kirjaston nimikään ole niteiden lisäys/muokkaus-näytölle päivittynyt.

**Comment by janPasi** [comment]
Näköjään joku mystinen välimuistiongelma. Tyhjensin välimuistit ja ylimääräinen teksti katosi.

**Comment by ajrajala** [comment]
Kiitokset! Täytyypä seurata seuraavien nimi-muutosten yhteydessä tapahtuuko tämä uudelleen.

**Comment by rakkyllo** [comment]
Hei, tämä ongelma ilmeni taas tänä aamuna kun päivitimme RUPK-yksikön aukioloaikatiedot. Voisimmeko saada taas välimuistin tyhjennyksen? Kiitos!

**Comment by emta001** [comment]
> Hei, tämä ongelma ilmeni taas tänä aamuna kun päivitimme RUPK-yksikön aukioloaikatiedot. Voisimmeko saada taas välimuistin tyhjennyksen? Kiitos!

Toimiiko nyt?
