### ISSUE TITLE
message_queue-taulu vuositauluiksi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#711]
### Tukipyyntö

OUTIssa ja Vaskissa on ollut Kohassa käyttökatkoksia, joissa käyttäjä saa ilmoituksen 503 service unavailable. 

OUTIssa katkot ovat ajallisesti n. 9.30-9.40 välimaastossa. Tällöin lähetetään ainakin päivän ensimmäinen setti viestejä.

Vaskissa katkot ovat olleet ajallisesti klo 13 seutuvilla. Siellä taas on ollut ongelmia saada auki Ilmoitukset-välilehteä sellaisilla asiakkailla, joille on lähetetty paljon viestejä #691.

Keskustelimme ongelmista Koha-Suomen viikkopalavereissa ja päätimme kokeille, olisiko message_queue-taulun jakamisesta vuositauluihin apua näihin ongelmiin.

Aktiiviseen tauluun jätetään kuluva vuosi ja muut vuodet omiksi tauluikseen. Viestien säilytysajaksi on asiantuntijaryhmässä päätetty 3 vuotta + kuluva.

**Comment by lmstrand** [comment]
Skripti archive_message_queue lisätty koha-suomi-utility -repoon.

**Comment by AnneliO** [comment]
Muutetaan ohjeistusta niin, että vanhat viestit viedään yhteen arkistotauluun vuositaulujen sijaan. Se helpottaa mm. kyselyjen tekemistä. Taulun nimeksi message_queue_archive.

**Comment by lmstrand** [comment]
Kaikkiin kimppoihin on arkistoitu 12kk vanhemmat viestit vuositauluihin. Arkistointicroni ajetaan joka kuun ensimmäinen päivä. Skriptiä on muutettava niin, että arkistoitavat viestit siirtyvät message_queue_archive-tauluun ja arkistoidut taulut on yhdistettävä tähän.

**Comment by lmstrand** [comment]
Koska päätimme säilyttää vuositaulut (ainakin toistaiseksi) suljen tiketin.
