### ISSUE TITLE
Template toolkitin kanssa ongelmia sähköposti-kuiteilla

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#712]
### Mikä vikana?

Vaskissa ollaan päivittämässä kuittipohjia ja jostain syystä en saa testiympäristössä sähköpostilla lähtevissä CHECKIN ja CHECKOUT -pohjissa toimimaan lainatietojen hakemista template toolkitillä vaikka sama koodi on testattu toimivaksi CHECKINSLIP, ISSUESLIP ja ISSUEQSLIP -pohjissa. Testauksessa käytössä siis CHECKIN ja CHECKOUT -viestipohjien Oletus-kielipohja. Muodostunut viesti löytyy esim. [tältä testiasiakkaalta](https://vaski-test.koha-suomi.fi/cgi-bin/koha/members/notices.pl?borrowernumber=360797). Muodostuneeseen viestiin näyttää tulostuvan pelkästään pätkä _Lainaaja: [% borrower.cardnumber %]_, ei pohjassa sen jälkeen olevia tekstejä.

[Yhteisön wikin](https://wiki.koha-community.org/wiki/Notices_with_Template_Toolkit#Example:_CirculationRules.Renewals) perusteella ymmärsin, että CHECKIN ja CHECKOUT -pohjissa pitäisi olla käytettävissä tarvittavat palikat. Pohjien esikatselutoiminnolla jos testaan niin esikatselun perusteella noiden borrower.*-tietojen haku onnistuu mutta lainatietojen ei:
![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/76a48868-cc96-4794-8d62-5f66e278fb17)

Onko vika koodissa vai viestipohjan muokkaajassa? 😄

**Comment by lmstrand** [comment]
Lisäsin tuohon CHECKIN-pohjan foreach-riviin borrower.old_checkoutsin eli muuttui
[% FOREACH checkin IN borrower.old_checkouts %]

Palauttaessa tulostui tällainen kuitti:

![image](https://github.com/KohaSuomi/Koha/assets/18394834/4bd8e81b-2da8-4f0b-b008-384def2bc52d)

**Comment by lmstrand** [comment]
Ainiin, mutta tuo oli kuittipohja...no esimerkeissä on käytetty tuota borrower.xxxxx noissa FOREACH-loopeissa.

**Comment by ajrajala** [comment]
Hmm, testasin tuota ja näyttää siltä, että sähköposti-palautuskuittiin tulee asiakkaan aiemminkin palauttamat niteet, ei pelkästään tänään palautetut ([testiasiakas](https://vaski-test.koha-suomi.fi/cgi-bin/koha/members/notices.pl?borrowernumber=360797)).

**Comment by ajrajala** [comment]
Herättelen henkiin vielä tätä tikettiä ennen kuin kokonaan luovutan. 😄 Mietin, että olisiko TT-syntaksiin pystynyt ottamaan mukaan rajausta kuluvana päivänä lainattuihin/palautettuihin lainoihin? Silloin esim. lainauskuitilla tämä koodi pelittelisi oikein. Nyt tuo koodi antaa siis kuitille kaikki asiakkaan lainoissa olevat lainat.

```
[% FOREACH checkout IN checkouts %]
[%~ SET item = checkout.item %]
[%~ SET biblio = checkout.item.biblio %]
<p>
[% IF biblio.author %][% biblio.author %]:<br />[% END %]
[% biblio.title %][% IF biblio.part_number %] / [% biblio.part_number %][% END %][% IF biblio.part_name %] - [% biblio.part_name %][% END %][% IF item.enumchron %] ([% item.enumchron %])[% END %]<br />
[% item.barcode %]<br />
<b>Eräpäivä: [% checkout.date_due | $KohaDates %]</b><br />
</p>
[% END %]
```

Olispa kiva kun näissä sähköpostikuiteissa toimis sama syntaksi kuin paperikuiteissa.

**Comment by ajrajala** [comment]
...huomasinkin yhteisössä tiketin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=19167, tuon perusteella päättelen ettei kuluvaan päivään rajaaminen tällä hetkellä ole mahdollinen?

**Comment by lmstrand** [comment]
Koska tuo poha tukee TT:tä niin kai tuon pitäisi onnistua tuon saman päivän aikana luotujen lainojen rajaus.

[% USE KohaDates %]
[% USE date %]

[% IF checkout.issuedate | $KohaDates == date.format('%Y-%m-%d') %]

[% END %]

 Jotenkin tuonne päin, pitäisi testailla.

**Comment by lmstrand** [comment]
Sain aikaiseksi suodatettua vain kyseisen päivän aikana tehdyt lainat tällä rimpsulla ISSUESLIP:lle

[%- USE KohaDates -%]

[% FOREACH checkout IN checkouts %]

[% todaydate = today | $KohaDates %]
[% issuedate = checkout.issuedate | $KohaDates %]

[% IF todaydate == issuedate %]

[%~ SET item = checkout.item %]
[%~ SET biblio = checkout.item.biblio %]
<p>
[% IF biblio.author %][% biblio.author %]:<br />[% END %]
[% biblio.title %][% IF biblio.part_number %] / [% biblio.part_number %][% END %][% IF biblio.part_name %] - [% biblio.part_name %][% END %][% IF item.enumchron %] ([% item.enumchron %])[% END %]<br />
[% item.barcode %]<br />
<b>Eräpäivä: [% checkout.date_due | $KohaDates %]</b><br />
</p>

[% END %]
[% END %]

**Comment by ajrajala** [comment]
Näköjään toimii vain ISSUESLIPillä, ei CHECKOUT- eli sähköpostikuitilla ehkä enää ymmärrä miten tuo aiemman kommenttini FOREACH-looppi olisi ylipäätään toiminut, sillä en saa sitäkään kyllä toimimaan enää. Varmaan viime viikolla käynyt joku kämmi testatessa, testiasiakas käyttänyt ehkä eri kielipohjaa kuin mihin muutokset olin tehnyt. Summa summarum tässä kai on, että tuossa TT-syntaksin käytössä on noilla CHECKOUT ja CHECKIN -pohjilla ongelma ja kyllä tästä ainakin tällaisen yhteisön tiketin onnistuin löytämään: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31656.

Laitoin itseni nyt seuraamaan yhteisön tikettiä jos se joskus liikahtaisi. Ehkä nyt suljen tämän tiketin, ongelma ei ole kriittinen eikä tätä nyt ehkä tällä erää ole enempää aikaa edistää.
