### ISSUE TITLE
Vaara: Rantakylän kirjaston muutto

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#713]
### Tukipyyntö

Rantakylän kirjasto (JOERAN) muuttaa takaisin remontoituihin tiloihin 4.9. alkaen. Aineisto pitää laittaa ei-lainattavaksi, ei varattavaksi ja asiakkaiden varaukset siirtää pääkirjastolle (JOEJOE). Tarkemmat tiedot:

**4.9. tehtävä**
JOERAN paikalla oleva aineisto NOT_LOAN tilaan 9 (ei lainassa oleva aineisto)
Jos asiakkaan varauksen noutopaikka on JOERAN ->JOEJOE

**9.10. tehtävä**
JOERAN NOT_LOAN tilan 9 poistaminen niteiltä
4.9. tehdyn varausten noutopaikan muutoksen peruuttaminen (jos onnistuu)

**Comment by emta001** [comment]
Muutokset tehty seuraavasti:
```
CREATE TABLE ks_230904_items_713 SELECT itemnumber, biblionumber, notforloan FROM items WHERE holdingbranch = "JOE_RAN" AND onloan IS NULL;
UPDATE items SET notforloan = 9 WHERE holdingbranch = "JOE_RAN" AND onloan IS NULL;
```
```
CREATE TABLE ks_230904_reserves_713 SELECT reserve_id, borrowernumber, biblionumber, branchcode FROM reserves WHERE brachcode = "JOE_RAN";
UPDATE reserves SET branchcode = "JOE_JOE" WHERE branchcode = "JOE_RAN";
```

**Comment by pknuuti** [comment]
Asiakkaalle on lähtenyt 30.8. noutoilmoitus Rantakylän kirjastoon, viimeinen noutopäivä 16.10. Varaukset on siirretty Joensuun pääkirjastoon 4.9. ja asiakas on sen sieltä lainannut samana päivänä. Varattu nide näkyy edelleen asiakkaalla noudettavissa. Asiakkaan id 1096181.
Jääkö muutkin viime päivinä Rantakylään noudettavaksi jääneet niteet väärään tilaan, kun ne lainataan pääkirjastosta? Voiko niiden noutopaikan vielä vaihtaa JOE_JOE:ksi?

**Comment by emta001** [comment]
> Asiakkaalle on lähtenyt 30.8. noutoilmoitus Rantakylän kirjastoon, viimeinen noutopäivä 16.10. Varaukset on siirretty Joensuun pääkirjastoon 4.9. ja asiakas on sen sieltä lainannut samana päivänä. Varattu nide näkyy edelleen asiakkaalla noudettavissa. Asiakkaan id 1096181. Jääkö muutkin viime päivinä Rantakylään noudettavaksi jääneet niteet väärään tilaan, kun ne lainataan pääkirjastosta? Voiko niiden noutopaikan vielä vaihtaa JOE_JOE:ksi?

Kummallista, tuon varauksen noutopaikkahan on jo JOE_JOE eikä Vaaran kannassa ole yhtään varausta, joiden noutopaikka olisi JOE_RAN. Tutkitaan.

**Comment by pknuuti** [comment]
Avaamispäivä päivitetty, tiketti Odottaa-tilassa.

**Comment by lmstrand** [comment]
Ajettu: 
```
MariaDB [vaaraprod]> update items i 
    -> inner join ks_230904_items_713 i2 on(i.itemnumber = i2.itemnumber)
    -> set i.notforloan = i2.notforloan
    -> where i.itemnumber = i2.itemnumber;
Query OK, 17292 rows affected (2.755 sec)
Rows matched: 18432  Changed: 17292  Warnings: 0
```

**Comment by lmstrand** [comment]
Varauksille ajettu:

```
MariaDB [vaaraprod]> update reserves set branchcode = "JOE_RAN" where reserve_id in(select reserve_id from ks_230904_reserves_713);
Query OK, 648 rows affected (21.537 sec)
Rows matched: 793  Changed: 648  Warnings: 0
```

**Comment by pknuuti** [comment]
Kiitos. Suljen tiketin.
