### ISSUE TITLE
Vaski: Erikoistila pois Maskun pääkirjaston niteiltä 15.8.

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#714]
### Tukipyyntö

Maskun pääkirjasto avataan 15.8, joten pääkirjaston niteiltä tarvitsee tuona aamuna poistaa erikoistila ei saatavana, ei varattavissa.

Eli notforloan arvo 4 pois niteiltä, joiden nykyinen kirjasto on MAPK.

**Comment by AnneliO** [comment]
Seuraavaksi yöksi kannattaa ajastaa myös täydellinen uudelleenindeksointi, jotta tilat päivittyvät myös indeksiin.

**Comment by emta001** [comment]
Liittyy ilmeisesti tikettiin [573](https://github.com/KohaSuomi/Koha/issues/573)? Tuohon liittyy aputaulu ks_20230605_items_ks573, tilat voinee palautella sen perusteella.

**Comment by emta001** [comment]
Ajo tehty:

`UPDATE items SET notforloan = 0 WHERE holdingbranch = "MAPK" AND notforloan = 4;`

Muutos koski 34368 nidettä.

**Comment by MikkoLiimatainen** [comment]
Tämä on kunnossa, suljen tiketin.
