### ISSUE TITLE
Toistettujen tekijäfunktioiden perässä kaksi pilkkua

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#716]
### Mikä vikana?

Siirretty [Redminestä tiketistä #3798](https://tiketti.koha-suomi.fi/issues/3798).

Jos tietueessa tekijällä on 1XX tai 7XX-kentissä monta funktiota eli e-kenttää on toistettu, Kohan näytölle tulee kaksi pilkkua peräkkäin, vaikka yksikin riittäisi:

esim: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1912019

Majava, Tanja [kirjoittaja,, valokuvaaja,, toimittaja.] -> Majava, Tanja [kirjoittaja, valokuvaaja, toimittaja.]

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/a47a2f9a-44e6-4276-90d8-ca29e926a692)

### Mitä pitäisi tapahtua

Pilkkuja tarvitaan vain yksi toistettujen kenttien perään.

**Comment by paxed** [comment]
On tätin testillä, ja näyttäisi toimivan.

**Comment by AnttHeik** [comment]
Juu, sehän näyttää ihan hyvältä nyt :)

Jos jossain välissä käsittelet haun tulokset -sivua, niin siellä ehkä voisi tehdä tämän saman jutun. Nyt sivulla näkyy tietueet näin:
![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/93433f29-1113-4904-b447-8a78363af325)

**Comment by AnneliO** [comment]
Siirretäänkö tämä takaisin työn alle, eli sama muutos myös hakutuloslistalle?

**Comment by paxed** [comment]
Hakutuloslistan muutos on tehty myös, tulee seuraavaan päivitykseen
