### ISSUE TITLE
OUTI: Testille päälle ajo, joka muodostaa kirjastokorttien vanhenemismuistutukset

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#717]
### Tukipyyntö

Saisimmeko OUTIn testille muutamaksi päiväksi päälle ajon, joka muodostaa kirjastokorttien vanhenemismuistutukset (membership_expiry.pl). Muokkasimme muistutusviestiä niin, että asiakkaille ja virkailijoille lähtisi eri viestit. Haluaisimme varmistaa testillä, että muistutukset näyttävät oikeanlaisilta molemmissa viesteissä.

Viestit eivät saa saa lähteä kuitenkaan eteen päin. ;) Tarkistamme syntyneet ilmoitukset asiakastiedoista.

**Comment by lasse-koha** [comment]
Ajastettu membership_expiry.pl puoli yhdeltä yöllä.

**Comment by pirliis** [comment]
OUTIn testillä testaukset tehty. Ajon saa ottaa pois päältä, jos niin on parempi. :)

**Comment by pirliis** [comment]
Suljen tiketin.
