### ISSUE TITLE
RUPK:n varausten keskeytyksen jatkaminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#719]
### Tukipyyntö

Ruskon pääkirjaston kiinniolo pitkittyy ja aiemmin jo keskeytettyjen varausten kestoa pitäisi siksi jatkaa.

Eli saisiko seuraavat ehdot täyttäville varauksille suspend_until arvoksi 2023-09-03 23:59:59:
- branchcode = RUPK
- varauksen suspend_until arvo on entuudestaan 2023-08-09

Pyyntö tulee viime tintaan, mutta tarvitsisi siis vielä tehdä tänään.

**Comment by paxed** [comment]
Muutos tehty tällä rimpsulla, ja koski 80 varausta:

update reserves set suspend_until = '2023-09-03 23:59:59' where branchcode='RUPK' and DATE(suspend_until) = '2023-08-09';

**Comment by ajrajala** [comment]
Suurkiitos, tämä ok!
