### ISSUE TITLE
OUTI: Nidenumerolla haku antaa "Virhe 500"

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#723]
### Mikä vikana?

Kun hakee nidenumerolla tietueen: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1354963 nidettä 564N17524655 tai nidettä 564N17524667, tulee virhe 500. 

Niteiden lainaaminen ja palauttaminen toimivat ongelmitta eli ei tule virheilmoitusta.

**Comment by emta001** [comment]
Molempien niteiden haulla lokiin kirjautuu seuraavaa:

```
Invalid header value contains a newline not followed by whitespace: location="/cgi-bin/koha/catalogue/detail.pl?biblionumber=1354963
&amp;fo... at /usr/share/perl5/CGI.pm line 1561.
```

**Comment by pirliis** [comment]
Korjasitkohan lie jotain, mutta nyt molemmilla niteillä haku toimii. Kiitos!

**Comment by emta001** [comment]
> Korjasitkohan lie jotain, mutta nyt molemmilla niteillä haku toimii. Kiitos!

Anneli kävi tallentamassa tietueen uudestaan. Jossain on kai ollut rivinvaihto, joka on sitten headerissä laittanut rivit sekaisin (näin epäili Pasi).

**Comment by pirliis** [comment]
Kiitos Anneli! Suljen tiketin.
