### ISSUE TITLE
Virhe 404 -ilmoitus kun tilauksen sisäistä/toimittajan huomautusta muokkaa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#724]
### Mikä vikana?

Jos käyttäjä yrittää muokata tilauksella olevaa sisäistä/toimittajan huomautusta, tallenna-painikkeesta tulee virhe 404 -ilmoitus. Sama toistuu myös silloin, jos tilauksella ei entuudestaan ole huomautusta ja yrittää lisätä uutta.

Molemmissa tapauksissa tieto näyttää kuitenkin tallentuneen, kun selaimessa siirtyy takaisin edelliselle sivulle ja päivittää sivun.

### Kuinka toistaa ongelma/asia

1. Avaa jokin hankinnan tilauskori
2. Kokeile muokata tilauksen sisäistä huomautusta (internal note) tai toimittajan huomautusta (vendor note)
3. Tallenna tekemäsi muutos, huomaa että saat 404 virheilmoituksen
4. Palaa takaisin edelliselle sivulle ja päivitä sivu, huomaa että tekemäsi muutos on kuitenkin tallentunut huomautukseen

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/24532813-1ea5-4674-9412-188cac6d89c6)

**Comment by lasse-koha** [comment]
Johtuu ilmeisesti branchin [ksdev/ks-0025-KD-4349](https://github.com/KohaSuomi/Koha/tree/ksdev/ks-0025-KD-4349) muutoksista mutta omassa testiympäristössäni kyllä ohjautuu oikein takaisin tilauskorisivulle basket.pl.

**Comment by lasse-koha** [comment]
Korjaus tuotu testeille.

**Comment by ajrajala** [comment]
Näyttäisi korjaantuneen, testasin sekä olemassa olevan sisäisen/toimittajan huomautuksen muokkaamista että uuden lisäämistä.

**Comment by Kati-Helle** [comment]
Helle-testissä 
- Sisäinen huomautus: toimii virheettömästi olemassa olevan huomautuksen muokkaus, poisto, uuden huomautuksen lisäys.
- Huomautus toimittajalle: toimii virheettömästi olemassa olevan huomauksen muokkaus, poisto, uuden huomautuksen lisäys.

**Comment by pknuuti** [comment]
Kun lisää/muokkaa huomautusta (sisäistä tai toimittajalle), ei tule mitään virheilmoitusta kun huomautus tallennetaan. Tallennuksen jälkeen palaa Hankinnan aloitussivulle.

**Comment by AnneliO** [comment]
> Kun lisää/muokkaa huomautusta (sisäistä tai toimittajalle), ei tule mitään virheilmoitusta kun huomautus tallennetaan. Tallennuksen jälkeen palaa Hankinnan aloitussivulle.

Hmm.. hankinnan etusivulle pitäisi päätyä vain virhetilanteessa. Muulloin sivun pitäisi palata sille sivulle, mistä lähdettiin liikkeelle (esim. tilauskoriin).

**Comment by pknuuti** [comment]
> > Kun lisää/muokkaa huomautusta (sisäistä tai toimittajalle), ei tule mitään virheilmoitusta kun huomautus tallennetaan. Tallennuksen jälkeen palaa Hankinnan aloitussivulle.
> 
> Hmm.. hankinnan etusivulle pitäisi päätyä vain virhetilanteessa. Muulloin sivun pitäisi palata sille sivulle, mistä lähdettiin liikkeelle (esim. tilauskoriin).

Tallennus kyllä onnistui eikä mitään virheilmoitusta tullut.

**Comment by AnneliO** [comment]
Hmm.. väärälle sivulle se nyt kyllä minusta ohjautui.

**Comment by ajrajala** [comment]
Omissa testeissäni pysyn aina samalla tilauskori-sivulla kuin mistä lähdin huomautusta muokkaamaan/lisäämään.

**Comment by lasse-koha** [comment]
Kyyti-testillä ainakin staffClientBaseURL on tyhjä, siksi ei toimi oikein. Nyt ilmeisesti siis koodi kunnossa mutta järjestelmäasetukset osassa kimpoista väärin.

**Comment by Kati-Helle** [comment]
> Omissa testeissäni pysyn aina samalla tilauskori-sivulla kuin mistä lähdin huomautusta muokkaamaan/lisäämään.

Helle-testissäkin toimii Annin mainitsemalla tavalla.

**Comment by pknuuti** [comment]
Hyvä huomio, Lasse! Vaaran testillä oli nextin osoite, joten se ei ollut oikein. Kun vaihdoin testin osoitteen tuohon asetukseen

> Kyyti-testillä ainakin staffClientBaseURL on tyhjä, siksi ei toimi oikein. Nyt ilmeisesti siis koodi kunnossa mutta järjestelmäasetukset osassa kimpoista väärin.

Hyvä huomio, Lasse! Vaaran testillä oli nextin osoite, joten se ei ollut oikein. Kun vaihdoin testin osoitteen tuohon asetukseen, se toimii kuten pitääkin eli palaa oikealle sivulle.

**Comment by pirliis** [comment]
> > Omissa testeissäni pysyn aina samalla tilauskori-sivulla kuin mistä lähdin huomautusta muokkaamaan/lisäämään.
> 
> Helle-testissäkin toimii Annin mainitsemalla tavalla.

OUTIssa myös.

**Comment by LeenaKinnunen** [comment]
Lapissa hankinnan testin mukaan ei tullut virheilmoitusta.

**Comment by ajrajala** [comment]
Toimii tuotannossa, suljen tiketin.
