### ISSUE TITLE
Vaara: Niteet eivät ole varattavissa Finnan kautta, vaikka pitäisi olla

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#726]
### Mikä vikana?

Finnan kautta on useita cd-tietueita sellaisessa tilassa, että asiakas ei pysty varaamaan niteitä. Virkailijatyökalussa varaaminen onnistuu ja esimerkkitietueessa ei ole mitään sellaista virhettä näkyvissä, joka estäisi niteiden varaamisen. Tiedossamme on tilanne, jossa kiinteämittaisessa kentässä (000) oleva puutteellinen koodaus aiheuttaa varaamisongelman, mutta tässä tapauksessa koodaus on ihan oikein. 
Kysyin ongelmasta Kansalliskirjastolta ja sieltä tuli vastaus: "Kohan puolella ilmeisesti jotain ongelmaa. Rajapinta palauttaa Internal Server error 500 -virhettä tuon esimerkkikuvan tietueen saatavuustietoja Finnaan haettaessa."
Mistä tämä virheilmoitus johtuu? Ja ennen kaikkea: miten se korjataan?
https://vaara.finna.fi/Record/vaarakirjastot.436085?sid=3075676815

![2023kuvat 123](https://github.com/KohaSuomi/Koha/assets/73887264/bc706fa0-5874-4dbe-80ff-0773e2ff4408)
![2023kuvat 124](https://github.com/KohaSuomi/Koha/assets/73887264/339f771e-f0b6-4a9a-b5bd-6debca3eddef)

**Comment by emta001** [comment]
Testailtiin Larin kanssa, testi-Finnassa varaus onnistuu. Kokeilin myös suoraan selaimessa kutsua tuota saatavuustietoa APIn kautta, se näkyy ok. Voitko Irina katsoa, näkyykö selaimen konsolissa jotain tarkempaa virheilmoitusta?

**Comment by lmstrand** [comment]
Yksittäisen niteen lisätiedot avatessa (keltainen tarkista varaus-nappi jää näkymään toisin kuin testillä, siellä se näkyy hetken ja katoaa) selain herjaa POST
https://vaara.finna.fi/AJAX/JSON?method=checkRequestsAreValid -kutsuun 500-erroria jonka vastauksena "tapahtui virhe".

![image](https://github.com/KohaSuomi/Koha/assets/18394834/007351f5-c840-4673-9c4b-dd2782a3549f)

**Comment by emta001** [comment]
Tässä käy nyt niin, että seuraava laina- ja maksusääntö aiheuttaa Finna-plugarissa virheen "The method Koha::Items->itemlost is not covered by tests!"

```
+-------+------------+--------------+----------+--------------+------------+
| id    | branchcode | categorycode | itemtype | rule_name    | rule_value |
+-------+------------+--------------+----------+--------------+------------+
| 55420 | JOE_OKU    | NULL         | L28RAJ   | onshelfholds | 2          |
+-------+------------+--------------+----------+--------------+------------+
```

Itse sääntö ei ole siis ongelma, vaan se että plugarissa on virhe  "on_shelf_holds_forbidden" metodissa, joka tutkii niteen tilan. Siihen lähetetään nyt jostain syystä Koha::Items tyyppinen objekti, ei yhden niteen sisältävä Koha::Item kuten pitäisi. Tästä olisi luultavasti oltava yhteydessä Finnan päähän (ellei korjaus sitten onnistu meidän päässä ja tehdään sitten pull request Finnaan).

**Comment by pknuuti** [comment]
Todella outoa, miten tuollainen virhe yhtäkkiä on tullut. Koetatteko korjata itse?

**Comment by emta001** [comment]
> Todella outoa, miten tuollainen virhe yhtäkkiä on tullut. Koetatteko korjata itse?

Minusta tämä olisi korjattava Finnan päässä. Miulla ei ole ainakaan äkkiseltään ajatusta miten tuo virhe pääsee syntymään ja kuinka se pitäisi korjata. Ja vaikka saisinkin sen korjattua, voi olla että jotain muuta menee siinä ohessa rikki. 

Irina tai Päivi, jos olisitte vielä yhteydessä Finnaan. Eiköhän siellä saada noilla meidän löytämillä tiedoilla selvitettyä missä vika on. Tässä vielä tuo virheviesti kokonaisuudessaan:

> [2023/08/23 06:30:50] [ERROR] The method Koha::Items->itemlost is not covered by tests!
> 
> Trace begun at /home/koha/Koha/Koha/Objects.pm line 572
> Koha::Objects::AUTOLOAD('Koha::Items=HASH(0x561112a4b9a8)') called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/Koha/Availability/Checks/CirculationRule.pm line 242
> Koha::Plugin::Fi::KohaSuomi::DI::Koha::Availability::Checks::CirculationRule::on_shelf_holds_forbidden('Koha::Plugin::Fi::KohaSuomi::DI::Koha::Availability::Checks::CirculationRule=HASH(0x5611133f5d68)') called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/Koha/Item/Availability/Hold.pm line 206
> Koha::Plugin::Fi::KohaSuomi::DI::Koha::Item::Availability::Hold::common_issuing_rule_checks('Koha::Plugin::Fi::KohaSuomi::DI::Koha::Item::Availability::Hold=HASH(0x56110ee91898)', 'HASH(0x56110ee903c8)') called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/Koha/Biblio/Availability/Hold.pm line 227
> Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold::_item_check('Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold=HASH(0x56110ee455e0)', 'Koha::Item=HASH(0x56110ecc8210)', 'Koha::Patron=HASH(0x56110ee982f0)', 'ARRAY(0x561108fa5480)', 'ARRAY(0x5611086b4670)') called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/Koha/Biblio/Availability/Hold.pm line 184
> Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold::_item_looper('Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold=HASH(0x56110ee455e0)', undef) called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/Koha/Biblio/Availability/Hold.pm line 108
> Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold::in_opac('Koha::Plugin::Fi::KohaSuomi::DI::Koha::Biblio::Availability::Hold=HASH(0x56110ee455e0)') called at /var/lib/koha/plugins/Koha/Plugin/Fi/KohaSuomi/DI/AvailabilityController.pm line 115
> Koha::Plugin::Fi::KohaSuomi::DI::AvailabilityController::biblio_hold('Koha::Plugin::Fi::KohaSuomi::DI::AvailabilityController=HASH(0x561112a53668)') called at /usr/local/share/perl/5.30.0/Mojolicious.pm line 190

**Comment by pknuuti** [comment]
Ok, mä laitan Finnaan viestiä.

**Comment by lmstrand** [comment]
Lisätty commit NatLibFi:n repositoriosta https://github.com/KohaSuomi/koha-plugin-rest-di/commit/64a16b96fb0be66de7f380db625a1e6fb6f06f2b 22.xx-haaraan ja testattu Vaaran testi-Finnassa toimivaksi ratkaisuksi ja varaaminen onnistuu.

Viedään tuotantoon ensi tiistaina.

**Comment by IrinaHalminen** [comment]
Nyt varaaminen onnistuu useammissa niteissä kuin aiemmin, mutta kaikissa tietueissa ei varaaminen ole silti mahdollista. Ongelma on sama eli varausnappi katoaa ja osan niteitten kohdalla vilahtaa Tarkista varaus -nappi hetkellisesti. Tässä muutamia esimerkkejä tietueista, joissa varaaminen ei edelleenkään toimi:

https://vaara.finna.fi/Record/vaarakirjastot.11486908?sid=3091433508 (äänikirja)
https://vaara.finna.fi/Record/vaarakirjastot.425594?sid=3076974453 (CD:itä tästä alaspäin)
https://vaara.finna.fi/Record/vaarakirjastot.11520393?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.450380?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.11701274?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.11691074?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.11699822?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.439261?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.173392?sid=3091430319
https://vaara.finna.fi/Record/vaarakirjastot.451145?sid=3091698324

**Comment by emta001** [comment]
Meidän lokit on tosiaan Larin ja miun testailujen perusteella tyhjät. Osaisivatkohan Finnassa sanoa, mitä heidän päässä näkyy noiden osalta?

**Comment by AnneliO** [comment]
Sekä Vaarassa että OUTIssa näkyy Finnassa selaimen konsolissa tällainen css-virhe:

Source map error: Error: request failed with status 404
Resource URL: https://outi.finna.fi/cache/eb84d15a3d75953bff61279f9eb3fe47.min.css
Source Map URL: L.Control.Locate.min.css.map

Source map error: Error: request failed with status 404
Resource URL: https://vaara.finna.fi/cache/f37059761fa826ef79ad16a51ecc259f.min.css
Source Map URL: L.Control.Locate.min.css.map

OUTIssa näkyy konsolissa (joissain) tietueen tiedoissa jokin kovin punainen virheilmoitus. Esim:

https://outi.finna.fi/Record/outi.1049509?sid=3091799814

En tiedä, liittyvätkö aiheeseen mitenkään.

**Comment by pknuuti** [comment]
Laitoin nuo esimerkit Erelle Kansalliskirjastoon.

**Comment by emta001** [comment]
> Sekä Vaarassa että OUTIssa näkyy Finnassa selaimen konsolissa tällainen css-virhe:
> 
> Source map error: Error: request failed with status 404 Resource URL: https://outi.finna.fi/cache/eb84d15a3d75953bff61279f9eb3fe47.min.css Source Map URL: L.Control.Locate.min.css.map
> 
> Source map error: Error: request failed with status 404 Resource URL: https://vaara.finna.fi/cache/f37059761fa826ef79ad16a51ecc259f.min.css Source Map URL: L.Control.Locate.min.css.map
> 
> OUTIssa näkyy konsolissa (joissain) tietueen tiedoissa jokin kovin punainen virheilmoitus. Esim:
> 
> https://outi.finna.fi/Record/outi.1049509?sid=3091799814
> 
> En tiedä, liittyvätkö aiheeseen mitenkään.

Hmm, en kyllä ite saa minkäänlaista virhettä konsoliin aikaseks :thinking:

**Comment by IrinaHalminen** [comment]
Mulla näkyy sama virhe kuin Annelilla, kun olen sisäänkirjautuneena ja katselen noita viallisia tietueita.

**Comment by emta001** [comment]
> Mulla näkyy sama virhe kuin Annelilla, kun olen sisäänkirjautuneena ja katselen noita viallisia tietueita.

Siijnä varmaan vika, en oo kirjautunut sisään :D

**Comment by AnneliO** [comment]
Mie sain ainakin nuo source map -virheet ilman kirjautumistakin.

**Comment by IrinaHalminen** [comment]
Joo, testattu ja virheet tulevat mullekin ilman kirjautumista näkyville.

**Comment by emta001** [comment]
Onko tästä kuulunut mitään uutta?

**Comment by pknuuti** [comment]
Ei ole kuulunut. Juuri testailin ja edelleen löytyy sellaisia nimekkeitä, joita ei pysty varaamaan enkä keksi syytä, miksi ei pysty.
Esim. https://vaara.finna.fi/Record/vaarakirjastot.425594?sid=3206264904
https://vaara.finna.fi/Record/vaarakirjastot.449696?sid=3206264904
https://vaara.finna.fi/Record/vaarakirjastot.327310?sid=3206264904
Pitänee laittaa uutta viestiä Finna-postiin.

**Comment by pknuuti** [comment]
Nyt on ongelma ratkaistu. Joensuun seutukirjaston laina- ja maksusääntöihin oli tullut jossain vaiheessa virhe tietyn nidetyypin kohdalle hyllyvaraussääntöön ja se aiheutti tämän ongelman. Ongelma ei kohdistunut muihin Vaara-kirjastoihin, niiden säännöt olivat oikein. Suljen tiketin.
