### ISSUE TITLE
Tiedonhaku ei löydä tietuetta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#727]
### Mikä vikana?

Vaskissa on ilmennyt ongelmia tiedonhaun kanssa. Aiemmin tällä viikolla käyttäjä raportoi isbn-hauista, joilla ei löytynyt hakutuloksia vaikka tietueet olivat olemassa. Ongelma oli korjaantunut eilen, mutta tänään käyttäjä oli saanut tilanteen uudelleen toistettua. Kyseessä [tämä tietue](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2810610), jota haku ei siis löydä esim. nimellä, isbn-numerolla tai vaikka tietueen niteen nidetunnuksella.

Kyseessä ei ole mikään uusi tietue, joten kyse ei ehkä ole siitäkään ettei hakuindeksi ole päivittynyt vaan hakuindeksiin olisi ennemmin tullut reikiä. :D

### Kuinka toistaa ongelma/asia

Esimerkikkitietueen kanssa ongelman saa toistettua yrittämällä hakea tietuetta Vaskin tuotannossa vaikkapa isbn:llä 9789525960211.

**Comment by emta001** [comment]
Luultavasti tietueen kuvailussa on jotain vialla. Selvittelemme asiaa.

**Comment by ajrajala** [comment]
Siltä varalta, että sittenkin liittyisi tähän, niin Vaskin tuotannossa Tietoja Kohasta > Järjestelmätiedot -sivulla varoitetaan tällä hetkellä indeksoitumattomista tietueista: _3904 tietue(tta) puuttuu tietueiden kokonaismäärästä: 2480749 indeksissä vaski-test_biblios._ Pisti myös silmään, että varoituksessa puhutaan indeksistä vaski-test, mutta onko indeksi vaan jäänyt sen nimiseksi?

**Comment by emta001** [comment]
> Siltä varalta, että sittenkin liittyisi tähän, niin Vaskin tuotannossa Tietoja Kohasta > Järjestelmätiedot -sivulla varoitetaan tällä hetkellä indeksoitumattomista tietueista: _3904 tietue(tta) puuttuu tietueiden kokonaismäärästä: 2480749 indeksissä vaski-test_biblios._ Pisti myös silmään, että varoituksessa puhutaan indeksistä vaski-test, mutta onko indeksi vaan jäänyt sen nimiseksi?

Kappas, niinpä näkyy jääneen tuon nimiseksi :D Pitänee selkeyden vuoksi korjata tuo jossain vaiheessa. 

Mutta noissa puuttuvissa tietueissa lienee sama ongelma kuin tässä tiketissä mainitussa tietueessa, jotain niissä on vialla, eivätkä ne siksi indeksoidu. Senkun vielä tietäs mikä :D

**Comment by AnneliO** [comment]
Indeksoituuko tietue, jos sen tallentaa uudelleen ilman mitään muutoksia?

**Comment by ajrajala** [comment]
Joo, näyttäisi indeksoituneen. Kuulin myös, että kuvailijat olivat viime viikolla törmänneet tapauksiin, joissa edellisen päivän niteetön tietue ei löytynyt. Kuitenkin myöhemmin tietueet löytyivät eikä meille Vaskitukeen siksi näistä oltu laitettu esimerkkejä. Mietin, että noissakin tapauksissa tietueen uudelleen tallentaminen (tai niteiden lisääminen?) on ehkä voinut laittaa tietueet indeksoitumaan.

**Comment by AnneliO** [comment]
Niteen lisäminen aiheuttaa uudelleenindeksoitumisen, joten se on voinut vaikuttaa. Eli vaikuttaisi siltä, että itse tietueessa ei todennäköisesti ole mitään vikaa, koska se indeksoituu oikein toisella yrittämällä.

**Comment by emta001** [comment]
Jännää, kokeiltiin viime viikolla indeksoida käsin tuo tietue, eikä sillä ollut vaikutusta. Nyt se näköjään löytyy ongelmitta.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 21.8.2023: Kokeillaan koko tietokannan uudelleenindeksointia, auttaisiko se.

Sitä ennen Emmi kokeilee käsin indeksoida yhden tietueen. Löytyiskö teiltä sopivaa indeksoitumatonta tietuetta?

**Comment by ajrajala** [comment]
En ole muita esimerkkejä saanut, mutta voin kysellä vaikka vielä kuvailijoilta josko heille olis tullut lisää tapauksia vastaan.

**Comment by emta001** [comment]
Sovittiin pääkäyttäjäpalaverissa, että ajetaan uudelleenindeksointi ja toivotaan siitä olevan apua. Jos ongelma jatkuu, tutkitaan sitten uudestaan.

**Comment by emta001** [comment]
Uudelleenindeksoinnista ei näyttäisi olleen mitään apua, nyt "Tietoja Kohasta" sivulla on seuraava ilmoitus:

`9804 record(s) missing on a total of 2475163 in index vaski-test_biblios.`

**Comment by emta001** [comment]
> Uudelleenindeksoinnista ei näyttäisi olleen mitään apua, nyt "Tietoja Kohasta" sivulla on seuraava ilmoitus:
> 
> `9804 record(s) missing on a total of 2475163 in index vaski-test_biblios.`

Olinkin liian hätäinen tämän kanssa, tarkistin tuon herjan noin klo 8.30, mutta ajo olikin valmistunut vasta 8.33 :D Nyt ei näy enää valitusta. Tiketin voinee sulkea tältä erää ja palata asiaan, jos ongelma toistuu.

**Comment by ajrajala** [comment]
No hyvä, että korjaantui! Toivotaan, ettei ongelma uusiudu, mutta meillä on tapana tsekata nuo järjestelmän virheilmoitukset viikottain niin tulee viimeistään sitä kautta sitten esille jos alkaa taas olla indeksoitumattomia tietueita.
