### ISSUE TITLE
Internal Server Error valutuksessa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#728]
### Mikä vikana?

Ainakin OUTIssa, Lumpeissa, Kyytissä ja Hellessä on ollut kolmisen päivää aamulla klo 6 jälkeen paljon Internal Server Erroriin päättyneitä tietueiden valutuksia.

Tänään virheitä on ollut enimmäkseen OUTIssa, mutta näytti olevan pari Kyytissäkin. Tässä OUTIn aamun ensimmäinen epäonnistunut:

OUTI | 18.8.2023 6:06:03 | update | 2315468 |  Internal Server Error

**Comment by emta001** [comment]
Kodo sulki perjantaina nextit, koska epäili file handlejen loppuvan (saa korjata jos muistan tämän väärin :D). Tänään "Internal Server" virheitä ei näytä syntyneen.

**Comment by emta001** [comment]
Kokeillaan lähettää uudelleen nuo viime viikon epäonnistuneet valutukset laittamalla niiden tilaksi "pending". Ihan täyttä varmuutta ei ole mitä hassuuksia tästä seuraa, mutta tuskin tilanne yhtään pahenee.

**Comment by AnttHeik** [comment]
Kävi ainakin niin, että nyt on monella osakohteellisella tietueella tuplamäärä osakohteita tai melkein tupla. Pitää poistella noita ylimääräisiä.

**Comment by emta001** [comment]
> Kävi ainakin niin, että nyt on monella osakohteellisella tietueella tuplamäärä osakohteita tai melkein tupla. Pitää poistella noita ylimääräisiä.

Mietinkin ton ylemmän kommentin postaamisen jälkeen, että olin varmaan turhan optimistinen. Pahoittelut. 

Mutta siis, eivätkö kaikki tulleet tuplana? Osa vain? Liittyisikö siihen, että OUTIssa on ilmeisesti tuotu jo käsin joitakin tietueita?

**Comment by janPasi** [comment]
Edustapalvelimille on tehty ongelman (toivottavasti) korjaava asetusmuutos, joka kuitenkin saadaan voimaan vasta seuraavassa huoltoikkunassa. Siihen asti yritetään pärjäillä ilman Nextejä.

**Comment by AnttHeik** [comment]
> Mietinkin ton ylemmän kommentin postaamisen jälkeen, että olin varmaan turhan optimistinen. Pahoittelut.
> 
> Mutta siis, eivätkö kaikki tulleet tuplana? Osa vain? Liittyisikö siihen, että OUTIssa on ilmeisesti tuotu jo käsin joitakin tietueita?

Juu, eipä siinä mitään, tietääpähän taas jatkossa enemmän, mitä voi sattua :)

Ei ehkä ihan kaikki tulleet tuplana. Toisaalta noita osakohteita oli niin paljon, että välttämättä en löytänyt kaikkia viallisia. Enkä enää muista kaikki käsiteltyjä aineistoja viime viikolta. Kaikki löytämäni tietueet olivat niitä, jotka oli poimittu viime viikolla jo käsin. Nyt oli sitten ilmeisesti käynyt niin, että ensin osakohteet tulivat uusina ja heti sen jälkeen osaan tuli vielä muokkaus. En sitten tiedä, miten ne onnistuivat vielä tuplaantumaan.

**Comment by AnneliO** [comment]
Suljen tiketin tältä erää. Avataan uudelleen tarvittaessa.

**Comment by piiaseme** [comment]
OUTIssa tämän aamun valutuksessa on epäonnistunut useampi tietue klo 6.06.07 – 6.07.14 Internal server erroriin. Avaan tiketin.

**Comment by piiaseme** [comment]
Tässä OUTIn aamun ensimmäinen epäonnistunut: 
OUTI | 26.9.2023 6:06:07 | update | 2320383 | Open | Internal Server Error

**Comment by piiaseme** [comment]
OUTIssa myös tänään aamun valutuksessa epäonnistunut moni tietue. Vain pieni määrä tietueita oli valunut.
Tässä aamun ensimmäinen Internal server error-tapahtuma:
27.9.2023 6:06:05 | Muokkaus | 2317384 | 2393978 | Internal Server Error

**Comment by AnttHeik** [comment]
Tänään oli noiden Kirjastopalvelun kaikkien tietueiden lisäksi kolme epäonnistunutta Melinda-valutustakin vielä 6.32.04 eteenpäin.

**Comment by johannaraisa** [comment]
Näyttää siltä, että vika johtuu Elasticista. OUTIn lokissa on paljon "Unable to perform your search. Please try again." virheitä. Tietueelle yritetään aina etsiä emoa, joten jos Elasticiin ei saa yhteyttä niiin aivan varmasti OUTIn rajapinta antaa "Internal Server Error"-virheen.

**Comment by johannaraisa** [comment]
Tänään ei ole tainnut tulla yhtään virhettä, ei näkynyt ainakaan lokeissa. Tosiaan Elastic on ollut kuuden jälkeen tavoittamattomissa ja siksi haut eivät tietenkään mene läpi. Muutin Tätin päässä valutusta niin, että se alkaa tarkastella tietueita vasta seitsemältä.

**Comment by AnttHeik** [comment]
Joo, tänään on tullut kaikki läpi, eilenkin oli vain kaksi tietuetta. Eihän tuolloin klo 7 ole Kohassa mitään muita ajoja päällä, koska jostakin syystä valutusaikaa vaihdettiin lomasi aikana klo 7:stä klo 6:teen, mutta en nyt tietenkään löydä enää syytä, että miksi? Muistaako @emta001 ?

**Comment by emta001** [comment]
> Joo, tänään on tullut kaikki läpi, eilenkin oli vain kaksi tietuetta. Eihän tuolloin klo 7 ole Kohassa mitään muita ajoja päällä, koska jostakin syystä valutusaikaa vaihdettiin lomasi aikana klo 7:stä klo 6:teen, mutta en nyt tietenkään löydä enää syytä, että miksi? Muistaako @emta001 ?

Muisteltiin ihan joukolla, että syynä oli huoltokatko. Mutta sen kanssa ei pitäisi tulla ongelmia, koska sen aikana kaikki cronit ovat pois päältä. Joten valutus voi olla hyvin päällä vasta 7 aikaan.

**Comment by AnttHeik** [comment]
> Muisteltiin ihan joukolla, että syynä oli huoltokatko. Mutta sen kanssa ei pitäisi tulla ongelmia, koska sen aikana kaikki cronit ovat pois päältä. Joten valutus voi olla hyvin päällä vasta 7 aikaan.

Aivan, niinhän se olikin. Kiitos tiedosta, pitää seurata tätä sitten seuraavan huoltokatkon aikoihin.

**Comment by AnttHeik** [comment]
Tänä aamuna 4.10. oli OUTIssa kaksi Melindasta tullutta virheellistä klo 7:00:25 alkaen  ja Kirjastopalvelun paketista 5 epäonnistunuttta. Niistä eka 7:02, mutta muut on sitten putoilleet välistä.

**Comment by johannaraisa** [comment]
Voikohan tämän jo sulkea, valutus on vaihtunut Tietuesiirtäjään?

**Comment by piiaseme** [comment]
Suljen tiketin.
