### ISSUE TITLE
Finna-näkymä ei saa haravoitua aineistoa test-kannasta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#730]
### Mikä vikana?

Vaski-test kantaan liitetyn Finna-näkymän haravointi on jossain vaiheessa keskeytynyt eikä Kansalliskirjasto saa haravointia takaisin päälle, koska haravointirajapinnasta tulee vastauksena 404 Not Found -virheilmoitus. Finna-toimiston mukaan ongelma olisi Kohan päässä.

Anneli lupasi vielä testata outi-testillä haravoitumista, joten tässä kohtaa ei vielä tietoa onko ongelma pelkästään vaski-testillä vai muillakin test-kannoilla.

**Comment by AnneliO** [comment]
[Lisäsin yhden tietueen](https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2261865) outi-testille ja lisäksi muokkasin yhtä jo [olemassa olevaa tietuetta](https://outi-test.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=900039). Odottelin haravointia tunteroisen, mutta kumpikaan muutos ei tullut näkyville testi-Finnaan. [Muokatun tietueen](https://outi.finna-pre.fi/kohatest/Record/outi_kohatest.900039?sid=226434750#details) viimeisin indeksointi on tehty 23.3.2023. Eli ei näyttäisi toimivan myöskään outin testillä haravointi.

**Comment by janPasi** [comment]
OAI on siirretty meillä OPAC:ista staff clientin puolelle ja testiltä puuttui tarvittava linkki. Nyt korjattu.

**Comment by ajrajala** [comment]
Voin tekemääni Finna-tikettiin päivittää tilanteen ja pyytää käynnistämään haravoinnin nyt uudelleen. Kysyn samalla, voivatko pistää haravoinnin käyntiin myös [muihin testi-Finnoihin](https://github.com/KohaSuomi/Koha/wiki/Testi-Kohien-testi-Finnat) vai pitääkö kimppojen pyytää sitä erikseen Finna-toimistolta.

**Comment by ajrajala** [comment]
Kansalliskirjasto on laittanut haravoinnin päälle Vaskille ja muille [testi-Finnoille](https://github.com/KohaSuomi/Koha/wiki/Testi-Kohien-testi-Finnat). Tsekkasin meidän testiltä niin sieltä näytti nyt haku löytävän lisäämäni tietueen.
