### ISSUE TITLE
Puhelinnumeron tarkistavan js-rimpsun päivitys

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#732]
### Tukipyyntö

Puhelinnumeron tarkistavaan js-rimpsuun pitää tehdä pieni päivitys, jotta asiakkaan lisäys/muokkaussivulla Tallenna-nappi näkyisi keltaisena, kuten pitää.

Oikea muoto on tässä:
```
$('#pat_memberentrygen #saverecord').replaceWith('<button class="btn btn-primary" id="modified_saverecord"><i class="fa fa-save"></i> '+save_text+'</button>');
```

Koska kyseessä on JS, pääkäyttäjät eivät voi tehdä muutosta itse. Pääkäyttäjät, laittakaa tähän tikettiin kommentti, jos teillä on väärän värinen nappula asiakkaan lisäyksessä/muokkauksessa, niin päivystäjä voi käydä muokkaamassa rimpsun oikeanlaiseksi.

**Comment by pknuuti** [comment]
Vaarassa on väärä väri eli muokata pitää.

**Comment by Tuomas-Kyyti** [comment]
Kyytissä myös korjattava.

**Comment by pirliis** [comment]
OUTI:ssa myös korjattava.

**Comment by lasse-koha** [comment]
Vaara, Kyyti ja OUTI korjattu.

**Comment by Kati-Helle** [comment]
Myös Hellessä tarve värinvaihdolle.

**Comment by lasse-koha** [comment]
Helle korjattu.

**Comment by ReettaSiili** [comment]
Siilissäkin pitäisi korjata.

**Comment by lasse-koha** [comment]
Siili korjattu.

**Comment by PiaKusmin** [comment]
Lappiinkin pitäisi korjata.

**Comment by lasse-koha** [comment]
Lappi korjattu.

**Comment by Hanna-Lumme** [comment]
Lumpeissa on myös harmaa namiska.

**Comment by lasse-koha** [comment]
Lumme korjattu.

**Comment by MikkoLiimatainen** [comment]
Vaskissa tämä on ok. Taisin tehdä tämän muutoksen jo versionvaihdon aikaan.

**Comment by ElinaUotila** [comment]
Kirkesiin pitäisi vielä korjata.

**Comment by lasse-koha** [comment]
Kirkes korjattu.

**Comment by AnneliO** [comment]
Kaikilla ok, joten suljen tiketin. Kiitos! :)
