### ISSUE TITLE
Uutta käyttäjätunnusta tehdessä virheilmoitus palauttaa kirjastovalinnan oletukseksi

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#736]
### Mikä vikana?

Kun tekee uutta asiakastunnusta, joka on riittävän samanlainen jo olemassa olevan tunnuksen kanssa, Koha pyytää varmistamaan, että ei ole tekemässä tuplatietuetta (Kopioi asiakastiedot-kysymys). Tuo kysely palauttaa kirjastovalinnan oletusvalinnaksi (oletusvalinta näkyy lomakkeella jo kun kysymys esitetään). Jos on tekemässä uutta tunnusta, tulee helposti tallennettua tunnus väärään kirjastovalintaan. 

![image](https://github.com/KohaSuomi/Koha/assets/99008412/0867bb20-5cc3-43a8-b7b8-92e9443cb2dc)

### Mitä pitäisi tapahtua

Jo valittu kirjastovalinta pitäisi säilyä tuplatietuekysymyksestä huolimatta.

**Comment by sksandel** [comment]
Kyllä, sama ongelma on kyseessä.

**Comment by emta001** [comment]
Tässä on hieman mutkia matkassa. Olemassa olevaa branchcodea käytetään jos seuraava ehto täyttyy:

```
if (defined ($data{'branchcode'}) and ( $op eq 'modify' || $op eq 'duplicate' || ( $op eq 'add' && $category->category_type eq 'C' ) )) {
    $userbranch = $data{'branchcode'};
}
```

Eli  $data{'branchcode'} muuttujan on oltava olemassa ja muuttujan $op on oltava joko "modify", "duplicate" tai "add". Ja jos se on "add", niin käyttäjän categorytypen on oltava "C" (lapsi). Kysäisin, että miksi näin on ja eikö riittäisi, että jos  $data{'branchcode'} on olemassa. Mutta siihen asti kunnes tuo selviää, niin tälle ei oikein uskalla tehdä mitään, ettei mikään mene rikki.

**Comment by emta001** [comment]
> Tässä on hieman mutkia matkassa. Olemassa olevaa branchcodea käytetään jos seuraava ehto täyttyy:
> 
> ```
> if (defined ($data{'branchcode'}) and ( $op eq 'modify' || $op eq 'duplicate' || ( $op eq 'add' && $category->category_type eq 'C' ) )) {
>     $userbranch = $data{'branchcode'};
> }
> ```
> 
> Eli $data{'branchcode'} muuttujan on oltava olemassa ja muuttujan $op on oltava joko "modify", "duplicate" tai "add". Ja jos se on "add", niin käyttäjän categorytypen on oltava "C" (lapsi). Kysäisin, että miksi näin on ja eikö riittäisi, että jos $data{'branchcode'} on olemassa. Mutta siihen asti kunnes tuo selviää, niin tälle ei oikein uskalla tehdä mitään, ettei mikään mene rikki.

Tein tämän korjauksesta ehdotuksen yhteisöön. Nähdäkseni tuon ehdon, että käyttäjän asiakastyypin/lajin/kategorian on oltava C, poistaminen ei vaikuta oleellisesti mihinkään. Sen on kai aikoinaan ollut tarkoitus varmistaa, että taattavalle tulee sama kirjasto kuin takaajalle, mutta miun testien perusteella ei tuo enää toimi. Pitänee keskustella siitä, tuodaanko tää meillekin vai odotellaanko sitä, että yhteisöstä tulee kommenttia tms.

**Comment by AnneliO** [comment]
Tuotu testeille, testattava.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä. Olin Joensuun pääkirjastoon kirjautuneena. Tein asiakkaan Ilomantsin kirjastoon ja valitsin alle 15-vuotiaalle (jonka pitäisi olla Vaarassa lapsiasiakas) henkilöasiakkaan pohjan eli väärän pohjan ja tallennuksessa siitä tuli tietenkin virheilmoitus. Kun sitten katsoin tämän uuden asiakkaan kotikirjastoa, se oli muuttunut Joensuun pääkirjastoksi, vaikka piti olla Ilomantsi. Eikö tämänkin kirjastovalinnan pitäisi pysyä alkuperäisenä valintana eikä muuttua virhetilanteessa?

**Comment by emta001** [comment]
> Testasin Vaaran testillä. Olin Joensuun pääkirjastoon kirjautuneena. Tein asiakkaan Ilomantsin kirjastoon ja valitsin alle 15-vuotiaalle (jonka pitäisi olla Vaarassa lapsiasiakas) henkilöasiakkaan pohjan eli väärän pohjan ja tallennuksessa siitä tuli tietenkin virheilmoitus. Kun sitten katsoin tämän uuden asiakkaan kotikirjastoa, se oli muuttunut Joensuun pääkirjastoksi, vaikka piti olla Ilomantsi. Eikö tämänkin kirjastovalinnan pitäisi pysyä alkuperäisenä valintana eikä muuttua virhetilanteessa?

Pitäisi, tuossa korjauksessa on siis jotain pielessä.

**Comment by emta001** [comment]
Olin vahingossa laittanut yhteen ehtolauseeseen väärät arvot. Nyt korjattu, pitäs toimia.

**Comment by pknuuti** [comment]
Ei toimi oikein, toimii ihan samalla tavalla kuin tuossa edellisessä testauksessani.

**Comment by emta001** [comment]
> Ei toimi oikein, toimii ihan samalla tavalla kuin tuossa edellisessä testauksessani.

Se korjaus oli jostain syystä tipahtanut testeiltä, mutta on nyt paikallaan. Testasin vaara-testillä ja vaikuttaisi toimivan.

**Comment by pknuuti** [comment]
Ou jee, nyt toimii :)

**Comment by sksandel** [comment]
Vaskin testitulos: Toimii. Kirjastovalinta pysyy vaikka tulisi kopioi asiakastiedot-kysymys.

**Comment by emta001** [comment]
Hieno homma! Voidaan laittaa tämä vaikka ensi viikon päivityksessä mukaan.
