### ISSUE TITLE
Lumme: lainausautomaatit tekevät turhia PIN-kyselyjä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#737]
### Mikä vikana?

Lumpeissa Mikkelin uudet automaatit tekevät turhia PIN-koodikyselyjä, jotka merkkaantuvat lokeihin epäonnistuneiksi kirjautumisyrityksiksi. Tämä kasvattaa asiakkaiden väärien kirjautumisyritysten määrää, jolloin tili nasahtaa lukkoon. Lysyltä ollaan asiaa tiedusteltu ja heidän päässään kaikki toimii niin kuin pitää. Tarkentavia tietoja on pyydetty, josko ne auttaisivat ongelman selvittämisessä. Kaikki neljä automaattia tekevät tätä samaa.

### Mitä pitäisi tapahtua

Automaattien ei pitäisi lähettää Kohaan PIN-koodikyselyjä.

**Comment by lmstrand** [comment]
Kyseisille automaattitunnuksille lisätty määritys allow_empty_passwords="1" SIP-palvelinkonfiguraatioon. Voimassa huomisesta lähtien.

**Comment by lmstrand** [comment]
Automaatit pitäisi vielä konfiguroida niin, etteivät ne lähetä pin-koodia Kohan sip-palvelimelle, jos noita epäonnistuneita kirjautumisyrityksiä edelleen syntyy.

**Comment by Hanna-Lumme** [comment]
On nyt testailtu automaateilla, tuleeko lisäkyselyjä ja näyttäisi olevan kaikki kunnossa. Suljen tiketin, mutta seuraillaan vielä tilannetta.
