### ISSUE TITLE
Epäonnistuneet Niteiden poisto eräajona -ajot

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#738]
### Mikä vikana?

OUTIssa on paljon epäonnistuneita Niteiden poisto eräajona -ajoja. Ensimmäiset viime vuoden kesäkuulta (8.6.2022) ja viimeisimmät nyt tältä päivältä (25.8.2023). Tällä hetkellä 765 epäonnistunutta ajoa.

Pystyykö näitä jollain ajolla tarkistamaan, ovatko niteet jääneet roikkumaan tietokantaan, eivätkä ole poistuneet? Ja jos eivät ole poistuneet, voisiko ne poistaa myös ajona?

Saimme palautetta, että poistoja jää roikkumaan ja kirjastot joutuvat tekemään poistokäsittelyjä useampaan kertaan samoista niteistä. 

Tänään tulleessa palautteessa kirjastossa oli taas toistamiseen poistettu samoja niteitä, mutta näiden kolmen niteen kohdalla tulee virhe 500:
748N00657950 (itemnumber=2890816)
748N00301678 (itemnumber=1305748)
748N00232861 (itemnumber=1102487)

**Comment by pirliis** [comment]
Kaikki kolme poistettavaa nidettä antavat vielä virhettä 500.

**Comment by AnneliO** [comment]
Kaikki kolme nidettä on [KOMPPALINNA-siirtokokoelmassa](https://outi.koha-suomi.fi/cgi-bin/koha/rotating_collections/addItems.pl?colId=56) ja se estää nyt poistamisen.

Tietokantaan on jäänyt meidän vanhasta versiosta riippuvuus, joka estää poistamisen. Tämä riippuvuus poistetaan tietokannasta, jonka jälkeen vastaavaa ongelmaa ei pitäisi enää tulla.

Tällä hetkellä ongelman voi kiertää poistamalla niteet ensin kokoelmasta.

**Comment by AnneliO** [comment]
Elekää muuten ihan vielä koittako poistaa, teemme juttuja sitä ennen. :D

**Comment by AnneliO** [comment]
Lisäsin OUTIin raportin 644 ja siihen seuraavan kyselyn:

```
select id,status,size,type,enqueued_on,started_on,ended_on,data,context from background_jobs where status='failed' and id=<<Työn id>>
```

Anna raportille taustatyöt-sivulta löytyvä ID-numero ja aja raportti. data-sarakkeesta näkee, mitä tietueita ajo on koskenut. Jos kyseessä on tietueisiin liittyvä ajo, ovat numerot biblionumbereita. Jos taas kyseessä on niteisiin kohdistuva ajo, ovat numerot itemnumbereita. Helpoiten tietueet löytää hakemalla biblionumerilla/itemnumberilla perushaussa.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 31.8.2023: Niteiden poistoa voisi nyt yrittää uudelleen niin, että ne ovat vielä siirtokoelmassa.

**Comment by pirliis** [comment]
> Koha-Suomen palaveri 31.8.2023: Niteiden poistoa voisi nyt yrittää uudelleen niin, että ne ovat vielä siirtokoelmassa.

Kirjastossa olivat poistaneet nyt niteet onnistuneesti.

**Comment by pirliis** [comment]
Tsekkailin epäonnistuneita poistoajoja raportilla. Paljon oli Siikajoen poistoja. Suurin osa on varmaan lopulta jossain vaiheessa poistuneet tietokannasta, mutta kun tein otantaa, niteitä löytyi vielä kannasta. Tässä esimerkkejä etäajoista, joista niitä ainakin löytyi:

Työn id 2449334: 
748N00348587, 1343646
748N00640119, 2307867
748N00417837, 1445165

Työn id 2452152:
748N00149179, 963941

Työn id 2447398:
748N00274326, 1146698

Työn id 3108431:
748N00779136, 3202792
748N00663939, 2917119
748N00675364, 3071776
748N00679007, 3113471
748N00703531, 3132301
748N00708668, 3151595
748N00709090, 3150212

Työn id 2863190:
0725287015810010, 166198

Työn id 2862965:
748N00173310, 1025831

Työn id 169/191:
Näyttäisi, että onkohan kaikki Hailuodon ajon poistettavat niteet vielä tietokannassa? En käynyt niitä kaikkia läpi, kun ajossa 126 nidettä.

**Comment by AnneliO** [comment]
Jos koitat poistaa eräajona vaikka tuon erän 2449334 jäljellä olevat niteet, niin poistuvatko ne nyt? Vai epäonnistuuko poisto edelleen? Tuossa ois potentiaalisesti taas ehdokkaita löytää lisää poiston estäviä virheitä.

**Comment by pirliis** [comment]
Kaikki erän kolme nidettä poistuivat ongelmitta.

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 5.9.2023: Laitetaan failed-tilassa olevat niteiden eräpoistot uudelleen pending-tilaan ja katsotaan, poistuuko niteet.

**Comment by pirliis** [comment]
Ehtisikö joku laittaa OUTIn epäonnistuneet Niteiden poisto eräajona -ajot (557 ajoa) uudelleen pending-tilaan, kuten olemme sopineet 5.9. pääkäyttäjäpalaverissa. Nähdään, poistuuko niteet, jotka siellä vielä roikkuvat.

**Comment by lmstrand** [comment]
Ajettu:

MariaDB [outiprod]> update background_jobs set status = 'pending' where status = 'failed' and type = 'batch_item_record_deletion';
Query OK, 557 rows affected (0.037 sec)
Rows matched: 557  Changed: 557  Warnings: 0

**Comment by lmstrand** [comment]
Tuo pending taisi olla väärä status, vaihdoin newiksi:

MariaDB [outiprod]> update background_jobs set status = 'new' where status = 'pending' and type = 'batch_item_record_deletion';
Query OK, 557 rows affected (0.029 sec)
Rows matched: 557  Changed: 557  Warnings: 0

**Comment by AnneliO** [comment]
Taustatyö näyttäisi käyneen kaikki läpi ja vain yksi meni failed-tilaan. Useammassa työssä on nyt poistettu joko kaikki tai osa.

Tuo yksi failed-tilainen työ oli sellainen, jossa sama nide oli mukana kolmessa eri taustatyössä ja kaksi niistä oli ajossa yhtä aikaa. Todennäköisesti se nyt aiheutti yhden epäonnistumisen. Töihin liittyvä nide 3366401 ja tietue 2243042 ovat kuitenkin poistuneet.

Eli sanoisin, että kokeilu oli onnistunut. :)

**Comment by pirliis** [comment]
Huippua, saatiin siivottua noi pois. :)

Nyt kun hakee ainokaisen epäonnistuneen ajon tietuetta tietuenumerolla 2243042, tulee ilmoitus: 
![image](https://github.com/KohaSuomi/Koha/assets/98814860/75acd699-5eb5-421a-9972-c574977f4da9)

Mutta itemnumber 3366401 antaa virheen 500:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/b32ee1ad-66f0-4c70-bb0f-f2c40ecab7ed)

Tälle voi olla joku looginen selitys, jota en vain älyä. :D

**Comment by AnneliO** [comment]
Poistettua nidettä ei todennäköisesti vain pysty näyttämään liittymän kautta. Yleensä tuossa osoitteessa, mikä sinulla näkyy kuvassa, on mukana myös biblionumber eli tähän tyyliin: https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=3628751&biblionumber=2295604&bi=2295604#item3628751

Eli voi olla ihan vain siitä kiinni, että tuollaista https://outi.koha-suomi.fi/cgi-bin/koha/catalogue/moredetail.pl?itemnumber=3366401 osoitetta ei vain ole olemassa. :)

**Comment by pirliis** [comment]
Jep. Voidaan todeta, että tämä on nyt hoidettu. :) Suljen tiketin.
