### ISSUE TITLE
Lappi : 6.-20.4. saapunut -tilasta saatavaksi muutetut niteet ROPK

### ISSUE THREAD

**Issue by LeenaKinnunen** [KohaSuomi/Koha#739]
### Tukipyyntö

Tarvitsisimme tiedot niteistä, joiden tila on vaihdettu saapunut (-3) tilasta saatavana-tilaan 6.-20.4.2023 välisenä aikana, niteen kotikirjasto ROPK. Eli kun nide on ollut saapuneena, ja sen jälkeen palautettu. Kyseisenä aikana niteisiin on liimattu virheelliset tarrat, ja nämä niteet pitäisi saada nyt kiinni.

**Comment by AnneliO** [comment]
Työkalujen Lokien katselulla voi kokeilla hakea näin:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/ad6bce61-da79-4676-8d68-9a4d50dcfeee)

Mutta aika selailuksi tuokin menee. Eli infossa on "notforloan' => -3".

**Comment by AnneliO** [comment]
Tuossa siis haetaan lokilta tietueisiin liittyvät muutokset, joissa notforloan on ollut -3 ennen tallennusta. Hakutuloksia voi sitten koittaa vielä rajata kirjoittamalla Haku-kenttään esim. ROPK.

**Comment by LeenaKinnunen** [comment]
Ilmeni, että virhettä on ilmennyt jo melkein vuosi sitten, joten päätettiin selvittää ongelma muulla tavalla. Suljen tiketin.
