### ISSUE TITLE
Lumme: Koha ei hae asiakasta kannasta

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#741]
### Mikä vikana?

Viime viikolla oli käynyt ilmi, että lainaustilanteessa Koha ei ole löytänyt asiakkaan tietoja tietokannasta.

"Ensimmäisenä, asiakaan korttia piipatessa Koha ei löydä asiakasta. Kortti saatetaan piipata useampaankin otteeseen, eikä asiakasta löydy. Kun asiakas etsitään nimellä, löytyy asiakas sekä sen kortin numero, jolla asiakasta yritettiin alunperinkin hakea. Kortin piippaamiseenhan pitäisi voida luottaa, muutenhan nopeasti ollaan uutta kirjastokorttia tekemässä jos asiakasta ei ole ”olemassa”.

Toisena, kortti piipataan Kohaan lainaukselle ja Koha avaa väärän asiakkaan tiedot. Koha klikataan takaisin etusivulle ja piipataan kortti uudelleen lainauksella ja se EDELLEEN avaa väärän asiakkaan tiedot."

Yritetään selvittää, olisiko mihinkään laitettu ylös keistä asiakkaista tässä on ollut kyse.

**Comment by AnneliO** [comment]
Tyhmä kysymys ehkä, mutta onhan varmistettu, että viivakoodilukija ei lue väärin? :) Sitähän voi testata lukemalla saman kortin esim. Muistioon.

**Comment by Hanna-Lumme** [comment]
Kyselin virkailijalta vähän lisätietoja, niin hän oli myös kirjoittanut korttinumeron käsin Kohaan, mutta asiakasta ei ollut löytynyt. Asiakkaan nimeä hän ei tähän hätään muistanut.

**Comment by AnneliO** [comment]
Ihan arvailua, mutta voiskohan tässä olla tilanne, jossa sama korttinumero on jollakulla toisella asiakkaalla userid-kentässä? Lumpeissa ei ole vielä tehty kirjastokorttinumeroiden ja käyttäjätunnusten yhtenäistämisajoa.

**Comment by janPasi** [comment]
Näillä asiakkailla on keskenään ristiriitaisia cardnumbereita/userid:itä:

```
MariaDB [lummeprod]> select borrowernumber from borrowers where (cardnumber in (select userid from borrowers) and userid!=cardnumber) or (userid in (select cardnumber from borrowers) and userid!=cardnumber);
+----------------+
| borrowernumber |
+----------------+
|         239027 |
|         240071 |
|         240527 |
|         243380 |
|         247347 |
|         259667 |
+----------------+
6 rows in set (1.828 sec)

+----------------+
|         239027 |
|         240071 |
|         240527 |
|         243380 |
|         247347 |
|         259667 |
+----------------+
6 rows in set (1.828 sec)
```

**Comment by janPasi** [comment]
Raportti täällä: https://lumme.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=658&phase=Run%20this%20report

**Comment by AnneliO** [comment]
Tässä vielä raportti asiakkaista/tunnuksista, joilla cardnumber ja userid ei vastaa toisiaan: https://lumme.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=657&phase=Run%20this%20report

**Comment by janPasi** [comment]
> Eli voisikin hyvin todennäköisesti johtua tuosta. Onkohan tähän tulossa jossain vaiheessa yhtenäistämisajoa? Tietää infota virkailijoita. :)

Nuo ristiriidat täytyy selvittää käsin ennenkuin yhtenäistämisajoa voidaan tehdä.

**Comment by Hanna-Lumme** [comment]
Nyt olisi nuo tiedot käyty lävitse ja ristiriidat selvitelty.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 31.8.2023: Lari tekee yhtenäistämisajon ja laittaa paikoilleen triggerin, joka pitää cardnumberin ja userid:n samana.

**Comment by AnneliO** [comment]
Ajon jälkeen voisi vielä seurailla, jatkuuko asiakkaiden hakuongelma.

**Comment by lmstrand** [comment]
Ajo tehty:
```
MariaDB [lummeprod]> update borrowers set userid = cardnumber where cardnumber != userid;
Query OK, 516 rows affected (0.786 sec)
Rows matched: 516  Changed: 516  Warnings: 0
```
Triggerit lisätty:

```
create or replace trigger before_borrowers_insert
    BEFORE INSERT
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;

create or replace trigger before_borrowers_update
    BEFORE UPDATE
    ON borrowers FOR EACH ROW
    SET new.userid=new.cardnumber;
```
