### ISSUE TITLE
Saisiko piiloon Myöhässä ja maksuja -toiminnon, jossa näkyy asiakkaan nimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#743]
### Kehitysehdotukseni

Myöhässä ja maksuja -toiminnossa näkyy asiakkaan nimi, kirjastokorttiarvo, mahdolliset puhelinnumerot sekä mahdollinen sähköpostiosoite.

Koha-pääkäyttäjäpalaverissa 29.8.2023 sovittiin, että kimpassa
- Myöhässä-osio piilotetaan (sisältää toiminnot Myöhässä JA Myöhässä ja maksuja) 
tai
- Myöhässä ja maksuja -toiminto piilotetaan

Piilotustavan voi valita kimpan tarpeiden mukaan.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/96872278-240e-4956-a9cc-171c73f0c426)

**Comment by AnneliO** [comment]
Tässäpä olisi piilotuksia:

Piilota Myöhässä
```
/* Piilota Myöhässä -raportti Lainaus ja palautus -sivulta */
body#circ_circulation-home.circ a[href*="/cgi-bin/koha/circ/overdue.pl"] {
display: none;
}
```
Piilota Myöhässä ja maksuja:
```
/* Piilota Myöhässä ja maksuja -raportti Lainaus ja palautus -sivulta */
body#circ_circulation-home.circ a[href*="/cgi-bin/koha/circ/branchoverdues.pl"] {
display: none;
}
```

Jos piilottaa kummankin, pitää otsikkokin silloin piilottaa:
```
/* Piilota Overdues/Myöhässä-otsikko */
body#circ_circulation-home.circ div.col-sm-5.col-md-4 h3:nth-of-type(2) { display: none; }
```

**Comment by Kati-Helle** [comment]
Kiitos Anneli rimpsutriosta :)
Helle-testissä testasin: hienosti toimivat yhdessä ja itsekseen.

**Comment by pknuuti** [comment]
Vaarassa otettu käyttöön, kiitos!

**Comment by iinaniemi** [comment]
Vaskissa otettu käyttöön. Näyttää toimivan ongelmitta.

**Comment by pirliis** [comment]
OUTIssa piilotettu sekä "Myöhässä" että "Myöhässä ja maksuja" -toiminnot.
