### ISSUE TITLE
Asiakastiedot: uuden muotoinen henkilötunnus ei tallennu

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#745]
### Mikä vikana?

Kun asiakkaalle lisää uuden muotoisen henkilötunnuksen, ilmoittaa Koha: Tarkista hetu

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/34ff623b-46b8-48a2-9e53-d786e11cef13)

(Kuvassa näkyvä hetu on Henkilötunnuksen uudistaminen -tiedotteesta.)

Lisäksi asiakastiedon syntymäaika-kenttään ei muodostu automaattisesti arvoa hetusta.

Henkilötunnuksen uudistaminen -tiedote
https://dvv.fi/hetu-uudistus#

**Comment by AnneliO** [comment]
Turvan ssnservice/AddSsn.pm:ssä on

if ($ssnvalue =~ /(\d{6})[-+AB](\d{3})(.)/)

johon pitää lisätä tämän listan mukaisesti kirjaimia:

* vuonna 2000 tai sen jälkeen syntyneillä kirjaimet nykyinen A ja uudet B, C, D, E, F.
* 1900-luvulla syntyneillä nykyinen yhdysmerkki (-) tai uudet kirjaimet Y, X, W, V, U.
* 1800-luvulla syntyneillä nykyinen plusmerkki (+), ei uusia välimerkkejä.

**Comment by Kati-Helle** [comment]
Uuden muotoinen henkilötunnus tallentuu nyt Sotusiiloon. Myös Syntymäaika-kentän arvo muodostuu automaattisesti uuden muotoisesta henkilötunnuksesta.
