### ISSUE TITLE
Kohan itsepalvelulainauksessa tule timeout 30 minuutin kuluttua

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#748]
### Mikä vikana?

Kempeleen liikuntavälinelainaamo on ottanut käyttöön Kohan itsepalvelulainauksen. Ohjelma kirjautuu nyt ulos aina 30 minuutin kuluttua, kuten virkailijatunnukset tekevät. Järjestelmäasetuksen Timeout2, jossa automaatille oli määritelty 31536000 sekunttia timeoutiksi, ei auttanut asiaa. 

Miten saisimme itsepalvelulainauksen aikakatkaisun pitemmäksi?

**Comment by lmstrand** [comment]
Tuotannosta ja testeiltä puuttuu itsepalvelun aikakatkaisun muuttava koodi. Aikakatkaisu on kovakoodattu käyttämään kirjautuneelle sessiolle vuoden voimassaoloaikaa, jos asiakasnäkymään kirjautunut virkailijatunnus on tyyppiä "AUTO*" eli teillä pitäisi käyttämänne AUTOM-tyypin virkailijatunnus kelvata ja saada tuo vuoden voimassaoloaika.

Ilmoitan tikettiin, kunhan ominaisuus on tuotu testeille. Yritetään saada piakkoin tuotantoon.

**Comment by pirliis** [comment]
Testillä automaattiasiakastyypillä ohjelma on ollut päällä yli tunnin eikä timeoutia ole ainakaan vielä tullut eli oletettavasti toimii.

**Comment by pirliis** [comment]
Testattu myös testillä virkailijatunnuksen timeoutia. Uloskirjautuminen toimii kuin pitääkin eli 30 min. kuluttua.

**Comment by lmstrand** [comment]
Kuulostaa lupaavalta. @IrinaHalminen Vaarassa voisi siis teoriassa siirtyä käyttämään Automaatti-tyypin virkailijatunnuksia itsepalvelun kirjautumisnäkymässä, jos näitä itsepalvelulainausautomaatteja haluttaisiin lisää. Tähän asti kirjautuminen on tapahtunut automaattisesti sysprefillä AutoSelfCheckAllowed (ja siihen liitetyillä tunnuksilla) ja tuolla sysprefillä kirjautuminen saa myös sen vuoden voimassaoloajan.

Itse pääsin äsken Vaaran testin itsepalvelulainauksen asiakasnäkymään suoraan (testillä ei päällä AutoSelfCheckAllowed:ia). Poistettuani sessions-taulusta tallentuneet sessiot, heitti selain minut virkailijakirjautumiseen, joten oletan että useamman vuorokauden takainen viimeinen virkailijatunnuskirjautumiseni oli edelleen voimassa.

Viedään näillä testailuilla seuraavaan päivitykseen.

**Comment by lmstrand** [comment]
Sysprefit vaihtoehtoiselle timeoutille voi poistaa, sillä se on kovakoodattu tuotavaan ominaisuuteen. Tuotantoihin on päivitetty truncate_sessions-skripti ja Vaaraan ja Outiin on asetettu siivousskriptille --sco -vipu, joka skippaa nämä itsepalvelulainaussessiot siivouksessa.

**Comment by Kati-Helle** [comment]
Ovatkohan muutokset myös Hellessä (tuotannossa)? Itsepalvelulainauksen tunnukset ovat Automaatti-tyyppiä.

**Comment by lmstrand** [comment]
Ensi tiistain päivityksessä vasta siirretään toteutus tuotantoon.

**Comment by pirliis** [comment]
Päivitetty tuotantoon 19.9.2023. Suljen tiketin.
