### ISSUE TITLE
Vaara: Asiakkaalle käyttökielto Heinävaaran omatoimikirjastoon

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#751]
### Tukipyyntö

Asiakkaalle tarvitaan käyttökieltoprosessin ajaksi esto käyttää Heinävaaran (JOE_HEI) omatoimikirjastoa. Käyttökielto on voimassa 1.9.-30.9.2023 eli pääsy omatoimikirjastoon tulisi olla sallittu taas 1.10. Asiakkaan id:n laitan suojattuna spostina.

**Comment by paxed** [comment]
Esto lisätty.

**Comment by IrinaHalminen** [comment]
Kiitos!
