### ISSUE TITLE
Kieliasun korjaus: "viimeeksi nähty", "viimeeksi lainattu"

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#753]
### Tukipyyntö

Niteen muokkaustilassa muokattavana olevan niteen alla olevassa nidelistauksessa on otsikoissa virheellinen kieliasu kohdissa viimeksi lainattu ja viimeksi nähty. Näyttää koskevan vain tiettyjä nidetyyppejä, esim. ainakin lehtiä ja esineitä.

Avaa esim. https://vaara.koha-suomi.fi/cgi-bin/koha/cataloguing/additem.pl?op=edititem&biblionumber=11693946&itemnumber=101580904#edititem ja skrollaa alas nähdäksesi lista muista niteistä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/9990c88c-1420-42ac-8bba-4f1b93afae02)

**Comment by AnneliO** [comment]
Tuon saa korjattua MARC-kuvailupohjista käsin eli täältä: https://vaara.koha-suomi.fi/cgi-bin/koha/admin/marc_subfields_structure.pl?op=add_form&tagfield=952&tagsubfield=r&frameworkcode=#subrfield

Jokainen kuvailupohja pitää muokata erikseen. :)

**Comment by pknuuti** [comment]
Vaaran tekstit korjattu.

**Comment by IrinaHalminen** [comment]
Kiitos avusta!
