### ISSUE TITLE
OUTI: automaattiset asiakastyyppimuutokset tapahtuvat päivän liian myöhässä

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#754]
### Mikä vikana?

OUTIssa automaattiset asiakastyyppimuutokset "Lapsi, omatoimi kielletty" -> "Lapsi, omatoimi sallittu" ja "Lapsi, omatoimi sallittu" -> "Henkilöasiakas" tapahtuvat päivän liian myöhään. Esimerkiksi tuotannon testiasiakas 302248 täytti 18 vuotta tänään 1.9.2023, mutta hänen asiakastyyppinsä on yhä "Lapsi, omatoimi sallittu". Testiasiakas 302092 puolestaan täytti eilen 31.8.2023 16 vuotta, mutta hänen asiakastyyppinsä vaihtui oikeaksi vasta tänään 1.9.2023.

![laomatoimi](https://github.com/KohaSuomi/Koha/assets/118160273/e810da88-63ab-4647-95a3-2f153f40d213)

### Mitä pitäisi tapahtua

Asiakastyypin pitäisi muuttua syntymäpäivänä.

**Comment by emta001** [comment]
Tämä on taas sarjassamme näitä "works on my machine" :D pitäänee seurailla paria asiakkasta, että kuinka heidän kohdallaan käy.

**Comment by velimarj** [comment]
Ajoin nyt OUTIn tuotannossa taas raportin 645, jolla löysin 13 kpl 16-vuotiaita asiakkaita, joilla asiakastyyppi "Lapsi, omatoimi kielletty". Syntymäpäivät heillä oli joko 3.9.2007 tai 4.9.2007.

**Comment by emta001** [comment]
> Ajoin nyt OUTIn tuotannossa taas raportin 645, jolla löysin 13 kpl 16-vuotiaita asiakkaita, joilla asiakastyyppi "Lapsi, omatoimi kielletty". Syntymäpäivät heillä oli joko 3.9.2007 tai 4.9.2007.

Vilkaisin OUTIn kannasta, siellä on 14 asiakasta joiden syntymäpäivä on 3.9.2007 ja asiakastyyppi on "LAPSI". Näyttäs nyt siltä, että tuo ajo ei nappaa välillä edes toissapäivänä yli-ikäisiksi tulleisiin?

**Comment by emta001** [comment]
Toinen huomio, asiakkaat, joiden syntymäpäivä oli 5.9.2005, ovat päivittyneet tänään kuten pitääkin (LAOMATOIMI -> HENKILO)

**Comment by velimarj** [comment]
> > Ajoin nyt OUTIn tuotannossa taas raportin 645, jolla löysin 13 kpl 16-vuotiaita asiakkaita, joilla asiakastyyppi "Lapsi, omatoimi kielletty". Syntymäpäivät heillä oli joko 3.9.2007 tai 4.9.2007.
> 
> Vilkaisin OUTIn kannasta, siellä on 14 asiakasta joiden syntymäpäivä on 3.9.2007 ja asiakastyyppi on "LAPSI". Näyttäs nyt siltä, että tuo ajo ei nappaa välillä edes toissapäivänä yli-ikäisiksi tulleisiin?

Katselin kanssa nyt vähän laajemmin, niin vuodelta 2007 näyttäisi olevan 28 kpl 16-vuotiasta tuolla "LAPSI" asiakastyypillä, jos nyt oikein katsoin. Eli siinä jotain häikkää?

**Comment by emta001** [comment]
Jokin siinä nyt on tosiaan hieman vinksallaan, tuohan toimii ihan miten sattuu nyt :D Tutkailen tuota tarkemmin, kunhan saan käsiä vapaammaks muista hommista.

**Comment by velimarj** [comment]
Testailu jatkuu: laitoin eilen molemmille asiakastyypeille testiasiakkaat (LAOMATOIMI ID: 302248  ja LAPSI ID: 302092) eikä kumpikaan ollut muuttunut.

Tällä kertaa löysin myös muita 18-vuotiaita LAOMATOIMIa. Mutta jostain syystä en löytänyt niitä hakemalla päivämäärää 6.9.2005 vaan 7.9.2005. Myös 16-vuotiaista "LAPSI" asiakastyyppiä oli ja sama havainto, että löytyi aina ikään kuin päivän taaksepäin.

**Comment by emta001** [comment]
Sekin on hyvin jännittävää, ettei näin näyttäisi käyvän muissa kimpoissa :thinking:

**Comment by emta001** [comment]
Okei, eli OUTIn lokeissa näkyy ainakin viimeisen kolme ajon kohdalla seuraava virhe:

Use of uninitialized value in string eq at /home/koha/Koha/Koha/Patron.pm line 337.
[Child patron needs a guarantor]

Eli tää liittynee jollain tapaa huoltaja-vaatimukseen.

**Comment by emta001** [comment]
Ongelmana vaikuttaisi olevan asiakas 117541, jolla ei ole huoltajatietoja. Koko ajo kaatuu tuohon _[Child patron needs a guarantor]_ virheeseen. Hieman ikävä tilanne, sillä tällä hetkellä yksikään asiakas ei päivity ennen kuin tuo on korjattu.

Se miksi LAOMATOIMI -> HENKILO toimii hieman miten sattuu on kyllä vielä arvoitus. Mutta tänään kaikki näyttäisivät vaihtuneen onnistuneesti. Ehkäpä ajon siirto eteenpäin auttoi.

**Comment by pirliis** [comment]
> Ongelmana vaikuttaisi olevan asiakas 117541, jolla ei ole huoltajatietoja. Koko ajo kaatuu tuohon _[Child patron needs a guarantor]_ virheeseen. Hieman ikävä tilanne, sillä tällä hetkellä yksikään asiakas ei päivity ennen kuin tuo on korjattu.
> 
> Se miksi LAOMATOIMI -> HENKILO toimii hieman miten sattuu on kyllä vielä arvoitus. Mutta tänään kaikki näyttäisivät vaihtuneen onnistuneesti. Ehkäpä ajon siirto eteenpäin auttoi.

Voisiko auttaa asiaa, jos asiakkaan 117541 asiakastyyppi vaihdetaan manuaalisesti LAPSI -> LAOMATOIMI? Meillä kun ei ole tuolle lapsiasiakkaalle mistä lisätä takaajaa. :D

**Comment by emta001** [comment]
> > Ongelmana vaikuttaisi olevan asiakas 117541, jolla ei ole huoltajatietoja. Koko ajo kaatuu tuohon _[Child patron needs a guarantor]_ virheeseen. Hieman ikävä tilanne, sillä tällä hetkellä yksikään asiakas ei päivity ennen kuin tuo on korjattu.
> > Se miksi LAOMATOIMI -> HENKILO toimii hieman miten sattuu on kyllä vielä arvoitus. Mutta tänään kaikki näyttäisivät vaihtuneen onnistuneesti. Ehkäpä ajon siirto eteenpäin auttoi.
> 
> Voisiko auttaa asiaa, jos asiakkaan 117541 asiakastyyppi vaihdetaan manuaalisesti LAPSI -> LAOMATOIMI? Meillä kun ei ole tuolle lapsiasiakkaalle mistä lisätä takaajaa. :D

Kyllä vois, rupesinkin eilen illalla miettimään, että saahan tämän tuollakin tavoin kierrettyä myös :D Ja kun asiakas aikuistuu, niin silloin tätä vastaavaa ongelmaa ei tule enää vastaan.

**Comment by emta001** [comment]
Nyt tuo on muokattu. Mietin vielä pitäisikö nämä muut nyt jumissa olevat asiakkaat myös muokata samantien vai katsellaanko, että toimiko tämä korjaus ja toimiiko automatiikka nyt oikein :thinking:

**Comment by pirliis** [comment]
> Nyt tuo on muokattu. Mietin vielä pitäisikö nämä muut nyt jumissa olevat asiakkaat myös muokata samantien vai katsellaanko, että toimiko tämä korjaus ja toimiiko automatiikka nyt oikein 🤔

Jos katsotaan ensin auttoiko korjaus. Jos ei, niin korjataan muutkin sitten käsin.

**Comment by emta001** [comment]
Näyttäisi sille, että asiakastyypit ovat muuttuneet onnistuneesti. Seuraillaan vielä jatkuuko tämä päivitysongelma muuten, ehkäpä ajojen ajastuksen muutoksesta oli tosiaan apua.

**Comment by emta001** [comment]
Service-checkiin tehdään tarkistus takaajattomien lapsiasiakkaiden varalle (tiketti #765 ).

**Comment by emta001** [comment]
Kävin muuttamassa seuraavat asiakkaat käsin categorycodeen "LAOMATOIMI": 148770 ja 154459. Ensimmäinen oli jäänyt jumiin 15.9. ja toinen olisi kumittanut ajon huomenna 19.9.

**Comment by velimarj** [comment]
Kaikesta päätellen toimii kuten pitää, suljen tiketin.
