### ISSUE TITLE
OUTI: Asiakastyyppimuutoksen oletusviestiasetusten pop up -kysely piiloon

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#755]
### Kehitysehdotukseni

OUTIssa on tullut vastaan ongelmia, kun muutetaan asiakastyyppiä manuaalisesti, esimerkiksi "Lapsi, omatoimi kielletty" -> "Lapsi, omatoimi sallittu". Asiakastyyppiä vaihdettaessa näkyviin tulee alla oleva pop up -kysely, jossa kysytään halutaanko viestiasetukset laittaa uuden asiakastyypin mukaiseksi.

![viestien_oletusasetukset](https://github.com/KohaSuomi/Koha/assets/118160273/7fab5ee6-59f5-4317-8781-694c424c24cc)

OUTIssa millekään asiakastyypille ei ole asetettu oletusviestiasetuksia. Kun pop upin hyväksyy klikkaamalla "OK", tipahtavat viestitäpät kokonaan pois. Puhelinnumero ja sähköpostiosoite säilyvät ennallaan. Klikkaamalla "Peruuta" muutosta ei tapahdu. Ohjeistaminen (klikkaa "Peruuta") on toki yksinkertaisin vaihtoehto, mutta koska koemme koko kyselyn "turhaksi", haluaisimme mielellään sen kokonaan piiloon, jos mahdollista. OUTIssa on varsin paljon omatoimikirjastoja, joten tilanteita tulee kyllä vastaan. 

### Jotain muuta?

oletusviestiasetukset
asiakastyyppi

**Comment by AnneliO** [comment]
Tähän etäisesti liittyen, tämä aiemmin käännösmuutos oli kadonnut jossain välissä ja tein sen nyt uudelleen. Tulee mukaan seuraavassa päivityksessä: https://github.com/KohaSuomi/Koha-translations/issues/3

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 4.9.2023: Tämän toteuttaminen on todella hankalaa. Ei toteuteta tällä hetkellä.

**Comment by velimarj** [comment]
Kiitokset selvittämisestä, suljenpa siis tämän tiketin tässä kohtaa.
