### ISSUE TITLE
Raportti, jolla saa vanhemmat lokitiedot nimekkeestä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#756]
### Tukipyyntö

Nimekkeen muutoslokissa näkyy suoraan vain kuluvan ja edellisen vuoden tiedot. Tarvitsen vuoden 2020 tiedot nimekkeestä. Tarvitaan raportti, jolla voi hakea vanhoista action_logseista tarvittavan vuoden tiedot.

**Comment by AnneliO** [comment]
Vaarassa on nyt raportti nro 771, jossa on tällainen kysely:

```
select timestamp,user,module,action,object,info,interface from action_logs
where module='CATALOGUING'
and object=<<biblionumber>>

UNION
select timestamp,user,module,action,object,info,interface from action_logs_2021
where module='CATALOGUING'
and object=<<biblionumber>>

UNION
select timestamp,user,module,action,object,info,interface from action_logs_2020
where module='CATALOGUING'
and object=<<biblionumber>>

UNION
select timestamp,user,module,action,object,info,interface from action_logs_2019
where module='CATALOGUING'
and object=<<biblionumber>>

UNION
select timestamp,user,module,action,object,info,interface from action_logs_2018
where module='CATALOGUING'
and object=<<biblionumber>>

UNION
select timestamp,user,module,action,object,info,interface from action_logs_2017
where module='CATALOGUING'
and object=<<biblionumber>>

ORDER BY 1 DESC
```

Vuositauluja oli Vaarassa vain vuoteen 2017 saakka. Tiedot järjestetään timestampin mukaan laskevasti.

**Comment by pknuuti** [comment]
Kiitän ja suljen tiketin.

**Comment by AnneliO** [comment]
Muistiin tänne, että raportti lisätty nyt myös Raportti-kirjastoon [Lokien katselu -osioon](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#kuvailutietueen-muutosten-katselu).
