### ISSUE TITLE
OUTI: Pudasjärven kirjaston Ceepos-palvelin vaihtuu 11.10.2023

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#763]
### Tukipyyntö

Pudasjärven kirjaston Ceepos-palvelin vaihtuu 11.10.2023:

• VPN Clienttien -tilaus. VPN Clienttien toteutus hoidetaan CPU:n toimesta vk 36-37 aikana.
• Uuden palvelimen valmistelut. Uusi palvelin valmistellaan CPU:n toimesta vk 37-38 aikana. Palvelinvalmistelujen valmistuttua toimitetaan Pudasjärvelle ohjeistus työasemien valmistelutoimenpiteitä varten.
• Työasemien esivalmistelu. Työasemien esivalmistelutoimenpiteet hoidetaan Lapit toimesta vk 39-40 aikana.
• Palvelimen yliheitto. Y**liheiton ajankohdaksi sovittiin 11.10. klo 8-11.** Kassassa käyttökatko tuon ajan.
• KOHA-integraatio. Voisitteko Pudasjärveltä olla KOHA:an yhteydessä ja kertoa, että **Ceeposin kohdeosoite muuttuu yliheittomme yhteydessä. Uusi yhteysosoite on 91.123.141.122**. Lisäksi voisitteko samassa viestissä pyytää KOHA:laisia olemaan yhteydessä meihin, jotta voimme samassa yhteydessä päivittää asiaan liittyvän sertifikaatin.

Support-postiin välitetty 7.9. viestiketju, josta löytyy myös CPU:n yhteyshenkilöiden tiedot.

Samanlainen muutos Iin kirjaston Ceepos-palvelimelle tiketissä #787.

**Comment by lmstrand** [comment]
Ceepos-konfiguraatioon vaihdettu sertifikaatit ja uusi yhteysosoite.

**Comment by pirliis** [comment]
Hyvä homma. Ilmoitin CPU:lle, että Kohan päähän muutokset tehty.
