### ISSUE TITLE
OUTI: Asiakkaan muokkaukset -raportti 495 ei toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#764]
### Tukipyyntö

OUTIn tuotannossa on raportti 495: Asiakkaan muokkaukset. 
En saa sitä toimimaan. Tulee virheilmoitus: 
Virheitä:
Tietokannassa tapahtui virhe:
The used SELECT statements have a different number of columns
Tarkista loki lisätietoja varten.

Ehtisikö joku katsomaan, mikä raportissa on pielessä?

**Comment by emta001** [comment]
Action_logs-tauluun on lisätty sarake _script_ (yhteisön tiketti [30984](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30984)), jota ei löydy vuositauluista, joten taulujen sarakkeiden määrä vaihtelee. Tällöin tauluista ei voi valita kaikkia sarakkeita. Määritin pikakorjauksena ensimmäiseen selectiin haettavaksi samat sarakkeet kuin muissa tauluissa. Mutta tuo pitäisi ratkaista minusta niin, että vuositauluihin lisätään myös script-sarake.

**Comment by emta001** [comment]
Perutaas tää muutos vielä hetkeks ja testaillaan testeillä. Onnistuin äsken saamaan proxy errorin, kun kokeilin tuota omalla borrowernumberilla.

**Comment by AnneliO** [comment]
Tein äskettäin vastaavan raportin kuvailutietojen muutosten katseluun ja ratkaisin siinä ongelman määrittämällä selectiin, mitkä sarakkeet otetaan mukaan. Kysely löytyy raporttikirjastosta: https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#kuvailutietueen-muutosten-katselu

**Comment by emta001** [comment]
Anneli hoksautti myös siitä, että tuon ehdon _convert(object using 'utf8') like @Asiakas_ voi korvata _object = <<borrowernumber>>_. Kokeilin testillä, eikä raportin ajamiseen mennyt enää kuin hetki.

**Comment by pirliis** [comment]
> Anneli hoksautti myös siitä, että tuon ehdon _convert(object using 'utf8') like @asiakas_ voi korvata _object = <>_. Kokeilin testillä, eikä raportin ajamiseen mennyt enää kuin hetki.

Näytti toimivan minullakin nopeasti. Minäpä kopsaan testiltä tuotantoon.

**Comment by emta001** [comment]
> > Anneli hoksautti myös siitä, että tuon ehdon _convert(object using 'utf8') like @asiakas_ voi korvata _object = <>_. Kokeilin testillä, eikä raportin ajamiseen mennyt enää kuin hetki.
> 
> Näytti toimivan minullakin nopeasti. Minäpä kopsaan testiltä tuotantoon.

Anneli on korjaamassa tuota rapsapankissa olevaa esimerkkiä. Kannattaa mieluummin käyttää sitä.

**Comment by AnneliO** [comment]
[Rapsapankin](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#asiakkaan-tietojen-muutokset) esimerkki nyt korjattu.

**Comment by pirliis** [comment]
> [Rapsapankin](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#asiakkaan-tietojen-muutokset) esimerkki nyt korjattu.

Kiitos toimii. Suljen tiketin.
