### ISSUE TITLE
Service-checkiin tarkistus lapsiasiakaista joilta puuttuu takaaja

### ISSUE THREAD

**Issue by emta001** [KohaSuomi/Koha#765]
### Kehitysehdotukseni

OUTIssa automaattiset asiakastyyppimuutokset epäonnistuivat johtuen "LAPSI" tyyppisestä asiakkaasta, jolta puuttuivat takaajatiedot. Lisätään service-checkiin tarkistus tällaisille asiakkaille vastaisuuden varalle.

**Comment by emta001** [comment]
Laitanpa vielä tännekin mitä jo Matrixiin pistin. Eli nuo määrät ei täsmää, koska taattavalla voi olla useampi kuin yksi takaaja. Varmin tapa saada takaajattomat selville on tarkistaa löytyykö taattavan borrowernumber borrower_relationships-taulusta. Tällä rimpsulla pitäis onnistua noiden takaajattomien taattavien laskeminen:

`SELECT COUNT(*) FROM borrowers WHERE categorycode IN (SELECT categorycode FROM categories WHERE can_be_guarantee = 1) AND borrowernumber NOT IN(SELECT guarantee_id FROM borrower_relationships);`

Hieman muokkaamalla tätä voi käyttää sitten Kohassa rapsana:
```
SELECT borrowernumber, categorycode 
FROM borrowers 
WHERE categorycode IN (SELECT categorycode FROM categories WHERE can_be_guarantee = 1) 
AND borrowernumber NOT IN(SELECT guarantee_id FROM borrower_relationships)
```

**Comment by emta001** [comment]
Tein tästä tarkistuspyynnön https://github.com/KohaSuomi/Koha/discussions/802

**Comment by janPasi** [comment]
Jep, toihan on tosiaan paljon järkevämpi tapa, kiitos @emta001. Tämä nyt tuotannossa ja herjailee jokaisessa kimpassa tosiaan, joten tarkistuspyyntö on paikallaan :D

**Comment by emta001** [comment]
Tarkistus on ollut tuotannossa jo jonkin aikaa ja toimii kuten pitää. Suljen tämän.
