### ISSUE TITLE
Asiakasviestipohjaan ehto, jos asiakkaan Muu nimi-kenttä on tyhjä, käytetään Etunimi-kentän tietoa

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#767]
### Tukipyyntö

OUTIssa haluttaisiin ottaa käyttöön asiakkaan tiedoissa Muu nimi -kenttä asiakkaan kutsumanimi-kentäksi. Olisiko mahdollista saada asiakasviestien pohjaan ehtoa, että jos asiakkaan Muu nimi -kenttä on tyhjä, viestipohjassa käytetään asiakkaan Etunimi-kenttää?

Laskupohjiin Muu nimi -kenttää ei otettaisi käyttöön, koska laskuissa pitää olla asiakkaan virallinen nimi.

**Comment by lmstrand** [comment]
[% IF ( borrower.othernames ) %] <<borrowers.othernames>>
[% ELSE %]  <<borrowers.firstname>> 
[% END %]

tuntuisi testieni mukaan toimivan.

**Comment by pirliis** [comment]
Kiitos! Näyttäisi toimivan ja myös viestipohjassa, jossa on toinenkin ehto.

**Comment by pirliis** [comment]
Palataan asiaan, jos tulee ongelmia, kun otamme ehdon käyttöön tuotannossa. Suljen tiketin tältä erää.
