### ISSUE TITLE
Sarakevalinnat eivät käyttäydy aina oikein niteiden eräpoistossa/erämuokkauksessa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#769]
### Mikä vikana?

Virkailija oli huomannut, että niteiden eräpoistossa sarakkaiden näyttäminen/piilottaminen toimii oikein työkalua ensimmäisen kerran käyttäessä, mutta jos työkaluun siirtyy myöhemmin uudelleen, sarakkaiden näyttäminen/piilottaminen ei enää toimikaan oikein.

Sain itse toistettua ongelman. Kun avasin ensimmäistä kertaa eräpoiston ja piilotin osan sarakkeista, toimi piilotus sinällään oikein joskin huomasin että minulle näkyi myös sarake _Varauksia_ jolle ei ollut olemassa piilotusmahdollisuutta.

Kun avasin työkalun uudelleen, tekemäni sarakevalinnat olivat edelleen tallessa mutta ne eivät täsmänneet näkyvillä olevien sarakkeiden kanssa. Esim. _Hankintahinta_ näkyi, vaikka se oli piilotettu, mutta _Lainauksia yhteensä_ ei näkynyt vaikka olisi pitänyt olla näkyvillä. Lisäksi aiemmin näkynyt sarake _Varauksia_ oli kadonnut.

Kun valitsin "Näytä kaikki sarakkeet", sain sarakkeiden piilottamisen/näyttämisen toimimaan taas oikein. Siltikään näkyville ei tullut tuota työkalussa ensimmäisellä kerralla näkynyttä _Varauksia_ -saraketta.

Lopuksi avasin vielä niteiden erämuokkauksen ja luin viivakoodit sinne. Nidenäkymässä sielläkin näkyivät sarakevalinnat jotka olin eräpoistoon tehnyt, eivätkä valinnat täsmänneet näkyville oleviin sarakkeisiin.

### Kuinka toistaa ongelma/asia

1. Avaa Niteiden eräpoisto ja lue sinne viivakoodeja, omassa testissä käytin viivakoodeja
853N15104843
853N15409685
853N16647337
853N19177472
853N20700868
2. Valitse Jatka. Nidenäkymässä on oletuksena kaikki sarakkeet näkyvillä. Jätä vain osa sarakkeista näkyville, itse jätin näkyville
Lainauksia yhteensä
Kohan koko signum
Viivakoodi
Lainassa
Viimeksi lainattu pvm
Nidetyyppi
3. Huomaa, että näkymästä piiloutuu ne sarakkeet mitkä pitikin. Poistu työkalusta.
4. Avaa työkalu uudelleen, lue viivakoodit ja valitse Jatka. Itse testasin sekä samoja että eri viivakoodeja.
5. Huomaa, että nidenäkymässä on edelliset sarakevalinnat muistissa, mutta ne eivät täysin täsmää näkyvillä oleviin sarakkeisiin.

### Jotain muuta?

**Näkymä työkalua ensimmäistä kertaa käytettäessä:**

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/cc3edd38-439e-4b6c-af7e-7742b55812e7)

**Näkymä, kun työkaluun on siirtynyt uudemman kerran:**

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/7d4bf608-7f0f-4856-ba31-6da8b0c17fc6)

**Comment by AnneliO** [comment]
Testaan, toimiiko tämä sandboxissa ja koitan etsiä bögzillasta tähän liittyviä tikettejä.

**Comment by AnneliO** [comment]
Tämä näyttäisi toistuvan myös PTFS Europen sandboxissa:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/089b0c7f-ca8f-450e-a1a2-73d6f84aaa2d)

**Comment by AnneliO** [comment]
Nyt en kyllä tunnu löytävän tästä tikettiä Bögzillasta.

**Comment by MikkoLiimatainen** [comment]
Johtuisikohan tämä ongelma siitä, että kun valinnasta poistetaan ruksi, niin valinnan span elementiltä poistetaan selected-luokka, mutta sen inputille jää checked="checked" attribuutti? Tästä voisi aiheutua koodissa ristiriita, jossa ei ole varmuutta siitä onko valinta valittuna vai ei.

**Comment by emta001** [comment]
> Nyt en kyllä tunnu löytävän tästä tikettiä Bögzillasta.

Tämä vaikuttaisi olevan samasta asiasta https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32477.

**Comment by emta001** [comment]
> Johtuisikohan tämä ongelma siitä, että kun valinnasta poistetaan ruksi, niin valinnan span elementiltä poistetaan selected-luokka, mutta sen inputille jää checked="checked" attribuutti? Tästä voisi aiheutua koodissa ristiriita, jossa ei ole varmuutta siitä onko valinta valittuna vai ei.

Juu, tästä tän täytyy johtua. Koodissa on seuraava pätkä:

```
 if ($(this).prop("checked")) {
    showColumn(num);
 } else {
    hideColumn(num);
}
```
Eli kun se checked-arvo jää tuonne roikkumaan, niin tuo pätkä rupeaa käsittelemään sitä ihan miten sattuu.

**Comment by emta001** [comment]
> > Johtuisikohan tämä ongelma siitä, että kun valinnasta poistetaan ruksi, niin valinnan span elementiltä poistetaan selected-luokka, mutta sen inputille jää checked="checked" attribuutti? Tästä voisi aiheutua koodissa ristiriita, jossa ei ole varmuutta siitä onko valinta valittuna vai ei.
> 
> Juu, tästä tän täytyy johtua. Koodissa on seuraava pätkä:
> 
> ```
>  if ($(this).prop("checked")) {
>     showColumn(num);
>  } else {
>     hideColumn(num);
> }
> ```
> 
> Eli kun se checked-arvo jää tuonne roikkumaan, niin tuo pätkä rupeaa käsittelemään sitä ihan miten sattuu.

Ongelma taitaakin olla siinä, että sivun uudelleenlatautuessa piilotetaankin aluksi väärä kenttä. Tai sitten ongelma on nää kaks hassuutta yhdessä.

**Comment by emta001** [comment]
Jeppis, ongelma taisikin olla ihan se, että tuo piilottaa väärän sarakkeen. Tein korjauksen yhteisöön ja tuon tän meillekin jossain vaiheessa. Tää tuskin kerkeää enää versioon 23.11 mukaan.

**Comment by emta001** [comment]
Tuotu testeille.

**Comment by MikkoLiimatainen** [comment]
Muuten tuo näyttäisi nyt toimivan, mutta jos niteiden erämuokkauksessa valitsee piilota kaikki sarakkeet, peruuttaa muokkauksen ja aloittaa uuden, niin silloin nidetyyppi on ainoa valittu sarake. Siinä varmaankin pitäisi olla sareke Varaukset, joka ei nähdäkseni ole piilotettavissa oleva sarake, mutta jonka saa näin kikkailemalla katoamaan kokonaan.

Eräajon puolella tuo sama kikka valitsee edelliset valitut sarakkeet sen sijaan, että piilottaisi kaikki palatessa eräpoistoon peruutuksen jälkeen.

**Comment by emta001** [comment]
> Muuten tuo näyttäisi nyt toimivan, mutta jos niteiden erämuokkauksessa valitsee piilota kaikki sarakkeet, peruuttaa muokkauksen ja aloittaa uuden, niin silloin nidetyyppi on ainoa valittu sarake. Siinä varmaankin pitäisi olla sareke Varaukset, joka ei nähdäkseni ole piilotettavissa oleva sarake, mutta jonka saa näin kikkailemalla katoamaan kokonaan.
> 
> Eräajon puolella tuo sama kikka valitsee edelliset valitut sarakkeet sen sijaan, että piilottaisi kaikki palatessa eräpoistoon peruutuksen jälkeen.

Hyvä huomio. Sama näemmä tapahtuu yhteisön versiossa.

**Comment by emta001** [comment]
Testeille on tuotu päivitys, jolla tuon Mikon huomaaman ongelman pitäisi kojraantua.

**Comment by piiaseme** [comment]
OUTI-testillä niteiden erämuokkaus ja niteiden eräpoisto säilyttävät valitut sarakkeet ruksattuina ja ruksatut sarakkeet näkyvät oikein. Vaihdoin välillä eräajosta toiseen, niin samat sarakevalinnat säilyivät valittuina ja näkyvillä.

Sarakevalinnat nollautuivat ainoastaan siten, että lopetin Koha-istunnon. 

OUTI-testillä korjauspäivitys toimii.

**Comment by MikkoLiimatainen** [comment]
Erämuokkaus näyttäisi nyt toimivan muuten paitsi ettei Piilota kaikki sarakkeet kohdassa ole ruksia, jos se valittuna peruuttaa ja aloittaa uuden muokkauksen. Oikeat sarakkeet on kyllä näkyvissä.

Niteiden eräpoiston puolella tuo Piilota kaikki sarakkeet valinta ei edelleenkään säily peruutuskikkaa käyttäen, mutta muut sarakevalinnat säilyvät kyllä.

Huomasin, että olin kirjoittanut asian epäselvästi aiemmin, mutta tämän saman korjauksen voisi tehdä niteiden poiston puolellekin ja jos tuon Piilota kaikki sarakkeet ruksin vielä saisi näkyviin.

**Comment by emta001** [comment]
> Erämuokkaus näyttäisi nyt toimivan muuten paitsi ettei Piilota kaikki sarakkeet kohdassa ole ruksia, jos se valittuna peruuttaa ja aloittaa uuden muokkauksen. Oikeat sarakkeet on kyllä näkyvissä.
> 
> Niteiden eräpoiston puolella tuo Piilota kaikki sarakkeet valinta ei edelleenkään säily peruutuskikkaa käyttäen, mutta muut sarakevalinnat säilyvät kyllä.
> 
> Huomasin, että olin kirjoittanut asian epäselvästi aiemmin, mutta tämän saman korjauksen voisi tehdä niteiden poiston puolellekin ja jos tuon Piilota kaikki sarakkeet ruksin vielä saisi näkyviin.

Tuosta eräpoistosta pitänee tehdä uusi tiketti Bugzillaan (vastaava kuin [32477](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32477)). Tekisitkö Mikko semmosen? Pitää vielä tutkasta tuota "Piilota kaikki sarakkeet" ruksia ja mitä sen kanssa tehdään yhteisössä, koska tuohon erämuokkaukseen tehty muutos on jo mennyt masteriin... Pitää varmaan siitäkin tehdä oma tiketti.

**Comment by emta001** [comment]
Tarkistin vielä tuon niteiden "Niteiden poisto eräajona" työkalun ja se vaikuttaisi toimivan kuten pitääkin, lukuunottamatta tuota "Piilota kaikki sarakkeet" ruksin ongelmaa. Työkalut jakaa saman koodin, joten ongelma on korjaantunut molemmissa.

**Comment by emta001** [comment]
Lisäsin yhteisöön tiketin [36129](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36129).

**Comment by emta001** [comment]
Tehdään tuosta "Piilota kaikki sarakkeet" nappi ongelmasta oma tiketti.

**Comment by ajrajala** [comment]
Ohops, tämä tiketti on minulta jäänyt sulkematta. Piilota kaikki sarakkeet -valinnan ongelmasta on oma tiketti avattuna, joten tämä nyt ok.
