### ISSUE TITLE
TäTi-tietokantaan päälle cardnumber->userid triggeri ja ajo, joka vie cardnumberin userid-kenttään

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#770]
### Tukipyyntö

Pääkäyttäjien kokouksessa 12.9.2023 päätettiin ottaa käyttöön myös TäTi-tietokannassa triggeri, joka kopioi cardnumber-kentän tiedot userid-kenttään.

Lisäksi tietokannassa pitää tarvittaessa (jos triggeri ei tee sitä) tehdä ajo, joka vie kaikilla nykyisillä tunnuksilla cardnumber-kentän arvon userid-kenttän.

Triggerin voi ottaa käyttöön ja ajon voi tehdä viikon 38 päivityksen yhteydessä, jotta TäTi-käyttäjät ehtivät tarvittaessa käydä tarkistamassa omat tietonsa sitä ennen.

**Comment by paxed** [comment]
Triggeri on paikallaan, mutta en vielä muuttanut userid:tä samaksi kuin cardnumber - tätissä on tällä hetkellä 89 käyttäjää joiden userid on esim. etunimi.sukunimi (tjsp), ja cardnumber on pelkkä numerosarja. Käyttäjät voisivat vielä tarkistaa millä ovat tätiin kirjautuneet, ettei tule ongelmia.

**Comment by AnneliO** [comment]
Muutoksen voi tehdä, koska sovimme pääkäyttäjäpalaverissa, että käyttäjät tarkistavat tähän päivään mennessä tunnuksensa. :)

**Comment by johannaraisa** [comment]
Tässä tulee sellainen ongelma, että nuo userid:t on linkitetty mikropalveluun joten luultavasti se Vie/Tuo kosahtaa niiden osalla joilla tunnus muuttuu.

**Comment by AnneliO** [comment]
Onko tässä vielä jotain kesken? :)

**Comment by AnneliO** [comment]
Ilmeisesti mahdolliset kosahukset on hoidettu tapauskohtaisesti. Suljen tiketin.
