### ISSUE TITLE
Asiakastiedot: uuden asiakastiedon luonti olemassa olevasta asiakastiedosta kopioiden: uuden asiakastiedon Tullut asiakkaaksi -kentän arvoksi ei muodostu automaattisesti kuluva päivä

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#771]
### Mikä vikana?

Kun kopioi olemassa olevan virkailijatunnuksen uuden virkailijatunnuksen 'pohjaksi', muodostuu uuden virkailijatunnuksen Tullut asiakkaaksi -kentän arvo pitkälle tulevaisuuteen. Esimerkiksi tänään 12.9.2023 Hellessä arvoksi tulee automaattisesti päiväys 12.12.2106. (Virkailija-asiakastyypin voimassaoloaika on 999 kuukautta)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/36666879-a5d3-421a-94eb-8f8d43433385)

Tänään 12.9.2023 Aikuinen-asiakastyypin kopioinnissa Tullut asiakkaaksi -kentän arvoksi muodostuu automaattisesti päiväys 12.09.2033. (Aikuinen-asiakastyypin voimassaoloaika on 120 kuukautta.)

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/5a010b2c-a7fe-4bad-bdd4-7c9c87da0d81)

Vastaava myös esim. Lapsi-asiakastyypin asiakastiedon kopioinnissa. (Lapsi-asiakastyypinkin voimassaoloaika on 120 kuukautta.)

**Comment by emta001** [comment]
Liittynee yhteisön tikettiin [34117](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34117).

**Comment by AnneliO** [comment]
Tähän kaivataan testauksia. :)

**Comment by ajrajala** [comment]
Testailin Vaski-testillä eri asiakaslajeilla ja kaikille näytti muodostuvan kuluva päivämäärä _Tullut asiakkaaksi_ -kenttään.

**Comment by Kati-Helle** [comment]
Toimii myös Helle-testillä. Kopioidulle asiakastiedolle muodostuu Tullut asiakkaaksi -kenttään automaattisesti kopiointipäivän päiväys.

**Comment by ReettaSiili** [comment]
Siilissä testatuilla asiakastyypeillä päivämäärä muodostuu oikein kuluvaksi päiväksi.

**Comment by piiaseme** [comment]
OUTI-testillä testatuilla eri asiakastyypeillä päivämääräksi muodostuu oikein kuluva päivä.

**Comment by Kati-Helle** [comment]
Toimii nyt myös tuotannossa (Koha-päivitys 26.9.2023).
