### ISSUE TITLE
Vaara: Kuittipohjien <<item.content>> -sisällön muokkaus

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#773]
### Tukipyyntö

Olisi tarve saada muokattua esim. PREDUEDGST ja DUEDGST -kuittipohjissa käytössä olevaa <<item.content>> sisältöä. Pääkäyttäjäpalaverissa oli tänään puhetta, että se sisältää vain eräpäivän lisäksi niteen nimen, tekijän ja nidetunnuksen. Tarve olisi esim. kausijulkaisujen ja niteen numeroinnin tiedoille, jotta asiakkaan on helpompi erottaa ilmoituksesta, mikä nide on palautettava ilman nidetunnuksen tarkkailua.

PREDUE- ja DUE-pohjissa <<part_number>>-lisäys onnistuu, mutta olisi hyvä saada muutos tehtyä myös item.content-koostetta käyttäviin pohjiin.

**Comment by lmstrand** [comment]
Testille asetettu croniin:
```
$TRIGGER cronjobs/advance_notices.pl -c -v --itemscontent date_due,t
itle,part_number,enumchron,author,barcode
```
ja croni ajettu Irinan pyynnöstä.

**Comment by pknuuti** [comment]
Mulle kelpaa oikein hyvin. Pääasia on, että numero näkyy.

**Comment by Hanna-Lumme** [comment]
Lumpeet voisi ottaa tämän ominaisuuden myös.

**Comment by Kati-Helle** [comment]
Saisiko ominaisuuden Helleenkin.

**Comment by Tuomas-Kyyti** [comment]
Kyytiin myös.

**Comment by ReettaSiili** [comment]
Ja Siiliin.

**Comment by pirliis** [comment]
Myös OUTIin.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä ja jäin ihmettelemään, miksi tuohon Suureen pop-toivelaulukirjaan ei tullut osan numeroa, vaikka se on samassa kentässä kuin Irinan testin mangassa.
15.09.2023 23:59 Ressun joulu / Schulz, Charles M. 167N01718379
15.09.2023 23:59 Koiramme : 2017 : 12 VK0191726
15.09.2023 23:59 Suuri pop-toivelaulukirja. 146N00513362

Lisäksi: saisiko nuo kellonajat pois? Hämää vaan asiakasta, koska luulee, että kirjastoon voi palauttaa (palautusluukkuun) pikkuisen ennen puoltayötä ja selviää ilman maksuja. Näinhän se ei mene.

**Comment by AnneliO** [comment]
Suuri pop-toivelaulukirjassa on kyllä biblioitems-taulussa tieto part_number-sarakkeessa eli sen puolesta tieto olisi kyllä pitänyt tulla.

**Comment by lmstrand** [comment]
Ei ole testillä biblio-taulussa part_numberissa tietoa Suuri pop-toivelaulukirja 6:lle. Sieltä se haetaan.

**Comment by AnneliO** [comment]
Aaa, joo, katsoin tuotannosta. :)

**Comment by ajrajala** [comment]
Nyt vähän tyhmä kysymys, mutta onko PREDUEDGST ja DUEDGST -pohjissa nykyisessä versiossa mahdollista myös käyttää suoraan items-taulua Template toolkitin kanssa? Tuli vastaan taannoin nimittäin tällainen yhteisön tiketti: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29698

**Comment by AnneliO** [comment]
Kyllähän tuo vähän siltä näyttäis tuon tiketin perusteella. Täällä [Customising notices and slips](https://wiki.koha-community.org/wiki/Customising_Notices_and_Slips) -wikissä annetaan edelleen vain items.content-mahdollisuus.

**Comment by ajrajala** [comment]
Voisin tuota meillä testailla kunhan kerkeän.

**Comment by lmstrand** [comment]
mainitsin patchista myös tikettiin https://github.com/KohaSuomi/Koha/issues/299.

**Comment by lmstrand** [comment]
Lumme, Helle, Kyyti, Siili, OUTI: lisätty --itemscontent date_due,title,part_number,enumchron,author,barcode
Vaara: lisätty --itemscontent title,part_number,enumchron,author,barcode

Näkyy tuotannoissa huomenaamulla muodostuvissa viesteissä, joissa käytetään items.content:ia.

**Comment by IrinaHalminen** [comment]
Vaarassa jäi tänään lähteneistä ilmoituksista puuttumaan eräpäivä. Eli vain kellonaika haluttiin pois. ;)

**Comment by lmstrand** [comment]
Lisätty Vaaran tuotantoon takaisin: --itemscontent date_due,title,part_number,enumchron,author,barcode.

**Comment by lmstrand** [comment]
Tiketissä aiemmin mainittu patch on meillä jo mukana, joten viestipohjan voisi muuttaa käyttämään template toolkitia. Sitten voisi varmaan käyttää pohjissa:
Adding the dateonly filter, will show the date only, without the time part of your selected column. Example: << biblio.timestamp | dateonly >>

Nyt voisi siis käyttää (bugzilla-tiketin mukaan):

2) For DUE and PREDUE notices, set the message body to the following:
Title: [% issue.title %]
3) For DUEDGST and PREDUEDGST notices, set the message body to the following:
Titles:
[% FOREACH i IN issues %]
* [% i.title %]
[% END %]

**Comment by erikamiettinen** [comment]
Myös Kirkes toivoo, että eräpäivämuistutuksissa olisi lisätietona kausijulkaisun numerointi.

**Comment by PiaKusmin** [comment]
Saataisiinko vielä myös Lappiin sama muutos kuin Vaaralla eli ilman sitä kellonaikaa.

**Comment by AnneliO** [comment]
> Saataisiinko vielä myös Lappiin sama muutos kuin Vaaralla eli ilman sitä kellonaikaa.

Tätä Larin mainitsemaan tapaa pitää ensin testata testillä, koska siinä menee viestipohja uusiksi.

```
2) For DUE and PREDUE notices, set the message body to the following:
Title: [% issue.title %]
3) For DUEDGST and PREDUEDGST notices, set the message body to the following:
Titles:
[% FOREACH i IN issues %]
* [% i.title %]
[% END %]
```

**Comment by lmstrand** [comment]
Kirkesiin ja Lappiin lisätty tuotantoon --itemscontent date_due,title,part_number,enumchron,author,barcode

**Comment by AnneliO** [comment]
Testailimme Larin kanssa tuota Template Toolkit -muotoista viestipohjaa, mutta emme saaneet vielä sitä toimimaan.

**Comment by IrinaHalminen** [comment]
Voin ottaa tämän testailutyön alle perjantaina.

**Comment by IrinaHalminen** [comment]
Heheheh, minäköhän perjantaina meinasin testata. Tämä on nyt joka tapauksessa testattu Vaarassa toimivaksi. Tällaisellä lauseella on mukana kausijulkaisujen numerointi ja osan numerot sekä poistuu myös eräpäivän perässä ollut kellonaika 23.59. 

```[%- USE KohaDates -%]
Hei <<borrowers.firstname>>! 

Sinulla on <<count>> erääntyvää lainaa. 

Lainat:[% FOREACH c IN checkouts %][% duedate = c.date_due | $KohaDates %]
    [% c.title %]  [% c.author %] [% c.part_number %] [% c.enumchron %] ([% c.barcode %]) Eräpäivä: [% duedate %][% END %]
```
Kiitos! 👏🏿
