### ISSUE TITLE
OUTI: Nide samaan aikaan lainassa ja saatavana

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#774]
### Mikä vikana?

Asiakkaalla borrowernumber=200378 on lainassa nide 564N26800107 (biblionumber=2238427, itemnumber=3344194), joka näkyy samaan aikaan lainassa ja saatavana-tilassa. 

![image](https://github.com/KohaSuomi/Koha/assets/98814860/31bac956-b77f-49cf-920a-f5013edabc61)

Asiakkaan muutoslokilla eikä niteen tapahtumalokilla näy lainaustapahtumaa, joka on tehty 8.9.2023. Tapahtumalokilla näkyy niteen viimeisin lainaus 8.3.2023 ja palautus 23.6.2023, jotka on tehnyt eri asiakas. 

Vastaava tapaus on ollut myös Kyytissä, tiketti #210

**Comment by AnneliO** [comment]
Koha-Suomen palaveri: Korjataan ainakin niteen onloan-arvo, jolloin nide ei näy saatavana-tilaisena.

**Comment by lasse-koha** [comment]
Onloan-arvo lisätty.

**Comment by pirliis** [comment]
Kiitos! Nyt niteellä ei näy enää Saatavana-tilaa. 

Asiakkaan tiedoissa on kyllä erikoisuus, että on samaan aikaan itselle sekä takaajana että huollettava. :D Olisikohan voinut vaikuttaa tuohon lainakummallisuuteen? Asiakastieto tallennettu Kohaan 2016. Olisikohan lie tullut vaikka Raahen konversiossa.

**Comment by lasse-koha** [comment]
En osaa sanoa mutta voisihan tuon korjata jos vaikka aiheuttaa muitakin virhetilanteita.

**Comment by pirliis** [comment]
> En osaa sanoa mutta voisihan tuon korjata jos vaikka aiheuttaa muitakin virhetilanteita.

Joo, asiakkaan huomautuksissa on tieto virheellisestä huoltajatiedosta, joka pitää korjata.

Suljen tiketin ja toivotaan, ettei vastaavia tule enää. :)
