### ISSUE TITLE
Lumme: Tietue ei poistunut yhdistämisen jälkeen

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#777]
### Mikä vikana?

Lumpeissa virkailija teki tietueen yhtenäistämisen ja tämän jälkeen tietue jäi keikkumaan listoille kuvan mukaisesti. Kun tietuetta yritti avata, Koha ilmoitti: Tietuetta 353518 ei ole tietokannassa. 

![Bugi2](https://github.com/KohaSuomi/Koha/assets/129748294/5f292aad-9969-4a1d-874a-b927b6726e59)

**Comment by emta001** [comment]
Tietue oli jostain syystä jäänyt pyörimään indeksiin poiston jälkeen. Poistin sen käsin seuraavalla rimpsulla:

`curl http://localhost:9200/lumme-prod_biblios/_doc/353518?pretty=true -XDELETE`

Pasi ehdotti, että tehdään näille yksittäisille poistoille oma skriptinsä.

**Comment by emta001** [comment]
Koha-Suomen palaveri 14.9.2023: Näitä tapauksia tulee niin harvoin vastaan, että skriptille ei ole tarvetta.

Eli tältä osin homma on OK. Tiketin voi sulkea.
