### ISSUE TITLE
Lumme: lehtien vastaanotto heittää errorin

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#779]
### Mikä vikana?

Lumpeissa on nyt tapahtunut kahdesti yhdelle työntekijälle ID263135 niin, että kun hän on ollut syöttämässä lehtien tietoja ja painanut tallenna, Koha on heittänyt ruutuun "Virhe, sinulla ei ole oikeuksia tähän sivuun. Kirjaudu sisään toisella tunnuksella." Kyseisellä henkilöllä on kaikki oikeudet kausijulkaisujen käsittelyyn. Ensimmäisen kerran tämä sattui n. kk sitten. Molemmilla kerroilla hänen onnistui laittaa ensin muutama lehti, ennen kuin Koha heitti kyseisen errorin ruudulle. Errorista huolimatta lehden tiedot viivakoodeinen ovat kuitenkin tallentuneet Kohaan.

Ongelman on saanut toistaiseksi kierrettyä niin, että virkailijan oikeudet ottaa pois ja laittaa takaisin, minkä jälkeen virkailija joutuu kirjautumaan uudelleen Kohaan.

**Comment by AnneliO** [comment]
Eli niteen tallennuksen jälkeen tulee ilmoitus puuttuvista oikeuksista. Kohahan pyrkii siinä vaiheessa tälle sivulle: https://lumme-test.koha-suomi.fi/cgi-bin/koha/serials/serials-collection.pl?subscriptionid=8785

Tapahtuuko tämä aina jonkin tietyn lehden kohdalla vai ihan randomisti? Onko kokeiltu selaimen välimuistin tyhjennystä virheen jälkeen? Tai onko koitettu tehdä [uusi profiili Firefoxiin](https://support.mozilla.org/fi/kb/profiilien-hallinta-luo-ja-poista-profiileja)?

**Comment by Hanna-Lumme** [comment]
Ihan randomisti, muista tapauksista ei ole tällä hetkellä tullut ilmoituksia muuten kuin tämän henkilön kohdalla. Ja se on jännä, että se antaa kuitenkin laittaa osan lehdista ennen tuota erroria ihan normaalisti. Minkään tietyn lehden ongelmaksi sitä ei olla pystytty paikantamaan. Tällä kertaa ongelman heitti Tekniikka & Talous -lehden nro 29.

**Comment by AnneliO** [comment]
Tuon Tekniikka & Talous -lehden osalta näyttää olevan ainakin sellainen kummallisuus, että se ehdottaa seuraavaksi vastaanotettavaksi numeroksi numeroa 2023 : 30 ilman arvioitua julkaisuaikaa (julkaisuaikahan oli numeroiden järjestämisen kannalta kriittinen ja pitäisi lisätä numeroa vastaantotettaessa). Eikä tuota mainitsemaasi nroa 29 ole listalla.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/9b2ade48-2302-4dc4-97fb-d56ba2a21d84)

Niteet numeroista 18-29 on kuitenkin olemassa.

Tilausta katsoessa numerointikaava on menossa oikeassa kohdassa:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/25471244-157f-4b1b-b0ea-26ec7df3799b)

**Comment by Hanna-Lumme** [comment]
Ompas outoa... Vastaanotossa se oli ihan normaalisti ehdottanut sitä nro 29 vastaanotettavaksi.

**Comment by emta001** [comment]
Onko tämä vielä ajankohtainen?

**Comment by Hanna-Lumme** [comment]
Ei ole tullut enää uusia tapauksia, joten suljen tiketin.
