### ISSUE TITLE
Useamman samanaikaisen varauksen varaamisessa valinnan poisto tietueelta ei vaikuta ja varaus tehdään silti

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#780]
### Mikä vikana?

Jos asiakkaalle on valinnut yhtäaikaisesti varattavaksi useamman teoksen ja ennen varauksen vahvistamista haluaakin jättää osan niistä varaamatta ja ruksii pois valinnat ei-varattavien kohdalta, järjestelmä varaa silti kaikki. Kuvassa valittu kaksi ensimmäistä, mutta varauksiin tulisi Varaa-napin klikkaamisen jälkeen kuitenkin kaikki neljä teosta.

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/da619d6b-abed-4483-8cc0-db0d1c32c2d2)

Ps. Tälle voi keksiä paremman otsikon. ;)

### Mitä pitäisi tapahtua

Varausten tulisi kohdistua vain listalta ruksattuihin/valittuihin ja/tai pitäisi olla jokin muu mahdollisuus poistaa varattavaksi valittuja ilman lähtöruutuun palaamista.

**Comment by AnneliO** [comment]
Testasin tätä PTFS Europen sandboxissa (versio 23.06) ja sama ongelma toistuu myös siellä.

**Comment by AnneliO** [comment]
En löydä yhteisöstä tähän liittyen tikettejä.

**Comment by atarnus** [comment]
Tätä kun kaiveli niin ongelma on siinä, että nuo ruksaukset ei vaikuta mihinkään. Biblionumberit välittyy lomaketta lähettäessä placerequest.pl:lle täysin piilotetuista kentistä.

Tieto URL:iin menevistä biblionumbereista välittyy tällä name=biblionumber:
`<input type="hidden" name="biblionumber" value="[% biblionumber | html %]"/>`

Tieto varsinaiseen varaukseen menevistä biblionumbereista välittyy holdable_bibsillä:
`<input type="hidden" name="holdable_bibs" id="holdable_bibs" value="[% biblioloo.biblionumber | html %]"/>`

Ja checkbox on sitten täällä:
`<input class="multi_hold_item_checkbox" type="checkbox" checked="checked" title="[% biblioloo.biblionumber | html %]"/>`

Templaten oma form validation tarkistaa vain, että onhan joku ruksittu ja onhan ruksituilla noutopaikka. Jos lähettää lomakkeen merkkaamatta noutopaikkaa ruksimattomalle bibliolle, niin tulee 500 error.

Testasin yhdistämällä holdable_bibsin checkboxin riviin:
`<input class="multi_hold_item_checkbox" name="holdable_bibs" id="holdable_bibs" type="checkbox" checked="checked" value="[% biblioloo.biblionumber | html %]"/>`

Tuo toimi ainakin periaatteessa, mutta pitää vähän konsultoida että miten tämä olisi parasta ratkaista.
Kolmas teos tuossa on jätetty valitsematta, ja se tulee mukaan sivulle, koska biblionumber välittyy urliin, mutta kuten näkyy, sille ei tullut varausta kun holdable_bibs kytkettiin tuohon checkboxiin.

![image](https://github.com/KohaSuomi/Koha/assets/63994411/b3232c3b-2878-4a32-800d-1c8dfcc41893)

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 9.1.2024: Piilotetaan ruksi-sarake.

**Comment by atarnus** [comment]
Piilotuksen pitäisi toimia lisäämällä seuraava koodi intranetuser.css:

```
/* Piilota valintaruudut (1. sarake) monivarauksessa (request.pl) */
#requesttitles th:first-child,
#requesttitles td:first-child { display: none; }
```

Laitettu jo Outi-testille.

**Comment by pknuuti** [comment]
Vaaran testillä ruksi on piilossa varausnäytöllä kuten on tarkoituskin.

**Comment by ReettaSiili** [comment]
Samoin Siilin testillä ruksi-sarake piilottuu nätisti.
Muutoin varausjonot ovat testillä kyllä vähän vinksin vonksin, mutta se tuskin johtuu tästä css:stä, vaan testikannan koostamisesta.

**Comment by Kati-Helle** [comment]
Helle-testilläkin varauksen valintaruutu on piilossa.

Tiedoksi englanninkielinen huomautusikkuna, kun noutokirjaston jättää valitsematta. (Tuotannossa sama.)
Varaa-painikkeen klikkauksesta tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fb59420b-bd63-4729-bfa4-d30a3fbfe538)

**Comment by AnneliO** [comment]
> Tiedoksi englanninkielinen huomautusikkuna, kun noutokirjaston jättää valitsematta. (Tuotannossa sama.) Varaa-painikkeen klikkauksesta tämä 

Tuota tekstiä ei löydy käännöstiedostoista eli ilmeisesti se on taas sellaisia lauseita, joita ei pysty kääntämään. Tein siitä bugin yhteisöön: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35769

**Comment by atarnus** [comment]
Tuo virheilmoitus tulee request.tt:ssä olevasta seuraavasta koodinpätkästä:

```
function checkMultiHold() {

    var selected_bibs = $(".multi_hold_item_checkbox:checked");
    if ( selected_bibs.length > 0 ) {
        // there are biblios selected in the form!
        // verify they have a pickup location selected

        var pickup_not_set = 0;
        selected_bibs.each(function() {
            if ( $(this).closest('tr').find(".multi_pickup_select").val() === "" ) {
                pickup_not_set++;
            }
            else {
                var bibnum = $(this).attr("title");
            }
        });
        if ( pickup_not_set > 0 ) {
            alert( _("Please make sure all selected titles have a pickup location set" + "\n") );
            return false;
        }
    }
    else {
        alert( _("Please select at least one title" + "\n") );
        return false;
    }

    $('#hold-request-form').preventDoubleFormSubmit();

    return true;
}
```

Mikä tätä ei saada käännettäviin lauseisiin, niin voidaan paikallisesti kyllä lisätä tuonne suomi/ruotsi.

**Comment by AnneliO** [comment]
Tein toisesta kääntymättömästä oman tikettinsä: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35770

**Comment by ajrajala** [comment]
Vaskinkin testillä piilotus nyt asetettuna enkä havainnut ongelmia.

**Comment by pirliis** [comment]
> Piilotuksen pitäisi toimia lisäämällä seuraava koodi intranetuser.css:
> 
> ```
> /* Piilota valintaruudut (1. sarake) monivarauksessa (request.pl) */
> #requesttitles th:first-child,
> #requesttitles td:first-child { display: none; }
> ```
> 
> Laitettu jo Outi-testille.

Laitettu myös OUTIn tuotantoon.

**Comment by pknuuti** [comment]
Vaaran tuotantoon lisätty.

**Comment by ReettaSiili** [comment]
Siilin tuotantoon lisätty.

**Comment by PiaKusmin** [comment]
Lapissa nyt myös tuotannossa.

**Comment by Tuomas-Kyyti** [comment]
Kyyti tehty

**Comment by ajrajala** [comment]
Lisätty Vaskin tuotantoon.

**Comment by Kati-Helle** [comment]
Nyt myös Hellen tuotannossa.

**Comment by AnneliO** [comment]
Tämä rimpsu on nyt dokumentoitu [IntranetUserCSS-kirjastoon](https://koha-suomi.fi/dokumentaatio/intranetusercss/#piilota-monivarauksen-teossa-ensimm%C3%A4inen-sarake-eli-valintat%C3%A4p%C3%A4t). Tiketin voi sulkea. :)

**Comment by atarnus** [comment]
Anneli oli tehnyt itse tästä asian pihvistäkin yhteisötiketin: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35771
Kommentoin sinne tarkennusta. Mahd. tarjoan myös patchia myöhemmin.
