### ISSUE TITLE
Palautuskehotuksen maksuriville näkymään teokset, joista kehotus aiheutuu (myös Finnaan)

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#781]
### Kehitysehdotukseni

Aiemmin maksuissa näkyi huomautusrivillä palautuskehotuksen aiheuttaneitten niteitten lista (nidetunnukset linkkeinä). Saisiko ne myös tässä versiossa näkyville?

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/742d7c2e-dd6b-4b0c-bc11-d956993e3c62)

Tämä helpottaisi asiakaspalvelua. Lisäksi tuli toinen kehitysehdotus, joka liittyy samaan asiaan. Asiakas toivoo, että Finnassa näkyisi, mistä teoksista palautuskehotus on tullut. Testasin, että Finnassa näkyy maksun tyyppi ja maksujen kuvaus, mutta palautuskehotuksen osalta teoksia ei ole listattu maksujen kuvaukseen. Myöhästymismaksuissa näin kuitenkin on. Saisiko palautuskehotuksen aiheuttaneiden niteitten tiedot näkyville tässä yhteydessä samalla sekä Kohaan että Finnaan?

![kuva](https://github.com/KohaSuomi/Koha/assets/99409279/95729cc2-0cd3-48f6-963f-c5b220af3b87)

**Comment by AnneliO** [comment]
OUTIssa ei ole ikinä mennyt palautuskehotusmaksun huomautuksiin tietoa niteistä, joten tuo on täytynyt olla jonkin sellaisen palautuskehotusten lähetys -toiminnon ominaisuus, joka on ollut käytössä vain Vaarassa. Muistelimme Emmin kanssa, että teillä oli erilainen toiminto aiemmin.

Mutta sinänsä siis kyllä mielestäni ihan hyvä ehdotus, jos se teknisesti on mahdollista.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 25.9.2023: Käytettävyyden kannalta muutos ei ole mahdollinen. Jos niteet lisätään esimerkiksi maksun kuvaukseen, niin kuvauksesta voi tulla liian pitkä, jos muistutettavia lainoja on kymmeniä.
