### ISSUE TITLE
Automaatti laskee yhteen takaajan ja taattavan maksut

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#782]
### Mikä vikana?

Kyytissä on edelleen ongelmia takaajien ja taattavien maksujen aiheuttaman lainauksen eston kanssa automaateilla lainattaessa. Kyytissä on käytössä asetus NoIssuesChargeGuarantees eli takaaja on lainauskiellossa, jos joku hänen taattavistaan on lainauskiellossa maksujen takia. Sen sijaan asetus NoIssuesChargeGuarantorsWithGuarantees ei ole käytössä.

Takaajan lainatessa lainausautomaatilta lasketaan yhteen takaajan ja taattavan maksut. Ja jos yhteissumma menee yli määritetyn lainakieltorajan, ei takaaja voi lainata. Virkailija-Kohasta lainatessa näin ei tapahdu.

Siis jos lainakieltoraja on 9,99 € ja taattavalla on maksuja 6 e ja takaajalla 4 e, niin automaatti ilmoittaa, että "Asiakasta ei hyväksytty". Takaaja ei mistään (Finnasta) eikä virkailijakaan (Kohasta) suoraan näe syytä tälle lainauksen estolle, vaan pitäisi tietää, että automaatti laskee yhteen kaikkien taattavien ja takaajan maksut. 

Tämä ei ole hyvä toimintatapa, vaikka oma logiikkansa siinäkin on. Automattien pitäisi kuitenkin toimia samalla tavalla kuin virkailija-Kohankin. Etenkin omatoimikirjastoissa tämä aiheuttaa ongelmia turhien lainauksen estojen takia.

Aikaisemmin saatiin onglmavyyhtiä osin korjattua (tiketti [#609](https://github.com/KohaSuomi/Koha/issues/609)). Bugzillassa on tätä liippaavia tikettejä 29755, 33411 ja 32624, mutta nämä kaikki ovat kuulemma jo meillä käytössä.

Onkohan tähän mitään ratkaisua? Toinen vaihtoehto on, että otamme asetuksen NoIssuesChargeGuarantees pois päältä.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 25.9.2023: 

Voisiko automaatin toimittajaa pyytää muuttamaan "Asiakasta ei hyväksytty" -viestin informatiivisemmaksi?

Suosittelemme, että muutatte järjestelmäasetusta toisenlaiseksi.

**Comment by Tuomas-Kyyti** [comment]
Vaihdamme asetusta NoIssuesChargeGuarantees, niin ettei takaaja enää mene lainauskieltoon taattavan maksujen takia.
