### ISSUE TITLE
Ongelma varausten käsittelyssä automaattipalautuksessa?

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#784]
### Mikä vikana?

Yhdestä kirjastosta on muutamaan otteeseen valiteltu, ettei automaatti antaisi lainata niteitä joiden tietueeseen kohdistuu hyllyvaraus. Saimme nyt ensimmäistä kertaa tiedot esimerkkitapauksista ja tutkiessani niitä lokeista, pisti silmään että niteet on palautettu automaatilla ja niihin on jo palautushetkellä kohdistunut varaus/varauksia. Lokien perusteella varaus on automaattipalautuksen yhteydessä saanut suoraan found-arvon 'T' eli olisi ikäänkuin mennyt suoraan kuljetettavaksi. Olen kuitenkin ollut siinä käsityksessä, että automaattiin palautuessa found-arvoksi pitäisi tulla 'P' (processing/käsittelyssä)?

Näissä esimerkkitapauksissa niteet on siis automaattipalautuksen jälkeen päätyneet hyllyyn mistä asiakkaat ovat niitä yrittäneet automaatilla lainata. Oma epäilykseni on, että tuo palautuksessa tapahtunut found-arvon muutos estää niteen lainaamisen automaatilla, jolloin lähinnä nyt ehkä pitäisi selvittää onko palautuksen yhteydessä tapahtunut jokin virhe kun found-arvoksi on tullut 'T' eikä 'P'?

Mistään muualta ei ole vastaavasta ongelmasta valiteltu. Kirjastosta ei ole myöskään tullut vastausta siihen, että toistuuko ongelma jos he tekevät itse hyllyvarauksen, palauttavat niteen ja yrittävät lainata sen.

Automaattitunnukset, jotka kirjastossa on käytössä, ovat PAPKLPA1001 ja PAPKLPA1002. Tiketin lisätiedoissa tarkemmat tiedot esimerkkiniteistä.

### Jotain muuta?

**1. Tapaus**
- Varaus tietueeseen 3996225 tehty 11.9. klo 11:45.
- Automaatilla palautettu tietueen nide 2776346 11.9. klo 15:35.
- Kohan lokien mukaan nide on tuossa palautuksessa tarttunut aiemmin päivällä tehtyyn Vahdon kirjaston varaukseen ja varaus saanut found-arvon T (=kuljetettavana).
- Asiakas yrittänyt lainata niteen automaatilla, muttei onnistunut, nide lainattu tiskillä 11.9. klo 17:47.

**2. Tapaus**
- Tietueeseen 4152428 kohdistunut useampi syyskuun alkupuolella tehty varaus.
- Edellinen asiakas palauttanut tietueen niteen 2595389 automaattiin 10.9. klo 18:15.
- Kohan lokien mukaan nide on tuossa palautuksessa tarttunut jonossa olleeseen varaukseen (varaus Nummeen asiakkaalle 853A3328114) ja varaus on saanut found-arvon T (=kuljetettavana).
- Kun ko. asiakkaan 853A3328114 varausta tarkasteli lokeista ja tietokannasta, ei varauksella näyttänyt kuitenkaan olevan found=T -arvoa vaikka se varauksen muutoslokin mukaan olikin asetettu. 
- Samalla niteelle on kirjautunut vielä toinen palautusyritys 11.9. klo 18:59, mutta lokien mukaan nide ei ole tuossa palautuksessa tarttunut yhteenkään varaukseen.

**Comment by AnneliO** [comment]
Tapaus 1. 

Jos nide jää kiinni toisessa kirjastossa olevaan varaukseen, menee se edelleen found=T. Miksi tässä tapauksessa varausta/nidettä ei ole lähetetty Vahdon kirjastoon vaan asiakas on sen yrittänyt lainata? Siihen on jäänyt kiinni asiakkaan 173857 varaus. Lokilla näkyy, että sen jälkeen asiakkaalle on tärppäytetty toinenkin nide 2023-09-11 18:44:34.

Tapaus 2.

Asiakkaalle 89344 on jäänyt kiinni tuo nide 2595389 ja se on mennyt kuljetettavaksi TUNUun. Mutta kun se on TUNUssa palautettu, onkin varauksessa kiinni toinen nide 2633939.

branchtransfers-taulussa näkyy, että nide on mennyt kuljetettavaksi PAPK->TUNU 2023-09-10 18:15:03 ja niteen kuljetus on päättynyt kommentilla Forced branchtransfer ja kohdekirjasto on PAPK.

statistics-taulussa näkyy, että nide on palautettu PAPK:ssa kahdesti, ensin pois lainasta 2023-09-10 18:15:03 ja sen jälkeen uudelleen 2023-09-11 18:59:59. Sen jälkee se on lainattu 2023-09-11 19:01:17.

Eli jos nyt yhtään pysyn kärryillä, niin kummassakin tapauksessa varaus on jotenkin ohitettu palautus/lähtökirjastossa ja yritetty sitten lainata toiselle asiakkaalle.

**Comment by ajrajala** [comment]
Ihmettelin tuossa tiketin kuvauksessa sitä, miksi automaattipalautuksessa found-arvoksi tuli suoraan 'T' eikä 'P', mutta mitä tuota nyt Turun pk:ssa äsken testasin niin silläkin automaatilla nide sai suoraan arvon 'T'. Eli siinä tapauksessa ei kai noissa Paimion tapauksissa olisi sitten kyse muusta kuin että niteet on palautusautomaatilta päätyneet virheellisesti hyllyyn vaikka olisi pitänyt mennä virkailijalle.

Kysyn nyt tässä samassa yhteydessä kuitenkin, että milloin tuo found='P' oikein tulee? Silloin kun nide palautuu automaatilla noutoyksikössään?

**Comment by AnneliO** [comment]
> Kysyn nyt tässä samassa yhteydessä kuitenkin, että milloin tuo found='P' oikein tulee? Silloin kun nide palautuu automaatilla noutoyksikössään?

Juu, juuri silloin. Se on "processing" ja jos on käytössä HoldsNeedProcessingSIP -järjestelmäasetus, niin varaukset menevät ensin P(rosessing)-tilaan ja vasta Kohassa palautettaessa W(aiting)-tilaan. Tuolla estetään noutoilmoitusten lähtö heti, kun nide palautuu automaattiin.
