### ISSUE TITLE
Virheilmoitus tiedonhaussa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#786]
### Mikä vikana?

Käyttäjällä oli tullut tiedonhaussa vastaan virheilmoitus, joka virheellisesti väitti ettei mitään hakuehtoja olisi annettu (_Virhe: Unable to perform your search. Please try again._), liitteenä kuva tilanteesta. Kuten kuvassa näkyy niin esim. osoiterivillä näkyy kuitenkin annetut hakuehdot.

En tiedä voiko tätä sen enempää tutkia, kun ongelmaa ei saatu enää toista kertaa toistumaan, mutta tiketöin nyt kuitenkin niin jää tästä joku jälki.

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/95a4b3d2-779c-4836-8bf5-73de05871232)

**Comment by AnneliO** [comment]
Tuo virhe viittaa enemmänkin siihen, että Elasticsearch ei ole jostain syystä toiminut. Tuollainen ilmoitus tulee yleensä silloin, kun esim. indeksiä ei ole. Tai indeksissä on jotain vikaa.

**Comment by AnneliO** [comment]
Tuo tietue, jota ilmeisesti pyritään hakemaan on indeksoitu 2023-09-18 12:59:47. Olisiko haku sattunut juuri samalle hetkelle, kun tietuetta on indeksoitu?

**Comment by ajrajala** [comment]
Haku tehty kuvakaappauksen perusteella 18.9. 13:32 eli n. puoli tuntia indeksoitumisen jälkeen.

**Comment by AnneliO** [comment]
Onko tuo klo 13:32 nyt sitten se oikea hakuaika, jos joku kehittäjistä pystyisi vilkaisemaan, näkyykö lokeilla jotain? Ettei esim. kuvakaappausta ole otettu joskus myöhemmin, kun on tullut hiljaisempi hetki? :)

**Comment by ajrajala** [comment]
Varmistan vielä ja kuittaan sitten tähän tikettiin.

**Comment by ajrajala** [comment]
Kuvakaappaus oli tosiaan aika lailla heti otettu, joten hakuaika tosiaan 18.9. n. 13:32.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri: Tilanne vaikuttaa siltä, että Elasticsearchiin ei ole saatu hakuhetkellä yhteyttä. Ongelma saattaa johtua file handle -ongelmasta. Seurataan tilannetta.

**Comment by ajrajala** [comment]
Tänään tuli toiselta käyttäjältä ilmoitus samasta ongelmasta, oli saanut saman virheilmoituksen useamman kerran (ehkä 5 kertaa) tänään. Haut olivat kaikki olleet niteen viivakoodilla tehtyjä hakuja, niteet oli tietueille lisätty/käsitelty viime viikolla. Pääasiassa heti perään tehdyllä uudella haulla tietueet löytyivät, mutta joissakin tapauksissa haku oli pitänyt tehdä useamman kerran ennen kuin tietue löytyi.

Nyt viimeksi virheilmoitus tuli n. 13:55 haulla 538N00699504. Käyttäjä oli aloittanut hakujen tekemisen n. 12:30 jälkeen eli siitä eteenpäin näitä virhetilanteita oli tullut.

Voi olla sattumaa, mutta ainakin pistää silmään että tuo aikaisemmin ilmoitettu virhetilanne sattui maanantaina klo 13:32 ja nyt nämä jälleen maanantai-iltapäivällä. 🤔

**Comment by ajrajala** [comment]
Pääkäyttäjäpalaverissa mainitsinkin, mutta kirjataan tänne vielä tiedoksi että kolmas käyttäjä ilmoitti, että virheilmoitusta on tullut tänä aamuna tavallista enemmän. Lisäksi oli törmätty virheilmoitukseen ”analyyttista hakua ei voi suorittaa” (tjsp, kuvakaappausta ei ollut tarjota).

Eli ilmeisesti monikin on tähän ongelmaan jo aiemmin törmännyt, mutta nyt jostain syystä tänä aamuna virheilmoitusta on esiintynyt vielä aiempaa enemmän.

**Comment by AnneliO** [comment]
Kodo sulki kaikki next-tietokannat palaverin aikana, joten seuraillaan taas hetki, tuleeko tiedonhaussa edelleen virheilmoituksia.

**Comment by ajrajala** [comment]
Pyysin meidän kuvailijoita seurailemaan ja ilmoittelemaan jos havaitsevat vielä virheilmoituksia. Virheilmoitusta "Virhe: Unable to perform your search. Please try again." ei ilmeisesti ole enää tänään havaittu, mutta yhdelle käyttäjälle oli tänään tullut muutaman kerran virheilmoitus ”Analyyttinen virhe. Tarkasta lokitiedot.”

**Comment by AnneliO** [comment]
Tuleeko tuo Analyyttinen virhe siinä samassa kohtaa kuin tuo Unable to perform your search? Vai näkyykö se tietueen perustiedot-näytöllä? Muistelisin, että jotain vastaavia analyyttisiä virheitä on ainakin siellä näkynyt joskus. Liittyy Kohan analyyttisiin tietueisiin, jotka ovat vähän sama asia kuin osakohteet.

**Comment by ajrajala** [comment]
Varmistin vielä ja tuokin virheilmoitus on tullut nimenomaan yrittäessä hakea.

**Comment by ajrajala** [comment]
Kyselin meidän uuden aineiston käsittelijöiltä vieläkö virheilmoituksia on tullut (tekevät hakuja paljon ja törmäsivät aiemmin virheilmoituksiin toistuvasti). Nyt ei kuulemma enää hetkeen ole virheilmoituksia näkynyt. Tulkitsenko oikein, että tähän ongelmaan löytyi syypää ja tiketin voi sulkea?

**Comment by AnneliO** [comment]
Tiedostokahvojen määrää on nostettu, mikä todennäköisesti on vaikuttanut tähän positiivisesti. Mutta ei vielä osata sanoa, oliko se syypää tähän.

**Comment by ajrajala** [comment]
Ilmeisesti satunnaisesti alkuperäistä virheilmoitusta vielä tulee, sillä itselläni tänään 7.11. klo 8:24 virhe tuli kun tein haun 'puuvillatehtaan varjossa'. Uusi haku heti perään tuotti hakutuloksia.

**Comment by AnneliO** [comment]
Testataan seuraavassa versiossa.

**Comment by MikkoLiimatainen** [comment]
En ole onnistunut toistamaan ongelmaa Nextillä. Yritin saada tietueen biblionumber=4283813 indeksin päivittymään muuttamalla niteiden tietoja ja tekemällä samalla haun tietueeseen, mutta näin tuota tilannetta en saanut aikaan. En keksinyt muutakaan keinoa saada aikaan indeksin päivittymistä ja hakua samaan aikaan, mutta en tiedä voiko tällainen tapa edes aiheuttaa alkuperäistä tilannetta. Olisiko tähän jotain testausohjetta, miten tällaisen tilanteen voisi saada muodostettua?

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 2.9.2024: Ei ole mitään kattavaa testausohjetta, mutta onko näitä tullut nykyään tuotannossa?

**Comment by ajrajala** [comment]
Itse en muista enää törmänneeni, mutta laitoin kyselyä vielä meidän kuvailijoille jotka tuohon aikanaan melko usein törmäsivät. Odottelen hetken mitä sieltä kuuluu ja suljen sitten tiketin jos havaintoja ei tule.
