### ISSUE TITLE
Raportti, jolla saa teoksen varausten yhteismäärän tauluista: reserves, old_reserves 

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#788]
### Tukipyyntö

Miten saa haettua tietueen varausten yhteismäärän tauluista reserves JA old_reserves ?

Kokeilemani UNION ALL -hakutapa tuo kyllä tiedot molemmista tauluista. Mutta kun tietue on molemmissa tauluissa, ovat tiedot hakutuloksessa omilla riveillään eivätkä yhteenlaskettuna yhdeksi hakutulosarvoksi.

**Comment by lmstrand** [comment]
```
SELECT all_reserves.biblionumber, Count(all_reserves.biblionumber)as count, title, author
from
(SELECT biblionumber FROM reserves
UNION ALL
SELECT biblionumber FROM old_reserves
) AS all_reserves
left join biblio on all_reserves.biblionumber = biblio.biblionumber
 GROUP BY biblionumber
 order by count DESC;
```

**Comment by lmstrand** [comment]
Lisäämällä loppuun esim. limit 100 saa listattua sata varatuinta .
