### ISSUE TITLE
Lumme: Nide samaan aikaan lainassa ja saatavana

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#789]
### Mikä vikana?

Nyt tuli Lumpeissa esiin tapaus, missä nide on samaan aikaan saatavana ja lainattavana tilassa. Kyseessä nide N0000L595908.

Liittyy Outin ja Kyytin tiketteihin #210 ja #774.

**Comment by AnneliO** [comment]
Lisätään niteelle onloan-arvo.

**Comment by lasse-koha** [comment]
Niteelle lisätty onloan-arvo, nyt ei pitäisi näkyä saatavana.

**Comment by Hanna-Lumme** [comment]
Nyt näkyy oikein, kiitos!
