### ISSUE TITLE
UDK- ja YKL-luokituksen indeksit näkyvät myös Boolen-operaattoreiden valikossa tarkassa haussa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#790]
### Mikä vikana?

Indeksointityöryhmän aikanaan tarkan haun alasvetovalikkoon lisäämä UDK- ja YKL-luokitus näkyvät nykyään jostain syystä myös Boolen operaattorin valintavalikossa.

Vaihtoehdot lisätään valikkoon tällä IntranetUserJs-rimpsulla:

```
/// ALKU ///

/* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
$(document).ready(function() {

    if ( $('html').attr('lang') == 'fi-FI') {
      $("#advsearch-tab-mtype a").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-subloc a").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-agelevel a").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-bib-level a").text("Emokohde/Osakohde"); /* bib-level auktorisoituarvo tarkassa haussa */
      $("#searchterms select").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
      $("#searchterms select").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    }
    else if ( $('html').attr('lang') == 'sv-SE') {
      $("#advsearch-tab-mtype a").text("Materialtyp");
      $("#advsearch-tab-subloc a").text("Underplats");
      $("#advsearch-tab-agelevel a").text("Åldersgränser");
      $("#advsearch-tab-bib-level a").text("Huvudobjekt/Delobjekt");
      $("#searchterms select").append(new Option('YKL-klassification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC-klassification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
    }
    else if ( $('html').attr('lang') == 'en') {
      $("#advsearch-tab-mtype a").text("Material type");
      $("#advsearch-tab-subloc a").text("Sub location"); 
      $("#advsearch-tab-agelevel a").text("Age levels");
      $("#advsearch-tab-bib-level a").text("Child/monographic record");
      $("#searchterms select").append(new Option('Other classification', 'other-classification'));
      $("#searchterms select").append(new Option('UDC classification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
    }

    $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa */
});

/// LOPPU ///
```

Ja se tosiaan näyttää liittymässä tältä:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/f305d568-669d-47b7-85fc-13e55c3728a7)

### Mitä pitäisi tapahtua

Saisiko UDK- ja YKL-luokitusvaihtoehdot lisättyä vain viereiseen valikkoon, josta varsinaisesti valitaan käytettävä indeksi?

### Kuinka toistaa ongelma/asia

1. Mene Tarkkaan hakuun
2. Avaa Boolen-operaattoreiden valikko
3. Huomaa ylimääräiset UDK- ja YKL-vaihtoehdot.

### Jotain muuta?

tarkka haku, valikko

**Comment by johannaraisa** [comment]
Tuossa viitataan kaikkiin select-elementteihin searchtermin alla, joten siksi näkyy booleanissa. Pitää vaihtaa select -> .advsearch luokaksi. Alla on korjattu javascripti:

    /// ALKU ///

    /* Näillä rimpsuilla tehdään tiedonhakuun Indeksointi-työryhmän päättämät muutokset. Asetetaan otsikot eri kielillä aineistotyyppi-, hyllytarkenne- ja ikärajavälilehdille tiedonhaussa. Lisätään alasvetovalikoihin YKL, UDK, Päivittyvä julkaisu ja Kausijulkaisu */
    $(document).ready(function() {

    if ( $('html').attr('lang') == 'fi-FI') {
      $("#advsearch-tab-mtype a").text("Aineistotyyppi"); /* MTYPE auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-subloc a").text("Hyllytarkenne"); /* SUBLOC auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-agelevel a").text("Ikärajat"); /* AGELEVEL auktorisoituarvo tarkassa haussa */
      $("#advsearch-tab-bib-level a").text("Emokohde/Osakohde"); /* bib-level auktorisoituarvo tarkassa haussa */
      $("#searchterms .advsearch").append(new Option('YKL-luokitus', 'other-classification')); /* Lisää uuden valinnan YKL-luokitus */
      $("#searchterms .advsearch").append(new Option('UDK-luokitus', 'udc-classification')); /* Lisää uuden valinnan UDK-luokitus */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Päivittyvä julkaisu', 'bib-level:i')); /*Lisää lisärajoitukset valikkoon uuden arvon */
      $("#subtype select option[value='mus:i'").parent().append(new Option('Kausijulkaisu', 'bib-level:s')); /*Lisää lisärajoitukset valikkoon uuden arvon */
    }
    else if ( $('html').attr('lang') == 'sv-SE') {
      $("#advsearch-tab-mtype a").text("Materialtyp");
      $("#advsearch-tab-subloc a").text("Underplats");
      $("#advsearch-tab-agelevel a").text("Åldersgränser");
      $("#advsearch-tab-bib-level a").text("Huvudobjekt/Delobjekt");
      $("#searchterms .advsearch").append(new Option('YKL-klassification', 'other-classification'));
      $("#searchterms .advsearch").append(new Option('UDC-klassification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Publikation som uppdateras', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Seriell publikation', 'bib-level:s'));
    }
    else if ( $('html').attr('lang') == 'en') {
      $("#advsearch-tab-mtype a").text("Material type");
      $("#advsearch-tab-subloc a").text("Sub location"); 
      $("#advsearch-tab-agelevel a").text("Age levels");
      $("#advsearch-tab-bib-level a").text("Child/monographic record");
      $("#searchterms .advsearch").append(new Option('Other classification', 'other-classification'));
      $("#searchterms .advsearch").append(new Option('UDC classification', 'udc-classification'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Integrating resource', 'bib-level:i'));
      $("#subtype select option[value='mus:i'").parent().append(new Option('Serial', 'bib-level:s'));
    }

    $("#searchterms select option[value='location']").val('loc'); /* Muuttaa location-arvon loc-arvoksi "Hakusanat"-valikossa */
    });

    /// LOPPU ///

**Comment by AnneliO** [comment]
IntranetUserJS:n muutos vaatii checksummauksen ottamisen pois päältä. Olisiko helpoin, jos joku kehittäjistä kävisi muuttamassa tämän kaikkiin kimppoihin? :)

**Comment by AnneliO** [comment]
Kodo tekee muutoksen viikon 40 päivityksen yhteydessä kaikkiin kimppoihin.

**Comment by janPasi** [comment]
Muutos on tehty kaikkiin kimppoihin.

**Comment by AnneliO** [comment]
Kiitos! Suljen tiketin.
