### ISSUE TITLE
OUTI: Vaalan kirjaston kokoelma takaisin varattavaksi (muutos toivotaan ajettavan 28.9.)

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#793]
### Tukipyyntö

Vaalan kirjasto avautuu remontin jälkeen syyskuun ja lokakuun vaihteessa.

Vaalan kirjaston kokoelman saa ajaa takaisin varattavaksi to 28.9. seuraavin ehdoin:

Ajo tehdään niteille
- joiden kotikirjasto on  Vaalan kirjasto (VAPK)  
- jotka ovat Saatavana, ei varattavissa- tilassa (damaged-arvo on 5)

Muutosta ei tehdä, jos nide on kokoelmassa:
- LYLA eli lyhytlaina
- PIKALAINA eli pikalaina
- PIKAPOKKAR eli pikapokkari

Muutosta ei tehdä, jos aineistotyyppi on 
- ESINE

### Jotain muuta?

Tiketissä https://github.com/KohaSuomi/Koha/issues/699 ajettiin Vaalan kirjaston aineisto (tiketissä näkyvin ehdoin) Saatavissa, ei varattavissa-tilaan: damaged-arvo 5 (Saatavana, ei varattavissa).

**Comment by emta001** [comment]
Muutos tehty seuraavasti:

`UPDATE items i LEFT JOIN biblioitems bi ON(i.biblionumber = bi.biblionumber) SET damaged = 0 WHERE i.homebranch = "VAPK" AND i.damaged = 5 AND i.ccode NOT IN("LYLA", "PIKALAINA", "PIKAPOKKAR") AND bi.itemtype != "ESINE";`

Muutos koski 5064 nidettä. Niteet otettu varuiksi talteen tauluun ks_20230927_items_ks793.

**Comment by piiaseme** [comment]
Onkohan mulla jäänyt jotain tästä tiketistä pois, kun tiketin #699 määrä (42 079)eroaa niin kovasti tämän aamun muutettujen määrästä?

Ainakin näillä kahdella niteellä on edelleen Saatavissa, ei varattavissa -tila:
785N10126832
785N10089250
Ne ovat nidetyyppiä 28 VRK eli olisi pitänyt lähteä tuo tila pois.
Tällä on myös edelleen tuo nidetila: 785N00583977 (28 VRK- LN) ja siltä olisi myös pitänyt lähteä se pois.

Etsinkö lisää esimerkkejä, jos se helpottaa selvittämään mitä speksejä mun tiketistä uupui?

**Comment by emta001** [comment]
HIeman ihmettelin kanssa tuota määrää, mutta en sitten kummemmin kyseenalaistanut sitä :sweat_smile: Eli siis tuo ero rupes syntymään noista kokoelmarajauksista. Siinä on nyt jotain mätää. Tällä haulla sain 5673 nidettä:

SELECT count(*) FROM items WHERE homebranch = "VAPK" AND ccode NOT IN("LYLA", "PIKALAINA", "PIKAPOKKAR");

Tällä taas vain:

SELECT count(*) FROM items WHERE homebranch = "VAPK" AND ccode IN("LYLA", "PIKALAINA", "PIKAPOKKAR");

**Comment by emta001** [comment]
Hmm, ongelma lienee siinä, että aika monella niteellä ei ole kokoelmakoodia:
```
MariaDB [outiprod]> SELECT ccode, count(*) FROM items WHERE homebranch = "VAPK" group by ccode;

+------------+----------+
| ccode      | count(*) |
+------------+----------+
| NULL       |    40305 |
| CELIA      |      164 |
| ERA        |      170 |
| FANTASIA   |      835 |
| JANNITYS   |     2529 |
| JOULU      |      134 |
| KAUHU      |      343 |
| LYLA       |      170 |
| NOVELLIT   |      224 |
| ROMANTIIKK |      758 |
| SCIFI      |       62 |
| SOTA       |      454 |
+------------+----------+
```

**Comment by emta001** [comment]
Jeps, tällä tulee enemmän tuloksia:

`SELECT count(*) FROM items WHERE homebranch = "VAPK" AND (ccode IS NULL OR ccode NOT IN("LYLA", "PIKALAINA", "PIKAPOKKAR"));`

Ja noilla laittamillasi niteillä ei tosiaan ole kokoelmakoodia. Jospa ajan vielä toisen ajon, jossa on mukana tuo ccode IS NULL ehto ja katsotaan menikö sitten enemmän oikein?

**Comment by emta001** [comment]
Uusi yritys :D Muutos koski 37566 nidettä, jotka on tallessa aputaulussa ks_20230927_items_ks793_2. Ajo tehty seuraavalla rimpsulla:

`
UPDATE items i LEFT JOIN biblioitems bi ON(i.biblionumber = bi.biblionumber) SET damaged = 0 WHERE i.homebranch = "VAPK" AND i.damaged = 5 AND (i.ccode IS NULL OR i.ccode NOT IN("LYLA", "PIKALAINA", "PIKAPOKKAR")) AND bi.itemtype != "ESINE";`

**Comment by piiaseme** [comment]
Nyt näyttää hyvältä, kiitos tuhannesti :) Pyydän Vaalan kirjastossakin tsekkaamaan huomaavatko mitään poikkeuksia. Kommentoin tänne, jos huomaavat.

**Comment by piiaseme** [comment]
Tarkistelujen perusteella takaisinmuutos onnistui. Suljen tiketin.
