### ISSUE TITLE
TäTi tietueen siirto-ongelma

### ISSUE THREAD

**Issue by janPasi** [KohaSuomi/Koha#797]
### Tukipyyntö

Alunperin Annin avaama tiketti 794 hieman muokattuna tässä uudelleenavattuna:

>Käyttäjä **** ei perjantaista 22.9. lähtien ole saanut siirrettyä tietueita TäTistä Melindaan vaan saa virheviestin 'Unauthorized'. Ongelma jatkuu edelleen tänään maanantiana. Katsoin, että virheviesti viittaisi epäonnistuneeseen autentikointiin, mutta mistä epäonnistuminen voisi johtua?
>
>Käyttäjä ei ole vaihtanut Melinda-tunnuksensa salasanaa, joten se ei ainakaan voi selittää ongelmaa. Virheviesti tulee minkä tahansa tietueen kohdalla siirtoa yrittäessä. Muilla käyttäjillä ongelmia ei ole.
>
>Tietuetta 2393472 yritti nyt viimeksi siirtää.

**Comment by johannaraisa** [comment]
Kysyin Kansalliskirjastolta ja ilmeisesti Melindassa ei ole kyseistä Melinda-tunnusta olemassa millä yritetään siirtoa. Onko tämä siis aikaisemmin toiminut?

**Comment by ajrajala** [comment]
Kuulemma olisi toiminut, mutta kysyin meidän Melinda-tunnusten haltijalta vielä kuvailijan Melinda-tunnuksen ja selvisi että se on tosiaan eri kuin mikä mikropalvelussa TäTi-tunnukseen on linkitettynä. Tunnus kuitenkaan tuskin on itsestään muuttunut, joten vaikea nyt kyllä uskoa että siirto olisi missään vaiheessa toiminut. 🤨 Noh, poistan virheellisen linkityksen ja teen käyttäjän kanssa uuden linkityksen huomenna, suljen sitten tämän tiketin.

**Comment by AnttHeik** [comment]
Sori, että kommentoin tähän väliin, mutta olisiko mahdollista saada jonkin tietueen tietuenumero, jonka kyseinen käyttäjä olisi saanut aiemmin vietyä Melindaan? Voisi tarkistaa, että millä tunnuksella se on mennyt läpi.

**Comment by ajrajala** [comment]
@AnttHeik, tässä olisi ainakin yksi esimerkki: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2387976

**Comment by ajrajala** [comment]
Saatiin tosiaan siirto toimimaan kun päivitettiin mikropalveluun oikea Melinda-tunnus ja salasana. Sellainen seikka selvisi, että tälle käyttäjälle oli TäTi-Melinda-linkitys aikanaan (noin 2 vuotta sitten) tehty ensin väärälle, Auroran aikaiselle Melinda-tunnukselle. Virhe oli nopeasti huomattu ja linkitys tehty uudelleen.

En tiedä voisiko olla siis jotenkin mahdollista, että se aikanaan ensimmäisen kerran mikropalveluun lisätty väärä Melinda-tunnus olisi pompsahtanut jostain takaisin?

**Comment by AnttHeik** [comment]
> @AnttHeik, tässä olisi ainakin yksi esimerkki: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2387976

Kiitokset, tuo esimerkkitietue on näköjään mennyt läpi OUTIn Melinda-tunnuksilla eli siinä on ilmeisesti taustalla jotain muutakin, jonka Johanna varmasti osaa selittää paremmin :)

**Comment by johannaraisa** [comment]
> Saatiin tosiaan siirto toimimaan kun päivitettiin mikropalveluun oikea Melinda-tunnus ja salasana. Sellainen seikka selvisi, että tälle käyttäjälle oli TäTi-Melinda-linkitys aikanaan (noin 2 vuotta sitten) tehty ensin väärälle, Auroran aikaiselle Melinda-tunnukselle. Virhe oli nopeasti huomattu ja linkitys tehty uudelleen.
> 
> En tiedä voisiko olla siis jotenkin mahdollista, että se aikanaan ensimmäisen kerran mikropalveluun lisätty väärä Melinda-tunnus olisi pompsahtanut jostain takaisin?

Hirveän hankala sanoa, ei sen pitäisi mistään sinne itsestään tulla ellei tallentajalla ole ollut jossain selaimen välimuistissa tietoa ja on ajatuksissa poiminut sen.

Voisiko tämän tiketin sulkea, tuo asia taitaa olla selvinnyt jo?
