### ISSUE TITLE
Tarramuutoksia vaativien niteiden kiinnisaaminen

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#799]
### Tukipyyntö

Tähän tikettiin on kuvattu yksi mahdollinen tapa, jolla tarramuutosta kaipaavat niteet saataisiin erilleen palautuksessa, eivätkä ne lähde varauksien kautta seuraavalle asiakkaalle.

Järjestelmäasetusmuutokset:

1. Lisää Auktorisoiduissa arvoissa uusi NOT_LOAN-tila "Tarramuutos", jonka arvo on positiivinen numero (seuraava vapaa positiivinen luku).
2. Lisää  SkipHoldTrapOnNotForLoanValue -järjestelmäasetukseen juuri lisäämäsi arvo, jotta niteet eivät jää palautettaessa kiinni varauksiin.
3. Lisää  UpdateNotForLoanStatusOnCheckin -järjestelmäasetukseen uusi arvopari juuri lisäämälläsi notforloan-arvolla ja sen kaveriksi ONLYMESSAGE. Esim. 11 : ONLYMESSAGE
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/e40e2fc8-318b-4292-a8e2-1603cccafe47)
4. Tarkista palautusautomaatin lajittelusäännöistä, että alertin saavat niteet ohjataan uudelleenkäsiteltäväksi kuten laskutetut niteet.

Toimintatapa, kun tarra pitää muuttaa:
1. Vie tarramuutosta kaipaavat niteet tavalla tai toisella niteiden erämuokkaukseen ja aseta niille Ei lainata -tila Tarramuutokset.
2. Odottele, että asiakas palauttaa lainan.
3. Jos palautus tapahtuu automaattiin, ohjautuu se uudelleen käsiteltäviin, josta virkailija poimii sen ja palauttaa uudelleen Kohassa.
4. Kohassa virkailija saa palautuksessa ilmoituksen _Tarramuutos_ samalla tavalla kuin laskutetusta aineistosta tulee _Laskutettu_-ilmoitus.
5. Virkailija toimittaa tarramuutosta kaipaavan sovittuun paikkaan, jossa niille tulostetaan uudet tarrat.
6. Tarrat tulostava virkailija poistaa käsittelemiltään niteiltä erämuokkauksessa _Tarramuutos_-tilan.
7. Niteet palautetaan, jolloin ne jäävät kiinni mahdollisiin seuraaviin varauksiin.

**Comment by ajrajala** [comment]
Otamme testaukseen Vaskissa tämän tavan, kommentoin tikettiin testaustulokset.

**Comment by ajrajala** [comment]
Vaskissa on testiympäristössä tätä testattu ja todettu hyväksi käytännöksi. Jatkossa pääkirjauksen muutoksen yhteydessä Turun kuvailijoiden ei tarvitse enää tehdä liutaa nidevarauksia + nostattaa niitä jonon kärkeen, joten säästää ihan huomattavasti aikaa runsasniteisten nimekkeiden kohdalla.

Laitetaan uusi erikoistila meille tuotantokäyttöön maanantaina. Nimettiin se Kohaan "Tarramuutos, lähetä omistavaan kirjastoon" ja verkkokirjastoon "Käsiteltävänä".
