### ISSUE TITLE
Lumme/Vastaanotettavien kuljetusten raportti antaa Savonlinnassa virheen 500

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#801]
### Mikä vikana?

Savonlinnassa tulee vastaanotettavissa kuljetuksissa virhe 500. Muissa kirjastopisteissä pelittää. 

Selvittelyssä selvinnyt ainakin että:
- nidetaulussa löytyi ylimääräisiä nidetyyppejä, Lumpeilla esim. LAUTAPELI, PUHECD,VIDEOPELI, MONIVIES, jotka eivät ole valideja nidetyyppejä ja niitä on silti niteille tallennettu
-  kuvailupohjissa on kyllä 952y-kentissä oletusarvoja, jotka eivät ole nykyisiä nidetyyppejä - kannattaa korjata pois

Tällä rapsalla saa kiinni:

SELECT itemnumber
FROM items i 
WHERE i.itype NOT IN(SELECT itemtype FROM itemtypes)

**Comment by emta001** [comment]
Noissa kuivailupohjissa oli muitakin hassuuksia ainakin esineiden osalta, siellä on laitettu liitännäiseksi barcode.pl. Ei se tähän ongelmaan vaikuta, mutta kannattaa siivota pois :D

**Comment by pirliis** [comment]
Korjasin OUTIsta kaksi virheellistä nidetyyppiä pois.

**Comment by Katja-Lumme** [comment]
Lumpeista korjattu ja vastaanotettavien kuljetusten rapsa toimii nyt myös Savonlinnassa😊

**Comment by emta001** [comment]
Tehdään niin, että teen tästä tarkistuspyynnön. Tän tiketin voi sulkea.

**Comment by emta001** [comment]
https://github.com/KohaSuomi/Koha/discussions/811
