### ISSUE TITLE
OUTI: Finvoice-laskutuksessa erikoismerkit katkaisevat laskutetun aineiston ajon

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#803]
### Tukipyyntö

Oulussa Finvoice-laskutuksessa erikoismerkit (esim. š) katkaisevat laskutetun aineiston sisäänluvun. Erikoismerkit ilmeisesti aiheuttavat herkästi ongelmia intimessä. Eli Kohasta laskutusaineisto lähtee ongelmitta, mutta ajo kosahtaa sitten aineistossa olevaan erikoismerkkiin ja, kun ajo on saatu uudestaan liikkeelle, niin ongelmamerkin omaavan laskun tuotetiedot eivät tulostu laskulle vaan ovat katkenneet erikoismerkin kohdalla. 

Monetran järjestelmäpuoli on tähän mennessä korjannut aineiston, jotta laskut saadaan ajettua ja sieltä nyt tiedustellaan, että onnistuisiko meidän päässä tehdä noille erikoismerkeille jotain, jotta niitä ei lähtisi laskutettavan aineiston mukana?

### Jotain muuta?

Laskun tuotetiedot ovat katkenneet tähän kohtaan:

<img width="356" alt="ArticleName Martinovitš" src="https://github.com/KohaSuomi/Koha/assets/98805552/33842bae-b8a8-4ec9-85c0-f4d22d1ef7a8">

**Comment by johannaraisa** [comment]
Milloin tämä on siirtynyt, pitää nähdä se alkuperäinen finvoice?

**Comment by piiaseme** [comment]
Eilen on tapahtunut tämä viimeisin eli 27.9.2023.

(noin kuukausi sitten tapahtui sitä ennen)

**Comment by piiaseme** [comment]
Sitä edellinen erikoismerkistä johtuva laskutuksen tökkis tapahtui 30.8.2023.

**Comment by johannaraisa** [comment]
Teille lisätty finvoiceajon noescape-muutos näyttää myös nuo suhuässät, aikaisemmin se taisi poistaa myös ääkköset. Perl ei osannut käsitellä ääkkösiä oikein sen escapen kanssa, lisäsin nyt koodiin kohdan minkä pitäisi kertoa Perlille merkistön. Pitää vaan nyt muistaa ottaa se noescape-vipu pois.

**Comment by emta001** [comment]
Viety tuotantoon.

**Comment by piiaseme** [comment]
Erikoismerkkitapauksia tulee harvoin laskutuksessa vastaan, niin emme voi testata toimiiko korjaus, joten suljen tiketin. 
Avaamme uudelleen tarvittaessa.
