### ISSUE TITLE
Valutus: Viivalliset ISMN-tunnukset eivät valu TäTistä paikalliskantaan

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#807]
### Mikä vikana?

Antti Heikkiseltä tuli seuraavanlainen korjauspyyntö:

Valutuksessa on ongelma koskien nuotteja, joilla on vain ISMN-tunnus 024-kentässä. Kun paikalliskantaan tulee jonkin nuotin hankintatietue, jossa on vain ISMN-tunnus 024a-kentässä , niin ISMN-tunnus on yleensä ilman viivoja, ja se myös aktivoituu Mikropalvelussa tässä muodossa. Ongelma muodostuu, kun TäTiin tulee valmis tietue, jossa ISMN-tunnus on viivallisessa muodossa. Tällöin tämä tietue ei valu paikalliskantaan, koska aktivointiarvot eivät kohtaa. 020a-kentässä olevalla ISBN-tunnuksella tätä ongelmaa ei kuitenkaan ole. Vaikka paikalliskannassa on hankintatietue, jolla on viivaton ISBN, niin siihen valuu TäTistä päälle tietue, jolla on viivallinen ISBN. Olisi hyvä jos valutuksen saisi toimimaan samalla tavalla myös 024a-kentän suhteen.

En tiedä, voiko tämä liittyä siihen, että 024-kentässä ei välttämättä ole samanlaista väliviivat pudottavaa tietokantatriggeriä kuin 020-kentässä vai siihen, että Kohan indeksi sallii nykyään tallentaa kokonaisen viivallisen tunnuksen 024-kenttään. Aiemmin se ilmeisesti tallensi ne niin, että viivallisesta ISMN-tunnuksesta jäi osa puuttumaan, koska tunnus ei mahtunut indeksikenttään. Annelin kanssa näistä joskus keskusteltiin. Joka tapauksessa olisi hyvä, jos tuon valumisen voisi säätää toimimaan myös tuon viivallisen ISMN-tunnuksen osalta.

### Jotain muuta?

Ongelmasta on keskusteltu Koha-Suomen kuvailuryhmässä keväällä 2023. Korjauspyyntö tehdään vasta nyt, kun on varmistunut, että ongelma on edelleen olemassa eikä kevään -23 versiopäivitys vaikuttanut ongelmaan mitenkään.

**Comment by johannaraisa** [comment]
Saisinko jonkun ISMN-tunnuksellisen tietueen Tätistä esimerkiksi?

**Comment by AnttHeik** [comment]
Tässä olisi ainakin yksi 2395284, joka ei ollut valunut 2.10., joten poimin sen sitten vie/tuo-nappulalla.

**Comment by johannaraisa** [comment]
Tuosta en nyt oikein saa kiinni, sillä tietueella oli ISMN myös viivattomana, ja pitäisi kyllä ensisijaisesti ottaa tarkasteluun tuo millä on indikaattori kolme. Jos löytyy sellainen mikä ei ole valunut, niin katsoisin sitä ennen kuin nappaat kiinni.

**Comment by AnttHeik** [comment]
Ok, minäpä yritän etsiskellä. Voi olla että joutuu odottamaan siihen asti kun saapuu jokin uusi kuvailtu nuotti.

**Comment by AnttHeik** [comment]
Onnistuisko tästä: Poimin valmiin tietueen Melindasta TäTiin: TäTi-id: 2397046, mutta se ei suostu valumaan OUTIin, vaikka tallensin sen pari kertaa TäTissä. OUTIn tietueella 2312374 on aktivointiarvo 024a-kentässä: 9790550138490. 

Tässä on lisäksi sellainen juttu, ettei OUTIn Vie-Tuo-nappikaan löydä TäTistä vastintietuetta, koska hankintatietueella on ainoastaan ykkösindikaattorina 2 024-kentässä. Sama tapahtuu myös TäTin ja Melindan välillä (esim. tietue 2193928), mutta tästä pitäisi tehdä ehkä oma tikettinsä.

**Comment by AnttHeik** [comment]
> Onnistuisko tästä: Poimin valmiin tietueen Melindasta TäTiin: TäTi-id: 2397046, mutta se ei suostu valumaan OUTIin, vaikka tallensin sen pari kertaa TäTissä. OUTIn tietueella 2312374 on aktivointiarvo 024a-kentässä: 9790550138490.
> 
Jaa, tämä olikin valunut seuraavana aamuna klo 5, joten jollain tasolla tuo kuitenkin toimii. Pitää odottaa, että tulee vastaan jokin sellainen ISMN:n sisältävä nuotti, joka on Kirjastopalvelun aamupaketissa.

**Comment by AnttHeik** [comment]
Nyt olisi tällainen esimerkki: TäTissä ID: 2396809 ei ole valunut OUTIssa tietueen 2312402 päälle. Aktivointiarvo on 024a-kentän 9790801507617, aktivoitunut 3.7.2023. TäTin tietue on tullut Kirjastopalvelusta 9.10.

**Comment by johannaraisa** [comment]
En kyllä osaa sanoa miksi tuo on jäänyt välistä, lokeissa ei näy mitään mikä selittäisi virheen. Näyttää, että sitä on käsitelty, mutta jostain syystä ei ole siirtynyt Mikropalvelulle. Lisäsin sen uudestaan käsittelyyn ja näytti siirtyvän, joten se vika ei ole noissa arvoissa vaan jokin katkoo tuota käsittelyä.

**Comment by AnttHeik** [comment]
Ok, pitääpä seurata tätä sitten vielä. Voisiko tähän samaan asiaan liittyä sitten tiketissä https://github.com/KohaSuomi/Koha/issues/845 mainitut viime aikojen valutusongelmat?

**Comment by AnttHeik** [comment]
Tässä on taas kolme täysin samanlaista tapausta. Näkyykö näissäkään mitään erityisempää vai ovatko samanlaisia tapauksia, etteivät vain ole siirtyneet?
TäTi-ID:T:

2401382
2397236
2397234

**Comment by johannaraisa** [comment]
> Tässä on taas kolme täysin samanlaista tapausta. Näkyykö näissäkään mitään erityisempää vai ovatko samanlaisia tapauksia, etteivät vain ole siirtyneet? TäTi-ID:T:
> 
> 2401382 2397236 2397234

Nää vaikuttaa samanlaisilta tapauksilta, yritetään päästä uuteen valutukseen, jospa sillä saisi näitä ongelmia ratkaistua.

**Comment by AnttHeik** [comment]
Hei, tässä olisi tietuesiirtäjästä vastaavanlainen tapaus, jossa ei ole nuotti valunut: OUTI-ID: 2342312 ja TäTi-ID: 2436527. Aktivointiarvona 024a-kentän 9790201815794

**Comment by AnttHeik** [comment]
Tietuesiirtäjä ei näytä löytävän TäTistä tietuetta, jos paikalliskannan hankintatietueessa ei ole viivoja 024a-kentän ISMN-tunnuksessa, mutta TäTin tietueessa on. Tässä nuotissa Kirjastopalvelu on merkinnyt vain viivalliset osan ja kokonaisuuden ISMN-tunnukset tietueeseensa.
 
9790900174550 Repullinen rohkeutta. 3

OUTI-ID: 2351056
TäTi-ID: 2371852

OUTIn tietue:
![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/a39b2016-c74d-4e06-90ad-87a430f35733)

TäTin tietue:
![kuva](https://github.com/KohaSuomi/Koha/assets/116169663/7d215e81-9539-4ee0-bfca-97b7ec81681e)

**Comment by johannaraisa** [comment]
Näköjään jos käyttää haku indeksiä identifier-other, niin se ei osaa yhdistää viivattomia viivalliseen. Ajattelin, että tuo olisi ollut hyvä kun meillä siihen on yhdistetty vain tuo 024a. Vaihdoin sen käyttämään identifier-standard, sillä näyttää toimivan. Tämä tulee seuraavaan päivitykseen.

**Comment by AnttHeik** [comment]
> Näköjään jos käyttää hakuindeksiä identifier-other, niin se ei osaa yhdistää viivattomia viivalliseen. Ajattelin, että tuo olisi ollut hyvä kun meillä siihen on yhdistetty vain tuo 024a. Vaihdoin sen käyttämään identifier-standard, sillä näyttää toimivan. Tämä tulee seuraavaan päivitykseen.

Ok, hyvä että selvisi :)
