### ISSUE TITLE
Finna: PIN-koodin vaihdosta ei tule ilmoitusta, jos sen vaihtaa "Unohditko PIN-koodisi"-linkin kautta

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#809]
### Mikä vikana?

Finnassa PIN-koodin vaihdosta ei tule ilmoitusta, jos PINin vaihtaa "Unohditko PIN-koodisi"-linkin kautta. Jos PINin vaihtaa Finnaan kirjautuneena Omissa tiedoissa, niin silloin PINin vaihdosta saapuu sähköpostiin ilmoitus.

### Mitä pitäisi tapahtua

Kun vaihtaa PINin salasananvaihto-linkin kautta, niin siitä tulisi lähteä asiakkaalle sähköpostiviestinä ilmoitus.

### Kuinka toistaa ongelma/asia

1. Klikkaa Finnan kirjautumisruudussa "Unohditko PIN-koodisi?"-linkkiä
2. Odota, että salasananvaihtoviesti tulee sähköpostiisi ja klikkaa viestissä olevaa linkkiä.
3. Vaihda PIN.

4. Sähköpostiin ei tule ilmoitusta salasanan vaihdosta.

**Comment by rakkyllo** [comment]
Ollaan Vaskissakin ottamassa tätä ilmoitusta käyttöön, joskin hiomme vielä vähän tekstejä. Testasin nyt tähän väliin, että onko meillä tätä samaa ongelmaa, ja näyttäisi siltä että ei ole (meillä on käytössä termi "tunnusluku" PIN-koodin sijaan):

1. Klikkaa Finnan kirjautumisruudussa "Unohditko tunnuslukusi?"-linkkiä ja anna kirjastokortin numero ja sähköpostiosoite.
2. Odota, että tunnusluvun vaihtoviesti tulee sähköpostiisi ja klikkaa viestissä olevaa linkkiä.
3. Vaihda tunnusluku.
4. Sähköpostiin tulee ilmoitus tunnusluvusta vaihdosta.

Otin NotifyPasswordChange-asetuksen pois käytöstä nyt testaamisen jälkeen, koska tekstit ovat vielä vähän työn alla. Mutta tämä siis toimii Vaskissa.

**Comment by AnneliO** [comment]
Tämähän jännää. Miepä testaan vielä OUTIssa omalla kirjastokortilla.

**Comment by AnneliO** [comment]
Ahaa, sain sekä toistettua Piian tapauksen että Roosan.

1. Jos pin-koodi on sama kuin aiemmin, ei viestiä generoidu (kun eihän se vaihdu).
2. Jos pin-koodi on eri kuin aiemmin, viesti generoituu.

@piiaseme oliko sinun testeissä tuo ykköskohdan tapaus eli lisäsit saman pinin kuin aiemmin? :)

**Comment by piiaseme** [comment]
> Ahaa, sain toistettua sekä Piian tapauksen että Roosan.
> 
>     1. Jos pin-koodi on sama kuin aiemmin, ei viestiä generoidu (kun eihän se vaihdu).

> @piiaseme oliko sinun testeissä tuo ykköskohdan tapaus eli lisäsit saman pinin kuin aiemmin? :)

Vaihdoin pinin ihan uuteen.

**Comment by piiaseme** [comment]
Testasin ja nyt minulle tuli ilmoitus  PINin vaihdosta :)

(Jännä, kun vaihdoin viimeeksikin PINin eriksi. Muistan sen siitä, että sanoin Vellulle, että pitää vaihtaa se takaisin vanhaksi samantien, kun kotona ei kuiten muista tuota uuttaa naputella.. )

**Comment by piiaseme** [comment]
PINin vaihto samaan Finnassa- ei tule viestiä
PINin vaihto Finnassa eri PINIksi - tuli viesti

PINin vaihto "Unohditko salasanasi"-linkin kautta eri PINiksi - tuli viesti
PINin vaihto "Unohditko salasanasi"-linkin kautta samaksi PINiksi - ei tule viestiä

PINin vaihto samaan Kohassa - ei tule viestiä
PINin vaihto Kohassa eri PINIksi - tulee viesti

Suljen tiketin, kun homma toimii kuten pitääkin :)
