### ISSUE TITLE
Huollettava-tyyppisen asiakastiedon muokkaus asiakkaiden erämuokkaus -toiminnolla ei onnistu, kun asiakastiedolta puuttuu takaajatieto

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#812]
### Mikä vikana?

Kun huollettava-tyyppisellä (esim. Lapsi, Holhottava) asiakastiedolla ei ole takaajatietoa, asiakastiedon muokkaus Asiakkaiden muokkaus eräajona -toiminnolla ei onnistu. 

Koha ilmoittaa

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ae1bc2c0-fe55-464b-a3d4-841d805807db)

**Comment by emta001** [comment]
Tää on juuri näitä ongelmia, joita takaajattomuus voi aiheuttaa. Samoin kävisi, jos takaajatonta taattavaa yrittäisi muokata muuten. Tähän ei oikeastaan ole mitään järkevää ratkaisua, koska takaajan olemassa olo tarkistetaan aina taattavaa tallentaessa eikä sitä voida kiertää oikeastaan millään tapaa.

**Comment by Kati-Helle** [comment]
Kiitos Emmi tiedosta. 
Tarkoitukseni oli juurikin lisätä takaajattomille huollettava-asiakastyyppisille massana huomautus takaaja-tiedon puuttumisesta.

**Comment by AnneliO** [comment]
Onnistuuko Viesti-toiminnolla huomautuksen lisääminen kuitenkin?

**Comment by Kati-Helle** [comment]
Toimii. Kiitos Anneli vinkistä!
