### ISSUE TITLE
Lappi: Varausten viimeisen noutopäivän siirto

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#816]
### Tukipyyntö

Tarvitaan varausten viimeisten noutopäivien siirto.

Toimipiste: KEPK
Muutos: 11.-15.10. -> 16.10.

Toimipiste ei halunnut käyttää hyväksi Kohan bugia, jolla noutopäiväivä siirtyisi palauttaessa eteenpäin.

**Comment by emta001** [comment]
Laitatko vielä @PiaKusmin tähän määräajan, niin tiedetään milloin muutos on ajettava.

**Comment by PiaKusmin** [comment]
Lisätty. 
Ja saa ajaa hetikin, mutta viimeistään maanantaina, että ehtivät tarkistaa.

**Comment by emta001** [comment]
Muutos tehty seuraavasti:

`UPDATE reserves SET expirationdate='2023-10-16' WHERE branchcode = "KEPK" AND found='W' AND expirationdate BETWEEN '2023-10-11' AND '2023-10-15';`

Ajo koski 44 varausta. Tarkistakaa ensi kerralla montako noita varauksia on, noin pienen määrän voi siirtää myös käsin.

**Comment by PiaKusmin** [comment]
Kiitos! Pyydän tarkistamaan, että on mennyt oikein. Mistä mie voin katsoa nuo tietyn kirjaston noudettavissa olevat varaukset ja siirtää niiden noutoaikaa?

Eräpäivien siirtoon on työkalu ja sen tein itse.

**Comment by emta001** [comment]
> Kiitos! Pyydän tarkistamaan, että on mennyt oikein. Mistä mie voin katsoa nuo tietyn kirjaston noudettavissa olevat varaukset ja siirtää niiden noutoaikaa?
> 
> Eräpäivien siirtoon on työkalu ja sen tein itse.

Eipä sille tosiaan ole työkalua ja tuo on jo määrä, joka on aika työläs siirtää käsin. Joten ihan oikein meni tämä :sweat_smile:

**Comment by PiaKusmin** [comment]
Kaikki kunnossa. Suljen tiketin.
