### ISSUE TITLE
OUTI: Paavolan kirjaston lainaus/palautusautomaatin SIP2-tunnuksen lisäys

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#817]
### Tukipyyntö

Support-postiin on lähetetty Paavolan kirjaston lainaus/palautusautomaatin SIP2-tunnus lisättäväksi OUTIn automaattipalvelinten konfiguraatioon.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle (etelään). Ovat käytössä huomisesta alkaen.

**Comment by pirliis** [comment]
Emmi korjasi tunnuksen ryhmään Outi-Outi, johon se kuuluu. 
Asia kunnossa, joten suljen tiketin.
