### ISSUE TITLE
Käännösvirhe lähtemättömissä ilmoituksissa?

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#824]
### Mikä vikana?

Tänään tuli törmättyä Lumpeissa mahdolliseen käännösvirheeseen. Lähteneen viestin tyyppinä on tekstiviesti, mutta toimitushuomautuksessa puhutaan sähköpostista.

<img width="781" alt="Bugi" src="https://github.com/KohaSuomi/Koha/assets/129748294/3c7dcd3a-3673-48fb-88d0-3f4464d06574">

**Comment by AnneliO** [comment]
Laitatko vielä linkin asiakkaaseen, jolla tämä virheilmoitus näkyy? :)

**Comment by AnneliO** [comment]
Muistelen, että tässä ei ole kyse käännösvirheestä, vaan liittymä näyttää jostain syystä väärän virheilmoituksen. Tietokannassa se on oikein. Mutta tutkitaan tarkemmin, kunhan on esimerkki. :)

**Comment by pknuuti** [comment]
Sama asia Redminessä: https://tiketti.koha-suomi.fi/issues/5572 eli tavallaan ohjelmavirhe.

**Comment by AnneliO** [comment]
Se muistelemani tiketti olikin Redminessä, hyvä kun Päivi löysit sen! :)

**Comment by ajrajala** [comment]
Githubissakin meidän tekemä tiketti, en ole näköjään tehdessä tajunnut että Redminessä olis ollut jo tiksu: https://github.com/KohaSuomi/Koha/issues/329

**Comment by AnneliO** [comment]
> 270638

Tietokannassa message_queue-taulussa asiakkaan viestin kohdalla on failure_code-sarakkeessa *Recipient phone number is invalid or unknown*. Eli tämä vaikuttaa samalta virheeltä kuin noissa kahdessa muussa mainitussa tiketissä. :)

**Comment by Hanna-Lumme** [comment]
No niinpä on. Minäpä suljen tämän triplan, kun niistä on noita muita tikettejäkin. :)  Kiitokset selvityksestä!
