### ISSUE TITLE
Lumme: Tietue indeksoitunut väärin?

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#825]
### Mikä vikana?

Lumpeissa tuli eteen tapaus, jossa Elly Griffitsin kirja "Neiti Marplen jäljillä" kummittelee. Kohasta jos hakee kyseistä kirjaa nimellä, niin näyttöön tulee teksti "Tietuetta 3115169 ei ole tietokannassa". Myöskin jos tuolla biblionumberilla hakee Kohasta, tuloslistaan tulee kyseinen kirja ja kun linkkiä klikkaa, tulee sama virheilmoitus. 

Emmi tarkisti tietueen omalta puoleltaan ja Koha näyttää kyseiselle tietueelle biblionumberia 3135334. MARC:in 999-kentässä näyttäisi olevan tuo 3115169.

### Kuinka toistaa ongelma/asia

Hae Lumme-Kohasta "Neiti Marplen jäljillä" ja klikkaa tietue auki.

**Comment by johannaraisa** [comment]
Selvitettiin Emmin kanssa tätä ja näyttää siltä, että #548 tiketin korjausajo on tässä sekoittanut 999-kentän biblionumberit. Meillä on olemassa skripti jolla tuon 999-kentän voi korjata. Pitäisi selvittää onko samanlainen sekaannus käynyt muissakin kimpoissa.

**Comment by johannaraisa** [comment]
Nämä 999-kentät on nyt korjattu kaikissa kimpoissa ja tietueet on indeksoitu uudestaan.

**Comment by Hanna-Lumme** [comment]
Kiitos!
