### ISSUE TITLE
Hankinnan vastaanotossa haku ei pysy perässä tai väärä haku jää välillä voimaan

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#826]
### Mikä vikana?

Käyttäjiltä on tullut palautetta siitä, ettei hankinnan vastaanotossa viivakoodinlukijalla tehty ISBN-haku löydä teosta vaikka tiedoissa ISBN onkin.

Mikko selvittele, mitä tuossa tapahtuu, ja näyttää käyvän niin että aina kun lukee viivakoodin Hae-kenttään, Koha tekeekin kaksi hakua. Ensimmäisen pelkällä viivakoodin ensimmäisellä numerolla ja toisen koko viivakoodilla. Näyttää siltä, että välillä tuo ensimmäinen virheellinen haku on se, joka jää näkyville.

Myös näppäilemällä hyvin nopeasti voi saada aikaan tilanteen, jossa jää voimaan viimeistä edellinen haku vajaalla ISBN:llä. Sain itse tämän toistettua myös hankinnan vastaanoton sarake-kohtaisessa suodatuksessa. Näppäilin isbn:n 9789523740662 mutta hakutulosten perusteella voimaan jäi haun alkuosa 97895237 (kuva liitteenä). Nopeasti pidemmän nimekkeen kirjoittamalla näyttäisi tapahtuvan helposti myös niin, että jossain vaiheessa hakuun ei "ehdi" enää kaikki syötetyt merkit mukaan (toinen kuva).

Vastaavantyyppistä hakuongelmaa ilmeisesti myös tietueen Perustiedot-näytöllä jo suljetussa tiketissä https://tiketti.koha-suomi.fi/issues/5469. Perustiedot-näytöllä toistuu myös se ongelma, että sarake-kohtaiseen suodatukseen nopeasti kirjoitettu sana ei tule mukaan kokonaan vaan osa merkeistä jää pois.

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/5ed540e4-dddb-4ee4-aefd-33abeb872b68)

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/1fc9927c-4433-412d-b3bb-589d8d631f74)

**Comment by lmstrand** [comment]
Vaarasta on tullut myös palautetta, että joskus viivakoodilla hakemalla haku ei palauta tuloksia, mutta jos viivakoodista poistaa viimeisen numeron, saa oikean hakutuloksen.

**Comment by AnneliO** [comment]
Vastaavasta raportoitu myös [Redmine-tiketissä 5460](https://tiketti.koha-suomi.fi/issues/5460).

**Comment by johannaraisa** [comment]
Pahoin pelkään, ettei tälle ole oikein mitään tehtävissä. Hakukenttä alkaa hakemaan tietoja APIn kautta kun lomakkeeseen kirjoitetaan ja haku käyttää täsmäytyksessä contains-sääntöä, eli jos se sisältää noita merkkejä. Hakuun on mahdollista määritellä, että käytetään exact-sääntöä, mutta sitten ei pysty etsimään esim. nimekkeen osalla jne. 

Tuosta toisesta kuvasta, niin tuo hakutermi näyttää virheelliselle, en usko että löytyy auanturvajan-termiä. Kokeilin itse, että kirjoitin tekijän sukunimen oikein ja etunimeen virheen, se hävitti kyllä hakutulokset.

**Comment by ajrajala** [comment]
Näin vähän ounastelinkin. Mietin vielä, että olisiko sellaisessa kehitysehdotuksessa mieltä että hakukenttä ei alkaisi hakea tietoja heti kirjoittaessa vaan haku pitäisi aktivoida enterillä/haku-painikkeella?

Tuo toinen kuva oli siis esimerkki tilanteesta, jossa nopeasti kirjoitettu pidempi hakusana ei ottanut kaikkia kirjoittamiani merkkejä mukaan. Eli kirjoitin kyllä hakuun "rauhanturvaajan" mutta osa kirjaimista jäi pois.

**Comment by IrinaHalminen** [comment]
Samaa ongelmaa esiintyy myös hyllyvarauslistassa. Ainakin nimekkeen kohdalta suodattaessa kaikki kirjaimet eivät ehdi haun matkaan.

**Comment by lmstrand** [comment]
Sain aikaiseksi rimpsun, jolla voi lisätä suodatuskenttiin ja hakukenttiin viiveen. Toiminnan havainnoinnin helpottamiseksi säädin viiveen 1,3 sekuntiin (rimpsun loppupäässä luku 1300 millisekunteina). 300ms tuntuu olevan ok viive "oikeassa käytössä". Lisätty Vaaran testille.
Muokattuna rimpsua voi varmaankin käyttää muillakin sivuilla, kuten tietueen perusnäkymässä.

```
$(document).ready(function() {
    if (window.location.href.indexOf("acqui/parcel.pl") > -1) {

        $.holdReady(true);
        setTimeout(function() {

            // wait until dt elements are rendered and can be bound to
            $.holdReady(false);
        }, 3000);
        $(document).ready(function() {

            function delay(callback, ms) {
                var timer = 0;
                return function() {
                    var context = this,
                        args = arguments;
                    clearTimeout(timer);
                    timer = setTimeout(function() {
                        callback.apply(context, args);
                    }, ms || 0);
                };
            }

            var inputs = $('input[type="text"]');

            var search_thread = null;

            inputs
                .unbind()
                .bind("input", function(e) {
                    clearTimeout(search_thread);
                    search_thread = setTimeout(function() {
                        var dtable = $("#pending_orders").dataTable().api();
                        var elem = $(".dataTables_filter input");
                        return dtable.search($(elem).val()).draw();
                    }, 1300);
                });

            //dt element wait finished
        });
    }
});
```

**Comment by lmstrand** [comment]
Viive siis odottaa x ms ajan, kunnes kenttään kirjoittaminen on loppunut. Sen jälkeen suoritetaan tauluun suodatus/haku. En havaitse omissa testeissäni tökkimistä tai kirjainten tippumista kenttää täyttäessä.

**Comment by lmstrand** [comment]
Paitsi että rikoin rimpsun jossain vaiheessa tai sitten se ei ole toiminut lainkaan :). No ainakin sen saa lisättyä yleishaku-kenttään taulukon oikeassa ylälaidassa sivutuselementtien jälkeen (suodatin) jos siitä on apua.

**Comment by lmstrand** [comment]
Korjasin rimpsun. En saa itse taulun sarakkeissa oleviin suodatinkenttiin aikaiseksi viivettä. Tietenkin tuota globaalia haku-kenttää voi nyt käyttää niiden sijaan...

**Comment by lmstrand** [comment]
tietueen persunäkymän haku-kentän viive:
```
//tietueen perusnäkymän haku-kentän hakuviive #826
$(document).ready(function() {
    if (window.location.href.indexOf("/catalogue/detail.pl") > -1) {

        $.holdReady(true);
        setTimeout(function() {

            // Setting a delay after page load to catch dt elements
            $.holdReady(false);
        }, 3000);
        $(document).ready(function() {

            function delay(callback, ms) {
                var timer = 0;
                return function() {
                    var context = this,
                        args = arguments;
                    clearTimeout(timer);
                    timer = setTimeout(function() {
                        callback.apply(context, args);
                    }, ms || 0);
                };
            }

            var search_thread = null;
            $(".dataTables_filter input")
                .unbind()
                .bind("input", function(e) {
                    clearTimeout(search_thread);
                    search_thread = setTimeout(function() {
                        var dtable = $("#holdings_table").dataTable().api();
                        var elem = $(".dataTables_filter input");
                        return dtable.search($(elem).val()).draw();
                    },2000);
                });

            //Delayed 
        });

    }
});
```

**Comment by lmstrand** [comment]
Hyllyvarauslistan haku-kentän hakuviive:
```
//hyllyvarauslistan haku-kentän hakuviive #826
$(document).ready(function() {
    if (window.location.href.indexOf("/circ/kohasuomi-pendingreserves.pl") > -1) {

        $.holdReady(true);
        setTimeout(function() {

            // Setting a delay after page load to catch dt elements
            $.holdReady(false);
        }, 3000);
        $(document).ready(function() {

            function delay(callback, ms) {
                var timer = 0;
                return function() {
                    var context = this,
                        args = arguments;
                    clearTimeout(timer);
                    timer = setTimeout(function() {
                        callback.apply(context, args);
                    }, ms || 0);
                };
            }

            var search_thread = null;
            $(".dataTables_filter input")
                .unbind()
                .bind("input", function(e) {
                    clearTimeout(search_thread);
                    search_thread = setTimeout(function() {
                        var dtable = $("#holdst").dataTable().api();
                        var elem = $(".dataTables_filter input");
                        return dtable.search($(elem).val()).draw();
                    },2000);
                });

            //Delayed 
        });

    }
});
```

**Comment by lmstrand** [comment]
Ongelmaan on ratkaisu yhteisössä, jota ei voi tuoda meidän 22.11-versioon. https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35284. Yhteisöversiossa on muutos myös sakarekohtaiseen filtteröintiin. Voin katsoa, onnistuisiko koodin istuttaminen meidän versioon niiltä osin (tai kokeilla jos muutos onnistuisi JS-rimpsuna). Muuten voisi testailla, josko rimpsuista olisi apua tökkimisongelmiin odotellessa versionvaihtoa. Jos testaaminen suorituskyvyn osalta ei onnistu testeillä ja rimpsut eivät testeillä ainakaan riko mitään, niitä voisi testata jonkin kimpan, vaikka Vaskin tuotannossa.

**Comment by lmstrand** [comment]
Tein koha-suomispesifin muutoksen sarakkeiden suodattamiseen. Nyt suodatuskentissä on 500ms viive, ennenkuin suodatus alkaa. Toimii ainakin sarakesuodatuksissa hankinnan vastaanotossa ja esim. asiakashaun sarakesuodatuksessa. Pitäsi toimia missä tahansa muuallakin kohassa sarakesuodatuksessa, paitsi meidän hyllyvarauslistassa ei näy toimivan ja suodatuskentät edelleen tökkivät. Haku-kentän viiveen kanssa korjaus ei auttanut. Sille saa viiveen lisättyä noilla js-rimpsuilla jos on tarvetta. Ainakin hyllyvarauslistalla voisi sitten käyttää viivästettyä haku-kenttää noiden rivisuodatusten sijaan. Tosin hakee silloin koko taulun tiedoista osumia.

**Comment by lmstrand** [comment]
Korjaus siis testeillä.

**Comment by lmstrand** [comment]
Mainintana vielä, että yhteisön korjaus ei viivästytä suodatusta sen mukaan, onko kenttään kirjoittaminen lakannut, vaan suodatustapahtumien "laukaisemisen" lukumäärää pienennettiin yhteisökorjauksessa ja suodatus tapahtuu aina heti alkuun kenttään kirjoittaessa joka tapauksessa, mikä ei ole mielestäni optimaalinen tapa ratkaista ongelmaa ja ei näköjään ratkaise kentän tökköilyongelmaa. Kommentoin havainnon yhteisötikettiin.

**Comment by MikkoLiimatainen** [comment]
Hankinnan vastaanotossa en onnistunut enää toistamaan siellä havaittuja ongelmia. Sekä haku että sarakesuodatukset vaikuttivat toimivan. Tietueen perusnäytöllä sen sijaan sarakesuodatus ei pysynyt kirjoituksen perässä, vaan pudotteli kirjaimia pois.

**Comment by lmstrand** [comment]
Lisäsin filtteröintikenttien responsiivisempaan toimintaan ehdotuksen yhteisötikettiin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35396

**Comment by lmstrand** [comment]
Nuo erilliset "Haku:" -kentät itse taulukkojen yllä, jotka suodattavat kaikesta sisällöstä, vaativat js-rimpsut IntranetUserJS:ään, jotta viive toimii. Lisäsin kaikki kolme (hankinnan vastaanotto, hyllyvarauslista, tietueen perusnäyttö) Vaski-testille IntranetUserJS-asetusten loppuun.

**Comment by lmstrand** [comment]
Ajoin vielä Vaski-testillä hyllyvarauslistan, niin sitäkin voi testata @MikkoLiimatainen.

**Comment by emta001** [comment]
Koha-Suomen palaveri 11.12.2023: Viedään sarake-muutos tuotantoon seuraavassa päivityksessä. Lari testailee vielä js-rimpsuja.

**Comment by lmstrand** [comment]
Hyllyvarauslistaan pitäisi varmaan tehdä oma koodimuutoksensa, koska se on Koha-Suomen oma toteutus ja varmaan siksi tuo yleinen suodatusmuutos ei toimi siinä. IntranetUserJS-rimpsulla voi käyttää yleistä Haku: -laatikkoa taulukon yllä suodattamiseen koko taulun sisällöstä, jolloin kirjaimia ei putoa kyydistä ja ongelmaa voi kiertää näin. Kannattaisi ehkä tehdä oma tikettinsä hyllyvarauslistan sarakekohtaisen suodattamisen ongelmasta.

**Comment by ajrajala** [comment]
Muutokset näyttävät toimivan tuotannossa, joten suljen tiketin. Hyllyvarauslistalla tuo sarakesuodatus lienee vähän harvemmin tarvittu ominaisuus. Voisin kysellä vaikka muilta pääkäyttäjiltä koetaanko tarvetta tehdä siitä tiketti.

**Comment by lmstrand** [comment]
IntranetUserJS-rimpsuissa ilmeisesti ongelma. Avaan tiketin uudelleen.

**Comment by ajrajala** [comment]
Tietueen Perustiedot-näkymässä js näyttää rikkovan haun _Muut kokoelmat_ -välilehdellä.

Kommentoin js:t pois ja tuossa äsken vielä testailin haku-kenttää perustiedot-näytöllä ja tilausten vastaanotossa. En nyt saanut itse asiassa enää toistumaan sellaista ongelmaa, että haku-kentästä putoilisi merkkejä pois, mutta tiketin alkuperäisen kuvauksen perusteella ainakin tilausten vastaanotossa ongelmaa on kuitenkin aiemmin ilmennyt.

**Comment by lmstrand** [comment]
Sain korjattua tuon tietueen perusnäkymärimpsun toimimaan molemmissa kokoelmat-välilehdissä. Jätin Vaski-testille 2,5 sek viiveellä. Korjattu rimpsu 500ms viiveellä korjattuna yllä.

**Comment by ajrajala** [comment]
Jes, nyt näyttäisi toimivan molemmilla välilehdillä. 👍

**Comment by lmstrand** [comment]
Haku-kenttien rimpsuja puuttuu vielä tuotannosta. Lisään tänään illalla.

**Comment by lmstrand** [comment]
Rimpsut siirretty tuotantoihin.
