### ISSUE TITLE
Vaara: Yhteisöasiakkaan noutamattoman varauksen maksu pois

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#827]
### Tukipyyntö

Vaarassa lapsiasiakkaille ei kerry noutamattoman varauksen maksua. Haluaisimme, että myöskään yhteisöasiakkaille ei kertyisi tätä maksua. Muutoksen voi laittaa voimaan heti, kun mahdollista.

**Comment by lmstrand** [comment]
Lisätty croniin 10 00 * * *        $TRIGGER misc/expire_holds.sh LAPSI KOTIPALVEL KAUKOLAINA KIRJASTO YHTEISO

**Comment by IrinaHalminen** [comment]
Kiitos!
