### ISSUE TITLE
OUTI/Vaara: Koha-Ceepos-maksurajapinta ei toimi

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#828]
### Mikä vikana?

Ainakin Oulun kirjastojen Ceepos-kassoilla 10, 11 ja 15 (oletettavasti myös muilla) tulee tämä virheilmoitus, kun lähettää Koha-maksut Ceeposiin:
![image](https://github.com/KohaSuomi/Koha/assets/98814860/62de2e57-7da2-477f-9254-f6db831498fb)

Ehtisikö päivystäjä tarkistamaan, missä ongelma?

Eilen on Iin kirjaston Ceepos-palvelimen osoite ja sertifikaatit muutettu ja ilmeisesti tänään Pudasjärven kirjaston, voisiko ongelma liittyä tehtyihin muutoksiin, vaikkei koske suoraan Oulun kirjastojen Ceeposta.

**Comment by janPasi** [comment]
[2023/10/11 12:51:46] [ERROR] Payment 5195DBB80AFED848DD1F9A03 did not return HTTP200 from server, but 500[2023/10/11 12:51:46] [FATAL] Payment 5195DBB80AFED848DD1F9A03 died with an error: Server closed connection without sending any data back at /usr/share/perl5/Net/HTTP/Methods.pm line 391.
[2023/10/11 12:52:51] [ERROR] Payment 3BB0B5A7E5CFC71811415AC9 did not return HTTP200 from server, but 500[2023/10/11 12:52:51] [FATAL] Payment 3BB0B5A7E5CFC71811415AC9 died with an error: Can't connect to 85.202.201.238:8000 (Connection timed out)

Connection timed out at /usr/share/perl5/LWP/Protocol/http.pm line 50.

**Comment by lmstrand** [comment]
CPU:lta toimitettiin uusi sertifikaatti mikä sallii nämä edustapalvelinmuutokset ja vein sen .pem -muodossa outin tuotantoon. Jatkan huomenna konfiguraatiomuutoksista, kunhan otan selvää, minkä sertifikaatin tuo uusi nyt sitten korvaa :D. Tämän uuden sertifikaatin pitäisi siis ymmärtääkseni toimia kaikille kimpoille ja se on vaihdettava myös muihin ceepos-kimppoihin.

**Comment by lmstrand** [comment]
Ceepos-pluginiin tehtiin äsken muutos sertifikaattien käsittelyyn. Kävin muokkaamassa konfiguraatiot uutta toimintatapaa vastaavaksi ja nyt maksujen pitäisi toimia jo OUTIssa. Ilmoittelen, kun saan sertifikaatit/konfiguraatiot kuntoon muissa Ceepos-kimpoissa.

**Comment by lmstrand** [comment]
Nyt pitäisi toimia Vaarassakin.

**Comment by LeenaKinnunen** [comment]
Lapissa Kemissä myös vastaavantyyppinen tilanne. Eilisestä lähtien Ceepoksen maksu on päättynyt virheeseen: Error: Can't connect to [ip-numero].

**Comment by lmstrand** [comment]
Ongelmia selvitellään CPU:n kanssa. Ceepos-plugin muutettiin käyttämään vain yhtä root-sertifikaattia ja yliheittopalvelimet konfiguroitiin uusiksi. Vanhoihin maksuosoitteisiin ei muutos kohdistunut. CPU:lle raportoitu tarpeesta. Ongelma koskee nyt kaikkia Ceepos-kimppojen toimipisteitä ennenkuin CPU:lta saadaan ratkaisu asiaan (sertifikaattikonfiguraatio kaikkiin kimppojen maksuosoitteisiin yliheitto-osoitteita vastaavaksi ja palomuuriavaukset vanhoihin maksuosoitteisiin). Maksujen kuittautuminen Kohaankin on ilmeisesti jotenkin riippuvainen nyt CPU:n päästä.

**Comment by lmstrand** [comment]
CPU on tehnyt tarvittavat palvelinmuutokset ja nyt näyttäisi yhteydet pelaavan ja maksut kuittautuvan ainakin Lapissa, Vaarassa ja OUTIn vanhoihin palvelinosoitteisiin lähtevissä maksutapahtumissa.

**Comment by pirliis** [comment]
OUTIssa toimii Oulussa. 

Iissä, Pudasjärvellä ja Utajärvellä maksun lähetys Kohasta Ceeposiin toimii, mutta maksetun maksun kuittaus Ceeposista Kohaan ei vielä toimi. Saimme CPU:lta tiedon: _"Ongelma on todennäköisesti työasemien ja kassapalvelimen välisessä liikenteessä. Olemme pyytäneet varmistamaan tarvittavat palomuuriavaukset."_
