### ISSUE TITLE
OUTI: Utajärven kirjaston Ceepos-palvelin vaihtuu 17.10.2023

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#829]
### Tukipyyntö

Utajärven kirjaston Ceepos-palvelin vaihtuu CPU:n palvelimelle 17.10.2023 klo 8-11.

Hoitaisitteko tarvittavat muutokset kuntoon Kohan osalta.

![image](https://github.com/KohaSuomi/Koha/assets/98814860/671af2f1-0f1a-4e58-ae9e-ec8724322ef6)

CPU:n yhteyshenkilöt Mika Wolff ja Juho Kähkönen.

**Comment by lmstrand** [comment]
Uusi yhteysosoite vaihdettu uuden sertifikaatin kera.

**Comment by pirliis** [comment]
Kiitos!
