### ISSUE TITLE
Nidetyyppien indeksointitarve

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#833]
### Kehitysehdotukseni

Nidetyyppejä voi hakea kirjoittamalla hakulauseen (esim. itemtype:28VRK) Kohaan. Käyttäjäystävällisempi tapa olisi saada haku Tarkkaan hakuun nidetyyppien perusteella, mutta se ei toimi, koska indeksointi on väärin.
- itemtype-indeksissä on sekä 942c että 952y
- mtype-indeksissä on 942c ja itype-indeksissä myös 942c
- itypessä olisi loogisempi 952y

Tämä tiketti perustettavalle indeksointi/kuvailuryhmälle.

**Comment by johannaraisa** [comment]
> Tätä muutosta ei ilmeisesti ole vielä tehty? Ajattelin, että tätä olisi voinut testata testillä, mutta vaatii ilmeisesti uudelleenindeksoinnin.

En ole vielä tehnyt ja vaatii kyllä sen uudelleen indeksoinnin, teillä ei tainnut olla redusoitua testiä, joten se kestää hetken.

**Comment by johannaraisa** [comment]
Teen tämän tuonne nexteille, koska jäädytimme muun kehityksen.

**Comment by johannaraisa** [comment]
Muutos tuotu Nextille ja uudelleen indeksointu.
- [ ] Vaski
- [ ] Vaara
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Lumme
- [ ] OUTI
- [ ] Siili
- [ ] Lappi
- [ ] Täti

**Comment by Kati-Helle** [comment]
Helle-nextissä - lisäsin AdvancedSearchTypes-asetukseen rimpsun viimeiseksi arvoksi itemtypes (ohjeessa mainitun itemtype-määrityksen sijaan).

Tarkka haku -toiminnossa on nyt uutuutena Nidetyyppi
![Image](https://github.com/KohaSuomi/Koha/assets/99952449/8864016d-d5c2-4b9d-a64a-b01bb10bd341)

Testasin haun toimivuuden valitsemalla hakuarvoksi: 10 vrk, pika

Hakutulosnäyttöä
![Image](https://github.com/KohaSuomi/Koha/assets/99952449/ed2afe1c-c3bc-45cb-9cf5-cacd210279ce)

**Comment by pknuuti** [comment]
Vaaran nextillä testattu toimivaksi lisäämällä AdvancedSearchTypes-asetukseen rimpsun viimeiseksi arvoksi itemtypes.

**Comment by ajrajala** [comment]
Samoin Vaski-nextillä toimii.

**Comment by Tuomas-Kyyti** [comment]
Toimii Kyytin nextillä.

**Comment by AnneliO** [comment]
Tämä muutos aiheuttaa nyt sen, että Nidetyypit-fasetissa näkyy oikeasti nykyään vain nidetyypit nexteillä. 

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/491a3d33-c2e9-4f7e-995a-c7212bd98bcf)

Pitänee miettiä jokin ratkaisu tähän. Oma Aineistotyypit-fasetti mtype-indeksille?

**Comment by emta001** [comment]
Testattu ja toimii. Suljen tiketin.
