### ISSUE TITLE
OUTI: asiakkaan Tekstiviesti numeroon: -kenttään ei siirry asiakkaan puhelinnumero

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#835]
### Mikä vikana?

Näettekö miksi asiakkaan matkapuhelinnumero ei siirry Tekstiviesti numeroon: -kenttään?

Asiakas
https://outi.koha-suomi.fi/cgi-bin/koha/members/memberentry.pl?op=modify&destination=circ&borrowernumber=277502

### Mitä pitäisi tapahtua

Asiakkaan tietoja muokatessa matkapuhelinnumeron tulisi siirtyä automaattisesti Tekstiviesti numeroon: -kenttään.

### Jotain muuta?

Näitä on tullut OUTIssa muutamia tämmöisiä nyt vastaan. Tässä yhden tapauksen ID 89648 (tämän asiakkaan tiedot ovat nyt ok), mutta jos lokilta näkyy mikä meni pieleen?

Tiketin asiakkaan tilanne on edelleen päällä, jos se auttaa löytämään syyn siirtymisongelmaan.

**Comment by piiaseme** [comment]
Aiemmin tilanne saatiin korjattua siten, että poistettiin matkapuhelinnumero kentästä numero. Lähdettiin pois asiakkaan muokkausnäytöltä. Kun meni uudestaan asiakkaan muokkausnäytölle ja lisäsi matkapuhelinnumeron,  niin numero siirtyi saman tien myös tekstiviestikenttään ja tallennus onnistui.

**Comment by pirliis** [comment]
Tarkennan ongelmaa vielä siltä osin, että matkapuhelin numero kyllä siirtyy Tekstiviesti numeroon -kenttään, mutta kun tallentaa asiakkaan tiedot, numero häviää kentästä.

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [outiprod]> update borrowers set smsalertnumber = mobile where (mobile != '') and (smsalertnumber is null or smsalertnumber = '');
Query OK, 28711 rows affected (13.240 sec)
Rows matched: 28711  Changed: 28711  Warnings: 0
```

**Comment by piiaseme** [comment]
Kiitos Lari :)

Aktivoituuko triggeri jatkossa, vaikka matkapuhelinnumero ei muuttuisi asiakkaan tietojen muokkauksen yhteydessä? 
Ts. vaikuttiko ajo triggerin toimintaan?

**Comment by lmstrand** [comment]
Triggeri toimii samalla tavoin kuin ennenkin. Nyt vain ei pitäisi enää olla tällaisia tilanteita missä puhelinnumero on jo olemassa, mutta sitä ei löydy tekstiviesti numeroon- kentästä. Uuden numeron lisääminen tai vanhan muuttaminen aiheuttaa siirtymisen, kuten ennenkin.

Tietokannassa on viel n. 5000 asiakasta joilla numerot kentissä ovat eri arvoilla, mutta nuo tapaukset pitäisi käydä jotenkin käsin läpi.

**Comment by piiaseme** [comment]
Saisimmeko sinulta raportin tai SQL:n, niin pääsemme käsiksi noihin asiakkaisiin?

**Comment by lmstrand** [comment]
select borrowernumber, mobile, smsalertnumber from borrowers where (mobile != smsalertnumber) and mobile != '';

**Comment by piiaseme** [comment]
Kiitos myös tästä! Koodi siirretty Kohan rapsoihin. Suljen tiketin.

**Comment by piiaseme** [comment]
> Tietokannassa on viel n. 5000 asiakasta joilla numerot kentissä ovat eri arvoilla, mutta nuo tapaukset pitäisi käydä jotenkin käsin läpi.

Onko mahdollista ajaa viesti näille asiakkaille viestikenttään? Mietimme, että 5000 asiakkaan läpikäyminen on aikamoinen homma eikä kaikille voi edes tehdä mitään muuta kuin lisätä viesti, jossa neuvotaan tarkistamaan puhelinnumerot sekä viestiasetukset. 

Jos ajo onnistuu, niin viestikenttään voisi ajaa seuraavan viestin:
_Tarkista onko asiakkaan matkapuhelin- ja tekstiviesti numeroon -kentissä samat numerot. Korjaa tarvittaessa._

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [outiprod]> insert into messages (message_type,message, borrowernumber)
    -> select "L", "Tarkista onko asiakkaan matkapuhelin- ja tekstiviesti numeroon -kentissä samat numerot. Korjaa tarvittaessa.", borrowernumber
    -> from borrowers
    -> where (mobile != smsalertnumber) and mobile != '';
Query OK, 5224 rows affected (2.539 sec)
Records: 5224  Duplicates: 0  Warnings: 0
```

**Comment by piiaseme** [comment]
Kiitos viestiajosta.

Ohjeistimme henkilökuntaa miten toimia, kun vastaan tulee asiakas, jolla tuo viesti on tiedoissaan. Mutta mahdollisuus virheeseen on nykyisellä systeemillä suuri, sillä virkailijan tulee tyhjätä Matkapuhelinnumero-kenttä, tallentaa ja mennä uudestaan tallentamaan numero Matkapuhelinnumero -kenttään, jotta Tekstiviesti numeroon -kenttään lopulta tallentuisi sama numero kuin Matkapuhelinnumero -kentässä.

Näin ohjeistimme henkilökuntaa:
1. Mene asiakkaan tietojen muokkaukseen.
2. Leikkaa asiakkaan matkapuhelinnumero talteen.
3. Tallenna.
4. Klikkaa ok, ilmoitukseen, että viestiasetukset muuttuvat tallennuksen yhteydessä.
5. Mene takaisin asiakkaan tietojen muokkaukseen.
6. Liitä asiakkaan matkapuhelinnumero Matkapuhelinnumero-kenttään.
7. Muista ruksata asiakaalle tekstiviesti-täppä.
8. Tallenna.
....Tässä on monta kohtaa, jotka voi mennä pieleen..

Kokeilimme sitä, että jos leikkaa puhelinnumeron (Tekstiviesti numeroon-kenttä tyhjenee) ja liittää sen takaisin Matkapuhelinnumero-kenttään (Tekstiviesti numeroon-kenttään siirtyy numero) ja tallentaa, niin riittääkö se, mutta tallennuksen jälkeen puhelinnumerotiedot olivat edelleen väärin.

Tässä esimerkki siitä, kun numero siirtyy kenttään, mutta tallennus ei onnistu:

![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/f7d3e89f-0775-4173-880b-147aeebbf83a)
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/13922c3a-7a1f-4e2c-96de-ecc490e4b79b)
Klikkasin kursoria Matkapuhelinnumero-kentässä ja sen jälkeen muualla. Numero siirtyi Tekstiviesti numeroon-kenttään.
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/fed29b07-2de9-45aa-85c8-60c664518e84)
Tallennuksen jälkeen Tekstiviesti numeroon-kentässä on edelleen tähtöset:
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/499e9fc7-d10b-4614-9065-5f014c256423)


Miksi se vaatii sen, että matkapuhelinnumeroa on joko muokattava tai molemmat numerokentät on ensin tallennettava tyhjänä ennen kuin Matkapuhelinnumeron siirto ja tallennus Tekstiviesti numeroon -kenttään onnistuvat? Miksi ei riitä, että kun numero siirtyy Tekstiviesti numeroon-kentään, niin se tallentuu sinne myös?

**Comment by lmstrand** [comment]
Muutosten pitää päätyä tietokantaan, jotta tietokantatriggeri laukeaa ja siirtää numerotiedon Tekstiviesti numeroon-kenttään. Numerotieto tosiaan pitää olla erilainen kun tietokannassa tallessa oleva, jotta triggeri aktivoituu.

**Comment by lmstrand** [comment]
Tuon numerotiedon ei kyllä pitäisi kopioitua virkailijaliittymässä ollenkaan, vaan sen pitäisi näkyä vasta tallennuksen jälkeen Tekstiviesti numeroon-kentässä tallentuneena. Onkohan tiellä jäänyt intranetuserJS-rimpsu paikalleen, joka siirtää numeron matkapuhelin-kentästä.

**Comment by lmstrand** [comment]
Kävin tutkimassa asiaa ja niinhän se on jäänyt tuotantoon tuo rimpsu. Tarkoitus on ollut korvata tuo rimpsu juurikin tuolla tietokantatriggerillä.

**Comment by lmstrand** [comment]
Poistan tuon rimpsun, jotta ei aiheuta sekaannusta, kun numero olevinaan siirtyy. Eli siis asiakastietojen tallennus vaaditaan, jotta saa muutettua Tekstiviesti numeroon-kentän tiedon. Muutos näkyy kentässä vasta tallennuksen jälkeen. Ja puhelinnumeron on siis muututtava matkapuhelin-kentässä entisestä, jotta triggeri tekee hommansa ja kopiointi tapahtuu. Valitettavasti tuota systeemiä ei nyt simppelimmäksi saa.

**Comment by piiaseme** [comment]
Kiitos. Hyvä, ettei numero enää ole siirtyvinään :) Suljen tiketin.
