### ISSUE TITLE
Kentät 386m ja 386a näkymään Perustiedot-näytöllä otsikolla "Tekijän ominaisuudet"

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#841]
### Kehitysehdotukseni

Olisiko tietueen Perustiedot-näyttöä mahdollista säätää siten, että siinä näkyisi tarvittaessa myös 386m- ja a-kentät otsikolla ”Tekijän ominaisuudet” samaan tapaan kuin nyt näkyy 385m- ja a-kenttien tiedot?

386-kentän tietojen pitäisi näkyä perustiedot-näytöllä ehkä näin:
Tekijän ominaisuudet: Ammatti/harrastus: laulaja-lauluntekijät

386-kentän tietoja ei tällä hetkellä näy muussa näytössä kuin Marc-tietueessa, joten ne olisi hyvä saada näkyville. 

### Jotain muuta?

Noin näkyvät 385m- ja a-kentät Perustiedot-näytöllä:
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/43c8b57f-10fc-4de1-9470-fcd3e078c54f)

**Comment by AnneliO** [comment]
Indeksointiryhmä 7.3.2024: Tehdään muutos omaan xslt-tiedostoon. Teetkö Piia tästä myös tiketin yhteisön Bugzillaan, niin tarjotaan samaa muutosta myös sinne.

**Comment by piiaseme** [comment]
Tiketti yhteisölle tehty: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=36489

**Comment by lmstrand** [comment]
Lisäsin tuon kentän samalla tapaa, kuin 385m ja a.

Omalla testilläni sain näkyviin m-kentän. A-kentän pitäisi näkyä samoin kuin 385-a-kentän.

![image](https://github.com/user-attachments/assets/f728370c-0ddf-4d67-8622-e8c355db9c7b)

**Comment by lmstrand** [comment]
Tämä siis testattavissa nexteillä.

**Comment by Kati-Helle** [comment]
Helle-nextissä kenttien arvot näkyvät tietueen perustiedoissa. 
(Kuvailupohjassa ei ole valittuna vaihtoehtoa Muut rajoitukset/Editori.)

**Comment by MikkoLiimatainen** [comment]
Vaski-nextissä näkyy kuten kuuluukin.

**Comment by piiaseme** [comment]
OUTIssa ja Tätissä testattu. Hyvin näkyi.

**Comment by LLK-Hanninen** [comment]
Lastussa näkyy ok nimekkeen perustiedoissa englantia lukuunottamatta:
Kohderyhmä Ikä: lapset (ikäryhmät)
Creator/Contributor Characteristics: Kansallisuus/asuinalue: suomalaiset

**Comment by lmstrand** [comment]
Tämän pitäisi olla ok tuotannossa.

**Comment by Kati-Helle** [comment]
Helle-tuotannossa kentät näkyvät, esimerkiksi tietue biblionumber=826619
![kuva](https://github.com/user-attachments/assets/be8b4b5a-c9e2-4000-928d-a685a906b1cf)

Tietueen 386-kenttä
![kuva](https://github.com/user-attachments/assets/d82b031c-7b07-4cee-a103-d77b021cb321)

**Comment by piiaseme** [comment]
OUTIn tuotannossa näkyvät myös.
