### ISSUE TITLE
Ongelmia Kirjastopalvelun päiväpakettien valumisessa

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#845]
### Mikä vikana?

Vaskissa on havaittu, että Kirjastopalvelulta päivittäin tulevien tietuepakettien valumisessa on ollut häikkää viime aikoina. Paketit ovat aiemmin valuneet luotettavasti, mutta viime viikosta (mahd. 11.10.) lähtien valuneiden tietueiden tarkasteluun tehdyllä raportilla on ollut vähemmän tietueita. Alla kuvailijoiden havaitsemien ongelmatapausten ISBN-numerot:

9789518849493 (tullut TäTiin 11.10.)
9789523452282 (tullut TäTiin 17.10.)
9789511456247 (tullut TäTiin 17.10.)
9789524031332 (tullut TäTiin 17.10.)

Lisäksi tällaiset tapaukset oli ilmoitettu, mutta niihin on manuaalisesti siirretty tiedot tänä aamuna, joten lokissa näkyy siksi TäTi-valutus:
9789511463399 (tullut TäTiin 17.10.)
9782073020932 (tullut TäTiin 12.10.)

**Comment by AnttHeik** [comment]
Katseltiin, että noissa samoissa tietueissa on ollut häikkää myös OUTIssa ja tietueet on poimittu sitten Vie/Tuo-napilla.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 8.1.2024: Tarkoitus siirtyä uuteen valuttamiseen, seurataan, jatkuuko ongelma sen kanssa.

**Comment by AnttHeik** [comment]
OUTIssa on nyt viime aikoina jäänyt taas Kirjastopalvelun tietueita jostain syystä valumatta, esim. tämä 2322868 Mistäköhän se voisi johtua? Kyseisessä tietueessa aktivointiarvona on 035a-kentän (FI-BTJ)7415484 eli sekin on ihan oikein.

**Comment by johannaraisa** [comment]
> OUTIssa on nyt viime aikoina jäänyt taas Kirjastopalvelun tietueita jostain syystä valumatta, esim. tämä 2322868 Mistäköhän se voisi johtua? Kyseisessä tietueessa aktivointiarvona on 035a-kentän (FI-BTJ)7415484 eli sekin on ihan oikein.

En nyt keksi miksi se ei OUTIin olisi valunut, Lumpeeseen oli mennyt. Lokit väittää, että OUTIn rajapinta on ottanut vastaan. Onko datassa tai koodaustasoissa jotain, mikä voisi estää?

**Comment by AnttHeik** [comment]
> > OUTIssa on nyt viime aikoina jäänyt taas Kirjastopalvelun tietueita jostain syystä valumatta, esim. tämä 2322868 Mistäköhän se voisi johtua? Kyseisessä tietueessa aktivointiarvona on 035a-kentän (FI-BTJ)7415484 eli sekin on ihan oikein.
> 
> En nyt keksi miksi se ei OUTIin olisi valunut, Lumpeeseen oli mennyt. Lokit väittää, että OUTIn rajapinta on ottanut vastaan. Onko datassa tai koodaustasoissa jotain, mikä voisi estää?

Ok, ihan perus 8-tason hankintatietue tuo on. Tosin se on kyllä noita outoja Hankintaportaalin yhdistämiä tietueita, mutta en ole aiemmin ajatellut, että vika johtuisi siitä. Vie/Tuo-nappi löytää vastintietueen TäTistä eikä hankintatietueessa ollut mitään tyhjiä kenttiäkään. Viime syksynä tietue on luotu, joten mitään rajoituksiakaan ei pitäisi olla voimassa. Aktivointi oli 6.2.2024. No, poimin tuon muuta kautta nyt.

**Comment by johannaraisa** [comment]
Ok, katsotaan näitä tarkemmin versiopäivityksen jälkeen. Tietuesiirtäjään tulee aika paljon muutoksia, ehkä nuo jää helpommin kiinni.

**Comment by ajrajala** [comment]
Näitä ei ole tullut ilmi, suljenko tiketin ja avataan uudelleen jos ongelmia ilmenee?

**Comment by AnttHeik** [comment]
OUTIssakaan ei ole nyt tullut näitä vastaan, joten minusta voi sulkea.
