### ISSUE TITLE
Asiakkaan maksut näkymään oikein lainausautomaatilla

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#846]
### Tukipyyntö

Nyt kun maksut näkyvät oikein Kohassa asiakkaan lainaustilanteessakin, saisiko tämän näkymään myös automaatilla. Tällä hetkellä automaatti näyttää vain julkisoikeudelliset maksut.

Mikroväylän automaatin osalta tullut tällainen tieto korjauksesta:
"Ongelma tulee siis siinä, että yksityisoikeudellisia maksuja ei tule SIP viestissä automaatille missään kentässä. Joten automaatti ei voi osata laskea yhteen tai erotella niitä. Tässä esimerkki logeista:

24.04.2023 18:47:03 6300020230424 184703 AOJOE_ENO|AA110|AD|
24.04.2023 18:47:03 64 00020230424 184703000000000005000800000009AOJOE_ENO|AA110|AE|BLY|CQY|BV14.6|CC14.99|BD***|PB***|PC***|PIY|AFGreetings from Koha. -- Patron owes 14.60|PA1|

Eli logista tulee julkisoikeudelliset maksut tuossa SIP viestin BV kentässä. Sitten CC kenttä vieressä kertoo mikä on maksimi määrä mitä saa olla, jotta voi lainata.

Joten jos halutaan saada yksityisoikeudellisia maksuja näkyviin, niin ensimmäinen muutos pitäisi tapahtua Kohan päässä. Jopa mielellään silleen, että tuohon BV kenttään tulisi aina yksityisoikeudellisten ja julkisoikeudellisten maksujen yhteyssumma. "

**Comment by janPasi** [comment]
Tuota noin... tavallaan ne näkyy oikein :D Yksityisoikeudellisia maksuja ei voine välittää automaatille, koska muuten automaatti todennäköisesti laskee lainakieltorajan ylityksen väärin. SIP:issa kun on vain yksi kenttä, jossa maksut voidaan ilmaista. Ei taida olla mitään keinoa kertoa automaatille, että osa sen kentän summasta vaikuttaa lainakieltoon ja osa ei.

**Comment by janPasi** [comment]
Pienen varmistelun jälkeen näin se todellakin on. SIP-standardi ei mahdollista tätä ja toteutus vaatisi epästandardeja Koha-Suomi spesifejä muutoksia SIP-palvelimen koodiin. Eli siis käytännössä teknisesti mahdoton.

Voisiko kuitille lisätä tekstin "Lainakieltorajaan vaikuttavat maksut: nn€, katso kaikki avoimet maksusi Finnasta." tjsp? Tai sitten koko se summa pois kuitilta kun ei se pidä paikkaansa.

**Comment by pknuuti** [comment]
Koska tilanne on tämä, suljen tiketin.
