### ISSUE TITLE
Lumme: Ongelma TäTi-tietueessa

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#847]
### Mikä vikana?

Lumpeissa on tullut ongelma tietueen Depraved heart / Patricia Cornwell 978-0-06-256132-9 TäTi-kuvailussa. Jostain syystä tietue on ei suostu menemään Melindaan, vaan heittää errorin "Epäonnistui (Unprocessable Entity {"databaseId":"000000000","recordMetadata":null,"recordStatus":"INVALID","detailedRecordStatus":"UNPROCESSABLE_ENTITY","message":"Error in record. Error while serializing record. Record is invalid: instance.fields[15] is not any of [subschema 0],[subschema 1]","ids":[]})".

Kaksi meidän TäTi-kuvailijaa on yrittänyt korjata tätä, mutta ongelma jatkuu. Yksi ongelma oli mm. sama tietuenumero kuin TäTissä olevalla osakohteella, jonka toinen kuvailija korjasi ja TäTi edelleen heitti yllämainitun errorin. 

![TäTi Error](https://github.com/KohaSuomi/Koha/assets/129748294/a503696a-5b32-4acc-8daf-09177921e51d)

**Comment by johannaraisa** [comment]
Tuon tietueen 520 kentässä on rivivaihtoja, keskellä ja viimeisenä. Rivivaihdot ei kuulu tuonne.

**Comment by Hanna-Lumme** [comment]
Kiitoksia selvityksestä, minäpä välitän tietoa eteenpäin. :)
