### ISSUE TITLE
Lumme: asiakkaan ilmoitusasetuksissa häikkää

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#848]
### Mikä vikana?

Virkailija kertoi, että asiakas ID34751 oli tullut tiskille ja kertonut, että hän oli saanut varauksen noutoilmoitukset tekstiviestin sijaan paperisena tulosteena. Tekstiviestit olivat kuulemma tulleet perille normaalisti vielä aikaisemmin. Virkailija oli katsonut viestiasetukset ja sieltä oli puuttunut täppä.

Katsoin lokeja, niin asiakas oli saanut tekstiviestitse varausilmoitukset vielä 18.8. asti, mutta nyt syyskuussa ilmoitukset olivat lähteneet kirjeellä. Muutoslokistakaan ei näy muuta kuin tuo virkailijan lisäämä täppä tekstiviesti-ilmoituksiin.

**Comment by johannaraisa** [comment]
Selvisi, että tämä liittyy viestiasetusajoon #391 mikä tehtiin 22.8. Kokeilin samoja ajoja testillä ja se näköjään osui tuohon tekstiviestiinkin koska asiakkaalta puuttui sähköposti.

Pitää ajella noita tekstiviestitäppiä takaisin sen perusteella, että asiakkaalla on smsalertnumber.

**Comment by johannaraisa** [comment]
Ajoin tänään aamulla Lumpeeseen, vaikutti 1811 henkilöasiakkaaseen. Osa tosin näytti olevan asiakkuuksia, jotka eivät ole käyttäneet ollenkaan kirjastoa Koha-aikana. Onko muita asiakastyyppejä joille pitäisi ajella?

**Comment by Hanna-Lumme** [comment]
Kiitoksia! 😄 Yhteisöasiakkaille voisi varmaan ajon suorittaa myös, jos esim. päiväkodeilta ja kouluilta on tippunut niitä ilmoitusasetuksia.

**Comment by johannaraisa** [comment]
Ajoin korjauksia nyt myös Siilissä.

**Comment by johannaraisa** [comment]
Avaan tämän uudestaan, ajelen vielä noita muillekin.

**Comment by emta001** [comment]
Näihin katoaviin viestiasetuksiin liittyy vielä tiketti #839 . Katoamiseen vaikuttavat siis JS-rimpsu, sekä asiakastyypin oletusviestiasetukset (tiketissä oon kirjaillut näistä tarkemmin). Joten jos näiden ajojen jälkeen esiintyy vielä katoamisia, niin tuossa on luultavasti ainakin yksi syyllinen.

**Comment by Kati-Helle** [comment]
Ei ainakaan vielä ajoa Helleen. Kommentoin tikettiin, jos ajolle on tarve.

**Comment by johannaraisa** [comment]
Selvä, kimpat kommentoivat tänne jos ajellaan muillekin.

**Comment by johannaraisa** [comment]
Tiedoksi vielä, että niiltä asiakkailta joille tämä poisto on virheellisesti osunut on nollautunut kaikki viestiasetukset. Palautin Lumpeessa ja Siilissä myös ennakkoilmoituksen sähköpostilla, mutta muihin en viitsinyt koskea.

**Comment by AnneliO** [comment]
Viestiasetukset on poistettu tiketissa #391 ja sieltä näkee, kuinka paljon täppiä on poistunut.

**Comment by johannaraisa** [comment]
Nuo ajot nyt voivat lisätä niitä useammalle, koska meillä laitetaan sitä puhelinnumeroa triggerillä siihen smsalertnumber-kenttään ja tuossa voi vain tarkistaa sen onko olemassa ja oletetaan että se halutaan.

**Comment by LeenaKinnunen** [comment]
Lapissa virheita on tullut esille vain pari -kolme, joten ei tehdä meille tässä vaiheessa korjausajoja.

**Comment by pirliis** [comment]
OUTIssa ei ole tehty vielä päätöstä, ajetaanko tekstiviestitäpät vai ei. Varmaan tänään päätämme.

**Comment by pirliis** [comment]
> OUTIssa ei ole tehty vielä päätöstä, ajetaanko tekstiviestitäpät vai ei. Varmaan tänään päätämme.

**Comment by pirliis** [comment]
@johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse? 

Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.

**Comment by pknuuti** [comment]
Jos tuollaisen ajon voi tehdä mitä Pirkko-Liisa ehdotti, sellaisen voisi tehdä Vaarassakin.

**Comment by ajrajala** [comment]
Vaskissa tultiin siihen lopputulokseen, että meille ei tarvitse tehdä ajoa.

**Comment by piiaseme** [comment]
> > @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> > Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.
> 
> Tuo kyllä tarkistaa ensin, että onko asiakkaalla jo saapumisilmoitus aktivoituna, oli se sitten sähköposti tai sms. Ei siis tule tuplia. Voin ajaa teille eka raportin niistä kehen kohdistuu, voitte tarkastella joukosta, että osuuko oikein.

Kiitos, tuo raportti olisi hyvä, niin nähdään mitä ajossa tulisi tapahtumaan :)

**Comment by piiaseme** [comment]
> > @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> > Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.
> 
> Tuo kyllä tarkistaa ensin, että onko asiakkaalla jo saapumisilmoitus aktivoituna, oli se sitten sähköposti tai sms. Ei siis tule tuplia. Voin ajaa teille eka raportin niistä kehen kohdistuu, voitte tarkastella joukosta, että osuuko oikein.

Sitten kun Johanna ehdit, niin meille saa ajaa raportin (tai antaa meille raportin rimpsut).

**Comment by piiaseme** [comment]
> @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> 
> Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.

OUTIlle voi tehdä tämän korjausajon. Jos voi vaikuttaa aikatauluun, niin voisiko sen ajaa maanantaina 29.1.?

**Comment by johannaraisa** [comment]
> > @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> > Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.
> 
> OUTIlle voi tehdä tämän korjausajon. Jos voi vaikuttaa aikatauluun, niin voisiko sen ajaa maanantaina 29.1.?

Onnistuu, ajastan sen maanantaiaamulle?

**Comment by piiaseme** [comment]
> > > @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> > > Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.
> > 
> > 
> > OUTIlle voi tehdä tämän korjausajon. Jos voi vaikuttaa aikatauluun, niin voisiko sen ajaa maanantaina 29.1.?
> 
> Onnistuu, ajastan sen maanantaiaamulle?

Kyllä kiitos :)

**Comment by piiaseme** [comment]
> @johannaraisa, voisiko OUTIssa ajaa varauksen saapumisilmoituksen tekstiviestitäpät vain niille asiakkaille, joilla on numero SMSnumber-kentässä, mutta joilla ei ole täppää kohdassa saapumisilmoitus sähköpostitse?
> 
> Tällä ajolla voisimme ottaa huomioon sen, että tekstiviestejä ei lähtisi ainakaan niille asiakkaille, jotka ovat valinneet saapumisilmoitukset vain sähköpostiin. Samoin tällä ajolla voimme estää sen, että asiakkaille ei lähde turhaan e-kirjeitä.

Ajo tehty nyt aamulla OUTIssa. Näyttäisi menneen kuten pitääkin. Kiitos :)

**Comment by AnneliO** [comment]
Tämän tiketin voinee sulkea?
