### ISSUE TITLE
Tietueen Varaukset-välilehdellä näkyy Tulosta kuitti -painike kaikkien varausten kohdalla

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#849]
### Mikä vikana?

Tietueen Varaukset -välilehdellä on sarake _Tulosta kuitti_ -painikkeelle, joka tulostaa varaus-/kuljetuskuitin. Vaskissa huomattiin, että painike näkyy jokaisen varauksen kohdalla vaikka loogista olisi, että painike näkyisi vain niillä varauksilla jotka ovat joko noudettavissa tai kuljetettavana.

Tutkailin ominaisuuden taustoja Bugzillasta ja [tiketin 29338](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=29338) perusteella toiminnon on ainakin alkujaan suunniteltu ottavan huomioon tämä seikka. Yhteisön sandboxissa kun testasin niin siellä Tulosta-painike näkyy ainoastaan niiden varausten kohdalla, jotka ovat noudettavissa/kuljetettavana ja painike katoaa näkyvistä, mikäli varaukselta peruuttaa Odottaa/Kuljetettavana-tilan.

Onko mahdollisesta, että meillä on tehty jokin muutos (Varaukset-välilehden sivutus tms?), jonka vuoksi painike näkyy meillä jokaisen varauksen kohdalla?

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/74b23408-d402-44f4-8d0a-ef8133c72037)

**Comment by lasse-koha** [comment]
Korjaus tuotu testeille.

**Comment by ajrajala** [comment]
Hyvältä näyttää Vaski-testillä, kuittipainike nyt vain noudettavilla/kuljetettavilla varauksilla:

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/f70b333a-7b58-424b-8e35-83d682975e21)

**Comment by velimarj** [comment]
Myös OUTIn testillä näyttää nyt siltä miltä pitääkin.

**Comment by pknuuti** [comment]
Vaarankin testillä toimii kuten pitääkin eli ei turhia kuittipainikkeita.

**Comment by ajrajala** [comment]
Korjaus tuotu onnistuneesti tuotantoon, suljen tiketin.
