### ISSUE TITLE
Lappi: Poistetun niteen palauttaminen Kohaan lainahistorian kanssa

### ISSUE THREAD

**Issue by MariaJoon** [KohaSuomi/Koha#851]
### Tukipyyntö

Lapin Kohaan pitäisi palauttaa poistettu nide lainahistorian kanssa:  itemnumber 2396388 biblionumber 1874065
(viivakoodi: 241N22032800788).

**Comment by AnneliO** [comment]
Lainahistoriaa sinänsä ei pitäisi tarvia palauttaa, nide näkynee lainahistoriassa taas, kun se on aktiivisessa nidetaulussa.

**Comment by lmstrand** [comment]
MariaDB [lappiprod]> insert into items (select * from deleteditems where barcode = '241N22032800788');
Query OK, 1 row affected (0.013 sec)
Records: 1  Duplicates: 0  Warnings: 0

MariaDB [lappiprod]> delete from deleteditems where barcode = '241N22032800788';
Query OK, 1 row affected (0.007 sec)

**Comment by lmstrand** [comment]
Indeksoin vielä tuon niteen tietueen uudestaan, niin ilmestyi hakutuloksiin. Lainahistoria näyttää tyhjää ja uusintoja ei saa auki nidenäkymässä. En tiedä saako tuota tietoa palautettua.

**Comment by emta001** [comment]
Lainahistoriaa ei saa palautettua. Kun nide poistetaan, myös sen old_issues-taulussa olevat vanhat lainatiedot poistetaan. Ne säilyvät kuitenkin statistics-taulussa.

**Comment by lmstrand** [comment]
Eli tarvittaessa vanhoja laina/lainaajatietoja voi kyllä kaivaa statistics-taulusta tapauskohtaisesti.

**Comment by MariaJoon** [comment]
Tästä niteestä tarvittaisiin siis vielä viimeisin lainaaja -tieto.

**Comment by emta001** [comment]
> Tästä niteestä tarvittaisiin siis vielä viimeisin lainaaja -tieto.

Niin tarvitsisiko tieto palauttaa niin, että se näkyy Kohassa vai riittääkö teille viimeisimmän lainaajan borrowernumber pelkkään omaan tietoon? Koska ensimmäinen vaihtoehto ei onnistu.

**Comment by MariaJoon** [comment]
Riittää, että saamme viimeisen lainaajan borrowernumberin.

**Comment by lmstrand** [comment]
Asiakas-id 488886 näyttäisi olleen viimeinen lainaaja/palauttaja.

**Comment by AnneliO** [comment]
Jos haluatte itse joskus vielä tarkistaa niteen tietoja statistic-taulusta, niin se onnistuu esim. näin:

<pre>select * from statistics where itemnumber = <<Anne nidenumero>></pre>

**Comment by MariaJoon** [comment]
Kiitos avusta! Suljen tiketin

**Comment by MariaJoon** [comment]
Kiitos avusta! Suljen tiketin.
