### ISSUE TITLE
Kahden uuden automaattitunnuksen lisääminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#853]
### Tukipyyntö

Vaskille pitäisi lisätä kaksi uutta automaattitunnusta SIP-palvelimelle. Lisätiedot lähetetty support-postiin.

**Comment by paxed** [comment]
Nämä lisätty, tulevat voimaan ensi yönä

**Comment by ajrajala** [comment]
Kiitos!
