### ISSUE TITLE
Uusi automaattitunnus Kirkes-kirjastoille

### ISSUE THREAD

**Issue by erikamiettinen** [KohaSuomi/Koha#857]
### Tukipyyntö

Kirkes-kirjastoille tarvittaisiin yksi uusi automaattitunnus. Laitoin lisätiedot osoitteeseen support@koha-suomi.fi

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle, ovat huomenna käytössä.

**Comment by erikamiettinen** [comment]
Automaatti ei syystä tai toisesta saa yhteyttä kirjastojärjestelmään, verkkoyhteys ja Koha toimivat.
