### ISSUE TITLE
Konversiossa siirtyneiden yksityisoikeudellisten maksujen mitätöinti

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#858]
### Tukipyyntö

Vaskille tarvittaisiin ajo, joka mitätöisi kannassa olevat, konversiossa siirtyneet yksityisoikeudelliset maksut. Näiden maksujen mitätöinti yksinkertaistaa sitä, miten Vaskin konversiomaksuja voidaan käsitellä tiketin #804 mitätöintiajoissa.

Katsoimme raportilla, että tällaisia maksuja (joissa on maksettavaa jäljellä) on 368 kpl ja ne ovat lähestulkoon kaikki vanhentuneet 3 vuoden vanhenemisajan perusteella. Vain 11 kpl on vielä voimassa, mutta vanhenevat ~puolen vuoden sisällä joten tulimme siihen lopputulokseen että kaikki voitaisiin tässä yhteydessä mitätöidä.

Hain mitätöitävät maksut tällä kyselyllä:

```
SELECT date, description
FROM accountlines
WHERE debit_type_code = 'VASKO' AND description LIKE '%muut maksut%' AND amountoutstanding > 0
```

**Comment by lmstrand** [comment]
Jos näille maksuille loisi uuden oman maksutyypin, ja se asetettaisiin tietokanta-ajolla kyseisiin maksuriveihin, saataisiin ajo suoritettua vanhentamisskriptillä "turvallisesti". Tätä ei voi testata testilläkään, koska maksutyypin kuvaus on anonymisoitu.

**Comment by ajrajala** [comment]
Turvallisesti kuulostaa hyvältä. Loin credit-tyyppeihin maksutyypin VASKO_EXPIRED (maksuissa näkyvä selite: Yksityisoikeudellisten konversiomaksujen mitätöintiajo). Olisiko tuo hyvä?

**Comment by lmstrand** [comment]
Debit typeihin (maksutyypit) pitää saada omansa. Kannattaa varmaan käyttää yhtä ja samaa maksutyyppiä EXPIRED credit-puolella jotta vanhentuneet maksut-raportit osuvat tulevaisuudessa näihinkin maksuriveihin.

**Comment by lmstrand** [comment]
Tietokanta-ajon jälkeen sitten skriptillä tyyliin: write_off_expired_debits.pl -v --debittypes "VASKO_YKSOIK (tai mikälie)" --years 1 -c jotta vuoden tai vanhemmat maksurivit tulisi kaikki käsiteltyä?

**Comment by ajrajala** [comment]
Aivan, uudesta maksutyypistähän tosiaan puhuit koko ajan. Eli maksutyypeissä on nyt tyyppi VASKO_YKSOIK

Saakohan tuolta Credit-tyypeistä kokonaan pois turhaan tehtyä VASKO_EXPIRED-tyyppiä? Käyttöliittymästä käsin pystyi näköjään vaan arkistoimaan, ei kokonaan poistamaan.

**Comment by lmstrand** [comment]
Voin poistaa tietokannasta käsin.

**Comment by lmstrand** [comment]
Poistettu.

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [vaskiprod]> update accountlines set debit_type_code = 'VASKO_YKSOIK' where accountlines_id in
    -> (
    -> SELECT accountlines_id FROM accountlines WHERE debit_type_code = 'VASKO' AND description LIKE '%muut maksut%' AND amountoutstanding > 0
    -> );
Query OK, 368 rows affected (5.707 sec)
Rows matched: 368  Changed: 368  Warnings: 0
```

**Comment by ajrajala** [comment]
Kiitos, näyttää menneen kuten piti. Mites tehdään näiden maksujen mitätöinnin osalta? Vaikka alunperin pyydettiin näiden mitätöimistä nyt heti, niin tokihan nämä voi jättää odottamaan niitä kaikille kimpoille tehtäviä säännöllisiä mitätöintiajoja kun tuo uusi debit-tyyppi voidaan määritellä niihinkin mukaan. Kumpi kuulostaisi järkevämmältä?

**Comment by lmstrand** [comment]
Ihan miten haluatte. Skripti on testattu Vaara-testillä ja toimii kuten pitää, joten voi nytkin jo ajaa. Joka tapauksessa maksurivit päätyvät raporteille, kun niitä aikavälejä käytetään sitten tyyliin 1.1.2023-1.1.2024 niin lukeutuvat mukaan vaikka olisivat nyt tänään mitätöity. Onhan tässä tosin reilu kuukausi asiakkailla aikaa vielä noita maksella turhaan pois vaikkei tarvitsisi...

**Comment by lmstrand** [comment]
Tosin sitten nämä asiakkaat ovat ikäänkuin eriarvoisia muiden maksutyyppien maksurivien omaavien asiakkaiden rinnalla :D en tiedä.

**Comment by ajrajala** [comment]
Kallistuttiin siihen, että ehkä selkeämpää ottaa nämä huomioon samalla kun muitakin vanhentuneita maksuja mitätöidään sen sijaan että lähdettäisiin nyt etukäteen tekemään näille mitätöintiä.

Huomioin tämän uuden maksutyypin siis kun kommentoin Vaskin määritykset yhteisiä mitätöintiajoja varten.
