### ISSUE TITLE
Tekstiviestivalinnan estäminen noutomuistutukselta

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#861]
### Kehitysehdotukseni

Tekstiviestivalinta-mahdollisuus pitäisi poistaa noutomuistutukselta.

Vaskissa on tällä hetkellä estetty tekstiviestivalinta noutomuistutuksilta CSS-piilotuksella Kohasta ja Finnasta. Finna.fi:n kautta tekstiviestivalinta onnistuu. Tavoitteena on, että jos muilla sama tarve estää tekstiviestivalinta noutoilmoitukselle, niin tehdään se jollain järkevämmällä tavalla.

### Jotain muuta?

Sovittu 24.10. pääkäyttäjäpalaverissa, että tehdään tästä tiketti.

**Comment by AnneliO** [comment]
Asiantuntijaryhmä 8.4.2024:

Tutkitaan, onko se mahdollista esim. tiputtamalla sms-message_transport (tjsp.) noutomuistutukselta.

**Comment by lmstrand** [comment]
Vaski-testillä ei näy varauksen noutomuistutukselle sms-täppää. Olette varmaan piilottaneet Finnan päässä css:llä?
![image](https://github.com/user-attachments/assets/58a0cf74-a64b-4a59-9fff-d73f1ca26147)

**Comment by lmstrand** [comment]
SMS-message_transport on siis edelleen paikallaan tietokannassa.

**Comment by lmstrand** [comment]
Aa joo niinhän tuolla alussa mainittiinkin, että CSS:llä piilotettu. Poistanko tuon message_transportin nyt Vaski-testiltä/nextiltä, jos haluatte kokeilla, katoaako se myös tietokantamuokkauksella?

**Comment by sksandel** [comment]
Joo hyvä. Voidaan testata vaikka kummassakin.

**Comment by lmstrand** [comment]
Ajettu:

delete from message_transports where letter_code = 'HOLD_REMINDER' and message_transport_type= 'sms';

Vaski-testillä ja nextillä.

**Comment by rakkyllo** [comment]
Tekstiviestivalinta näyttäisi nyt kadonneen meidän testi- ja next-näkymistä. Siellä pitäisi olla elementti "Hold_Reminder_transport_types_sms", mutta sitä ei näy koodin tasolla.

Tässä vertailuksi **tuotanto** (jossa edelleen CSS-piilotus):

![kuva](https://github.com/user-attachments/assets/d082863b-55f0-479c-9613-fbf4ba73bfbb)

Ja tässä kuvakaappaus, joka näyttää **tilanteen nextillä ja testillä**:

![kuva](https://github.com/user-attachments/assets/e29690d7-a6a5-428d-801a-571bade28f62)

Tuota inputtia Hold_Reminder_transport_types_sms ei siis enää näy testinäkymien puolella. Tämä lienee siis onnistunut kokeilu?

**Comment by lmstrand** [comment]
Joo näin tulkitsen itsekin. Oletan, että täppä on kadonnut testeillä/nexteillä Kohankin puolella.

**Comment by rakkyllo** [comment]
Joo, täppä on kadonnut nextiltä/testiltä samaan tapaan kuin Finnan puolella. Me oltiin piilotettu se CSS:llä Kohankin puolelta, mutta nyt ei ole enää elementtiä, jota piilottaa.

**Comment by AnneliO** [comment]
Tämä tehtävä vielä tuotantoon.

**Comment by iinaniemi** [comment]
Onkohan tätä edistetty? Onko tulossa sitten nextin myötä?

**Comment by lmstrand** [comment]
Sori, tiketti jäänyt roikkumaan. Vaskin tuotantoon ajettu:

MariaDB [vaskiprod]> delete from message_transports where letter_code = 'HOLD_REMINDER' and message_transport_type= 'sms';
Query OK, 1 row affected (0.012 sec)

**Comment by MikkoLiimatainen** [comment]
Tuotannossakin homma ok. Oletan, että tämä on valmis, kun muista kimpoista ei ole tullut kommentoitu kiinnostusta tälle ajolle. Suljen tiketin.
