### ISSUE TITLE
Lumme: Kokoelmakoodisarake + täppä häviää niteiden erämuokkauksen yhteydessä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#863]
### Mikä vikana?

Siivosin Lumpeiden kokoelmakoodeja ja tarkoituksena oli yhdistää kolme eri Kielikurssi-kokoelmakoodia uuden Kielikurssit-kokoelmakoodin alle. Tein niteiden muutoksen eräajon normaalisti, mutta kun työn tuloksia tarkasteli, listasta oli hävinnyt kokonaan Kokoelmakoodi-sarake, kuten myös sen täppä. Tämä ongelma ilmeni ainoastaan tällä uudella koodilla. 

Nidetietoja katsoessa kokoelmakoodi oli kuitenkin muuttunut normaalisti Kielikurssit-kokoelmakoodiksi.

Kokoelmakoodi näkyy normaalisti, kun kokoelmakoodin muutti Kielikurssit keskitasoksi. 
![Koodi näkyy](https://github.com/KohaSuomi/Koha/assets/129748294/11692d8e-d511-4e2f-bc39-7bbe21de0734)

Kokoelmakoodi puuttuu, kun kokoelmakoodin on vaihtanut pelkäksi Kielikurssiksi.
![Koodi puuttuu](https://github.com/KohaSuomi/Koha/assets/129748294/203e2682-b982-480b-bb51-906b43635e29)

### Kuinka toistaa ongelma/asia

Tee niteiden erämuokkaus ja valitse muokkaustilanteessa Kokoelmakoodi-sarakkeesta Kielikurssit. Valmiin taustatyön tiedoista puuttuu kokonaan Kokoelmakoodi-sarake.

**Comment by AnneliO** [comment]
Voisko liittyä tähän #769 tiketissä raportoituun ongelmaan?

**Comment by Hanna-Lumme** [comment]
Voisi ehkä jollain tavalla liittyä tähän - muokkauksessa en tehnyt muutoksia noihin täppiin ja ongelma tosiaan toistuu vain tämän yhden kokoelmakoodin kohdalla. 🤔 Venkslasin noita koodeja edes takaisin muutaman kerran ja sama juttu jokaisella kerralla. Poistin myös koodin ja tein sen uudestaan, eikä sekään auttanut ongelmaan.

**Comment by Hanna-Lumme** [comment]
Kokeilin tuota niteiden erämuokkausta uudelleen Kielikurssit-kokoelmakoodin alle ja tällä kertaa kokoelmakoodi näkyi normaalisti. 

![Kielikurssit](https://github.com/KohaSuomi/Koha/assets/129748294/183e5562-30ae-4539-bcca-e2da4df3702e)

**Comment by Hanna-Lumme** [comment]
Testasin tätä uudelleen tuotannossa tekemällä uuden kokoelmakoodin "Testikoodi". Ongelma toistui niteiden erämuokkauksessa jälleen - alkulistauksessa ns. vanha kokoelmakoodi näkyi normaalisti, mutta muutosraportissa sarake oli jälleen kadonnut. Kun vaihdoin ns. uudesta kokoelmakoodista niteen alkuperäiseen kokoelmakoodiin, alkulistauksessa koodia ei näkynyt, mutta muutosraportissa näkyi jälleen muutos vanhaan koodiin. 

Ongelma näyttäisi syntyvän uusien kokoelmakoodien kanssa ja varsinkin, jos muutoksia alkaa ajamaan heti koodin tekemisen jälkeen.

**Comment by AnneliO** [comment]
[Taustatyön raportilla](https://lumme.koha-suomi.fi/cgi-bin/koha/admin/background_jobs.pl?op=view&id=3308681) näkyy Tarkastele-toiminnolla tällainen virheilmoitus:

Uncaught ReferenceError: allColumns is not defined
    hideAllColumns https://lumme.koha-suomi.fi/intranet-tmpl/prog/js/pages/batchMod_22.1100001.js:115
    <anonymous> https://lumme.koha-suomi.fi/intranet-tmpl/prog/js/pages/batchMod_22.1100001.js:154
    jQuery 2
[batchMod_22.1100001.js:115:24](https://lumme.koha-suomi.fi/intranet-tmpl/prog/js/pages/batchMod_22.1100001.js)
    hideAllColumns https://lumme.koha-suomi.fi/intranet-tmpl/prog/js/pages/batchMod_22.1100001.js:115
    <anonymous> https://lumme.koha-suomi.fi/intranet-tmpl/prog/js/pages/batchMod_22.1100001.js:154
    jQuery 2

**Comment by AnneliO** [comment]
Tuo siis näkyi ainakin silloin, kun tilanne oli ns. päällä. Nyt kun raporttia menee katsomaan, näkyy sarakkeet oikein.

**Comment by emta001** [comment]
Miun testiympäristö ei nyt suostu tämän kanssa yhteistyöhön. Kun tarkastelee tuota työtä, tulee vain ilmoistus ettei niteitä muokattu eikä tuota tarkempaa viestiä tule. Kannasta kun kattoo, niin kokoelmakoodi on kyllä muuttunut :D

**Comment by AnneliO** [comment]
> Voisko liittyä tähän #769 tiketissä raportoituun ongelmaan?

Mulla on edelleen kutina, että tämä ongelma liittyy tähän samaan ja varsinkin siellä mainittuu bugzilla-tikettiin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32477.

**Comment by emta001** [comment]
> > Voisko liittyä tähän #769 tiketissä raportoituun ongelmaan?
> 
> Mulla on edelleen kutina, että tämä ongelma liittyy tähän samaan ja varsinkin siellä mainittuun bugzilla-tikettiin https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=32477.

Hyvin mahdollisesti liittyykin, en vaan nyt saa toistumaan tätä Hannan skenaariota omilla testeillä. Vois tehdä niin, että tutkitaan ja korjataan tuo #769 ja katsotaan sitten poistuuko tämäkin ongelma.

**Comment by emta001** [comment]
Laitan tämän tilaksi "Odottaa".

**Comment by emta001** [comment]
Toin tikettiin #769 korjauksen testeille. Sitä testatessa vois samalla testailla oliko siitä apua myös tähän ongelmaan.

**Comment by Hanna-Lumme** [comment]
Testailin eri kokoelmakoodien muuttamista ja nyt näkyi kokoelmakoodi alussa ja lopussa paria poikkeusta lukuunottamatta. Kokoelmakoodi hävisi yhdestä nuorten urheilukirjasta ensimmäisessä listauksessa ennen kokoelmakoodin vaihtoa, mutta kun kokeilin uudelleen samalla kirjalla, niin koodi näkyi oikein.

Pysyvämpi tapaus oli kuvan mukainen tapaus, joka ei suostu näyttämään ensimmäisessä listassa kokoelmakoodia.
![Eläimet - puuttuu](https://github.com/KohaSuomi/Koha/assets/129748294/f74b5ef8-c6a1-4b79-b62d-586dbb83cc3d)

**Comment by Hanna-Lumme** [comment]
En saanut ongelmaa toistumaan, suljen tiketin.
