### ISSUE TITLE
Huoltajille lähetettävä viesti

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#865]
### Kehitysehdotukseni

Vaarassa on lapsiasiakkaita, joille on merkitty tietoihin viesti/huomautus: "Kela-kortti esitettävä". Tämä on tehty sellaisissa tilanteissa, että lapselle on tehty kortti, mutta hetun oikeellisuutta ei ole voitu tarkistaa mistään dokumentista. Lainaustilanteessa huomautus näkyy asiakastiedoissa, mutta käytännössä jos lainataan automaatilla huomautuksella ei ole merkitystä.

Nyt haluttaisiin lähettää viesti tällaisen lapsen vastuuhenkilölle (huoltajalle), jonka huollettavalla on mainittu huomautus. Bywater on tehnyt emailer pluginin, jota voisi testata Vaaran testillä. Sitä varten tarvitaan raportti, jolla saadaan haettua ne vastuuhenkilöt, joille viesti pitäisi lähettää.

**Comment by lmstrand** [comment]
Bywaterin plugin on poistettu heidän repositoriostaan, varmaankin mahdollisten väärinkäytösten/spämmin lähettelyn välttämiseksi. Viestiajon voi silti tehdä raporttia ja viestipohjaa vasten devaajan toimesta palvelimella ajettavalla skriptillä.

**Comment by AnneliO** [comment]
Tässähän on myös sellainen vaihtoehto, että jos kaupungilla on käytössä jokin uutiskirje/viestityspalvelu, niin raportin avulla voi poimia sinne tarvittavat sähköpostiosoitteet. Ihan vaan pistän tällaisena varasuunnitelmana ylös. :)

**Comment by atarnus** [comment]
Tässä olisi ainakin jonkinlainen SQL-lauseke. Se hakee huoltajan borrowernumberin ja emailin niiltä lapsiasiakkailta, joilta löytyy viesteistä tai opacnotesta 'Kela-kortti'. Voi lisätä huoltajan tietoja tuohon tai hakea muistakin mahdollisista huomautuskentistä. Hashatyn salasanan voin tuohon myös asettaa. (Salasanan toimimisen vuoksi piti vähän pyöritellä tuota lauseketta ettei mitään tietoa pääse tulemaan läpi väärällä.) Ja jos tarvisi hakea vain messages-taulusta niin tuo lauseke olisi selkeästi yksinkertaisempi, mutta ilmeisesti huomautuksia oli myös borrowers-taulussa.

```
SELECT b.borrowernumber, b.email
  FROM borrower_relationships AS r
       INNER JOIN borrowers AS b
       ON r.guarantor_id = b.borrowernumber
       INNER JOIN (SELECT borrowernumber
	  	     FROM borrowers AS b
	       		  LEFT JOIN messages AS m
	       		  USING(borrowernumber)
     		    WHERE b.categorycode = 'LAPSI'
	   	      AND m.message LIKE '%Kela-kortti%'
	    	       OR b.opacnote LIKE '%Kela-kortti%') as lapsi
 WHERE r.guarantee_id = lapsi.borrowernumber
   AND md5(<<Salasana>>) = 'xxxxxxxxxxxxxx';
```

Viestien lähettämisen metodiin en osaa ottaa kantaa.

**Comment by emta001** [comment]
Koha-Suomen palaveri 19.2.2024: Tässä on nyt ehdotettu muutamaa ratkaisua. Jos tarvitsette ajoa, niin ilmoittakaa.

**Comment by pknuuti** [comment]
Tuossa raportissa pitäisi olla joku tieto myös siitä lapsesta, jonka tiedoista on kysymys. Kun viesti lähetetään huoltajalle, pitäisi siinä voida esittää ketä lasta (etunimi) viesti koskee, sillä jos perheessä on useita lapsia, nimetön viesti on huono. Miten nimi saaaisiin tuohon?

**Comment by atarnus** [comment]
Tässä ottaa mukaan huollettavan etunimen, ja ryhmittelee ne niin, että tulee vain yksi email per rivi (useampi huollettava erottuu pilkulla)

```
SELECT b.borrowernumber, b.email, GROUP_CONCAT(huoll.etunimi) AS 'Huollettavan nimi'
  FROM borrower_relationships r
       INNER JOIN borrowers b ON r.guarantor_id = b.borrowernumber
       INNER JOIN (SELECT b.borrowernumber,
                          CASE WHEN b.firstname LIKE '% %'
                          THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
                          ELSE b.firstname 
                          END AS etunimi
                     FROM borrowers b
                          LEFT JOIN messages AS m USING(borrowernumber)
                    WHERE b.categorycode = 'LAPSI'
                      AND m.message LIKE '%Kela-kortti%'
                       OR b.opacnote LIKE '%Kela-kortti%') AS huoll
 WHERE r.guarantee_id = huoll.borrowernumber
 GROUP BY b.borrowernumber
```
![image](https://github.com/KohaSuomi/Koha/assets/63994411/9dba92aa-7d49-40b5-9f7f-5f53a0e31f52)


Tällä lailla listaa kaikki huollettavat nimet erikseen:
```
SELECT b.borrowernumber, b.email, huoll.etunimi AS 'Huollettavan nimi'
  FROM borrower_relationships r
       INNER JOIN borrowers b ON r.guarantor_id = b.borrowernumber
       INNER JOIN (SELECT b.borrowernumber,
                          CASE WHEN b.firstname LIKE '% %'
                          THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
                          ELSE b.firstname 
                          END AS etunimi
                     FROM borrowers b
                          LEFT JOIN messages AS m USING(borrowernumber)
                    WHERE b.categorycode = 'LAPSI'
                      AND m.message LIKE '%Kela-kortti%'
                       OR b.opacnote LIKE '%Kela-kortti%') AS huoll
 WHERE r.guarantee_id = huoll.borrowernumber
```

**Comment by atarnus** [comment]
Hmm, hoksasin että piti olla ON eikä WHERE, vaikka ainakin omalla pienellä testiotannalla tuo näköjään toimi vallan mainiosti noinkin. Kuitenkin selkeämmin hahmotettava on tuo ON r-guarantee_id = huoll.borrowernumber, ja mahdollisesti tämä karsii sieltä ylimääräisiä rivejä jo aiemmin. Editoin yo. viestiin.

**Comment by pknuuti** [comment]
Kiitos, suljen tiketin.
