### ISSUE TITLE
AllowRenewalIfOtherItemsAvailable-asetus ja Damaged-tila

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#866]
### Mikä vikana?

Laitan tännekin nyt kuvauksen tästä ongelmasta, jotta jää muistiin.

Otimme Lumpeissa käyttöön AllowRenewalIfOtherItemsAvailable-asetuksen ja tämän jälkeen Liikkuvilta palveluilta tuli viestiä, että heidän lainassa oleva kirja oli yhtäkkiä pompannut varausjonon jatkoksi. Tämä esti kirjan uusimisen asiakkaan tiedoissa. Asetuksen kun otti pois päältä, niin niteen pystyi uusimaan normaalisti ja Varattu-tila oli kadonnut. 

Liikkuvien palveluiden kirjat ovat "Lainattavissa, ei varattavissa" -tilassa DAMAGED-tilan alla. AllowHoldsOnDamagedItems-asetuksessa meillä on "Älä salli".

![Damaged-tila](https://github.com/KohaSuomi/Koha/assets/129748294/40cec7b8-ee97-4930-9b82-892bdadb1df1)

**Comment by AnneliO** [comment]
AllowRenewalIfOtherItemsAvailable sallii uusinnan, jos vapaana on niteitä, jotka voivat täyttää olemassa olevan varauksen. Se ei siis katso, onko itse uusittava nide varattavissa vai ei. Jos tietueella ei ole muita niteitä, jotka voivat täyttää varauksen, uusintaa ei sallita.

**Comment by johannaraisa** [comment]
Minä yritin selvittää tämän logiikkaa ja minusta se käy kyllä CanItemBeReserved-funktiossa tarkistamassa onko tämä other available item varattavissa. Pitäisi itse varmaan katsoa omassa ympäristössä, että onko tuo vaan ominaisuus vai onko siinä bugi.

**Comment by AnneliO** [comment]
Sinänsä kuulostaa bugilta, jos ilman asetusta uusinnan voi tehdä ja asetuksen kanssa ei voi.

**Comment by pirliis** [comment]
OUTIssa kävi myös samoin muutamassa pienessä kirjastossa, joiden lainattavat niteet ovat "Saatavana, ei varattavissa" -tilassa. Kun kerroimme heille, mistä muutos johtuu, vastasivat: "Täytynee vain tottua tähän uuteen ominaisuuteen." 😊

**Comment by johannaraisa** [comment]
Selvittelin tätä asiaa ja minusta tuo asetus joko nimetty väärin tai siinä on logiikkavirhe. Tämä perustuu Kansalliskirjaston korjaukseen, https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=31112

Tuolla on rivi missä tarkistetaan kuinka paljon on varauksia ja niteitä, jotka voivat täyttää varauksen. Jos varauksia on enemmän kuin niteitä niin ilmoitetaan, että on varauksia ja ei pysty uusimaan. Minusta tuo asetuksen nimi ja kuvaus viittaa siihen, että pitäisi täyttää varaukset vaikka niitä olisi enemmän kuin niteitä. Mitä järkeä koko asetuksessa muuten on?

En nyt tiedä miten tätä lähtisi purkamaan yhteisön suuntaan.

**Comment by velimarj** [comment]
OUTIssa huomasimme, että asetus ei huomioi tarkistuksessaan myöskään sitä, ovatko saatavana olevat niteet varattavissa. Eli se tulkitsi myös "Saatavana, ei varattavissa" -tilassa olevat niteet sellaisiksi, jotka voivat täyttää varauksen. 

Ja testattiin tätä siis siten, että lainattiin nide X ja kokeiltiin montako varausta pitää tehdä että uusiminen estyy.

**Comment by johannaraisa** [comment]
Itseasiassa tuo tarkistus taidetaan tehdä vasta myöhemmin, kun noita niteitä käydään läpi. Katselin koodia ja näköjään 23.11 versiossa tuohon nopeuteen tulee parannusta.

**Comment by johannaraisa** [comment]
Voiko tämän jo sulkea, ollaan jo versiossa 23.11?

**Comment by pirliis** [comment]
Tsekkailin OUTIssa lainassa olevia niteitä, joiden tilana on "Saatavana, ei varattavissa", nyt niteet ovat jälleen uusittavissa, vaikka tietueeseen kohdistuu varaus. Eli OUTIn puolesta tiketin voi sulkea.

**Comment by AnneliO** [comment]
Hanna on pitkällä lomalla, joten suljen tiketin hänen puolestaan. :)
