### ISSUE TITLE
OUTI: Delivery delayed:EDItX tilaussanomien käsittelyssä oli ongelmia

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#867]
### Tukipyyntö

Saimme "Delivery delayed:EDItX tilaussanomien käsittelyssä oli ongelmia" -viestejä OUTIn Koha-tuen sähköpostiin kaksi kappaletta emmekä ymmärrä mitä nämä ovat. Niissä molemmissa oli yhtenä yhteystietona noreply@koha.outikirjastot.fi.

Tallensin toisen noista viesteistä tekstitiedostona ja liitin tikettiin. Jos tutkimuksiin tarvitsee alkuperäistä viestiä, niin voimme lähettää ne support-lootaan.

### Jotain muuta?

[Delivery delayedEDItX tilaussanomien käsittelyssä oli ongelmia.txt](https://github.com/KohaSuomi/Koha/files/13165374/Delivery.delayedEDItX.tilaussanomien.kasittelyssa.oli.ongelmia.txt)

**Comment by janPasi** [comment]
Virheellinen from-osoite EDItX:n asetuksissa. Sinne oli jäänyt roikkumaan tuo koha.outikirjastot.fi, jota ei ole ollut olemassakaan enää vuosiin. Korjattu nyt.

**Comment by janPasi** [comment]
Samanlaisia konfiguraatiovirheitä on muissakin kimpoissa, joten palautanpa vielä tiketin työn alle hetkeksi ja korjailen nekin.

**Comment by janPasi** [comment]
Kaikkiin kimppoihin on nyt vaihdettu from-osoitteeksi noreply@koha-suomi.fi EDItX:n virheraporteille.

**Comment by janPasi** [comment]
Avataanpas vielä takaisin. Tässä villakoirassa taitaa nyt olla hieman useampia ulottuvuuksia. Näyttäisi tuon virheraportin perusteella siltä, että joku Oulun kaupungin (ouka.fi) "FortiMail Appliance" yrittää lähettää vastauksia tuonne noreply@koha.outikirjastot.fi:hin. Pitäisi varmaan selvittää Oulun Digiltä miksi se itsekseen yrittää vastailla noreply-osoitteisiin.

**Comment by piiaseme** [comment]
Okei, laitan tämän eteenpäin, niin saadaan meidän suunnaltakin asia kuntoon. Kiitos Kodo :)
Suljen tämän nyt. Avataan uudestaan, jos tarvis.
