### ISSUE TITLE
Vaara: Varaus ei näy hyllyvarauslistalla

### ISSUE THREAD

**Issue by IrinaHalminen** [KohaSuomi/Koha#868]
### Mikä vikana?

Varausjonon kautta löytyi varattu lehti, joka ei ole tullut näkyville hyllyvarauslistalle. Siihen oli ollut asiakkaalla varaus kuukauden verran. Virkailija oli poistanut varauksen ja tehnyt sen uudelleen, mutta edelleenkin varaus näkyi vain Varausjonossa, eikä hyllyvarauksissa. 

Tein itselleni varauksen ko. tietueen eri niteeseen ja ongelma toistui. (Alkuperäinen varattu nide on laitettu asiakkaalle matkaan, oma testivaraukseni voimassa ja sen löytää Varausjonon kautta Pyhäselän kirjaston valitsemalla.)

Tietue: https://vaara.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=10944782
Varausjono/Pyhäselän kirjasto: https://vaara.koha-suomi.fi/cgi-bin/koha/circ/view_holdsqueue.pl?branchlimit=JOE_PYH&itemtypeslimit=&ccodeslimit=&locationslimit=&run_report=1

**Comment by IrinaHalminen** [comment]
Ongelma on edelleen olemassa. Aloin tutkia järjestelmällisesti hyllyvarauslistan ja varausjonoraportin niteitten eroja. Huomasin heti aakkosten alkupäässä Ilomantsin kohdalla yli kuukauden jonossa olleita lehtivarauksia, jotka eivät näy hyllyvarauslistalla. Kun otin varausjonoraportilla haun nidetyypillä AIK, 14 vrk, lehti, löytyi jopa yli vuoden vanhoja varauksia kesältä 2022. Kyseessä on siis lehtiin kohdistuvat nidevaraukset, mutta ongelma ei koske kaikkia lehtitietueita tai -niteitä. Vaihdoin asiasta keskusteltuani tähän tikettiin Larin vastuuhenkilöksi.

Vertasimme hyllyvarauslistalla olevia lehtivarauksia ja niitä, jotka eivät sinne tule. Lari huomasi, että ongelmallisilta niteiltä puuttuu signum.

Kokeilin lisätä tekemälleni varaukselle siltä puuttuvan signumin, jonka jälkeen se ilmestyikin hyllyvarauslistalle. 

Nyt tarvittaisiin varmaankin raportti, jolla saataisiin esille kaikki sellaiset lainattavissa olevat lehdet, joilta puuttuu signum? Voisimme korjata nuo signumit paikoilleen kirjastoittain.

**Comment by pknuuti** [comment]
Muistaakseni jossain vaiheessa mä olen ohjeistanut lisäämään sen signumin lehtiin, mutta kuka niitä ohjeita noudattaa.

**Comment by AnneliO** [comment]
Lehden tilaukseen kannattaa laittaa signum valmiiksi Luokka-kenttään, niin se tulee sitten niteelle automaattisesti, kun lehti vastaanotetaan.

Koitan katsoa, josko löytyisi jokin valmis (hyödynnettävä) raportti signumeista.

**Comment by AnneliO** [comment]
En löytänyt raporttia, mutta periaatteessa ihan vain näin ne pitäis löytyä:

```
select itemnumber,holdingbranch,homebranch,barcode,itemcallnumber from items 
where itemcallnumber is null
and itype='ALEHTI'
```

**Comment by IrinaHalminen** [comment]
Lari väsäilee raporttia, joka on vähän laajempi. On tuosta signumeitten lisäämisestä muistutettu useammankin kerran, ja mainitaan uudelleen huomenna (kun olen töissä, enkä saikulla)! Meillä laitettiin joskus harjoittelija korjaamaan niitä unohtuneita signumeita, mutta pari varastossa ollutta joululehteä oli oman kirjaston osalta jäänyt käsittelemättä. Pika-apuna muokkailin nyt osaan varatuista signumit ja katsoin, että tulivat hyllyvarauslistalle.

**Comment by AnneliO** [comment]
Sinänsä jännä, että signumin puute estää niteen näkymisen hyllyvarauslistalla. Eihän se toki niin pitäisi olla, varsinkin kun signum ei ole pakollinen tieto.

**Comment by lmstrand** [comment]
Niin, olisiko sitten syytä harkita koodimuutosta hyllyvarauslistan generointiin.

**Comment by AnneliO** [comment]
> Niin, olisiko sitten syytä harkita koodimuutosta hyllyvarauslistan generointiin.

Bugilta tuo minusta vaikuttaa.

**Comment by IrinaHalminen** [comment]
Jätänkö tämän siis vielä auki?

**Comment by AnneliO** [comment]
Pistän Koha-Suomen palsun listalle asian. Mietitään, miten edetään asian kanssa. Riittääkö esim. että kimpoissa huolehditaan varsinkin lehtiniteille signumit paikoilleen vai tarvitaanko jotain muutakin toimia.

**Comment by AnneliO** [comment]
Tässä on Larin tekemä signumittomien niteiden raportti vähän stilisoituna:

```
select biblio.title as 'Nimeke', CONCAT('<a href="/cgi-bin/koha/catalogue/moredetail.pl?biblionumber=', biblio.biblionumber, '#item', i.itemnumber, '">', i.barcode, '</a>') AS 'Viivakoodi',
itemnumber, i.biblionumber, homebranch as 'Kotikirjasto', holdingbranch as 'Sijaintikirjasto', onloan as 'Eräpäivä', location as 'Hyllypaikka', itype as 'Nidetyyppi', enumchron as 'Lehden numero'
from items i
inner join biblio ON i.biblionumber = biblio.biblionumber
and i.itemcallnumber is null and i.notforloan = 0 and i.itemlost = 0
and i.holdingbranch = <<Sijaintikirjasto|branches>>
order by 1 asc
```

Raportti hakee niteet, joissa ei ole signumia ja ei ole mitään notforloan-arvoa. Eli ulos jää esim. tilattu-tilaiset, joissa on paljon signumittomia. Näin rajattuna signumittomien määrä tippuu ainakin OUTIssa ja Vaarassa ihan merkittävästi.

**Comment by AnneliO** [comment]
Koha-Suomen palaveri 20.11.2023: Hyllyvarausraportin koodissa on tarkistus, että signum on olemassa. Testataan versionvaihdon yhteydessä, mitä tapahtuu, jos tarkistuksen poistaa koodista.

Siihen saakka kannattaa korjailla esim. käsin raporttien avulla niteet, joilta puuttuu signum (ei kannata tilattu-tilaisia).

**Comment by AnneliO** [comment]
Testailin tätä sekä outi-testillä että vaara-testillä ja en ainakaan itse saanut enää vastaanotettua lehtiniteitä niin, että niille tulisi tyhjä signum-kenttä, koska se on määritetty pakolliseksi. Eli periaatteessa signumittomia ei pitäisi enää syntyä. Tosin, Vaaran tuotannossa 952o-kenttä ei näytä olevan pakollinen lehteä vastaanotettaessa. Voisiko senkin muuttaa pakolliseksi?

Onko koodimuutos tätä aatellen edelleen tarpeen?

**Comment by pknuuti** [comment]
Muutin Vaarassa kausijulkaisujen pohjaan 952o-kentän pakolliseksi.

**Comment by IrinaHalminen** [comment]
Kiitos! Näitä korjattiin käsin aika paljon ja voin vielä tsekata, onko tullut lisää korjattavaa. Suljen tiketin.
