### ISSUE TITLE
TäTiin raportteja erityyppisistä vanhoista poistettavista tietueista

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#870]
### Tukipyyntö

Heikkisen Antilta tuli pyyntö:

TäTissä kirjoista/tekstiaineistosta on raportti vanhoista poistettavista tietueista, niin samanlaisen voisi tehdä myös äänitteistä, nuoteista, videotallenteista, äänikirjoista ja elektronisesta aineistosta. Onnistuisikohan näistä tehdä raportti siten, että siihen tulee vain sellaiset tietueet, joilla ei ole ollenkaan tietoja 336-, 337- ja 338-kentissä? Yritän rajata ISBD-ajan tietueet vielä ulkopuolelle näistä.

- [x] Äänitteet (ei osakohteita): 000/06=j, 000/07=m, 003: FI-BTJ
- [x] Nuotit (ei osakohteita): 000/06=c, 000/07=m, 003: FI-BTJ
- [x] Videotallenteet (ei osakohteita): 000/06=g, 000/07=m, 003: FI-BTJ
- [x] Äänikirjat (ei osakohteita): 000/06=i, 000/07=m, 003: FI-BTJ
- [x] Elektroninen aineisto (ei osakohteita): 000/06=m, 000/07=m, 003: FI-BTJ

**Comment by AnneliO** [comment]
TäTissä on nyt raportti nro 255, joka hakee Äänitteet-määritelmän mukaan. Näyttääkö se Antti oikealta?

**Comment by AnttHeik** [comment]
Sen verran mitä nyt tuosta muutamia kävin läpi, niin juuri oikealta näyttäisi. Voisiko tässäkin saada kerralla näkyviin 1000 tietuetta tai ainakin 500?

**Comment by AnneliO** [comment]
Muutin raportin näyttämään kerralla 1000 tietuetta.

**Comment by AnneliO** [comment]
Raportissa 256 on nyt nuotit. Onko ok? :)

**Comment by AnttHeik** [comment]
Joo, oikealta näyttää, kiitokset :)

**Comment by pknuuti** [comment]
Tein noista lopuistakin eli videoista, äänikirjoista ja elektronisen aineiston tietueista vastaavat raportit.

**Comment by AnneliO** [comment]
Kiitos Päivi! Tarvittavat raportit olemassa, joten suljen tiketin.
