### ISSUE TITLE
TäTiin raportti, joka hakee tietueet, joissa ääkköset kummalliset

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#871]
### Tukipyyntö

Heikkisen Antti: Onkohan mahdollista tehdä raporttia, jolla saisi haettua tietueita, joissa ääkköset ja muut erikoismerkit ovat näin: 1 CD-�a�anilevy?

Esim: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=1468551

**Comment by emta001** [comment]
Ainakin tämä onnistuu hakemaan oikeanlaisen tuloksen:

`select * from biblio where notes like "%�%" limit 1;`

Joten eiköhän tuo onnistu.

**Comment by AnttHeik** [comment]
Minkälaisia tuloksia tuo tekemäsi esimerkkiraportti sitten hakee? Hakeeko se vain yhdestä tietystä kentästä/kentistä?

**Comment by emta001** [comment]
> Minkälaisia tuloksia tuo tekemäsi esimerkkiraportti sitten hakee? Hakeeko se vain yhdestä tietystä kentästä/kentistä?

Joo, se hakee vain biblio-taulun notes-sarakkeesta noita kummia. En tiedä mikä MARC-kenttä tuossa on kyseessä tarkalleen. Mutta mitä tuota Annelin esimerkkiä katsoin, niin näitä näyttää löytyvän useammastakin MARC-kentästä per tietue.

**Comment by AnttHeik** [comment]
Aivan, joo, yleensä koko tietueesta on kaikki ääkköset tai muut erikoismerkilliset kirjaimet menneet sekaisin. Sen takia mietin, että jos valitsisi raporttiin vain ne yleisimmät kentät, joissa noita voi esiintyä, ja sitä kautta saisi sitten kuitenkin suurimman osan kiinni.

**Comment by emta001** [comment]
Tämmönen ainakin voisi onnistua, nuo muut kentät voi lisätä samalla kaavalla:

```
SELECT biblionumber FROM biblio_metadata 
WHERE ExtractValue(metadata,'//datafield[@tag="300"]/subfield[@code="a"]') LIKE "%�%" 
OR ExtractValue(metadata,'//datafield[@tag="300"]/subfield[@code="b"]') LIKE "%�%"
OR ExtractValue(metadata,'//datafield[@tag="337"]/subfield[@code="a"]') LIKE "%�%"
LIMIT 10;
```

En osaa kyllä yhtään sanoa kauanko tuossa menee ilman rajausta. Kokeilin laskea pelkästään nuo kummat 300$a-kentät ja ajoon meni 30 sekunttia, saman verran meni kun tulosti biblionumberit. Tuon ajon tulos oli muuten 60 tietuetta.

**Comment by AnttHeik** [comment]
Ok, kiitokset! Hyvä, ettei tuon enempää ollut noita.

**Comment by AnttHeik** [comment]
Pystyisikö tämän raportin siirtämään jo TäTiin vai vieläkö tuota pitää muokata jotenkin?

**Comment by emta001** [comment]
> Pystyisikö tämän raportin siirtämään jo TäTiin vai vieläkö tuota pitää muokata jotenkin?

Laitoin tuon nyt tuollaisenaan Tätiin, raportin id on 258. Siinä kestää hetken kun sitä ajaa.

**Comment by emta001** [comment]
Voisihan tuota tehdä myös niinkin, että kun on korjannut nuo 300-kentät, niin sitten vaihtaa aina tutkittavaa kenttää ja varmistaa löytyykö niistä vielä kummia. Ei ehkä kaikkea kannata hakea kerralla, muuten tuossa ajossa kestää.

**Comment by AnttHeik** [comment]
Joo, käy se toki niinkin.

**Comment by pknuuti** [comment]
Mä muokkasin Tätiin uuden raportin 259 tuon Emmin raportin pohjalta ja olen hakenut 245a ja c-kenttien tiedot ja poistanut/korjannut ne. 600a ja 610a-kenttien haku ei tuonut virheellisiä merkkejä esiin.
