### ISSUE TITLE
Lisäättekö Helle-testin ylläpitoon tämän puuttuvan: Tietueiden yhdistämissäännöt (Record overlay rules)

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#872]
### Tukipyyntö

Helle-testin ylläpidosta puutuu Tietueiden yhdistämissäännöt (Record overlay rules).

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/fd3392a3-699f-4c0e-8e6e-55f2552cdb60)

Lisäättekö puuttuvan palasen?

**Comment by emta001** [comment]
Tämä ominaisuus on  käyttöoikeuden takana; CAN_user_parameters_manage_marc_overlay_rules. Eikö tuo siis näy edes superlibrarian oikilla?

**Comment by Kati-Helle** [comment]
Ei näy superlibrarian oikeuksilla.

**Comment by emta001** [comment]
Ahas, sieltä puuttuu koko manage_marc_overlay_rules-oikka. Ilmankos ei näy. Lisäilen tuon ja tarkistan samalla muutkin testit. Mistä lie syystä jäänyt puuttumaan.

**Comment by emta001** [comment]
Lisäsin oikan helle-testiin, muualla se näyttikin olevan kunnossa.

**Comment by Kati-Helle** [comment]
Kiitti Emmi :)
