### ISSUE TITLE
Lumme: sukupuolen poisto vanhoista asiakastiedoista

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#874]
### Tukipyyntö

Lumpeiden asiakastiedoista täytyisi poistaa asiakkaiden sukupuolitiedot. Näitä näkyy erityisesti vanhoissa asiakastiedoissa, esim. ID51023.

**Comment by emta001** [comment]
Ajo tehty, koski 178249 asiakasta.

`update borrowers set sex = NULL where sex in("0","F","M");`

Jätin sinne ne asiakkaat, joiden sukupuolena on N eli None. Vanhan Redmine tiketin mukaan se muodostuu jokatapauksessa yhteisöasiakkaille eikä siitä ole mitään haittaakaan https://tiketti.koha-suomi.fi/issues/3782

**Comment by Hanna-Lumme** [comment]
Kiitos!
