### ISSUE TITLE
Raportti kuvailupohjista CDAP ja NUOP

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#876]
### Tukipyyntö

Saisimmeko OUTIin raportin, jolla voisi hakea tietueet, jotka käyttävät kuvailupohjia CDAP ja NUOP.

**Comment by AnneliO** [comment]
OUTIssa nyt raportti nro 668. Riittääkö tuollainen?

**Comment by pirliis** [comment]
Kiitos Anneli! Raportti on riittävä. Suljen tiketin.
