### ISSUE TITLE
AllowRenewalIfOtherItemsAvailable -asetus estää lainojen latautumisen, jos asiakkaalla paljon lainoja joihin kohdistuu hyllyvarauksia

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#879]
### Mikä vikana?

Vaskissa raportoitiin asiakkaasta (https://vaski.koha-suomi.fi/cgi-bin/koha/members/moremember.pl?borrowernumber=324576), jonka lainat latautuvat Kohassa näkyville todella hitaasti eikä asiakas saa niitä näkyville Finnassa ollenkaan (asiakas saa virheilmoituksen, ettei kirjastojärjestelmään saada yhteyttä).

Asiakkaalla on samojen nimekkeiden useita niteitä lainoissa ja osaan nimekkeistä kohdistuu varauksia. Aloin siksi epäillä, että AllowRenewalIfOtherItemsAvailable voisi aiheuttaa tässä latautumisongelman kun lainoissa on ehkä normaalia enemmän niteitä joiden uusimisen sallimisen tarkistamiseksi pitää laskeskella paljonko niteitä on saatavilla suhteessa jonossa oleviin varauksiin.

Sain toistettua ongelman testillä testiasiakkaalla https://vaski-test.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=366331 ja todennettua, että AllowRenewalIfOtherItemsAvailable -järjestelmäasetuksen muuttaminen vaihtoehtoon "Älä salli" korjaa latautumisongelman. Tuon testiasiakkaan kanssa näytti myös olevan niin, että kun palautin lainoista yhden niteen LVask119794397, asiakkaan lainat latautuivat sen jälkeen näytölle (joskin todella hitaasti). Kun lainasin niteen LVask119794397 asiakkaalle takaisin, lainat eivät enää latautuneet ja testi-Finnan puolella tulee ilmoitus ettei kirjastojärjestelmään saada yhteyttä.

Onkohan tällaiselle suorituskykyongelmalle käytännössä mitään tehtävissä? Meillä on ollut ko. järjestelmäasetus käytössä kesäkuun alusta lähtien ja tämä on ensimmäinen palaute joka on meidän korviimme tullut, joten tilanne lienee sinänsä melko harvinainen.

### Kuinka toistaa ongelma/asia

1. Avaa testiasiakkaan https://vaski-test.koha-suomi.fi/cgi-bin/koha/circ/circulation.pl?borrowernumber=366331 tiedot ja klikkaa Lainat-välilehdeltä Lainassa-painiketta.
2. Huomaa, että Koha jää lataamaan lainoja mutta ne eivät pitkän odotteluajan jälkeenkään lataudu.
3. Muuta järjestelmäasetuksene AllowRenewalIfOtherItemsAvailable valinta "Älä salli".
4. Avaa testiasiakkaan tiedot uudelleen ja klikkaa Lainat-painiketta. Huomaa, että nyt lainat latautuvat.
5. Muuta järjestelmäasetukseen AllowRenewalIfOtherItemsAvailable takaisin valinta "Salli".
6. Palauta testiasiakkaan lainoista nide LVask119794397. Mene takaisin testiasiakkaan lainoihin ja huomaa, että nyt lainat latautuvat pitkähkön odotusajan jälkeen näkyville.

**Comment by AnneliO** [comment]
Tämä kuulostaa samanalaiselta suorituskykyongelmalta, minkä vuoksi OUTIssa aikanaan luovuttiin asetuksen käytöstä. Se oli silloin tosin paljon huonompi tilanne ja ongelmallisia asiakastilejä runsaasti.

**Comment by johannaraisa** [comment]
Tuo testiasiakas kyllä kaatuu ihan muuhun kuin pitkään hakuun, saan virheeksi Can't call method "notforloan" on an undefined value at /home/koha/Koha/C4/Reserves.pm line 1446.

**Comment by johannaraisa** [comment]
> Tuo testiasiakas kyllä kaatuu ihan muuhun kuin pitkään hakuun, saan virheeksi Can't call method "notforloan" on an undefined value at /home/koha/Koha/C4/Reserves.pm line 1446.

Jännää, kaikkien datat on kyllä ok. Piti käynnistää plack uudestaan, ni loppui tuo virhe.

**Comment by johannaraisa** [comment]
Nyt selvisi, eli tuolla testillä oli ainakin virheellisiä nidetyyppejä ja ne niteet osui tuohon haravaan. Sama tilanne ei ole sitten tuotannossa.

Minulla on yksi idea miten tuota voisi saada nopeammaksi.

**Comment by johannaraisa** [comment]
Nyt on testeillä tähän suorituskykyyn korjaus. Tarkastakaa, että varattavuus on kuten pitää.

**Comment by ajrajala** [comment]
Vedin tuolle tiketin kuvauksessa mainitulle testiasiakkaalle edellisten lainojen jatkeeksi lainaan liudan sellaisen tietueen niteitä, johon kohdistuu pari hyllyvarausta. Asiakkaan lainat latautuivat (heti siinä kesti mutta kohtalaisen nopeasti silti), samoin kävi testikannassa kiinni olevassa Finna-näkymässä.

Tein sitten vielä asiakkaalla lainassa olevaan biblioon 2931931 toisen varauksen, jotta tietueella ei olisi enää riittävästi hyllyssä olevia niteitä varauksia täyttämään. Kun latasin asiakkaan lainat tämän jälkeen uudestaan, näkyi tuon tietueen niteen kohdalla ihan oikein "Varattu" eli nide ei ollut enää uusittavissa.

Olikos jotain muuta mitä olisi tähän liittyen vielä hyvä testata?

**Comment by johannaraisa** [comment]
Poistin sieltä sellaisen rivin, joka tarkistaa tietueen kaikki niteet ennen kuin käsittelee noita vapaana olevia niteitä. Tekee kuitenkin samat tarkistukset sitten noille vapaana oleville niteillä, minusta tuossa on liikaa tarkistusta, ja ollaan vain oikeasti kiinnostuneita niistä vapaana olevista niteistä.

Tätä voisi testata muissakin kimpoissa. Lisätkää asiakkaalle lainoja tietueisiin, joissa on paljon niteitä ja varauksia. Latauksen pitäisi olla jonkun verran nopeampi kuin ennen.

**Comment by johannaraisa** [comment]
Tämä taitaa ratketa 23.11 versiossa, siihen on tullut tällainen [korjaus](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34178). Tuo korjaa asioita muuallakin, mutta tuossa ainakin tekevät saman mitä minä tämän tiketin kanssa.

**Comment by ajrajala** [comment]
Testasin tätä vielä tuotannossa lainaamalla asiakkaalle 27 nidettä teoksesta johon kohdistuu varauksia ja johon on niteitä saatavilla. Lainat näyttävät latautuvan suht nopeasti ja mikäli saatavilla olevia niteitä ei ole riittävästi, estyy lainojen uusiminen. Nähdäkseni ongelma on siis korjaantunut ja suljen tiketin.
