### ISSUE TITLE
Myöhässä olevien hankintojen listauksessa Kirjasto-sarake näyttää Tuusulan pääkirjastoa silloinkin kun tilaussanoman mukaan tilaaja on muu kirjasto

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#880]
### Mikä vikana?

Myöhässä olevien hankintojen listauksessa ( https://kirkes.koha-suomi.fi/cgi-bin/koha/acqui/lateorders.pl ) Kirjasto-sarake näyttää valtaosassa tilauksia Tuusulan pääkirjastoa, vaikka tilaajakirjasto olisikin joku muu. Tilaussanomassa tilaajakirjasto on oikein, joten sivulla on luultavasti bugi.

**Comment by AnneliO** [comment]
Tutkin, löytyykö ongelmasta yhteisötikettiä.

**Comment by AnneliO** [comment]
> Tutkin, löytyykö ongelmasta yhteisötikettiä.

En löytänyt ja en pysty oikein muissa kimpoissa edes testaamaan asiaa, koska sivun latautuminen on suuren tilausmäärän vuoksi niin hidas, että tulee timeout ja proxy error.

Melkein suosittelen käyttämään [SQL-raporttia](https://koha-suomi.fi/dokumentaatio/raporttikirjasto/#nimekkeet-joissa-on-niteit%C3%A4-tilattu-tilassa) tuon toiminnon sijaan, koska taitaa olla ihan ajan kysymys, koska se lakkaa Kirkeksessäkin toimimasta.
