### ISSUE TITLE
Koriin linkki teokseen verkkokirjastossa

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#883]
### Kehitysehdotukseni

Siirretty Redminestä [tiketistä 5440](https://tiketti.koha-suomi.fi/issues/5440), [RedGrave 5440](https://github.com/KohaSuomi/RedGrave/blob/main/Kehitysehdotukset/2022/%235440%20Koriin%20linkki%20teokseen%20verkkokirjastossa.md).

Kori-toiminnossa on aiemmin ollut linkki teoksen tietoihin verkkokirjastossa. Tätä toivotaan uuteenkin versioon.

---

Koha-Suomen asiantuntijaryhmän päätös 16.1.2023: Toteutetaan ja samalla tutkitaan muutkin avoinna olevat Finna-linkkitoiveet.

**Comment by atarnus** [comment]
Pykersin vähän tämän kanssa ja sain ihan intranet.js-säädöillä luotua lisälinkit finnaan omassa testiversiossa. En koskisi tuohon peruslinkkiin kun silläkin on tarkoituksensa, mutta tuollalailla perään voidaan laittaa toinen linkki, joka avaan uuteen välilehteen tietueen finna-verkkokirjastosivun. Olisiko toiveita miltä linkin pitäisi näyttää? Tai muita täsmennyksiä?

![image](https://github.com/KohaSuomi/Koha/assets/63994411/ffb362db-141b-45ba-a1d6-29ab13e95a54)

Piia oli Redgraven puolella puhunut myös linkeistä kun korin lähettää eteenpäin, mutta semmoisen tekeminen on sitten isompi homma. Ei tainnut lopulta kuulua tähän tehtävään?

**Comment by AnneliO** [comment]
Versiossa 23.11 pystyy viestipohjissa määrittämään Korista lähtevän sähköpostiviestin sisällön. Siellä pystyy lisäämään linkin myös Finnaan. Olen sellaisen alustavasti jo viestipohjaan lisännytkin [23.xx-version wikissä](https://github.com/KohaSuomi/Koha-23x/wiki/Uudet-viestipohjat#cart) olevassa viestipohjassa.

**Comment by Kati-Helle** [comment]
Lisäsin Helle-Koha-testin rimpsuun Helle-Finnan tuotannon osoitteen.

Testasin Helle-Koha-testissä lisäämällä koriin tietueen.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/ecb06204-2c7e-4e4f-9172-791b6115c044)

Klikkasin Korin Avaa Finnassa -linkkiä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/438dc9ea-4059-41c8-8d72-43c99c1b01e1)

Linkistä avautui oikein tämä Helle-Finna tuotannon tietue
https://helle.finna.fi/Record/helle.1611059

**Comment by AnneliO** [comment]
Tämänkin pitäisi olla otettu huomioon, mutta testaatteko myös, että linkit toimii oikein, kun korissa on useampi teos. :)

**Comment by Kati-Helle** [comment]
Helle-testaus jatkuupi.

Korissa nyt kaksi teosta - molemmat linkit toimivat oikein
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b412420a-b36b-44f0-91ef-25c7d08ea6d5)

Korissa kolme teosta - kaikki linkit toimivat oikein
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/579e5d1f-7ca6-4f36-adbd-d26b3b1f5c1d)

Lisähuomiona se, että Korin niteettömän tietueen linkki toimii, mutta ei vie oikeaan tietueeseen. Saman korin niteellisten tietueiden linkit toimivat myös ja vievät oikeaan tietueeseen.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d1fe8531-a367-4d17-a4fe-0c1a75c3df50)

**Comment by Kati-Helle** [comment]
Lisäsin koriin nyt myös osakohteen:  Avaa Finnassa -painikkeesta aukeaa oikea tietue Finnassa.

**Comment by Kati-Helle** [comment]
Tuossa niteettömän tietueen Avaa Finnassa -tapauksessa onkin kyse siitä, että Helle-Koha-testin tietueen biblionumber-arvolla 1631064 on eri teos tuotannossa.

**Comment by pknuuti** [comment]
Testasin Vaaran testillä ja laitoin tuotanto-Finnan osoitteen. Linkki toimi oikein.

**Comment by piiaseme** [comment]
Testasi OUTIssa yhdellä teoksella. Linkki toimi oikein.

**Comment by janPasi** [comment]
JavaScriptit lisätty kaikkiin kimppoihin.

**Comment by Kati-Helle** [comment]
Hellessä Avaa koriin -linkki on
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/645c91fc-303f-4b7b-b2e8-92217aa5f2fb)

mutta linkki ei vie vastaavaan tietueeseen Helle-Finnassa, vaan linkistä aukeaa tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/3dc1291f-ebdb-4fba-92a0-b60a210fc6da)

jonka linkkinä on 
https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi.1606812

**Comment by atarnus** [comment]
Siellä on nyt jäänyt huomioimatta, että pitäisi kimppakohtainen Finnan url vaihtaa aina rimpsuun. Siilinjärvi saa vähän liikennettä nyt :D

Otan asian puheeksi scrummissa, korjataan.

**Comment by atarnus** [comment]
Avuksi:

`var finnaurl = 'https://outi.finna.fi/Record/outi.';`

`var finnaurl = 'https://lapinkirjasto.finna.fi/Record/lapinkirjasto.';`

`var finnaurl = 'https://vaski.finna.fi/Record/vaski.';`

`var finnaurl = 'https://vaara.finna.fi/Record/vaarakirjastot.';`

`var finnaurl = 'https://helle.finna.fi/Record/helle.';`

`var finnaurl = 'https://kirkes.finna.fi/Record/kirkes.';`

`var finnaurl = 'https://kyyti.finna.fi/Record/kyyti.';`

`var finnaurl = 'https://lumme.finna.fi/Record/lumme.';`


```
/// ALKU ///
// Finna-verkkokirjastolinkkien lisääminen ostoskoriin. Muista vaihtaa kimppakohtainen URL
$(document).ready(function () {
  if ( window.location.pathname == '/cgi-bin/koha/basket/basket.pl' ) {

    // Finnan URL -- Vaihda tähän oma kimppa, huomaa piste lopussa
    var finnaurl = 'https://siilinjarvenkirjasto.finna.fi/Record/siilinjarvi.';

    // Kielivalinta
    var linktext = 'Avaa Finnassa';
    if ( document.documentElement.lang.toLowerCase() === "en" ) {
	    linktext = 'Open in Finna';
	  } else if ( document.documentElement.lang.toLowerCase() === "sv-se" ) {
    	linktext = 'Öppna i Finna';
  	}

    // Linkin muodostaminen
    $("a.title").parent().each(function(index, v) {
      var $v = $(v);
      var $finnalink = '<a class="btn btn-default" target="_blank" href="' + finnaurl + $v.find('a.title').attr('href').replace('/cgi-bin/koha/catalogue/detail.pl?biblionumber=','') + '"><i class="fa fa-external-link"></i> ' + linktext + '</a>';
      $v.append($finnalink);
    });
  }
});
/// LOPPU ///
```

**Comment by janPasi** [comment]
Linkit nyt korjattu.

**Comment by AnneliO** [comment]
Jälkikäteen muistuu vielä mieleen, että tämä pitää dokumentoidakin, eli rimpsu lisätty nyt [IntranetUserJS-kirjastoon](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#koriin-linkit-finnaan-jokaisesta-teoksesta).
