### ISSUE TITLE
Pilkut ja pisteet eri näytöillä

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#889]
### Kehitysehdotukseni

Redminen tiketti 4569:
Kohan eri näytöillä ja toiminnallisuuksissa ei toimi täysin lokalisointi ja numeroiden yhteydessä pitää käyttää näytöstä riippuen joko pilkkua tai pistettä.

Päätös: tutkitaan, onko yhteisöversiossa korjattu puutteet lokalisoinnissa

Keskustelua: 
Susanna Sandell yli vuosi sitten: "Uudessa versioissa Maksutyypin oletussumman piste muuttuu pilkuksi kun esimerkiksi on lisäämässä maksua asiakkaalle. Eli vaikka maksutyyppiin on määritelty oletussummaksi 2.00, on kyseistä maksua lisättäessä maksun summa 2,00. Koha ei kuitenkaan hyväksy (tässä versiossa) pilkkua maksuissa."

Anneli Österman yli vuosi sitten: "Meillä on varmaan kaikilla CurrencyFormat-järjestelmäasetuksessa valittuna, että hinnat (rahayksikkö) näytetään käyttäen pilkkua. Tämä asetus kuitenkin ilmeisesti koskee vain hintojen näyttämistä, ei niiden syöttämistä erilaisiin hintakenttiin. Syöttämisessä käytetään pistettä.

Eli esimerkiksi hankinnassa budjettien summat näytetään pilkun kera, mutta hinnat pitää syöttää pisteen kera. Yhteisössä on tehty toteutus vain tuolle näyttämiselle, ei syöttämiselle.

Tästä pitänee tehdä yhteisöön bugiraportti. Sitä ennen hinnat kannattaa syöttää pisteellä, kuten esimerkeissä kehotetaan. :)"

Asiantuntijaryhmän 20.2.2023 päätös: Tehdään yhteisöön tiketti, jossa ehdotetaan, että hinnat voi syöttää CurrencyFormat-järjestelmäasetuksen mukaisesti.

**Comment by pknuuti** [comment]
Tehty tiketti Bugzillaan: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=35223
Saa käydä kommentoimassa/korjaamassa.

**Comment by emta001** [comment]
Koha-Suomen palaveri 9.9.2024: Pääkäyttäjät selvittävät missä kaikkialla pilkut ja pisteet menevät väärin ja raportoivat ne tähän tikettiin. Koha-Suomi selvittää, saako tähän tehtyä plugarin joka konvertoi pilkut ja pisteet oikein tietoja syötettäessä.

**Comment by AnneliO** [comment]
Pääkäyttäjien palaveri 10.9.2024: Osa kimpoista on muuttanut CurrencyFormat-asetukseen valinnaksi pisteen, jonka jälkeen numerot näytetään pisteellä. Tämä ohjaa paremmin tällöin myös syöttämään tiedot pisteellä. Muutkin kimpat selvittää, voisiko heillä muuttaa myös CurrencyFormat-asetukseen US-vaihtoehdon. Ei tehdä plugaria ennen kuin tämä on selvitetty. Jos käy kaikille, plugari ei tarvitse tehdä.

**Comment by pknuuti** [comment]
Vaarassa otettu käyttöön US-vaihtoehto.

**Comment by PiaKusmin** [comment]
Lapissa otettu käyttöön US-vaihtoehto.

**Comment by atarnus** [comment]
OUTIssa on ollut US käytössä jo pitkään, luultavasti viime versionvaihdosta.

**Comment by Kati-Helle** [comment]
Hellessä käytössä US-vaihtoehto.

**Comment by pknuuti** [comment]
Tämä sovittu palaverissa, suljen tiketin.
