### ISSUE TITLE
Nidevarausta tehdessä jo asiakkaan voimassa olevan saman tietueen nidevarauksen Peruuta varaus -painike ei toimi

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#892]
### Mikä vikana?

Kun tekee nidevarausta ja asiakkaalla on jo voimassa oleva nidevaraus johonkin saman tietueen niteeseen, ei olemassa oleva nidevaraus poistu varatun niteen Tiedot-sarakkeen Peruuta varaus -painikkeella.

Helle-testillä nidevaraus 
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/2dfa6149-a698-4e33-b3b3-076687ee5689)

Peruuta varaus-painikkeen valinnasta Vahvista poisto -popupin Vahvista poisto -painikkeesta ei tapahdu mitään
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/420c6e32-c6e4-45b7-a599-defc011c86c2)

Vahvista poisto -popupin Peruuta-panike toimii.

**Comment by lasse-koha** [comment]
Varaussivun sivutus rikkoo tämän painikkeen.

**Comment by lasse-koha** [comment]
Korjaus tuotu testeille.

**Comment by Kati-Helle** [comment]
Nidevarauksen saa nyt poistettua Peruuta varaus -painikkeella Helle-testissä.

Toimii niin, että Peruuta varaus -painiketta klikkaamalla Vahvista poisto -popup vilahtaa niin nopeasti, että vahvista poisto -painiketta en ehdi klikata. Peruutettu varaus poistuu kyllä. 
Poiston peruutusta en onnistunut vilahtavasta popupista valitsemaan.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/52500908-08cd-452b-a9d9-55db3f8f5232)

**Comment by ajrajala** [comment]
Vaski-testillä näyttäisi onnistuvan nidevarauksen peruminen tilanteessa jossa asiakkaalla on samaan teokseen kaksi nidevarausta. En havainnut meidän testillä tuota Katin mainitsemaan ongelmaa pop-upin vilahtamisesta vaan pystyin normaalisti vahvistamaan poiston pop-up-ikkunasta. Testasin varauksen poistoa kahdella eri asiakaslajilla (henkilöasiakas, ei-tilastoitavat).

**Comment by velimarj** [comment]
OUTI-testillä sama homma kuin Hellessä, eli varauksen pystyy kyllä perumaan, mutta pop-up vilahtaa nopeaa ja valitsee oletettavasti tuon "Vahvista poisto", koska se tosiaan poistuu. Mutta jos haluaisi perua perumisen, niin ei onnistu ainakaan minun reflekseillä.

**Comment by Tuomas-Kyyti** [comment]
Kyytin testillä vilahtaa pop-up kyllä niin nopeasti, ettei sitä ehdi painaa. Varaus kyllä poistuu.

**Comment by lasse-koha** [comment]
Yhteisössä ollaan tätä painiketta kokonaan poistamassa.

**Comment by lasse-koha** [comment]
Painike poistettu.

**Comment by Kati-Helle** [comment]
Helle-testissä Peruuta varaus -painike on edelleen käytettävissä ja toimii samoin kuin aiemmin, eli Peruuta varaus -painiketta klikkaamalla Vahvista poisto -popup vilahtaa niin nopeasti, että vahvista poisto -painiketta en ehdi klikata.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/abb701a4-cf24-444f-a9ba-1e58961e7cb5)

Kirjastokortti-arvolla asiakasta hakiessa näkyi hetken tämä. Asiakkaan haku toimi oikein ilmoituksesta huolimatta.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/feb8bbaf-da51-4db1-b3f1-34e1a2b0bcd8)

**Comment by lasse-koha** [comment]
Nexteiltä siis poistettu, korjataan versionvaihdossa.

**Comment by Kati-Helle** [comment]
Ok, olin väärässä paikassa :)
Helle-nextissä nidevarauksen teko ei nyt onnistu asiakkaalle, jolla on jo olemassa oleva nidevaraus.
Koha ilmoittaa niteiden kohdalla: Varaus pitää tehdä tietueeseen.
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/73f16eb6-e13e-450e-8bde-ce6cb6324048)

**Comment by AnneliO** [comment]
> Ok, olin väärässä paikassa :) Helle-nextissä nidevarauksen teko ei nyt onnistu asiakkaalle, jolla on jo olemassa oleva nidevaraus. Koha ilmoittaa niteiden kohdalla: Varaus pitää tehdä tietueeseen. ![kuva](https://private-user-images.githubusercontent.com/99952449/321947290-73f16eb6-e13e-450e-8bde-ce6cb6324048.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTcxNzcsIm5iZiI6MTcxMjkxNjg3NywicGF0aCI6Ii85OTk1MjQ0OS8zMjE5NDcyOTAtNzNmMTZlYjYtZTEzZS00NTBlLThiZGUtY2U2Y2I2MzI0MDQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEyVDEwMTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMDA3ZDVmNTU0NjE2MjI0NTE3MmVhODE0Yjg4YWFjZDhiODkwYzdhZTNiZmQ4NjIwMTU4ZGFlZTJkNzY4NDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nP3XW1hQc1jlwlllDu2G0hqhQN1ztKTbrMpEVZngb2o)

Jos kyse on [tästä tietueesta, varauksesta ja asiakkaasta](https://helle-next.koha-suomi.fi/cgi-bin/koha/reserve/request.pl?biblionumber=1598465), niin asiakkaan jo olemassa oleva varaus kohdistuu tietueeseen, eikä niteeseen. Silloin voi tehdä vain tietueeseen kohdistuvia varauksia. :)

**Comment by Kati-Helle** [comment]
Totta! Olin tehnyt varauksen tietueeseen. Testasinpa taas, ja nyt nidevarauksena kuten pitää. Peruuta varaus -painike näkyvillä.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/cc686ac2-71d9-4d9e-99db-53208584eed8)

Painikkeesta paikallaan pysyvä pop
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1947e080-1902-42e9-ba69-d04ca2db0da2)

Vahvista poisto -painikkeesta ei tapahdu mitään.
Peruuta-painike sulkee ko. popupin.

**Comment by lasse-koha** [comment]
Painike oli jo kertaalleen poistettu mutta näköjään muutos ei ole tämänhetkisessä buildissä mukana. Poistuu seuraavassa buildissä.

**Comment by MikkoLiimatainen** [comment]
Nyt ei Peruuta varaus-painiketta näkynyt, eikä vastaani tullut hiirikättä nopeampia popup-ikkunoitakaan.

**Comment by Kati-Helle** [comment]
Helle-nextissäkään ei näy nyt Peruuta varaus -painiketta
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/d02e320d-2fec-45e8-827f-44fbbb639661)
