### ISSUE TITLE
Lumme: Laina- ja maksusääntöjen poisto epäonnistuu

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#898]
### Mikä vikana?

Kävin läpi Lumpeissa laina- ja maksusääntöjä ja tarkoituksena oli poistaa väärät/tarpeettomat säännöt. Kun sääntöä lähtee poistamaan poista-nappulasta, säännön poistumisen sijaan arvot resetoituvat. Sama ongelma toistui testillä. Lieköhän tämä sama ongelma myös muissa kimpoissa?

Esimerkkikuvassa oli tarkoitus poistaa lapsi- ja henkilöasiakkaan säännöt kirjastoauton säännöistä, mutta lapsiasiakkaan sääntöjen poistoyritys tuli näyttämään tältä: 

![Lainasäännöt](https://github.com/KohaSuomi/Koha/assets/129748294/7e758eb8-e6cc-452f-853d-569dad2ef322)

**Comment by emta001** [comment]
Tarkennuksena vielä, että tämä nimenomainen tilanne syntyy Savonlinnan kirjastoauton kanssa.

**Comment by Hanna-Lumme** [comment]
Pieksämäen autossa näyttää olevan myös omia sääntöjään ja niihin en ole viitsinyt koskea. Voisi olettaa, että ongelma toistuu myös tässä. 

Katja poisti myös tuon A3-säännön Oletussäännöt-osiosta, mitkä on tarkoitettu kaikille tyypeille ja sekin näkyy tuolla listalla vielä.

**Comment by emta001** [comment]
Ongelma johtuu decreaseloanhold-säännöstä eli sarakkeesta "Decreased loan period for high holds (day)". Se pitää tyhjentää manuaalisesti, jotta säännön voi poistaa. 

Tutkin lisää mikä tässä on, jotenkin tämä vaikuttaisi liittyvän yhteisön [bugiin 30694](https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=30694).

**Comment by emta001** [comment]
Liittyy tikettiin #259

**Comment by emta001** [comment]
Elikäs, meiltä on jäänyt vahingossa matkasta branch 0077, jossa tämän korjaus oli. Tuodaan se takaisin (ja tiputetaan sitten oikeasti seuraavassa versiossa).

**Comment by emta001** [comment]
Branchi palautettu testeille.

**Comment by Hanna-Lumme** [comment]
Lumpeiden testillä onnistuu muokkaus ja poisto.

**Comment by ReettaSiili** [comment]
Samoin Siilin testillä onnistui muokkaus ja poisto. Meillä ei normaalioloissa ole Decreased loan period for high holds (day) käytössä, mutta kun lisäsin sen, poisto onnistui silti.

**Comment by ajrajala** [comment]
Samaten vaski-testillä onnistui laina- ja maksusääntörivin poisto.

**Comment by Hanna-Lumme** [comment]
Nyt onnistui sääntöjen poisto tuotannossakin. 👍

**Comment by emta001** [comment]
Tämä on tuotannossa, tiketin voisi sulkea.
