### ISSUE TITLE
TäTin proxy Error

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#901]
### Mikä vikana?

Oulun luetteloinnista ilmoittivat viime viikolla (vko 44), että TäTissä on alkanut tulla proxy erroria. 

Viimeeksi sitä havaittiin Oulussa 30.10. klo 12.43. Tämä tapahtui, kun luetteloija vaihtoi oletuspohjasta äänitteen osakohdepohjaan. Luetteloija suoritti taustalla samalla poistotöitä TäTissä. Voisiko error johtua poistotöistä tai kahdesta yhtäaikaisesta hommasta?

**Comment by ajrajala** [comment]
Vaskissa havaittu proxy error -virheilmoitusta tietuetta tallentaessa, tällaiset ajankohdat on saatu ylös:
- 31.10. n. klo 10.45
- 3.11. klo Klo 11.01

**Comment by pknuuti** [comment]
Vaarassa havaittu Tätin tietuetta poistettaessa proxy error 7.11. klo 14:14.
Tietue https://tati.koha-suomi.fi/cgi-bin/koha/cataloguing/addbiblio.pl?op=delete&amp;biblionumber=1491549

**Comment by AnttHeik** [comment]
TäTissä Proxy Error 9.11. Klo 10.29 aloin muokata uutta tietuetta kopiosta:

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server

**Comment by emta001** [comment]
> TäTissä Proxy Error 9.11. Klo 10.29 aloin muokata uutta tietuetta kopiosta ja error tuli, kun vaihdoin oletuspohjasta äänitepohjaksi:
> 
> The proxy server received an invalid response from an upstream server. The proxy server could not handle the request
> 
> Reason: Error reading from remote server

Argh, tutkin tätä ja onnistuin tekemään jotain tyhmää. Tietue 2364012 saattoi mennä nyt jotenkin vinksalleen.

**Comment by AnttHeik** [comment]
> > TäTissä Proxy Error 9.11. Klo 10.29 aloin muokata uutta tietuetta kopiosta ja error tuli, kun vaihdoin oletuspohjasta äänitepohjaksi:
> > The proxy server received an invalid response from an upstream server. The proxy server could not handle the request
> > Reason: Error reading from remote server
> 
> Argh, tutkin tätä ja onnistuin tekemään jotain tyhmää. Tietue 2364012 saattoi mennä nyt jotenkin vinksalleen.

Ainakin se näyttää ihan ok:lta. Itse en käsitellyt tuota tietuetta. Päättelen, että joku muu poimi sen Melindasta samoihin aikoihin :)

**Comment by emta001** [comment]
> > > TäTissä Proxy Error 9.11. Klo 10.29 aloin muokata uutta tietuetta kopiosta ja error tuli, kun vaihdoin oletuspohjasta äänitepohjaksi:
> > > The proxy server received an invalid response from an upstream server. The proxy server could not handle the request
> > > Reason: Error reading from remote server
> > 
> > 
> > Argh, tutkin tätä ja onnistuin tekemään jotain tyhmää. Tietue 2364012 saattoi mennä nyt jotenkin vinksalleen.
> 
> Ainakin se näyttää ihan ok:lta. Itse en käsitellyt tuota tietuetta. Päättelen, että joku muu poimi sen Melindasta samoihin aikoihin :)

Vilkaisin ja siltä uupuu 999-kentät nyt, jotka kai aiemmin oli paikallaan. Kokeilin siis semmosta toiminnallisuutta kuin "Muokkaa tietuetta käyttäen pohjaa" enkä tajunnut, että se muokkaus menee suoraan työjonoon :sweat_smile:

**Comment by AnttHeik** [comment]
Ok, onkos se mahdollista, että tähän vaikuttaisi se, jos TäTissä ajaa raportteja tai tekee eräpoistoja tai erämuokkauksia samohin aikoihin?

**Comment by piiaseme** [comment]
> Ok, onkos se mahdollista, että tähän vaikuttaisi se, jos TäTissä ajaa raportteja tai tekee eräpoistoja tai erämuokkauksia samohin aikoihin?

Eli onko sulla Antti ollut lähes samanlainen tilanne tänään kuin oli 30.10.?

**Comment by AnttHeik** [comment]
> > Ok, onkos se mahdollista, että tähän vaikuttaisi se, jos TäTissä ajaa raportteja tai tekee eräpoistoja tai erämuokkauksia samohin aikoihin?
> 
> Eli onko sulla Antti ollut lähes samanlainen tilanne tänään kuin oli 30.10.?

Joo, paitsi itse en tehnyt poistoja tai raportin ajoja, mutta Päivillä oli ehkä joitakin käynnissä.

**Comment by pknuuti** [comment]
Tätissä 9.11. klo 12:19 yritin avata tietueen https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773 ja sain proxy errorin "Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request

Reason: Error reading from remote server"

**Comment by lmstrand** [comment]
> Tätissä 9.11. klo 12:19 yritin avata tietueen https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773 ja sain proxy errorin "Proxy Error
> 
> The proxy server received an invalid response from an upstream server. The proxy server could not handle the request
> 
> Reason: Error reading from remote server"

Lokissa merkinnät:

[Thu Nov 09 12:19:19.989245 2023] [proxy_http:error] [pid 455242:tid 139739898304256] (104)Connection reset by peer: [client 10.0.36.254:22998] AH01102: error reading status line from remote server httpd-UDS:0, referer: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773
[Thu Nov 09 12:19:19.989303 2023] [proxy:error] [pid 455242:tid 139739898304256] [client 10.0.36.254:22998] AH00898: Error reading from remote server returned by /cgi-bin/koha/catalogue/MARCdetail.pl, referer: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773
[Thu Nov 09 12:19:19.993457 2023] [proxy_http:error] [pid 455242:tid 139739571152640] (20014)Internal error (specific information not available): [client 10.0.36.254:22667] AH01102: error reading status line from remote server httpd-UDS:0, referer: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773
[Thu Nov 09 12:19:19.993507 2023] [proxy:error] [pid 455242:tid 139739571152640] [client 10.0.36.254:22667] AH00898: Error reading from remote server returned by /api/v1/app.pl/api/v1/contrib/kohasuomi/biblios/2323773/componentparts, referer: https://tati.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=2323773

Tällaisia tapauksia myös lokeilla:

[Thu Nov 09 12:16:09.723251 2023] [proxy_http:error] [pid 455241:tid 139739638261504] (104)Connection reset by peer: [client 10.0.36.254:11622] AH01102: error reading status line from remote server localhost:8081, referer: https://lumme.koha-suomi.fi/
[Thu Nov 09 12:16:09.723290 2023] [proxy:error] [pid 455241:tid 139739638261504] [client 10.0.36.254:11622] AH00898: Error reading from remote server returned by /service/api/biblio/active/Lumme/416322, referer: https://lumme.koha-suomi.fi/

**Comment by AnttHeik** [comment]
Virhe tietuetta tallentaessa 10.11 klo 11.07. Tälle tuli nyt tietuenumeroksi: 2408102

**Comment by ajrajala** [comment]
Vaskissa eilen kuulemma useita havaintoja proxy errorista ja äskettäin klo 13:20 oli tullut sellaisen tietueen kohdalla kuin 2408133. Onko näistä yksittäisistä tapauksista vielä lisähyötyä, mietin pyydänkö kuvailijoita ilmoittelemaan törmäämistään tapauksista?

**Comment by ajrajala** [comment]
Sain meidän kuvailijoilta vielä tällaisia lisähavaintoja proxy error -ongelmasta aiheutuvaan tietojen katoamiseen liittyen:

- Proxy errorin iskiessä katoavat tiedot ovat usein sellaisia, jotka esiintyvät kenttätoistumissa – eli jos jotain kenttää tai osakenttää on lisännyt useita toistumia (esim. monia asiasanoja 650-kenttään), niin Proxy Errorin jäljiltä jää tallennettaessa vain ensimmäinen kyseinen kenttä muiden kadotessa. Näin ei käy kuitenkaan aina, vaan sattumanvaraisesti, hiljattain alusta asti tehtyyn tietueeseen iski proxy error ensimmäisellä tallennuksella ja mitään tietoja ei huomattu sillä kertaa kadonneen.
- Muokatessa tietueita, tai käyttäessä uuden tekemisen pohjana jotain toista jo valmista tietuetta, tietojen häviämisiä tuntuisi tulevan enemmän (ehkä sellaisissa on usein enemmän dataakin).

**Comment by AnttHeik** [comment]
Onkohan tälle Proxy errorille tehtävissä mitään? Näitä tulee aina silloin tällöin edelleen tietueita tallentaessa. Tänäänkin 19.12. pari kertaa jo.

**Comment by janPasi** [comment]
Ongelmat liittyvät luultavasti koha-suomi-servicesiin, eli tietueiden valutuspalveluun. En nyt äkkipäätä osaa arvata mikä siellä on vinossa, mutta kokeilinpa kuitenkin käynnistää sen uusiksi. Katsotaan olisiko siitä ensiapua. Services poistuu käytöstä versiopäivityksessä ja sen toiminnallisuus siirtyy Koha-pluginiin.

**Comment by johannaraisa** [comment]
Tietueen muokkaus ei kutsu Mikropalvelua, niitä käsitellään ajastetulla skriptillä tai RESTin kautta. Minua hieman mietityttää noiden plack workereiden määrä, onhan tässä tullut lisää Täti-kuvailijoita ja jos kaikki siellä tekevät jotain, niin ehkä ei kaikkeen riitä workerit. Lisäsin nyt kokeiluksi workereiden määrää.

**Comment by johannaraisa** [comment]
Onkohan näitä vielä tullut vastaan?

**Comment by AnttHeik** [comment]
Ei minulle ainakaan tuon viimeisen korjauksen jälkeen. Muista kuvailijoista en ole kuullut.

**Comment by annavii** [comment]
Turun kuvailijat eivät ole enää törmänneet virheilmoitukseen.

**Comment by emta001** [comment]
Ongelma näyttäisi ratkenneen. @piiaseme suljetko tiketin?
