### ISSUE TITLE
Vaski: API-tunnukset Turun tietovarastolle

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#905]
### Tukipyyntö

Tarvitsemme API-tunnukset Raportteri-rajapinnan käyttöön Turun tietovarastolle.

Tunnukset voi toimittaa Loihteen kehittäjälle milla-linnea.keranen@loihde.com

**Comment by lmstrand** [comment]
Loin Vaski-tuotantoon api-asiakkaan borrowernumberilla 396021 ja annoin raporttipluginien käyttöoikeuden. Tiliin liitetty API-tunnus lähetetty mainittuun emailiin onetimesecretinä.

**Comment by MikkoLiimatainen** [comment]
Tuo raporttiplugin käyttöoikeus puuttuu käyttäjältä ja sen tallennus ei onnistu. Mikähän tuossa on vialla?

**Comment by MikkoLiimatainen** [comment]
Ongelma ratkaistu. Liittyy tikettiin https://github.com/KohaSuomi/Koha/issues/909
