### ISSUE TITLE
Siilinjärvi: Varausta tehdessä noutopaikan valinta tyhjentää muut sitä ennen tehdyt valinnat

### ISSUE THREAD

**Issue by ReettaSiili** [KohaSuomi/Koha#907]
### Mikä vikana?

Bugi #5467 Redminestä on edelleen olemassa. Tämä voi Annelin testien perusteella kyllä olla pelkästään Siilin ongelma.

Varausta tehdessä noutopaikan valinta tyhjentää muut sitä ennen tehdyt valinnat. Ainakin kiireettömän varauksen valinta tai nidevalinta tai viestin lisääminen Muuta-kenttään katoavat, jos noutopaikka valitaan vasta niiden jälkeen. Ongelman voi toki kiertää valitsemalla noutopaikan ensimmäiseksi ja tekemällä vasta sen jälkeen muut valinnat.

### Mitä pitäisi tapahtua

Varauksenteossa valintojen pitäisi säilyä, riippumatta siitä missä järjestyksessä niitä tehdään.

**Comment by AnneliO** [comment]
Kassu tutki tätä ja sivun uudelleenlatautuminen johtuu siitä, että Siilissä on käytössä UseBranchTransferLimits-järjestelmäasetus. Otin tuon pois päältä siili-testillä ja sivu ei tosiaan enää latautunut kirjastonvalinnan muuttuessa.

Näyttäisi vähän, että Siilissä on [kuljetus sallittu kaikkien yksiköiden välillä](https://siili-test.koha-suomi.fi/cgi-bin/koha/admin/branch_transfer_limits.pl), joten asetus on ehkä turhaan päällä. Jos näin on, niin tämän ongelman saa siis muuttamalla  UseBranchTransferLimits-järjestelmäasetukseen "Älä käytä" -vaihtoehdon. :)

**Comment by ReettaSiili** [comment]
Asetuksen muuttaminen korjasi ongelman myös tuotannossa. Kiitos, enpä olisi tuollaisesta asetuksesta keksinyt ratkaisua etsiä :) Suljen tämän.
