### ISSUE TITLE
Viestien lähetyksen ajastusmuutos 5 min välein

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#908]
### Tukipyyntö

Taululukkojen hallitsemiseksi ajo muutetaan tapahtuvaksi 5 min välein, 500 kpl/ajo.

Kimpat, joihin muutos tehty:

- [x] Vaski
- [x] Helle
- [x] Siili
- [x] Vaara
- [x] Kyyti
- [x] Kirkes
- [x] Lumme
- [x] Lappi
- [x] Outi

**Comment by lmstrand** [comment]
Ajastukset muutettu kaikkiin tuotantoihin.

**Comment by Tuomas-Kyyti** [comment]
Muutos olisi hyvä päivittää myös tuonne https://koha-suomi.fi/dokumentaatio/ajastetutajot/#asiakasviestint%C3%A4

**Comment by lmstrand** [comment]
> Muutos olisi hyvä päivittää myös tuonne https://koha-suomi.fi/dokumentaatio/ajastetutajot/#asiakasviestint%C3%A4

Päivitetty myös asiakasviestintä-osioon.
