### ISSUE TITLE
Virkailijaoikeuksien tallentumisessa/käytössä ongelmia, jos korttinumero puuttuu asiakkaalta

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/Koha#909]
### Mikä vikana?

Tullut vastaan Vaskin API-käyttäjän kanssa. Raportterirajapinta ei sallinut pääsyä rajapintaan, vaikka tietokantaan tallentui oikeudet oikein (user_permissions). Oikeuksien näkymisessä myös häikkää virkailijaliittymässä, kun vain yksi oikeus (report) valittu. Ilmeisesti vaati asiakkaalle korttinumeron, jotta oikeudet toimivat kuten kuuluu. Korttinumeron lisäämisen jälkeen plugin-oikeudet olivat eri järjestyksessä virkailijaliittymässä kuin ilman korttinumeroa.

**Comment by lmstrand** [comment]
Ongelma johtui ilmeisesti siitä, että ilman korttinumeroa ei asiakastilillä ollut userid:tä. Korttinumero kopioidaan triggerillä userid:ksi.

**Comment by AnneliO** [comment]
Onko tässä vielä jotain kesken vai miksi Lari avasit tiketin uudelleen? :)

**Comment by lmstrand** [comment]
Koska mielestäni userid:n ei tulisi olla pakollinen ainakaan API-tyypin tileille jos tunnistautuminen tapahtuu Oauth:n kautta, mutta tämä vaatisi yhteisön kanssa keskustelua johon en nyt heti ole kyllä ryhtymässä. Suljen tiketin. Avataan uudelleen jos asiaa joskus edistetään.

**Comment by emta001** [comment]
Tämän kanssa päästiin taas tuskailemaan kohtuuttoman pitkä tovi, joten avaan tiketin ja viedään asia yhteisöön.

**Comment by emta001** [comment]
Tästä onkin tehty tuoreempi tiketti #1974. Suljen tämän ja edistetään asiaa tuossa toisessa.
