### ISSUE TITLE
Valkealan kirjaston niteet ei-varattaviksi

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#910]
### Tukipyyntö

Valkealan kirjasto on muuton vuoksi kiinni 16.11.2023 - 1.1.2024.

Niteet pitäisi muuttaa ei-varattaviksi seuravasti:

Jos nykyinen kirjasto on KOU_VA ja nide on saatavana, muutetaan damaged-arvoksi 3 _Ei saatavana, ei varattavissa (kirjasto suljettu)_

Muutosta ei tehdä, jos niteellä on
- damaged-arvo 2 _Saatavana, ei varattavissa_
- not_loan-arvo -1 _tilattu_
- not_loan-arvo -3 _viimeisteltävänä_

Eikä myöskään, jos nide on
- kuljetettavana
- kuljetettavana kiinni jääneeseen varaukseen
- lainassa
- odottamassa varattuna noutoa

Ajon toivottu ajankohta on to 16.11. aamulla. Voi tehdä myös ti 15.11. klo 16 jälkeen.

**Comment by johannaraisa** [comment]
Tarkennuskysymys, pitäisikö osua jos on esim. Laskutettu-tilassa? Tuolla kerrotaan, että saatavana oleviin niteisiin, mikä käytännössä tarkoittaa, että niiden not_loan-arvo on 0.

**Comment by Tuomas-Kyyti** [comment]
Ei tarvi osua oikeastaan mihinkään niteeseen, jossa on joku notforloan-tila. Nehän eivät tartu varauksiin muutenkaan.

**Comment by johannaraisa** [comment]
Nyt on tämä muutos tehty.

```sql
CREATE TABLE items_kd910_20231116 SELECT i.itemnumber, i.holdingbranch, i.onloan, r.found, i.damaged FROM items i LEFT JOIN reserves r ON(i.itemnumber = r.itemnumber) WHERE i.holdingbranch = "KOU_VA" AND i.notforloan = 0 AND i.damaged = 0 AND r.found IS NULL AND i.itemnumber NOT IN (SELECT itemnumber FROM issues) AND i.itemnumber NOT IN (select itemnumber from branchtransfers where datearrived is null);
UPDATE items i LEFT JOIN items_kd910_20231116 kd ON(i.itemnumber = kd.itemnumber) set i.damaged = 3 where kd.itemnumber is not null;
```

**Comment by Tuomas-Kyyti** [comment]
Kiitos. Vaikuttaa olevan kunnossa.
