### ISSUE TITLE
Varaukset eivät tule hyllyvarausraportille

### ISSUE THREAD

**Issue by MikkoLiimatainen** [KohaSuomi/Koha#911]
### Mikä vikana?

Vaskissa asiakas (borrowernumber=323250) oli kirjastoon yhteydessä, kun hän ei ollut saanut aktivoimiaan varauksia. Asiakas oli varausjonoissa ensimmäisenä ja vapaita niteitä oli kirjastoissa, mutta varaukset eivät tulleet hyllyvarauslistalle.

Asiakkaan ilmoittamat tapaukset ovat varaus-id:t 268058 ja 276815, mutta ne on nyt jo käsitelty virkailijan toimesta. Nähdäkseni tälläkin hetkellä samalla asiakkaalla on varaus 251126, joka on ensimmäisenä jonossa ja vapaita niteitä löytyy, mutta hyllyvarausraportilla kyseistä teosta ([Uudesta maailmasta](https://vaski.koha-suomi.fi/cgi-bin/koha/catalogue/detail.pl?biblionumber=4193966)) ei näy.

**Comment by lmstrand** [comment]
Samankaltainen tapaus: https://github.com/KohaSuomi/Koha/issues/868

**Comment by AnneliO** [comment]
Oisko tässä nyt ihan vain kyse siitä, että  HoldsToPullStartDate-järjestelmäasetuksessa on määritetty, että mukaan haetaan maksimissaan 730 päivää vanhoja varauksia? Tuo kyseisen teoksen varaus on jo 817 päivää vanha.

**Comment by MikkoLiimatainen** [comment]
No, tuohan se näytti olevan ongelmana. Oli jäänyt muuttamatta, kun varausten voimassaoloaikaa pidennettiin.
