### ISSUE TITLE
Tietueen 1544451 poisto ei onnistu OUTIssa.

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#913]
### Tukipyyntö

Tietueen 1544451 poisto ei onnistu OUTIssa. Tietue antaa ilmoituksen "Tietuetta 1544451 ei ole tietokannassa", mutta se kuitenkin kummittelee hakutuloslistassa. 
![tietue](https://github.com/KohaSuomi/Koha/assets/118160273/3ad0000b-4bd6-4a07-bcba-8a21f2c277fb)

Tietueen poisto eräajona puolestaan antaa alla olevan virheilmoituksen. 
![tietueen_poisto](https://github.com/KohaSuomi/Koha/assets/118160273/7d42371f-9658-485d-ba3a-a077eb1343e1)

**Comment by janPasi** [comment]
Jäänyt näköjään roikkumaan indeksiin, vaikka tietue on poistettu. Poistellaanpa indeksimerkintä.

**Comment by janPasi** [comment]
Nyt poistettu.

**Comment by velimarj** [comment]
Kiitos, suljen tiketin.
