### ISSUE TITLE
Lumme: niteissä vanhoja Tila-arvoja

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#917]
### Tukipyyntö

Lumpeissa on joitakin niteitä, joiden Tila-arvot ovat vanhentuneita. Tästä syystä kirjojen Tila-kohta ei näy oikein. Yhtenä esimerkkinä on Mikkelin nide tietueessa 205941 - nide on merkitty vanhalle Kadonnut-arvolle. Nämä pitäisi saada korjattua.

**Comment by AnneliO** [comment]
Johanna otti jo tämän itsellensä, mutta onko tässä siis kyse niteistä, joissa ei ole kadonnut-tilaa, mutta on merkitty päivä, jolloin nide on kadonnut? Eli niteet, jotka löytyvät esim. tällä raportilla: https://lumme.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?phase=Run+this+report&reports=645&limit=100

**Comment by johannaraisa** [comment]
> Johanna otti jo tämän itsellensä, mutta onko tässä siis kyse niteistä, joissa ei ole kadonnut-tilaa, mutta on merkitty päivä, jolloin nide on kadonnut? Eli niteet, jotka löytyvät esim. tällä raportilla: https://lumme.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?phase=Run+this+report&reports=645&limit=100

Juu, raportilta näkee nuo. Tuo itemlost = 1 ei enää pidä paikkaansa, koska Lumpeessa ne koodit on negatiivisia numeroita. Korjaan ne kannasta.

**Comment by AnneliO** [comment]
Kohassa itemlost=1 on yleensä se "oikea" kadonnut-arvo. Pitäisikö arvot muuttaa vastaamaan muita asennuksia? Edellisessä versionpäivityksessä nuo miinusmerkkiset arvot aiheuttivat ongelmia, koska konversio lisäsi uusia lost-arvoja alkaen nollasta, jolloin kaikki nolla-arvoiset olivat ikään kuin kadonneita.

**Comment by johannaraisa** [comment]
Olikohan tolle jotain syytä, että on miinusmerkkisiä? Tapahtuuko palauttaessa jotain eritavalla?

**Comment by AnneliO** [comment]
> Olikohan tolle jotain syytä, että on miinusmerkkisiä? Tapahtuuko palauttaessa jotain eritavalla?

Olisiko joku joskus testannut ja yrittänyt saada aikaiseksi jotain tiettyä toiminnallisuutta. Muistaakseni Lumpeissa pohdittiin jossain vaiheessa erilaisia ratkaisuja (ehkä) näyttelyssä oleville tms. Minusta lost-arvoissa miinusmerkkiset eivät toimi eri tavalla kuin plusmerkkiset. Notforloan-arvoissa etumerkillä on merkitystä.

**Comment by johannaraisa** [comment]
@Hanna-Lumme yhtenäistetäänkö nuo Lumpeen Kadonneet-tilat vastaamaan muita kimppoja?

**Comment by Hanna-Lumme** [comment]
Joo, yhtenäistetään vaan. Keskusteltiin tuosta niin on varmaan jäänyt jossain vaiheessa tuonne, kun on kokeiltu joskus sitä Tilanahtausvarasto-tilan poistoa palautuksessa. Kiitoksia!

**Comment by johannaraisa** [comment]
Nyt on yhdenmukaistettu nuo Kadonnut-tilat.

```sql
CREATE TABLE items_kd917_20231116 SELECT itemnumber, itemlost FROM items WHERE itemlost != 0 AND itemlost != 1 AND itemlost != 2 AND itemlost != 3;
UPDATE items set itemlost = 1 WHERE itemlost = -1;
UPDATE items set itemlost = 2 WHERE itemlost = -2;
UPDATE items set itemlost = 3 WHERE itemlost = -3;
UPDATE authorised_values set authorised_value = 1 WHERE authorised_value = -1 AND category = 'LOST';
UPDATE authorised_values set authorised_value = 2 WHERE authorised_value = -2 AND category = 'LOST';
UPDATE authorised_values set authorised_value = 3 WHERE authorised_value = -3 AND category = 'LOST';
```

**Comment by Hanna-Lumme** [comment]
Kiitos paljon avusta! 👍
