### ISSUE TITLE
Lumme: niteiden automaattiseen muokkaukseen iän mukaan "tyhjä arvo"?

### ISSUE THREAD

**Issue by Katja-Lumme** [KohaSuomi/Koha#918]
### Tukipyyntö

Kamppailemme edelleen hyllytarkenteen automaattisen poistumisen kanssa. Eli **tilanahtausvarasto -hyllytarkenne** pitäisi saada poistumaan niteeltä kun asiakas sen lainaa tai palauttaa. Tämä oli ennen kesän 22 versiovaihtoa toteutettu kovakoodauksella tms. 

Mutta. Niteiden iän mukainen muokkaus voisi toimia tässä esimerkiksi jos niteen oltua lainassa yhden päivän (datelastborrowed-arvo 1?) itemsublocation-kenttä muuttuisi tyhjäksi, poistuisi siis niteestä kokonaan.

Onnistuisiko tämmöinen mitenkään? Tai muita ehdotuksia miten tätä voitaisiin ratkaista:P?

![kuva](https://github.com/KohaSuomi/Koha/assets/98803917/415e1278-7c43-40d1-9150-e22552fc9e9c)

**Comment by AnneliO** [comment]
Tuo aikamääre pitää testata vaikka testikannassa. Ajo tehdään öisin, joten jos nide lainataan tänään, niin tippuuko tilanahtaus-tila jo seuraavana yönä vai vasta sitä seuraavana yönä? Tai onko sillä merkitystä? Toimiikohan tuossa ikänä 0 päivää?

**Comment by Katja-Lumme** [comment]
Moikka, testailuissa ei arvolla 1 tai arvolla 0 ainakaan tippunut hyllytarkenne pois. Eli tuon ylläolevan kaltainen sääntö ei toimi niin että se korvaava arvo on tyhjä ruutu...

**Comment by AnneliO** [comment]
Onkohan ajo päällä testeillä?

**Comment by Katja-Lumme** [comment]
Uskalsin kokeilla tuotannossakin tätä, ei tapahdu mitään.

**Comment by AnneliO** [comment]
Todennäköisesti tuo ajo ei ole päällä Lumpeissa, jos sitä ei ole aiemmin käytetty. Sitä on laitettu päälle vain silloin, jos toiminto otetaan kimpassa käyttöön.

**Comment by Katja-Lumme** [comment]
Aa ok! No sittenhän tässä on vielä mahdollisus, että tää toimii:D:D @emta001 @johannaraisa : saako meille tuon ajon päälle? Testille nyt vaikka sitten ekaksi?

**Comment by emta001** [comment]
> Aa ok! No sittenhän tässä on vielä mahdollisus, että tää toimii:D:D @emta001 @johannaraisa : saako meille tuon ajon päälle? Testille nyt vaikka sitten ekaksi?

Mie voin käydä laittaa testille päälle :) mikä ajo tässä on siis kyseessä?

**Comment by AnneliO** [comment]
automatic_item_modification_by_age.pl

**Comment by emta001** [comment]
Nyt on se on päällä, pyörähtää päälle minuutin yli puolen yön. Hoksauta @Katja-Lumme miuta, jos haluutte sen testille päälle vaikka tämän päivän aikana, niin käyn säätämässä.

**Comment by Katja-Lumme** [comment]
> Nyt on se on päällä, pyörähtää päälle minuutin yli puolen yön. Hoksauta @Katja-Lumme miuta, jos haluutte sen testille päälle vaikka tämän päivän aikana, niin käyn säätämässä.

Jesh, riittää hyvin, että puolen yön jälkeen pyörähtää, tutkaillaan tuloksia maanantaina sit😊

**Comment by Katja-Lumme** [comment]
No nyt ehdin tutkia, niin tämä esimerkki testissä on nyt sekä lainassa, että saatavana, snif. 
![kuva](https://github.com/KohaSuomi/Koha/assets/98803917/34ec8e56-a68e-42f7-91de-f6f42c36403f). Olisikohan vikana se, ettei hyllytarkenteelle ole määritettyä korvaajaa TIGHT -> ?, vaan sen pitäisi poistua kokonaan🤔

**Comment by AnneliO** [comment]
Hyllytarkennehan tuossa on kyllä poistunut ihan oikein. Mitä katselen tuon niteen muutoslokia, niin sillä ei näy siellä ollenkaan, että onloan-arvoa olisi ollutkaan, edes ennen ajoa. Eli kun se on tyhjä, on tilana "Saatavana".

**Comment by Katja-Lumme** [comment]
> Hyllytarkennehan tuossa on kyllä poistunut ihan oikein. Mitä katselen tuon niteen muutoslokia, niin siellä ei näy ollenkaan, että onloan-arvoa olisi ollutkaan, edes ennen ajoa. Eli kun se on tyhjä, on tilana "Saatavana".

Aa, olisiko jälleen lisää toivoa:D Mutta sttenpä tipahdin, koska mie lainasin tämän kirjan tuolle asiakkaalle perjantaina ja sehän on hänellä edelleen lainassa? Ehkä tarkoitit nyt jotain muuta mitä en tajunnut?

**Comment by Katja-Lumme** [comment]
> Juu, se on kyllä lainassa, mutta jostain syystä niteen onloan-arvo on tyhjä, vaikka siinä pitäisi olla eräpäivä. Näin on käynyt silloin tällöin, esim. tiketit #774 ja #210. Eli aattelisin, että kyseessä on nyt sen osalta jokin muu ongelma.
> 
> Tuonhan voi testata tekemällä lainan uudelleen, tarkistaa sen jälkeen, että niteellä ei ole tuota Saatavana-tilaa lainassa tilan lisäksi ja oottelee taas ajon pyörähtämistä. Sitten taas tarkistaa tilanteen uudelleen.

No nyt muistan minäkin, että joskus näitä oli Lumpeillakin jokin tapaus. Mutta jes, testailen uudelleen👍

**Comment by Katja-Lumme** [comment]
Wu-huu! Toimi! Kahdesta testikannasta asiakkaalla lainassa olleesta kirjasta oli poistunut tilanahtaus-tila ja olivat edelleen ihan oikein lainassa asiakkaalla kuitenkin.. @emta001, laitatko ajon päälle myös tuotantoon😊.

**Comment by emta001** [comment]
> Wu-huu! Toimi! Kahdesta testikannasta asiakkaalla lainassa olleesta kirjasta oli poistunut tilanahtaus-tila ja olivat edelleen ihan oikein lainassa asiakkaalla kuitenkin.. @emta001, laitatko ajon päälle myös tuotantoon😊.

Ajo on nyt päällä myös tuotannossa.

**Comment by AnneliO** [comment]
Jos tämä on ok, niin suljetko Katja tiketin? :)

Sellainen huomio vielä, että versiossa 23.11 näyttäisi olevan uusi järjestelmäasetus UpdateItemLocationOnCheckout, jolla saa päivittymään niteen **hyllypaikan** toiseen lainauksen yhteydessä. Ennestään olikin jo asetus UpdateItemLocationOnCheckin, joka tekee saman, mutta palautuksen yhteydessä.

**Comment by AnneliO** [comment]
Kuittausta ei ole tullut yli kuukauteen, joten oletan asian olevan kunnossa ja suljen tiketin. :)
