### ISSUE TITLE
Kirjastoon TUSK tehtyjen varausten noutopaikan muuttaminen

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#920]
### Tukipyyntö

Tarvitsisimme maanantaiaamuna 27.11. noutopaikan muutoksen varauksille, joiden

- branchcode on tällä hetkellä 'TUSK'
- found IS NULL

Varausten uudeksi branchcode-arvoksi pitäisi asettaa 'TUIL'.

**Comment by paxed** [comment]
Muutos tehty näillä rimpsuilla:

create table reserves_kd920_20231127 select * from reserves where branchcode='TUSK' and found is null;
update reserves set branchcode='TUIL' where branchcode='TUSK' and found is null;


ja koski 684 varausta.

**Comment by ajrajala** [comment]
Mainiota, tämä ok, kiitos!
