### ISSUE TITLE
Raportit kellutuksen hallinnan työkalua varten

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#928]
### Tukipyyntö

Kolme raporttia (teos-, nide- ja lainaajatiedot), raporteille tarvittavat tiedot määritelty erilliseen excel-tiedostoon joka toimitettu sähköpostilla. Liittyy tikettiin #925 .

**Comment by atarnus** [comment]
**Asiakastiedot:**
Näiden kohdalla on vielä vähän haussa, että millä parametrillä niiden raportointia halutaan ohjata. Halutaanko hakea asiakkaat esim. kirjastoittain? Halutaanko yksittäisen asiakkaat kaikki lainat listata? Ikätiedoksi riittänee syntymävuosi, joka on helppo poimia? Pidetäänkö borrowernumber "piilossa", vaikka sitä toki käytetään yhdistämään asiakas lainoihin tarvittaessa.

_Tässä simppeli alku, jossa listataan lainat lainaajan mukaan:_
```
   SELECT b.borrowernumber,
          CASE WHEN b.firstname LIKE '% %'
          THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
          ELSE b.firstname 
          END AS firstname,
          year(b.dateofbirth) AS birthyear,
          iss.itemnumber, iss.branchcode
     FROM borrowers b LEFT JOIN issues iss USING(borrowernumber)
    WHERE itemnumber IS NOT NULL
 ORDER BY b.borrowernumber
```

**Teostiedot:**
- Aikarajaus: Onko tarpeen kerätä kaikkien kolmen taulun (biblio, biblioitems, biblio_data_elements) timestampit aikarajausta varten? Voidaan mennä yhdellä, katsoa näistä uusinta tai katsoa näistä kaikkia.
- Varaukset: Ao. lausekkeissa tehdään teokseen kohdistuvien varauksien laskenta. On myös mahdollista antaa tämä tieto kyllä/ei -tasolla.

_Tässä huomioidaan kaikki kolme timestampia ja valitaan niistä uusin, jonka mukaan haku tehdään:_
```
  SELECT b.biblionumber, b.title, b.subtitle, b.part_name, b.part_number, b.author, 
   	   bi.isbn, bi.ean, bi.publicationyear, bi.editionstatement, bi.collectiontitle,
         bde.primary_language, bde.itemtype, bde.genres,
  	   COUNT(r.reserve_id) AS 'reserves',
         date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) AS 'timestamp' 
    FROM biblio b
         
         LEFT JOIN biblioitems AS bi
         ON b.biblionumber = bi.biblionumber
         LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements AS bde
         ON b.biblionumber = bde.biblionumber
         LEFT JOIN reserves AS r
         ON b.biblionumber = r.biblionumber

   WHERE date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) BETWEEN <<Start Date|date>> AND <<End Date|date>> 
GROUP BY b.biblionumber
```
_Tässä huomioidaan kaikki kolme timestampia, ja haetaan niistä kaikista:_
```
  SELECT b.biblionumber, b.title, b.subtitle, b.part_name, b.part_number, b.author, 
         bi.isbn, bi.ean, bi.publicationyear, bi.editionstatement, bi.collectiontitle,
    	   bde.primary_language, bde.itemtype, bde.genres, COUNT(r.reserve_id) AS 'reserves',
         b.timestamp, bi.timestamp, bde.last_mod_time
    FROM biblio b
         LEFT JOIN biblioitems AS bi
         ON b.biblionumber = bi.biblionumber
         LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements AS bde
         ON b.biblionumber = bde.biblionumber
         LEFT JOIN reserves AS r
         ON b.biblionumber = r.biblionumber
         CROSS JOIN
         (SELECT <<Alkupv|date>> AS 'alku', <<Loppupv|date>> AS 'loppu') AS a
   WHERE (b.timestamp BETWEEN alku AND loppu)
      OR (bi.timestamp BETWEEN alku AND loppu)
      OR (bde.last_mod_time BETWEEN alku and loppu)
GROUP BY b.biblionumber
```

**Nidetiedot**
```
  SELECT i.itemnumber, i.biblionumber, i.holdingbranch, i.permanent_location, i.ccode,
         i.sub_location, i.cn_sort, i.itemnotes, i.dateaccessioned, i.issues,
         i.datelastborrowed, i.timestamp,
         CASE WHEN i.onloan IS NOT NULL OR i.itemlost != 0 OR i.notforloan != 0 OR r.found IS NOT NULL
         OR (bt.itemnumber IS NOT NULL AND bt.datearrived IS NULL AND bt.datecancelled IS NULL)
         THEN 'No'
         ELSE 'Yes'
         END AS on_shelf
    FROM items AS i

   		 LEFT JOIN reserves AS r
     	 ON i.itemnumber = r.itemnumber
		 LEFT JOIN branchtransfers AS bt
         ON i.itemnumber = bt.itemnumber
         
   WHERE date(i.timestamp) BETWEEN  <<Start Date|date>> AND <<End Date|date>>
         GROUP BY i.itemnumber
```

**Comment by atarnus** [comment]
Tässä vaihtoehtoinen lähestymistapa asiakaslistaan:

_Listaa asiakkaat, joilla aktiivisia lainoja kyseisessä kirjastossa, branch-sarakkeessa näkyy kirjasto, josta asiakkaalla eniten lainoja: (tässä vain lainojen määrä, ei eriteltyjä itemnumbereita)_
```
SELECT CASE WHEN b.firstname LIKE '% %'
       THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
       ELSE b.firstname 
       END AS firstname,
       year(b.dateofbirth) AS birthyear,  
       count(iss.itemnumber) AS loans,
       (SELECT iss.branchcode
          FROM issues iss
         WHERE iss.borrowernumber = b.borrowernumber
         GROUP BY iss.branchcode
         ORDER BY count(iss.branchcode) DESC
         LIMIT 1) AS branch 
  FROM borrowers b
       INNER JOIN issues iss ON b.borrowernumber = iss.borrowernumber
 WHERE iss.branchcode LIKE <<Branchcode>>
 GROUP BY b.borrowernumber
 ORDER BY loans DESC;
```

Näissä katsotaan nyt tosiaan asiakkaita, joilla on aktiivisia lainoja. Aikarajaaminen ei ole järkevää pelkästään aktiivisten lainojen kanssa, koska ne palautettaessa siirtyvät old_issues tauluun, eli taaksepäin menevät aikarajaukset antavat sitten aina nollatulosta. Jos old_issues halutaan mukaan, niin sitten käydään läpi lainahistoriaa, jossa asiakkaista osa on anonymisoitu.

Onko tarkoitus saada raporttiin mukaan ei-lainaavia asiakkaita, ja onko heitä tarpeen saada luokiteltua eri kirjastoille? Lainoihin liittyvä branchcode taitaa kuitenkin olla ainoa ajantasalla oleva branchcode-tieto. Ylemmästä asiakas/laina-lausekkeesta voi poistaa WHERE-rivin, jolloin se listaa mukaan myös asiakkaat, joilla ei ole lainoja, mutta branchcode tieto jää näistä sitten myös puuttumaan.

**Comment by atarnus** [comment]
Nidetietoihin voi helposti myös yhdistää voimassaolevan lainauksen tiedot. Mikäli halutaan käyttää lainahistoriaa, sitä ei kannattane kytkeä nidetietoihin suoraan, old_issues taulu on massiivinen ja siihen suoritetut haut hitaita. Nämä nidehaut taas tulevat nopsaan.

_Nidetiedot + mukaan tämänhetkinen laina:
- kirjasto, josta lainattu
- lainaajan etunimi
- lainaajan syntymävuosi_

```
SELECT i.itemnumber, i.biblionumber, i.holdingbranch, i.permanent_location, i.ccode,
       i.sub_location, i.cn_sort, i.itemnotes, i.dateaccessioned, i.issues,
       i.datelastborrowed, i.timestamp,
       CASE WHEN i.onloan IS NOT NULL OR i.itemlost != 0 OR i.notforloan != 0 OR r.found IS NOT NULL
       OR (bt.itemnumber IS NOT NULL AND bt.datearrived IS NULL AND bt.datecancelled IS NULL)
       THEN 'No'
       ELSE 'Yes'
       END AS on_shelf,
       iss.branchcode AS loaned_from,
       CASE WHEN b.firstname LIKE '% %'
       THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
       ELSE b.firstname 
       END AS loaner,
       year(b.dateofbirth) AS birthyear
  FROM items AS i
       LEFT JOIN issues AS iss
       ON i.itemnumber = iss.itemnumber
       LEFT JOIN borrowers AS b
       ON iss.borrowernumber = b.borrowernumber
       LEFT JOIN reserves AS r
       ON i.itemnumber = r.itemnumber
       LEFT JOIN branchtransfers AS bt
       ON i.itemnumber = bt.itemnumber
 WHERE date(i.timestamp) BETWEEN <<Alkupv|date>> AND <<Loppupv|date>>
 GROUP BY i.itemnumber
```

**Comment by ajrajala** [comment]
Kiitos eri vaihtoehdoista! Joitain huomioita tuli kaikkiin, laitan huomiot ja vastaukset kustakin raportista omina kommentteinaan.

**Asiakastiedot:**

Tässä ensimmäinen, simppeli vaihtoehto vaikuttaisi käyttökelpoisimmalta kellutusprojektiin. Lainaajatiedot on tarkoitus hakea harvemmalla syklillä, joten sen vuoksi päädyttiin myös siihen ettei yhdistetä tietoja nidetiedot-raportille. Syntymävuosi on raportille riittävä tieto, borrowernumber saattaa olla turha mutta pudotamme sen raportilta pois kun selkiytyy ettei sille varmasti ole kohdejärjestelmän päässä tarvetta.

Rajauksissa oli tosiaan vielä tarkennettavaa, nämä parametrit ovat oleelliset:
- rajaus henkilöasiakkaisiin
- rajaus lainauskirjastoon (asetetaan raporttia ajaessa, mahdollisuus rajata kunta-tasolle Turun yksiköihin valinnalla TU%)
- salasanarajaus (estetään näin virkailijoilta raportin ajo käyttöliittymän kautta, sisältää kuitenkin asiakastietoja)

Noilla WHERE-ehdon muutoksilla pitäisi minusta mennä näin, mutta ehkä voit vielä vilkaista että se on varmasti järkevä. :D

```
   SELECT b.borrowernumber,
          CASE WHEN b.firstname LIKE '% %'
          THEN SUBSTRING(b.firstname, 1, POSITION(' ' IN b.firstname)-1)
          ELSE b.firstname 
          END AS firstname,
          year(b.dateofbirth) AS birthyear,
          iss.itemnumber, iss.branchcode
     FROM borrowers b LEFT JOIN issues iss USING(borrowernumber)
    WHERE itemnumber IS NOT NULL
      AND b.categorycode IN ('HENKILO', 'LAPSI', 'MUUHUOL')
      AND iss.branchcode LIKE <<Branchcode>>
      AND md5(<<Salasana>>)='tähänsalasana'
 ORDER BY b.borrowernumber
```

**Comment by ajrajala** [comment]
**Teostiedot:**

Timestamppien osalta todettiin, että järkevintä ja riittävää on valita timestampeistä uusin ja tehdä haku sen perusteella. Varaus-tietoa hyödynnetään mahdollisesti analytiikassa ja päädyttiin siihen, että lasketaan nyt ainakin toistaiseksi varausten lukumäärä. Tuo ihan ensimmäinen teostiedot-raportti näyttäisi siis olevan sitä mitä tarvitaankin eikä siihen ainakaan tässä kohtaa muutostarpeita.

```
  SELECT b.biblionumber, b.title, b.subtitle, b.part_name, b.part_number, b.author, 
   	   bi.isbn, bi.ean, bi.publicationyear, bi.editionstatement, bi.collectiontitle,
         bde.primary_language, bde.itemtype, bde.genres,
  	   COUNT(r.reserve_id) AS 'reserves',
         date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) AS 'timestamp' 
    FROM biblio b
         
         LEFT JOIN biblioitems AS bi
         ON b.biblionumber = bi.biblionumber
         LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements AS bde
         ON b.biblionumber = bde.biblionumber
         LEFT JOIN reserves AS r
         ON b.biblionumber = r.biblionumber

   WHERE date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) BETWEEN <<Start Date|date>> AND <<End Date|date>> 
GROUP BY b.biblionumber
```

**Comment by ajrajala** [comment]
**Nidetiedot**

Nidetietojen osalta pitäisi saada rajattua hakua vielä Turussa kelluviin niteisiin. Tämä on ollut hiukan kinkkinen kun kellutus-tietoa ei saa suoraan nidetiedoista haettua ja lisäksi Turku ei kelluta pelkästään omia niteitään vaan myös Vaski-tasolla kelluu osa aineistosta. Ajattelin, että muuten rajauksen voisi ehkä kuitenkin tehdä tyyliin 'holdingbranch LIKE 'TU%' + rajata sen lisäksi pois aineistolajit ja hyllypaikat jotka ei Turun sisällä kellu, mutta tuli mieleen että vanhentuneet varaukset poistava cron ajetaan yöllä. Cronin seurauksena varaushyllyjen niteet muuttuu periaatteessa 'on_shelf' -tilaan ja virkailijat käsittelee ne vasta aamulla, joten jos kellutusjärjestelmä hakee raportin puolenyön jälkeen, tulee rapsalle mukaan niteitä jotka on näennäisesti hyllyssä mutta saattavat oikeasti olla menossa varausjonon seuraavalle tai palaamassa takaisin toiseen Vaski-kirjastoon.

Tuon cronin aiheuttaman ongelman voisi ratkaista ajoittamalla tietojen haun ennen cancel_expired_holds-cronia, jos ei ole mitään syytä ajoittaa hakua puolen yön jälkeen tapahtuvaksi.

Siinä tapauksessa riittäisi, kun rajauksiin lisäisi seuraavat ehdot:

- i.holdingbranch LIKE 'TU%'
- i.permanent_location ei saa olla VAR eikä VRL
- biblioitems.itemtype (vai haetaanko bde-taulusta?) ei saa olla ALEHTI eikä ESINE

Long story short, kuulostaako tämä jonkun muunkin mielestä loogiselta? :D Alla vielä versio raportista, johon nuo rajaukset haluttaisiin mukaan.

```
  SELECT i.itemnumber, i.biblionumber, i.holdingbranch, i.permanent_location, i.ccode,
         i.sub_location, i.cn_sort, i.itemnotes, i.dateaccessioned, i.issues,
         i.datelastborrowed, i.timestamp,
         CASE WHEN i.onloan IS NOT NULL OR i.itemlost != 0 OR i.notforloan != 0 OR r.found IS NOT NULL
         OR (bt.itemnumber IS NOT NULL AND bt.datearrived IS NULL AND bt.datecancelled IS NULL)
         THEN 'No'
         ELSE 'Yes'
         END AS on_shelf
    FROM items AS i

   		 LEFT JOIN reserves AS r
     	 ON i.itemnumber = r.itemnumber
		 LEFT JOIN branchtransfers AS bt
         ON i.itemnumber = bt.itemnumber
         
   WHERE date(i.timestamp) BETWEEN  <<Start Date|date>> AND <<End Date|date>>
         GROUP BY i.itemnumber
```

**Comment by ajrajala** [comment]
Muokkasin vielä hiukan ylempänä olevaa Teostiedot-raportin kommenttia. Tuli näin jälkikäteen vasta mieleen, että osakohteet eivät ole kohdejärjestelmässä tarpeellisia vaan tarvittaisiin pelkät emotietueet.

**Comment by atarnus** [comment]
**Nidetiedot**

Tässä päivitetty ehdotetut muutokset. Tuon branchcodenkinhan saa parametriksi, jos niin haluaa, tähän käyttöön kuitenkin tuo lienee pysyvä rajaus.

```
SELECT i.itemnumber, i.biblionumber, i.holdingbranch, i.permanent_location, i.ccode,
       i.sub_location, i.cn_sort, i.itemnotes, i.dateaccessioned, i.issues,
       i.datelastborrowed, i.timestamp,
       CASE WHEN i.onloan IS NOT NULL OR i.itemlost != 0 OR i.notforloan != 0 OR r.found IS NOT NULL
       OR (bt.itemnumber IS NOT NULL AND bt.datearrived IS NULL AND bt.datecancelled IS NULL)
       THEN 'No'
       ELSE 'Yes'
       END AS on_shelf
  FROM items AS i
       LEFT JOIN biblioitems AS bi
       ON i.biblionumber = bi.biblionumber
       LEFT JOIN reserves AS r
       ON i.itemnumber = r.itemnumber
       LEFT JOIN branchtransfers AS bt
       ON i.itemnumber = bt.itemnumber
 WHERE date(i.timestamp) BETWEEN <<Start Date|date>> AND <<End Date|date>>
   AND i.holdingbranch LIKE 'TU%'
   AND i.permanent_location NOT IN ('VAR', 'VRL')
   AND bi.itemtype NOT IN ('ALEHTI', 'ESINE')
 GROUP BY i.itemnumber
```

**Comment by atarnus** [comment]
**Teostiedot**

Tähän lisätty määreeksi tuo bde.host_record IS NULL, jonka pitäisi poistaa kaikki osakohteet. Vaihdoin myös itemtypen tulemaan biblioitems-taulusta, jossa ilmeisesti ajantasainen tieto. Ja timestamp oli myös aiemmassa turhaan muutettu päiväykseksi. (Ellei näkyviä timestampeja nimenomaan haluta kaikkia muuttaa päivämääriksi.)

```
SELECT b.biblionumber, b.title, b.subtitle, b.part_name, b.part_number, b.author,
       bi.isbn, bi.ean, bi.publicationyear, bi.editionstatement, bi.collectiontitle, bi.itemtype,
       bde.primary_language, bde.genres,
       COUNT(r.reserve_id) AS 'reserves',
       greatest(b.timestamp, bi.timestamp, bde.last_mod_time) AS 'timestamp' 
  FROM biblio b       
       LEFT JOIN biblioitems AS bi
       ON b.biblionumber = bi.biblionumber
       LEFT JOIN koha_plugin_fi_kohasuomi_okmstats_biblio_data_elements AS bde
       ON b.biblionumber = bde.biblionumber
       LEFT JOIN reserves AS r
       ON b.biblionumber = r.biblionumber
 WHERE date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) BETWEEN <<Start Date|date>> AND <<End Date|date>>
   AND bde.host_record IS NULL
 GROUP BY b.biblionumber
```

**Comment by ajrajala** [comment]
Suljen tämän tiketin nyt ainakin tällä erää, sillä viilatut raportit on viety vaski-testille eikä tällä hetkellä ole tiedossa muutostapeita.

**Comment by ajrajala** [comment]
Kolmas kerta toden sanoo eli joudun vielä kertaalleen pyytämään muokkausta kelluttimen raporteille, sillä hoksattiin että tieto poistetuista niteistä ja teoksista täytyisi vielä saada mukaan sekä nidetiedot-raportille että teostiedot-raportille. Weasel näki heidän kannalta parhaimpana vaihtoehtona sen, että molemmille raporteille lisättäisiin uusi sarake 'status' johon tulisi arvo deleted, jos nide/teos on poistettu ja arvo active jos nide/teos ei ole poistettu.

Viimeisimmät raporttiversiot löytyvät tuotannosta raportti-id:illä 2279 (nidetiedot) ja 2280 (teostiedot).

Sen verran jo nidetiedot-raporttia testailin itse muokata, että union-lauseella saisi deleteditems-taulun otettua mukaan toivotulla tavalla. Räpellykseni löytyy [tältä testiraportilta](https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2282&phase=Edit%20SQL). Raportti nähdäkseni toimii mutta se on ehkä hyvä jonkun viisamman katsoa silti läpi. Teostiedot-raporttia en yrittänyt lähteä omin päin muokkaamaan.

**Comment by CodoDerDritte** [comment]
Tässä on nyt muutama mutka matkassa. Meillä on tällä hetkellä melko vajaa miehitys, eikä Kassu, joka siis teki nuo raportit ole enää meillä remmissä. Käytännössä jonkun meistä pitäisi siis ensin perehtyä siihen, miten ne raportit on tehty ja sen jälkeen vielä tehdä tarvittavat muutokset.

**Comment by ajrajala** [comment]
Äh, enpä tajunnut ettei Kassu enää ollut remmissä. Mutta siis suurkiitos, jos Johanna voi katsoa näitä ja pahoittelut että tuli tällaisena pikapyyntönä. Jotenkin oli niin tiukasti keskitytty muuttuneiden tietojen hakemiseen, että poistot oli jäänyt kokonaan huomiotta.

**Comment by johannaraisa** [comment]
Korjasin siitä @ajrajala raportilta group by arvot ja tässä on teoksille testiraportti, https://vaski.koha-suomi.fi/cgi-bin/koha/reports/guided_reports.pl?reports=2304&phase=Show%20SQL

Sen teoksen poistoarvon saa biblio_data_elements-taulusta.

**Comment by ajrajala** [comment]
Kiitos näistä! Varmistan vielä teostiedot-raporttiin liittyen, että päivittyykö bde.last_mod_time silloin kun teos poistetaan?

**Comment by johannaraisa** [comment]
> Kiitos näistä! Varmistan vielä teostiedot-raporttiin liittyen, että päivittyykö bde.last_mod_time silloin kun teos poistetaan?

@emta001 Osaatko vastata tuohon? Siellä oli ainakin deleted_on-aikaleima kenttä sille poistolle, mutta muuttuuko tuo last_mod_timekin?

**Comment by emta001** [comment]
Tuo last_mod_time-sarake päivittyy vaan sillon, kun bde-taulun riviä päivitetään. Eli lähinnä vain silloin kun tehdään öisin päivitysajo.

**Comment by ajrajala** [comment]
Mietin tuota `WHERE date(greatest(b.timestamp, bi.timestamp, bde.last_mod_time)) BETWEEN <<Start Date|date>> AND <<End Date|date>>` ehtoa, saadaanko poistettuja tietueita kiinni tuon mukaisella aikarajauksella vai pitääkö tuonne ottaa vielä bde.deleted_on mukaan?

**Comment by johannaraisa** [comment]
Joutuu tuota kyllä muokkaaman enemmän, ku nyt vasta katselin että eihän siellä ole sitä poistotaulua ollenkaan.

**Comment by ajrajala** [comment]
Aivan, hyvä kun huomasit.

Kuittaan vielä, että nidetiedot-raportti on siis ok, siihen ei tarvitse enempää muutoksia. 👍

**Comment by johannaraisa** [comment]
No nyt on, siihenkin piti lisätä se union all ja ne poistotaulut. Laitoin tuohon testiin nämä.
