### ISSUE TITLE
Lumme: Vanhojen lehtitilausten sulku

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#929]
### Tukipyyntö

Lumpeissa on jäänyt roikkumaan eri vuosilta lehtitilauksia, joita ei ole suljettu. Olisiko mahdollista saada suljettua kaikki sellaiset tilaukset, joissa on päättymispäivä 1.1.2023? Eli avonaiseksi jäisi vain tämän vuoden lehtitilaukset. Ajo koskisi kaikkia Lumme-kirjastoja.

**Comment by lmstrand** [comment]
Ajettu:
```
MariaDB [lummeprod]> UPDATE subscription SET closed='1' WHERE enddate < '2023-01-01';
Query OK, 217 rows affected (0.046 sec)
Rows matched: 8042  Changed: 217  Warnings: 0
```
eli 217 tilausta meni kiinni joissa tuo 1.1.2023 tai aiempi pvm päättymispäivänä.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon! 👍
