### ISSUE TITLE
Helle: vuoden 2022 lehtitilausten sulkeminen

### ISSUE THREAD

**Issue by Kati-Helle** [KohaSuomi/Koha#930]
### Tukipyyntö

Suljetteko Hellen vuoden 2022 lehtitilaukset.

**Comment by emta001** [comment]
Tilaukset suljettu seuraavasti:

`update subscription set closed='1' where startdate > '2021-12-31' and enddate < '2023-01-01';`

Sulku koski 1052 tilausta.

**Comment by Kati-Helle** [comment]
Kiitti Emmi!
