### ISSUE TITLE
Kiinteämittaisten kenttien korjaus: 008-MU/24-29

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#931]
### Tukipyyntö

Vaarassa on paljon kuvailuvirhettä (008-MU/24-29 illegal value "|||| |", should be [" ","a","b","c","d","e","f","g","h","i","k","r","s","z","||||||"])
Näiden korjaus yksitellen on työlästä, mutta ajolla ne voisi korjata laittamalla |||||| eli kaikki merkkipaikat putkimerkillä.

Vastaavasti (008-MU/24-29 illegal value "|||| 0", should be [" ","a","b","c","d","e","f","g","h","i","k","r","s","z","||||||"] voisi korjata laittamalla |||||| eli kaikki merkkipaikat putkimerkillä.

Marc21-formaatin mukaan: "24-29 - Liiteaineisto (= 006/07-12)
Aakkosjärjestyksessä voidaan tallentaa kuusi eri koodia, jotka ilmaisevat äänitteen, nuottikäsikirjoituksen tai nuottijulkaisun liiteaineiston sisältöä. Jos tallennetaan vähemmän kuin kuusi koodia, koodit tasataan vasemmalle ja käyttämättömissä merkkipaikoissa on tyhjä (#)."

Jos siis merkkipaikka alkaa |-merkillä, loppujenkin on oltava |-merkkejä. Nämä saisi kaikki korjata oikeaan muotoon.

**Comment by AnttHeik** [comment]
Tämän saman korjauksen voisi tehdä myös kaikissa muissakin paikalliskannoissa ja TäTissä.

**Comment by paxed** [comment]
Hämärästi muistelen että nämä olisi johtuneet (ainakin aikoinaan Vaarassa) lähinnä konversiossa tapahtuneesta virheestä, jossa kaksi tai useampia välilyöntejä olisi kutistettu yhteen välilyöntiin. Olisikohan ollut että /11-14, eli julkaisuvuosi 1 olisi ollut tyhjää, jolloin kaikki myöhemmät merkkipaikat olisi olleet viallisia. Pitää tutkia jos nämä johtuvat tälläsestä ongelmasta, jolloin korjaus olisikin esim. kolmen välilyönnin lisääminen julkaisuvuosi 1:een ...

**Comment by paxed** [comment]
Tämä korjaus ajeltu kaikkiin kimppoihin ja tätiin.

**Comment by pknuuti** [comment]
Kiitos Pasi. Suljen tiketin.
