### ISSUE TITLE
Lumme: vanhojen lehtitietueiden poisto

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#932]
### Tukipyyntö

Lehtisiivouksien yhteydessä on tullut vastaan monia tyhjiä lehtitietueita, joissa on ollut lehtitilaukset vielä auki. Nyt kun nämä vanhat lehtitilaukset on suljettu, niin olisikohan mahdollista ajaa eräpoistolla nämä lehtietueet, joissa ei ole niteitä?

**Comment by AnneliO** [comment]
Pystytte tekemään sen MARC-tietueiden eräpoisto -työkalulla Kuvailu-osiossa. :)

Tässä suomenkielinen ohje: https://koha-suomi.fi/dokumentaatio/kuvailu/#534-tietueiden-poisto-er%C3%A4ajona

Tässä englanninkielisen manuaalin ohje: https://koha-community.org/manual/22.11/en/html/cataloging.html#batch-deleting-records

Poiston voi tehdä myös raportin avulla. Kerro, jos tarvitsette raportin, jolla voi hakea tietyt ehdot täyttävät tietueet. :)

**Comment by Hanna-Lumme** [comment]
Joo, raportti olisi kyllä hyvä! Saisi suoraan listan noista lehtitietueista, mitkä ovat tyhjiä. 😄

**Comment by AnneliO** [comment]
OUTIsta löytyi tällainen Niteettömät nimekkeet -raportti, jolla voi rajata tulokset tietueen aineistotyypin mukaan:

```
SELECT b.title AS 'Teos', bi.itemtype AS 'Aineistotyyppi', b.biblionumber
from biblio b
LEFT JOIN items i ON b.biblionumber = i.biblionumber
LEFT JOIN biblioitems bi ON bi.biblionumber = b.biblionumber
LEFT JOIN biblio_metadata bm ON bm.biblionumber = b.biblionumber
WHERE ExtractValue(bm.metadata,'//datafield[@tag="773"]/subfield[@code="w"]') = ''
AND i.itemnumber IS NULL
AND bi.itemtype=<<Valitse aineistotyyppi|MTYPE>>
```

**Comment by Hanna-Lumme** [comment]
Kiitos paljon avusta, eiköhän se tällä selviä! 👍
