### ISSUE TITLE
Lumme: nide lainassa ja saatavana

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#944]
### Mikä vikana?

Lumpeissa olisi taas yksi nide saatavana ja lainassa samaan aikaan: biblionumber 3040527. Muutoslokissa näkyy lainausautomaatin ja virkailijan Muokkaa-toiminto 9 sekunnin erolla toisistaan tällä samalla niteellä.

![image001](https://github.com/KohaSuomi/Koha/assets/129748294/f13e4435-2c34-42e9-b008-ba5e182fe502)

**Comment by emta001** [comment]
Tutkittiin tätä Annelin kanssa ja tultiin samaan tulokseen kuin Kyytin vastaavassa tiketissä (#210). Tässä on siis luultavasti ollut tilanne, että nide on ollut virkailijan käsittelyssä samaan aikaan kuin se on lainattu ja tämä on jotenkin vaikuttanut onloan-arvon muodostumiseen. Epäiltiin, että luultavasti myös Lumpeen aiemmassa tapauksessa (#789) ja OUTIssa (#774) on käynyt samoin. Mutta se mistä tää tarkemmin johtuis tai onko tämä nyt oikeasti se syy, on vähän hankala selvittää. Ensinnäkin Kohan action_logsit on reikäsiä. Kaikki lainaustapahtumat ei ole välttämättä lokittuneet ja ainakaan OUTIn tapauksessa niteellä ei ole mitään muokkaustietoja. Automaatti ongelma tää tuskin on, koska lainauksia on tehty sekä automaatilla, että tiskillä. Näin ainakin siitä päätellen, että yhdellä tapauksella ei ole edes SIP-lokilla kirjausta.

Mutta edetään tämän kanssa nyt niin, että käyn nakkaamassa tuolle niteelle onloan-arvon paikalleen. Jatketaan muuta selvittelyä vielä hetki, jospa jotain löytys.

**Comment by emta001** [comment]
Eipä tästä ole selvinnyt mitään kummempaa. Suljen tiketin, avataan uudestaan jos tarvis.
