### ISSUE TITLE
Nalkutin käyttöön jo tietojen tuontivaiheessa TäTiin

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#945]
### Kehitysehdotukseni

Koska yllättävän paljon formaatin vastaisia merkkivirheitä löytyy uusista BTJ:n tietueista TäTissä, olisi hyvä, jos nalkutin toimisi jo tietueiden tuontivaiheessa. Näin saataisiin BTJ:lle (Kirjastopalvelu) heti tieto heidän virheistään ja voisivat korjata virheet heti tuoreeltaan. Paikalliskantoihin valuisi vähemmän virheellisiä tietueita ja kuvailijan työ helpottuisi sen myötä.

**Comment by paxed** [comment]
EditX-plugarissa on valmiina Validator.pm, johon Nalkuttimen sais ehkä suoraan tunkattua.

- Pitäis void laittaa EditX:n konffeihin mistä luettelointivirheistä valitettais suoraan aineistotoimittajalle, mistä ilmotettas pääkäyttäjälle tms.

**Comment by johannaraisa** [comment]
Täydennystietueet tuodaan Tätiin [Import remote records ](https://github.com/KohaSuomi/koha-plugin-import-remote-biblios)-liitännäisellä, siihen voi lisätä tuon Nalkuttimen.

**Comment by AnneliO** [comment]
Indeksointi- ja tiedonhakuryhmä 22.5.2024:

Uusissa tietueissa ei ole enää juurikaan formaatin vastaisia tietueita, vanhemmissa tietueissa niitä on ollut enemmän. Todettiin, että ongelma ei ole enää akuutti, eikä teknistä ratkaisua tarvita. EDItX:n kautta tulevat tietueet ovat ennakkotietueita, jotka korvautuvat myöhemmin täysluetteloiduilla, jolloin tarvetta nalkuttamiselle ei ole vielä tietueen luontivaiheessa.

Ei siis ole tarvetta tehdä mitään teknisiä ratkaisuja tällä hetkellä.
