### ISSUE TITLE
Lumme: signumien korjaus

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#946]
### Tukipyyntö

Lumpeissa tarvittaisiin apua varastokirjojen ja jo lakkautettujen kirjastojen signumien korjaamiseen.

1) Mikkelistä on lakkautettu muutamia kirjastoja ja niiden aineisto siirrettiin Mikkelin pääkirjastolle. Kirjojen kotikirjastot, yms. on korjattu vastaamaan Mikkelin pääkirjastoa, mutta niteiden signumit ovat edelleen vanhojen kirjastojen. 

Nämä signumit voisi korjata seuraavasti:
* RAA, KAA, SA -> uusi signum PKA
* RAL, KAL, SL -> uusi signum PKL
* RAN, KAN, SN -> uusi signum PKN
* RAM -> PKM

2) Mikkelin varastokirjojen signumeiden merkitsemisessä on ollut aikojen saatossa vaihtelua, mikä aiheuttaa nyt ongelmia palautusautomaateilla.

Nämä signumit voisi korjata seuraavasti:
* PKAVA, PKMV, PKMVA, PKVM -> uusi signum PKVA
* PKVO -> uusi signum PKKO
* PKVALN, PKLVA, PKVLN, PKLN VA, PK VALN, PK VL -> uusi signum PKVL

Jos mahdollista, niin voisi tarkistaa, että hyllypaikka täsmää signumin kanssa. Esiin tuli joitakin tapauksia, joissa signumissa on PKA, mutta hyllypaikka Varasto.

**Comment by johannaraisa** [comment]
Sama tuon lasten ja nuorten varaston kanssa, sen arvo on auktorisoiduissa arvoissa VALN ja niille tulee PKVALN.

**Comment by Hanna-Lumme** [comment]
Nämä sopii meille. 😄

**Comment by johannaraisa** [comment]
Taisin sekoittaa tuon kotiseudun, sehän olikin PKVO->PKKO. Sen voi vielä ajella. Tuota VL-arvoa ei ollut, eli noista lasten ja nuorten varastoaineistosta tulee tuo PKVALN. Jatkan tämän loppuun tänään.

**Comment by johannaraisa** [comment]
Nyt nämä on muutettu tietokannasta, en tosin tiedä miltä näyttävät haussa, voi vielä vaatia indeksin päivityksen.

**Comment by johannaraisa** [comment]
Nyt hakuindeksikin on päivitetty noiden osalta.

**Comment by Hanna-Lumme** [comment]
Kiitos paljon avusta! 😄
