### ISSUE TITLE
Tarratulostus-liitännäinen: Toiminnot "Valitse kaikki" + "Lisää valitut niteet tulostusjonoon" vievät niteet tulostusjonoon eri järjestyksessä

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#953]
### Kehitysehdotukseni

Kun käyttää toimintoa Valitse kaikki ja sen jälkeen toimintoa Lisää valitut niteet tulostusjonoon, niin jostain syystä lisätyt niteet järjestyvät tulostusjonoon miten sattuu.

Järjestykseen ei auta se, että ennen toimintoa "Valitse kaikki" napsauttaa niteet nidenumeron mukaiseen järjestykseen. Napsautuksesta huolimatta niteet asettuvat tulostusjonoon miten sattuu.

Jos vie niteet tulostusjonoon käsin, yksi kerrallaan (esim. samalla, kun tallentaa nidenumeron), niin tarrat menevät jonoon ja pysyvät siinä halutussa järjestyksessä.

### Jotain muuta?

Valitaan nämä niteet, niiden ollessa tässä järjestyksessä ja käytetään Lisää valitut niteet tulostusjonoon -toimintoa.
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/0a3c9ebf-07d0-4411-8668-0dccc66fe911)

Niteet ovat tulostusjonossa eri järjestyksessä:
![kuva](https://github.com/KohaSuomi/Koha/assets/98805552/409637be-dfa9-4b68-9f74-78fb8cbe7417)

(Virkalija testasi, että menevätkö niteet samaan järjestykseen, jos toistaa yllä tehdyt toimenpiteet. Niteet menivät taas eri järjestykseen.)

**Comment by lmstrand** [comment]
Ratkaisuksi intranetUserJS-rimpsuun voi lisätä AJAX-kutsuille async: false -ominaisuuden, jolla jokaisen niteen lisäys odotetaan loppuun ennen seuraavan käsittelyä. Tuolla en saanut toistettua niteiden järjestyksen muuttumista tarratulostus-pluginissa enää.

Ratkaisussa on sellainen ongelma, että jos kutsu epäonnistuu esim. verkkovian takia, selain saattaa jumahtaa. En ole ihan varma, mutta sitten voi yrittää lisäämistä uudelleen.

Tuollainen nyt ainakin tuntuisi pikaratkaisuna toimivan.

Tein muutoksen OUTI-testille.

**Comment by piiaseme** [comment]
Onko rimpsu testattavissa vielä 12.12. jälkeen? Jos ei ole, niin testataan maanantaina.

**Comment by piiaseme** [comment]
Testien perusteella niteiden järjestys pysyi samana koko tulostus-prosessin ajan.

**Comment by ajrajala** [comment]
Myös vaski-testillä järjestys näyttää säilyvän oikein, testasin niteiden lisäämistä tulostusjonoon sekä Perustiedot-näytöltä että niteen muokkauksesta.

**Comment by lmstrand** [comment]
Muutos lisätty tuotantojen js-skripteihin. Suljen tiketin.
