### ISSUE TITLE
OUTI: SIP2-tunnuksien lisäyksiä

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#955]
### Tukipyyntö

Support-postiin on laitettu pyyntö Pateniemen kirjaston omatoimiovikoneen ja lainaus-palautusautomaatin SIP-tunnusten lisäämisestä OUTIn automaattipalvelinten konfiguraatioon, palvelinryhmään outi-pohjoinen.

Asennukset ovat viikolla 51, joten toivomme että uudet tunnukset ovat valmiina käytettäväksi 15.12.2023 mennessä.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle.

**Comment by velimarj** [comment]
Kiitokset, suljenpa siis tiketin.
