### ISSUE TITLE
OUTI: Other name -kentän piilotus valituille asiakastyypeille

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#956]
### Tukipyyntö

OUTIssa otetaan käyttöön Muu nimi -kenttä (Other name -kenttä) asiakkaan kutsumanimelle maanantaina 11.12.2023.

Kenttä halutaan kuitenkin piilottaa asiakastyypeiltä YHTEISO ja KAUKOLAINA. 

Voisiko päivystäjä lisätä Kassun tekemän rimpsun IntranetUserJS:ään tulevana maanantaiaamuna. Rimpsua on testattu OUTIn tesillä ja todettu toimivaksi.

///ALKU///

// Piilottaa 'Other names' kentän valituille asiakastyypeille (categorycode) muokkauslomakkeilla (add, modify, duplicate)
$(document).ready(function () {
  if ( window.location.pathname == '/cgi-bin/koha/members/memberentry.pl' ) {
    var categories = ["YHTEISO", "KAUKOLAINA"];
    if ( ( window.location.search.includes('?op=add') && categories.some(cat => window.location.search.includes(cat)) ) || ( ( window.location.search.includes('?op=modify') || window.location.search.includes('?op=duplicate') ) && categories.some(cat => $('.patroncategory')[0].innerHTML.includes(cat)) ) ) {
      $('#othernames').attr('disabled', 'disabled');
      // Piilottaa li-elementin, jonka sisällä on label ja input
      $('#othernames').parent().hide();
    }
  }
});
///LOPPU///

**Comment by johannaraisa** [comment]
Ei nyt ihan ehdi maanantaiaamuun, mutta lisään huomenna aamulla.

**Comment by johannaraisa** [comment]
Nyt on lisätty

**Comment by AnneliO** [comment]
Rimpsu lisätty [IntranetUserJS-kirjastoon](https://koha-suomi.fi/dokumentaatio/intranetuserjs/#othername-kent%C3%A4n-piilotus-m%C3%A4%C3%A4ritetyilt%C3%A4-asiakastyypeilt%C3%A4).

**Comment by pirliis** [comment]
Kiitos!
