### ISSUE TITLE
Varauksen keskeytykselle ei tallennu määräpäivää jos pvm on kentässä jo valmiina

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#957]
### Mikä vikana?

Jos asiakkaan tietojen kautta keskeyttää yksitellen useamman varauksen, "Keskeytä varaus" -ponnahdusikkunassa on jo valmiiksi valittuna päivämäärä jota ensimmäistä keskeytystä tehdessä käytti. Jos käyttäjä ei tee muutosta päivämäärään, tallentuu varauksen keskeytys kuitenkin ilman keskeytyksen päättymispäivää.

Jos pvm-kenttään valitsee kalenterista päivämäärän uudelleen, tallentuu keskeytys oikein päivämäärän kanssa.

### Kuinka toistaa ongelma/asia

1. Tee asiakkaalle kaksi varausta
2. Mene asiakkaan tietoihin Varaukset-välilehdelle
3. Keskeytä ensin toinen varauksista ja aseta keskeytykselle jokin päättymispäivä
4. Keskeytä sitten toinenkin varaus, huomaa että ponnahdusikkunassa on valittuna jo valmiiksi päivämäärä jota äsken käytit
5. Älä tee muutoksia päivämääräkenttään vaan tallenna keskeytys
6. Huomaa, että keskeytys tallentui ilman päivämäärää

**Comment by AnneliO** [comment]
Sama tapahtuu myös PTFS Europen sandboxissa, versio 23.12.

**Comment by AnneliO** [comment]
@ajrajala Tekisitkö tästä yhteisöön tiketin, niin tarjotaan korjausta myös sinne.

**Comment by atarnus** [comment]
Tässä oli kyse jälleen siitä, että mukana on piilotettu kenttä, joka kantaa mukanaan päivämäärä-arvoa. Jos valitun päivämäärän poistaa punaisesta ruksista, niin se tyhjää sekä tuon pvm-valikon että piilotetun arvon, mutta jos painaa tuosta 'Clear date to suspend indefinitely' -tekstistä tai Suspend-napista, niin se kutsuu eri funktiota, joka tyhjentää vain piilotetun arvon, eikä tuota valittavaa kenttää. (Jos painaa cancelia tai ikkunan yläkulman ruksia, niin arvo jää talteen vielä molempiin inputeihin, ja tuo "esitäytetty" päiväys tallentuu myös varsinaiseen keskeytykseen, eli tämä toimii ihan oikein.)

![image](https://github.com/KohaSuomi/Koha/assets/63994411/0d6e405c-b8f2-4b9c-a5de-fede7b8b62fb)

Nykyisellään 'Clear suspend...'-teksti ja Suspend-nappi tyhjentävät arvon id:ltä suspend-modal-until. Jos muuttaa nämä kohdat tyhjentämään arvon classilta suspend-until, molemmat inputit tyhjenee, ja homman pitäisi toimia oikein. 

```
<input name="suspend_until" id="suspend-modal-until" class="suspend-until flatpickr flatpickr-input" data-flatpickr-futuredate="true" size="10" type="hidden" value="2024-01-18">
<span class="flatpickr_wrapper">
  <input class="suspend-until flatpickr flatpickr-input" placeholder="" tabindex="0" type="text" autocomplete="off">
```

**Comment by atarnus** [comment]
```
$("#suspend-modal-clear-date").on( "click", function() { $("#suspend-modal-until").val(""); } );

$("#suspend-modal-submit").on( "click", function( e ) {
  e.preventDefault();
  var suspend_until_date = $("#suspend-modal-until").val();
  if ( suspend_until_date !== null ) suspend_until_date = $date(suspend_until_date, {dateformat:"r>
  suspend_hold(
      $(this).data('hold-id'),
      suspend_until_date
  ).success(function () {
      holdsTable.api().ajax.reload();
  }).error(function (jqXHR, textStatus, errorThrown) {
      if (jqXHR.status === 404) {
          alert(__("Unable to suspend, hold not found"));
      }
      else {
          alert(__("Your request could not be processed. Check the logs"));
      }
      holdsTable.api().ajax.reload();
  }).done(function() {
      $("#suspend-modal-until").val(""); // clean the input
      $('#suspend-modal').modal('hide');
  });
});
```
--->
```
$("#suspend-modal-clear-date").on( "click", function() { $(".suspend-until").val(""); } );
```

```
 }).done(function() {
            $(".suspend-until").val(""); 
```

**Comment by ajrajala** [comment]
> @ajrajala Tekisitkö tästä yhteisöön tiketin, niin tarjotaan korjausta myös sinne.

Tästä löytyikin jo näköjään tiketti yhteisöstä, korjausta siihen ei ole vielä tarjottu: https://bugs.koha-community.org/bugzilla3/show_bug.cgi?id=34263

**Comment by atarnus** [comment]
Githubissa. Tuotava testeille.

**Comment by atarnus** [comment]
Tämä nyt Githubissa myös 23-versiossa. Tuotava nexteille.

**Comment by Kati-Helle** [comment]
Testasin Helle-nextissä.
Keskeytin asiakkaan tietojen Varaukset-välilehdellä asiakkaan voimassa olevista varauksista yhden määrittäen keskeytyksen aktivoitumispäivän.
Toisen saman asiakkaan voimassa olevan varauksen Keskeytä varaus -painiketta klikatessa ponnahdusikkunassa ei ole valmiiksi valittuna aktivoitumispäivämäärää, eli päivämääräkenttä on tyhjä. Kun jätän päivämääräkentän tyhjäksi, ei keskeytetylle varaukselle muodostu päivämäärällistä varaus aktivoituu -tietoa.

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/7f3059d8-d630-4882-ba03-404072b5b096)

**Comment by pknuuti** [comment]
Testattu Vaaran nextillä toimivan samoin kuin Hellen nextillä. Eli toimii kuten pitääkin.

**Comment by MikkoLiimatainen** [comment]
Toimii Vaski-nextilläkin kuten pitää

**Comment by ajrajala** [comment]
Tämä tuotannossa ok, suljen tiketin.

**Comment by atarnus** [comment]
Korjattu yhteisöversiossa 24.05
