### ISSUE TITLE
OUTI: Pyhäjoen kirjaston uudet SIP2-tunnukset

### ISSUE THREAD

**Issue by pirliis** [KohaSuomi/Koha#959]
### Tukipyyntö

Support-postiin on laitettu pyyntö Pyhäjoen kirjaston omatoimiovikoneen ja lainaus/palautusautomaatin SIP2-tunnusten lisäämisestä OUTIn automaattipalvelinten konfiguraatioon, palvelinryhmään outi-outi.

**Comment by emta001** [comment]
Onko näille jotain takarajaa tai muuta päivää, jolloin nää vois lisätä vai voiko tän tehdä vaikka samantien?

**Comment by pirliis** [comment]
Laitteiden tarkkaa asennusajankohtaa kirjastosta eivät tienneet. Ilmoittivat vain, että asennus ja käyttöönotto menee varmasti pitkälle kevääseen. Onko haittaa, vaikka tunnukset lisää jo palvelimelle? Olisivat jo valmiina, kun tekevät asennukset.

**Comment by emta001** [comment]
> Laitteiden tarkkaa asennusajankohtaa kirjastosta eivät tienneet. Ilmoittivat vain, että asennus ja käyttöönotto menee varmasti pitkälle kevääseen. Onko haittaa, vaikka tunnukset lisää jo palvelimelle? Olisivat jo valmiina, kun tekevät asennukset.

Ei siitä mitään haittaa ole, voin käydä laittaa ne samantien paikalleen.

**Comment by emta001** [comment]
Tunnukset lisätty palvelimelle.

**Comment by pirliis** [comment]
Kiitos!
