### ISSUE TITLE
Kirkes: vahingossa poistettujen niteiden palauttaminen

### ISSUE THREAD

**Issue by ElinaUotila** [KohaSuomi/Koha#960]
### Tukipyyntö

Virkailija on tehnyt 5.12.2023 klo 7.58 niteiden poiston eräajona (https://kirkes.koha-suomi.fi/cgi-bin/koha/admin/background_jobs.pl?op=view&id=1259034). Ajossa on poistunut tuhatkunta nidettä, joita ei oikeasti ole ollut tarkoitus poistaa. Saako niteet palautettua?

**Comment by emta001** [comment]
Halutaanko näistä niteistä palauttaa kaikki vai vain osa?

**Comment by ElinaUotila** [comment]
Tarkistan vielä poiston tekijältä, palautetaanko kaikki.

**Comment by emta001** [comment]
> Tarkistan vielä poiston tekijältä, palautetaanko kaikki.

Oikeastaan, parempi että palautetaan kaikki ja voitte sitten myöhemmin katsoa, että mitä tuolta oikeasti halutaan poistaa. Noiden rajaaminen tuolta background_jobs-taulusta ei kyllä onnistu mitenkään helposti (ei varmaan ollenkaan).

**Comment by ElinaUotila** [comment]
Jees, palautetaan sitten kaikki. Selkeämpää niin.

**Comment by emta001** [comment]
Kaikki niteet on nyt palautettu seuraavasti:

`INSERT IGNORE INTO items SELECT * FROM deleteditems WHERE itemnumber IN(tähän pitkä rimpsu itemnumbereita);`

Palautetut niteet on poistettu deleteditems-taulusta. Lisäksi niiltä on poistettu arvo deleted_on-sarakkeesta.

**Comment by ElinaUotila** [comment]
Kiitos, kaikki vaikuttaa palautuneen.
