### ISSUE TITLE
Lumme: asiakkaan myöhästymismaksut eivät johda lainauskieltoon

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#965]
### Mikä vikana?

Lumpeissa tuli esiin, että asiakkaat, joiden mm. myöhästymismaksusaldo ylittää lainauskieltorajan, eivät mene lainauskieltoon. Yksi tällainen tapaus on asiakas ID38319. Kohan asetuksissa noissuecharge- ja maxoutstanding -asetukset on määritelty 9.99€.

**Comment by AnneliO** [comment]
Kun järjestelmäasetuksessa AllowFineOverride on valittuna _Salli_, ilmoitus maksuista tulee vasta lainatessa:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/43874b5b-5607-4e1b-a22d-9618f7fbf906)

Jos asetuksessa on _Älä salli_, tulee asiakkaan lainauksessa heti ilmoitus, että lainaus ei ole sallittua:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/6e9f4715-b1ba-4a71-aea4-b469342075fe)

Jos asetus on _Älä salli_, tulee asiakkaan maksaa maksut alle lainakieltorajan ennen kuin hänelle voidaan lainata.

**Comment by Hanna-Lumme** [comment]
Kiitos! Tämä asetus on nyt korjattu. 😄
