### ISSUE TITLE
Asiakkaan varaukset-välilehdelle näkyviin aineistotyyppi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#966]
### Kehitysehdotukseni

Siirretty [Redminestä tiketti #442](https://tiketti.koha-suomi.fi/issues/442). Asiantuntijaryhmä käsitellyt 11.12.2023 päätöksellä _Toteutetaan itse Record-level-itemtype-sarake ja tarjotaan yhteisöön muutos. Lainat-välilehdellä on jo kyseinen sarake yhteisöversiossa._

## Kuvaus

Asiakkaan tiedoissa Varaukset-välilehdelle halutaan näkyviin varatun aineiston aineistotyyppi samaan tapaan kuin Lainat-välilehdellä jo on.

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/e4658f37-637b-4337-aeca-dcc90c5b1bfe)

Huomioitava, että meillä kentässä näkyy MTYPE-auktorisoitu arvo, eikä Kohan oletuksen mukaisesti itemtype eli nidetyyppi. Lainaus-sivulle on muutettu näkymään MTYPE kyseiseen sarakkeeseen.

**Comment by atarnus** [comment]
Tämä ei olekaan ihan hirveän simppeli juttu.

Varaustaulun otsikkokenttä luodaan moremember.tt -tiedostossa.
Varaustaulun rivit luodaan holds.js.
Objekti, joka lähetetään holds.js:lle ei sisällä tarvittavaa tietoa tällä hetkellä. Objekti rakennettaan tiedostossa svc/holds
Tuokaan tiedosto ei sisällä varsinaista sql-kyselyä, joten mahdollisesti etsitään tässä sitten vielä neljättä tiedostoa, ja pähkäillään vähän että miten se oikea kenttä saadaan sieltä käsittelyyn.

**Comment by atarnus** [comment]
Tutkittiin koko holds-taulun rakentamisen prosessi, ja missään vaiheessa mukana ei ole biblioitems.itemtype-tietoa, eli se pitäisi poimia sinne ihan erikseen. Keskustellaan vielä, mitä olisi järkevää tehdä.

**Comment by janPasi** [comment]
Keskustelimme asiasta 15.1.2024 (kehittäjät+toimitusjohtaja/tuotepäällikkö). Muutos olisi suhteellisen isotöinen, tilapäinen ja Koha-Suomi spesifi, joten siihen ei ole järkevää ryhtyä. Yhteisöversiossa toiminnallisuus tullaan luultavasti tulevaisuudessa muuttamaan kooditasolla Lainat-välilehteä vastaavaksi, jolloin tämä korjaantunee itsekseen (tai vähintäänkin korjaamisesta tulee paljon helpompaa). Hylkään tiketin.
