### ISSUE TITLE
Niteiden erämuokkauksen "Poista lainassa-tila" -linkki ei tee mitään

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#972]
### Mikä vikana?

Yritin poistaa niteiden erämuokkauksessa massana lainassa-tilan testiniteiltä, jotta saisin niteet poistettua. Vaikuttaa kuitenkin siltä, ettei erämuokkauksessa oleva linkki tekisi yhtään mitään eikä tallennuksen jälkeenkään niteet näytä poistuneen lainasta. Sama tapahtuu myös testikannan puolella.

### Kuinka toistaa ongelma/asia

1. Vie Vaskin tuotannossa niteiden erämuokkaukseen viivakoodit LVask20231200629, LVask20231200630, LVask20231200631, LVask20231200632
2. Siirry eteenpäin erämuokkauksessa ja klikkaa nidelistan yltä löytyvää Poista lainassa-tila (Clear on loan) -linkkiä
3. Huomaa, että mitään ei näytä varsinaisesti tapahtuvan
4. Tallenna vielä niteiden erämuokkaus. Huomaa, että vaikka työ valmistuu, ei niteiltä ole poistunut lainassa-tila.

**Comment by AnneliO** [comment]
Tuossa näyttäisi olevan huono käännös, koska manuaalin mukaan toiminto tekee vain tätä:

To uncheck all items that are currently checked out you can click the ‘Clear on loan’ link at the top of the form.

Eli sen pitäisi ottaa valinta pois niistä niteistä, jotka ovat lainassa. Mutta ei se kyllä näytä tekevän sitäkään.

Tuollainen toiminto, jota yrität nyt tehdä, tulee mahdolliseksi niteiden erämuokkauksessa versiossa 23.11:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/64a59b62-dd58-4903-bf2d-50c43808d95f)

**Comment by ajrajala** [comment]
Ah aivan, uskoin liikaa linkin tekstiä. :D Mutta totta, tuo ei siis joka tapauksessakaan tee sitä mitä pitäisi joten jätetäänpä tiketti auki.

**Comment by emta001** [comment]
Johtuu siis siitä, että sivun HTML:ssä lähetetään data-attribuuttina Koha::Hash, ei 1 kuten pitäisi. Alla kuvakaappaus selaimen konsolista:

![image](https://github.com/KohaSuomi/Koha/assets/37581745/f3007717-203d-47dd-b6fb-8e1fb1e86876)

Yhteisön masterissa tuo menee oikein. Samoin meidän nexteillä. Eli tämän kanssa voinee odotella versionvaihtoon asti, sehän on tulossa kohtapuoliin.

**Comment by MikkoLiimatainen** [comment]
Nextillä Poista valinta lainassa olevilta -linkki poistaa valinnan niteiltä, jotka ovat lainassa. Vaikuttaisi siis toimivan oikein.

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii Poista valinta lainassa olevilta -linkki. Linkin klikkaus poistaa valinnan vain niiltä niteiltä, joilla on Niteiden erämuokkauksen Lainassa-kentässä eräpäivä-arvo.

**Comment by emta001** [comment]
Toimii, suljen tiketin.
