### ISSUE TITLE
Kausijulkaisunäkymä epälooginen

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#975]
### Mikä vikana?

Kausijulkaisun vastaanottonäkymä kausijulkaisun kokoelmatiedot-sivulla on epälooginen vuosivalinnan korostuksen kohdalla. Normaalisti käyttäjä olettaa, että se valinta, mikä on korostettuna, on "päällä", mutta tässä näkymässä on juuri päinvastoin. Kuvassa 2024 on vihreällä pohjalla korostettuna, joten käyttäjä olettaa sen olevan valittuna, mutta alla esillä on kuitenkin vuoden 2023 tilaukset.
![2023kuvat 249](https://github.com/KohaSuomi/Koha/assets/73887264/6b3fdf24-2aed-49bb-9fa6-3cb420ef815b)

**Comment by IrinaHalminen** [comment]
Myös mm. ilmoitusten/kuittien pohjissa on vastaava logiikka, samoin lainauksessa (eli ei-avatut ovat ikään kuin varjossa ja tummempia). Kuitenkin, kun hiirellä hoveroi valikoiden päällä esim. etusivulla, tummanvihreä väri ilmentää hiiren sijaintia.

**Comment by Kati-Helle** [comment]
Voisiko värimaailman ideana olla se, että avattu välilehti on samanvärinen (eli valkoinen) välilehden tietosivun kanssa?

![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/1df68559-b5f1-467e-ba19-f613a1eace4b)

**Comment by AnneliO** [comment]
Mitä tässä kävin läpi eri sivuja ja niillä olevia välilehtiä, niin korostus on nimenomaan tuo valkoinen ei vihreä. Eli valittu välilehti on aina valkoinen, muut vihreitä.


https://github.com/KohaSuomi/Koha/assets/33121325/a8110cb9-337e-4b3e-9557-ffafd34e67ea

**Comment by pknuuti** [comment]
Ehkä tässä on sellainen ongelma, että tuo valittu välilehti on samalla pohjalla kuin taustaväri ja nuo värilliset ei-valitut välilehdet korostuvat sen vuoksi liian selvästi. Voisiko tuon valitun välilehden väri olla jotain muuta kuin valkoinen eli pohjaväri?

**Comment by AnneliO** [comment]
Mie oon aatellut, että kun se on valkoinen, niin se on ikään kuin samaa aluetta kuin välilehdellä näkyvä tieto. Tausta on kuitenkin harmaa, niin se on sitten yhtenäistä aluetta.

Tuo sama toiminto on ympäri käyttöliittymää, joten voi olla iso työ muuttaa se kaikkialle ja se olisi sitten itse ylläpidettävä muutos. Tuo on selkeästi päätetty tehdä noin käyttöliittymää suunniteltaessa.
