### ISSUE TITLE
Valkealan kirjaston niteet varattaviksi 2.1.2024

### ISSUE THREAD

**Issue by Tuomas-Kyyti** [KohaSuomi/Koha#976]
### Tukipyyntö

Valkealan kirjasto avataan 2.1.2024. Niteet pitäisi muuttaa normaaliin tilaan varattavaksi seuraavasti:

Nykyinen kirjasto on KOU_VA ja niteellä on damaged-arvo _3 Ei saatavana, ei varattavissa (kirjasto suljettu)_, poistetaan damaged-arvo 3.

Ajon toivottu ajankohta on ti 2.1. heti aamulla (kirjasto aukeaa klo 10). Jos ei onnistu, niin sitten pe 29.12. mahdollisimman myöhään. 

### Jotain muuta?

Niteet ajettiin damaged-tilaan tiketillä [910](https://github.com/KohaSuomi/Koha/issues/910)

**Comment by emta001** [comment]
Niteiden damaged-arvo poistettu seuraavasti:

`UPDATE items SET damaged = 0 WHERE holdingbranch = "KOU_VA" AND damaged = 3;`

Muutos koski 10824 nidettä.

**Comment by Tuomas-Kyyti** [comment]
Nämä kunnossa. Kiitos.
