### ISSUE TITLE
Vaara: tietokannan siivousta kentässä 006

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#981]
### Tukipyyntö

Vaaran tietokannasta saisi tyhjentää kaikki muut 006-kentät paitsi moniviestimiä koskevat.
Moniviestimet on määritelty nimiön merkkipaikalla 06 merkillä o (000/06=o) Näissä siis ei tyhjennetä merkkipaikkaa 006, kaikissa muissa tietueissa sen saa tyhjentää.

**Comment by AnttHeik** [comment]
> Tutkin tätä vähän ja tämän saa tehtyä myös tietueiden erämuokkauksella.
> 
> Tällä raportilla saa haettua muokattavat tietueet:
> 
> ```
> SELECT biblionumber from biblio_metadata bm 
> WHERE SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="006"]'),1,5) NOT IN ('o')
> AND SUBSTR(ExtractValue(bm.metadata,'//controlfield[@tag="006"]'),1,5) !=''
> ```
> 
> Raportti hakee tietueet, joilla ei ole 006:ssa merkkipaikalla 6 merkkiä o ja 006:n ei ole tyhjä. Kannattaa tarkistaa, että raportti antaa oikeat tulokset eli olen osannut tehdä hakuehdot oikein :D. Jos ne meni oikein, on käsiteltäviä tietueita 2800.
> 
> Ja tällaisella muokkauspohjalla 006:n saa tyhjäksi tietueiden erämuokkauksessa:
> 
> ![kuva](https://private-user-images.githubusercontent.com/33121325/337188820-dc060726-b364-41b0-95d1-b63a0b3395ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMDkzMTQsIm5iZiI6MTcxODAwOTAxNCwicGF0aCI6Ii8zMzEyMTMyNS8zMzcxODg4MjAtZGMwNjA3MjYtYjM2NC00MWIwLTk1ZDEtYjYzYTBiMzM5NWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDA4NDMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNmU5ZTAzODk0MmRjYzk0YmY3YWIxNTNlN2IyZjRhNGI0NDEwYmM4ZTg2ZjI4YTg3MTBmYTllN2QzYmM4ZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mQahuY2HDH3Wu6Nke0YF5jpc9XuWISSn4xGWYiCTw6A)

Milloinkahan tämä on alkanut toimimaan? Muistelin, ettei erämuokkaus anna käsitellä 006- ja 007-kenttiä, koska niillä ei ole osakenttiä, mutta niin vain näyttää toimivan molemmissa, mainiota :)

**Comment by AnneliO** [comment]
Hmm, itseasiassa. On se tainnut osata muokata noita kiinteämittaisia, mutta on pitänyt muokata koko kenttää kerralla. Ei ole vain pystynyt muokkaamaan yksittäistä merkkipaikkaa, kuten ei nytkään.

**Comment by AnttHeik** [comment]
> Hmm, itseasiassa. On se tainnut osata muokata noita kiinteämittaisia, mutta on pitänyt muokata koko kenttää kerralla. Ei ole vain pystynyt muokkaamaan yksittäistä merkkipaikkaa, kuten ei nytkään.

Aivan, no pitääpä testailla näitä, kunhan tässä ehtii.

**Comment by AnneliO** [comment]
Mulla oli mennyt kyselyssä sekaisin merkkipaikka ja kuinka monta merkkiä haetaan. Korjasin alkuperäisen kommentin SQL-kyselyä hieman.

**Comment by IrinaHalminen** [comment]
@pknuuti Marjan kanssa sovittu, että palaat asiaan lomasi jälkeen. Raportilla tuli 2552 tulosta. Avataan sitten uudelleen, jos tarvetta.

**Comment by paxed** [comment]
Kysely pitäisi olla muotoa:

`
SELECT biblionumber
FROM biblio_metadata
WHERE SUBSTR(ExtractValue(metadata,'//leader'),7,1) != 'o'
AND ExtractValue(metadata,'count(//controlfield[@tag="006"])') > 0;
`

Eka ehto: tietueet joissa LDR/06 on jotain muuta kuin 'o'
Toinen ehto: pitää olla yksi tai useampia 006 kenttiä.

**Comment by pknuuti** [comment]
Kiitos Pasi! Nyt raportti antoi 1964 tietuetta enkä pistokokeissa huomannut yhtään moniviestintä, joten muokkasin 006-kentän pois noista.

**Comment by AnttHeik** [comment]
@pirliis Voisiko tämän raportin asentaa myös OUTIin? Näyttäisi olevan meilläkin siivottavaa 006-kentissä.

**Comment by pirliis** [comment]
> @pirliis Voisiko tämän raportin asentaa myös OUTIin? Näyttäisi olevan meilläkin siivottavaa 006-kentissä.

OUTIssa raportti 794.
