### ISSUE TITLE
BTJ:n vanhojen linkkien korjaus

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#982]
### Tukipyyntö

Kirjastopalvelu on ilmoittanut, että niiden vanhojen kirjankansilinkkien osoite on muuttunut eli entinen ei enää toimi. Linkeille pitäisi tehdä korjaus www.btj.com --> armas.btj.fi. 

esimerkit
http://www.btj.com/btjcgi/arvo/get_add_info.cgi?type=PRES&key=6199182327056767
http://www.btj.com/btjcgi/arvo/get_add_info.cgi?type=IMAGE&key=6199182327056767

korjataan näin: 
https://armas.btj.fi/btjcgi/arvo/get_add_info.cgi?type=PRES&key=6199182327056767
http://armas.btj.fi/btjcgi/arvo/get_add_info.cgi?type=IMAGE&key=6199182327056767

Koska tämä ongelma koskee kaikkia kimppoja enemmän tai vähemmän, Anneli lupasi testata voiko muutoksen tehdä erämuokkauksella vai pitääkö kehittäjien tehdä skripti, jolla korjausajo tehdään kaikissa kimpoissa.

**Comment by AnneliO** [comment]
Testailin tätä vaara-testillä ja sain mielestäni toimimaan homman kuvailutietueiden erämuokkauksella.

Hain tietueet tällaisella raportilla:
```
select biblionumber, ExtractValue(metadata, '//datafield[@tag="856"]/subfield[@code="u"]') from biblio_metadata where ExtractValue(metadata, '//datafield[@tag="856"]/subfield[@code="u"]') like '%www.btj.com%'
```

Tein sitten MARC-muokkauksen pohjan, jossa oli yksi toiminto:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/2d63e5d5-4e06-4a02-82be-37a0ebd398b5)


Hain tietueet raportilla ja vein ne siitä tietueiden erämuokkaukseen ja valitsin muokkauspohjan. Tarkistelin tulevaa muutosta _Näytä MARC_ -napilla ja mielestäni osoitteet muokkautuivat oikein. Myös silloin, kun osoite ei ollut ensimmäinen toistuma. Enkä huomannut muutoksia muissa osoitteissa.

Joku muukin voisi testailla tätä. :)

**Comment by AnneliO** [comment]
Vaaran tuotannossa näyttäisi btj.com-tietueita löytyvän reilu 57 000, mikä on vielä erämuokkauksella mielestäni tehtävissä. :)

**Comment by Tuomas-Kyyti** [comment]
Kyytin testillä toimi hyvin näillä ohjeilla. Tuotannossa tietueita löytyi n. 75 000.

**Comment by pknuuti** [comment]
Vaaran linkit korjattu tuotantoon. Kansikuvalinkit toimii, vaikka kansikuvat eivät näy välttämättä perustiedot-näkymässä.

**Comment by AnneliO** [comment]
> Vaaran linkit korjattu tuotantoon. Kansikuvalinkit toimii, vaikka kansikuvat eivät näy välttämättä perustiedot-näkymässä.

Mielenkiinnosta voisin katella niitä kansikuvia. Oisko sulla linkata tietuetta, jossa kansikuva ei näy, mutta linkki toimii?

**Comment by Tuomas-Kyyti** [comment]
Niin, eikö se kansikuvien näkymättömyys johtu [tästä](https://github.com/KohaSuomi/Koha/issues/897)

**Comment by Kati-Helle** [comment]
Helle-tuotannossa www.btj.com arvon sisältämiä tietueita on 63779. Erämuokattavissa siis :)

Mutta: testissä testatessani muodostuu uudet 856-toistumat, eli olemassa olevat eivät muutu/korvaudu

Heittääkö tässä pohjassa nyt joku?
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/b1d227c4-844c-449a-b2bc-aa465293df05)

Muutettujen tietueiden esikatselussa mm. tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/0fe81904-7101-448c-b968-f6fdd6616842)

**Comment by Kati-Helle** [comment]
Ai niin, Hellen tietueiden yhdistämissäännöissä on myös tämä
![kuva](https://github.com/KohaSuomi/Koha/assets/99952449/db15549e-28bd-4c38-9aa3-11b543c5c122)

**Comment by AnneliO** [comment]
> Ai niin, Hellen tietueiden yhdistämissäännöissä on myös tämä ![kuva](https://private-user-images.githubusercontent.com/99952449/291830038-db15549e-28bd-4c38-9aa3-11b543c5c122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjEyODMsIm5iZiI6MTcwMzA2MDk4MywicGF0aCI6Ii85OTk1MjQ0OS8yOTE4MzAwMzgtZGIxNTU0OWUtMjhiZC00YzM4LTlhYTMtMTFiNTQzYzVjMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4Mjk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwODc3ZWRiNzE1YzU2ODE5MTdhZmNjYmViMWZiMWQzYWYxNmFmYzk3MWM5YjkwOWVkYzU3MjgxNzY1MDA4OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8LEstV4OrB9rEyB3-5O1dVYN6S7BLtln111WkYO9qbk)

Uskoisin teillä ongelman johtuvan juurikin tuosta säännöstä. Kannattaa joko muuttaa se koskemaan vain Z39.50:stä tai ottaa muokkausten ajaksi kokonaan pois.

**Comment by Kati-Helle** [comment]
> Ai niin, Hellen tietueiden yhdistämissäännöissä on myös tämä ![kuva](https://private-user-images.githubusercontent.com/99952449/291830038-db15549e-28bd-4c38-9aa3-11b543c5c122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNjEyODAsIm5iZiI6MTcwMzA2MDk4MCwicGF0aCI6Ii85OTk1MjQ0OS8yOTE4MzAwMzgtZGIxNTU0OWUtMjhiZC00YzM4LTlhYTMtMTFiNTQzYzVjMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA4Mjk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0NGQ2YzdjZDkzYmUxN2Q4NmIyYjM4YjQ4YWI3NzYyNDgwMDE1MmUzOTk4OWNiYTdkMDU2NWZhZjVhMTMzYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.emqTsZ8gjwzyWndCgRyEU6Ts_PbOBIBFgJSkteTL-4c)

Säännön poistin, mutta edelleen 856u-kenttä tuplaantuu.

**Comment by Kati-Helle** [comment]
Testasin nyt vielä uudestaan: nyt 856-kenttä ei tuplaantunut :)

**Comment by pknuuti** [comment]
> Niin, eikö se kansikuvien näkymättömyys johdu [tästä](https://github.com/KohaSuomi/Koha/issues/897)

Juuri tuosta se johtuu.

**Comment by ajrajala** [comment]
Vaskin tuotannossa näyttää olevan vajaa 120 000 tietuetta muutettavana. Onko tämä määrä edelleen sellainen, että tehdään kuitenkin erämuokkauksella? Onko tietoa, häiritseekö muutosten ajo muuta käyttöä eli tarvitseeko miettiä ajeleeko erämuokkauksia millaisena ajankohtana?

**Comment by pirliis** [comment]
OUTIssa on parempi tilanne, vain 812 tietuetta.

**Comment by AnneliO** [comment]
> Vaskin tuotannossa näyttää olevan vajaa 120 000 tietuetta muutettavana. Onko tämä määrä edelleen sellainen, että tehdään kuitenkin erämuokkauksella? Onko tietoa, häiritseekö muutosten ajo muuta käyttöä eli tarvitseeko miettiä ajeleeko erämuokkauksia millaisena ajankohtana?

No on kyllä korjattavaa. Me keskustellaan tästä vuodenvaihteen jälkeen ekassa palaverissa.

Sinänsä muutokset menevät taustatöihin, joten niiden ei pitäisi ihan kauhiasti häiritä. Mutta varmaksi en osaa sanoa.

**Comment by Hanna-Lumme** [comment]
Lumpeissa näyttää olevan 83121 eli ihan kiitettävästi.

**Comment by janPasi** [comment]
> Testailin tätä vaara-testillä ja sain mielestäni toimimaan homman kuvailutietueiden erämuokkauksella.
> 
> Hain tietueet tällaisella raportilla:
> 
> ```
> select biblionumber, ExtractValue(metadata, '//datafield[@tag="856"]/subfield[@code="u"]') from biblio_metadata where ExtractValue(metadata, '//datafield[@tag="856"]/subfield[@code="u"]') like '%www.btj.com%'
> ```
> 
> Tein sitten MARC-muokkauksen pohjan, jossa oli yksi toiminto: ![kuva](https://private-user-images.githubusercontent.com/33121325/291560445-2d63e5d5-4e06-4a02-82be-37a0ebd398b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMzQ0ODgsIm5iZiI6MTcwMzIzNDE4OCwicGF0aCI6Ii8zMzEyMTMyNS8yOTE1NjA0NDUtMmQ2M2U1ZDUtNGUwNi00YTAyLTgyYmUtMzdhMGViZDM5OGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA4MzYyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUwOWM3ZTE4MzE2MTEwMjMzN2FhMjIwN2ExZTQwZTE3N2JiYTdmZGU2ZWQ4NjZjOWFhNzkyODFmZTUxMDU0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iyyRxBtZY00ENIaEysgHfsxqhOskAO_qY4M4lXZZmOA)
> 
> Hain tietueet raportilla ja vein ne siitä tietueiden erämuokkaukseen ja valitsin muokkauspohjan. Tarkistelin tulevaa muutosta _Näytä MARC_ -napilla ja mielestäni osoitteet muokkautuivat oikein. Myös silloin, kun osoite ei ollut ensimmäinen toistuma. Enkä huomannut muutoksia muissa osoitteissa.
> 
> Joku muukin voisi testailla tätä. :)

. on regexissä jokerimerkki, joten _periaatteessa_ se pitäisi suojata \-merkillä. Muuten se täsmää mihin tahansa merkkiin. Ei varmaan tässä ongelma, mutta siis periaatteessa www\.btj\.fi -> armas\.btj\.fi on oikea muoto tuolle regexille.

**Comment by pirliis** [comment]
> OUTIssa on parempi tilanne, vain 812 tietuetta.

OUTIssa piste (.) suojattiin ja linkit korjattu.

**Comment by PiaKusmin** [comment]
Lapissa oli noin 72 000. Nyt kaikki korjattu.

**Comment by ReettaSiili** [comment]
Siilinjärven 7 509 korjattu.

**Comment by AnneliO** [comment]
> Vaskin tuotannossa näyttää olevan vajaa 120 000 tietuetta muutettavana. Onko tämä määrä edelleen sellainen, että tehdään kuitenkin erämuokkauksella? Onko tietoa, häiritseekö muutosten ajo muuta käyttöä eli tarvitseeko miettiä ajeleeko erämuokkauksia millaisena ajankohtana?

Keskustelimme tästä Koha-Suomen eilisessä viikkopalaverissa ja linjasimme, että jos työ on tehtävissä itse erämuokkauksella, niin silloin kimpat tekevät sen itse. Tietokanta-ajona tehtäessä pitäisi mm. ensin luoda tarvittava skripti, testata se, ajaa se, indeksoida tietueet uudelleen yms. eli se veisi kehittäjiltä useamman tunnin työaikaa, mikä on poissa sitten muusta. :)

**Comment by ajrajala** [comment]
Kiitos tiedosta, kuittaan tänne kunhan nämä on keretty meilläkin korjailla.

**Comment by Hanna-Lumme** [comment]
Lumpeiden tietueet korjattu.

**Comment by ajrajala** [comment]
Vaskinkin tietueet nyt korjattu.

**Comment by AnneliO** [comment]
Linkit korjattu:
- [ ] Lappi
- [ ] OUTI
- [ ] Siili
- [ ] Vaara
- [ ] Lumme
- [ ] Kyyti
- [ ] Helle
- [ ] Kirkes
- [ ] Vaski

**Comment by Kati-Helle** [comment]
Hellessä linkit korjattu. Olen unohtanut ilmoittaa täällä.

**Comment by ElinaUotila** [comment]
Kirkesissä on linkit nyt korjattu.

**Comment by Tuomas-Kyyti** [comment]
Kyytikin korjattu.

**Comment by AnneliO** [comment]
Linkit korjattu kaikissa kimpoissa, eli tiketin saa sulkea. :)
