### ISSUE TITLE
Lappi: Inventaarionumero-sarakkeen piilotus nidehaun tuloksista

### ISSUE THREAD

**Issue by PiaKusmin** [KohaSuomi/Koha#983]
### Tukipyyntö

Nidehaun tuloksissa on turhaa sarake Inventaarionumero. Saisiko sen jotenkin piilotettua?

### Jotain muuta?

![image](https://github.com/KohaSuomi/Koha/assets/99241432/242b82bc-57cf-48a3-abc8-a621895c29d6)

**Comment by AnneliO** [comment]
IntranetUserCSS:ään kun lisää tällaisen rimpsun, niin ainakin mie sain tuon sarakkeen kadoksiin:

```
/* Piilota inventaarionumero-sarake nidehaun tuloksissa */
body#catalog_itemsearch.catalog th#item_inventoryno.sorting { display: none; }
```

Jos se ei katoa heti, niin kannattaa päivittää sivu nidehaussa ctrl+F5:lla. :) Ja suosittelen testaamaan ensin testillä.

**Comment by PiaKusmin** [comment]
Testasin. Tuo kadotti vain sen ylimmän rivin sarakkeen. Se tulos sarake jäi voimaaan ja sarakkeet meni epäsynkkaan. 

![image](https://github.com/KohaSuomi/Koha/assets/99241432/f1fd2cf0-1085-4be4-82af-05bcc08383b5)

**Comment by AnneliO** [comment]
No niinpä vain! Uusi yritys:

```
/* Piilota inventaarionumero-sarake nidehaun tuloksissa */
body#catalog_itemsearch.catalog td:nth-child(13) { display: none; }
body#catalog_itemsearch.catalog th#item_inventoryno { display: none; }
```

**Comment by PiaKusmin** [comment]
Nyt toimii oikein. Kiitos!
Suljen tiketin.

**Comment by AnneliO** [comment]
Lisäsin rimpsun vielä [IntranetUserCSS-kirjastoon](https://koha-suomi.fi/dokumentaatio/intranetusercss/#piilota-nidehaussa-inventaarionumero-sarake).
