### ISSUE TITLE
Ongelma ACQ-kuvailupohjassa lisättäessä hankinnassa tilausta uudesta tyhjästä tietueesta

### ISSUE THREAD

**Issue by ajrajala** [KohaSuomi/Koha#985]
### Mikä vikana?

Vaskin musiikin sopimustoimittaja vaihtuu ja musiikkilevyjen tilauksia ei jatkossa saada Kohaan enää editx-sanomina vaan tilaukset pitää viedä käsin. Tähän liittyen vaski-testillä on kokeilussa UseACQFrameworkForBiblioRecords-järjestelmäasetus, koska jos tilausta tehdessä tietuetta ei saa valmiiksi (Tätistä) haettua ja se pitää viedä minitiedoilla tilauksen tallennuksen yhteydessä, haluttaisiin hankinnan lomaketta hiukan kustomoida eikä käyttää pohjaa joka hankinnassa on silloin kun ed. mainittu järjestelmäasetus on pois käytöstä.

Nyt kun hankinta käyttää kuvailupohjaa ACQ, näyttää siinä olevan sellainen ongelma että aineistotyyppiä ei saa valittua vaikka 942c-kenttään on nähdäkseni linkitetty MTYPE oikein ja samalla tavalla kuin muissakin kuvailupohjissa. Mikäköhän tuossa mättää?

### Kuinka toistaa ongelma/asia

1. Avaa vaski-testillä esim. tilauskori https://vaski-test.koha-suomi.fi/cgi-bin/koha/acqui/basket.pl?basketno=9254
2. Valitse _Lisää tilauskoriin_ > _Uudesta (tyhjästä) tietueesta_
3. Lomakkeella näkyy toistaiseksi vielä suuri määri kenttiä, mutta ihan viimeisenä löytyy "Koha [default] item type (942c)", huomaa että valikosta ei löydy mitään

### Jotain muuta?

![kuva](https://github.com/KohaSuomi/Koha/assets/44638512/e0ad4ddf-617f-48ea-ac63-4b80d8e8d76c)

**Comment by AnneliO** [comment]
Testailin tätä outi-nextillä (eli versiossa 23.11) ja siellä valikko toimii oikein:
![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/956b427f-1c4b-4241-b391-fe849c667061)

**Comment by emta001** [comment]
@ajrajala testaisitko tätä vielä nextillä?

**Comment by ajrajala** [comment]
Nyt aineistotyyppi on valittavissa ihan normaalisti ja näyttää myös tallentuvan. Suljen tiketin.
