### ISSUE TITLE
Vaski: SIP-tunnukset SVPK-yksikölle

### ISSUE THREAD

**Issue by sksandel** [KohaSuomi/Koha#988]
### Tukipyyntö

Support-postiin lähetetty tarkemmat tiedot.

**Comment by emta001** [comment]
Onko tälle jotain aikataulua mihin mennessä tunnukset on viimeistään lisättävä palvelimmelle?

**Comment by lmstrand** [comment]
Tunnus lisätty SIP-palvelimelle, käytettävissä huomisaamusta.
