### ISSUE TITLE
OUTI: Kaikki asiakkaan lainat eivät muodostuneet "Lainasit tänään"-viestiin

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#991]
### Mikä vikana?

OUTI-kimpan asiakas (borrowernumber: 22442) lainasi eilen 28.12.2023 kaksi kirjaa, joista vain ensimmäisestä muodostui ja lähti asiakkaalle "Lainasit tänään"-viesti. Kohassa asiakkaan ilmoitukset -välilehdellä viestissä kuitenkin näkyy molemmat lainat.

Asiakas lainasi ensimmäisen lainan (564N26859605) klo 13.39:59
Lainanne Pekurin kirjastosta-viesti muodostui klo 13.39
Lainanne Pekurin kirjastosta-viesti lähti asiakkaalle klo 13.40
Asiakas lainasi toisen lainan (564N26343703) klo 13.40:05

Miksi tuo toinen laina puuttuu lähteneestä viestistä, kun se kuitenkin näkyy lähetetyissä ilmoituksissa?
Miksi tuosta jälkimmäisestä lainasta ei lähtenyt omaa viestiä, jos se ei ehtinyt samaan viestiin ensimmäisen lainan kanssa?
Miksi Kohan Ilmoitukset-välilehden viestissä näkyy molemmat lainat, kun asiakkaan viestissä näkyy vain ensin lainattu nide?

### Mitä pitäisi tapahtua

Asiakkaalle pitäisi lähteä jokaisesta lainasta tieto sähköpostiin. Joko yhdessä viestissä tai useina viesteinä.

### Jotain muuta?

Kohassa näyttää tältä:
<img width="305" alt="Lainasi Pekurin kirjastosta - Koha" src="https://github.com/KohaSuomi/Koha/assets/98805552/470dd698-d9ef-4814-b0d6-3ee7bd72fcdb">

Asiakkaan saama sähköpostiviesti:
<img width="197" alt="Lainasi Pekurin kirjastosta - sposti" src="https://github.com/KohaSuomi/Koha/assets/98805552/0e1c1c61-885b-4c07-9e46-673647659a09">

**Comment by emta001** [comment]
Annelin kanssa tätä pohdimme ja tulimme siihen tulokseen, että tässä on käynyt luultavasti seuraavasti: 

- Klo 13.39:59: asiakas tekee ensimmäisen lainan, josta muodostuu viesti.
- Klo 13.40:01: viestien lähetysajo käynnistyy.
- Klo 13.40:05: asiakas tekee toisen lainan, viesti on edelleen pending-tilassa ja lainaa yritetään lisätä siihen.
-> Viestitaulu on lukossa muiden muutosten vuoksi, joten viestin päivitys jää odottamaan taulun vapautumista. 
- Klo 13.40:08: viestien lähetysajo on valmistuu ja samaan aikaan viestiin päivitetään nyt myös toinen laina.
-> Viesti on kuitenkin tässä vaiheessa jo sent-tilassa, eikä sitä lähetetä uudestaan.
-> Molemmat lainat näkyvät olevan viestissä Kohan päässä, mutta asiakkaalle on lähtenyt viesti jossa lainoja on yksi.

Tässä on siis pari ongelmaa, toinen on tuo viestitaulun lukkiutuminen, joka estää viestien muokkauksen.  Toinen se, että Koha ei ota kunnolla huomioon sitä onko viestiin tulossa vielä lisää sisältöä. Mitään pikaista ratkaisua tähän ei ole, viestien käsittely pitäisi laittaa kokonaan uusiksi mikä on iso remppa. Ajoakaan ei oikeastaan voine säätää tapahtumaan harvemmin, sillä sitä nopeutettiin juuri taululukkojen aiheuttaman Kohan kaatuilun välttämikseksi.

**Comment by piiaseme** [comment]
Aamun pääkäyttäjäpalaverissa oli puhetta, että Johanna aikoo tutkia tuota viestitaulun lukkiutumista. Jätänkö tiketin vielä siis auki vai suljenko tämän ratkaistuna + teen kehitysehdotustiketin, jossa viittaan tähän tikettiin?

**Comment by emta001** [comment]
> Aamun pääkäyttäjäpalaverissa oli puhetta, että Johanna aikoo tutkia tuota viestitaulun lukkiutumista. Jätänkö tiketin vielä siis auki vai suljenko tämän ratkaistuna + teen kehitysehdotustiketin, jossa viittaan tähän tikettiin?

Tuo jälkimmäinen vaihtoehto voisi olla fiksuin ratkaisu, se muutos pitäisi varmaan käyttää asiantuntijaryhmässäkin :thinking:

**Comment by piiaseme** [comment]
Tein kehitysehdotuksen: https://github.com/KohaSuomi/Koha/issues/996
Suljen tämän tiketin.
