### ISSUE TITLE
Lumme: Tietueet eivät poistu indeksistä

### ISSUE THREAD

**Issue by Hanna-Lumme** [KohaSuomi/Koha#992]
### Mikä vikana?

Lumpeissa tuli jälleen tapaus eteen, jossa virkailija oli yhdistänyt tietueita eivätkä tietueet eivät poistuneet indeksistä niiden poiston jälkeen. Kyseessä olevat tietueet: MARC: 2964144, 2964166, 2964170 ja 1824729. 

_Taktiikkani aluksi oli, että availin tietueita eri välilehdille, ja toin niistä niteitä emoon yksitellen "Liitä nide" toiminnolla. Niteiden tietoihin piti päivitellä sarjanumerot, minkä vuoksi etenin yksi kerrallaan. Kun nide oli liitetty, ilmoitti Koha, että tietueessa on 0 nidettä, ja kysyi, poistetaanko tietue. Hyväksyin tämän, samaan aikaan kun ko. tietue oli vielä toisella välilehdellä auki. Aina tämä ei johtanut tietueen kummitteluun, mutta kun huomasin, että neljä oli jäänyt roikkumaan, vaihdoin taktiikkaa. Yhdistelin loput valikoimalla yhdistettävät tietueet -> "Muokkaa" -> "Yhdistä tietueita" -toiminnolla. Näistä mikään ei jäänyt kummittelemaan._ 

Ongelma saatiin korjattua, mutta teen asiasta tiketin, jotta tästä jää muistijälki.

**Comment by Hanna-Lumme** [comment]
Joo, tais tulla hutiklikkaus. 😅

**Comment by emta001** [comment]
Kummittelevat tietueet on nyt poistettu indeksistä.

**Comment by emta001** [comment]
Tarkistin Lumpeen taustatyöt näiden osalta. Kaikista löytyy työ jonka tyyppi on "Päivitä Elasticsearch indeksi" ja niiden tilana on "Valmis. Työn raportissa lukee "/ tietuetta indeksoitu onnistuneesti. Joitain virheitä esiintyi.". Näitä on ollut aiemminkin muualla.

**Comment by emta001** [comment]
Hyvin samankaltainen tilanne ollut OUTIssa joku aika sitten, siitä on tiketti #678

**Comment by emta001** [comment]
Lumpeille on laitettu päälle taustatyöajon lokitus. Katsotaan selviäisikö jotain sitä kautta.

**Comment by janPasi** [comment]
Jostain syystä Koha näyttää luovan indekseille automaattisesti replikan, joka ei kaiketi toimi, kerta elasticsearch palvelininstansseja on vain yksi per kimppa. Tästä syystä indeksoinnissa näyttää tapahtuvan häröjä, koska dataa yritetään replikoida saman Elasticsearch-instanssin sisällä, eli tavallaan kopioida itsensä päälle.

Tästä syystä myös indeksien statuksena näkyy "Yellow", joka tarkoittaa että häikkää siellä on. Kokeilimme tipauttaa nuo replikat pois Lumpukoiden testillä ja indeksin tilaksi saatiin siellä asettumaan "Green" tällä operaatiolla. Saman operaation voisi ensihätään Lumpeen tuotannossa ja sitten kun on varmistuttu, että kaikki varmasti pelaa oikein, niin myös kaikkien muiden kimppojen kaikissa Koha-installaatioissa.

**Comment by janPasi** [comment]
Tämä nyt tehty.

**Comment by Hanna-Lumme** [comment]
Tuli nyt uusi tapaus, missä yhdistetty ja poistettu tietue jäi kummittelemaan. Kyseessä tietue: 1024839.

**Comment by emta001** [comment]
> Tuli nyt uusi tapaus, missä yhdistetty ja poistettu tietue jäi kummittelemaan. Kyseessä tietue: 1024839.
> 
> Lisäys 16.1. Tänään jäi tällaiset tietueet vielä roikkumaan indeksiin yhdistämisen jälkeen: 1624149 1624159

Nämä on nyt poistettu indeksistä.

**Comment by Hanna-Lumme** [comment]
Taas tuli yhdistämisen jälkeen kummitus: tietue 1708363.

**Comment by emta001** [comment]
> Taas tuli yhdistämisen jälkeen kummitus: tietue 1708363.

Tämäkin on nyt poistettu.

**Comment by Hanna-Lumme** [comment]
Kummituksista indeksissä raportoitiin taas: 374621.

**Comment by Hanna-Lumme** [comment]
Jälleen indeksöintivirhe, tietue 200042.

Miten oli toimittu poiston yhteydessä:
- Eli hain eka kaikki Gute idee! kurssikirjat ihan hakemalla tuolla nimekkeellä.
- Avasin listasta uuden välilehden aina kullekin kurssin osalle, joita olin poistamassa.
- Klikkasin nidetietueen auki Muokkaa - painikkeesta
- Poistin niteen ja palasin takaisin -toiminnolla takaisin emotietueeseen
- Muokkaa toiminnon alta valitsin ”poista tietue”

Kaikki muut osat sain poistettua, ainoastaan tämä 4.-osa jäi roikkumaan.

**Comment by emta001** [comment]
Kummitukset poistettu.

**Comment by emta001** [comment]
Keräilin hieman dataa backgorund_jobs-taulusta näihin liittyen:

**Tietueet 2964144, 2964166, 2964170 ja 1824729**

![Screenshot from 2024-01-26 09-47-44](https://github.com/KohaSuomi/Koha/assets/37581745/b28636d9-59dd-4bec-9fc6-4de32300b29c)

**Tietue 1024839**

![image](https://github.com/KohaSuomi/Koha/assets/37581745/5f7da8fe-c5bd-44ad-96a2-34d50d8d06a1)

**Tietueet 1624149 ja 1624159**

![image](https://github.com/KohaSuomi/Koha/assets/37581745/d84151a3-3c8a-41d2-8515-5e4e91ef2f2a)

**Tietueista 1708363 ja 374621 ei löydy mitään**

![image](https://github.com/KohaSuomi/Koha/assets/37581745/aa17afed-bd5f-4aa2-a79a-c88d1ad7a15e)

**Tietue 200042**

![image](https://github.com/KohaSuomi/Koha/assets/37581745/5bb99d8e-a388-4c89-9cfb-a611699c2ea1)

Ei näissä ainakaan näiden osalta tunnu olevan mitään logiikkaa sille, miksi poisto ei onnistu. Tarkistin myöskin lokit tuon 24.1. poistetun tietueen 200042 osalta, enkä löytänyt mistään viittausta siihen että Elasticiin ei olisi juuri tuolloin saatu yhteyttä. Eikä niistä kyllä mitään muutakaan selkeää syytä näyttänyt löytyvän. Vaikea sano onko vika sitten background_jbs ajossa, koska sen lokitus ei ole enää päällä jostain syystä. Kaikki työt jotka löysin on kuitenkin näennäisesti menneet läpi.

**Comment by Hanna-Lumme** [comment]
Tuli yksi esimerkkitapaus lisää: tietueet 657325 ja 2798622. Poistettiin, kun yhdistettiin tietueeseen 1371125.

**Comment by emta001** [comment]
> Tuli yksi esimerkkitapaus lisää: tietueet 657325 ja 2798622. Poistettiin, kun yhdistettiin tietueeseen 1371125.

Hmm, näistäkään ei löydy taustatyö-taulusta mainintaa.

**Comment by Hanna-Lumme** [comment]
Muutama lisäesimerkki. Kaksi tietuetta 2489376 ja 1397356 oli yhdistetty tietueeseen 1863704. Tämän jälkeen poistettu ja jääneet indeksiin. Koko setissä oli ollut yhteensä 5 tietuetta. Tehty äsken ja tehty Muokkaa-painikkeen kautta "Yhdistä tietueita".

**Comment by AnneliO** [comment]
En löydä tuollaista Muokkaa-painikkeen takana olevaa "Yhdistä tietueita". Onko se joku näistä:

![kuva](https://github.com/KohaSuomi/Koha/assets/33121325/6830ae00-55e5-4732-955c-bd8529a5d337)

**Comment by AnneliO** [comment]
Aa, eikö nyt löysin sen hakutuloslistan yläpuolelta.

**Comment by emta001** [comment]
Tietueet 657325, 2798622, 2489376, 1397356 poistettu indeksistä.

**Comment by Hanna-Lumme** [comment]
Pari tietuetta löytyi indeksistä, joita ei ole: 1498193 ja 2570241. Ei tietoa milloin/miten on poistettu.

**Comment by emta001** [comment]
> Pari tietuetta löytyi indeksistä, joita ei ole: 1498193 ja 2570241. Ei tietoa milloin/miten on poistettu.

Näyttäisivät olevan joulukuun alusta samaan aikaan poistettuja.

**Comment by Hanna-Lumme** [comment]
Uusi kummitus: 1330621. Ei tietoa tästäkään, että milloin ja miten poistettu.

**Comment by emta001** [comment]
Johanna olikin kommentoinut tästä OUTIn vastaavaan [tikettiin](https://github.com/KohaSuomi/Koha/issues/678#issuecomment-1918704195).

**Comment by Hanna-Lumme** [comment]
Nyt oli poistunut eilen raportoitu tietue, joka oli vielä eilen poiston jälkeen jäänyt roikkumaan indeksiin. Suljen tiketin.
