### ISSUE TITLE
Next-kantojen redusointi

### ISSUE THREAD

**Issue by AnneliO** [KohaSuomi/Koha#995]
### Tukipyyntö

Next-tietokannat pitää redusoida OUTIa lukuunottamatta. OUTIlle luodaan nextille kokonainen tietokanta.

Huomioitavaa:
- API-avaimet pitää ottaa kaikissa kimpoissa (myös OUTI) talteen, jotta nextien Finna-testikannat toimivat jatkossakin.

### Jotain muuta?

Kannat pitää indeksoida uudelleen redusoinnin jälkeen.

**Comment by AnneliO** [comment]
> Otammeko siis itse kimpoissa API-avaimet talteen? :)

Pasi ottaa ne talteen samalla tavalla kuin testeillä. :)

**Comment by paxed** [comment]
helle-next redusoitu, anonymisoitu, sekä api-avaimet palautettu.

**Comment by emta001** [comment]
Helle-nextille on nyt myös päivitetty kanta sekä ajettu indeksointi.

**Comment by paxed** [comment]
kirkes-next, kyyti-next, ja lappi-next redusoitu, anonymisoitu, ja Finnan api-avaimet palautettu.

**Comment by emta001** [comment]
kyyti-next on päivitetty ja uudelleenindeksoitu.

**Comment by emta001** [comment]
Myös kirkes-next ja lappi-next on päivitetty ja uudelleenindeksoitu. Nexteillä on kuitenkin ongelmaa Elasticsearchin kanssa, joten haku ei välttämättä toimi.

**Comment by emta001** [comment]
Elastic-ongelma selätetty ja tiedonhaun pitäisi toimia kaikilla päivitetyillä nexteillä.

**Comment by emta001** [comment]
Täti-next on päivitetty ja uudelleenindeksoitu.

**Comment by pknuuti** [comment]
Vaara vielä puuttuu?

**Comment by emta001** [comment]
> Vaara vielä puuttuu?

Juu, Vaara meinasi jäädä kyydistä. Pasi laittaa sinne tälle illalle redusoinnin.

Muut nextit on nyt sit päivitetty ja uudelleenindeksoitu. Vaara odottaa ensi viikkoa, Outille pitää hakea kokonainen kanta.

**Comment by emta001** [comment]
Myös vaara-next on nyt päivitetty ja uudelleenindeksoitu.

**Comment by emta001** [comment]
Myös outi-next on nyt päivitetty ja uudelleenindeksoitu.

**Comment by AnneliO** [comment]
Nämä nyt ilmeisesti toimii, joten suljen tiketin.
