### ISSUE TITLE
Viestitaulun lukkiutuminen estää viestien muokkauksen

### ISSUE THREAD

**Issue by piiaseme** [KohaSuomi/Koha#996]
### Kehitysehdotukseni

Viestitaulu lukkiutuminen estää viestien muokkauksen. Tämä voi olla ongelma, jos asiakkaalla on esim. lainaustapahtuma kesken, kun viestiajo alkaa. Silloin voi käydä esim. näin:

- Asiakas tekee ensimmäisen lainan, josta muodostuu viesti.
- Viestien lähetysajo käynnistyy.
- Asiakas tekee toisen lainan. Muodostunut viesti on edelleen pending-tilassa ja toista lainaa yritetään lisätä siihen.
- Viestitaulu on lukossa muiden muutosten vuoksi, joten viestin päivitys jää odottamaan taulun vapautumista.
- Viestien lähetysajo on valmis ja samaan aikaan viestiin päivitetään nyt myös toinen laina. Viesti on kuitenkin tässä vaiheessa jo sent-tilassa, eikä sitä lähetetä uudestaan.
- Molemmat lainat näkyvät viestissä Kohassa (Ilmoitukset-välilehdellä), mutta asiakkaalle on lähtenyt viesti, jossa lainoja on vain yksi.

Voiko Kohassa muuttaa ajoa siten, että se ottaisi huomioon meneillään olevan tapahtuman jollain tavalla? 
Joko
Ajo jättäisi meneillään olevan tapahtuman kokonaan huomiotta -> viesti muodostuisi ja lähtisi vasta seuraavassa ajossa.
tai
Lukitus ei estäisi meneillään olevaa tapahtumaa päivittymästä kokonaisuudessaan asiakkaalle lähtevään viestiin.
tai
Toista lainaa ei yritettäisi päivittää jo muodostuneeseen viestiin vaan lopuista lainoista lähtisi 5 min. myöhemmin uusi viesti.

### Jotain muuta?

Liittyy tikettiin: https://github.com/orgs/KohaSuomi/projects/4/views/1?pane=issue&itemId=48643075

**Comment by janPasi** [comment]
Vastaan tähän pikaisesti tälleen lonkalta. Äkkipäätä sanoisin ettei tuo "Voiko Kohassa muuttaa ajoa siten, että se ottaisi huomioon meneillään olevan tapahtuman jollain tavalla?" ei oikein ole mahdollista. "Tapahtuma" Kohassa on yksi lainaus, ei siis saman asiakkaan yhden lainauskerran kaikki lainat. Käytännössä siis "meneillään olevaa tapahtumaa" ei käsitteenä Kohassa ole olemassa tuossa mielessä, eikä viestien käsittelyllä ole mitään keinoa tietää onko tulossa samalle lainakerralle vielä lisää lainoja vai eikö ole.

Tuon lukituksen fiksumpaan hoitamiseen on olemassa suunnitelma ja yritetään hoitaa nämä taululukkoihin liittyvät ongelmat ennemminkin sitä kautta pois päiväjärjestyksestä.

**Comment by emta001** [comment]
Koha-Suomen palaveri 19.2.2024: Lukitus on nyt hoidettu, mutta tätä ongelmaa ei pystytä ratkaisemaan.

**Comment by piiaseme** [comment]
Suljen tiketin.
