### ISSUE TITLE
OUTI: Muhoksen kirjaston niteet Muuttolaatikossa-tilaan

### ISSUE THREAD

**Issue by velimarj** [KohaSuomi/Koha#997]
### Tukipyyntö

Oulussa Muhoksen kirjasto menee kiinni toistaiseksi. Muuttaisitteko niteille, joiden havaintokirjasto (nykyinen kirjasto) on MUPK ja ovat saatavana tilassa:

- not_loan-arvoksi 15 (Muuttolaatikossa)

Muutosajossa tule rajata pois niteet, jotka ovat:
- kuljetettavana
- kuljetettavana kiinni jääneeseen varaukseen
- lainassa
- odottamassa varattuna noutoa
 
tai jos niteen not_loan-arvo on:
1 (Ei lainattavissa)
-1 (Tilattu)
-2 (Saapunut)
2 (Henkilökunnan käsikirjasto)
6 (Laskutettu, toimi kirjastosi laskutusohjeiden mukaisesti)
8 (Ei laskuteta, toimi kirjastosi laskutusohjeiden mukaisesti)
9 (Tarkistettavat)
10 (Poistoehdotukset)
-11 (Korjattavana)
-12 (Tarroitettavat)
13 (Puutteelliset)
-14 (Uusin numero, ei lainata)
15 (Muuttolaatikossa)
16 (Turmeltuneet)
 
tai jos niteen lost-arvo on:
1 (Kadonnut)
 
tai jos niteen damaged arvo on:
6 (Saatavana oppilaille, ei varattavissa)

tai jos niteen hyllypaikka on:
- Koulukirjasto
- Lukion kirjasto
- Kotiseutukokoelma

### Jotain muuta?

Muutokset pitäisi tehdä 15.1.2024.

**Comment by paxed** [comment]
Muutettu näillä rimpsuilla:

CREATE TABLE items_gh997_20240115 select i.* from items i left join reserves r on (i.itemnumber=r.itemnumber) where holdingbranch = "MUPK" and i.notforloan=0 and i.onloan IS NULL and r.found IS NULL AND NOT(i.itemlost = 1) AND NOT(i.damaged = 6) AND location NOT IN ('KOULU','LUKIO','KOT');
update items i left join reserves r on (i.itemnumber=r.itemnumber) set i.notforloan=15 where holdingbranch = "MUPK" and i.notforloan=0 and i.onloan IS NULL and r.found IS NULL AND NOT(i.itemlost = 1) AND NOT(i.damaged = 6) AND location NOT IN ('KOULU','LUKIO','KOT');

Ja muutos koski 54237 nidettä.

**Comment by velimarj** [comment]
Kiitokset, näyttäisi että tämä on pääosin onnistunut kuten pitääkin. Kuljetustilaisia niteitä oli syystä tai toisesta mennyt myös ”Muuttolaatikossa”-tilaan, mutta niitä on sen verran vähän (n. 150kpl) että saamme korjailtua ne itse käsin. 

Suljen samalla tiketin.
