### ISSUE TITLE
Marc-virheiden korjausta kentästä 007-s

### ISSUE THREAD

**Issue by pknuuti** [KohaSuomi/Koha#998]
### Tukipyyntö

Tätiin ja myös joihinkin paikalliskantoihin pitää korjata nalkuttimen herjaamat virheet, joiden määrä on sellainen, että käsin korjaaminen on työlästä.

Jos 007-s (Äänite) kentissä on virheellinen merkki (formaatin vastainen) alla mainituissa osakentissä, se korvataan |-merkillä
007-s/04
007-s/05
007-s/07
007-s/08
007-s/09
007-s/11
007-s/12
007-s/13

**Comment by pknuuti** [comment]
Tämä korjaus on tehtävä tietokantoihin
[x] TäTi
[ ] Helle
[ ] Kirkes
[ ] Kyyti
[ ] Lappi
[ ] Lumme
[ ] Outi
[ ] Siili
[x] Vaara
[ ] Vaski

**Comment by AnttHeik** [comment]
OUTIin voi tehdä myös.

**Comment by Hanna-Lumme** [comment]
Samoin Lumpeisiin.

**Comment by annavii** [comment]
Vaskille voi tehdä myös.

**Comment by Tuomas-Kyyti** [comment]
Kyytille myös

**Comment by mauriaittaniemi** [comment]
Lapin Kohaan myös.

**Comment by paxed** [comment]
Tämä ajettu vaaraan ja vaskiin, ajastan ensi yöksi lisää.

**Comment by Kati-Helle** [comment]
Helleen myös.

**Comment by ReettaSiili** [comment]
Pyydetään tämä myös Siiliin.

**Comment by paxed** [comment]
Tämä ajettu myös siiliin.

**Comment by pknuuti** [comment]
Oletan, että kaikki tarvittavat korjaukset on tehty. Suljen tiketin.
